ofiwg/libfabric

- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_conn.c
- prov/rxm/src/rxm_cq.c
- prov/rxm/src/rxm_domain.c
- prov/rxm/src/rxm_ep.c
- 	rxm: Fix memory leaks & remove unnecessary free
-	prov/rxm: Free tx util bufs on EP close
> Updates for rxm provider.

- prov/gni/src/gnix_nic.c
a merge that had conflicts needed patching up.
> prov/gni: fix a merge problem

- include/unix/osd.h
- include/windows/osd.h
- include/windows/sys/wait.h
- libfabric.sln
- libfabric.vcxproj
- libfabric.vcxproj.filters
- pingpong.vcxproj
- pingpong.vcxproj.filters
- strerror.vcxproj
- strerror.vcxproj.filters
- util/pingpong.c
1) Add strerror and pingpong VS projects
2) Update Win, Unix OS dependency files
3) Update pingpong.c test
> util/pingpong: Add support of pingpong and strerror smoke tests on WinOS

- include/fi.h
- include/fi_list.h
- prov/verbs/src/fi_verbs.c
- prov/verbs/src/fi_verbs.h
- prov/verbs/src/verbs_info.c
Resolved merge conflicts on commit dc95559
> verbs: Cherry picked commits from master to 1.4.x

- prov/verbs/src/verbs_info.c
Added the solution from #2963 PR to verbs provider
> prov/verbs: Update check for FI_LOCAL_MR

- prov/gni/src/gnix_ep.c
upstream merge of ofi-cray/libfabric-cray#1335
Signed-off-by: Zach <ztiffany@cray.com>
(cherry picked from commit ofi-cray/libfabric-cray@6f9af2df40ecd004f6c3bfb5fd44fc2817391c46)
> prov/gni: Allow src addr matching in tagged API

- prov/psm2/src/psmx2_init.c
The PSM2 multi-EP feature (if present) is controlled by the environment
variable PSM2_MULTI_EP which is off by default. This patch tries to set
this variable automatically if the application asks for the scalable
endpoint feature and the variable has not been set yet.
More specifically, when fi_getinfo() is called the first time, the following
condition is checked: "hints->ep_attr->tx_ctx_cnt > 1". In absence of a
dedictaed flag for scalable endpoint support, this is the next best thing
that captures the scalable endpoint requirement.
> prov/psm2: Try to turn on PSM2 multi-EP support automatically

- libfabric.vcxproj
- prov/rxm/Makefile.include
- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_attr.c
- prov/rxm/src/rxm_cq.c
- prov/rxm/src/rxm_domain.c
- prov/rxm/src/rxm_ep.c
- prov/rxm/src/rxm_init.c
- prov/rxm/src/rxm_rma.c
- 	prov/rxm: Refactor allocating tx_entry and tx_buf
- 	prov/rxm: Add support for FI_RMA
> prov/rxm: Add RMA support + some refactoring

- prov/gni/include/gnix.h
- prov/gni/include/gnix_ep.h
- prov/gni/src/gnix_ep.c
- prov/gni/src/gnix_msg.c
- prov/gni/src/gnix_rma.c
fixes ofi-cray/libfabric-cray#1199
upstream merge of ofi-cray/libfabric-cray#1333
(cherry picked from commit ofi-cray/libfabric-cray@f33cfdea785f0d2bfa6d5df17b31702672831b78)
> prov/gni: Add ability to grow the int tx pool

- prov/gni/test/api_cq.c
We have transactions in flight while tearing down endpoints.
Wait for transactions to finish before tearing down.
fixes ofi-cray/libfabric-cray#819
upstream merge of ofi-cray/libfabric-cray#1340
(cherry picked from commit 1d6e8be1299acde3a812b715f20df31797bc0b6d)
> prov/gni: fix api_cq test

- prov/psm/libfabric-psm.spec.in
- prov/psm2/libfabric-psm2.spec.in
- prov/sockets/libfabric-sockets.spec.in
- prov/udp/libfabric-udp.spec.in
- prov/verbs/libfabric-verbs.spec.in
Copy-paste-modify of usnic specfile, and hope that it's right.
> prov: Add specfiles for verbs, psm, sockets, and udp providers

- prov/psm2/src/psmx2_tagged.c
> prov/psm2: Handle FI_DISCARD in tagged receive functions

- prov/usnic/src/usdf_fabric.c
per #2629 
@jsquyres @bturrubiates please review.
> prov/usnic: handle authorization key

- prov/usnic/src/usdf.h
- prov/usnic/src/usdf_ep_dgram.c
- prov/usnic/src/usdf_ep_msg.c
- prov/usnic/src/usdf_ep_rdm.c
Per #2626 
Signed-off-by: Thananon Patinyasakdikul <apatinya@cisco.com>
> prov/usnic: handle domain caps properly

- man/fi_mr.3.md
- man/fi_msg.3.md
Updates based on end-user feedback (submitted directly to me).
> Minor clarifications to man pages

- prov/sockets/src/sock_ep.c
> prov/sockets: Fix setting mr_mode for version 1.5+

- prov/util/src/util_attr.c
If the user passes in caps = 0, then the provider should return
a default set of caps that work best with that provider.  The
ofi_alter_info() calls discard the primary capabilities set by
the provider in this case.  Add a check to keep them.
Fixes #3034
> prov/util: Do not reset primary caps if hints->caps are NULL

- prov/verbs/src/ep_rdm/verbs_rdm_cm.c
These commits are untested, but 'look' right.  :)
> Coverity fixes for verbs provider

- prov/psm/src/psmx_av.c
- prov/psm2/src/psmx2_av.c
> prov/psm,psm2: Use utility function to stringfy addresses

- man/fi_psm2.7.md
> man/psm2: Update the man page about scalable endpoint support

- include/fi_indexer.h
- prov/rxm/src/rxm_cq.c
- prov/rxm/src/rxm_ep.c
- prov/util/src/util_av.c
- 	common: Add range checks to indexer functions
- 	prov/rxm: Bug fixes + minor refactoring.
> common: add range checks to indexer functions; rxm: bug fixes

- prov/gni/include/gnix.h
upstream merge of ofi-cray/libfabric-cray#1369
(cherry picked from commit ofi-cray/libfabric-cray@dc29b46ab769ebeb3572afb49c8c53672cb5b7a2)
> prov/gni: Update gni minor version number.

- prov/gni/test/auth_key.c
Added test for ofi-cray/libfabric-cray#1349 to test race conditions with authorization
keys
upstream merge of ofi-cray/libfabric-cray#1353
(cherry picked from commit ofi-cray/libfabric-cray@dd3cd929aaa742b7ab5432fb27130c9a84e1c893)
> prov/gni: added test for 1349

- prov/sockets/src/sock_trigger.c
> prov/sockets: set iov count with triggered atomic operations

- README.md
- man/fi_netdir.7.md
- prov/netdir/src/netdir.h
- prov/netdir/src/netdir_init.c
> prov/netdir: Add the provider's man-page

- prov/psm2/src/psmx2.h
- prov/psm2/src/psmx2_av.c
- prov/psm2/src/psmx2_cm.c
- prov/psm2/src/psmx2_cq.c
- prov/psm2/src/psmx2_domain.c
- prov/psm2/src/psmx2_ep.c
- prov/psm2/src/psmx2_init.c
- prov/psm2/src/psmx2_util.c
> prov/psm2: Add support for string address format

- prov/udp/src/udpx_init.c
- UDP provider generates own fi_info per address. in some cases
fi_info created for loopback (localhost) interface is
generated first and application who uses first available
fi_info (for instance fi_pingpong) uses such info for
communication (and there are fail to send packet to peer)
- fix: move non-loopback fi_info to head of list
> prov/udp: loopback fi_info shifted to end of list

- prov/gni/src/gnix_rma.c
- prov/gni/test/rdm_dgram_rma.c
FI_MORE cannot currently generate any eventso a remote EP.
This commit will disallow requests with FI_REMOTE_CQ_DATA
or FI_RMA_EVENT (enabled on the peer) from being added to
the fi_more list.
fixes ofi-cray/libfabric-cray#1110
upstream merge of ofi-cray/libfabric-cray#1207
Signed-off-by: Amith Abraham <aabraham@cray.com>
(cherry picked from commit ofi-cray/libfabric-cray@dac65ed34aea169df62caeacef887ad2248d00bd)
> prov/gni: disallow FI_REMOTE_CQ_DATA w/FI_MORE

- include/unix/osd.h
- include/windows/osd.h
- prov/gni/test/cm.c
- prov/sockets/src/sock_fabric.c
- prov/udp/src/udpx_init.c
- prov/verbs/src/verbs_info.c
- implementation of is_loopback_addr call is moved
to common code section
- added windows implementation
- added IP V6 address processing
> utils: added common implementation of is_loopback call

- prov/psm2/src/psmx2_init.c
If the "node" parameter passed to fi_getinfo is in the string
address format "fi_addr_psmx2://x:y" it is taken directly as the
native address. No further address resolution is performed and
the "service" parameter is ignored.
Otherwise, "node" is interpreted as host name and used together
with "service" for address resolution.
> prov/psm2: Allow fi_getinfo to take "node" in string address format

- prov/verbs/src/verbs_info.c
FI_MR_LOCAL domain mr_mode bit replaces FI_LOCAL_MR from v1.5 onwards. Remove any
references to FI_LOCAL_MR and use the domain mr_mode bit to infer MR registration
requirement.
Also add verbs/RDM related rx attr caps directly in the "prov_info". This removes
a check in fi_getinfo path. When app doesn't requrest FI_RMA, we avoid requiring
FI_RX_CQ_DATA.
> prov/verbs: Remove references to old FI_LOCAL_MR mode bit and add new v1.5 caps

- src/windows/osd.c
- for the most often case (IOV vector where only one element)
additional temp buffer is not required and may be used in-place
data buffer
- fix: do not allocate temporary buffer for single-element IOV
- changes are windows specific
> win/osd: minor performance tuning on malloc

- include/fi_util.h
- prov/util/src/util_av.c
> util: Add missed AV remove func to util API

- prov/rxm/src/rxm_ep.c
The issue was introduced by 19bd6460.
> prov/rxm: Fix coverity found issue of unlocking unlocked lock.

- include/fi_util.h
- prov/mlx/src/mlx.h
- prov/mlx/src/mlx_callbacks.c
- prov/mlx/src/mlx_ep.c
- prov/mlx/src/mlx_tagged.c
- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_ep.c
- prov/udp/src/udpx_ep.c
- prov/util/src/util_cq.c
- prov/util/src/util_ep.c
The PR also includes:
Updates of rxm, udp and mlx providers to utilize new utility function
> util: Add utility function for binding CQ to EP

- prov/psm/src/psmx.h
- prov/psm2/src/psmx2.h
> prov/psm,psm2: Remove a fabric field that is no longer used

- prov/util/src/util_ns.c
> util: Fix Coverity issues in NS functionality

- Makefile.am
- include/fi.h
- include/ofi_atomic.h
- include/unix/osd.h
- include/windows/osd.h
- include/windows/sys/mman.h
- libfabric.vcxproj
- prov/gni/include/gnix.h
- prov/gni/src/gnix_atomic.c
- prov/psm/src/psmx.h
- prov/psm/src/psmx_atomic.c
- prov/psm2/src/psmx2.h
- prov/psm2/src/psmx2_atomic.c
- prov/sockets/include/sock.h
- prov/sockets/src/sock_atomic.c
- prov/sockets/src/sock_progress.c
- prov/util/src/util_atomic.c
- prov/verbs/src/fi_verbs.h
- prov/verbs/src/verbs_atomic.c
- src/common.c
And migrate the socket code to use them
> util: Add generic software based atomic operations

- prov/util/src/util_ns.c
> Revert "util: Fix Coverity issues in NS functionality"

- prov/util/src/util_ns.c
> util: Fix coverity issues in the NS functionality

- util/pingpong.c
> pingpong: Update to use 1.5 version

- prov/mlx/src/mlx_ep.c
- prov/rxm/src/rxm_ep.c
- prov/util/src/util_ep.c
+ Update MLX and RXM providers to use it
> util: Add decrement of CQ ref counter in EP close

- prov/sockets/src/sock_atomic.c
- prov/util/src/util_atomic.c
> 2 fixes to util atomic operations

- man/fi_psm2.7.md
Add some details about the scalable endpoint support.
> man: Update psm2 provider man page

- prov/psm/src/psmx_init.c
- prov/psm2/src/psmx2_init.c
> prov/psm,psm2: Allow FI_SHARED_CONTEXT for tx_ctx_cnt

- NEWS.md
> NEWS.md: Update psm/psm2 provider notes for 1.5.0

- prov/psm2/src/psmx2_atomic.c
> prov/psm2: atomic bug fixes

- prov/rxd/src/rxd.h
- prov/rxd/src/rxd_ep.c
- prov/rxd/src/rxd_fabric.c
- prov/rxd/src/rxd_init.c
- in case if receive traffic is too aggressive progress
thread may work very long time. added spin counter
to force stop receiving loop
> prov/rxd: added force progress loop exit

- prov/rxd/src/rxd_cq.c
- prov/rxd/src/rxd_ep.c
- added ack on duplicate start data: in case if
original ack is lost sender may enter to infinite loop
sending packet again & again. now receiver send ack
on every start data packet
- added ack on packet with segno greater than expected
> prov/rxd: added ack on dup start data and invalid packet

- util/pingpong.c
- added send/recv using tagged interface
> util/pingpong: added tagged pingpong

- util/pingpong.c
- in case if requested tagged interface for pingpong
finalize will use tagged too to be consistent with
pingpong
> util/pingpong: finalize uses same API as pingpong

- prov/rxm/src/rxm_cq.c
This is to handle providers which doesn't support inject.
> prov/rxm: Use regular send instead of inject to send ACKs

- Makefile.am
- include/fi_util.h
- include/rdma/providers/fi_log.h
- libfabric.vcxproj
- libfabric.vcxproj.filters
- prov/util/src/util_cntr.c
- prov/util/src/util_ep.c
- src/log.c
- this is basic implementation of counters. as reference
util/CQ implementation is used
- no deeply tested yet, planning to add to RXD provider
counters support
> util/cntr: added preliminary implementation of cntr

- prov/util/src/util_cntr.c
- fixed copy/paste issue in error message
> utils/cntr: fixed typo in log

- prov/sockets/src/sock_conn.c
- prov/sockets/src/sock_ep_msg.c
- prov/sockets/src/sock_fabric.c
Signed-off-by: pmmccorm <patrick.m.mccormick@intel.com>
> Trivial cleanups for socket provider.

- NEWS.md
- README.md
- man/fi_fabric.3.md
- man/fi_provider.7.md
- man/fi_rxm.7.md
- man/fi_verbs.7.md
- Update man page with utility provider details
- Man page and NEWS updates for verbs and rxm providers
> man page updates

- man/fi_domain.3.md
- man/fi_getinfo.3.md
> man/domain: Clarify when FI_LOCAL_MR is ignored

- prov/psm/src/psmx_cq.c
- prov/psm2/src/psmx2_cq.c
> prov/psmx: set flags in psm and psm2 on error

- prov/rxm/src/rxm_init.c
- Only allow modes that can be passed along to the core provider instead of
disabling unsupported modes.
> prov/rxm: Squash some bugs in setting modes and caps

- prov/psm/src/psmx.h
- prov/psm/src/psmx_atomic.c
- prov/psm/src/psmx_domain.c
- prov/psm2/src/psmx2.h
- prov/psm2/src/psmx2_atomic.c
- prov/psm2/src/psmx2_domain.c
> prov/psm,psm2: Implement fi_query_atomic

- src/fi_tostr.c
- util/info.c
Update fi_info output to match
Signed-off-by: Patrick McCormick <patrick.m.mccormick@intel.com>
> fi_tostr: Add missing caps and modes

- prov/usnic/src/usdf.h
- prov/usnic/src/usdf_av.c
- prov/usnic/src/usdf_av.h
- prov/usnic/src/usdf_cm.c
- prov/usnic/src/usdf_cm.h
- prov/usnic/src/usdf_domain.c
- prov/usnic/src/usdf_ep_dgram.c
- prov/usnic/src/usdf_ep_rdm.c
- prov/usnic/src/usdf_fabric.c
- prov/usnic/src/usdf_pep.c
This commit added FI_ADDR_STR support for usNIC provider.
The commit is expected to get pulled in after #3172 .
Tested with #3172.
@jsquyres @bturrubiates
> prov/usnic: add support for FI_ADDR_STR

- include/fi_list.h
- include/fi_rbuf.h
- prov/sockets/src/sock_comm.c
- prov/sockets/src/sock_cq.c
- prov/sockets/src/sock_ep.c
- prov/sockets/src/sock_progress.c
- prov/sockets/src/sock_rx_entry.c
- src/fi_tostr.c
Fix duplicate list removal and possible invalid memory access.
> Select fixes from PR #3193

- prov/usnic/src/usdf_domain.c
@jsquyres 
Signed-off-by: Thananon Patinyasakdikul <apatinya@cisco.com>
> usnic: fix coverity issue.

- NEWS.md
- man/fi_sockets.7.md
> NEWS.md: Update news for netdir, mlx, sockets, usnic providers

- include/fi_rbuf.h
- prov/psm/src/psmx_cq.c
- prov/psm2/src/psmx2_atomic.c
- prov/psm2/src/psmx2_cq.c
- prov/psm2/src/psmx2_tagged.c
- prov/sockets/src/sock_comm.c
- prov/sockets/src/sock_cq.c
- prov/sockets/src/sock_ep.c
- prov/sockets/src/sock_msg.c
- prov/sockets/src/sock_progress.c
- prov/sockets/src/sock_rx_entry.c
- prov/udp/src/udpx_init.c
Fixes to udp, socket, and psm2 providers from master (from May 2017 up to 1.5 release)
> Cherry-picked fixes from master to v1.4.x branch

- prov/psm2/src/psmx2_tagged.c
This reverts commit f869d5d084073b2c3d69d62b14d1fe9453865682.
> Revert "prov/psm2: Handle FI_DISCARD in tagged receive functions"

- include/fi.h
- man/fi_verbs.7.md
- prov/util/src/util_attr.c
- prov/verbs/src/fi_verbs.c
- prov/verbs/src/fi_verbs.h
- prov/verbs/src/verbs_info.c
Some of the commits have been modified to remove v1.5.0 API specific changes and to resolve merge conflicts.
> prov/verbs: cherry picked commits from v1.5.0

- include/fi_util.h
- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_cq.c
- prov/rxm/src/rxm_ep.c
- prov/util/src/util_wait.c
- prov/util: Augment util wait code to wait on additional file descriptors
- prov/rxm: Use ofi_cq_sread calls, add msg_cq fd to util_wait fd list
> util, rxm: Updates to util_wait code

- .gitignore
- include/fi_list.h
- include/fi_osd.h
- include/fi_util.h
- prov/gni/include/gnix.h
- prov/gni/include/gnix_ep.h
- prov/gni/include/gnix_vector.h
- prov/gni/src/gnix_atomic.c
- prov/gni/src/gnix_buddy_allocator.c
- prov/gni/src/gnix_cm.c
- prov/gni/src/gnix_ep.c
- prov/gni/src/gnix_fabric.c
- prov/gni/src/gnix_mr.c
- prov/gni/src/gnix_mr_cache.c
- prov/gni/src/gnix_msg.c
- prov/gni/src/gnix_nic.c
- prov/gni/src/gnix_rma.c
- prov/gni/src/gnix_trigger.c
- prov/gni/src/gnix_vc.c
- prov/gni/src/gnix_vector.c
- prov/gni/src/gnix_xpmem.c
- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_cq.c
- prov/rxm/src/rxm_domain.c
- prov/rxm/src/rxm_ep.c
- prov/rxm/src/rxm_init.c
- prov/util/src/util_ns.c
The intent is to replace RxM macro that check local MR bit set and likely/unlikely macro.
The PR is created to cover the comments of PR #3199
> common/util: Add utility macros

- man/fi_psm2.7.md
> man: Fix a format issue in the fi_psm2 man page

- include/fi_enosys.h
> add a few more fi_no_cq function prototypes

- prov/util/src/util_ns.c
Fix for issue #3236
The implemented reference counting for NS functionality in the commit [bd7db0a](https://github.com/ofiwg/libfabric/commit/bd7db0a5ad37c1070e7fb479c175591e9f5086f7) breaks NS functionality (start of NS thread).
> common/util: Fix mismatch of reference counter in NS functionality

- index.md
> gh-pages/index: Add link to HOTI tutorial

- prov/verbs/src/ep_rdm/verbs_rdm_cm.c
> prov/verbs: Fix coverity issue

- README.md
- prov/mlx/src/mlx_av.c
- prov/mlx/src/mlx_ep.c
- prov/mlx/src/mlx_init.c
- prov/mlx/src/mlx_tagged.c
> prov/mlx: Fix build issue

- prov/gni/configure.m4
- prov/gni/include/gnix_util.h
- prov/gni/src/gnix_buddy_allocator.c
- prov/gni/src/gnix_util.c
- prov/gni/test/utils.c
this is an upstream merge of
upstream merge of ofi-cray/libfabric-cray#1408
and
upstream merge of ofi-cray/libfabric-cray#1405
> prov/gni: upstream merge of downstream prs 1405/1408

- prov/util/src/util_av.c
The code to move handle from peer list to handles_av is already there in
av_insert.
> prov/util: Remove redundant check in get cmap handle

- src/common.c
> common: Remove unreachable code

- prov/rxd/src/rxd.h
- prov/rxd/src/rxd_cntr.c
- prov/rxd/src/rxd_cq.c
> prov/rxd:  Optimize handling of received data

- include/fi.h
- include/fi_abi.h
- man/fi_verbs.7.md
- prov/mlx/src/mlx_av.c
- prov/psm/src/psmx_cq.c
- prov/psm2/src/psmx2_cq.c
- prov/psm2/src/psmx2_init.c
- prov/sockets/src/sock_cq.c
- prov/sockets/src/sock_progress.c
- prov/util/src/util_cq.c
- prov/util/src/util_main.c
- prov/verbs/src/fi_verbs.c
- prov/verbs/src/fi_verbs.h
- prov/verbs/src/verbs_eq.c
- src/common.c
- src/fabric.c
- src/log.c
first batch of patches from master to 1.5.x
> cherry-picked fixes to v1.5.x branch

- prov/sockets/src/sock_ep_msg.c
- prov/sockets/src/sock_fabric.c
- prov/sockets/src/sock_progress.c
- prov/util/src/util_attr.c
- prov/util/src/util_av.c
> cherry-picked patches for v1.5.x branch

- include/fi_util.h
- prov/util/src/util_attr.c
> util: cherry-picked fix for check_ep_attr

- prov/gni/configure.m4
- prov/gni/include/gnix_util.h
- prov/gni/src/gnix_buddy_allocator.c
- prov/gni/src/gnix_util.c
- prov/gni/test/utils.c
cherry pick of commits in #3276
> prov/gni: Cherry pick pr3276

- include/fi_osd.h
- prov/verbs/src/ep_rdm/verbs_queuing.h
- prov/verbs/src/ep_rdm/verbs_rdm.h
- prov/verbs/src/ep_rdm/verbs_rdm_cm.c
- prov/verbs/src/ep_rdm/verbs_rdm_msg.c
- prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm.c
- prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm_states.c
- prov/verbs/src/ep_rdm/verbs_utils.c
- prov/verbs/src/fi_verbs.c
- prov/verbs/src/verbs_rma.c
- src/fabric.c
> cherry picked fixes for v1.5.x

- prov/verbs/src/ep_rdm/verbs_rdm_cm.c
> prov/verbs: Fix a bug introduced by 862a18a commit

- man/fi_psm2.7.md
> man: Update the psm2 provider page on inject size setting

- prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm_states.c
Cherry picked commit that would be merged to master.
> prov/verbs: [cherry-picked] Fix additional klocwork issues

- man/fi_atomic.3.md
> man/fi_atomic: Fix misprint

- prov/psm2/src/psmx2_rma.c
> prov/psm2: Add a missing break statement

- prov/verbs/src/fi_verbs.c
- prov/verbs/src/fi_verbs.h
- prov/verbs/src/verbs_cq.c
- prov/verbs/src/verbs_eq.c
- prov/verbs/src/verbs_msg.c
- prov/verbs/src/verbs_msg_ep.c
- prov/verbs/src/verbs_srq.c
> prov/verbs: Fix unexpected WCs with bad status when the connection is closed by peer

- prov/psm2/src/psmx2_cq.c
The request descriptor was freed before the completion generation,
which made use of part of the descriptot.
> prov/psm2: Fix a segfault bug in RMA completion generation

- prov/verbs/src/verbs_domain.c
Cherry-picked from the #3335 PR
> prov/verbs: Cherry-picked fix (#3335) for v1.5.x branch

- prov/psm2/src/psmx2_cq.c
When generating completion for a large size RMA that is carried out
as special tagged message, the RMA request is put back into the free
pool before the completion is generated. If the request is reused
soon enough, the completion generation may access the "fi_context"
field with modified content.
Fix this issue by delaying the action of putting back the RMA request
into the free pool.
> prov/psm2: Fix a potential data corruption in completion generation

- prov/verbs/src/verbs_cq.c
> prov/verbs: Fix for issue #3355

- prov/verbs/src/ep_rdm/verbs_av_ep_rdm.c
Fix for issue #3357 
Signed-off-by: Richard Halkyard <rhalkyard@cray.com>
> prov/verbs: fix overwrite of return value

- prov/verbs/src/verbs_domain.c
This patch fixes the crash of the verbs/RDM's CM thread when the allocation of the protection domain fails.
This occurs due to thread is keeping alive when `rdm_cm` is freed by `free(_domain->rdm_cm);` in the end of the error handling of the `fi_domain` function.
The problem is being fixed by extended error handling in the verbs' `fi_domain` fucntion
> prov/verbs/RDM: fix a crash of the CM thread that occurs if the allocation of the PD fails

- prov/verbs/src/ep_rdm/verbs_cq_ep_rdm.c
- prov/verbs/src/ep_rdm/verbs_ep_rdm.c
- prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm_states.c
- prov/verbs/src/ep_rdm/verbs_utils.h
- prov/verbs/src/fi_verbs.c
- prov/verbs/src/fi_verbs.h
- prov/verbs/src/verbs_domain.c
- prov/verbs/src/verbs_info.c
All common stuff is replaced from the PR #3199 to this PR
> prov/verbs: Preparation to enable DGRAM EP type in verbs provider

- prov/psm/src/psmx_cq.c
- prov/psm2/src/psmx2_cq.c
> prov/psm,psm2: Cherry-picked fix for branch v1.5.x

- prov/psm/src/psmx_cq.c
- prov/psm2/src/psmx2_cq.c
> prov/psm,psm2: Backported fix for branch v1.4.x

- prov/psm2/src/psmx2.h
- prov/psm2/src/psmx2_rma.c
prov/psm2: Fix long RMA protocol tag collisions
> prov/psm2: Cherry-picked patch for branch v1.5.x 

- configure.ac
> Bump release number to v1.5.2a1

- man/fi_endpoint.3.md
- man/fi_mr.3.md
- man/fi_netdir.7.md
- man/fi_provider.7.md
- man/fi_psm.7.md
- man/fi_rxm.7.md
- man/fi_sockets.7.md
- man/fi_usnic.7.md
- man/fi_verbs.7.md
Signed-off-by: Erik Paulson <erik.r.paulson@intel.com>
> Scrub the manpages of typos

- prov/util/src/util_av.c
- Fix incorrect hash removal in util_av_hash
- Add extra variable to improve clarity
- Add NULL check for cmap handle before removing
> prov/util: Fix av_hash remove

- prov/verbs/src/ep_rdm/verbs_av_ep_rdm.c
- prov/verbs/src/ep_rdm/verbs_ep_rdm.c
- prov/verbs/src/ep_rdm/verbs_queuing.h
- prov/verbs/src/ep_rdm/verbs_rdm.h
- prov/verbs/src/ep_rdm/verbs_rdm_cm.c
- prov/verbs/src/ep_rdm/verbs_rdm_msg.c
- prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm.c
- prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm_states.c
> prov/verbs - Make some counters atomic

- prov/verbs/src/verbs_info.c
This patch applies comments from the PR #3268 + some code cleanups for the new added functions
> prov/verbs: Apply remaining comments from the PR #3268

- prov/sockets/src/sock_atomic.c
Commit dcab6f2 lost saving the user's context value.  The result is
that apps end up getting a completion with null for their context.
This fixes a crash in SandiaOpenSHMEM.
> prov/sockets: Fix losing user's context

- prov/verbs/Makefile.include
- prov/verbs/src/ep_dgram/verbs_dgram.h
- prov/verbs/src/ep_dgram/verbs_dgram_av.c
- prov/verbs/src/ep_dgram/verbs_dgram_cntr.c
- prov/verbs/src/ep_dgram/verbs_dgram_cq.c
- prov/verbs/src/ep_dgram/verbs_dgram_ep.c
- prov/verbs/src/ep_dgram/verbs_dgram_ep_msg.c
- prov/verbs/src/ep_rdm/verbs_av_ep_rdm.c
- prov/verbs/src/ep_rdm/verbs_cq_ep_rdm.c
- prov/verbs/src/ep_rdm/verbs_ep_rdm.c
- prov/verbs/src/ep_rdm/verbs_rdm_cntr.c
- prov/verbs/src/fi_verbs.h
- prov/verbs/src/verbs_atomic.c
- prov/verbs/src/verbs_cq.c
- prov/verbs/src/verbs_domain.c
- prov/verbs/src/verbs_msg.c
- prov/verbs/src/verbs_msg_ep.c
- prov/verbs/src/verbs_srq.c
> prov/verbs: Add support of DGRAM EP type in verbs provider

- include/fi.h
- include/fi_mem.h
- include/rdma/fabric.h
- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_attr.c
- prov/rxm/src/rxm_conn.c
- prov/rxm/src/rxm_cq.c
- prov/rxm/src/rxm_domain.c
- prov/rxm/src/rxm_ep.c
- prov/rxm/src/rxm_init.c
- prov/rxm/src/rxm_rma.c
- src/common.c
> prov/rxm: Updates to rxm provider to suppress warnings

- include/unix/osd.h
- include/windows/osd.h
- include/windows/sys/socket.h
- prov/udp/src/udpx.h
- prov/udp/src/udpx_ep.c
- prov/udp/src/udpx_init.c
- src/windows/osd.c
>  prov/udp: Fix build warnings

- include/fi.h
- prov/gni/test/cm.c
- prov/sockets/src/sock_ep.c
- prov/sockets/src/sock_fabric.c
- prov/udp/src/udpx_init.c
- prov/util/src/util_av.c
- prov/verbs/src/verbs_info.c
- src/common.c
> prov/verbs: fi_ibv_getifaddrs fixes

- prov/verbs/src/verbs_info.c
This patch addresses the problem when the coming first ports are in the state DOWN, and after these ports there are ACTIVE ports.
Now all DOWN ports is skipping and the first found ACTIVE port is chosen
> prov/verbs: Use only active ports

- include/fi_util.h
- prov/rxm/src/rxm_init.c
- prov/util/src/util_attr.c
- prov/verbs/src/fi_verbs.c
- prov/verbs/src/verbs_info.c
- prov/verbs/src/verbs_msg_ep.c
- prov/util,rxm,verbs: Add extra logging
- prov/util: Fix mr mode bits returned in fi_getinfo
- prov/rxm: Fix setting modes and caps when modifying user hints
> prov/util,rxm: Update caps and modes processing

- prov/psm2/src/psmx2_atomic.c
- prov/psm2/src/psmx2_rma.c
> prov/psm2: Fix compilation warnings

- man/fi_fabric.3.md
> man/fi_fabric: Indicate that FI_MAJOR/MINOR macros apply to prov_version

- configure.ac
> common/configure: Fix a broken build for PowerPC 32-bit

- prov/verbs/src/fi_verbs.c
This patch can be considered as an improvement that just replaces `ibv_post_send` w/ `switch-case` result verification by utilizing common `FI_IBV_INVOKE_POST` macro
> prov/verbs: Replace ibv_post_send by common FI_IBV_INVOKE_POST macro

- prov/rxm/src/rxm_cq.c
- prov/rxm/src/rxm_ep.c
This patch is going to cover the following issues:
- The incorrect filling of the RMA i/o vector and Remote Key for the LMT (only the first entry is filled)
- Remove an excessive logic for the preparing of the `match_iov` array
> prov/rxm: Fix LMT (rendezvous protocol) filling of the i/o vector

- prov/verbs/src/ep_rdm/verbs_ep_rdm.c
- prov/verbs/src/ep_rdm/verbs_rdm_cm.c
- prov/verbs/src/fi_verbs.c
Fixes for errno misuses in the verbs provider.
> prov/verbs: errno patches

- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_conn.c
- prov/rxm/src/rxm_ep.c
- prov/rxm/src/rxm_init.c
- prov/verbs/src/verbs_info.c
- prov/verbs [cherry-picked]: Fix setting rx_attr iov_limit
- prov/verbs: Don't throw error if default values are > supported by hardware
> prov/verbs: Bug fixes

- prov/verbs/src/ep_rdm/verbs_ep_rdm.c
Fix possible two possible problem:
- crash while accessing a non-allocated memory pool
- memory (allocated for the pools) leak if Send/Recv CQ isn't allocated
> prov/verbs: Minor refactoring of the EP allocation

- prov/verbs/src/ep_rdm/verbs_ep_rdm.c
The yet another implementation of the PR #3477 for v1.5.x branch
> prov/verbs: Disable ODP by default for v1.5.x

- prov/verbs/src/ep_rdm/verbs_rdm_cm.c
No bug fix here. Just some cleanups.
> prov/verbs CM cleanups

- prov/rxd/src/rxd_ep.c
- prov/util/src/util_av.c
- prov/util/src/util_cntr.c
I figured out some minor issues after testing RxD with the UDP provider. Thanks for reviewing! 
> prov/rxd: Few fixes after testing RxD

- man/fi_verbs.7.md
- prov/verbs/src/fi_verbs.c
> prov/verbs: Some fixes to verbs' man pages

- prov/sockets/src/sock_fabric.c
These changes improve the `MPI_init`-`MPI_Finalize` test:
BDW+EDR (number of ranks - 176, ppn 1):
- 1.51833218 sec - w/o optimizations (only the sockets provider is enabled)
- 1.4842533 sec - w/ optimizations (only the sockets provider is enabled)
- 1.81241148 sec - w/o optimizations (all available providers is enabled)
- 1.80456235 sec - w/ optimizations (all available providers is enabled)
KNL+OPA (number of ranks -136, ppn 68)
- 11.77717361 sec - w/o optimizations (only the sockets provider is enabled)
- 11.5522065 sec - w/ optimizations (only the sockets provider is enabled)
- 10.33442811 sec - w/o optimizations (all available providers is enabled)
- 10.31751561 sec - w/ optimizations (all available providers is enabled)
> prov/sockets: Optimize startup

- prov/verbs/src/ep_rdm/verbs_av_ep_rdm.c
- prov/verbs/src/ep_rdm/verbs_rdm_msg.c
- prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm.c
This two commits is going to fix reported Coverity issues:
- Fix a possible deadlock
- Fix incorrect verification of the user's inputs
>  prov/verbs: Fix a possible deadlock

- man/fi_rxm.7.md
- man/fi_verbs.7.md
> man: Update verbs, rxm provider specific fabtests issues

- prov/util/src/util_av.c
- prov/util/src/util_shm.c
> prov/smr: Ensure peer names are null terminated

- prov/usnic/src/usdf_eq.c
- prov/util/src/util_cntr.c
- prov/util/src/util_main.c
- prov/verbs/src/ep_rdm/verbs_cq_ep_rdm.c
- prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm_states.c
- prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm_states.h
- prov/verbs/src/verbs_eq.c
- prov/verbs/src/verbs_srq.c
- src/fabric.c
- src/rbtree.c
- src/var.c
Make some local functions static, add fallthrough strings that gcc
recognizes.
> all: fixes some gcc warnings

- prov/psm2/src/psmx2_ep.c
> prov/psm2: Fix a bug in domain reference counting

- man/fi_verbs.7.md
- prov/verbs/src/fi_verbs.c
> prov/verbs: Use common fork_unsafe variable instead

- configure.ac
> config: Fix an incorrect behavior of the --enable-debug

- prov/verbs/src/ep_rdm/verbs_rdm_cm.c
If the **PASSIVE** (a local address is less than a remote address) **RDM EP** is establishing connection to the **ACTIVE RDM EP**, the ACTIVE EP RDM rejects this connection. If the `RDMA_CM_EVENT_REJECTED` event comes to the **PASSIVE EP RDM** when it closes the EP, it hangs.
The solution is just to check whether EP is closing during handling of the `RDMA_CM_EVENT_REJECTED` event. If the EP is closing at this moment, the connection is moved to the `FI_VERBS_CONN_CLOSED` and nothing is done anymore. The QP and CM ID will be closed during connections cleanup procedure.
> prov/verbs: Fix hanging during an EP closure in the MPI_Finalize

- prov/rxm/src/rxm_rma.c
This patch also refactors the checks a little so that there are no
additional branches with the fix.
> prov/rxm: add missing check for core provider FI_MR_LOCAL mode

- include/fi_util.h
- prov/util/src/util_main.c
- src/common.c
- src/fabric.c
- src/windows/osd.c
This patch is cherry-pick of the #3447 PR's content
> common: Fix unitialized global lock (appears on Windows) [cherry-pick into v1.5.x]

- prov/psm2/src/psmx2_cntr.c
Triggered ops over SEP should use the queue associated with the
corresponding context.
> prov/psm2: Use the right queue for triggered ops when SEP is enabled

- prov/netdir/src/netdir_ep.c
- prov/netdir/src/netdir_init.c
- prov/netdir/src/netdir_pep.c
This is just picking of changes form #3565 into the v1.5.x branch
>  prov/netdir: Fix fi_getname (cherry-pick #3565)

- man/fabric.7.md
- man/fi_bgq.7.md
- man/fi_direct.7.md
- man/fi_eq.3.md
- man/fi_getinfo.3.md
- man/fi_gni.7.md
- man/fi_info.1.md
- man/fi_mlx.7.md
- man/fi_netdir.7.md
- man/fi_pingpong.1.md
- man/fi_provider.7.md
- man/fi_psm.7.md
- man/fi_psm2.7.md
- man/fi_rxd.7.md
- man/fi_rxm.7.md
- man/fi_shm.7.md
- man/fi_sockets.7.md
- man/fi_trigger.3.md
- man/fi_udp.7.md
- man/fi_usnic.7.md
- man/fi_verbs.7.md
- prov/rxm/src/rxm_init.c
- prov/util/src/util_attr.c
This pull request contains the patches that I applied to libfabric 1.5.2-1 in Debian.
> Fixes from the Debian package

- prov/shm/src/smr_ep.c
- remove extra address check causing never-ending loop
- free unexpected and stored command freestacks
> prov/shm: bug fixes

- man/fabric.7.md
- man/fi_bgq.7.md
- man/fi_direct.7.md
- man/fi_eq.3.md
- man/fi_getinfo.3.md
- man/fi_gni.7.md
- man/fi_info.1.md
- man/fi_mlx.7.md
- man/fi_netdir.7.md
- man/fi_pingpong.1.md
- man/fi_provider.7.md
- man/fi_psm.7.md
- man/fi_psm2.7.md
- man/fi_rxd.7.md
- man/fi_rxm.7.md
- man/fi_sockets.7.md
- man/fi_trigger.3.md
- man/fi_udp.7.md
- man/fi_usnic.7.md
- man/fi_verbs.7.md
- prov/rxm/src/rxm_init.c
- prov/util/src/util_attr.c
- prov/verbs/src/verbs_info.c
These fixes were originally applied to the v1.5.x release by @bdrung, but updated for master.
> cherry-picking man page fixes from master to v.1.5.x

- prov/psm2/src/psmx2_domain.c
Remove disconnected addresses from the list of connected peers. This
eliminates intermittent segfault or assertion failure at finalization
time due to disconnection requests being issued to addresses that have
already been disconnected.
> prov/psm2: Fix a bug in the connection clean-up protocol

- prov/psm2/src/psmx2_domain.c
Here is the deadlock scenario:
#0  0x00007fed3a439495 in pthread_spin_lock ()
#1  0x00007fed37ad7cfd in fastlock_acquire ()
#2  0x00007fed37ad80a4 in psmx2_lock ()
#3  0x00007fed37ad8361 in psmx2_am_trx_ctxt_handler_ext ()
#4  0x00007fed37b084e7 in psmx2_am_trx_ctxt_handler_0 ()
#5  0x00007fed373c08c5 in self_am_short_request ()
#6  0x00007fed3739bf83 in __psm2_am_request_short ()
#7  0x00007fed37ad84ee in psmx2_trx_ctxt_disconnect_peers ()
A lock has been held in psmx2_trx_ctxt_disconnect_peers before
psm2_am_request_short is called. While making progress inside
this function, the execution is redirected to the AM handler
due to the arrival of an incoming disconnection request. The AM
handler tries to acquire the same lock that has already been
held and reaches a deadlock.
Fix by …
> prov/psm2: Fix a deadlock in connection cleanup handler

- prov/tcp/src/tcpx_conn_mgr.c
> prov/tcp: fix resource leak reported by coverity

- prov/psm2/src/psmx2_ep.c
Some applications set FI_SELECTIVE_COMPLETION in ep/cq bind flags and
set FI_COMPLETION in op_flags.  (This gives them a completion by
default, while allowing them to selectively disable completions by
using tsendmsg.)
With this change, those applications will get specialized (faster)
versions of the tagged send/recv routines rather than the generic
(slow) versions.
Signed-off-by: Jim Snow <jim.m.snow@intel.com>
> prov/psm2: Allow specialization when FI_COMPLETION op_flag is set.

- prov/psm2/src/psmx2_cq.c
- prov/psm2/src/psmx2_msg.c
prov/psm2: Fix multi-receive issues when paired with iov send
> v1.5.x: cherry-pick one bug fix for psm2 provider

- include/windows/osd.h
- prov/sockets/src/sock_wait.c
- prov/util/src/util_fabric.c
- prov/util/src/util_ns.c
- prov/util/src/util_poll.c
- prov/util/src/util_wait.c
- src/common.c
- src/fasthash.c
- src/log.c
- src/var.c
- src/windows/osd.c
I will be adding more commits to this PR as I work through the warnings.
> Fix build warnings on Windows

- prov/verbs/src/ep_rdm/verbs_cq_ep_rdm.c
- prov/verbs/src/ep_rdm/verbs_rdm.h
- prov/verbs/src/fi_verbs.h
The content of this patch is manually picked up from #3532
> prov/verbs: Add support of different CQ formats for the verbs/RDM

- prov/shm/src/smr_ep.c
- prov/util/src/util_domain.c
> prov/shm, util: coverity fixes

- prov/util/src/util_av.c
- prov/util/src/util_cq.c
- prov/util/src/util_wait.c
- prov/util: improve cmap logging
- prov/util: fix a race condition in connection close (cc: v1.5.x)
- prov/util: trywait function should return success when poll returns EAGAIN (cc: v1.5.x)
- prov/util: Fix util cq_sread function (cc: v1.5.x)
> prov/util: Bug fixes to cmap and util wait

- prov/psm2/src/psmx2_av.c
Fix the mechanism for translating the source "epaddr" reported by PSM2
into proper "fi_addr" so that it works for both regular endpoints and
scalable endpoints. Dynamic connection support is also improved.
There is still a limitation: the scalable endpoints must have already
been inserted into the address vector in order for the translation to
work properly. Otherwise, FI_ADDR_NOTAVAIL will be returned and due to
the platform limitation the source address information delivered via
the CQ error data will be identified as a regular endpoint instead of
a context of a scalable endpoint. The mis-identified address, however,
should still function normally (e.g. be inserted into address vector)
in later usage.
> prov/psm2: Report correct source address for scalable endpoints

- prov/shm/src/smr_ep.c
Fixes a few bugs when processing rma ops:
- If rx_cq is full and remote data is requested, don't discard the commands
- If mr verification failed, discard both cmds but don't process message
- Don't set rx_cq entry buf field when generating completion
> prov/shm: coverity/bug fixes

- prov/hook/src/hook_eq.c
> prov/hook: Fix coverity issue comparison always true

- prov/verbs/src/fi_verbs.h
> prov/verbs: Fix compiling issue with GCC < 4.6

- prov/util/src/util_attr.c
If the domain name is NULL, this causes a seg fault in strdup.
Hit this issue because the getinfo test in fabtests makes a request using FI_VERSION(1, 0) and for compatibility reasons, usNIC returns a NULL domain name. 
> Check if domain name is NULL when constructing util info.

- prov/usnic/src/usdf_rdm.c
- prov/usnic/src/usnic_direct/usd_dest.c
Cherry picked from #3627.
Fixes #3688.
> v1.5.x: clang fixes for usnic

- include/windows/config.h
- libfabric.vcxproj
- libfabric.vcxproj.filters
> prov/tcp: Add tcpx provider to the Visual Studio solution

- prov/tcp/src/tcpx_domain.c
- prov/tcp/src/tcpx_progress.c
- prov/util/src/util_wait.c
> prov/tcp, util: coverity fixes

- prov/verbs/src/fi_verbs.c
- prov/verbs/src/fi_verbs.h
- prov/verbs/src/verbs_cq.c
- prov/verbs/src/verbs_msg_ep.c
> prov/verbs: Avoid calculating threshold at runtime

- prov/verbs/src/verbs_msg_ep.c
- prov/verbs/src/verbs_srq.c
This patch reduces amount of code for MSG, RMA, Atomics operations.
> prov/verbs: Some code cleanups and simplifications

- prov/rxm/src/rxm_cq.c
- prov/rxm/src/rxm_ep.c
This patch proposes to use `fi_inject()` instead `fi_send()` for transferring the following LMT protocol messages:
- Acknowledgment (1st commit)
- Request (2nd commit)
> prov/rxm: Use fi_inject for LMT protocol

- prov/tcp/src/tcpx_ep.c
Coverity complains about uninitialized pointer read for `msg.context` - [CID 259844](https://scan4.coverity.com/reports.htm#v27196/p10344/fileInstanceId=36062666&defectInstanceId=6728618&mergedDefectId=259844)
> prov/tcp: Fix Coverity issue

- prov/sockets/src/sock_ep.c
The per endpoint connection map stores a list of active connections.
Each connection stores a av_index that corresponds to that
connection's address in the local AV.
The av_index is left unset (FI_ADDR_NOTAVAIL) if we accept a connection
from a peer.  This can result in mis-matching tagged receive messages,
since FI_ADDR_UNSPEC correponds with any source.
Add a check to sock_ep_lookup_conn() to set the av_index if it is
unset.  Sock_ep_lookup_conn() is called when sending data to a
specific peer, or when receiving a connection message from a peer.
The latter is the first message a peer sends in order to publish its
address.
> prov/sockets: Set av_index in conn_map on passive side

- prov/psm2/src/psmx2.h
Bring back the optimized routines for setting & retrieving the first
64 bit from a 96 bit tag. These routines were removed during recent
tag bit re-arrangement.
> prov/psm2: Re-apply optimization for 96-bit to 64-bit tag conversion

- prov/tcp/src/tcpx_ep.c
> prov/tcp Add getopt support for endpoints

- prov/gni/src/gnix_nic.c
> prov/gni: fix an assert's logic

- prov/gni/src/gnix_wait.c
Fix the way the GNI provider wait progress thread
handles unlocking upon "return" from pthread_cond_wait.
It was incorrect for case of thread cancellation
while blockedin the call, resulting in a mutex
remaining locked after the thread was canceled.
Fixes #3777
> prov/gni: handle pthread_cond_wait correctly

- prov/usnic/src/usdf_av.c
- prov/usnic/src/usdf_domain.c
- prov/usnic/src/usdf_ep_rdm.c
- prov/usnic/src/usdf_fabric.c
Take care of a bunch of corner cases where allocations can fail.
Fixes #3295
> prov/usnic: fix klockwork issues

- prov/psm2/src/psmx2_ep.c
A list of active Tx/Rx contexts is maintained for each domain. This list
is used by the progress function. Previously there were two issues: for
regular endpoints, the Rx context was added to the list when allocated,
but was not removed from the list when freed, which could cause the auto
progress thread to access invalid context during finalization. For shared
Tx context, the context was not added to the list at all. Both issues
have been addressed here.
> prov/psm2: Fix finalization error in auto progress thread

- NEWS.md
- README.md
- man/fi_domain.3.md
- man/fi_endpoint.3.md
- prov/sockets/src/sock_ep_msg.c
- prov/verbs/src/ep_rdm/verbs_ep_rdm.c
- prov/verbs/src/fi_verbs.c
- prov/verbs/src/fi_verbs.h
- prov/verbs/src/verbs_info.c
- src/fi_tostr.c
> Docs: Update release notes and documentation for 1.6 release

- prov/shm/src/smr_init.c
> prov/shm: fix possible NULL reference

- prov/util/src/util_domain.c
> prov/util: Fix 'variable set but not used' warning for non-debug build

- man/fi_rxm.7.md
- prov/rxm/Makefile.include
- prov/rxm/src/rxm_cq.c
- prov/rxm/src/rxm_init.c
- prov/rxm: add support for fi_cq_signal 
- prov/rxm: reword env variable definitions
- prov/rxm: update man page
> prov/rxm: add support for fi_cq_signal + man page updates

- prov/rxm/src/rxm_cq.c
This fixes Coverity scan issue - [CID 262919](https://scan4.coverity.com/reports.htm#v27196/p10344/fileInstanceId=37202355&defectInstanceId=6884155&mergedDefectId=262919)
> prov/rxm: Check return value from ofi_cq_write

- include/ofi_file.h
- include/unix/osd.h
- include/windows/osd.h
- libfabric.vcxproj
- libfabric.vcxproj.filters
- prov/tcp/src/tcpx_conn_mgr.c
- prov/tcp/src/tcpx_ep.c
- prov/tcp/src/tcpx_init.c
- prov/tcp/src/tcpx_progress.c
- src/windows/osd.c
Signed-off-by: Hefty <sean.hefty@intel.com>
> windows: Add missing headers to project

- include/ofi_indexer.h
This updates code comments only to describe the use of the indexer
and index_map in more detail.
> util/indexer: Provide more documentation around use of indexer/map

- config/cron-run-all-md2nroff.pl
> Update ofiwg bot for dco mandatory check

- config/cron-run-all-md2nroff.pl
> md2nroff.pl: one last place where it's ok to fail

- include/unix/osd.h
- include/windows/osd.h
- prov/tcp/src/tcpx_conn_mgr.c
- prov/tcp/src/tcpx_ep.c
> prov/tcp adding fi_reject support

- src/fabric.c
Utility providers are always enabled, which makes it easy
for them to be used by specifying only the core provider.
However, there's no way to disable the utility provider,
which may result in it being preferred.  Allow disabling
the util providers using the FI_PROVIDER environment
variable.
> core: Allow disabling utility providers

- prov/sockets/src/sock_fabric.c
Signed-off-by: Dmitry Durnov <dmitry.durnov@intel.com>
In order to select a concrete interface we have to modify application logic. (E.g. specify node)
The idea here is to reduce interface list with a help of interface name filter.
So we won't have to modify application level.
E.g.
`FI_SOCKETS_INTERFACE_NAME=ib0` will make only ib0 interface available (+ lo by default)
`FI_SOCKETS_INTERFACE_NAME=ib` will make available all interfaces which match to ib* (ib0, ib1, etc)
> prov/sockets: Initial implementation of interface filter

- prov/util/src/util_av.c
Instead move it to peer list since the peer can be actively using the connection
to send data.
A follow up PR would update this to be more deterministic.
> prov/util: don't remove connection info on av remove addr

- prov/rxm/src/rxm_ep.c
> prov/rxm: Fix a possible uninitialized TX entry

- prov/psm2/src/psmx2.h
- prov/psm2/src/version.h
> prov/psm2: Fix potential dereference of NULL pointer

- prov/tcp/src/tcpx_ep.c
> prov/tcp adding fi_shutdown support

- prov/psm2/src/psmx2_av.c
When lazy connection mode is on, the per local context table that holds remote
SEP addresses may still be uninitialized when an SEP address is being resolved.
Detect such condition and make the necessary initialization.
> prov/psm2: Fix SEP address translation bug under lazy connection mode

- prov/psm2/Makefile.include
- prov/psm2/src/psmx2.h
- prov/psm2/src/psmx2_attr.c
- prov/psm2/src/psmx2_domain.c
- prov/psm2/src/psmx2_init.c
> prov/psm2: Use utility functions to check provider attributes

- NEWS.md
> NEWS.md: Update change logs for the psm and psm2 providers

- NEWS.md
> prov/gni: update NEWS for 1.6 release

- man/fi_verbs.7.md
- prov/verbs: Update man page with new env variables.
> prov/verbs: update man page with new env variables

- util/pingpong.c
> pingpong: Add support of FI_MSG_PREFIX mode

- prov/util/src/util_attr.c
> util/attr: Add missed newline for the log messages

- NEWS.md
> prov/psm2: Update NEWS for 1.6

- prov/verbs/src/verbs_info.c
> prov/verbs: Add missed FI_LOCAL_COMM and FI_REMOTE_COMM

- prov/rxm/src/rxm_attr.c
> prov/rxm: Add missed FI_LOCAL_COMM and FI_REMOTE_COMM

- include/ofi_util.h
- prov/util/src/util_wait.c
> util/wait: Fix failure in ofi_wait_fd_del

- prov/rxm/src/rxm_ep.c
> prov/rxm: Fix TX buffer leak

- prov/rxm/src/rxm_ep.c
- prov/rxm/src/rxm_rma.c
> prov/rxm: Change hexadecimal print length to decimal

- prov/shm/src/smr.h
> prov/shm: update version to 1.0 for release

- NEWS.md
> docs/psm2: Update docs to indicate required psm2 version

- prov/tcp/src/tcpx_cq.c
- prov/tcp/src/tcpx_progress.c
> prov/tcp: Adding GETWAIT support for CQ

- include/windows/config.h
> osd/win: Fix string representation of version (for 1.6.x)

- include/windows/config.h
> osd/win: Fix string representation of version

- prov/sockets/src/sock_ep_msg.c
if ptrhead's spinlock is available (i.e. `PT_LOCK_SPIN == 1`), then CM thread is hanging due to trying to lock already held spinlock.
Fixes Coverity scan issue ([CID 264631](https://scan4.coverity.com/reports.htm#v27196/p10344/fileInstanceId=37919674&defectInstanceId=6984681&mergedDefectId=264631))
> prov/sockets: Fix hanging while trying to lock already held spinlock

- prov/sockets/src/sock_cntr.c
As part of updating a counter, an associated deferred work queue
is checked.  For example, sock_cntr_add() calls
sock_cntr_check_trigger_list() after the counter has been updated.
If an application is waiting on the counter to reach a specific
threshold, it can see that the counter has been set, then attempt
to free the counter, endpoint, and other resources.  This leads
to a condition where the checking of the trigger list may be
called after the counter has been freed.
There's not a great fix for this.  To help avoid potential use
after free issues, hold the counter mutex around the call to
check the trigger list.  Then in destroy acquire and release the
mutex.  This ensures that destroy block until counter updates
have fully completed.
This fixes a crash in MPI as a result of …
> prov/sockets: Fix use after free error handling triggered ops

- prov/util/src/util_av.c
This is same as #3931, but for stable v1.6.x branch
> util/av: Fix handling of double insertion of the same address (for v1.6.x)

- prov/rxm/src/rxm_ep.c
> prov/rxm: Fix compiler warning

- configure.ac
(cherry picked from commit 2c931b2104b20cad679d5488974360575c8002e5)
> v1.6.x: configure.ac: ensure that all the debug compiler flags work

- prov/shm/src/smr_attr.c
> prov/shm: fix mem_tag format

- prov/tcp/src/tcpx_ep.c
> prov/tcp: added fi_setname and fi_getname for pep

- prov/util/src/util_av.c
This fixes crash in the fi_av_remove for the providers that doesn't specify `OFI_AV_HASH` (verbs/DGRAM)
> util/av: Fix crash in the fi_av_remove if OFI_AV_HASH isn't specified

- configure.ac
- include/ofi_atom.h
> configure: Fix compilation failure with icc 18 (cherry-picked)

- prov/sockets/src/sock_progress.c
Signed-off-by: Anatoliy Rozanov <anatoliy.rozanov@intel.com>
> prov/sockets: Fix segfault in sockets provider

- prov/psm2/src/psmx2_atomic.c
- prov/psm2/src/psmx2_av.c
- prov/psm2/src/psmx2_cq.c
- prov/psm2/src/psmx2_ep.c
- prov/psm2/src/psmx2_mr.c
- prov/psm2/src/psmx2_msg.c
- prov/psm2/src/psmx2_rma.c
- prov/psm2/src/psmx2_tagged.c
> prov/psm2: Replace some parameter checking with assertions

- prov/verbs/src/fi_verbs.h
- prov/verbs/src/verbs_cq.c
- prov/verbs/src/verbs_msg_ep.c
- prov/verbs/src/verbs_srq.c
The `fi_ibv_wre_pool` structure contains pool, list and lock that are used for Work Request Entry (WRE) allocation.
The `fi_ibv_wre_pool` is needed for further re-use -- prepare handling of threading model like #3992 
> prov/verbs: Create new object fi_ibv_wre_pool

- configure.ac
> configure: Fix ICC 17 compilation

- prov/verbs/src/fi_verbs.c
Some verbs providers handle passed capabilities in a different way.
`fi_ibv_find_max_inline` sets `max_inline_data` size to 2 for iWarp devices, because some of iWarp devices can create QP with unsupported value for `max_inline_data` capability.
This PR implements presents for all known providers ("i40iw" only for now) to eliminate impact of the above  behavior and use max supported value.
> prov/verbs: Implement presets of device capabilities

- prov/verbs/src/fi_verbs.h
- prov/verbs/src/verbs_cq.c
- prov/verbs/src/verbs_msg_ep.c
- prov/verbs/src/verbs_srq.c
We are free to remove code that allocates WRE for each TX/RX (except fi_inject).
This isn't needed anymore.
This PR improves latency of RxM/verbs for MPI data < 8 bytes (~1-2 microseconds).
> prov/verbs: Remove Work Request Entry for TX/RX

- prov/mrail/Makefile.include
- prov/mrail/src/mrail.h
- prov/mrail/src/mrail_attr.c
- prov/mrail/src/mrail_av.c
- prov/mrail/src/mrail_cq.c
- prov/mrail/src/mrail_domain.c
- prov/mrail/src/mrail_ep.c
- prov/mrail/src/mrail_init.c
- src/common.c
- Add prelim code for AV, CQ and progress.
- update EP and add send/recv functions.
- minor fixes
> prov/mrail: updates for AV, CQ, EP + minor fixes

- prov/verbs/src/ep_dgram/verbs_dgram.h
- prov/verbs/src/ep_dgram/verbs_dgram_av.c
- prov/verbs/src/fi_verbs.h
> prov/verbs: Fix AV functionality in verbs/DGRAM

- prov/verbs/src/ep_dgram/verbs_dgram.h
- prov/verbs/src/ep_dgram/verbs_dgram_av.c
This is the back-port of #4017
> prov/verbs: Fix AV functionality in verbs/DGRAM (for v1.6x)

- prov/tcp/src/tcpx.h
- prov/tcp/src/tcpx_conn_mgr.c
- prov/tcp/src/tcpx_ep.c
> prov/tcp: support for reserving ep address with provider context handle

- libfabric.vcxproj
- libfabric.vcxproj.filters
- prov/tcp/Makefile.include
- prov/tcp/src/tcpx.h
- prov/tcp/src/tcpx_attr.c
- prov/tcp/src/tcpx_comm.c
- prov/tcp/src/tcpx_cq.c
- prov/tcp/src/tcpx_domain.c
- prov/tcp/src/tcpx_ep.c
- prov/tcp/src/tcpx_progress.c
- prov/tcp/src/tcpx_rma.c
> prov/tcp: changing the recv to accommodate rma read/writes

- NEWS.md
> NEWS: Update release notes

- prov/verbs/src/fi_verbs.c
> prov/verbs: Fix name of run-time parameter

- prov/sockets/src/sock_ep_msg.c
> prov/sockets: Fix wrong error reporting in fi_connect

- include/windows/config.h
> common/config: Fix version of libfabric on Windows

- configure.ac
- include/windows/config.h
> Set version to 1.6.2a1

- prov/verbs/src/fi_verbs.h
- prov/verbs/src/verbs_cm.c
- prov/verbs/src/verbs_msg_ep.c
This PR enables usage of utility EP code
>  prov/verbs: Implement usage of utility EP

- prov/tcp/src/tcpx.h
- prov/tcp/src/tcpx_attr.c
- prov/tcp/src/tcpx_comm.c
- prov/tcp/src/tcpx_cq.c
- prov/tcp/src/tcpx_ep.c
- prov/tcp/src/tcpx_progress.c
- prov/tcp/src/tcpx_rma.c
> prov/tcp: Adding RMA Read

- prov/verbs/src/verbs_msg_ep.c
> prov/verbs: Optimize receive path for single buffer

- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_cq.c
- prov/rxm/src/rxm_ep.c
> prov/rxm: Handle failed deferred operations

- master/man/index.md
- v1.4.0/man/index.md
- v1.4.1/man/index.md
- v1.4.2/man/index.md
- v1.5.0/man/index.md
- v1.5.1/man/index.md
- v1.5.2/man/index.md
- v1.5.3/man/index.md
- v1.6.0/man/index.md
- v1.6.1/man/index.md
> index: Add utility man pages to index lists

- prov/util/src/util_av.c
- src/fabric.c
> prov/util: Use variable to control AV addr size

- prov/rxm/src/rxm_cq.c
> prov/rxm: Add handling of completed SAR segment transfer

- include/ofi_mr.h
- prov/rxm/src/rxm_domain.c
- prov/rxm/src/rxm_ep.c
- prov/rxm/src/rxm_init.c
- prov/util: replace check mr local macro with function
- prov/rxm: rxm should advertise FI_MR_LOCAL when NULL hints is given
> prov/util,rxm: updates for FI_MR_LOCAL

- prov/util/src/util_attr.c
Endpoint type is an oft-used attribute by apps so check it first to avoid
unwanted checks of other attributes. This also keeps the logging less verbose.
> prov/util: move endpoint type check to the front

- prov/tcp/src/tcpx_cq.c
> prov/tcp: Use CQ utility fastlock

- prov/rxm/src/rxm_ep.c
This allows to same 10 instructions for TAGGED transport (5 for MSG transport) at receive path:
- `rxm_ep_[t]recv` -> `rxm_ep_recv_common` -> `rxm_ep_format_rx_res` (5 instructions)
- TAGGED only w/o `FI_DIRECTED_RECV` bit set: `rxm_cq_handle_comp` (5 instructions)
> prov/rxm: Reduce instruction counts for the receive path

- contrib/cray/Jenkinsfile.verbs
This commit introduces a Jenkins pipeline file for testing the
verbs provider. This is a first iteration of the pipeline.
> Add Cray Libfabric Jenkins pipeline file

- prov/tcp/src/tcpx_init.c
> prov/tcp: Enable possiblity to select the interface name

- contrib/cray/Jenkinsfile.verbs
Add steps to build libfabric RPMs during pipeline
> contrib/cray: Add RPM build step

- prov/gni/configure.m4
double check that the user gave a correct path
to kdreg package
> prov/gni: improve kdreg configury check

- prov/gni/test/allocator.c
Turns out for some reason that on Cray ARM
systems, the output of /proc/self/maps is
not indicating that large page allocations are
being backed by file systems in /var/lib/hugepages/global.
This confuses one of the GNI criterion tests.
Disable the large page counting in these tests
for now.
> prov/gni: suppress hugepage counting for ARM

- prov/mrail/src/mrail_ep.c
> prov/mrail: Add setopt.

- man/fi_msg.3.md
- man/fi_tagged.3.md
> man: Fix typos in fi_msg and fi_tagged

- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_conn.c
- prov/rxm/src/rxm_cq.c
- prov/rxm/src/rxm_ep.c
- prov/rxm/src/rxm_rma.c
> prov/rxm: Implement SAR protocol

- prov/gni/include/gnix_ep.h
- prov/gni/src/gnix_ep.c
- prov/gni/src/gnix_sep.c
- prov/gni/test/sep.c
> prov/gni: add support for cancel on SEP tx/rx

- prov/rxm/src/rxm_ep.c
There are no needs to calculate comp_flags, because the flags can be used from comp_flags that are passed as an argument to `rxm_ep_send|inject_common`
> prov/rxm: Use passed completion flags from rxm_ep_send|inject_common

- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_ep.c
> prov/rxm: Fix incorrect flags reported to user

- include/ofi_list.h
`struct dlist_ts` - container for lock and dlist
All functions take `head` as an argument to be able to insert, start a loop and so on not only to/from real headd of dlist, but to/from any element.
> common: Implemented thread safe version of dlist

- prov/rxm/src/rxm.h
> prov/rxm : Fix issue in SAR protocol

- include/ofi_list.h
This patch 
- fixes `dlist_ts_insert_before` -- we should use previous node to insert before head.
- makes possible to use head that isn't dynamically allocated by setting `divider` to head.
- fixes `dlist_ts_pop_front` -- we should check whether the list is empty
> common: dlist_ts bug-fixing

- prov/psm2/src/psmx2_init.c
Reporting the total number of contexts for all active HFI units doesn't
work properly for two cases:
(1) HFI_UNIT is set to select a specific HFI unit. Here only the contexts
from that HFI unit should be counted.
(2) PSM2_MULTIRAIL is set to enable multirail mode. Here contexts from
multiple HFIs are grouped together for a single endpoint.
Applications that try to use all avialble contexts would oversubscribe
and fail under these conditions.
Now check the relevant environment variable settings and adjust the reported
number of contexts accordingly.
> prov/psm2: Adjust reported context numbers for special cases

- prov/tcp/src/tcpx_comm.c
The following patches are fixing two issues I discovered while testing the TCP provider.
Please let me know if you want additional details about the issues.
Thanks!
> prov/tcp: few fixes to the provider

- prov/rxm/src/rxm_cq.c
> prov/rxm: Added reporting of errors in SAR protocol

- prov/mrail/src/mrail_ep.c
> prov/mrail: Add fi_recvmsg() call.

- prov/verbs/src/verbs_info.c
Instead ignore the particular verbs device.
(cherry picked from commit fabad16f8f6eb53af26e84acabd5062b23dfcf37)
> [v1.6.x] prov/verbs: don't assert when a verbs device exposes unsupported MTU types

- include/windows/config.h
> osd/windows: Fix versions of package

- .travis.yml
> prov/tcp: enable tcp in travis CI testing with fabtests.

- prov/rxm/src/rxm.h
Use locks for locks for RX buffers always, because they are accessed
from application thread(s) and CM thread.
> prov/rxm: Use locks for RX buffers

- .appveyor.yml
- .travis.yml
> CI testing: Use fabtests v1.6.x branch for testing

- include/ofi.h
- prov/hook/src/hook.c
- prov/hook/src/hook.h
- prov/hook/src/hook_perf.c
- prov/hook/src/hook_perf.h
- src/fabric.c
- src/perf.c
- prov/hook: improve perf hook output formatting
- prov/hook: include the right provider info when logging
> prov/hook: augment provider logging

- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_ep.c
- prov/rxm/src/rxm_rma.c
It saves 13 instructions for fi_inject().
> prov/rxm: Improve fast path by avoiding locks in Connected case

- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_domain.c
- prov/rxm/src/rxm_ep.c
- prov/verbs/src/verbs_info.c
- prov/verbs: change logging level of a log to info
- prov/rxm: add fi_mr_regv, fi_mr_regattr functions
- prov/rxm: remove recursive progress call on send path
> prov/verbs, rxm: updates for MR, progress.

- prov/rxm/src/rxm_init.c
- prov/util/src/util_av.c
- prov/verbs/src/verbs_info.c
Cherry-picked bug fixes from PR #4309
> [v1.6.x] prov/verbs, rxm: bug fixes

- prov/psm/src/psmx_cq.c
- prov/psm2/src/psmx2_cq.c
> prov/psm,psm2: Fix race condition in fi_cq_readerr()

- prov/rxm/src/rxm_ep.c
> prov/rxm: Fix memory leak

- prov/mlx/src/mlx_callbacks.c
- prov/mlx/src/mlx_tagged.c
> prov/mlx: Fix compilation errors

- prov/rxm/src/rxm_cq.c
> prov/rxm: Simplify completion handling

- contrib/cray/Jenkinsfile.verbs
- contrib/cray/sft_test_results_baseline.txt
- prov/rxm/src/rxm_cq.c
Allows us to monitor the progression of various providers through test result expectation matching. 
@rmeegan @tonyzinger
> contrib/Cray: Add SFT with fingerprint support

- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_ep.c
The patch reduces latency (1-2 ms) and message rate (+ ~50k) by saving
40 instructions on a critical send path.
The patch proposes the following behavior:
If the FI_THREAD_SAFE threading mode isn't set, EP doesn't allocate a pool
of buffers for inejct operations, EP allocates single TX buffer for
inject operations and uses it in each inject operation.
Also patch reduces size of RxM EP by using storing only the pointer to
the pools instead of the entire array.
> prov/rxm: Use preallocated inject TX buffer for non-threadsafe mode

- prov/tcp/src/tcpx_comm.c
- prov/tcp/src/tcpx_progress.c
This PR includes two bugfixes to the TCP provider.
> prov/tcp: few additional fixes to the provider

- prov/psm2/configure.m4
> psm2: fix CPU detection

- prov/rxm/src/rxm.h
> prov/rxm: Fix reported size in the log messages

- prov/verbs/src/fi_verbs.h
> prov/verbs: Check return value of ibv_post_send() before handle it

- include/ofi_util.h
- prov/util/src/util_av.c
> util/av: Implement lightweight version of utility AV

- prov/rstream/src/rstream.h
- prov/rstream/src/rstream_ep.c
- prov/rstream/src/rstream_fabric.c
- prov/rstream/src/rstream_msg.c
-send_cq/recv_cq merged
-cq_read pathway unified
-PEEK send/recv
-trywait: enables verbs to arm cqs
> prov/rstream: poll ep to single cq fd

- include/ofi_mr.h
> util/mr_cache: Remove unused mr_tree

- NEWS.md
Also add some missing changes to the 1.6.1 section.
> prov/psm,psm2: Update NEWS for 1.6.2

- fabtests/common/shared.c
On getting EAGAIN from a send/recv operation, we should progress the
corresponding CQ. The "get completion" function may not progress the CQ
if tx/rx seq == tx/rx cq_cntr (i.e. no new completions are expected). This may
result in hangs when run over providers that does "connection progress"
(e.g. RxM).
This patch also updates the inject progress function to just do progress by
reading the CQ irrespective of what the test requested (sread/counters).
> fabtests/common: pass a progress function to FT_POST

- prov/tcp/src/tcpx_progress.c
This patch fixes the following
1) On message receiver side, the recv cq completion notification is
now generated after creating the response message.
2) On transmit side, if we detech error/shutdown and responses for
previous sends are pending, then tcp prov would generate error for
those pending messages on cq.
3) on transmit side, after receiving and consuming the response hdr,
it was not being reset to read the next incoming message. This patch fixed
it.
> prov/tcp: fix bug in delivery response implementation

- NEWS.md
> prov/psm2: Update NEWS for 1.5.4

- NEWS.md
> NEWS: Fix markdown bullet list

- prov/rxm/src/rxm_ep.c
- prov/rxm/src/rxm_rma.c
This is backport of commits from #4410
>  prov/rxm: Fix RDMA Write and MSG inject paths

- NEWS.md
> NEWS: update v1.6.2 news for GNI provider

- prov/rxm/src/rxm_cq.c
> prov/rxm: Remove unnecessary NULL check

- include/ofi_util.h
- prov/tcp/src/tcpx_conn_mgr.c
- prov/tcp/src/tcpx_ep.c
- prov/tcp/src/tcpx_eq.c
- prov/util/src/util_av.c
- prov/util/src/util_eq.c
- prov/verbs/src/fi_verbs.h
- prov/verbs/src/verbs_cm.c
- prov/verbs/src/verbs_ep.c
- prov/verbs/src/verbs_eq.c
- prov/verbs/src/verbs_info.c
> util/eq, prov/tcp, prov/verbs: Fix handling of EQ entry error data

- contrib/cray/Jenkinsfile.verbs
- contrib/cray/verify_requirements.sh
Merge sections and introduce pipeline parallelism when possible.
@tonyzinger @rmeegan
> contrib/cray: Refactor Jenkinsfile 

- prov/rstream/src/rstream.h
- prov/rstream/src/rstream_ep.c
- prov/rstream/src/rstream_msg.c
> prov/rstream: move tx contexts to freestack

- prov/tcp/src/tcpx_ep.c
- prov/tcp/src/tcpx_rma.c
> prov/tcp: fixing bug with flags in msg send and rma write

- prov/sockets/src/sock_ep.c
- prov/verbs/src/verbs_info.c
Fix some fi_info output bugs including the Verbs and sockets fabric reporting.
This is a new pull request integrating all comments...  correctly this time...
> Fi info fixes

- prov/verbs/src/verbs_cq.c
> prov/verbs: Fix return value of fi_cq_readerr

- prov/mrail/src/mrail_cq.c
Thanks go to @a-ilango for figuring out what the issue was. :-)
> prov/mrail: Fix recv completion reporting.

- prov/mrail/src/mrail_ep.c
> prov/mrail: Add support for fi_trecvmsg

- prov/mrail/src/mrail_cq.c
> prov/mrail: Add src addr matching.

- man/fi_rxm.7.md
Fixes #4425 
@jswaro does this look good?
> prov/rxm: man page updates

- prov/rxm/src/rxm_ep.c
- prov/rxm: fix a crash in error path 
- prov/rxm: fix a crash when fi_send returns error in large message transfer
> [v1.6.x] prov/rxm: bug fixes

- fabtests/benchmarks/rma_bw.c
- fabtests/common/shared.c
- fabtests/functional/rdm_atomic.c
- fabtests/functional/rdm_rma_simple.c
- fabtests/functional/rdm_rma_trigger.c
- fabtests/include/shared.h
> fabtests: Add support for FI_MR_RAW keys exchange.

- prov/tcp/src/tcpx.h
- prov/tcp/src/tcpx_cq.c
- prov/tcp/src/tcpx_ep.c
- prov/tcp/src/tcpx_progress.c
- prov/tcp/src/tcpx_rma.c
> prov/tcp: proper implementation of completion flags

- prov/rxm/src/rxm_conn.c
@dmitrygladkov @a-ilango this addresses issue #4512
I was seeing stack smashing with OSU benchmarks at termination. This makes sure space
is allocated for the RXM connection data, the structure "entry" allocated on the stack
did not include space for RXM connection data. This was problem is first seen
in commit: 632421e.
> prov/rxm: bugfix - stack corruption in in rxm_conn_progress (#33)

- man/fi_atomic.3.md
Based on several conversations, this tries to clarify the behavior
of atomic operations where there is inconsistency or incorrect
documentation.
Fixes #4504
Fixes #4500
> man/atomic: Add clarifications on atomic behavior

- man/fi_mr.3.md
> man/mr: Add missing field to fi_mr_attr

- include/ofi_util.h
- prov/rxd/src/rxd.h
- prov/rxd/src/rxd_cq.c
> prox/rxd: check seq_no for wrapping

- src/fabric.c
Signed-off-by: Ignacio Hernandez <ignacio.hernandez@intel.com>
> fabric: Make sure we have a valid provider ptr before using it

- prov/rxm/src/rxm_cq.c
TX completion counter should be incremented for LMT TX
> prov/rxm: Remove unneeded checks for LMT TX

- fabtests/scripts/runfabtests.sh
Add the -E option to export environment variables to client and server
applications launched via ssh.
closes #4559
> fabtests: Add -E option to export environment vars

- prov/rstream/src/rstream_cm.c
> prov/rstream: fi_shutdown

- man/fi_tcp.7.md
- prov/tcp/Makefile.include
> prov/tcp: Add tcp man page

- contrib/cray/Jenkinsfile.verbs
- prov/rxm/src/rxm.h
Create a unique xml file for each SFT test.
> contrib/cray: Create a unique xml file for each SFT test.

- prov/rstream/src/rstream_cm.c
> prov/rstream: add cm getname

- prov/rxm/src/rxm_av.c
- prov/rxm/src/rxm_conn.c
- prov/rxm: fix issues with moving connection handle to peer list 
- prov/rxm: fixes for AV insert/remove
> prov/rxm: bug fixes for AV and cmap

- prov/psm2/src/psmx2_cq.c
In the HAVE_PSM2_MQ_REQ_USER=1 case, whether source address should be reported
is determined by if the "src_addr" passed to fi_cq_read() is non-NULL. However,
even if "src_addr" is NULL, it is possible that the event is enqueued and then
be read later with non-NULL "src_addr". In such case, the source address info
is lost.
Fix by copying correct handling from the HAVE_PSM2_MQ_REQ_USER=0 case.
> prov/psm2: Fix source address reporting in the HAVE_PSM2_MQ_REQ_USER=1 case

- include/ofi_net.h
- include/ofi_util.h
- prov/tcp/src/tcpx_conn_mgr.c
- prov/tcp/src/tcpx_cq.c
- prov/tcp/src/tcpx_ep.c
- prov/tcp/src/tcpx_eq.c
- prov/util/src/util_eq.c
- src/common.c
Minor cleanups to the tcp provider.
Also, as a test I enabled LGTM code analysis.  Added a badge to the readme.md file for this.  Coverity is no longer running against the repo, so enabling an alternative analysis tool to see how well it works.
> prov/tcp: Cleanups to the tcp provider

- prov/rstream/src/rstream_init.c
-re-abled wildcard usage over verbs
> prov/rstream: wildcard enabling regression fix

- prov/psm2/src/psmx2_av.c
Disconnect a remote address when it is removed from the address vector. This
allows the remote address be reused by a different peer and thus prevents
"out of resource" error for applications that use dynamic processes.
> prov/psm2: Clean up connection state in fi_av_remove

- include/ofi_util.h
`ofi_cq_write_src` doesn't unlock CQ after handling full CQ cirq case.
This patch fixes it by adding thread unsafe version of `ofi_cq_write_src`
that will be used for futher needs.
> prov/util: Add missed unlocking CQ lock

- contrib/cray/Jenkinsfile.verbs
Use source tree rather than distributed source tree.
> contrib/cray: Change source tarball for DST

- prov/rstream/src/rstream_eq.c
> prov/rstream: added eq_read

- prov/rxm/src/rxm_ep.c
- prov/util/src/util_av.c
- prov/verbs/src/verbs_cm.c
- prov/verbs/src/verbs_domain_xrc.c
first batch of fixes for coverity issues.
> coverity related fixes

- prov/rxm/src/rxm_conn.c
- prov/udp/src/udpx_cq.c
- prov/util/src/util_av.c
- prov/verbs/src/verbs_info.c
@aingerson - includes update for udp to support fi_control
@a-ilango @dmitrygladkov - simplifies cmap av handle array allocation
> yay for coverity fixes

- fabtests/scripts/runfabtests.sh
This avoids unnecessary waiting for server process to finish. Also renamed
ret variables to improve clarity.
> fabtests/runfabtests.sh: kill server process if client errors

- prov/psm2/src/psmx2_av.c
> prov/psm2: Fix scalalble endpoint handling in fi_av_remove()

- prov/rxm/src/rxm_cq.c
- prov/rxm/src/rxm_ep.c
- prov/util/src/util_mr_cache.c
This PR would be updated once #4605 is merged
> prov/rxm, util: bug fixes for rxm CQ and util MR cache

- fabtests/test_configs/ofi_rxd/ofi_rxd.exclude
- include/ofi.h
- include/ofi_util.h
- man/fi_endpoint.3.md
- prov/rxd/src/rxd.h
- prov/rxd/src/rxd_attr.c
- prov/rxd/src/rxd_cntr.c
- prov/rxd/src/rxd_cq.c
- prov/rxd/src/rxd_ep.c
- src/common.c
- add blocking/fd waiting support
- fix counter increments
- redefine fetch and compare tx and rx flags
> prov/rxd: sread support, fix counters and completion handling

- prov/rxd/src/rxd_cq.c
- prov/rxd/src/rxd_ep.c
- prov/rxd/src/rxd_rma.c
> prov/rxd: use rx entry instead of tx entry for read/fetches

- prov/rxd/src/rxd_cq.c
Previously, if the CTS packet to a peer was dropped, the peer will not have saved the peer_addr causing a seg fault (ep->peers[FI_ADDR_UNSPEC]) when receiving the first message from that peer. Add a few fixes to avoid this issue:
- Only progress op if peer_addr is initialized
- Only progress list if peer_addr is initialized
Not related to CTS issue but this also removes an extra, unneeded ACK
> prov/rxd: handle case if CTS was dropped

- prov/rxd/src/rxd_attr.c
- src/fi_tostr.c
Manually pulling in fixes from @aingerson master, though  I messed up somewhere and ended up with 2 extra patches.  Anyway, pulling them in here, so I can re-force CI.
> rxd fixes; from PR #4703

- prov/mlx/src/mlx_av.c
- prov/mlx/src/mlx_cm.c
This patch fixes wrong behavior of `fi_getname` in MLX provider
in case of FI_SOCKADDR_IN address format used by application.
MLX provider reports the required length of EP name buffer to user
and returns `-FI_ETOOSMALL` errro in case of an user provided
a small buffer.
> prov/mlx: Fix wrong fi_getname behavior

- prov/rxd/src/rxd.h
- prov/rxd/src/rxd_cq.c
- prov/rxd/src/rxd_ep.c
Fixes hfi issue when CQ was overflowed with extra ACKs
> prov/rxd: CQ overflow fix

- COPYING
- NEWS.md
- configure.ac
- fabtests/configure.ac
- prov/usnic/src/usnic_direct/usd_ib_sysfs.c
> v1.7.0 - for CI testing - will push directly when ready

- configure.ac
- fabtests/configure.ac
> fabric: Update release number to post 1.7

- configure.ac
- fabtests/configure.ac
> fabric: Update release to 1.7.1a1

- include/ofi.h
- prov/rxd/src/rxd_cq.c
- prov/rxd/src/rxd_init.c
- prov/rxd/src/rxd_proto.h
The description can be found in the commit messages
> prov/rxd: Various improvements

- util/pingpong.c
> pp: Fix the finalization of the test

- include/rdma/fi_domain.h
> common: Code cleanups in the fi_mr_refresh

- prov/tcp/src/tcpx_conn_mgr.c
> prov/tcp: Fixing code ambiguity

- prov/rxd/src/rxd_attr.c
> prov/rxd: Added missed EP attributes

- prov/udp/src/udpx_init.c
> prov/udp: Fix leak of address list

- index.md
> index: Add link to webinar slides

- src/fi_tostr.c
> Add FI_MR_ENDPOINT to ofi_tostr_mr_mode()

- prov/shm/src/smr_av.c
- prov/shm/src/smr_cq.c
Fixes memory leak and memory corruption
> [v1.7.x] prov/shm: cherry picked fixes for shm

- include/windows/osd.h
- src/log.c
> Include process ID in log messages

- prov/tcp/src/tcpx.h
- prov/tcp/src/tcpx_cq.c
- prov/tcp/src/tcpx_progress.c
> prov/tcp: seperate out functions for cq success and error cases.

- prov/sockets/src/sock_cq.c
> Sockets cq_sread should retry on -EINTR

- prov/verbs/src/verbs_info.c
Handle the case where the application has not requested FI_RX_CQ_DATA
in the RX attribute check by removing FI_RX_CQ_DATA in a copy of the
default fi_info. Note, that this fix also removes the check of
domain->cq_data_size as a method of determining if FI_RX_CQ_DATA is
required. It is an error to set domain->cq_data_size and not also
include FI_RX_CQ_DATA.
> prov/verbs: Make verbs fi_getinfo rx_attr verification thread-safe

- prov/verbs/src/verbs_domain_xrc.c
When an XRC connection request is rejected and the associated
XRC Send QP represents the physical QP to the rejecting host,
destroy that QP before any pending connection to that same
rejecting host proceeds.
> prov/verbs: Fix intermittent CQ busy at MPI finalize when using XRC

- prov/sockets/src/sock_fabric.c
> manual merge of Chris' patches

- include/windows/osd.h
> windows: Remove duplicate getpid define

- include/ofi_proto.h
- include/ofi_util.h
> prov/util: rename ofi_op_last to ofi_op_max

- prov/mrail/src/mrail_init.c
Also fix a potential NULL dereference of domain_attr.
> prov/mrail: Add log output when given modes fail to pass through

- prov/verbs/src/verbs_domain_xrc.c
- prov/verbs/src/verbs_info.c
prov/verbs: Make verbs fi_getinfo rx_attr verification thread-safe
prov/verbs: Fix intermittent CQ busy at MPI finalize when using XRC
> [v1.7.x] prov/verbs: Additional cherry picked fixes for Verbs provider

- prov/tcp/src/tcpx_progress.c
when get_rx_entry fails, there is a possibility that tcpx_recv_hdr will return FI_ENOTCONN - when called after full header already read from socket. This patch eliminates that case.
> prov/tcp: refactor rx msg processing

- fabtests/Makefile.am
- fabtests/test_configs/shm/quick.test
- fabtests/test_configs/shm/shm.exclude
Cherry pick testing updates for shm to avoid failures on the CI when testing 1.7.x PRs
> [v1.7.x] test_cofigs/shm: cherry-pick shm testing updates

- src/common.c
Allow the input address string be host name, ip address, or network interface
name in addition to the original "fi_addr[...]://address" format.
> common: Add flexibility to ofi_str_toaddr()

- prov/mrail/src/mrail_init.c
> prov/mrail: Fix mr_mode passthough with FI_MR_BASIC

- prov/rxm/src/rxm_init.c
> prov/rxm: change getinfo logging from debug to info

- prov/gni/test/sep.c
> prov/gni: squash minor compiler warning

- NEWS.md
> NEWS: Update psm2 provider notes for release 1.7.1

- NEWS.md
- configure.ac
- fabtests/configure.ac
- include/windows/config.h
Will be pushed directly once testing completes.
> v1.7.1 - CI testing only - do not merge

- configure.ac
- fabtests/configure.ac
- include/windows/config.h
> configure: Update to post v1.7.1 release

- util/info.c
Verbs man pages says that `fi_info -e -p verbs` will show environment variables related only to verbs provider, but it seems that this functionality of `-e` flag with explicitly specified provider was broken or not implemented yet. `-p` flag was simply ignored in case of `-e` option.
This changes enables `fi_info` to show provider related environment variables by `-e -p <provider_name>` flags.
> fi_info: enable envvars output for explicitly scpecified provider

- prov/rxm/src/rxm_conn.c
- prov/rxm/src/rxm_cq.c
Free cmap handles after CM thread join. This avoids the need to set the state
to "shutdown" and also avoid having to fetch the cmap lock. Any unread events
in the MSG provider EQ should be cleaned up by MSG provider on endpoint close.
With this change we shouldn't hit failure in the assertion in
rxm_cmap_process_connect: assert(handle->state == RXM_CMAP_CONNREQ_RECV).
Previously, the state was set to RXM_CMAP_SHUTDOWN by rxm_cmap_del_handle to
allow postponing freeing of the connection handle until after we process all
events corresponding to it.
> prov/rxm: fix incorrect ordering in cmap cleanup

- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_conn.c
- prov/rxm/src/rxm_cq.c
Some smaller commits were picked to avoid some of the merge conflicts.
>  [v1.7.x] prov/rxm: cherry-picked fixes / improvements

- prov/tcp/src/tcpx_ep.c
> prov/tcp: verify info when creating pep.

- prov/rxd/src/rxd_ep.c
(cherry-picked from af098c3b7fffe207cb17e5eb8690b8f0a3e2ca9a)
Signed-off-by: Nikita Gusev nikita.gusev@intel.com
> [v1.7.x] prov/rxd: fix segfault

- prov/gni/test/run_gnitest
since other developers may start using this, make it easier
> prov/gni: update criterion test script

- prov/util/src/util_mem_monitor.c
> core/monitor: Add missing newline debug print

- contrib/cray/Jenkinsfile.verbs
Increase timeout for ubertest, additional tests have been added.
> contrib/cray: Increase timeout for ubertests

- prov/rxd/src/rxd.h
- prov/rxd/src/rxd_atomic.c
- prov/rxd/src/rxd_msg.c
- prov/rxd/src/rxd_rma.c
Generalized checking of cq_data for all transmit operations
> prov/rxd: Added check function for rxd_remote_cq_data

- prov/verbs/src/verbs_eq.c
- add missing lock when accessing EQ error entry
- return EAGAIN when the EQ error entry is NULL
> prov/verbs: fixes for EQ readerr

- include/ofi_util.h
- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_atomic.c
- prov/rxm/src/rxm_av.c
- prov/rxm/src/rxm_conn.c
- prov/rxm/src/rxm_cq.c
- prov/rxm/src/rxm_ep.c
- prov/rxm/src/rxm_init.c
- prov/rxm/src/rxm_rma.c
- prov/util/src/util_av.c
- prov/util/src/util_ep.c
- prov/verbs/src/fi_verbs.h
- prov/verbs/src/verbs_cm.c
- prov/verbs/src/verbs_cm_xrc.c
- prov/verbs/src/verbs_domain_xrc.c
- prov/verbs/src/verbs_ep.c
- prov/verbs/src/verbs_eq.c
@swelch I've picked your commits in #5033 to here. Please verify if they look good.
> [v1.7.x] prov/verbs, rxm: cherry pick fixes for v1.7.2

- prov/tcp/src/tcpx_ep.c
The commits with [v1.7.x] tag are equivalent to corresponding commits in master.
> [v1.7.x] prov/tcp: cherry picked fixes

- prov/psm2/configure.m4
- prov/psm2/src/version.h
> prov/psm2: Add configuration options to disable some PSM2 features

- prov/psm2/configure.m4
> prov/psm2: Change the default setting of optional PSM2 features to off

- man/fi_tcp.7.md
> prov/tcp: man page update

- prov/rxd/src/rxd.h
- prov/rxd/src/rxd_cq.c
- prov/rxd/src/rxd_ep.c
- prov/rxd/src/rxd_msg.c
- Reposting fix
- Fix incorrect op
- Optimize retrying
- Optimize/fix unexpected messaging reposting
- Don't send acks if peer is uninitialized
- Get rid of pending_cnt
> prov/rxd: various updates/fixes

- include/ofi_iov.h
- include/ofi_mr.h
- include/ofi_tree.h
- prov/util/src/util_mr_cache.c
- prov/util/src/util_mr_map.c
- src/tree.c
> mr cache: Proposed fix for handling page fault notifications

- NEWS.md
- configure.ac
- fabtests/configure.ac
> v1.7.2 - final release for CI testing

- prov/gni/src/gnix_msg.c
- prov/gni/test/rdm_multi_recv.c
the GNI provider wasn't handling certain cases for multi-receive
where the rendezvous protocol was being used with multi-receive
buffers.
> prov/gni: fix another issue with GNI mrecv

- prov/rxm/src/rxm_conn.c
- prov/verbs/src/verbs_eq.c
> prov/rxm, verbs: fixes for memory leaks

- prov/tcp/src/tcpx.h
> prov/tcp: Change version to 1.0

- fabtests/common/shared.c
- prov/util/src/util_cntr.c
- prov/util/src/util_wait.c
- prov/verbs/src/fi_verbs.h
- prov/verbs/src/verbs_cq.c
- prov/verbs/src/verbs_domain.c
- prov/verbs/src/verbs_eq.c
> prov/util, verbs: fixes for counter wait and trywait.

- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_rma.c
- prov/efa/src/rxr/rxr_rma.h
> prov/efa : two RMA related patches

- NEWS.md
> add a few NEWS items for GNI provider

- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_ep.c
Currently read repsonse packet only contain remote EP tx_entry's tx_id,
which is inefficient. Moreover, there is a potential race condition:
Although we start sending data packets after we got sent completion for
the read response packet, it is still possible that data packets arrive
before read response packet does. For short message,
rxr_cq_handle_data() will release rx_entry, which means
rxr_cq_handle_readrsp() will be operating on a wild pointer.
Adding data to read response packet both improves efficiency and solves
the problem of race condition.
> prov/efa : let read response packet contain data

- prov/tcp/src/tcpx_progress.c
> prov/tcp: fix coverity warning

- prov/mrail/src/mrail.h
- prov/mrail/src/mrail_cq.c
- prov/mrail/src/mrail_ep.c
Implement a Rendezvous protocol that deliver large size messages via RMA
reads. This naturally enables message striping because RMA operations are
always striped across all the rails.
Future enhancement will add tuning knobs to the RMA striping algorithm
to improve the performance of medium size messages.
Also consolidate two mostly identical common send functions into one.
> prov/mrail:  Implement message striping using Rendezvous and RMA

- prov/efa/src/rxr/rxr_init.c
> prov/efa: Use FI_AV_TABLE as the preferred av_type

- fabtests/Makefile.am
- fabtests/Makefile.win
- fabtests/benchmarks/benchmark_shared.c
- fabtests/benchmarks/benchmark_shared.h
- fabtests/benchmarks/msg_bw.c
- fabtests/benchmarks/rdm_tagged_bw.c
- fabtests/benchmarks/rma_bw.c
- fabtests/common/shared.c
- fabtests/fabtests.vcxproj
- fabtests/functional/bw.c
- fabtests/functional/rdm_tagged_peek.c
- fabtests/functional/shared_ctx.c
- fabtests/functional/unexpected_msg.c
- fabtests/include/shared.h
- fabtests/scripts/runfabtests.cmd
- fabtests/scripts/runfabtests.sh
Add new bandwidth test with multiple MRs and data verification and common code support for the test:
- Replace old context arrays with new context/MR arrays
- Add option flags for allocating multiple MRs and support for these flags
Add new test to runfabtests script for regular testing.
> fabtests/functional/bw: add new bw data verification test and modify common code for support

- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_init.c
- prov/efa/src/rxr/rxr_rma.c
This is a take on peer-aware flow control. The heuristic is described in the individual commit msg.
> prov/efa: Peer-aware flow control

- prov/efa/src/rxr/rxr_init.c
> prov/efa: Check for a valid domain_attr object

- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_init.c
These fixes also need to land in 1.8.x.
> prov/efa: Some bugfixes for the 1.8.x branch

- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_ep.c
Fix two issues in the EFA provider discovered by coverity.
> EFA coverity fixes

- prov/rxd/src/rxd_ep.c
> prov/rxd: Added calling rxd_ep_free_res() in err path

- prov/tcp/src/tcpx_ep.c
**Issue:**
While we try to bind to a port after several unexpected interrupts, while the app is in process, the port stays in `TIME_WAIT` status. It is the specific feature of Linux OS, `TIME_WAIT` state is what a socket goes into when it closes. We need to wait, when OS let the specific port  `LISTEN` again because the app, you try to launch just failed and cant be launched.
**Fixed:**
That is why we should use `SO_REUSEADDR`(calling `tcpx_setup_socket()`). This socket option tells the kernel that even if this port is busy (in the TIME_WAIT state), go ahead and reuse it anyway.  If it is busy,  but with another state, you will still get an address already in use  error.
**Tested:**
Since [ae62148](https://github.com/ofiwg/libfabric/commit/ae62148c8d73b8bdd001f15c87e97ca7583720c9) we …
> prov/tcp: Bind a specific port range, using SO_REUSEADDR

- include/rdma/fi_domain.h
Signed-off-by: Doug Oucharek <dougso@me.com>
> common: Address compile error when using g++

- prov/efa/src/rxr/rxr_ep.c
EFA's fi_cancel() implementation was not handling multi recv buffers correctly
and was leaking rx entries. It still does not search for messages in flight
which will need to be addressed in a follow up commit.
> prov/efa: fix fi_cancel crash and leak

- contrib/cray/Jenkinsfile.verbs
Only build master branch and PRs from OFIWG at this point.
May include other branches later.
> contrib/cray: Add verification for Jenkins builds

- prov/psm2/src/psmx2_trx_ctxt.c
The AM handler for the disconnection protocol could be invoked when
the AV lock is already held. Move the operations that require locking/
unlocking to the new thread to avoid deadlock.
> prov/psm2: Avoid a potential deadlock in disconnection protocol

- prov/util/src/util_mem_hooks.c
Inside brk() intercept, we get sbrk(0) - the current address of break.
And if we do brk(value + current address of break), so we notify monitor about
intercept and then the intercept is finished successfully, else we just call origional brk().
> prov/util: Add brk intercept for memhooks mechanism

- prov/efa/src/efa_verbs/efa_ib_cmd.c
Linux copy-on-write semantics mean that following a fork() call,
parent and child processes will have page table entries pointing to
the same physical page. Since these pages are write protected, if
either the parent or child writes to the page, the hardware will
trap the event. The kernel will then allocate a new page and copy
the contents from the original page, breaking the virtual to physical
page link for that process.
To prevent this case, marking pinned memory with MADV_DONTFORK
only allows the memory range to be seen by the parent process, and
the copy-on-write semantics no longer apply to this memory range.
Since the rdma-core library already does all this work for us,
when we add rdma-core, we will move the logic down a layer and
remove it from here.
Signed-off-by: William Zhang …
> prov/efa: Fix mismanagement of pinned memory after fork()

- prov/rxd/src/rxd.h
- prov/rxd/src/rxd_cq.c
- prov/rxd/src/rxd_ep.c
> prov/rxd: Add rxd_remove_free_pkt_entry for dlist_remove/buf_free of pkt_entries

- prov/rxd/src/rxd.h
- prov/rxd/src/rxd_ep.c
- prov/rxd/src/rxd_msg.c
> prov/rxd: Refactor for cleanup_unexp_msg

- prov/tcp/src/tcpx_ep.c
> prov/tcp: Code clean up 

- prov/efa/src/rxr/rxr_ep.c
Would like these two fixes to be in the 1.8.1 release.
> EFA fixes for 1.8.1

- Makefile.am
- include/ofi_coll.h
- include/ofi_util.h
- include/rdma/fabric.h
- include/rdma/fi_collective.h
- libfabric.vcxproj
- libfabric.vcxproj.filters
- man/fi_collective.3.md
- prov/util/src/util_coll.c
> util/collective: Merging of collective APIs

- NEWS.md
> NEWS.md: Update psm2 provider notes for 1.8.1

- NEWS.md
> NEWS.md: EFA changelog for 1.8.1

- prov/verbs/src/verbs_eq.c
- prov/verbs/src/verbs_info.c
~~The first 6 patches would be dropped from this PR once #5259 is merged.~~
> prov/verbs: fixes for handling IPv6 link local address, unknown CM event

- NEWS.md
> [v.1.8.x] NEWS.md: update change log for shm and rxd

- prov/verbs/src/verbs_eq.c
By allowing the verbs CM event processing to continue if
an internal XRC event has been processed, XRC connection
setup time can be reduced between 47% in light and medium
loaded PPN environments, and ~ 15% on fully loaded PPN
(i.e. PPN == # virtual cores) environments.
RC will not hit the condition checked and will continue
to process at most 1 CM event.
> prov/verbs: Speedup XRC connection setup time

- configure.ac
- fabtests/configure.ac
Will be merged directly when ready
> v1.8.1rc2 - for CI testing only

- prov/shm/src/smr_atomic.c
- prov/shm/src/smr_ep.c
Fix issue reported by klocwork
> prov/shm: cast address pointer correctly

- prov/rxm/src/rxm_cq.c
- prov/tcp/src/tcpx_init.c
- prov/udp/src/udpx.h
- prov/udp/src/udpx_init.c
- prov/verbs/src/fi_verbs.h
- prov/verbs/src/verbs_ep.c
- prov/verbs/src/verbs_info.c
Minor, but valid, issues reported by klocworks.
> prov/tcp, rxm, udp, verbs: minor cleanups to silence klocworks

- NEWS.md
- configure.ac
- fabtests/configure.ac
> v1.8.1 - for CI testing only

- fabtests/multinode/include/core.h
- fabtests/multinode/src/core.c
- fabtests/multinode/src/harness.c
- fabtests/multinode/src/pattern.c
- fabtests/scripts/runfabtests.sh
- fabtests/test_configs/sockets/sockets.exclude
Fab tests will now run the multinoded test at 16, 32, 48, and 64 processes. 
> Multinode tests in runfabtests.sh

- fabtests/test_configs/efa/efa.exclude
> fabtests: Exlude multinode tests for EFA provider

- src/fabric.c
The user can set FI_PROVIDER=socket (misspeling "sockets"),
and FI_WARN will mention about misspelling and suggest a samilliar
variant of a providers' list.
It also works for FI_PROVIDER="xxx;yyy", it will notify about
misspelling one of values or two ones.
And it also warns about using the sentitive case, it means,
when the user set FI_PROVIDER value into the upper case.
> src/fabric.c: spell checker for value of FI_PROVIDER

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/build.py
- contrib/intel/jenkins/common.py
- contrib/intel/jenkins/run.py
- contrib/intel/jenkins/runtests.py
- contrib/intel/jenkins/tests.py
changes for Jenkins-CI
Signed-off-by: nikhilnanal <nikhilnanal1@gmail.com>
> test scripts for Jenkins-CI

- contrib/cray/Jenkinsfile.verbs
Signed-off-by: Tony Zinger <ajz@cray.com>
> contrib/cray: Increase the number of simultaneous jobs for the SFT tests

- contrib/cray/Jenkinsfile.verbs
Change the install label from the git short hash
to the git description for the current tag.
> contrib/cray: Change install label

- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_ep.c
> Efa 3 refactors fixed

- src/fi_tostr.c
- util/info.c
> core: Add HMEM bits to the string converters

- prov/util/src/util_mr_cache.c
See Issue #5347 for more details. Due to userfault unsubscribing from
monitored regions automatically in the notify path, calling unsubscribe
could unregister regions that still need to be monitored.
> prov/util: Remove monitor unsubscribe from cache notify

- prov/efa/src/rxr/rxr_cq.c
> prov/efa: Bugfix the missing of rx_entry release

- prov/tcp/src/tcpx.h
- prov/tcp/src/tcpx_comm.c
- prov/tcp/src/tcpx_conn_mgr.c
- prov/tcp/src/tcpx_cq.c
- prov/tcp/src/tcpx_domain.c
- prov/tcp/src/tcpx_ep.c
- prov/tcp/src/tcpx_eq.c
- prov/tcp/src/tcpx_init.c
- prov/tcp/src/tcpx_msg.c
- prov/tcp/src/tcpx_progress.c
- prov/tcp/src/tcpx_rma.c
- prov/tcp/src/tcpx_shared_ctx.c
Fix CQ error number reporting.  Fix formatting issues.  Fix 0 length transfers
> prov/tcp: Handle 0 length transfers

- contrib/cray/Jenkinsfile.verbs
Jenkins was not fetching tags, so git describe failed
Migrated from 3.3b3 for MPICH to 3.3
> contrib/cray: Fix recent build issue

- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_rma.c
- prov/efa/src/rxr/rxr_rma.h
3 refactors:
1. refactor rxr_cq_process_rts() and related functions
2. refactor rxr_tx() and related functions
3. refactor rxr_inline_mr_reg()
> Efa 3 new refactors v2

- prov/tcp/src/tcpx_ep.c
When a tcp endpoint is closed, all queued transmit and
receive operations are simply freed.  However, no
notification is given to the caller.  This can result
in the caller (e.g. the rxm provider) losing data buffers,
resulting in a memory leak.
When closing the endpoint, provide a error completion
entry for each canceled request.  This provides the
context needed by the caller to reclaim resources without
needing to track the requests separately.
Fixes #5381
> prov/tcp: Report aborted requests as canceled

- prov/rxm/src/rxm.h
> prov/rxm: align code style

- prov/psm2/src/psmx2.h
- prov/psm2/src/psmx2_av.c
- prov/psm2/src/psmx2_cq.c
- prov/psm2/src/psmx2_init.c
- prov/psm2/src/psmx2_trx_ctxt.c
> prov/psm2: Fix memory leaks

- prov/efa/src/efa_mr.c
fixed problem where fabtests would fail when rxd was enabled and
mr_cache was disabled.
pass efa_mr_cache_reg to run efa_mr_reg when OFI_MR_NOCACHE flag is set
added goto error to error cases and return error codes
> prov/efa: Added case to efa_mr_reg and efa_mr_cache_reg to handle OFI_MR_NOCACHE flag

- NEWS.md
> NEWS: Update for v1.9.0 release

- prov/verbs/src/verbs_domain.c
- prov/verbs/src/verbs_info.c
Fix inversion of check introduced in commit d38c8869.
> prov/verbs: Fix regression for issue #5427

- NEWS.md
> prov/efa: NEWS.md updates for the 1.9 release

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/Jenkinsfile.daily
- contrib/intel/jenkins/runtests.py
-added Jenkinsfile.daily to handle comprehensive testing once a day on branches.
- modified Jenkinsfile to do quick validation on every commit for a PR.
- added post step for cleanup in Jenkinsfile.
> Added daily builds, made per commit build faster, added cleanup code

- NEWS.md
> NEWS.md: 1.9 updates

- prov/rxm/src/rxm_conn.c
> prov/rxm: Refactor rxm_msg_eq_progress()

- contrib/intel/jenkins/Jenkinsfile.daily
> Jenkinsfile.daily: added email Notification on failure for daily builds

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/build.py
- contrib/intel/jenkins/run.py
- contrib/intel/jenkins/runtests.py
- contrib/intel/jenkins/tests.py
build.py: added code to  build shmem, ISx and PRK, uh
tests.py: added class ShmemTest
runtests.py:added function calls to invoke shmemtests
run.py: added function defintion for shmemtests
> Added SHMEM testing to Jenkins-CI

- prov/util/src/util_cntr.c
Move all cntr_fid initialization to fi_cntr_init() and
add separate no-wait ops to fix clobber of wait pointer.
Fixes #5472 
> prov/util Add separate no_wait ops in util_cntr.c

- prov/shm/src/smr_cq.c
> prov/shm: fix pointer passed into ofi_cq_init

- prov/shm/src/smr_cq.c
Cherry-picked from commit dcb9c6dbf5e9bebefec5fc00ea1d6133a701f4e6
> [v1.8.x] prov/shm: fix pointer passed into ofi_cq_init

- contrib/intel/jenkins/Jenkinsfile.daily
Jenkinsfile.daily: added code to build shmem for nightly builds.
Signed-of-by: Nikhil Nanal<nikhil.nanal@intel.com>
> shmem build for nightly builds

- prov/efa/src/efa_verbs/efa_init.c
- prov/efa/src/rxr/rxr_ep.c
- prov/shm/src/smr.h
- prov/shm/src/smr_ep.c
- prov/shm/src/smr_msg.c
- prov/shm/src/smr_progress.c
> Efa 1.9 backport

- prov/efa/src/rxr/rxr_init.c
If a user specifies `FI_PROVIDER=efa` the shm provider will not be found
when the efa provider queries for it. Instead of failing the efa getinfo
call follow the selection given by the user and skip shm initialization.
> prov/efa: Do not fail getinfo when shm is unavailable

- prov/efa/src/rxr/rxr_init.c
If a user specifies `FI_PROVIDER=efa` the shm provider will not be found
when the efa provider queries for it. Instead of failing the efa getinfo
call follow the selection given by the user and skip shm initialization.
> [v1.9.x] prov/efa: Do not fail getinfo when shm is unavailable

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/Jenkinsfile.daily
- contrib/intel/jenkins/tests.py
Jenkinsfile, Jenkinsfile.daily : added code to invoke test scripts for shm prov
> added shm prov testing.

- contrib/intel/jenkins/Jenkinsfile
Jenkinsfile: removed parallel stage eth-sockets-dbg
> Removed testing of sockets for PR tests.

- contrib/intel/jenkins/Jenkinsfile.daily
Jenkinsfile.daily : corrected paranthesis for one of the stages
Signed-off-by : Nikhil Nanal <nikhil.nanal@intel.com>
> Fixed syntax error in Jenkinsfile.daily

- prov/tcp/src/tcpx.h
- prov/tcp/src/tcpx_comm.c
- prov/tcp/src/tcpx_eq.c
- prov/tcp/src/tcpx_progress.c
> prov/tcp: minor refactoring of tcp  prov

- contrib/intel/jenkins/run.py
- contrib/intel/jenkins/tests.py
tests.py: added IMB test abstract class and implementations for mpi1 and rma tests.
> Added IMB RMA tests

- libfabric.def
> add missing "fi_version" symbol in "libfabric.def'

- prov/rxm/src/rxm_ep.c
When posting a multi-recv buffer, if there are unexpected messages
waiting, complete them, up to the size of the multi-recv buffer.
> prov/rxm: Handle unexpected messages when posting multi-recv buffers

- prov/efa/src/efa_fabric.c
FI_INJECT is not optional, only way to disable it is by setting
tx_attr->inject_size to 0. Setting inject size for dgram endpoint
causes a failure with fi_dgram_pingpong, as there is no way to
discard completions in EFA layer. We should set inject size for rdm
only
> prov/efa: Set inject buffer size only for rdm

- prov/efa/src/efa_fabric.c
efa_get_matching_info could return multiple
eligible fi_info structs. efa_set_fi_address
should set all of them.
> prov/efa: Bugfix of efa address setting

- src/fabric.c
The return value from ofi_register_provider is not checked.
If we fail to register a provider, it is simply skipped.
> core: Convert ofi_register_provider to void

- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_msg.c
- prov/efa/src/rxr/rxr_msg.h
- prov/efa/src/rxr/rxr_pkt_type.h
- prov/efa/src/rxr/rxr_pkt_type_rts.c
> Refactor rts

- prov/mrail/src/mrail_init.c
The FI_SOURCE bit is added to the hints when getting information from the
core providers. If the original hints is NULL or with empty caps, the
modified hints would result in the returned fi_info structure having only
FI_SOURCE and secondary capability bits set. This is different from the
default behavior with NULL hints or empty caps.
Fix by calling fi_getinfo() twice, with empty caps passed for the first
call to retrieve the default caps.
> prov/mrail: Properly handle fi_getinfo() with empty hints

- NEWS.md
- configure.ac
- fabtests/configure.ac
- include/windows/config.h
Will be pushed directly once CI validation is confirmed
> v1.9.1: CI testing

- prov/tcp/src/tcpx_progress.c
When a connection is shut-down, the EQ may receive
incorrect events for failed RX entries. This may
cause some bad bugs in the user application because
a single call to fi_shutdown() may generate multiple
EQ events for the same endpoint.
The patch removes the call to tcpx_report_error(), which
incorrectly causes invalid events to be reported in
the EQ. Most significantly, tcpx_report_error() doesn't
protect from reporting multiple FI_SHUTDOWN events
for the same endpoint.
Removing this function is safe because the call to
ep->get_rx_entry[op](ep) (which maps to the functions
tcpx_get_rx_entry_op_*) already does the following
in case the RX entry fails:
1. It generates a CQ event.
2. It cleans the RX entry and reset ep->cur_rx_entry
to NULL. The new assert() enforces this assumption. …
> prov/tcpx: Remove incorrect events reported to EQ

- prov/rxm/src/rxm_conn.c
- prov/rxm/src/rxm_cq.c
- prov/rxm/src/rxm_ep.c
> prov/rxm: code cleanups

- fabtests/common/shared.c
- fabtests/functional/multi_recv.c
- fabtests/test_configs/efa/efa.exclude
- fabtests/test_configs/psm2/psm2.exclude
- prov/shm/src/smr.h
- prov/shm/src/smr_comp.c
- prov/shm/src/smr_ep.c
- prov/shm/src/smr_msg.c
- prov/shm/src/smr_progress.c
+small change removing unused variable
> fabtests/multi_recv, prov/shm: change to better test FI_MULTI_RECV and fix shm FI_MULTI_RECV completion reporting

- prov/efa/src/rxr/rxr_pkt_type_req.c
This patch rearrange rxr_init_req_hdr intto two parts.
The first part set base header.
The second part set optional header.
> prov/efa: refactor rxr_init_req_hdr()

- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_init.c
- prov/efa/src/rxr/rxr_msg.c
- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_entry.h
- prov/efa/src/rxr/rxr_pkt_type_misc.c
- prov/efa/src/rxr/rxr_pkt_type_req.c
- prov/efa/src/rxr/rxr_pkt_type_req.h
- prov/efa/src/rxr/rxr_pkt_type_rts.c
- prov/efa/src/rxr/rxr_read.c
- prov/efa/src/rxr/rxr_read.h
- prov/efa/src/rxr/rxr_rma.c
This PR contains 4 commits:
1. implement emulated write using REQ packet types
2. implement emulated read using REQ packet types.
3. implement the read message protocol.
4. implement the read write protocol.
> prov/efa: Implement more protocols using REQ packet types

- prov/efa/src/rxr/rxr_pkt_type_req.c
> prov/efa: Replace mr access modes

- prov/efa/src/efa.h
- prov/efa/src/efa_av.c
- prov/efa/src/efa_cm.c
- prov/efa/src/efa_ep.c
- prov/efa/src/efa_msg.c
- prov/efa/src/efa_rma.c
- src/common.c
This PR contain 2 commits:
1. prov/efa: assign random Q-Key to EFA ep
2. src/common: update EFA address in ofi_straddr() and ofi_str_to_efa()
> prov/efa: Q Key related changes

- prov/rxm/src/rxm_cq.c
RxM currently only reports errors for a subset of data transfers that
fail.  For others (such as RMA), it reports an incomplete, generic
error.  Improve error reporting.  Note that some transfers types are
still not being reported.  A full update will be needed as a follow on
patch set.
As part of this change, we restructure successful completion reporting,
so that the switch case statements align with the order of the transfer
states.  This helps ensure that all states are covered.
> prov/rxm: Report CQ errors for failed RMA transfers

- man/fi_av_set.3.md
Updates to man page based on feedback from user.
> man/av_set: Add fi_close and clarify init params

- include/ofi_shm.h
- prov/shm/src/smr.h
- prov/shm/src/smr_atomic.c
- prov/shm/src/smr_av.c
- prov/shm/src/smr_ep.c
- prov/shm/src/smr_msg.c
- prov/shm/src/smr_progress.c
- prov/shm/src/smr_rma.c
- Rename smr_ep_entry to smr_rx_entry and add smr_tx_entry
- Properly align cmd data
- Return correct addrlen on av lookup
- Fix incorrect addr passed into the RMA fast path
- Reorganize format functions
- Fix typo
> prov/shm: refactoring and bug fixes

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/Jenkinsfile.daily
- contrib/intel/jenkins/tests.py
Jenkinsfile, Jenkinsfile.daily : added code to invoke test scripts for shm prov
cherry-picked from commit cb6bafde.
> [v1.9.x] Added shm prov testing.

- contrib/intel/jenkins/Jenkinsfile
Jenkinsfile: changed  stage name eth-udp-dbg to eth-udp-shm-dbg.
> Jenkins-CI: updated Stage Name for shm prov

- prov/efa/src/rxr/rxr_pkt_type_req.c
This patch fix various issues with error handling in rxr_pkt_type_req.c,
icluding:
1. rxr_pkt_proc_msgrtm() and rxr_pkt_proc_tagrtm() did not
write EQ or CQ error entry when error happens
2. rxr_pkt_handle_eager/long_rtw/rxr_recv() did not release
all the resources when error happens.
> prov/efa: Fix issues with error handling in rxr_pkt_type_req.c

- prov/efa/src/rxr/rxr_msg.c
- prov/efa/src/rxr/rxr_pkt_type_req.c
Change the match logic to ignore addresses when FI_DIRECTED_RECV is not
set for the endpoint. Some of the tests that do not require this
capability started to fail when this logic was dropped.
> prov/efa: re-add check for FI_DIRECTED_RECV

- prov/util/src/util_coll.c
three commits to fix three bugs in fi_collective
> bug fixes for fi_collective

- prov/efa/src/rxr/rxr_init.c
This commit conditionally disables the use of the shm provider in EFA,
if an application explicitly provides a hint that it does not require
local communication.
> prov/efa: Use shm provider only when local communication is needed

- configure.ac
- fabtests/configure.ac
- include/windows/config.h
After CI completes, will be pushed directly.
> v1.10.0rc2

- prov/efa/src/efa_av.c
Before this fix, we go to efa_av_close when
shm's av_open fails and dgram's av->conn_table
calloc fails. This is not correct, because efa's
av has not been opened successfully.
In this patch instead, we close the resources which
are opened/initialized till the failure point
(shm_av, ofi_util_av, efa_av).
> prov/efa: Fix error handling when av open fails

- NEWS.md
> NEWS: Update release notes for 1.10

- prov/efa/src/rxr/rxr_init.c
MPICH uses
info->ep_attr->max_order_raw_size,
info->ep_attr->max_order_war_size,
info->ep_attr->max_order_waw_size,
to determine whether it should use provider's atomic. This patch
set these values to max_atomic_size, so that atomic will be used
by MPICH
> prov/efa: set info->ep_attr->max_raw/war/waw_size for atomic

- prov/gni/include/gnix.h
to keep the Open MPI OFI MTL happy with GNI provider.
> GNI: add local/remote comm

- NEWS.md
> prov/efa: 1.10 release notes for EFA provider

- prov/verbs/src/verbs_info.c
There are two reasons why this is required.
1) rdma_cm required by verbs provider is not supported
by efa device, even if verbs is selected
2) Since verbs is registered before efa, during registration
of verbs provider rdma_get_devices() is called which leaves the
devices open, leading to efa not being registered on some ranks.
> prov/verbs: Add check for efa_devices

- AUTHORS
- configure.ac
- fabtests/configure.ac
- include/windows/config.h
> v1.10.0rc3

- configure.ac
- fabtests/configure.ac
- include/windows/config.h
> fabric: Update release number to 1.11.0a1

- src/fabric.c
Library is caught from LD_LIBRARY_PATH if prov libs built as fi<provname>-fi.so
1) Why is UDP provider spelled in capital letters?
2) Why is psm2 provider built in fipsmx2-fi.so dl library? The symbol "x" in "psmx2" does not comply with the general rules for generating a dl library name.
> src/fabric.c: Add loading of DL providers by their names

- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_msg.c
This PR contain 2 commits:
1. use tx_attr->op_flags as the default flag when calling rxr_msg_generic_send()
2. fix the logic of writing completion entry in rxr_cq_write_tx_completion() and rxr_cq_write_rx_completion()
> prov/efa: fix bug in handling FI_SELECTIVE_COMPLETION

- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_msg.c
This PR contain 2 commits:
use tx_attr->op_flags as the default flag when calling rxr_msg_generic_send()
fix the logic of writing completion entry in rxr_cq_write_tx_completion() and rxr_cq_write_rx_completion()
This is https://github.com/ofiwg/libfabric/pull/5889 but targeting 1.10.x branch
> [1.10.x] prov/efa: fix a bug in handling FI_SELECTIVE_COMPLETION

- include/ofi_signal.h
fd_signal_set() and fd_signal_reset() have an optimization
to avoid writing more than needed to the signal socket.
Now this optimization is done with counters (wcnt and rcnt)
and if the user of fd_signal (for example prov/tcp) does
not protect the call chain with its own locks a
write leak might come up filling up the socket.
Prov/tcp uses struct fd_signal through util_wait, but it
is also not easily possible to use the util_wait_fd
lock to protect struct fd_signal counters, as a lock ordering
issue comes up
Thread 14 (Thread 0x7fbaae42a700 (LWP 2623488)):
==> tries to aquire ep->lock
tcpx_try_func           at prov/tcp/src/tcpx_progress.c:657
==> holds wait_fd->lock
in util_wait_fd_try     at prov/util/src/util_wait.c:249
ofi_trywait             at prov/util/src/util_wait.c:70
fi_trywait …
> ofi_signal Add a lock to protect wcnt and rcnt

- prov/efa/src/rxr/rxr_pkt_cmd.c
Currently rxr_pkt_handle_recv_completion() will call
rxr_pkt_proc_common_req_hdr(),
if the received packet is an REQ packet.
This is wrong because the received REQ packet might be
from a different version of EFA provider, and the provider
cannot process the header.
This patch handle this case by printing a warning and
calling rxr_cq_handle_cq_error(), the same way we handle
an invalid control packet.
> prov/efa: fix a bug in rxr_pkt_handle_recv_completion()

- prov/efa/src/rxr/rxr_pkt_cmd.c
Currently rxr_pkt_handle_recv_completion() will call
rxr_pkt_proc_common_req_hdr(),
if the received packet is an REQ packet.
This is wrong because the received REQ packet might be
from a different version of EFA provider, and the provider
cannot process the header.
This patch handle this case by printing a warning and
calling rxr_cq_handle_cq_error(), the same way we handle
an invalid control packet.
> [v1.10.x] prov/efa: fix a bug in rxr_pkt_handle_recv_completion()

- .gitignore
- fabtests/configure.ac
> fabtests configure needs to use the "pax" tar format

- prov/sockets/src/sock_ep.c
If peer with restart, it possibly being disconnect but not detected yet
when communicate with the peer. That leads to lookup invalid connection
and further cause failure in sock_pe_progress_tx_entry().
For example two nodes A and B, A send RPC request to B, and B will send
reply to A. But A only insert B's address to AV at first time and reuse
it later. After several RPC round trip, B restart executing with the same
IP+port. Then A cannot send RPC request to B any more because it always use
the cached fi_addr and cached connection information.
Another example - there are 3 nodes -- client_A and server_A, server_B, with
the usage steps as below -
1) client_A sends RPC+bulk_handle to server_A,
2) server_A finds that both server_A and server_B need to involve, so
forwards the RPC+BULK to …
> prov/sockets: check connection's valid in sock_ep_lookup_conn

- prov/efa/src/efa_av.c
- prov/efa/src/efa_domain.c
- prov/efa/src/rxr/rxr_domain.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_init.c
fix memory leaks and memory access violations
> prov/efa: fix multiple bugs

- prov/efa/src/efa_verbs/efa_cmd.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_init.c
This PR fix memory leaks in EFA provider v1.9.x
> [v1.9.x] prov/efa: fix efa mem leaks

- prov/rxm/src/rxm_atomic.c
- prov/rxm/src/rxm_cq.c
- prov/util/src/util_atomic.c
- prov/verbs/src/fi_verbs.h
- prov/verbs/src/ofi_verbs_priv.h
- prov/verbs/src/verbs_cm_xrc.c
- prov/verbs/src/verbs_domain_xrc.c
- prov/verbs/src/verbs_ep.c
- prov/verbs/src/verbs_eq.c
Just adding missing System Fabric Works, Inc. copyright statements. Thanks.
> prov/verbs,rxm: Add a few missing copyright statements

- configure.ac
- include/ofi_hmem.h
- src/fabric.c
- src/hmem.c
- src/hmem_cuda.c
See https://github.com/ofiwg/libfabric/issues/5928.
> Dlopen CUDA runtime proposal

- prov/efa/src/efa_mr.c
This PR contain 2 MR related patches.
> prov/efa: one mr related patches

- prov/tcp/src/tcpx_ep.c
Lifbabric doesn't report the correct error code to the
caller if fi_passive_ep() fails.
For example, in the case where the port is already bound
to another process, fi_passive_ep() would return -1 to
the application. It's because the value returned by bind()
is forwarded to the caller instead of the errno value.
(on error, bind() returns -1, and errno is set appropriately).
The patch also fixes an issue where fi_dupinfo() may fail
but fi_passive_ep() would return FI_SUCCESS.
> prov/tcpx: Fix wrong error handling in fi_passive_ep()

- fabtests/unit/mr_test.c
> fabtest: Initialize MR attributes to zero.

- prov/efa/src/efa_mr.c
This will call ofi_mr_cache_flush() when the cached MR entry count
is multiple of 512, this improve the performace of some applications.
> [v1.10.x] prov/efa: fix a MR related issue

- prov/efa/src/efa_fabric.c
1.  replace ibv_fork_init() with aborting at fork()
2. do not unset RDMAV_HUGEPAGES_SAFE if user has it
> prov/efa: two patches related to fork support

- prov/efa/src/efa_fabric.c
same as https://github.com/ofiwg/libfabric/pull/5993
> [v1.10.x] prov/efa: two patches related to fork support

- contrib/cray/Jenkinsfile.verbs
Libfabric is now configured and built with CUDA support.
> contrib/cray: Update Jenkinsfile for CUDA support

- include/ofi.h
- include/ofi_mem.h
- prov/efa/src/efa_fabric.c
- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_ep.c
- prov/rxm/src/rxm_init.c
- prov/util/src/util_attr.c
- prov/util/src/util_av.c
- prov/util/src/util_buf.c
- prov/util/src/util_mem_monitor.c
- prov/verbs/src/verbs_info.c
- src/common.c
- src/fabric.c
A couple more bugfix backports, this time for the common code (and 1 EFA fid_nic fix which was relying on the vrb_speed method).
> [v1.10.x] Backport of some common code fixes for the v1.10.x branch

- include/ofi_hmem.h
- include/rdma/fabric.h
- man/fi_fabric.3.md
- prov/efa/src/rxr/rxr_init.c
- prov/verbs/src/fi_verbs.c
- src/fabric.c
- src/fi_tostr.c
- src/hmem.c
Initialize HMEM functions for use by providers.
> Ofi hmem init

- src/fi_tostr.c
Signed-off-by: Zach Tiffany <zachary.tiffany@hpe.com>
> List FI_MATCH_COMPLETE in fi_info utility output

- prov/efa/src/rxr/rxr_pkt_type_data.c
This patch resets the `tx_entry->iov_index` and `tx_entry->iov_offset`
in `rxr_pkt_send_data_desc` if `rxr_pkt_entry_sendv` fails.
We do this because the while loop that constructs the 
iov is going to update 
the `tx_entry->iov_index` and `tx_entry->iov_offset`.
If the send fails, we need to reset them.
Otherwise when we resend the packet,
loop conditions will not be satisfied and
thus iovs cannot be constructed.
> Reset tx_entry iov on Data Send Failure

- prov/mrail/src/mrail_av.c
- prov/mrail/src/mrail_cq.c
- prov/psm2/src/psmx2_init.c
- prov/rxd/src/rxd_cq.c
- prov/rxm/src/rxm_av.c
- prov/rxm/src/rxm_cq.c
- prov/rxm/src/rxm_rma.c
- prov/shm/src/smr_av.c
- prov/shm/src/smr_progress.c
- prov/sockets/src/sock_ep.c
- prov/util/src/util_av.c
- prov/util/src/util_coll.c
- prov/util/src/util_shm.c
- prov/verbs/src/verbs_cm.c
- prov/verbs/src/verbs_cm_xrc.c
- prov/verbs/src/verbs_domain_xrc.c
- prov/verbs/src/verbs_ep.c
- prov/verbs/src/verbs_eq.c
- prov/verbs/src/verbs_info.c
- src/common.c
- src/fabric.c
- util/pingpong.c
Mostly adds bound checks, and editor automatically removed some unneeded white space when saving.
> minor provider updates to resolve klocworks issues

- contrib/cray/Jenkinsfile.verbs
> contrib/cray: Update Jenkinsfile for ROCR support

- include/rdma/fi_domain.h
Align query_collective op with rest of ops.
> fi_domain: Fix indentation

- src/fi_tostr.c
> fi_tostr: Add FI_HMEM_ROCR support

- prov/tcp/src/tcpx_progress.c
A few changes stemming from coverity issues about possible buffer overruns and untrusted data received from the network.
The receive side message handling needs more work.  The control flow is confusing, with new message initialization occurring in several places throughout the code and no clear state tracking.  This provides a start at simplifying that path, but more work is needed.  This should resolve the open coverity issues against the provider, however.
> prov/tcp: Cleanups and error checks receiving data on socket

- prov/efa/src/rxr/rxr_msg.c
- prov/efa/src/rxr/rxr_pkt_type.h
- prov/efa/src/rxr/rxr_pkt_type_data.c
- prov/efa/src/rxr/rxr_pkt_type_misc.c
- prov/efa/src/rxr/rxr_pkt_type_req.c
- prov/efa/src/rxr/rxr_rma.c
There are a few more fixes I am tracking, but these are the ones that have already landed in master.
> [v1.10.x] prov/efa: Cherry-pick of fixes for 1.10.x

- AUTHORS
- Makefile.am
- configure.ac
- fabtests/configure.ac
- include/rdma/fabric.h
- include/windows/config.h
CI validation.  Will be pushed directly when ready.
> v1.11.0rc1

- prov/efa/src/efa_fabric.c
Rather than relying on the CUDA runtime availability and the build
configuration, this commit uses the driver's sysfs device file to
determine the need for FI_MR_HMEM.
> prov/efa: Use sysfs to detect driver's ability to handle CUDA buffers

- prov/efa/src/efa_fabric.c
Currently, the efa provider will register atfork callback function and
set the environment variable RDMAV_HUGEPAGES_SAFE in efa_fabric().
The intention is that if an application needs fork support, it should
set the environment variable IBV_FORK_SAFE or RDMAV_FORK_SAFE to enable
it. Because EFA provider uses huge page, the provider should set
environment variable RDMAV_HUGEPAGES_SAFE, so when the fork support
was enabled, it also support huge page.
There is an issue with current implementation: RDMAV_HUGEPAGES_SAFE
was set too late.
For it to be effective, RDMAV_HUGEPAGE_SAFE must be set before the function
ibv_fork_init() was called. However, the EFA provider call ibv_fork_init()
during the initialization of the provider, the call stack is: …
> prov/efa: move rdma-core related initialization to init_lower_efa_prov()

- prov/efa/src/efa_fabric.c
> prov/efa: Fix up compilation warning about unused symbol.

- prov/efa/src/rxr/rxr_msg.c
The recent commit 73a80b1cd introduce a change that will use read
message protocol for all GPU memory regardless the message size.
That commit has an issue: read message protocol is an extra feature
therefore the receiver does not necessary support it.
This patch fixed the issue by calling rxr_pkt_wait_handshake() before
using read message protocol. The handshake packet contains the capability
bit of the receiver, so the sender can use it to be sure whether receiver
support read message protocol.
If the receiver does not support read message protocol, the patch will
return -FI_EOPNOTSUPP, and not proceed.
> prov/efa: Wait handshake before using read messge protocol on GPU memory

- prov/efa/src/efa_cq.c
- prov/efa/src/efa_fabric.c
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_attr.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_init.c
- prov/efa/src/rxr/rxr_msg.c
- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_entry.c
- prov/efa/src/rxr/rxr_pkt_entry.h
- prov/efa/src/rxr/rxr_pkt_type_req.c
- prov/efa/src/rxr/rxr_pkt_type_req.h
This PR can not be merged till the fixed up delivery complete PR gets in (I expect CI to fail too). Sending it out for review nonetheless.
> prov/efa: msg_prefix and other changes

- src/hmem_rocr.c
Treat HSA_STATUS_ERROR_OUT_OF_RESOURCES as ROCR not being supported
instead of a ROCR error. This ROCR error is typically returned when no
supported devices are found.
> hmem: Update ROCR HMEM init

- src/fi_tostr.c
> fi_tostr: Add FI_HMEM_ZE support

- AUTHORS
- NEWS.md
- configure.ac
- fabtests/configure.ac
- include/windows/config.h
> v1.11.0rc2 -- for CI

- fabtests/common/hmem_ze.c
- src/hmem_ze.c
Level Zero v1.0 was just released - update to new API which is based on context handles instead of driver handles.
Level Zero is not backwards compatible
> src/hmem_ze, fabtests/hmem_ze: update to L0 v1.0 API

- include/ofi_mr.h
> core/mr_cache: Update OFI_HMEM_MAX for ze devices

- prov/psm2/src/psmx2.h
- prov/psm2/src/psmx2_av.c
The function psmx2_epid_to_epaddr() is the core for dynamic connection
setup. Previous it returned error code to the caller when connection
failed. However, the call sites simply used assert() to catch the
errors because trying to deliver the errors further to upper layers
would introduce extra overhead to the critical path of communication.
Since assert() is optimized out for non-debug build, this means the
errors are unhandled in production code.
Change psm2_epid_to_epaddr() to abort on connection errors. The log
message is enhanced with suggestion for handling connection timeout.
As the side effect, the call sites become less cluttered.
> prov/psm2: Treat dynamic connection errors as fatal

- src/hmem_ze.c
> src/hmem_ze: remove undefined goto

- prov/efa/src/rxr/rxr_pkt_cmd.c
Currently, receiver will write an eq error when it received
a REQ packet it cannot support. This patch make the receiver
to send a handshake back and ignore the unsupported REQ packet,
sender can act accordingly when it received handshake.
> prov/efa: ignore unsupported req packets instead write error

- NEWS.md
Also add a missing update for 1.10.0.
> NEWS: Update psm2 provider notes for 1.11.0

- NEWS.md
> News.md: Updated news for prov/rxd for 1.11.

- NEWS.md
> NEWS.md: add EFA provider changes for 1.11.0

- include/ofi_util.h
- prov/tcp/src/tcpx.h
- prov/tcp/src/tcpx_conn_mgr.c
- prov/tcp/src/tcpx_ep.c
- prov/tcp/src/tcpx_progress.c
- prov/util/src/util_wait.c
> prov/tcp: Rework of CM state machine to fix possible deadlock

- contrib/cray/Jenkinsfile.verbs
contrib/cray: Add building of LTU and SFT
Signed-off-by: Anthony Zinger <anthony.zinger@hpe.com>
> contrib/cray: Add building of LTU and SFT

- man/fi_efa.7.md
Change wording for memory registration and update man page to reflect
recent feature changes.
> man: update fi_efa man page

- fabtests/functional/recv_cancel.c
Also fixes line lengths and updates copyright
> fabtests/recv_cancel: repost cancelled recv to match posted send

- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_pkt_entry.c
- prov/efa/src/rxr/rxr_pkt_type_req.c
This PR contain 4 commits that are needed for an upcoming change that use fi_read to copy data into GPU buffer.
> prov/efa: four commits

- include/ofi_shm.h
- prov/shm/src/smr.h
- prov/shm/src/smr_atomic.c
- prov/shm/src/smr_av.c
- prov/shm/src/smr_ep.c
- prov/shm/src/smr_msg.c
- prov/shm/src/smr_progress.c
- prov/shm/src/smr_rma.c
- prov/util/src/util_shm.c
- src/tree.c
> prov/shm: fix shm mapping/addressing issues

- prov/gni/src/gnix_mbox_allocator.c
Signed-off-by: Trevor Hendricks <trevorhe@amazon.com>
> prov/gni: Replace sprintf with size checked snprintf

- prov/rxm/src/rxm_ep.c
Registering all HMEM bounce buffers with HMEM can lead to decreased
memcpy times.
> prov/rxm: Register bounce buffers with HMEM
