prov/sockets/src/sock_ep.c

The prefix handling code assumes we're running on a little
endian system.  Support BE systems as well.
Move the call inside HAVE_GETIFADDRS check, since it is
only called from one location that's wrapped by that check.

prov/socket: Fix sock_get_prefix_len to handle BE systems

---

prov/util/src/util_cntr.c
prov/util/src/util_cq.c

This patch addresses problem where the `util_cq` and `util_cntr` objects aren't freed.
The `util_cq_close` and `util_cntr_close` functions are set as a function pointer to `fi_close()` function.
This solution fixes the problem in the same meaner as it's already done for the `util_eq`

common/cntr,cq: Add missed memory release in the util_cntr|cq_close

---

prov/verbs/src/verbs_info.c

TX and RX iov_limits must be 1 for RDM endpoints. fi_ibv_alloc_info() would only set iov_limit for the TX side, but not for RX. Add the missing changes.
Also minor cleanup in fi_ibv_alloc_info.

prov/verbs: set rx iov_limit to 1 for RDM endpoints

---

include/fi_mem.h
include/fi_shm.h
man/fi_tagged.3.md
prov/shm/src/smr_ep.c

- smr_freestack mirrors original freestack implementation but with added base_addr of owning process to translate entry pointers from one address space to the other when pushing and popping.
- update shm provider to use smr_freestack instead of original freestack.
- also including an unrelated minor man page update.

include/fi_mem: add smr_freestack implementation for use with shared memory

---

prov/shm/configure.m4

This fixes problem by adding the separate variable `cma_support` for the checking CMA support.
The previous solution reports that `process_vm_readv` is unsupported, but the next check assign 1 to `shm_happy` variable if the shm_open was found in the `librt` library. 
```
configure: *** Configuring shm provider
checking for process_vm_readv... no
checking for shm_open... (cached) no
checking sys/mman.h usability... yes
checking sys/mman.h presence... yes
checking for sys/mman.h... yes
looking for library without search path
checking for shm_open in -lrt... yes
configure: shm provider: disabled
```
This check disables SHM provider, if `process_vm_readv` isn't found. Is it expected behavior? Or Is there some fallback from the `process_vm_readv` to the some analog? If no, seems this patch …

prov/shm: Separate checks for process_vm_readv and shm_open

---

include/fi_util.h
prov/util/src/util_main.c
src/common.c
src/fabric.c
src/windows/osd.c

The problem is the UDP provider crashes on Windows.
This appears because the global `pthread_mutex_t` lock in the `util_main.c` file is initialized by `PTHREAD_MUTEX_INITIALIZER` that is mapped to NULL for Windows. There is no static variant to initialize `CRITICAL_SECTION` (`pthread_mutex_t` is mapped to this type on Windows) object. The one way is to call `InitializeCriticalSection` for this object.
The main idea of this patch is initialize this mutex only once. It can be done by `InitOnceExecuteOnce` function during loading of the DLL library. This patch fixes this problem in the same way as it's done for the `ofi_ini_lock` from the `fabric.c` file. These two locks are combined into one instance of the `ofi_common_locks` structure.
Signed-off-by: Dmitry Gladkov …

common: Fix uninitialized global lock (appears on Windows)

---

include/unix/osd.h
include/windows/osd.h
prov/udp/src/udpx_ep.c
src/windows/osd.c
util/pingpong.c

The current limit of the addresses is 64 bytes that is too short for the MLX provider (UCX wrapper) - we're going to revive this provider.
This patch strives to avoid this limit by requesting the needed length of memory space that is needed for the address (`fi_getname` with the passed length = 0). After that the needed buffer is dynamically allocated and passes to the `fi_getname` again to retrieve the address.
Only UDP wasn't compliant with expected behavior. The UDP `fi_getname` has been aligned with correct behavior in this patch

 pingpong: Add support of large addresses

---

prov/rxm/src/rxm_ep.c

This patch addresses problem where RxM/sockets stacks doesn't work.
The `fi_getname` of socket provider checks in which time was this function is called. For the passive EP it should be after `fi_listen`/`fi_setname`.
The RxM provider allocates CMAP during binding to the RxM's AV (I mean the place of code in the RxM's `fi_ep_bind`) - here fi_getname of the sockets provider is failing.
The `fi_listen` for the MSG passive endpoints  is called during calling of the `fi_enable` for RxM's EP.
This patch fixes it by replacing allocation cmap from binding (AV to EP) stage to the enabling of the EP stage.

prov/rxm: fi_getname of the prov/sockets MSG EP fails

---

prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_ep.c

This patch fixes resource leak if the `fi_getname` for an underlying MSG EP fails:
```
$ FI_LOG_LEVEL=warn I_MPI_OFI_PROVIDER="sockets;ofi_rxm" I_MPI_FABRICS=ofi mpirun -n 2 –ppn 1 manyget
[0] MPI startup(): ofi fabric is not available and fallback fabric is not enabled
libfabric:ofi_rxm:ep_ctrl:rxm_conn_cmap_alloc():380<warn> Unable to fi_getname on msg_ep
libfabric:ofi_rxm:av:ofi_av_close():438<warn> AV is busy
[1] MPI startup(): ofi fabric is not available and fallback fabric is not enabled
libfabric:ofi_rxm:ep_ctrl:rxm_conn_cmap_alloc():380<warn> Unable to fi_getname on msg_ep
libfabric:ofi_rxm:av:ofi_av_close():438<warn> AV is busy
```
After applying this patch:
```
$ FI_LOG_LEVEL=warn I_MPI_OFI_PROVIDER="sockets;ofi_rxm" I_MPI_FABRICS=ofi mpirun -n 2 –ppn 1 manyget …
```

prov/rxm: Fix resource leak

---

include/fi_util.h
prov/rxm/src/rxm_attr.c
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_init.c
prov/util/src/util_attr.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_info.c
prov/verbs/src/verbs_msg_ep.c

The following series reduces the number of failures seen running the ofi_rxm provider over sockets.  It corrects issues with fi_getinfo_test, and rdm EP tests using writedata.
With these changes, the ofi_rxm;sockets provider only fails with fi_rdm_tagged_peek test.

util/rxm: Fixes to rxm provider when used over sockets

---

.appveyor.yml
.travis.yml

Ensure that we're testing with the fabtests v1.5.x codebase, rather than upstream master.

travis/appveyor: Use fabtests branch v1.5.x

---

prov/gni/test/api.c
prov/gni/test/rdm_multi_recv.c

While debate proceeds on issues #3441 and #3443 and friends.
disable GNI provider unit tests that are caught up in
the discussion to reduce noisiness.
This commit can be reverted once the situation has settled
down.

prov/gni: disable failing GNI unit tests

---

prov/gni/src/gnix_rma.c

There was a race condition in the rma get path
for unaligned source buffers.  There was an
atomic dec followed by an atomic read.  This
leads to a race condition when using the GNI
provider in multi-threaded conditions.
upstream merge of ofi-cray/libfabric-cray#1418
(cherry picked from commit ofi-cray/libfabric-cray@778825a043c469e8e75677309c38a5d188bbdb44)

prov/gni: plug race condition in rma get path

---

prov/verbs/src/ep_dgram/verbs_dgram_ep.c
prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm.c

EP/RDM and EP/DGRAM has some non-implemented functions.
Just to avoid possible crash, set them to to the non-operational stub functions

prov/verbs: Fix possbile crash by accessing not set EP-ops functions

---

prov/usnic/src/usdf_ep_dgram.c
prov/usnic/src/usdf_ep_msg.c
prov/usnic/src/usdf_ep_rdm.c

gcc 6.3.0 was complaining about no return value
when compiling parts of usnic provider.

prov/usnic: swat a compiler warning

---

prov/verbs/src/ep_rdm/verbs_ep_rdm.c
prov/verbs/src/ep_rdm/verbs_rdm.h
prov/verbs/src/ep_rdm/verbs_rdm_cm.c
prov/verbs/src/ep_rdm/verbs_rdm_msg.c
prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm.c
prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm_states.c

This patch is prepared to address the following:
- Utilize special macro instead of just casting
- verbs/RDM sets `IBV_SEND_SIGNALED` flag for each send operation. Remove this by setting `sq_sig_all` attribute during QP allocation.
- The QP is created twice for EP that has passive CM role.
The first one is done during processing `RDMA_CM_EVENT_ADDR_RESOLVED` CM event
The second one is done during processing connection request (`RDMA_CM_EVENT_CONNECT_REQUEST`)

prov/verbs: Some cleanups for verbs/RDM

---

prov/verbs/src/ep_rdm/verbs_rdm_cm.c

fi_ibv_rdm_process_connect_request() will call
fi_ibv_rdm_conn_cleanup() on its error path, and sometimes the QP
hasn't been created. This leads to a NULL QP dereference in
ibv_destroy_qp() which crashes the process. Ensure that the QP
actually exists in fi_ibv_rdm_conn_cleanup() before destroying it.
Signed-off-by: Frank Zago <fzago@cray.com>

prov/verbs: QP may not have been created in fi_ibv_rdm_conn_cleanup()

---

prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm.c

When a wr completes in error, fi_ibv_rdm_tagged_poll_recv() will
perform extra actions on all the work completions is got. However the
number of valid completions in the array is not "wc_count", but
"ret". Fix the for loop.
Same error with fi_ibv_rdm_tagged_poll_send().
Signed-off-by: Frank Zago <fzago@cray.com>

prov/verbs: fix possible completion array overrun

---

prov/verbs/src/ep_rdm/verbs_rdm_cm.c
prov/verbs/src/fi_verbs.c

Some MPICH collective tests (and not only these tests) are failed due to data corruption on MlxOFED.
When `IBV_EXP_ACCESS_RELAXED` isn't set the ibv_dereg_mr doesn't do lazy deregistration of the MR (it's internally handled by libmlx5) and there are no problems, but it leads to poor bandwidth for RNDV messaging.
The ODP is disabled by default for now to avoid data corruption. The problem is seen even if #2496 is used, i.e. there are no regressions on the master code.
The 1.5, 1.5.1 are impacted and there are failures when using release branch. We need to cherry-pick this w/a to the v1.5.x branch.
Seems it's related to:
```
int mlx5_free_pd(struct ibv_pd *pd)
{
struct mlx5_pd *mpd = to_mpd(pd);
int ret;
/* TODO: Better handling of destruction failure due to resources
* opened. At the …
```

prov/verbs: Disable ODP by default

---

prov/verbs/src/ep_rdm/verbs_rdm.h
prov/verbs/src/ep_rdm/verbs_rdm_cm.c

If rdma_accept fail, the CM params private data will not be freed.
Instead of adding another error handling path, refactor the code by
having the private data in a structure on the stack. This change
fixes the leak and allows to simplify the pack and unpack code.

prov/verbs: fix possible leak in fi_ibv_rdm_process_connect_request

---

prov/sockets/include/sock.h

tag field is not used for send. Data field is already accounted outside of this structure in sock_ep_sendmsg. So removing tag and data fields from the the structure as they are using up space in ring buffer for no reason.

prov/sockets optimization of sock_op_send structure

---

include/fi_shm.h
prov/shm/src/smr.h
prov/shm/src/smr_attr.c
prov/shm/src/smr_ep.c

- split rxq into two recv_queues, for regular msg and tagged recvs
- add unexpected queue to buffer commands with unmatched tag
- use common endpoint recv freestack for all receives
- make generic functions for msg and tagged sends and recvs
- also including patch to fix asserts from < to <= (IOV_LIMIT and INJECT_SIZE)

prov/shm: add tagged messaging

---

Makefile.am

Invoke the perl interpreter directly from PATH instead of relying on
hardcoded shebang.  This improves support for sandboxed build
environments.
Signed-off-by: Lisanna Dettwyler <lisanna.dettwyler@intel.com>

Invoke perl interpreter from PATH

---

prov/util/src/util_attr.c
prov/verbs/src/verbs_eq.c
prov/verbs/src/verbs_info.c

- prov/verbs: Don't throw error if default values are > supported by hardware
- prov/util: Add check for shared context counts
- prov/verbs: ACK CM event on error path

prov/verbs, util: getinfo updates + bug fixes

---

prov/verbs/src/ep_rdm/verbs_ep_rdm.c

From time to time some MPI ranks (MPICH/CH4 device) hang in `fi_close` of a EP.
The `FI_VERBS_CONN_ESTABLISHED` -> `FI_VERBS_CONN_CLOSED` (conn_closed is received from remote side) leads to  this situation. We need to end up looping in case of `FI_VERBS_CONN_CLOSED`.

prov/verbs: Fix hang in the MPI_Finalize during destroying of some EPs

---

Makefile.am

Initialize EXTRA_DIST to nothing prior to invoking the Makefile includes
from each provider.  This allows providers to append files they want to
include in the dist with "+=".

Initialize EXTRA_DIST

---

prov/verbs/src/ep_rdm/verbs_av_ep_rdm.c
prov/verbs/src/ep_rdm/verbs_cq_ep_rdm.c
prov/verbs/src/ep_rdm/verbs_ep_rdm.c
prov/verbs/src/ep_rdm/verbs_queuing.h
prov/verbs/src/ep_rdm/verbs_rdm.h
prov/verbs/src/ep_rdm/verbs_rdm_msg.c
prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm.c
prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm_states.c
prov/verbs/src/ep_rdm/verbs_utils.c
prov/verbs/src/verbs_rma.c

- The connection is established in the `fi_ibv_rdm_check_connection` that checks state of the connections.
Simplifies the `fi_ibv_rdm_check_connection` function to just check the conn->state and no more actions.
The connection establishment is moved to the functions that allocates an Connection entry for the specified EP. It looks more natural.
- Some code cleanups:
- Removes extra brackets
- Introduce new filed to the EP - `iov_per_rndv_thr` to avoid each time calculation of the available count of the I/O vectors.
- Use the utility `ofi_total_iov_len` function instead of self-implemented `for (...)`

prov/verbs: Some code cleanups and simplifications

---

include/fi_util.h
prov/gni/src/gnix_fabric.c
prov/netdir/src/netdir_init.c
prov/rxm/src/rxm.h
prov/rxm/src/rxm_attr.c
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_init.c
prov/sockets/src/sock_dom.c
prov/usnic/src/usdf_domain.c
prov/util/src/util_attr.c

Running an updated fi_getinfo_test to validate mr_mode, the
ofi_rxm;sockets provider fails.  The core issue is that the
mr_mode checks and subsequent alterations fail to handle
applications that request FI_MR_BASIC or FI_MR_SCALABLE when
running with api version 1.5 or new.
To fix this, we restructure the mr_mode checks in an attempt
to simplify things.  Providers now indicate if they support
FI_MR_BASIC and FI_MR_SCALABLE by explicitly setting those
mr_mode bits.  Previously, FI_MR_SCALABLE was assumed based
on no other bits being set.

prov/util: Restructure and fix mr_mode checks

---

prov/sockets/src/sock_cntr.c

prov/sockets: Fix an incorrect default filling of the cntr attr

---

prov/verbs/src/verbs_info.c

Most iWARP HW don't support immediate data.
@gladkovdmitry17 Can you verify if this looks good for RDM and DGRAM EP types? If not I can add a check for the same.

prov/verbs: Set CQ data size to zero for iWARP

---

prov/verbs/src/verbs_info.c

Most iWARP HW don't support immediate data.

prov/verbs: [cherry-picked] Set CQ data size to zero for iWARP

---

prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_av.c
prov/psm2/src/psmx2_domain.c

The address information of scalable endpoints is expanded to allow
connection be established between any pair of contexts from two
scalable endpoints. This eliminates the previous limitation of
only supporting pair-wise communication between scalable endpoints.
There is still one limitation remaining: communication between a
regular endpoint and a scalable endpoint is not supported.

prov/psm2: Allow all-to-all communication between SEP contexts

---

util/pingpong.c

Per @shefty's famous ["Yeah, I pretty much hate this test at this point"](https://github.com/ofiwg/libfabric/issues/2307#issuecomment-250322720) comment, strip down fi_pingpong to be what @jsquyres and @shefty decided on a phone call after that comment.  😄 
This is a branch I started a long time ago to address @shefty's concerns, and it is not complete.  I'm filing this here so that @bturrubiates and I can collaborate to actually finish the work.
I *believe* that the last thing that actually needs to be done is the biggest: remove all use of TCP sockets from the code.  Unfortunately, it's been so long since I worked on this that I lost my notes and don't remember exactly -- @shefty does that sound right to you?  Or were there other things?

Update / strip down fi_pingpong

---

prov/psm/src/psmx_init.c
prov/psm2/src/psmx2_init.c

According to latest API update, providers should preserve the FI_MR_SCALABLE
mr_mode bit passed in from the hints if the mode is supported, even though
setting mr_mode to 0 would indicate the same support level.

prov/psm,psm2: Preserve FI_MR_SCALABLE mode bit in fi_getinfo

---

util/pingpong.c

This fixes a build error not checking return value from asprintf

pingpong: Remove call to asprintf

---

prov/udp/src/udpx_domain.c
prov/util/src/util_domain.c

ofi_domain_init() was internally freeing the caller's memory on error and
most of the providers that use this function were also freeing the memory on
error. This commit removes the free from ofi_domain_init() and lets the
caller be responsible for freeing the memory they own.
Fixes #3511
Signed-off-by: Erik Paulson <erik.r.paulson@intel.com>

util: Fix double free issue with ofi_domain_init

---

prov/verbs/src/verbs_info.c

In its commit 7ca357571c950, the rdma-core library changed the types
of global gid subnet_prefix and interface_id from 64 bits ints to big
endians, which introduced a compile warning in libfabric. Convert the
values to host endian, and print them as 64 bits.
Signed-off-by: Frank Zago <fzago@cray.com>

verbs: fix display of global gids

---

include/fi_shm.h
prov/shm/src/smr.h
prov/shm/src/smr_av.c
prov/shm/src/smr_ep.c
prov/util/src/util_shm.c

- Change format of address storage so allow peers to exchange addresses through the shared memory region
- Create specific smr_cmd over ofi_cmd
- Increase msg_id to uint64_t and hold context
- Some renaming
- Fix inconsistent locking order reported by coverity

prov/shm: refactor address mapping and smr_cmd structure + coverity fix

---

prov/verbs/src/fi_verbs.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_cq.c
prov/verbs/src/verbs_msg.c
prov/verbs/src/verbs_msg_ep.c
prov/verbs/src/verbs_srq.c

The intent of the PR is to fix a not serialized access to the EP/SRQ's Work Request pool and list.
Fixes #3389 (Multi-threaded usage)

prov/verbs: Serialize an access to the EP/SRQ's Work Requests pool and list

---

prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_am.c
prov/psm2/src/psmx2_av.c
prov/psm2/src/psmx2_domain.c

A session of a client-server application may have multiple clients
communicating with the same server. If some clients run on the same
node one after another, it is possible that the PSM2 endpoints they
open map to the same physical resource (i.e. with the same epid). In
order to work correctly under such situation, the connection states
associated with the reused epid need to be properly cleaned up at
both the client and the server side. The client side cleanup is done
automatically when the endpoint is closed before exiting. The server
side cleanup, however, requires calling psm2_ep_disconnect() explicitly.
The patch adds an AM based protocol to let all connected peers do the
cleanup when a PSM2 endpoint is about to be closed.

prov/psm2: Allow PSM2 epid be reused within the same session

---

prov/gni/include/gnix_util.h

some code got added that caused compilation
problems for GNI provider.
Fixes #3524

prov/gni: swat issue 3524

---

prov/psm/configure.m4
prov/psm/src/psm_am.h
prov/psm/src/psmx.h
prov/psm/src/psmx_atomic.c
prov/psm/src/psmx_av.c
prov/psm/src/psmx_fabric.c
prov/psm/src/psmx_msg2.c
prov/psm/src/psmx_tagged.c
prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_atomic.c
prov/psm2/src/psmx2_av.c
prov/psm2/src/psmx2_cq.c
prov/psm2/src/psmx2_domain.c
prov/psm2/src/psmx2_fabric.c
prov/psm2/src/psmx2_msg.c
prov/psm2/src/psmx2_rma.c

Replace any occurrence of 8 consequent spaces with a tab unless it
is part of comments.

prov/psm,psm2: Minor coding style clean-up

---

prov/verbs/src/verbs_cq.c

If an user asks to read multiple CQ entries (`FI_CQ_FORMAT_DATA`) at single `fi_cq_(s)read` call, the all entries have an incorrect value of the received length/

prov/verbs: Fix an incorrect CQ entries filling in the verbs/MSG

---

prov/udp/src/udpx_ep.c
prov/verbs/src/ep_rdm/verbs_rdm_msg.c
prov/verbs/src/verbs_rma.c
src/unix/osd.c
util/pingpong.c

Fix some of the warnings when --enable-picky is set. These are mostly a bunch of functions that have no prototypes (found with -Wmissing-prototypes -Wstrict-prototypes) and must be made static.

fix function declarations + minor changes

---

prov/gni/src/gnix_mr_notifier.c

In working with libfabric/GNI provider consumers that
are also being used within a Cray MPI application,
opening a domain would fail owing to Cray kdreg
limitations.  It was not obvious from the output
of FI_LOG_LEVEL warn what was going on in this case.
Improve the warn level output from the part of the
GNI provider which is opening kdreg for use by
its rcache.

prov/gni: use warning level for kdreg open

---

include/fi_list.h
include/rdma/fabric.h
prov/gni/include/gnix_util.h

During outgoing development in the libfabric, the new macro `count_of` was introduced. This macro calculates count of element of any arrays and provides the following compile-time checks:
- The passed parameter `x` is an array (not a just pointer). It is possible due to the dividing by `((size_t)(!(sizeof(x) % sizeof(0[x]))))`.
- The passed parameter `x` isn't an array of C++ objects. It is possible due to the `0[x]` construction.

common: Move useful GNI's list functions to the common code

---

prov/psm2/src/psmx2_atomic.c
prov/psm2/src/psmx2_rma.c

The logic of setting the destination endpoint for self-targeted
RMA/atomic operations didn't take into account scalable endpoint
cases and thus could cause segfault when SEP was used.

prov/psm2: Fix a bug for self-targeted RMA/atomic over SEP

---

prov/verbs/src/ep_rdm/verbs_cq_ep_rdm.c
prov/verbs/src/ep_rdm/verbs_rdm.h
prov/verbs/src/fi_verbs.h

The intent of this patch is to fix possible an invalid memory read/write when user uses not `FI_CQ_FORMAT_TAGGED` CQ format for reading CQ entries (this becaomers a major issue when user reads a bunch of CQ entries, because verbs/RDM writes to a memory of next CQ entry buffer).

prov/verbs: Add support of different CQ formats for the verbs/RDM

---

include/fi_shm.h
prov/shm/src/smr.h
prov/shm/src/smr_av.c
prov/shm/src/smr_ep.c

Report errors on cq:
- pass return value/error to tx_comp and rx_comp
- add error entry to err_list and make available for cq_readerr
Pending command queue:
- limit response ack to msg_id and status, get rid of flags
- add pending command queue to store incomplete commands
- look up pending command by context/msg_id and report flags through pending command
Also includes memory leak fix reported by coverity

prov/shm: add cq errors, add pending command queue,+ coverity fix

---

prov/verbs/src/ep_rdm/verbs_rdm_cm.c
prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm_states.c
prov/verbs/src/verbs_domain.c

iWarp specification requires Remote Write access for an MR that is used as a data sink for a Remote Read as a data sink for a Remote Read.
This patch fixes this problem in the same way as it's done for the `FI_READ` flag

prov/verbs: Fix fi_read over iWarp verbs devices

---

prov/mlx/src/mlx.h
prov/mlx/src/mlx_av.c
prov/mlx/src/mlx_cm.c
prov/mlx/src/mlx_ep.c
prov/mlx/src/mlx_fabric.c
prov/mlx/src/mlx_init.c

Implemented built-in NS support in MLX provider.
MPICH-CH3 usage scenario is covered.

MLX provider: Nameserver support (stage 1/3: MPI-CH3 is covered)

---

prov/gni/src/gnix_mr.c
prov/gni/test/mr.c

This commit changes the behavior of the provider
to ignore the requested key when using basic registration.

prov/gni: Ignore requested key with basic reg

---

prov/gni/src/gnix_mr.c
prov/gni/src/gnix_mr_cache.c

The GNI provider internal rcache had a bug when
trying to compute overlaps of incoming memory
registration requests with existing registrations
in the rcache.
The nature of the problem was such that it was almost
never encountered with OpenSHMEM or MPI applications,
but for Mercury, which was doing consecutive registrations
of buffers within a larger previously allocated virtual
memory range, the bug was hit.
Also add some better debug output for the MR subsys in
the GNI provider.
Thanks to Jerome Soumagne for reporting.
@soumagne

prov/gni: fix a problem with internal rcache

---

prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_rma.c

The intent of this patch is to fix RxM's LMT.
The problem is only reproducible over iWarp devices.
The access flags for the region that is used in the fi_read should be `FI_READ` rather than `FI_WRITE`, because if `FI_READ` is specified for the region it means that the buffer can be used as a target buffer in the fi_read operations.

prov/rxm: Fix a MR access flag for a region that is used in the fi_read

---

prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_init.c

Note: I've pulled in some patches from PR #3523 
- prov/rxm: Fix core provider mr_mode not being passed on to app 
- prov/rxm: Fix incorrect handling of CQ data 
- prov/rxm: Fix a crash when doing RMA over sockets core provider. 
- prov/rxm: Fix incorrect buf size for buf pool and posted recvs 
- prov/rxm: Refactor rma iov match code to fix klockworks issue

prov/rxm: Bug fixes

---

prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_ep.c
prov/psm2/src/psmx2_init.c

prov/psm2: Improve resource counting for Tx/Rx contexts
Keep track of both the number of contexts supported on the system (the "max"
value), and the number of contexts that are available to the application (the
"free" value). Use them at different places where previously only the "free"
value was used.
A few issues have been addressed with this change:
(1) Premature "out of resource" error due to the "free" value being used
as the context allocation limit. The value is updated with each call to
fi_getinfo and can get smaller after some endpoints have been opened.
(2) Insufficient resource allocation could happen for the same reason when
the "free" value is used to determine the allocation size.
(3) Unable to utilize the last context for non-SEP runs due to different
interpretation of the …

prov/psm2: Improve resource counting for Tx/Rx contexts

---

prov/verbs/Makefile.include
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_domain.c
prov/verbs/src/verbs_mr.c

This straightforward changes are needed for the planned enabling of MR caching into verbs/MSG,DGRAM ep types and then into verbs/RDM ep type
The `verbs_mr.c` contains the same implementation as for `verbs_domain.c` (w/o any changes applied)

prov/verbs: Separate MR functionality from Domain

---

include/fi_mem.h
prov/rxm/src/rxm_ep.c
prov/sockets/src/sock_progress.c

Commit 3a8755ad added a check for a disconnected connection as
part of progressing transmit requests.  However, the check was
added before the check for a valid connection.  The result is
that attempting to access the progress engine (pe) connection
(conn) can result in a segfault.
Problem was reported by Sandia OpenSHMEM developers.

Bug fixes for sockets, rxm, and util providers

---

prov/rxd/src/rxd_cq.c
prov/rxd/src/rxd_ep.c
prov/rxm/src/rxm_ep.c
prov/sockets/src/sock_progress.c

Fix the following format string warnings:
```
CC       prov/sockets/src/src_libfabric_la-sock_progress.lo
../prov/sockets/src/sock_progress.c:135:52: warning: format specifies type 'long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
SOCK_LOG_DBG("Remaining for %p: %ld\n", pe_entry, pe_entry->rem);
~~~               ^~~~~~~~~~~~~
%llu
../prov/sockets/src/sock_progress.c:63:57: note: expanded from macro 'SOCK_LOG_DBG'
#define SOCK_LOG_DBG(...) _SOCK_LOG_DBG(FI_LOG_EP_DATA, __VA_ARGS__)
^~~~~~~~~~~
../prov/sockets/include/sock_util.h:55:63: note: expanded from macro '_SOCK_LOG_DBG'
#define _SOCK_LOG_DBG(subsys, ...) FI_DBG(&sock_prov, subsys, __VA_ARGS__)
^~~~~~~~~~~
../include/rdma/providers/fi_log.h:93:40: note: expanded from macro 'FI_DBG'
FI_LOG(prov, …
```

Fix format string type warnings/errors

---

prov/sockets/src/sock_progress.c

Commit 3a8755ad added a check for a disconnected connection as
part of progressing transmit requests.  However, the check was
added before the check for a valid connection.  The result is
that attempting to access the progress engine (pe) connection
(conn) can result in a segfault.
Problem was reported by Sandia OpenSHMEM developers.

prov/sockets: Move check for valid conn to top of progress function

---

include/fi_util.h
prov/util/src/util_attr.c

prov/util: Advertise RMA target capability based on hints and provider mode
This patch handles the case when user passes zero in hints->caps.
ofi_alter_info through ofi_get_caps sets all supported caps by the provider
if hints->caps is zero. This can have the inadvertent effect of advertising
RMA target caps when the app doesn't support provider required mr_modes for
it.
Fix:
If a provider supports RMA target caps but require certain MR modes for the
support, check the hints for those modes and disable the caps if needed.

prov/util: Return RMA caps based on hints mr mode

---

prov/psm2/src/psmx2_msg.c
prov/psm2/src/psmx2_tagged.c

Previously, when the application set FI_SELECTIVE_COMPLETION and did
not enable FI_COMPLETION but the fi_context is not a NULL pointer,
the provider would enable a completion.  With this change, the
completion is suppressed.
It's possible that an application might want to use the fi_context as
a key to cancel an outstanding operation, but the man pages say that
providers ought to ignore fi_context if completions are supressed,
and so fi_cancel shouldn't be supported in that case.
Signed-off-by: Jim Snow <jim.m.snow@intel.com>

prov/psm2: Allow completion suppression when fi_context is non-NULL.

---

man/fi_endpoint.3.md

There's confusion about which requests can be canceled,
since cancel relies on using the per operation context
parameter.  Not all operations require a context parameter,
or the context parameter can be ignored.  Document that
such operations cannot be canceled.

man/cancel: Clarify that cancel requires a valid context

---

prov/sockets/src/sock_av.c

Turns out that there's an edge case in the sockets provider
fi_av_remove method where a socket conn in the table may
be in a connecting state.  This condition needs to be
checked for in order to avoid segfaults.
This behavior was observed highly irregularly (usually took
many 100s of runs) of Open MPI's IBM test suite.  Without
this patch, every few hundred runs on 4 processes one would
get a segfault.
With this patch, the problem is no longer observed.

prov/sockets: plug an edge case for fi_av_remove

---

src/fabric.c

-In ofi_create_prov_entry, prov_name is allocated and set in the ofi_prov
struct for the corresponding provider.
-At fi_fini the ofi_prov struct is freed, but prov_name is not freed at
close resulting in a memory leak for the prov_name strings.
-A free is now called to cleanup the memory allocated from strdup for
prov_name.

src/fabric: Fix memory leak for prov_name string in struct ofi_prov

---

prov/netdir/src/netdir_ep.c
prov/netdir/src/netdir_init.c
prov/netdir/src/netdir_pep.c

The fi_pingpong test fails for the NetDir provider.
This fixes `fi_getname` and removes `FI_LOCAL_MR` mode.
Btw, `GetLocalAddress` should return `ND_BUFFER_OVERFLOW` if size of provided buffer is too small. But how the ND document says that it is vendor-specific to return any value:
`When you implement this method, you should return the following return values. If you return others, try to use well-known values to aid in debugging issues.`

prov/netdir: Fix fi_ep_getname

---

man/fi_sockets.7.md
prov/sockets/include/sock.h
prov/sockets/include/sock_util.h
prov/sockets/src/sock_conn.c
prov/sockets/src/sock_ep_msg.c
prov/sockets/src/sock_fabric.c

Please find a set of two patches to add the support of TCP keepalive to the `sockets` provider.
The patch introduces 4 new environment variables to deal with keepalive: 
* FI_SOCKETS_KEEPALIVE_ENABLE: A boolean to enable the keepalive support.
* FI_SOCKETS_KEEPALIVE_TIME: An integer to specify the idle time in seconds before sending the first
keepalive probe. Only relevant if FI_SOCKETS_KEEPALIVE_ENABLE is enabled.
* FI_SOCKETS_KEEPALIVE_INTVL: An integer to specify the time in seconds between individual keepalive probes. Only relevant if FI_SOCKETS_KEEPALIVE_ENABLE is enabled
* FI_SOCKETS_KEEPALIVE_PROBES: An integer to specify the maximum number of keepalive probes sent before dropping the connection. Only relevant if FI_SOCKETS_KEEPALIVE_ENABLE is enabled
This feature is currently …

prov/sockets: Add support for keepalive

---

man/fi_psm2.7.md
prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_am.c
prov/psm2/src/psmx2_atomic.c
prov/psm2/src/psmx2_av.c
prov/psm2/src/psmx2_cm.c
prov/psm2/src/psmx2_cq.c
prov/psm2/src/psmx2_domain.c
prov/psm2/src/psmx2_ep.c
prov/psm2/src/psmx2_init.c
prov/psm2/src/psmx2_msg.c
prov/psm2/src/psmx2_rma.c
prov/psm2/src/psmx2_tagged.c

This patch series rework the regular endpoint implementation to use separate PSM2 endpoints for different OFI endpoints instead of sharing a single PSM2 endpoint via the "virtual lane" mechanism. The address vector implementation is also updated to accommodate the change.

prov/psm2: Replace virtual lanes with real PSM2 endpoints for supporting multiple endpoints 

---

include/fi_indexer.h
include/fi_util.h
prov/rxm/src/rxm_cq.c
prov/util/src/util_av.c
src/indexer.c

The issue was originally observed when running ofi_rxm over sockets provider in travis CI.
This PR contains the following patches:
- common: update indexer entry to struct
- prov/util: Fix # of bits used for connection index
- prov/util: rename function names to align with naming for static functions
- prov/rxm: Serialize access to cmap key_idx
- prov/rxm: improve CQ error handling

prov/util,rxm: Fix race condition issue in util cmap

---

Makefile.am
include/fi_util.h
include/ofi_mr.h
libfabric.vcxproj
libfabric.vcxproj.filters
prov/rxd/src/rxd_domain.c
prov/sockets/include/sock.h
prov/sockets/src/sock_dom.c
prov/sockets/src/sock_progress.c
prov/util/src/util_mem_monitor.c
prov/util/src/util_mr_map.c

The intent of this patch is to move MR functionality from utility header-file to the separate header-file and add Memory monitor from the Sean's #3569 PR.
The patch consists from the 2 commits:
- Cherry-pick commit from #3569 
- Rename utility "MR" to "MR map"
-- Apply changes to the sockets provider
-- Apply changes to the rxd provider

 util: Add Memory monitor and Rename MR to MR map

---

prov/util/src/util_mem_monitor.c

Coverity complains that we initilaize ref_cnt w/o NQ::lock held - CID [209353]( https://u2389337.ct.sendgrid.net/wf/click?upn=08onrYu34A-2BWcWUl-2F-2BfV0V05UPxvVjWch-2Bd2MGckcRb-2FSCqabEQT-2FUiYsE2p3yBDPW9oUWfnyZHxURWIS0a-2FmYjzNXEAns846z0FmqumnYo-3D_eVm0CEQ-2FtI-2Fu8SBfRY9SEJtCLmujXF2YqcBkLxltbg0Wdak9HAiFB6Po7bD20JPqKiBgggxpE2-2Bj4B8RGr3ILoKPvEY0SYqZtivgw3r7L85AkYr48UiGYssR6m9YZo65-2FPPcL2vnuWeC2otr07Od2SqzCZhGQljZqaEP3xVJYqv88rDmDauPFeQbrBOgGOhsHgbMI3JBcDWaglpetHwQI2vN0NRO5E6x-2Foou2zpydcE-3D)
Seems it's false-positive. But anyway, it could be fixed easily instead of marking as false-positive. 
@shefty @jswaro What do you think?

util: Fix coverity issue (false-positive actually)

---

prov/shm/src/smr.h
prov/shm/src/smr_domain.c
prov/shm/src/smr_ep.c
prov/shm/src/smr_fabric.c

- add domain and endpoint counters
- ep_name = pid:dom_idx:ep_idx
- can still call fi_setname, just setting default for easy initialization
- still assuming out-of-band endpoint name exchange (or fi_setname)

prov/shm: create default endpoint name on init

---

libfabric.vcxproj
libfabric.vcxproj.filters
prov/sockets/Makefile.include
prov/sockets/src/sock_dom.c
prov/sockets/src/sock_mr.c

This patch moves MR operations to the separate file `sock_mr.c`
This is needed to improve readability of sock::Domain code and for further implementation of MR functionality on top of utility MR manager (that will provider MR caching) for the Sockets provider (as a reference implementation).

prov/sockets: Move MR functionality to a separate source file

---

prov/sockets/include/sock.h
prov/sockets/src/sock_conn.c
prov/sockets/src/sock_progress.c

The epoll set 'map->epoll_set' is configured in level-triggered
mode, meaning that epoll_wait() will continue reporting events
for the monitored file descriptors until the file descriptors
that generated the events are effectively read.
We mustn't retry epoll_wait() if the returned value is equal to
the maximum number of events specified in arguments (32 by default),
otherwise the same events for the same file descriptors will be
indefinitely reported by epoll_wait(). This will cause libfabric
to allocate RX buffers in a loop, leading to the exhaustion of the
memory on the machine.
The patch dynamically resizes the array of epoll contexts to match
the number of connections ysed in the connection map.
Array resizing for the epoll contexts must be done in
sock_pe_progress_rx_ep() and not in …

prov/sockets: do not retry after epoll_wait()

---

prov/psm/src/psmx.h
prov/psm/src/psmx_init.c
prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_init.c

Previously the ordered sizes were set to 0 due to the existence of
multiple data transfer paths for RMA operations. However, according to
current fi_endpoint man page, to satisfy the data ordering requirement
only RMA operations under the provider defined threshold need to be
considered. As the result, the provider can declare ordering of RMA
operations that take the small-size message path.

prov/psm,psm2: Enable ordering of RMA operations

---

man/fi_cq.3.md

RMA writedata calls that generate a completion at the target
do not have an op_context available to return as part of a
completion unless FI_RX_CQ_DATA is set.

man: Clarify cq op_context is not valid for RMA writedata

---

prov/psm2/src/psmx2_av.c
prov/psm2/src/psmx2_domain.c

In fi_av_insert() and fi_close(domain).

prov/psm2: Fix two instances of memory leak

---

prov/psm2/src/psmx2_av.c

Commit a75cc62 made a mistake in the calculation of array indices
when copying the input addresses into the internal table. This
could result in failure of subsequent fi_av_insert() calls.

prov/psm2: Fix a bug in fi_av_insert()

---

prov/shm/src/smr_ep.c
prov/shm/src/smr_init.c

- when creating a new endpoint, create endpoint name from info src_addr if present
- if no src_addr given, default to pid:dom_idx:ep_idx
- get rid of comment in getinfo because no longer applicable (src_addr not needed)

prov/shm: check info src_addr before defaulting to pid:dom:ep

---

prov/gni/test/rdm_dgram_rma.c
prov/gni/test/rdm_dgram_stx.c

Two of the GNI provider criterion tests are
failing sporadically, leading to false positive
CI failures.
Disable till we have time to figure out what's going on.

prov/gni: disable a couple of tests

---

prov/psm2/src/psmx2_atomic.c
prov/psm2/src/psmx2_init.c
prov/psm2/src/psmx2_rma.c

prov/psm2: Allow all free contexts be used for scalable endpoints
prov/psm2: Simplify the handling of self-targeted RMA operations

prov/psm2: Two small code enhancements

---

man/fi_domain.3.md

Call out rx/tx contexts as part of the defined threading models.

man/threading: Clarify that threading applies to scalable endpoints

---

prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_domain.c
prov/psm2/src/psmx2_ep.c

(1) Remove the special case for empty ep which was used to initialize
AM handlers before any endpoint was created. It is no longer needed
since now AM handlers are initialized for each endpoint.
(2) Remove duplicated capability checking at the time an endpoint is
opened.

prov/psm2: Simplify the code for checking endpoint capabilities

---

configure.ac
include/rdma/fabric.h
include/rdma/providers/fi_prov.h
prov/psm2/Makefile.include
prov/psm2/build-psm2.sh
prov/psm2/configure.m4
prov/psm2/src/psm2_revision.c
prov/psm2/src/version.h
src/abi_1_0.c
src/fabric.c
src/fi_tostr.c
src/log.c
src/var.c

Compiling the source code of PSM2 library together with the provider
allows more aggressive compile-time/link-time optimization. In addition,
the provider can be further optimized by having access to the internal
definitions of the PSM2 library.
This option is enabled with the configure option "--with-psm2-src=DIR".
The resulting provider no longer uses or depends on the stand-alone PSM2
library.
Exported symbols need additional "externally_visible" attribute to remain
public when  link time optimization is used.
A script is provided as an example for the new building options.

prov/psm2: Add option to include PSM2 library source and use link time optimization

---

prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_cq.c
prov/psm2/src/psmx2_ep.c
prov/psm2/src/psmx2_tagged.c

These patches are targeted for improving MPI performance. 
@shefty This is for the stable branch, but doesn't create demand for a future new release by itself.

v1.5.x:  psm2 provider critical path optimization for send and recv (2 patches)

---

prov/psm2/src/psmx2_av.c

When resizing the address vector realloc() is called to expand a few
internal tables. Some of the tables are expected to be initialized to
0, which is not done by realloc().
Uninitialized entries in these tables could cause memory access error.

prov/psm2: Initialize internal address tables after resizing AV

---

man/fi_psm2.7.md
prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_domain.c
prov/psm2/src/psmx2_init.c

Now the provider depends more on the multi-ep feature it makes
sense to have it on by default. It can still be turned off manually
by setting PSM2_MULTI_EP=0.
Update the man page accordingly.

prov/psm2: Enable PSM2 multi-ep feature by default

---

prov/tcp/src/tcpx.h
prov/tcp/src/tcpx_conn_mgr.c
prov/tcp/src/tcpx_ep.c

Moved connection management functions in a new file (tcpx_conn_mgr.c) from tcpx_fabric.c in first commit. And added support for connection data exchange in second commit. I didn't merge these commits to make it easier to see what was changed in the moved code.

prov/tcp: Added support for connection data exchange during connection setup

---

prov/gni/src/gnix_mr.c
prov/gni/src/gnix_mr_cache.c
prov/gni/src/gnix_rma.c

Mercury crew found a number of issues when trying to use the 1.5.3rc1 tarball.  These cherry picks plus manual patches get them at least going now.  There does appear to be an underlying issue
possibly concerning Cray kdreg that Mercury seems to be hitting when using lazy memory deregistration, but that problem is not going to be resolved for the 1.5.3 release.
@soumagne

Topic/gni missing commits for v1.5.x

---

include/linux/osd.h
include/osx/osd.h
include/unix/osd.h
include/windows/osd.h
prov/sockets/src/sock_fabric.c
prov/sockets/src/sock_progress.c
prov/verbs/src/fi_verbs.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_domain.c
src/unix/osd.c
src/windows/osd.c

This patch consists from 3 commits:
- Add setting thread affinity functionality to common code
- Replace the sockets' setting thread affinity by common one
- Enabling setting CM thread affinity in the verbs proider

prov/verbs: Add support of setting CM thread affinity

---

prov/psm2/src/psmx2_cq.c
prov/psm2/src/psmx2_msg.c

Fix the following two issues for the scenario that a message sent via the
iov send protocol is delivered into a multi-receive buffer: (1)incorrect
receive request for reposting the receive buffer; (2) missing FI_MULTI_RECV
completion flag.

prov/psm2: Fix multi-receive issues when paired with iov send

---

prov/usnic/src/usdf.h
prov/usnic/src/usdf_domain.c
prov/usnic/src/usdf_ep_dgram.c
prov/usnic/src/usdf_ep_msg.c
prov/usnic/src/usdf_ep_rdm.c

Update default endpoint flags to enable the usnic provider to work properly with the changes from da4f8f7e9223c68529db7dedd7c88c28957bb3f0. Also remove the now-unnecessary usdf_check_mr_mode() wrapper (and just use ofi_check_mr_mode() directly).

usnic: update MR mode checks

---

prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_am.c
prov/psm2/src/psmx2_atomic.c
prov/psm2/src/psmx2_av.c
prov/psm2/src/psmx2_domain.c
prov/psm2/src/psmx2_rma.c
prov/psm2/src/psmx2_trx_ctxt.c

-Update PSM2 provider to register the AM handlers with the new
psm2_am_register_handlers_2 function which allows for the user to
register AM handlers with a calling context.
-Changed to registering psm2_am_handler_2_fn_t AM handler functions
which include the calling context.
-Allows for removal of internal context tracking and simplifies the AM
handler code.

prov/psm2: Update PSM2 prov to use PSM2 AM Handler with Context

---

include/rdma/fi_errno.h

At least EINTR can be returned by calls that wait on an fd.
Problem was reported by OMPI.  Add other defines that may be
likely to be hit.

errno: Expose additional errno values

---

prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_cq.c
prov/psm2/src/psmx2_msg.c
prov/psm2/src/version.h

Use macros to abstract the completion status data structure and the way
completion is polled from PSM2. This allows switching to a different
implementation with minial code change.

prov/psm2: Abstract the completion polling mechanism

---

prov/psm2/configure.m4

The provider now requires this newly added PSM2 function. Compatible
PSM2 source code is available at https://github.com/01org/opa-psm2.

prov/psm2: Check for psm2_am_register_handlers_2 in configure

---

include/fi_proto.h
include/fi_shm.h
include/fi_util.h
include/ofi_mr.h
prov/rxd/src/rxd.h
prov/shm/src/smr.h
prov/shm/src/smr_attr.c
prov/shm/src/smr_domain.c
prov/shm/src/smr_ep.c
prov/shm/src/smr_init.c
prov/util/src/util_domain.c
prov/util/src/util_mr_map.c

- change EP type from DGRAM to RDM
- fix check_info bug
- simplify peer verification
- add MR registration calls
- implement RMA transfers using 2 methods:
(1) send RMA by inserting 2 commands into and let peer do transfer through CMA call (for large writes and all reads) or inline (for smaller writes)
(2) no peer MR verification, local side does complete transfer using CMA call
Currently, method is chosen based on number of rma iovs, but can adapt later for increased performance based on other variables/settings

prov/shm: initial RMA implementation

---

prov/verbs/src/fi_verbs.c
prov/verbs/src/verbs_domain.c

This patch addresses Coverity issues that are reported  12/23/17:
- CID 215114: Copy-paste error
- CID 215113: Double lock of pthread mutex
this code doesn't cause program hanging because pthread mutex is marked as `Reentrant`

prov/verbs: Fix Coverity issues

---

prov/util/src/util_ns.c

Blocking read/write returns 0 only when the peer is closed or encounters
EOF. Keep issuing the same call will result in infinite loop. Treat 0 the
same way as error because the required bytes to read/write will never be
satisfied.

prov/util: Fix potential deadlock in name server thread

---

man/fi_psm2.7.md
prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_init.c
prov/psm2/src/psmx2_trx_ctxt.c

The automatic connection cleanup mechanism introduces extra overhead at
the finalization phase, which is unnecessary for most applications since
they never reuse epids within a session.
Add the environment variable FI_PSM2_DISCONNECT to control whether this
mechanism is used.

prov/psm2: Add an environment variable for automatic connection cleanup

---

configure.ac

This option helps identify stack smashing issues with a small
performance overhead.

config: Add stack protector gcc option to debug build.

---

prov/verbs/src/ep_rdm/verbs_av_ep_rdm.c
prov/verbs/src/ep_rdm/verbs_ep_rdm.c
prov/verbs/src/ep_rdm/verbs_queuing.h
prov/verbs/src/ep_rdm/verbs_rdm.h
prov/verbs/src/ep_rdm/verbs_rdm_cm.c
prov/verbs/src/ep_rdm/verbs_rdm_msg.c
prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm.c
prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm_states.c
prov/verbs/src/verbs_domain.c

This is initial patch that is applying some minor optimizations for the critical path.
It allows to reduce a latency by 0.04 usec for small messages.

prov/verbs: Optimize verbs/RDM critical path

---

prov/psm2/Makefile.include
prov/psm2/src/psmx2_cq.c
prov/psm2/src/version.h

Include bug fix to the makefile, addition to the configure script, and new / updated completion polling macros.

prov/psm2: Enable completion polling optimization when PSM2 source is compiled in

---

prov/psm2/src/psm2_revision.c

The PSM2 library can output detailed version information when the
environment variable PSM2_IDENTIFY is set. A few externally defined
strings are needed to make this work. When the provider is built
together with the PSM2 source, these strings are defined by the
provider. Previously random definitions were used which wouldn't
match the actual build. This patch sets meaningful default values
and allows them be overridden at compile time.

prov/psm2: Update the definition of the PSM2 version string

---

prov/gni/src/gnix_dom.c

Plug a memory leak reported by a diligent valgrind user.
Thanks to @sougmagne for reporting.
Fixes #3663
Fixes ofi-cray/libfabric-cray#1425

prov/gni: plug a memory leak

---

prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_atomic.c
prov/psm2/src/psmx2_cm.c
prov/psm2/src/psmx2_cntr.c
prov/psm2/src/psmx2_cq.c
prov/psm2/src/psmx2_domain.c
prov/psm2/src/psmx2_ep.c
prov/psm2/src/psmx2_init.c
prov/psm2/src/psmx2_mr.c
prov/psm2/src/psmx2_msg.c
prov/psm2/src/psmx2_rma.c
prov/psm2/src/psmx2_tagged.c

prov/psm2: Keep Tx context and Rx context separate for each endpoint
prov/psm2: Add shared Tx context support
prov/psm2: Allow binding any number of endpoints to a CQ/counter

prov/psm2: Three patches for enabling shared tx context support

---

prov/rxm/src/rxm_ep.c
prov/verbs/src/ep_rdm/verbs_ep_rdm.c
prov/verbs/src/fi_verbs.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_info.c

- prov/verbs: Select highest possible inject size for verbs/MSG as well
- prov/rxm: Always do progress when fi_send from MSG provider returns -FI_EAGAIN

prov/verbs: Select max inline size possible

---

include/fi_shm.h
man/fi_msg.3.md
prov/shm/src/smr.h
prov/shm/src/smr_attr.c
prov/shm/src/smr_ep.c

- modify smr_op_hdr struct
- include op_flags (for signaling CQ data)
- differentiate between src_data (tx_buf/resp offset) and data
- make generic inject function to reuse for fi_inject, fi_tinject, fi_injectdata, and fi_tinjectdata
- add smr_rx_comp_flags to get rx completion flags
- fix some errors
- check if rx_cq is full before committing
- free recv entry if was processed in unexpected messages
- switch some "ret"s to "err"s when passing in before completion because coverity complained once before
Verified working on ubertest latency, bandwidth, and unit tests
Also updated license dates because it's 2018 now apparently :O
Throwing a man page error update in here as well

prov/shm: add data functions

---

Makefile.am
prov/hook/src/hook.c
prov/hook/src/hook.h
prov/hook/src/hook_av.c
prov/hook/src/hook_cm.c
prov/hook/src/hook_cntr.c
prov/hook/src/hook_cq.c
prov/hook/src/hook_domain.c
prov/hook/src/hook_ep.c
prov/hook/src/hook_eq.c
prov/hook/src/hook_wait.c
prov/hook/src/hook_xfer.c

Introduce a new provider capable of hooking all calls to a
provider.  The intercepting provider can be used to enable debugging or
performance profiling over any provider.  Because the hook provider
is always built, it can be available even in release builds, with no impact if not enabled.
This PR adds the code for the hook provider, incorporates it into the build, but doesn't enable it.  Enabling will need to come in a follow on patch.  As a result, there's no way to test this code.
Although this is a large patch, since it hooks across the entire API.  Most of the code is straightforward and simply passes calls through to the hooked provider.
The plan is to introduce a new environment variable, FI_HOOK.  When set, the hook provider will inject itself between the application and whichever …

prov/hook: Add framework for hooking all provider calls

---

prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_av.c
prov/psm2/src/psmx2_init.c
prov/psm2/src/psmx2_trx_ctxt.c

By now the required PSM2 library version should have included all the
features that were previously optional. It is no longer necessary to
check for those features.

prov/psm2: Remove obsolete feature checking code

---

include/fi_util.h
prov/sockets/include/sock.h
prov/sockets/src/sock_cq.c
prov/util/src/util_cq.c

This series fixes (in theory) the handling of fi_cq_signal, so that any thread waiting in cq sread or sreadfrom will unblock and return when signal is called.  The current code does not unblock threads waiting in sread.  Sreadfrom will unblock, but has a separate issue that it may return prematurely before the timeout expires.
This PR is related to #3645, however, the fix only applies to code that uses the utility CQ.  A fix to the socket provider will follow.
The signal code itself is untested, pending enhancements to fabtests to test for correctness. That too will follow.

util/cq: Fix support for fi_cq_signal

---

prov/gni/src/gnix_datagram.c

When trying to debug problems in the GNI provider
using trace, the gnix_datagram poll method generates
way too much output.

prov/gni: remove a trace macro from datagram path

---

prov/util/src/util_cq.c

This patch fixes a regression introduced by 928e688

prov/util: fix incorrect handling of infinite timeout in sread

---

prov/psm2/src/psmx2_cq.c

Re-organize the code in order the reduce overhead associated with
completion generation:
* Redesign the internal interface to consolidate two similar switch
statements in two functions into a single one;
* Use separate specialized functions for tx and rx completion;
* Improve code locality by distributing shared code segment into
individual switch cases.
* Add likely/unlikely hints to a few selected branches.
Also fix a memory leak related to iov send.

prov/psm2: Code refactoring for completion generation

---

prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_cq.c

Check if the CQ has been signaled when waiting inside fi_cq_sread
and allow early return when the condition is true.
This is a follow up for commit 043e1dd (prov/util: Fix fi_cq_signal).
See #3666 

prov/psm2: Fix fi_cq_signal

---

prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_cq.c

Adopt a method that allows direct access of the first 64 bit of the
96-bit tag without breaking strict-aliasing rules. This should perform
better than the previous method that involves bit manipulation.

prov/psm2: Optimize the conversion between 96-bit and 64-bit tags

---

include/fi.h
prov/verbs/src/fi_verbs.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_eq.c
prov/verbs/src/verbs_info.c
src/common.c

- prov/verbs: catch fatal errors on connection request
- common: Augment address sizeof function to handle AF_IB 
- prov/verbs: Update provider to use common address sizeof function
- prov/verbs: use ofi_straddr for address logging
- common: add a function to check if a sockadddr is a wildcard address
- prov/verbs: check for FI_RX_CQ_DATA in rx_attr as well
- prov/verbs: handle wildcard addresses correctly

prov/verbs: handle wildcard addresses correctly for passive EPs + bug fixes

---

prov/psm2/src/psmx2_ep.c

AM initialization depends on EP caps. Usually it is done when the
endpoint is created. When shared Tx context is used, the initialization
should be done inside fi_ep_bind.

prov/psm2: Initialize AM parameters for shared Tx context

---

prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_cq.c
prov/psm2/src/psmx2_ep.c
prov/psm2/src/psmx2_msg.c
prov/psm2/src/psmx2_tagged.c

(1) Use a static array to define the completion flags for each context
type. This allow merging a few switch cases without adding branch.
(2) Receive operations that don't generate completions always need
allocated context in order to support iov send. Consolidate the
"alloc" and "non-alloc" types into one.
(3) Add dedicated context types for tagged send/recv operations that
don't generate completions. This allows correct flags be set in
error CQE.
(4) Remove a redundant type checking when freeing allocated contexts.

prov/psm2: Refactor the handling of op context type

---

prov/psm2/configure.m4

When configuring for building with PSM2 source included, the predefined
macro AC_EGREP_HEADER was used to check for the presence of a required
symbol. Instead of running a straight grep command, the macro would
call cpp to process the file and then run grep on the result. This was
an overkill here and created unnecessary dependencies on all the headers
included in the file being processed.
Use grep directly instead of the macro to check the condition.

prov/psm2: Remove unnecessary dependencies from the configure script

---

prov/gni/test/mr.c

The logic for disabling some GNI unit tests when
kdreg not available was backwards.

prov/gni: fix logic error in gni unit tests

---

prov/gni/test/rdm_dgram_rma.c
prov/gni/test/rdm_dgram_stx.c
prov/gni/test/rdm_sr.c

Intermittent failing tests are making it difficult to establish a
testing baseline. Temporarily skip these tests to establish
baseline and return to fix these issues later.
It would seem that the majority of the issues affect the inject path.

prov/gni: Disable intermittent failing tests

---

prov/gni/src/gnix_dom.c
prov/gni/src/gnix_mr.c
prov/gni/test/mr.c

Turns out that when libfabric is used with an application that
is also using Cray MPICH, the GNI provider needs to use UDREG if
kdreg support is required.
Unfortunately there was a critical flag left out of the
UDREG attributes modes that caused the GNI provider to
use UDREG without using kdreg.  For applications (like
applications using mercury apparently) that are susceptible
to munmap operations under the covers in glibc's heap allocator,
this can lead to data corruption.
Also, it turns out that the GNI provider needs to be less
aggressive with kdreg entries since the Cray MPICH also uses
up some.
This commit addresses these two issues.

prov/gni: fixes for UDREG use

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_init.c
prov/rxm/src/rxm_rma.c

This patch adds some optimizations for the  RxM critical path
- Inject and tagged inject paths are splitted into special function.
- Optimizations of CQ engine
**NOTE:**
The part of this PR contains some commits form #3686 that will be removed after #3686 is being merged into the master branch:
- Avoid excessive variable
- Minor changes to the RxM and utility/cmap code. This reduces only single instruction on critical path when the library is built by GCC
- RXM_NONE state has been removed as unneeded and used only in debug case
- Make TX/RX entry routines as static inline
- Simplifies conditions for MR_LOCAL and non-MR_LOCAL cases
- rxm_pkt_init() is doing an excessive memset()
- Remove function's declarations that are defined, but aren't implemented
- Mark some local functions as static

prov/rxm: Optimizations of the critical path

---

include/fi_mem.h
include/fi_shm.h
prov/shm/src/smr_attr.c
prov/shm/src/smr_ep.c
prov/util/src/util_shm.c

Patches address two general areas:
- reorganization of cmd hdrs and data to make implementation easier and more intuitive and a better use of space (patches 1&2)
- issues causing unexpected message test to fail (patches 3&4)
Also includes various bug fixes and code cleaning
Verified working on ubertest. Now also passing unexpected message test.

prov/shm: various fixes and regorganizations

---

prov/psm2/Makefile.include

When built as DSO provider, too many symbols were exported and could
cause conflict with other shared libraries. One example was that a
DSO psm2 provider with PSM2 source compiled in could fail at API
version checking because an identically named function from the PSM
(not PSM2) library was used.
The only symbol needs to be exported by a DSO provider is "fi_prov_ini".
By limiting the exported symbol, all symbols that can be resolved
internally would not affect or be affected by other shared libraries.

prov/psm2: Limit exported symbols for DSO provider

---

prov/psm2/src/psmx2_cm.c
prov/psm2/src/psmx2_ep.c

Normally a HW context is allocated for each endpoint to be used for
both TX and RX operations. However, if an endpoint uses shared TX
context and doesn't need RX capability there is no need to allocate
a dedicated HW context. This make it possible to reduce the number
of HW contexts needed by using shared TX context.

prov/psm2: Reduce HW context usage for certain TX only endpoints

---

prov/psm2/configure.m4
prov/psm2/src/psmx2_am.c
prov/psm2/src/version.h

The use of psm2_am_register_handlers_2 has allowed a large chunk of
redundant code being removed. However it requires the latest PSM2
library that is currently only available in source format from
https://github.com/01org/opa-psm2 and is not compatible with a
wide range of PSM2 libraries currently in use.
A new scheme is adopted to bring back the compatibility without
reintroducing the bulk of the old code removed by this new function.
Now the provider should work with PSM2 libraries from IFS 10.5 and
later (corresponding to PSM2 release 10.2.235 and later).

prov/psm2: Add backward compatibility for earlier PSM2 libraries

---

include/fi_iov.h

Fix bug introduced in #3686 (commit - `046e9df`)
Bug is reproducible for the OFI/RxD provider when `iov_offset` > 0

common/iov: Fix ofi_copy_[to|from]_iov routines

---

prov/psm2/src/psmx2_ep.c

There was a bug in the following commit that could cause segfault when
endpoints with NULL RX context were closed.
0dd75e1 prov/psm2: Reduce HW context usage for certain TX only endpoints

prov/psm2: Fix a segfault in fi_close(ep)

---

Makefile.am
include/fi.h
include/fi_util.h
include/ofi_net.h
libfabric.vcxproj
libfabric.vcxproj.filters
prov/mlx/src/mlx_fabric.c
prov/psm/src/psmx_fabric.c
prov/psm/src/psmx_init.c
prov/psm2/src/psmx2_fabric.c
prov/psm2/src/psmx2_init.c
prov/util/src/util_ns.c
prov/verbs/src/verbs_domain.c
prov/verbs/src/verbs_info.c

2nd attempt at cleaning up the name server code.  The changes are most identical to the first post.  Github closed my PR when I reset my master branch in order to run internal CI on the psm2 provider.
The main change is that I discovered via testing that closing a listening socket does NOT impact another thread calling accept on that socket (this may be system dependent).  Accept() can continue to block.  The cleanup code now sets a 'run' variable to false, connects to the server thread, and exits.  This unblocks the accepting thread.
The psm2 provider passes CI with these changes now.

util/ns: Restructuring and cleanups to name server code

---

prov/rxm/src/rxm_ep.c

Set TX entry's comp_flags instead of ORed them

prov/rxm: Set TX entry's comp_flags properly

---

prov/util/src/util_cq.c

ofi_cq_read is modified to call ofi_cq_readfrom to avoid code duplication in #3666. But this function have already been calling ofi_cq_read in case of no cq->src - causing stack overflow by infinite recursion. 

prov/util: bug fix for ofi_cq_readfrom()

---

prov/psm2/src/psmx2_trx_ctxt.c

The error was introduced by the following commit:
e027ef5 2018-01-20 util/buf: Update buf pool routines

prov/psm2: Fix a compilation error

---

prov/rxm/src/rxm_cq.c
prov/util/src/util_ns.c

- util/ns: Coverity complains that there is a chance that `sock` can be negative value, but `ofi_close_socket` can't handle a negative value - [CID 257273](https://scan4.coverity.com/reports.htm#v27196/p10344/fileInstanceId=35561707&defectInstanceId=6629322&mergedDefectId=257273)
- prov/rxm: The `rx_buf->pkt.ctrl_hdr.version` field will be assigned the `OFI_CTRL_VERSION` value that it was intended to compare against, causing the result to always be true - [CID 259145](https://scan4.coverity.com/reports.htm#v27196/p10344/fileInstanceId=35769499&defectInstanceId=6663500&mergedDefectId=259145)

util/ns, prov/rxm: Fix Coverity issues

---

prov/tcp/src/tcpx.h
prov/tcp/src/tcpx_conn_mgr.c
prov/tcp/src/tcpx_domain.c
prov/tcp/src/tcpx_ep.c
prov/tcp/src/tcpx_progress.c

commit 1:
Removed pe_entry_table and associated lists
commit 2:
Removed domain reference in progress structure
Changed function signatures for progress calls.

prov/tcp: code cleanup

---

prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c

The 1st commit of PR #3669 is causing send w/ zero payload buffer.

prov/rxm: Fix broken send path (eager)

---

prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_cq.c
prov/psm2/src/psmx2_ep.c
prov/psm2/src/psmx2_msg.c
prov/psm2/src/psmx2_tagged.c
prov/psm2/src/version.h

For receives with completion suppressed, internal allocation of fi_context
was needed in order to be able to generate error completion events. When
compiled with PSM2 source code, it is possible to use reserved space inside
the request handle as fi_context.
The behavior is now controlled by a macro PSMX2_USE_REQ_CONTEXT. A non-zero
value enables the above mentioned optimization when the PSM2 source is
compiled in.

prov/psm2: Replace allocated context with reserved space in psm2_mq_req

---

prov/psm2/src/psmx2_av.c

The domain handle can be obtained in a better way.

prov/psm2: Eliminate one reference to "fabric->active_domain"

---

man/fi_endpoint.3.md

The fi_ep_bind documentation indicates that binding an EP to a CQ
is mandatory (in order to report errors).  However, later the man
page states that an EP may 'instead' be bound to a counter.
The intent is that CQs should always be available in order to provide
details on errors.  Fabtests adheres to this requirement.  Strike the
confusing 'instead of' text.

man: Remove confusing/contradictory text binding an EP to counters

---

prov/psm2/Makefile.include
prov/psm2/configure.m4

All the changes are related to building the provider with PSM2 source
included:
(1) Use the internal uuid implementation and remove libuuid from the
dependencies. This is consistent with how the PSM2 library is built.
(2) In addition to checking the existence of hfi1_user.h, check that
the header file has the correct version.
(3) Check both the header file and library of the numactl-devel package.
(4) Provide more descriptive output for failed checks.
(5) Add configure option "--with-numa=DIR" to allow non-standard location
of the numactl-devel package.

prov/psm2: Update makefile and configure script

---

include/ofi_net.h

Fixes signed/unsigned comparison warning on windows.

core/net: Fix build warnings on windows

---

prov/tcp/src/tcpx.h
prov/tcp/src/tcpx_comm.c
prov/tcp/src/tcpx_ep.c
prov/tcp/src/tcpx_progress.c

Simplified data structures, merged iov and inject under union.
Removed ring buffer in endpoint.

prov/tcp: remove ringbuf for send requests and simplify data structures

---

prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_rma.c

Setting of MSG EP pointer for TX buffers is unnecessary. This can be removed.

prov/rxm: Remove setting of core MSG EP pointer for TX buffers

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c

This patch splits LMT protocol buffers into separate pool
This allows us to not set `rxm_pkt::ctrl_hdr::type` from `ofi_ctrl_large_data` to `ofi_ctrl_data` for the TX/MSG and TX/TAGGED buffers. As a result, this help us to minimize further development errors and avoid confusion.

prov/rxm: Split LMT TX buffer into separate pool

---

prov/sockets/src/sock_progress.c

This bug fix was missed in the v1.5.2 and v1.5.3 releases. I want to make sure it gets into the branch in case of a v1.5.4.
Original PR:
This bug was found by testing GASNet, which has some tests that very
rigourously stress messaging endpoints. The behaviour was that tests would
sporadically hang when put under heavy loads.
The root cause is found in the provider's handling of previously buffered
messages (ones that came in without a matching receive buffer). When the
handler grabbed a posted buffer to place a buffered message into, it was not
marking that receive buffer as free once it was done with it, which causes
buffers posted with FI_MULTI_RECV to become unusable in the future, which
leads to the provider running out of receive buffers.
After fixing the root cause, there was also …

Cherry-pick to v1.5.x: prov/sockets: Fix #3217, bug in buffered receive path

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c

This patch use index of send_queue's buffer instead of calculating index for msg_id

prov/rxm: Use send_queue freestack buf index for msg_id in LMT protocol

---

prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_domain.c
prov/psm2/src/psmx2_fabric.c
prov/psm2/src/psmx2_wait.c

Previously multiple calls to fi_domain() would return the same domain
object. That allowed multiple upper layer libraries be used together
by the same process, but lacked the protection provided by separate
domains and didn't work when different domain attributes (e.g. MR mode)
were needed.
Adding true multi-domain support remove the above limitations.

prov/psm2: Support opening multiple domains

---

include/fi_util.h
prov/shm/src/smr.h
prov/shm/src/smr_attr.c
prov/shm/src/smr_av.c
prov/shm/src/smr_ep.c
prov/shm/src/smr_init.c
prov/util/src/util_attr.c
prov/util/src/util_av.c

General improvements to the shm provider (see specific commits for details):
- fix trimming of provider capabilities in utility code
- set shm provider tx_attr and rx_attr caps correctly
- set shm provider MR iov limit and FI_CONTEXT mode
- standardize FI_ADDR_STR usage and format in util and shm code

prov/shm, util: various updates and fixes

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_attr.c
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c

This patch adds support of `FI_MULTI_RECV` capability for the RxM provider.
An object of `struct rxm_multi_recv_entry` structure is supervisor object that maps to a single `struct rxm_recv_entry` object.  Whenever the previous `struct rxm_recv_entry` object was consumed and then released, the new` struct rxm_recv_entry` object is created and maps to the same `struct rxm_multi_recv_entry`. This process continues until the `rxm_ep::min_multi_recv_size` value is reached.

prov/rxm: Add support of FI_MULTI_RECV cap

---

prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_cq.c
prov/psm2/src/psmx2_init.c
prov/psm2/src/psmx2_msg.c
prov/psm2/src/psmx2_rma.c
prov/psm2/src/psmx2_tagged.c

With this change, we use 32 bits of PSM2's 96 bit tag for remote CQ
data, 4 bits for internal metadata, and 60 bits for the OFI tag.
This also enables fi_tsenddata.

prov/psm2: Re-arrange how we use tag bits to support remote CQ data.

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c

The man page [fi_cq(3)](https://ofiwg.github.io/libfabric/master/man/fi_cq.3.html) says that providers have to handle multi_recv in the following way:
"..._This completion flag indicates that the original receive buffer referenced by the completion has been consumed and was released by the provider. Providers may set this flag on the last message that is received into the multi- recv buffer, or may generate a separate completion that indicates that the buffer has been released._"
Align implementation of RxM's Multi_recv feature with defined behavior in man page:
When the buffer is consumed, the RxM provider generates separate CQ with only `FI_MULTI_RECV` flag set and points `cq::buf` at the begging of multi-recv buffer.

prov/rxm: Report FI_MULTI_RECV flag when buffer is completely consumed

---

Makefile.am
prov/sockets/src/sock_fabric.c

Move mem.c to common sources file.  This is needed for DL
provider builds.  Call pmem_init() routine for socket provider
DL builds.

build/sockets: Fix DL build with PMEM extensions

---

include/fi.h
prov/psm/src/psmx_init.c
prov/psm2/src/psmx2_init.c
src/common.c

The functions fi_tag_bits() and fi_tag_format() didn't work as
expected.
Fixes #3751 
@shefty

fabric: Fix utility functions for tag format conversion

---

prov/util/src/util_wait.c

This PR updates `ofi_trywait()` to handle counter's wait fds

util/wait: Update ofi_trywait to handle counter's wait fd

---

prov/util/src/util_cntr.c

This patch fixes the following problems in the utility counter code:
- Fix invalid flags check (excessive `FI_RECV` -> `FI_READ`)
- Close wait FD when counter is closing
- Unset wait routine if FI_WAIT_NONE wait object is requested

util/cntr: Various fixes for utility counter code

---

prov/util/src/util_av.c

Currently utility AV implementation doesn't support Shared AV. If user sets `fi_av_attr::name` we should report that a named AV isn't supported.
This patch fixes this behavior by returning `-FI_ENOSYS` value in `fi_av_open()`

util/av: Handle a named AV

---

prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_msg.c
prov/psm2/src/psmx2_rma.c
prov/psm2/src/psmx2_tagged.c

(1) Code refactoring
(2) Full implementation of fi_tsenddata and fi_tinjectdata, including specialization

prov/psm2: Follow-up patches for supporting remote CQ data over tagged messages

---

prov/psm2/src/psmx2_init.c

This field is intended to be used as output only to convey the number
of tagged bits supported by a provider.

prov/psm2: Ignore mem_tag_format input from hints

---

include/fi_util.h
prov/rxm/src/rxm.h
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_domain.c
prov/rxm/src/rxm_ep.c
prov/util/src/util_ep.c

This PR adds support of CNTR objects for RxM provider (the 1st patch). This support is limited to `wait_obj = FI_WAIT_NONE` now. This restriction will be removed soon.
Also the 2nd patch changes behavior for `.wait` routine in case of `FI_WAIT_NONE` object is passed.

 prov/rxm: Add support of CNTR

---

src/common.c

Right shifting 64 bits is NOP instead of resulting 0. As the result
the while loop wouldn't end for numbers with the top bit set.

fabric: Fix a bug in ofi_msb()

---

man/fi_psm.7.md
man/fi_psm2.7.md

(1) Enhanced name server functionality;
(2) Updated capabilities for the psm2 provider;
(3) Minor cosmetic fixes.

man: Update man pages for psm and psm2 providers

---

man/fi_shm.7.md
prov/shm/src/smr.h
prov/shm/src/smr_atomic.c
prov/shm/src/smr_attr.c
prov/shm/src/smr_ep.c
prov/shm/src/smr_msg.c
prov/shm/src/smr_progress.c
prov/shm/src/smr_rma.c

- implement fi_cancel
- eliminate the need for FI_CONTEXT mode by setting the msg_id internally using the pending cmd address
- update man/fi_shm to reflect current support

prov/shm: fi_cancel, no FI_CONTEXT, and man update

---

include/ofi_util.h
prov/util/src/util_cntr.c
prov/util/src/util_ep.c

Fix counter cleanup order.  Convert atomic initialize calls to atomic set where appropriate.  Trap for errors when waiting on counters.

util/cntr: A few fixes plus minor code cleanups

---

prov/rxm/src/rxm_init.c

This patch removes `FI_LOCAL_MR` and `FI_MR_LOCAL` MR mode bits from `fi_info`s if an user doesn't support it

prov/rxm: Fix MR modes

---

prov/rxm/src/rxm_cq.c

memset() call can be removed for RX buffers when re-posting of receive buffer.
Only rx_buf->conn should be set to NULL

prov/rxm: Remove excessive memset() for RX buffers

---

prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_cq.c
prov/verbs/src/verbs_msg_ep.c
prov/verbs/src/verbs_srq.c

This PR applies the following optimization for the verbs' critical path:
- Drop excessive `ibv_send|recv_wr` structures from WR entry -- allows us to avoid `memset()` call
- Optimize CQ entry processing by refactoring completion flags handling

prov/verbs: Optimize verbs critical path

---

prov/gni/src/gnix_vc.c

Turns out the pack/unpack connection message
logic got messed up, disabling XPMEM and likely
garbling other connection data.
Fixes #3632

prov/gni: fix breakage in XPMEM path

---

prov/psm2/src/psmx2_init.c

Also replace a few references of PSM with PSM2 for consistency.

prov/psm,psm2: Add some provider build options to debug output

---

include/ofi_util.h
prov/rxm/src/rxm_ep.c
prov/util/src/util_cntr.c

- prov/util: check if wait object is internal before closing it
- prov/rxm: Add msg_cq fd to counter wait object epoll fd_list

prov/util,rxm: fixes for counters

---

Makefile.am
configure.ac
include/linux/osd.h
include/linux/rdpmc.h
include/ofi_perf.h
src/linux/rdpmc.c

I've got the following build failure on RedHat 6.7 with gcc 4.4.7:
```
src/linux/rdpmc.c: In function ‘rdpmc_read’:
src/linux/rdpmc.c:152: warning: implicit declaration of function ‘__builtin_ia32_rdpmc’
```
It's not enough to check that `linux/perf_event.h` header file is present. We have to check that `__builtin_ia32_rdpmc` built-in is declared and can be used.

linux/rdpmc: Fix build failure with GCC <= 4.4.7

---

prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_cq.c
prov/psm2/src/psmx2_msg.c

As part of the recent changes to support remote CQ date over tagged
messages, the iov protocol was slightly modified to use a different tag
bit layout. As the result, the payload packets for iov sends no longer
carries the original tag information. That means the completion would
have incorrect tag field if generated in the old way.
Update the completion generation routine to handle the new iov protocol.

prov/psm2: Fix incorrect tag received from iov send

---

prov/psm2/src/psmx2_tagged.c

The top 4 tag bits are reserved for internal protocol use. Trying to
send messages with any of these bits set would lead to undefined
result. Adding these assertions can help debugging such scenario.

prov/psm2: Add assertions to check that reserved tag bits are unused

---

include/freebsd/osd.h

Compiling on FreeBSD gives the following errors:
prov/sockets/src/sock_conn.c:246:24: error: use of undeclared identifier 'SOL_TCP'
if (setsockopt(sock, SOL_TCP, TCP_KEEPIDLE, &optval, sizeof(optval)))
^
prov/sockets/src/sock_conn.c:253:24: error: use of undeclared identifier 'SOL_TCP'
if (setsockopt(sock, SOL_TCP, TCP_KEEPINTVL, &optval, sizeof(optval)))
^
prov/sockets/src/sock_conn.c:260:24: error: use of undeclared identifier 'SOL_TCP'
if (setsockopt(sock, SOL_TCP, TCP_KEEPCNT, &optval, sizeof(optval)))

prov/sockets: Fix SOL_TCP not available on FreeBSD

---

src/common.c

Problem reported by coverity.  A bit shift of 64 is undefined.
A 0 value for either indicates that no tag values are supportable.
This essentially would convert the tagged interface into a normal
message interface.

core: Fix possibility of undefined bit shift

---

prov/rxm/src/rxm_ep.c
prov/verbs/src/verbs_msg_ep.c
prov/verbs/src/verbs_srq.c

- prov/verbs: fix missing initialization for wre
- prov/rxm: minor cleanups
- prov/rxm: rearrange bind cq/cntr 
- prov/rxm: delay cq_open until bind to determine if we need wait object

prov/verbs,rxm: bug fixes and refactoring

---

include/ofi_util.h
prov/verbs/src/fi_verbs.h

This patch fixes incorrect handling of case when `FI_INJECT` flag only set and cq_flags isn't set to `FI_SELECTIVE_COMPLETION`. Completion is generated by the prov/verbs/MSG in this case.

prov/verbs: Update completion flags handling for verbs/FI_EP_MSG

---

prov/rxm/src/rxm_ep.c

`MPI_Prove` calls fi_trecvmsg with `FI_PEEK` and expects that CQ entry obtained from `fi_cq_read()` contains the size of buffer.
This patch fixes this problem 

prov/rxm: Fix MPI_Probe: CQ entry should contain size of peeked buffer

---

prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_rma.c

This patch fixes two problems:
- When RMA operations are completed, MR descriptors aren't released
- Entries of registered MR array are overridden by their desc (local key) 

prov/rxm: Fix MR descriptor leak for RMA operations

---

man/fi_psm2.7.md
prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_init.c

The 96 bit tag provided by PSM2 is not enough to support 64 bit
application tag and 32 bit CQ data at the same time because a few
bits need to be reserved for the provider's internal protocols
for features such as untagged message, RMA, and iovec. As the
result, compromise has to be made to fit the most wanted feature
sets into the limited resource.
Support for remote CQ data over tagged message was added recently.
However, the application tag was reduced to 60 bit at the same
time. While new applications can adapt to the changes, existing
code may run into compatibility issue with the reduced tag space.
This patch implements a mechanism to allow different tag layout
schemes to coexist, being selected at compile time or at runtime.
In addition to the existing scheme, a new one is defined …

prov/psm2: Support two different tag layout schemes

---

prov/util/src/util_attr.c

Without this patch, fi_dom_test (fabtest) with tcpx enters an infinite
loop where rxm_fabric() calls fi_fabric_(), which calls rxm_fabric(),
etc...

prov/util: ofi_get_core_info_fabric() must only return core providers

---

include/ofi_util.h
prov/rxm/src/rxm_cq.c
prov/util/src/util_cq.c

The RxM provider have to fill error CQ entry and report it to an user when posted recv buffer is smaller than size of incoming message

prov/rxm: Report FI_ETRUNC error if posted recv buffer isn't large enough

---

include/ofi_iov.h

The program is aborted when `iov_count = 0`, but it has to handled.

common: Fix copy to/from iov functions for iov_count = 0

---

configure.ac

The macro AM_PROG_AS sets CFLAGS="-g -O2" if it has not been set already. This
causes the custom CFLAGS initialization being bypassed if AM_PROG_AS is called
first. Relocate the call to keep the custom initialization effective.

configure: Relocate AM_PROG_AS to avoid incorrect default CFLAGS setting

---

man/fi_psm2.7.md
prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_init.c

Change the default tag layout setting to "auto" which would choose
the best option based on the hints passed to fi_getinfo(). More
specifically, "tag64" is used if "hints->domain_attr->cq_data_size"
is 0, and "tag60" is used otherwise.
The default selection can still be overridden by explicitly setting
FI_PSM2_TAG_LAYOUT to "tag60" or "tag64".

prov/psm2: Enable auto selection of default tag layout

---

src/fabric.c

The provider should be aligned closer with sockets.  Moving after
to account for its early development stage.

prov/tcp: Move tcp provider to last in provider ordering

---

prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_ep.c
prov/psm2/src/psmx2_init.c

The number of "free contexts" is volatile and can't be depended on. Check
the user request against the "total contexts" instead. Let the PSM2 library
be the last and only place to determine if a free context is available.
Report the total number of contexts in "fi_info->domain_attr->max_ep_tx_ctx"
and "fi_info->domain_attr->max_ep_rx_ctx". This provides a static view of
the system limit that can actually be used by the application. Report the
current number of free contexts in "fi_info->domain_attr->tx_ctx_cnt" and
"fi_info->domain_attr->rx_ctx_cnt" to serve as a recommended value.
Remove the artificial limit PSMX2_MAX_TRX_CTXT that is no longer used.

prov/psm2: Improve how Tx/Rx context limits are handled

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_rma.c
prov/util/src/util_av.c

This patch adds mechanism to buffer messages before connection is established between peers.
This mechanism allows fi_[t]inject, fi_[t]send[msg,v] buffer data (or LMT request) and add the TX buffer into postponed queue. When the connection between peers is established, RxM provider goes through postponed queue and if there are any outstanding messages, it just sends them to an appropriate peer.
So, this allows avoid returning `-FI_EAGAIN` from OFI library and avoid burning CPU cycles while polling CQ and busy waiting for the connection to be established. Apps can do some computational work (if possible)

prov/rxm: Implement postponed queue

---

include/unix/osd.h
include/windows/osd.h
prov/tcp/src/tcpx.h
prov/tcp/src/tcpx_comm.c
prov/tcp/src/tcpx_ep.c
prov/tcp/src/tcpx_progress.c
src/windows/osd.c

Currently tcp provider maintains a ring buffer in every send/recv queue entry (pe_entry). A smaller messages gets buffered in the ring buffer before its sent which involves copying multiple times. This results in unnecessary mem copies and mem usage.  This PR gets rid of ringbuffers.
With this PR, tcp provider can try sending each message using scatter-gather sockets calls. so inbest case scenarios, one syscall for sending the whole message (when message < mtu). In case of recv two syscalls for receving (one recv call for reading header and the other for receiving message data. 
For larger messages, tcp provider breaks the iovec appropriately before every call to sendmsg/recvmsg.

prov/tcp Changes to message send/recv functions

---

prov/rxm/src/rxm_ep.c

Setting min_multi_recv_size should be independent of op_flags
follow up from comments in #3811

prov/rxm: fix setting of min_multi_recv_size

---

prov/shm/src/smr.h
prov/shm/src/smr_attr.c
prov/shm/src/smr_ep.c
prov/shm/src/smr_msg.c
prov/shm/src/smr_progress.c
prov/shm/src/smr_rma.c

- enable FI_MULTI_RECV for shm provider
Verified working with streaming/fi_rdm_multi_recv test

prov/shm: enable FI_MULTI_RECV

---

prov/psm/src/psmx.h
prov/psm/src/psmx_domain.c
prov/psm/src/psmx_init.c
prov/psm2/src/psmx2_domain.c
prov/psm2/src/psmx2_init.c

Move some quick checks to the very beginning so that queries that are
apparently unsuitable for the provider will immediately return, thus
avoiding any further steps related to provider initialization.

prov/psm,psm2: Shortcut obviously unsuccessful fi_getinfo() calls

---

prov/sockets/src/sock_av.c

See Issue #3828.
An endpoint maintains a mirror of the associated AV used to map
the AV index to a specific tcp connection.  However, if an
address is inserted into the AV more than once (which happens
in some MPI use cases), there can be multiple mappings from
the endpoints av_idm (AV index map) to a given conn_map
(connection map) entry.
When an AV entry is removed, any connection that references that
entry is also removed.  This results in other av_idm entries that
reference that same connection pointing to a connection that
is no longer usable.
Although this is not a fail safe solution, when an AV entry is
removed, leave any associated connection to that entry connected.
This allows peers to continue sending to the local endpoint.
Instead, simply remove the association from the …

prov/sockets: Fix possible removal of in use connection

---

util/pingpong.c

Some providers require FI_CONTEXT2. This just changes the context parameter in the pingpong test to pass the additional memory. Providers that do not require FI_CONTEXT2, or FI_CONTEXT, will ignore the parameter. Providers that require FI_CONTEXT, but not FI_CONTEXT2, will be ok, too.

util: use FI_CONTEXT2 for pingpong in case a provider requires it

---

configure.ac
include/windows/config.h
src/fi_tostr.c

This patch introduces version suffix that can be applied to the library version by `--with-version_string=<string>`  
Examples on how this works:
1. `$ ./configure --with-version_suffix=RHEL7.4`
`$ fi_info --version`
`/p/pdsd/Users/dgladkov/ofi/bin/fi_info: 1.6.0rc1`
`libfabric: 1.6.0rc1-RHEL7.4`
`libfabric api: 1.6`
2. `$ ./configure`
`$ fi_info --version`
`/p/pdsd/Users/dgladkov/ofi/bin/fi_info: 1.6.0rc1`
`libfabric: 1.6.0rc1`

configure: Introduce version suffix

---

prov/psm2/src/psmx2_ep.c
prov/psm2/src/psmx2_init.c
prov/psm2/src/psmx2_tagged.c

* Improve automatic tag layout selection
* Reduce noise when optimizing tagged message functions
* Fix a bug in fi_tsenddata()

prov/psm2: Bug fix and improvements to tagged message

---

config/cron-run-all-md2nroff.pl

...and it's ok.  If there were no changes, then we want to let the
commit / push "fail" without killing the entire script.

md2nroff.pl: those commands really *can* fail

---

prov/psm2/src/psmx2_msg.c
prov/psm2/src/psmx2_tagged.c
prov/psm2/src/psmx2_trigger.h

Fix incorrect initialization of the receive side completion flags for iov
sends. Detect iov sends that contain only one non-zero length segment and
process them as regular sends. Fix function prototypes.

prov/psm2: Fix minor issues for iov send

---

src/fabric.c

The rxm RDM EP support is more complete than that provided by
the verbs provider.  Move RxM before verbs, so that rxm RDM EPs
will be preferred over verbs.

core: Reorder provider list to move rxm before verbs

---

util/pingpong.c

The pingpong test does not pass the source address with the various send operations and does not specify the FI_DIRECTED_RECV capability bit as a hint to fi_getinfo() accordingly.
However, according to the fi_getinfo man page (circa dcf66b):
> Providers may indicate support for additional capabilities beyond those requested when the use of expanded capabilities will not adversely affect performance or expose the application to communication beyond that which was requested.
An application may not request FI_DIRECTED_RECV but a provider may report that it is available anyway. Unless the application will use the FI_DIRECTED_RECV capability it must clear the FI_DIRECTED_RECV capability bit before creating fi objects (domain, endpoint, etc) otherwise the provider will not ignore the src_addr …

util: clear the FI_DIRECTED_RECV capability bit since the test does not use it

---

prov/psm2/src/psmx2_tagged.c

prov/psm2: Fix fi_trecv() with FI_PEEK for remote CQ data support

---

prov/psm2/src/psmx2_av.c

Two issues have been fixed:
(1) The SEP id was set incorrectly in fi_av_lookup;
(2) Under certain conditions the step to query SEP information could be
skipped and resulted in uninitialized SEP context table.

prov/psm2: Fix address vector issues related to scalable endpoints

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_ep.c

This patch applies changes to the TX/RX functions that initializes/destroys pools and queues
This is a part of #3822 

prov/rxm: Refactor init/destroy functions for TX/RX resources

---

prov/psm2/src/psmx2_am.c
prov/psm2/src/psmx2_av.c
prov/psm2/src/psmx2_ep.c
prov/psm2/src/psmx2_init.c
prov/psm2/src/psmx2_trx_ctxt.c

Always allow the application to ask for FI_AV_MAP or FI_AV_TABLE,
even though it may be forced to FI_AV_TABLE internally.

prov/psm2: Minor tweaks to AV type checking and debugging output

---

man/fi_psm2.7.md

Revise the description of the environment variables FI_PSM2_LAZY_CONN and
FI_PSM2_TAG_LAYOUT.

man: Update psm2 provider man page

---

prov/psm/src/psmx_init.c
prov/psm2/src/psmx2_init.c

These variables are not supposed to change during the run and thus
there is no need to recheck for each fi_getinfo() call.

prov/psm,psm2: Move environment variable reading out from fi_getinfo()

---

prov/hook/src/hook.c
prov/hook/src/hook.h
prov/shm/src/smr_atomic.c

hook_to_hfid can return NULL in the default case.  This is an
unexpected code flow (coding error), but can trigger warnings
from static code analysis tools.  Add an assert to silence them.

prov/hook + shm: Change checks to asserts

---

include/ofi_iov.h
prov/tcp/src/tcpx_progress.c
src/iov.c

App can post buffers larger than anticipated rx size for a rx transaction. To ensure message boundaries, the posted buffer has to be matched with the size of transfer. Otherwise, next message(s) would be read into this buffer advertently.

prov/tcp Bug fix to resize available rx buffers before passing to readv

---

prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_av.c
prov/psm2/src/psmx2_init.c

And turn on FI_THREAD_SAFE support as the result.

prov/psm2: Make address vector operations thread-safe

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c

This PR applies the following changes to the RxM provider:
- Renames `RXM_BUF_POOL_END` enum value to `RXM_BUF_POOL_MAX`
- Use `RXM_BUF_POOL_TX_START` enum value instead of `RXM_BUF_POOL_TX_MSG`
- Add missed log message from LMT_READ to LMT_SENT_ACK for fast ACK send path
- Refactor handling of deferred TX operations

prov/rxm: Refactor handling of defered TX operations

---

prov/usnic/src/usdf_domain.c
prov/usnic/src/usdf_ep_dgram.c
prov/usnic/src/usdf_ep_msg.c
prov/usnic/src/usdf_ep_rdm.c

usNIC doesn't support RMA at the moment so it should not require
FI_MR_PROV_KEY and FI_MR_VIRT_ADDR.
This closes #3871. 

prov/usnic: Remove MR mode bits for RMA.

---

prov/psm2/src/psmx2_attr.c

When these fields are not explicitly specified in hints (absent or
with value 0), use default value 1 instead of the number of available
contexts to prevent applications from unintentionally asking for too
many contexts when opening scalable endpoints with default settings.
System resource limits are returned via similar fields in "domain_attr"
so no information is lost.

prov/psm2: Fix ep_attr->tx_ctx_cnt/rx_ctx_cnt returned by fi_getinfo

---

include/ofi_mr.h
include/rdma/fabric.h
include/rdma/providers/fi_prov.h
prov/util/src/util_mr_cache.c
prov/verbs/src/fi_verbs.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_domain.c
prov/verbs/src/verbs_mr.c
src/var.c

This PR adds the following updates to the core, utility, verbs code:
- core: New type of runtime params - `FI_PARAM_LONG`
- utility:
Implement MR caching limitation with a total cached size;
Change type of counters from `uint64_t` to `size_t` to align with their thresholds
- verbs:
Remove `FI_VERBS_MR_CACHE_LAZY_SIZE` variable
Rename `FI_VERBS_MR_CACHE_SIZE` to `FI_VERBS_MR_MAX_CACHED_CNT`
Add `FI_VERBS_MR_MAX_CACHED_SIZE` variable

core, verbs: Implement MR caching limitation with a total cached size

---

prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_ep.c
prov/psm2/src/psmx2_trx_ctxt.c

The hardware contexts allocated by PSM2 always have both Tx and Rx
capability. Previously, endpoints (or STX context) that only need Tx
or Rx would still consume full hardware contexts, wasting half of the
capability. Applications using separate Tx and Rx endpoints would
consume more hardware contexts than those using combined Tx and Rx
endpoints.
This patch allows the unused Tx or Rx capability of existing contexts
be used for new endpoints that only need Rx or Tx capability.

prov/psm2: Allow contexts be shared by Tx-only and Rx-only endpoints

---

include/ofi_util.h
prov/rxm/src/rxm_ep.c
prov/util/src/util_av.c

This patch addresses comments that are received in the #3822:
- Split `ofi_cmap_get_handle` into two calls - 'acquire' handle and handling of CMAP state
- Refactor OFI/RxM provider's unconnected TX operations handling

 prov/rxm, util/av: Refactor unconnected TX op handling

---

prov/psm2/src/psmx2_ep.c

When no specific HFI unit is asked for, round-robin assignment is used
for scalable endpoint context allocation. Previously such assignment was
also accidentally applied to regular endpoints and could cause the first
HFI unit being always used for all regular endpoints.
Bypass the round-robin assignment for regular endpoints, shared Tx contexts,
and scalable endpoints with a single context.

prov/psm2: Fix incorrect application of round-robin HFI unit assignment

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_domain.c
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_rma.c

- The 1st pathc applies some minor refactoring to RxM's RMA transport.
Some code is moved into common functions that will be re-used for implementing postponed queue for RMA
- The 2nd patch adds implementation of postponed queue for RMA operations

prov/rxm: Implement postponed queue for RMA operations

---

prov/rxm/src/rxm_rma.c

prov/rxm: Fix crash in fi_writemsg for inject path

---

include/ofi_shm.h
prov/shm/src/smr.h
prov/shm/src/smr_atomic.c
prov/shm/src/smr_attr.c
prov/shm/src/smr_comp.c
prov/shm/src/smr_ep.c
prov/shm/src/smr_init.c
prov/shm/src/smr_progress.c

- update domain_attr->caps to FI_LOCAL_COMM
- update max_order_sizes in ep_attr
- add atomic fetch support when fast_rma support is not enabled
See commit messages for more details. All tests in test_configs/shm/all.test and test_configs/shm/verify.test verified passing with these updates

prov/shm: various attr updates and atomic fetch without fast_rma support

---

prov/verbs/configure.m4

The configure checks are failed for the verbs provider if the rsockets isn't available
This fix is to check rdma/rdma_cma.h header file instead rdma/rsocket.h

prov/verbs: Fix config check for librdmacm

---

include/ofi_shm.h
prov/shm/src/smr_av.c
prov/util/src/util_av.c
prov/util/src/util_shm.c
prov/verbs/src/ep_dgram/verbs_dgram_av.c

- removing an address from the AV requires:
- unmapping the region and removing it from the av->map
- unmapping the region from the peer endpoint to mark that it is not in the AV which requires the addition of a new function smr_unmap_from_endpoint to counter the smr_map_to_endpoint call
- note that this patch moves the av lock acquire/release to outside the util av_remove function because the smr_av->map is protected by the av->lock as well. This mirrors the requirment in the util av_insert call which requires the lock to be held before calling the function
- changed this in the two other calls to this function to be holding the lock before calling it (in prov/util/src/util_av.c and prov/verbs/src/ep_dgram/verbs_dgram_av.c)
Verified passing fi_av_xfer test
Signed-off-by: aingerson …

prov/shm: implement fi_av_remove

---

prov/sockets/include/sock.h
prov/sockets/src/sock_cntr.c
prov/sockets/src/sock_cq.c
prov/sockets/src/sock_progress.c

Sockets emulates the functionality of a scalable endpoint over a
single TCP socket.  As a result, data from multiple transmit/
receive contexts can show up in any order on the socket.
If the application polls a CQ associated with a specific rx
context, but data is at the head of the socket for a different
rx context, the CQ polling can get stuck unable to proceed.  This
can result in the application hanging.
To fix this, we need to progress any associated rx context that
is using the same underlying socket.
Fixes #3886

prov/sockets: Progress all rx contexts for a scalable endpoint

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_ep.c
prov/util/src/util_wait.c

This patch contains the following bug fixes and optimizations:
- Adds printing of FD in util/wait code
- Removes excessive line and excessive semicolon
- Binding CNTR to EP passes wrong file descriptor, if CQ is opened and bound w/o wait object, but CNTR is opened w/ wait object
- E.x. an user opens single completion counter and binds with flags `FI_READ` and `FI_WRITE`, `util_ep::rd_cntr` and `util_ep::wr_cntr` point to the same cntr. `ofi_wait_fd_del` is called multiple time for the same `counter->wait`

prov/rxm: Fix multiple deletion of the same wait object

---

prov/psm2/src/psmx2_init.c

(1) Variable "use_tag64" could be used uninitialized.
(2) Format mismatch in FI_INFO.

prov/psm2: Fix compilation warnings

---

prov/rxm/src/rxm_ep.c

This patch removes the redundant allocation of TX resources for the defered send requests.
The issue was introduced in the #3796 PR

prov/rxm: Fix multiple TX resource allocation

---

prov/rxm/src/rxm_rma.c

This patch just renames `rxm_ep_postponed_rma` to `rxm_ep_postpone_rma`

prov/rxm: Rename internal function

---

include/ofi_signal.h
prov/sockets/include/sock.h
prov/sockets/src/sock_conn.c
prov/sockets/src/sock_dom.c
prov/sockets/src/sock_ep.c
prov/sockets/src/sock_ep_msg.c
prov/sockets/src/sock_progress.c
prov/udp/src/udpx_ep.c
prov/util/src/util_wait.c
src/common.c

Hi Libfabric's team!
I have been using Libfabric in my company (DDN Storage) for the last year.
I have already contributed from time to time to the Verbs/socket/PSM2 providers. Today I come up with a pretty long patch series that mainly focuses on improvements/fixes to the socket provider.
The general goal of this patch series is to fix scalability issues in the socket's connection manager.
With the current code, libfabric requires the creation of 1 POSIX thread and 2 file descriptors (socketpair, to signal any connection thread blocked in epoll_wait()) per connection.
This patch series completely rewrites this connection manager.
The general idea of the new code is the following: one connection manager (CM) thread is created per OFI domain, which is responsible for progressing connection …

prov/sockets: new code for the connection manager for improved scalability

---

include/ofi_util.h
prov/rxd/src/rxd_av.c
prov/rxm/src/rxm_domain.c
prov/rxm/src/rxm_init.c
prov/util/src/util_av.c
prov/verbs/src/ep_dgram/verbs_dgram_av.c

- prov/util: use a separate flag to determine if we need to create av hash table
- prov/rxm: use ip_av_create_flags
- prov/rxm: don't include FI_DIRECTED_RECV, FI_SOURCE caps if they're not needed

prov/util,rxm: optimizations

---

man/fi_mlx.7.md
prov/mlx/src/mlx_fabric.c
prov/mlx/src/mlx_init.c

This patch drops redundant `mlx` prefix to avoid `FI_MXL_MLX_...` name of knob

prov/mlx: Drop redundant mlx prefix from knob names

---

man/fi_sockets.7.md
prov/sockets/src/sock_fabric.c

This patch changes the name of knob and declares the knob in the sockets man page

prov/sockets: Rename interface name knob

---

man/fi_mlx.7.md
prov/mlx/src/mlx_cm.c

This patch fixes the following:
- Compiler warning
- misprint in man page that was introduced in #3914

 prov/mlx: Fix compiler warning

---

prov/rxm/src/rxm_ep.c

Fixes Coverity scan issue ([CID 264629](https://scan4.coverity.com/reports.htm#v27196/p10344/fileInstanceId=37919712&defectInstanceId=6984677&mergedDefectId=264629))

prov/rxm: Fix read from pointer after free

---

prov/rxm/src/rxm_ep.c

Fixes Coverity scan issue (CID 264629)
See #3927

prov/rxm: Fix read from pointer after free (cheery-pick onto v1.6.x branch)

---

util/pingpong.c

Fixes Coverity scan issue ([CID 264626](https://scan4.coverity.com/reports.htm#v27196/p10344/fileInstanceId=37919729&defectInstanceId=6984675&mergedDefectId=264626))

pingpong: Remove unnecessary NULL-checking for hints

---

include/rdma/fi_domain.h

Fixes issue #3935.  MSVC++ cannot handle gcc initializers.

include/rdma: Fix C++ compile for msvc++

---

include/rdma/fi_domain.h
prov/sockets/src/sock_cntr.c

As part of updating a counter, an associated deferred work queue
is checked.  For example, sock_cntr_add() calls
sock_cntr_check_trigger_list() after the counter has been updated.
If an application is waiting on the counter to reach a specific
threshold, it can see that the counter has been set, then attempt
to free the counter, endpoint, and other resources.  This leads
to a condition where the checking of the trigger list may be
called after the counter has been freed.
There's not a great fix for this.  To help avoid potential use
after free issues, hold the counter mutex around the call to
check the trigger list.  Then in destroy acquire and release the
mutex.  This ensures that destroy block until counter updates
have fully completed.
This fixes a crash in MPI as a result of …

prov/sockets: Fix use after free error handling triggered ops

---

prov/util/src/util_av.c

This patch fixes problem when the same address is inserted into AV multiple times.
If the AV contains some address and this address is inserted again, the AV has to return already allocated index and don't allocate any additional resources/indices for this address.

util/av: Fix handling of double insertion of the same address

---

prov/util/src/util_av.c

Fixes Coverity scan issue CID [266178](https://scan4.coverity.com/reports.htm#v27196/p10344/fileInstanceId=38219678&defectInstanceId=7036389&mergedDefectId=266178)

util/av: Handle possible incorrect slot value

---

prov/util/src/util_av.c

This is picked up from #3945 for the stable v1.6.x branch

util/av: Handle possible incorrect slot value (for v1.6.x)

---

src/tree.c

Fixes Coverity scan issue - CID [264630](https://scan4.coverity.com/reports.htm#v27196/p10344/fileInstanceId=38114255&defectInstanceId=7013005&mergedDefectId=264630)

common/tree: Fix Red-Black tree balance

---

configure.ac

configure.ac: ensure that all the debug compiler flags work

---

prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_attr.c
prov/psm2/src/psmx2_cq.c
prov/psm2/src/psmx2_ep.c

The function is used to process request queues associated with large size
RMA and triggered ops. Previously the initialization of the AM mechanism
was used as the condition to call this function. Since the AM mechanism is
now also used for non-RMA functionality, the condition has become overly
broad and could cause the function be called unnecessarily.
Change the condition to be the presence of FI_RMA or FI_TRIGGERED caps in
the associated endpoints.

prov/psm2: Avoid unnecessary calls to psmx2_am_progress()

---

prov/util/src/util_av.c

We shouldn't check `slot` value for AV when `OFI_AV_HASH` isn't set.
This patch fixes this issue
Fixes #3951

util/av: Don't check slot value if OFI_AV_HASH isn't set

---

prov/util/src/util_av.c

We shouldn't check `slot` value for AV when `OFI_AV_HASH` isn't set.
This patch fixes this issue

util/av: Don't check slot value if FI_SOURCE isn't set (for v1.6.x)

---

configure.ac

This patch removes -DNDEBUG flag for debug build to fix compiler warning and to make `assert` executable
This is an example of warning:
```
In file included from ./include/ofi.h:49:0,
from src/iov.c:37:
./include/ofi_lock.h: In function ‘fastlock_destroy’:
./include/ofi_lock.h:92:6: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
int ret;
^~~
./include/ofi_lock.h: In function ‘fastlock_acquire’:
./include/ofi_lock.h:102:6: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
int ret;
^~~
./include/ofi_lock.h: In function ‘fastlock_release’:
./include/ofi_lock.h:117:6: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
int ret;
^~~
libtool: compile:  /p/pdsd/opt/EM64T-LIN/compilers/gnu/gcc-7.1.0/bin/gcc -DHAVE_CONFIG_H -I. -I./include …
```

config: Remove -DNDEBUG flag for debug build

---

prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_cq.c
prov/verbs/src/verbs_msg_ep.c

This patch makes all Send Requests signaled.
Internal Send Requests will have `wr_id` set to 0.
This addresses performance issue for critical path when the unsignaled send count reaches `max_send_wr`. When verbs provider reaches the threshold of unsignaled send count, it send the next Send Request as signaled and polling to receive CQ entry for this.

prov/verbs:  Make all send requests signaled

---

configure.ac

config: Remove NDEBUG for debug build (for v1.6.x)

---

include/ofi_util.h
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_rma.c
prov/util/src/util_av.c

This patch applies some minor performance optimizations to util/av code that allows RxM refactor handling case of unconnected EPs

prov/rxm, util/av: Minor optimizations for acquiring connection info

---

prov/rxm/src/rxm_rma.c

Fixes Coverity scan issue - CID [266480](https://scan4.coverity.com/reports.htm#v27196/p10344/fileInstanceId=38650744&defectInstanceId=7111874&mergedDefectId=266480)

prov/rxm: Fix coverity issue

---

include/unix/osd.h
include/windows/osd.h
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_domain.c
prov/verbs/src/verbs_mr.c

This patch moves functions for memory hooks to OS dependency code for Unix and Windows from verbs provider code.
This allows for other providers re-use this common code.

 common/osd, prov/verbs: Move getters/setters of Memory hooks to common code

---

include/ofi_util.h
prov/util/src/util_av.c

This fixes handling of multiple deletion of the same address.
The idea of this patch is the following:
- When an user inserts the address, AV functionality increments the
`use_cnt` value for this entry in AV hash table.
- When an user removes the address, AV functionality decrements the
use_cnt value for this entry in AV hash table. If the `use_cnt`
`value == 0`, the entry is deleted.

util/av: Handle the deletion of the same address multiple times

---

include/ofi_util.h
prov/util/src/util_av.c

This fixes handling of multiple deletion of the same address.
The idea of this patch is the following:
- When an user inserts the address, AV functionality increments the `use_cnt` value for this entry in AV hash table.
- When an user removes the address, AV functionality decrements the `use_cnt` value for this entry in AV hash table. If the `use_cnt` value == 0, the entry is deleted.

util/av: Handle the deletion of the same address multiple times (for v-1.6.x)

---

configure.ac
include/unix/osd.h

Older versions of icc and gcc do not support this intrinsic.  Sigh

cherry-picked  build: Check for presence of __cpuid_count

---

prov/netdir/src/netdir_ndinit.c

prov/netdir: Fix crash in the ND init

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_rma.c

This PR does the following:
- Fixes problem for deffered non-inject RMA write and RMA read. The I/O vectors are not filled.
- Makes internal MR regv and closev function inline.

 prov/rxm: Fill I/O vector for deffered RMA write/read

---

prov/util/src/util_av.c

util/av: Fix crash in the fi_av_remove if FI_SOURCE isn't specified

---

prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_rma.c

prov/rxm: Fill I/O vector for deffered RMA write/read (v1.6.x)

---

configure.ac
include/ofi_atom.h

Fixes #3982 
with added checks the output of configure looks as follows:
```
checking compiler support for c11 atomics... yes
checking compiler support for c11 atomic `least` types... no
checking compiler support for built-in atomics... yes
```

configure: Fix compilation failure with icc 18

---

include/ofi_iov.h
include/ofi_mr.h
prov/util/src/util_mr_cache.c
prov/verbs/src/fi_verbs.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_domain.c

This PR consists from the following patches:
- Implement MR caching way w/o the merging regions
- Updated verbs provider to be able switching between different ways. Disabled merging entries is the default one
- Allocate MR entries from pool

util/mr_cache: Implement MR caching w/o the merging regions

---

prov/psm2/src/psmx2_msg.c
prov/psm2/src/psmx2_tagged.c

The iov limit was checked in sendv but not sendmsg. Add the check
to ensure consistent error handling.

prov/psm2: Check iov limit in sendmsg

---

prov/sockets/src/sock_progress.c

Fixes #3979.
This patch fixes out of boundary access for `rx_array` and `tx_array`.
These arrays are allocated [here (for example rx_array)](https://github.com/ofiwg/libfabric/blob/7bb4d2307cdd41ebebbf0ed1fb8d99fc18a76c54/prov/sockets/src/sock_ep.c#L1742)
Signed-off-by: Anatoliy Rozanov <anatoliy.rozanov@intel.com>

prov/sockets: Fix segfault in sockets provider

---

prov/verbs/src/ep_rdm/verbs_rdm_cm.c
prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm.c

This fixes the following warnings that only occur with ICC 18:
```
prov/verbs/src/ep_rdm/verbs_rdm_cm.c(527): warning #279: controlling expression is constant
assert(0 && "Wrong state");
prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm.c(561): warning #279: controlling expression is constant
assert("Error recv wc\n" &&
```

prov/verbs: Fix ICC 18 warnings

---

prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_cq.c

The `fi_ibv_poll_cq` can easily be `static inline`

prov/verbs: Make fi_ibv_poll_cq static inline

---

prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_cq.c

Check if the CQ has been signaled when waiting inside fi_cq_sread
and allow early return when the condition is true.
(Cherry-picked from commit 054913b1817154fa5351eaf5539ab00c7956e790)

prov/psm2: Cherry-picked fix for branch v1.5.x

---

prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_cq.c
prov/verbs/src/verbs_msg_ep.c

This patch reduces # of instructions before `ibv_post_send`, i.e. before data is passed on a wire.
But total amount of instructions is the same as previous.
This should improve receive side, because we will do polling (if needed) after data is passed on a wire. i.e. receiver should receive data a bit earlier than it was in the previous realization. Is it viable?

prov/verbs: Move CQEs polling after calling of ibv_post_send

---

include/ofi_util.h
prov/rxm/src/rxm.h
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c
prov/util/src/util_domain.c

This PR improves latency for RxM provider by removing locks for Send/Recv queue and Tx/Rx resources from critical send and receive paths
MPICH/CH4/OFI/RxM/verbs results:
bytes | master | #3989
-- | -- | --
0 | 1.19 | 1.17
1 | 1.19 | 1.17
2 | 1.18 | 1.17
4 | 1.18 | 1.17
8 | 1.19 | 1.17
16 | 1.19 | 1.17
32 | 1.19 | 1.17
64 | 1.22 | 1.21

prov/rxm: Use locks for EP resources if FI_THREAD_SAFE is requested

---

prov/rxm/src/rxm_init.c

prov/rxm: Pass threading level from hints to core provider

---

include/ofi_lock.h
include/ofi_util.h
prov/rxm/src/rxm.h
prov/rxm/src/rxm_ep.c
prov/util/src/util_cq.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_cq.c
prov/verbs/src/verbs_eq.c
prov/verbs/src/verbs_msg_ep.c
prov/verbs/src/verbs_srq.c

This patch applies optimizations for verbs provider (only CQ and WRE handling) and util/cq like #3992 for rxm provider.

util/cq, prov/verbs: Use locks only if needed threading level set

---

prov/verbs/src/ep_dgram/verbs_dgram.h
prov/verbs/src/ep_dgram/verbs_dgram_ep_msg.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_msg_ep.c
prov/verbs/src/verbs_srq.c

This patch removes `FI_IBV_INVOKE_POST` macro for MSG and DGRAM code that was requested in some previous PR for verbs

prov/verbs: Remove fi_ibv_invoke_post macro

---

prov/verbs/src/fi_verbs.c

This fixes bug introduced in #3999 

prov/verbs: Fix handling of device presets

---

prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_cq.c

Under rare condition, it was possible that completions were generated
by both the iov message header and the message body. Fix by counting
the header together with the body before generating completion.
Also make sure iov send completions have tag set in a way consistent
with non-iov sends, even though it is not required by the API.

prov/psm2: Fix potential duplication of iov send completion

---

prov/rxm/src/rxm_cq.c

This fixes matching of the I/O vectors for RMA
The error occurs if a posted (receive) I/O vector is large enough to contain I/O vector(s) that will be gathered from remote side.
We should adjust `offset` by adding `iov_len` while we can fill the same posted I/O vector.

prov/rxm: Fix matching for RMA I/O vectors

---

prov/rxm/src/rxm_cq.c

This is a back-port of #4009 for v1.6.x stable branch

prov/rxm: Fix matching for RMA I/O vectors (for v1.6)

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_rma.c

This patch fixes deferred RMA operations.
RxM has to use its own pre-allocated storage for RMA I/O vectors instead of I/O vector from `fi_msg_rma` structure that passed to the `fi_read`/`write` function.

prov/rxm: Fix deferred RMA operations

---

man/fi_mr.3.md

The intent is to match the behavior of fi_getname() wrt who
allocates and owns the raw_key buffer.  But this was not
defined in the man pages.
Fixes #4018

man/mr: Clarify how to use the fi_mr_raw_attr function

---

prov/psm2/src/psmx2_av.c
prov/psm2/src/psmx2_trx_ctxt.c

When a PSM2 endpoint is involved in many-to-many connection, closing the
endpoint can be very slow. The workaround is to explicitly disconnect all
connections related to the endpoint before calling psm2_ep_close.

prov/psm2: Avoid long delay in psm2_ep_close

---

prov/psm2/src/psmx2_trx_ctxt.c

The call to psm2_ep_disconnect may fail with timeout, leaving the
endpoint in a state that fails an assertion inside psm2_ep_close.
Fix by making the disconnection call with the "force" flag.

prov/psm2: Fix occasional assertion failure in psm2_ep_close

---

include/ofi_util.h
prov/rxm/src/rxm_cq.c
prov/util/src/util_cq.c

This PR prepares small optimizations and reduces ~10 instructions in the code that is responsible to handle CQ entries

  util/cq, prov/rxm: Reduce instruction counts

---

prov/verbs/src/verbs_eq.c

Errors returned in RDMA CM events are expected to be negative,
but libfabric sometimes assumes they are positive.
This cause eq->err.err to contain negative error codes, while
only posistive error codes are expected.
The patch ensures that eq->err.err contains a positive error
code for the the following RDMA CM events:
RDMA_CM_EVENT_ADDR_ERROR
RDMA_CM_EVENT_ROUTE_ERROR
RDMA_CM_EVENT_CONNECT_ERROR
RDMA_CM_EVENT_UNREACHABLE

prov/verbs: eq->err.err must return a positive error code

---

prov/verbs/src/verbs_eq.c

Errors returned in RDMA CM events are expected to be negative,
but libfabric sometimes assumes they are positive.
This cause eq->err.err to contain negative error codes, while
only posistive error codes are expected.
The patch ensures that eq->err.err contains a positive error
code for the the following RDMA CM events:
RDMA_CM_EVENT_ADDR_ERROR
RDMA_CM_EVENT_ROUTE_ERROR
RDMA_CM_EVENT_CONNECT_ERROR
RDMA_CM_EVENT_UNREACHABLE

 prov/verbs: eq->err.err must return a positive error code (for v1.6.x)

---

include/ofi_proto.h
prov/rxm/src/rxm.h
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c

This PR consists of the following patches:
- **common/proto: Add new type of message**
The new message type will be used in SAR (Segmentation And Reassembly)
protocol for message transfers
- **prov/rxm: Move CQ handling functions to common code**
This patch moves rxm_cq_log_comp() and rxm_finish_send_nobuf()
functions to rxm.h header file for further re-use across RxM
source code.
This will be needed for SAR protocol implementation.
- **prov/rxm: Optimize function that handles RX buffers**
The rxm_cq_handle_data() function is getting long. Handling of
message type that is being added makes the function longer.
The function was renamed to rxm_cq_handle_rx_buf() to reflect its
intent better. So, rxm_cq_handle_rx_buf() uses switch-case statement
to call an appropriate function:
- …

 prov/rxm: Various optimizations to the provider

---

prov/tcp/src/tcpx_conn_mgr.c
prov/tcp/src/tcpx_cq.c
prov/tcp/src/tcpx_ep.c
prov/tcp/src/tcpx_progress.c

I've been reading code for prov/tcp the last few days and I've found some bugs, which I address in this PR.
@vkrishna, can you please review these patches when you have time? Thank you!
PS: the new code for tcpx is way easier to read than the sockets provider! 
Regards,
Sylvain

prov/tcp: few fixes/optimizations to the provider

---

prov/rxm/src/rxm.h

The fi_tostr expects pointer to the uint64_t, but rxm passes
the value of uint64_t and casts it to (void *).
The fix is to pass pointer to value of uint64_t instead.
This bug was added in #4031 PR

prov/rxm: Fix crash with log level = debug

---

prov/tcp/src/tcpx_conn_mgr.c
prov/tcp/src/tcpx_progress.c

prov/tcp: fixing the usage of fi_eq_write

---

prov/verbs/src/ep_dgram/verbs_dgram.h
prov/verbs/src/ep_dgram/verbs_dgram_cq.c
prov/verbs/src/ep_dgram/verbs_dgram_ep.c
prov/verbs/src/ep_dgram/verbs_dgram_ep_msg.c

Fixes #4038
This patch removes usage if unsignaled sends from verbs/DGRAM as it is already done for verbs/MSG.
And there were places when verbs/DGRAM did `util_buf_release` twice for the same allocated buffer

prov/verbs: Makes all sends signaled

---

include/ofi.h
include/ofi_util.h
prov/mrail/src/mrail_init.c
prov/rxm/src/rxm_fabric.c
prov/util/src/util_attr.c
src/common.c
src/fabric.c

This patch enables layering utility providers on top of each other. This allows providers like ofi_mrail (multi-rail) to layer over ofi_rxm provider.
- Ordering would be enforced if `hints->fabric_attr->name` lists more than two providers. The rightmost provider would be the top layer.
- Otherwise the existing behavior of not checking the order is maintained.
- The patch also allows excluding providers with a caret symbol - `^`. This is for internal use only and enables an utility provider to not layer over itself or certain other providers. Excluded providers should be listed at the end.
This PR is WIP and needs some more changes around `ofix_getinfo`.

common: allow layering more than one utility provider

---

prov/rxm/src/rxm_cq.c

This function is pretty small to be `static inline`.
This commit was a part of #4032 PR

prov/rxm: Make rxm_finish_send static inline

---

man/fi_rxm.7.md
prov/rxm/src/rxm.h
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_init.c

This patch updates initialization routine of RxM provider
to define FI_OFI_RXM_SAR_LIMIT environment variable.
The value of this parameter is stored in objects of the rxm_ep
structure (RxM EPs).
If the passed value is less than min(FI_OFI_RXM_SAR_LIMIT;
sizeof(struct rxm_pkt)) (i.e. RxM inject size), then the SAR protocol
wouldn't be used. If the value isn't passed, the SAR limit is set to
the default one (256 Kb = 262144 bytes).
This patch add description of this variable to the fi_rxm(7) man page.
Also this patch appliesminor updates to the description of
FI_OFI_RXM_BUFFER_SIZE variable in both the source code and the man page.

prov/rxm: Add run-time parameter for SAR protocol

---

prov/rxm/src/rxm.h

This patch add new protocl mstate - RXM_SAR_TX - that would be used
by SAR protocol to send segments to peer.

prov/rxm: Add new protocol state

---

prov/rxm/src/rxm_rma.c

This path is only used when the first operation done with the endpoint
is an RMA operation.
Thanks go to @a-ilango for figuring it out!

prov/rxm: Fix desc field when postponing RMA ops.

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_ep.c

This PR does the following:
- prov/rxm: Update TX/RX entry for SAR protocol needs
The commit applies the following updates to structures:
- TX entry with new fields that are related to SAR protocol:
`segs_left` - current remained (not completed) count of segments
`msg_id` - message identifier
`in_flight_tx_buf_list` - the list of TX buffers tht contains buffer
that aren't completed yet, but already sent
`rxm_iov` - I/O vectors
`iov_offset` - current offset across all I/O vectors
- RX entry wth new fields that are related to SAR protocol:
`total_recv_len` - current total recv size
`msg_id` - value that is used to match correct RX buffers to the
RX entry
- prov/rxm: Use separate buffer pool for SAR protocol
Added necessary updates to use separate buffer pool for SAR protocol needs

prov/rxm: Updates structures and add separate pool for SAR

---

Makefile.am
include/ofi.h
include/ofi_perf.h
libfabric.vcxproj
libfabric.vcxproj.filters
prov/hook/src/hook.c
prov/hook/src/hook.h
prov/hook/src/hook_av.c
prov/hook/src/hook_cntr.c
prov/hook/src/hook_cq.c
prov/hook/src/hook_domain.c
prov/hook/src/hook_ep.c
prov/hook/src/hook_eq.c
prov/hook/src/hook_perf.c
prov/hook/src/hook_perf.h
prov/hook/src/hook_wait.c
src/fabric.c
src/perf.c

This series expands the hooking provider and enables it.  It allows the ability to hook all calls to a provider in order to capture data or modify the calls.  It adds the ability to capture performance data (from the PMU) for all msg, rma, and tagged operations.  Hooking is controlled via environment variables (updates to the man pages to document them are still needed).
For now, performance data is limited to CPU cycle or instruction counts.  Future additions can expand this.
Hooking works with most fabtests.  However, hooking will not work with triggered operations of any kind.
There are a couple of additional enhancements that I need to make, but this series is already getting long and should be good enough to continue building off of.

Enable ability to hook provider calls

---

NEWS.md
include/ofi_iov.h
include/ofi_mr.h
prov/util/src/util_mr_cache.c
prov/verbs/src/fi_verbs.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_domain.c

This is back-port of #3974 
This fixes some boundary cases for MPI ring-based algorithm on large data

util/mr_cache, prov/verbs: Implement new MR caching path w/o merging regions (for v1.6.x)

---

prov/psm2/src/psmx2_cq.c

In a typical usage model applications call fi_cq_read in a loop to poll
completions. This would put PSM2 polling action inside a nested loop
because PSM2 is polled in a loop inside fi_cq_read. Such nested polling
has shown negative performance impact on some platforms. Remove the loop
inside fi_cq_read to avoid the issue.

prov/psm2: Avoid polling PSM2 in a nested loop

---

prov/rxm/src/rxm_cq.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_cq.c

This patch applies minor optimizations for verbs and rxm provider wrt reduce instructions count for RxM/verbs stack

 prov/verbs, rxm: Reduce instruction count

---

prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_cq.c
prov/verbs/src/verbs_domain.c
prov/verbs/src/verbs_msg_ep.c

This patch enables usage of utility CQ for verbs provider.
This is used to control flags, thread level, references.

prov/verbs: Use utility CQ for implementation of verbs CQ

---

prov/util/src/util_av.c
src/fabric.c

This is a back-port of #4067 for v1.6.x branch

prov/util: Use variable to control AV addr size (for v.1.6.x)

---

prov/verbs/src/verbs_cq.c

The utility ofi_cq_init expects that progress routine is not a NULL.
verbs doesn't uses this, therefore it passes NULL as the progress
routine.The problem is fixed by passing non-operation callback that
isn't used by utility CQ.

prov/verbs: Fix CQ progress engine initialization

---

prov/sockets/src/sock_msg.c

I forgot to sign my commit in the previous PR I made, so I closed that one and made a new one. This is intended as a fix for #4040.

prov/sockets: Fix accessing msg's iovec without checking its length

---

prov/sockets/src/sock_msg.c

Fixes code formatting issues from patch:
prov/sockets: Fix accessing msg's iovec without checking its length

prov/sockets: Fixup formatting from commit f2118d27

---

prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_cq.c
prov/verbs/src/verbs_msg_ep.c

This PR does the following:
- prov/verbs: Refer to CQ from EP through utility CQ
It optimizes verbs provider from usage of its own lock and pointer to Send/Recv CQs from verbs EP.
Now verbs uses Send/Recv CQ from utility EP that doesn't add any overhead for critical path. CQ::lock is used from utility CQ code that allows us to remove excessive lock from verbs code,

prov/verbs: Refer to CQ from EP through utility CQ

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_ep.c

Fix a bug where received messages whose source hasn't been determined
were matching with directed receives.

prov/rxm: fix a bug in matching directed receives

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_ep.c

Fix a bug where received messages whose source hasn't been determined
were matching with directed receives.

[v1.5.x] prov/rxm: fix a bug in matching directed receives

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_ep.c

Fix a bug where received messages whose source hasn't been determined
were matching with directed receives.

[v1.6.x] prov/rxm: fix a bug in matching directed receives

---

prov/verbs/src/verbs_dgram.h
prov/verbs/src/verbs_dgram_ep.c
prov/verbs/src/verbs_dgram_ep_msg.c

This patch is a part of PRs that merge MSG EP with DGRAM EP.
This commit removes `struct fi_ibv_dgram_ep`

prov/verbs: Use common EP structure for DGRAM EP

---

prov/verbs/src/verbs_cq.c

prov/verbs: Fix usage of util/CQ lock when util/CQ has been destroyed

---

prov/psm2/src/psmx2_fabric.c
prov/psm2/src/psmx2_trx_ctxt.c

This fixes the fi_ubertest error:
ft_recv_test_info(): ../complex/ft_main.c:673, ret=-107 (Transport endpoint
is not connected)
The cause of the error is shown in the following log message:
libfabric:psm2:core:psmx2_trx_ctxt_alloc():273<warn> number of Tx/Rx contexts
exceeds limit (24).

prov/psm2: Reset Tx/Rx context counter when fabric is initialized

---

include/ofi_util.h
prov/rxm/src/rxm_cq.c
prov/util/src/util_av.c

- prov/util: add a provider specific update function as part of cmap_update
- prov/rxm: update unexpected messages when app inserts a new AV address

prov/rxm: update unexpected messages and re-process recvs on AV insert

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_init.c

This significantly improves latency (~10%), but increase memory consumption
This isn't optimal scheme on a large scale.
We need to implement automatic decision whether we have to use SRX instead. It should be done based on how many process will be run (use PMI in the AV?).

 prov/rxm: Disable usage of SRX by default

---

prov/rxm/src/rxm_conn.c

Such situtation may happen only when an application issues transmit operations
that are deffered and then completed when the connection is successfully
established.

prov/rxm: Fix bug when saved msg EP wasn't destroyed

---

prov/mrail/src/mrail.h
prov/mrail/src/mrail_init.c

Also use the OFI prefix macro for provider name.

prov/mrail: set passthrough modes when calling fi_getinfo for underlying provider

---

include/rdma/fabric.h
include/rdma/fi_endpoint.h
include/rdma/fi_tagged.h
man/fi_cq.3.md
man/fi_endpoint.3.md
man/fi_getinfo.3.md
man/fi_msg.3.md
src/fi_tostr.c

This bit separates out part of the FI_VARIABLE_MSG feature.
As a mode bit, providers that must provide receive side
buffering can report receive completions to applications
by referencing their buffers directly.  This avoids a
data on the receive side.  The rxm and rxd providers both
can use this function with applications that support the
new mode bit.
Most of the description for FI_BUFFERED_RECV is taken
from the FI_VARIABLE_MSG definition.  However, some
modifications are made to that definition based on
mapping to implementation details.

fabric: Introduce new mode bit FI_BUFFERED_RECV

---

include/ofi_osd.h
include/ofi_util.h
prov/rxm/src/rxm.h
prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_rma.c
prov/util/src/util_av.c

This PR improves instructions flow for TX/RX and RMA paths 
- The 1st commit:
Add run-time endiannes detector. This approach allows to detect 4 different endian byte format.
- The 2nd commit:
prov/rxm: Check RXM op version two peers during connection establishment procedure
- The 3rd commit:
prov/rxm: Check endianness of two peers during connection establishment procedure
- The 4th commit:
The pkt::hdr::flags can be set only to FI_REMOTE_CQ_DATA, because RxM handles.
Increment OP version to ensure wire protocol compatibility 
only this flag on receiver side.
- The 5th commit:
An allocation of connection handle gives an opportunity to remove
check for NULL on critical path.
So, we can easily use rxm_conn converted from handle when performing
send or rma operation.
Signed-off-by: Dmitry …

prov/rxm: Reduce instructions on critical path

---

prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_atomic.c
prov/psm2/src/psmx2_rma.c

Applications like MPI may aggregate a sequence of RMA operations and
issue them in a batch (e.g. via MPI_Win_flush). A limitation in the AM
implementation of the PSM2 library can lead to sudden performance drop
for such aggregated RMA operations. A workaround is provided here to
prevent the limitation from being triggered.

prov/psm2: Fix irregular performance drop for aggregated RMA operations

---

prov/rxm/src/rxm_conn.c

fi_eq.3 man page says:
A connection request (FI_CONNREQ) event indicates that a remote endpoint
wishes to establish a new connection to a listening, or passive, endpoint.
The fid is the passive endpoint. Information regarding the requested,
active endpoint’s capabilities and attributes are available from the info
field. The application is responsible for freeing this structure by
calling fi_freeinfo when it is no longer needed.

prov/rxm: Fix leak of fi_info

---

util/pingpong.c

I'm not sure how this wasn't noticed and fixed as part of #3821. This commit
just completes the FI_CONTEXT2 fix that was identified earlier.  Without
this fix to fi_pingpong providers that require FI_CONTEXT2 will trigger
the gnu "stack smashing" abort in debug builds.
Signed-off-by: Michael Blocksome <michael.blocksome@intel.com>

util: fi_pingpong FI_CONTEXT2 fixup

---

prov/verbs/src/verbs_domain.c

Application leaked a small amount of memory and a file
descriptor when a verbs RDM domain was destroyed.

prov/verbs: Add missing free event channel in fi_ibv_domain_close()

---

prov/verbs/src/verbs_info.c

Found by inspection: rdma_addrinfo would leak in error case,
but it probably can't be hit in real life.

prov/verbs: Fix memory leak in fi_ibv_getifaddrs() in error case.

---

prov/rxm/src/rxm_attr.c
prov/rxm/src/rxm_init.c
prov/verbs/src/verbs_info.c

@shefty I've added FI_ORDER_DATA to RxM since as per the definition it seemed RxM can support it implicitly. RxM copies the received data in order to application buffers. Please review.

prov/verbs, rxm: fix incorrect reporting and handling of tx, rx attributes 

---

include/ofi_util.h
prov/rxm/src/rxm_ep.c
prov/util/src/util_ep.c

The full set of the OP flags in't used for inejct path, only `FI_CQ_REMOTE_DATA` are needed.

prov/rxm: Use the full set of the OP flags only for non-inject path

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c

This helps to avoid leak of the RX buffers that were preposted for closed
MSG EP in case of bi-directional connection (passive side of connection).
Before the connection is established and new MSG EP is allocated, move
old preposted RX buffers to the temporarily list and then cleanup the list.
When we have multiple spawned and then destroyed processes, the memory growths for every spawned processes. 
The following situation:
`spawn 1 proc -> destroy 1 proc -> spawn 2 proc -> destroy 2 proc -> ... -> spawn N proc -> destroy N proc
`would lead that (N * (rx-attr->size)) RX buffers will be available in RX buffers pool.
In this situation we can re-use allocated buffers that are no longer needed for the destroyed connection.
With this PR, RxM will allocate only (1 * (rx_attr->size)) RX …

prov/rxm: Use separate list of the posted RX buffers per connection

---

prov/tcp/src/tcpx_ep.c

prov/tcp: fix fi_getname implementation for ep and pep

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_ep.c

The PR does the following:
- prov/rxm: Fix the reseting of TX buffer packet flags
The flags should be reseted by FI_REMOTE_CQ_DATA rather than OFI_REMOTE_CQ_DATA,
because when TX buffer is allocated, FI_REMOTE_CQ_DATA is set to the flags,
if requested by user.
- prov/rxm: Preset FI_MSG and FI_TAGGED for TX buffers during EP setup
It is possible to preset hdr.flags to FI_TAGGED and FI_MSG based on
the type of the message once when allocated buffer pool.
- prov/rxm: Don't pass comp_flags into internal send/inject functions
We can drop redundant argument comp_flags and just use TX buffer hdr.flags
that are already set to the FI_MSG or FI_TAGGED.

prov/rxm: Remove redundant code + fix resetting of TX buffer during releasing

---

prov/tcp/src/tcpx.h
prov/tcp/src/tcpx_attr.c
prov/tcp/src/tcpx_conn_mgr.c
prov/tcp/src/tcpx_cq.c
prov/tcp/src/tcpx_ep.c
prov/tcp/src/tcpx_init.c
prov/tcp/src/tcpx_progress.c
prov/tcp/src/tcpx_rma.c

Instead of filling the fixed fields along fast path (send/recv/read/write), pre-initialize them once at the buffer pool creation.

prov/tcp: optimization: Maintain buf pool array with preset fields

---

include/ofi.h
man/fi_rxd.7.md
prov/rxd/src/rxd.h
prov/rxd/src/rxd_cq.c
prov/rxd/src/rxd_ep.c
prov/rxd/src/rxd_fabric.c
prov/rxd/src/rxd_init.c

- restructures environment variables to make future additions easier
- add FI_RXD_OOO_RDM environment variable to turn on out-of-order reliability mode (turn of retries, add reassembly of segments)
- coverity initialization fix
- reorganization to minimize amount of initialization, better readability, lock move, and removal of unnecessary return variable

prov/rxd: out-of-order reliability mode and other enhancements

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_init.c

- prov/rxm: serialize access to repost_ready_list
- prov/rxm: add support for FI_BUFFERED_RECV mode

prov/rxm: add support for buffered recv

---

prov/gni/src/gnix_av.c

Checking the FI_SYNC_ERR flag is done incorrectly with `&&` instead of `&`. This will produce errors if somebody provides the FI_MORE flag.

prov/gni: fix incorrect check of FI_SYNC_ERR flag

---

prov/mrail/src/mrail_init.c

prov/mrail: Return one fi_info per rail.

---

prov/tcp/src/tcpx_ep.c

prov/tcp: [bugfix] On closing endpoint, release rma read queue entries, if present

---

include/ofi_util.h
prov/rxm/src/rxm.h
prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_rma.c
prov/util/src/util_av.c

Currently RxM uses TX buffer (only non-inject case) and TX queue entry to prepare send request.
The TX pool buffer and TX queue are common objects per RxM EP (i.e. per all connections). The TX pool buffer is able to increase number of entries at the run-time, and TX queue (`queue size == tx_attr->size`) isn't able to do this.
So, the TX queue is a bottleneck for large message flow, when messages are sent to several receivers. RxM is able to transmit `tx_attr->size` messages per each connection. For example, if RxM has `N` peers, theoretically it's possible to transmit `N*(tx_attr->size)` messages by sending `tx_attr->size` per connection. Current implementation doesnt' allow to do this, because TX queue is limited by `tx_attr->size`, i.e. it's possible to transmit only `tx_attr->size` …

prov/rxm: Allocate TX queue per connection

---

prov/rxd/src/rxd.h
prov/rxd/src/rxd_attr.c
prov/rxd/src/rxd_cq.c
prov/rxd/src/rxd_ep.c

- Add initial tagged implementation
- Coverity fix - initialize window size on resent EOM ACK
- When writing an error to the CQ, properly set the prov_errno to 0, instead of the negative error value
All FI_MSG and FI_TAGGED ubertest passing latency, bandwidth, and unit tests. Seems to be a closing issue with the inject calls, but those pass the benchmarks, so it seems like a test issue.

prov/rxd: initial tagged implementation and some bug fixes

---

prov/rxm/src/rxm_ep.c

The OP flags (`FI_TAGGED`, `FI_MSG`) must be set, because the flags are reported to user through CQ entries.

prov/rxm: Set OP flags for LMT send requests

---

prov/rxm/src/rxm_cq.c

When not using shared receive context we can easily get to rxm_conn instead
of doing a lookup which involves slightly more work.

prov/rxm: avoid additional look-ups when not using shared receive context

---

man/fi_rxd.7.md

man/rxd: fix rxd environment variable name

---

prov/tcp/src/tcpx_ep.c

This optimizes the fi_recv and fi_recvv code paths by implementing them directly rather than calling through fi_recvmsg.

prov/tcp: Optimize fi_recv* code paths

---

prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c

(cherry picked from commit e5baf8928e7217836a94b4fb927fb6b9746d7582)

[v1.6.x] prov/rxm: serialize access to repost_ready_list

---

prov/rxm/src/rxm_attr.c
prov/rxm/src/rxm_init.c

There are run-time parameters `FI_VERBS_RX_SIZE` and `FI_VERBS_TX_SIZE` that adjust verbs' provider default value for the `rx_attr::size` and `tx_attr::size` respectively.
But the `rx_attr::size` can be adjusted for RxM/verbs provider due to hard-coded value (1024). The patch fixes this issue.

prov/rxm, verbs: Use the RX attribute size of a core provider

---

prov/shm/src/smr_msg.c

Note bug fix in first commit.  Other commits optimize the recv paths for tagged and untagged messages.

prov/shm: Optimize receive code paths

---

prov/sockets/src/sock_progress.c

at least on aarch64, gcc 7.3.0 complains about
using memcpy with NULL 1st argument

prov/sockets: swat gcc 7.3.0 warning

---

contrib/cray/Jenkinsfile.verbs
prov/tcp/src/tcpx_ep.c

This should help us to pick up the newest library rather than
the system default library.

 contrib/cray: Add LD_LIBRARY_PATH to environment

---

prov/gni/configure.m4

double check that the user gave a correct path
to kdreg package
(cherry picked from commit ca53e30cb721ea33acbace66ffdc5d06b0d2f7df)

prov/gni: improve kdreg configury check

---

prov/sockets/src/sock_fabric.c

At least for GCC 6.3 and 7.3, this rather prominent warning
appears everytime I build libfabric:
```
prov/sockets/src/sock_fabric.c: In function 'sock_getinfo':
./include/unix/osd.h:199:62: warning: 'addr.sin6_addr.__in6_u.__u6_addr32[2]' may be used uninitialized in this function [-Wmaybe-uninitialized]
(addr->sa_family == AF_INET6 &&
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
((struct sockaddr_in6 *)addr)->sin6_addr.s6_addr32[0] == 0 &&
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
((struct sockaddr_in6 *)addr)->sin6_addr.s6_addr32[1] == 0 &&
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
((struct sockaddr_in6 *)addr)->sin6_addr.s6_addr32[2] == 0 &&
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
prov/sockets/src/sock_fabric.c:677:21: note: …
```

prov/sockets: suppress another gcc warning

---

include/ofi_mem.h
prov/rxd/src/rxd_cq.c
prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c

This PR fixes the corruption of users buffer in the freestack. `freestack_push` (`smr_freestack_push`) corrupts the first byte of the user data by setting the fs->next. Added the ctx field that is used by freestack implementation to set service data without touching user buffers.
The freestack functionality allocates an array of user's buffers and then pushes them into a LIFO list. Every user buffers contains reference to the previous value (the reference is assigned in the `freestack_push`). But this is set directly to the user buffer that leads to user's data corruption.
This PR fixes this by wrapping every user's buffer in the allocated array into structure that includes a pointer to the previous buffer in the freestack and the user's data. This solution helps to avoid user's data …

common, rxm, rxd: Fix corruption of user buffer

---

prov/rxm/src/rxm_ep.c

When running the cq_test over rxm;tcp on windows, the
ep_bind call fails (unable to allocate the tcp cq, since
there's no fd on windows).  However, the failure code is
lost, since it's overwritten when closing the cq on the
error path.
Instead, simply close the cq and return the original error
code.  This avoids the crash.

prov/rxm: Don't overwrite failed return value creating CQ

---

prov/gni/src/gnix_rma.c

Add a missing %d to a debug print statement.
Thanks to Philip Davis for reporting.
Fixes #4135

prov/gni: fix a debug print statement

---

prov/gni/include/gnix.h
prov/gni/include/gnix_ep.h
prov/gni/src/gnix_ep.c
prov/gni/src/gnix_sep.c

Turns out the effort to get MPI RMA over OFI in
Open MPI is flushing out latent bugs in the GNI
provider's SEP implementation.
This flushes out a problem with enabling SEP
tx/rx contexts.  We were actually doubly allocating
resources in cases where an app enables both the tx
and rx, and not initializing some resources the
underlying EP needed.

prov/gni: rework SEP setup

---

prov/rxm/src/rxm_attr.c
prov/rxm/src/rxm_init.c

RxM doesn't support `FI_ORDER_STRICT`, because RxM is a provider that supports RDM EP and doesn't add synchronization logic for different destination paths to report CQ entries in a strict ordering.

prov/rxm: Set FI_ORDER_NONE for tx and rx completion ordering

---

prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_cq.c
prov/verbs/src/verbs_ep.c

prov/verbs: verbs/msg doesn't generate CQE if a context is NULL

---

include/ofi_util.h
prov/mrail/src/mrail.h
prov/mrail/src/mrail_attr.c
prov/mrail/src/mrail_cq.c
prov/mrail/src/mrail_ep.c
prov/mrail/src/mrail_init.c
prov/rxm/src/rxm.h
prov/rxm/src/rxm_ep.c

- prov/mrail: set mrail_ep as context when opening rail endpoint
- prov/util: add a generic receive queue with tag matching and directed recv support
- prov/rxm: use util recv match functions
- prov/mrail: add support for tag matching and use buffered recv
- prov/mrail: remove unused rx get rail function

prov/mrail: Add tag matching support for small messages and use buffered recv

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_ep.c

- **prov/rxm: Replace rxm_pkt_size by direct calling sizeof()**
- **prov/rxm: Use common pool for TAGGED and MSG TX operations**
- **prov/rxm: Implement separate pool for inject operations**
Use TX buffers allocated from separate TX pool for inject operations, if
a size is <= core_prov::tx_attr::inject_size.
Fix the following sizes of allocated buffers for differents pools:
-- ACK - sizeof(rxm_pkt) + sizeof(rxm_tx_buf)
-- LMT - sizeof(rxm_rma_iov) * iov_limit + sizeof(struct ofi_rma_iov) +
sizeof(struct rxm_tx_buf)
It's not neccessary to allocate buffer_size + sizeof(rxm_tx_buf) for these pools

prov/rxm: Implement separate pool for inject operations

---

include/ofi_proto.h
prov/rxm/src/rxm.h
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c

- **prov/rxm: Improve support of SAR protocol [RX side]** 
This improvement adds support of core providers that doesn't keep
ordering on receive side
First received SAR messages sets expected number of segments and then
`segs_left` value of RX entry is decremented.
Comparing `segs_left` with 1 means that we expecting the last SAR segment.
- **prov/rxm: Improve support of SAR protocol [TX side]**
Added support of providers that doesn't keep orderign of generating
TX CQ entries.
This implemented by removing in_flight_list queue and storing TX entry
per every TX buffer (pointer to TX buffer is passed as a context to fi_send)

prov/rxm: Improve support of SAR protocol

---

prov/rxm/src/rxm_ep.c

This addresses [CID-293079](https://scan4.coverity.com/reports.htm#v27196/p10344/fileInstanceId=45757273&defectInstanceId=8524319&mergedDefectId=293079)

prov/rxm: Address Coverity scan issue

---

prov/mrail/src/mrail_ep.c

- We need to get a valid dlist_entry before we do container_of
- Also fix check for unexp_msg_entry

prov/mrail: fix for issue reported by coverity

---

prov/rxm/src/rxm_ep.c

The maximum possible length of user buffer that can be injected is calculated as follows:
core provider inject size (`rxm_ep->msg_info->tx_attr->inject_size`) - RxM packet size (`struct rxm_pkt`)
The size of buffers that are allocated from TX INJECT pool should have size:
`rxm_ep->msg_info->tx_attr->inject_size + sizeof(struct rxm_tx_buf) - sizeof(struct rxm_pkt)`
The other pools isn't impacted by this, because `rxm_ep->rxm_info->tx_attr->inject_size` takes into account the size of the RxM packet.

prov/rxm: Don't consider RxM pkt size twice

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_ep.c

This is PR created to cover comment from #4208 

prov/rxm: Move fill of TX entry into separate function

---

include/ofi_util.h
prov/rxm/src/rxm.h
prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_rma.c
prov/util/src/util_cq.c

This PR does the following:
- prov/rxm: Remove deferred queue that is used before connections is established
- prov/rxm: Implemented deferred queue [TX inject]
The new implementation of deferred queue (covers FI_INJECT only) is used for the following cases:
-- before a connection has not bee established yet
-- if fi_send/fi_inject fails or lack of TX queue resources
The rxm_ep object contains the common `conn_deferred_list` list of connections that require the progressing their deferred queues. When a operation needs to be queued into deferred queue, it is inserted into tail of the `rxm_conn::deferred_op_list` queue. If the connection entry hasn't been inserted yet to `conn_deferred_list` list, this is done to enable the progressing for this conenction.
The progressing of connection's …

prov/rxm: Refactor deferred queue (TX inject)

---

include/ofi_mem.h
prov/rxm/src/rxm_ep.c

This patch addresses the following:
If a TX buffer is already allocated, it isn't allocated second time from a pool.

prov/rxm: Refactor handling of deferred TX inject

---

contrib/cray/Jenkinsfile.verbs

The fabtests seem to be passing now. No sense in fingerprinting that test
when all tests now pass.

contrib/cray: Remove true statement from test

---

prov/psm2/src/psmx2_domain.c
prov/psm2/src/psmx2_mr.c

Although the provider doesn't have constraint related to MR mode, trivial
implementation of these control functions are needed in order to allow code
that support certain MR mode to work.

prov/psm2: Support control functions related to MR mode

---

include/ofi_shm.h
prov/util/src/util_shm.c

- fix inject pool allocation in smr_region creation based on recent smr_freestack changes
- clarify cmd_cnt usage

prov/shm: fix smr_region size allocation

---

include/ofi_list.h

Functions to concatenate slists at head or tail were added. An
additional function for swapping slists was also implemented.
This prevents providers from having to loop around when moving
entries from one list to other.
Signed-off-by: Jaime Arteaga <jaime.a.arteaga.molina@intel.com>

common: Add concatenation and swapping support for slists

---

include/ofi_util.h
prov/rxm/src/rxm.h
prov/rxm/src/rxm_cq.c
prov/util/src/util_av.c

- prov/util: initialize fi_addr in util_cmap_handle to correct macro
- prov/util: add a cq write function that also reports source address
- prov/rxm: keep src addr reporting in sync with completion entry

prov/rxm: keep src addr reporting in sync with completion entry reporting.

---

prov/psm/src/psmx_cntr.c
prov/psm2/src/psmx2_cntr.c

Previously fi_cntr_read would make progress calls at one percent frequency
in order to keep the average overhead of the function itself low. This could
actually have negative impact on the performance in case fi_cntr_read was the
only means of making progress because a large number of calls might be needed
even though per-call overhead was low.

prov/psm,psm2: Always try to make progress when fi_cntr_read is called

---

contrib/cray/Jenkinsfile.verbs

When testing fabtests, we request a static resource. The name
and address of that resource changed, so the test must change
accordingly. In the future, this needs to be more resilient.

contrib/cray: Fix static request of resources

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_cq.c

There are two problems fiexd in the patch:
- applications does several sends -> TX requests moved to
deferred queue -> flushing TX requests -> after N successful
sends, N+1 fi_send/fi_inject fails -> hangs (the progress are
not called)
Solution: move progress of deferred queue after calling of fi_cq_read
- rxm_conn entry added twice to RxM EP deferred progress list,
because the entry is not deleted in rxm_ep_handle_unconnected
when the all deferred requests for this connection were sent
and queue is empty
Solution: added removal of rxm_conn entry from RxM EP deferred
progress list in rxm_ep_handle_unconnected

prov/rxm: Fix incorrect behavior of deferred queue

---

include/unix/osd.h
include/windows/osd.h
prov/tcp/src/tcpx_conn_mgr.c
prov/tcp/src/tcpx_ep.c
prov/util/src/util_cq.c
prov/util/src/util_ep.c
prov/util/src/util_wait.c

This grabs 3 patches from #4231, plus adds a related fix based on the problem Sylvain reported.
I think 1 more patch from 4231 is ready for merging, but the sendmsg patch highlights an issue with the base implementation of that call on windows.

Select patches from PR #4231 + additional fixes

---

prov/gni/include/fi_ext_gni.h
prov/gni/src/gnix_auth_key.c
prov/gni/src/gnix_mbox_allocator.c
prov/gni/src/gnix_nic.c

If an authorization key is provided by the user the mbox and nic allocations will fail due to the fact that the default key is hard-coded.
The solution for the hard-coded arguments is to use the cookie stored with the nic to create a `struct fi_gni_auth_key` for the actual key lookup. This also requires a different handling of the default auth key within the functions of gnix_auth_key.c.
This will fix the issues for #4153

prov/gni: Fix user provided authorization key

---

include/unix/osd.h
include/windows/osd.h
prov/udp/src/udpx_ep.c
src/windows/osd.c

Windows does not support socket send or receive calls that
take an iovec on a streaming socket.  The current abstraction
ends up allocating a buffer, copying the iovec in/out of it,
and using the standard send/recv calls.
Optimize this by separating the sendmsg/recvmsg calls based
on the socket type.  For UDP sockets, we can use WSASendMsg/
WSARecvMsg.  For TCP sockets, we iterate over the iovec.

osd/windows: Rework sendmsg/recvmsg calls

---

Makefile.am
include/ofi_recvwin.h

This commit adds a simple header that both utility and core providers
can use to implement packet ordering for `FI_ORDER_*` guarantees. The
reorder buffer utilizes a circular queue to hold packets that arrive
early on the rx side. The buffer can hold entries of any entry type as
declared using `OFI_DECL_RECVWIN_BUF`.

core: Add circular-queue based sliding receive window utility

---

prov/mrail/src/mrail.h
prov/mrail/src/mrail_cq.c
prov/mrail/src/mrail_ep.c
prov/mrail/src/mrail_init.c
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c

Note: RxM support for claiming large messages (rndv protocol) in the context of buffered recv is still a TODO.

prov/mrail: add support for claiming large messages

---

prov/rxm/src/rxm_ep.c

prov/rxm; Call fi_listen before CMAP is allocated

---

include/ofi_proto.h
prov/rxm/src/rxm.h
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c

This PR fixes the following issues:
- prov/rxm: Fix truncation of data in SAR protocol
The patch fixes problems with truncated messages received due to
incorrect calculation of segment size/numbers.
Also this patch adds minimal number of segments and maximum segment
size to enable adjusting SAR protocol.
- prov/rxm: Added reporting of errors in SAR protocol

prov/rxm: Fix truncation of data in SAR protocol

---

include/ofi_util.h
prov/rxd/src/rxd_cq.c
prov/shm/src/smr_comp.c
prov/util/src/util_cq.c
prov/verbs/src/verbs_dgram_cq.c

If an user doesn't read CQ entries as fast as it's needed to avoid
out of space issue in a circular buffer of CQ, the utility CQ reports
to a provider that there is no space. For instance, RxM generates an error
CQ entry. This is not right behavior. Provider shouldn't silently drop the
entry.
This patch fixes the isses described above by implementing bufferization
of CQ entries that don't fit into the circular queue until the space won't
be available.

util/cq: Fix out-of-space issue in Circular queue

---

prov/rxd/src/rxd.h
prov/rxd/src/rxd_av.c
prov/rxd/src/rxd_cq.c
prov/rxd/src/rxd_ep.c

- various AV bug fixes
- eliminate the need for a CTS and data message when sending small messages (save data within RTS and ACK right away)
Verified working on ubertest test_configs/ofi_rxd/udp,test and also with data verification

prov/rxd: AV bug fixes and small message optimization

---

include/windows/config.h

osd/windows: Remove an excessive definition of HAVE_TCP provider macro

---

include/ofi_list.h

Add variants of the existing single and multithreaded macros for traversing
dlists to perform a reverse traversal of the lists, starting at the tail.
Signed-off-by: Jaime Arteaga <jaime.a.arteaga.molina@intel.com>

common: Add reverse versions of macros to traverse dlists

---

prov/rxm/src/rxm_ep.c

This reverts commit ee9ab13e468f0eab6566825cc4d390aeff377bf2.

Revert "prov/rxm: Don't consider RxM pkt size twice"

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c

- **prov/rxm: Fix the buffered receive with SAR protocol**
Set an offest into ctrl_data field of ctrl_hdr instead of use
offset from pkt.hdr.size that is used by the buffred receive
functionality to report total size of messages received.
- **prov/rxm: Implement rough estimation of the number of the segments**
RxM estimates how much segments have to be sent to transfer an entire
message. If the number of the segments greater than TX queue size of
core provider, RxM uses Rendezvous protocol to transfer the message as
a fallback.

prov/rxm: Fixes for SAR protocol

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c
prov/util/src/util_av.c
prov/util/src/util_buf.c

- prov/util,rxm: fix memory leaks
- prov/util: add debug asserts to avoid size_t underflow/overflow
- prov/rxm: move writing truncation error to a functon 
- prov/rxm: make use of ofi_copy_iov_desc

prov/util,rxm: refactoring + bug fixes

---

prov/rxm/src/rxm_cq.c

prov/rxm: Reprocess directed receives when AV updated only in case of FI_DIRECTED_RECV enabled

prov/rxm: Reprocess directed receives for FI_DIRECTED_RECV enabled

---

prov/gni/src/gnix_nic.c

While using hpctoolkit with Sandia OpenSHMEM on Cray progress thread
was getting confused by interrupts being generated by the toolkit,
leading to much sadness. With this change the tool works.
Signed-off-by: Srdjan Milakovic <srdjan@rice.edu>

prov/gni: Fix interrupt for gni cq wait

---

include/ofi_util.h
prov/rxm/src/rxm.h
prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_cq.c
prov/util/src/util_av.c

- prov/rxm: move re-processing of directed recvs to av insert
- prov/rxm: acquire cmap->lock ony when updating addr for unexpected messages
@dmitrygladkov I've cherry-picked your patch from #4279 with some modification to fix an issue with locking in `ofi_cmap_update`. Also updated the commit message to better reflect the changes.

prov/util, rxm: fix some issues in re-processing directed recvs

---

include/ofi_net.h
include/ofi_util.h
prov/rxm/src/rxm.h
prov/rxm/src/rxm_conn.c
prov/sockets/include/sock.h
prov/sockets/src/sock_av.c
prov/sockets/src/sock_comm.c
prov/sockets/src/sock_conn.c
prov/sockets/src/sock_ep.c
prov/sockets/src/sock_ep_msg.c
prov/sockets/src/sock_fabric.c
prov/sockets/src/sock_progress.c
prov/tcp/src/tcpx_ep.c
prov/udp/src/udpx_ep.c
prov/util/src/util_av.c
src/common.c
src/windows/osd.c

Changes do not work.
Posting as work in progress to add ipv6 support to the socket provider. These changes currently break MSG EP support and have not been tested with ipv6 addresses yet.

prov/sockets: Add support for IPv6 addressing

---

prov/rxm/src/rxm_cq.c

Fixes #4283 
@jswaro This should fix the error that you see when running MPICH.

prov/rxm: fill missing rxm_conn in rx_buf when SRX is not used

---

include/ofi_iov.h
prov/mrail/Makefile.include
prov/mrail/src/mrail.h
prov/mrail/src/mrail_cq.c
prov/mrail/src/mrail_ep.c
prov/mrail/src/mrail_init.c
prov/mrail/src/mrail_rma.c
src/iov.c

Small RMA operations (i.e. fi_inject_write()) are round-robined while
large RMA operations are striped over all rails.
Two new structs 'mrail_rma_req' and 'mrail_rma_subreq' were added to
keep track of large RMA operations and their sub-operations on the
different rails.
Support for FI_MR_LOCAL will be added later.

prov/mrail: Add RMA ops.

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_conn.c

This reverts commit c86ef2d0970a260d490412f932e9a31bcf82a3e2.
struct ofi_sock_ip (along with other info) doesn't fit within most
verbs devices CM data.

Revert "prov/rxm: Enable IPv6 support in RxM"

---

prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_rma.c
prov/util/src/util_mem_monitor.c
prov/util/src/util_mr_cache.c

Looks like types of several fields have changed from uint64_t, size_t, and ssize_t.  Update format specifiers in FI_DBG messages to match the updated types.

Update format specifiers in FI_DBG messages

---

prov/tcp/src/tcpx_conn_mgr.c
prov/tcp/src/tcpx_ep.c

when epoll is not supported natively in OS (i.e macOS), libfabric uses the
poll implementation for the epoll API. In case of poll we need to
explictily signal any blocked threads on wait object to include a new
fd. On the other hand epoll does not need this. So the
failures are happening only macOS in our CI. This patch fixes those failures.

prov/tcp: signal the eq wait when new fd is added to it

---

include/rdma/fi_domain.h

When compiling c++ code against libfabric, the compiler gives a warning about an uninitialized member

fix warning missing-field-initializers

---

prov/gni/src/gnix_mbox_allocator.c
prov/gni/src/gnix_nic.c

SMSG buffers could contain stale data in the slab when first
allocated on some systems or when reused. This commit fixes that by
zero'ing the memory allocated upon first use, regardless of assumptions
that may have been made about the underlying implementation.
closes #4300

prov/gni: Fix stale data issue with SMSG buffers

---

prov/rxm/src/rxm_init.c
prov/util/src/util_av.c
prov/verbs/src/verbs_info.c

- prov/rxm: add an assert for fi_info->src_addr
- prov/rxm: fix missing src addr info in case of connections to self
- prov/verbs: don't report unusable fi_info (no source IP address)

prov/verbs, rxm: bug fixes

---

prov/rxm/src/rxm.h

This fixes case when several SAR requests are in-flight and some segments are
re-transmitted due to lack of resources in TX queue. The segments from different
SAR requets can be mixed and it leads to unexpected behavior

prov/rxm: Fix handling of RX buffer from unexpected queue in SAR

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_init.c

This resolves a hang in mpi_stress test for high # of ranks.

[v1.6.x]  prov/rxm: make postpone/defer requests opt-in

---

man/fi_sockets.7.md
prov/sockets/include/sock.h
prov/sockets/include/sock_util.h
prov/sockets/src/sock_conn.c
prov/sockets/src/sock_fabric.c

Make the 15s connection timeout configurable via environment
variable FI_SOCKETS_CONN_TIMEOUT. Also, remove the sleep(10) in
sock_ep_get_conn(). For example,
export FI_SOCKETS_MAX_CONN_RETRY=1    # try only once
export FI_SOCKETS_CONN_TIMEOUT=2000   # time out after 2s
Signed-off-by: Wei Li <liw2@boro-70.boro.hpdd.intel.com>

prov/sockets: Add FI_SOCKETS_CONN_TIMEOUT parameter

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c

The deferred queue is not needed and leads to poor performance due to
if stetement on the critical path

prov/rxm: Remove deferred queue

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_init.c
prov/rxm/src/rxm_rma.c

Having of TX queues per connection gives total queue size more
than MSG CQ allows. It leads to the case that CQ is overrun.
The PR implements the shared TX queue (rxm_conn has a pointer to
the shared TX queue). This is default behavior.
If fair TX queues is needed (per connection TX queue), this can be
enabled by specifying FI_OFI_RXM_USE_FAIR_TX_QUEUES=1. In this case,
rxm_ep::send_queue is NULL.

prov/rxm: Implement knob to use fair queues

---

prov/rxm/src/rxm_cq.c

The patch fixes crash in sending LMT ACK when ACK requests doesn't fit
into inject buffer of the core provider (this is case for HFI1 verbs device).

prov/rxm: Fix crash in rndv receive when sending ACK

---

prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_av.c
prov/psm2/src/psmx2_trx_ctxt.c

The "epaddr" info stored in address vector becomes invalid when the
corresponding peer is disconnected. Usually it's not an issue because
the entry is not supposed to be used later. However, if an application
uses fi_cq_readfrom to get the source address of incoming messages,
and multiple senders reuse the same HW address (successively, not
concurrently), the receiver may reuse old entries for new peers and
thus attempt to use the stale information instead of setting up new
connections.
Fix by removing stale "epaddr" information from the address vector
when the peer is disconnected.

prov/psm2: Remove stale info from address vector when disconnecting

---

man/fi_rxm.7.md
prov/rxm/src/rxm.h
prov/rxm/src/rxm_attr.c
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_init.c

This PR has the following fixes cherry-picked from master (#4332 ):
- prov/rxm: make tx, rx queue sizes independent of MSG provider
- prov/rxm: define default rxm univ size and use it for calculating MSG CQ size
- prov/rxm: man page updates

[v1.6.x] prov/rxm: fix tx, rx and CQ sizes

---

prov/psm/src/psmx_atomic.c
prov/psm/src/psmx_cq.c
prov/psm/src/psmx_mr.c
prov/psm/src/psmx_rma.c
prov/psm2/src/psmx2_atomic.c
prov/psm2/src/psmx2_cq.c
prov/psm2/src/psmx2_mr.c
prov/psm2/src/psmx2_rma.c

Add the missing check to ensure that target side counter update for RMA
operations only happens when the FI_RMA_EVENT capability is enabled for
the associated endpoint.
Also make sure the flags used for binding MR to counter only contains
supported values (currently only FI_REMOTE_WRITE is valid).

prov/psm,psm2: Enforce FI_RMA_EVENT checking when updating counters

---

prov/tcp/src/tcpx_progress.c
prov/tcp/src/tcpx_rma.c

@vkrishna I've finally had a chance to test your recent patches, which add the progression of endpoints in blocking polling mode. I've found a bug, which I address in this patch. 
I still have some bugs where the `tcp` provider stops progressing messages in blocking mode. I'll dig into the problem and I will probably post some additional patches in the next days.
This patch fixes a bug that has been introduced in commit
55192cde9a86f92b50cf6c427447ccfefe2ef5cd("prov/tcp: Modify which
poll events the endpoint's sock can be blocked on")
- FI_EPOLL_OUT must be monitored when ep->tx_queue is not empty
and send_ready_monitor is set to false.
- FI_EPOLL_OUT must be unmonitored when ep->tx_queue is empty and
send_ready_monitor is set to true.

prov/tcp: fix wrong conditions in tcpx_try_func()

---

include/ofi_recvwin.h

Add size mask in generating write index, else write
index can fall out of bound.
Change-Id: Ia0a55b92e444a4d1c7fc71b8c239dcbb4b569611
Signed-off-by: Mohan Gandhi <mohgan@amazon.com>

util/recvwin: Fix write index to be within bound

---

include/unix/osd.h
include/windows/osd.h
prov/tcp/src/tcpx_ep.c
src/windows/osd.c

This patch adds the support of fi_getpeer() call into the
tcp provider.

prov/tcp: add support for getpeer() function

---

prov/tcp/src/tcpx_ep.c

During connection management, the socket gets added to the eq wait list for processing connreq send, connreq responses. So when the endpoint is being closed, we should remove the socket from the eq wait list.

prov/tcp: remove socket from the eq wait list when closing the endpoint

---

prov/sockets/include/sock.h

This provides a work-around for an MPI bug performing data
transfers larger than the size supported by the provider.

prov/sockets: Increase maximum message size

---

prov/rxm/src/rxm_conn.c

When used fair TX queues, RxM must allocate TX queues with size not greater
than can be transmitted via MSG provider's TX queue.

prov/rxm: Allocate TX queues per connectio with size based on MSG TX queue

---

prov/verbs/src/verbs_domain.c

prov/verbs: Fix bad fallthrough

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_cq.c

RxM on the receiver side registers the MR for the receiver's I/O vector with
the total length of the I/O vector entries when the LMT request is received.
This patch changes behavior to register the MR for the receiver's I/O vector
with the length received from the LMT request (sender's I/O vector total length).
So, this reduces registration time of the MR in the following case (just an example):
Sender side:
fi_send(buf, 1000); -> fi_cq_read();
Receiver side:
fi_recv(buf, 10000000); -> fi_cq_read();
w/ the patch:
RxM will register MR with length = 1000 on the sender and receiver sides.
w/o the patch:
RxM will register MR with length = 1000 on the sender side and 10000000 -
on the receiver side.

prov/rxm: Improve Rendezvous protocol

---

include/unix/osd.h
include/windows/osd.h
prov/sockets/include/sock.h

WinSockAPI and BSD Sockets have a different type of length parameter for their
send/recv functions. WinSockAPI uses int, BSD Sockets uses size_t.

osd, prov/sockets: Define the maximum socket buffer size

---

prov/rxm/src/rxm_ep.c

- prov/rxm: don't use inject buf pool when threading level is not FI_THREAD_SAFE
- prov/rxm: use fi_inject for MSG provider whenever possible

prov/rxm: fix using wrong buffer for inject operations

---

prov/psm2/src/psmx2_cq.c

This basically reverts "prov/psm2: Avoid polling PSM2 in a nested loop",
but adds specially handling for large size send completions to avoid a
platform-specific bi-directional send/recv performance issue that was
fixed by the reverted commit. Enabling polling multiple completions in
a single fi_cq_read call is good for performance in general.

prov/psm2: Reintroduce nested polling, with a tweak

---

prov/psm2/src/psmx2_cq.c

The default pointer for completion status may be modified when sendv
completions are processed. Restore the pointer to prevent memory
corruption during later polling iterations.

prov/psm2: Fix memory corruption related to sendv

---

prov/psm2/configure.m4
prov/psm2/src/psmx2_cq.c

* prov/psm2: Fix memory corruption related to sendv (Jianxin Xiong)
* prov/psm2: Reintroduce nested polling, with a tweak (Jianxin Xiong)
* prov/psm2: fix CPU detection (Holger HoffstÃ¤tte)

v1.6.x: cherry-picked fixes for psm2

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c

The patch moves calculations of SAR segments count to the layer that
issues SAR transmissions. It helps to know how much segements are needed
to send full message before we issued rxm_ep_sar_tx_send().
The functionality will be used to check the number of free entries in the MSG
provider's TX queue and RxM will decide which protocl should be used - SAR
or Rendezvous.

prov/rxm: Refactor SAR

---

prov/rxm/src/rxm_ep.c

prov/rxm: Fix crash when impossible to allocate fist SAR TX buffer

---

Libfabric.Build.Default.props
info.vcxproj
libfabric.vcxproj
pingpong.vcxproj
strerror.vcxproj

This patch:
- improves portability on different target Windows platform versions
- removes setting root libfabirc directory into the additional include directories to make possibility build two version Linux and Windows from single directory (auto-generated config.h file)
The way from [Microsoft/ChakraCore](https://github.com/Microsoft/ChakraCore/blob/master/Build/Chakra.Build.Default.props) has been applied to fix [portability issue](https://developercommunity.visualstudio.com/content/problem/140294/windowstargetplatformversion-makes-it-impossible-t.html) 

windows: Improve portability on different target Windows platform versions

---

.travis.yml

Coverity stopped running automatically in June.  I've gone through their documentation to link coverity into travis, and this is the result.  I have no idea if it's correct at this point, but it should be close.

coverity: Update travis.yml to force coverity runs

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_ep.c

This patch targets reducing latency numbers for messages with size <= MSG provider inject size
This patch saves ~5 instruction on critical path and simplifies code path by presetting Completion flags (`FI_MSG` or `FI_TAGGED`) and Operation code (`ofi_op_msg` or `ofi_op_tagged`) and using `struct rxm_pkt` instead of `struct rxm_tx_buf`

prov/rxm: Use separate pkt structures for msg and tagged ops

---

contrib/cray/sft_test_results_baseline.txt
prov/rxm/src/rxm_conn.c

Addresses intermittent failing tests by adding new sections to the baseline file that are understood by the parsing tool.

contrib/cray: Address intermittent failing tests

---

.travis.yml

This reverts commit 4536fa97c779ac7be350e867b4415671800ac690.
This will hopefully re-enable travis CI

Revert "coverity: Update travis.yml to force coverity runs"

---

include/ofi_util.h
prov/rxm/src/rxm_cq.c
prov/util/src/util_cq.c

This patch implements `fi_control()` for utility CQ that can handle
`FI_GETWAIT` command. This is almost the same as for EQ.

prov/rxm, util: Enable support of explicit usege of util CQ FD

---

include/ofi_net.h
prov/rxm/src/rxm_init.c
prov/verbs/src/verbs_info.c
src/common.c

When an app passes a wildcard address in string format as node argument to
fi_getinfo, we should return a passive fi_info.

prov/verbs: detect string format of wildcard address

---

include/ofi_net.h
prov/rxm/src/rxm_init.c
prov/verbs/src/verbs_info.c
src/common.c

When an app passes a wildcard address in string format as node argument to
fi_getinfo, we should return a passive fi_info.
(cherry picked from commit 575075e108a3fea82ac3c17643d7210d7986373a)

[v1.6.x] prov/verbs: detect string format of wildcard address

---

prov/rstream/src/rstream.h
prov/rstream/src/rstream_ep.c
prov/rstream/src/rstream_msg.c

-previously waited for recv side completion for tx_mr segment return
-this is too strong of a requirement, tx completion is sufficient

prov/rstream: tx_mr return len improvement

---

include/ofi_mr.h
prov/util/src/util_mem_monitor.c
prov/util/src/util_mr_cache.c

This PR implement the following commits:
- util/mr_cache: Change the sequence between the MR tree and the subscription when allocate/release the new MR entry. This is needed for futher re-use (will prepare new PR that fixes some major bugs and improves performance).
- util/mem_monitor: Remove a subscription entry from NQ list when unsubscribed from a MR entry (to avoid read-after-free issue)
- util/mr_cache: Add support of MR storage as a plugin. This patch makes possible to implement new types of MR storage (Red-Black Tree (default), AVL Tree (will be added), User defined and etc).

util/mr_cache, mem_monitor: Minor bug-fixing + improvements

---

README.md

This should help solving trouble integrating libfabric onto their Windows Platform.
As VS2017 Community Edition is free this solution is definitely available to anyone.

added Windows Instructions for Visual Studio 15/17

---

NEWS.md

Use '-' in place of '--' for markdown formatting.

news: Fix bullet lists

---

NEWS.md

Use '-' instead if '--' to format bulleted list.

news: Fix markdown bullets

---

prov/psm2/src/psmx2_av.c
prov/psm2/src/psmx2_trx_ctxt.c

This reverts commit 7741df0db37085c1a49c05185c9b3f8170981661.
Sporadic assertion failures have been observed inside psm2_ep_disconnect2().
Disable the patch until the issue is fixed.

Revert "prov/psm2: Avoid long delay in psm2_ep_close"

---

include/ofi_mr.h
include/rbtree.h
prov/util/src/util_mem_monitor.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_domain.c
prov/verbs/src/verbs_mr.c
src/rbtree.c

This PR consists from 3 commits:
- **util/mem_monitor, prov/verbs: Write free/realloc events from hooks to NQ event list**
The current implementation works as follows:
Events from free/realloc hooks (if an user subscribes on this memory address)
are written to its own intermediate event list and then they are written to
a NQ's event list.
The commint improves current implementation by removing intermediate event list
of notifier. The notifier (verbs global notifier) inserts events directly
into the NQ's event list.
- **common/rbtree: Add tree traversal and get root routine**
The commit adds two routines:
-- tree traversal that applies user-provided handler function for each node
-- get root of a tree
- **prov/verbs, util/mem_monitor: Fix notofication mechanism for MR cache**
The commit …

 prov/verbs, util/mem_monitor: Fix notification mechanism for MR cache 

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_rma.c

The PR fixes two issues:
- RDMA Write inject path doesn't increment Write completion/error counter when MSG `fi_write_inject`/`fi_write_inejctdata` completed with success/error.
- MSG inject path increments error counter when MSG `fi_inject` completes with states `-FI_EAGAIN`
The PR fixes MPICH/CH4 RMA path ('honest' RMA over OFI RMA operations).

prov/rxm: Fix RDMA Write and MSG inject paths

---

README.md

To ease the testing of fabtests on any system, this
script will utilize known environment variables of the
SLURM WLM to identify client and server. This should ease
the transition of the tests to other development systems.

contrib/cray: Wrap fabtests for client/server

---

README.md

Instead of MPICH3.3b2, use MPICH3.3b3 with OSU
microbenchmark tests.

contrib/cray: Migrate MPI tests to use MPICH3.3b3 

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_rma.c

This PR includes the following commits:
- Move send/inject helper function to EP code from header file, because they are used only EP code
- Remove increment of error counter when inject operation failed, because the result of operation is returned to an user immediately

 prov/rxm: Don't increment error counter when inject operation failed

---

configure.ac

Since CFLAGS was initialized with "-O2" and was appended to debug CFLAGS,
"-O0" was overriden by "-O2". This patch fixes the issue.

configure: don't set "-O2" in CFLAGS by default for debug builds

---

prov/psm2/src/psmx2_atomic.c

The following warnings were observed for non-debugging builds:
../prov/psm2/src/psmx2_atomic.c: In function psmx2_atomic_compwritev_generic:
../prov/psm2/src/psmx2_atomic.c:1636:27: warning: variable result_len set but
not used [-Wunused-but-set-variable]
size_t len, compare_len, result_len, iov_size;
^
../prov/psm2/src/psmx2_atomic.c:1636:14: warning: variable compare_len set but
not used [-Wunused-but-set-variable]
size_t len, compare_len, result_len, iov_size;
^
Fixes #4054

prov/psm2: Fix compiler warnings

---

include/ofi_util.h

util: Add parentheses for parameters used in the macros

---

prov/rxm/src/rxm_cq.c

prox/rxm: Remove assert since SAR is disabled.

---

prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_domain.c
prov/verbs/src/verbs_mr.c

Handle duplicated insertion to rbtree by having abstraction entry
that may contain several sucription entries.
This allows to useVerbs notification mechanism (and as a result
MR caching functionality) per several domains.

prov/verbs: Fix memory notifier usage for multiple domains

---

contrib/cray/Jenkinsfile.verbs

Added email notification section to send email when
the state of the pipeline changes.
@tonyzinger  @rmeegan

contrib/cray: Send pipeline email notifications 

---

include/ofi_util.h
prov/tcp/src/tcpx_eq.c
prov/util/src/util_eq.c

This patch sets all the eq ops fn pointers, instead of just overriding some of them.

prov/tcp: fixing improper eq ops override 

---

Libfabric.Build.Default.props

Currently libfabirc's VS projects support only Windows SDK 10.0.
Add support of older ones (8.1, 8.0, 7.1, 7.0) by checking instalaltion
path of SKDs and choose the more new.

windows: Add support of old Windows SDKs

---

prov/psm2/Makefile.include
prov/psm2/configure.m4

The latest PSM2 source code introduces a Hardware Abstraction Layer
and as the result brings in changes to source code layout as well as
compiler flags. Amend the provider configuration code to detect the
new version of PSM2 source code to allow the provider to continue
be built with the PSM2 source included.
There is no impact if the provider is built separately from the PSM2
code, i.e., using PSM2 as a library.

prov/psm2: Support building with latest PSM2 source code

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_cq.c

This patch fixes case when the length of the supplied buffer is smaller than
the length of the message that will be read by fi_readv().
The problem was reproduced with MPICH errors/pt2pt/truncmsg1 test.

prov/rxm: Fix handling of truncated messages in Rendezvous protocol

---

include/ofi.h
include/ofi_mem.h
include/rdma/fabric.h
man/fi_fabric.3.md
man/fi_nic.3.md
src/fabric.c
src/fi_tostr.c

Check for and handle fid_nic when referenced by an fi_info structure.
We use the fid_nic ops to route calls to the correct provider, with default implementations of calls provided.  For example, now to free a fid_nic, we call fi_close(fid_nic).  The provider can set ops->close to an internal call, or simply use the common cleanup function ofi_nic_close().  The provider specific call can call ofi_nic_close() internally as well.  This gives the provider a way to cleanup the prov_attr structure if one is used.
Similarly, we can duplicate a fid_nic by using a new fi_control() command, FI_DUP.  E.g. fi_control(fid_nic, FI_DUP, &fid_nic_ptr).  The fi_dupinfo() call will invoke fi_control(... FI_DUP...) for any fi_info->handle that exists (with proper checks).  This will route the dup operation …

core: Handle struct fid_nic through various API calls

---

include/ofi.h
include/ofi_list.h
include/ofi_mem.h
include/rdma/fi_endpoint.h
man/fi_endpoint.3.md
man/fi_msg.3.md
prov/mrail/src/mrail.h
prov/mrail/src/mrail_cq.c
prov/mrail/src/mrail_ep.c
prov/rxm/src/rxm.h
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c
prov/util/src/util_buf.c

- prov/rxm: make the header used for rendezvous protocol fixed size
- common: add a minimum buffered recv limit option
- prov/rxm: add support for buffered limit opts
- prov/rxm: add support for buffered recv for rendezvous protocol messages 
- prov/util: add a initializer function for util buffer pool 
- prov/mrail: add a buffer pool for mrail header
- prov/mrail: set correct values for buffered limits 
- prov/mrail: remove selective completion requirement from underlying provider
- common, mrail: fix slist_insert_order function

prov/rxm, mrail: enable buffered recv for large messages.

---

prov/psm2/Makefile.include
prov/psm2/configure.m4
prov/psm2/src/version.h

There has been another major update to the open source PSM2 code at
https://github.com/intel/opa-psm2 that requires the provider configury
be modified in order to allow building the provider with the PSM2 source
built-in. To avoid unnecessary complication, now such building option no
longer works with older PSM2 source.
Also remove header files from the "nodist" file list because they are
redundant.

prov/psm2: Sync with yet another PSM2 source code update

---

prov/psm2/configure.m4
prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_am.c
prov/psm2/src/psmx2_ep.c
prov/psm2/src/psmx2_init.c
prov/psm2/src/psmx2_rma.c
prov/psm2/src/psmx2_trx_ctxt.c

-Updated OFI PSM2 to use the new psm2_mq_fp_msg functionality in PSM2
that allows for a user to enqueue isends/irecvs into the MQ from within
an AM handler.
-Removes the need for tracking large RMAs with an internal queue and
improves the speed at which the target of RMAs can respond to read/write
requests. This greatly increases the performance in several areas making
RMA usage quicker with OFI PSM2.
-Added backwards compatability support for checking if psm2_mq_fp_msg is
available in the provided psm2 and instead compile with the previous
large size AM support enabled. This check is enabled in the
configure.m4.

prov/psm2: AM Large Size RMA usage of Fast Path isend/irecv in PSM2

---

man/fi_rstream.7.md
prov/rstream/Makefile.include

Please let me know what other features/info should be included in the man page. 

prov/rstream: Add provider specific man page

---

prov/psm2/src/psmx2_cq.c

-During psmx2_cq_readfrom if no events are read from poll_mq, then
psmx2_cq_dequeue_event will be called before exiting
even if there are no events in the cq->event_queue slist.
-Avoid unnecessary locking overhead associated with the dequeue_event
function by checking if the queue is empty in advance.
-This improves the latency & bandwidth for MPI usecases by up to 2-3% by
removing the lock during cq_read calls when 0 events are read.

prov/psm2: Prevent calls to dequeue event given no MQ events

---

include/ofi_util.h
prov/mrail/src/mrail.h
prov/mrail/src/mrail_cq.c
prov/mrail/src/mrail_domain.c
prov/mrail/src/mrail_ep.c
prov/mrail/src/mrail_rma.c
prov/util/src/util_ep.c

FI_RECV, FI_SEND, FI_READ and FI_WRITE supported. An additional protocol would
be needed in order to support FI_REMOTE_READ and FI_REMOTE_WRITE.

prov/mrail: Add basic support for counters.

---

include/ofi_mem.h
prov/util/src/util_buf.c

Currently, there is no way to retrieve an already allocated buffer
by its index.
The patch implements way to retrieve a buffer by specifying its index.
util_buf_ftr structure is updated to contain index of the buffer and
util_buf_pool structure is updated to contain the regions table that is
dynamically expanded (if there is no space in the regions table, the
regions table is reallocated and `its size = its previous size + 16`).
The tracking by index functionality will be used for implementing
FI_AV_TABLE for the new version of the utility AV.

util/buf: Add tracking of buffers by index

---

config/cron-make-nightly-tarball.pl
config/cron-run-all-md2nroff.pl
config/cron-submit-coverity.pl

Note that Coverity builds are still broken on the new OFI server (flatbed2) for a reason that I don't quite understand yet.  This PR fixes a bunch of stuff and sets us up on flatbed with the notable exception of Coverity builds.

Fixes and updates for cron/infrastructure scripts

---

config/cron-run-all-md2nroff.pl

The extra "git status"/"git add" is not necessary because a few lines
below, we just "git commit -a".  Also, with the new "all files in the
array contain the entire relative path name" schehem, we're not
currently chdir'ed into a git repository, so these git commands are
failing, anyway.

md2nroff: remove some useless code

---

prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_am.c
prov/psm2/src/psmx2_av.c
prov/psm2/src/psmx2_cntr.c
prov/psm2/src/psmx2_cq.c
prov/psm2/src/psmx2_domain.c
prov/psm2/src/psmx2_ep.c
prov/psm2/src/psmx2_mr.c
prov/psm2/src/psmx2_rma.c
prov/psm2/src/psmx2_trx_ctxt.c
prov/psm2/src/version.h

- Add Specialized functions for lock/unlock/trylock
given locks are enabled or disabled.
- Add function pointers to psmx2_fid_domain to set
lock/unlock functions for each individual lock
that is related to a specific domain.
- By default, all locks are enabled with all the
lock/unlock function pointers per domain set
to the lock enabled functions.
- Given a user requests FI_THREAD_DOMAIN OFI psm2
disables the locks for all uses of domain related objects
by setting the corresponding lock function pointers to the
lock disabled functions.
- If FI_RMA or FI_ATOMIC is set in the capabilities, then
cq_lock, rma_queue_lock, & am_req_pool_lock must always
be taken even with FI_THREAD_DOMAIN.
- The use of FI_PSM2_LOCK_LEVEL overrides this behavior
set in the domain_attr and uses the default …

prov/psm2: Lock optimization for FI_THREAD_DOMAIN

---

prov/tcp/src/tcpx_ep.c
prov/tcp/src/tcpx_rma.c

prov/tcp: bugfix - clear msg header flags before using

---

include/ofi_util.h

ofi_cirque_commit() increments the windex. So, we need to set the src before.

util/cq: Fix source address reporting.

---

prov/hook/src/hook.c
prov/hook/src/hook.h

Allow multiple hooks to be enabled at the same time when
specified in the FI_HOOK variable (e.g. FI_HOOK=perf:noop)
Signed-off-by: Ignacio Hernandez <ignacio.hernandez@intel.com>

hook: allow multiple hooks to be enabled

---

contrib/cray/Jenkinsfile.verbs
contrib/cray/bin/logwrap

Groovy variables defined in the pipeline are not exported
as environment variables to 'sh' steps. This commit fixes
the existing problem in the pipeline by explicitly exporting
the LIBFABRIC_INSTALL variable as part of the LIBFABRIC_INSTALL_PATH
environment variable during the test stage.

contrib/cray: Address scoping error in Pipeline

---

prov/psm2/configure.m4
prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_cq.c
prov/psm2/src/psmx2_msg.c
prov/psm2/src/psmx2_tagged.c
prov/psm2/src/version.h

-Updated PSM2 MQ to CQE conversion to use a new function psm2_mq_ipeek_dequeue_multi
which allows for a callback to be used to process the MQ entries into CQE events
to pass back to the user.
-PSM2 status structure now defaulted to psm2_mq_req_user with the structure being
exported by libpsm2 for reading by users.
-New callback function psmx2_mq_status_copy performs conversion of MQ request to
CQE event.
-New struct psmx2_status_data, is used to pass the user's event buffer along with
the poll CQ, src_addr, & trx_ctx to PSM2 for use in the callback when processing
each MQ request.
-All conditionals now assume the most common path will be when the user's event buffer
is used to store the events.
-psmx2_cq_any_complete updated to reduce branches given the most common
usecases by customers. …

prov/psm2: MQ to Completion Queue Event conversion optimization

---

prov/rxm/src/rxm.h

@shefty - This patch corrects the RxM wire protocol pad value that caused a wasteful alignment. The Verbs experimental XRC implementation uses some of the wasted space in implementing the sharing of XRC QP.
I was not sure if the RXM_CTRL_VERSION was the right thing to bump, but it seems like a version must be bumped to detect the differences in the structure alignment.

prov/rxm: Correct pad in RXM wire protocol structure (#35)

---

prov/util/src/util_buf.c

The commit fixes allocation of new buffer region.
Previous code doesn't set buf_region pounters in the `regions_table` and
foesn't increment `regions_cnt`.
It sets only for the first (with index = `0`) buffer region.

util/buf: Set missed buf_region pointers in the table

---

prov/usnic/src/usdf_fabric.c

This PR adds support for https://ofiwg.github.io/libfabric/master/man/fi_nic.3.html.
However, there are (at least) 2 problems that need to be resolved:
***EDIT: there's only 1 problem left***
1. https://ofiwg.github.io/libfabric/master/man/fi_nic.3.html states that `fid_nic.prov_attr` is only understood by the provider.
1. How do we know how to `tostr()` it?
1. How do we know how to free it (during `fi_freeinfo()`)?
Do we need additional provider ops for these functions?

Add core and usnic support for fid_nic

---

prov/gni/src/gnix_cq.c

@hppritcha @jswaro Can you please merge that one too? When multiple events were dequeued from fi_cq_readfrom(), the src_addr was not copied correctly and always overwriting the first entry.

prov/gni: Fix CQ readfrom overwriting src_addr in case of multiple events

---

include/ofi.h
include/ofi_prov.h
man/fi_hook.7.md
prov/hook/src/hook.c
prov/hook/src/hook.h
prov/hook/src/hook_ep.c
prov/hook/src/hook_perf.c
prov/hook/src/hook_perf.h
src/fabric.c

This series re-works how hooking providers are published and accessed by the core.  Hooking providers now register the same as other providers.  That is, they publish a struct fi_provider with the core.  Hooking providers are identified by the lack of support for getinfo().  This change will allow external providers to be used as hooks.  It also provides a mechanism to programmatically report what hooks are available in the current libfabric install.
Hooks are still identified using a string name.  The name can either be the provider name (e.g. ofi_perf_hook) or a shortened version of the provider name (e.g. perf).  Shortened names are expanded by prefixing with 'ofi_' and suffixing with '_hook'.  This provides backwards compatibility with previous names.
Hooks are now installed by …

Re-working of hooking providers

---

fabtests/common/shared.c
include/rdma/fabric.h

Include a necessary header file for struct iovec.

fabric/headers: Include sys/uio.h in files that reference iovec

---

include/ofi_list.h
include/ofi_mem.h
prov/util/src/util_av.c
prov/util/src/util_buf.c

This is related to discussions in PR #4543.  The buffer footer's are always enabled, with the slist entry used to track the request moved into the footer.  This avoids overlapping with user data, which allows the user to pre-format portions of the data as an optimization.
Several cleanups are applied around supporting this change.

util_buf: Always enable footer and use it to track buffers

---

fabtests/functional/poll.c
fabtests/test_configs/ofi_rxm/ofi_rxm.exclude
fabtests/test_configs/verbs/verbs.exclude
prov/rxm/src/rxm.h
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_rma.c

- fabtests: add some logging to fi_poll test 
- prov/rxm: fix counter increment for inject ops (not needed for v1.6.x)
- prov/rxm: use util_ep counter increment functions which don't have branches
- fabtests: enable some tests for verbs, rxm providers

fabtests, prov/rxm: updates to counters and fi_poll test

---

include/ofi_mem.h
prov/util/src/util_av.c
prov/util/src/util_buf.c

Currently, the utility buffer implementation allocates buffers from LRU list of buffers. This leads that it's impossible to determine what the index will be next.
Since utility AV uses utility buffer functionality to allocate `struct util_av_entry` and FI address, utility buffer has to allocate buffer with the lowest index from free buffer list.
This is done by adding new capability `indexing` = `{0, 1}` that should be set by user (e.g AV) to enable ordered allocation of buffers. The user which set `indexing = 1` has to use `util_buf_indexed_get` and `util_buf_indexed_release` and vice versa (`indexing = 0` - `util_buf_get`/`util_buf_release`).
- `util_buf_indexed_get` allocates buffer by retrieving the head of the buffer list (`util_buf_region::buf_list`) from the region that is the head …

util/buf: Allocate buffers with lowest index

---

contrib/cray/Jenkinsfile.verbs

In a prior commit, a srun of ldd was left in accidentally and was
not caught in review. This should be removed.

contrib/cray: remove unnecessary srun 

---

prov/rxm/src/rxm_rma.c

The commit makes the followign fucntions `static inline`:
- `rxm_ep_[write|read]msg`. They are used in [read|write]v and read|write. (4 palces)
- `rxm_ep_rma_inject`. It's used in `rxm_ep_writemsg`. (1 place)
- `rxm_ep_rma_common`. It's used in `rxm_ep_writemsg` and `rxm_ep_readmsg` (2 places)
i.e. `rxm_ep_rma_common` will be inlined in 8 places and `rxm_ep_rma_inject` in 1 place

prov/rxm: Make some RMA functions inline

---

prov/rxm/src/rxm.h

RxM increments Remote Read counter when handling `FI_READ` event, but
should increment Read counter. The patch fixes this + added `assert()`
to check whether `comp->flags` is `FI_READ or not`
Fixes #4557

prov/rxm: Increment Read counter when handling FI_READ event

---

fabtests/common/shared.c
fabtests/unit/av_test.c
prov/rxm/src/rxm_av.c

- prov/rxm: check for fi_addr before calling cmap update (bug fix not needed for v1.6.x)
- fabtests/unit: add a test for fi_av_insert with NULL fi_addr arg 
- fabtests/common: test passing NULL fi_addr to fi_av_insert 
Fixes #4551

fabtests, prov/rxm: fix missing check for fi_addr in av_insert + new tests

---

prov/rxd/src/rxd.h
prov/rxd/src/rxd_attr.c
prov/rxd/src/rxd_cq.c
prov/rxd/src/rxd_ep.c
prov/rxd/src/rxd_msg.c

- Add FI_MULTI_RECV support
- Change tx and rx freestacks to buffer pools for proper MULTI_RECV support and to allow x_entry pool to grow (gets rid of funky size*2 freestack size definition)

prov/rxd: FI_MULTI_RECV support and freestack to buffer pool change

---

prov/tcp/src/tcpx.h
prov/tcp/src/tcpx_comm.c
prov/tcp/src/tcpx_ep.c
prov/tcp/src/tcpx_progress.c

tcp provider performs two socket read calls to OS even for small messages. To reduce that overhead, read the first 4k bytes in the OS buffer to local buffer and process it. For only msgs larger than 4k would need more than one read call to get the message.

prov/tcp: improve small messages xfer rate by reducing num of sys calls per transfer

---

prov/rxm/src/rxm_av.c

RxM provider always checks (to find AV entry, to check already established connections
by peer) the first EP address from the array of addresses passed by user to
`fi_av_insert()`.

prov/rxm: Fix CM address handling

---

prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_cntr.c
prov/psm2/src/psmx2_cq.c
prov/psm2/src/psmx2_ep.c
prov/psm2/src/psmx2_trx_ctxt.c

Fix potential run-time errors when a CQ/counter is polled after one or more
endpoints bound to it have been closed.

prov/psm2: Clean up CQ/counter poll list when endpoint is closed

---

include/ofi_mr.h
include/rbtree.h
include/unix/osd.h
include/windows/osd.h
prov/rxm/src/rxm_cq.c
prov/util/src/util_mem_monitor.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_domain.c
prov/verbs/src/verbs_mr.c
src/rbtree.c

- common/osd: Add memory hooks setters and getters 
- prov/verbs: Use common memory hooks 
-  util/mem_monitor: Remove a subscription entry from NQ list when unsubscribed from a MR entry
- common/rbtree: Add tree traversal and get root routines 
- util/mem_monitor, prov/verbs: Write free/realloc events from hooks to NQ event list
- prov/verbs, util/mem_monitor: Fix notofication mechanism for MR cache 
- prov/rxm: fix a crash when incrementing error counter

[v1.6.x] cherry-picked bug fixes and related commits from master

---

prov/psm2/configure.m4
prov/psm2/src/psmx2_init.c

- Updated OFI PSM2 init to call the new PSM2 API psm2_info_query to read
--Number of HFI units
--HFI Unit status
--Number of free contexts on a specific HFI Unit
--Number of available contexts on a specific HFI Unit
- Removed need for OFI PSM2 to read HFI device status
and details for the sysfs and instead relies on libpsm2 to provide
accurate device information.
- Removed a 15s delay by verifying that /dev/hfi* exists
before calling psm2_init().
- Added backwards compatability when building with an older
libpsm2 without psm2_info_query.

prov/psm2: Use psm2_info_query to read HFI device info for OFI PSM2 init

---

prov/sockets/src/sock_ep_msg.c

The endpoint should transition into the enabled state on
fi_accept() automatically.

prov/sockets: Enable MSG EP when calling fi_accept

---

prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_cq.c
prov/psm2/src/psmx2_msg.c
prov/psm2/src/psmx2_tagged.c
prov/psm2/src/version.h

* Remove macros that have become redundant
* Clean-up definition format in the headers
* Port a sendv completion patch from the HAVE_PSM2_MQ_REQ_USER=1
case to the HAVE_PSM2_MQ_REQ_USER=0 case

prov/psm2: Code refactoring related to completion generation

---

.travis.yml

This PR is meant to address a deficiency in the current Travis CI build environment. With the XRC PR, Travis CI does not provide a sufficiently recent version to build the XRC implementation. The intent of this PR is to build a newer rdma-core for the Travis CI container and use that rdma-core build to compile the new feature.

travis: Provide newer ibverbs/rdma-core to support XRC builds in linux with Travis CI

---

prov/rstream/src/rstream_init.c
src/fabric.c

- common: don't print warning log when provider filter is created successfully
- prov/rstream: fix missing return value check

common, prov/rstream: fix logging and missing error checking

---

prov/psm2/src/psmx2_cq.c

When the source address is not present in the address table, an error
event is created to report the raw addess. In the HAVE_PSM2_MQ_REQ_USER=1
case, the error event was not put into the event queue, which it should.

prov/psm2: Yet another fix for source address reporting

---

prov/verbs/src/verbs_info.c

XRC requires the use of shared receive context; reflect this in the EP attrs
to indicate the XRC MSG_EP are configured to use a fi_srx_context.

prov/verbs: Set XRC info EP attribute rx_ctx_cnt

---

fabtests/common/shared.c
fabtests/functional/cm_data.c
fabtests/functional/multi_ep.c
fabtests/functional/rdm_atomic.c
fabtests/functional/rdm_deferred_wq.c
fabtests/functional/rdm_multi_recv.c
fabtests/functional/unexpected_msg.c
fabtests/include/shared.h
prov/verbs/src/verbs_ep.c

RxM will allocate a passive endpoint using the fi_info structure
allocated for an active endpoint.  As a result, the info::
dest_addr field may be set.  This triggers the assertion in
fi_ibv_eq_cm_getinfo() that dest_addr is null.
The issue is that when the passive endpoint is created, the
fi_info passed in is copied to the PEP.  This includes the
dest_addr, if present.
It turns out that the xrc code discards the dest_addr.  Remove
the xrc portion of the check and always discard (i.e. ignore)
the dest_addr if present.

prov/verbs: Discard destination address when allocated PEP

---

fabtests/test_configs/verbs/all.test
fabtests/test_configs/verbs/verbs.exclude
fabtests/ubertest/config.c
fabtests/ubertest/uber.c
include/ofi_util.h
prov/rxm/src/rxm.h
prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_init.c
prov/verbs/src/verbs_info.c
src/common.c

- util: fix reading CQ errors 
- prov/rxm: fix file descriptor and memory leaks
- fabtests/ubertest: don't skip utility providers 
- fabtests/ubertest: support FI_RX_CQ_DATA by default 
- fabtests/ubertest: add test config for testing verbs;ofi_rxm
- fabtests/test_config: update verbs exclude file to run ubertes

fabtests, prov/rxm: bug fixes + add ubertest config

---

contrib/cray/Jenkinsfile.verbs

Places the source tarball into a directory not read
by tar when creating the original file

contrib/cray: Place src tarball into exclude dir

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_rma.c

RxM supports WAS, RAS message orderings by design if a core provider supports them.
But it was broken when deferred TX queue was implemented for deferred protocol
messages of SAR and RNDV protocols.
The commit fixes it by checking the deferred TX queue of the particular connection in
the RMA operations. If the deferred TX queue is empty, it performs RMA operation, else
it return -FI_EAGAIN to the caller.
This patch impelements `rxm_ep_prepare_tx()` functions that acquires connections and
checks deferred queue.

prov/rxm: Fix support of WAS, RAS message orderings + small code refactoring

---

.gitignore
fabtests/Makefile.am
fabtests/scripts/runfabtests.sh
fabtests/test_configs/ofi_rxd/ofi_rxd.exclude
fabtests/test_configs/verbs/all.test
fabtests/ubertest/uber.c
prov/rxd/src/rxd.h
prov/rxd/src/rxd_atomic.c
prov/rxd/src/rxd_av.c
prov/rxd/src/rxd_cq.c
prov/rxd/src/rxd_ep.c
prov/rxd/src/rxd_msg.c
prov/rxd/src/rxd_rma.c
src/fabric.c

Summary:
- enable provider by default
- AV return bug fixes
- peer connection organization/retrying of connection packets
- add retry warning message
- recv_cancel fix to maintain sequence numbers
- length calculation fix/clean
- add exclude file
- add UDP;ofi_rxd to make test for Travis
Also throwing a gitignore fix in here (add fabtests/* extension since repos were merged)
Updated:
Added commit to enable psm2;ofi_rxd by copying resolved address needed for the name server.
Added commit to re-enable skipping of utility providers in ubertest.

prov/rxd: bug fixes, enable provider, add to Travis

---

prov/verbs/src/verbs_info.c

This patch improves checks for IB UD addresses (verbs/DGRAM only) by adding
additional check for EP type. If an application requsts FI_EP_DGRAM we can
check for only IB UD addresses and don't check for Sockets addresses.
Also it adds separate branch for MSG EP type - checks for FI_EP_MSG EP type and
addres type == FI_SOCKADDR*.
As a results, this patch fixes fi_getinfo_test tests (that set destination
address) with RxD/Verbs/DGRAM provider.

prov/verbs: Improve address handling in fi_getinfo

---

fabtests/test_configs/ofi_rxd/ofi_rxd.exclude
include/ofi_util.h
prov/util/src/util_av.c
prov/util/src/util_main.c

UDP;ofi_rxd was failing the fi_unexpected_msg test because UDP wasn't setting the address format correctly
This resolves the issue and re-enables the test for rxd

prov/util: set addr_format correctly + reenable unexpected test for RxD

---

contrib/cray/Jenkinsfile.verbs

With the DST integration work, emails had to be disabled temporarily.
This commit enables emails using the new email function in the shared
library in Jenkins.

contrib/cray: enable email messages 

---

prov/psm2/src/psmx2_av.c

Make sure scalable endpoint information have been initialized before
being used for source address translation.

prov/psm2: Fix potential segfault in source address translation

---

prov/rxm/src/rxm_ep.c

Thanks to @AddyLaddy for finding the root cause.
FIxes #4616

prov/rxm: fix incorrect length in packet header for inject

---

src/fi_tostr.c

tostr: Fix signed to unsigned size_t print format specifier

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_av.c
prov/rxm/src/rxm_conn.c

This patch fixes the issues where application inserts the same
addresses several times. util/av searches the addresses in the
hash. If utl/av finds some address in the hash, it returns
address's fi_addr to the user.
So, relying on this fact, this fix is to check handles_av array
and retrieve the CMAP handle if this is known `fi_addr`.

prov/rxm: Fix handling of addresses inserted several times

---

prov/verbs/src/fi_verbs.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_info.c

The function returns rdma_addrinfo and rdma_cm_id that corresponds to a valid
verbs device if the parameters don't correspond to a wildcard address. Unlike
fi_ibv_create_ep, fi_ibv_get_rai_id doesn't create the QP. Update fi_ibv_getinfo
to use this function.
This fixes an issue where an utility provider may need to call fi_getinfo with
CM fi_info as hints. Without this fix rdma_create_ep invoked in fi_ibv_getinfo
would return "address already in use" error. Utility providers call fi_getinfo
on a fi_domain or fi_endpoint call to resolve the right core provider info for
creating core provider domain or endpoint resource.

prov/verbs: add a lightweight function that gets rdma_addrinfo and rdma_cm_id

---

contrib/cray/Jenkinsfile.verbs

Depending on ordering, and parallel execution of pipeline stages,
the Jenkinsfile could redefine the test directory variable during
execution.

contrib/cray: Use unique dirs for RC/XRC tests 

---

prov/verbs/Makefile.include
prov/verbs/configure.m4
prov/verbs/src/fi_verbs.h
prov/verbs/src/ofi_verbs_priv.h
prov/verbs/src/verbs_domain_xrc.c
prov/verbs/src/verbs_ep.c
prov/verbs/src/verbs_info.c
prov/verbs/src/verbs_msg.c
prov/verbs/src/verbs_rma.c

RHEL runs an old version of libibverbs that isn't supported
with the current version of the verbs provider. This commit
introduces several defines and macros to simulate the existence
of an updated libibverbs and header files and relies on the
underlying libraries to provide the appropriate errors when
necessary.
closes #4658

verbs: Add defines and macros to support RHEL build

---

contrib/cray/Jenkinsfile.verbs

This commit introduces the isRelease function to the set of
criteria checked during the publish stage. If the branch name provided
is the same branch that should be published to the DST repository,
then the expression should trigger the publish stage.

contrib/cray: Change publish criteria 

---

contrib/cray/Jenkinsfile.verbs

contrib/cray: Add ubertest to test matrix
Adds fi_ubertest to test matrix for Jenkins pipeline for
additional validation of the verbs provider.

contrib/cray: Add ubertest to test matrix 

---

prov/gni/include/gnix_vc.h
prov/gni/src/gnix_msg.c
prov/gni/src/gnix_vc.c

retain the gnix_ep_name field in the vc struct
if needed and free in vc destructor.  make a copy
of the content of the gnix_ep_name when reporting back
to the application using FI_SOURCE_ERR.
fixes #4521

prov/gni: fix a problem with double free

---

prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_eq.c

This PR fixes two XRC CM REJ message handling segfaults associated with CM REJ messages that are initiated from the CM, not the peer provider (two commits). It also temporarily disables the early release of XRC connection resources letting the existing EP close normal processing handle it (one commit). The latter is to allow correct operation until resources remaining in the timed wait state can be further addressed.

prov/verbs: Fix segfault caused by XRC CM REJ message handling for non-application rejects

---

prov/rxm/src/rxm_atomic.c

Correctly set the RMA IOC count member for fi_inject_atomic() API
implementation.

prov/rxm: Fix fi_inject_atomic() RMA IOC count

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_atomic.c
prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_rma.c

RxM can drive progress across an EP from several call sites.  The result is that while serialization is provided on individual queues, structures, and lists, the overall progress model is not thread safe.  This can be seen by the app as receiving messages out of order, or received messages being associated with the wrong posted buffer.
To fix this, we need to serialize the progress handling at a higher level.  However, this requires restructuring the locking, so that the EP lock can be held across the full handling of messages.  Care must be taken that we don't lose locks where they are needed, and that we don't introduce nested locking/deadlocks.
This series provides several patches to restructure and simplify the code.  We then move the EP locking up to the desired functions, so that …

prov/rxm: Rework locking around progress

---

prov/rxm/src/rxm.h

When the underlying message endpoint is unable to connect, return -FI_EHOSTUNREACH instead of -FI_ENOTCONN, since the RDM EP itself is connectionless.

prov/rxm: Don't return -FI_ENOTCONN for RDM endpoint

---

util/pingpong.c

These changes allow fi_pingpong to work with the tcp provider.
It still hangs when running over rxm + tcp, with rxm unable to complete its connection.  That is being debugged.

fi_pingpong: Fixes to work with tcp provider

---

fabtests/test_configs/ofi_rxd/ofi_rxd.exclude

The RxD provider doesn't use msg_prefix so exclude those tests.
(The Intel CI tests master periodically in "Strict" mode which treats all "Notrun" results as failures)

test_configs/ofi_rxd: disable prefix tests

---

man/fi_rxm.7.md

Explicitly note that in addition to the expected FI_EAGAIN error return cases described in the fi_msg man page, that FI_EAGAIN should also be expected during on-demand connection setup of the core provider message EP.
Application feedback has indicated that FI_EAGAIN was not expected for the first data transfer operation.

prov/rxm: Update man page to note FI_EAGAIN return for on-demand connection setup

---

man/fi_rxm.7.md
man/fi_verbs.7.md

MAN page update commits to reflect support for FI_ATOMIC in fi_rxm(7), and mention XRC limitations and the new FI_VERBS_PREFER_XRC parameter in fi_verbs(7).

man: MAN page updates for fi_verbs(7) and fi_rxm(7)

---

configure.ac
prov/util/src/util_atomic.c

Implements a new version of common code emulated atomics that takes advantage of compiler built-in memory model aware atomic operations. If MMA built-in atomics are not supported, the atomic handlers will continue to use the previous non-compiler built-in functions.
Note: data-types > 8 bytes in size are not supported; otherwise there is the same op/data-type coverage.

prov/util: Add support for compiler builtin common atomic implementation

---

prov/util/src/util_cq.c

Most of OFI applications implemnts send-progress-retry logic in case of
`fi_send`/`fi_inject` operations returns -FI_EAGAIN.
Some of them don't provide the buffer(s) for completions (i.e.
`fi_cq_[s]read` with `count` = 0), because they don't know how to handle
unexpected completions.
If there is at least one CQ entry (for the previous operations) in circular
queue (utility CQ storage for the completions that ready to read by user)
and such application calls handles -FI_EAGAIN from `fi_send`/`fi_inject` with
`fi_cq_read(..., count = 0)`, it leads to hang in this send-progress-retry.

prov/rxm: Fix lack of MSG CQ progress

---

prov/rxd/src/rxd_av.c

This patch fixes the issue that has been reproduced by #4708 PR.
RxD reports the same `fi_addr_t` identifications for the different
addresses without this patch.

prov/rxd: Fix wrong insertion of addresses into AV

---

prov/rxd/src/rxd_cq.c
prov/rxd/src/rxd_ep.c
prov/rxd/src/rxd_init.c
prov/rxd/src/rxd_msg.c
prov/rxd/src/rxd_rma.c

- NULL check
- release and repost recv packet if RMA entry could not be initialized
- fix max_inline calculation
- set inject size for usage with tagged, RMA, and atomic injects
- subtract prefix size when progressing unexpected packets
- get rid of unnecessary return set

prov/rxd: various fixes

---

prov/psm2/src/psmx2.h

Single threaded applications may set FI_PSM2_LOCK_LEVEL=0 to reduce
locking overhead. However, the existence of the PSM2 receive thread
means race condition can still happen even if the application itself
has only one thread.
Fix by keeping the affected lock in effect when FI_PSM2_LOCK_LEVEL
is set to 0.

prov/psm2: Fix a race condition with PSM2 receive thread

---

prov/verbs/src/verbs_dgram_ep_msg.c
util/pingpong.c

Without these fixes verbs/DGRAM provider doesn't work with `fi_pingpong` utility.

pingpong, prov/verbs: Various fixes for verbs/DGRAM provider and pingpong

---

prov/psm/src/psmx_init.c
prov/psm2/src/psmx2_init.c

prov/psm,psm2: Disable name server when PMIx is in use

---

prov/psm/src/psmx_init.c
prov/psm2/src/psmx2_init.c

prov/psm,psm2: Correct the name of the environment variable set by PMIx

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_conn.c

This patch reduces number of simultaneous connections by adding
connection events progress in the function that handles initiates
connections to the remoteside in case of them is unconnected
(dynamic connections).

prov/rxm: Add connection events progress

---

util/pingpong.c

This patch changes behavior of PP by inserting the local and
remote address into OFI AV es in the following order:
1) The PP client inserts the remote nae and then the local name
2) The PP server inserts the local name and then the remote name
This is needed to construct behavior of many apps that are
relises on PMI and its Key-value Storage (KVS).

pingpong: Insert local name into AV

---

contrib/buildrpm/buildrpmLibfabric.sh
contrib/cray/Jenkinsfile.verbs

This PR addresses two issues:
- In the build RPM script, it seems that the new arguments for RPM build are being prepended to the incorrect variable.
- For Cray builds, the default installation prefix should be different to accommodate different installation namespaces. 
closes #4723

contrib/buildrpm,contrib/cray: Change prefix for pipeline generated RPMs

---

prov/rxm/src/rxm_init.c

Make sure FI_MSG and FI_RMA caps are set correctly in the core provider
hints, taking into account that RXM support for FI_ATOMIC requires
provider support for FI_MSG, and RXM support for FI_MSG requires core
provider support for FI_RMA in addition to FI_MSG.

prov/rxm: Fix setting of FI_MSG and FI_RMA caps for core hints

---

prov/rxm/src/rxm_init.c

Make sure FI_MSG and FI_RMA caps are set correctly in the core provider
hints taking into account that RXM support for FI_ATOMIC requires
provider support for FI_MSG, and RXM support for FI_MSG requires core
provider support for FI_RMA in addition to FI_MSG. Explicitly set the
RMA and Message caps required by RXM protocols.

prov/rxm: Fix setting of required RXM caps in the core provider hints

---

prov/rxm/src/rxm_cq.c

Do not access the CQ err_entry context field prior to being initialized.

prov/rxm: Fix segfault reading provider CQ error entries.

---

configure.ac

This fixes #4742.
Signed-off-by: Ben Menadue <ben.menadue@nci.org.au>

configure: save CFLAGS when testing for valid flags from `debug_c_other_flags`

---

man/fi_psm2.7.md
prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_av.c
prov/psm2/src/psmx2_init.c

Define new environment variable FI_PSM2_CONN_TIMEOUT to control timeout
of connection establishment. Larger value (the default is 5 seconds)
may be necessary for large scale runs.

prov/psm2: Add runtime parameter for connection timeout

---

contrib/buildrpm/buildrpmLibfabric.sh
libfabric.spec.in

Adds variables to enable creation of default version file
for the Modules package, change module prefix, and change
installation prefix.
closes #4724

contrib/buildrpm: Add options for RPM creation

---

prov/verbs/src/verbs_cm_xrc.c

When fi_accept() fails, do not free the connection request handle,
it will get freed when fi_reject is called for this failure. This
is consistent with the RC error path. Also correct the log statement
associated with this error.

prov/verbs: Fix double free of connection request info in XRC fi_accept error path

---

man/fi_mr.3.md

The access flags indicate the type of operations allowed against
a memory region, not necessarily the 'access' being made to the region.
The flag definitions clarify this, but make it clearer up front.
This does not change the semantics of the flags.

man/mr: Clarify MR access flags applies to operations

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_cq.c

prov/rxm: Remove excessive RX buffer in Rendezvous TX

---

prov/util/src/util_buf.c

The tcp provider uses the buffer pool, but does not fully
initialize newly allocated buffer entries.  This results in
applications accessing uninitialized memory.  As a fix and
to prevent similar issues appearing in other providers or
future code, always zero new buffer allocations.

core/buf_pool: Zero newly allocated memory

---

prov/tcp/src/tcpx.h
prov/tcp/src/tcpx_conn_mgr.c
prov/tcp/src/tcpx_ep.c

tcpx_passive_ep use a structure assignment to make a copy of
struct fi_info.  However, this does not result in a deep
copy of the structure, which can lead to a double free
condition.  Use fi_dupinfo to make a deep copy correctly.

prov/tcp: Use fi_dupinfo to copy fi_info

---

fabtests/functional/stream_msg.c

fabtests/stream: Fix static function declaration

---

fabtests/unit/getinfo_test.c
include/ofi_net.h
prov/sockets/src/sock_fabric.c
prov/tcp/src/tcpx_init.c
src/common.c

This allows the fi_getinfo_test to run cleanly without reported memory leaks.

prov/tcp: Couple of memory leak fixes

---

fabtests/functional/av_xfer.c
fabtests/functional/cm_data.c

Reported by leak sanitizer running over tcp provider.

fabtests: Fixes for a couple of memory leaks

---

prov/tcp/src/tcpx_ep.c

handle allocated by tcp provider for FI_CONNREQ notifications. App would use it to either create a new active ep or reject the request. In both cases, handle has to be freed after expected action. Reject path is not freeing it. This patch fixes that.

prov/tcp: fix memory leak

---

prov/psm2/src/psmx2_atomic.c
prov/psm2/src/psmx2_rma.c

Replace the alternative method adopted before the function was introduced.

prov/psm2: Use psm2_epaddr_to_epid() for epaddr to epid conversion

---

prov/rxm/src/rxm_ep.c

SAR protocol uses eager limit as segment size. The seg_size field in ofi_ctrl_hdr
is limited to 16 bits, so we should check if segment size fits before employing
SAR protocol.
An alternative solution is to use bigger type (e.g. uint32_t) for seg_size but
that would increase latency for small messages.

prov/rxm: fix truncation error when using SAR protocol with eager_limit > 64KB

---

prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_init.c
prov/verbs/src/verbs_info.c

- prov/verbs: fix FI_RX_CQ_DATA not being set in info->mode on return from fi_getinfo
- prov/rxm: fix setting default buffered min limit

[v1.7.x] prov/verbs, rxm: fix for FI_RX_CQ_DATA and default buffered min

---

prov/verbs/src/verbs_cm_xrc.c

Connection request handle will be freed on subsequent fi_reject().
This makes XRC consistent with RC implementation.
(fix from commit: 893eb199a7f683102546914cd120b3b307dd122c)

[v1.7.x]prov/verbs: Fix double free of connection request info in XRC fi_accept error path 

---

configure.ac

1. Do not use a link test before checking whether libatomic is
required to provide __atomic built-in symbols.
2. Include usage of an __atomic_load_n function in compilation test,
since some old compilers (e.g. Clang 3.4) support __atomic_load but
not __atomic_load_n.

configury: Fix mm aware atomic test

---

src/linux/osd.c

Configure checks puts macro definitions of supported ethtool functionality: `#define HAVE_ETHTOOL,` `#define HAVE_DECL_SPEED_UNKNOWN`, etc. in config.h. So, `#ifdef` directives in src/linux/osd.c are always true even in cases when target machine doesn't support some of these features. That results in compilation error. 
This PR fixes this problem.

linux/osd: fix ethtool preprocessor directives

---

fabtests/test_configs/shm/all.test
include/ofi_shm.h
include/ofi_util.h
man/fi_shm.7.md
prov/rxm/src/rxm_atomic.c
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_rma.c
prov/shm/src/smr.h
prov/shm/src/smr_atomic.c
prov/shm/src/smr_attr.c
prov/shm/src/smr_av.c
prov/shm/src/smr_comp.c
prov/shm/src/smr_ep.c
prov/shm/src/smr_msg.c
prov/shm/src/smr_progress.c
prov/shm/src/smr_rma.c
prov/util/src/util_ep.c
prov/util/src/util_shm.c

- fix shm unmapping to allow ubertest to run
- add selective completion support in shm provider
- add SELECTIVE_COMPLETION tests to shm and sockets to check all cases
- change assert to check and return
- man page update
- add util_ep->tx_msg_flags and util_ep->rx_msg_flags to check for default flags for msg functions and update in the rxm provider
- set mr_key_size
- address fixes

prov/shm: add SELECTIVE_COMPLETION support and other fixes

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_domain.c

Take into account the RXM atomic protocol headers when determining maximum payload size for atomic operations.

prov/rxm: Fix initialization of maximum atomic payload size

---

contrib/buildrpm/buildrpmLibfabric.sh

The 'libfabric' tag was missing from the package path. RPMs were installing
to /opt/my/prefix rather than /opt/my/prefix/libfabric. This commit fixes
that issue.
@tonyzinger @jsquyres

contrib/buildrpm: Add libfabric tag to path

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_domain.c

[v1.7x] prov/rxm: Fix initialization of maximum atomic payload size

---

include/ofi_mem.h
prov/tcp/src/tcpx.h
prov/tcp/src/tcpx_domain.c
prov/tcp/src/tcpx_ep.c
prov/tcp/src/tcpx_progress.c
prov/tcp/src/tcpx_shared_ctx.c

This series fixes an issue where buffers may be returned to the wrong buffer pool.  The last 2 patches in the series need to be examined for correctness.  The last one fixes what I believe is an issue that would result in losing application posted receives.  This looks to be severe enough that I'm surprised that the provider works well at all.  But because it is working makes me question the fix.  The second to last one merges two functions that conceptually should be doing the same thing.  However, they are notable differences between them, so the merged function needs to be examine to see which of the two functions it needs to match.

prov/tcp: Fixes for memory leaks

---

configure.ac

The previous attempt to fix this test was wrong because AC_TRY_COMPILE
succeeded in compiling the test case if implicit function declaration
was allowed. Now the strategy is:
1. Use AC_SEARCH_LIBS to detect if atomic symbols are internal to the
compiler, or provided by -latomic. Set LIBS accordingly.
2. Use AC_TRY_LINK to build the main test case. If the test is
unsuccessful, restore LIBS to its prior state.

configury: Fix mm aware atomic test (2nd try)

---

prov/rxm/src/rxm_cq.c

cherry picked from commit c6c6ef79f250b1a88479c8d008b58d0e1e319cd3

[v1.6.x] prov/rxm: repost directed recv when AV updated only FI_DIRECTED_RECV is used

---

fabtests/common/shared.c
fabtests/functional/multi_mr.c
fabtests/functional/rdm_multi_domain.c
fabtests/functional/rdm_multi_recv.c
fabtests/functional/resmgmt_test.c
fabtests/functional/unexpected_msg.c
fabtests/include/shared.h
prov/rxm/src/rxm.h
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c

- prov/rxm: add some logging 
- fabtests: use size_t for some size types to fix comparison warnings 
- fabtests: add data integrity verification to multi recv test 
- prov/rxm: merge op_flags and flags args in rxm_ep_recv_common_flags 
- prov/rxm: remove RXM_INJECT_TX state from MSG CQ completion handler

prov/rxm: minor refactoring + bug fix and updates for fabtests

---

fabtests/Makefile.am
fabtests/test_configs/freebsd.exclude

test_configs/freebsd: Exclude msg_epoll

---

fabtests/test_configs/shm/shm.exclude

av_test does not support FI_ADDR_STR

test_configs/shm.exclude: exclude av_test

---

prov/util/src/util_eq.c

Use fi_strerror instead of strerror

---

prov/rxm/src/rxm_conn.c

If RxM receives a FI_CONNECTED event from the underlying MSG provider,
RxM assumes the context is the cmap handle and dereferences it. This
should always be safe, but it can be hard to debug in optimized code
if the context is incorrectly null. This is not a performance
sensitive code path so an extra defensive check is harmless.

RxM: Defensive code against a null pointer deref.

---

include/ofi_mem.h
include/ofi_rbuf.h
include/ofi_util.h
prov/util/src/util_wait.c

Three types of fixes:
* missing extern "C"
* implicit casts from void*
* the "try" reserved word

C++ compatibility fixes

---

prov/sockets/src/sock_ep_msg.c

Fix uninitialized pointer in sock_ep cm_entry.info

---

fabtests/test_configs/osx.exclude

This issue was fixed in https://github.com/ofiwg/libfabric/pull/4028.

test_configs/osx: Re-enable msg_sockets

---

prov/psm/src/psmx_wait.c
prov/psm2/src/psmx2_wait.c

Updates to fix the C++ compile broke the psm/psm2 builds.

prov/psm: Fix build error with rename of 'try'

---

prov/verbs/src/verbs_cm_xrc.c

If the physical INI XRC QP is rejected, allow any reciprocal INI
XRC QP connections pending on that QP to be scheduled.

prov/verbs: Fix shared XRC INI QP connection setup scheduling error

---

prov/sockets/src/sock_ep_msg.c

Backtrace is the following:
0 in pthread_spin_lock (&cm_head->signal_lock)
1 in sock_ep_cm_connect_handler () **Tries to acquire cm_head->signal_lock**
2 in sock_ep_cm_handle_rx ()
3 in in sock_ep_cm_thread () **Holds cm_head->signal_lock**

prov/sockets: fix double lock acquisition

---

prov/rxm/src/rxm_cq.c

When setting the RXM CQ error entry status, convert provider error to a positive code when assigning to the "err" field to comply with fi_cq_readerr fi_cq_err_entry description. The routines that write the CQ error entry are passed provider error values.

prov/rxm: Fix setting of the CQ error entry "err" sign

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_conn.c
prov/tcp/src/tcpx_conn_mgr.c

- prov/rxm: skip unnecessary endian conversion for eager_size
- prov/tcp: set cm_entry->info->dest_addr when writing FI_CONNREQ event 
- prov/rxm: redo CM data exchange in connection management 
@vkrishna the 3rd patch fixes an issue in tcp provider.

prov/rxm, tcp: updates for CM data exchange and handling connection request

---

include/ofi_mem.h
prov/mrail/src/mrail.h
prov/mrail/src/mrail_cq.c
prov/mrail/src/mrail_ep.c
prov/psm2/src/psmx2.h
prov/rxd/src/rxd.h
prov/rxd/src/rxd_cq.c
prov/rxd/src/rxd_ep.c
prov/rxm/src/rxm.h
prov/rxm/src/rxm_atomic.c
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_rma.c
prov/sockets/src/sock_progress.c
prov/tcp/src/tcpx_cq.c
prov/tcp/src/tcpx_domain.c
prov/tcp/src/tcpx_shared_ctx.c
prov/util/src/util_av.c
prov/util/src/util_buf.c
prov/util/src/util_mr_cache.c
prov/verbs/src/verbs_cq.c

Add an extra buffer to each region, which allows each entry to reference the previous entry's footer as its header.  Using a header allows using a fixed sized offset to jump between the user's buffer and the header. 
This removes the need to provide the pool as input into several calls, most notably free.  With that change, we remove the chance of a caller returning the buffer to the wrong pool, leading to difficult to isolate data corruption issues.  It also allows further optimizations in the providers where they are tracking the pool, simply to handle the free case.

util/bufpool: Final set of changes, switch from footer to header to simplify APIs

---

include/ofi_util.h
prov/tcp/src/tcpx_ep.c
prov/util/src/util_eq.c

RxM over TCP case:
In rxm when two processes try to connect to each other at same time, they accept or reject connection based on whose address is higher. The process that accepts the connection 1 would go ahead and close the other connection 2. But the peer may reject the connection 2 later, resulting in broken pipe. 
This patch suppresses broken pipe on reject. Also pending eq events are removed on ep close, avoiding any actions on closed ep based on stale events.

prov/tcp; Fixes the issue with mpich ic2 test.

---

man/fi_cq.3.md
man/fi_eq.3.md

This affects cq and eq sread calls.  Both allow for something
to wake up the blocked thread.  If the wake-up is not the result
of a fatal error, sread will return EAGAIN.
The only implication here is that the thread may return prior
to any timeout value expiring.

man/sread: Add clarifying text to sread return values

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_cq.c

- prov/rxm: avoid fi_getinfo roundtrip during FI_EP_MSG connect 
- prov/rxm: minor refactoring to simplify code 
- prov/rxm: add a cast for fi_recv return value

prov/rxm: optimize MSG_EP connect code path and do minor refactoring

---

include/ofi_proto.h
include/ofi_util.h
prov/rxd/src/rxd.h
prov/rxd/src/rxd_cntr.c
prov/rxd/src/rxd_cq.c
prov/rxm/src/rxm_cq.c
prov/shm/src/smr.h
prov/shm/src/smr_atomic.c
prov/shm/src/smr_cntr.c
prov/shm/src/smr_comp.c
prov/shm/src/smr_msg.c
prov/shm/src/smr_progress.c
prov/shm/src/smr_rma.c
prov/util/src/util_cntr.c
prov/util/src/util_cq.c

Change counter function declaration from using flags (256->8192) to the op enums (1->9)

prov/util,shm,rxd,rxm: optimize cntr function array

---

prov/rxm/src/rxm.h

Correctly set the tx buffer descriptor when returning atomic response with
fi_send.

prov/rxm: Fix sending of non-inline atomic response protocol message

---

prov/rxm/src/rxm_init.c

Clear EP max order size for unsupported message order and require
data FI_MANUAL_PROGRESS until auto data progress can be supported.

prov/rxm: Fix returned fi_info attributes when FI_ATOMIC is specified

---

include/freebsd/osd.h

Include fi_errno.h to avoid undeclared identifier FI_ENOSYS.

osd/freebsd: Fix missing header include

---

prov/rxm/src/rxm_cq.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_cq.c

This PR cherry-picks @sydidelot 's commit from #4756 and adds additional handling needed in verbs and rxm providers.
Since app thread can read MSG CQ before the CM thread has handled shutdown or reject we may end up getting error entries for canceled receives and that needs to be handle in rxm.
This should also avoid de-referencing a NULL `rx_buf->recv_entry` and is a replacement fix for the commit in PR #4821 . @chrisdolan would you be able to verify that you don't see any NULL pointer de-referencing in your app?

prov/rxm: handle canceled receives from MSG provider

---

prov/mlx/configure.m4

The underlying ucx library has not maintained backwards
compatibility.  This can result in build errors because of
modified or removed APIs.  Disable the mlx provider by
default.

prov/mlx: Do not enabled unless explicitly requested

---

fabtests/ubertest/cq.c
include/ofi_util.h
prov/rxd/src/rxd.h
prov/rxd/src/rxd_atomic.c
prov/rxd/src/rxd_cq.c
prov/rxd/src/rxd_ep.c
prov/rxd/src/rxd_msg.c
prov/rxd/src/rxd_rma.c
prov/rxd/src/rxd_tagged.c
prov/rxm/src/rxm_cq.c
prov/shm/src/smr_atomic.c
prov/shm/src/smr_comp.c
prov/shm/src/smr_msg.c
prov/shm/src/smr_progress.c
prov/shm/src/smr_rma.c

- Add util_ep->msg_flags
- Pre-calculate flags
- Correctly use cntr functions
- Use util_cq write functions
- Also includes small fabtests fix related to completions

prov/rxd: cq, cntr, flag fixes

---

man/fi_psm2.7.md

Did you think you would get rid of my random typo fixes that easily? BWAHAHAHAHA.
Signed-off-by: Erik Paulson <epaulson10@gmail.com>

Fix repeated 'the' in fi_psm2 manpage

---

prov/util/src/util_atomic.c

Atomics can end up being supported in a couple of different ways.
Add a log message to the atomic_valid call to indicate which
implementation is being used.

util/atomics: Add log message to indicate atomic implementation

---

man/fi_atomic.3.md

Document that the behavior of multiple actors performing atomic
operations against the same memory target is undefined.  Actors
in this term mean CPUs and NICs.

man/atomics: Expand definition of atomic correctness

---

fabtests/COPYING
man/fi_cq.3.md
man/fi_gni.7.md
prov/gni/src/gnix_util.c
prov/psm/src/psm_am.h
prov/usnic/src/usdf_rdm.c

In #4854, @j-xiong pointed out more instances of this typo in the man pages. I fixed those and went on a further pedantic rampage, removing it from code comments and the fabtest dual-license as well.

Remove "the the" from manpages, comments, and license.

---

prov/verbs/src/verbs_mr.c

Problem was reported by a multi-threaded app with each thread
accessing an isolated endpoint.  The cache would become
corrupted.

prov/verbs: Add locking around registration cache calls

---

prov/verbs/configure.m4

The code for XRC requires the support of rdmacm_create_qp_ex, which
is not always available. On some platforms like Centos 7.x, this
would result in an error due to implicit declaration of function
rdma_create_qp_ex:
prov/verbs/src/verbs_domain_xrc.c:89:2: warning: implicit declaration
of function 'rdma_create_qp_ex' [-Wimplicit-function-declaration]

prov/verbs: check the presence of rdmacm_create_qp_ex for XRC

---

fabtests/test_configs/ofi_rxd/ofi_rxd.exclude
fabtests/test_configs/ofi_rxm/ofi_rxm.exclude
fabtests/test_configs/ofi_rxm/verbs/exclude
fabtests/test_configs/osx.exclude
fabtests/test_configs/psm2/psm2.exclude
fabtests/test_configs/shm/shm.exclude
fabtests/test_configs/tcp/tcp.exclude
fabtests/test_configs/udp/udp.exclude
prov/rxd/src/rxd_ep.c

Crash shows up when running fi_rdm_cntr_pingpong on OS X.  OS X doesn't support epoll, which results in a failure obtaining the underlying fd.

prov/rxd: Fix crash resulting from double free in error case

---

prov/rxm/src/rxm_atomic.c
prov/rxm/src/rxm_cq.c

This PR fixes wrong counters being incremented for atomic ops. Also adds some logging to aid in debugging.

prov/rxm: bug fixes for atomics

---

prov/mrail/src/mrail_init.c

Modes are restrictions from the provider. The application can set more
mode bits than necessary in the hints to indicate that the application
is ready to handle those restrictions. It is incorrect to reject mode
bits outside the pass-through set because they may be cleared by the
core provider in the end. The correct way is to clear these bits from
hints so that the core provider would not assume those modes are handled
by upper layer.

prov/mrail: Fix how pass-through mode bits are checked

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_init.c

Additional cherry picked fixes for RXM Atomic support:
prov/rxm: Fix returned fi_info attributes when FI_ATOMIC is specified
prov/rxm: Fix sending of non-inline atomic response protocol message

[V1.7.x] prov/rxm: Cherry pick of additional RXM atomic fixes

---

prov/tcp/src/tcpx_comm.c

when get_rx_entry fails, there is a possibility that tcpx_recv_hdr will return FI_ENOTCONN - when called after full header already read from socket. This patch eliminates that case.

[v1.7.x] prov/tcp: fix for tcpx_recv_hdr returning FI_ENOTCONN

---

fabtests/common/shared.c
fabtests/functional/av_xfer.c
fabtests/functional/unexpected_msg.c
fabtests/include/shared.h
fabtests/man/fabtests.7.md

The '-b' option enables OOB address exchange and test synchronization.
However, some tests rely on the synchronization to make progress over
certain providers. They won't work with OOB channel turned on.
Add the '-E' option that enables address exchange over the OOB channel
but keeps test synchronization going through the provider.

fabtests: Add option to enable OOB address exchange only

---

fabtests/scripts/parseyaml.py
fabtests/scripts/toCSV.py

Upstream no longer supports python 2.  Starting in RHEL 8
all python scripts must be python 3.

scripts/python: Convert python 2 scripts to version 3

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_atomic.c
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_init.c

This PR cherry-picks the eager limit fix from #4874 without the API changes. This also includes some harmless minor patches to avoid merge conflicts.

[v1.7.x] prov/rxm: cherry-pick eager limit fix

---

prov/verbs/src/verbs_domain_xrc.c

Problem reported by Yuri in PR #4861

prov/verbs: Add missing include for S_IWUSR

---

prov/sockets/src/sock_ep_msg.c
prov/tcp/src/tcpx.h
prov/tcp/src/tcpx_conn_mgr.c
prov/tcp/src/tcpx_domain.c
prov/tcp/src/tcpx_ep.c
prov/tcp/src/tcpx_progress.c
prov/tcp/src/tcpx_shared_ctx.c

The following original commits were modified to resolve conflicts
3cc855f prov/tcp: Remove duplicate rx_queue removal
f05a18b prov/tcp: Fix returning srx xfer_entry to cq buffer pool
9c0ff17 prov/tcp: set cm_entry->info->dest_addr when writing FI_CONNREQ event

[v1.7.x] /prov/tcp, /prov/sockets Cherry picked few fixes 

---

configure.ac

Cherry-picked fixes to support building with clang on CentOS 7.6.

[v1.7.x] clang fix

---

include/ofi_shm.h
include/ofi_util.h
man/fi_shm.7.md
prov/rxd/src/rxd.h
prov/rxd/src/rxd_atomic.c
prov/rxd/src/rxd_cq.c
prov/rxd/src/rxd_msg.c
prov/rxd/src/rxd_rma.c
prov/rxd/src/rxd_tagged.c
prov/rxm/src/rxm_atomic.c
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_rma.c
prov/shm/src/smr.h
prov/shm/src/smr_atomic.c
prov/shm/src/smr_comp.c
prov/shm/src/smr_ep.c
prov/shm/src/smr_msg.c
prov/shm/src/smr_progress.c
prov/shm/src/smr_rma.c
prov/util/src/util_ep.c

Add util_ep->tx/rx_msg_flags for proper FI_COMPLETION usage in msg API calls with SELECTIVE_COMPLETION
Update usage in rxm and rxd.
Applying these changes to shm is best done pulling in the SELECTIVE_COMPLETION support because it refactors the completion flags and calls that are needed for the msg flag changes. This refactoring helped fix some completion changes too.

[v1.7.x] prov/util, rxd, rxm, shm: add util_ep->msg_flags for proper msg API flags

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_ep.c

Also add some asserts to check for tx_cq/rx_cq in tx/rx calls.

prov/rxm: don't access tx_cq when app doesn't bind it with endpoint

---

include/ofi.h
prov/mrail/src/mrail_init.c
src/fabric.c

The environment variable FI_PROVIDER is a comma separated list of provider
names that are allowed to be used. Previously layered provider names were
not supported and a definition such as FI_PROVIDER="verbs;ofi_rxm" would
eliminate all providers because any core provider would fail to register
due to not matching the name "verbs;ofi_rxm".
This patch extends the FI_PROVIDER usage to allow layered provider names
while remain fully backward compatible with previous implementation in all
other aspects.

core: Support layered provider names in FI_PROVIDER

---

man/fi_rxm.7.md
man/fi_verbs.7.md
prov/rxm/src/rxm.h
prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_cq.c
prov/verbs/src/verbs_domain.c
prov/verbs/src/verbs_ep.c

The Infiniband spec doesn't say if the send queue space should be freed after
a WR is processed. Based on the implementation, we may need to track available
space in CQ to avoid overflowing it (which renders any QPs bound to it unusable).
Use an atomic counter to track available space and return -FI_EAGAIN on
ibv_post_send when we don't have credits.
@mmarcini, this PR updates libfabric verbs provider to avoid CQ overrun.

prov/verbs, rxm: avoid CQ overrun and empty receive queue

---

prov/mrail/src/mrail.h
prov/mrail/src/mrail_init.c

* Use unique fabric names to ensure that correct rail information can be found later in fi_fabric().
* Allow returning multiple mrail provider instances from fi_getinfo(). Keep the rail details internal.

prov/mrail: Re-work the getinfo implementation

---

prov/gni/include/gnix_mbox_allocator.h
prov/gni/src/gnix_fabric.c
prov/gni/src/gnix_mbox_allocator.c

There may be cases where huge pages are not available
on a node type where a libfabric application may
wish to use the GNI provider.
This commit provides a fallback to use base pages.
The fallback can be disabled via an environment variable:
export GNIX_MBOX_FALLBACK_DISABLE=1
Fixes #4911

prov/GNI: add fallback when no huge pages

---

prov/gni/src/gnix_fabric.c

we just put in 0 for mem_tag_format when first
writing the gni provider.  There was no need for
this and now Open MPI is unhappy.  Its happy though
with FI_TAG_GENERIC.
Signed-off-by: Howard Pritchard <hppritcha@gmail.com>

prov/gni: use the FI_TAG_GENERIC

---

prov/mrail/src/mrail_ep.c

prov/mrail: Bug fix - addrlen should be set in fi_getname()

---

prov/mrail/src/mrail_ep.c

The tx_buf allocated for a message send is freed when the lower level
completion is processed. This should not affect the final completion
generation because that is determined by the flags stored in tx_buf.
This fixes the following assertion failure with debugging build:
"../prov/util/src/util_buf.c:239: ofi_bufpool_destroy: Assertion
`(pool->attr.flags & OFI_BUFPOOL_NO_TRACK) || (buf_region->use_cnt == 0)'
failed."

prov/mrail: Always generate lower level send completions
