- prov/psm/src/psmx_atomic.c
- prov/psm/src/psmx_msg.c
- prov/psm/src/psmx_rma.c
- prov/psm/src/psmx_tagged.c
Account for new named union in fi_triggered_context.
> fix compile errors in psm provider

- Makefile.am
> man: install the fi_errno.3 man page

- man/fi_errno.3.md
> man: fix incorrect "fi_fabric(7)" SEE ALSO text

- prov/sockets/src/sock.h
- prov/sockets/src/sock_av.c
- prov/sockets/src/sock_comm.c
- prov/sockets/src/sock_conn.c
- prov/sockets/src/sock_cq.c
- prov/sockets/src/sock_dom.c
- prov/sockets/src/sock_ep.c
- prov/sockets/src/sock_ep_dgram.c
- prov/sockets/src/sock_ep_msg.c
- prov/sockets/src/sock_ep_rdm.c
- prov/sockets/src/sock_progress.c
- prov/sockets/src/sock_rx_entry.c
> sockets provider updates merged manually

- man/fi_fabric.3.md
- man/fi_version.3.md
> man: more incorrect "fi_fabric(7)" SEE ALSO text

- prov/sockets/src/sock_cntr.c
- prov/sockets/src/sock_cq.c
- prov/sockets/src/sock_ep_dgram.c
- prov/sockets/src/sock_util.c
- prov/sockets/src/sock_util.h
- src/fi_tostr.c
@shefty Can you quick sanity check this (trivial) patch?
> license: remove "OpenIB.org" from the BSD license description

- Makefile.am
- prov/usnic/configure.m4
- prov/usnic/src/usnic_direct/libnl_utils.h
- prov/usnic/src/usnic_direct/linux_types.h
- prov/usnic/src/usnic_direct/usd_poll.c
- prov/usnic/src/usnic_direct/usd_post_udp_normal.c
- prov/usnic/src/usnic_direct/usnic_direct.h
- prov/usnic/src/usnic_direct/vnic_cq.c
- prov/usnic/src/usnic_direct/vnic_cq.h
- prov/usnic/src/usnic_direct/vnic_dev.h
- prov/usnic/src/usnic_direct/vnic_devcmd.h
- prov/usnic/src/usnic_direct/vnic_rq.c
- prov/usnic/src/usnic_direct/vnic_rq.h
- prov/usnic/src/usnic_direct/vnic_wq.c
- prov/usnic/src/usnic_direct/vnic_wq.h
Update usnic / sync with internal Cisco repo.
> usnic update

- man/fi_endpoint.3.md
@shefty Per #506, how is this phrasing about the buffer behavior?
> fi_endpoint: clarify FI_MULTI_RECV buffer handling

- prov/usnic/src/usdf_ep_dgram.c
including fixing a segfault and a socket leak
> miscellaneous usnic fixes

- man/fi_getinfo.3.md
> man: fix fi_freeinfo retval

- prov/verbs/src/fi_verbs.c
> verbs: avoid SEGV on null fabric name

- Makefile.am
- include/fi_enosys.h
- include/rdma/fi_endpoint.h
- man/fi_msg.3.md
- man/fi_rx_size_left.3
- man/fi_tx_size_left.3
- prov/psm/src/psmx_msg.c
- prov/psm/src/psmx_msg2.c
- prov/sockets/src/sock_msg.c
- prov/usnic/src/usdf_dgram.c
- prov/usnic/src/usdf_dgram.h
- prov/usnic/src/usdf_ep_dgram.c
- prov/verbs/src/fi_verbs.c
- src/enosys.c
Per Reese's proposal here: http://lists.openfabrics.org/pipermail/ofiwg/2014-December/000477.html
This PR also adds support in the usnic provider.
A corresponding fabtests PR is imminent.
fixes #480 
@rfaucett please review
> add fi_rx_size_left/fi_tx_size_left functions

- prov/verbs/src/fi_verbs.c
This PR is just a collection of a few trivial bug fixes that I made while working on the port of UNH EXS to libfabric.
> Trivial verbs provider bug fixes

- man/fi_endpoint.3.md
Add an entry for fi_pep_bind to accompany fi_ep_bind and fi_scalable_ep_bind.
Closes #548 .
> man: add fi_pep_bind to fi_endpoint(3)

- include/rdma/fabric.h
- man/fi_atomic.3.md
- man/fi_endpoint.3.md
- man/fi_getinfo.3.md
- man/fi_msg.3.md
- man/fi_rma.3.md
- man/fi_tagged.3.md
- prov/sockets/src/sock.h
- prov/sockets/src/sock_conn.c
- prov/sockets/src/sock_dom.c
- prov/sockets/src/sock_ep.c
- prov/sockets/src/sock_ep_msg.c
- prov/sockets/src/sock_eq.c
Addresses #476, #474, and #333.
> Add one new op flag, one mode bit, and one new attribute.  Fix to socket provider

- prov/sockets/src/sock_ctx.c
- prov/sockets/src/sock_progress.c
Add missing release of lock and check for empty free_list.
> prov/sock: minor updates based on GASNet testings.

- include/rdma/fabric.h
- include/rdma/fi_tagged.h
- man/fi_av.3.md
- man/fi_cq.3.md
- man/fi_domain.3.md
- man/fi_endpoint.3.md
- man/fi_eq.3.md
- man/fi_getinfo.3.md
- man/fi_tagged.3.md
Plus define 1 new flag and 2 alias flags.
> Mostly a bunch of man page updates

- src/fabric.c
If we load multiple providers of the same name, we'll end up cleaning up and ignoring the older one.  Add some logic to actually dlclose() the older provider if it was actually dlopen()ed.  Also dlclose() a DL if something else goes wrong while registering it.
@goodell please review
> fabric.c: Fix memory leak: dlclose() DLs that fail to load or are replaced

- src/fabric.c
I missed @goodell's suggestion for cleanup_provider on #573.  Also, we all missed that there should be dlclose()s in fi_fini().
This patch adds cleanup_provider(), per Dave's suggestion, and also adds a call to it during fi_fini().
> fabric.c: combine cleanup_provider functionality

- configure.ac
- libfabric.spec.in
Update version to work with rpmbuild.
Add buildrequires for src.rpm
Build all in-tree providers for release.
Signed-off-by: pmmccorm <patrick.m.mccormick@intel.com>
> 1.0 release prep for spec file.

- include/fi_list.h
I will create a separate PR for the usage case of the new function in the PSM provider.
> include: implement "remove-first-match" function for linked list

- AUTHORS
Signed-off-by: pmmccorm <patrick.m.mccormick@intel.com>
> Update AUTHORS file.

- include/fi_log.h
- src/log.c
Added function name, line number info to logger output
> Logger updates

- man/fi_msg.3.md
found during discussion prep for #598
> man: fixes for fi_msg(3)

- prov/usnic/src/usdf.h
- prov/usnic/src/usdf_domain.c
- prov/usnic/src/usdf_fabric.c
> usnic: small fixes

- prov/verbs/src/fi_verbs.c
I am sending this PR since UNH EXS requires this functionality.
There are two issues with this PR that may require some changes (maybe @shefty has some input on these):
1. The librdmacm calls do not allow the caller to discover the length of the address buffer that it returns, so this code guesses based on `sa_family`.
2. I'm not sure what to do in the case that the address is not available (e.g., since the endpoint isn't connected yet).  FWIW, I don't think librdmacm does anything in this case either, so this code basically just passes whatever librdmacm does up to the user.
> [RFC] fi_verbs: Implement fi_getname() and fi_getpeer()

- prov/sockets/src/sock_msg.c
- prov/sockets/src/sock_progress.c
- prov/sockets/src/sock_rma.c
- Add check for FI_DIRECTED_RECV
- Add check for connection lookup in RMA ops
- Bug fix to avoid resetting tx_pe_entry
> Sockets Provider - Minor updates

- prov/sockets/src/sock_msg.c
> Fix an issue in length calculation with fi-tsend inject

- src/fabric.c
> fabric: Free fi_prov instances when no longer needed

- config/cron-make-nightly-tarball.pl
- config/cron-submit-coverity.pl
Improve the logging in the nightly tarball script and add a new script to build/submit to Coverity.
> Build server scripts for Coverity

- README.md
- config/cron-submit-coverity.pl
* Add Coverity status badge to README.md
* Update Coverity project name (from `libfabric` to `ofiwg/libfabric`)
> Minor Coverity updates

- master/man/index.md
Otherwise it is missing from
http://ofiwg.github.io/libfabric/master/man/
Refs #625,#633.
> add fi_control(3) to man page index

- prov/sockets/src/sock_ep_msg.c
See issue #632:
In sock_msg_ep_listener_thread and sock_pep_listener_thread,
the user private data is copied onto the event structure on the
stack. However, the event structure does not include space for
the private data, so copying the private data corrupts the stack.
Handle this by allocating a large enough buffer to avoid
overrunning the stack.  Also fix a memory leak.
> prov/sockets: Fix stack corruption in listen thread

- configure.ac
> configure.ac: 1.0rc2 has been released; on to 1.0rc3

- config/cron-make-nightly-tarball.pl
> nightly tarball: also log the git commands

- prov/usnic/src/usdf_av.c
- prov/usnic/src/usdf_cm.c
- prov/usnic/src/usdf_ep_msg.c
- prov/usnic/src/usdf_ep_rdm.c
- prov/usnic/src/usdf_eq.c
- prov/usnic/src/usdf_fabric.c
- prov/usnic/src/usdf_msg.c
- prov/usnic/src/usdf_pep.c
- prov/usnic/src/usdf_rdm.c
- prov/usnic/src/usnic_direct/usd_ib_sysfs.c
- prov/usnic/src/usnic_direct/usd_socket.c
- prov/usnic/src/usnic_direct/usnic_ip_utils.c
Gathered from the Open MPI Coverity runs.
@goodell please review
> usnic Coverity fixes

- prov/sockets/src/sock_atomic.c
- prov/sockets/src/sock_av.c
- prov/sockets/src/sock_cntr.c
- prov/sockets/src/sock_comm.c
- prov/sockets/src/sock_conn.c
- prov/sockets/src/sock_cq.c
- prov/sockets/src/sock_dom.c
- prov/sockets/src/sock_ep.c
- prov/sockets/src/sock_ep_dgram.c
- prov/sockets/src/sock_ep_msg.c
- prov/sockets/src/sock_ep_rdm.c
- prov/sockets/src/sock_eq.c
- prov/sockets/src/sock_msg.c
- prov/sockets/src/sock_progress.c
- prov/sockets/src/sock_rma.c
- prov/sockets/src/sock_wait.c
> Coverity fixes 

- prov/sockets/src/sock.h
- prov/sockets/src/sock_ep_msg.c
- Fixes #634 
- Add fi-getname for passive endpoints
> Bug fixes: sockets provider

- prov/usnic/src/usdf_av.c
- prov/usnic/src/usdf_fabric.c
2 fixes.
Talked to @rfaucett to come to the final conclusion on the usdf_fabric.c fixes.
@goodell can you review?
> More usnic coverity fixes

- prov/usnic/src/usdf_av.c
Two commits:
1. Fix Coverity 31693 (@goodell and I discussed this on the phone already)
1. An attempt to make the loop a little more readable.  I'm not 100% sure I succeeded -- @goodell -- thoughts?
> usnic: fix coverity 31693

- prov/verbs/src/fi_verbs.c
> prov/verbs: Replace hard-code value with #define

- prov/sockets/src/sock_cntr.c
- prov/sockets/src/sock_cq.c
- prov/sockets/src/sock_ep_msg.c
> Fix sockets provider build warnings

- prov/psm/src/psmx_av.c
- prov/psm/src/psmx_cntr.c
- prov/psm/src/psmx_cq.c
- prov/psm/src/psmx_domain.c
- prov/psm/src/psmx_ep.c
- prov/psm/src/psmx_init.c
- prov/psm/src/psmx_util.c
- prov/psm/src/psmx_wait.c
remove duplicated output of function name; add debug output for errors in fi_av_insert.
> prov/psm: debug output improvements

- prov/sockets/src/sock_ep_msg.c
- prov/sockets/src/sock_progress.c
> - Minor coverity fixes

- index.md
> OFI/pages: Define OS support as part of overview

- include/rdma/fabric.h
- src/fi_tostr.c
This is just an enhancement to allow applications to easily log which
events they receive.
Signed-off-by: Patrick MacArthur <pmacarth@iol.unh.edu>
> fi_tostr: Add FI_TYPE_EQ_EVENT, FI_TYPE_CQ_EVENT_FLAGS

- prov/sockets/src/sock_eq.c
- Fixed fi_cq_write to return number of bytes returned
- Fixed fi_eq_read to return 0 when eq is empty
Fixes #708. Will push a fix for Fabtests as well. @jithinjosepkl, @luomiao can you please take a look?
> prov/sockets: Fixed EQ issues

- prov/verbs/src/fi_verbs.c
Removes unwanted fi_info processing when creating endpoints
> prov/verbs: Refactor getinfo and endpoint creation code + cleanup

- include/rdma/fi_domain.h
- man/fi_av.3.md
Signed-off-by: Ben Turrubiates <bturrubiates@lanl.gov>
> Add implementation for fi_av_straddr.

- prov/usnic/src/usdf_fabric.c
- prov/usnic/src/usnic_direct/usd_device.c
@xuywang or @goodell or @rfaucett please review
> Fix usd_open resource leak

- man/fi_eq.3.md
Signed-off-by: Ben Turrubiates <bturrubiates@lanl.gov>
> Update fi_eq man page to mirror the structures in fi_eq.h.

- prov/psm/configure.m4
- prov/sockets/configure.m4
- prov/usnic/configure.m4
- prov/verbs/configure.m4
> configury: fix trivial typos in comments

- Makefile.am
- man/man3/fi_open_ops.3
May need to change the contents of this file depending on the outcome of #760.
> fi_open_ops.3: add missing fi_open_ops.3 page

- prov/psm/src/psmx_init.c
- prov/sockets/src/sock_fabric.c
- prov/verbs/src/fi_verbs.c
@goodell Please review -- fairly trivial
> usnic: add missing fi_log_init()

- prov/sockets/src/sock_comm.c
- prov/sockets/src/sock_conn.c
- prov/sockets/src/sock_fabric.c
- OSX warning fixes (fixes #772)
- Coverity scan fixes
> - OSX warning fixes (fixes #772)

- prov/sockets/src/sock_cq.c
- prov/sockets/src/sock_eq.c
Updated return value based on latest agreement.
> Update return value of EQ/CQ read/sread

- prov/sockets/src/sock_comm.c
- prov/sockets/src/sock_ep_msg.c
> Set cm_addr to EP CM addr after ACCEPT.

- prov/verbs/src/fi_verbs.c
Fixes for issue #738 Return value when reading from empty event/error queue.
> prov/verbs: Return -FI_EAGAIN for EQ and CQ reads when the queue is empty

- src/fabric.c
Having a default location for DLs is fine (i.e., `$pkglibdir`), but it's not enough.  Specifically, if a provider maintainer wants to provide an asynchronous update to their built-in/inbox provider, it's easy enough to create a DL of the provider and install it in `$pkglibdir`.
But what about the provider's extension header file?
That extension header file is currently installed into `$includedir/fi_ext_<provider>.h`.  It would be extremely anti-social for an async provider update to overwrite that file (and potentially make package managers -- such as rpm -- unhappy).  Indeed, the point of allowing DLs to "override" built-in providers is to provide async provider updates *without* replacing any of the libfabric packaged files (including the inbox-provided `fi_ext_<provider>.h`).
The …
> fabric: $FI_PROVIDER_PATH env var specifies where DLs live

- prov/sockets/src/sock_atomic.c
- prov/sockets/src/sock_av.c
- prov/sockets/src/sock_comm.c
- prov/sockets/src/sock_conn.c
- prov/sockets/src/sock_cq.c
- prov/sockets/src/sock_ctx.c
- prov/sockets/src/sock_dom.c
- prov/sockets/src/sock_ep.c
- prov/sockets/src/sock_ep_dgram.c
- prov/sockets/src/sock_ep_msg.c
- prov/sockets/src/sock_ep_rdm.c
- prov/sockets/src/sock_eq.c
- prov/sockets/src/sock_fabric.c
- prov/sockets/src/sock_msg.c
- prov/sockets/src/sock_poll.c
- prov/sockets/src/sock_progress.c
- prov/sockets/src/sock_rma.c
- prov/sockets/src/sock_rx_entry.c
- prov/sockets/src/sock_util.h
- prov/sockets/src/sock_wait.c
> Updated sockets-provider to use new logging framework

- prov/verbs/src/fi_verbs.c
> prov/ibverbs: Re-enabled logging output

- prov/psm/src/psmx.h
- prov/psm/src/psmx_av.c
- prov/psm/src/psmx_cntr.c
- prov/psm/src/psmx_cq.c
- prov/psm/src/psmx_domain.c
- prov/psm/src/psmx_ep.c
- prov/psm/src/psmx_init.c
- prov/psm/src/psmx_msg2.c
- prov/psm/src/psmx_tagged.c
- prov/psm/src/psmx_util.c
- prov/psm/src/psmx_wait.c
> prov/psm: Re-enable logging in psm provider

- configure.ac
- include/fi.h
- prov/sockets/src/sock_poll.c
@pmmccorm  @jsquyres 
Please review. 
Signed-off-by: Ben Turrubiates <bturrubiates@lanl.gov>
> Add configury to enable spinlock.

- prov/psm/src/psmx_am.c
The RMA queue is locked when processing the delayed RMA requests
(those over tagged message). However, while a specforific request is
being processed, the AM handler could be invoked asynchronously
and try to enqueue more RMA requests, causing deadlock.
Similar fix is also applied to the send queue lock for AM based
message.
> prov/psm: fix a deadlock in RMA progress

- prov/sockets/src/sock.h
- prov/sockets/src/sock_ep.c
- prov/sockets/src/sock_ep_msg.c
> Init CM locks, cleanups

- man/fi_usnic.7.md
> fi_usnic.7.md: update usnic provider page per fi_provider.7

- man/fi_psm.7.md
> man: finish the man page about the PSM provider

- Makefile.am
- include/fi.h
- prov/sockets/src/sock_av.c
- prov/sockets/src/sock_cntr.c
- prov/sockets/src/sock_comm.c
- prov/sockets/src/sock_cq.c
- prov/sockets/src/sock_ctx.c
- prov/sockets/src/sock_dom.c
- prov/sockets/src/sock_ep_dgram.c
- prov/sockets/src/sock_ep_msg.c
- prov/sockets/src/sock_ep_rdm.c
- prov/sockets/src/sock_eq.c
- prov/sockets/src/sock_poll.c
- prov/sockets/src/sock_progress.c
- prov/usnic/src/usdf_cq.c
- prov/usnic/src/usdf_ep_rdm.c
- prov/usnic/src/usdf_pep.c
Updates Jeff's changes to resolve conflicts in the sockets provider.
> Fix build warnings, see PR #838

- prov/verbs/src/fi_verbs.c
Verbs drivers use the ENOMEM error code to indicate that the send or
receive queue overflowed.  However, the drivers do not consistently use
the same mechanism to return this value to the caller.  Most drivers do
as the man page says (return the errno value directly), but some drivers
instead return -1 and set errno.  This commit catches both of these
cases and returns -FI_EAGAIN as libfabric applications expect.
Signed-off-by: Patrick MacArthur <pmacarth@iol.unh.edu>
See PR #824 - updated to resolve conflicts
> prov/verbs: Return -FI_EAGAIN on queue pair overflow

- man/fi_psm.7.md
> man: format fix for the PSM provider man page.

- prov/psm/src/psmx_cq.c
> prov/psm: implement fi_cq_signal

- man/fi_psm.7.md
> man: update the PSM provider man page

- prov/psm/src/psmx_cq.c
> prov/psm: bug fix for reading multiple CQ completions

- man/fi_mr.3.md
> man: Clarify RMA write completions at target

- prov/sockets/src/sock_ep_msg.c
> Delay FI_CONNECTED event until ACK is received for CM accept message

- README
> README: Expand readme with more details

- prov/psm/src/psmx_rma.c
The RMA write long protocol sends an AM request followed by a
tagged message. Somehow the tagged send would hang if the number
of arguments passed to the AM request is greater than 5 and the
destination endpoint is on the same node (i.e. the message goes
through the shared memory channel). This is the case when the
write has an immediate data. The fix changes the protocol to
send the immediate data as payload instead of an argument.
> prov/psm: fix a hanging in the RMA write long protocol

- prov/verbs/src/fi_verbs.c
* Request for event notification right after creating the CQ so that when
users wait on the CQ FD, they get events.
* Fix sread race condition: Reap for unread completions after requesting for
event notification. Then poll if there are no completions.
> prov/verbs: CQ and CQ sread fixes

- man/fi_sockets.7.md
@jithinjosepkl can you please review?
> prov/sockets Added content to sockets provider release note

- include/fi.h
- prov/verbs/src/fi_verbs.c
- src/common.c
> prov/verbs: Implement fi_cq_signal

- prov/verbs/src/fi_verbs.c
* FI_RX_CQ_DATA should be checked only when user has requested FI_RMA.
* Fix size mismatch issue found by coverity scan.
* Remove unused function.
> prov/verbs: fix FI_RX_CQ_DATA mode bit check.

- Makefile.am
- prov/psm/src/psmx.h
- prov/psm/src/psmx_eq.c
- prov/psm/src/psmx_init.c
> prov/psm: implement event queue

- Makefile.am
- include/rdma/fi_eq.h
- include/rdma/fi_tagged.h
- man/fi_av.3.md
- man/fi_endpoint.3.md
- man/fi_eq.3.md
- man/fi_tagged.3.md
- man/man3/fi_tsearch.3
- prov/psm/src/psmx_tagged.c
- prov/sockets/src/sock_msg.c
@jithinjosepkl @j-xiong - I need help updating the PSM and sockets provider to generate asynchronous events for what was tsearch.
> Replace tsearch with FI_PEEK + man page updates

- prov/sockets/src/sock.h
- prov/sockets/src/sock_msg.c
- prov/sockets/src/sock_progress.c
- prov/sockets/src/sock_rx_entry.c
- Update sockets-provider to support FI_PEEK/FI_CLAIM/FI_DISCARD.
- Minor cleanups
> - Update sockets-provider to support FI_PEEK/FI_CLAIM/FI_DISCARD.

- prov/psm/src/psmx_tagged.c
Tagged recv with FI_PEEK flag replace the tsearch function, which
used to allow the result be returned immediately. The new function
always works asynchronously and the result is returned via the
completion event.
Follow-up of #892
> prov/psm: make peek recv work asynchronously

- prov/psm/src/psmx_ep.c
> prov/psm: add rx_size_left and tx_size_left

- prov/usnic/src/usdf_msg.c
While fragmenting the message into datagrams, the payload length was
incorrect [larger than the payload, which was resulting in copying
garbage values in the buffer]
And while reassembling the packets, the later datagrams were
overwriting the earlier ones.
Signed-off-by: Prankur Gupta <prankgup@cisco.com>
@goodell
> usnic: fix fragmentation and reassembly bug

- man/fi_tagged.3.md
> man: fix fi_tagged formatting

- man/fi_psm.7.md
- prov/psm/src/psmx.h
- prov/psm/src/psmx_am.c
- prov/psm/src/psmx_domain.c
- prov/psm/src/psmx_init.c
> Revert "prov/psm: add environment variable OFI_PSM_AM"

- prov/psm/src/psmx.h
- prov/psm/src/psmx_am.c
- prov/psm/src/psmx_domain.c
- prov/psm/src/psmx_eq.c
* check ep caps against domain caps
* fix a few wrong log types
* add a long message for AM initialization function
> prov/psm: a few minor updates

- man/fi_verbs.7.md
> man: Update fi_verbs man page

- prov/psm/src/psmx_init.c
> prov/psm: fill out the missing fields of domain_attr

- configure.ac
- libfabric.spec.in
> Update version to next rc to avoid issues with current rc release

- include/rdma/fabric.h
- Fix FI_REMOTE_CQ_DATA flag value (avoid conflict with another flag)
> Fix FI_REMOTE_CQ_DATA flag value

- prov/usnic/src/usdf_cm.c
- prov/usnic/src/usdf_cq.c
- prov/usnic/src/usdf_ep_msg.c
A couple of long-overdue fixes for usnic that should have been done shortly after #676 landed.
> usnic: followup to PR #676

- prov/sockets/src/sock_util.h
> Fix build error from PR #907

- prov/usnic/src/usdf_fabric.c
This is my interpretation of @shefty's recommendation in issue #771.
> usnic: fix getinfo logic for domain_attr attributes

- man/fi_msg.3.md
> man: fix typo in fi_msg(3)

- include/fi_list.h
- include/fi_rbuf.h
> Coverity scan fixes for rbuf, list

- prov/psm/src/psmx_init.c
> prov/psm: check addr_format hint in fi_getinfo

- prov/verbs/src/fi_verbs.c
The usnic device plugs into the verbs framework, but doesn't really
support verbs.  As a result, the libibverbs and librdmacm libraries
will fail to use it properly.  In particular, the librdmacm will
detect the error and send an error message to stderr.  In order to
avoid the error message, have the verbs provider search for valid
libibverbs devices.  If any are found, initialization proceeds as
normal.  If not, the verbs initialization will return ENODATA and
abort.
> prov/verbs: Search for verbs device on init

- prov/sockets/src/sock_ep_msg.c
> sockets: fi_getname()/fi_getpeer() set addrlen

- prov/verbs/src/fi_verbs.c
> prov/verbs: Move verbs_info cleanup to fini.

- prov/verbs/src/fi_verbs.c
> prov/verbs: Fix coverity issues.

- prov/usnic/src/usnic_direct/usd_mem.c
If fork support is required, memory registered for usd internal use should be
denied access to child processes during fork. This patch added calls to madvise
in usd_alloc_mr to achieve this purpose.
Signed-off-by: Xuyang Wang <xuywang@cisco.com>
> Disabled copy-on-write for memory used for usd internal buffers

- Makefile.am
- man/fi_sockets.7.md
- man/fi_trigger.3.md
- prov/sockets/src/sock.h
- prov/sockets/src/sock_atomic.c
- prov/sockets/src/sock_cntr.c
- prov/sockets/src/sock_msg.c
- prov/sockets/src/sock_rma.c
> Revert "Pr/sockets"

- index.md
> gh-pages: Update website to define and use OFI correctly

- prov/sockets/src/sock_dom.c
- Close locks after progress engine finalize
> pr/sockets: bug fix

- Makefile.am
- man/man3/fi_setname.3
- prov/usnic/src/usdf.h
- prov/usnic/src/usdf_av.c
- prov/usnic/src/usdf_cm.c
- prov/usnic/src/usdf_cm.h
- prov/usnic/src/usdf_endpoint.c
- prov/usnic/src/usdf_endpoint.h
- prov/usnic/src/usdf_ep_dgram.c
- prov/usnic/src/usdf_ep_msg.c
- prov/usnic/src/usdf_eq.c
- prov/usnic/src/usdf_fabric.c
- prov/usnic/src/usdf_pep.c
This was more work than expected, but now seems to be passing @patrickmacarthur's tests on his [`setname-test` fabtests branch](https://github.com/patrickmacarthur/fabtests/tree/setname-test).
> usnic: implement fi_setname

- man/fi_control.3.md
> man: fix fi_control(3) typo

- prov/verbs/src/fi_verbs.c
> prov/verbs: fix missing free for ibv devs + misc updates

- prov/usnic/src/usdf_av.c
- prov/usnic/src/usdf_cm.c
- prov/usnic/src/usdf_dgram.c
- prov/usnic/src/usdf_domain.c
- prov/usnic/src/usdf_ep_msg.c
- prov/usnic/src/usdf_ep_rdm.c
- prov/usnic/src/usdf_msg.c
- prov/usnic/src/usdf_pep.c
- prov/usnic/src/usdf_rdm.c
> usnic: fix -Wsign-compare warnings

- src/fi_tostr.c
Add some notes about naming and format as well. I don't know what to do with
fi_domain_attr.domain , so I just print its value.
Signed-off-by: pmmccorm <patrick.m.mccormick@intel.com>
> Add some missing fields to fi_tostr function.

- CONTRIBUTORS
Per 2015-06-02's conference call discussion.
> CONTRIBUTORS: clarify Signed-off-by tag

- prov/sockets/src/sock_conn.c
- prov/sockets/src/sock_ep.c
- Support fi-cancel for tx operations
- Assign valid IP address (hostname) when endpoint is enabled, instead
of using any-src-address (this case occurs only if app does not pass
any addressing info)
> sockets: minor bug fixes

- prov/verbs/src/fi_verbs.c
Return all matching fi_info structures (corresponding to different devices) when fi_getinfo is called. Move verbs_info initialization to VERBS_INI so that we need not check if it is initialized in other places.
> prov/verbs: fi_getinfo fixes

- src/fabric.c
> Revert "Wrong array boundaries check"

- src/fabric.c
Signed-off-by: Paolo Inaudi <p91paul@gmail.com>
> Wrong array boundaries check

- prov/psm/src/psmx_init.c
Fixed some typos that caused build errors.
@j-xiong @jsquyres can you please review?
> prov/psm: Fixed build errors and warnings

- config/github-webhook/README
- config/github-webhook/apache-config.txt
- config/github-webhook/github-webhook-ofiwg-init.d
- config/github-webhook/verify-signed-off.rb
Ruby Sinatra server to run on flatbed.openfabrics.org that will check to ensure that all commits on a Github pull request contain a Signed-off-by line in their commit messages.
@patrickmacarthur Please review
> server: github webhook checking for Signed-off-by lines

- src/var.c
> CID 98882: ensure to check the return of asprintf

- prov/verbs/src/fi_verbs.c
> prov/verbs: Pass imm_data in network byte order.

- prov/psm/src/psmx_init.c
(1) move the registration to the INI function
(2) remove the value readout log message since it's already done
in the fi_var_get function
> prov/psm: more tweaks to the environment variables

- index.md
> gh-pages: Provide link to official download location

- prov/sockets/src/sock_atomic.c
- prov/sockets/src/sock_av.c
- prov/sockets/src/sock_cntr.c
- prov/sockets/src/sock_comm.c
- prov/sockets/src/sock_conn.c
- prov/sockets/src/sock_cq.c
- prov/sockets/src/sock_ctx.c
- prov/sockets/src/sock_dom.c
- prov/sockets/src/sock_ep.c
- prov/sockets/src/sock_ep_dgram.c
- prov/sockets/src/sock_ep_msg.c
- prov/sockets/src/sock_ep_rdm.c
- prov/sockets/src/sock_eq.c
- prov/sockets/src/sock_fabric.c
- prov/sockets/src/sock_msg.c
- prov/sockets/src/sock_poll.c
- prov/sockets/src/sock_progress.c
- prov/sockets/src/sock_rma.c
- prov/sockets/src/sock_rx_entry.c
- prov/sockets/src/sock_trigger.c
- prov/sockets/src/sock_util.h
- prov/sockets/src/sock_wait.c
- Enable option to set affinity for progress thread 
- thanks Robichaux, Joseph <joseph.robichaux@intel.com> for the patch.
- Change SOCK_LOG_INFO as debug logs
- Add check for progress mode in sock_pe_signal
@shantonu
> sockets: minor updates

- include/fi.h
The gnix provider uses atomic_add and atomic_sub in a few places. This code should belong as part of the common code. 
> Add atomic_add and atomic_sub to the list of supported basic atomics

- src/var.c
> var.c: ensure ret is initialized

- src/var.c
> fabric/var: Minor code cleanups

- include/fi_list.h
- src/var.c
@shefty @hppritcha 
closes #1119 
> Initialize param_list to avoid crashing in library destructor

- prov/usnic/src/usnic_direct/usd.h
- prov/usnic/src/usnic_direct/usd_ib_cmd.c
- prov/usnic/src/usnic_direct/usd_ib_cmd.h
- prov/usnic/src/usnic_direct/usd_ib_sysfs.c
- prov/usnic/src/usnic_direct/usd_queues.c
- prov/usnic/src/usnic_direct/usnic_abi.h
- prov/usnic/src/usnic_direct/usnic_direct.h
- prov/usnic/src/usnic_direct/usnic_ib_abi.h
- prov/usnic/src/usnic_direct/vnic_dev.c
- prov/usnic/src/usnic_direct/vnic_rq.c
- prov/usnic/src/usnic_direct/vnic_rq.h
- prov/usnic/src/usnic_direct/vnic_wq.c
- prov/usnic/src/usnic_direct/vnic_wq.h
Signed-off-by: Xuyang Wang <xuywang@cisco.com>
> update usnic_direct to SVN 231979

- prov/verbs/src/fi_verbs.c
This patch fixes an issue where the server would reject a connection request from
client if ibacm is running on the client.
Root cause: When ibacm service is running, rdma_getaddrinfo returns an "ib rai"
that contains addresses in sockaddr_ib format. The address info present in 
rai->connect corresponds to whatever address format that was presented originally
to rdma_getaddrinfo( IPv4 for example). In verbs provider, rdma_getaddrinfo 
gets called twice. Once during fi_getinfo and another during endpoint creation.
The app passes the fi_info got from fi_getinfo to fi_endpoint. This fi_info has 
the addresses in sockaddr_ib format. So when rdma_getaddrinfo gets called again,
the returned rai->connect has address info in IPv6 (corresponding to sockaddr_ib).
When kernel rdma_cm sends a connect …
> prov/verbs: Ignore address info got from ibacm

- man/fi_getinfo.3.md
- man/fi_usnic.7.md
- prov/usnic/src/usdf_dgram.c
- prov/usnic/src/usdf_fabric.c
Update of #1122 and #1123.
@shefty @jsquyres
> RFC: Fix inconsistency between send and receive paths.

- prov/verbs/src/fi_verbs.c
> prov/verbs: fix coverity issue and memory leaks

- man/fi_cq.3.md
- man/fi_getinfo.3.md
- man/fi_msg.3.md
Formally define the meaning of the CQ entry fields, including
when the fields are valid.
> fabric: Define CQ entry fields

- .gitignore
> .gitignore: add util/fi_info

- prov/usnic/src/usdf_cq.c
The completion lengths are determined by the amount sent/received. There
are two cases to handle when setting the completion length:
- Prefix Mode
The app gives send/recv a length value that includes usnics advertised
header size. For performance reasons the reported header size is
slightly larger than it actually is. Internally the usnic provider
sends starting at the header offset. This means that the returned
completion length omits the length of the padding. This addresses the
issue by adding the length of the padding to all completions generated
on endpoints in prefix mode.
- Non-Prefix Mode
The app gives send/recv a length value that reflects the size of the
payload. The app is not aware of headers. Internally the usnic
provider allocates a header to perform the send/recv and it …
> usnic: Return the correct completion length.

- prov/psm/src/psmx_ep.c
Only receives can be cancelled. Failed cancellation would just
return error.
> prov/psm: generate cq entries for cancelled operations

- prov/psm/src/psmx_init.c
> prov/psm: fix provider parameter type

- prov/usnic/src/usdf.h
- prov/usnic/src/usdf_cq.c
- prov/usnic/src/usdf_dgram.c
- prov/usnic/src/usdf_ep_dgram.c
- prov/usnic/src/usdf_fabric.c
@goodell @jsquyres @prankurgupta 
Please review.
> usnic: add support for handling flags to dgram send calls.

- prov/sockets/src/sock_cq.c
sockets: reset ret after polling CQ ringbuffer
> sockets: Make CQ read thread-safe

- man/fabric.7.md
> man: fix fabric(7) env var name typo

- man/fi_msg.3.md
> fi_msg.3.md: Fix fi_completion description.

- prov/usnic/src/usdf_ep_dgram.c
> usnic: usdf_ep_dgram_open: On failure free ep.

- prov/usnic/src/usdf_dgram.c
usnic: make dgram recvmsg implementation be native instead of trickling  down to usd_post_recv(), use FI_MORE flag to defer writing posted_index to RQ control register
Signed-off-by: Reese Faucette <rfaucett@cisco.com>
> make fi_recvmsg respect FI_MORE for usnic

- prov/sockets/src/sock_progress.c
- Ensure progress of ctrl context
> sockets: bug fix

- prov/sockets/src/sock_av.c
Added code to release _av->name, _av->key and _av->table_hdr in the error path. Fixes #1208 
> Added code to release av resources in the error path

- prov/verbs/src/fi_verbs.c
- Add support for fi_eq_write.
- Replace poll with epoll so that a single fd can be passed
if the user requests the wait object.
- Bug fix: Add missing rdma event channel for FI_WAIT_NONE
> prov/verbs: Add support for fi_eq_write

- configure.ac
> configure.ac: v1.1.0 has been released; bump to v1.2.0

- prov/sockets/src/sock_fabric.c
If connect fails, set the src address based on the hostname
> Add fallback mechanism for getting src address

- prov/usnic/src/usdf_rdm.c
This resolves a segmenting issue in the usNIC implementation of EP_RDM
where the buffer position isn't updated and newer segments overwrite
memory from earlier segments.
@jsquyres @goodell @rfaucett 
> usnic: Fix reassembly bug in EP_RDM.

- prov/psm/src/psmx_am.c
This reverts commit 969591cd58b36bd639cfe60820cbd8a0ef2c9320.
As discussed in issue #1206.
> Revert "prov/psm: eliminate some unnecessary mutex lock/unlock calls"

- man/fi_msg.3.md
- man/fi_rma.3.md
- man/fi_tagged.3.md
> manpages: Add info about injectdata functions

- prov/usnic/src/usdf_msg.c
- prov/usnic/src/usdf_rdm.c
Decrement number of free entries when removing from the free work queue
and increment when processing an ACK. This fixes #1232.
@goodell @rfaucett 
> usnic: usdf_msg.c: Track number of free entries in tx work queue.

- prov/psm/src/psmx_atomic.c
> prov/psm: more fix for coverity issue #29854 -- unused value

- configure.ac
> configure.a: bump version to 1.1.1

- prov/psm/src/psmx_av.c
When psm_ep_connect is called with duplicated addresses, all but
one will fail with error "Endpoint not reachable". Handle such
case so that it behaves the same as "Already connected" instead.
> prov/psm: handle duplicated addresses in fi_av_insert

- CONTRIBUTORS
@shefty, please review at your leisure
> CONTRIBUTORS: link to OFA bylaws

- prov/sockets/src/sock.h
- prov/sockets/src/sock_conn.c
- prov/sockets/src/sock_ep.c
- prov/sockets/src/sock_ep_msg.c
- prov/sockets/src/sock_fabric.c
-Removed common code to get src_addr and created a function sock_get_src_addr_from_hostname()
@jithinjosepkl, can you please review?
> prov/sockets: Removed common code and added a function to get src_add

- config/cron-run-all-md2nroff.pl
For the v1.1.x branch, we want to update the man pages, but we do *not* want to push to the gh-pages branch.
So make it possible to not specify the --pages-branch CLI option, and skip that step if it is not specified.
(cherry picked from commit 7bde7f17bb06c166a83d7ec0bd6a6a6e6ed58d53)
Reviewed by @patrickmacarthur on master
> cron-run-all-md2nroff.pl: update without pushing to gh-pages

- man/fi_rma.3.md
> man pages: fix to fi_rma_msg def in man page

- configure.ac
- man/fi_sockets.7.md
- prov/sockets/src/sock.h
- prov/sockets/src/sock_atomic.c
- prov/sockets/src/sock_av.c
- prov/sockets/src/sock_conn.c
- prov/sockets/src/sock_cq.c
- prov/sockets/src/sock_dom.c
- prov/sockets/src/sock_ep.c
- prov/sockets/src/sock_ep_msg.c
- prov/sockets/src/sock_fabric.c
- prov/sockets/src/sock_progress.c
- prov/sockets/src/sock_rma.c
- prov/sockets/src/sock_util.h
Cherry-picking sockets-provider commits for 1.1.1 release.
> prov/sockets - Commits for v1.1.1

- man/fi_verbs.7.md
> prov/verbs: Update man pages

- Makefile.am
- configure.ac
- include/prov.h
- man/fi_mxm.7.md
- man/man7/fi_mxm.7
- prov/mxm/AUTHORS
- prov/mxm/configure.m4
- prov/mxm/src/mlxm.h
- prov/mxm/src/mlxm_av.c
- prov/mxm/src/mlxm_cm.c
- prov/mxm/src/mlxm_cq.c
- prov/mxm/src/mlxm_domain.c
- prov/mxm/src/mlxm_ep.c
- prov/mxm/src/mlxm_helpers.h
- prov/mxm/src/mlxm_init.c
- prov/mxm/src/mlxm_mq_storage.h
- prov/mxm/src/mlxm_mr.c
- prov/mxm/src/mlxm_tagged.c
- prov/mxm/src/mpool.h
- prov/mxm/src/uthash.h
- src/fabric.c
- EP_RDM, FI_TAGGED
- Basic CQ, AV interfaces
Signed-Off-By: Valentin Petrov <valentin.petrov@intel.com>
> MXM OFI provider

- man/fi_tagged.3.md
- prov/sockets/src/sock_progress.c
- Update sockets provider to make FI_PEEK asynchronous (for message not-found case)
- Man page clarification about FI_PEEK
@shefty, @sayantansur, @j-xiong - Please review.
> sockets, man pages: Updates to FI_PEEK

- prov/psm/src/psmx_tagged.c
In accordance with the updated man page of the FI_SEEK flag. Instead of
returing -FI_ENOMSG, return 0 and report the result in a CQE with error
code -FI_ENOMSG.
> prov/psm: create error entry for empty result of recv with FI_SEEK flag

- prov/usnic/src/usdf_msg.c
- prov/usnic/src/usdf_rdm.c
Here's the fix for v1.1.x. 
@goodell @jsquyres
> usnic: Drop erroneous packets

- prov/psm/src/psmx.h
- prov/psm/src/psmx_init.c
Check the threading, progress, ordering, iov limit, and inject
size requirements.
> prov/psm: check more fields of the hints passed to fi_getinfo

- prov/psm/src/psmx_am.c
> prov/psm: fix a typo in log messages

- prov/psm/src/psmx.h
- prov/psm/src/psmx_domain.c
- prov/psm/src/psmx_util.c
> prov/psm: add UUID and PSM epid to debug output

- prov/psm/src/psmx_init.c
> prov/psm: fix inversed condition for freeing up fabric object

- prov/psm/src/psmx_util.c
> prov/psm: convert a remaining "perror" to logging function

- prov/psm2/src/rename.h
> prov/psm: update psm2 rename.h with new symbols

- NEWS.md
> NEWS: update usnic provider notes for v1.1.1

- NEWS.md
> NEWS: update psm provider notes for v1.1.1

- man/fi_usnic.7.md
> update fi_usnic(7) man page for the 1.1.1 release

- NEWS.md
- man/fi_usnic.7.md
I updated the NEWS and man page on the 1.1.x branch but forgot to update master.
This is the combined content of #1310 and #1312.
@bturrubiates please review
> master documentation updates for 1.1.1

- prov/sockets/src/sock_ep_msg.c
- Fixes #985 
@shefty, @shantonu  - please review.
> prov/sockets: set address size correctly in fi_getname/fi_getpeer

- NEWS.md
> Update news.md with verbs provider updates.

- NEWS.md
> NEWS: Update sockets provider notes for v1.1.1 and v1.1.0

- prov/verbs/src/fi_verbs.c
- Flag IBV_SEND_INLINE is valid only for IBV_WR_SEND and
IBV_WR_RDMA_WRITE opcodes. Don't set it for other opcodes.
- Fix MR access permissions corresponding to FI_REMOTE_WRITE
to allow atomic ops.
> prov/verbs: Fix invalid usage of IBV_SEND_INLINE

- libfabric.spec.in
- man/fi_atomic.3.md
- man/fi_endpoint.3.md
- man/fi_getinfo.3.md
Man page updates + 1 update to the spec file
> V1.1.x picked updates from master

- prov/sockets/src/sock_atomic.c
- prov/sockets/src/sock_av.c
- prov/sockets/src/sock_cntr.c
- prov/sockets/src/sock_comm.c
- prov/sockets/src/sock_conn.c
- prov/sockets/src/sock_cq.c
- prov/sockets/src/sock_ctx.c
- prov/sockets/src/sock_dom.c
- prov/sockets/src/sock_ep.c
- prov/sockets/src/sock_ep_dgram.c
- prov/sockets/src/sock_ep_msg.c
- prov/sockets/src/sock_ep_rdm.c
- prov/sockets/src/sock_eq.c
- prov/sockets/src/sock_fabric.c
- prov/sockets/src/sock_msg.c
- prov/sockets/src/sock_poll.c
- prov/sockets/src/sock_progress.c
- prov/sockets/src/sock_rma.c
- prov/sockets/src/sock_rx_entry.c
- prov/sockets/src/sock_trigger.c
- prov/sockets/src/sock_util.h
- prov/sockets/src/sock_wait.c
Removed trailing spaces and fixed other indentation issues.
@jithinjosepkl, can you please review?
> prov/sockets: Formatting fix

- index.md
- v1.1.1/man/fabric.7.md
- v1.1.1/man/fi_atomic.3.md
- v1.1.1/man/fi_av.3.md
- v1.1.1/man/fi_cm.3.md
- v1.1.1/man/fi_cntr.3.md
- v1.1.1/man/fi_control.3.md
- v1.1.1/man/fi_cq.3.md
- v1.1.1/man/fi_direct.7.md
- v1.1.1/man/fi_domain.3.md
- v1.1.1/man/fi_endpoint.3.md
- v1.1.1/man/fi_eq.3.md
- v1.1.1/man/fi_errno.3.md
- v1.1.1/man/fi_fabric.3.md
- v1.1.1/man/fi_getinfo.3.md
- v1.1.1/man/fi_mr.3.md
- v1.1.1/man/fi_msg.3.md
- v1.1.1/man/fi_poll.3.md
- v1.1.1/man/fi_provider.7.md
- v1.1.1/man/fi_psm.7.md
- v1.1.1/man/fi_rma.3.md
- v1.1.1/man/fi_sockets.7.md
- v1.1.1/man/fi_tagged.3.md
- v1.1.1/man/fi_trigger.3.md
- v1.1.1/man/fi_usnic.7.md
- v1.1.1/man/fi_verbs.7.md
- v1.1.1/man/fi_version.3.md
- v1.1.1/man/index.md
> gh-pages: update site for v1.1.1 release

- man/fi_cq.3.md
> fi_cq.3.md: trivial s/event/completion/ fix.

- include/fi_list.h
- include/fi_rbuf.h
> Fix rbuf-fd/dlist-fd reset op

- prov/verbs/src/fi_verbs.c
This patch refactors fi_send, fi_rma and atomic functions to use more common code. Added the following fi_inject functions: fi_inject, fi_injectdata, fi_inject_write, fi_inject_writedata. fi_inject_atomic is not supported since verbs doesn't support inline atomic operations.
> prov/verbs: Refactor fi_send, fi_rma and atomic functions, add fi_inject functions

- .travis.yml
- include/fi_signal.h
Allow travis CI to perform continuous integration testing.
> Add .travis.yml to support Travis CI

- prov/verbs/src/fi_verbs.c
> verbs: Fix build by updating to fi_signal.h

- .travis.yml
- Makefile.am
This will make it easier to verify the build and integrate
with the travis CI test system.
> make: Add make test option

- .travis.yml
Increase build and testing speed by adding container
support for travis.
> travis: Add support for containers

- man/fi_poll.3.md
> man/poll: Minor grammar fix

- prov/verbs/src/fi_verbs.c
> prov/verbs: Fix crash in fi_sendmsg when msg->desc is NULL

- prov/psm/src/psmx.h
- prov/psm/src/psmx_domain.c
> prov/psm: add a progress thread to enable auto progress

- prov/psm/src/psmx_init.c
Auto progress is supported with the addition of the progress thread.
Support of additional threading modes is made possible by the
addition of the spin lock inside the poll funciton.
> prov/psm: allow auto progress & more threading modes in fi_getinfo

- man/fi_av.3.md
> man/av: Minor formatting tweak

- src/fabric.c
> Add debug error message if prov_name is non-NULL in fabric_attr field of struct fi_info

- .travis.yml
> Enable Travis CI on OS X

- prov/psm/src/psmx_cq.c
- prov/psm/src/psmx_eq.c
To make the free list access thread safe.
> prov/psm: protect the access of the CQ/EQ free list with mutex

- prov/psm/src/psmx_atomic.c
> prov/psm: bug fix -- add missing check of malloc return values

- prov/psm/src/psmx_av.c
> prov/psm: fix a potential memory leak

- include/fi.h
> fi.h: add definition of fastlock_tryacquire

- prov/psm/src/psmx.h
- prov/psm/src/psmx_cq.c
- prov/psm/src/psmx_domain.c
> prov/psm: replace pthread spinlock with fastlock

- man/fi_msg.3.md
- man/fi_rma.3.md
> man: Add reference to FI_DELIVERY_COMPLETE to msg and rma man pages

- src/enosys.c
> fabric: provide enosys like call for cq_strerror

- include/fi_list.h
> fi_list: Add foreach macros for list iteration

- man/fi_atomic.3.md
- man/fi_rma.3.md
- man/fi_tagged.3.md
Fix reference to incorrect flag name.
Fixed #1381
> man: Change wording from FI_COMPLETION to FI_SELECTIVE_COMPLETION

- prov/sockets/src/sock_progress.c
> sockets: coverity fix

- prov/verbs/src/verbs_info.c
After finding the right "verbs_info", make a copy of it for
check_info so that check_info->next is NULL. This is needed
so that fi_ibv_get_matching_info doesn't return a list of
fi_info structures. When the info given in hints resolves to
a particular verbs device the app expects only one fi_info
structure.
> prov/verbs: Make a copy for check_info

- include/rdma/fabric.h
- prov/mxm/src/mlxm_init.c
> mxm: define a protocol value

- Makefile.am
- prov/psm/src/psmx.h
- prov/psm/src/psmx_fabric.c
- prov/psm/src/psmx_init.c
- prov/psm2/src/psmx_fabric.c
> prov/psm: move fabric implementation into a separate source file

- prov/psm/src/psmx_domain.c
(1) take the fabric reference when domain is already open
(2) set active domain before installing AM handlers
> prov/psm: a few minor fixes for domain opening

- prov/psm/src/psmx.h
> prov/psm: add FI_SOURCE to the supported capabilities on PSM2

- prov/psm/src/psmx_msg.c
- prov/psm/src/psmx_rma.c
- prov/psm/src/psmx_tagged.c
> prov/psm: add the missing injectdata functions for PSM2

- man/fi_psm.7.md
> man: update the fi_psm page to reflect the latest changes

- prov/usnic/src/usdf_av.c
Fairly obvious fixes.
@bturrubiates or @jsquyres, please review
> usnic: AV improvements

- man/fi_psm.7.md
> man: minor tweaks of the fi_psm page

- NEWS.md
> NEWS: update psm/psm2 provider notes for 1.2.0

- NEWS.md
> NEWS: Update sockets provider notes for 1.2.0

- prov/usnic/src/usdf_av.c
- Use getaddrinfo to resolve the given node/service into an address that
can be used in the regular fi_av_insert calls.
> usnic: Implement fi_av_insertsvc.

- prov/gni/test/run_gnitest
Merge of ofi-cray/libfabric-cray#545
@sungeunchoi 
(cherry picked from commit ofi-cray/libfabric-cray@12b984f7ab1c633f26743e43651278f0ef21cc93)
> Add aprun/srun timeout

- prov/gni/include/gnix.h
- prov/gni/include/gnix_hashtable.h
- prov/gni/include/gnix_nic.h
- prov/gni/include/gnix_vc.h
- prov/gni/src/gnix_atomic.c
- prov/gni/src/gnix_ep.c
- prov/gni/src/gnix_hashtable.c
- prov/gni/src/gnix_msg.c
- prov/gni/src/gnix_nic.c
- prov/gni/src/gnix_rma.c
- prov/gni/src/gnix_vc.c
- prov/gni/test/cancel.c
- prov/gni/test/hashtable.c
Merge ofi-cray/libfabric-cray#516
@sungeunchoi
> Upstream stage pr516

- prov/gni/include/gnix_av.h
- prov/gni/include/gnix_cq.h
- prov/gni/include/gnix_hashtable.h
- prov/gni/include/gnix_vc.h
- prov/gni/src/gnix_atomic.c
- prov/gni/src/gnix_av.c
- prov/gni/src/gnix_cq.c
- prov/gni/src/gnix_hashtable.c
- prov/gni/src/gnix_msg.c
- prov/gni/src/gnix_rma.c
- prov/gni/src/gnix_vc.c
- prov/gni/test/cq.c
- prov/gni/test/rdm_sr.c
Fixes ofi-cray/libfabric-cray#348.
Merge of ofi-cray/libfabric-cray#536
@sungeunchoi 
(cherry picked from commit f7392c173a506b9ef75dc3d018485c797775ddcc)
> Implement FI_SOURCE capability.

- prov/gni/src/gnix_msg.c
- prov/gni/src/gnix_vc.c
merge of ofi-cray/libfabric-cray#539
@sungeunchoi
> Upstream stage pr539

- prov/gni/test/rdm_rx_overrun.c
The previous assertion in this test went away with some of the recent
changes.  When I enabled this test, I noticed it wasn't going through
the overrun path as intended, since we were using the same domain for
all endpoints and hence always making progress.  So I rewrote it to
use separate domains for each endpoint and ran into an issue in
__gnix_vc_connect_to_self that eventually leads to a Criterion
assertion.
Merge of ofi-cray/libfabric-cray#522
@sungeunchoi 
(cherry picked from commit d2aad6beb65aa40d08d68c47e92a91c23cf4a583)
> Update the rdm_rx_overrun test (still doesn't work)

- prov/gni/include/gnix.h
- prov/gni/include/gnix_nic.h
- prov/gni/src/gnix_ep.c
- prov/gni/src/gnix_msg.c
- prov/gni/src/gnix_rma.c
- prov/gni/test/rdm_rma.c
- prov/gni/test/rdm_sr.c
Merge of ofi-cray/libfabric-cray#542
@sungeunchoi
> Upstream stage pr542

- prov/psm2/src/psmx2_domain.c
> prov/psm2: simplify the key comparing function

- prov/sockets/src/sock_wait.c
prov/sockets: read out wait_fd after wait() call
> prov/sockets: read out wait_fd after wait() call

- prov/sockets/src/sock_dom.c
prov/sockets: Simplify mr_key comparison
> prov/sockets: Simplify mr_key comparison

- prov/psm2/src/psmx2_init.c
There is a deadlock scenario that psm2_finalize() as part of call
chain of exit() is called within the PSM signal handler, which
happens to take place inside a PSM call that holds the lock that
psm2_finalize() tries to acquire.
> prov/psm2: fix a potential deadlock with abnormal termination

- prov/psm/src/psmx_init.c
The same as the psm2 fix (commit 5ee09d60).
> prov/psm: fix a potential deadlock with abnormal termination

- man/fi_psm.7.md
To reflect the latest changes to the psm2 provider.
> man: update fi_psm man page

- Makefile.am
- configure.ac
- prov/sockets/src/sock.h
- prov/sockets/src/sock_atomic.c
- prov/sockets/src/sock_av.c
- prov/sockets/src/sock_comm.c
- prov/sockets/src/sock_conn.c
- prov/sockets/src/sock_ctx.c
- prov/sockets/src/sock_dom.c
- prov/sockets/src/sock_ep.c
- prov/sockets/src/sock_ep_dgram.c
- prov/sockets/src/sock_ep_msg.c
- prov/sockets/src/sock_ep_rdm.c
- prov/sockets/src/sock_epoll.c
- prov/sockets/src/sock_msg.c
- prov/sockets/src/sock_progress.c
- prov/sockets/src/sock_rma.c
Scalability enhancements for sockets-provider
> prov/sockets - Scalability enhancements

- prov/sockets/src/sock_conn.c
- prov/sockets/src/sock_progress.c
> prov/sockets: coverity scan fixes

- prov/gni/src/gnix_vc.c
When multiple threads in the gni provider
are using the same gnix_nic, there was the potential
for hitting the dining philosopher problem when
processing the work queue in one thread and processing
smsg messages in another thread.
This commit fixes that problem.
@ztiffany 
Upstream merge of ofi-cray/libfabric-cray#557
(cherry picked from commit ofi-cray/libfabric-cray@2b95e7891894141a9557131dfebff1d8579ac2fb)
> prov/gni: fix potential deadlock in vc wq

- Makefile.am
- prov/usnic/src/usdf_cq.c
- prov/usnic/src/usdf_ep_msg.c
- prov/usnic/src/usdf_ep_rdm.c
- prov/usnic/src/usdf_fabric.c
- prov/usnic/src/usnic_direct/cq_desc.h
- prov/usnic/src/usnic_direct/cq_enet_desc.h
- prov/usnic/src/usnic_direct/kcompat.h
- prov/usnic/src/usnic_direct/usd.h
- prov/usnic/src/usnic_direct/usd_device.c
- prov/usnic/src/usnic_direct/usd_ib_cmd.c
- prov/usnic/src/usnic_direct/usd_poll.c
- prov/usnic/src/usnic_direct/usd_queues.c
- prov/usnic/src/usnic_direct/usnic_abi.h
- prov/usnic/src/usnic_direct/usnic_direct.h
- prov/usnic/src/usnic_direct/usnic_ib_abi.h
- prov/usnic/src/usnic_direct/vnic_cq.c
- prov/usnic/src/usnic_direct/vnic_cq.h
- prov/usnic/src/usnic_direct/vnic_dev.c
- prov/usnic/src/usnic_direct/vnic_dev.h
- prov/usnic/src/usnic_direct/vnic_devcmd.h
- prov/usnic/src/usnic_direct/vnic_intr.c
- prov/usnic/src/usnic_direct/vnic_intr.h
- prov/usnic/src/usnic_direct/vnic_resource.h
- prov/usnic/src/usnic_direct/vnic_rq.c
- prov/usnic/src/usnic_direct/vnic_rq.h
- prov/usnic/src/usnic_direct/vnic_wq.c
- prov/usnic/src/usnic_direct/vnic_wq.h
Signed-off-by: Xuyang Wang <xuywang@cisco.com>
@goodell @jsquyres @bturrubiates
> Update usnic_direct to SVN r253971

- prov/mxm/src/mlxm_tagged.c
> MXM: fi_tinject support

- prov/verbs/src/ep_rdm/verbs_rdm.h
- prov/verbs/src/ep_rdm/verbs_rdm_cm.c
- prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm.c
- prov/verbs/src/ep_rdm/verbs_utils.c
- prov/verbs/src/ep_rdm/verbs_utils.h
Squashed #1512 + signature.
Signed-off-by: Dmitry Durnov <dmitry.durnov@intel.com>
> Verbs provider. EP_RDM/FI_TAGGED. fi_tinject fix + ack handling opt

- .travis.yml
I don't know a better way to test my `.travis.yml` modifications than to open a PR.  So hold off merging this until we see if it works or not.
> travis: attempt to enable verbs and usnic

- README.md
> README.md: add Travis CI badge to GH landing page

- prov/mxm/configure.m4
> Redundant configure options for mxm provider.

- prov/usnic/src/usnic_direct/usd_ib_cmd.c
- prov/usnic/src/usnic_direct/vnic_dev.c
> Update to SVN r254426: Fixed 2 coverity warnings

- prov/gni/src/gnix_av.c
- prov/gni/src/gnix_cm.c
- prov/gni/src/gnix_cq.c
- prov/gni/src/gnix_dom.c
- prov/gni/src/gnix_ep.c
upstream merge of ofi-cray/libfabric-cray#569
@sungeunchoi 
(cherry picked from commit ofi-cray/libfabric-cray@3e0f3f75857453a40efc1e303f97da5f83c286d4)
> prov/gni:Install the proper fi_no_* versions

- prov/verbs/src/ep_rdm/verbs_ep_rdm.c
- prov/verbs/src/fi_verbs.h
> verbs: Fix for coverity issue.

- .mailmap
> Update entry in .mailmap.

- prov/usnic/src/usdf_ep_dgram.c
- prov/usnic/src/usdf_ep_msg.c
- prov/usnic/src/usdf_eq.c
- prov/usnic/src/usdf_fabric.c
- prov/usnic/src/usdf_timer.c
Update memory handling in the usnic provider.
@jsquyres
> usnic: Update memory handling 

- NEWS.md
> usnic: Add NEWS.

- man/fi_provider.7.md
> Adding GNI provider man page link to fi_provider

- AUTHORS
- NEWS.md
> Update NEWS and AUTHORS with GNI provider stuff

- NEWS.md
prov/sockets: Update NEWS for sockets provider
> prov/sockets: Update NEWS for sockets provider

- prov/gni/include/gnix.h
- prov/gni/include/gnix_nic.h
- prov/gni/src/gnix_msg.c
- prov/gni/src/gnix_nic.c
- prov/gni/src/gnix_rma.c
- prov/gni/test/rdm_sr.c
Upstream merge of ofi-cray/libfabric-cray#572
@sungeunchoi 
@ztiffany
> Stage upstream pr572

- prov/gni/test/run_gnitest
upstream merge of ofi-cray/libfabric-cray#565
@sungeunchoi 
(cherry picked from commit ofi-cray/libfabric-cray@ea4df6fdb84083c1726fb1754ce56f378c08cce9)
> Disable CPU binding on job launch

- prov/gni/test/rdm_rx_overrun.c
exercise the RX overrun path.
Howard got the basic test working with a bug fix, and now I finally
got this test to exercise the RX overrun path.
The test sets the RX CQ size to 1 and then sends messages from many
endpoints to endpoint 0.  Note that even tho we request an RX CQ size
of 1, the ugni internal minimum appears to be something like 511, so
we have to send more than 1 message per endpoint.  Currently 60
endpoints send 10 message each before endpoint 0 queries its CQ.
When run with FI_LOG_LEVEL=warn, we see the warning due to calling
__nic_rx_overrun.
TODO: Figure out a good way to make sure we continue to test the
overrun path, without having to manually check if we get the warning.
@sungeunchoi 
upstream merge of ofi-cray/libfabric-cray#568
Signed-off-by: Sung-Eun Choi …
> prov/gni:Update rdm_rx_overrun test to actually

- prov/gni/configure.m4
The criterion tests are not included in the dist
tarball.  Modify configury to report an error
at configure time if --with-criterion option is
supplied when building from a dist tarball rather
than failing during make.
upstream merge of ofi-cray/libfabric-cray#570
@sungeunchoi 
(cherry picked from commit ofi-cray/libfabric-cray@ba30d9faf84743370261b4ff503324e9101efdbe)
Conflicts:
prov/gni/configure.m4
> prov/gni: disable criterion config for dist

- man/fi_provider.7.md
> Change formatting of GNI text in fi_provider man page

- prov/usnic/src/usdf_cq.c
- prov/usnic/src/usdf_dgram.c
- prov/usnic/src/usdf_dgram.h
- prov/usnic/src/usdf_ep_dgram.c
- prov/usnic/src/usdf_ep_msg.c
- prov/usnic/src/usdf_ep_rdm.c
- prov/usnic/src/usdf_msg.c
- prov/usnic/src/usdf_msg.h
- prov/usnic/src/usdf_pep.c
- prov/usnic/src/usdf_rdm.c
- prov/usnic/src/usdf_rdm.h
> usnic: Use fi_no_* functions for unimplemented features.

- man/fi_gni.7.md
> man/fi_gni: Fix type-o in FI_TAGGED section

- prov/psm2/src/psmx2.h
- prov/psm2/src/psmx2_cq.c
- prov/psm2/src/psmx2_msg.c
> prov/psm2: fix a bug in multi-recv.

- Makefile.am
- config/fi_provider.m4
- configure.ac
- libfabric.pc.in
- libfabric.spec.in
> Adding pkg-config support.

- prov/verbs/src/ep_rdm/verbs_ep_rdm.c
- prov/verbs/src/ep_rdm/verbs_rdm.h
- prov/verbs/src/ep_rdm/verbs_rdm_cm.c
- prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm.c
- prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm_states.c
- prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm_states.h
- prov/verbs/src/ep_rdm/verbs_utils.h
- prov/verbs/src/fi_verbs.h
- prov/verbs/src/verbs_rma.c
Reopen #1604 - excluded merge commit
1) Commit #3c27306 fixes debug build
Others are nice to have
2) Refactoring send/recv paths + request structure
3) Implementation of rma read/write/inject
> verbs RDM. fix of debug build + refactoring send/recv part + rma read/write/inject

- prov/gni/src/gnix_dom.c
upstream merge of ofi-cray/libfabric-cray#579
@sungeunchoi 
Fixes ofi-cray/libfabric-cray#452
(cherry picked from commit ofi-cray/libfabric-cray@4b405f4f47a5753eac0c201c4d1b1ad1156bd012)
> prov/gni: Set SMSG max retransmits #452

- NEWS.md
- man/fi_verbs.7.md
> verbs: Update man pages and news

- prov/gni/include/gnix_bitmap.h
- prov/gni/src/gnix_bitmap.c
upstream merge of PR ofi-cray/libfabric-cray#586
@sungeunchoi 
(cherry picked from commit ofi-cray/libfabric-cray@752e961e927ff08e368142704b80ce190632c3b0)
> prov/gni/src: Fixed "HAVE_ATOMICS" build warnings.

- man/fi_usnic.7.md
> usnic: Update usnic.7 man page for 1.2.0

- NEWS.md
Updated to include the latest commits.
> prov/sockets: Updated NEWS for 1.2.0

- NEWS.md
Looks like we missed updating these.  There's no good way to go back and
update the existing releases, but we can at least get the dates right
for all future releases.
> NEWS.md: fix release dates

- index.md
> gh-pages: Link to tutorial slides, not overview slides

- configure.ac
> configure.ac: bump version to 1.3.0a1

- prov/usnic/src/usdf_cq.c
Also, deliberately error on calls to fi_cq_sread when FI_WAIT_NONE has
been specified.  It's not as user friendly in some ways, but I think
taking a stricter interpretation of the libfabric docs is helpful to
users and the project in the long run so that users do not get the
incorrect impression that it is OK to use NONE+sread together.
See discussion in #1629 for more info.
@bturrubiates please review
> usnic: allow FI_WAIT_UNSPEC

- prov/gni/test/rdm_atomic.c
- prov/gni/test/rdm_rma.c
- prov/gni/test/rdm_sr.c
for tests:      
rdm_atomic.c
rdm_rma.c
rdm_sr.c
(cherry picked from commit ofi-cray/libfabric-cray@5781f3760a371ee5cb747243ce7e6a805ff34cd1)
This is a squash of commits that went in with PR ofi-cray/libfabric-cray#575
@sungeunchoi 
> prov/gni/test: Allocated separate domains for eps

- prov/gni/include/gnix_util.h
- prov/gni/src/gnix_cm_nic.c
- prov/gni/src/gnix_cq.c
- prov/gni/src/gnix_dom.c
- prov/gni/src/gnix_ep.c
- prov/gni/src/gnix_eq.c
- prov/gni/src/gnix_nameserver.c
- prov/gni/src/gnix_nic.c
- prov/gni/src/gnix_wait.c
Fixes ofi-cray/libfabric-cray#467
Upstream merge of ofi-cray/libfabric-cray#597
@sungeunchoi 
(cherry picked from commit ofi-cray/libfabric-cray@fed282bcaae8bcc0d9e672b966137e99f8205026)
> prov/gni: Review and update use of GNIX_ERR

- index.md
Provide a link to Jianxin's document that describes how to get
starting writing to libfabric.
> gh-pages: Add link to Getting Started with Libfabric document

- index.md
> gh-pages: Use embedded link, not html link to Getting Started doc

- .gitignore
> gitignore: ignore the generated pkg-config file

- prov/gni/test/allocator.c
that checks for errors.
I think the intention of the double_free test was to check an error
path, but as written, it reads freed memory and cannot be relied on
(though it usually works).  Replace this with a new test that forces
_gnix_mbox_free() to exercise the error paths by manipulating internal
state.
@sungeunchoi 
Upstream merge of ofi-cray/libfabric-cray#505
(cherry picked from commit ofi-cray/libfabric-cray@cb4e58da5843f7c3289a4839b0100973294348b0)
> prov/gni: Replace mbox double_free tests with one

- prov/gni/include/gnix_mr.h
- prov/gni/include/gnix_util.h
- prov/gni/src/gnix_mr.c
- prov/gni/test/dlist-utils.c
- prov/gni/test/mr.c
upstream merge of ofi-cray/libfabric-cray#582
and
ofi-cray/libfabric-cray#622
@sungeunchoi
> prov/gni: improvements to registration cache

- prov/usnic/src/usdf_av.c
- prov/usnic/src/usdf_cm.c
> Set the DF (do not fragment) bit in the IP header.

- man/fi_poll.3.md
- Clarify that when using a wait set, the FD may not always be used with
poll, epoll, or select.
- Clarify that fi_control when used with the FI_GETWAIT command is
provider specific and may fail if it is not supported.
@jsquyres @goodell @shefty
> Add fi_control to fi_poll manpage.

- prov/gni/include/gnix.h
- prov/gni/include/gnix_tags.h
- prov/gni/src/gnix_ep.c
- prov/gni/test/av.c
- prov/gni/test/cntr.c
- prov/gni/test/dlist-utils.c
- prov/gni/test/eq.c
- prov/gni/test/queue.c
- prov/gni/test/rdm_atomic.c
- prov/gni/test/rdm_rma.c
Upstream merge of ofi-cray/libfabric-cray#621
@sungeunchoi
> prov/gni: minor code fixes

- prov/gni/src/gnix_cm_nic.c
upstream merge of PR ofi-cray/libfabric-cray#627
@sungeunchoi 
(cherry picked from commit ofi-cray/libfabric-cray@4cedb537c12a1150548ec82353fd654dd48a19c9)
> prov/gni: minor code cleanup

- man/fi_av.3.md
- prov/sockets/src/sock_av.c
@shefty - Please review.
Please see discussion on #1671.
> Allow FI_AV_UNSPEC during AV-open

- _config.yml
@shefty 
I think this should fix the issue.
> Github-pages no longer supports pygments.

- _config.yml
> Fix the typo on updating the highlighter.

- prov/gni/include/gnix_util.h
enabled
Performance could drop by as much as 80% in debug
builds due to the unconditional calls of sprintf
and atomic functions. This commit adds the FI_LOG_*
levels to the GNIX_* log calls and passes those log
levels to the fi_log_enabled function
@sungeunchoi 
(cherry picked from commit ofi-cray/libfabric-cray@3487d718566e6f1399f01ef93d4f583a49fae4a6)
upstream merge of ofi-cray/libfabric-cray#630
(cherry picked from commit ofi-cray/libfabric-cray@6e536d882be99c04f3cebf3444ea0444f00c7886)
upstream merge of ofi-cray/libfabric-cray#631
> prov/gni: Only retrieve debug strings if log

- prov/util/src/util_domain.c
> util: Release reference on fabric when domain is closed

- prov/verbs/src/verbs_domain.c
iWARP spec (RDMA Protocol Verbs Specification 1.0) requires consumers
of RDMA read responses (RDMA read data sinks) to have Remote Write
Access flags enabled. Verbs provider should enable this access
flag for iWARP transports. Also allow Local Write only when required.
> verbs: Add REMOTE_WRITE access for RMA reads on iWARP

- Makefile.am
- include/fi.h
- include/fi_list.h
- include/fi_mem.h
- include/fi_util.h
- prov/util/src/util_buf.c
prov/util: Add buffer pool utility in common code
@shefty
> prov/util: Add buffer pool utility

- include/fi_util.h
- prov/udp/src/udpx_domain.c
- prov/udp/src/udpx_fabric.c
- prov/util/src/util_domain.c
- prov/util/src/util_fabric.c
prov/util: Update util_fabric / util_domain create operations to allow these util objects to be encapsulated
> prov/util: Update util_fabric / util_domain create operations to allow util objects to be encapsulated

- prov/udp/configure.m4
prov/udp: Allow configure time enable/disable of UDP provider.
> prov/udp: Allow configure time enable/disable of UDP provider.

- prov/sockets/src/sock_av.c
We added an index array for shared_av. Updated av_table size calculation during <code>sock_av_close</code>. Verified with other fabtests and <code>fi_rdm_shared_av</code> test.
@jithinjosepkl 
> prov/sockets: Fixed av_table size calculation in av_close for shared av

- include/fi_list.h
>  Add null check to slist item reset in slist_remove_head

- prov/gni/test/tags.c
Replaced the traditional test fixtures with
parameterized tests. This shortens the file and reduces
complexity at the cost of verbosity in the test output.
(cherry picked from commit ofi-cray/libfabric-cray@e53bb9bea4c6848ab78fd3dcdd9941a750d2c2fc)
upstream merge of ofi-cray/libfabric-cray#632
@sungeunchoi
> prov/gni: Replaced tests with parameterized tests

- prov/gni/src/gnix_cq.c
- prov/gni/test/cq.c
This is an inefficient implementation of blocking CQ read functions.
(cherry picked from commit ofi-cray/libfabric-cray@3996ea8fca00424968e7d57519f9a55bc7d5e307)
upstream merge or PR ofi-cray/libfabric-cray#641
@sungeunchoi
> prov/gni: busy sread() implementation

- prov/gni/include/gnix_buddy_allocator.h
- prov/gni/src/gnix_buddy_allocator.c
- prov/gni/test/buddy_allocator.c
upstream merge of ofi-cray/libfabric-cray#649
@sungeunchoi
> prov/gni: add stressor tests for buddy allocator

- prov/gni/src/gnix_ep.c
- prov/gni/test/ep.c
Fixes ofi-cray/libfabric-cray#612.
Fixes ofi-cray/libfabric-cray#637.
(cherry picked from commit ofi-cray/libfabric-cray@21d941a9b88b98f0433703f4d627fd6a59516a6e)
upstream merge of ofi-cray/libfabric-cray#648
@sungeunchoi
> prov/gni: Implement ep_getopt/setopt/sizeleft

- prov/gni/src/gnix_vc.c
This make it look like the TX progress loop and fixes some hangs.
(cherry picked from commit ofi-cray/libfabric-cray@6618214b5dfd8d8d44043082962008aabcae42b1)
upstream merge of ofi-cray/libfabric-cray#650
@sungeunchoi
> prov/gni: Break out of the RX progress loop after seeing the same VC twice

- index.md
* Fix typo
* Add libfabric-users mailing list to the web page
> Minor updates to gh-pages

- prov/psm2/src/psmx2.h
- prov/psm2/src/psmx2_cntr.c
- prov/psm2/src/psmx2_cq.c
- prov/psm2/src/psmx2_msg.c
- prov/psm2/src/psmx2_tagged.c
> prov/psm2: support multi-iov send for tagged message queue

- prov/psm2/src/psmx2.h
- prov/psm2/src/psmx2_cntr.c
- prov/psm2/src/psmx2_rma.c
> prov/psm2: add multi-iov support for RMA write

- prov/gni/include/gnix_buddy_allocator.h
- prov/gni/src/gnix_buddy_allocator.c
and
__gnix_buddy_coalesce.  Moved BITMAP_INDEX and BUDDY to inline
functions.
(cherry picked from commit ofi-cray/libfabric-cray@b09fd7396462266070124fc86fcf6102e8b13108)
upstream merge of ofi-cray/libfabric-cray#656
@sungeunchoi
> prov/gni: Improve performance of gnix_buddy_alloc

- prov/usnic/src/usnic_direct/libnl_utils_common.c
Querying the routing tables via netlink is expensive, especially when many processes are doing so at the same time on a single server (e.g., in an MPI job).  As such, we cache netlink responses to alleviate pressure on the netlink kernel interface.
Reviewed by @bturrubiates and @rfaucett
> usnic: add a cache for netlink route query lookups

- prov/usnic/src/usdf_dgram.c
> usnic: Check length field given to dgram send functions.

- prov/sockets/src/sock_av.c
prov/sockets: do ftruncate only once on the initial shm segment, to support OSX.
> prov/sockets: do ftruncate only once on the initial shm segment, to support OSX.

- prov/verbs/src/ep_rdm/verbs_queuing.h
- prov/verbs/src/ep_rdm/verbs_rdm.h
- prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm.c
- prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm_states.c
- prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm_states.h
- prov/verbs/src/ep_rdm/verbs_utils.c
- prov/verbs/src/ep_rdm/verbs_utils.h
- prov/verbs/src/verbs_rma.c
This is a bunch of bugfixes and refactoring for TAGGED and RMA capabilities of verbs provider
> Verbs provider. EP_RDM improvements.

- _config.yml
This should fix #1635. 
@jsquyres @shefty 
> Fix assets loading over http.

- man/fi_endpoint.3.md
- man/fi_version.3.md
> Minor updates to man pages.

- config/github-webhook/README
- config/ofiwg-bot@flatbed:.bashrc
Update the github webhook README with a bit more information about the
Sinatra installation.  Also save a copy of ofiwg-bot's .bashrc.
> infrastructure: update notes

- include/fi_mem.h
- prov/sockets/src/sock_progress.c
- prov/util/src/util_buf.c
> util/buf: Extend util_buf to add memory region alloc/free handlers

- .travis.yml
> Update librdmacm git dependency to point at the Github mirror.

- include/fi_mem.h
- prov/util/src/util_buf.c
> util: Add missing include to fi_mem.h + fix buf pool release

- prov/usnic/src/usdf_eq.c
@jsquyres Please review, I apologize for it being kinda messy. 
Cleanup of the EQ code. I saw some bugs and fixed them. Of the extra tests added in PR ofiwg/fabtests#458, 2 will fail without this PR.
> usnic: EQ updates

- prov/gni/include/gnix_buddy_allocator.h
- prov/gni/test/buddy_allocator.c
tests.
(cherry picked from commit ofi-cray/libfabric-cray@2e89509ddf58ae01f6dd12e03c4202b767577441)
upstream merge of ofi-cray/libfabric-cray#674
@sungeunchoi
> prov/gni: Reduce runtime of buddy allocator unit

- prov/sockets/src/sock.h
- prov/sockets/src/sock_cntr.c
- prov/sockets/src/sock_cq.c
- prov/sockets/src/sock_ep.c
- prov/sockets/src/sock_fabric.c
- prov/sockets/src/sock_progress.c
- prov/sockets/src/sock_wait.c
- Increase max_atomic_msg_size 
- Disable get-wait-obj in manual-progress mode
- minor cleanups in connection management
> prov/sockets: minor updates

- README
> Mention Libfabric-users mailing list in distribution README.

- prov/sockets/src/sock_progress.c
- Fix out of order tx operations
> prov/sockets: Check pending tx-ops-list before issuing new tx-ops.

- config/cron-make-nightly-tarball.pl
- config/ofiwg-bot@flatbed:crontab.txt
Minor fix and minor update to the nightly tarball script.
> Minor nightly tarball tweaks

- man/fi_getinfo.3.md
It wasn't clear to me why this sentence was in quotes. Seemed
rather weird.
> man: minor change removing quotes

- prov/gni/src/gnix_vc.c
fixes ofi-cray/libfabric-cray#661
(cherry picked from commit ofi-cray/libfabric-cray@cfc2ccbeeecfbccbe30478f3b5e934155dfc8736)
upstream merge of ofi-cray/libfabric-cray#686
@sungeunchoi
> prov/gni: fixes for vc setup

- NEWS.md
- Create 1.3.0 entry. 
- Add new provider slots (excluded util). 
- Add initial information for usNIC.
@shefty @jsquyres @goodell 
> NEWS: Provide initial information for 1.3 release.

- prov/verbs/src/ep_rdm/verbs_av_ep_rdm.c
- prov/verbs/src/ep_rdm/verbs_rdm.h
- prov/verbs/src/ep_rdm/verbs_rdm_cm.c
- prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm.c
- prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm_states.c
- prov/verbs/src/ep_rdm/verbs_utils.c
- prov/verbs/src/ep_rdm/verbs_utils.h
Implemented support messaging within the process + code clean up in connection management logic
@a-ilango
> verbs/RDM. Add connection to self

- prov/usnic/src/usdf_msg.c
- prov/usnic/src/usdf_rdm.c
> usnic: Minor cleanups

- include/fi_mem.h
- include/fi_rbuf.h
- man/fi_endpoint.3.md
- prov/udp/src/udpx.h
- prov/udp/src/udpx_cq.c
- prov/udp/src/udpx_ep.c
2 of these commits are from PR #1793, which are helper functionality that will be used by at least the shared memory provider.
> util: Update to cirque, addition of freestack, plus man page tweak

- man/fi_poll.3.md
> Fix minor spelling mistake.

- prov/usnic/src/usdf_cq.c
> usnic: Some CQ refactoring

- NEWS.md
> NEWS: update psm and psm2 provider notes for 1.3 release.

- NEWS.md
> NEWS: Added sockets provider updates for 1.3 release

- prov/verbs/src/ep_rdm/verbs_utils.h
Issue #1842 Non-x86 
Signed-off-by:Evgeny Leksikov <evgeny.leksikov@intel.com>
> verbs/RDM: fix non-x86 build

- prov/usnic/Makefile.include
- prov/usnic/src/usdf_cq.c
- prov/usnic/src/usdf_cq.h
- prov/usnic/src/usdf_domain.c
- prov/usnic/src/usdf_poll.c
- prov/usnic/src/usdf_poll.h
@goodell @jsquyres 
We now pass the `fi_poll` test in fabtests.
> usnic: Implement pollsets

- prov/sockets/src/sock_poll.c
- Added reference counting for pollset
- Cleanup code
@jithinjosepkl
> prov/sockets: Added reference counting for pollset

- prov/usnic/src/usdf_poll.c
Compiler warned that "ret" was set but not used.  Now support the run-time error in non-debug builds (i.e., where the assert() will not be tripped).  Also move the existing assert() beyond the debug statement (so that something useful is printed out on the screen), and add a symetric assert() in the poll_close() case.
@bturrubiates Please review.
> usnic: fix compiler warning

- include/fi_mem.h
- include/fi_proto.h
- prov/util/src/util_buf.c
- Add context parameter for buffer pool
- Update freestack_pop macro
- Update fi_proto to add new field
> prov/util - Updates to freestack, util-buf and fi_proto

- prov/gni/src/gnix_nameserver.c
On XC nodes with KNC, the "bridge" name for the
gni device shows up in the arp tables.  Check both
ipogif0 and fall back to br0 to get the local
ipv4 addr.
Thanks to @tschuett for reporting.
fixes ofi-cray/libfabric-cray#706
(cherry picked from commit ofi-cray/libfabric-cray@8ce575b5e470e01058f888beb994d29af23c9cfe)
upstream merge of ofi-cray/libfabric-cray#715
@sungeunchoi
> prov/gni: use br0 iface for nodes with KNC

- man/fi_poll.3.md
Minor clarifications / corrections to the fi_poll.3.md page.
> fi_poll.3.md: minor corrections

- prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm.c
fix coverity issue #123865
@a-ilango 
Signed-off-by:Evgeny Leksikov <evgeny.leksikov@intel.com>
> verbs/RDM: fix coverity issue #123865

- NEWS.md
Also correct a minor typo in sockets news.
> verbs: Update NEWS.md

- prov/usnic/src/usnic_direct/kcompat.h
- prov/usnic/src/usnic_direct/libnl_utils_common.c
- prov/usnic/src/usnic_direct/usd_device.c
- prov/usnic/src/usnic_direct/usd_enum.c
- prov/usnic/src/usnic_direct/usd_ib_cmd.c
- prov/usnic/src/usnic_direct/usnic_direct.h
- prov/usnic/src/usnic_direct/vnic_dev.c
- prov/usnic/src/usnic_direct/vnic_rq.c
> usnic: Update usnic_direct to SVN r267315.

- man/fi_usnic.7.md
- prov/usnic/Makefile.include
- prov/usnic/src/fi_ext_usnic.h
- prov/usnic/src/usdf_av.c
- prov/usnic/src/usdf_ext.c
- prov/usnic/src/usdf_fabric.c
> usnic: Add v2 of usnic getinfo extension

- NEWS.md
> NEWS: update psm2 provider notes for 1.3 release

- prov/gni/src/gnix_atomic.c
- prov/gni/src/gnix_datagram.c
- prov/gni/src/gnix_nic.c
- prov/gni/src/gnix_rma.c
- prov/gni/src/gnix_tags.c
- prov/gni/src/gnix_vc.c
Fixes ofi-cray/libfabric-cray#670.
(cherry picked from commit ofi-cray/libfabric-cray@cf11910a5e9b934d63014d8683f835254d2bbd51)
upstream merge of ofi-cray/libfabric-cray#722
@sungeunchoi
> prov/gni: Remove all assert(0) statements

- prov/usnic/Makefile.include
- prov/usnic/src/usdf.h
- prov/usnic/src/usdf_cq.c
- prov/usnic/src/usdf_cq.h
- prov/usnic/src/usdf_domain.c
- prov/usnic/src/usdf_ep_dgram.c
- prov/usnic/src/usdf_ep_msg.c
- prov/usnic/src/usdf_ep_rdm.c
- prov/usnic/src/usdf_eq.c
- prov/usnic/src/usdf_fabric.c
- prov/usnic/src/usdf_poll.c
- prov/usnic/src/usdf_progress.c
- prov/usnic/src/usdf_wait.c
- prov/usnic/src/usdf_wait.h
This PR replaces #1851 (simply because @bturrubiates is out on vacation and we can't amend his original branch).
I addressed all the comments except [@goodell's last comment](https://github.com/ofiwg/libfabric/pull/1851#issuecomment-201149955).  
@goodell Do you think we need to fix locking at the fabric level while accessing the domain list before @bturrubiates returns?
> usnic: Implement waitsets

- NEWS.md
> prov/sockets: NEWS.md updates for 1.3

- prov/gni/src/gnix_util.c
Provide ability to read the ccm file, so when running
using ccm mode you can use the gni provider.
Signed-off-by: James Shimek <jshimek@cray.com>
(cherry picked from commit ofi-cray/libfabric-cray@17642e0fbe800a71f9dcd1010a0fc2eb1ef53659)
upstream merge of ofi-cray/libfabric-cray#746
@sungeunchoi
> prov/gni: Add CCM capability

- prov/gni/include/gnix_util.h
- prov/gni/src/gnix_atomic.c
- prov/gni/src/gnix_rma.c
- prov/gni/test/ep.c
(cherry picked from commit ofi-cray/libfabric-cray@2b8d24d9e9aa4c8f20a3b1105be716dd19a97d1e)
upstream merge of ofi-cray/libfabric-cray#745
@sungeunchoi
> prov/gni: Minor debug cleanup

- AUTHORS
- NEWS.md
> release updates for GNI provider

- AUTHORS
- man/man7/fi_sockets.7
- Updated AUTHORS
- Update sockets man page
> sockets: release updates

- include/fi_rbuf.h
Fix bug in size calculation in cirque-create
@shefty - Please review.
> util/cirque: Fix bug in size calculation in cirque-create

- man/fi_gni.7.md
> Update of gni man page for 1.3.0 release

- prov/sockets/include/rdma/fi_direct.h
@hppritcha found a incomplete comment in the socket provider's version of fi_direct.h.
@sungeunchoi
> prov/sockets: Added terminating comment.

- NEWS.md
> News: Update MXM and UDP news section for v1.3

- Makefile.am
- configure.ac
1. Update to 1.3.0rc2
1. Fix "make rpm" target.
> Release engineering updates

- configure.ac
> configure.ac: bump to v1.3.0rc3

- NEWS.md
- README.md
- man/fi_verbs.7.md
Can these changes make into 1.3?
> verbs/RDM: Update Readme, news and man pages.

- NEWS.md
> NEWS.md: add link to v1.3.0 provider feature matrix wiki page

- prov/verbs/src/ep_rdm/verbs_av_ep_rdm.c
> verbs/RDM. Fix fi_av_test

- configure.ac
> configure.ac: bump version to v1.3.0

- NEWS.md
> NEWS.md: bump the v1.3.0 release date to today

- NEWS.md
- configure.ac
> configure.ac/NEWS.md: bump version to v1.3.1a1

- config/ofiwg-bot@flatbed-crontab.txt
> crontab: update backup of ofiwg-bot@flatbed crontab

- include/fi_util.h
- prov/gni/src/gnix_fabric.c
- prov/udp/src/udpx_fabric.c
- prov/udp/src/udpx_init.c
- prov/util/src/util_attr.c
- prov/util/src/util_fabric.c
- prov/util/src/util_main.c
Also add some logging to fi_check_info
> util: Add getinfo, parsing and naming functions for layered providers

- config/cron-make-nightly-tarball.pl
Described in
http://lists.openfabrics.org/pipermail/ofiwg/2016-April/001159.html.
> cron-make-nightly-tarball: update www dir layout

- config/cron-make-nightly-tarball.pl
> configure.ac: remove debug print statements

- prov/verbs/src/ep_rdm/verbs_av_ep_rdm.c
Signed-off-by:Evgeny Leksikov <evgeny.leksikov@intel.com>
> verbs/RDM. Fix coverity issue CID (124952)

- include/rdma/fi_endpoint.h
- man/man3/fi_endpoint.3
Add fi_ep_alias, update man pages.
> Add fi_ep_alias

- prov/psm2/src/psmx2_domain.c
- prov/psm2/src/psmx2_fabric.c
> prov/psm2: update to new function names from the utility provider

- include/fi_enosys.h
- include/fi_util.h
- man/fi_cq.3.md
- prov/psm2/src/psmx2_fabric.c
- prov/psm2/src/psmx2_wait.c
- prov/udp/src/udpx_fabric.c
- prov/util/src/util_attr.c
- prov/util/src/util_eq.c
- prov/util/src/util_wait.c
- prov/verbs/src/verbs_eq.c
- src/enosys.c
Rename fi/util to ofi + misc fixes
> util: Fix layered getinfo to handle fi_info list

- prov/usnic/src/usdf_ep_dgram.c
- prov/usnic/src/usdf_ep_msg.c
- prov/usnic/src/usdf_ep_rdm.c
> usnic: Report 'usnic' as name field of domain attr.

- prov/usnic/src/usdf_cm.c
- prov/usnic/src/usdf_ep_msg.c
- prov/usnic/src/usdf_eq.c
- prov/usnic/src/usdf_pep.c
This set of commits fixes several problems with the CM data handling. 
@goodell @jsquyres
> usnic: Fixes to the CM handling

- prov/gni/Makefile.include
- prov/gni/include/gnix.h
- prov/gni/include/gnix_cntr.h
- prov/gni/include/gnix_ep.h
- prov/gni/include/gnix_freelist.h
- prov/gni/include/gnix_trigger.h
- prov/gni/include/gnix_vc.h
- prov/gni/src/gnix_atomic.c
- prov/gni/src/gnix_cntr.c
- prov/gni/src/gnix_ep.c
- prov/gni/src/gnix_freelist.c
- prov/gni/src/gnix_msg.c
- prov/gni/src/gnix_rma.c
- prov/gni/src/gnix_trigger.c
- prov/gni/src/gnix_vc.c
- prov/gni/test/cancel.c
- prov/gni/test/ep.c
- prov/gni/test/freelist.c
- prov/gni/test/rdm_dgram_rma.c
> prov/gni:implement triggered ops

- prov/sockets/src/sock_ep.c
Fixed a resource leak found by Coverity scan.
@jithinjosepkl @shefty 
> prov/sockets: Coverity scan fix

- prov/gni/src/gnix_vc.c
upstream merge ofi-cray/libfabric-cray#781
Fixes ofi-cray/libfabric-cray#780.
@sungeunchoi 
(cherry picked from commit ofi-cray/libfabric-cray@954607543d4fbe061924f52fc9bd29ababb7000c)
> prov/gni: Fix race in *_push_tx/work_reqs()

- prov/gni/include/gnix.h
- prov/gni/include/gnix_cntr.h
- prov/gni/include/gnix_cq.h
- prov/gni/include/gnix_nic.h
- prov/gni/include/gnix_util.h
- prov/gni/src/gnix_atomic.c
- prov/gni/src/gnix_cntr.c
- prov/gni/src/gnix_cq.c
- prov/gni/src/gnix_datagram.c
- prov/gni/src/gnix_dom.c
- prov/gni/src/gnix_ep.c
- prov/gni/src/gnix_mbox_allocator.c
- prov/gni/src/gnix_mr.c
- prov/gni/src/gnix_msg.c
- prov/gni/src/gnix_nic.c
- prov/gni/src/gnix_rma.c
- prov/gni/src/gnix_vc.c
Added conditional locking checks to the provider code.
upstream merge ofi-cray/libfabric-cray#776
@sungeunchoi 
(cherry picked from commit ofi-cray/libfabric-cray@d4db022618a2830eaf0e739835c41c58423cef19)
> prov/gni: Add FI_THREAD_COMPLETION support

- prov/gni/src/gnix_cq.c
- prov/gni/src/gnix_msg.c
- prov/gni/src/gnix_nic.c
- prov/gni/src/gnix_tags.c
- prov/gni/src/gnix_vc.c
in critical functions.
upstream merge of ofi-cray/libfabric-cray#810
@sungeunchoi 
(cherry picked from commit ofi_cray/libfabric-cray@f7ba2a18e76a9f379af814bfb9277440bf70b024)
> prov/gni: Changed GNIX_INFO to GNIX_DEBUG

- prov/sockets/include/sock.h
- prov/sockets/src/sock_conn.c
- prov/sockets/src/sock_ep.c
- prov/sockets/src/sock_ep_msg.c
- prov/sockets/src/sock_fabric.c
- Use new port for every msg-endpoint
- Donot reset CM thread on exit
> prov/sockets: Use new port for new msg-endpoints

- prov/sockets/src/sock_ep.c
- prov/sockets/src/sock_msg.c
-  Set op_flags correctly for recvs
> prov/sockets: Set op_flags correctly for recvs

- man/fi_endpoint.3.md
- man/man3/fi_endpoint.3
- prov/util/src/util_main.c
- Clarify fi_enable applies to active endpoint 
- Update fid_list_insert
> Updates to man page, util fid list

- prov/sockets/src/sock_atomic.c
- prov/sockets/src/sock_progress.c
When <code>FI_INJECT</code> is set as a flag in <code>fi_compare_atomic</code>, the compare data was not being copied to the internal buffer. This should fix #1959.
@jithinjosepkl
> prov/sockets: Fix compare buffer bug in fi_compare_atomic

- include/fi_util.h
- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_fabric.c
- prov/rxm/src/rxm_init.c
- prov/util/src/util_attr.c
Move code that can be shared to util provider. Rename
functions to agreed upon naming convention for layered
providers.
> util: Refactor layered provider code

- prov/gni/test/gnix_rdma_headers.h
@sungeunchoi 
not sure when this started, jenkins failures are somewhat confusing.
> prov/gni: fix some breakage in criterion

- prov/gni/src/gnix_nic.c
upstream merge of ofi-cray/libfabric-cray#822
@sungeunchoi 
(cherry picked from commit ofi-cray/libfabric-cray@6203e784e4c37c3bb7dcd5c5547eb69d91250b25)
> prov/gni: Grow vc_id_bitmap with vc_id_table.

- prov/verbs/src/ep_rdm/verbs_cq_ep_rdm.c
- prov/verbs/src/ep_rdm/verbs_rdm.h
- prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm_states.c
prov/verbs: add completion flags support for ep_rdm
@a-ilango
> prov/verbs: add completion flags support for ep_rdm

- prov/gni/Makefile.include
- prov/gni/test/vc_lookup.c
upstream merge of ofi-cray/libfabric-cray#821
@sungeunchoi 
(cherry picked from commit ofi-cray/libfabric-cray@0047214fbc3e371bca904865f52f2b8df560a17e)
> prov/gni: Add vc lookup perf test.

- libfabric.def
- libfabric.sln
- libfabric.vcxproj
- libfabric.vcxproj.filters
- added default solution file
- VS 2015 project file + VS filter file
project file is configured to use Intel compiler 13.0, applied 64-bit
arch only
Signed-off-by: Sergey Oblomov <sergey.oblomov@intel.com>
> added windows build files

- include/unix/osd.h
- include/windows/osd.h
- prov/sockets/src/sock_conn.c
- src/fabric.c
- src/windows/osd.c
- updated initialization of libfabric on windows platform
- added macro for OS specific init of libfabric core
- some fixes in windows code
Signed-off-by: Sergey Oblomov <sergey.oblomov@intel.com>
> updated initialization on windows

- configure.ac
Small fixes for `CFLAGS` and `CPPFLAGS` handling.
@jsquyres please review at your leisure
> miscellaneous configure fixes

- prov/gni/include/gnix.h
- prov/gni/include/gnix_vc.h
- prov/gni/include/gnix_vector.h
- prov/gni/src/gnix_ep.c
- prov/gni/src/gnix_vc.c
- prov/gni/src/gnix_vector.c
- prov/gni/test/av.c
- prov/gni/test/vc_lookup.c
Performance enhancements related to VC lookup.
@sungeunchoi 
upstream merge of ofi-cray/libfabric-cray#824   
> prov/gni: improvements to VC lookup

- prov/gni/src/gnix_mr_cache.c
with a single state variable
- Added simple functions for using and manipulating the bit flags
- Added a 'merged' bit to identify entries that have been coalesced
- Warn about unmapped pages only for entries that are merged
upstream merge of ofi-cray/libfabric-cray#836
(cherry picked from commit ofi-cray/libfabric-cray@70b30ffe36bd6e84eab0bf1b1a3fe60de4cc7634)
> prov/gni: Replaced MR cache entry flags and state

- prov/gni/configure.m4
Fix a problem with udreg related configury.
@charlesarcher
> prov/gni: fix a configure flub up with udreg

- prov/gni/src/gnix_mr.c
choices
@sungeunchoi 
upstream merge of ofi-cray/libfabric-cray#846
(cherry picked from commit ofi-cray/libfabric-cray@c69e47f96c8a5c6e48eb22e6cae50d927cce165b)
> prov/gni: Add UDREG to lazy dereg capable cache

- prov/sockets/src/sock_ep_msg.c
- Removed unused argument in <code>sock_release_shutdowns</code>
- Added a check to avoid sending <code>fi_shutdown</code> msg when <code>FI_SHUTDOWN</code> event is already received from the remote peer.
This should fix the Travis-CI failure in the fabtests PR 532.
@jithinjosepkl 
> prov/sockets: Don't send fi_shutdown msg when FI_SHUTDOWN event is already received

- prov/psm/src/psmx_cq.c
- prov/psm2/src/psmx2_cq.c
Re-arrange case statements so that common code can be shared for
closely related branches.
> prov/psm,psm2: Minor code tweak to reduce code duplication

- .travis.yml
> Enable dl builds for Travis.

- prov/gni/configure.m4
upstream merge of ofi-cray/libfabric-cray#851
@sungeunchoi 
(cherry picked from commit ofi-cray/libfabric-cray@5a47c4cbf0cd3b53b0331034143385adc6e705a9)
> prov/gni: more configury cleanup

- prov/gni/test/mr.c
Added additional suites to cover non-lazy cases
upstream merge ofi-cray/libfabric-cray#853
@sungeunchoi 
(cherry picked from commit ofi-cray/libfabric-cray@1fb9f242d6ee4d59cbaaf477f30dad3dbefe61ff)
> prov/gni: Extend MR tests to cover non-lazy-dereg

- prov/gni/test/mr.c
upstream merge of ofi-cray/libfabric-cray#858
@sungeunchoi 
(cherry picked from commit ofi-cray/libfabric-cray@4d3041e4dc67529c42438cef62244638399ca576)
> prov/gni: Fix the debug code in the mr tests

- prov/gni/test/tags.c
upstream merge of ofi-cray/libfabric-cray#855
(cherry picked from commit ofi-cray/libfabric-cray@267ba7711d8ccb3c39a5560360847ccc1c193a2b)
> prov/gni: Enable tag matcher hlist tests

- prov/gni/include/gnix.h
- prov/gni/include/gnix_atomic.h
- prov/gni/include/gnix_ep.h
- prov/gni/include/gnix_nic.h
- prov/gni/include/gnix_rma.h
- prov/gni/src/gnix_atomic.c
- prov/gni/src/gnix_ep.c
- prov/gni/src/gnix_fabric.c
- prov/gni/src/gnix_msg.c
- prov/gni/src/gnix_rma.c
- prov/gni/test/cntr.c
- prov/gni/test/rdm_atomic.c
- prov/gni/test/rdm_dgram_rma.c
Fixes ofi-cray/libfabric-cray#456.
@sungeunchoi 
(cherry picked from commit ofi-cray/libfabric-cray@06b7a5d1b5df4413975795841c0193d6754f6e1e)
> prov/gni: Implement FI_RMA_EVENT

- src/windows/osd.c
updated error handling in windows implementation of
fi_read_file function
Signed-off-by: soblomov <sergey.oblomov@intel.com>
> win: fi_read_file improved error handling

- prov/gni/include/gnix_util.h
- prov/gni/src/gnix_nic.c
- prov/gni/src/gnix_util.c
Fixes ofi-cray/libfabric-cray#868.
upstream merge of ofi-cray/libfabric-cray#873
@sungeunchoi 
(cherry picked from commit ofi-cray/libfabric-cray@24ac0033298ee8721339d7d3741697491ef67910)
> prov/gni: Dump GNI resource info on error

- README
- docs/windows.txt
described dependencies, limitations
> added windows specific docs

- prov/sockets/src/sock_progress.c
Restructure acquiring/releasing the list_lock, so that it is
only acquired once per iteration.  This also fixes a locking
issued reported by helgrind/valgrind
Replaces patch from PR ##2152 -- and let's hope that it doesn't break the provider.  :)
> socket: Optimize locking by progress thread

- prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm_states.c
There was wrong placement of user's data.
@a-ilango
> prov/verbs: fix buffered rma operations for ep_rdm.

- prov/sockets/include/sock.h
- prov/sockets/src/sock_conn.c
- prov/sockets/src/sock_ep.c
- prov/sockets/src/sock_ep_msg.c
Refactor MSG EP connection management
@shantonu
> prov/sockets: Refactor MSG-EP connection management

- prov/psm2/src/psmx2.h
- prov/psm2/src/psmx2_atomic.c
Together with the existing multi-iov support for send, tagged send,
rma write, and rma read, this makes the transmit side multi-iov
support complete.
> prov/psm2: Add multi-iov support for atomic operations

- src/windows/osd.c
updated error handling for windows implementation
of ofi_shm_map function to follow common code styling
> updated error handling for windows ofi_shm_map

- prov/sockets/src/sock_av.c
- prov/sockets/src/sock_ep_msg.c
- prov/sockets/src/sock_progress.c
- Coverity scan fixes
- Fix log level for a debug log entry.
> Pr/sockets: misc fixes

- prov/sockets/src/sock_ep_msg.c
- Fix couple of memory leaks from pthread_create. Added pthread_join to
handle these.
> prov/sockets: Fix couple of memory leaks in FI_EP_MSG

- prov/gni/test/av.c
Note that AV operations are not thread safe, so for these tests there
is a lock used around all the av operations that happen concurrently.
This lock should be removed when thread safety is added.
- mt_simple: concurrent insertions, followed by concurrent lookups, followed by concurrent removes
- mt_lookup: One thread continually does lookups, while another inserts and removes
- mt_insert_remove: N threads inserting while M threads removing
upstream merge of ofi-cray/libfabric-cray#867
@sungeunchoi 
(cherry picked from commit ofi-cray/libfabric-cray@ea7900ca85432110eafd4ce7e1f70bdb48e018b2)
> prov/gni: New mulththreaded av tests

- configure.ac
- include/fi.h
- include/fi_proto.h
- include/fi_util.h
- prov/sockets/include/sock.h
- prov/sockets/src/sock_ep.c
- prov/sockets/src/sock_fabric.c
- prov/util/src/util_av.c
- prov/util/src/util_cq.c
- src/common.c
- Minor updates to util-cq (default CQ size, fix bug in tagged-cq-read)
- Add new control packet types in fi_proto (NACK, DISCARD)
- Expose util-AV interface to report AV events
- Add util-function to get time in us
- Add util-function to get node name
> Misc. updates to common, util-prov

- man/fi_endpoint.3.md
> clarifications on FI_ORDER_NONE

- prov/sockets/src/sock_progress.c
- src/unix/osd.c
- common: Set size parameter for shared memory segment 
- prov/sockets: Set source-address for unexpected messages
> Bug fixes in common, sockets

- prov/verbs/src/fi_verbs.c
- prov/verbs/src/verbs_msg_ep.c
Add fi_getopt to passive EP ops.
> verbs: Fill source address in fi_info

- man/fi_rxd.7.md
- Add fi_rxd.7.md man page
- Fix formatting issues in fi_rxd.7
> prov/rxd: Add provider specific man page

- prov/gni/include/gnix_vector.h
- prov/gni/src/gnix_vector.c
- prov/gni/test/vector.c
Upstream merge of ofi-cray/libfabric-cray#887
@sungeunchoi
> prov/gni: Upstream merge pr887

- prov/rxm/Makefile.include
- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_attr.c
- prov/rxm/src/rxm_cq.c
- prov/rxm/src/rxm_domain.c
- prov/rxm/src/rxm_fabric.c
- prov/util/src/util_av.c
These set of patches updates the util code and adds domain and CQ features to rxm provider.
> Updates to util and rxm provider

- prov/gni/include/gnix_vector.h
- prov/gni/src/gnix_ep.c
- prov/gni/test/vector.c
upstream merge of ofi-cray/libfabric-cray#894
@sungeunchoi
> prov/gni: Fix bug in __gnix_ep_fini_vc

- prov/gni/src/gnix_mbox_allocator.c
With CLE 6.x, the entries in /proc/mounts can be quite
large.  Use the mntent interfaces to parse /proc/mounts
to avoid buffer overflows.
upstream merge of ofi-cray/libfabric-cray#899
(cherry picked from commit ofi-cray/libfabric-cray@2eff2d630c104364003fa5bb1614e57f37e2efc0)
> prov/gni: switch to using mntent interface

- config/cron-submit-coverity.pl
> coverity: update the coverity tool download URL

- prov/gni/src/gnix_msg.c
- prov/gni/src/gnix_nic.c
upstream merge of ofi-cray/libfabric-cray#897
@sungeunchoi
> prov/gni: fixes for iov_cnt > 1 send/recv

- prov/gni/test/rdm_rx_overrun.c
rdm_rx_overrun
We can run out of uGNI resources for an endpoint depending on the
processor type and/or arguments to the WLM.  Rather than failing the
test, just use as many endpoints as we can open.
upstream merge of ofi-cray/libfabric-cray#913
@sungeunchoi 
(cherry picked from commit ofi-cray/libfabric-cray@1d58f3c8a2e161749ceccaad184d07c2b7488e90)
> prov/gni: Use as many endpoints as we can open in

- prov/gni/include/fi_ext_gni.h
- prov/gni/src/gnix_dom.c
- prov/gni/src/gnix_xpmem.c
- prov/gni/test/dom.c
upstream merge of ofi-cray/libfabric-cray#898
@sungeunchoi 
(cherry picked from commit ofi-cray/libfabric@59bba0f8e39b511daecd1251000f22145e01a789)
(cherry picked from commit ofi-cray/libfabric@899d6c36d5f9f5ccec4cf2f3c743a53f6c61513f)
> prov/gni: add domain op for toggling xpmem on/off

- prov/gni/src/gnix_nameserver.c
endpoint initialization fails
upstream merge of ofi-cray/libfabric-cray#915
@sungeunchoi 
(cherry picked from commit ofi-cray/libfabric-cray@f56a687be01cba1a25c6aa94ab79ca92590192c8)
> prov/gni: fix addr resolution for gpu nodes

- man/fi_usnic.7.md
Document that resource management is not supported.
@goodell 
> usnic: Update provider man page.

- prov/util/src/util_mr.c
> util_mr: coverity scan fixes

- include/fi_proto.h
- include/fi_util.h
- prov/rxd/Makefile.include
- prov/rxd/src/rxd.h
- prov/rxd/src/rxd_attr.c
- prov/rxd/src/rxd_av.c
- prov/rxd/src/rxd_cq.c
- prov/rxd/src/rxd_domain.c
- prov/rxd/src/rxd_ep.c
- prov/rxd/src/rxd_rma.c
- prov/udp/src/udpx_cq.c
- prov/util/src/util_domain.c
- prov/rxd: Add RMA read-write functionality
- common/proto: Add message types for RMA operations
- prov/udp: Fix memory leaks in UDP CQ
- prov/rxd: Coverity scan fixes
> prov/rxd: Add RMA read-write functionality 

- .gitignore
> .gitignore: Add configure generated file

- man/fi_usnic.7.md
- prov/usnic/src/usdf.h
- prov/usnic/src/usdf_dgram.h
- prov/usnic/src/usdf_domain.c
- prov/usnic/src/usdf_ep_dgram.c
- prov/usnic/src/usdf_ep_msg.c
- prov/usnic/src/usdf_ep_rdm.c
- prov/usnic/src/usdf_fabric.c
- prov/usnic/src/usdf_msg.h
- prov/usnic/src/usdf_rdm.h
Fixes ofiwg/libfabric#2052
Signed-off-by: Pierre Roux <piroux@cisco.com>
> usnic: change of fabric/domain naming

- prov/gni/src/gnix_mr.c
registration
upstream merge of ofi-cray/libfabric-cray#929
@sungeunchoi 
(cherry picked from commit ofi-cray/libfabric-cray@ea64d25350540787fe57ce5b2b5b7d82de188381)
> prov/gni: resolved memory leak issues with basic memory registration

- prov/gni/src/gnix_vc.c
some open mpi tests revealed some problems with
the send to self path in the GNI provider.
@sungeunchoi 
upstream merge of ofi-cray/libfabric-cray#934
(cherry picked from commit ofi-cray/libfabric-cray@87c2d29c66f490af64295b83e46b4a8f8c2aacf8)
> prov/gni: fix some problems with send to self

- prov/verbs/src/ep_rdm/verbs_utils.c
- prov/verbs/src/verbs_av.c
Our internal Jenkins instance caught some possible bugs.
@evgeny-leksikov @a-ilango 
Could you verify that these changes are correct?
> verbs: Fix warnings.

- prov/verbs/src/ep_rdm/verbs_av_ep_rdm.c
- prov/verbs/src/ep_rdm/verbs_cq_ep_rdm.c
- prov/verbs/src/fi_verbs.c
- prov/verbs/src/verbs_domain.c
Bugfixes:
- fix Coverity issues
- fix cq_sreadfrom for ep rdm
- Fix overwrite of user's buffer if count > 1
- Fix possible user's buffer violation when count may be increased > threshold
@a-ilango , please review
> prov/verbs: ep rdm bugfixes

- prov/psm2/src/psmx2_cq.c
- prov/verbs/src/verbs_cq.c
- src/common.c
Here are some minor fixes for the psm2 and the verbs providers.
Thanks for your review,
Sylvain
> Some fixes for psm2 and verbs providers

- man/fi_pingpong.1.md
- util/pingpong.c
@jsquyres @goodell @shantonu @j-xiong 
> Update man page for fi_pingpong.

- man/fi_endpoint.3.md
- man/fi_verbs.7.md
- man/man3/fi_endpoint.3
- man/man7/fi_verbs.7
- prov/verbs/src/verbs_cm.c
- prov/verbs/src/verbs_msg_ep.c
They have been detected by lintian, the Debian package checker
> A few typo fixes

- include/fi_util.h
- prov/util/src/util_ep.c
> Added ep_close for utils provider

- man/fi_verbs.7.md
This PR fixes #2319.
@evgeny-leksikov you may want to prepare a PR for verbs/RDM specific man page updates.
> verbs: Fix man page to list unsupported features.

- prov/mxm/src/mlxm.h
- prov/mxm/src/mlxm_av.c
- prov/mxm/src/mlxm_domain.c
> MXM provider: Removed unnecessary variables, fixed minor issues.

- prov/psm/src/psmx_mr.c
- prov/psm2/src/psmx2_mr.c
> prov/psm,psm2: Remove some duplicated code

- prov/gni/src/gnix_av.c
Throughout most of the GNI provider code we use
XX_priv to show when we are using the provider
internal version of a libfabric object.  Make
gnix_av.c code consistent with that practice.
Upstream merge of ofi-cray/libfabric-cray#942
(cherry picked from commit ofi-cray/libfabric-cray@9511015210cf2db02b26c36a54b25d4672091def)
@hppritcha
> prov/gni: cosmetic name change

- util/pingpong.c
> util/pingpong.c: Fix errors on 32-bit systems.

- .travis.yml
> travis: ensure that we have good GNU Autotools

- prov/psm/src/psmx_cq.c
- prov/psm2/src/psmx2_cq.c
There is a corner case that fi_cq_readfrom needs to return 0 --
when the input count is 0 and the CQ is not empty. This is useful
as a progress call that also checks the CQ state: return value
-FI_EAGAIN or 0 indicates whether the CQ is empty or not. The util
poll function relies on such behavior.
The conditions for identifying the corner case was not exactly
right in the existing code. As the result 0 could be returned
incorrectly under rare cases when multithreading is enabeld. This
patch fixes the conditions.
> prov/psm,psm2: Fix the return value of fi_cq_readfrom

- Makefile.am
- util/pingpong.c
A few compatibility fixes for build issues on FreeBSD.
> FreeBSD compile fixes

- prov/rxd/src/rxd_attr.c
- prov/rxd/src/rxd_cq.c
- prov/util/src/util_mr.c
util_mr: Warning fixes for 32-bit build
prov/rxd: Warning fixes for 32-bit build
Fixes #2353, #2350, #2348
> util_mr, prov/rxd: 32bit build warning fixes

- NEWS.md
> NEWS: Update psm and psm2 provider notes for 1.4 release

- man/fi_domain.3.md
- prov/rxd/src/rxd_av.c
- prov/rxd/src/rxd_ep.c
- prov/sockets/src/sock_cntr.c
- prov/util/src/util_av.c
- prov/verbs/src/verbs_domain.c
- src/unix/osd.c
@jithinjosepkl @a-ilango - please confirm that the fixes are correct for your providers
> coverity fixes - util, rxd, sockets, verbs, osd

- NEWS.md
- man/fi_verbs.7.md
@a-ilango , @shefty please review
> prov/verbs: documentation update for EP_RDM (v1.4)

- include/freebsd/osd.h
> core: Fix compilation warnings for FreeBSD

- NEWS.md
> prov/sockets: Update NEWS.md for 1.4 release

- AUTHORS
> AUTHORS: Add missing patch authors

- prov/usnic/src/usdf_av.c
- prov/usnic/src/usdf_av.h
- prov/usnic/src/usdf_ep_dgram.c
- prov/usnic/src/usdf_ep_rdm.c
> prov/usnic: Miscellaneous AV fixes

- NEWS.md
> NEWS.md: 1.4 updates.

- util/info.c
- Use strcasecmp so lowercase values will also be accepted.
- Add error handling to parsing functions. If a token is not recognized,
then print a friendly error message and return -EINVAL. The program
will exit with exit code EINVAL.
Signed-off-by: Ben Turrubiates \<bturrubi@cisco.com\>
> util/info.c: Improve error handling.

- COPYING
- NEWS.md
- configure.ac
> release 1.4.0rc1

- prov/rxd/src/rxd_ep.c
> prov/rxd: Fix strict-aliasing warning

- prov/verbs/src/verbs_info.c
Contents:
- [Util] Add macros for accessing fields in sockaddr_in* structs
- Return all valid verbs interfaces on a system when user doesn't specify a node, or any addressing info and FI_SOURCE is passed.
- Fix incorrect reporting cq_size.
Update: Dropped patch 1 and 3 from this PR.
> verbs: Bug fixes

- include/fi_util.h
- prov/rxm/src/rxm_conn.c
- util: Fix CQ/EQ readerr macros
- rxm: Get cm_data size using fi_getopt before using it.
> rxm, util: bug fixes

- NEWS.md
@hppritcha 
Signed-off-by: Sung-Eun Choi <sungeun@cray.com>
> updates to 1.4 NEWS file for gni provider

- .travis.yml
> build: Cope with travis brew update failure

- prov/gni/src/gnix_ep.c
upstream merge of ofi-cray/libfabric-cray#980
yet another bug discovered by a user
@sungeunchoi 
(cherry picked from commit ofi-cray/libfabric-cray@c133c07fe07404cca8096b4c335669cd78a43e57)
> prov/gni: Fix error exit path for fi_endpoint

- NEWS.md
- man/fi_verbs.7.md
- Add clarification regarding fork usage
- Add supported environment variables
> verbs: man page updates

- prov/udp/src/udpx_init.c
If the node, service, and hints parameters are NULL, fi_getinfo
should return a list of available interfaces.  Adjust the UDP
provider to return a list of all IP addresses in the system.
> prov/udpx: Report all available interfaces from fi_getinfo

- README.md
> README: Add using fi_info as a quick validation test

- src/fabric.c
- src/var.c
- src/windows/osd.c
> fabric: Rename init variable

- prov/gni/include/gnix.h
- prov/gni/src/gnix_msg.c
- prov/gni/src/gnix_rma.c
fixes ofi-cray/libfabric-cray#968
@sungeunchoi 
(cherry picked from commit ofi-cray/libfabric-cray@4e51b64e605ce8401d450144bfb135a746ea09ed)
> prov/gni: address issue 968

- man/fi_cq.3.md
- man/man3/fi_cq.3
> fixed typo in CQ docs/man pages

- prov/gni/src/gnix_cm_nic.c
- prov/gni/src/gnix_vc.c
- prov/gni/test/vc.c
This commit fixes a few VC connect edge cases.  Intra-CM NIC connections are
now handled inside the connection manager.  Inside _gnix_cm_nic_send(), if it
is found that the connection is being established between two endpoints which
shared the same CM NIC, the datagram exchange is skipped.  Connection data is
simply copied to the datagram out buffer to simulate a datagram exchange.
Handling data movement in the connection manager fixes a locking issue in
__gnix_vc_connect_to_same_cm_nic() where two EP VC locks could not be held at
the same time.  Refactoring intra-CM NIC connect eliminates another issue with
incorrect address to EP VC lookup.  Moving intra-CM NIC connection setup into
the connection manager also simplifies the true connect to self case.  Tests
were added to verify correct …
> prov/gni: Fix connect to self

- man/fi_usnic.7.md
- prov/usnic/src/fi_ext_usnic.h
The introduction of version 2 of the fi_usnic_info extension caused a
compatibility issue with older versions of the extension. This commit
adds padding to the structure to explicitly maintain the alignment
requirements for the extension in the 1.3 release. Also, mark the outer
structure as having the packed attribute.
Relevant documents have been updated to document the issue and recommend
possible solutions.
Fixes #2454 
> usnic: Explicitly pad the fi_usnic_info struct.

- prov/gni/src/gnix_atomic.c
- prov/gni/test/rdm_atomic.c
upstream merge of ofi-cray/libfabric-cray#986
@sungeunchoi 
(cherry picked from commit ofi-cray/libfabric-cray@0ff5039c8231e442c1262dda346440ea5fc2b013)
> prov/gni: Fix counters for AXOR

- prov/rxd/src/rxd_attr.c
- prov/rxd/src/rxd_av.c
- prov/rxd/src/rxd_cq.c
- prov/util/src/util_attr.c
- prov/rxd: Update rxd provider capabilities, bug fixes in AV
- prov/util - Invoke alter_info in ofix_getinfo to set caps/flags
> rxd, util: Minor bug fixes

- man/fi_atomic.3.md
- man/fi_cq.3.md
- man/fi_getinfo.3.md
> man/cq: Clarify when len field is valid

- man/fi_rma.3.md
Signed-off-by: Erik Paulson <erik.r.paulson@intel.com>
> Fix typo in fi_rma.3.md

- prov/verbs/src/verbs_info.c
Split up too long function + fix coverity issue #138023
Applying comments in PR https://github.com/ofiwg/libfabric/pull/2481
@shefty @a-ilango
> prov/verbs: refactoring of remove nonaddr fi_info

- configure.ac
> configure: make a final rc: 1.4.0rc3

- configure.ac
> configure.ac: bump to v1.4.0

- configure.ac
> configure.ac: bump to 1.5.0a1

- prov/gni/src/gnix_util.c
per node in CCM mode
CCM under PBS is a little squirrely, so use the PBS_NODEFILE for
figuring out the number of PEs per node.
upstream merge of ofi-cray/libfabric-cray#1008
@sungeunchoi 
(cherry picked from commit ofi-cray/libfabric-cray@ffd6aa841c39f941ebbdb0ba037e0b71b81fc812)
> prov/gni: Use PBS_NODEFILE for determining PEs

- prov/gni/test/rdm_sr.c
Handle out-of-order return of RX CQEs.
@sungeunchoi 
upstream merge of ofi-cray/libfabric-cray#1016
(cherry picked from commit ofi-cray/libfabric-cray@1ddc767fd6e9dcacd975a82c484b2c526a68d582)
> prov/gni: improve multirecv criterion tests

- Makefile.am
- include/fi_iov.h
- include/fi_mem.h
- prov/rxd/src/rxd.h
- prov/rxd/src/rxd_cq.c
- prov/rxd/src/rxd_ep.c
- prov/util/src/util_buf.c
- src/iov.c
- Add a get context function to util buf pool
- Move the function to copy data to and from iov to common code after simplifying it a bit.
- Move function to get iov buf size to common code.
> Updates to util and common code

- src/enosys.c
> enosys: add a couple no CQ functions

- prov/gni/test/cm.c
Also change output to debug output and add curly braces around
conditionals with only debug printfs.
upstream merge of ofi-cray/libfabric-cray#1059
@sungeunchoi 
(cherry picked from commit ofi-cray/libfabric-cray@eec6be8efa90186dedd2ed18d766fc7c9ff60762)
> prov/gni: Disable cm test

- Makefile.am
- configure.ac
- include/prov.h
- include/rdma/fabric.h
- man/fi_mlx.7.md
- man/man7/fi_mlx.7
- prov/mlx/Makefile.include
- prov/mlx/configure.m4
- prov/mlx/src/mlx.h
- prov/mlx/src/mlx_av.c
- prov/mlx/src/mlx_callbacks.c
- prov/mlx/src/mlx_cm.c
- prov/mlx/src/mlx_cq.c
- prov/mlx/src/mlx_domain.c
- prov/mlx/src/mlx_ep.c
- prov/mlx/src/mlx_fabric.c
- prov/mlx/src/mlx_init.c
- prov/mlx/src/mlx_tagged.c
- prov/util/src/util_attr.c
- src/fabric.c
- src/fi_tostr.c
> MLX provider.

- include/unix/osd.h
- include/windows/osd.h
- prov/sockets/src/sock_comm.c
- prov/sockets/src/sock_cq.c
- prov/sockets/src/sock_ep_msg.c
- prov/sockets/src/sock_progress.c
Hi,
I recently started testing Libfabric with the socket providers, where I figured out some minor bugs.
Some patches also aim at improving the disconnection process and the cancellation of outstanding network messages.
Thank you for your time reviewing the patches.
Sylvain
> prov/sockets: Bug fixing and disconnection improvement

- prov/gni/include/gnix_cm.h
- prov/gni/src/gnix_cm.c
- prov/gni/src/gnix_ep.c
- prov/gni/test/cm.c
- prov/gni/test/ep.c
upstream merge of ofi-cray/libfabric-cray#1079
@sungeunchoi 
Signed-off-by: Zach <ztiffany@cray.com>
(cherry picked from commit ofi-cray/libfabric-cray@82386338dbae31c8e62ddffbcceeba2918d60c9b)
> prov/gni: implement MSG EP CM data

- .travis.yml
See if we can catch new warnings.
Testing Travis.  Do not merge.
> travis: a bunch of updates, including a -Werror build

- index.md
> index: Update public web page to reflect current support

- prov/gni/src/gnix_mr.c
- prov/gni/test/mr.c
In a multi-threaded environment, it is possible that the NIC which
was allocated for the MR would not be the NIC picked by the memory
registration subsystem. To fix this, the NIC reference is taken later
during the registration step.
upstream merge of ofi-cray/libfabric-cray#1103
@sungeunchoi 
(cherry picked from commit ofi-cray/libfabric-cray@7b6c0db24546805baee517de20247072631e4d8c)
> prov/gni: Fix NIC reference issue on MR

- prov/gni/src/gnix_mr.c
In the memory registration code, the NIC list was being walked without
the NIC list lock held. This patch acquires the lock prior to walking the list.
upstream merge of ofi-cray/libfabric-cray#1104
@sungeunchoi 
(cherry picked from commit ofi-cray/libfabric-cray@ac5cae54ddfe3daab540db8fb4c32e690c2d2aba)
> prov/gni: Add NIC list lock to mem reg path

- prov/verbs/src/ep_rdm/verbs_rdm_cm.c
- prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm.c
fix prepost recv size & out-of-order clarification comment
@a-ilango @hoopoepg @shefty please review
> prov/verbs: fix prepost recv size

- prov/gni/src/gnix_sep.c
- prov/gni/test/sep.c
Fixes ofi-cray/libfabric-cray#1072
upstream merge of ofi-cray/libfabric-cray#1108
@sungeunchoi 
(cherry picked from commit ofi-cray/libfabric-cray@440b988d0a8b8ece873aa62a9f9a177fb180322a)
> prov/gni: Add tagged message support for scalable endpoints

- index.md
> Add link to developer's guide in development

- man/fi_endpoint.3.md
Addresses my confusion in #2634 and #2635 
Signed-off-by: Sung-Eun Choi <sungeun@cray.com>
> man: Clarify man page documentation on tx and rx contexts

- prov/gni/src/gnix_rma.c
- prov/gni/test/rdm_dgram_rma.c
upstream merge of ofi-cray/libfabric-cray#1106
@sungeunchoi 
Signed-off-by: Amith Abraham <aabraham@cray.com>
(cherry picked from commit ofi-cray/libfabric-cray@2945c89d07b0770a6eda200e50aef83f58367d08)
> prov/gni: FI_MORE support for read_msg

- prov/gni/test/rdm_sr.c
- Change existing multirecv tests to be able to receive messages from
more than one endpoint.  This currently does not work (issue #1116),
so leave the number of endpoints at 2.
- Change the tests to be able to send more than 3 messages.
- Rename multirecv2 to multirecv_send_first
- Add a test that overflows the multirecv buffer and thus gets
truncated.  This test is currently disabled, because we do not
generate a CQ error in this case (issue #1119).  Also, there's some
question about how to handle the case when FI_OPT_MIN_MULTI_RECV is
set to 0 (issue ofi-cray/libfabric-cray#1120).
upstream merge of ofi-cray/libfabric-cray#1121
@sungeunchoi 
(cherry picked from commit …
> prov/gni: Updates to multirecv tests

- man/man7/fi_gni.7
fixes ofi-cray/libfabric-cray#1112
upstream merge of ofi-cray/libfabric-cray#1122
@sungeunchoi 
(cherry picked from commit ofi-cray/libfabric-cray@9660ba006981d38d2f09081fdfbf6144ef9945a3)
> prov/gni: Update man page for scalable ep

- man/fi_cq.3.md
> man/cq: Fix typo in RMA completion description

- prov/psm/src/psmx.h
- prov/psm/src/psmx_av.c
- prov/psm/src/psmx_cntr.c
- prov/psm/src/psmx_ep.c
- prov/psm/src/psmx_init.c
- prov/psm2/src/psmx2.h
- prov/psm2/src/psmx2_av.c
- prov/psm2/src/psmx2_cntr.c
- prov/psm2/src/psmx2_cq.c
- prov/psm2/src/psmx2_ep.c
- prov/psm2/src/psmx2_init.c
- prov/psm2/src/psmx2_tagged.c
> prov/psm,psm2: ABI 1.1 related updates

- prov/gni/src/gnix_rma.c
fi_more list
fixes ofi-cray/libfabric-cray#1074
upstream merge of ofi-cray/libfabric-cray#1144
@sungeunchoi 
Signed-off-by: Amith Abraham <aabraham@cray.com>
(cherry picked from commit ofi-cray/libfabric-cray@d355eb5280b33af34a78005290507b7f3fad73e4)
> prov/gni: Disallow fi_fence reqs to be added to

- man/fi_domain.3.md
Make the RM table more precise and helpful to apps.  Remove
'buffered' entries, as internal buffering is hidden from the app.
Clarify if an error is detected by the provider or must be
avoided by the application.
Fixes #2643
@jsquyres - I forgot to push these changes out until now.
> man/domain: Update resource mgmt table

- prov/verbs/src/verbs_info.c
on systems where multiple network interfaces configured
user may specify preferrable interface to be used by provider
this is additional fix for
https://github.com/ofiwg/libfabric/pull/2665
> prov/verbs: added iface-name filtering

- prov/gni/src/gnix_sep.c
- prov/gni/test/sep.c
fixes ofi-cray/libfabric-cray#1139
upstream merge of ofi-cray/libfabric-cray#1143
@sungeunchoi 
please go ahead and merge
(cherry picked from commit ofi-cray/libfabric-cray@0e21d0f1ea97d7d08599f34712fb504669803f93)
> prov/gni: Check for open contexts on close of sep

- prov/gni/src/gnix_rma.c
message
fixes ofi-cray/libfabric-cray#1157
upstream merge of ofi-cray/libfabric-cray#1168
@sungeunchoi 
(cherry picked from commit ofi-cray/libfabric-cray@231e41e289659287afed60e7a75cccff85c8c45f)
> prov/gni: fix missing format specifier in info

- prov/usnic/Makefile.include
- prov/usnic/configure.m4
- prov/usnic/src/usdf_fabric.c
- prov/usnic/src/usnic_direct/usd_device.c
- prov/usnic/src/usnic_direct/usd_event.c
- prov/usnic/src/usnic_direct/usd_ib_cmd.c
- prov/usnic/src/usnic_direct/usd_ib_sysfs.c
- prov/usnic/src/usnic_direct/usnic_ib_abi.h
- prov/verbs/src/fi_verbs.h
> v1.4.1 usnic fixes

- NEWS.md
> NEWS.md: Update 1.4.1 release notes for the psm and psm2 providers

- NEWS.md
- prov/udp/src/udpx_attr.c
- prov/udp/src/udpx_init.c
> prov/udp: Add fix setting addr_format field

- prov/usnic/configure.m4
> usnic: fix broken test to see if we need -libverbs

- prov/gni/include/gnix_ep.h
upstream merge of ofi-cray/libfabric-cray#1182
@sungeunchoi 
(cherry picked from commit ofi-cray/libfabric-cray@9f927b40d773a3b909dba0eff43b8ef3f2a75d7c)
> prov/gni: gnix_pep_bind prototypes match in headers.

- prov/gni/src/gnix_rma.c
- prov/gni/src/gnix_vc.c
- prov/gni/test/rdm_dgram_rma.c
fi_more would not work with mixed transaction types since
the handling was all in gnix_rma.c. By adding these checks
in gnix_vc_queue_tx_req we can handle any outstanding
fi_more chains when we have mixed transaction types.
Fixes ofi-cray/libfabric-cray#1142
upstream merge of ofi-cray/libfabric-cray#1181
(cherry picked from commit ofi-cray/libfabric-cray@9bf9bbcd1b2ef926f0b9198f74c629b64e9ffc6c)
> prov/gni: Fix FI_MORE w/ mixed transaction types

- prov/bgq/src/fi_bgq_domain.c
- prov/rxd/src/rxd_attr.c
- prov/rxm/src/rxm_attr.c
- prov/sockets/include/sock.h
- prov/sockets/src/sock_cntr.c
- prov/sockets/src/sock_dom.c
- prov/sockets/src/sock_ep.c
- prov/sockets/src/sock_progress.c
- prov/verbs/src/ep_rdm/verbs_rdm_cntr.c
- prov/verbs/src/verbs_info.c
- src/fabric.c
Update socket and verbs providers to support new counter functions.
Update providers to initialize domain::mr_iov_count.
@pkcoff @a-ilango @gladkovdmitry17
> Update providers for counter and mr_iov_count API changes

- prov/gni/src/gnix_cm.c
Use strerror in FI_EP_MSG connection setup in GNI provider
to help with debugging.  This is more useful than just printing
error return code.
upstream merge of ofi-cray/libfabric-cray#1201
(cherry picked from commit ofi-cray/libfabri-cray@b60008f4425397e1973ab31afbae219b2f276189)
> prov/gni: improve some warn statements

- man/fi_eq.3.md
This has a dependency on the definitions introduced in PR #2729
> man/eq: Document EQ data structure fields

- prov/sockets/src/sock_dom.c
* Fixed: will call `sock_dom_add_to_list` for successfully created domains
* Fixed: error handling and resource finalization
> prov/sockets: misinterpreted the return value of ofi_mr_map_init

- man/man7/fi_gni.7
fixes ofi-cray/libfabric-cray#1113
upstream merge of ofi-cray/libfabric-cray#1233
bot:notest
Signed-off-by: Amith Abraham <aabraham@cray.com>
(cherry picked from commit ofi-cray/libfabric-cray@d14d7cb9ba73a3e9cd7a1c7417f3be2070c0688e)
> prov/gni:Update Man page to include FI_MORE for rma

- prov/gni/src/gnix_sep.c
ep_table and release the associated av
Not removing closed contexts from the ep_table results in a read from
the previously freed ep struct associated with the context during sep
close.
upstream merge ofi-cray/libfabric-cray#1257
(cherry picked from commit ofi-crya/libfabric-cray@51d210e058728f8c5072bb7278325089b277b6b4)
> prov/gni: Remove closed contexts from sep's

- prov/gni/test/allocator.c
- prov/gni/test/api.c
- prov/gni/test/api_cntr.c
- prov/gni/test/api_cq.c
- prov/gni/test/av.c
- prov/gni/test/cancel.c
- prov/gni/test/cm.c
- prov/gni/test/cntr.c
- prov/gni/test/cq.c
- prov/gni/test/datagram.c
- prov/gni/test/dom.c
- prov/gni/test/ep.c
- prov/gni/test/eq.c
- prov/gni/test/mr.c
- prov/gni/test/mr_notifier.c
- prov/gni/test/nic.c
- prov/gni/test/rdm_atomic.c
- prov/gni/test/rdm_dgram_rma.c
- prov/gni/test/rdm_dgram_stx.c
- prov/gni/test/rdm_fi_pcd_trecv_msg.c
- prov/gni/test/rdm_rx_overrun.c
- prov/gni/test/rdm_sr.c
- prov/gni/test/rdm_tagged_sr.c
- prov/gni/test/sep.c
- prov/gni/test/tags.c
- prov/gni/test/vc.c
- prov/gni/test/vc_lookup.c
- prov/gni/test/wait.c
upstream merge of ofi-cray/libfabric-cray#1252
fixes ofi-cray/libfabric-cray#1250
(cherry picked from commit ofi-cray/libfabric-cray@ee3ac19ee7e3c4871abfa633a759a017159e3c09)
> prov/gni: Update tests to use latest version

- prov/psm2/src/psmx2_init.c
The initialization code checks the existence of /dev/hfi1_0 before calling
psm2_ep_num_devunits() to avoid a 15 second delay. However, the hfi1 devices
don't necessarily appear consecutively so it is more appropriate to check
all possible device names before returning "no device found" error.
> prov/psm2: Improve the method of checking device existence

- prov/gni/src/gnix_mr.c
upstream merge of ofi-cray/libfabric-cray#1248
(cherry picked from commit ofi-cray/libfabric-cray@38d713d327d13ae10811032a452be8632a63cf8e)
> prov/gni: white space cleanup

- prov/util/src/util_cq.c
Commit https://github.com/ofiwg/libfabric/commit/9a39e432ac0b1ba346671ed9c45eca42ca194d1e enables app to pass a buffer to the provider to store cq error
data. Update ofi_cq_readerr to handle this.
Compile tested.
> util: Handle err_data in ofi_cq_readerr

- prov/gni/src/gnix_fabric.c
Also fix up comments in places where we might need to do a version check.
upstream merge of ofi-cray/libfabric-cray#1274
(cherry picked from commit ofi-cray/libfabric-cray@9f6e7a3814799a598efbec97da982d67fdb1f39c)
> prov/gni: Check for NULL hints before dereferencing for addr_format.

- prov/verbs/src/verbs_info.c
- prov/verbs: Refactor source addr filling in fi_info
Edit: updated verbs patch description, removed util provider update.
> prov/verbs: Refactor source addr filling in fi_info

- prov/gni/src/gnix_util.c
fixes ofi-cray/libfabric-cray#1057
upstream merge of ofi-cray/libfabric-cray#1263
(cherry picked from commit ofi-cray/libfabric-cray@b75e7315fe2875df89f2eb02ce8c1af162dd03eb)
> prov/gni: clean up gni resource dump

- include/fi_util.h
- prov/udp/src/udpx_ep.c
- prov/util/src/util_av.c
- prov/util/src/util_cq.c
- prov/util/src/util_domain.c
- prov/util/src/util_main.c
- util/info.c
- Update info.c to support all modes
- Correct match function for util_find_domain
- Store mr_mode bits with util_domain
> Updates to util code, info.c

- man/fi_tagged.3.md
> man: minor fix to trailing sentence

- prov/gni/src/gnix_vc.c
testing with Sandia SHMEM(SOS) revealed a problem with setting
peer_caps.  The SOS use of atomics and short puts revealed
a race condition when using FI_PROGRESS_AUTO in setting the peer
caps in the vc structure.
upstream merge of ofi-cray/libfabric-cray#1239
(cherry picked from commit ofi-cray/libfabric-cray@b33932be4b249a504272bb94c9f48eaca7c12873)
> prov/gni: fix race condition for peer_caps

- prov/util/src/util_av.c
- The previous implementation didn't pass the right field to inet_ntop
for retrieving the address.
- Print port in host order.
@shefty noticed this while doing some testing.
> util: Fix ip_av_straddr function.

- prov/gni/src/gnix_vc.c
upstream merge of ofi-cray/libfabric-cray#1268
(cherry picked from commit ofi-cray/libfabric-cray@d7748773675ca120d97878bd7012ff004746efcb)
> prov/gni: Minor comment fixes.

- prov/gni/test/api.c
upstream merge of ofi-cray/libfabric-cray#1275
(cherry picked from commit ofi-cray/libfabric-cray@8976e9ee07a20123bbc2f2baacfc0162f15f7afc)
> prov/gni: Added null hints test.

- prov/psm2/src/psmx2_cq.c
> prov/psm2: Fix another bug related to FI_SOURCE error reporting

- prov/gni/test/fi_addr_str.c
- Close counters before tx/rx eps and cqs.
- Removed fi_open_ops, it's not being used.
- Close peps.
- Free sep tx/rx cq's and ep's.
upstream merge of ofi-cray/libfabric-cray#1295
(cherry picked from commit ofi-cray/libfabric-cray@23dc4ad5e8605244921f6fbeebdd6d4caa4909bb)
> prov/gni: Fix valgrind errors.

- prov/gni/test/api.c
upstream merge of ofi-cray/libfabric-cray#1283
(cherry picked from commit ofi-cray/libfabric-cray@8ecab146de3053d39c8a0f0963154ffb87f2cb5e)
Conflicts:
prov/gni/test/api.c
> prov/gni: Do a noop for setup and teardown for null hints.

- man/fi_msg.3.md
Signed-off-by: Jason Godfrey <godfrey@cray.com>
> Clarify fi_send man page language.

- src/fabric.c
Move/enhance check that the provider has registered correctly.
> Add API version check against provider's supported version

- include/fi_util.h
- prov/util/src/util_fabric.c
- prov/util/src/util_main.c
- src/fabric.c
Manual merge of PR #2872 as well, due to conflicts.
> Updates to handle util providers in fi_getinfo

- prov/gni/src/gnix_msg.c
Plug a resource leak (GNI memory registration resources)
when using XPMEM transfer for cases where iov_cnt is > 1
on the receive side.
Fixes ofi-cray/libfabric-cray#1215
upstream merge of ofi-cray/libfabric-cray#1308
(cherry picked from commit ofi-cray/libfabric-cray@173dfdeb4534b90e4491e47d267b73149757655f)
> prov/gni: fix a problem with iov on receive side

- prov/gni/test/cntr.c
- Add multiple domains (plus avs and addrs)
- Refactor set up and test code for more shared usage
- Add NUM_THREADS (rather than using NUM_EPS)
upstream merge of ofi-cray/libfabric-cray#1318
(cherry picked from commit ofi-cray/libfabric-cray@b0cfe5b426f1d87cfa6fcf9420d5bed4d0c083b9)
> prov/gni: Use multiple domains for counter tests

- prov/gni/src/gnix_vc.c
In its usual fashion SOS seems to be really good
at rooting out bugs.  Turns out there are certain
shmem_putmem/quiet call patterns that could cause the GNI provider
to get stuck in an infinite loop, endlessly trying to
progress vc's without ever breaking out to recover more
TXs.
Fixes ofi-cray/libfabric-cray#1314
usptream merge of ofi-cray/libfabric-cray#1315
(cherry picked from commit ofi-cray/libfabric-cray@01ef1de043ad6bfe7b30d80706bfcdae5ced4353)
> prov/gni: swat a bug revealed with SOS testing

- prov/gni/test/allocator.c
Turns out that on production systems like NERSC edison,
it can be difficult to assemble large (128 MB and greater)
page sizes reliably.  This was causing periodic failure
of criterion test runs, and thus spurious failures in
CI testing.
This commit adds a "may_fail" argument to the mbox allocator
routine in the test.  If the mbox allocator returns -FI_ENOMEM,
don't treat as an error for these large page size requests.
upstream merge of ofi-cray/libfabric-cray#1317
(cherry picked from commit ofi-cray/libfabric-cray@bda6adbcf2f5626fcd4055bb65b18847e60822eb)
> prov/gni: adjust mbox_allocator criterion test

- include/fi.h
- include/fi_mem.h
- include/unix/osd.h
- include/windows/osd.h
- include/windows/pthread.h
- include/windows/sys/mman.h
- src/fabric.c
- src/log.c
Cherry picking commits that are good to go.
> Manual merge of commits from PR #2885 

- prov/gni/src/gnix_fabric.c
MPICH/CH4 testing revealed a bug in the caps field
in the returned info struct from fi_getinfo.  It
turned out that if the user had not supplied a
hints argument, GNI provider would just return 0 for
capabilities.  This got the MPICH/CH4 confused and
it would also devolve to the sockets provider,
or abort if the gni provider was explicitely selected.
upstream merge of ofi-cray/libfabric-cray#1327
(cherry picked from commit ofi-cray/libfabric-cray@5dc1b75979a65130982b14914df6dfab659fbb3d)
> prov/gni: fix returned caps field in info struct

- prov/mlx/src/mlx_callbacks.c
Fixed missed lock issue in recv-callback
> OFI/MLX: Fixed missed lock.

- prov/gni/src/gnix_hashtable.c
- prov/gni/src/gnix_mr_cache.c
> prov/gni: change 32-bit atomic addition to subtraction

- src/fabric.c
Update the fi_dupinfo and fi_freeinfo to handle copying
and freeing authorization keys.
> fabric: Add auth_key handling to dup/free info calls
