ofiwg/libfabric

prov/verbs/src/verbs_cm_xrc.c
prov/verbs/src/verbs_domain_xrc.c
prov/verbs/src/verbs_ep.c
prov/verbs/src/verbs_eq.c

Enable releasing of the H/W resources used to reserve unique QP numbers
during RDMA CM connection setup of XRC shared connections. Since the
RDMA CM is used for connection setup only, the associated RDMA CM ids
are disconnected and the QP that were reserved and in the INIT state are
destroyed.
With this change the number of QP context in use matches the number of
physical QP connections required for XRC; for all-to-all connectivity:
For XRC: number QP = (N - 1) x PPN x 2.
For RC: number QP = (N - 1) x PPN x PPN.

prov/verbs: Release XRC shared connection setup resources once connected

---

prov/gni/src/gnix_av.c
prov/gni/test/av.c

argument.  Return -FI_EINVAL if that arg is null.

prov/gni: for AV MAP type, check for NULL fi_addr

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c
prov/verbs/src/verbs_domain.c

This PR adds patches to exchange peer RX queue size information during connection establishment and use it to limit outstanding rendezvous tx requests to limit memory usage at the peer.
Edit: added a minor patch that adds qib (psm verbs) to the list of fabric that would need tx credits monitoring.

prov/rxm: limit outstanding rendezvous protocol requests

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c

The changes break IMB-EXT test. Reverting them for now.

[v1.7.x] revert commits that limit outstanding rndv tx ops

---

prov/rxm/src/rxm_cq.c

For non-segmented messages, the code path for claiming buffered receives
is different from regular receives and completions are always generated
there.  However, for segmented messages, the code to finishes the receive
is the same for buffered receives and regular receives and completion
generation depends on the FI_COMPLETION flag.
Add additional check to the finishing code so that completions are always
generated when buffered messages are claimed.

prov/rxm: Ensure completion generation when claiming buffered messages

---

prov/verbs/src/fi_verbs.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_domain.c

Ideally, fi_ibv_mem_notifier should be freed when all verbs domains that use it
are closed. In case this doesn't happen we have to unset the alloc, free hooks
set by fi_ibv_mem_notifier_init. Otherwise bad things would happen.

prov/verbs: check and free fi_ibv_mem_notifier on provider cleanup

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_cq.c

In regular receive mode, multiple segments of a single message either
go to the same matching receive entry (if already posted) or go to the
unexpected message queue, where they will all be processed when a
matching receive is posted.
In buffered receive mode, the first segment creates a completion event
and a receive entry is only created when the message is claimed. There
is no problem if the follow-up segments arrive after the message has
been claimed. However, if any of the segments arrives before the message
is claimed, it won't match any receive entry and will be treated in the
same way as the first segment, causing application error.
This patch fixes the issue associated with the buffered receive mode.
A deferred message queue is used to queue up follow-up message segments
before …

prov/rxm: Handle segments ordering in buffered receive mode

---

prov/verbs/src/fi_verbs.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_domain.c

Ideally, fi_ibv_mem_notifier should be freed when all verbs domains that use it
are closed. In case this doesn't happen we have to unset the alloc, free hooks
set by fi_ibv_mem_notifier_init. Otherwise bad things would happen.

[v1.7.x] prov/verbs: check and free fi_ibv_mem_notifier on provider cleanup

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_init.c

prov/rxm: Allow data FI_PROGRESS_AUTO with FI_ATOMIC capability
Enable the RXM emulated FI_ATOMIC protocol to support one-sided
use cases where the target of the atomics is using data FI_PROGRESS_AUTO,
and is not calling into the API to make progress.
This will promote the domain threading to FI_THREAD_SAFE to protect
CQ resources shared between the application and auto progress thread.
To reduce EQ/CQ progress overhead, a unique processing loop is used
to implement auto progress of only the EQ prior to the CQ being bound
to the EP.

prov/rxm: Allow data FI_PROGRESS_AUTO with FI_ATOMIC capability

---

prov/verbs/src/fi_verbs.c

XRC send side QP do not have responder logic, so avoid
attempting to set the minimum RNR NAK timer that should
be returned. It continues to be set for XRC receive QP.

prov/verbs: Do not update min RNR timer on XRC initiator QP

---

prov/verbs/src/fi_verbs.c

XRC send side QP do not have responder logic, so avoid attempting
to set the minimum RNR NAK timer that should be returned. It
continues to be set for XRC receive QP.

[v1.7.x] prov/verbs: Do not update min RNR timer on XRC initiator QP

---

prov/rxm/src/rxm_cq.c

rxm_ep_do_progress() processes eq and then posts available recieve
buffers associated with particular msg ep. After eq processing it's
possible that repost list may include buffers binded to closed msg ep.
Then, rxm ep try to post recieve operation for this msg ep and it
results in segfault.
This commit fixes this issue.
Signed-off-by: Mikhail Khalilov <mikhail.khalilov@intel.com>

prov/rxm: discard rx buffer prepost when msg ep closed.

---

prov/mrail/src/mrail_domain.c

Plus minor coding style cleanup of mrail_mr_reg() to make them consistent.

prov/mrail: Support fi_mr_regv() and fi_mr_regattr()

---

prov/tcp/src/tcpx_msg.c
prov/tcp/src/tcpx_progress.c
prov/tcp/src/tcpx_rma.c

1) removed unnecessary FI_COMPLETION flag manipulation in case of transmit & delivery complete semantic
2) fix transmit and delivery complete handling for send, sendv and senddata calls.

prov/tcp: op flags handling fixes.

---

prov/mrail/src/mrail_av.c

prov/mrail: Add missing copyright header

---

prov/rxm/src/rxm_conn.c

Peer ECONNREUSED errors are expected events, do not log
these as EQ error warnings.
When reading the MSG_EP EQ error the size returned from
fi_eq_readerr is checked. Although it should not happen, make
sure an error is returned if a mismatch in size is detected so
the contents of the error entry will not be used.

prov/rxm: MSG_EP rejects are expected, reduce logging severity

---

include/linux/osd.h
include/osx/osd.h
include/windows/osd.h
man/fi_verbs.7.md
prov/verbs/src/fi_verbs.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_info.c

Memory registration can fail with libibverbs when hugepages are
available and application fork support is enabled. In multi-model
applications, libfabric cannot guarantee the correct ordering of
calls to ibv_fork_init with the correct environment settings. To
address both of these problems, the verbs provider does not set any
environment variables related to fork and hugepage safety.
closes #4969

verbs,ofi_rxm: check hugepages when fork enabled

---

prov/tcp/src/tcpx.h
prov/tcp/src/tcpx_ep.c
prov/tcp/src/tcpx_init.c

Added options `FI_TCP_PORT_HIGH_RANGE`  and `FI_TCP_PORT_LOW_RANGE` in tcp provider in order to use a specific range of ports for launching applications.

prov/tcp: adding a port_range variables

---

fabtests/test_configs/ofi_rxd/ofi_rxd.exclude
include/ofi_list.h
prov/rxd/src/rxd.h
prov/rxd/src/rxd_cq.c
prov/rxd/src/rxd_ep.c
prov/rxd/src/rxd_msg.c
prov/rxd/src/rxd_tagged.c

- Add FI_PEEK, FI_CLAIM, and FI_DISCARD
- Refactor/fix unexpected message buffering/processing to support large unexpected messages and simplify code path
- Fix segfault
- Fix fi_ep_cancel
- Fix slist_insert_tail

prov/rxd: fix unexpected messaging and add FI_PEEK, FI_CLAIM, FI_DISCARD support

---

prov/tcp/src/tcpx_ep.c
prov/tcp/src/tcpx_init.c

Reworked the place where initing port range is.
The handling port numbers is taking place in tcpx_init_env() now.

prov/tcp: selecting port in tcpx_init_env

---

prov/verbs/src/verbs_domain_xrc.c
prov/verbs/src/verbs_info.c

Separate commits for minor verbs provider cleanup which do not change provider function: Log statement text, duplicate line of code, and log severity level.

prov/verbs: Minor cleanup/corrections and log severity reduction

---

include/ofi.h
prov/rxd/src/rxd_atomic.c
prov/rxd/src/rxd_cq.c
prov/rxd/src/rxd_ep.c
prov/rxd/src/rxd_init.c
prov/rxd/src/rxd_msg.c
prov/rxd/src/rxd_proto.h
prov/rxd/src/rxd_rma.c
prov/rxd/src/rxd_tagged.c

Because RxD does not use two of the ofi_op enums in ofi_proto.h and then defines RxD-specific ones after, the printing (which is based on the array index of the new defines) is off by 2 for the new RxD-specific enums.
To fix this, eliminate the connection to the ofi_proto.h enums and define completely separate RXD types but make sure to align them with the ofi_proto enums so we don't break the protocol. Add in 2 placeholder enums to line up the enums for printing

prov/rxd: fix packet type declaration and printing

---

prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_cm_xrc.c
prov/verbs/src/verbs_eq.c

When mapping connection tags to endpoints make the mapping to the
endpoint and the reset of the map entry a single protected operation.
Verify the mapped endpoint matches the requested key exactly. Make
sure to free connection tags for connections that do not complete
(e.g. rejected).

prov/verbs: Refactor/fixes for more robust XRC connection tag use

---

man/fi_gni.7.md
prov/gni/src/gnix_msg.c

When FI_SOURCE is specified, the gni provider issues a FI_EAVAIL
error with -FI_EADDRNOTAVAIL error code whenever the initiator's
address is unknown, even though FI_SOURCE_ERR is not specified.
Change this to only issue the erro when FI_SOURCE_ERR is specified.

prov/gni: Only generate FI_EADDRNOTAVAIL if FI_SOURCE_ERR specified

---

prov/mrail/src/mrail.h
prov/mrail/src/mrail_cq.c
prov/mrail/src/mrail_ep.c
prov/mrail/src/mrail_init.c
prov/mrail/src/mrail_rma.c

prov/mail: CQ polling optimization for small size messages
CQ polling overhead increases in proportion to the number of rails in
use. For small messages, better performance can be achieved by staying
with a single rail.
This patch also adds an experimental runtime parameter to set the
configuration of rail utilization algorithms.
Some optimization measures are also applied to the CQ polling loop:
- Allow batch polling a rail when multiple completions are available
- When fixed rail is used for small messgaes, don't continue with other
rails when at least one completion has been polled. This help improve
small message performance.
- Always start with the rail that was polled successfully last time. This
makes any rail to perform similarly as the default rail.
Signed-off-by: Jianxin Xiong …

prov/mail: CQ polling optimization for small size messages

---

fabtests/unit/av_test.c
include/ofi_util.h
prov/rxm/src/rxm.h
prov/rxm/src/rxm_av.c
prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_init.c
prov/util/src/util_av.c
prov/verbs/src/verbs_eq.c

This PR refactors cmap and fixes serialization issues in verbs EQ, rxm AV and atomics progress.
@swelch please take a look at patches 4 and 5 that modifies auto-progress for atomics.

prov/rxm, verbs: fixes for cmap and EQ

---

include/ofi_mem.h
include/ofi_mr.h
include/windows/dirent.h
prov/util/src/util_buf.c
prov/util/src/util_mem_monitor.c
prov/util/src/util_mr_cache.c
prov/verbs/src/fi_verbs.c
src/fabric.c
src/mem.c

Add a global array to store the list of possible page sizes.  Fill the list by adding the standard page size, plus all available huge page sizes.  The latter is obtained by parsing the directories under /sys/kernel/mm/hugepages.

userfaultfd: Support all available huge page sizes

---

prov/gni/configure.m4

Replace an incorrect environment variable name in configure.m4
that causes the gni provider to not find the gni_pub.h include
file.  The variable to be corrected is a name in the gni-headers
module.  this was also tested on 6.0.UP07 and it works there
as well
fixes #5005

prov/gni: fix configure.m4 so that GNI compiles on CLE 7.0.UP01

---

include/ofi_mr.h
man/fabric.7.md
man/fi_mr.3.md
man/fi_verbs.7.md
prov/util/src/util_mem_monitor.c
prov/util/src/util_mr_cache.c
prov/verbs/src/fi_verbs.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_domain.c

Rather than having per provider controls for the memory
registration cache, use a single set of controls.  This
avoid duplicate values for different providers.

prov/verbs: Move MR cache controls into core

---

prov/tcp/src/tcpx_msg.c

prov/tcp: fix recvmsg flags to support FI_SELECTIVE_COMPLETION

---

prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_cm.c
prov/verbs/src/verbs_cm_xrc.c
prov/verbs/src/verbs_domain_xrc.c
prov/verbs/src/verbs_ep.c
prov/verbs/src/verbs_eq.c

Once an XRC shared connection completes setup, initiate a disconnect of the associated CM ID's. Wait until the CM timed wait state is exited for the ID before destroying the associated QP. This prevents the QP from being reused while a stale connection will be detected.
If the EP is closed prior to timewait exit (or if a disconnect was not required) the resources will be released at that point.

prov/verbs: Fix the release of XRC shared connection resources

---

prov/rxd/src/rxd.h
prov/rxd/src/rxd_atomic.c
prov/rxd/src/rxd_cq.c
prov/rxd/src/rxd_ep.c
prov/rxd/src/rxd_msg.c
prov/rxd/src/rxd_proto.h
prov/rxd/src/rxd_rma.c

Starting to optimize the send path (tx_entry and first packet initialization) by making them function type specific. This allows us to skip RMA and atomic-specific steps. This also lets us get rid of the send_op function by initializing straight into the tx_entry->pkt during initialization and using the existing start_xfer function.
This PR also changes the order of the op packet headers to clean the initialization process and avoid having to check for data and tags twice. Because of this change, the protocol version is incremented. A patch is included to avoid communicating with peers with different protocols.
According to the hooking provider, this PR removes 19 instructions from both the send and inject paths

prov/rxd: restructure tx_entry + op packet initialization to reduce instructions

---

include/ofi_mr.h

The callback function typedefs are only used in one place.
Just declare the function handlers as part of struct
ofi_mr_storage

core/mr_cache: Remove unneeded typedefs for callbacks

---

prov/gni/Makefile.include
prov/gni/include/gnix_cm.h
prov/gni/src/gnix_av.c
prov/gni/src/gnix_cq.c
prov/gni/src/gnix_msg.c
prov/gni/test/rdm_addr_str_sr.c
prov/gni/test/sep.c

when also using FI_SOURCE_ERROR.  There were a bunch of places
in the GNI provider where the case of FI_ADDR_STR address format
was not being correctly handled.
Improve error handling for av insert.
Fixes #4963

prov/gni: fix a problem with handling fi_addr_str

---

fabtests/man/fabtests.7.md
fabtests/ubertest/config.c
fabtests/ubertest/fabtest.h
fabtests/ubertest/uber.c
prov/rxm/src/rxm_atomic.c
prov/rxm/src/rxm_rma.c

This PR adds missing serialization for RMA and atomics. This change was missed in #5014 .
Also updated ubertest to accept a threading level config (tests only hints). Did a minor refactoring for rxm RMA functions to reduce indent levels and fix logging level.

prov/rxm: fix serialization for RMA, atomics; fabtests: update ubertest

---

contrib/cray/Jenkinsfile.verbs
contrib/cray/bin/fabtest_wrapper.sh

If provided in the environment, use the fabtest installation in the environment.
This allows us to select the correct version of fabtests when running functional
tests.

contrib/cray: Use environment provided fabtest

---

prov/rxd/src/rxd_ep.c

Deleted handling of fid_list_remove(). Why?
The function fid_list_remove() is called inside ofi_endpoint_close()
for tx/rx cq.

prov/rxd: Cleaned up rxd_ep_close() function

---

prov/gni/src/gnix_ep.c
prov/gni/src/gnix_msg.c
prov/gni/test/cm.c
prov/gni/test/rdm_fi_pcd_trecv_msg.c
prov/gni/test/rdm_multi_recv.c
prov/gni/test/rdm_sr.c

Have no idea how things were working, but the GNI provider
was incorrectly using the length of the incoming message
for transfer to recv buffers/iovecs rather than the
length of receive buffers.
Fixes #5002

prov/gni: fix a problem with not truncating recvs

---

prov/gni/configure.m4

compiles on CLE 7.0.UP01
Replace an incorrect environment variable name in configure.m4
that causes the gni provider to not find the gni_pub.h include
file.  The variable to be corrected is a name in the gni-headers
module.  this was also tested on 6.0.UP07 and it works there
as well
fixes #5005
related to #5006
(cherry picked from commit 192d52ce53e8677878451b8bb3c7ae02d22dc99b)

[v1.7.1x] prov/gni: fix configure.m4 so that GNI

---

docs/policy

This document simply tries to capture the existing policies and
procedures used in the development of libfabric.  Most of these
are based on decisions reached by the community during ofiwg
calls.
The document is a guideline only of what is currently being done.

docs: Document general policies for the project

---

fabtests/test_configs/ofi_rxd/ofi_rxd.exclude
fabtests/test_configs/osx.exclude
include/ofi_list.h
prov/rxd/src/rxd.h
prov/rxd/src/rxd_atomic.c
prov/rxd/src/rxd_cq.c
prov/rxd/src/rxd_ep.c
prov/rxd/src/rxd_init.c
prov/rxd/src/rxd_msg.c
prov/rxd/src/rxd_proto.h
prov/rxd/src/rxd_rma.c
prov/rxd/src/rxd_tagged.c

Most fixes have to do with fixing the unexpected message buffering.
All of these together allow rxd to run properly with Intel MPI

[v1.7.x] prov/rxd: cherry-picked fixes

---

include/rdma/fi_domain.h
include/rdma/fi_endpoint.h
util/pingpong.c

These warnings show up because of two reasons: (1) variable names
shadow existing global symbols or (2) some variables are
uninitialized.

ofi: warning squashes

---

prov/verbs/src/verbs_info.c
src/fi_tostr.c

- set addr format correctly for verbs UD
- add FI_ADDR_IB_UD format string

[v1.7.x] verbs, fi_tostr: cherry-picked FI_ADDR_IB_UD fixes

---

include/rdma/fi_domain.h
include/rdma/fi_endpoint.h
util/pingpong.c

These warnings show up because of two reasons: (1) variable names
shadow existing global symbols or (2) some variables are
uninitialized.

ofi: warning squashes (backport to v1.7.x)

---

prov/verbs/src/verbs_cm_xrc.c
prov/verbs/src/verbs_domain_xrc.c
prov/verbs/src/verbs_eq.c

Changes to XRC logging to allow for selecting a logging level of warn
and a subsystem of ep_ctrl to capture both RXM and Verbs XRC
connection failure related logs.

prov/verbs: Align logging severity and subsystem for XRC with RXM

---

fabtests/test_configs/osx.exclude
fabtests/test_configs/udp/udp.exclude

Move rdm_tagged_peek exclusion from UDP (now supported by RxD) to OSX exclusion (not supported)

fabtests/test_configs/udp.exclude: move tagged_peek exclusion from UDP to OSX

---

man/fi_gni.7.md
prov/gni/src/gnix_msg.c

When FI_SOURCE is specified, the gni provider issues a FI_EAVAIL
error with -FI_EADDRNOTAVAIL error code whenever the initiator's
address is unknown, even though FI_SOURCE_ERR is not specified.
Change this to only issue the erro when FI_SOURCE_ERR is specified.
fixes #4922
related to #4993
(cherry picked from commit 0b8cabe632a3eb6db6412c4c01923fd74b7746bc)

[v1.7.x] prov/gni: Only generate FI_EADDRNOTAVAIL if FI_SOURCE_ERR specified

---

prov/gni/src/gnix_ep.c
prov/gni/src/gnix_msg.c
prov/gni/test/cm.c
prov/gni/test/rdm_fi_pcd_trecv_msg.c
prov/gni/test/rdm_multi_recv.c
prov/gni/test/rdm_sr.c

ing recvs
Have no idea how things were working, but the GNI provider
was incorrectly using the length of the incoming message
for transfer to recv buffers/iovecs rather than the
length of receive buffers.
Fixes #5002
(cherry picked from commit 50f90a4e5103e4110aa109a8526558f1363a3259)

[v1.7.x] prov/gni: fix a problem with not truncat

---

prov/gni/src/gnix_atomic.c
prov/gni/src/gnix_msg.c
prov/gni/src/gnix_rma.c
prov/gni/test/rdm_atomic.c
prov/gni/test/rdm_dgram_rma.c
prov/gni/test/rdm_dgram_stx.c
prov/gni/test/rdm_sr.c

returning GNI_RC values in the CQE for error cases
confuses some users.
Fixes #5050

prov/gni: use ofi error values for provider

---

man/fi_sockets.7.md
src/fabric.c

Move tcp before sockets provider.  Add missing shm provider.  Move
verbs forward of utility providers.  Drop mlx near the end of the
list because of minimal support.
Update man page to indicate that sockets is being deprecated.

core: Re-order provider priorities

---

configure.ac

Added configure option (--enable-atomics) to control atomics support.

Configure.ac: Enable atomics option

---

prov/gni/src/gnix_atomic.c
prov/gni/src/gnix_msg.c
prov/gni/src/gnix_rma.c
prov/gni/test/rdm_atomic.c
prov/gni/test/rdm_dgram_rma.c
prov/gni/test/rdm_dgram_stx.c
prov/gni/test/rdm_sr.c

returning GNI_RC values in the CQE for error cases
confuses some users (or at least Bob C.)
Fixes #5050 
(cherry picked from commit 77d792bddf21bccce18dc42cf3eb14a840e2120e)

[v1.7.x] prov/gni: use ofi error values for provider

---

man/fi_verbs.7.md
prov/verbs/src/fi_verbs.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_dgram_av.c
prov/verbs/src/verbs_ep.c

- add a way to specify a gid index
- only check lid if local addressing
- print correct address insertions

prov/verbs: addressing fixes

---

fabtests/scripts/runfabtests.sh

Add flags to runfabtests.sh that set additional flags to the
client/server fabtests.

fabtests: add option for additional client/server arguments

---

src/common.c

Previously, in order to convert a name into an address, the name was first
tried as a host name and if failed then tried as an interface name. However,
depending on system configuration, the function getaddrinfo() called in the
first step might incur seconds of delay if the name could not be resolved.
This could result in very slow operation when trying to convert an interface
name into address.
The workaround is to check the input name as an interface name first.

common: Work around possible long delay in getaddrinfo()

---

man/fi_rxm.7.md
prov/rxm/src/rxm.h
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_init.c

This commit changes the default behavior for progressing the
RXM connection manager. Prior to this patch, if manual progress
was requested by the application, then the CM would be progressed once
every 10000 function calls to fi_cq read functions. With this patch,
the default behavior is changed to once every 10 ms, and it is tunable
with an environment variable -- FI_OFI_RXM_POLL_FREQ_USEC. See fi_rxm(7)
for additional details on the environment variable.
closes #5066

prov/rxm: Modify poll mechanism for CM progress

---

prov/util/src/util_buf.c
prov/util/src/util_mr_map.c

Avoid segfault when calling fi_mr_bind() and fix cleanup in util_buf wrt huge pages.

cherry picked commits for minor issues

---

prov/gni/src/gnix_rma.c

Fix _gnix_rma() to clear the FI_LOCAL_MR flag at the same time that
local memory is de-registered so that the _gnix_fr_free() call
just after the err_get_vc: tag doesn't immediately assert.

prov/gni: fix fi_readmsg to not assert if fi_addr_t is incorrect

---

util/pingpong.c

The code currently segfaults when it finalizes because of
this issue.

util/pingpong: 'desc' must be an array of memory descriptors

---

prov/rxd/src/rxd.h
prov/rxd/src/rxd_domain.c
prov/rxd/src/rxd_ep.c
prov/rxd/src/rxd_init.c

Proper mr mode usage/passing to the core provider
This allows Open MPI to run

prov/rxd: mr mode fixes

---

prov/efa/src/rxr/rxr_ep.c

In MPI, when FI_PEEK was used to receive a message, the code structure
is usually like the following:
while( !MPIDI_OFI_PEEK_FOUND ) {
fi_trecvmsg( ..., FI_PEEK );   -> rxr_ep_peek_trecv();
MPIDI_progress();              -> fi_cq_read();
}
This code will hang on EFA if rxr_ep_peek_trecv() did not receive a
message at its first attemp.
The reason is:
1. rxr_ep_peek_trecv() will write a cq error entry if no data
was received.
2. fi_cq_read() will not call rxr_ep_progress() if CQ is NOT empty.
Thus if rxr_ep_peek_trecv() did not receive data the first time it was
called, the code will run into an infinite loop: rxr_ep_peek_trecv()
keep writing cq error entry and fi_cq_read will keep reading them
without calling rxr_ep_progress().
This patch added a call to __rxr_ep_progress() at the …

prov/efa : call progress function in rxr_ep_peek_trecv() to avoid hang

---

libfabric.spec.in

The module file should be part of the libfabric-devel RPM. Additionally,
pkgconfig requires an entry in the modulefile so that the environment is
set appropriately when the module is loaded

spec: Move modulefile to devel rpm

---

include/ofi_mem.h
prov/efa/src/efa_cq.c
prov/efa/src/rxr/rxr_ep.c
prov/mlx/src/mlx_domain.c
prov/mrail/src/mrail_ep.c
prov/psm2/src/psmx2_trx_ctxt.c
prov/rxd/src/rxd_ep.c
prov/rxm/src/rxm_ep.c
prov/sockets/src/sock_progress.c
prov/tcp/src/tcpx_cq.c
prov/tcp/src/tcpx_domain.c
prov/util/src/util_av.c
prov/util/src/util_buf.c
prov/util/src/util_mr_cache.c
prov/verbs/src/verbs_cq.c

Commit c181344092b6d43359c51173a6c9dbf18b01630f modified the buffer pool in such a way that the default behavior of supporting huge pages was removed, becoming an opt-in model.  This meant that buffer pool usage that could have made use of huge pages was switched back to normal page allocations.
This series updates the buffer pool creation calls to simplify the interface, so that huge pages can more easily be specified.  There are updates to most providers as buffer pool create calls are updated, but they should not affect the functionality of the providers.  The number of patches in this series make the changes look worse than they are.  Only about 100 lines of code change, with a net reduction of about 25 lines.

core/bufpool: Rework bufpool creation for huge page support

---

prov/rxd/src/rxd_attr.c
prov/rxm/src/rxm.h
prov/rxm/src/rxm_attr.c
prov/rxm/src/rxm_init.c
prov/tcp/src/tcpx_attr.c
prov/util/src/util_attr.c
prov/verbs/src/verbs_info.c

This is a quick fix for rxm, to play well with correct op_flags handling in util code. rxm getinfo code likely needs to be refactored and fixed to avoid other potential issues (some of which is captured in #5011). I'll work on that in a follow-up PR.

prov/util, verbs, rxm: fix op_flags handling

---

include/rdma/fabric.h

This fixes an error where fi_pingpong will segfault if run with
verbose output.
Signed-off-by: Peter Gottesman <pgottesm@cisco.com>

fabric.h: Check that ops exists in FI_CHECK_OP 

---

include/ofi_util.h
prov/tcp/src/tcpx.h
prov/tcp/src/tcpx_conn_mgr.c
prov/tcp/src/tcpx_ep.c
prov/tcp/src/tcpx_eq.c
prov/tcp/src/tcpx_progress.c
prov/util/src/util_eq.c

Currently tcp provider uses eq's internal wait fd to drive connection management progress. when conn is established the ep data progress func pointer is updated to the working one, from a dummy function. It also adds the ep's socket to cq's internal wait, by taking the ep-<lock first and then taking the cq->wait->lock. lets call it PATH-1
When an app wants to block on cq wait obj, it uses fi_cq_sread call. This would check for incoming messages but does not monitor the send queue before going to blocking state. So before try function is used to check and progress if any pending sends are there. Here cq->wait->lock is taken before entering the try func and in try func tcp provider takes the ep->lock. Lets call this PATH-2.
And there is another path(PATH-3), where ep->lock and ep state is …

/prov/tcp: fix potential deadlock due to lock ordering

---

prov/util/src/util_cq.c
prov/util/src/util_eq.c

The ofi_eq_sread() call will wait until the wait set fd is
signaled, then return any event found on the queue.  However,
it's possible that the wait set fd can be signaled without
a user event being written to the EQ.  In this case, we
need to loop until the full timeout has been reached.
This will match the semantics of the CQ and cntr blocking
read calls.
Also update the return value if CQ sread times out.  This
should be -EAGAIN, not -ETIMEDOUT, according to the man pages.

prov/util: Wait full timeout for EQ event in sread

---

prov/rxm/src/rxm_cq.c

Add check to fix SRX use with the PR5123 fixes.
@a-ilango - Let me know if this is sufficient. It enables the use of RXM SRX with the #5123 PR fixes; I was seeing a segfault where the conn was not set.

prov/rxm: Check for SRX use when freeing rx buf msg_ep close

---

prov/mrail/src/mrail_domain.c
prov/psm2/src/psmx2_cntr.c
prov/psm2/src/psmx2_trx_ctxt.c

prov/mrail: Fix potential NULL pointer dereference
prov/psm2: Remove unused assignments

prov/mrail,psm2: fix a few covscan defects

---

include/ofi_mem.h

smr_freestack_pop was setting next incorrectly and with no effect
Instead, set freestack->next to the next available entry after the pop.
Also add a re-initialization of the popped element->next for security (like in the normal freestack pop)

include/ofi_mem: fix smr_freestack_pop

---

fabtests/common/shared.c

OOB_SYNC and OOB_ADDR_EXCH are separate options. If the oob_port was initialized, it does not necessarily mean an out of band address exchange was requested. Explicitly check this option instead of just the port.

fabtests/common: only exchange addresses OOB if requested

---

prov/util/src/util_mr_cache.c

Although the MR cache may limit the number of registrations
stored in the cache, all user registrations may go through
the cache API.  This allows the user to register memory,
but not have it cached.  However, the MR cache currently
limits the buffer pool to track registrations to the
same size as the cache.  This prevents additional
registrations from succeeding.  Remove that limit.

core/mr_cache: Remove limit from MR cache buffer pool

---

prov/tcp/src/tcpx_comm.c

In case of recvs, tcp provider uses ofi_consume_iov to resize the recv buffer to the remaining msg len. ofi_consume_iov is optimized for single iov. Checking the iov[0]'s length for completion is sufficient for that case but not sufficient for multiple iov case. So added another check for iov_count along with iov[0]'s length to indicate recv completion.

prov/tcp: bugfix: properly check the recv completion

---

prov/shm/src/smr_progress.c

prov/shm: only pass through iov/ioc[0] if count > 0

---

include/ofi_mr.h
prov/util/src/util_mr_cache.c

If a memory region is not added to the cache, do not include it
as part of the cache_cnt or cache_size. This will eventually be
used to separate cacheable from non-cacheable registrations.
Plus it avoids reporting that the cache is full because an
uncached registration is active.

core/mr_cache: Do not add uncached regions to cache tracking

---

NEWS.md

Includes recent coverity fixes and missed mr_mode handling and pending_cnt updates

NEWS: update shm and rxd news for 1.8

---

include/windows/ifaddrs.h
include/windows/osd.h
src/windows/osd.c

1) Rewrote geifddars function for using new api - GetAdaptersAddresses.
Why do we use GetAdaptersAddresses?
- get a field -> Ipv4Metric
- add a possibility to support Ipv6 in future
2) Added an algorithm for sorting adapters under Ipv4Metric, using
IP_ADAPTER_ADDRESSES struct.
"Automatic Metric Assignment" assigns a higher metric to a slower
network interface. So, we sort the gotten metrics from the highest
to the slowest one. Then use the first IFF_UP adapter from linked list,
which we formed based on the metric and use for it as a main interface.

src/windows: Change getifaddrs for chosing the right adapter

---

prov/rxd/src/rxd_cq.c
prov/rxd/src/rxd_ep.c

The reason of getting out is don't do the checking for every
data packet while posting the data.
The solving is moving the checking of the flag in progress_tx_list,
checking RXD_READ_DATA before sending packets.
1)We had to add the check, which to make sure us that we don't
decrement the sequence unless we incremented it.
2)We flipped the return in rxd_ep_post_data_pkts in order to
change the condition. if (unacked >= tx_window) it returns 1 - there
is not space, 0 - there is more space to send. 

prov/rxd: Optimized rxd_ep_post_data_pkts

---

prov/efa/src/rxr/rxr.h

c6fed19b4 made it so the static assert used to validate the protocol
header sizes did not get compiled in for 32-bit architectures. There was
a typo in the preprocessor macro used which prevented the assert from
compiling even on 64-bit platforms. This commit fixes it.

prov/efa: Use the correct arch preprocessor macro

---

src/windows/osd.c

Does this even compile?  Fix obvious typo to add missing =.

windows/osd: Fix ret = -ENOMEM to include the '='

---

include/windows/ifaddrs.h
src/windows/osd.c

Added the support of IPv6 mechanism in getifaddrs:
1) Changed ifaddrs struct, defining in_addrs,
in_netmask fields as sockaddr_storage.
2) Using IP_ADAPTER_ADDRESSES struct made initilization
for sockaddr_in6 for making the IPv6 address of the
interface.

src/windows: Added support for IPv6 in getifaddrs

---

prov/util/src/util_buf.c

Instead of returning EINVAL if the pool is empty and cannot
grow, and ENOSPC if calloc() fails when growing, always return
ENOMEM.  ENOMEM is the correct return code for calloc failure.
And if we can't grow the pool anymore, returning ENOMEM makes
more sense than EINVAL, which is usually reserved for calls
made with invalid parameters.

core/buf_pool: Return ENOMEM if buffer pool is empty

---

fabtests/Makefile.am
fabtests/common/shared.c
fabtests/man/fabtests.7.md
fabtests/man/man1/fi_bw.1

Add man1/fi_bw.1 to create test man page.
Update man/fabtests.7.md with fi_bw test description.
Add fi_bw (which allows for EP specification) to -e usage list.

fabtests/fi_bw: update man page/usage

---

Makefile.am
include/rdma/fabric.h
include/rdma/fi_atomic.h
include/rdma/fi_collective.h
include/rdma/fi_domain.h
include/rdma/fi_endpoint.h
man/fi_atomic.3.md
man/fi_av.3.md
man/fi_av_set.3.md
man/fi_collective.3.md
man/man3/fi_allgather.3
man/man3/fi_allreduce.3
man/man3/fi_alltoall.3
man/man3/fi_av_set.3
man/man3/fi_av_set_diff.3
man/man3/fi_av_set_insert.3
man/man3/fi_av_set_intersect.3
man/man3/fi_av_set_remove.3
man/man3/fi_av_set_union.3
man/man3/fi_barrier.3
man/man3/fi_broadcast.3
man/man3/fi_collective.3
man/man3/fi_join_collective.3
man/man3/fi_query_atomic.3
man/man3/fi_query_collective.3
man/man3/fi_reduce_scatter.3
src/fi_tostr.c

Define the ability to access MPI style collective accelerations
supported by a provider.  This targets switch-based collectives,
but is not limited to that implementation.
Add a new man page that describes collective offloads, along
with updates to the header files.

fabric: Introduce support for collective offloads

---

prov/gni/src/gnix_msg.c

Routine __gnix_msg_copy_data_to_recv_addr() was recently changed because
an incoming message larger than the matched recv or multi-recv buffer
would result in buffer overflow. The reverse problem is now occurring,
the recv buffer's req->msg.cum_recv_len is now being used for the length
of the memcpy(), when the incoming SMSG is only a hundred bytes long.
There was no memory corruption occurring in this case, but a lot of random,
unexpected latency was introduced.   The tipoff was when I noticed that the
memcpy of a 1-byte eager message into a very large multi-recv buffer
was taking 1200 usecs.  :-)
The memcpy() is now called with the minimum of the cum_recv_len and
cum_send_len.
fixes ofiwg#5166

prov/gni: memcpy() of SMSG data to buffer using incorrect length

---

include/ofi_util.h
man/fi_verbs.7.md
prov/verbs/configure.m4
prov/verbs/src/fi_verbs.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_domain.c
prov/verbs/src/verbs_mr.c

See individual commits for details.  This is basically prep work for adding a flag that will allow a caller to indicate if a specific registration call should be cached or not.

prov/verbs: Cleanup of MR code

---

fabtests/configure.ac

fabtests/configure.ac: fix include path typo

---

prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_cq.c
prov/efa/src/rxr/rxr_ep.c

03ef12985 introduced protocol changes to support a more dynamic flow
control mechanism, and also changed the protocol version. In retrospect,
the protocol bump can be avoided and the change can be made without
breaking protocol compatibility.
With this change, if a sender is sending a request and the receiver is
on an older version, the request is just ignored and the older static
value (16) is returned with the CTS.  If a sender is running the older
protocol and fails to send a request, the receiver uses the
tx_min_credits value in the CTS window calculation.

prov/efa: Handle RTS credit request without breaking compat

---

prov/rxd/src/rxd_ep.c

**Issue:**
Optimizing rxd_ep_post_buf, when we set pkt_entry attributies.
**Solution:**
Threw away calling of `rxd_get_rx_pkt()` and call `ofi_buf_alloc()` at once during `rxd_ep_post_buf()`.
It gives us the opportunity  of taking buf_data at once.

prov/rxd: Set ofi_buf_alloc to pkt_entry while rxd_ep_post_buf

---

prov/util/src/util_mr_cache.c

We got an error but the memory registration is still in use and hence uncached
count has to be incremented. Call the right function that does it.

prov/util: fix incorrect uncache function being called in error path

---

prov/efa/src/rxr/rxr_init.c

The fi_nic structure part of the efa info object was not being properly
copied over. This caused the provider to not expose the field for its
non-dgram capabilities.

prov/efa: Bugfix fi_nic not being copied

---

prov/rxd/src/rxd.h
prov/rxd/src/rxd_cq.c
prov/rxd/src/rxd_ep.c

**Issue:**
The provided changes is posting a new recive buffer right away, and don't
wait for finishing the handle of a recive complition. We post a recieve
buffer at once.
**Results:**
The changes have caused the performance part results, which were run on 
`alltoal`l test, and it shows us better results from `64Kb to 4Mb`with comparing
'without the current changes'. But see a little regress from `1b to 64Kb`, 
the diff is about `~0.08 usec` **(not bigger)**.

prov/rxd: Move the receive repost/remove to earlier in the pkt handling

---

prov/gni/src/gnix_msg.c

A rendezvous message was to land in a multi-recv buffer.
A PostRdma() request was issued to retrieve the majority of the
message from the originator, but there was a problem with
memory permissions, and the request failed.  The code incorrectly
posted the error CQE to the endpoint's send CQ, when it should
have posted to the receive CQ.
Change the rendezvous code to post any CQE errors that occur on
a rendezvou PostRdma() request to the receive CQ, not the send CQ
since logically this is a receive operation.
fixes #5188

prov/gni: CQE error posted to the wrong endpoint CQ

---

prov/gni/src/gnix_msg.c

which could lead to a segfault rather than return an error.

prov/gni: fix an edge error case

---

prov/rxd/src/rxd.h
prov/rxd/src/rxd_ep.c

Since [7f8d168](https://github.com/ofiwg/libfabric/pull/5183) when we move receive repost/remove to earlier in the pkt
handling, we don't need to track post_bufs and post them immediately.

prov/rxd: Delete post_bufs tracking

---

include/ofi_tree.h
prov/rxd/src/rxd_av.c
prov/util/src/util_mr_cache.c
prov/util/src/util_mr_map.c
prov/verbs/src/verbs_domain_xrc.c
src/tree.c

Includes a couple of cleanup patches for failure handling.  Main change is to ensure that when we uncache a memory registration, that we remove the correct entry from the underlying rbtree.  This change is based on a code review and not in response to a specific sighting of this error, at least with the existing code.

mr/cache: Ensure that we remove the correct entry from the rbtree

---

contrib/cray/Jenkinsfile.verbs

A separate pipeline will be used for creating and publishing builds.
This commit removes this logic from the build verification pipeline.

contrib/cray: Remove build publishing step

---

Makefile.am
configure.ac
include/ofi_mr.h
libfabric.vcxproj
libfabric.vcxproj.filters
prov/util/src/util_mem_hooks.c
prov/util/src/util_mem_monitor.c
prov/verbs/src/verbs_domain.c

Integrate hooking memory allocation related calls into the MR
cache.  This allows us to support older linux kernel that do not
support userfaultfd.
The core of the code is adapted from OpenMPI.
Signed-off-by: Mikhail Khalilov <mikhail.khalilov@intel.com>
Merged all separate fixes together as part of the initial submission.  There are still some other calls to hook, which can fold into this commit if done quickly, or can be added as a follow on patch, since they can work as stand alone changes.

core/util: Adding MR cache malloc hooking mechanism

---

src/mem.c

While run openmpi/mpirun with linux containers, the libfabric failed
with segment fault message.
Signal: Segmentation fault (11)
Signal code: Address not mapped (1)
Failing at address: 0xfffffffffffffff0
[ 0] /lib64/libpthread.so.0(+0x12d80)[0x14feb5d4dd80]
[ 1] /lib64/libfabric.so.1(+0x23cd1)[0x14fea8105cd1]
[ 2] /lib64/libfabric.so.1(+0x18240)[0x14fea80fa240]
[ 3] /lib64/libfabric.so.1(fi_getinfo+0x695)[0x14fea80faea5]
[ 4] /lib64/libfabric.so.1(fi_getinfo+0x4e)[0x14fea80ffe9e]
[ 5] /usr/lib64/openmpi/lib/openmpi/mca_btl_usnic.so(+0xdf4e)[0x14fea8445f4e]
[ 6] /usr/lib64/openmpi/lib/libopen-pal.so.40(mca_btl_base_select+0xed)[0x14feb547815d]
[ 7] /usr/lib64/openmpi/lib/openmpi/mca_bml_r2.so(mca_bml_r2_component_init+0x16)[0x14fea9fab2f6]
[ 8] …

Fix segment fault issue for linux container

---

prov/rxd/src/rxd.h
prov/rxd/src/rxd_atomic.c
prov/rxd/src/rxd_ep.c
prov/rxd/src/rxd_msg.c
prov/rxd/src/rxd_rma.c

- Take out get/init base_hdr in a common part of tx_entry_init for msg, atomic, rma operations.
- Add rxd_pkt_size() for msg, atomic, rma operations.

prov/rxd: get/init base_hdr into init_common & add rxd_pkt_size()

---

prov/efa/src/rxr/rxr_cq.c

Currently, when duplicated RTS was deteced, peer->next_msg_id is printed
along with rts_hdr->msg_id, which is misleading because next_msg_id is
for sending message out, and has nothing to with received RTS msg_id.
What should be printed here is peer->robuf->exp_msg_id. This patch fix
it.

prov/efa : fix warning message about duplicated RTS

---

prov/rxd/src/rxd.h
prov/rxd/src/rxd_cq.c
prov/rxd/src/rxd_ep.c

1. Add inline rxd_pkt_remove() in order to common calls of dlist_remove() and ofi_buf_free().
2. Get rid of calls rxd_remove_rx_pkt() in recieve paths:
Remove the item from the list right when we get recv completion

prov/rxd: Make common pkt removal & reduce calls of remove_rx_pkt

---

prov/efa/src/efa_verbs/efa_ib_cmd.c
prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_cq.c
prov/efa/src/rxr/rxr_ep.c
prov/efa/src/rxr/rxr_init.c
prov/efa/src/rxr/rxr_rma.c

Some critical fixes that need to be backported to the release branch. The flowcontrol changes were also fixed with `0da8130` so that it does not break protocol compatibility and is safe to be backported.

prov/efa: Some EFA fixes for 1.8.x

---

prov/gni/src/gnix_msg.c

prov/gni: fix a breakage from previous commit

---

fabtests/multinode/src/core.c
fabtests/multinode/src/harness.c

fabtests/multinode: bugfix hints fields are accessed before allocation

---

prov/psm2/src/psmx2_domain.c

FI_THREAD_DOMAIN requires application to serialize domain access. This
allows most provider locks be disabled. However, such serialization
doesn't cover the internal progress thread. As the result, race condition
may arise if the locks accessed by the progress thread are turned off.
Fix by enabling such locks when the progress thread is enabled.

prov/psm2: Fix race condition with progress thread and FI_THREAD_DOMAIN

---

contrib/cray/Jenkinsfile.verbs

Change Jenkinsfile.verbs from using currentBuild.result to currentBuild.currentResult
Change Jenkinsfile.verbs from using XUnitBuilder to XUnitPublisher.
Signed-off-by: Tony Zinger <ajz@cray.com>

contrib/cray: Change Jenkinsfile.verbs to use currentBuild.currentResult

---

prov/psm2/src/psmx2_domain.c

prov/psm2: Always enable the lock accessed by the disconnection thread

---

prov/rxm/src/rxm_conn.c

When an RDMA CM disconnect event is received do not
immediately create a FI_SHUTDOWN event. Instead wait until
the timewait event is received before reporting the shutdown.
In larger fabrics we were seeing the FI_SHUTDOWN event delivered
prior to the QP fully draining and CQ entries processed.

prov/rxm: Fix connection handle shutdown/CQ processing race

---

include/ofi_recvwin.h

Given a message ID, this function return the message in robuf.
If message was not set, this function will return NULL.
Signed-off-by: Chenwei Zhang <chenwz@amazon.com>

include/ofi_recvwin.h: Add a new function ofi_recvwin_get_msg()

---

man/fi_mr.3.md
prov/util/src/util_mem_hooks.c

The memhooks handle cleaning up intercepted calls.  Once cleanup
runs, it is safe to re-hook memory calls.
This fixes temporary code that was added until cleanup could be added.
However, when cleanup was added, the temporary code was left.

core/mr_cache: Allow re-initializing memhooks

---

fabtests/Makefile.am
fabtests/multinode/include/core.h
fabtests/multinode/include/pattern.h
fabtests/multinode/src/core.c
fabtests/multinode/src/harness.c
fabtests/multinode/src/pattern.c

For more advanced and different testing patterns, the ability for
each process to know its own rank is required.
Users also will use ranks on processes for other collective communication
patterns.
Setup is done by having the server send off a rank to each other process
in the order that they are listed in the pm_job.clients table.
Adding common hpcs testing patterns
Broadcast: host sends to each client and each client receives once
Gather: each client sends to host and host receives all sends
Ring: each process sends to the next process and receives
from the previous
Each pattern is run during the multinode test, in additon to the
original all to all.

Added initialization for ranks for each process.

---

prov/efa/src/rxr/rxr_ep.c

The alloc handler was using the pointer and size for the buf pool
allocation area without the buf pool headers. Instead, it should use the
pointer that is returned by mmap/posix_memalign to avoid page alignment
issues.

prov/efa: fix alloc handler to use correct pointer and size

---

include/ofi_mem.h
include/windows/osd.h
prov/util/src/util_mem_monitor.c
prov/util/src/util_mr_cache.c
src/mem.c

The MR cache is currently unlimited in how much memory may be
registered by the cache.  At scale, this causes application
crashes when the system runs out of memory.  Change the default
to limit the cache size to:
total memory / # of cpus / 2
Assuming 1 process per core, this will limit the total amount
of system memory that will be maintained by the collective
caches to half of system memory.
Disable the cache if cache size is set to 0.

core/mr_cache: Limit cache size by default

---

prov/sockets/src/sock_av.c

set new memory obtained through realloc to 0.
Signed-off-by: Yulu Jia <yulu.jia@intel.com>

prov/sockets: memset realloced new memroy to 0

---

prov/verbs/configure.m4
prov/verbs/src/ofi_verbs_priv.h
prov/verbs/src/verbs_eq.c

The rdma-core librdmacm has been extended to implement the
RDMA_CM_EVENT_CONNECT_RESPONSE event to notify the
active side of a connection if the QP is not managed
by the RDMA CM (i.e. id->qp == NULL). Allowing additional
connection initialization to take place if required.
This patch adds XRC support for these updates if the
librdmacm supports the required new call, rdma_establish().

prov/verbs: Add XRC support for updated rdma-core librdmacm

---

include/ofi_mr.h
prov/util/src/util_mem_hooks.c
prov/util/src/util_mem_monitor.c
prov/util/src/util_mr_cache.c

Bug fix: some of the critical paths in util_mr_cache may yield while holding the
monitor lock.  If the monitor lock is a spinlock, then starvation can happen
if all available cores spin trying to acquire the lock while the thread holding
the lock is suspended.
fixes #5244

convert ofi_mem_monitor spinlock to pthread mutex

---

prov/gni/src/gnix_msg.c

Routine __handle_mrecv_req() checks if a buffer is a multi-recv
buffer, and if so, it allocates a separate gnix_fab_req struct to
use for the message about to be landed in that buffer.  However,
code in __smsg_eager_msg_w_data() and __smsg_rndzv_start() would
interpret that returned req pointer as a pointer to the multi-recv
buffer, and would not free the 'req' after completing the message
transfer.  The result was the leaking of one gnix_fab_req struct
for each message landing in a multi-recv buffer.
This PR removes the 'multi_recv' variable handling in those two
routines so that the gnix_fab_req struct that gets allocated by
__handle_mrecv_req gets properly freed in the same way that a
non-multi-recv gnix_fab_req would be freed.
fixes #5232
Signed-off-by: Kevan Rehm krehm@cray.com

prov/gni: fix memory leak in multi-recv buffer handling

---

include/ofi_mr.h
prov/util/src/util_mr_cache.c

The cache previously only allowed support for searching and registering
at the same time. In order to provide more control, a peek function is
added to allow only searching without registering.

core/mr_cache: Create a find function for the cache

---

include/unix/osd.h
include/windows/osd.h
src/common.c

The loopback addresses are being set using host order, rather
than network order.  As a result, the returned src_addr from
fi_info calls does not include the loopback addresses, but
rather something like this: 1.0.0.127.
Update calls from ntoh to hton to better reflect reality when
accessing the loopack address.

core: Fix setting loopback addresses

---

src/windows/osd.c

Fixed netmask value in getifaddrs implementation on Windows.
The bug does not break core functionality, but leads to wrong
IPv4 addresses in fi_info output.

windows/osd: fixed netmask in getifaddrs function

---

prov/verbs/src/verbs_mr.c

RXM now passes the OFI_MR_NOCACHE flag on a MR registration.

verbs: Allow passing of OFI_MR_NOCACHE flag

---

prov/sockets/include/sock.h
prov/sockets/src/sock_av.c

add a lock to make av table access thread-safe
Signed-off-by: Yulu Jia <yulu.jia@intel.com>

prov/sockets: add lock to protect av table access

---

fabtests/man/fabtests.7.md
fabtests/scripts/runfabtests.sh
fabtests/test_configs/eq_cq.test
fabtests/test_configs/lat_bw.test
fabtests/test_configs/ofi_rxd/udp.test
fabtests/test_configs/psm/all.test
fabtests/test_configs/psm2/all.test
fabtests/test_configs/psm2/verify.test
fabtests/test_configs/shm/all.test
fabtests/test_configs/shm/quick.test
fabtests/test_configs/shm/verify.test
fabtests/test_configs/tcp/quick.test
fabtests/test_configs/udp/all.test
fabtests/test_configs/udp/functional.test
fabtests/test_configs/udp/lat_bw.test
fabtests/test_configs/udp/quick.test
fabtests/test_configs/usnic/all.test
fabtests/test_configs/usnic/quick.test
fabtests/test_configs/verbs/all.test
fabtests/test_configs/verbs/quick.test
fabtests/ubertest/config.c
fabtests/ubertest/uber.c
include/ofi_mr.h
include/ofi_tree.h
prov/rxd/src/rxd_av.c
prov/util/src/util_mr_cache.c
prov/verbs/src/verbs_domain_xrc.c
src/tree.c

Includes a batch of updates to ubertest which were useful in debugging the issue.  The main patch here is the following change (2nd patch in series).  I believe the described problem can actually occur (my original PR resulted in the problem being hit repeatedly), so the updated patch is marked for v1.8.x
The rbtree delete call takes as input a node to remove from the
tree.  As an optimization, that node may be left in place in the
tree, with only the data it references replaced.  Instead, another
node in the tree (the node that is logically immediately to the
right of the given node) may be delete.  But the data values
of the two nodes are swapped.
This can lead to a possible use after free issue.
The issue results from the rbtree insert call returning a
pointer to the node where new …

core/mr_cache: Ensure that we remove the correct entry + ubertest updates

---

prov/sockets/src/sock_conn.c
prov/sockets/src/sock_ep.c

protect av table access in a few more places in addition to PR-5300
Signed-off-by: Yulu Jia <yulu.jia@intel.com>

prov/sockets: protect av table access continued

---

include/rdma/fabric.h
include/rdma/fi_domain.h
man/fi_getinfo.3.md
man/fi_mr.3.md

Add API changes for GPU aware applications:
- Add FI_HMEM capability for applications to request device support
- Add FI_MR_HMEM mr_mode for providers to set if they require the
application to register device memory
- Add fi_mr_attr::iface to pass the hmem interface to the provider
when registering device memory
- Add fi_mr_attr union to pass interface-specific device
identifier to specify on which device the memory resides
This allows providers to easily know what buffers are on which device
without having to query the device.

include/fabric, domain: add HMEM API changes

---

include/ofi_mr.h
include/ofi_tree.h
prov/rxd/src/rxd_av.c
prov/sockets/src/sock_conn.c
prov/sockets/src/sock_ep.c
prov/util/src/util_mem_monitor.c
prov/util/src/util_mr_cache.c
prov/util/src/util_mr_map.c
prov/verbs/src/verbs_domain_xrc.c
src/tree.c

Some modifications were needed to resolve conflicts, but this pulls in the MR cache locking change (to a mutex) and MR cache entry deletion adjustments.

cherry picked fixes to sockets AV and MR cache

---

man/fi_cq.3.md

FI_FENCE is defined such as previous operations must have
completed prior to the fenced operation.  However, no
requirement is defined for the strength of those completions.
For example, if an operation requires FI_INJECT_COMPLETE, but
the fenced operation needs FI_DELIVERY_COMPLETE, the state
of the first operation is not known.
Expand the fence definition such that all previous operations
must meet the same completion semantic as the fenced
operation.  This is basically the only definition that makes
sense for fencing to be usable.  Just specify this in the
man pages.

man/fence: Expand completion semantics of FI_FENCE ops

---

man/fi_atomic.3.md
man/fi_mr.3.md
man/fi_msg.3.md
man/fi_rma.3.md
man/fi_tagged.3.md

Only updates to the wording to clarify use and point
developers to the fi_mr man page.

man/mr: Tweak wording on FI_MR_HMEM and desc use

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_atomic.c
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c

Change the RXM atomic protocol TX buffer pool to be unbounded,
but use a credit scheme that limits the number of atomic requests
initiated by the application that can be outstanding (RXM tx_attr->size).
This allows the RXM atomic protocol CQ processing to allocate an atomic
response TX buffer as needed independent of the application usage.

prov/rxm: Remove atomic response buffer allocation limitation

---

prov/efa/src/rxr/rxr_av.c

When the attr->type is FI_AV_UNSPEC, failure occurs in
util_verify_av_attr. util_verify_av_attr also does a check to ensure
that attr->type and domain->util_domain.av_type match. The following
change has been done: Set the attr->type to FI_AV_TABLE if the
domain->util_domain.av_type is FI_AV_UNSPEC. Otherwise, attr->type
should be equal to domain->util_domain.av_type.
@rajachan, could you please check?

prov/efa: Fix failure in rxr_av when av type is FI_AV_UNSPEC

---

include/rdma/fi_collective.h
man/fi_av_set.3.md
man/fi_collective.3.md

fi_join_collective() performs a collective operation itself with
the endpoints identified via the coll_addr parameter.  This
works well for all join operations except the first.  In the case
of the first join, the user passes in ADDR_UNSPEC.  This indicates
that all endpoints that are part of the associated AV are
participarint in the collective.
From the viewpoint of the app, this is restrictive and a little
unusual.
Instead of creating a special case to handle the first join
call, associate an fi_addr with an AV set.  Applications can
create an AV set, populate it with peer addresses, then obtain
an fi_addr for that set of peers.  The fi_addr returned by the
AV set is a local operation only.
By creating an AV set that contains all addresses in an AV,
we maintain the existing support. …

fabric/collectives: Assign an address to an AV set

---

prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_cm_xrc.c
prov/verbs/src/verbs_domain_xrc.c
prov/verbs/src/verbs_eq.c

With the evolution of the EQ lock to make connection
processing thread-safe, the INI QP management lock
is no longer needed, the structure is protected by
the EQ lock.

prov/verbs: Remove XRC shared INI QP management lock

---

prov/shm/src/smr.h
prov/shm/src/smr_comp.c
prov/shm/src/smr_ep.c
prov/shm/src/smr_progress.c

The previous implementation was not saving the source address
properly if requested, either improperly casting the fi_addr_t
to a pointer or not passing in the correct address.
Change the completion function to take in a fi_addr_t instead of
void * and make sure it's passing in the correct value.

prov/shm: save completion address properly

---

man/fi_efa.7.md
prov/efa/src/efa.h
prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_av.c
prov/efa/src/rxr/rxr_cq.c
prov/efa/src/rxr/rxr_domain.c
prov/efa/src/rxr/rxr_ep.c
prov/efa/src/rxr/rxr_fabric.c
prov/efa/src/rxr/rxr_init.c

When using shm provider for data transfer:
1. For small/medium (adjustable threshold by macro RXR_MEDIUM_SIZE)
message, sender sends RTS packet with real data payload to the receiver
via shm provider. Receiver receives it and extracts the data to the user buffer.
2. For large message, sender only sends the RTS packet with IOV structures to the
receiver. Upon receiving the RTS packet, the receiver first extracts the IOV structures.
Then the receiver issues a RMA READ operation to the sender's address (included
in IOV) to get the real data, which utilizes CMA copy. Upon receiving the completion of the
RMA READ operation, the receiver sends a EOR packet to notify the sender that
data copy is done, so that sender can write send completion.
Runtime environment variable …

prov/efa: Enable shared memory based transfer with SHM provider for intra-node communication

---

prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_ep.c
prov/efa/src/rxr/rxr_rma.c

This commit changes the rather messy function signatures of
rxr_ep_tx_entry_init(), rxr_generic_tx_entry_init(), rxr_tx(), and
rxr_generic_rma() to use `struct fi_msg` or `struct fi_msg_rma` as
applicable. The send descriptor was also getting dropped in some paths,
which is now fixed by using the msg structures.

prov/efa: Rework function signatures of generic tx functions

---

include/ofi_abi.h
include/rdma/fabric.h
libfabric.map.in
man/fi_domain.3.md
man/fi_endpoint.3.md
src/abi_1_0.c

From PR #5148
Changes:
Move tclass documentation from fi_domain to fi_endpoint man page
Changed fi_tc_dscp_get/set macros into functions.  Added to man pages
Fixed ABI compatibility issues (tclass field should not be in ABI 1.2 structs)
Removed FI_TC_PROV_SPECIFIC, FI_PROV_SPECIFIC define already exists for this purpose
Remove lengthy and unneeded examples from tclass documentation

core: Add support for traffic class selection

---

prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_domain.c
prov/verbs/src/verbs_eq.c

This patch is an attempt to provide an initial support of async events into the verbs provider. Async event are particularly interesting to report events such as a network device removal or
CQ overrun into the Event Queue (EQ).
This patch was initially part of the pull request #4324, but because of a low activity, it was considered as dead. The patch however contains all my latest changes (the last update is from 2 months ago) and it is basically waiting for feedback/reviews from the community.
PS: only MSG and RDM endpoints are supported as for now.

prov/verbs: Attempt at providing IB async events

---

prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_atomic.c
prov/psm2/src/psmx2_attr.c
prov/psm2/src/psmx2_av.c
prov/psm2/src/psmx2_cntr.c
prov/psm2/src/psmx2_domain.c
prov/psm2/src/psmx2_ep.c
prov/psm2/src/psmx2_init.c
prov/psm2/src/psmx2_msg.c
prov/psm2/src/psmx2_rma.c
prov/psm2/src/psmx2_tagged.c
prov/psm2/src/psmx2_trx_ctxt.c
prov/psm2/src/psmx2_wait.c
prov/psm2/src/version.h

By default, PSM2 uses all active HFI devices. In order to report fi_nic
information a domain must be associated to a specific HFI device. This
is done by converting a single fi_info structure with default device
selection (-1) into a list of fi_info structures with specific device
settings. Only the PCI bus attributes of the fi_nic information are
populated. The original fi_info structure is kept intact if there are
more than one active devices.
Set the domain name to be the name of the selected HFI device(s).
Update the year in the copyright headers.

prov/psm2: Add fi_nic support and use device name for domain name

---

fabtests/scripts/runfabtests.sh
include/rdma/fabric.h
include/rdma/fi_atomic.h
include/rdma/fi_collective.h
include/rdma/fi_domain.h
man/fi_collective.3.md
prov/util/src/util_coll.c
src/fi_tostr.c

Update the collective APIs to support gather and reduce
operations.  These were missing from the initial collective
calls.  Adding these exposed an issue with the existing calls
providing the 'root' of broadcast calls, which are also
needed for gather and reduce.
To support the new calls, and make it easier to extend support
for other collective ops, modify the calls into the provider.
Instead of using a single writeread() atomic style call, define
separate entry points for each collective.

collectives: Rework collective APIs to add gather / reduce support

---

prov/efa/src/rxr/rxr_init.c

fi_param_get_<x> are just passthrough functions to fi_param_get
which looks up the type of parameter based on how it was defined.
Thus, since we incorrectly defined the parameters as integers,
fi_param_get_size_t would treat the parameter as an integer,
effectively overflowing its value.

prov/efa: Bugfix params defined incorrectly

---

prov/rxm/src/rxm_ep.c

Parameter type mismatch (void *)

prov/rxm: fix desc parameter on senddata path

---

prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_domain.c
prov/verbs/src/verbs_eq.c

This reverts commit df435c92dfb1233680d69be8881b533a885218ed.
This patch is an attempt to provide an initial support of async
events into the Verbs provider. Async event are particularly
interesting to report events such as a network device removal or
CQ overrun into the Event Queue (EQ).
PS: only MSG and RDM endpoints are supported as for now.
Two separate issues have been reported.  Multi-threaded apps with
auto-progress without FI_ATOMIC is failing.  Also, ubertest is
experiencing hangs during shutdown waiting for the async thread
to exit.

Revert "prov/verbs: Attempt at providing IB async events"

---

prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_ep.c

With this commit, the inline registration path allows for reuse of
application descriptors when provided, avoiding the need for the bounce
buffers for the data packets.

prov/efa: Use application's registration when available

---

prov/rxm/src/rxm_ep.c

Parameter type mismatch (void *)
Cherry-picked from commit 9a3cdafc244812fbfe9a93f0ad61a162e1b81fa8

[v.1.8.x] prov/rxm: fix desc parameter on senddata path

---

contrib/cray/python/parse_results.py

Adds Excluded result to parser. Without the change, the script assumes
the test has failed.

contrib/cray: Added Excluded result to parser

---

fabtests/ubertest/uber.c
prov/util/src/util_mem_monitor.c
prov/util/src/util_mr_cache.c

First commit adds auto-unsubscribe for the REMOVE event, to align it with UNMAP.
The second commit moves unsubscribe from the MR free path to the uncache path.  Note that the resulting changes actually show that other lines moved because of the structure of the code.  But the code that moved is the call to ofi_monitor_unsubscribe() and related if statement and comment.
This is a slight improvement over the existing code, but an additional cleanup could be added to better handle entries for which we've received a notification.

mr/cache: Tweaks to unsubscribe paths

---

fabtests/Makefile.am
fabtests/common/shared.c
fabtests/multinode/include/coll_test.h
fabtests/multinode/src/core.c
fabtests/multinode/src/core_coll.c
fabtests/scripts/runfabtests.sh
include/ofi.h
include/ofi_coll.h
include/ofi_enosys.h
include/ofi_util.h
prov/rxm/src/rxm.h
prov/rxm/src/rxm_attr.c
prov/rxm/src/rxm_av.c
prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c
prov/util/src/util_coll.c
prov/util/src/util_ep.c
src/enosys.c

This PR makes several improvements over the initial collective implementation and integrates join and barrier collectives with prov/rxm
- when handling collective transfers during the ep->progress flow, additional transfers
could be generated for the collective operations.  If these collective messages are generated
during ep->progress, we will hit a deadlock when the collective handling tries to send its
messages.  To work around this, we've moved the collective transfers to a pending queue,
which will need to be progressed by providers using the util/coll implementation
- Refactor collective state structures so that there is a single structure
to describe in-progress collective calls
- Reserve the most significant bit of the collective message tags to identify a collective
transfer when …

prov/util: rework collective implementation

---

fabtests/test_configs/psm2/all.test

Ubertest re-uses the same data buffer for all sends and receives.
This exposed an issue in the psm2 provider.  The provider posts
the start of the data buffer in order to receive the underlying
protocol header.  After parsing the header, it posts the buffer
to receive the rest of the data.
With bandwidth tests, a stream of messages are received.  When
a single buffer is posted to receive the messages, the received
header is overwritten.  This results in the test hanging.
Since it's highly unlikely that a real application is going to
reuse the same buffer to receive all messages, the simplest
solution is to remove this specific test for the psm2
provider.

ubertest/psm2: Remove SENDV bandwidth testing

---

prov/efa/src/rxr/rxr_cq.c
prov/efa/src/rxr/rxr_ep.c

There were a few places where we were missing the check for shm environment
variable (rxr_env.enable_shm_transfer). Although the code path won't be
affected, fix them to make the code more readable.

prov/efa: Fix the missing shm env. variable check

---

prov/efa/src/rxr/rxr_ep.c
prov/efa/src/rxr/rxr_rma.c

If MR cache is turned on, EFA provider will try to send data inline
(not using bounce buffer), which require inline memory regitration.
For send/receive, this happens in rxr_ep_handle_rts_sent() on sending
EP. Emulated read does not send a RTS on the sending EP, thus did
not turn on memory registration.
This patch do inline memory registration for emulated read path
after readrsp packet was sent.

prov/efa : turn on inline memory registration for emulated read

---

prov/efa/src/rxr/rxr_ep.c

rxr_ep_rx_entry_init() is not setting rx_entry->cq_entry.flags for
ofi_op_read_rsp and ofi_op_write correctly.
For these operations, it should set the FI_RMA flag, but is
setting the FI_MSG flag. This patch fix this issue.

prov/efa : fix a bug in rxr_ep_rx_entry_init()

---

prov/efa/src/efa_fabric.c

MR cache issues have been diagnosed, details in issue #5347 . We have
decided to enable it by default.

prov/efa: Change efa mr cache defaults

---

Makefile.am
fabtests/multinode/src/core_coll.c
include/ofi_bitmask.h
include/ofi_coll.h
include/ofi_util.h
libfabric.vcxproj
libfabric.vcxproj.filters
prov/rxm/src/rxm_cq.c
prov/util/src/util_coll.c
prov/util/src/util_ep.c

This PR aims to clean up some of the confusing and extraneous queuing and locking of collective work items.  We reduce to 1 queue of all ready-to-go items across all collectives in flight and structures to track collectives and their work items that are waiting to be processed.
The PR also offers a few other minor clean up items, such as some clarification to the context id mask, the addition of some missing file listings in the vsxproj, and some minor collective multinode fabtest clean up.

prov/util: Refactor queuing of collective work items

---

prov/sockets/src/sock_av.c

sock_av_insertsym() may return postive FI_ETOOSMALL on
error. Fix nit (#5387) before fixing #5386.

prov/sockets: postive value returned on error

---

prov/sockets/src/sock_av.c
prov/util/src/util_shm.c

Fixes issue #5386. gcc 9 adds compiler warnings for strncpy
overflows and NUL termination. This fixes the two warnings
that occurred when compiling the existing code. The change
in util_shm.c just suppresses the warning; the existing code
was correct. The change in sock_av.c does fix a possible
overflow in the non-debug case.

Fix gcc-9.2.1 stringop warnings

---

contrib/cray/Jenkinsfile.verbs

Tags can be fetched through the pipeline configuration.
This commit removes the tag fetching from the pipeline.

contrib/cray: Remove tag fetching from pipeline

---

prov/efa/src/rxr/rxr_init.c

76a9f40ffe added logic to mark pinned memory with MADV_DONTFORK to
prevent the copy-on-write semantics in the face of a fork. Given the
pinned memory could be backed by regular or huge pages, efa_madvise()
relied on the global page_sizes array to try marking the region with all
known sizes. When the provider is built as a DSO library, the global
page_sizes array is uninitialized causing the function to fail and
return an erroneous errno. This commit fixes it by calling
`ofi_mem_ini()` explicitly when initializing the EFA provider in a DSO
build.
Likewise, the MR cache code in EFA relies on the global monitor which
needs to be initialized inside a DSO build.

prov/efa: prov/efa: Initialize global objects for DSO builds

---

prov/efa/src/rxr/rxr_ep.c

Currently in rxr_ep_progress_internal() there is a VALGRIND_MAKE_MEM_DEFINED
statment which should have gone to the function rxr_ep_poll_cq().
This patch fix this issue.

prov/efa : fix a VALGRIND_MAKE_MEM_DEFINED statment location

---

prov/psm2/src/psmx2_init.c

1) Move tmp_nctxts, tmp_nfreectxts in common code,
because it doesn't compile, when we do not use PSM2_INFO_QUERY
2) Clean up directive writing warning of sprintf()

prov/psm2: fix compiling, when NOT HAVE_PSM2_INFO_QUERY

---

man/fi_shm.7.md
prov/shm/src/smr_ep.c
src/common.c
src/fabric.c

3 addressing fixes:
- avoid unnecessary getaddrinfo calls
- skip utility provider layering if shm was specifically requested since it cannot be layered
- add user ID to shm address to avoid user permission/duplicate errors

src/common, prov/shm: addressing fixes

---

fabtests/man/fabtests.7.md
fabtests/man/man1/fi_multinode.1
fabtests/man/man7/fabtests.7
fabtests/multinode/src/harness.c
fabtests/scripts/runfabtests.sh

The issue of the OSX tests timing out was likely caused by not waiting for client processes to finish executing before killing the server. The bash script now waits for all of those clients to finish.

scripts/runfabtests.sh: Fix multinode test running on OSX devices

---

include/ofi_shm.h
prov/shm/Makefile.include
prov/shm/src/smr_av.c
prov/shm/src/smr_ep.c
prov/shm/src/smr_init.c
prov/shm/src/smr_signal.h
prov/util/src/util_shm.c

Four commits:
e2edcc7a9 prov/shm: Cleanup tmpfs cruft after an unclean shutdown
aa71fb16a prov/shm: Register custom signal handlers
1692a4765 prov/shm: Return the correct addrlen on a fi_getname()
076168a4e prov/shm: Replace SMR_NAME_SIZE with NAME_MAX

prov/shm: Register custom signal handlers

---

prov/efa/src/rxr/rxr_ep.c

While calling rxr_ep_tsendv(), rxr_ep_tsend() should use pointer
to desc, but it is use desc itself currently.
This patch fix this issue.

prov/efa : fix a bug in rxr_ep_tsend()

---

fabtests/test_configs/eq_cq.test
fabtests/test_configs/lat_bw.test
fabtests/test_configs/sockets/all.test
fabtests/test_configs/sockets/complete.test
fabtests/test_configs/sockets/quick.test
fabtests/test_configs/sockets/verify.test
fabtests/ubertest/ofi_atomic.c
fabtests/ubertest/uber.c

- Update atomic swap calls to match libfabric
- Check for info on server ENODATA
- Remove old FT_MODE_* configs
- Remove sockets FI_EP_DGRAM tests (broken, times out, out of sync)

fabtests/ubertest: fixes and updates

---

contrib/intel/jenkins/tests.py

- added code to change current directory to the
fabtest configs directory for running runfabtests
as fi_ubertest inside runfabtest script creates path to config file
relative to this location.
-added -T 300 option for runfabteststo support fi_ubertest

Fix for fi_ubertest failures on jenkins-ci

---

prov/efa/src/rxr/rxr.h

Currently if efa memory poisoning is turned on, compilation will fail.
It is caused by a typo in rxr_release_rx_pkt_entry(), this patch fix it.

prov/efa : fix a typo which cause compilation fail

---

prov/verbs/configure.m4
prov/verbs/src/fi_verbs.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_domain.c
prov/verbs/src/verbs_domain_xrc.c
prov/verbs/src/verbs_ep.c
prov/verbs/src/verbs_mr.c

Experimental verbs API were removed previously.  This adds ODP support through the main verbs API.

prov/verbs: Enable ODP support for filesystem DAX support

---

include/ofi_indexer.h

When running more than 64K application ranks, the indexer
hits a hard limit as defined in the header file. This commit
increases the number of bits in the indexer from 16 to 22,
increasing the size from (64K - 1) entries, to (1M - 1) entries.
Fixes #5429

core: Increase the size of the indexer to 1M

---

man/fi_cq.3.md

As indicated by issue #5433, the use of the buffer for input
is not documented clearly enough.

man/cq: Clarify use of err_data buffer

---

fabtests/common/shared.c
fabtests/functional/rdm.c
fabtests/include/shared.h
prov/rxm/src/rxm.h
prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_cq.c

when multiple 'clients' are connecting and disconnecting from a single 'server'
the structures tracking the connection state were not being cleaned up, which
could quickly balloon memory depending on the application use case

prov/rxm: delete cmap handles when processing client shutdowns

---

src/common.c

explicitly set revents field to zero for the new fds during add operation.
Otherwise we might use incorrect (related to deleted fds) revents during
contexts filling if fd set modified just after poll(). This can be easily
reproduced with tcp/rxm on Windows when endpoint connects to itself.

common: fixed epoll_wait implementation

---

man/fi_rxm.7.md
prov/rxm/src/rxm_init.c

fixed value to 128 Kb refer to #define RXM_SAR_LIMIT

man: set a correct value for SAR_LIMIT in doc

---

prov/efa/src/rxr/rxr_attr.c

The RDM endpoint should advertise FI_LOCAL_COMM and FI_REMOTE_COMM.

prov/efa: fix info and domain capabilities for RDM endpoint

---

include/rdma/fi_collective.h
include/rdma/fi_domain.h

Compiling the `fi_domain.h` header with C++ compiler ends up to the following error:
```
include/rdma/fi_domain.h:206:8: error: use of enum 'fi_collective_op'
without previous declaration  enum fi_collective_op;
```
In C++, the storage required for the enum variables is determined by the compiler, whilst it is always an integer with C.
As a consequence, C++ doesn't allow to forward-declare an enum without specifying its actual size.
The suggested fix is to move the declaration of the `enum fi_collective_op` to `fi_domain.h`. It should be fine as `fi_collective.h` does include `fi_domain.h` anyway.
IMPORTANT: I haven't tested my patch with collective operations since the code I compile doesn't need this support. Can someone please confirm that I'm not breaking this support?

headers: fix forward-declaration of enum fi_collective_op with C++

---

fabtests/multinode/src/core_coll.c
include/ofi_coll.h
prov/util/src/util_coll.c

The initial implementation of the join collective was updating the group id
of the initial mc group rather than the new mc group created during the join
in simple tests, the previous appeared to work if you're using the same set of
ranks for all collectives, but would be incorrect for multiple and varying
groups

util/coll: apply negotiated group id to new mc during collective join

---

prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_domain_xrc.c
prov/verbs/src/verbs_eq.c

Adds the capability to write an EQ entry while already holding the EQ lock. This
has not been seen in practice, but could occur in the XRC error path if an asynchronous
call into rdma_resolve_route() returned an error.

prov/verbs: Remove possible deadlock in XRC error path logic

---

include/ofi.h
include/ofi_recvwin.h
prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_cq.c
prov/efa/src/rxr/rxr_ep.c
prov/efa/src/rxr/rxr_rma.c

The EFA provider and ofi_recvwin.h were not handling the case where message ID wraps around. This patch series fixes this issue.

Handle message ID wraparound in EFA and ofi_recvwin header

---

include/ofi.h
include/ofi_recvwin.h
prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_attr.c
prov/efa/src/rxr/rxr_cq.c
prov/efa/src/rxr/rxr_ep.c

Pull in the `FI_LOCAL_COMM | FI_REMOTE_COMM` and message ID fixes for EFA for the next 1.8.x release.

1.8.x fixes for efa

---

prov/shm/src/smr_cq.c

Cherry-picked from commit dcb9c6dbf5e9bebefec5fc00ea1d6133a701f4e6

[v1.9.x] prov/shm: fix pointer passed into ofi_cq_init

---

prov/util/src/util_shm.c

Fix strncpy() bounds check warning.

prov/util: Fix gcc 9.2.1 stringop warning

---

contrib/intel/jenkins/build.py
contrib/intel/jenkins/runtests.py
contrib/intel/jenkins/tests.py

added the right  options for mpich build commmand for Jenkins-CI
--with-device=ch4:ofi, --enable-ch4-direct=netmod
- Holding back MPICH testing for Jenkins-CI
runtests.py: removed mpich from the mpilist,
for testing untill MPICH issues are resolved.

Mpich build/test changes for Jenkins-CI

---

contrib/intel/jenkins/Jenkinsfile
contrib/intel/jenkins/Jenkinsfile.daily
contrib/intel/jenkins/build.py
contrib/intel/jenkins/run.py
contrib/intel/jenkins/tests.py

Job name includes both the name of the job and name of the branch.
Using Job name helps differentiate the same branch being built by
two different jobs. Moreover, it prevents two builds for the same 
branch overwriting the same build path. 
changes made to build.py and run.py: replace BRANCH_NAME,
brname and branchname to JOB_NAME, jobname and jbname.

Changed to using Jenkins environment variable job name instead of branch name in build path 

---

fabtests/common/shared.c
fabtests/functional/multi_recv.c
fabtests/include/shared.h
fabtests/scripts/runfabtests.sh

adds -b option for oob testing and adds logic to support this
in common/shared and functional/multi_recv.
Signed-off-by: Nikola Dancejic <dancejic@amazon.com>

fabtests: added -b option for oob address testing

---

fabtests/common/shared.c
fabtests/include/shared.h
include/ofi_util.h
include/rdma/fi_eq.h
include/windows/pthread.h
man/fi_cntr.3.md
man/fi_cq.3.md
man/fi_eq.3.md
man/fi_poll.3.md
prov/shm/src/smr_cntr.c
prov/shm/src/smr_cq.c
prov/shm/src/smr_ep.c
prov/shm/src/smr_fabric.c
prov/util/src/util_cntr.c
prov/util/src/util_cq.c
prov/util/src/util_eq.c
prov/util/src/util_wait.c

- Add definition of new wait object type FI_WAIT_YIELD to allow for waiting without an underlying wait object.
- Add support of FI_WAIT_YIELD in utility code
- Add FI_WAIT_YIELD as the default (and only) waiting method for the shm provider
- Add testing option of FI_WAIT_YIELD

prov/util, shm: add FI_WAIT_YIELD

---

contrib/intel/jenkins/Jenkinsfile

added timeout to abort the build after 4
hours of inactivity (on the logs) of a pull request build. 
Jenkinsfile: added timeout under options. 

Added timeout

---

prov/shm/src/smr_av.c
prov/shm/src/smr_ep.c
prov/shm/src/smr_init.c

2 address name fixes:
- include NULL terminator in addrlen to make sure to duplicate/use it
- cast address correctly in fi_av_insert

prov/shm: address name fixes

---

contrib/intel/jenkins/common.py

reformatted printing of exeuted commands as a string instead of a list
This saves time for developers when testing failed tests commands manually
common.py: added " ".join to the print statement in run_command

Reformatted printing of test commands in the logs

---

prov/verbs/src/fi_verbs.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_cm.c
prov/verbs/src/verbs_cm_xrc.c
prov/verbs/src/verbs_domain_xrc.c
prov/verbs/src/verbs_ep.c
prov/verbs/src/verbs_eq.c

This is a series of patches that implement using RDMA CM SIDR message exchanges to setup virtual/shared XRC QP connections. This avoids the necessity of creating temporary hardware resources when setting up the shared connections. With these changes XRC connection setup becomes faster than RC when the PPN count is greater than 4 PPN, and has up to a 70% improvement in connection setup time over the existing XRC connection setup implementation.

prov/verbs: Use RDMA CM SIDR message exchanges for shared XRC QP connections

---

include/ofi_net.h

Avoid combining unrelated warning messages on the same line.

core/net: Add trailing newline to warning messages

---

util/pingpong.c

Only insert the local address into the AV if the provider supports
FI_LOCAL_COMM.  This fixes usnic with fi_pingpong.
Fixes #5497.  This PR replaces the first attempt (i.e., reverting the original commit that caused the problem): #5509

pingpong: selectively AV insert local address

---

util/pingpong.c

Only insert the local address into the AV if the provider supports
FI_LOCAL_COMM.  This fixes usnic with fi_pingpong.
(cherry picked from commit 3bf9513f284a89ae834dc58680634a9f817bc49c)
Refs #5497

v1.9: pingpong: selectively AV insert local address

---

util/pingpong.c

Only insert the local address into the AV if the provider supports
FI_LOCAL_COMM.  This fixes usnic with fi_pingpong.
(cherry picked from commit 3bf9513f284a89ae834dc58680634a9f817bc49c)
Refs #5497

v1.8: pingpong: selectively AV insert local address

---

prov/efa/src/efa_verbs/efa_init.c

Currently, efa_find_sysfs_devs() which check ibdev name, and will skip
a device whose name does not start with efa_. This name check is
unnecessary, because driver_init() already checks for vendor ID and
device ID, which is sufficient.
The name check will also cause problem on CentOS7 platform, when rdma-core
v27 is used. Under that case, rdma-core will rename EFA device name to
rdmap0s6.
This patch address the issue by removing the name check.

prov/efa : remove EFA device name check

---

prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_init.c

Detect the availability of CMA system calls by directly
calling process_vm_writev during EFA initialization.
Earlier, we were trying to put it in the getinfo function
of SHM provider. But there are two issues with that.
1. getinfo could be invoked anytime during the lifetime of
the application. Therefore, copy-on-write could silently
corrupt the application data if those buffers are pinned.
2. Not all providers support fork, e.g., verbs.
So we decide to move this detection in EFA_INI, as it will
be invoked once before any memory registration or libfabric
object allocation. Copy-on-write will not be a problem.
We are also working on the large message segmentation. Once
it is landed, we can delay the CMA detection till the real
communication phase between local peers. If CMA is not …

prov/efa: Detect CMA systemcall directly

---

fabtests/unit/cq_test.c

If no wait object is actually needed, use FI_WAIT_NONE instead of
FI_WAIT_UNSPEC which associates a wait object.
Signed-off-by: Firas Jahjah <firasj@amazon.com>
Signed-off-by: Daniel Kranzdorf <dkkranzd@amazon.com>

fabtests/unit: Use FI_WAIT_NONE by default

---

prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_init.c

Cherry-picking 0fc2e9955072d5cc348818131259492cda3d7b6e from master into 1.9.x, where shared-memory support was enabled by default in the EFA provider.

[1.9.x] prov/efa: Detect CMA systemcall directly

---

prov/efa/src/rxr/rxr_ep.c

Fix two bugs in the inject path that showed up with memory poisoning.

EFA packet inject bugfixes

---

prov/shm/src/smr.h
prov/shm/src/smr_ep.c
prov/shm/src/smr_msg.c
prov/shm/src/smr_progress.c

A recent commit:
371456d910cf8435fa8f5f606c4207c9a5cba47d
titled
"prov/shm: fix unexpected message on empty recv queue"
has put unexpected command into unexpected msg queue.
Because untagged recv functions (smr_recv(), smr_recvv() and
smr_recvmsg()) will not process unexpected msg queue, dead
lock can sometimes happen.
This patch fix the issue by letting untagged recv functions
progress unexpected msg queue before put smr_entry into
ep->recv_list.

prov/shm : Let non-tagged recv also progress unexpected queue

---

include/ofi_util.h
prov/rxm/src/rxm.h
prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_rma.c
prov/tcp/src/tcpx_conn_mgr.c
prov/tcp/src/tcpx_progress.c

The cause of the crash still isn't known, but this is a series of cleanups and minor fixes to the rxm and tcp providers.  The crash appears to be a use after free bug somewhere in the cmap handling, so work is being done to simplify that code path, including the progress threads.

prov/rxm, tcp: Mostly code restructuring in pursuit of identifying cause of crash

---

prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_av.c

Previously the AV remove operation focused on cleaning up connection
states so that the same process could talk to different peers that
might reuse hardware context. Some information were left intact in
the AV table which worked fine in most cases.
However, some applications rely on the FI_EADDRNOTAVAIL event to do
special handling for connection management. The leftover information
in the AV table may prevent the event from being generated. Fix by
cleaning up the removed entries and marking them as invalid.

prov/psm2: Clean up AV table entries that have been removed

---

include/ofi_util.h
man/fi_domain.3.md
man/fi_fabric.3.md
prov/util/src/util_main.c

ofi_find_fabric locks around the fabric list, but once the
lock is released, the fabric could be destroyed by the
app.  Hold the lock around accessing the fabric object.
Fixes #5530

core: Fix locking around fabric list

---

include/ofi_shm.h
prov/efa/src/efa.h
prov/util/src/util_shm.c
prov/verbs/src/fi_verbs.h

Starting from the upcoming GCC release 10, the default of -fcommon option will change to -fno-common:
In C, global variables with multiple tentative definitions will result in linker errors.
Global variable accesses are also more efficient on various targets.
This patches adds missing extern keywords to global variables in headers and declarations outside of headers when needed.
Signed-off-by: Nicolas Morey-Chaisemartin <nmoreychaisemartin@suse.com>

Fix compilation with -fno-common

---

prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_eq.c

fi_ibv_eq_remove_events() will remove all events from the EQ
that reference a specific CQ or EQ.  However, the CQ and EQ
fields in fi_ibv_eq_entry belong to a union.  There's no
guarantee that either has been set.  When the event data is
used instead (or no event data is present), then attempting to
access the eq/cq field can result in dereferencing a null
pointer.
Check the event type before dereferencing the union
members.  Rename the entry member to data, to indicate that
it is only storing data associated with the event.

prov/verbs: Fix null dereference in fi_ibv_eq_entry

---

fabtests/ubertest/uber.c

Streamlines test such that it only tests one fi_info configuration per test.
This is the full fix that was requested on a previous pr.
Error checking is also more robust and if a test fails in part of setup or communication, it will communicate that to the other process and then exit cleanly. If the error is ENODATA, ubertest will record that and then continue with all of the other tests.

fabtests/ubertest: remove extra looping from ubertest

---

prov/shm/src/smr_fabric.c

While the CQ cannot use an fd wait object, the EQ still
can. Allow the creation of an fd wait object by the user
for the EQ.

prov/shm: allow the creation of an fd wait object

---

include/ofi_shm.h
prov/efa/src/efa_fabric.c
prov/shm/src/smr_init.c
prov/util/src/util_shm.c

DL builds do not call ini/fini and will not properly
initialize or cleanup the ep_name_list.
Move the initialization out of ini and use DEFINE_LIST
to initialize.
Move the cleanup out of fini and into a cleanup function
to be called by any provider using the utility shm code.
Call this function on shm fabric cleanup.

prov/shm: move ep_name_list initialization/cleanup

---

prov/verbs/src/fi_verbs.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/ofi_verbs_priv.h
prov/verbs/src/verbs_cm.c
prov/verbs/src/verbs_cm_xrc.c
prov/verbs/src/verbs_cq.c
prov/verbs/src/verbs_dgram_av.c
prov/verbs/src/verbs_dgram_ep_msg.c
prov/verbs/src/verbs_domain.c
prov/verbs/src/verbs_domain_xrc.c
prov/verbs/src/verbs_ep.c
prov/verbs/src/verbs_eq.c
prov/verbs/src/verbs_info.c
prov/verbs/src/verbs_mr.c
prov/verbs/src/verbs_msg.c
prov/verbs/src/verbs_rma.c

The fi_ prefix is intended for external facing APIs and
data structures only.  Use a shorter prefix to improve
code readability.
This is a simple find-replace change that updates the
verbs provider in one shot.

prov/verbs: Replace fi_ibv_ prefix with vrb_

---

.travis.yml
configure.ac
prov/mrail/src/mrail_ep.c
prov/rxm/src/rxm_ep.c
prov/util/src/util_mr_cache.c

Commit 98bd1afd added the use of AC_PROG_CC_C99.  But that's not
enough to *guarantee* that we have a C99-compliant compiler.  The
Autoconf docs state that we must check $ac_cv_prog_cc_c99 to see if we
really got a C99-compliant compiler or not.
Refs #5544
FYI @rajachan @dancejic

configury: force a C99-compliant compiler

---

prov/efa/src/efa.h
prov/efa/src/efa_domain.c

The EFA MR cache limits are currently set based on a fully subscribed
c5n.18xlarge EC2 instance. However, users may not utilize all ranks when
running jobs with frameworks like OpenMP, or may use a different
instance type with more cores. In these situations performance is poor
due to cache thrashing despite the fact that the hardware will allow
additional registrations.
Instead, set limits that are near the device limits. This is safe to do
since the MR cache will attempt to evict registrations when the device
returns an error and if the cache cannot evict registrations the
segmentation code will fallback to use bounce buffers. We leave some
overhead here for bootstraping if processes are added to a job.
Users that wish to enforce memory lock limits should do so via ulimits
or the …

prov/efa: change MR cache count and size limits

---

fabtests/unit/cq_test.c

A Mellanox bug is causing this test to take too long and
resulting in memory issues/leaks when we try to open too
many CQs (around ~65k). Add a test max to not run into
system memory issues.

fabtests/cq_test: limit max CQs to test

---

prov/efa/src/rxr/rxr_init.c

Users may set FI_PROVIDER=efa which will hide the shm provider. Use the hidden
flag when querying for shm so that we can still use the shm provider in this
case.

prov/efa: use OFI_GETINFO_HIDDEN flag when querying for shm

---

include/ofi_shm.h
prov/efa/src/efa_fabric.c
prov/shm/src/smr_init.c
prov/util/src/util_shm.c

DL builds do not call ini/fini and will not properly
initialize/cleanup the ep_name_list.
Move the initialization out of ini and use DEFINE_LIST
to initialize.
Make common smr_cleanup function for code that uses
the utility shm code to cleanup the ep_name_list and
call this in the EFA provider which uses the shm provider.
Cherry-picked from commit 2c9aeb8846f620278d154c97cb1fb8470a5743ed

[v1.9.x] prov/shm: move ep_name_list initialization/cleanup

---

prov/util/src/util_poll.c

prov/util: destroy fastlock in poll_close

---

fabtests/README.md

We had a customer pulling the stale fabtest release from the README badge in the ofiwg/libfabric repo. This PR removes these stale badges.

Remove stale badges pointing to the old fabtest repo

---

prov/efa/src/efa_fabric.c
prov/efa/src/efa_msg.c

`efadv_query_device()` fetches the `inline_buf_size` of the EFA device.
If a send is within this limit and if the OFI application requests
FI_INJECT, set IBV_SEND_INLINE.

prov/efa: Post inlined send if FI_INJECT is set

---

include/ofi_mr.h
include/ofi_tree.h
prov/util/src/util_mr_cache.c
src/tree.c

Not tested.
This series restructures the mr_cache, so that ofi_mr_cache_flush() will cleanup stale entries without holding the monitor lock.  Specifically, we cannot hold the monitor lock while calling util_mr_free_entry().
However, there are still code paths that call util_mr_free_entry() while holding the monitor lock.  For example, notify, merge, cleanup, and create still call uncache_entry, which calls free_entry.  The intent is for additional patches to update uncache_entry to move the stale entries to a flush_list, and have ofi_mr_cache_flush() cleanup those entries when called.

util/mr_cache: Series of changes to avoid calling malloc/free while holding monitor lock

---

prov/efa/src/efa_mr.c

efa_mr_cache_entry_dereg() call ibv_dereg_mr() with mem_desc->mr
to deregister a memory region, if mem_desc-mr is NULL, this will
cause segmentaion fault.
This patch fix the issue by checking if mem_desc->mr is NULL,
and does not call ibv_dereg_mr() on the NULL pointer.

prov/efa : fix a bug in efa_mr_cache_entry_dereg()

---

prov/util/src/util_mr_cache.c

There is an unused variable entry of type "struct ofi_mr_entry *",
which is causing compiler warnings. This patch removes it.

util/mr_cache : remove an unused variable in ofi_mr_cache_cleanup()

---

include/windows/osd.h
info.vcxproj
info.vcxproj.filters
man/fi_info.1.md
src/shared/ofi_str.c
util/info.c

The number of environment variables can be fairly long.
Using grep on the output can help search for a variable
containing a specific string, but in doing so, it loses
the vars description.  Allow passing in a string to use
as a filter.  Only variables containing that string will
be displayed.
This removes the need for the variable prefix hack to
filter based on provider name.

fi_info: Add filter option when displaying environment vars

---

configure.ac
docs/providers
include/ofi.h
include/unix/osd.h
include/windows/osd.h
prov/efa/src/rxr/rxr_cntr.c
prov/efa/src/rxr/rxr_cq.c
prov/efa/src/rxr/rxr_ep.c
prov/netdir/src/netdir.h
prov/rxd/src/rxd_ep.c
prov/rxm/src/rxm_cq.c
prov/sockets/src/sock_cntr.c
prov/sockets/src/sock_cq.c
prov/sockets/src/sock_progress.c
prov/sockets/src/sock_wait.c
src/common.c
src/unix/osd.c

1)clock_gettime() works about 33% faster than gettimeofday().
2)Added fi_gettime_ns - it will give an oppurtunity to call to
clock_gettime() in a single function and easy to modify in
the future if it requires.
3)Added check for clock_gettime() in configure.ac and added a fallback
function on gettimeofday() for UnixOS. For WinOS, provided own
implementation.
4)common: Refactored fi to ofi prefix -- fi_gettime_xxx to ofi_gettime_xxx
5)docs/prov: changed prefix fi to ofi, add gettime_ns\us

common: Using clock_gettime() instead of gettitmeofday()

---

config/fi_provider.m4
configure.ac
include/ofi_cuda.h

~~This PR is built on https://github.com/ofiwg/libfabric/pull/5561, so ignore the rdma-core related commits and just look at the two top commits in this branch. Github doesn't handle parent-child PR relationships well across forks.~~ (The latest version has the right commits.)
@shefty @j-xiong I have added the copy functions to EFA in this case, but I see no reason why they can not be general enough and live in a ofi_cuda.h. I know we have talked about a generic peer software interface for providers that support `FI_HMEM` in the past, so until that gets defined I did not want to push this to core. Let me know what you think.
I have more changes to support `FI_HMEM` in the EFA provider lined up, but they depend on these helpers (and the parent PR), so I'll wait for these two to get merged …

core: Adding CUDA IOV copy helpers

---

man/fi_efa.7.md
prov/efa/src/efa_fabric.c
prov/efa/src/rxr/rxr_init.c

We are starting to see performance issues with the MR cache thrashing
with larger message sizes. This commit disables the cache for EFA until
we have a better handle on the issue with an acceptable solution.

prov/efa: Disable MR cache

---

prov/rxm/src/rxm_ep.c
src/fabric.c

To protect against a provider modifying the fi_info structure from
another provider, set the cur list pointer to NULL before calling
the provider's getinfo call.

core/getinfo: Set current info list to NULL when calling providers

---

configure.ac

configure: Fix typo setting LDFLAGS

---

man/fi_endpoint.3.md
man/fi_getinfo.3.md

The man pages do not clearly identify which capability bits are
tx vs rx attributes.

man: Define Tx and Rx capabilities

---

man/fi_domain.3.md
man/fi_endpoint.3.md
man/fi_getinfo.3.md

Although it's been commented that the current ordering of flags is
'spicy', it makes it hard to find flags.  Re-order them.
This changes no existing text, only the order.  However, some missing
text has been added where needed.

man: Sort flags into alphabetical order

---

man/fi_shm.7.md
prov/shm/src/smr.h
prov/shm/src/smr_init.c

The availability of CMA/ptrace_scope needs to be
known throughout shm and not just on getinfo since
it is needed to determine whether to use the fast
RMA path or not. Add an environment variable to
access this throughout shm. This also allows
applications to toggle to turn off CMA if desired.

prov/shm: refactor ptrace_scope to use globally

---

prov/shm/src/smr_init.c
prov/shm/src/smr_signal.h

Save the old action of different signals separately,
so that they can be recovered correctly.

prov/shm: Fix signal handling bug

---

prov/efa/src/efa_fabric.c

In DSO build, ofi_shm.h should be included to
declare function smr_cleanup().

prov/efa: Fix compilation warning in DSO build

---

prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_av.c

Previously the AV remove operation focused on cleaning up connection
states so that the same process could talk to different peers that
might reuse hardware context. Some information were left intact in
the AV table which worked fine in most cases.
However, some applications rely on the FI_EADDRNOTAVAIL event to do
special handling for connection management. The leftover information
in the AV table may prevent the event from being generated. Fix by
cleaning up the removed entries and marking them as invalid.
Cherry-picked from commit 7b6b34cb6a1402c7928802bf2800f7d952bff343.

[v1.9.x] prov/psm2: Clean up AV table entries that have been removed

---

prov/efa/src/efa.h
prov/efa/src/efa_av.c
prov/efa/src/rxr/rxr_ep.c

The function rxr_ep_poll_cq() call fi_cq_readfrom() on both efa_cq
and shm_cq, and get the src_addr back. For shm_cq, src_addr returned
is shm address, which is used in rxr_ep_poll_cq() as EFA address.
This patch fix the issue by introducing a shm_rdm_addr_map to efa_av,
which is filled in efa_av_insert_addr() and used in rxr_ep_poll_cq()
to convert shm address to EFA address.

prov/efa: fix a bug in rxr_ep_poll_cq()

---

man/fi_shm.7.md
prov/efa/src/efa_fabric.c
prov/efa/src/efa_mr.c
prov/shm/src/smr.h
prov/shm/src/smr_init.c
prov/shm/src/smr_signal.h

I took the liberty of pulling in two shm fixes too (CMA detection for fastpath and the signal handling fix), given we need it for EFA's use of shm. Let me know if you'd rather not take these for the 1.9.x branch.
Running some internal tests with this PR. Will move it out of draft state once the testing passes.

Fixes for 1.9.x (targeting 1.9.1)

---

configure.ac
include/ofi_epoll.h
include/ofi_util.h
prov/rxd/src/rxd_ep.c
prov/rxm/src/rxm_ep.c
prov/sockets/include/sock.h
prov/sockets/src/sock_conn.c
prov/sockets/src/sock_ep.c
prov/sockets/src/sock_ep_msg.c
prov/sockets/src/sock_progress.c
prov/tcp/src/tcpx.h
prov/tcp/src/tcpx_comm.c
prov/tcp/src/tcpx_conn_mgr.c
prov/tcp/src/tcpx_cq.c
prov/tcp/src/tcpx_ep.c
prov/tcp/src/tcpx_progress.c
prov/udp/src/udpx_ep.c
prov/util/src/util_ep.c
prov/util/src/util_wait.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_eq.c
src/common.c
src/fi_tostr.c

Progress over tcp currently requires iterating over all open endpoints seeing if there is data available  This maps to reading each open socket.  At scale, this results in a large number of 'no-op' read calls to the kernel.  Replace the progress model with epoll, and only read sockets that have data available.

tcp: Rework progress functionality

---

prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_av.c
prov/efa/src/rxr/rxr_ep.c

The function rxr_ep_poll_cq() call fi_cq_readfrom() on both efa_cq
and shm_cq, and get the src_addr back. For shm_cq, src_addr returned
is shm address, which is used in rxr_ep_poll_cq() as EFA address.
This patch fix the issue by introducing a shm_rdm_addr_map to efa_av,
which is filled in efa_av_insert_addr() and used in rxr_ep_poll_cq()
to convert shm address to EFA address.

[v1.9.x] prov/efa: fix a bug in rxr_ep_poll_cq()

---

prov/efa/Makefile.include
prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_cq.c
prov/efa/src/rxr/rxr_ep.c
prov/efa/src/rxr/rxr_pkt_entry.c
prov/efa/src/rxr/rxr_pkt_entry.h
prov/efa/src/rxr/rxr_rma.c

This patch move packet entry related structs and enums from rxr.h
to rxr_pkt_entry.h,
It also move paket entry related functions from rxr.h and rxr_ep.c
to rxr_pkt_entry.c.
It als rename functions to add a rxr_pkt_entry prefix. Such as:
rxr_ep_get_pkt_entry -> rxr_pkt_entry_alloc
rxr_copy_pkt_entry -> rxr_pkt_entry_copy
rxr_release_tx_pkt_entry -> rxr_pkt_entry_release_tx
rxr_release_rx_pkt_entry -> rxr_pkt_entry_release_rx
rxr_ep_send_pkt -> rxr_pkt_entry_send
rxr_ep_sendv_pkt -> rxr_pkt_entry_sendv
rxr_ep_inject_pkt -> rxr_pkt_entry_inject
rxr_ep_send_pkt_flags -> rxr_pkt_entry_send_with_flags

prov/efa: extract packet entry related items to a separate file

---

man/fi_efa.7.md
prov/efa/src/efa_fabric.c
prov/efa/src/rxr/rxr_init.c

This commit re-enables the MR cache in EFA. The thrashing is affecting
large-scale large-message alltoall patterns in synthetic benchmarks, but
we don't see this impacting real applications, which otherwise
benefit from the cache. The EFA device will also be increasing the
memory registration limits, which will mitigate this issue.
This reverts commit 8e7a674df51d5411d9ff5deffb23a671c925ff7a.

Revert "prov/efa: Disable MR cache"

---

prov/efa/Makefile.include
prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_ep.c
prov/efa/src/rxr/rxr_pkt_type.h
prov/efa/src/rxr/rxr_rma.c
prov/efa/src/rxr/rxr_rma.h

Each packet type need to define a header struct and some functions,
this patch move these definitions into a separate header file
rxr_pkt_type.h,
also rename the functions included in the header files to add
a rxr_pkt prefix

prov/efa: move definition of packet types to a separate header file

---

include/rdma/providers/fi_log.h
prov/util/src/util_shm.c

1. Add FI_WARN_ONCE marco 
2. Only print out warning message once if failing with shm_open

Add FI_WARN_ONCE macro

---

prov/efa/configure.m4

The current behavior does not make it obvious why configure failed when
the necessary direct verbs are not available, and needed digging in the
config.log. This commit it makes it explicit for users. The check itself
is fine as it is, given we are checking for the functionality needed and
not for a specific version.

prov/efa: Provide explicit warning when rdma-core v27 is not available

---

prov/rxm/src/rxm_ep.c

rxm_ep_post_trecv requires that we hold the ep lock.  Replace call with
rxm_ep_trecv_common, which acquires the locks.

prov/rxm: Fix locking in rxm_ep_trecvmsg

---

prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_cq.c
prov/verbs/src/verbs_ep.c

Fixes #5653
If an operation completes in error, then the only valid field
in a verbs work completion is the wr_id.  In order to determine
if a work completion corresponds to a send or receive, we need
to track it ourselves.  Allocate a vrb_context structure for
all posted receive operations (similar to the send side).  This
allows casting the wr_id to a vrb_context always to access the
necessary data stored prior to posting the work request.

prov/verbs: Fix segfault processing completions

---

man/fi_mr.3.md
prov/util/src/util_mem_monitor.c

There are reports of userfaultfd caching causing failures.  See
issue #5662.  Until those are resolved, set memhooks as the
default cache monitor.

mrcache: Set memhooks as the default caching mechanism

---

fabtests/functional/rdm_atomic.c

This patch added a call of ft_init_oob() to rdm_atomic's init_fabric()
function to enable out of band address exchange for that test.

fabtests/rdm_atomic: call ft_init_oob() from init_fabric()

---

fabtests/ubertest/uber.c

Update test_info's mr_mode in ubertest with the one returned
from the provider.

fabtest: Update test_info's mr_mode

---

man/fi_verbs.7.md
prov/verbs/src/fi_verbs.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_info.c

This also reorganizes the definitions of parameters both in the code and the man pages to clarify which parameters are for both msg and dgram eps or only one.

prov/verbs: add environment variable to select specific verbs device by name

---

fabtests/common/shared.c
fabtests/man/fabtests.7.md
fabtests/multinode/include/core.h
fabtests/multinode/src/core.c
fabtests/multinode/src/harness.c
fabtests/multinode/src/pattern.c
fabtests/scripts/runfabtests.sh
fabtests/test_configs/sockets/sockets.exclude

By specifying rma with a -C flag, the multinode tests will run all of the normal patterns over RMA instead of MSG. msg can also be specified through the -C flag, but is the default. There are a few changes to shared.c to help with the memory registration and key exchange. By having one large buffer that is divided up for each process to read and write from, fewer keys need to be exchanged to set up the RMA exchanges.

Add RMA mode to the multinode tests

---

prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_cq.c
prov/efa/src/rxr/rxr_pkt_cmd.c
prov/efa/src/rxr/rxr_pkt_type.h
prov/efa/src/rxr/rxr_pkt_type_data.c
prov/efa/src/rxr/rxr_pkt_type_misc.c
prov/efa/src/rxr/rxr_pkt_type_rts.c

This patch refactor the function rxr_pkt_handle_send_completion:
1. Extract the section handle tx_entry into a separate function
rxr_cq_handle_tx_completion().
2. Extract the handling of RTS, DATA and READRSP packet into 3
separate functions:
rxr_pkt_handle_rts_send_completion(),
rxr_pkt_handle_data_send_completion() and
rxr_pkt_handle_readrsp_send_completion().
All these functions call rxr_cq_handle_tx_completion().

prov/efa: refactor rxr_pkt_handle_send_completion()

---

include/ofi_net.h
include/ofi_util.h
prov/sockets/include/sock.h
prov/sockets/src/sock_attr.c
prov/sockets/src/sock_dom.c
prov/sockets/src/sock_ep.c
prov/sockets/src/sock_ep_dgram.c
prov/sockets/src/sock_ep_msg.c
prov/sockets/src/sock_ep_rdm.c
prov/sockets/src/sock_fabric.c
prov/tcp/src/tcpx_init.c
prov/udp/src/udpx_init.c
prov/util/src/util_attr.c
prov/util/src/util_main.c
src/common.c

Update the udp, tcp, and sockets providers to report the network and interface names.  This fixes a regression with the sockets provider.  Convert the sockets provider to use the util calls for handling fi_getinfo.
Patches are not quite ready, but posting for early evaluation in response to bug report.

prov/ip-based: Add reporting of network and interface names to getinfo

---

prov/efa/Makefile.include
prov/efa/configure.m4
prov/efa/src/efa.h
prov/efa/src/efa_ep.c
prov/efa/src/efa_fabric.c
prov/efa/src/efa_mr.c
prov/efa/src/efa_rma.c

This patch implement EFA core provider's RMA read using rdma-core WR API.

prov/efa : implement EFA core provider's RMA read

---

prov/efa/src/rxr/rxr_pkt_cmd.c

Currently, in rxr_pkt_handle_send_completion(), pkt_entry->addr
was used to get peer, after pkt_entry was released.
This patch fix the issue by adjst the sequence of operation.

prov/efa: fix a bug in rxr_pkt_handle_send_completion()

---

src/tree.c

We need to cleanup the free_list when destroying the rbmap to avoid
a memory leak.

[v1.9.x] core/tree: Fix memory leak in free_list

---

src/tree.c

We need to cleanup the free_list when destroying the rbmap to avoid
a memory leak.

core/tree: Fix memory leak in free_list

---

include/ofi_iov.h

This patch implement function ofi_total_rma_iov_len()

include/ofi_iov.h : add function ofi_total_rma_iov_len()

---

man/fi_endpoint.3.md
prov/util/src/util_attr.c

core/getinfo: Ignore invalid rx/tx caps

---

prov/tcp/src/tcpx.h
prov/tcp/src/tcpx_ep.c
prov/tcp/src/tcpx_progress.c

I noticed that the polling thread in our applicatioon
is spinning for some time after calling fi_shutdown().
Reason is that we only call fi_close() after all references
to our internal connection handling are dropped and that
can be much later than the call of fi_close() and the
FI_SHUTDOWN event handling. Our polling thread then
started to spin without ever going to sleep.
The solution here is to remove the endpoint from polling
after the TCPX_EP_SHUTDOWN flag is set and only after
another round of polling in tcpx_progress() - similar to
what the socket provider does.
Signed-off-by: Bernd Schubert <bschubert@ddn.com>

tcp provider: Early remove ep from polling after shutdown

---

prov/efa/src/efa_ep.c

this patch fixed a bug where efa_ep_progress_internal would check for
FI_EAVAIL instead of -FI_EAVAIL and fixed some of the logic surrounding error
detection on the function. EQ entries are now filled when the cq cannot be
read or when error entries cannot be read.
Signed-off-by: Nikola Dancejic <dancejic@amazon.com>

prov/efa: fixing bug with reporting cq errors and fixing logic

---

.travis.yml

!!DO NOT MERGE!!
This patch enables the thread sanitizer into Travis testing to verify invalid memory accesses.
As you can see, the TCP provider now fails multiple tests. 
We should get all these tests fixed as they reflect some bugs in the code. 
Also, I would suggest to always run all the CI tests with the address sanitizer as it works very well at reporting nasty bugs. 
PS: I'm not sure why ASAN doesn't report the symbols in the backtrace (I enabled debug mode, but it still fails). I'll try to fix it.

travis: enable address sanitizer

---

include/ofi_iov.h
src/iov.c

This patch introduce the following two functions:
ofi_consume_iov_desc(): some provider advertise FI_MR_LOCAL mode,
which require caller to provider mem_desc together with iov. In
which case, desc should be consumed together with iov.
ofi_consume_rma_iov(): as the name suggested, this function consume
rma iov.

core/iov: add ofi_consume_iov_desc() and ofi_consume_rma_iov()

---

contrib/intel/jenkins/Jenkinsfile.daily

Jenkinsfile.daily: Added timeout for daily builds.
This ensures that if a daily build hangs it will
abort itself after 4 hours of inactivity and release
resources for other builds.

Jenkins-CI: Timeout For Daily builds

---

prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_domain.c

Adds a descriptor field to later use in the datapath to identify the
peer device interface if FI_MR_HMEM is used.

prov/efa: Add descriptor for peer memory registrations

---

prov/efa/configure.m4

Currently we check the existence of max_rdma_size in
struct efadv_attr using AC_CHECK_MEMBER, which rely on CPPFLAGS.
If rdma-core is not installed in standard path, this check will
always fail.
This patch address issue by setting CPPFLAGS to include efa_prefix/include
before AC_CHECK_MEMBER(), and set it back to original value afterwards.
cr https://code.amazon.com/reviews/CR-21303694

prov/efa: include efa_prefix/include when checking struct efadv_struct

---

include/ofi_mr.h
man/fi_efa.7.md
man/fi_mr.3.md
prov/efa/src/efa.h
prov/efa/src/efa_domain.c
prov/efa/src/efa_fabric.c
prov/efa/src/rxr/rxr_init.c
prov/util/src/util_mem_monitor.c
prov/util/src/util_mr_cache.c

PR is untested.
See #5687 - MR cache use results in a deadlock when using the memhooks option.
We cannot hold the monitor lock when performing any operation which may invoke the monitor notification callback.  This is true for both the memhooks and userfaultfd monitors.  This series restructures the code holding the lock when allocating memory or registering memory (which may allocate memory).  Because the lock is necessary to serialize access to the cache, the code is modified to perform a secondary check after registering a new region, and rollback in case of a conflict.

mr_cache: Do not hold monitor lock when allocating or registering memory

---

prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_ep.c
prov/efa/src/rxr/rxr_msg.c
prov/efa/src/rxr/rxr_pkt_type_data.c
prov/efa/src/rxr/rxr_pkt_type_misc.c
prov/efa/src/rxr/rxr_pkt_type_req.c
prov/efa/src/rxr/rxr_rma.c

Two commits in prep for FI_MR_HMEM.
```
commit d8c3b6c7395c310919244efda6517e791b343336 (HEAD -> mr-desc-updates, origin/recv-desc)
Author: Raghu Raja <craghun@amazon.com>
Date:   Mon Mar 9 17:35:05 2020 -0700
prov/efa: Make rxr_inline_mr_reg() usable beyond the MR cache path
The original rxr_inline_mr_reg() was written with the MR cache usage in
mind and a world where the EFA provider did not require memory
registrations, with the upper layer use pre-registered bounce buffers.
In preparation for FI_MR_HMEM, this commit extends the function to be
more useful beyond the inline registration. It can still walk the iov to
register buffers inline, but will now do it only when a descriptor is
not provided. …
```

prov/efa: MR descriptor updates

---

prov/efa/src/rxr/rxr_pkt_type_req.c

Currently, when calling rxr_rma_verified_copy_iov(), the function
rxr_pkt_handle_write_rta_recv() and rxr_pkt_handle_fetch_rta_recv()
is using FI_SEND and FI_RECV access mode, which is incorrect and
will cause test fail if MR cache is turned off.
This patch address this issue by using correct access mode.

prov/efa: fix access mode for atomic operations

---

prov/efa/src/efa_fabric.c
prov/efa/src/efa_rma.c

Currently efa_rma_post_read() assumes iov_count and
rma_iov_count to be 1. This patch addresses the issue.

prov/efa: handle multiple sge in efa_rma_post_read()

---

prov/verbs/src/verbs_info.c

Commit 77b79ae removed the domain name check from the util
code in order to handle dynamically named domains (e.g. tcp
and udp providers).  However, verbs needs this check when
multiple devices are present, or we can match with the
incorrect device.  (Verbs forms a list of all valid domains
during initialization).  Add back in the check but directly
in the verbs code when it's searching its saved fi_info domain
list.

prov/verbs: Add check against domain name

---

prov/efa/src/rxr/rxr_pkt_type_misc.c

The recent commit a163f5673ec69 introduce a change
which caused compiler warning. This patch fixes it.

prov/efa: fix compiler warning

---

prov/efa/src/efa_domain.c

We have seen MR cache initialization failure in container,
because userfaultfd syscall is blocked by default.
Switch to the default cache monitor (memhooks), so that
MR cache can still be enabled in container.

prov/efa: Use the default cache monitor

---

prov/efa/src/rxr/rxr_cq.c

Currently rxr_cq_handle_cq_error() is checking the return of
fi_cq_readerr() against sizeof(fi_cq_err_entry), which is wrong
because fi_cq_readerr() should return either a negative error
code or number of entries it retrived.
This patch fix the issue.

prov/efa: fix a bug in rxr_cq_handle_cq_error()

---

v1.9.0/man/index.md
v1.9.1/man/index.md

man/index: Add links to missing man pages in v1.9.x

---

prov/efa/src/efa_ep.c

Currently Q Key is generated by calling srandom(time(NULL)) then
calling random(). However, it has been pointed out by @sydidelot
that calling srandom() might in some case change application behavior:
https://github.com/ofiwg/libfabric/pull/5744
https://github.com/open-mpi/ompi/issues/1877
https://github.com/pmodels/mpich/pull/2997
This patch address the issue by generating Q Key using gettimeofday
result, which set qkey to
(tv.tv_usec << 12) + tv.tv_sec
and do not call srandom()

prov/efa: introduce function efa_generate_qkey()

---

prov/efa/src/efa_domain.c

Nightly tests are failing validation checks with memhooks. Revert the
change to memhooks until we are able to determine the root cause.
This reverts commit d95b60ce12f42053280c5c29d2a963dfcf07575e.

Revert "prov/efa: Use the default cache monitor"

---

prov/shm/src/smr_av.c

smr_name() should take a peer_region, not the addr

prov/shm: fix recent av lookup bug fix

---

include/ofi.h
prov/sockets/src/sock_ep.c
prov/util/src/util_attr.c

If the wrong tx/rx caps have been set (rx-only as a tx cap, and
vice versa), we ignore them in getinfo.  Add the same ignore logic
when performing the subset checks.
This fixes a regression with MPICH.

core: Ignore invalid caps in ofi_check_attr_subset

---

prov/shm/src/smr_atomic.c
prov/shm/src/smr_progress.c

Remove an optimization that allows for some atomic
fetch operations to remotely fetch the data from the
peer using CMA before the peer actually processes the
incoming request. To be completely correct, this would
have to have a message ordering check around it to make
sure the application does not require atomic write after
read ordering. However, it is a rare use case that makes
the code more complicated so this is getting removed
rather than getting fixed to check the ordering.
This patch removes the optimization, making all atomic
fetch operations use the SMR_RMA_REQ path and also cleans
up and simplifies the code to make it more readable.
Note that applications using previous versions may be
broken if data ordering for atomic fetches is needed.
Cherry-picked from commit …

[v1.9.x] prov/shm: fix potential data ordering issue in atomic fetch path

---

prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_init.c
prov/efa/src/rxr/rxr_msg.c
prov/efa/src/rxr/rxr_rma.c

This environmental variable is used as the upper limit of
the long messge protocol. Messages whose size is larger than
this value will be using read message protocol (with firmware
support.)

prov/efa: add environmental variable efa_max_long_msg_size

---

prov/efa/src/rxr/rxr_pkt_cmd.c
prov/efa/src/rxr/rxr_pkt_type_req.c

Currently rxr_pkt_insert_addr() is called only when the source address
is FI_ADDR_UNAVAIL, this behavior will cause problem when the packet
is from a newly created EP with the same GID and QP of a previous one.
This patch address the issue by calling rxr_pkt_insert_addr() as long
as incoming REQ packet contains raw address in the header.

prov/efa: call rxr_pkt_insert_addr() if REQ packet contain raw address

---

prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_eq.c

In many-to-one connection patterns at large scale, the retry of IB CM
REQ messages can be exhausted. For XRC, this active side connect
failure can be cleaned up and the RDMA connect reissued.

prov/verbs: Add verbs retry of XRC active side connection errors

---

prov/shm/src/smr.h
prov/shm/src/smr_atomic.c
prov/shm/src/smr_ep.c
prov/shm/src/smr_msg.c
prov/shm/src/smr_progress.c
prov/shm/src/smr_rma.c

Use id (peer's addr) instead of peer id (its own addr
in peer's av) to access the peer's shm region when
progressing response entry.
To do so, struct smr_tx_entry is extended to include
the peer's addr.

prov/shm: Bugfix the id for accessing peer region

---

prov/rxm/src/rxm_cq.c

**commit 1, valgrind issue:**
```
==206074==  Address 0x7cbce7a is 378 bytes inside a block of size 360,800 alloc'd
==206074==    at 0x4C2C3C8: memalign (vg_replace_malloc.c:898)
==206074==    by 0x4C2C4C9: posix_memalign (vg_replace_malloc.c:1062)
==206074==    by 0x50F12AF: ofi_memalign (osd.h:91)
==206074==    by 0x50F1685: ofi_bufpool_grow (util_buf.c:81)
==206074==    by 0x50C18A9: ofi_buf_alloc (ofi_mem.h:449)
==206074==    by 0x50C1FD4: tcpx_xfer_entry_alloc (tcpx_cq.c:113)
==206074==    by 0x50BDC86: tcpx_alloc_send_entry (tcpx_msg.c:74)
==206074==    by 0x50BE2FB: tcpx_send (tcpx_msg.c:238)
==206074==    by 0x4E458C8: fi_send (fi_endpoint.h:291)
==206074==    by 0x4E495DF: rxm_ep_msg_normal_send (rxm_ep.c:1030)
==206074==    by 0x4E4A352: rxm_ep_emulate_inject (rxm_ep.c:1296) …
```

prov/rxm: Fixed uninitialised value

---

prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_cq.c
prov/efa/src/rxr/rxr_ep.c
prov/efa/src/rxr/rxr_msg.c
prov/efa/src/rxr/rxr_pkt_cmd.c
prov/efa/src/rxr/rxr_pkt_entry.h
prov/efa/src/rxr/rxr_pkt_type_misc.c
prov/efa/src/rxr/rxr_pkt_type_req.c
prov/efa/src/rxr/rxr_read.h

This patch let medium message protocol us descriptor if
it is available.
It includes the following changes:
1. The memory registration part of rxr_prepare_mr_send()
was extracted into a function rxr_ep_init_tx_mr_desc().
If MR cache is turned on, rxr_pkt_post_rtm() will call
it before posting medium RTM to setup descriptor.
2. The following member was added to rxr_pkt_entry:
int iov_count;
struct iovect iov[2];
void *desc[2];
Note for code simplicity, we use 2 iov: one the header,
the other for data.
3. A function rxr_pkt_data_from_tx() was added that will
set RTM packet iov_count,iov and desc if tx_entry->desc
is available
4. rxr_pkt_post_ctrl_once() was modified such that it will
call rxr_pkt_entry_sendv() if pkt_entry->iov_count > 0.

prov/efa: let medium message protcol use memory desc

---

prov/shm/src/smr.h
prov/shm/src/smr_atomic.c
prov/shm/src/smr_ep.c
prov/shm/src/smr_msg.c
prov/shm/src/smr_rma.c

Use local peer address instead of remote address
stored in cmd to get the correct peer_smr.
To do this, modify the pending->cmd after it is
copied to have the correct address.
Modified from commit ff35c6322f97feb394f01decb8fa6482b15b7f1f
By Jie Zhang zhngaj@amazon.com

[v1.9.x] prov/shm: fix peer_smr address

---

include/ofi_shm.h
man/fi_shm.7.md
prov/efa/src/rxr/rxr_atomic.c
prov/efa/src/rxr/rxr_init.c
prov/efa/src/rxr/rxr_pkt_type_misc.c
prov/efa/src/rxr/rxr_read.c
prov/efa/src/rxr/rxr_rma.c
prov/efa/src/rxr/rxr_rma.h
prov/shm/src/smr.h
prov/shm/src/smr_atomic.c
prov/shm/src/smr_ep.c
prov/shm/src/smr_init.c
prov/shm/src/smr_msg.c
prov/shm/src/smr_progress.c
prov/shm/src/smr_rma.c
prov/util/src/util_shm.c

This series of commit includes two parts
1. Added mmap-based fallback solution in shm provider if CMA is not available
2. Made corresponding change in efa provider
Note:
1. This work can be rebased onto PR #5664, once it's merged. 
2. Open this PR first for community review.
3. The fabtests for shm provider (especially fi_ubertest) takes longer time. We might need to increase the timeout value (`-N 1200` works fine on my end).

Add mmap-based fallback solution if CMA is not available

---

include/ofi_epoll.h
include/ofi_util.h
include/rdma/fi_eq.h
prov/rxd/src/rxd_ep.c
prov/tcp/src/tcpx.h
prov/tcp/src/tcpx_conn_mgr.c
prov/tcp/src/tcpx_cq.c
prov/tcp/src/tcpx_eq.c
prov/tcp/src/tcpx_progress.c
prov/usnic/src/usdf.h
prov/usnic/src/usdf_cm.c
prov/usnic/src/usdf_cq.c
prov/usnic/src/usdf_endpoint.c
prov/usnic/src/usdf_eq.c
prov/usnic/src/usdf_fabric.c
prov/usnic/src/usdf_pep.c
prov/usnic/src/usdf_progress.c
prov/usnic/src/usdf_socket.c
prov/usnic/src/usdf_wait.c
prov/usnic/src/usdf_wait.h
prov/util/src/util_cntr.c
prov/util/src/util_cq.c
prov/util/src/util_eq.c
prov/util/src/util_wait.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_cq.c
prov/verbs/src/verbs_eq.c
src/common.c

The purpose behind this series is to provide the ofi_epoll semantics over the poll() implementation directly to providers.  In scale-up testing, poll significantly outperforms epoll (by multiple factors).  So the epoll over poll implementation is exposed as a separate option that is directly callable, under a new name (ofi_pollfds).  The behavior of ofi_epoll remains the same, based on whether epoll is available or not.
Additional changes are still in the works to adapt the tcp provider to use the new ofi_pollfds.  Posting these changes for review, particularly since it updates the usnic provider to use the epoll abstraction.

core/epoll: Enables the epoll over poll abstraction for all builds

---

prov/efa/src/rxr/rxr_pkt_type_req.c
prov/efa/src/rxr/rxr_read.c

1. truncate the receiving buffer to incoming message size, this can save registered memory pages.
2. if memory regulation failed with FI_ENOMEM and MR cache is one, retry the memory registration one more time because MR cache might have released some unused MR entries.

prov/efa: two memory registration related bug fixes

---

prov/efa/src/rxr/rxr_pkt_entry.c

This patch fix a bug in rxr_pkt_entry_alloc(), it should
initialize pkt_entry->iov_count to 0. Not initializing the
variable cause pkt_entry to send as iov.

prov/efa: fix a bug in rxr_pkt_entry_alloc()

---

prov/tcp/src/tcpx_cq.c

tcpx_cq_progress() was taking cq->ep_list_lock, but was
then calling functions that required holding ep->lock.
This ended up in bad list corruption of tx_queue (and likely
also of rx queue).

prov/tcp: Fix missing ep-lock / list corruption

---

prov/efa/src/rxr/rxr_init.c

Remove "/" from the shm file name.

prov/efa: Fix shm file name

---

include/ofi_util.h
prov/rxd/src/rxd_ep.c
prov/rxm/src/rxm_ep.c
prov/shm/src/smr_ep.c
prov/tcp/src/tcpx_conn_mgr.c
prov/tcp/src/tcpx_ep.c
prov/util/src/util_wait.c

The long term goal here is for an rxm level wait set to monitor all wait objects (sockets in this case) used by the tcp level wait set *without* needing to use epoll, because epoll performance is the suck.
This continues a set of changes to the util wait code.  The changes are aimed at allowing a fid to be directly associated with a wait set.  The shm provider and yield based wait set supports this today.  These changes make this more generic, so that the underlying fid can be associated with one or more fd's as its wait object.

util/wait: Trickling of patches aimed at improve tcp performance

---

prov/efa/src/efa_fabric.c
prov/efa/src/efa_mr.c
prov/efa/src/efa_msg.c
prov/efa/src/efa_rma.c
prov/efa/src/rxr/efa_cuda.h
prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_attr.c
prov/efa/src/rxr/rxr_domain.c
prov/efa/src/rxr/rxr_ep.c
prov/efa/src/rxr/rxr_init.c
prov/efa/src/rxr/rxr_msg.c
prov/efa/src/rxr/rxr_pkt_cmd.c
prov/efa/src/rxr/rxr_pkt_type.h
prov/efa/src/rxr/rxr_pkt_type_data.c
prov/efa/src/rxr/rxr_pkt_type_misc.c
prov/efa/src/rxr/rxr_pkt_type_req.c
prov/efa/src/rxr/rxr_read.c

This is the update of 
https://github.com/ofiwg/libfabric/pull/5742
What I did is address the comments from myself and Robert:
1. Introduced helper function rxr_copy_from_tx() and rxr_copy_to_rx() to wrap rxr_cuda_copy_iov.
2. rename rxr_pkt_send_data_mr_cache to rxr_pkt_send_data_desc() and rxr_prepare_mr_send to rxr_prepare_desc_send() .

prov/efa: Handling CUDA buffers in send/recv paths (new)

---

prov/util/src/util_wait.c

Release the spinlock before returning.

util/wait: Fix locking issue in util_wait_yield_run

---

include/ofi_util.h
include/rdma/fabric.h
prov/rxd/src/rxd_ep.c
prov/rxm/src/rxm_ep.c
prov/tcp/src/tcpx_conn_mgr.c
prov/tcp/src/tcpx_cq.c
prov/tcp/src/tcpx_ep.c
prov/util/src/util_cq.c
prov/util/src/util_eq.c
prov/util/src/util_wait.c
prov/verbs/src/verbs_cq.c
prov/verbs/src/verbs_eq.c

Updates to util wait code and callers to allow direct use of struct pollfd array as a wait object type.

util/wait: More changes to support poll() as a wait call

---

prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_init.c

Since peer-peer cma check has been added recently in shm
provider, we do not need this check any more.

prov/efa: Remove CMA check during efa initialization

---

prov/efa/src/rxr/rxr_init.c

The emulation layer for RDM endpoints in the EFA provider was
overwriting the addr_format field of the caller's hints without
verifying the contents.  This would result in endpoints being
returned with address formats other than the one requested (for
example, requesting FI_ADDR_STR would result in an endpoint with
FI_ADDR_EFA address format).
This patch removes that munging.  The core efa provider already
has a check that the addr_format is either EFA or UNSPEC, so the
end result of this patch is that efa endpoints will not be
returned if the addr_format in hints is not EFA or UNSPEC.
Signed-off-by: Brian Barrett <bbarrett@amazon.com>

prov/efa: Fix addr_format handling for RDM endpoints

---

prov/efa/src/efa.h
prov/efa/src/efa_av.c
prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_msg.c
prov/efa/src/rxr/rxr_rma.c

Currently, an EP will use RDMA read on a peer only if both the EP
and the peer support RDMA read. The peer's information was received
via a handshake packet.
In the case an EP want to use RDMA read on itself, it does not
need to wait for a handshake packet. If should use RDMA as long
as it supports RDMA.
This patch introduced a flag is_self to struct rxr_peer, which
was set at efa_av_insert_addr(), and was used to determine whether
RDMA read should be used.

prov/efa: handle the case an EP want to use RDMA read on itself

---

prov/efa/src/rxr/rxr_pkt_type_data.c

A bug was introduced when we introduced the function
rxr_copy_from_tx()
The return value of that function was not checked
and there is a wrong assertion in the code.
This function was only used when MR cache was turned off,
which is why the code has been passing the tests.
This patch addressed the issue.

prov/efa: fix a bug in rxr_pkt_send_data()

---

prov/efa/Makefile.include

rxr_pkt_type_req.h and efa_cuda.h was missing in the
_efa_headers section in file Makefile.include, this
patch fixes it.

prov/efa: add missing header file to Makefile.include

---

.travis.yml

Using `make rpm` will drop the needed configure flags to use the
non-standard rdma-core installation path. Fix this so that the tarball
and rpm build test these providers as well.

travis: fix rpm build step so that efa, usnic, and verbs are built

---

prov/psm2/src/psmx2_attr.c

In the past, FI_REMOTE_CQ_DATA was a capability bit and the provider
used it to determine if a provider instance with TAG64 layout should
be enabled.
This is no longer true and the check was removed by commit 8b9ae5ba8dc.
However, some comments were left behind and they make no sense under
current context.
Remove those obsolete comments and add back the scenarios that were
previously covered by the caps bit for enabling the TAG64 layout.

prov/psm2: Remove obsolete comments

---

include/linux/osd.h
prov/psm2/configure.m4
prov/shm/configure.m4
prov/shm/src/smr_progress.c
prov/shm/src/smr_rma.c
prov/util/src/util_shm.c

When building on an older kernel without CMA for use on
systems with CMA, shm will not get built and will be disabled.
To bypass this for x86 systems, skip the configure check and
provide a wrappers for the CMA calls which call the syscall
directly.
The newly added runtime checks for CMA calls and the alternate
large message protocol for use without CMA will allow the shm
provider to run with or without CMA.

prov/shm: allow building of shm provider on older kernels

---

include/ofi.h

This patch introduce a fucntion ofi_xorshift_random() which implement
the Xorshift random number generator.

include/ofi.h: add function ofi_xorshift_random()

---

prov/verbs/src/verbs_eq.c

Need to free the connection request duplicated fi_info for a
XRC reciprocal connection request handled internally by the Verbs
provider.

prov/verbs: Fix fi_info memory leak for XRC reciprocal connections

---

prov/efa/src/rxr/rxr_msg.c
prov/efa/src/rxr/rxr_rma.c

Currently, read based message protocol is used for messages whose
size is large than
rxr_env.efa_max_long_message_size.
However, we have noticed that read message protocol is slower than
segmented message protocol if application does not provide memory
descriptor and MR cache is not enabled.
This patch make rxr_msg_post_rtm() fallback to use segmented
protocol under such condition (no descriptor and no MR cache).
This patch also make rxr_rma_post_rtw() to fallback
to segmented write protocol under same condition.

prov/efa: fallback to segmented protocol under certain condition

---

prov/verbs/src/verbs_eq.c

For SIDR Requests, the RDMA CM event status determines if
RDMA_CM_EVENT_UNREACHABLE event is reporting a reject of
the SIDR request or a error/timeout.
This prevented a Verbs retry of a SIDR connection request if
IB CM SIDR Request retries are exhausted.

prov/verbs: Fix XRC SIDR request reject/retry identification

---

prov/efa/src/rxr/rxr_rma.c

rxr_rma_post_shm_write() allocate pkt_entry and use it
as context to call fi_writemsg() on shm_ep. In the
case that fi_writemsg() failed, it did not release the
pkt_entry, causing a memory leak.
This patch address the issue by release pkt_entry in
case fi_writemsg() return an error.
It also do a little refactoring: the function name
rxr_rma_port_rtw()
is not correct, because it not only post rtw, but also
call rxr_rma_post_shm_write(). This patch rename it to
rxr_rma_post_write().

prov/efa: fix memory leak in rxr_rma_post_shm_write()

---

prov/efa/src/efa.h
prov/efa/src/efa_mr.c
prov/efa/src/rxr/rxr_read.c

rxr_read_init_iov() prepare the iov for read message
protocol by registering send buffers.
Currently, even when the send buffer was intended to local peer
it will still register the buffer for a remote peer by calling
ibv_reg_mr(), which caused performance issue.
This patch introduced a function efa_mr_reg_shm() and let
rxr_read_init_iov() to use it to register memory for local peer.

prov/efa: fix a bug of rxr_read_init_iov()

---

prov/efa/src/efa_ep.c

This patch uses the Xorshift random number generator to randomize
Q Key

prov/efa: randomization of Q Key

---

prov/util/src/util_attr.c

FI_MR_HMEM is similar to FI_MR_LOCAL, in that it specifies that device buffers
must be registered. However, it is valid for a provider to require FI_MR_HMEM
support but not FI_MR_LOCAL.
Change ofi_cap_mr_mode to not drop FI_MR_HMEM so this mr mode bit is still set
in this case.

util/util_attr: fix ofi_cap_mr_mode to not drop FI_MR_HMEM

---

prov/efa/src/rxr/rxr_init.c

When the FI_HMEM capabability is set FI_MR_HMEM is required.

prov/efa: fix getinfo path to validate FI_HMEM/FI_MR_HMEM

---

prov/verbs/src/verbs_eq.c

Add additional debug logs for identification of nodes involved in connection retries.

prov/verbs: Log XRC connection retry address information

---

prov/efa/src/efa.h
prov/efa/src/efa_av.c

In EFA, there's a variable shm_av_size, which can
be dynamically changed to cater for future instance
types that might have high #core. Currently the
default size is 128. There's another macro
EFA_SHM_MAX_AV_COUNT, which tracks the hard limit
SMR_MAX_PEERS in shm provider, and the current
value is 256. In any cases, shm_av_size cannot
be large than EFA_SHM_MAX_AV_COUNT.
Since we use shm_av_size when opening shm's av,
the returned shm fi_addr should not exceed
shm_av_size. And the assertion should check
against shm_av_size as well.

prov/efa: Error handling when shm av is exhausted

---

include/ofi_util.h
prov/rxm/src/rxm.h
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_init.c
prov/tcp/src/tcpx_conn_mgr.c
prov/tcp/src/tcpx_ep.c
prov/util/src/util_cq.c
prov/util/src/util_wait.c

This allows rxm to use pollfd based wait sets, with a control to switch from epoll to pollfd via an environment variable.  The pollfd changes the timing in such a way that some additional bugs were exposed.  Include fixes uncovered through testing.

rxm/util: A couple fixes and updates to support pollfd wait sets

---

fabtests/multinode/src/core_coll.c
include/ofi_coll.h
prov/util/src/util_coll.c

ofi_av_set_addr creates a new collective address for an av_set
by building a new coll_mc with only the group members, instead
of using the av_set's AV address.
Signed-off-by: Gengbin Zheng <gengbin.zheng@intel.com>
fixes https://github.com/ofiwg/libfabric/issues/5809

util/coll: Create collective address for an av_set correctly

---

fabtests/include/shared.h

entry.prov_errno should be passed to fi_eq_strerror/fi_cq_strerror
function call instead of entry.err

fabtests: Fix parameter passed to fi_eq_strerror/fi_cq_strerror

---

man/fi_endpoint.3.md
man/fi_getinfo.3.md
man/fi_mr.3.md
man/fi_mrail.7.md
man/fi_nic.3.md
man/fi_poll.3.md
man/fi_rstream.7.md
man/fi_rxm.7.md
man/fi_tagged.3.md
man/fi_tcp.7.md
man/fi_verbs.7.md

man: Fix spelling errors and formatting throughout man pages

---

man/fi_rxm.7.md
prov/rxm/src/rxm.h
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_init.c

In cases where a RXM endpoint is performing extensive operations
that create completion entries, it is possible for the EQ to
get starved from making progress. This change adds a check
so that after some number of consecutive CQ entries being
reaped (across many progress calls), the EQ CM progress interval
will be checked and if it has elapsed EQ progress will be made.

prov/rxm: Add EQ progression fairness to progress routine

---

prov/rxm/src/rxm_conn.c

Since RXM does not offer protection between the reading
the message provider EQ and subsequent reading of an
available error, do not log a warning if an error is
not available. The return value is still passed to the
caller so this does not change behavior.

prov/rxm: Do not log -FI_EAGAIN warning within rxm_eq_readerr

---

include/ofi_shm.h
prov/shm/src/smr.h
prov/shm/src/smr_av.c
prov/shm/src/smr_init.c
prov/util/src/util_shm.c

1. Add error handling to avoid inserting more than SMR_MAX_PEERS
addresses into shm av.
2. Add shm space size check to ensure we have enough shm space to create the basic shm structures, this is to deal with the case where users run libfabric in small shm space environment, e.g., Docker container (64M /dev/shm space by default).

prov/shm: shm space check and error handling to avoid more than SMR_MAX_PEERS insert

---

prov/efa/src/efa_av.c

Use `ofi_freealign()` to release memory allocated with ofi_memalign().

prov/efa: Use ofi_freealign() to free conn

---

man/fi_shm.7.md
prov/shm/src/smr_init.c

The shm provider defaults to a rx and tx size of 1024 to minimize
resources in the shared memory region.
Add environment variables to allow the app to toggle these sizes
if needed.

prov/shm: add environment variable to control tx and rx size

---

prov/util/src/util_mr_cache.c

If ofi_mr_cache_init_storage() fails for some reason, destroy the lock
before letting the caller free the domain resources.

mrcache: Free lock when cache is not initalized

---

prov/efa/src/rxr/rxr_init.c

rxr_reset_rx_tx_to_core() adjust core_info->tx/rx_attr->iov_limit according
to application provided info, which is not right because device
supported iov_limit is not related to application input.
Especailly, it would cause problem when application specify
tx_attr->iov_limit to 1, in this case core_info->tx_attr->iov_limit
would be set to 1, but the upper layer need at least 2 iov to do
MR cached send.
This patch remove the adjustment of core_inof->tx/rx_attr->iov_limit
from the function.

prov/efa: fix a bug in rxr_reset_rx_tx_to_core()

---

prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_init.c
prov/efa/src/rxr/rxr_pkt_type_req.c

This patch remove enable_sas_ordering and enable_atomic_ordering
from rxr_env, because ordering should be solely determining by
EP's attribute. Having an environmental variable to control
ordering is dangerous, and can cause error.
While in there, this patch also remove the check for
!(ep->core_msg_order & FI_ORDER_SAS)
from rxr_need_sas_ordering(), because we know for sure
that core EP does not support FI_ORDER_SAS.

prov/efa: remove ordering bits from rxr_env

---

prov/rxm/src/rxm_atomic.c

If the rxm_buffer_size is significantly small, the number of elements
RxM can support for a given AMO operation may be zero. For these cases,
when the user checks to see if an AMO operation is valid, return
-FI_EOPNOSUPP instead of returning FI_SUCCESS with a zero count.

prov/rxm: Return EOPNOTSUPP for zero count AMO op

---

prov/rxm/src/rxm_init.c

If rxm_buffer_size and rxm_sar_limit size are set significantly low such
that most small message operations are issued using the rendezvous
protocol, the target receive buffer may be too small to hold the
incoming rendezvous control message. This results in the core provider
raising a CQ error which causes RxM to crash on an assert. To fix this
issue, always ensure that the rxm_buffer size is greater than the
rendezvous control message.

prov/rxm: Fix rxm_buffer_size param checking

---

.gitignore
include/ofi_util.h
include/rdma/fabric.h
prov/rxm/src/rxm.h
prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_cq.c
prov/verbs/src/verbs_dgram_ep_msg.c
prov/verbs/src/verbs_domain.c
prov/verbs/src/verbs_ep.c
prov/verbs/src/verbs_msg.c
prov/verbs/src/verbs_rma.c

To mitigate some performance issues caused by packet loss due to CQ overrun, this set of changes implements an optional flow control mechanism in RxM. Utility providers that want to take advantage of this flow control should implement the new ofi_ops_flow_ctrl structure and return this struct from ops_open.  Currently, only verbs implements this interface and all other utility providers will not user credit based flow control by default.

prov/rxm: Implement support for credit based flow control

---

include/ofi.h
include/ofi_mem.h
prov/rxm/src/rxm.h
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_init.c
prov/sockets/include/sock.h
prov/sockets/src/sock_cq.c
prov/sockets/src/sock_poll.c
prov/util/src/util_av.c
prov/util/src/util_buf.c
src/common.c
src/fabric.c

prov/sockets: Convert spinlocks to mutexes.
bufpool: Fallback to normal allocations any time hugepage allocations fails.
core/rxm/av: Use a single, consistent universe size variable

sockets: Convert to mutexes.  bufpool: Hugepage fallback.  core: Add universe variable

---

configure.ac

The "ustar" tar format (POSIX.1-1988) imposes a restriction that the UID/GID is at most 2097151. Unfortunately, the configure step will *not fail* if this condition is not met - from the GNU Automake documentation:
> configure knows several ways to construct these formats. It will not abort if it cannot find a tool up to the task (so that the package can still be built), but 'make dist' will fail.
The "pax" tar format (POSIX.1-2001) supports "unlimited" UID/GID value and also supports unlimited filename lengths and an unlimited file size. The "ustar" tar format has the UID/GID restriction, but also has a maximum 8GB file size and a 256 character maximum filename length.

configure.ac: use "pax" tar format

---

include/windows/osd.h
prov/tcp/src/tcpx.h
prov/tcp/src/tcpx_comm.c
prov/tcp/src/tcpx_cq.c
prov/tcp/src/tcpx_ep.c
prov/tcp/src/tcpx_progress.c
prov/verbs/src/fi_verbs.c
prov/verbs/src/fi_verbs.h
src/windows/osd.c

verbs: Fix a minor memory leak in the verbs provider, along with updates to the surrounding code.
tcp: cleanup and renaming of struct stage_buf
windows: Handle mapping of linux socket calls to windows socket API.  The latter use 'int' for data transfers sizes, rather than size_t.

verbs: cleanup + memory leak fix, tcp: cleanup, windows: handle socket API diffs

---

include/ofi_util.h
prov/rstream/src/rstream.h
prov/rstream/src/rstream_ep.c
prov/rstream/src/rstream_init.c
prov/rxd/src/rxd.h
prov/rxd/src/rxd_init.c
prov/rxm/src/rxm.h
prov/rxm/src/rxm_attr.c
prov/rxm/src/rxm_init.c
prov/util/src/util_attr.c
util/info.c

This change modifies rxm_getinfo to return an additional set of info describing
rxm with and without FI_COLLECTIVE support.  This is necessary to enable apps
that want to use collective support without breaking apps that do not use the
mem_tag_format negotiation.

prov/rxm: fix fi_getinfo handling of FI_COLLECTIVE

---

prov/efa/src/efa.h
prov/efa/src/efa_av.c
prov/efa/src/efa_domain.c
prov/efa/src/efa_ep.c
prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_domain.c

Add a field to identify the endpoint type for the domain. Using the
domain name to identify the type does not work with the new RDMA
device naming conventions.
In addition, remove the rdm field from efa_domain since this type field
can be used instead.

prov/efa: add type field to efa_domain and rxr_domain

---

prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_cq.c
prov/verbs/src/verbs_domain.c

the fi_open_ops query should be on the domain rather than the ep
and should supply the ep as context

prov/rxm: fix flow control ops_open

---

prov/efa/src/efa.h
prov/efa/src/efa_av.c
prov/efa/src/efa_domain.c
prov/efa/src/efa_ep.c
prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_domain.c

Add a field to identify the endpoint type for the domain. Using the
domain name to identify the type does not work with the new RDMA
device naming conventions.
In addition, remove the rdm field from efa_domain since this type field
can be used instead.

[v1.10.x] prov/efa: add type field to efa_domain and rxr_domain

---

prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c
prov/verbs/src/verbs_ep.c

This set of changes addresses a few things
1. Makes sure deferred messages are cleaned up during connection shutdown.  Lingering deferred messages were sometimes being sent to the peer if there was a duplicate connection to the same peer, which happens when two peers try to connect to eachother at the same time
2. Make sure that only messages marked for repost are actually added to the repost queue
3. make sure that the credit avail counter is protected by the rx cq during verbs send

prov/rxm: credit flow control fixes

---

include/freebsd/osd.h

Add missing wrappers for CMA calls for BSD
Cherry-picked from commit 40868d289040a7629e9557fac987c79cde53ca8f

[v1.10.x] include/freebsd: add CMA wrappers

---

Makefile.am

The libtool versioning data was incorrectly set for the 1.10 release and
ended up matching the 1.9 release.  Fix this for 1.10.1.

build: Set libtool version correctly for 1.10.1 release

---

include/freebsd/osd.h

Add missing wrappers for CMA calls for BSD

include/freebsd: add CMA wrappers

---

prov/util/src/util_mem_monitor.c

Current memory monitor initialization does not allow the selection
of userfaultfd over default memhooks using FI_MR_CACHE_MONITOR.
Also log warning if requested and not available. This is a proposed 
fix for issue #5908

prov/util: Fix to allow forcing userfaultfd memory monitor

---

prov/sockets/include/sock.h
prov/sockets/src/sock_ctx.c
prov/sockets/src/sock_msg.c
prov/sockets/src/sock_progress.c
prov/sockets/src/sock_rx_entry.c

MPICH currently tests against sockets provider and we run into performance issue when message queue gets too long, say above 10k. We run progress test repeatedly in a progress wait loop. Most of these progress test will make no progress as relevant operations haven't been posted yet. When message queue is large, current sockets provider traverses entire queue in every progress test causing latency which in turn delays posting operations, exacerbates the bad performance.
This PR implements a shallow mechanism so each time progress only try match a limited number of entries and pick up where it left off in the next progress. 
However, it appears a more appropriate fix is not to try to match the entire message queue against the entire posted queue at all in progress. Rather, if we simply try …

prov/sockets: shallow progress in matching rx_buffered_list

---

prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_av.c
prov/psm2/src/psmx2_cq.c
prov/psm2/src/psmx2_ep.c
prov/psm2/src/psmx2_msg.c
prov/psm2/src/psmx2_tagged.c

The 'source' address information of a message received from the PSM2
layer contains only the PSM2 endpoint address. The information itself
is insufficient to tell whether the source is a scalable endpoint. If
source has already been inserted into the address vector, the provider
can retrieve the right fi_addr by looking into the addresses of each
SEP context. However, if the source has not been inserted into the
address vector, the generated FI_EADDRNOTAVAIL event have to assume the
address is a regular endpoint. This works fine if the address is then
inserted into the address vector and used as-is for later communication,
but can cause error if the application takes advantage of prior
knowledge and tries to use the resulting fi_addr as scalable endpoint
address.
This is improved by …

prov/psm2: Improve source address translation for scalable endpoints

---

prov/util/src/util_cq.c

The FI_MSG flag was not being set for FI_SEND message events.

prov/util: Set CQ FI_MSG flag for TX msg ops

---

include/ofi_util.h
prov/rxm/src/rxm.h
prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_domain.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_domain.c
prov/verbs/src/verbs_ep.c

This set of changes is a proposal to address #5907 and enables core providers to decide if credit based flow control should be enabled.  
With this implementation, verbs will disable flow control if shared receive queue is used.

prov/rxm: allow core providers to decide if flow control should be enabled

---

prov/rxd/src/rxd_atomic.c

rxd_atomic.c : In the rxd_atomic_inject function, the 'addr'
argument which corresponds to the remote memory address was
incorrectly used in place of dest_addr when fetching rxd_addr
from fi_addr_table. This is now corrected.
Cherrypicked from f4588e5

[v1.10.x] prov/rxd: Corrected the use of dest_addr in rxd_atomic_inject.

---

prov/rxd/src/rxd_atomic.c

rxd_atomic.c : In the rxd_atomic_inject function, the 'addr'
argument which corresponds to the remote memory address was
incorrectly used in place of dest_addr when fetching rxd_addr
from fi_addr_table. This is now corrected.

RXD: Corrected the use of dest_addr in rxd_atomic_inject.

---

prov/efa/src/efa.h
prov/efa/src/efa_device.c
prov/efa/src/efa_domain.c

We currently are limited in the number of protection domains for EFA,
which causes issues with newer versions of Open MPI that open a
Libfabric domain in both the OFI MTL and BTL for a single rank.
Although we plan to increase this limit in the future, we have to add a
workaround to reuse a protection domain if possible in the meantime. Add
a list of protection domains and reuse it during domain open.

prov/efa: reuse protection domain in same process address space

---

prov/rxd/src/rxd_atomic.c

rxd_atomic.c : In the rxd_atomic_inject function, the 'addr'
argument which corresponds to the remote memory address was
incorrectly used in place of dest_addr when fetching rxd_addr
from fi_addr_table. This is now corrected.
cherrypicked from f4588e5

[v1.9.x] prov/rxd: Corrected the use of dest_addr in rxd_atomic_inject.

---

prov/efa/src/efa_av.c
prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_atomic.c
prov/efa/src/rxr/rxr_ep.c
prov/efa/src/rxr/rxr_init.c
prov/efa/src/rxr/rxr_msg.c
prov/efa/src/rxr/rxr_pkt_cmd.c
prov/efa/src/rxr/rxr_pkt_entry.c
prov/efa/src/rxr/rxr_pkt_type_req.c
prov/efa/src/rxr/rxr_rma.c

Currently, whether to use shm was controlled by a global variable
rxr_env.enable_shm_transfer
, which means all end points behavior the same on shm usage.
However, some applications want to be able to choose shm usage when
it is enabled.
This patch allow application to do that by setting hints->caps
with FI_REMOTE_COMM and without FI_LOCAL_COMM off.
The following change has been made to the code to acheive that:
1. a flag use_shm has been added to struct rxr_ep, which will be
set in rxr_endpoint()
2. only set peer->is_local flag when ep->use_shm is true.
3. In data transmission code path, change the condtion check:
if (rxr_env.enable_shm_transfer && peer->is_local)
to
if (peer->is_local) with assert(ep->use_shm)

[v1.10.x] prov/efa: allow end point to choose shm usage

---

prov/efa/src/efa_av.c
prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_atomic.c
prov/efa/src/rxr/rxr_ep.c
prov/efa/src/rxr/rxr_init.c
prov/efa/src/rxr/rxr_msg.c
prov/efa/src/rxr/rxr_pkt_cmd.c
prov/efa/src/rxr/rxr_pkt_entry.c
prov/efa/src/rxr/rxr_pkt_type_req.c
prov/efa/src/rxr/rxr_rma.c

Currently, whether to use shm was controlled by a global variable
rxr_env.enable_shm_transfer
, which means all end points behavior the same on shm usage.
However, some applications want to be able to choose shm usage when
it is enabled.
This patch allow application to do that by setting hints->caps
with FI_REMOTE_COMM and without FI_LOCAL_COMM off.
The following change has been made to the code to acheive that:
1. a flag use_shm has been added to struct rxr_ep, which will be
set in rxr_endpoint()
2. only set peer->is_local flag when ep->use_shm is true.
3. In data transmission code path, change the condtion check:
if (rxr_env.enable_shm_transfer && peer->is_local)
to
if (peer->is_local) with assert(ep->use_shm)

prov/efa: allow end point to choose shm usage

---

prov/util/src/util_attr.c

The RxM provider was not altering the MR mode attribute based on API
version if the fi_getinfo() hints argument was NULL. Define
ofi_alter_mr_mode() to alter the MR mode attribute and have RxM call
it accordingly.
Resolves https://github.com/ofiwg/libfabric/issues/5607

prov/util: Alter provider info with NULL hints

---

libfabric.spec.in

Since SUSE packages libraries separately from tools and binaries in a
<library><version> format, when building on SUSE platforms, add a
Provides: to maintain compatibility with the SUSE packaged libfabric.
This allows this packaging to be compatible with other packages on a
SUSE system that might have a "Requires: libfabric1 >= ..." in them.
Signed-off-by: ￼Brian J. Murrell <brian.murrell@intel.com>

Add compatibility with SUSE packaging

---

Makefile.am
include/ofi_hmem.h
libfabric.vcxproj
libfabric.vcxproj.filters
prov/util/src/util_attr.c
src/hmem.c
src/hmem_cuda.c

The generalized HMEM interface allows providers to perform operations
with all supported HMEM interfaces without calling HMEM specific calls.
FI_HMEM_SYSTEM and FI_HMEM_CUDA are currently supported.

hmem: Generalized HMEM copy interface

---

include/ofi_mr.h
prov/efa/src/rxr/rxr_init.c
prov/util/src/util_mem_hooks.c
prov/util/src/util_mem_monitor.c
prov/verbs/src/fi_verbs.c
src/fabric.c

This renames the existing memory monitor init/cleanup routines to start/stop, and moves the real init/cleanup functionality out of the generic monitor call into dedicated calls.  PR has not been tested yet.

Tweak mem monitor init, cleanup, start, stop routines

---

prov/efa/src/rxr/rxr_pkt_cmd.c
prov/efa/src/rxr/rxr_pkt_entry.c
prov/efa/src/rxr/rxr_pkt_entry.h
prov/efa/src/rxr/rxr_pkt_type_req.c
prov/efa/src/rxr/rxr_pkt_type_req.h

Some recent commits added data members to struct rxr_pkt_entry and
increase its size from 64 bytes to 192 bytes. This has caused
increased cache misses and degraded bandwidth.
This patch remove data members from struct rxr_pkt_entry and make
it 64 bytes again. The removed data members include:
1. hdr_size, raw_addr, cq_data. They are used in processing
REQ packet types, we introduced the following functions:
rxr_pkt_req_hdr_size()
rxr_pkt_req_raw_addr()
rxr_pkt_req_cq_data()
to retrieve on the fly.
2. iov_count, iov and desc. They are used in sending packets and
only used inside rxr_pkt_post_ctrl_once().
We added a new struct rxr_pkt_sendv, rxr_pkt_post_ctrl_once()
will declare a rxr_pkt_sendv, rxr_pkt_init_ctrl() will initialize
it.

prov/efa: adjust struct rxr_pkt_entry

---

prov/shm/src/smr_ep.c

Current code did not release sar_fs and ep_name in smr_ep_close().
This patch address the issue.

[v1.10.x] prov/shm: fix memory leaks

---

fabtests/unit/getinfo_test.c

Currently validate_bit_combos() call fi_getinfo() in a loop, and
did not release the memory allocated by it.
This patch added call to free the info object, and only return
the last one.

fabtests/getinfo_test : fix memory leak in validate_bit_combos()

---

src/fabric.c

Changes the log level for failing to find a
loadable library from FI_WARN to FI_DBG. This reduces
the number of messages sent to the console when there
are little to no dynamically loaded libraries found.
fixes #5937

core: Change log level in dynamic prov loading

---

prov/shm/src/smr_ep.c

Current code did not release sar_fs and ep_name in smr_ep_close().
This patch address the issue.

prov/shm: fix memory leaks

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_cq.c

In some cases, RxM tries to be aggressive about when rx buffers
are reposted, such as when long running processing (RNDV) or
unexpected messages are received.  These messages are sometimes
not meant to be reposted but are still unconditionally reposted.
Now, we will check that the rx buffers are intended for reuse before
reposting.
This is another change that helps prevent cases where RxM may post
more rx buffers than the core provider can handle.

prov/rxm: optimize reposts only for msgs marked for repost

---

prov/shm/src/smr_ep.c

This patch release smr_ep->ep_name in smr_ep_close()

[v1.9.x] prov/shm: fix a memory leak

---

include/ofi_atom.h
include/ofi_signal.h
include/unix/osd.h
include/windows/osd.h

fd_signal_set() and fd_signal_reset() have an optimization
to avoid writing more than needed to the signal socket.
Now this optimization is done with counters (wcnt and rcnt)
and if the user of fd_signal (for example prov/tcp) does
not protect the call chain with its own locks a
write leak might come up filling up the socket.
Prov/tcp uses struct fd_signal through util_wait, but it
is also not easily possible to use the util_wait_fd
lock to protect struct fd_signal counters, as a lock ordering
issue comes up
Thread 14 (Thread 0x7fbaae42a700 (LWP 2623488)):
==> tries to aquire ep->lock
tcpx_try_func           at prov/tcp/src/tcpx_progress.c:657
==> holds wait_fd->lock
in util_wait_fd_try     at prov/util/src/util_wait.c:249
ofi_trywait             at prov/util/src/util_wait.c:70
fi_trywait …

ofi_signal Add a lock to protect wcnt and rcnt

---

.travis.yml

travis: Add coverity builds to Travis

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c

Some minor cleanups to make the code easier to follow.

prov/rxm: Simplification of rxm_handle_txrx_ops

---

prov/sockets/src/sock_av.c
prov/sockets/src/sock_conn.c
prov/sockets/src/sock_ep.c
prov/sockets/src/sock_progress.c

1. When detects peer disconnected, call sock_ep_remove_conn() to remove
the connection.
2. Fixes a case using 16bits av index that possibly be overflowed.
3. Takes av->table_lock in sock_av_remove().
4. Adds a few more verbose debug msg.
Signed-off-by: Xuezhao Liu <xuezhao.liu@intel.com>

prov/sockets: do sock_ep_remove_conn() when detects disconnect

---

contrib/cray/Jenkinsfile.verbs

Use stable MPICH instead of a hardcoded version.

contrib/cray: Update Jenkinsfile.verbs MPICH path

---

include/ofi.h
prov/efa/src/efa_fabric.c
prov/verbs/src/verbs_info.c
src/common.c

Move the vrb_speed() function to a common function and fix the units so that it reports bits per second. Use that function in the EFA provider to populate the fid_nic speed field.

Move vrb_speed to src/common.c and use it in EFA provider

---

prov/efa/src/efa_fabric.c
prov/efa/src/rxr/rxr_pkt_type_req.c
prov/efa/src/rxr/rxr_pkt_type_req.h

Reporting mtu size as device MTU minus the biggest EFA
provider protocol header gives applications the correct
mtu for the provider which can fully fit application's
payload

prov/efa: Report mtu size as maximum payload

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c

There are several rxm function with the prefix rxm_cq_, which have nothing
to do with the cq.  Remove the 'cq' from the prefix to make it clearer that
these are not cq related functions, and are merely handling received data.
Rename other calls to follow the more common format of 'verb-object' used
throughout the code.  The provider has a mix of function names, making it
difficult to figure out what action is being taken on what object.

prov/rxm: Rename several functions in rxm_cq

---

include/ofi_util.h
prov/rstream/src/rstream.h
prov/rstream/src/rstream_ep.c
prov/rstream/src/rstream_init.c
prov/rxd/src/rxd.h
prov/rxd/src/rxd_init.c
prov/rxm/src/rxm.h
prov/rxm/src/rxm_attr.c
prov/rxm/src/rxm_init.c
prov/util/src/util_attr.c
util/info.c

this is a port of #5851 into the v1.10.x branch

prov/rxm: fix fi_getinfo handling of FI_COLLECTIVE port to v1.10.x

---

prov/efa/src/rxr/rxr_pkt_cmd.c
prov/efa/src/rxr/rxr_pkt_entry.c
prov/efa/src/rxr/rxr_pkt_entry.h
prov/efa/src/rxr/rxr_pkt_type_req.c
prov/efa/src/rxr/rxr_pkt_type_req.h

Some recent commits added data members to struct rxr_pkt_entry and
increase its size from 64 bytes to 192 bytes. This has caused
increased cache misses and degraded bandwidth.
This patch remove data members from struct rxr_pkt_entry and make
it 64 bytes again. The removed data members include:
1. hdr_size, raw_addr, cq_data. They are used in processing
REQ packet types, we introduced the following functions:
rxr_pkt_req_hdr_size()
rxr_pkt_req_raw_addr()
rxr_pkt_req_cq_data()
to retrieve on the fly.
2. iov_count, iov and desc. They are used in sending packets and
only used inside rxr_pkt_post_ctrl_once().
We added a new struct rxr_pkt_sendv, rxr_pkt_post_ctrl_once()
will declare a rxr_pkt_sendv, rxr_pkt_init_ctrl() will initialize
it.

[v1.10.x] prov/efa: fix alignment of struct rxr_pkt_entry

---

prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_ep.c
prov/efa/src/rxr/rxr_init.c
prov/efa/src/rxr/rxr_msg.c

Commit 717f14b4db retired the RTS packet and set the inject_size to zero.
Commmit 5aa0faede started inlining sends based on the inline_buf_size we get
from efadv_query_device(). With the completions already squashed for
fi_(t)inject(), we can advertise the correct size based on the capabilities
requested and the corresponding largest header type for eager messages.

prov/efa: Advertise the correct inject_size

---

.travis.yml

Sending notifications to Sean, per discussion in
https://github.com/ofiwg/libfabric/pull/5954. If the builds work after
this, we can think about setting up a generic list with OFA.

travis: Send Coverity scan reports to the maintainer

---

contrib/intel/jenkins/Jenkinsfile
contrib/intel/jenkins/build.py
contrib/intel/jenkins/run.py
contrib/intel/jenkins/runtests.py
contrib/intel/jenkins/tests.py

build.py: added code to build mpich_test_suite.
tests.py: added class for mpich_suite.
runtests.py: added calls to run the spawn tests.
Note: Currently not enabled for psm2 provider due to errors.

Jenkins-CI: enabled spawn tests

---

prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_ep.c
prov/efa/src/rxr/rxr_init.c
prov/efa/src/rxr/rxr_msg.c

This change is causing performance regressions with certain codes.
Reverting it till we can root cause and fix it.
This reverts commit 42cb642d183126e1b6e2b3a84e070d0f2b292bc8.

Revert "prov/efa: Advertise the correct inject_size"

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_init.c

This allows optimizing rxm over tcp separately from optimizing over verbs.

prov/rxm: Allow setting tcp defaults separate from verbs

---

prov/rxm/src/rxm_domain.c

On MR registration failure, only close MR's for IOV
that were successfully registered.

prov/rxm: Adjust MR registration error path cleanup

---

include/ofi_mr.h
prov/util/src/util_mem_hooks.c
prov/util/src/util_mem_monitor.c
prov/util/src/util_mr_cache.c

~~Instead of serializing on the memory monitor's lock, serialize MR cache
accesses using the MR cache lock. This will allow the MR cache to
subscribe to multiple memory monitor's and still maintain the correct
locking.~~
Instead of having a lock per memory monitor, have a single, global lock
which all memory monitors and MR caches will use. This change enables a
future change to have an MR cache subscribe to multiple memory monitors,
one per HMEM iface type.

core/mr_cache: Rework MR cache locking

---

configure.ac
contrib/cray/Jenkinsfile.verbs
prov/util/src/util_mem_hooks.c
prov/util/src/util_mem_monitor.c

This commit introduces two new configure options for controlling
how memory monitors are used with applications by default:
--disable-uffd-monitor
--disable-memhooks-monitor
When a monitor is disabled, it cannot be selected as the default monitor
at init, or when the environment variables are read in. If a user selects a
monitor with FI_MR_CACHE_MONITOR, then the following behavior is expected:
- if the monitor is available, it becomes the default.
- otherwise, no monitor is chosen as the default monitor and caching is disabled
The behavior choice was made so that users will experience a predictable behavior
when the monitor of choice is not available.
The behavior for default cache selection has been modified. If an available monitor is
disabled, the next monitor in order (memhooks, …

prov/util: Add config options to disable monitors

---

prov/rxm/src/rxm_ep.c
prov/verbs/src/verbs_cq.c
prov/verbs/src/verbs_ep.c

The XRC SRQ and associated CQ can be closed in any order.
If the SRQ were to be closed first, then a temporary
variable is needed to release the CQ SRQ list lock.

prov/verbs,rxm: Fix possible XRC SRQ close segfault and simplify code

---

prov/verbs/src/verbs_ep.c

This change allows Verbs CQ credits to more accurately reflect the
reserved RX credits when an XRC shared context is used.
For XRC shared receive contexts, the CQ is directly associated with
the XRC SRQ. This allows the CQ credits for the RX queue to be
taken and accurately reflect the CQ credits that are available for TX
operations.

prov/verbs: Implement XRC shared RX context CQ credit reservation

---

include/ofi_util.h
prov/rstream/src/rstream_domain.c
prov/rxd/src/rxd_domain.c
prov/rxd/src/rxd_ep.c
prov/rxm/src/rxm.h
prov/rxm/src/rxm_attr.c
prov/rxm/src/rxm_domain.c
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_init.c
prov/util/src/util_attr.c

The overall objective of this series is to allow rxm to optimize differently when running over tcp versus verbs.  To support this, we need to pass the base fi_info's (supplied by the providers) into the getinfo callbacks.  Previous work by @ooststep added this for the core_to_util callback.  This expands that functionality to support the info_to_core callback.
The rxm provider is updated with verbs and tcp specific fi_info structures (in order to maintain priority of using verbs first).  When the tcp base info is detected, shared receive contexts are requested.  This greatly improves the scalability of the tcp provider.  The verbs provider still adjusted based on an environment variable.

core / rxm: Pass base fi_info to getinfo callbacks to adjust core hints

---

prov/rxm/src/rxm_ep.c

When using shared RX contexts the required message CQ size
calculated is inflated. Change so for shared RX contexts,
only the required RX CQ entries are added. The universe size
can be used to size the CQ as needed for TX.
This change has no impact on non-shared RX context usage.

prov/rxm: Update message CQ size calculation to consider SRX context

---

include/rdma/providers/fi_log.h

Subject: [PATCH] fi_log.h: save and restore the errno in FI_LOG
There are multiple occurances of something like
func()
{
ret = somefunction();
if (ret) {
FI_LOG();
return -errno
}
}
At least stated by opengroup, printf functions might
set errno on their own and the returned or used errno
might then be the wrong value from a printf function.
In the chosen solution errno is saved in the FI_LOG()
macro and not in fi_log(), in order to also exclude errno
overwrite by a possible function argument of FI_LOG, like
FI_WARN(..., "result:", function_overwriting_errno());
I.e., errno is saved before arguments are evaluated.
Signed-off-by: Bernd Schubert <bschubert@ddn.com>

fi_log.h: save and restore the errno in FI_LOG

---

prov/tcp/src/tcpx_conn_mgr.c

Reported by coverity and absolutely right - I broke the returned
error code with my recent patches, as the ofi_wait_del_fd() call
in err_del handling overwrote the return code that is supposed to
be set.

prov/tcp coverity#359028 Fix the err_entry.err value in _send_connreq

---

include/ofi_hmem.h
src/hmem_cuda.c

cuPointerGetAttribute is required for a CUDA MR cache implementation.

hmem: Support CUDA cuPointerGetAttribute

---

prov/verbs/src/verbs_cq.c
prov/verbs/src/verbs_ep.c

This reverts commit 07b53c39cb974c3715a2c72d753f7d32c0a46005.
This commit is causing the osu_allreduce benchmark to fail. Reverting
the commit while root cause is determined.
Signed-off-by: James Swaro <james.swaro@hpe.com>

Revert "prov/verbs: Simplify XRC SRQ/CQ close code"

---

include/ofi_mr.h
prov/efa/src/efa_mr.c
prov/util/src/util_mr_cache.c

This patch introduce an argument flush_lru to
ofi_mr_cache_flush_unmapped().
Currently ofi_mr_cache_flush_unmapped() does two things:
it will clear the registration in mr_cache->flush_list.
it will remove the first registration in mr_cache->lru_list
if it is not empty.
mr_cache->flush_list contains registrations whose
corresponding memory region was not mapped any more, thus
is always good to clear.
mr_cache->lru_list contains registrations whose use_cnt is 0,
but memory region is still mapped, so they can be reused.
Sometimes, caller want to clear the flush list for some
applications, but do not want to touch lru list because it
might impact performance of other applications. This patch
will allow them to do that by calling ofi_mr_cache_flush()
with flush_lru set to false.
Signed-off-by: …

util/mr_cache: add argument flush_lru to ofi_mr_cache_flush

---

prov/efa/src/efa_fabric.c

This patch fix an important typo in the warning message in
efa_atfork_callback(). "not" should be "now". The typo was
introduced because an old revision was submitted to the
v1.10.x branch.
It also fix a comment to make it consitant between v1.10.x
and master.

[v1.10.x] prov/efa: fix a typo in efa_atfork_callback()

---

include/ofi_mr.h
prov/efa/src/efa_mr.c
prov/util/src/util_mr_cache.c

This patch introduce an argument flush_lru to
ofi_mr_cache_flush_unmapped().
Currently ofi_mr_cache_flush_unmapped() does two things:
it will clear the registration in mr_cache->flush_list.
it will remove the first registration in mr_cache->lru_list
if it is not empty.
mr_cache->flush_list contains registrations whose
corresponding memory region was not mapped any more, thus
is always good to clear.
mr_cache->lru_list contains registrations whose use_cnt is 0,
but memory region is still mapped, so they can be reused.
Sometimes, caller want to clear the flush list for some
applications, but do not want to touch lru list because it
might impact performance of other applications. This patch
will allow them to do that by calling ofi_mr_cache_flush()
with flush_lru set to false.
Signed-off-by: …

[v1.10.x] util/mr_cache: add argument flush_lru to ofi_mr_cache_flush

---

contrib/intel/jenkins/tests.py

Removed spawn tests for sockets provider.
Sockets provider is throwing errors causing the
nightly builds to abort with a timeout and holding
up builds for long duration.

Jenkins-CI : remove spawn tests for sockets provider

---

prov/efa/src/rxr/rxr_pkt_type_req.c

We did not take the size of core address into
account when calculating the max_data_size, which lead to
incorrect max header size in some cases.
This patch corrected the size calculation by adding back
the size of core address.
Also added the assertion in rxr_pkt_init_eager_msgrtm()
and rxr_pkt_init_eager_tagrtm() to have better protection.

prov/efa: fix a bug in rxr_ptk_req_max_hdr_size()

---

prov/efa/src/rxr/rxr_pkt_type_req.c

We did not take the size of core address into
account when calculating the max_data_size, which lead to
incorrect max header size in some cases.
This patch corrected the size calculation by adding back
the size of core address.
Also added the assertion in rxr_pkt_init_eager_msgrtm()
and rxr_pkt_init_eager_tagrtm() to have better protection.

[v1.10.x] prov/efa: fix a bug in rxr_ptk_req_max_hdr_size()

---

man/fi_rxm.7.md
prov/rxm/src/rxm_init.c

The tcp provider will use SRX by default.  Override this default
if the user explicitly disables SRX through the environment
variable.

prov/rxm: Allow disabling SRX from tcp provider

---

include/ofi_hmem.h
src/hmem.c
src/hmem_cuda.c

ofi_get_hmem_iface() will return the fi_hmem_iface type of an address.
Needs https://github.com/ofiwg/libfabric/pull/5976

hmem: Support querying HMEM iface type

---

include/ofi_shm.h
prov/shm/src/smr.h
prov/util/src/util_shm.c

On non-debug builds, the compiler optimizes shared memory
queues out causing performance issues for the shm provider
in non-debug builds.
Declare the entire EP's region as volatile to resolve
performance issues.

prov/shm: mark smr_region as volatile

---

prov/efa/src/rxr/rxr_pkt_cmd.c
prov/efa/src/rxr/rxr_pkt_entry.c

When building libfabric with CFLAGS=-DENABLE_RXR_PKT_DUMP, it
returns an error, as rxr_ep_print_pkt function has been renamed
and replaced by rxr_pkt_print.

prov/efa: Replace rxr_ep_print_pkt by rxr_pkt_print

---

fabtests/test_configs/efa/efa.exclude

This reverts commit 99e83f1bde60b9838a8888d6e66dfb65f9750b10.
This commit excluded multi_recv test for efa because the EFA CI
did not support OOB address sync at that time.
Now the CI support OOB address sync. This patch re-enable
the test.

Revert "test_configs/efa: exclude multi_recv test"

---

contrib/intel/jenkins/tests.py

test.py: removed condition to disable shm tests for dl and
regular builds.

Jenkins-CI: Added shm tests for daily builds.

---

include/ofi_util.h
prov/efa/src/efa_av.c
prov/mrail/src/mrail_av.c
prov/rxd/src/rxd_av.c
prov/shm/src/smr_av.c
prov/util/src/util_av.c

To allow custom av entry size, add an additional field
i.e. av_entry_size to struct util_av_attr

prov/util: Add av_entry_size field to struct util_av_attr

---

prov/efa/src/rxr/rxr_pkt_type.h
prov/efa/src/rxr/rxr_pkt_type_misc.c

Currently, for read message protocol, the rx completion was wrote
after the sending of EOR packet was completed, which is too late
because the receive has completed when read is finished and impact
performance.
This patch fix that by writing rx completion when read is finished.

prov/efa: adjust timing of rx completion for read message protocol

---

include/ofi_mr.h
man/fi_mr.3.md
prov/efa/src/efa_domain.c
prov/util/src/util_mem_hooks.c
prov/util/src/util_mem_monitor.c
prov/util/src/util_mr_cache.c
prov/verbs/src/verbs_domain.c
prov/verbs/src/verbs_mr.c

This enables support for multiple memory monitors, (one per HMEM iface) per cache.

Support multiple memory monitors per cache

---

include/ofi_util.h
prov/shm/src/smr_av.c
prov/util/src/util_av.c

If addrlen is not a multiple of 8 bytes, add an offset to
align context. The offset + addrlen is stored as an additional
field, context_offset in struct util_av
Also set util_attr.addrlen back to NAME_MAX for shm

prov/util: Add context_offset to struct util_av

---

include/ofi_shm.h
prov/shm/src/smr.h
prov/shm/src/smr_av.c
prov/shm/src/smr_ep.c
prov/shm/src/smr_init.c
prov/shm/src/smr_progress.c
prov/util/src/util_shm.c

NAME_MAX (256) is defined as not including the terminating
null character in a string.
While the shm provider does use this for strings, its
max length and addrlen refer to data size not string length
and must include the terminating character. Therefore,
NAME_MAX is not fully comparable to how shm uses it.
To fix this, define SMR_NAME_MAX as 256 and use this instead
to avoid confusion with the terms.

prov/shm: redefine shm addrlen to not use NAME_MAX

---

prov/psm2/src/psmx2_atomic.c
prov/psm2/src/psmx2_av.c
prov/psm2/src/psmx2_rma.c
prov/psm2/src/psmx2_trx_ctxt.c

PSM2 Active Message calls are used for RMA and atomic operations.
Previously the return results of some of the calls were unchecked,
which may lead to application hanging on waiting for completions
when the connection is broken.
This partly addresses #5997, but a complete fix also depends on 
PSM2 calls being able to return error upon remote disconnection.

prov/psm2: Add missing return status checking for PSM2 AM calls

---

prov/tcp/src/tcpx_ep.c

The default backlog maps to 128 in socket.h.  This is too small when running
larger scale MPI jobs.  Bump to 4096, and let system limits decrease the
size if applicable.

prov/tcp: Increase listen backlog

---

prov/verbs/src/verbs_info.c

When interface entries have duplicated names, the later names are simply
dropped, leaking memory.

Fix leak of dev_name when it is a duplicate

---

contrib/intel/jenkins/tests.py

Removed shm from dl/reg builds, to investigate
fabtest failures.

Jenkins-CI: Removed shm daily builds

---

prov/sockets/src/sock_ctx.c

This happens when there is unclaimed messages at finalize. Free them to prevent leaking memory.
It is debatable that whether this is user error since users failed to post matching receive. We encountered this in a test of dynamic connection. When connection attempt fails (timeout) and we report as recoverable error to user, there seems no easy way to clean up the unexpected messages.
Potentially other lists also need cleanup.

Free any remaining buffered entries in sock_rx_ctx_free

---

include/ofi.h
prov/tcp/src/tcpx_ep.c
prov/tcp/src/tcpx_init.c
src/common.c

Context: Some applications such as IOR (with random pattern) depend
on having same initial seed across all MPI processes. Other
applications may also rely on a given pseudo random sequence.
The TCP provider calls:
- srand(getpid()): initializing a different seed per process
- rand(): changes the pseudo random sequence from the application
standpoint.
This patch serie prevents the TCP provider from interfering with the
rand() pseudo random sequence.

prov/tcp Do not alter rand() pseudo random sequence

---

fabtests/scripts/runfabtests.sh

In RHEL8, python is no longer linked to python 2. Instead, it is
preferred that the user specifies python2 or python3 (rather than
symlinking or setting alternatives). Since our scripts look to be
compatible with either version, we check for both and use python3 by
default.
This also exits the runfabtests script if python is not detected rather
than proceeding on (I have seen some unusual bugs when continuing without
python).

Fabtests: Replace python in runfabtests.sh with python3 or python2

---

prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_init.c
prov/efa/src/rxr/rxr_msg.c

This patch introduce efa_min_read_msg_size to rxr_env. This value
is used to limit the usage of the read message protocols.
Before this patch, messages whose size is larger than
rxr_env.max_medium_msg_size will be sent using read message
protocol (if both end points support RDMA read).
After this patch, messages whose size is larger than
rxrenv.efa_min_read_msg_size will be sent using read message
protocol. Messages whose size is between rxr_env.max_medium_msg_size
and rxr_env.efa_min_read_msg_size will be sent using the CTS
base long message protocol.
By default efa_min_read_msg_size is set to 1M. It can be changed
by setting the environmental variable:
FI_EFA_INTER_MIN_READ_MESSAGE_SIZE

prov/efa: introduce efa_min_read_msg_size to rxr_env

---

src/hmem.c

During HMEM initialization, when -FI_ENOSYS is returned, this is not a
failure. Instead, it is a sign libfabric does not support a given HMEM
iface type. Update ofi_hmem_init() to distinguish between a failure and
not supported.

hmem: Improve ofi_hmem_init() logging

---

fabtests/scripts/runfabtests.sh

In order to prevent some possible issues with older systems, add a check
for python in addition to python3 and python2. This should ensure
that we're backward compatible.

Fabtests: Add check for python in runfabtests.sh

---

prov/hook/hook_debug/src/hook_debug.c
prov/util/src/util_wait.c

possible use after free in error handling (hooking provider)
and fd memory leak resulting from calling wrong cleanup function

cleanups in response to coverity report

---

prov/rxd/src/rxd_cq.c
prov/sockets/include/sock.h
prov/sockets/src/sock_ep_msg.c

sockets: change spinlock to mutex to avoid blocking while holding spinlock
rxd: validate datatype value in received atomics

more coverity cleanups

---

include/ofi_indexer.h
src/indexer.c

src/indexer.c: The existing indexer interface ofi_idx_remove,
always adds a free-ed entry at the head of the free list.The new 
interface adds the free-ed entry in order based on the index.This 
ensures that subsequent inserts always happen at the lowest
available index.

ofi_indexer: Added a new interface, ofi_idx_ordered_remove.

---

fabtests/Makefile.am
fabtests/include/osx/malloc.h
fabtests/man/fabtests.7.md
fabtests/unit/mr_cache_evict.c

The new fi_mr_cache_evict unit fabtest will test a provider's capability
to evict MR cache entries. If a provider does not use the MR cache, the
test will be skipped. Different memory monitors can be tested by setting
the FI_MR_CACHE_MONITOR env variable. Currently, eviction capability is
tested for MMAP, SBRK, and BRK syscall allocations. Malloc is not used
since it wraps mmap and sbrk/brk.

fabtest: New unit MR cache evict test

---

prov/efa/src/rxr/rxr_ep.c

Move the variable 'tmp' into debug macro, as it's only
included in debug mode.

prov/efa: Bugfix compilation warning in non-debug build

---

Makefile.am
include/ofi_mr.h
libfabric.vcxproj
libfabric.vcxproj.filters
prov/util/src/cuda_mem_monitor.c
prov/util/src/util_mem_hooks.c
prov/util/src/util_mem_monitor.c
prov/util/src/util_mr_cache.c

PR to enable CUDA MR cache. Consists of two components:
~~1. Update MR cache to support multiple monitors.~~
2. Define CUDA memory monitor.
Needs ~~https://github.com/ofiwg/libfabric/pull/5976~~, https://github.com/ofiwg/libfabric/pull/6001

Cuda mr cache

---

Makefile.am
configure.ac
include/ofi_hmem.h
include/ofi_mr.h
include/rdma/fi_domain.h
libfabric.vcxproj
libfabric.vcxproj.filters
man/fi_mr.3.md
src/hmem.c
src/hmem_rocr.c

AMD ROCR is the HSA implementation used to access AMD GPUs. The following patch set introduces FI_HMEM_ROCR. In addition, memory movement ROCR functions are defined.
A future patch set will introduce the ROCR memory monitor.

Libfabric support for AMD ROCR

---

prov/rxd/src/rxd.h
prov/rxd/src/rxd_atomic.c
prov/rxd/src/rxd_cq.c
prov/rxd/src/rxd_ep.c
prov/rxd/src/rxd_msg.c
prov/rxd/src/rxd_rma.c

added a wrapper to get a pointer to a peer to be
able to add array of pointers to peers in the endpoint.

prov/rxd: added a wrapper to get a pointer to a peer

---

prov/efa/src/efa_mr.c

This patch revert d85c37935 "prov/efa: periodically flush mr cache"
Because test show there is no performance gain for that patch

prov/efa: do not call ofi_mr_cache_flush() in efa_mr_cache_regattr()

---

src/hmem_rocr.c

The incorrect ROCR ops field was being check for the dlsyms
hsa_shut_down and hsa_status_string.

hmem: Fix ROCR dlsym checking

---

fabtests/unit/mr_cache_evict.c

The binary name was called mr_cache in the usage info instead of
fi_mr_cache_evict. Fix this.

fabtests: Fix fi_mr_cache_evict usage

---

prov/util/src/util_mem_hooks.c

Previously, the `brk` invalidated a region in cache when the call
resulted in the heap growing, the changes to this function correct
that to occur when the heap shrinks.
Calls to `sbrk` can invalidate MRs on the heap but were not being
intercepted, this introduces an `sbrk` intercept to handle that case.
These changes address the `brk`/`sbrk` failures encountered when using
memhooks with the new mr_cache_evict fabtest (#6029).

util/memhooks: update brk and implement sbrk intercepts

---

prov/verbs/src/verbs_domain_xrc.c

prov/verbs: Fix non-debug enabled unused variable compiler warning

---

prov/efa/src/rxr/rxr_pkt_cmd.c

Currently in rxr_pkt_handle_send_completion(), RXR_MEDIUM_MSGRTM
and RXR_MEDIUM_TAGRTM was handle by calling
rxr_pkt_handle_long_rtm_send_completion(), which is typo. It should
be rxr_pkt_handle_medium_rtm_send_completion(). The reason this typo
did not cause problem is because the two functions have exactly same
implementation.
This function fix this issue by calling correct function.

prov/efa: fix a typo in rxr_pkt_handle_send_completion()

---

prov/util/src/util_mem_monitor.c

If libfabric is not configured with a memory monitor, the memory monitor
start operation returns -FI_ENOSYS. This should be treated as a memory
monitor not being supported instead of a start error.
Prior to this commit, ofi_monitors_add_cache() would fail when
-FI_ENOSYS is encountered. Instead, treat -FI_ENOSYS as a NULL memory
monitor and continue processing the array of memory monitors. If all
memory monitors assigned to a MR cache are NULL,
ofi_monitors_add_cache() will now return an error.
The end result is a MR cache having different combinations of valid
memory monitors based on HMEM interface type. If a memory monitor is
NULL for a given HMEM interface type, the MR cache does not support the
caching of the given HMEM interface type.

core/mr_cache: Fix initialization of multiple MMs

---

prov/tcp/src/tcpx.h
prov/tcp/src/tcpx_comm.c
prov/tcp/src/tcpx_progress.c

In tcpx_recv_hdr and tcpx_recv_msg_data, we either read from the
staging buffer if data is available, or from the socket if it is
empty.  If we empty the staging buffer, it's likely that data is
available to be read from the socket.  However, we require looping
back through the progress loop (usually returning to the app)
before checking the socket.
Update the code to immediately try reading from the socket once
the staging buffer is empty.
As part of this change, convert tcpx_recv_hdr to return ssize_t,
rather than int, since it returns the number of bytes read in the
success case.

prov/tcp: Read from socket if staging buffer is empty

---

prov/hook/src/hook_domain.c

This missing initialization was causing segfaults.

prov/hook: Initialize iface in hook_mr_regv()

---

prov/tcp/src/tcpx_progress.c

Fixes possible buffer overflow and accessing outside of array bounds.

prov/tcp: Verify that received values are in range

---

prov/util/src/util_mem_hooks.c

Use correctly sized specifier for intptr_t.

util/memhooks: Fix printf compilation warning

---

prov/tcp/src/tcpx_comm.c

prov/tcp: Fix compiler uninitialized warning

---

prov/rxd/src/rxd.h
prov/rxd/src/rxd_cq.c
prov/rxd/src/rxd_ep.c

replaced static array implementation of peers array
with an array of pointers to struct rxd_peer and the peers are
initialized during first rts sent(rxd_send_rts_if_needed) or when the first rts (rxd_handle_rts) is
received.

prov/rxd: Runtime allocation of peers.

---

include/osx/osd.h

OS X: Define ofi_process_vm_read/writev

---

man/fi_domain.3.md

Updated fi_domain man page with verbiage specifying system resources available at runtime may reduce the amount of EPs to less than what ep_cnt reports that an application is able to create

man/fi_domain: Available system resources may limit EP beyond ep_cnt

---

docs/policy
prov/udp/Makefile.include
prov/udp/libfabric-udp.spec.in
util/info.c

docs: Improve developer guideline documentation on patch submission
udp: Fix incorrect name in spec.in file
udp: Remove unused udp_shm_libs from makefile.include
fi_info: Fix help text for -g --getenv option

Minor unrelated fixes

---

fabtests/Makefile.am
fabtests/Makefile.win
fabtests/common/hmem.c
fabtests/common/shared.c
fabtests/fabtests.vcxproj
fabtests/fabtests.vcxproj.filters
fabtests/include/hmem.h
fabtests/include/shared.h

Initial device support for fabtests with L0 support
Changes:
- use fi_mr_regattr to register device memory
- general hmem_ops infrastructure mimicking libfabric structure
- add L0 configure check
- add L0 hmem ops for ZE testing

fabtests: add device support infrastructure

---

Makefile.am
include/ofi_hmem.h
include/ofi_mr.h
include/ofi_tree.h
libfabric.vcxproj
libfabric.vcxproj.filters
prov/util/src/rocr_mem_monitor.c
prov/util/src/util_mem_monitor.c
prov/util/src/util_mr_cache.c
src/hmem_rocr.c
src/tree.c

The ROCR memory monitor allows for the caching of AMD GPU buffers. The monitor works by registering a deallocation callback for subscribed GPU buffers. To prevent the registration of multiple deallocation callbacks for addresses within the same GPU memory region (design decision), the user provided GPU address is expanded to GPU memory region size, and the entire region is tracked in a RB tree. Tracked regions are cleaned up when the GPU memory region is freed or the ROCR memory monitor is stopped.
The reason I went the RB tree route instead of storing a context pointer in a MR's ofi_mr_hmem_info is since ofi_monitor_unsubscribe() is not called when a MR is freed, the list of subscribed callbacks would be continuously growing (one for each MR). These would then only be cleaned up if the …

Initial ROCR Memory Monitor

---

include/rdma/fabric.h
include/rdma/fi_domain.h
man/fi_domain.3.md

The following PR is a proposal for overriding the HMEM data movement operations a provider may used. Users defined a ```struct fi_hmem_override_ops``` structure and register the structure with a fid via ```fi_set_ops()``` with the ```FI_SET_OPS_HMEM_OVERRIDE``` string.
At this point, I am looking for feedback. I can provide a concrete example of the verbs;ofi_rxm provider using this. But, I need verbs;ofi_rxm HMEM support first https://github.com/ofiwg/libfabric/pull/5885.

Proposal: HMEM override operations

---

include/ofi_mr.h
prov/util/src/util_mr_cache.c

This field is no longer used, as subscriptions made from the cache
are always kept.  It used to be used to know when to unsubscribe.

core/mr_cache: Remove entry subscribed field

---

prov/util/src/rocr_mem_monitor.c

Use ofi_iov_end() in place of rocr_mm_entry_end_addr() for determining
the next ROCR address.

rocr_memory_monitor: Update to use common IOV code

---

prov/efa/src/efa.h
prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_atomic.c
prov/efa/src/rxr/rxr_cq.c
prov/efa/src/rxr/rxr_ep.c
prov/efa/src/rxr/rxr_msg.c
prov/efa/src/rxr/rxr_pkt_cmd.c
prov/efa/src/rxr/rxr_pkt_cmd.h
prov/efa/src/rxr/rxr_pkt_type.h
prov/efa/src/rxr/rxr_pkt_type_data.c
prov/efa/src/rxr/rxr_pkt_type_misc.c
prov/efa/src/rxr/rxr_pkt_type_req.c
prov/efa/src/rxr/rxr_pkt_type_req.h
prov/efa/src/rxr/rxr_rma.c

This patch adds true support for `FI_DELIVERY_COMPLETE`. 
It includes following changes:
1. If the sender requests `FI_DELIVERY_COMPLETE`. When sending 
eager rtm & rtw messages, medium messages, write rta messages, 
long rtw messages and long rtm messages, the corresponding new protocols will 
be used. With the new protocol, the sender will not report completion 
to application unless it receives a receipt packet sent back from the receiver.
2. It implements the backward compatibility for older libfabric versions 
which does not have true support for `FI_DELIVERY_COMPLETE`. The sender will fail 
with `FI_EOPNOTSUPP` if the sender requests `FI_DELIVERY_COMPLETE` when the 
receiver does not support it.

prov/efa: Add True Support for FI_DELIVERY_COMPLETE

---

prov/efa/src/rxr/rxr_rma.c

Currently in rxr_rma_readmsg(), when error was encountered,
the function return immediately. This is wrong because a lock
on rxr_ep->util_ep.lock has been acquired at the beginning
of the function and was not released.
This patch fix the issue by set err then "goto out", so that
the lock will be released.

[v1.10.x] prov/efa: fix a bug in rxr_rma_readmsg()

---

prov/efa/src/efa.h
prov/efa/src/efa_device.c
prov/efa/src/rxr/rxr_init.c

This patch with turn off FI_HMEM support when RDMA capability
is not available, either because device does not support or
rxr_env.use_device_rdma is 0.

prov/efa: turn off FI_HMEM support when RDMA is not available

---

prov/efa/src/efa.h
prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_atomic.c
prov/efa/src/rxr/rxr_cq.c
prov/efa/src/rxr/rxr_ep.c
prov/efa/src/rxr/rxr_msg.c
prov/efa/src/rxr/rxr_pkt_cmd.c
prov/efa/src/rxr/rxr_pkt_cmd.h
prov/efa/src/rxr/rxr_pkt_type.h
prov/efa/src/rxr/rxr_pkt_type_data.c
prov/efa/src/rxr/rxr_pkt_type_misc.c
prov/efa/src/rxr/rxr_pkt_type_req.c
prov/efa/src/rxr/rxr_pkt_type_req.h
prov/efa/src/rxr/rxr_rma.c

This is the revert for the pull request
https://github.com/ofiwg/libfabric/pull/6092.
This pull request will result in failure
in running openfoam with intel mpi U7
on 32 nodes and 128 nodes

Revert "prov/efa: Add True Support for FI_DELIVERY_COMPLETE"

---

configure.ac

On xlc, asm statements outside of function bodies are not supported. This causes a compilation error first seen with the CURRENT_SYMVER macros in `src/fabric.c`. However, the configure check for symver support uses AC_TRY_LINK and places the asm statement in the main() loop, so the configure check passes on xlc. This PR moves the asm statement into the 'include' argument of the AC_TRY_LINK macro. The build now succeeds using xlc, and symver support detection is unchanged on gcc (i haven't tested other compilers.)

Move symver check out of main() in configure check

---

prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_attr.c
prov/efa/src/rxr/rxr_init.c

The provider version between different endpoint types in EFA differred.
This fix synchronizes the version numbers.

prov/efa: Bugfix for prov version

---

prov/efa/src/rxr/rxr_msg.c

This PR make it such that read message protocol is used for all
GPU memory, regardless it size.
This is to address the issue:
https://github.com/ofiwg/libfabric/issues/6124

prov/efa: use read message protocol for all GPU memory

---

prov/shm/src/smr_signal.h

The shm signal handler should call the original handler inline with the same siginfo_t info object, instead of raising a new signal.
This is to fix an issue found with level zero which also register a page fault signal handle for SIGSEGV on DG1.

shm: fix signal handler function calling the original handler

---

prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_cq.c
prov/efa/src/rxr/rxr_pkt_cmd.c
prov/efa/src/rxr/rxr_pkt_cmd.h

This patch adds a function called `rxr_pkt_wait_handshake`,
which sends a eager rtw packet with no data and keep
calling rxr_ep_progress_internal() until rxr_peer->flags
has the HANDSHAKE_RECEIVED flag.
This function is used for any extra feature that does
not have an alternative. It can be used to check
whether the peer support the extra feature and
ensures its backwards compatbility.

prov/efa: Add a Function for Handshake Triggering

---

contrib/intel/jenkins/build.py

Changed the shmem build to source the ISx, PRK and uh from
prefetched repositories instead of attempting to clone run time.
This is done since shmem build is throwing https errors while
cloning these repos on the fly.

CI/Jenkins: changed build code for shmem tests due to git clone issues

---

prov/util/src/util_mr_map.c

Set iface and device when calling util regattr

prov/util: fix uninitialized variable

---

contrib/cray/Jenkinsfile.verbs
contrib/cray/bats/batsgenerator.sh
contrib/cray/bats/benchmark.template
contrib/cray/bats/imb.bats

Included additional parameters constraining IMB tests to minimize amount of time test takes. Additionally extended applications timeout cutoff in Jenkinsfile.verbs file to avoid timeout failure.

contrib/cray: Update IMB parameters

---

prov/efa/src/rxr/rxr_attr.c

The EFA provider is missing op_flag 'FI_MULTI_RECV' in rx_attr, which is
required by fabtest fi_multi_recv, so adding it back.

prov/efa: Add the missing op_flag FI_MULTI_RECV

---

prov/efa/src/rxr/rxr_pkt_type_data.c
prov/efa/src/rxr/rxr_pkt_type_req.c

Fix compilation warnings introduced by recent PR
that added device field to ofi_copy_*_hmem_iov calls.
Switch in EFA/rxr passes in NULL for uint64_t instead of 0
causing a compilation warning - change to 0.

prov/efa: fix compilation warnings

---

include/ofi_mr.h
prov/shm/src/smr.h
prov/shm/src/smr_progress.c
prov/sockets/src/sock_mr.c
prov/util/src/util_mr_map.c

Fixes compile warnings in smr provider
Updates util and sockets providers to handle fi_mr_attr backwards compatibility.  Specifically, do not access new HMEM related fields unless FI_HMEM capability has been requested by the app.  And do not access auth fields unless API version is 1.5 or greater.

smr: Fix compile warnings, util/sockets: Handle fi_mr_attr compatibility

---

Makefile.am
configure.ac
include/ofi_hmem.h
include/rdma/fi_domain.h
libfabric.vcxproj
man/fi_mr.3.md
src/hmem.c
src/hmem_ze.c

- Add FI_HMEM_ZE to libfabric API
- Add ZE library and header configure check and option for non-default installation location
- Add ZE hmem_ops

rdma/fi_domain, src/hmem_ze: L0 support

---

prov/efa/src/rxr/rxr_pkt_cmd.c

Currently, rxr_pkt_wait_handshake() would post a EAGER RTW, and
wait for 1 second for handshake to arrive. If the handshake packet
did not arrive in time, rxr_pkt_wait_handshake() will return FI_ETIMDOUT
Because receiver can only send a handshake back when the the progress
engine was called. The time for sender to get handshake is arbitrary, and
it is normal that sender did not receive handshake in time.
This patch made a change that if the sender did not receive handshake
in time, rxr_pkt_wait_handshake() would print a warning and return
-FI_EAGAIN. The application will then retry the send later.

prov/efa: rxr_pkt_wait_handshake() to return -FI_EAGAIN when timeout

---

fabtests/Makefile.am
fabtests/Makefile.win
fabtests/common/hmem.c
fabtests/common/hmem_ze.c
fabtests/common/shared.c
fabtests/configure.ac
fabtests/fabtests.vcxproj
fabtests/fabtests.vcxproj.filters
fabtests/include/hmem.h

- add L0 configure option for non default location and ZE library/header check for compilation
- add L0 hmem_ops and command line option for enabling testing

fabtests/hmem_ze: add L0 fabtests support

---

include/ofi_indexer.h
prov/rxd/src/rxd.h
prov/rxd/src/rxd_atomic.c
prov/rxd/src/rxd_av.c
prov/rxd/src/rxd_cq.c
prov/rxd/src/rxd_ep.c
prov/rxd/src/rxd_msg.c
prov/rxd/src/rxd_rma.c
src/indexer.c

- replaced peers array in rxd_ep to an index_map based implementation. 
- replaced fi_addr_table in rxd_av to an indexer based implementation.

prov/rxd: replacing statically allocated arrays with ofi index_map and ofi indexer.

---

include/ofi_hmem.h
src/hmem_cuda.c

During cuda_hmem_init(), attempt to initialize the CUDA driver. If no
CUDA devices are found, treat this CUDA error as CUDA not being
supported by libfabric. If any other error, except for CUDA_SUCCESS, is
returned, treat this as libfabric CUDA error.
Instead of treating the failure to dlopen CUDA runtime as a error
(ENODATA), assume the library could not be found and have libfabric
treat this as CUDA not being supported.

CUDA initialization updates

---

fabtests/common/shared.c

Or in FI_MR_HMEM to signal full HMEM support
to provider

fabtests/common: add FI_MR_HMEM

---

include/ofi_mr.h
prov/util/src/util_mr_cache.c

By storing the device in ofi_mr_info, providers can store the device
with the MR when the MR cache allocates a new MR.

core/mr_cache: Store HMEM device in MR entry info

---

prov/efa/src/efa_fabric.c
prov/efa/src/efa_mr.c
prov/efa/src/rxr/rxr_init.c

Two commits here, one to fix the capability bits internally so that we can look at the values in util_domain and another to fix the actual issue.

prov/efa: Fix FI_HMEM backwards compat

---

prov/psm2/src/psmx2_av.c

Use fi_log() directly so that the message explaining the fatal error
is always generated. This can save debugging time.

prov/psm2: Always generate log message for fatal errors

---

prov/util/src/util_shm.c

There is a case where an endpoint inserts itself into
the AV, and starts the CMA check against itself, thus
getting an incorrect CMA check result in a system which
has ptrace protection on.
Fix it by skipping the CMA check against itself.

prov/shm: Fix a CMA check bug

---

prov/efa/src/rxr/rxr_init.c

rxr_info_to_rxr() did not check if hints->domain_attr is NULL
before using hints->domain_attr->mr_mode. This PR fixes it.

prov/efa: fix a bug in rxr_info_to_rxr()

---

fabtests/common/hmem.c

If ft_hmem_init() failed, various fabtests would still call
ft_hmem_cleanup() as a part of cleanup. This can lead to segfault
issues especially if the HMEM library was dlopened. To prevent this,
only run the HMEM iface specific cleanup routine if ft_hmem_init() was
successful.

fabtests: Skip HMEM cleanup if not initialized

---

prov/efa/src/rxr/rxr_pkt_cmd.c

This reverts commit 2192cb97e65e98694259a938a6193fb872ebc2c1.
That commit caused rxr_pkt_req_raw_addr() to be called on an
unsupported packet entry, which will fail because the end
point does not know the header length of the packet.

prov/efa: revert "ignore unsupported req packets instead write error"

---

include/ofi_hmem.h
src/hmem.c

One thing I want to do with the internal ofi_copy_to_hmem_iov() and ofi_copy_from_hmem_iov() functions is to align these function signatures with the functions defined in struct fi_hmem_override_ops. This allows a provider to just update an HMEM op table instead of having to have branching logic to determine which HMEM op to use.
I'm open for suggestions on how to better keep these functions aligned.

hmem: Align ofi_copy_to_hmem_iov() to override op

---

fabtests/common/hmem_rocr.c
fabtests/include/shared.h

ROCR memset has been updated to use hsa_amd_memory_fill(). Since
hsa_amd_memory_fill() requires 4-byte alignment, any unaligned data
which needs to be memset is done with ROCR memcpy.

fabtests: Improve ROCR memset execution time

---

include/ofi_net.h
prov/util/src/util_main.c
src/common.c

When collecting the list of addresses available in the system, also
record if the address supports local and/or remote communication.
When fi_getinfo is called, a list of fi_info structures is created
based on the provider's base fi_info list.  That list may be expanded
in order to report all addresses that are usable to the app.  For
example, see udpx_getinfo -> ofi_ip_getinfo -> util_getinfo_ifs.
The list of available addresses in the system is created for each
provider through ofi_get_list_of_addr.  When constructing that list,
the loopback addresses are appended to the end of the list.
Currently, regardless of the application request, one fi_info
is created for each address and returned to the user.  This can
result in returnin a loopback address to the app even though it
requests …

core/net: Mark if addresses support local/remote communication

---

prov/util/src/util_shm.c

Acquiring the lock right after initialization
provides no protection. It was originally placed
there to protect peers from accessing the shared
memory region before all resources were initialized.
Use PID instead. ftruncate will set the shared memory
to 0 (including the PID). Move the setting of the PID
last to protect the initialization of resources.
The peer mapping (map_to_region) already checks for
!PID and does not finish mapping until the PID has
been set.

util/shm: replace lock with PID setting

---

prov/rxd/src/rxd.h
prov/rxd/src/rxd_ep.c

removed the fastlock_tryacquire for ep lock in the rxd_peer and
rxd_create_peer functions since all code paths calling these functions
already hold the ep lock.

prov/rxd: remove redundant calls to fastlock_tryacquire.

---

prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_ep.c

When we are enabling flow control, we artificially inject
a credit so that the credit messaging itself is not blocked
by a lack of credits.  To counter this, we will adjust the number
of credits we send the first time by initializing to -1.

prov/verbs: account for off-by-one credit initialization

---

prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_cm_xrc.c
prov/verbs/src/verbs_domain_xrc.c

XRC INI QP connection state is maintained in a RBTree
at the XRC domain. Connections can be shared among
all endpoint created using that domain; the destination
address maps to the shared XRC INI QP connection object.
This commit fixes the XRC INI QP connection object locking
to handle the case where message EP are not all bound to
the same EQ (and hence EQ locking is insufficient).
For example, when there are multiple RxM EP created using
the same RxM/Verbs domain.
This fix is rather course grain and will be subsequently
improved with finer grain locking to improve performance.

prov/verbs: Fix XRC transport shared INI QP locking

---

prov/sockets/src/sock_progress.c

If several messages are received immediately after a connection has been
established, the AV index for the connection may not be set when new
Rx process entries are initialized.  The result is that those messages may
be associated with the wrong data buffer due to the address being set to
FI_ADDR_UNAVAIL.
To handle this case, see if the pe_entry address has been set when handling
the receive.  This allows the first message to be processed completely, which
can set the av_index.  Other received messages will then have the av_index
set correctly.
This problem has shown up on BSD systems.

prov/sockets: Retry address lookup if not set

---

include/ofi.h
prov/udp/src/udpx_init.c
src/fabric.c

Allow core providers to prevent utility provider layering by adding a
flag to the fi_prov_context structure.

core: add disable_layering flag, prov name fixups

---

prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_ep.c

This patch add the following functions:
rxr_ep_raw_addr()
rxr_ep_raw_addr_str()
rxr_peer_raw_addr()
rxr_peer_raw_addr_str()
which return raw address of an end point and its peers.
They can be useful for debug.

prov/efa: add functions to print self and peer's raw address

---

prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_ep.c

I was seeing an osu_bw segfault that appeared with commit 220af33. I modified to avoid making an int64_t (-1) and uint64_t (UINT64_MAX) comparison it introduced. When flow control is not enabled when using SRQ, vrb_post_send() could still send credits due to this comparison.

prov/verbs: Fix disablement of RQ flow control

---

prov/verbs/src/fi_verbs.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_cm.c
prov/verbs/src/verbs_cm_xrc.c
prov/verbs/src/verbs_domain.c
prov/verbs/src/verbs_domain_xrc.c
prov/verbs/src/verbs_ep.c
prov/verbs/src/verbs_eq.c
prov/verbs/src/verbs_info.c

Reduce verbs provider message EP memory consumption by not duplicating
and saving the fi_info passed. Instead extract only what is required
from the fi_info. This results in a memory savings of about 750 bytes
per verbs message endpoint, which can result in saving GBs of memory per
node when utilizing all-to-all connectivity at a large scale.

prov/verbs: Reduce overall memory footprint in a fully connected fabric

---

fabtests/common/shared.c
fabtests/include/hmem.h
prov/shm/src/smr.h
prov/shm/src/smr_progress.c
prov/shm/src/smr_rma.c

Fabtests:
- remove extra allocation
- check host allocation properly
- parse size option correctly
Shm:
- Loop CMA calls for large transfers to avoid CMA copy limit

fabtests, prov/shm: fabtests and shm provider fixes to support very large transfers

---

contrib/cray/Jenkinsfile.verbs

In Jenkinsfile.verbs, evn should be env.

contrib/cray: Fix variable spelling error

---

include/ofi_bitmask.h
include/ofi_lock.h

Small changes to eliminate warnings that are generated under certain versions of gcc.
Changing cur to a size_t avoids a compare mismatch with mask.size
Adding (void)lock to avoid generating warnings about unused parameters when ENABLE_DEBUG is not set.

Fix warnings generated in the include file

---

Makefile.am
configure.ac
include/ofi_hmem.h
src/hmem_cuda.c
src/hmem_cuda_gdrcopy.c

This patch added gdrcopy as an alternative mechanism for cuda memory
copy to cudaMemcpy. It is to address the issue:
https://github.com/ofiwg/libfabric/issues/6124
which is using cudaMemcpy can cause deadlock when application lauches
kernel on the targeted buffer.
This patch include the following changes:
1. Two arguments --with-gdrcopy and --enable-gdrcopy-dlopen was
added to the configure script. User are expected to used them
together with the --with-cuda argument.
2. Four functions:
cuda_gdrcopy_hmem_init(),
cuda_gdrcopy_hmem_cleanup(),
cuda_gdrcopy_from_dev(),
cuda_gdrcopy_to_dev(),
was implemented and was called by repective cuda_hmem functions
3. Two additional functions:
ofi_hmem_cuda_dev_register() and
ofi_hmem_cuda_dev_dereigster()
are added. To use gdrcopy, user need to call …

hmem_cuda: add gdrcopy as an alternative mechanism for cuda memory copy

---

prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_ep.c

The functions:
rxr_ep_raw_addr_str() and rxr_ep_peer_addr_str()
return types are "char *", which is causing compilation warning.
This patch change the return type to "const char *" to fix it.

prov/efa: fix signature of function to avoid compilation warning

---

prov/efa/src/rxr/rxr_ep.c

Commit a6ce2bd01515fa06e643cecb051341c7ef1f3ed3 introduced bugs in creation of rx_ooo_pkt_pool and rxr_unexp_pkt_pool:
This PR contains 2 commits: the first one revert the commit. The 2nd one implement the feature correctly.

prov/efa: fix bugs in creation of rx_ooo_pkt_pool and rxr_unexp_pkt_pool

---

contrib/cray/Jenkinsfile.verbs

In the "Install Libfabric Build" stage, fix the usage of the BUILD_LIBFABRIC variable.

contrib/cray: Fix BUILD_LIBFABRIC usage.

---

fabtests/common/shared.c
fabtests/include/shared.h

Change fill_buf and check_buf to use size_t instead of ints
for filling buffers larger than 2GB

fabtests/common: fix large transfer data validation

---

fabtests/common/shared.c

To test device->host transfers, check for FI_HMEM
enabling rather than device usage.

fabtests/common: fix device OOB enabling

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_atomic.c
prov/rxm/src/rxm_attr.c
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_domain.c
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_init.c
prov/rxm/src/rxm_rma.c

For RXM support to be enabled, the core provider must support FI_HMEM and FI_MR_HMEM. To support a core provider that does not require FI_MR_HMEM to be would require rework to RXM core provider discovery.
If RXM FI_HMEM is enabled, FI_COLLECTIVE is always disabled due to the collective util layer not supporting device buffers. With this implementation, FI_HMEM takes precedence over FI_COLLECTIVE. This results in the user having to explicitly request FI_COLLECTIVE. I'm not sure if we want it the other way around or not.
RXM has the capability to operate with and without FI_MR_LOCAL. This functionality has been extended to FI_MR_HMEM. Currently, I have it setup such that the only supported combinations of FI_MR_LOCAL and FI_MR_HMEM is either none or FI_MR_LOCAL | FI_MR_HMEM. Not sure if we …

RXM HMEM Support

---

prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_ep.c
prov/efa/src/rxr/rxr_pkt_cmd.c
prov/efa/src/rxr/rxr_pkt_cmd.h
prov/efa/src/rxr/rxr_pkt_entry.h
prov/efa/src/rxr/rxr_pkt_type.h
prov/efa/src/rxr/rxr_pkt_type_data.c
prov/efa/src/rxr/rxr_pkt_type_misc.c
prov/efa/src/rxr/rxr_pkt_type_req.c
prov/efa/src/rxr/rxr_pkt_type_req.h
prov/efa/src/rxr/rxr_read.h

This patch use fi_read instead of cudaMemcpy() to copy data to gpu buffer. This change is because cudaMemcpy()
can cause deadlock, when the EFA provider is used by a NCCL plugin.
Related GitHub issue:
https://github.com/ofiwg/libfabric/issues/6124
The core change is to extend the function rxr_pkt_proc_data(), which will copy data to recieving buffer for all packets that
may contain data.
Each packet type implements a handler function to handle data copied event.
If recieving buffer is on host memory, rxr_pkt_proc_data() will copy data then call the handler fucntions.
If receiving buffer is on GPU memory, rxr_pkt_proc_data() will post a read, and the progress engine will call the handler functions.

prov/efa: use fi_read to copy data to gpu buffer

---

prov/rxm/src/rxm_attr.c
prov/rxm/src/rxm_init.c

Disable FI_HMEM support from rxm by removing the capability bits.
This fixes a regression where rxm over verbs fails CI validation.

prov/rxm: Revert HMEM changes to capability bits

---

prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_ep.c
prov/efa/src/rxr/rxr_pkt_cmd.c
prov/efa/src/rxr/rxr_pkt_cmd.h
prov/efa/src/rxr/rxr_pkt_entry.h
prov/efa/src/rxr/rxr_pkt_type.h
prov/efa/src/rxr/rxr_pkt_type_data.c
prov/efa/src/rxr/rxr_pkt_type_misc.c
prov/efa/src/rxr/rxr_pkt_type_req.c
prov/efa/src/rxr/rxr_pkt_type_req.h
prov/efa/src/rxr/rxr_read.h

This PR revert two recent commits:
76b77fb: register memory of rx_ooo_pkt_pool and rx_unexp_pkt_pool
We noticed registration of rx_ooo_pkt_pool can fail when running some test
f8fb944: use fi_read to copy data to gpu buffer
This commit depend on 76b77fb

prov/efa: Revert 2 commits

---

contrib/cray/bats/batsgenerator.sh
contrib/cray/bats/benchmark.template
contrib/cray/bats/imb.bats

The bats generator scrip will now pass the FI_ environment variables as one unit:
A level of indirection has been added for the FI_* environment variables to
facilitate simpler and more accurate modifications in the future.  Additionally,
the '-iter' flag option has been added as an optional parameter to the script
since it is not used in every test:
./batsgenerator.sh <TEST_SUITE> <BENCHMARK> <NUM_RANKS> <RANKS_PER_NODE> <BATS_FILE> [-iter count]
Signed-off-by: Patrick Bueb <patrick.bueb@hpe.com>

contrib/cray: Updating batsgenerator.sh script

---

prov/shm/src/smr_attr.c
prov/shm/src/smr_init.c

To support FI_HMEM, shm needs the mr_mode FI_MR_HMEM.
Since adding a mode restriction could break apps that
do not support FI_MR_HMEM, duplicate the infos to show
one with FI_HMEM and FI_MR_HMEM and one without either.

prov/shm: duplicate infos for FI_HMEM

---

include/ofi_shm.h
prov/shm/src/smr.h
prov/shm/src/smr_atomic.c
prov/shm/src/smr_av.c
prov/shm/src/smr_comp.c
prov/shm/src/smr_ep.c
prov/shm/src/smr_msg.c
prov/shm/src/smr_progress.c
prov/shm/src/smr_rma.c
prov/util/src/util_shm.c

To completely separate shm index from fi_addr (which are no longer interchangeable), change all definitions and usages of shm indeces to int64_t from fi_addr or ints.
Various bug fixes included because of the clarification

prov/shm: change shm index references to int64_t

---

src/common.c

src/common: fix segfault on print if address is NULL

---

include/ofi_shm.h
prov/shm/src/smr.h
prov/shm/src/smr_av.c
prov/shm/src/smr_ep.c
prov/shm/src/smr_msg.c
prov/shm/src/smr_progress.c
prov/util/src/util_shm.c

Rename all uses of shm indices/addrs to ids to
avoid confusion with fiaddrs
Fix one bug where smr_map_to_endpoint was getting
called with "index" which was an fiaddr, not id

prov/shm: renaming addr/id/index for clarity

---

fabtests/common/shared.c
fabtests/include/hmem.h
prov/shm/src/smr_attr.c
prov/shm/src/smr_init.c
src/common.c

fabtests FI_HMEM bugs:
- double memory allocation with ft_hmem_alloc
- fix malloc error checking/return
- fix OOB enabling for device->host transfers
shm:
- duplicate fi_infos for FI_HMEM, FI_MR_HMEM support
common:
- fix address print segfault

[v1.11.x] fabtests, prov/shm, common: cherry picks 

---

prov/efa/src/rxr/rxr_pkt_type.h
prov/efa/src/rxr/rxr_pkt_type_misc.c

Currently, we release the rx_entry after the receiver posts EOR packet
and it's failed with FI_EAGAIN, which results in that the EOR packet
does not get re-posted later, and the sender can not write send
completion accordingly.
This patch fixes the above issue by only releasing rx_entry of EOR
packet in FI_SUCCESS case.

prov/efa: Do not release rx_entry of EOR packet in EAGAIN case

---

prov/efa/src/rxr/rxr_pkt_type.h
prov/efa/src/rxr/rxr_pkt_type_misc.c

Currently, we release the rx_entry after the receiver posts EOR packet
and it's failed with FI_EAGAIN, which results in that the EOR packet
does not get re-posted later, and the sender can not write send
completion accordingly.
This patch fixes the above issue by only releasing rx_entry of EOR
packet in FI_SUCCESS case.

[v1.11.x] prov/efa: Do not release rx_entry of EOR packet in EAGAIN case

---

configure.ac
prov/util/src/util_mem_hooks.c

The previous implementation (from Open MPI patcher/linux) does not
intercept syscalls made by glibc. Port the overwrite patcher
implementation from Open MPI. This rewrites the beginning of glibc's
function call with a jump to our intercept and our intercept will make
the syscall directly.
Only the x86_64 and aarch64 support was ported over and we're only
supporting this on Linux at this time.
There are a handful of other fixes in here as well, see commit messages for specifics.

util/mem_hooks: port Open MPI overwrite patcher and intercept logic fixes

---

prov/efa/src/rxr/rxr_pkt_entry.c
prov/efa/src/rxr/rxr_pkt_type_req.c

Another round of patches for the EFA provider for the v1.11.x branch. This covers all patches since v1.11.0 that landed in master and need to be backported.

[v1.11.x] prov/efa fixes for v1.11.x

---

prov/efa/src/efa_domain.c

The uffd monitor we are using currently defers the de-registration
until after the free, which is erroneous according to the rdma-core
interface. (e.g., it causes the RBTree in rdma-core update incorrectly
if fork support is enabled).
Switch to memhooks monitor to avoid the deferring.

prov/efa: Switch to memhooks monitor

---

prov/shm/src/smr_signal.h

Because of signal stack limitations for languages such
as Go that might create alternate stacks, use the flag
SA_ONSTACK to use the signal stack

prov/shm: register signals with SA_ONSTACK

---

prov/util/src/util_mem_hooks.c

Coverity sent a warning that a negative value could be passed to a
parameter that cannot be negative, fix this.

util/mem_hooks: fix error handling when obtaining page size

---

prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_cq.c
prov/efa/src/rxr/rxr_ep.c
prov/efa/src/rxr/rxr_init.c
prov/efa/src/rxr/rxr_pkt_cmd.c
prov/efa/src/rxr/rxr_pkt_cmd.h
prov/efa/src/rxr/rxr_pkt_entry.c
prov/efa/src/rxr/rxr_pkt_entry.h
prov/efa/src/rxr/rxr_pkt_type.h
prov/efa/src/rxr/rxr_pkt_type_data.c
prov/efa/src/rxr/rxr_pkt_type_misc.c
prov/efa/src/rxr/rxr_pkt_type_req.c
prov/efa/src/rxr/rxr_read.c
prov/efa/src/rxr/rxr_read.h
prov/efa/src/rxr/rxr_rma.c

This PR contain 12 commits that implements using local read to copy data to GPU buffer.
The first 7 commits are refactors.
The next 5 commits implements the local read.

prov/efa: use local read to copy data to GPU buffer

---

configure.ac
prov/util/src/util_mem_hooks.c

Backport the memhooks fixes to Libfabric 1.11.x so that syscalls made in glibc are captured.

[v1.11.x] Memhooks fixes for 1.11.x

---

prov/efa/src/efa_domain.c

The uffd monitor we are using currently defers the de-registration
until after the free, which is erroneous according to the rdma-core
interface. (e.g., it causes the RBTree in rdma-core update incorrectly
if fork support is enabled).
Switch to memhooks monitor to avoid the deferring.

[v1.11.x] prov/efa: Switch to memhooks monitor

---

prov/shm/src/smr_signal.h

Because of signal stack limitations for languages such
as Go that might create alternate stacks, use the flag
SA_ONSTACK to use the signal stack
Cherry-picked from commit d5423c66d8fd744ffa75c1f8eabae3f55f7e5c92

[v1.11.x] prov/shm: register signals with SA_ONSTACK

---

man/fi_psm2.7.md
prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_ep.c
prov/psm2/src/psmx2_trx_ctxt.c

In addition to the existing job-wide UUID setting by the environment
variable FI_PSM2_UUID, applications now can set different UUIDs for
individual endpoint via 'info->ep_attr->auth_key'.
Update the man page accordingly.

prov/psm2: Allow per-endpoint UUID assignment

---

include/ofi_mr.h
include/windows/pthread.h
prov/util/src/rocr_mem_monitor.c
prov/util/src/util_mem_hooks.c
prov/util/src/util_mem_monitor.c

Depending on monitor behavior, some monitors require calls that may
result in a free operation (for example memory deregistration), to be
deferred until outside of the monitor. This patch adds a flag and only
requests free deferral if necessary.

util_mem_monitor: Add flag to indicate whether to defer free

---

prov/rxd/src/rxd_cq.c

Data packets that are at the end of a window should
trigger an ACK to the sender to drive progress on
the sender. However, due to incorrect parentheses, the
ACK was always getting skipped, requiring a resend in
order for an ACK to get sent. Fixing this significantly
improves performance at larger messages.

prov/rxd: fix bug preventing segmentation acks

---

prov/shm/src/smr_init.c

ofi_hmem_init is already called by the core code and does not
need to be called in the shm provider

prov/shm: remove unnecessary duplicate call to ofi_hmem_init

---

prov/shm/src/smr_init.c

ofi_hmem_init is already called by the core code and does not
need to be called in the shm provider
Cherry-picked from commit ad3433440e857c6a786be047b751a849bd65beee

[v1.11.x] prov/shm: remove unnecessary duplicate call to ofi_hmem_init

---

prov/rxd/src/rxd_cq.c

Data packets that are at the end of a window should
trigger an ACK to the sender to drive progress on
the sender. However, due to incorrect parentheses, the
ACK was always getting skipped, requiring a resend in
order for an ACK to get sent. Fixing this significantly
improves performance at larger messages.
Cherry-picked from commit 65184f55ddd733f3f9dc45253c8b5a19355fb099

[v1.11.x] prov/rxd: fix bug preventing segmentation acks

---

prov/shm/src/smr_progress.c

SAR can be used before the CMA check occurs and is also used for device
transfers. Call this function regardless whether CMA is available.

prov/shm: always call SAR progress function

---

prov/shm/src/smr.h
prov/shm/src/smr_msg.c
prov/shm/src/smr_rma.c

CMA is always allowed to the same thread so use CMA when sending to self. This fixes a hang when a SHM endpoint has no peers but tries to communicate with itself.
Test description: ran fabtests and the failing test (Intel MPI osu_alltoall -n 37 -ppn 36) with and without restricted ptrace.

prov/shm: always use CMA when sending to self

---

prov/shm/src/smr_msg.c

Use id, not peer_id for setting sar_status since
we are using the local smr data. The peer id is used
for remote smr data
Cherry-picked from commit 48395e99fa68fc520d348c93d74ca43bfbd1b9e9

[v1.11.x] prov/shm: fix incorrect id for sar protocol

---

prov/shm/src/smr_msg.c

Use id, not peer_id for setting sar_status since
we are using the local smr data. The peer id is used
for remote smr data

prov/shm: fix incorrect id for sar protocol

---

prov/util/src/util_mem_monitor.c

Problem reported by coverity.  The new mm_list_rwlock is not
released if read fails to return sizeof(msg).

core/cache: Fix incorrect unlocking in uffd_handler

---

prov/util/src/util_mem_monitor.c

Problem reported by coverity.  The new mm_list_rwlock is not
released if read fails to return sizeof(msg).

v1.11.x: core/cache: Fix incorrect unlocking in uffd_handler

---

contrib/intel/jenkins/Jenkinsfile
contrib/intel/jenkins/Jenkinsfile.daily
contrib/intel/jenkins/build.py

the mpich suite was being built from the same source directory for simultaneous builds leading
to builds overstepping over each other leading to CI failures. The build paths are now isolated
to ensure that two builds use independent copies of the source directory. Also added clean up
to prevent disk space overuse. 

Jenkins-CI: isolating mpich suite build path

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_atomic.c
prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_rma.c

If we fail to establish a connection to a peer, or if after a
connection has been established, the peer shuts down, the
connection map entry that corresponds with the peer's address
in the AV is cleared.  The result is that any attempts to
send to the same address will fail with -EHOSTUNAVAIL.
In the case where a connection to the peer fails, this can
be the result of starting a client process prior to the
server process being started.  (The server will be using a
well-known address).  This problem occurs running DAOS
tests.
A similar problem can occur if a peer is re-started.  The
client's connection to the server can be shutdown.  Once
the server is restarted, the client should be able to
communicate again.  However, since the server address is the
same, all future attempts to send to …

prov/rxm: Allow reconnecting to peers and retrying connection requests

---

configure.ac
include/ofi_cuda.h
include/ofi_hmem.h
prov/efa/src/efa_fabric.c
prov/efa/src/rxr/rxr_attr.c
prov/efa/src/rxr/rxr_init.c
prov/util/src/cuda_mem_monitor.c
src/hmem_cuda.c

The current logic was silently ignoring a failure to find the CUDA
runtime libraries. We would want the configure to abort if an explicit
request to build with CUDA fails to find the headers/libs in the
provided dir-path (or they are absent in the standard system paths
when no path is provided). When `--with-cuda` is not provided, we
still check to see if the runtime is available and define HAVE_LIBCUDA
if it is.

configure: Rework FI_CHECK_PACKAGE[(cuda)] logic

---

prov/shm/src/smr.h
prov/shm/src/smr_msg.c
prov/shm/src/smr_progress.c
prov/shm/src/smr_rma.c

Backport these two commits:
```
0525115da prov/shm: always use CMA when sending to self
213710c02 prov/shm: always call SAR progress function
```

[v1.11.x] prov/shm: sar progress fix and cma to self fix

---

man/fi_mr.3.md

This is not supported by some providers, plus is of questionable
value anyway.
Fixes #6245

core: Indicate that 0-length memory registrations are invalid

---

man/fi_msg.3.md
man/fi_rma.3.md

Address a long outstanding man page issue, and clarify that
these operations are not restricted to connected EPs.
Fixes #2683

man: Clarify write/read/send operations apply to RDM EPs

---

prov/util/src/rocr_mem_monitor.c
prov/util/src/util_mem_hooks.c
prov/util/src/util_mem_monitor.c

Calling malloc (which happens in rdma-core during deregistration if fork
support is enabled) causes a deadlock if called in the sbrk memhook.
glibc acquires a mutex in _int_free that is also acquired in
__libc_malloc.
See #6244
This reverts commit 4dbf0c964010a1a7b76ae4270d812a0ca61132c2.

Revert "util: Flush caches after notifying for memhooks and rocr"

---

prov/verbs/src/verbs_info.c

If the user has set FI_VERBS_IFACE, they are looking for
addresses which correspond to a specific network interface,
such as ib0.  In this case, skip adding sockaddr_ib native
IB addresses to the getinfo list.
This fixes a regression with Intel MPI.

prov/verbs: Skip SIB addresses if a network iface is set

---

prov/efa/src/efa_device.c

There is currently a case where closing the protection domain may fail.
Remove the assert here as the resources will be cleaned up by the
driver.

prov/efa: remove protection domain use_cnt assert

---

prov/efa/src/efa.h
prov/efa/src/efa_ep.c
prov/efa/src/efa_rma.c
prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_ep.c
prov/efa/src/rxr/rxr_pkt_type_misc.c
prov/efa/src/rxr/rxr_read.c

This PR contains 3 commits that do not inserting address during initialization. Doing that would cause addresses inserted by application do not start from 0, which is against libfabric standard.

prov/efa: do not insert address during initialization

---

contrib/cray/bats/batsgenerator.sh
contrib/cray/bats/benchmark.template
contrib/cray/bats/imb.bats
contrib/cray/bin/run_libfabric_pipeline

IMB and OMB tests have been added to run_libfabric_pipline. Additionally
a fix is included for a test bug in IMB.
Signed-off-by: patrickbueb <70724661+patrickbueb@users.noreply.github.com>

contrib/cray: Updating run_libfabric_pipeline and imb.bats

---

prov/efa/src/efa_domain.c
prov/efa/src/efa_mr.c

To allow better optimization, we turn off the memory registration cache
if the user attempts to open a domain with FI_MR_LOCAL bit set.

prov/efa: Turn off the MR Cache if FI_MR_LOCAL is set, set FI_REMOTE_READ for internal SHM MRs

---

prov/shm/src/smr_progress.c

There seems to be a possible hang/race condition
in the shm provider where a SAR buffer is set as READY
before the data has been saved.
Add a lock when progressing into the SAR buffer until
we determine a better solution.

prov/shm: add SAR buffer locking

---

configure.ac
include/ofi.h
prov/efa/src/efa_domain.c
src/common.c

The autoconf was done incorrectly causing builds to fail. Move the fork
check function into the EFA provider for now.
Fixes #6327

common: move fork check to EFA provider

---

prov/efa/src/efa.h
prov/efa/src/efa_device.c
prov/efa/src/efa_ep.c
prov/efa/src/efa_fabric.c
prov/efa/src/efa_mr.c
prov/efa/src/efa_rma.c
prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_ep.c
prov/efa/src/rxr/rxr_pkt_type_misc.c
prov/efa/src/rxr/rxr_read.c

This doesn't include the fork support checks and remaining MR cache PR that's in progress but picks the EFA commits in master that are ready to go.
```
a9cc492a5 prov/efa: fix a bug in efa_get_gdr_support()
f20ea2dd6 prov/efa: Add FI_REMOTE_READ access to shm registrations
57f708282 prov/efa: remove protection domain use_cnt assert
106b59951 prov/efa: fix a bug by removing address insertion during initialization
8b8fcc557 prov/efa: add argument self_comm to efa_rma_post_read()
1cb1342dd prov/efa: create an AH for EP's own address
```

[v1.11.x] EFA fixes for 1.11.x

---

prov/efa/src/efa.h
prov/efa/src/efa_domain.c
prov/efa/src/efa_mr.c
prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_cq.c
prov/efa/src/rxr/rxr_domain.c
prov/efa/src/rxr/rxr_msg.c
prov/efa/src/rxr/rxr_pkt_cmd.c
prov/efa/src/rxr/rxr_pkt_type_misc.c
prov/efa/src/rxr/rxr_pkt_type_req.c
prov/efa/src/rxr/rxr_rma.c

Due to efa_mr_cache_enable being a global variable, it is checked for
every domain. The check for FI_MR_LOCAL to disable efa_mr_cache_enable
caused a bug where domains with different mr_mode settings would cause
the domains with caches to not cleanup their cache. Due to needing a
domain specific check, we now check if the cache was malloc'd or not and
do not change efa_mr_cache_enable.

prov/efa: Bugfix, only disable the cache per domain when checking for FI_MR_LOCAL.

---

fabtests/multinode/src/core.c

Multinode tests now support device-device and host-device modes. Only
a small change was needed just to initialize the device buffers.
There is a small bug in ZE that does not support transfers of size 0. The 
multinode tests use a size 0 transfer as a barrier so assuming that fix is
made, the multinode tests work over ZE.

Multinode with ZE Support

---

prov/efa/src/efa_domain.c
prov/efa/src/efa_fabric.c

Update the fork support check so that it fails unless FI_MR_LOCAL is
set. We will only be supporting libibverbs fork support when memory
registrations are handled by the application.
Also change the fork support check to abort instead of returning an
error. Open MPI will continue if fi_domain fails and setup another
component for communication.
Test description: Verified with Open MPI that ring_c crashes when fork support is enabled but proceeds if fork support is not enabled. Called fork in ring_c and it aborted. Verified that the cache is enabled with Open MPI and the cache is disabled when the app specifies FI_MR_LOCAL (via fabtests).

prov/efa: update fork support check and change to abort

---

src/tree.c

The free_list is cleaned up as part of ofi_rbmap_destroy.
However, ofi_rbmap_destroy pairs with ofi_rbmap_create.
For users that allocate the rbmap as part of another
structure, they use ofi_rbmap_init / ofi_rbmap_cleanup.
In this use case, the free_list will leak memory for
allocated nodes.

common/rbmap: Fix leak by moving free_list cleanup

---

include/ofi_mr.h
prov/util/src/util_mr_cache.c
src/tree.c

The upstream MR cache only uses a rbtree to track registrations.  However, extra complexity and indirection is added to the code to support an alternative storage option which isn't actually used.  Simplify the code to remove the function indirection and call the  rbtree code directly.  This makes the code easier to manage and read.

core/mr_cache: Remove unused user storage complexity

---

prov/verbs/src/verbs_cm.c

This patch is a work-around to enable connection establishment
using native Infiniband addressing even if IPoIB is not installed
or configured.
Fixes issue #6247

prov/verbs: GID-base conn. establishment doesn't require IPoIB anymore

---

src/hmem.c

L0 does not currently support size 0 memory copies.
Even once it does, this allows skipping the overhead
of empty copies for any interfaces.

src/hmem: skip size 0 copies

---

fabtests/unit/getinfo_test.c

Intel and Open MPI both call fi_getinfo with NULL hints to
discover what's available.  They then modify that output to
use as hints into another fi_getinfo call.  As a result, they
can pick up new caps, but do not set new mode or mr_mode bits.
This can cause the subsequent fi_getinfo call to fail.
Add a test to simulate this behavior to catch regressions.

fabtests/getinfo: Add test similar to MPI behavior

---

include/ofi_util.h
prov/efa/src/efa.h
prov/efa/src/efa_av.c
prov/efa/src/rxr/rxr_ep.c
prov/rxm/src/rxm_conn.c
prov/util/src/util_av.c
prov/util/src/util_coll.c

The AV count field does not reflect the current size of the AV.  Add a function to retrieve that value and update calling sites to use it.  This fixes an issue where AV sets are created smaller than the number of addresses being stored in the associated AV.

util/av: Replace use of av->count with new ofi_av_size()

---

fabtests/man/fabtests.7.md
man/fi_atomic.3.md
man/fi_domain.3.md
man/fi_endpoint.3.md
man/fi_msg.3.md
man/fi_rma.3.md
man/fi_tagged.3.md

Connectionless and unconnected endpoints are used inter-
changeably in the man pages.  Use the term connectionless
instead.  Unconnected could refer to the state of a
connection-oriented endpoint.  This makes the documentation
consistent.
Fixes: 6346

man: Use connectionless term consistently

---

fabtests/common/shared.c
fabtests/include/shared.h
fabtests/man/fabtests.7.md
fabtests/multinode/src/core.c
include/ofi_util.h
prov/tcp/src/tcpx_domain.c
prov/util/src/util_domain.c

1. Fix build warning in multinode test
2. Document -D option in fabtests
3. Add fabtest option to bind the EQ to the domain, rather than the EP
4. Add domain bind support to the util_domain
5. Update tcp to use the new util domain bind function

tcp/util: Add support to bind EQ to domain, along with test

---

include/ofi.h
src/fi_tostr.c

This avoids possible buffer overruns, and prepares the way to add a re-entrant version of fi_tostr.

core/tostr: Pass buffer length to internal string calls

---

configure.ac

Attempt to use the function alias, since some compilers only warn that
aliases are not supported when defined. Usage is a stronger
check. Fixes build with Intel compilers on macOS.

configure: Improve __alias__ attribute check

---

include/ofi_bitmask.h
include/ofi_mem.h
include/ofi_rbuf.h
include/ofi_shm.h
include/ofi_util.h
prov/efa/src/efa.h
prov/efa/src/rxr/rxr_pkt_entry.h
prov/hook/hook_debug/src/hook_debug.c
prov/mrail/src/mrail.h
prov/psm/src/psmx.h
prov/rstream/src/rstream.h
prov/rstream/src/rstream_msg.c
prov/rxd/src/rxd_rma.c
prov/rxm/src/rxm.h
prov/rxm/src/rxm_ep.c
prov/shm/src/smr.h
prov/shm/src/smr_atomic.c
prov/shm/src/smr_ep.c
prov/shm/src/smr_msg.c
prov/shm/src/smr_progress.c
prov/shm/src/smr_rma.c
prov/sockets/include/sock.h
prov/usnic/src/usdf.h
prov/usnic/src/usdf_cm.h
prov/usnic/src/usnic_direct/vnic_devcmd.h
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_cm_xrc.c
prov/verbs/src/verbs_ep.c

First set of patches to cleanup build warnings when pedantic is enabled.  These cleanups touch a variety of places in the code.  See individual commits for details.  None of the changes are fix any functionality.
These changes do not address all build warnings.  There are plenty to go.  But this is a start at removing some of them.

Remove (some) warnings when building with --enable-picky

---

fabtests/include/freebsd/malloc.h

Use same workaround as macOS to enable building MR cache evict test on
FreeBSD platforms, where mallopt is not supported.

fabtest: Fix MR cache evict test on FreeBSD

---

prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_cq.c
prov/efa/src/rxr/rxr_domain.c
prov/efa/src/rxr/rxr_ep.c
prov/efa/src/rxr/rxr_msg.c
prov/efa/src/rxr/rxr_pkt_cmd.c
prov/efa/src/rxr/rxr_pkt_entry.c
prov/efa/src/rxr/rxr_pkt_type_data.c
prov/efa/src/rxr/rxr_pkt_type_misc.c
prov/efa/src/rxr/rxr_pkt_type_req.c

There is a bug in the EFA provider that causes the memory descriptor to be skipped when specified by the app, causing an unneeded memory copy in the send path. Do some other cleanup while we're here. There is more to do but this at least fixes the issue for now.
Test description: Added some prints and ran `fi_rdm_tagged_pingpong`/`fi_rma_bw -o write` to verify the descriptor is being used for the various protocols. Did some testing with MPI (latency, bw, message rate, alltoall) as well and verified inline registration is still functional.

prov/efa: EFA send path/MR fixes

---

fabtests/unit/av_test.c
include/ofi_net.h
include/ofi_util.h
prov/rxd/src/rxd_av.c
prov/rxm/src/rxm_av.c
prov/sockets/src/sock_av.c
prov/util/src/util_av.c
src/common.c

Fix a bug returning an incorrect (misleading) errno from the util AV code.
Add support for FI_SYNC_ERR to the IP AV code.  This allows rxm and rxd to support the flag.
Add a new test to the AV unit test to verify correct operation of FI_SYNC_ERR.
Fixes #6357

Add support for FI_SYNC_ERR to IP based AVs

---

fabtests/Makefile.am

Follow up to incomplete fix in
[f37705916a07bebfcb5814a7af16fd572bc55f60]. Modify AM_CFLAGS so the
dummy malloc.h file gets included.

fabtest: Include FreeBSD specific headers

---

fabtests/common/shared.c
fabtests/man/fabtests.7.md

This patch modify ft_parseinfo() and added cuda to supported
interaces. It also modify ft_cusage() to add cuda information.

fabtests: add cuda to supported interfaces

---

prov/verbs/src/verbs_info.c

Patch to modify Verbs provider ibv_query_gid() call to use FI_VERBS_GID_IDX to obtain the device's GID index, rather than being hardcoded to GID index 0.

prov/verbs: GID_IDX support

---

include/ofi.h

If addr is already page algined,
ofi_get_page_start(const void *addr, size_t page_size) and
ofi_get_page_end(const void *addr, size_t page_size) return the
same address.
If mem-hooks monitor is used, ofi_write_patch() will have both base
and bound pointing to the same address, and length will be 0.
Therefore, we can not set the memory protection correctly, which
causes the following memcpy failed with segfault.
Fix the issue by returning the ending address of the page.

prov/util: Fix a bug in ofi_get_page_end

---

include/ofi.h

If addr is already page algined,
ofi_get_page_start(const void *addr, size_t page_size) and
ofi_get_page_end(const void *addr, size_t page_size) return the
same address.
If mem-hooks monitor is used, ofi_write_patch() will have both base
and bound pointing to the same address, and length will be 0.
Therefore, we can not set the memory protection correctly, which
causes the following memcpy failed with segfault.
Fix the issue by returning the ending address of the page.

[v1.11.x] prov/util: Fix a bug in ofi_get_page_end

---

include/rdma/fabric.h
man/fi_control.3.md
man/fi_psm2.7.md
prov/psm2/Makefile.include
prov/psm2/include/fi_ext_psm2.h
prov/psm2/src/psmx2.h
prov/psm2/src/psmx2_domain.c
prov/psm2/src/psmx2_trx_ctxt.c

Define new fi_control() commands for accessing fid specific values.
Use the new interface to add domain level parameter setting for psm2 provider.

Add fi_get_val() and fi_set_val()

---

prov/shm/src/smr_progress.c

Normal ofi_atomic_op messages do not need to return the fetched
data. Their result buffers are NULL, causing a size mismatch when
the fetch tries to complete. Skip the fetch for non-fetch operations.

prov/shm: skip atomic fetch processing for non-fetch ops

---

prov/shm/src/smr_progress.c

Normal ofi_atomic_op messages do not need to return the fetched
data. Their result buffers are NULL, causing a size mismatch when
the fetch tries to complete. Skip the fetch for non-fetch operations.
Cherry-picked from commit 1aecf609b4725fa172943241ec300e864aeda40a

[v1.10.x] prov/shm: skip atomic fetch processing for non-fetch ops

---

prov/shm/src/smr_progress.c

Normal ofi_atomic_op messages do not need to return the fetched
data. Their result buffers are NULL, causing a size mismatch when
the fetch tries to complete. Skip the fetch for non-fetch operations.
Cherry-picked from commit 1aecf609b4725fa172943241ec300e864aeda40a

[v1.11.x] prov/shm: skip atomic fetch processing for non-fetch ops

---

include/ofi_hmem.h
src/hmem_cuda.c

As a part of CUDA HMEM initialization, add in a check to verify that CUDA compute-capable devices are present on the host. This check will prevent libfabric from hitting a segfault during ofi_hmem_host_register.

Add in cudaGetDeviceCount check into cuda_hmem_init()

---

prov/tcp/src/tcpx_rma.c

Signed-off-by: Jiakun Yan <jiakunyan1998@gmail.com>

prov/tcp: Fix swapping of dest_addr and cq data for RMA inject

---

prov/tcp/src/tcpx_rma.c

Signed-off-by: Jiakun Yan <jiakunyan1998@gmail.com>

prov/tcp: Fix swapping of dest_addr and cq data in RMA inject

---

include/ofi.h

Update the checks for CLWB, CLFLUSH, and CLFLUSHOPT to
match the latest code from the pmem/pmdk/libpmem2 source.
The CLWB register was incorrect, and the CLFLUSH/CLFLUSHOPT
bits have changed since the original code was provided.
Fixes #6391

core/pmem: Fix pmem instruction checks

---

include/ofi.h

Update the checks for CLWB, CLFLUSH, and CLFLUSHOPT to
match the latest code from the pmem/pmdk/libpmem2 source.
The CLWB register was incorrect, and the CLFLUSH/CLFLUSHOPT
bits have changed since the original code was provided.
Fixes #6391

[v1.11.x] core/pmem: Fix pmem instruction checks

---

include/ofi.h

Update the checks for CLWB, CLFLUSH, and CLFLUSHOPT to
match the latest code from the pmem/pmdk/libpmem2 source.
The CLWB register was incorrect, and the CLFLUSH/CLFLUSHOPT
bits have changed since the original code was provided.
Fixes #6391

[v1.9.x] core/pmem: Fix pmem instruction checks

---

include/ofi.h

Update the checks for CLWB, CLFLUSH, and CLFLUSHOPT to
match the latest code from the pmem/pmdk/libpmem2 source.
The CLWB register was incorrect, and the CLFLUSH/CLFLUSHOPT
bits have changed since the original code was provided.
Fixes #6391

[v1.10.x] core/pmem: Fix pmem instruction checks

---

Makefile.am
include/freebsd/osd.h
include/linux/osd.h
include/osx/osd.h
include/unix/osd.h
src/osx/osd.c

In practice, macOS returns an error (Invalid argument) with socket
operations > 2GB. Lower the limit to avoid infinite retry loops.

macOS: Handle socket API size limitations

---

prov/efa/src/rxr/rxr_pkt_type_req.c
prov/efa/src/rxr/rxr_rma.c
prov/efa/src/rxr/rxr_rma.h

Currently the emulated read protocol is not using caller provided
memory registration on the responder side, which caused degraded
bandwidth.
This patch address this issue by adding an argument desc to
function
rxr_rma_verified_copy_iov()
The function will then retrieve the memory registration from
efa_domain->mr_map and put it in desc. The memory registration
will then be used in sending data back.

prov/efa: Use memory registration for emulated read protocol

---

prov/rxm/src/rxm_attr.c
prov/rxm/src/rxm_init.c

Re-introduce RXM HMEM discovery. If the underlying core provider does
not support FI_HMEM, this capability will be masked off in RXM.

prov/rxm: RXM HMEM discovery

---

prov/gni/include/gnix_cm.h
prov/gni/include/gnix_freelist.h
prov/gni/src/gnix_av.c
prov/gni/src/gnix_cm.c
prov/gni/src/gnix_ep.c
prov/gni/src/gnix_msg.c
prov/gni/test/api.c
prov/gni/test/rdm_tagged_sr.c
prov/gni/test/vc.c

when using newer >8 gcc and with --enable-debug configure option.

prov/gni: clean up compiler warnings

---

prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_cq.c
prov/efa/src/rxr/rxr_domain.c
prov/efa/src/rxr/rxr_ep.c
prov/efa/src/rxr/rxr_msg.c
prov/efa/src/rxr/rxr_pkt_cmd.c
prov/efa/src/rxr/rxr_pkt_entry.c
prov/efa/src/rxr/rxr_pkt_type_data.c
prov/efa/src/rxr/rxr_pkt_type_misc.c
prov/efa/src/rxr/rxr_pkt_type_req.c
prov/efa/src/rxr/rxr_rma.c
prov/efa/src/rxr/rxr_rma.h

This PR backports 3 commits which fixed the bug that user provided MR was not used when MR cache is enabled

[1.11.x] prov/efa: fix bug that user provided MR was not used when MR cache is enabled

---

fabtests/benchmarks/dgram_pingpong.c
fabtests/benchmarks/msg_bw.c
fabtests/benchmarks/msg_pingpong.c
fabtests/benchmarks/rdm_cntr_pingpong.c
fabtests/benchmarks/rdm_pingpong.c
fabtests/benchmarks/rdm_tagged_bw.c
fabtests/benchmarks/rdm_tagged_pingpong.c
fabtests/benchmarks/rma_bw.c
include/ofi_util.h
man/fi_rxm.7.md
prov/rxm/src/rxm.h
prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_domain.c
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_init.c
prov/tcp/src/tcpx.h
prov/tcp/src/tcpx_domain.c
prov/tcp/src/tcpx_ep.c
prov/tcp/src/tcpx_init.c
prov/tcp/src/tcpx_progress.c

This series introduces a concept I named dynamic receive buffers.  The purpose is to eliminate the need for the tcp provider to copy data through rxm bounce buffers on the receive side.
Rxm must still allocate and post receive buffers.  However, the buffers are only posted to receive the size of the rxm packet (64 bytes).  Once tcp receives that header, it invokes a callback into rxm to retrieve the rest of the receive buffer.  This allows rxm to process the packet headers, identify the application buffer that the receive targets, and return that to tcp.  The tcp provider then continues reading from the socket, placing the data directly into the application's buffer, rather than staging it through an rxm bounce buffer.
Bounce buffers are still required to handle unexpected messages.  When …

rxm/tcp: Eliminate bounce buffers for medium message transfers

---

prov/rxm/src/rxm_domain.c

Dynamic receive buffers are disabled if FI_COLLECTIVE support
is enabled, however the check for collectives being enabled is
incorrect (always true).  Use '&' instead of '|' to check if the
flag is set.

prov/rxm: Fix check for FI_COLLECTIVE enabled

---

fabtests/common/shared.c

According to the man page fi_close on the mr should be called
after closing the endpoint/counters associated with the mr
When closing the MR, there must be no opened endpoints or
counters associated with the MR

fabtests: Close mr after closing the endpoint/counters

---

fabtests/common/shared.c

According to the man page fi_close on the mr should be called
after closing the endpoint/counters associated with the mr
When closing the MR, there must be no opened endpoints or
counters associated with the MR

[v1.11.x] fabtests: Close mr after closing the endpoint/counters

---

fabtests/common/shared.c

ft_finalize_ep() assumes that underlying providers always
support an inject size 4 + the prefix size.  However, some
providers do not support any inject size at all.
This shows up over verbs with the hfi device, which does not
support INLINE data.
Since there's no need for using inject in finalize, simply
remove the flag.

fabtests: Remove possible invalid use of FI_INJECT

---

include/linux/osd.h

The correct headers were not included for the syscall. This causes the
wrong syscall numbers to be used for aarch64 builds; the SHM provider
fails to use CMA due to this bug.

linux/osd.h: fix syscall include for process_vm_readv/writev

---

include/linux/osd.h

The correct headers were not included for the syscall. This causes the
wrong syscall numbers to be used for aarch64 builds; the SHM provider
fails to use CMA due to this bug.

[v1.11.x] linux/osd.h: fix syscall include for process_vm_readv/writev

---

prov/efa/src/efa.h
prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_atomic.c
prov/efa/src/rxr/rxr_cq.c
prov/efa/src/rxr/rxr_ep.c
prov/efa/src/rxr/rxr_msg.c
prov/efa/src/rxr/rxr_pkt_cmd.c
prov/efa/src/rxr/rxr_pkt_cmd.h
prov/efa/src/rxr/rxr_pkt_type.h
prov/efa/src/rxr/rxr_pkt_type_data.c
prov/efa/src/rxr/rxr_pkt_type_misc.c
prov/efa/src/rxr/rxr_pkt_type_req.c
prov/efa/src/rxr/rxr_pkt_type_req.h
prov/efa/src/rxr/rxr_rma.c

This patch is created to add support for FI_DELIVERY_COMPLETE
with packets of RXR_EAGER_MSGRTM_PKT and RXR_EAGER_TAGRTM type.
Signed-off-by: Ao Li aolia@amazon.com

prov/efa: FI_DELIVERY_COMPLETE Support

---

contrib/buildrpm/buildrpmLibfabric.sh
libfabric.spec.in

Create a symbolic link to abstract the version named directory. This will
assist the automated test process.
Signed-off-by: Patrick Bueb <patrick.bueb@hpe.com>

spec: Abstract version with symbolic link

---

prov/rxm/src/rxm_domain.c
prov/rxm/src/rxm_ep.c

Disable dynamic receive buffering and direct sends until
all issues have been resolved.  This, unfortunately, masks
issues handling differences in verbs devices, as well as
bugs in a couple of fabtests.  The changes will be reverted
once CI is passing with fixes in place.

prov/rxm: Always use eager bounce buffers

---

prov/efa/src/efa.h
prov/efa/src/rxr/rxr_read.c

This patch fix issues in function
efa_ep_support_rnr_retry_modify() and
rxr_read_post()
that cause compiler warning

prov/efa: fix compilation warning

---

prov/rxm/src/rxm_init.c

Providers built as dynamic libraries need to call ofi_mem_init()
to create buf pools.

prov/rxm: fixed rxm provider init when built as dynamic library

---

fabtests/functional/multi_recv.c
include/ofi_util.h
prov/rxm/src/rxm.h
prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_init.c
prov/shm/src/smr_comp.c
prov/util/src/util_av.c
prov/util/src/util_cq.c
prov/util/src/util_eq.c
prov/verbs/src/fi_verbs.h
prov/verbs/src/verbs_dgram_ep_msg.c
prov/verbs/src/verbs_ep.c
prov/verbs/src/verbs_msg.c
prov/verbs/src/verbs_rma.c

This series of patches are the result of debugging a segfault that occurred while running fabtests over rxm+tcp.  The segfault occurs if the client program is run without starting the server first, and waiting several seconds.
See #6414 and #6204 
The underlying issues are severe.  First if an app passing in a count > 1 to fi_cq_read, the returned completions will all be written to the first array entry passed in.  From the app's view, completions will be lost and/or corrupted.  Second, the attempts to handle CQ overrun by making use of an overflow queue were incorrect.  That could have resulted in returning successful completions as errors, if both successful and error completions were on the overflow queue.  Additional data corruptions could also occur, as seen by the app.  This is what …

at this point a bunch of fixes everywhere

---

prov/shm/src/smr_progress.c

Reverts commit bc73ecbf.
The bug seems to be somewhere in the L0 caching,
not the protocol.
Cherry-picked from commit 2aa18eda1ab1b16f21a0aced75d92c4ece728537

[v1.11.x] prov/shm: revert add SAR buffer locking

---

prov/efa/src/efa_mr.c

Currently, efa_mr_cache_regattr() call ofi_mr_cache_flush() when
cache->cached_cnt is multiple of EFA_MR_CACHE_FLUSH_CHECK.
The problem with this approach is that cache->cached_cnt can
go up and down depend on application's behavoir.
This patch address the issue by using a static call_counter, which
ensures that efa_mr_cached_regattr() is called more regularly.

prov/efa: adjust frequency of flush

---

prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_msg.c
prov/efa/src/rxr/rxr_pkt_type_misc.c
prov/efa/src/rxr/rxr_rma.c

Currently, in function `rxr_pkt_handle_receipt_recv()`,
`tx_entry->bytes_acked` > 0 is used to determine whether
long cts protocols are used.
This is wrong because for long cts protocols, receipt can
arrive before the completion of the LONG_RTW/LONG_RTM
and DATA packet.
If that happens, `tx_entry->bytes_acked` would be 0 even for
long cts protocols.
Given the above situation, this patch does the following
changes:
1. Introduced a flag called `RXR_LONGCTS_PROTOCOL`, which
shows whether the sender side is using long cts protocols
2. In `rxr_pkt_handle_receipt_recv()`, we use the
`RXR_LONGCTS_PROTOCOL` flag to determine whether long cts
protocols are used instead of checking `tx_entry->bytes_acked`.

prov/efa: Fix a Bug in rxr_pkt_handle_receipt_recv

---

.travis.yml

Re-enable support for dynamic receive buffering.  This
provides an optimization over the tcp provider to
avoid intermediate data copies through rxm bounce
buffers.

travis: set osx_image to a later (supported) version

---

.travis.yml

The travis OS X build hangs, printing a warning that the
default xcode is no longer supported by the app store.  Force
update to the latest OS X version as of this patch.

Set osx image to a later (supported) version

---

prov/verbs/src/verbs_info.c

I've recently got the case where libfabric tried to execute
ibv_query_device() with a NULL context (struct ibv_context *),
which caused the process to segv with the following call stack:
ibv_query_device  [/lib/x86_64-linux-gnu/libibverbs.so.1, 0x7ffff7f79000]
vrb_init_info  [xxx, 0x555555554000]
fi_verbs_ini  [xxx, 0x555555554000]
fi_ini  [xxx, 0x555555554000]
fi_getinfo  [xxx, 0x555555554000]
That crash happened because one network port was somehow malfunctioning
and its verbs context was NULL. The root cause of that malfunctioning
port is unknown but rebooting the node seems to have fixed the problem.
Below is an ibstat output for the faulty port:
ibpanic: [38248] main: stat of IB device 'mlx5_3' failed: Resource temporarily unavailable
As a fix, we should just skip the interfaces that …

prov/verbs: skip devices with NULL contexts

---

prov/efa/src/rxr/rxr_atomic.c
prov/efa/src/rxr/rxr_msg.c
prov/efa/src/rxr/rxr_rma.c

The PR contain 2 bugfixes:
1. Use rxr_ep_post_ctrl() to send RTM. This fix the issue when shm is used, message ordering was messed up.
2. fix a memory registration leak in the error handling path

prov/efa: two bug fixes

---

prov/efa/src/efa_fabric.c

The fork handler install was moved in commit ff72bf48a9 when fixing a
bug where the rdma-core hugepage environment variable was set too late.
However, this causes the fork handler to be installed if an EFA device
is not present or if EFA is not used. We only risk corruption with fork
when it is called after the bounce buffers are allocated, registered,
and pinned, so delay installing this handler to validate that fork can
be called safely until then.
Test description: Added a fork() to fi_pingpong and verified the handler is installed when EFA is used, and it is not installed when UDP is used.

prov/efa: move efa_atfork_callback install to fabric init

---

prov/efa/src/rxr/rxr_atomic.c
prov/efa/src/rxr/rxr_msg.c
prov/efa/src/rxr/rxr_rma.c

This PR back ports two bug fixes to the v1.11.x branch: 
1. use rxr_ep_post_ctrl to post REQ packets
2. fix a memory registration leak in error handling path.

[v1.11.x] prov/efa: fix MR leak and incorrect message queuing

---

include/ofi_shm.h
prov/shm/src/smr.h
prov/util/src/util_shm.c

We can not assume CMA always works when sending to self.
In the container context, CMA to self is not permitted because
the syscalls are already blocked by dropping CAP_SYS_PTRACE
https://docs.docker.com/engine/security/seccomp/.
Fix the issue by enabling CMA check for endpoint itself.
Field 'cma_cap' is changed into flags: High 4 bits for peer
CMA cap, while low 4 bits for self CMA cap. Since self CMA
cap and peer CMA cap might be different, we can not use
field 'cma_cap' as struct iovec in the test CMA call any more,
use field 'pid' instead.

prov/shm: Add CMA check for endpoint itself
