- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_init.c
- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_cmd.h
- prov/efa/src/rxr/rxr_pkt_entry.c
- prov/efa/src/rxr/rxr_pkt_entry.h
- prov/efa/src/rxr/rxr_pkt_type.h
- prov/efa/src/rxr/rxr_pkt_type_data.c
- prov/efa/src/rxr/rxr_pkt_type_misc.c
- prov/efa/src/rxr/rxr_pkt_type_req.c
- prov/efa/src/rxr/rxr_read.c
- prov/efa/src/rxr/rxr_read.h
- prov/efa/src/rxr/rxr_rma.c
This PR backports the efa local RDMA read to v1.11.x branch
> [v1.11.x] prov/efa: backport local read

- src/hmem_cuda.c
PR #6160 introduced the driver initialization as a sanity check to to
see if a CUDA-capable GPU is available before allowing FI_HMEM
operations. We use the CUDA runtime API for our CUDA needs in libfabric,
and should leave the driver initialization up to the runtime to manage.
We do not use a separate context for libfabric's needs either.
Moreoever, cuInit() forks and execs `nvidia-modrobe` to setup device files
and load drivers if they are missing. Rdma-core based providers are
not fork-safe by default, and this implicit fork causes the EFA provider
to abort for all applications on systems without a NVIDIA GPU when built
with CUDA.
> hmem: Remove cuInit() driver initialization

- src/hmem_cuda.c
Cherry-pick of https://github.com/ofiwg/libfabric/pull/6272 for the v1.11.x branch, which is where the issue was originally caught.
> [v1.11.x] Cherry-pick cuInit fix

- include/ofi_mr.h
- include/windows/pthread.h
- prov/util/src/rocr_mem_monitor.c
- prov/util/src/util_mem_hooks.c
- prov/util/src/util_mem_monitor.c
Contains 4 commits cherry-picked from:
bba19e79865d7058822369fd2d01d46d5235c96f
f9787b9dd7bbf6b1d8ab9b28d02bc0fe3def3379
431645b8676c0cf8c925d084057b61880d2d079d
d10df326973edcf2bf00cccaf3bf90168636fafb
Original PR: https://github.com/ofiwg/libfabric/pull/6241
> V1.11.x util: Flush caches after notifying for memhooks and rocr

- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_atomic.c
- prov/rxm/src/rxm_conn.c
- prov/rxm/src/rxm_ep.c
- prov/rxm/src/rxm_rma.c
cherry picked patches to support DAOS client/server communication model
> v1.11.x: prov/rxm: Allow reconnecting to peers

- configure.ac
- include/ofi_cuda.h
- include/ofi_hmem.h
- prov/efa/src/efa_fabric.c
- prov/efa/src/rxr/rxr_attr.c
- prov/efa/src/rxr/rxr_init.c
- prov/util/src/cuda_mem_monitor.c
- src/hmem_cuda.c
Cherry-pick of https://github.com/ofiwg/libfabric/pull/6294 into the 1.11.x branch, which has the same build issue.
> [v1.11.x] configure: Rework FI_CHECK_PACKAGE[(cuda)] logic

- man/fi_mr.3.md
Just word smithing of the fi_mr man page.  No changes to the defined
behaviors intended.
> man/mr: Clarify memory registration text

- README.md
> project: Add appveyor badge to git page

- prov/shm/src/smr_init.c
> prov/shm: Add missing ; in smr_fini and smr_ini

- prov/shm/src/smr_init.c
> prov/shm: fix missing ; in DL build

- AUTHORS
- Makefile.am
- NEWS.md
- configure.ac
- fabtests/configure.ac
- include/rdma/fabric.h
- include/windows/config.h
> v1.11.1rc1

- prov/efa/src/efa_fabric.c
Currently, efa_get_gdr_support() call fi_read_file()
with pointer to a single char gdr_support, then call
atoi() on that pointer.
This is wrong because the expected input of atoi()
is an string terminated by '\0', but gdr_support is
not necessary followed by '\0' in stack.
This patch address the issue by define a string
gdr_support_str, and call fi_read_file() and strtol()
on this string.
It also did some refactor by splitting return value
and result.
return value is either 0 (on success) or a negative value
(on failure)
result (gdr_support) is set on success and is either 0 or 1.
> prov/efa: fix a bug in efa_get_gdr_support()

- prov/rxm/src/rxm_conn.c
TSAN reports a data race with threads reading/writing the
endpoint do_progress variable simultaneously.  While this is
almost certainly a false positive (locking isn't needed), add
a lock to silence thread-sanitizer.
Fixes #6328
> prov/rxm: Add locking around do_progress access

- prov/efa/src/rxr/rxr_init.c
This commit fixes two issues. One, FI_HMEM is a primary capability that
should only be enabled if applications request it. Second, FI_HMEM was
always being advertised when NULL hints were passed by the application.
This was causing issues with applications like Intel MPI that query for
providers will NULL hints followed by a subsequent call to fi_getinfo()
with specific hints.
Testing:
- Tested with NCCL and HMEM
- IMPI with external libfabric no longer hits the `OFI addrinfo() failed ` error
> prov/efa: Fix FI_HMEM capability claims

- prov/efa/src/rxr/rxr_init.c
This commit fixes two issues. One, FI_HMEM is a primary capability that
should only be enabled if applications request it. Second, FI_HMEM was
always being advertised when NULL hints were passed by the application.
This was causing issues with applications like Intel MPI that query for
providers will NULL hints followed by a subsequent call to fi_getinfo()
with specific hints.
> [v1.11.x] prov/efa: Fix FI_HMEM capability claims

- prov/gni/test/api.c
- prov/gni/test/api_cntr.c
- prov/gni/test/api_cq.c
- prov/gni/test/av.c
- prov/gni/test/cancel.c
- prov/gni/test/cm.c
- prov/gni/test/cntr.c
- prov/gni/test/datagram.c
- prov/gni/test/rdm_addr_str_sr.c
- prov/gni/test/rdm_atomic.c
- prov/gni/test/rdm_dgram_rma.c
- prov/gni/test/rdm_dgram_stx.c
- prov/gni/test/rdm_multi_recv.c
- prov/gni/test/rdm_rx_overrun.c
- prov/gni/test/rdm_sr.c
- prov/gni/test/rdm_tagged_sr.c
- prov/gni/test/sep.c
- prov/gni/test/vc.c
something changed with default linkage and the criterion tests were not building
> prov/GNI: fix criterion tests

- NEWS.md
> NEWS.md: Update news with v1.11.1 release data

- util/info.c
Allow setting the source address via -s option, similar to
fabtests.
> util/info: Add -s <source_addr> option to fi_info test

- include/ofi.h
- include/ofi_abi.h
- include/rdma/fabric.h
- libfabric.map.in
- src/fabric.c
- src/fi_tostr.c
Adds a new API function for thread safe fi_tostr
@sydidelot
> fabric: Add fi_tostr_r re-entrant tostr function

- man/fi_fabric.3.md
> man: Document fi_tostr_r

- prov/tcp/src/tcpx.h
- prov/tcp/src/tcpx_progress.c
- prov/tcp/src/tcpx_shared_ctx.c
Cleanups extracted from a larger series still under development
> prov/tcp: Minor code cleanups

- prov/tcp/src/tcpx_rma.c
Signed-off-by: Jiakun Yan <jiakunyan1998@gmail.com>
> fix issue #6392

- prov/efa/src/rxr/rxr_cq.c
The EFA provider does not support FI_RMA_EVENT capablity, this
patch remove the related code
Signed-off-by: Wei Zhang <wzam@amazonc.com>
> prov/efa: remove FI_RMA_EVENT related code

- prov/verbs/src/fi_verbs.c
- prov/verbs/src/fi_verbs.h
- prov/verbs/src/verbs_dgram_ep_msg.c
- prov/verbs/src/verbs_domain.c
- prov/verbs/src/verbs_ep.c
- prov/verbs/src/verbs_info.c
- prov/verbs/src/verbs_mr.c
- prov/verbs/src/verbs_msg.c
- prov/verbs/src/verbs_rma.c
Patches from PR #6066 with a few minor updates applied.  All updates are based on comments from the last round of review.
> verbs: Initial support for HMEM

- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_cq.c
- prov/rxm/src/rxm_domain.c
Extracting some minor code cleanups added as part of an unrelated feature that updates similar portions of the code.
> prov/rxm: Minor code cleanups

- prov/efa/src/efa.h
- prov/efa/src/efa_domain.c
> prov/efa: Minor cleanups

- .travis.yml
> travis: Fixup travis.yml file syntax

- AUTHORS
- COPYING
- Makefile.am
- NEWS.md
- configure.ac
- fabtests/configure.ac
- include/rdma/fabric.h
- include/windows/config.h
> v1.11.2rc1

- prov/efa/src/rxr/rxr_msg.c
previous commit 71d36af0c made the change to use rxr_pkt_post_ctrl()
(instead of rxr_pkt_post_ctrl_or_queue) for all REQ packets.
This is wrong for medium RTM packets, which is used by medium message
protocol.
Medium message protocl send data in a batch of medium RTM packets
without flow control. It could happen that the first several
medium RTM packets was sent successfully, but a following RTM packet
encountered -FI_EAGAIN. When rxr_pkt_post_ctrl() is used, this would
cause application to re-send the whole message.
This patch fix the issue by using rxr_pkt_post_ctrl_or_queue() for
medium RTM packets.
> prov/efa: use rxr_pkt_post_ctrl_or_queue() for medium RTM packets

- prov/verbs/src/verbs_ep.c
This is a cherry pick from a fix to master branch
> prov/verbs: cherry-pick off-by-one credit fix

- prov/psm2/src/psmx2_init.c
Use Open MPI job key if present. This can still be overridden by setting
FI_PSM2_UUID explicitly.
> prov/psm2: Check for Open MPI job key

- prov/efa/src/rxr/rxr_rma.c
This patch fixes two memory leaks in the emulated read protcol:
1. In rxr_rma_readmsg(), when rxr_rma_post_efa_emulated_read() failed,
the allocated tx_entry was not released, causing memory leak.
2. In rxr_rma_post_efa_emulated_read(), when rxr_pkt_post_ctrl() failed,
the allocated rx_entry was not released, causing memory leak.
This patch fixes the two issues by releasing tx_entry/rx_entry
in the error handling path.
Besides these two changes. Currently in rxr_rma_post_efa_emulated_read(),
in some error handling path, the tx_entry passed in was released,
which is wrong because the tx_entry is allocated by the caller and
should be released by it too. This patch fixed that.
> [v1.11.x] prov/efa: fix memory leaks in emulated read protocols

- prov/psm2/src/psmx2_av.c
In psmx2_av_map_remove(), disconnection call is made without removing
the epaddr from the peer_list and clearing the epaddr context. A later
call to disconnect_all_peers() may cause double free when it tries to
disconnect every epaddr on the peer_list and some of them may have
already been disconnected. The issue is timing dependent because the
disconnection call is asynchronous.
> prov/psm2: Fix a double free issue related to disconnection

- AUTHORS
- COPYING
- NEWS.md
- configure.ac
- fabtests/configure.ac
- include/rdma/fabric.h
- include/windows/config.h
- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_domain.c
- src/common.c
- src/fi_tostr.c
Initial preparation for v1.12.0 release.
> v1.12.0rc1

- prov/util/src/util_shm.c
If shm_open returns an error because the file already exists, check
to see if the process is not running anymore and proceed with rewriting
if the process is dead.
This still prevents two processes from using the same shm name while
also allowing for using the same name if the last process was killed with
SIGKILL and did not get cleaned up by the signal handler.
Cherry-picked from commit c14dc4198a82b1cc7eb4b39e72cab2a8dfde5163
> [v1.11.x] prov/shm: retry shm_open without O_EXCL if process is dead

- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_domain.c
cherry pick of #6537 for v1.11.x
> prov/rxm: prioritize credit exchange in the deferred queue

- prov/efa/docs/building.md
- prov/efa/docs/overview.md
- prov/efa/docs/pkt-processing.md
> prov/efa: [docs] add building and pkt-processing docs

- prov/psm3/configure.ac
- prov/psm3/src/psmx3.h
- prov/psm3/src/psmx3_am.c
- prov/psm3/src/psmx3_cq.c
- prov/psm3/src/psmx3_ep.c
- prov/psm3/src/psmx3_init.c
- prov/psm3/src/psmx3_rma.c
- prov/psm3/src/psmx3_trx_ctxt.c
- prov/psm3/src/version.h
HAVE_PSM2_AM_REGISTER_HANDLERS_2
HAVE_PSM2_MQ_FP_MSG
HAVE_PSM2_MQ_REQ_USER
> prov/psm3: Replace HAVE_PSM2_ with HAVE_PSM3_ in code

- prov/psm3/Makefile.include
- prov/psm3/configure.m4
- prov/psm3/psm3/opa/opa_dwordcpy-x86_64.c
- prov/psm3/psm3/psm_mq_internal.h
- prov/psm3/psm3/psm_utils.c
- prov/psm3/psm3/psm_verbs_ep.c
- prov/psm3/psm3/psm_verbs_mr.h
- prov/psm3/psm3/ptl_am/am_reqrep_shmem.c
- prov/psm3/psm3/ptl_ips/ips_proto_mq.c
Split Code fixes from CI code changes in #6560
> prov/psm3: Fixes warnings and LeakSanitizer

- fabtests/Makefile.am
- fabtests/test_configs/psm3/all.test
- fabtests/test_configs/psm3/psm3.exclude
- fabtests/test_configs/psm3/verify.test
> fabtests/psm3: Add psm3 to fabtests configuration

- .travis.yml
> ci/travis: Add psm3 to Travis CI

- src/hmem_rocr.c
rocr_is_addr_valid() should only return true if hsa_agent_get_info() says the
agent is HSA_DEVICE_TYPE_GPU.
> hmem: Fix rocr_is_addr_valid() check for AMD GPU memory

- prov/psm3/psm3/psm_ep.c
- prov/psm3/psm3/psm_hal_gen1/psm_gdrcpy.c
- prov/psm3/psm3/ptl_ips/ips_expected_proto.h
> prov/psm3: Add missing ifdefs for rv module

- NEWS.md
> news: add EFA updates to 1.12 news

- README.md
> readme: Add psm3 to README.md

- prov/psm3/Makefile.include
> prov/psm3: remove warning from linking objects

- prov/psm3/Makefile.include
> prov/psm3: focus workaround to only edge case build

- config/fi_strip_optflags.m4
- configure.ac
- prov/psm3/Makefile.include
- prov/psm3/configure.m4
- prov/psm3/psm3/include/opa_user.h
- prov/psm3/psm3/psm_rndv_mod.c
- prov/psm3/psm3/psm_utils.c
- prov/psm3/psm3/psm_verbs_ep.c
This PR is to track build issues found in psm3 after v1.12.0 release.
> psm3 v1.12.0 build issues

- NEWS.md
- configure.ac
- fabtests/configure.ac
- include/windows/config.h
> v1.12.1- for CI validation

- prov/verbs/src/fi_verbs.h
- prov/verbs/src/verbs_domain.c
- prov/verbs/src/verbs_domain_xrc.c
- prov/verbs/src/verbs_ep.c
- prov/verbs/src/verbs_mr.c
Non-functional change to clarify verbs domain comment and
field name.
> prov/verbs: Cleanup/clarification of verbs domain flags field

- man/fi_shm.7.md
- prov/shm/src/smr.h
- prov/shm/src/smr_domain.c
- prov/shm/src/smr_ep.c
- prov/shm/src/smr_init.c
> [1.12.x] prov/shm: add option to disable CMA and addressing fix

- prov/tcp/src/tcpx.h
- prov/tcp/src/tcpx_cq.c
- prov/tcp/src/tcpx_ep.c
- prov/tcp/src/tcpx_progress.c
- src/common.c
Updates to pollfds implementation and tcp provider interaction with pollfds/epoll.
> prov/tcp: now with more fixes to progress!

- src/common.c
- Update pollfds to use a sparse array of fd's, rather than trying to compact it. This allows us to reference an entry in the pollfds using the fd as an index, eliminating linear searches for a matching entry.
- Optimize handling of epoll_mod in pollfds equivalent. When modifying an fd, handle this directly in the call. This replaces a memory allocation and the queuing of the modification for asynchronous processing.
- Update epoll/pollfds abstractions to return the events which were signaled. This update impacts the sockets provider.
- Update the tcp progress handling to act based on which events were set and to skip trying to progress send or receives if the corresponding event is not set.
PR updated with lost changes to verbs, smr, and usnic from 1st submission.  All updated to new …
> core + tcp: Optimizations to tcp progress handling

- prov/efa/src/efa.h
- prov/efa/src/efa_av.c
- prov/efa/src/efa_ep.c
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_atomic.c
- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_msg.c
- prov/efa/src/rxr/rxr_msg.h
- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_cmd.h
- prov/efa/src/rxr/rxr_pkt_entry.c
- prov/efa/src/rxr/rxr_pkt_type.h
- prov/efa/src/rxr/rxr_pkt_type_data.c
- prov/efa/src/rxr/rxr_pkt_type_misc.c
- prov/efa/src/rxr/rxr_pkt_type_req.c
- prov/efa/src/rxr/rxr_pkt_type_req.h
- prov/efa/src/rxr/rxr_read.c
- prov/efa/src/rxr/rxr_rma.c
A series of bug fixes and refactors related to address vector
> prov/efa: av related bug fixes and refactors

- prov/efa/src/efa.h
- prov/efa/src/efa_ep.c
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_init.c
- prov/efa/src/rxr/rxr_pkt_type_misc.c
A series of patches to refactor completion related routines
> prov/efa: completion related refactors

- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_init.c
- prov/efa/src/rxr/rxr_msg.c
This PR fixes issue related to inject.
> prov/efa: inject related changes

- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_msg.c
The PR contains 2 patches the removed some unnecessary code.
> prov/efa: remove unnecessary code

- prov/efa/src/efa.h
- prov/efa/src/efa_av.c
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_cmd.h
- prov/efa/src/rxr/rxr_pkt_type_req.c
a set of commits that refactor address vector.
> prov/efa: refactor address vector

- contrib/buildrpm/README
- contrib/buildrpm/buildrpmLibfabric.sh
This commit adds the option to build binary and source
packages using the existing build script.
Signed-off-by: James Swaro <james.swaro@hpe.com>
> contrib/buildrpm: Add source build option

- Makefile.am
> Move fi_atomic.3 to real_man_pages

- prov/util/src/util_mr_cache.c
Commit 5169390 changed the cache LRU flushing logic by moving
the flush check to the start of the loop.  The result is that
flushing is not performed as long as the cache is below its
threshhold.  This results in cleanup failing to run when the
cache is being destroyed.
The fi_mr_test will report an assertion that there are
outstanding registrations without the cleanup occurring.
Modify the LRU loop, so that we always flush at least 1
entry when flushing is requested and there are entries
to flush.
> core/mr_cache: Force flush 1 LRU entry when flush requested

- prov/tcp/src/tcpx_attr.c
- src/hmem.c
> core: Set hmem system ops to initialized

- fabtests/common/shared.c
We need to continue to make progress on the main ep even when
we're using the OOB socket.  Call ft_sock_setup() to initialize
the socket properly.  This fixes a hang in fi_unexpected_msg
test that shows up with rxm CM changes.  However, the hang could
happen with any test that uses OOB exchanges and blocks on recv().
Remove the unneeded sleep from the function, since progress can
be driven from the OOB exchanges.
> fabtests: Set OOB socket to nonblocking in init_oob

- prov/verbs/src/verbs_cq.c
We have recently discovered that some network devices do not create
one completion vector per core (it happens for example with virtual functions
when SRIOV is enabled, but there could be some other devices).
According to the man page of fi_cq_open, libfabric expects the value
for signaling_vector to be in the range of (0..max cpu - 1).
But CQ creation may still fail if the device doesn't create one
completion vector for every core.
If the comp_vector is incorrect, the Infiniband provider would return EINVAL.
Debugging such errors is however really hard (at least for Mellanox adapters)
because the error is thrown by the kernel module and there is absolutely no
debug message. The patch adds an error message if the value for the signal
vector is incorrect (lower than 0 or higher than the …
> prov/verbs: Additional checks for CQ's signaling_vector

- prov/efa/src/efa.h
- prov/efa/src/efa_av.c
- prov/efa/src/efa_msg.c
- prov/efa/src/efa_rma.c
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_type_req.c
This PR fix a bug in handling QP being reused.
> prov/efa: fix a bug in qp reuse

- src/fabric.c
If FI_PROVIDER_PATH is set and starts with '@', force
the use of an external provider over the internal one.
Providers in this case will be sorted by load order
rather than by version.  This allows direct use of
a specific provider.
> core: Add option to force use of DL provider

- prov/efa/src/efa.h
- prov/efa/src/efa_av.c
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_init.c
This PR contains two commits that fix a performance issue caused by lazy initialization of packet pool
> prov/efa: fix a performance issue caused by lazy initialization of packet pool

- .travis.yml
- AUTHORS
commit 10efce5411da47b369cbe7a27a748f4aa9909aa7 (HEAD -> coverity-fix, rajachan/coverity-fix)
Author: Raghu Raja <rajachan@protonmail.com>
Date:   Tue Jun 15 17:16:11 2021 +0000
travis: Use the main branch instead of master
Signed-off-by: Raghu Raja <rajachan@protonmail.com>
commit e0eb3bd34c748b0f07efd5d5ecdbe88db37e10ab
Author: Raghu Raja <rajachan@protonmail.com>
Date:   Tue Jun 15 17:15:38 2021 +0000
travis: Explicitly enable providers for coverity_scan
Signed-off-by Raghu Raja <rajachan@protonmail.com>
> coverity_scan updates

- prov/efa/src/efa.h
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_init.c
- prov/efa/src/rxr/rxr_msg.c
- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_entry.c
- prov/efa/src/rxr/rxr_pkt_type_req.c
- prov/efa/src/rxr/rxr_pkt_type_req.h
This PR contains a series of patches that fixed a bug in the zero copy receive model.
> prov/efa: fix a bug in zero copy receive

- prov/efa/src/efa_msg.c
- prov/efa/src/rxr/rxr_msg.c
fix bugs in posting receive buffers
> pro/efa: fix bugs in posting receive buffers

- AUTHORS
- Makefile.am
- NEWS.md
- configure.ac
- fabtests/configure.ac
- include/rdma/fabric.h
- include/windows/config.h
- man/fabric.7.md
- prov/psm3/Makefile.include
For CI testing -- do not merge, will push directly.
> v1.13.0rc1

- prov/rxm/src/rxm_init.c
> prov/rxm: Document valid choices for tcp_wait_obj

- NEWS.md
> NEWS: Update news for v1.13 release

- configure.ac
- fabtests/configure.ac
- include/windows/config.h
- prov/psm3/Makefile.include
> v1.13.0rc2

- prov/psm3/Makefile.include
> prov/psm3: Move psm3 intermediate files to provider directory

- AUTHORS
- NEWS.md
- configure.ac
- fabtests/configure.ac
- include/windows/config.h
> libfabric release v1.13 CI validation

- configure.ac
- fabtests/configure.ac
- include/windows/config.h
> v1.14.0a1 - merge first

- .github/workflows/pr-ci.yml
> ci: Add HMEM build checks to Github Action

- prov/efa/src/efa.h
- prov/efa/src/efa_av.c
- prov/efa/src/rxr/rxr_init.c
This PR contains 2 commits:
First one fixed a bug in RNR support.
With this bug fix, all known issues of RNR support will be fixed. Thus 2nd commit enable RNR support.
> prov/efa: fix a bug and enable RNR support

- prov/efa/src/efa.h
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_init.c
- prov/efa/src/rxr/rxr_pkt_entry.c
This PR contains patches that refactors RNR support
> prov/efa: refactor RNR support

- prov/efa/src/efa.h
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_entry.c
- prov/efa/src/rxr/rxr_pkt_entry.h
- prov/efa/src/rxr/rxr_pkt_type_misc.c
- prov/efa/src/rxr/rxr_pkt_type_req.c
- prov/efa/src/rxr/rxr_read.c
- prov/efa/src/rxr/rxr_rma.c
This PR contains several bug fixes and refactors on the TX path
> prov/efa: bugfixes and refactors on TX path

- fabtests/Makefile.am
- fabtests/functional/loopback.c
- include/ofi_list.h
- include/ofi_net.h
- include/ofi_util.h
- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_av.c
- prov/rxm/src/rxm_conn.c
- prov/rxm/src/rxm_cq.c
- prov/rxm/src/rxm_domain.c
- prov/rxm/src/rxm_ep.c
- prov/tcp/src/tcpx_conn_mgr.c
- prov/util/src/util_av.c
Testing fixes for PR #6833 while Sean is gone
> prov/rxm: CM rework + fixes (for testing purposes)

- .github/workflows/pr-ci.yml
- configure.ac
> ci: Add ZE build steps to Github Action

- v1.10.1/man/fabtests.7.md
- v1.11.0/man/fabtests.7.md
- v1.11.1/man/fabtests.7.md
- v1.11.2/man/fabtests.7.md
- v1.12.0/man/fabtests.7.md
- v1.12.1/man/fabtests.7.md
- v1.13.0/man/fabtests.7.md
All files taken from source tarball associated with each release
Resolves #6950
> gh-pages: Add missing fabtest man page for 1.10.1-1.13.0

- prov/shm/src/smr_progress.c
Changes resolve #6947
@aingerson I don't have review request perms, but your review would be appreciated
> prov/shm: Fixup progress return values, smr_progress_ipc error handling, buffer overrun

- prov/efa/src/rxr/rxr_cq.c
depend on https://github.com/ofiwg/libfabric/pull/6955
> prov/efa: detect and print error for recvwin overflow

- prov/shm/src/smr_progress.c
> prov/shm: Fix unsigned comparison introduced in #6948

- prov/shm/src/smr_progress.c
> [v1.13.x] prov/shm: Fixup progress return values, smr_progress_ipc error handling, buffer overrun

- prov/shm/src/smr_progress.c
> [v1.12.x] prov/shm: Fixup progress return values, smr_progress_ipc error handling, buffer overrun

- prov/efa/src/efa.h
- prov/efa/src/efa_av.c
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_init.c
backport 4 recent commits to efa provider
> [v1.13.x] prov/efa: back port 4 recent commits

- include/ofi_recvwin.h
- prov/efa/src/efa.h
- prov/efa/src/efa_av.c
- prov/efa/src/efa_msg.c
- prov/efa/src/efa_rma.c
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_atomic.c
- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_init.c
- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_cmd.h
- prov/efa/src/rxr/rxr_pkt_entry.c
- prov/efa/src/rxr/rxr_pkt_entry.h
- prov/efa/src/rxr/rxr_pkt_type_data.c
- prov/efa/src/rxr/rxr_pkt_type_misc.c
- prov/efa/src/rxr/rxr_pkt_type_req.c
- prov/efa/src/rxr/rxr_read.c
- prov/efa/src/rxr/rxr_read.h
- prov/efa/src/rxr/rxr_rma.c
This PR back port recent bug fixes for RNR and address vector. Some commits are refactors, but is needed by the following bug fix commits therefore was pulled in too.
> [v1.13.x] prov/efa: back port RNR and AV fixes

- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_entry.c
- prov/efa/src/rxr/rxr_pkt_entry.h
- prov/efa/src/rxr/rxr_read.c
> prov/efa: fix a bug in local read

- fabtests/test_configs/efa/efa.exclude
- prov/efa/src/efa_av.c
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_init.c
Fix a bug in shm and enable the rdm_multi_client test.
> prov/efa: fix a bug and enable multi client test

- Makefile.am
- configure.ac
- fabtests/benchmarks/dgram_pingpong.c
- fabtests/benchmarks/rdm_cntr_pingpong.c
- fabtests/benchmarks/rdm_pingpong.c
- fabtests/benchmarks/rdm_tagged_bw.c
- fabtests/benchmarks/rdm_tagged_pingpong.c
- fabtests/common/hmem_ze.c
- fabtests/common/shared.c
- fabtests/configure.ac
- include/ofi_hmem.h
- include/ofi_mr.h
- libfabric.vcxproj
- libfabric.vcxproj.filters
- man/fi_mr.3.md
- prov/util/src/util_mem_monitor.c
- prov/util/src/util_mr_cache.c
- prov/util/src/ze_mem_monitor.c
- prov/verbs/src/verbs_domain.c
- src/hmem_ze.c
- util/pingpong.c
> Cherry-picked fixes for the v1.13.1 release

- prov/efa/src/rxr/rxr_init.c
The SHM provider disables CMA when FI_HMEM is set so we should only pass
that hint when the app asks for FI_HMEM.
Test description: Verified that CMA is enabled again when cuda support is enabled. Also made some changes/did manual testing to test that CMA is off when FI_HMEM is enabled, for when we eventually use SHM + HMEM in EFA.
> prov/efa: only set FI_HMEM hint for SHM getinfo when requested

- prov/efa/src/rxr/rxr_init.c
The SHM provider disables CMA when FI_HMEM is set so we should only pass
that hint when the app asks for FI_HMEM.
(cherry picked from commit a429ef69d12459a219f5178014da1f02b887c4d4)
> [v1.13.x] prov/efa: only set FI_HMEM hint for SHM getinfo when requested

- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_pkt_cmd.c
> prov/efa: fix rnr deadlock

- v1.13.1/man/index.md
> gh-pages: Fix man page version for v1.13.1

- src/hmem_ze.c
Current path does not specify an engine.
Default engine could be compute and copy.
Add a check to find a copy only engine to use for optimization.
If no copy only engine is found it will use ordinal 0 which is always available for the engine.
> src/hmem_ze: select copy only engine

- prov/efa/src/rxr/rxr_pkt_entry.c
The function rxr_ep_record_tx_op_submitted() should be called for
any TX operations that has successfully submitted to update TX
related counters. However, it is not called for inject operations,
which are also TX operations.
This patch address the issue by calling rxr_ep_reocrd_tx_op_submitted()
in function rxr_pkt_entry_inject().
> prov/efa: update TX counter for inject

- AUTHORS
- NEWS.md
- configure.ac
- fabtests/configure.ac
- include/rdma/fabric.h
- include/windows/config.h
> [v1.13.x] v1.13.2a1

- src/hmem_ze.c
Some L0 calls may segfault when called from a "destructor" if any HMEM-capable
DL provider is enabled due to premature unloading of GPU specific L0 library.
The workaround is to bypass all L0 call inside a "destructor".
> hmem/ze: Provide workaround for segfault in ofi_hmem_cleanup()

- prov/tcp/src/tcpx.h
- prov/tcp/src/tcpx_progress.c
- prov/tcp/src/tcpx_rma.c
> [v1.13.x] prov/tcp: Fix rma read request error completion processing

- prov/efa/src/efa_fabric.c
- prov/efa/src/efa_mr.c
Instead of just relying on the sysfs file, validate that hmem support
was initialized for that particular device during core initialization,
and don't report FI_HMEM support if support is not available.
Also add some checks fo the mr regattr paths to validate whether support
exists. This isn't strictly necessary, but may help users when the
provider supports multiple devices. The current FI_HMEM flag doesn't
provide information on which devices are supported.
This doesn't contain changes around whether p2p support is available, and
falling back to copies when it is not, so p2p is still required for EFA +
FI_HMEM at this point.
Test description: Verified `fi_rdm_pingpong` still works on p4 with both cuda and host buffers. Also made some …
> prov/efa: check if hmem device is initialized, add check to mr regattr

- prov/efa/src/rxr/rxr_pkt_cmd.c
When RNR happens, if the packet is associated with a send
operation, it's supposed to do one of the following two:
(1) write an error to the application, and release the packet
if the resource management is disabled;
(2) queue the packet, and send later.
We were missing a 'else', so we ended up doing both (1) and (2).
This patch fixes the bug and also does code refactoring to
make the logic easier to understand.
> prov/efa: Fix a bug in rxr_pkt_handle_send_error

- AUTHORS
- NEWS.md
- configure.ac
- fabtests/configure.ac
- include/windows/config.h
> v1.13.2 CI

- fabtests/benchmarks/benchmark_shared.c
The '-j' option of the benchmark tests allows the user to specify the upper
limit of inject size. For example, one can disable inject calls by setting
the inject size to 0. This value is passed via the hints to fi_getinfo().
However, some providers (e.g. rxm) may report higher inject size than asked
in the hints. Take the value from the hints when '-j' option is used to honor
the user input.
> fabtests/benchmarks: Fix inject size setting

- prov/efa/src/efa_mr.c
EFA provider current consider all device memory is accessed by
device only, so we support this flags. This patch added this
flag to supported flags in efa_mr_regattr.
> prov/efa: claim support of FI_HMEM_DEVICE_ONLY

- AUTHORS
- NEWS.md
- configure.ac
- fabtests/configure.ac
- include/windows/config.h
> v1.14.0rc1 -- for CI

- NEWS.md
> prov/efa: news update for 1.14 release

- prov/shm/src/smr.h
- prov/shm/src/smr_ep.c
> prov/shm: fix indentation

- prov/efa/src/efa_fabric.c
- prov/efa/src/rxr/rxr_pkt_type_req.c
Check for 128 bit support and change a strdup call.
> prov/efa: fix two compilation issues

- configure.ac
- fabtests/configure.ac
- include/windows/config.h
> v1.14.0rc2 - for CI verification

- AUTHORS
- configure.ac
- fabtests/configure.ac
- include/windows/config.h
Letting CI run, but also debugging a crash with 128-bit atomics.
> v1.14.0rc3 -- for CI

- NEWS.md
updates for verbs, core, rxm, and tcp
> NEWS: Update news for v1.14.0 release

- NEWS.md
> NEWS.md: update shm for 1.14

- config/fi_check_package.m4
- configure.ac
- fabtests/configure.ac
- prov/psm2/configure.m4
- prov/psm3/configure.ac
- prov/usnic/configure.m4
> Configury updates for Autoconf >=v2.70

- prov/efa/docs/efa_rdm_protocol_v4.md
Contains formatting fixes, table label fixes, grammatical/spelling
improvements, clarified wording, etc.
> prov/efa: Edit the protocol doc

- prov/hook/hook_hmem/Makefile.include
- prov/hook/hook_hmem/include/hook_hmem.h
- prov/hook/hook_hmem/src/hook_hmem.c
Also pulls in fix to hmem makefile PR #7281
> Fix merge crossing with hmem and lock rename

- src/common.c
On Windows, send() call may return EWOULDBLOCK. Handle it properly
to avoid sending buffered message twice.
> core/bsock: handle EWOULDBLOCK returned by send call

- prov/netdir/src/netdir_cq.c
Fixes #7230
Add netdir provider implementation for fi_cq_signal and
adjust fi_cq_sread to return when signaled.
on-behalf-of: @cmru-ps <dshinaberry@mru.medical.canon>
> prov/nd: Implement fi_cq_signal

- contrib/intel/jenkins/Jenkinsfile
change agent from 'any' to a specific label
> contrib/intel/jenkins: update jenkins agent

- prov/sockets/src/sock_conn.c
- prov/sockets/src/sock_ep_msg.c
- prov/util/src/util_coll.c
FWIW, there are over a 100 issues clang scan highlights. Makes for a nice list to chip away at for anyone looking for busy-work:
(Generated by running a build through https://clang-analyzer.llvm.org/scan-build.html)
> Minor cleanups based on clang scan complaints

- prov/efa/src/efa.h
- prov/efa/src/efa_mr.c
- prov/efa/src/efa_msg.c
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_init.c
- prov/efa/src/rxr/rxr_msg.c
- prov/efa/src/rxr/rxr_pkt_type_base.c
This PR contains commits that make EFA to gdrcopy
> prov/efa: use gdrcopy

- contrib/intel/jenkins/Jenkinsfile
- prov/verbs/src/verbs_cq.c
> prov/verbs: Do not override receive completion opcode 

- README.md
> readme.md: Add github build actions check badge

- fabtests/configure.ac
> fabtests/configure.ac: fix --enable-debug=no not properly detected

- fabtests/configure.ac
> fabtests/configure.ac: Correct --with-libfabric doc string

- fabtests/unit/av_test.c
- fabtests/unit/cntr_test.c
- fabtests/unit/cq_test.c
- fabtests/unit/dom_test.c
- fabtests/unit/eq_test.c
- fabtests/unit/getinfo_test.c
- fabtests/unit/mr_cache_evict.c
- fabtests/unit/mr_test.c
Use argv[0] for name.  Remove extra "]" for -G.
> fabtests: Correct help for fi_av_test

- prov/tcp/src/tcpx_progress.c
Commit 45dce66 incorrectly negated a check that is used to signal
any threads waiting on a cq to wake up.  Without this signal,
applications can hang, as reported in issue 7443.  The situation is
as follows:
A thread waits for completions on the CQ. At the time that the thread
blocks, the socket has no outgoing transfers, so the thread calls
poll looking for a POLLIN event.
Another thread tries to send a large transfer. A portion of the data
is accepted by the socket. The rest of the transfer is queued on the ep.
That thread returns.  Additional messages may be posted to the ep, but
since there's already an active transfer, those messages simply get
queued on the tx_queue.
Note that the thread that was blocked on the CQ is still blocked waiting
for a POLLIN event.  However, it should be …
> prov/tcp: Wake-up threads blocked on CQ to update their poll events

- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_msg.c
- prov/efa/src/rxr/rxr_pkt_type_base.c
- prov/efa/src/rxr/rxr_pkt_type_req.c
This patch include 3 commits that aimed to enhance hmem performance when gdrcopy is used.
> prov/efa: hmem performance enhancement when using gdrcopy

- prov/efa/src/rxr/rxr_read.c
fix an issue that 0 byte read is not allowed.
> prov/efa: support 0 byte read

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Add templates for reporting issues and feature requests.
> github: Issues templates

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Setup a format to make it clear to the submitter that we want
to know the provider.
> github/templates: Format default title for reports

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/build.py
- contrib/intel/jenkins/run.py
- contrib/intel/jenkins/runtests.py
- contrib/intel/jenkins/tests.py
Add shm-ze Testing to Jenkins CI
> contrib/intel/jenkins: fabtests ze support

- include/ofi_util.h
- prov/hook/src/hook_domain.c
- prov/rxd/src/rxd_atomic.c
- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_atomic.c
- prov/rxm/src/rxm_conn.c
- prov/rxm/src/rxm_domain.c
- prov/rxm/src/rxm_ep.c
- prov/rxm/src/rxm_init.c
- prov/shm/src/smr_atomic.c
- prov/shm/src/smr_av.c
- prov/shm/src/smr_msg.c
- prov/shm/src/smr_rma.c
- prov/tcp/src/tcpx_ep.c
- prov/util/src/util_mem_hooks.c
- prov/verbs/src/fi_verbs.c
- prov/verbs/src/fi_verbs.h
- prov/verbs/src/verbs_cq.c
- prov/verbs/src/verbs_domain.c
- prov/verbs/src/verbs_ep.c
- prov/verbs/src/verbs_eq.c
- prov/verbs/src/verbs_info.c
- prov/verbs/src/verbs_mr.c
- src/hmem_ze.c
Next time I want to rename something like all the lock functions, can someone please hit me over the head with a pool noodle?  Hopefully, the resulting conflicts from cherry picking were resolved correctly.
> prov/[verbs/rxm/shm]: cherry picked fixes for v1.14.x

- AUTHORS
- Makefile.am
- NEWS.md
- configure.ac
- fabtests/configure.ac
- include/rdma/fabric.h
> v1.14.1rc1

- AUTHORS
- Makefile.am
- NEWS.md
- configure.ac
- fabtests/configure.ac
- include/rdma/fabric.h
- include/windows/config.h
- prov/shm/src/smr_ep.c
- prov/sockets/src/sock_ep_msg.c
- prov/sockets/src/sock_mr.c
- prov/verbs/src/verbs_cm_xrc.c
- prov/verbs/src/verbs_eq.c
Includes updated commits from #7504
> v1.15.0rc1

- man/fi_domain.3.md
> man/fi_domain: fix small linking typo

- prov/psm3/configure.m4
> psm3: fix typo in configure.m4

- NEWS.md
> news: updated for psm3 provider

- fabtests/pytest/efa/test_multi_recv.py
- prov/efa/src/rxr/rxr_pkt_type_misc.c
Added a test case for multi-recv and fixed a bug
> [v1.15.x] prov/efa: multi recv test and bug fix

- prov/util/src/util_buf.c
- src/fi_tostr.c
> core/util: Very minor coding fixes

- master/man/index.md
> gh-pages: Add opx to man pages

- fabtests/Makefile.am
- fabtests/scripts/runfabtests.sh
- fabtests/ubertest/config.c
- man/fi_domain.3.md
- prov/rxm/src/rxm_cq.c
- prov/rxm/src/rxm_ep.c
- prov/shm/src/smr_atomic.c
- prov/shm/src/smr_ep.c
- prov/sockets/src/sock_ep_msg.c
- prov/sockets/src/sock_mr.c
- prov/verbs/src/fi_verbs.h
- prov/verbs/src/verbs_cm_xrc.c
- prov/verbs/src/verbs_cq.c
- prov/verbs/src/verbs_eq.c
- prov/verbs/src/verbs_info.c
- src/common.c
- src/fi_tostr.c
prep for v1.14.1rc2
@ofiwg/aws-efa-team if there are EFA changes needed for v1.14.1 not yet in the branch, please add.
> v1.14.x: cherry picked fixes from main

- include/ofi_enosys.h
- src/enosys.c
> OFI: Stubs for av_set operations

- fabtests/Makefile.am
- fabtests/pytest/efa/efa_common.py
- fabtests/pytest/efa/test_rdm.py
- fabtests/pytest/efa/test_rma_bw.py
- prov/efa/src/efa_mr.c
- prov/efa/src/rxr/rxr_read.c
- prov/efa/src/rxr/rxr_rma.c
Extend the rma_bw test to multiple memory types and fix bugs reveal by it.
> prov/efa: rma test cases and bug fixes

- prov/opx/include/rdma/opx/fi_opx_endpoint.h
- prov/opx/include/rdma/opx/fi_opx_hfi1_packet.h
- prov/opx/src/fi_opx_ep.c
- prov/opx/src/fi_opx_tagged.c
prov/opx: Fix compiler warnings.
Signed-off-by: Michael Heinz <mheinz@cornelisnetworks.com>
> prov/opx: Fix compiler warnings.

- AUTHORS
- configure.ac
- fabtests/configure.ac
- include/windows/config.h
- prov/opx/include/rdma/opx/fi_opx_endpoint.h
- prov/opx/include/rdma/opx/fi_opx_hfi1_packet.h
- prov/opx/src/fi_opx_ep.c
- prov/opx/src/fi_opx_tagged.c
- prov/shm/src/smr_signal.h
PR includes cherry picked update for opx build warnings.
> v1.15.0rc2

- prov/efa/src/efa_cq.c
- prov/efa/src/efa_ep.c
- prov/efa/src/efa_msg.c
- prov/efa/src/rxr/rxr_atomic.c
- prov/efa/src/rxr/rxr_pkt_type_req.c
patches to fix issues identified by coverity
> prov/efa: patches to fix issues identified by coverity

- NEWS.md
> NEWS.md: efa update

- fabtests/scripts/runfabtests.sh
Signed-off-by: Yossi Leybovich <sleybo@amazon.com>
> runfabtests.sh: print timestamp of each test

- .appveyor.yml
> Appveyor: skip changes irrelevant to appveyor

- prov/efa/Makefile.include
- prov/efa/docs/naming_convention.md
- prov/efa/src/efa.h
- prov/efa/src/efa_av.c
- prov/efa/src/efa_cq.c
- prov/efa/src/efa_device.c
- prov/efa/src/efa_device.h
- prov/efa/src/efa_domain.c
- prov/efa/src/efa_ep.c
- prov/efa/src/efa_fabric.c
- prov/efa/src/efa_mr.c
- prov/efa/src/efa_msg.c
- prov/efa/src/efa_rma.c
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_init.c
> prov/efa: refactor code in efa_device

- NEWS.md
> NEWS.md: Update news for v1.14.1 release

- NEWS.md
> NEWS.md: Update news for v1.15.0 release

- AUTHORS
- NEWS.md
- configure.ac
- fabtests/configure.ac
- include/windows/config.h
> v1.14.1 -- moving to final release

- contrib/cray/Jenkinsfile.verbs
HPE git repos have moved.  Update the URLs.
> contrib/cray: update repo URLs.

- Makefile.am
- prov/efa/Makefile.include
> prov/efa: Make EFA unit tests build with make, but not be installed

- prov/efa/src/efa_prov_info.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_init.c
Fix a bug in `rxr_ep_alloc_app_dev_info()` about setting info's mr mode.
> prov/efa: fix rxr_ep_alloc_app_dev_info()'s mr_mode setting

- prov/efa/Makefile.include
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_op_entry.h
- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_type.h
- prov/efa/src/rxr/rxr_pkt_type_req.c
- prov/efa/src/rxr/rxr_read.c
- prov/efa/src/rxr/rxr_read.h
- prov/efa/src/rxr/rxr_rma.c
This PR merged the rxr_tx_entry and rxr_rx_entry into rxr op entry.
> prov/efa: merge rxr_tx_entry and rxr_rx_entry into rxr op entry

- NEWS.md
- fabtests/common/shared.c
- fabtests/functional/multi_ep.c
- fabtests/functional/scalable_ep.c
- fabtests/functional/shared_ctx.c
- fabtests/include/shared.h
- fabtests/multinode/src/core.c
- fabtests/multinode/src/core_coll.c
- fabtests/scripts/runfabtests.sh
- fabtests/test_configs/ofi_rxd/ofi_rxd.exclude
- fabtests/unit/av_test.c
- include/ofi_net.h
- include/ofi_util.h
- prov/util/src/util_attr.c
- prov/util/src/util_av.c
- prov/util/src/util_main.c
- prov/verbs/src/verbs_ep.c
- prov/verbs/src/verbs_info.c
Fixes to check addr_format, plus updates to the util AV to allocate enough space to store addresses
> [cherry-picked] v1.15.x: A beautiful set of fixes from Alexia

- prov/rxm/src/rxm_conn.c
From a valgrind report:
==3590290== at 0xCA3AD30: rxm_process_connect (rxm_conn.c:508)
ERROR: daos_engine:0 ==3590290== by 0xCA3C054: rxm_handle_event (rxm_conn.c:816)
==3590290== by 0xCA3C614: rxm_cm_progress (rxm_conn.c:915)
==3590290== by 0x6031179: start_thread (in /usr/lib64/libpthread-2.28.so)
==3590290== by 0x6E55DC2: clone (in /usr/lib64/libc-2.28.so)
==3590290== Address 0x38d04c6c8 is 8 bytes inside a block of size 18,864 free'd
==3590290== at 0x4C38A03: free (vg_replace_malloc.c:755)
==3590290== by 0xCBDE02C: tcpx_ep_close (tcpx_ep.c:624)
==3590290== by 0xCA3845B: fi_close (fabric.h:612)
==3590290== by 0xCA39538: rxm_close_conn (rxm_conn.c:88)
==3590290== by 0xCA3B08A: rxm_process_reject (rxm_conn.c:566)
==3590290== by 0xCA3BF95: rxm_handle_error (rxm_conn.c:798)
==3590290== by …
> prov/rxm: Fix possible use of event data after free

- libfabric.vcxproj
- prov/efa/Makefile.include
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_atomic.c
- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_msg.c
- prov/efa/src/rxr/rxr_op_entry.c
- prov/efa/src/rxr/rxr_op_entry.h
- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_cmd.h
- prov/efa/src/rxr/rxr_pkt_type_data.c
- prov/efa/src/rxr/rxr_pkt_type_req.c
- prov/efa/src/rxr/rxr_pkt_type_req.h
- prov/efa/src/rxr/rxr_rma.c
a series of patches that refactor the protocol selection of message
> prov/efa: refactor message protocol selection

- prov/efa/src/rxr/rxr_pkt_cmd.c
When posting medium RTM packets, multiple packets need to
be posted at the same time.
In a recent commit eef3ecffa, rxr_pkt_post() was simplified to
always post 1 packet. The handling of medium RTM packets was
moved to rxr_pkt_post_req(), which will queue medium RTM
if -FI_EAGAIN is encountered during posting packets. The
progress engine will resend.
This caused an issue because progress engine uses rxr_pkt_post()
to send packets. When a medium RTM is queued, multiple packets
need to be sent, but rxr_pkt_post() will only send one.
To address this issue, this patch made the following changes:
1. It introduce rxr_pkt_post_one(), which will post 1 packet.
2. It moved the handling of medium RTM packets from rxr_pkt_post_req()
to rxr_pkt_post(), so rxr_pkt_post() can send multiple medium
RTM …
> prov/efa: let rxr_pkt_post() post multiple medium RTM packets

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/tests.py
Re-enable osu+verbs and psm3 multinode test.
Change eth label to cvl label in Jenkinsfile
> contrib/intel/jenkins: re-enable tests and change labels

- include/ofi_indexer.h
- src/indexer.c
Variable renames to make the code more intuitive to understand.
Added a few asserts for verifications
Should be no functionality changes
> core/indexer: Code cleanups

- prov/efa/src/efa_prov_info.c
This patch fixed the memory leak on error handling path in
efa_prov_info_set_nic_attr(), reported by coverity.
It also did some refactor to combine two error handling label
into one.
> prov/efa: fix memory leak on eror in efa_prov_info_set_nic_attr()

- prov/efa/src/rxr/rxr_init.c
- prov/efa/src/rxr/rxr_msg.c
2 commits the adjusts the behavior of runting read protocol.
> prov/efa: adjust runting read protocol

- prov/efa/src/rxr/rxr_ep.c
2 patches that removed some excessive warning
> prov/efa: remove excessive warning

- prov/verbs/src/verbs_mr.c
The buffer length was incorrectly overwritten with the allocation length
returned from ze_hmem_get_base_addr(). This would cause registration failure
if the buffer has non-zero offset into the allocation because the address
range of registration would exceed the allocation.
Fix by ignoring the allocation length.
> prov/verbs: Fix incorrect length used in memory registration

- prov/verbs/src/verbs_mr.c
The buffer length was incorrectly overwritten with the allocation length
returned from ze_hmem_get_base_addr(). This would cause registration failure
if the buffer has non-zero offset into the allocation because the address
range of registration would exceed the allocation.
Fix by ignoring the allocation length. Also add a informational output
for the failover registration call.
(Cherry-picked from commit d1505794f6069d8594bba4b4c1af15841d1e86ae)
> [v1.15.x] prov/verbs: Fix incorrect length used in memory registration

- prov/verbs/src/verbs_mr.c
The buffer length was incorrectly overwritten with the allocation length
returned from ze_hmem_get_base_addr(). This would cause registration failure
if the buffer has non-zero offset into the allocation because the address
range of registration would exceed the allocation.
Fix by ignoring the allocation length. Also add a informational output
for the failover registration call.
(Cherry-picked from commit d1505794f6069d8594bba4b4c1af15841d1e86ae)
> [v1.14.x] prov/verbs: Fix incorrect length used in memory registration

- fabtests/common/shared.c
- fabtests/regression/shm_sighandler_test.c
> fabtests: fix shm_sighandler_test

- fabtests/Makefile.am
- fabtests/pytest/default/test_sighandler.py
- fabtests/pytest/efa/test_from_default.py
- fabtests/scripts/runfabtests.sh
> fabtests: Add shm_sighandler_test to runfabtests

- include/ofi_epoll.h
- prov/util/src/util_wait.c
- src/common.c
Picking a couple optimizations added as part of the tcp progress restructuring patches.
> core/pollfds: Minor optimizations

- prov/efa/src/rxr/rxr_ep.c
The previous PR to adopt wide completion APIs caused performance regression, e.g. RMA read/write bandwidth. This is attributed to the unlimited CQ poll size. It is observed that a single progress routine polled more than 1000 work completions (the cap was 50 before the change). This causes a long pole and blocks user thread from doing other work(further details are still under investigation). This PR partially reverts the previous change and reinstates the cap for CQ poll in the progress engine.
Running the same RMA BW fabtests, it is observed that, at 1MB transfer size, without this cap the read/write bandwidth is ~30% lower than before-wide-completion; with this cap the degradation drops to ~3%.
Signed-off-by: wenduwan <wenduwan@amazon.com>
> prov/efa: restrict rdm cq poll size

- include/ofi_util.h
- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_conn.c
- prov/rxm/src/rxm_cq.c
- prov/rxm/src/rxm_ep.c
- prov/rxm/src/rxm_init.c
- prov/shm/src/smr_av.c
- prov/tcp/src/tcpx_cq.c
- prov/util/src/rxm_av.c
- prov/util/src/util_av.c
- prov/util/src/util_coll.c
prov/tcp: increase the number of events to retrieve from the kernel
prov/util: always drive progress when reading from the cq
Fix genlock initialization
> util / tcp / rxm: added debug logging, minor fix to tcp, minor optimization to rxm

- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_msg.c
- prov/efa/src/rxr/rxr_op_entry.c
- prov/efa/src/rxr/rxr_op_entry.h
- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_type_req.c
- prov/efa/src/rxr/rxr_pkt_type_req.h
- prov/efa/src/rxr/rxr_rma.c
adjust the data size of multiple req sent via one call to ibv_post_send.
> prov/efa: adjust multi req data size

- fabtests/pytest/efa/conftest.py
- prov/efa/src/rxr/rxr_op_entry.c
- prov/efa/src/rxr/rxr_pkt_type_req.c
This PR fixed a bug in that can cause runtread message protocol to hang, and added test case for it.
> prov/efa: fix runtread bug and test

- fabtests/pytest/common.py
- prov/efa/src/efa_cq.c
This PR contains 2 patches:
1st one fixed a bug in pytest script that hide a testing failure.
2nd one fixed a bug in EFA provider that can cause the failure.
> prov/efa,fabtests/pytest: fix a bug in pytest that hide failure

- prov/efa/test/README.md
Update instructions on how to write unit tests.
> prov/efa: update unit test instructions

- fabtests/pytest/requirements.txt
> fabtests/pytest: Add pyyaml to requirements.txt

- fabtests/Makefile.am
- fabtests/common/check_hmem.c
- fabtests/pytest/common.py
> fabtests/pytest: Skip cuda tests if provider does not support hmem hints

- fabtests/pytest/efa/test_runt.py
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_msg.c
- prov/efa/src/rxr/rxr_op_entry.h
- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_type_base.c
- prov/efa/src/rxr/rxr_pkt_type_req.c
Adjust the strategy to copy data to GPU buffer.
> prov/efa: adjust cuda copy strategy

- prov/psm3/configure.ac
Also add Version Print to summary.
Fixes: #7901
> psm3: remove bashisms from configure

- AUTHORS
- COPYING
- Makefile.am
- configure.ac
- fabtests/configure.ac
- include/rdma/fabric.h
- include/windows/config.h
> v1.15.2rc1

- fabtests/prov/efa/src/rdm_rnr_read_cq_error.c
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_op_entry.h
- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_entry.c
- prov/efa/src/rxr/rxr_pkt_entry.h
Fix bugs in writting cq error entry for RNR, and update test.
> prov/efa: fix bugs in rnr cq entry and test

- fabtests/functional/rdm_stress.c
Add the ability to support CXI provider with FI_MR_ENDPOINT
mr mode.
> fabtests: Add FI_MR_ENDPOINT support to rdm_stress

- fabtests/README
fabtests: Update README to provide new fabtests URL
> fabtests: Update README to provide new fabtests URL

- fabtests/prov/efa/src/rdm_rnr_read_cq_error.c
- prov/efa/src/efa_cq.c
- prov/efa/src/efa_mr.c
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_msg.c
- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_entry.h
back port bug fixes to v1.15.x branch
> [v1.15.x] prov/efa: backport bug fixes

- AUTHORS
- NEWS.md
- configure.ac
- fabtests/configure.ac
- include/windows/config.h
> v1.15.2rc2

- src/hmem_neuron.c
neuron added a memcpy function and neuron_copy_to_dev()
should use it to copy data from host to device.
> hmem_neuron.c: Use nrt_memcpy_to_device to copy from host to dev.

- configure.ac
- include/ofi_hmem.h
- src/hmem_synapseai.c
This PR implements the required configure flags and hmem ops for synapseai hmem iface.
> hmem: Implement synapseai iface

- prov/efa/src/rxr/rxr_msg.c
This patch renamed
rxr_msg_select_rtm_for_cuda()
to
rxr_msg_select_rtm_for_hmem()
and used it for neuron memory too.
> prov/efa: use same strategy to select RTM for neuron and cuda

- prov/efa/src/efa_mr.c
This patch set the FI_HMEM_DEVICE_ONLY flag when register
a hmem region with shm provider because shm provider needs the
flag to determine IPC usage.
> prov/efa: set FI_HMEM_DEVICE_ONLY flag for hmem memory for shm

- fabtests/component/dmabuf-rdma/fi-rdmabw-xe.c
Add an option to the fi-rdmabw-xe test to allow preposting receives
for the send test. Some providers may see a performance boost with
preposted receives due to the overhead associated with unexpected
messages.
Also fix the requested MR keys.
> fabtests/component/dmabuf-rdma: Add option to prepost receives

- NEWS.md
- configure.ac
- fabtests/configure.ac
- include/windows/config.h
- prov/verbs/include/fi_verbs.h
- prov/verbs/src/verbs_cq.c
- prov/verbs/src/verbs_ep.c
Once merged, I will create the v1.16.x branch
> v1.16.0rc2

- man/fi_efa.7.md
- prov/efa/src/rxr/rxr_env.c
This patch updated man page and help message for FI_EFA_RUNT_SIZE
> prov/efa: update man page and help message for FI_EFA_RUNT_SIZE

- man/fi_efa.7.md
- prov/efa/src/rxr/rxr_env.c
This patch updated man page and help message for FI_EFA_RUNT_SIZE
(cherry picked from commit b1a28db5083efe37750ff92224efb546c164cf6f)
> [v1.16.x] prov/efa: update man page and help message for FI_EFA_RUNT_SIZE

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/build.py
- contrib/intel/jenkins/common.py
- contrib/intel/jenkins/run.py
- contrib/intel/jenkins/runtests.py
- contrib/intel/jenkins/summary.py
- contrib/intel/jenkins/tests.py
- fabtests/functional/rdm_stress.c
Includes one fix each to rdm_stress and net provider.  Bulk of changes are updating intel jenkinsfile
> [v1.16.x] mostly updating Intel CI scripts so CI can pass on this branch

- configure.ac
- fabtests/configure.ac
- include/windows/config.h
> v1.16.0rc3

- NEWS.md
Added news for EFA.
Also added 1 item for core regarding CUDA IPC support
> NEWS.md: efa and core update for 1.16.0

- NEWS.md
Added news for EFA.
Also:
added 1 item for core regarding HMEM IPC cache
(cherry picked from commit 2c7505cc629dc86949ada816c4cd046dc956bc18)
> [v1.16.x] NEWS.md: efa, core update for 1.16.0

- NEWS.md
> NEWS: Update news for v1.16.0 release

- AUTHORS
- COPYING
- NEWS.md
- README
- fabtests/COPYING
- fabtests/README
- prov/net/Makefile.include
- prov/net/src/xnet_init.c
Plus pull in readme/news updates from v1.16.x branch
> prov/net: Fix and rename DL build

- NEWS.md
Remove some duplicated entries
> NEWS.md: remove duplicated entries

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/run.py
- contrib/intel/jenkins/runtests.py
- contrib/intel/jenkins/tests.py
- fabtests/Makefile.am
- fabtests/Makefile.win
- fabtests/include/shared.h
- fabtests/multinode/include/core.h
- fabtests/multinode/include/timing.h
- fabtests/multinode/src/core.c
- fabtests/multinode/src/harness.c
- fabtests/multinode/src/pattern.c
- fabtests/multinode/src/timing.c
- fabtests/scripts/runmultinode.sh
Add options to run only one pattern for the multinode tests
Show performance data for connection management
> Fabtests/Multinode: Performance

- prov/util/src/util_mr_map.c
state the access violations
Signed-off-by: Thorsten Schütt <schuett@gmail.com>
> prov/util: add debugging in ofi_mr_map_verify

- prov/efa/Makefile.include
> prov/efa: add missing efa header

- .github/workflows/pr-ci.yml
> .github/workflows: add make distcheck

- fabtests/common/shared.c
- fabtests/include/shared.h
- fabtests/unit/mr_test.c
Two commits that added support for HMEM, and a test case that free and allocate buffer again.
> fabtests/mr_test: add hmem support and a new test case

- prov/efa/src/efa_mr.c
- prov/efa/src/efa_mr.h
back port two fixes  that fix memory registration.
> [v1.16.x] prov/efa: fix bugs in memory registration

- fabtests/Makefile.am
- fabtests/pytest/common.py
- fabtests/pytest/conftest.py
- fabtests/pytest/efa/test_fork_support.py
- fabtests/pytest/efa/test_from_default.py
- fabtests/pytest/efa/test_mr.py
- fabtests/pytest/efa/test_runt.py
add test cases for memory registration for both host memory and cuda memory
> fabtests/pytest/efa: add mr test

- prov/net/src/xnet_progress.c
We no longer start the progress thread, but trywait is okay as-is. Clarify why.
> prov/net: Fixup comment above xnet_trywait

- include/ofi_net.h
- src/common.c
The byte queue abstraction is managing what is basically a ring buffer.  However, that abstraction is broken by 2 calls (send and receive) where we pass in a socket.  Replace those calls and keep all socket access in the bsock abstraction.
This requires adding 2 new helper functions to add and consume data from the byteq.  This keeps the byteq abstraction generic, so that it's not tied to a socket, which will be useful in follow on patches to support io_uring.
(The byteq and ringbuf abstractions may be mergable, but that would need to be a separate change.)
> core/net: Restructure interface between bsock and byteq

- contrib/intel/jenkins/Jenkinsfile
Interface issue resolved. Re-enabling testing
> contrib/intel: re-enable shm ze testing

- include/ofi_mem.h
- prov/rxm/src/rxm_ep.c
- prov/util/src/util_buf.c
> [v1.15.x] Revert buffer pool flag changes

- include/ofi_mem.h
- prov/rxm/src/rxm_ep.c
- prov/util/src/util_buf.c
> [v1.16.x] Revert buffer pool flag changes

- fabtests/multinode/src/timing.c
> fabtests/multinode: Fix build warnings for unint vars

- fabtests/pytest/efa/efa_common.py
> fabtests/pytest/efa: retry when efa_retrieve_hw_counter_value hit ssh error

- prov/efa/src/efa_user_info.c
> prov/efa: Fix shm initialization path on error

- fabtests/multinode/src/core_coll.c
- include/ofi_coll.h
- include/ofi_enosys.h
- include/rdma/fabric.h
- include/rdma/fi_collective.h
- include/rdma/fi_domain.h
- include/rdma/fi_endpoint.h
- man/fi_collective.3.md
- man/fi_domain.3.md
- man/fi_endpoint.3.md
- man/fi_peer.3.md
- prov/util/src/util_coll.c
- src/enosys.c
* New calls to open domain & endpoint with flags
* Add flags to fi_barrier()
> core: API changes for peer provider and collectives

- prov/efa/src/efa_user_info.c
(cherry picked from commit 89878670f01937a8162fb0218e2084aed334b86c)
> [v1.16.x] prov/efa: Fix shm initialization path on error

- fabtests/functional/rdm_rma_trigger.c
> fabtests/rdm_rma_trigger: add sync to make sure counter values match

- include/ofi_hmem.h
- src/hmem.c
- src/hmem_rocr.c
> hmem: Support ROCR get_base_addr

- prov/net/src/xnet_progress.c
I was reviewing the code for the net provider when I found 2 possible bugs there. 
These bug fixes are based on my personal understanding of the code, which is probably not perfect :)
> prov/net: Various bug fixes

- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_op_entry.h
- prov/efa/src/rxr/rxr_pkt_cmd.c
fix bugs in emulated read protocol refactor
> prov/efa: fix bugs with emulated read refactor

- AUTHORS
- Makefile.am
- NEWS.md
- configure.ac
- fabtests/Makefile.am
- fabtests/configure.ac
- include/rdma/fabric.h
- include/windows/config.h
Merging this change into main prior to creating v1.17.x branch.
> v1.17.0rc1

- prov/efa/src/rxr/rxr_pkt_type_req.c
Currently rxr_pkt_req_hdr_size_from_pkt_entry() uses rxr_pkt_req_hdr_size() to calculate hdr size, which assumes the the raw address header size is always RXR_REQ_OPT_RAW_ADDR_HDR_SIZE.
The assumption is wrong because older version of efa provider uses a different opt raw address header size. The correct addres lenght is stored in the "addr_len" field of the raw_addr_header.
This patch addressed the issue by making
rxr_pkt_req_hdr_size_from_pkt_entry() not to call rxr_pkt_req_hdr_size(), but calculate the size by itself.
> prov/efa: fix the calculcation of REQ header size for a packet entry

- include/ofi_epoll.h
- prov/util/src/util_cq.c
- src/common.c
A small set of minor fixes for ofi_epoll and util_cq
> util: Minor fixes for ofi_epoll and util_cq

- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_op_entry.h
- prov/efa/src/rxr/rxr_pkt_cmd.c
1. merge tx_entry_queued_rnr_list and rx_entry_queued_rnr_list
2. remove state RXR_RX_QUEUED_CTRL
3. remove unused states
> prov/efa: mulitple fixes

- .github/workflows/coverity.yml
- .github/workflows/pr-ci.yml
ubuntu 18.04 runners are being deprecated, move to ubuntu-latest
Signed-off-by: Stephen Oost <stephen.oost@intel.com>
> github/workflows: update tested ubuntu versions

- prov/net/src/xnet.h
- prov/net/src/xnet_srx.c
Fix already queued for v1.17.x branch
> prov/net: minor restructures + fix for tagged_peek assert

- prov/net/src/xnet.h
- prov/net/src/xnet_srx.c
These 2 patches aren't fixes by themselves but are needed for a patch that follows these 2 that is a fix.  That actual fix is still being evaluated.
> [v1.17.x] prov/net: Update to align with main

- man/fi_peer.3.md
> man/peer: Clearly indicate that peer APIs are not stable

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/build.py
- contrib/intel/jenkins/summary.py
Additions to Summary.py:
Add a Logger class to print output to stdout and a specific local file
Add a Release class to handle printing of Makefile.am and configure.ac diffs, as well as the release number
Simplify the main class by moving the big logic block into a function
Small variable updates/localizations
Additions to Jenkinsfile:
Add logic to determine if a job is suspected to be a release
This will only push if all stages succeeded
Add version control pushing of local log files that contain:
release number,
Makefile.am diff (if there is one),
configure.ac diff (if there is one)
Non verbose summary
Add release arguments to build.py and summary.py calls
> contrib/intel/jenkins: Add local file logging and release job version control to summary

- prov/efa/src/rxr/rxr_ep.c
This check had essentially no effect
> prov/efa: Remove HMEM check from rxr_ep_ctrl()

- src/hmem_ze.c
Instead of creating and destroying a command list for every copy, create a pool of command lists that we can reuse by resetting them.
> src/hmem_ze: add ZE command list pool to reuse command lists

- prov/efa/src/efa_hmem.c
- prov/efa/src/rxr/rxr_ep.c
fix a bug in fi_setopt of FI_HMEM_P2P_OPT, and a refactor
> prov/efa: fix setopt hmem p2p opt and refactor

- fabtests/multinode/src/core_coll.c
fi_join() operation may produce several completion events if more than one ep is called. This can happen especially when offload and util providers are joining at the same time. In such a case, we should wait for final completion that comes from the top collective provider.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ofiwg/libfabric/8303)
> fabtests/multinode check event's context when read FI_JOIN_COMPLETE

- libfabric.vcxproj
> libfabric.vcproj: add hmem_cuda_gdrcopy.c to source list

- prov/efa/src/efa_hmem.c
- prov/efa/src/efa_hmem.h
- prov/efa/src/efa_user_info.c
- prov/efa/src/rxr/rxr_atomic.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_op_entry.h
- prov/efa/src/rxr/rxr_pkt_type_misc.c
- prov/efa/src/rxr/rxr_pkt_type_req.c
Formatting fixes.
Add emulated atomic support for CUDA.
Restrict claiming HMEM Atomic support to just HMEM CUDA interfaces.
> prov/efa: HMEM_CUDA Support For Emulated Atomics

- prov/efa/src/efa_mr.c
When cudaMemcpy is allowed, we want to use it and do not want to use gdrcopy. Gdrcopy is used when the memory is registered with gdrcopy.
Whether cudaMemcpy is allowed can now be determined by calling cuda_get_xfer_setting(). This patch therefore do not register memory with gdrcopy when cudaMemcpy is allowed.
> prov/efa: use cuda_xfer_setting to decide whether to use gdrcopy

- prov/efa/src/rxr/rxr_pkt_type_req.c
Atomics where implemented with VLA (variable length arrays) which are part of the C standard, but apparently not supported by the windows compiler.  Switching to malloc as a short term solution to get the build working again, and will eventually use a mempool.
Fixed some small naming issues
> prov/efa: Atomic VLA -> Malloc

- prov/efa/src/rxr/rxr_pkt_pool.c
> prov/efa: Release allocated pkt_pool if bufpool creation fails

- prov/efa/src/efa.h
- prov/efa/src/efa_domain.h
- prov/efa/src/efa_ep.c
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_msg.c
- prov/efa/src/rxr/rxr_pkt_type_base.c
- prov/efa/src/rxr/rxr_pkt_type_misc.c
- prov/efa/src/rxr/rxr_pkt_type_req.c
- prov/efa/src/rxr/rxr_read.c
- prov/efa/src/rxr/rxr_rma.c
- prov/efa/test/efa_unit_test_ep.c
Also add rnr_retry and hmem_p2p_opt to rxr_ep
> prov/efa: Remove some uses of rxr_ep->rdm_ep related to efa_domain

- prov/efa/src/rxr/rxr_pkt_cmd.c
> prov/efa: Remove unnecessary casts

- prov/efa/src/rxr/rxr_read.c
For SHM EP: use fi_read instead of fi_readmsg
For EFA EP: remove the call to efa_rma_post_read in efa_rma.c
> prov/efa: Call ibv_wr_read_rdma in rxr_read.c

- include/ofi_net.h
- src/common.c
ofi_sockerr() is only relevant for sockets operations: calling it for uring sockapi functions would return an incoherent code.
Problem is that the uring sockapi functions may return error codes like -FI_EAGAIN (no credit available, SQE is in use) or -FI_EOVERFLOW (ring overflowed). If those error codes are returned, the bsock API would try to convert them with ofi_sockerr(), which is wrong.
The patch pushes the calls to ofi_sockerr() down to the socket sockapi functions.
> ofi_net: Push ofi_sockerr() down to the socket sockapi functions

- prov/net/src/xnet_ep.c
- prov/net/src/xnet_progress.c
- prov/util/src/util_ep.c
The PR fixes 2 issues I have found while testing the provider:
- 1 memory leak when the EP is closed
- 1 annoying warn message that is printed for every EP that is closed.
> prov/net: A couple of hotfixes found while testing the provider

- prov/efa/src/rdm/rxr_op_entry.c
> prov/efa: fix comments in rxr_op_entry.c

- prov/hook/trace/src/hook_trace.c
> prov/hook/trace: Add trace log for CQ operation APIs.

- prov/efa/Makefile.include
- prov/efa/src/rdm/rxr_pkt_type_base.c
- prov/efa/test/efa_unit_test_ep.c
- prov/efa/test/efa_unit_test_mocks.c
- prov/efa/test/efa_unit_test_mocks.h
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
fixed a bug that caused an unnecessary copy
added a unit test to verify it
> prov/efa: remove one unnecessary copy and added a unit test

- prov/hook/trace/src/hook_trace.c
Changed to use msg/rma/tagged specific trace logs, so to better capture full information on the API calls.
> prov/hook/trace: Enhance trace log for data transfer API calls.

- man/fi_peer.3.md
> man/fi_peer.3.md: fix the sequence numbers in the examples.

- prov/hook/trace/src/hook_trace.c
> prov/hook/trace: Change tag in trace log to hex format.

- fabtests/functional/rdm_stress.c
- fabtests/test_configs/rdm_stress/stress-msg.json
- fabtests/test_configs/rdm_stress/stress-rd.json
- fabtests/test_configs/rdm_stress/stress-wr.json
> fabtests/rdm_stress: Add count option to json key/pair options

- include/ofi.h
- include/ofi_hmem.h
- include/ofi_iov.h
- include/ofi_mr.h
- prov/hook/hook_hmem/src/hook_hmem.c
- prov/psm3/src/psmx3.h
- prov/shm/src/smr.h
- prov/shm/src/smr_atomic.c
- prov/shm/src/smr_ep.c
- prov/shm/src/smr_msg.c
- prov/shm/src/smr_progress.c
- prov/shm/src/smr_rma.c
- prov/util/src/util_mr_map.c
- src/hmem.c
- src/iov.c
> prov/shm: enable multiple GPU iface/device support

- man/fi_opx.7.md
Two man page commits for changes relevant to the OPX provider.
> Man fix for opx prov

- prov/ucx/src/ucx_cq.c
With the default blocking CQ read functions (ofi_cq_sread*()), the ucx provider may block forever inside ofi_epoll_wait() since no progress can be made there. Create custom blocking CQ read functions that use sched_yield() instead of fi_wait().
> prov/ucx: Allow progress in blocking CQ reads

- prov/efa/docs/lttng.md
- prov/efa/src/rdm/rxr.h
I spelled a word wrong last year.
> prov/efa: Fix typo

- contrib/intel/jenkins/Jenkinsfile
> [v1.17.x] update Intel CI script

- include/osx/osd.h
Fixes: https://github.com/ofiwg/libfabric/issues/8496
> osd.h: fix spinlocks for macOS

- prov/hook/trace/src/hook_trace.c
Add trace log on cm operations for ep/pep.
Remove postfix "_op" in trace cq ops, to be consistent with other trace ops.
> prov/hook/trace: Add trace log for CM operation APIs.

- prov/efa/src/rdm/rxr.h
- prov/efa/src/rdm/rxr_ep.c
- prov/efa/src/rdm/rxr_pkt_entry.c
- prov/efa/src/rdm/rxr_pkt_entry.h
- prov/efa/src/rdm/rxr_pkt_pool.c
- prov/efa/src/rdm/rxr_pkt_pool.h
- prov/efa/src/rdm/rxr_pkt_type_base.c
- prov/efa/test/efa_unit_test_ep.c
A series of changes to re-arrange packet pool, aimed at reducing memory usage and improve performance
> prov/efa: re-arrange packet pool

- prov/efa/src/rdm/rxr_env.c
use_device_rdma was not set to a default value in rxr_env_get_use_device_rdma(). Hence when the environment variable FI_EFA_USE_DEVICE_RDMA is not set and the variable use_device_rdma is not set, random behaviour occurs.
This patch fixes the bug by initializing the default value of use_device_rdma.
> prov/efa: Set default value of use_device_rdma

- prov/efa/src/rdm/rxr_ep.c
With recent change that op_entry directly post remote read, read_entry is only allocated for local read. Therefore, the 1st read_entry can be allocated at different time of an application.
The 1st read_entry allocation is expensive because it will cause 1 chunk of memory to be allocated. When it happen at different time, the application overall performance can be impacted.
This patch address the issue by allowing the 1st chunk of the memory of read_entry_pool when progress engine is called the 1st time (inside rxr_grow_rx_pkt_pools).
> prov/efa: grow read_entry_pool when progress engine is called 1st time

- AUTHORS
- COPYING
- Makefile.am
- NEWS.md
- configure.ac
- fabtests/COPYING
- fabtests/configure.ac
- include/rdma/fabric.h
- include/windows/config.h
> v1.17.1rc1

- fabtests/pytest/efa/test_efa_protocol_selection.py
This fixes a bug that causes test failure on platforms without gdrcopy, where EFA will fallback to localread. Such data are also recorded in the hw counter.
This change should be backported to v1.17.x branch as well.
> fabtests/pytest/efa: use different assertions for protocol selection

- fabtests/pytest/efa/test_efa_protocol_selection.py
Backport a bugfix in fabtests.
> [v1.17.x] fabtests/pytest/efa: use different assertions for protocol selection

- man/fi_efa.7.md
Update fi_efa documentation with FI_EFA_USE_DEVICE_RDMA information
> man/fi_efa: Update with FI_EFA_USE_DEVICE_RDMA info

- prov/ucx/src/ucx_domain.c
- prov/ucx/src/ucx_rma.c
Use correct printf format string for uint64_t.
> prov/ucx: Fix compiler warnings in debug build

- Makefile.am
- configure.ac
- fabtests/configure.ac
- include/rdma/fabric.h
- include/windows/config.h
Move main version ahead of v1.17.x branch
> build: Update library version

- NEWS.md
updated based on git log for all currently included patches
> [v1.17.x] news: Update news for v1.17.1 release

- fabtests/pytest/efa/test_mr.py
Backport https://github.com/ofiwg/libfabric/pull/8611
> [v1.17.x] fabtests/pytest/efa: Remove the env append in test_mr.py

- prov/efa/src/rdm/rxr_pkt_cmd.c
- prov/efa/src/rdm/rxr_pkt_cmd.h
> prov/efa: remove rxr_pkt_wait_handshake

- prov/tcp/src/xnet_progress.c
When xnet_op_read_rsp() is executed, ep->cur_rx.entry is set to the head element of the list 'rma_read_queue'. The RX entry is effectively removed from the list only after the operation completes. This pattern becomes problematic if the EP is disabled before the RX completes (i.e., EP disabled because of a failing TX entry or an explicit shutdown). In this case, xnet_ep_flush_all_queues would complete the same RX entry twice: once when rma_read_queue is flushed (the RX entry is still listed here) and another time in the block for the condition "if (ep->cur_rx.entry)".
The patch removes the RX entry from rma_read_queue before it gets assigned to ep->cur_rx.entry. It guarantees that the RX entry will be completed only once if the EP is disabled.
> prov/tcp: Suspicion of bug where RX entry is freed twice

- prov/shm/src/smr_rma.c
two commits fix error completion in rma
> prov/shm: fix rma writing error completion in smr_generic_rma

- prov/efa/src/rdm/rxr_ep.h
> prov/efa: fix coverity defects

- prov/efa/src/rdm/rxr_pkt_type_base.c
This patch allows gdrcopy to be used when receive buffer is successfully registered with gdrcopy.
> prov/efa: allow gdrcopy to be used when available

- prov/shm/src/smr_ep.c
In smr_srx_context, shm should not modify the peer_ops of the imported srx. It should allocate a new srx and set it there.
This bug is fixed in https://github.com/ofiwg/libfabric/pull/8456 but that PR was closed. Open this PR for now
> prov/shm: fix the srx import procedure.

- include/rdma/fi_ext.h
- libfabric.vcxproj
- man/fi_efa.7.md
- prov/efa/Makefile.include
- prov/efa/configure.m4
- prov/efa/src/dgram/efa_dgram_ep.c
- prov/efa/src/efa.h
- prov/efa/src/efa_base_ep.c
- prov/efa/src/efa_base_ep.h
- prov/efa/src/efa_device.c
- prov/efa/src/efa_device.h
- prov/efa/src/efa_domain.c
- prov/efa/src/efa_domain.h
- prov/efa/src/efa_user_info.c
- prov/efa/src/rdm/efa_rdm_peer.h
- prov/efa/src/rdm/efa_rdm_util.c
- prov/efa/src/rdm/efa_rdm_util.h
- prov/efa/src/rdm/rxr_env.c
- prov/efa/src/rdm/rxr_env.h
- prov/efa/src/rdm/rxr_ep.c
- prov/efa/src/rdm/rxr_ep.h
- prov/efa/src/rdm/rxr_msg.c
- prov/efa/src/rdm/rxr_pkt_type_base.c
- prov/efa/test/efa_unit_test_common.c
- prov/efa/test/efa_unit_test_ep.c
- prov/efa/test/efa_unit_test_info.c
- prov/efa/test/efa_unit_test_mocks.c
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
back port recent changes to main
> [v1.18.x] prov/efa: backport recent changes

- prov/efa/src/rdm/rxr_ep.c
> prov/efa: fix switch case fallthrough

- include/shared/ofi_str.h
- include/windows/osd.h
- info.vcxproj
- info.vcxproj.filters
- src/shared/ofi_str.c
ofi_tostr_size() converts size to str with 1024 base G/M/K. ofi_tostr_count() convers count to str with 1000 base B/M/K.
> core/tostr: Add helper functions ofi_tostr_size() and ofi_tostr_count().

- prov/opx/Makefile.include
- prov/opx/include/fi_opx_tid.h
- prov/opx/include/opa_udebug.h
- prov/opx/include/rdma/opx/fi_opx_debug_counters.h
- prov/opx/include/rdma/opx/fi_opx_domain.h
- prov/opx/include/rdma/opx/fi_opx_endpoint.h
- prov/opx/include/rdma/opx/fi_opx_hfi1_packet.h
- prov/opx/include/rdma/opx/fi_opx_hfi1_progress.h
- prov/opx/include/rdma/opx/fi_opx_hfi1_sdma.h
- prov/opx/include/rdma/opx/fi_opx_hfi1_transport.h
- prov/opx/include/rdma/opx/fi_opx_match.h
- prov/opx/include/rdma/opx/fi_opx_rma.h
- prov/opx/src/fi_opx_atomic.c
- prov/opx/src/fi_opx_cm.c
- prov/opx/src/fi_opx_domain.c
- prov/opx/src/fi_opx_ep.c
- prov/opx/src/fi_opx_fabric.c
- prov/opx/src/fi_opx_hfi1.c
- prov/opx/src/fi_opx_init.c
- prov/opx/src/fi_opx_progress.c
- prov/opx/src/fi_opx_reliability.c
- prov/opx/src/fi_opx_service.c
- prov/opx/src/fi_opx_sysfs.c
- prov/opx/src/fi_opx_tid_domain.c
- prov/opx/src/opa_proto.c
Sorry for the delay.
Includes:
-Observability enhancements
-Expected receive fixes/tunings (still not enabled by default for OPX provider)
-Enhancements to tag matching
-Fixes for Coverity scan issues
> OPX provider updates

- include/rdma/fabric.h
- prov/hook/trace/src/hook_trace.c
- src/fi_tostr.c
Add trace log on mr reg operations and trace on cq, endpoint, scalable_ep, av,
and cntr open operation.
> prov/hook/trace: Add trace for resource creation operations.

- include/ofi_iov.h
This patch introduced two functions:
ofi_iov_locate() and
ofi_rma_iov_locate()
to find iov_index and iov_offset for an offset
> include/ofi_iov.h: locate iov_index and iov_offset for an offset

- prov/efa/src/efa_mr.c
- prov/efa/src/efa_mr.h
- prov/efa/src/rdm/rxr_ep.c
Backport of https://github.com/ofiwg/libfabric/pull/8795 to v1.18.x
> [v1.18.x] prov/efa: Fixes for RDMA Write and Writedata

- prov/efa/src/rdm/rxr_ep.c
- prov/efa/src/rdm/rxr_ep.h
> prov/efa: remove stale functions in rxr_ep.c and rxr_ep.h

- prov/tcp/src/xnet_domain.c
The domain lock must be held while deregistering a memory region, otherwise the underlying MR map might be corrupted if it is accessed by concurrent threads.
> prov/tcp: Hold domain lock while deregistering memory

- prov/efa/src/efa_domain.h
- prov/efa/src/efa_hmem.h
fix some issues with these two header file
> prov/efa: fix issues with efa_domain.h and efa_hmem.h

- prov/efa/src/efa_av.c
- prov/efa/src/efa_fork_support.c
- prov/efa/src/rdm/rxr_ep.c
- prov/efa/src/rdm/rxr_msg.h
- prov/efa/src/rdm/rxr_pkt_pool.c
Fix various bugs identified by coverity
> prov/efa: fix coverity identified bugs

- fabtests/component/dmabuf-rdma/fi-rdmabw-xe.c
> [v1.18.x] fabtests: new options for the fi-rdmabw-xe tests

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/build.py
- contrib/intel/jenkins/common.py
- contrib/intel/jenkins/runtests.py
- contrib/intel/jenkins/summary.py
- contrib/intel/jenkins/tests.py
Old files don't work properly with current CI infrastructure. The difference between the branch and main is too big to cherry-pick.
The 'net' provider is no long tested since it has been renamed to 'tcp' in main.
> [v1.17.x] contrib/intel/jenkins: Update with files from main

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/build.py
- contrib/intel/jenkins/common.py
- contrib/intel/jenkins/run.py
- contrib/intel/jenkins/runtests.py
- contrib/intel/jenkins/summary.py
- contrib/intel/jenkins/tests.py
- fabtests/Makefile.am
- fabtests/scripts/runmultinode.sh
Old files don't work properly with current CI infrastructure. The difference between the branch and main is too big to cherry-pick.
The v1.16.x branch doesn't support dsa. The jenkins scripts have some dsa related code but they are inactive.
> [v1.16.x] contrib/intel/jenkins: Update with files from main

- .appveyor.yml
- .github/workflows/coverity.yml
- .github/workflows/pr-ci.yml
Similar to #8870, with a few more cherry-picked commits since this branch is more behind.
> [v1.16.x] Cherry-picked fixes for CI

- libfabric.vcxproj
- prov/efa/Makefile.include
- prov/efa/src/efa_domain.c
- prov/efa/src/rdm/efa_rdm_atomic.c
- prov/efa/src/rdm/efa_rdm_atomic.h
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/src/rdm/efa_rdm_ep_utils.c
- prov/efa/src/rdm/efa_rdm_msg.c
- prov/efa/src/rdm/efa_rdm_msg.h
- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/src/rdm/efa_rdm_rma.c
- prov/efa/src/rdm/efa_rdm_rma.h
- prov/efa/src/rdm/efa_rdm_srx.c
- prov/efa/src/rdm/rxr_pkt_cmd.c
- prov/efa/src/rdm/rxr_pkt_entry.c
- prov/efa/src/rdm/rxr_pkt_type.h
- prov/efa/src/rdm/rxr_pkt_type_data.c
- prov/efa/src/rdm/rxr_pkt_type_misc.c
- prov/efa/src/rdm/rxr_pkt_type_req.c
- prov/efa/src/rdm/rxr_pkt_type_req.h
- prov/efa/src/rdm/rxr_rma.c
- prov/efa/test/efa_unit_test_ep.c
rxr_atomic -> efa_rdm_atomic
rxr_msg -> efa_rdm_msg
rxr_rma -> efa_rdm_rma
> prov/efa: rename rxr_atomic, rxr_msg and rxr_rma

- prov/efa/src/efa_mr.c
When EFA provider registers MR with SHM endpoint, pass in the associated hmem_data via fi_mr_attr.
> prov/efa: register shm MR with hmem_data

- prov/netdir/src/netdir_unexp.c
- prov/verbs/src/windows/verbs_nd_ibv.c
- prov/verbs/src/windows/verbs_nd_init.c
- prov/verbs/src/windows/verbs_nd_rdma.c
Problem reported by coverity.  Initialize all fields of ibv_wc.
> prov/verbs_nd: Initialize ibv_wc fields

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/tests.py
Opened to investigate some CI issues in daos.
> [Intel/CI]: Improvements for Jenkins daos testing

- prov/opx/include/rdma/opx/fi_opx_endpoint.h
- prov/opx/include/rdma/opx/fi_opx_hfi1_progress.h
- prov/opx/include/rdma/opx/fi_opx_reliability.h
- prov/opx/src/fi_opx_hfi1.c
- prov/opx/src/fi_opx_hfi1_sdma.c
- prov/opx/src/fi_opx_reliability.c
- prov/opx/src/fi_opx_tid_domain.c
Includes the following:
-Expected receive improvements
-More frequent updating of Receive Header Queue register
-Disabling Pre-NAKing by default
-Fix to a reliability bug
> Opx provider upstream for May

- prov/sm2/src/sm2_coordination.c
Remove the alignment of the list of allocation entries.  These are not page-aligned entries anyways, and are not in the critical path.
Correct the alignment of the regions which hold the xfer entries.  The alignment was previously based on universe size, but I believe that was the result of an erroneous refactor.
---
Note that this is not actually a format change to the sm2 coordination file.  The processes which creates the file gets to pick these pointer offsets and all other processes read and use them.
Also interesting to note that SM2_MAX_UNIVERSE_SIZE is 2048, so likely half a page.
on a machine with 4k pages:
ep_allocation_offset was 2048, now it is 72 bytes.
regions_offset was 149504 bytes (36.5 pages), now it is 151552 bytes (37 pages).
> prov/sm2: Align sm2 region start to page size

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/tests.py
Enabling ghostrankrpc test and multicntxt_one_node test on the CI
> [Intel/CI]: Adding more cart test

- prov/sm2/src/sm2.h
- prov/sm2/src/sm2_ep.c
Break out copy/pasted logic into sm2_pop_xfer_entry(), and move it to the header file so that it can be used by MSG/ATOMICS/RMA API's.
Move sm2_generic_format() to the header so it can be used by MSG/ATOMICS/RMA apis.
> prov/sm2: Move functions to header, and make them inline

- prov/netdir/src/netdir_cq.c
- prov/netdir/src/netdir_cq.h
- prov/netdir/src/netdir_ep.c
- prov/netdir/src/netdir_ep_msg.c
- prov/netdir/src/netdir_ndinit.c
- prov/netdir/src/netdir_unexp.c
- src/windows/osd.c
- util/windows/getopt/getopt.cpp
Updates mostly to netdir provider, plus some osd calls.
> windows: coverity inspired fixes

- prov/tcp/src/xnet_progress.c
When progressing receive data, we need to process all data that's been read into the socket prefetch buffer.  Prefetched data won't generate POLLIN events on the socket, since it's already been read from the kernel.
In the case of handling a truncated message, we write an error to the CQ, update the current rx msg to read off the rest of the message data, then return EAGAIN back to the progress loop.  This results in the progress loop exiting.  However, if there's data in the prefetch buffer, we won't return to claim it until the socket signals the POLLIN event.  In some MPICH tests, that doesn't occur, resulting in the test hanging.
Instead of returning to the progress loop, continue trying to read the message data and only return once the message completes or there's no data left to …
> prov/tcp: Handle prefetched data after reporting ETRUNC error

- prov/verbs/include/linux/verbs_osd.h
- prov/verbs/include/windows/verbs_osd.h
- prov/verbs/src/verbs_info.c
- prov/verbs/src/verbs_init.c
- prov/verbs/src/verbs_ofi.h
> prov/verbs: Delay device initialization

- Makefile.am
- include/ofi_mb.h
- prov/shm/configure.m4
- prov/shm/src/smr_ep.c
> [v1.18.x] prov/shm: add memory barrier before update resp->status for SAR

- fabtests/pytest/common.py
- fabtests/pytest/conftest.py
This PR makes neuron test parallelized
> fabtests/pytest: parallel neuron test

- fabtests/Makefile.am
- fabtests/pytest/efa/test_flood_peer.py
- prov/shm/src/smr.h
- prov/shm/src/smr_atomic.c
- prov/shm/src/smr_ep.c
- prov/shm/src/smr_msg.c
- prov/shm/src/smr_rma.c
two commits fix a shm provider bug, and a test
> [v1.18.x] prov/shm, fabtests/flood_peer: fix bug and add test

- prov/tcp/src/xnet_progress.c
When a completion is written to the CQ, the signaling fd is also written to.  This wakes up any thread blocked on the cq.  However, that signal is not cleared if the app is using fi_trywait() followed by blocking on the cq's completion fd.  This can result in the application thread spinning on fi_trywait() + fi_cq_read() loop.
Before returning from fi_trywait(), clear the signaling fd.  Also fail the trywait call if there are any pending completions to read.
> prov/tcp: Fix spinning on fi_trywait()

- include/ofi_mr.h
- prov/shm/src/smr_attr.c
- prov/shm/src/smr_ep.c
- prov/shm/src/smr_progress.c
Fix lack of FI_LOCAL_COMM in caps
Fix ROCR data coherency
Add assert to read inject path
Re-enable DSA
> [v1.18.x] prov/shm: cherry-picked fixes for 1.18.x

- fabtests/pytest/common.py
- fabtests/pytest/conftest.py
This patch backports main branch changes to execute cuda and neuron fabtests in parallel
> [v1.18.x] backport fabtests cuda,neuron parallelization changes

- fabtests/pytest/efa/efa_common.py
Need to backport another dependent change for parallel cuda tests.
> [v1.18.x] fabtests: backport cuda parallel test change

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/README
- contrib/intel/jenkins/build.py
- contrib/intel/jenkins/common.py
- contrib/intel/jenkins/run.py
- contrib/intel/jenkins/runtests.py
- contrib/intel/jenkins/summary.py
- contrib/intel/jenkins/tests.py
- fabtests/Makefile.am
- fabtests/common/hmem_ze.c
- fabtests/component/dmabuf-rdma/memcopy-xe.c
- fabtests/component/dmabuf-rdma/xe.c
- fabtests/component/dmabuf-rdma/xe.h
- fabtests/configure.ac
- fabtests/include/hmem.h
Cherry pick cloudbees migration changes to v1.18.x
Cherry pick libze_loader changes to fabtests so it isn't statically linked in fabtests
> [v1.18.x] contrib/intel/jenkins: Cherry pick cloudbees changes from main

- fabtests/pytest/efa/test_efa_device_selection.py
Increase timeout from 5s(default) to 30s
> pytest/efa: unset strict mode for dgram pingpong test

- prov/efa/src/rdm/rxr_msg.c
Sending messages for GPU type ifaces involves the protocols that require rdma-read on both sides. This patch forces handshake before selecting rtm for non-system ifaces so the both-side check should always work.
(cherry-picked from a0d733430d4e05)
> [v1.18.x] prov/efa: Force handshake before selecting rtm for non-system ifaces.

- prov/tcp/src/xnet_cm.c
Add additional return code failure information to select CM error messages.
> prov/tcp: Increase CM error debug output

- prov/efa/src/rdm/rxr_op_entry.c
This patch makes efa_rdm_ope_post_write() to be able to handle 0 byte write.
> [v1.18.x] prov/efa: make rxr_op_entry_post_write to handle 0 byte write

- contrib/intel/jenkins/build.py
- contrib/intel/jenkins/common.py
CI code changes to incorporate fabtests summary for ucx provider
and improvements in build step for ucx.
> UCX CI Summary/improvements

- prov/efa/docs/pkt-processing.md
- prov/efa/src/efa_av.c
- prov/efa/src/efa_mr.c
- prov/efa/src/efa_user_info.c
- prov/efa/src/rdm/efa_rdm_ep.h
- prov/efa/src/rdm/efa_rdm_ep_progress.c
- prov/efa/src/rdm/efa_rdm_msg.c
- prov/efa/src/rdm/efa_rdm_msg.h
- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/src/rdm/efa_rdm_pke.c
- prov/efa/src/rdm/efa_rdm_pke_cmd.c
- prov/efa/src/rdm/efa_rdm_pke_nonreq.c
- prov/efa/src/rdm/efa_rdm_pke_rta.c
- prov/efa/src/rdm/efa_rdm_pke_rtm.c
- prov/efa/src/rdm/efa_rdm_pke_utils.c
- prov/efa/src/rdm/efa_rdm_util.c
- prov/efa/test/efa_unit_test_ep.c
Replace the term RXR will proper terms in comments and documents
> prov/efa: fix rxr in comments and documents

- include/rdma/fabric.h
- include/rdma/providers/fi_peer.h
- man/fi_peer.3.md
This PR introduces peer counter API to fi_peer.
> core and man: Introduce the peer counter api

- fabtests/Makefile.am
- fabtests/pytest/efa/test_env.py
- prov/efa/Makefile.include
- prov/efa/src/efa_env.c
- prov/efa/src/efa_env.h
- prov/efa/src/efa_fork_support.c
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/test/efa_unit_test_ep.c
- prov/efa/test/efa_unit_test_fork_support.c
- prov/efa/test/efa_unit_test_mocks.c
- prov/efa/test/efa_unit_test_mocks.h
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
> prov/efa: add use_huge_page to efa_env

- prov/efa/src/efa_mr.c
EFA provider should be allowed to customize fi_mr_attr struct for internal memory registration, without affecting application fi_mr_attr with EFA.
This also helps avoiding ABI compatibility issues with new fi_mr_attr fields, if the application is compiled with an older libfabric.
> prov/efa: use an internal fi_mr_attr for memory registration

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/runtests.py
- contrib/intel/jenkins/summary.py
- contrib/intel/jenkins/tests.py
Cherrypick adding daos as multiple different agents from main to allow concurrent building and parallel running of daos smoke tests
> [v1.18.x] contrib/intel/jenkins: Pick daos into build and test nodes commit from main

- .github/workflows/nroff-elves.sh
Add fabtest man pages to the github actions scripts.
At least that's my hope with this change.
> github/actions: Update fabtests man pages

- src/hmem_cuda.c
Local testing on Debian has shown a case where the libnvidia-ml-so symlink to libnvidia-ml.so.1 doesn't exist (but libnvidia-ml.so.1 exists).  So, try to dlopen the .so.1 library if the generic .so dlopen fails.  In either case, if libnvidia-ml doesn't exist, but the CUDA shared libraries do, skip trying to use the NVML routines for getting the device count and just proceed to using the CUDA routine.
> Try libnvidia-ml.so.1 if .so symlink missing, and skip NVML when not available

- configure.ac
- include/unix/osd.h
- prov/util/src/util_mem_hooks.c
@shefty this PR adds support for risc-v.
> rv64g update

- src/hmem_cuda.c
[v1.18.x] Try libnvidia-ml.so.1 if .so symlink missing, and skip NVML when not available
Local testing on Debian has shown a case where the libnvidia-ml-so symlink to libnvidia-ml.so.1 doesn't exist (but libnvidia-ml.so.1 exists).  So, try to dlopen the .so.1 library if the generic .so dlopen fails.  In either case, if libnvidia-ml doesn't exist, but the CUDA shared libraries do, skip trying to use the NVML routines for getting the device count and just proceed to using the CUDA routine.
(cherry picked from commit 804be986ae9d8f5a7a0b81d1434e84347733a0c1)
> [v1.18.x] Try libnvidia-ml.so.1 if .so symlink missing, and skip NVML when not available

- contrib/intel/jenkins/Jenkinsfile
Cloudbees has been sending an email for every PR instead of just the weekly job. Updating the if/else logic to fix this.
> contrib/intel/jenkins: Update send_email logic

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/build.py
- contrib/intel/jenkins/common.py
- contrib/intel/jenkins/run.py
- contrib/intel/jenkins/runtests.py
- contrib/intel/jenkins/summary.py
- contrib/intel/jenkins/tests.py
- fabtests/Makefile.am
- fabtests/test_configs/ucx/ucx.exclude
- prov/shm/configure.m4
- prov/shm/src/smr_dsa.c
- prov/shm/src/smr_dsa.h
- prov/shm/src/smr_init.c
- prov/sm2/configure.m4
Update intel CI to match upstream/main
> [v1.18.x] contrib/intel: Update CI scripts to match upstream/main

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/summary.py
- contrib/intel/jenkins/tests.py
Update CI scripts to match upstream/main
> [v1.19.x] contrib/intel: Update CI scripts to match upstream/main

- fabtests/functional/unexpected_msg.c
- fabtests/pytest/conftest.py
- fabtests/pytest/efa/test_unexpected_msg.py
- fabtests/pytest/shm/shm_common.py
- fabtests/pytest/shm/test_unexpected_msg.py
- fabtests/scripts/runfabtests.py
Backport https://github.com/ofiwg/libfabric/pull/9230 and https://github.com/ofiwg/libfabric/pull/9231
> [v1.19.x] backport recent fabtests improvement

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/build.py
- contrib/intel/jenkins/summary.py
- contrib/intel/jenkins/tests.py
Pick dsa migration from standalone cluster to main cluster
> [v1.18.x] contrib/intel/jenkins: Pick DSA migration

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/build.py
- contrib/intel/jenkins/summary.py
- contrib/intel/jenkins/tests.py
Pick dsa migration from standalone cluster to main cluster
> [v1.19.x] contrib/intel/jenkins: Pick DSA migration

- prov/efa/test/efa_unit_test_cq.c
Backport https://github.com/ofiwg/libfabric/pull/9259 to v1.19.x
> [v1.19.x] prov/efa/test: Fix an assertion error.

- fabtests/prov/efa/src/rdm_rnr_queue_resend.c
- fabtests/pytest/efa/test_rnr.py
- prov/efa/src/rdm/efa_rdm_ep.h
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/src/rdm/efa_rdm_ep_progress.c
- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/src/rdm/efa_rdm_pke.c
- prov/efa/src/rdm/efa_rdm_pke.h
- prov/efa/src/rdm/efa_rdm_pke_cmd.c
- prov/efa/src/rdm/efa_rdm_pke_cmd.h
- prov/efa/src/rdm/efa_rdm_pke_nonreq.c
- prov/efa/src/rdm/efa_rdm_pke_nonreq.h
- prov/efa/test/efa_unit_test_rnr.c
Cherry-pick the changes in https://github.com/ofiwg/libfabric/pull/9276 to v1.19.x
> [v1.19.x]  prov/efa: Handle RNRs from RDMA writedata

- prov/efa/src/efa_prov.c
Backport https://github.com/ofiwg/libfabric/pull/9312 to v1.19.x
> [v1.19.x] prov/efa: Fix the efa_env_initialize() call sequence.

- prov/efa/docs/naming_convention.md
Noticed some typos while `git grep`ing for `g_device_list` and got carried away a bit.
> prov/efa: Touchup naming conventions doc

- prov/efa/src/efa_domain.c
This patch fixes a bug in EFA device name matching logic, which only accounts for the first prefix match. As a result, efa_10-rdm domain name is matched with efa_1 device instead of efa_10.
> prov/efa: fix efa device name matching

- prov/efa/src/efa_domain.c
This patch fixes a bug in EFA device name matching logic, which only accounts for the first prefix match. As a result, efa_10-rdm domain name is matched with efa_1 device instead of efa_10.
(cherry picked from commit 9961ccf2336d1f354f102f1c9b2c3a1305a7db6c)
> [v1.19.x] Backport prov/efa: fix efa device name matching

- prov/shm/src/smr_progress.c
ofi_mr_verify() grabs and releases the domain lock every iteration through the rma iov vector loop.  Grab the domain lock at the begining, and hold it until we are done verifying all the RMA IOV's.  It does not make sense to grab/free a lock in a loop.
> prov/shm: Reduce atomic locking with ofi_mr_map_verify

- fabtests/scripts/parseyaml.py
- fabtests/scripts/toCSV.py
Follow security best practice.
> fabtests/scripts: use yaml safe_load

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/build.py
- contrib/intel/jenkins/common.py
- contrib/intel/jenkins/run.py
- contrib/intel/jenkins/runtests.py
- contrib/intel/jenkins/summary.py
- contrib/intel/jenkins/tests.py
Cherry pick mpich test suite update and summary fast forward feature from upstream/main
> [v1.18.x] Pick mpichtestsuite update & fast forward feature

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/build.py
- contrib/intel/jenkins/common.py
- contrib/intel/jenkins/run.py
- contrib/intel/jenkins/runtests.py
- contrib/intel/jenkins/summary.py
- contrib/intel/jenkins/tests.py
Cherry pick mpich test suite update and summary fast forward feature from upstream/main
> [v1.19.x] Pick mpichtestsuite update & fast forward feature

- prov/efa/docs/efa_rdm_protocol_v4.md
- prov/efa/src/rdm/efa_rdm_msg.c
- prov/efa/src/rdm/efa_rdm_peer.h
- prov/efa/src/rdm/efa_rdm_pke_nonreq.c
- prov/efa/src/rdm/efa_rdm_pke_nonreq.h
- prov/efa/src/rdm/efa_rdm_protocol.h
- prov/efa/src/rdm/efa_rdm_rma.c
- prov/efa/test/efa_unit_test_common.c
- prov/efa/test/efa_unit_test_ep.c
- prov/efa/test/efa_unit_tests.h
Cherry-picked 8aa733e88^..d28e63aae
> [v1.19.x] prov/efa: Disallow RDMA read between incompatible EFA devices

- prov/efa/src/rdm/efa_rdm_pke.c
This change adjusts the posted buffer size to ibv_post_recv. Currently ep->mtu_size is used regardless of the actual pkt_size. In the case of zero-copy receive, the user provided buffer could be smaller than mtu_size - the actual useable size is stored in pkt_size.
> prov/efa: adjust posted receive size to pkt_size

- prov/efa/src/rdm/efa_rdm_pke.c
This change adjusts the posted buffer size to ibv_post_recv. Currently ep->mtu_size is used regardless of the actual pkt_size. In the case of zero-copy receive, the user provided buffer could be smaller than mtu_size - the actual useable size is stored in pkt_size.
(cherry picked from commit 55d1a5731ddc206d73b1be0f8922d4d568929ed6)
> [v1.19.x] prov/efa: backport adjust posted receive size to pkt_size

- prov/verbs/src/verbs_info.c
The domain name may contain a `-<xxx>` suffix, the original code used `strncmp(domain_name, dev_name, strlen(dev_name))` to check if the names match. However, this scheme does not work when the device name is a substring of the domain name (e.g. `mlx5_11-rdm` vs `mlx5_1`) and would incorrectly return match for such case.
> prov/verbs: Bug fix for matching domain name with device name

- prov/util/src/util_main.c
If users provide an auth_key as a hint, duplicate this auth_key into the return provider info.
> util: Update util_getinfo to dup auth_key

- include/ofi_list.h
> util: Define dlist_first_entry_or_null

- prov/util/src/util_attr.c
Verify that user provided auth key hints are sane.
> util: Add EP and domain auth key checking

- man/fi_efa.7.md
- prov/efa/src/efa_env.c
- prov/efa/src/efa_env.h
- prov/efa/src/efa_mr.c
- prov/efa/src/efa_mr.h
- prov/efa/src/rdm/efa_rdm_atomic.c
- prov/efa/src/rdm/efa_rdm_ep.h
- prov/efa/src/rdm/efa_rdm_msg.c
- prov/efa/src/rdm/efa_rdm_rma.c
> prov/efa: Move CUDA Sync Memops to EP Path

- prov/efa/src/dgram/efa_dgram_ep.h
- prov/efa/src/efa_base_ep.c
- prov/efa/src/efa_base_ep.h
- prov/efa/src/efa_domain.c
- prov/efa/src/rdm/efa_rdm_atomic.c
- prov/efa/src/rdm/efa_rdm_cq.c
- prov/efa/src/rdm/efa_rdm_ep.h
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/src/rdm/efa_rdm_ep_progress.c
- prov/efa/src/rdm/efa_rdm_msg.c
- prov/efa/src/rdm/efa_rdm_pke.c
- prov/efa/src/rdm/efa_rdm_rma.c
- prov/efa/test/efa_unit_test_cq.c
- prov/efa/test/efa_unit_test_ep.c
- prov/efa/test/efa_unit_test_rnr.c
Backport https://github.com/ofiwg/libfabric/pull/9463 and https://github.com/ofiwg/libfabric/pull/9465 to v1.19.x branch
> [v1.19.x] prov/efa: backport two fixes for performance

- .github/workflows/clang-format-check.yml
- .github/workflows/coverity.yml
- .github/workflows/gh-man.yaml
- .github/workflows/nroff-elves.yaml
- .github/workflows/pr-ci.yml
- .github/workflows/stale.yml
This should alleviate some warnings about deprecated Node.js versions
> ci: Upgrade various Actions versions

- src/hmem_synapseai.c
Synapseai currently initializes successfully if libraries are installed. Make synapseai only claim to be initialized if libraries are installed and a device exists.
(cherry picked from commit 95874ad4b5300ec6123aee178bf365211555c5da)
> [v1.19.x] src/hmem: Only initalize synapseai if device exists

- prov/util/src/util_av.c
- prov/util/src/util_cntr.c
- src/hmem.c
Fix a few Coverity issues in the core and util code.
> Coverity fixes

- AUTHORS
- Makefile.am
- NEWS.md
- README.md
- configure.ac
- fabtests/configure.ac
- include/ofi_hmem.h
- include/windows/config.h
- prov/psm2/src/psmx2_cq.c
- prov/sm2/src/sm2_progress.c
- prov/verbs/src/verbs_mr.c
- src/hmem.c
- src/hmem_cuda.c
- src/hmem_neuron.c
- src/hmem_synapseai.c
- src/hmem_ze.c
PR will be pushed directly along with release tags. This way the commit hashes will be preserved.
> v1.20.0rc1

- src/hmem_synapseai.c
Currently, synapseai_init return FI_ENODATA when there is no synapseai device on the platform. This will cause warnings are printed on any non-synapseai platform. This patch improves this by making synapseai_init return ENOSYS when all the API calls succeeded but zero devices are detected.
> hmem/synapseai: Refine the error handling and warning

- include/windows/config.h
- prov/efa/configure.m4
- prov/efa/src/efa_hmem.c
- prov/efa/src/efa_mr.c
This PR contains 2 commits to make efa provider onboard fi_mr_dmabuf API in mr reg
> prov/efa: Onboard fi_mr_dmabuf API in mem reg ops.

- include/windows/config.h
- prov/efa/configure.m4
- prov/efa/src/efa_hmem.c
- prov/efa/src/efa_mr.c
Backport https://github.com/ofiwg/libfabric/pull/9522 to v1.20.x
> [v1.20.x] prov/efa: Onboard fi_mr_dmabuf API in mem reg ops

- src/hmem_synapseai.c
Backport https://github.com/ofiwg/libfabric/pull/9523 to v1.20.x
> [v1.20.x] hmem/synapseai: Refine the error handling and warning

- .github/workflows/gh-man.yaml
- .github/workflows/nroff-elves.yaml
Changes to fabtests man pages should also trigger the man page converter and man page updater.
> github/actions: Add fabtests man page to the trigger condition

- AUTHORS
- NEWS.md
- configure.ac
- fabtests/configure.ac
- include/windows/config.h
Don't merge from the web GUI. Will be pushed directly to preserve the hash value (together with a tag).
> v1.20.0rc2

- .github/workflows/coverity.yml
- .github/workflows/gh-man.sh
- .github/workflows/gh-man.yaml
- .github/workflows/nroff-elves.sh
- .github/workflows/nroff-elves.yaml
- .github/workflows/pr-ci.yml
- .github/workflows/stale.yml
Actions are failing on the branch due to out-of-date settings.
> [v1.15.x] github/actions: Synchronize with main

- .github/workflows/coverity.yml
- .github/workflows/gh-man.sh
- .github/workflows/gh-man.yaml
- .github/workflows/nroff-elves.sh
- .github/workflows/nroff-elves.yaml
- .github/workflows/pr-ci.yml
- .github/workflows/stale.yml
Make sure the actions are up to date.
> [v1.16.x] github/actions: Synchronize with main

- .github/workflows/coverity.yml
- .github/workflows/gh-man.sh
- .github/workflows/gh-man.yaml
- .github/workflows/nroff-elves.sh
- .github/workflows/nroff-elves.yaml
- .github/workflows/pr-ci.yml
- .github/workflows/stale.yml
Make sure the actions are up-to-date.
> [v1.17.x] github/actions: Synchronize with main

- .github/workflows/coverity.yml
- .github/workflows/gh-man.sh
- .github/workflows/gh-man.yaml
- .github/workflows/nroff-elves.sh
- .github/workflows/nroff-elves.yaml
- .github/workflows/pr-ci.yml
- .github/workflows/stale.yml
Make sure the actions are up-to-date.
> [v1.18.x] github/actions: Synchronize with main

- .github/workflows/clang-format-check.yml
- .github/workflows/coverity.yml
- .github/workflows/gh-man.sh
- .github/workflows/gh-man.yaml
- .github/workflows/nroff-elves.sh
- .github/workflows/nroff-elves.yaml
- .github/workflows/pr-ci.yml
- .github/workflows/stale.yml
Make sure the actions are up-to-date.
> [v1.19.x] github/actions: Synchronize with main

- .github/workflows/gh-man.yaml
- .github/workflows/nroff-elves.yaml
Make sure the actions are up-to-date.
> [v1.20.x] github/actions: Synchronize with main

- fabtests/pytest/efa/test_rdm.py
- fabtests/pytest/efa/test_rma_bw.py
Add large message coverage to EFA tests.
> prov/efa: Test EFA with a 1GiB message

- fabtests/common/shared.c
- fabtests/include/shared.h
- fabtests/prov/efa/Makefile.include
- fabtests/prov/efa/src/efa_exhaust_mr_reg_common.c
- fabtests/prov/efa/src/efa_exhaust_mr_reg_common.h
- fabtests/prov/efa/src/efa_exhaust_mr_reg_rdm_pingpong.c
- fabtests/pytest/efa/conftest.py
- fabtests/pytest/efa/test_rdm.py
Follow up to https://github.com/ofiwg/libfabric/pull/9493
This PR adds a pingpong fabtest
> prov/efa: Add MR exhaustion pingpong fabtest

- prov/verbs/src/verbs_ep.c
When compiled with --enable-debug, the test fi_shared_ctx fails on the following assertion failure:
`fi_shared_ctx: prov/verbs/src/verbs_ofi.h:993: vrb_alloc_ctx: Assertion 'ofi_genlock_held(progress->active_lock)' failed.`
And here is the associated stack:
```
6  0x00007ffff7a39e96 in __GI___assert_fail (assertion=0x7ffff7f2ec28 "ofi_genlock_held(progress->active_lock)", file=0x7ffff7f2ec08 "prov/verbs/src/verbs_ofi.h", line=993, function=0x7ffff7f2f338 <__PRETTY_FUNCTION__.45> "vrb_alloc_ctx") at ./assert/assert.c:101 
7  0x00007ffff7e06b9b in vrb_alloc_ctx (progress=0x5555555ca1a0) at prov/verbs/src/verbs_ofi.h:993 
8  0x00007ffff7e0b9fe in vrb_post_srq (srx=0x5555555ca7c0, wr=0x7fffffffe120) at prov/verbs/src/verbs_ep.c:1603 
9  0x00007ffff7e0bd2d in vrb_srx_recv …
```
> prov/verbs: Add missing lock to protect SRX

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/build.py
- contrib/intel/jenkins/common.py
- contrib/intel/jenkins/run.py
- contrib/intel/jenkins/runtests.py
- contrib/intel/jenkins/summary.py
- contrib/intel/jenkins/tests.py
New CI uses slurm instead of Jenkins node allocation. Update branch to new scripts but remove invalid tests (ucx provider and DSA testing which came after).
Also changes name of dmabuf test which was changed after 1.16 from fi-rdmabw-xe
> [v1.16.x] contrib/intel: synchronize with main

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/build.py
- contrib/intel/jenkins/common.py
- contrib/intel/jenkins/run.py
- contrib/intel/jenkins/runtests.py
- contrib/intel/jenkins/summary.py
- contrib/intel/jenkins/tests.py
New CI uses slurm instead of Jenkins node allocation. Update branch to new scripts but remove invalid tests (dmabuf tests and DSA testing which came after)
> [v1.15.x] contrib/intel: synchronize with main

- fabtests/common/hmem.c
- fabtests/common/shared.c
- fabtests/component/sock_test.c
- fabtests/functional/rdm_stress.c
- fabtests/regression/sighandler_test.c
> [v1.16.x] Cherry-pickes fixes to allow CI build check to pass

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/build.py
- contrib/intel/jenkins/common.py
- contrib/intel/jenkins/run.py
- contrib/intel/jenkins/runtests.py
- contrib/intel/jenkins/summary.py
- contrib/intel/jenkins/tests.py
- prov/shm/configure.m4
- prov/shm/src/smr_dsa.c
- prov/shm/src/smr_dsa.h
- prov/shm/src/smr_init.c
New CI uses slurm instead of Jenkins node allocation.
Also changes name of dmabuf test which was changed after 1.17 from fi-rdmabw-xe
> [v1.17.x] contrib/intel: synchronize with main

- fabtests/common/hmem.c
- fabtests/common/shared.c
> [v1.15.x] Cherry-picked fixes to allow CI build check to pass

- configure.ac
- fabtests/common/hmem.c
- fabtests/common/shared.c
- fabtests/component/sock_test.c
- fabtests/functional/rdm_stress.c
- fabtests/regression/sighandler_test.c
(1) Fix MacOS build issues
(2) Fix build issue with '--with-lttng' configure option
> [v1.17.x] Cherry-picked fixes to allow CI build check to pass

- prov/efa/src/rdm/efa_rdm_rma.c
backport https://github.com/ofiwg/libfabric/pull/9580
> [v1.20.x] prov/efa: Don't do handshake for local fi_write

- man/fi_provider.7.md
(cherry picked from commit 474be8450595a5acda391661b5f71b97cfb6321a)
> [v1.20.x] man: Add ucx provider to the fi_provider man page

- prov/util/src/util_mem_hooks.c
> prov/util_mem_hooks: add missing parantheses

- prov/efa/src/rdm/efa_rdm_rma.c
backport https://github.com/ofiwg/libfabric/pull/9640
> [v1.20.x] prov/efa: Don't do handshake for local read

- fabtests/pytest/common.py
> fabtests/pytest: add a new ssh connection error pattern

- fabtests/pytest/common.py
Same as title
(cherry picked from commit 1d76026249b0b1a91053e0cbf8090dae2ae48706)
> [v1.20.x] backport fabtests/pytest: add a new ssh connection error pattern

- fabtests/pytest/common.py
Same as title
(cherry picked from commit 1d76026249b0b1a91053e0cbf8090dae2ae48706)
> [v1.19.x] backport fabtests/pytest: add a new ssh connection error pattern

- fabtests/prov/efa/src/efa_exhaust_mr_reg_common.c
- fabtests/prov/efa/src/efa_exhaust_mr_reg_common.h
- fabtests/prov/efa/src/efa_exhaust_mr_reg_rdm_pingpong.c
Backport of https://github.com/ofiwg/libfabric/pull/9676
> [v1.19.x] fabtests/efa: Improve MR exhaustion test

- man/fi_efa.7.md
Backport https://github.com/ofiwg/libfabric/pull/9670
> [v1.20.x] man: Update EFA docs for FI_EFA_INTER_MIN_READ_WRITE_SIZE

- fabtests/prov/efa/src/efa_exhaust_mr_reg_common.c
- fabtests/prov/efa/src/efa_exhaust_mr_reg_common.h
- fabtests/prov/efa/src/efa_exhaust_mr_reg_rdm_pingpong.c
Backport of https://github.com/ofiwg/libfabric/pull/9676
> [v1.20.x] fabtests/efa: Improve MR exhaustion test

- src/hmem_rocr.c
43e92bf82a introduce a build breakage for earlier versions of rocm. The DMA buf defines were added to handle compatibility, but were not added around the callback functions. This led to compile error:
src/hmem_rocr.c:182:36:
error: ‘hsa_amd_portable_export_dmabuf’ undeclared here (not in a function)
.hsa_amd_portable_export_dmabuf = hsa_amd_portable_export_dmabuf,
Also made a few changes to clean up warnings and code style.
> rocr: fix issue introduced by 43e92bf82a

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/build.py
- contrib/intel/jenkins/common.py
- contrib/intel/jenkins/run.py
- contrib/intel/jenkins/runtests.py
- contrib/intel/jenkins/summary.py
- contrib/intel/jenkins/tests.py
Pick CI architecture changes from PR-9638
> [v1.20.x] contrib/intel/jenkins: Pick CI architecture changes

- include/ofi_hmem.h
- prov/shm/src/smr.h
- prov/shm/src/smr_ep.c
- prov/shm/src/smr_progress.c
- src/hmem_ze.c
-dynamically allocate device info and resource to remove hard coded maximum
-create mapping between physical devices and user space devices to fix shm IPC fd mapping
-fix copy engine environment variable
> src/hmem_ze, prov/shm: dynamically allocate device resource, create mapping between physical devices and user space devices

- AUTHORS
- Makefile.am
- NEWS.md
- configure.ac
- fabtests/configure.ac
- include/rdma/fabric.h
- include/windows/config.h
- prov/psm3/psm3/hal_sockets/sockets_spio.c
For CI test only. Don't merge. Will be pushed directly.
> v1.18.3rc1

- AUTHORS
- Makefile.am
- NEWS.md
- configure.ac
- fabtests/configure.ac
- include/rdma/fabric.h
- include/windows/config.h
For CI test only. Don't merge. Will be pushed directly.
> v1.19.1rc1

- AUTHORS
- Makefile.am
- NEWS.md
- configure.ac
- fabtests/configure.ac
- include/rdma/fabric.h
- include/windows/config.h
For CI test only. Don't merge. Will be pushed directly.
> v1.20.1rc1

- prov/util/src/util_wait.c
All write accesses to `wait->signal` are protected by the lock. The read access should be protected, too.
> util: Fix coverity issue about missing lock

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/build.py
- contrib/intel/jenkins/common.py
- contrib/intel/jenkins/run.py
- contrib/intel/jenkins/runtests.py
- contrib/intel/jenkins/summary.py
- contrib/intel/jenkins/tests.py
Pick CI architecture changes from PR-9638
> [v1.18.x] contrib/intel/jenkins: Pick CI architecture changes

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/build.py
- contrib/intel/jenkins/common.py
- contrib/intel/jenkins/run.py
- contrib/intel/jenkins/runtests.py
- contrib/intel/jenkins/summary.py
- contrib/intel/jenkins/tests.py
Pick CI architecture changes from PR-9638
> [v1.19.x] contrib/intel/jenkins: Pick CI architecture changes

- fabtests/pytest/efa/test_rdm.py
- fabtests/pytest/efa/test_rma_bw.py
Adding a test with a small rx size, and with a test with small tx + small rx size.
> fabtests/efa: Expand the small_tx test to small_tx_rx

- contrib/intel/jenkins/tests.py
This commit updates the dmabuf stage to support tile-to-tile 
testing based on hierarchy update to newer agama versions.
> Intel/CI: Update dmabuf stage to support subdevice testing

- contrib/intel/jenkins/summary.py
OneCCL and OneCCL GPU stages were missing test names and correct
test numbers
SHMEM is missing PRK and ISx test names from the summary.
This patch adds the capability to find the test names and add
them to the passed and failed test lists for verbose reporting.
Tests will have the type of SHMEM test added as a prefix to them.
> Intel/CI: Fix missing test names in summary

- contrib/intel/jenkins/summary.py
- contrib/intel/jenkins/tests.py
- fabtests/test_configs/tcp/io_uring.exclude
Disable more failing io_uring tests
Bugfix summaries for shmem and oneccl tests
Add more tests to ze dmabuf tests
> [v1.20.x] contrib/intel/jenkins: Pick CI Summary Bugfixes

- contrib/intel/jenkins/summary.py
- contrib/intel/jenkins/tests.py
- fabtests/test_configs/tcp/io_uring.exclude
Disable more failing io_uring tests
Bugfix summaries for shmem and oneccl tests
Add more tests to ze dmabuf tests
> [v1.19.x] contrib/intel/jenkins: Pick CI Summary Bugfixes

- prov/efa/src/rdm/efa_rdm_pke_cmd.c
- prov/efa/test/efa_unit_test_cq.c
backport https://github.com/ofiwg/libfabric/pull/9812
> [v1.20.x] prov/efa: Handle rx pkts error without ope

- src/fabric.c
DL providers can be found under three types of locations: 
(1) The search path of ld.so
(2) Default libfabric DL provider installation path 
(3) Path specified by FI_PROVIDER_PATH
For (2) and (3), only provider libraries that actually exist at those locations are attempted with dlopen().
For (1), dlopen() is called with constructed lib names of all enabled providers to find out if those libs eixst and can be opened. In most cases, the attempts would fail because DL providers are usually not installed there.
Commit f4715e8382bb90e changed the log level of failed dlopen() calls from 'warn' to 'dbg' to suppress the error messages generated by case (1), which we usually don't care. However, it also suppressed the error messages for case (2) and (3), which are very useful in diagnozing why a …
> fabric: Selectively generate warnings on failed loading of DL providers

- prov/efa/src/rdm/efa_rdm_rma.c
backport https://github.com/ofiwg/libfabric/pull/9817
> [v1.20.x] prov/efa: Remove unnecessary check in rdma write.

- prov/opx/configure.m4
- prov/opx/include/rdma/opx/fi_opx_compiler.h
- prov/opx/include/rdma/opx/fi_opx_hfi1_packet.h
- prov/opx/include/rdma/opx/fi_opx_timer.h
adding riscv support to the ops provider.
> adding riscv support to opx conf

- include/rdma/fabric.h
- man/fi_endpoint.3.md
- src/fi_tostr.c
Reserve new Receiver-Not-Ready endpoint protocol for CXI provider.
> core: Add new CXI endpoint protocol FI_PROTO_CXI_RNR

- configure.ac
-pipe will speed up compilation
> configure: Add -pipe by default to CFLAGS

- prov/util/src/util_mem_monitor.c
When the import monitor is closed, its state is not updated. Then later, during provider cleanup when ofi_monitors_del_cache() is called, and the last cache is removed from the import monitor's cache list, the monitor's state is seen as running, and an attempt is made to stop it. Since the close already set impmon.impfid to NULL, this results in a failed assert/segfault.
This change sets the import monitor's state to idle when closed. In ofi_monitors_del_cache(), only update a monitor when the monitor's state needs updating.
> prov/util: Set import monitor state to idle upon close

- fabtests/prov/efa/src/rdm_rnr_queue_resend.c
Currently, atomic resources can be not cleaned up when alloc_atomic_res failed. This patch fixes it by always cleaning up all atomic resources once at the parent test function returns.
> fabtests/efa: fix coverity issues in rnr_queue_resend test

- fabtests/unit/getinfo_test.c
fix coverity # 414977 and # 414791
> Fabtests Coverity Issues

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/build.py
- contrib/intel/jenkins/common.py
- contrib/intel/jenkins/runtests.py
- contrib/intel/jenkins/summary.py
- contrib/intel/jenkins/tests.py
Add cuda + fabtests tests to CI. These will be the same tests that are run through shm + ze.
> contrib/intel/jenkins: Add cuda fabtests to CI

- include/rdma/fi_eq.h
- man/fi_cntr.3.md
- src/fi_tostr.c
Define new enum value to support byte counting with counters.
> rdma/fi_eq: Support cntr byte counting

- prov/efa/src/rdm/efa_rdm_ep_fiops.c
EFA provider supports delivery complete
> prov/efa: Remove wrong efa info

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/summary.py
- contrib/intel/jenkins/tests.py
- Add more providers to both oneccl CPU and GPU stages.
- Update summary for both stages.
> Intel/CI: Update oneccl CPU and GPU tests

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/build.py
- contrib/intel/jenkins/common.py
- contrib/intel/jenkins/run.py
- contrib/intel/jenkins/runtests.py
- contrib/intel/jenkins/summary.py
- contrib/intel/jenkins/tests.py
Pick Cuda, Shmem and oneCCL test updates from upstream/main
> [v1.19.x] contrib/intel/jenkins: Pick cuda, shmem, and oneCCL test updates

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/build.py
- contrib/intel/jenkins/common.py
- contrib/intel/jenkins/run.py
- contrib/intel/jenkins/runtests.py
- contrib/intel/jenkins/summary.py
- contrib/intel/jenkins/tests.py
Pick Cuda, Shmem and oneCCL test updates from upstream/main
> [v1.20.x] contrib/intel/jenkins: Pick cuda, shmem, and oneCCL test updates

- man/fi_opx.7.md
- prov/opx/include/fi_opx_tid.h
- prov/opx/include/fi_opx_tid_cache.h
- prov/opx/include/opa_service.h
- prov/opx/include/opa_user_gen1.h
- prov/opx/include/rdma/opx/fi_opx_debug_counters.h
- prov/opx/include/rdma/opx/fi_opx_domain.h
- prov/opx/include/rdma/opx/fi_opx_endpoint.h
- prov/opx/include/rdma/opx/fi_opx_eq.h
- prov/opx/include/rdma/opx/fi_opx_hfi1.h
- prov/opx/include/rdma/opx/fi_opx_hfi1_packet.h
- prov/opx/include/rdma/opx/fi_opx_hfi1_sdma.h
- prov/opx/include/rdma/opx/fi_opx_hfi1_transport.h
- prov/opx/include/rdma/opx/fi_opx_hmem.h
- prov/opx/src/fi_opx_ep.c
- prov/opx/src/fi_opx_hfi1.c
- prov/opx/src/fi_opx_hfi1_sdma.c
- prov/opx/src/fi_opx_init.c
- prov/opx/src/fi_opx_mr.c
- prov/opx/src/fi_opx_reliability.c
- prov/opx/src/fi_opx_service.c
- prov/opx/src/fi_opx_tid_cache.c
Commits include:
-Cuda and GPU-specific improvements
-Excluding empty immediate date 
-Improving HFI (NIC) selection logic
-Small refactoring and bug fixes
-Memory leak fixes.
> Cornelis Networks OPX provider upstream

- man/fabric.7.md
> man: Add description of FI_PROVIDER_PATH to fabric.7.md

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/build.py
- contrib/intel/jenkins/summary.py
- contrib/intel/jenkins/tests.py
Pick CI changes from #9903  and #9904
> [v1.20.x] contrib/intel/jenkins Pick CI changes for release

- .github/workflows/clang-format-check.yml
- .github/workflows/coverity.yml
- .github/workflows/gh-man.yaml
- .github/workflows/nroff-elves.yaml
- .github/workflows/pr-ci.yml
Avoid granting excessive permissions.
> github/workflow: Define permissions for actions

- .github/workflows/coverity.yml
`environments` is not a valid property.
> github/workflows: Update coverity.yml

- contrib/aws/Jenkinsfile
- contrib/aws/common.groovy
Adds windows test to new AWS CI
> contrib/aws: Add Windows Test

- contrib/aws/Jenkinsfile
- contrib/aws/common.groovy
(cherry picked from commit 996431aadd72e979469f9a09a11765b536efaee2)
> [v1.20.x] contrib/aws: Add Windows Test

- contrib/aws/Jenkinsfile
- contrib/aws/common.groovy
(cherry picked from commit 996431aadd72e979469f9a09a11765b536efaee2)
> [v1.21.x] contrib/aws: Add Windows Test

- man/fi_mr.3.md
Remove unintended bullet point
> man/fi_mr: superficial format fix

- man/fi_mr.3.md
FI_RAW_MR should be replaced to FI_MR_RAW
> man/fi_mr: Fix typo

- fabtests/functional/multi_ep.c
- fabtests/prov/efa/src/efa_exhaust_mr_reg_common.c
- fabtests/prov/efa/src/efa_exhaust_mr_reg_common.h
- fabtests/prov/efa/src/efa_exhaust_mr_reg_rdm_pingpong.c
- fabtests/prov/efa/src/efa_info_test.c
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/shm/src/smr_ep.c
Fix several memory leaks in efa and shm provider caught by ASAN
> prov/efa, shm, fabtests: ASAN memory leaks fix

- fabtests/functional/multi_ep.c
- fabtests/prov/efa/src/efa_exhaust_mr_reg_common.c
- fabtests/prov/efa/src/efa_exhaust_mr_reg_common.h
- fabtests/prov/efa/src/efa_exhaust_mr_reg_rdm_pingpong.c
- fabtests/prov/efa/src/efa_info_test.c
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/shm/src/smr_ep.c
> [v1.21.x] Backport ASAN detected memory leaks fix

- fabtests/multinode/src/harness.c
- fabtests/pytest/default/test_multinode.py
- fabtests/scripts/runfabtests.cmd
- fabtests/scripts/runfabtests.sh
- fabtests/scripts/runmultinode.sh
- fabtests/test_configs/tcp/io_uring.exclude
Update arguments to avoid conflicts with other tests.
Will fix #9330
> fabtests/multinode: update arguments

- prov/coll/src/coll_av_set.c
An empty AV set can be created by setting start_addr and end_addr to FI_ADDR_NOTAVAIL. The for loop condition doesn't handle this condition and will cause a failure
Rework error paths a bit to return more helpful error messages.
Fixes #9738
> prov/coll: fix empty AV set initialization

- contrib/intel/jenkins/Jenkinsfile
Added calls to run_middleware with verbs;rxm and sockets in multinode performance stage.
> [intel/ci]: Added fi_multinode testing with verbs;rxm and sockets on CI

- prov/efa/src/rdm/efa_rdm_cq.c
Currently, we only repost rx pkts when there is
completion of IBV_WC_RECV and IBV_WC_RDMA_WRITE_IMM. This is wrong because the rx pkt can be resolved
after being held for local read, which is a send
or read completion. This patch fixes this issue
by just checking the efa_rx_pkts_to_post counter
in ep instead of checking the IBV op codes, which
is safe and stable.
> prov/efa: Fix the rx pkt post procedure.

- prov/efa/src/rdm/efa_rdm_atomic.c
This simplifies the initialization a bit.
This should also satisfy CID 412757.
> prov/efa: Initialize instances of `struct efa_rdm_atomic_ex`

- prov/efa/src/rdm/efa_rdm_atomic.c
- prov/efa/src/rdm/efa_rdm_msg.c
- prov/efa/src/rdm/efa_rdm_rma.c
This PR contains 3 commits that refactor the msg/read/atomic post. Make them all post via a function that involves ep and ope only.
> prov/efa: Refactor msg/read/atomic post

- prov/efa/src/efa_domain.c
- prov/efa/src/efa_domain.h
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/src/rdm/efa_rdm_ope.h
- prov/efa/src/rdm/efa_rdm_pke_cmd.c
This PR re-enabled https://github.com/ofiwg/libfabric/pull/10075 with bug fixes
> prov/efa: Rework domain queued lists merging and bug fixes

- fabtests/Makefile.am
- fabtests/Makefile.win
- fabtests/benchmarks/rdm_bw.c
- fabtests/fabtests.vcxproj
- fabtests/fabtests.vcxproj.filters
This is mostly a copy of fi_rdm_tagged_bw but test with untagged msg.
> fabtest: Add fi_rdm_bw test

- prov/efa/src/efa_av.c
- prov/efa/src/rdm/efa_rdm_cq.c
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/src/rdm/efa_rdm_ep_utils.c
- prov/efa/src/rdm/efa_rdm_msg.c
- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/src/rdm/efa_rdm_peer.h
- prov/efa/src/rdm/efa_rdm_pke.c
- prov/efa/src/rdm/efa_rdm_pke.h
- prov/efa/src/rdm/efa_rdm_pke_cmd.c
- prov/efa/src/rdm/efa_rdm_pke_cmd.h
- prov/efa/src/rdm/efa_rdm_pke_rtm.c
- prov/efa/src/rdm/efa_rdm_pke_utils.c
- prov/efa/src/rdm/efa_rdm_pkt_type.h
- prov/efa/test/efa_unit_test_cq.c
- prov/efa/test/efa_unit_test_ep.c
- prov/efa/test/efa_unit_test_mocks.c
- prov/efa/test/efa_unit_test_mocks.h
This PR contains a series of commits that supports the user recv QP extra feature in send and receive path
> prov/efa: Support the user recv QP extra feature in send and receive

- fabtests/Makefile.am
- fabtests/benchmarks/benchmark_shared.c
- fabtests/pytest/efa/test_rma_pingpong.py
- fabtests/pytest/shm/test_rma_pingpong.py
Backport https://github.com/ofiwg/libfabric/pull/10064 test_rma_pingpong bugfix
> [v1.21.x] Backport pr10064 

- Makefile.am
> Makefile.am: Add Windows build files to distribution tarball

- contrib/aws/Jenkinsfile
> contrib/aws: add c6gn test coverage

- fabtests/prov/efa/src/rdm_rnr_read_cq_error.c
- prov/efa/src/efa_errno.h
Updated to match with the latest error code in rdma-core
> prov/efa: Improve the EFA_IO_COMP error code and explanation

- AUTHORS
- Makefile.am
- NEWS.md
- configure.ac
- fabtests/configure.ac
- include/rdma/fabric.h
- include/windows/config.h
For CI only. Do not merge. Will be pushed directly.
> v1.22.0rc1

- AUTHORS
- Makefile.am
- NEWS.md
- configure.ac
- fabtests/configure.ac
- include/rdma/fabric.h
- include/windows/config.h
- src/var.c
> [v1.21.x] v1.21.1rc1

- prov/efa/Makefile.include
- prov/efa/configure.m4
- prov/efa/src/efa_domain.c
- prov/efa/src/efa_env.c
- prov/efa/src/efa_env.h
- prov/efa/src/efa_hmem.c
- prov/efa/src/efa_hmem.h
- prov/efa/src/efa_mr.c
- prov/efa/test/efa_unit_test_hmem.c
- prov/efa/test/efa_unit_test_mocks.c
- prov/efa/test/efa_unit_test_mocks.h
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
This reverts commit c8de604b86edcc9d88995471d984cce1c7fc125d.
> Revert "prov/efa: refactor hmem interface initialization"

- fabtests/common/shared.c
- fabtests/include/shared.h
- fabtests/pytest/efa/conftest.py
- fabtests/pytest/efa/test_rdm.py
- prov/efa/src/rdm/efa_rdm_cq.c
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/src/rdm/efa_rdm_ep_utils.c
- prov/efa/src/rdm/efa_rdm_msg.c
- prov/efa/src/rdm/efa_rdm_pke.c
Also added efa fabtests cases that uses this option
> fabtests: Add benchmark option for FI_OPT_MAX_MSG_SIZE

- prov/efa/Makefile.include
- prov/efa/configure.m4
- prov/efa/src/efa_domain.c
- prov/efa/src/efa_env.c
- prov/efa/src/efa_env.h
- prov/efa/src/efa_hmem.c
- prov/efa/src/efa_hmem.h
- prov/efa/src/efa_mr.c
- prov/efa/test/efa_unit_test_hmem.c
- prov/efa/test/efa_unit_test_mocks.c
- prov/efa/test/efa_unit_test_mocks.h
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
This reverts commit c8de604b86edcc9d88995471d984cce1c7fc125d.
(cherry picked from commit fb63b6cd0a1d79be4e1b6b39bf00c71709f6fa0e)
> [v1.22.x] Backport Revert "prov/efa: refactor hmem interface initialization"

- prov/verbs/src/verbs_ep.c
This fixes issue 10150.
On post send, when we are out of SQ credit, attempt to gain SQ credit by polling CQ for SQ.
Looks like a copy-paste mistake.
> prov/verbs: Flush CQ for SQ on no SQ credit

- prov/efa/src/rdm/efa_rdm_pke_utils.c
Backport https://github.com/ofiwg/libfabric/pull/10176
> [v1.22.x] prov/efa: do not do copy for inline send

- contrib/aws/Jenkinsfile
> contrib/aws: deprecate centos7 tests

- configure.ac
- fabtests/configure.ac
- include/windows/config.h
This only updates the version string.
> configure: Bump the version to 2.0.0a1

- man/fi_efa.7.md
- prov/efa/src/efa_base_ep.c
- prov/efa/src/efa_cq.h
- prov/efa/src/efa_env.c
- prov/efa/src/efa_env.h
- prov/efa/src/rdm/efa_rdm_cq.c
- prov/efa/src/rdm/efa_rdm_util.h
backport https://github.com/ofiwg/libfabric/pull/10217
> [v1.22.x] prov/efa: Allow disabling unsolicited write recv via env

- contrib/aws/Jenkinsfile
- fabtests/pytest/shm/test_unexpected_msg.py
> [v1.21.x] backport CI changes

- src/hmem_cuda.c
backport https://github.com/ofiwg/libfabric/pull/10220
> [v1.22.x] hmem/cuda: Modify the logging for nvml dlopen 

- prov/verbs/src/verbs_info.c
This commit addresses issue #9443 for verbs provider. Address format matching needs to happen for each info in the linked list which was not happening earlier. This check has been moved to the end of vrb_getinfo().
> prov/verbs: Fix issue while displaying addresses with fi_info -a <addr_format>

- prov/efa/src/efa_hmem.c
- prov/efa/src/efa_hmem.h
- prov/efa/src/rdm/efa_rdm_pke_utils.c
In accordance with various changes in #10096
> prov/efa: Update data types for various IOV operations

- prov/efa/Makefile.include
- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/test/efa_unit_test_mocks.c
- prov/efa/test/efa_unit_test_mocks.h
- prov/efa/test/efa_unit_test_ope.c
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
backport https://github.com/ofiwg/libfabric/pull/10299
> [v1.22.x] prov/efa: Fix a memory leak in local read

- AUTHORS
- Makefile.am
- NEWS.md
- configure.ac
- fabtests/configure.ac
- fabtests/prov/lpp/Makefile.include
- include/rdma/fabric.h
- include/windows/config.h
For CI only, do not merge. Will be pushed directly.
> v2.0.0 alpha

- prov/tcp/src/xnet_av.c
When multiplexing av inserts to sub avs, correctly track and check the subav fi_addrs
> prov/tcp: fix incorrect usage of av insert apis when multiplexing

- fabtests/prov/lpp/src/test_util.c
Update version and protocol in fi_getinfo attribs.
> fabtests/prov/lpp: update version and protocol in fi_getinfo

- fabtests/prov/lpp/src/rcq_data.c
Change invalid condition in parameter check in fi_tsenddata test.
> fabtests/prov/lpp: change invalid condition in fi_tsenddata

- fabtests/prov/efa/Makefile.include
- fabtests/prov/efa/src/efa_rdma_checker.c
- fabtests/pytest/efa/efa_common.py
- fabtests/pytest/efa/test_efa_protocol_selection.py
- prov/efa/src/efa_env.c
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
Backport https://github.com/ofiwg/libfabric/pull/10415 and https://github.com/ofiwg/libfabric/pull/10411
> [v1.22.x] prov/efa: backport changes

- fabtests/configure.ac
- fabtests/prov/efa/Makefile.include
- fabtests/prov/efa/configure.m4
Backport https://github.com/ofiwg/libfabric/pull/10420
> [v1.22.x] fabtests/configure, efa: call provider specific configure

- prov/efa/src/efa_errno.h
- prov/efa/src/efa_strerror.c
- prov/efa/src/rdm/efa_rdm_cq.c
- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/src/rdm/efa_rdm_util.c
- prov/efa/src/rdm/efa_rdm_util.h
Backport https://github.com/ofiwg/libfabric/pull/10369
> [v1.22.x] prov/efa: Improve the zero-copy recv error message

- contrib/aws/Jenkinsfile
Add g4dn nccl tests with tcp provider
> contrib/aws: Add g4dn nccl tests with tcp provider

- prov/efa/src/efa_mr.c
Application should use FI_MR_DMABUF API to pass the dmabuf fd and offset to make Libfabric register the mr via dmabuf. The only exception is for synapseai, beacuse dmabuf is the only way to register Gaudi device buffer and it was implemented before the FI_MR_DMABUF API. Keep this behavior unchanged for compatibility.
> prov/efa: Only do dmabuf reg when FI_MR_DMABUF is set

- contrib/intel/jenkins/Jenkinsfile
Add back PSM3 OneCCL-GPU testing
Separate mpichtestsuite into two stages for faster runtime
> contrib/intel/jenkins: Update testing for psm3 and mpichtestsuite

- contrib/aws/Jenkinsfile
Running a quick test to confirm that when things fail, they still fail the job, and then will rebase away the test commit
> contrib/aws: Add/Extend timeouts + cleanup Jenkins

- fabtests/scripts/runmultinode.sh
Improvements to runmultinode.sh script
> Multinode test script update

- AUTHORS
- NEWS.md
- configure.ac
- fabtests/configure.ac
- include/windows/config.h
- man/fi_provider.7.md
For CI test only, do not merge.
> v2.0.0 beta

- src/common.c
Backport https://github.com/ofiwg/libfabric/pull/10496
> [v1.22.x] src/common.c: Update ofi_vrb_speed

- contrib/aws/Jenkinsfile
- prov/efa/Makefile.include
- prov/efa/src/rdm/efa_rdm_cq.c
- prov/efa/test/efa_unit_test_cq.c
- prov/efa/test/efa_unit_test_mocks.c
- prov/efa/test/efa_unit_test_mocks.h
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
backport https://github.com/ofiwg/libfabric/pull/10530
> [v1.22.x] prov/efa: Fix the error handling for unsolicited recv

- man/fi_efa.7.md
- prov/efa/configure.m4
- prov/efa/src/efa_base_ep.c
- prov/efa/src/efa_base_ep.h
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
backport https://github.com/ofiwg/libfabric/pull/10417 and https://github.com/ofiwg/libfabric/pull/10520
> [v1.22.x] Use tclass to prioritize the messages from an ep

- prov/cxi/test/rma.c
Adding an option for CQ/cntr to tests that verify FI_RM_ENABLED in CXI Libfabric provider. Now the tests are:
- read_mr_overrun_cntr
- read_mr_overrun_cq
- write_mr_overrun_cntr
- write_mr_overrun_cq
NETCASSINI-3288
> prov/cxi: testing FI_RM_ENABLED

- contrib/cray/build.sh
- contrib/cray/run.cxi.jenkins
- contrib/cray/run.cxi.local
- contrib/cray/run.verbs.jenkins
- contrib/cray/run.verbs.local
Intended for use with Jenkins and manual build processes
> contrib/cray: Add local and jenkins build scripts

- contrib/intel/jenkins/Jenkinsfile
Make middlewares build in parallel
Consolodate old names into stages they should be part of
Add ompi testing
Update opt-out to not test changes that are all part of prov/cxi or prov/lpp in addition to existing requirements
Add weekly target for weekly tests to be able to run
> contrib/intel/jenkins: Migrate to new head node

- prov/psm2/src/psmx2_attr.c
This fix a compiler warning of unused return value.
> prov/psm2: Check return value of asprintf

- prov/psm2/src/psmx2_attr.c
This fix a compiler warning of unused return value.
(cherry picked from commit cafbae7a68ca73367621146901d784b54a0f0ae2)
> [v2.0.x] prov/psm2: Check return value of asprintf

- prov/efa/Makefile.include
- prov/efa/test/efa_unit_test_common.c
- prov/efa/test/efa_unit_test_mocks.c
- prov/efa/test/efa_unit_test_mocks.h
- prov/efa/test/efa_unit_test_rma.c
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
> prov/efa: Add unit tests for efa_rma

- contrib/intel/jenkins/Jenkinsfile
Lookup a all teams and users in the ofiwg github team.
If the submitter is not in the list of users then deny them
> contrib/intel/jenkins: Do not run pipeline for unauthorized users

- contrib/intel/jenkins/Jenkinsfile
Lookup a all teams and users in the ofiwg github team. If the submitter is not in the list of users then deny them
> [v2.0.x] contrib/intel/jenkins: Pick #10650 Do not run pipeline for unauthorized users

- contrib/intel/jenkins/Jenkinsfile
Lookup a all teams and users in the ofiwg github team. If the submitter is not in the list of users then deny them
> [v1.21.x] contrib/intel/jenkins: Pick #10650 Do not run pipeline for unauthorized users

- contrib/intel/jenkins/Jenkinsfile
Lookup a all teams and users in the ofiwg github team. If the submitter is not in the list of users then deny them
> [v1.22.x] contrib/intel/jenkins: Pick #10650 Do not run pipeline for unauthorized users

- fabtests/pytest/common.py
This commit fixes the following bugs in neuron fabtests
1. The neuron accelerator detection is broken on some OSs because the full path of the executable `neuron-ls` was not used
2. Before this commit, each pytest worker was assigned a single  neuron core. This works on multi node tests but fails on single node tests because a neuron core can only be opened by a single process. This commit assigns two different neuron cores to each pytest worker for client-server tests: one for the server and one for the client. Trn1 has 2 cores per neuron device and Trn2 has 8 cores per neuron device, so
this assignment works for both.
3. When running in serial mode, the env var PYTEST_XDIST_WORKER is not set, so the NEURON_RT_VISIBLE_CORES env var is also not set. This causes the server to occupy all …
> fabtests: Bugfixes for neuron

- fabtests/pytest/common.py
This commit fixes the following bugs in neuron fabtests
1. The neuron accelerator detection is broken on some OSs because the full path of the executable `neuron-ls` was not used
2. Before this commit, each pytest worker was assigned a single  neuron core. This works on multi node tests but fails on single node tests because a neuron core can only be opened by a single process. This commit assigns two different neuron cores to each pytest worker for client-server tests: one for the server and one for the client. Trn1 has 2 cores per neuron device and Trn2 has 8 cores per neuron device, so
this assignment works for both.
3. When running in serial mode, the env var PYTEST_XDIST_WORKER is not set, so the NEURON_RT_VISIBLE_CORES env var is also not set. This causes the server to occupy all …
> [v1.22.x] fabtests: Bugfixes for neuron

- prov/efa/test/efa_unit_test_cq.c
Add missing mock for wc_is_unsolicited in unit test
> prov/efa: Add missing mock for wc_is_unsolicited in unit test

- prov/opx/include/rdma/opx/opx_hfi1_pre_cn5000.h
Fix: https://github.com/ofiwg/libfabric/issues/10661
> prov/opx: use `page_sizes[OFI_PAGE_SIZE]-1` instead of `PAGE_MASK`

- prov/efa/src/efa_cq.c
- prov/efa/src/efa_msg.c
- prov/efa/src/efa_rma.c
Add debug log for send/recv/write/read and cq poll
> prov/efa: Add debug log for efa-direct data transfer

- contrib/intel/jenkins/Jenkinsfile
Update the oneccl CPU and separate it to use different partitions.
> Intel/CI: Update oneccl CPU stage 

- util/pingpong.c
(cherry picked from commit 67932605d4a58cea495b50504d57eaa73543256e)
> [v1.22.x] util: Add fabric argument to pingpong test

- util/pingpong.c
(cherry picked from commit 67932605d4a58cea495b50504d57eaa73543256e)
> [v2.0.x] util: Add fabric argument to pingpong test

- contrib/intel/jenkins/Jenkinsfile
Set failfast to true
Polish jenkinsfile:
Remove legacy related things that are not in use anymore
Reorganize top level functions to make replaying easier
Remove unused variables
> contrib/intel/jenkins: Cleanup Jenkinsfile

- contrib/intel/jenkins/Jenkinsfile
- fabtests/test_configs/tcp/io_uring.exclude
Update the oneccl CPU and separate it to use different partitions.
> [v2.0.x] Intel/CI: Cherrypick CI updates 

- prov/cxi/src/cxip_coll.c
- prov/cxi/test/coll.c
Added or/and/xor logical support
> prov/cxi: Added collectives logical operators

- contrib/aws/Jenkinsfile
efa-direct fabtests need  some extra time
> contrib/aws: Increase timeout

- prov/efa/src/rdm/efa_rdm_ope.c
efa_rdm_txe_construct is called to construct a txe for the handshake packet and to construct txes for send, RMA and atomic operations.
iov_count is 0 only in the handshake path. When efa_rdm_txe_construct is called as part of an fi_send or fi_read or fi_write call from the application, iov_count is never 0.
The handshake packet is posted internally by the EFA provider, so it does not make sense to allocate and consume prefix space. Instead just check for iov_count before consuming the prefix space.
(cherry picked from commit 5ba76ab2b49c2cbfa6710e68f2478017e284e837)
> [v1.22.x] prov/efa: Bug fix in the RDM path with FI_MSG_PREFIX mode

- contrib/intel/jenkins/Jenkinsfile
Run AllReduce, Gather, Reduce, Allgather tests with water providers and fail PRs if regressions > 10%.
TODO: Simplify these stages into one stage that runs all providers that have files changed in the changes
> contrib/intel/jenkins: Add performance regression testing

- .github/workflows/coverity.yml
- .github/workflows/pr-ci.yml
- contrib/intel/jenkins/Jenkinsfile
Add regression testing stage
Update rdma-core version to 35.0 from 34.1
> [v2.0.x] contrib/intel/jenkins, .github/workflows: Pick CI updates

- .github/workflows/coverity.yml
- .github/workflows/pr-ci.yml
- contrib/intel/jenkins/Jenkinsfile
Add regression testing stage
Update rdma-core version to 35.0 from 34.1
> [v2.1.x] contrib/intel/jenkins, .github/workflows: Pick CI updates

- prov/efa/src/efa_msg.c
- prov/efa/src/efa_rma.c
Fail the operation if no valid desc is provided because EFA direct requires FI_MR_LOCAL.
> prov/efa: Enforce FI_MR_LOCAL in efa-direct

- prov/efa/src/efa_msg.c
- prov/efa/src/efa_rma.c
Fail the operation if no valid desc is provided because EFA direct requires FI_MR_LOCAL.
Signed-off-by: Jessie Yang <jiaxiyan@amazon.com>
(cherry picked from commit d0233f7262514a2bac5e95059cff5a59ae75f07f)
> [v2.1.x]prov/efa: Enforce FI_MR_LOCAL in efa-direct

- prov/rxm/src/rxm_conn.c
- prov/rxm/src/rxm_ep.c
When the application requests auto data progress, rxm needs to start a thread to drive data progress. This is required not only for atomic protocols but also for the rendezvous protocol. The existing code was only enabling the automatic progress thread when the application requested atomics.
This starts the correct thread function whenever auto progress is requested, not just for atomics, allowing the rendezvous protocol to pass in auto progress mode.
This also simplifies the checks to remove references to atomics capabilities.
We can still keep the optimized progress function but the check is updated to check whether we need auto control progress only and not whether or not the app requested atomic support.
Fixes issue #10945
> prov/rxm: fix auto progress

- fabtests/common/hmem_cuda.c
- src/hmem_cuda.c
The CU_MEM_RANGE_FLAG_DMA_BUF_MAPPING_TYPE_PCIE symbol requires newer CUDA driver support. While the symbol may exist during compile time in cuda.h, drivers with lower CUDA versions cannot support it. Fallback to no flags to ensure backward compatibility.
> hmem_cuda: Add runtime fallback for unsupported dmabuf flag

- prov/efa/src/rdm/efa_rdm_pke_utils.c
This commit functionally reverts the change in
https://github.com/ofiwg/libfabric/commit/8a4249790e07250a9e4a2d66c10560ce588ded38
The EFA provider in rdma-core should be able to handle inline sends without a copy to Libfabric buffer but certain workloads are failing with a truncation error when the copy is avoided
Revert the change until we can find a longer term fix
> prov/efa: do copy for inline send

- prov/efa/src/rdm/efa_rdm_pke_utils.c
This commit functionally reverts the change in
https://github.com/ofiwg/libfabric/commit/8a4249790e07250a9e4a2d66c10560ce588ded38
The EFA provider in rdma-core should be able to handle inline sends without a copy to Libfabric buffer but certain workloads are failing with a truncation error when the copy is avoided
Revert the change until we can find a longer term fix
(cherry picked from commit 807bdd6d59f6725c81839ee87f94a13dc1af238a)
> [v2.1.x]prov/efa: do copy for inline send

- fabtests/functional/resmgmt_test.c
(cherry picked from commit 5dd902300d2c5cdf27f436ffe430d4217c093f5c)
> [v2.1.x] fabtests: Add MR mode and descriptor to resource mgmt test

- prov/cxi/configure.m4
- prov/cxi/include/cxip.h
- prov/cxi/src/cxip_coll.c
- prov/cxi/src/cxip_curl.c
- prov/cxi/test/curl.c
This opt was needed for static and dynamic binding of these symbols.
> prov/cxi: New conf opt for binding of json symbols

- prov/efa/src/efa_av.c
- prov/efa/src/efa_av.h
- prov/efa/src/efa_base_ep.c
- prov/efa/src/efa_base_ep.h
- prov/efa/src/efa_device.c
- prov/efa/src/efa_device.h
- prov/efa/src/efa_domain.c
- prov/efa/src/efa_domain.h
- prov/efa/src/efa_fork_support.c
- prov/efa/src/efa_hmem.c
- prov/efa/src/rdm/efa_rdm_pke.c
- prov/efa/test/efa_unit_test_av.c
- prov/efa/test/efa_unit_test_cq.c
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
Backport https://github.com/ofiwg/libfabric/pull/11013
> [v2.1.x] prov/efa: Create 1:1 relationship between domain and PD, move address handle to domain level

- man/fi_efa.7.md
Introduce the efa-direct fabric in RDM endpoint and explained its difference from the efa fabric.
Updated various out-dated information.
> prov/efa: Update man page

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/Jenkinsfile_daos.nightly
Cherrypick CI updates from main
> [v2.1.x] contrib/intel/jenkins: Pick migrate daos to nightly, migrate to using RED CI runner

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/Jenkinsfile_daos.nightly
> [v2.0.x] contrib/intel/jenkins: Pick migrate daos to nightly, migrate to using RED CI runner

- prov/verbs/src/verbs_domain.c
The recent commit d15a7701d ("prov/verbs: Make a copy of the provider info in the fabric object) introduced a regression: the pointer returned by vrb_get_verbs_info() is never freed.
Rather than adding a missing call to fi_freeinfo(), I believe it's cleaner to move the domain attribute check directly into the function itself, while holding the lock.
For such a simple check, duplicating the fi_info structure is unnecessary.
Note: Leak found by ASAN.
> prov/verbs: Fix memory leak of fi_info structure in vrb_domain()

- fabtests/pytest/efa/efa_common.py
The goal of has_rdma is to skip tests on platforms that cannot use RDMA, which requires both sides have consistent capabilities. In that regard has_rdma
should check both server and client capabilities.
> fabtests/efa: Check rdma capability for both sides

- man/fi_shm.7.md
The shm man page hasn't been updated in a while and is quite out of date. Update to reflect the current status of the provider. Fix typos, grammar, and formatting while I'm here.
Fixes #11062
> man/fi_shm: update shm man page to be accurate and fix typos/formatting

- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/src/rdm/efa_rdm_ope.h
- prov/efa/src/rdm/efa_rdm_peer.c
- prov/efa/src/rdm/efa_rdm_pke.c
- prov/efa/test/efa_unit_test_ope.c
- prov/efa/test/efa_unit_test_pke.c
- prov/efa/test/efa_unit_test_rdm_peer.c
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
Backport https://github.com/ofiwg/libfabric/pull/11061
> [v2.1.x] prov/efa: Track cloned rx pkts

- fabtests/pytest/efa/efa_common.py
backport https://github.com/ofiwg/libfabric/pull/11049
> [v2.1.x] fabtests/efa: Check rdma capability for both sides

- prov/efa/src/efa_base_ep.c
backport https://github.com/ofiwg/libfabric/pull/11076
> [v2.1.x] prov/efa: Update qp table after qp destroy

- NEWS.md
This contains all the changes since v2.1.0. More changes may be added when the v2.2.0rc1 release is cut.
> NEWS.md: Update for v2.2.0rc1

- man/fi_efa.7.md
- prov/efa/Makefile.include
- prov/efa/configure.m4
- prov/efa/src/efa_base_ep.c
- prov/efa/src/efa_cq.c
- prov/efa/src/efa_cq.h
- prov/efa/src/efa_device.c
- prov/efa/src/efa_device.h
- prov/efa/src/efa_domain.c
- prov/efa/src/fi_ext_efa.h
- prov/efa/src/rdm/efa_rdm_cq.c
- prov/efa/test/efa_unit_test_domain.c
- prov/efa/test/efa_unit_test_mocks.c
- prov/efa/test/efa_unit_test_mocks.h
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
Backport https://github.com/ofiwg/libfabric/pull/11045 and https://github.com/ofiwg/libfabric/pull/11119
> [v2.2.x]prov/efa: Extend domain ops for GDA

- prov/efa/src/efa_device.c
Add log to print key variables and errors during device initialization to help debugging.
(cherry picked from commit f095d020387b7bfa5c5a456fd0b67611211780a5)
> [v2.1.x]prov/efa: Add detailed logging of device enumeration and selection

- man/fi_efa.7.md
- prov/efa/src/efa_domain.c
- prov/efa/src/fi_ext_efa.h
- prov/efa/test/efa_unit_test_domain.c
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
Backport https://github.com/ofiwg/libfabric/pull/11202 and https://github.com/ofiwg/libfabric/pull/11208
> [v2.2.x]prov/efa: Avoid flushing cq during ep close for external cq 

- fabtests/pytest/efa/test_rma_bw.py
Debug build takes longer to finish.
> fabtests/efa: Increase the timeout for test_rma_bw_range

- fabtests/multinode/src/core.c
This test wasn't correctly retrying the recvmsg and sendmsg calls when they would fail with -EAGAIN.
Note: This fixes a race condition failure in multinode verbs rma due to insufficient ibv credits and the client exiting too early.
> fabtests/multinode/src: Fix multi_barrier EAGAIN path

- man/cxi_collectives.7.md
- man/fi_cxi.7.md
- prov/cxi/Makefile.include
Adjust verbiage about fi_join_collective to match reality.
Add intro man page for hardware-accelerated collectives.
> man, prov/cxi: update fi_cxi, add cxi_collectives man pages

- fabtests/prov/efa/Makefile.include
- fabtests/prov/efa/configure.m4
- fabtests/prov/efa/src/efa_exhaust_mr_reg_common.c
- fabtests/prov/efa/src/efa_exhaust_mr_reg_common.h
- fabtests/prov/efa/src/efa_rdma_checker.c
- fabtests/pytest/efa/test_rdm.py
- prov/efa/test/efa_unit_test_cq.c
Backport https://github.com/ofiwg/libfabric/pull/11235
> [v2.2.x]fabtests/efa: Fix EFA device query 

- fabtests/prov/efa/Makefile.include
- fabtests/prov/efa/configure.m4
- fabtests/prov/efa/src/efa_exhaust_mr_reg_common.c
- fabtests/prov/efa/src/efa_exhaust_mr_reg_common.h
- fabtests/prov/efa/src/efa_rdma_checker.c
- fabtests/pytest/efa/test_rdm.py
- prov/efa/test/efa_unit_test_cq.c
Backport https://github.com/ofiwg/libfabric/pull/11235
> [v2.1.x]fabtests/efa: Fix EFA device query 

- contrib/intel/jenkins/Jenkinsfile
Also make release check require both makefile.am and configure.ac changes.
> contrib/intel/jenkins: Do not run authentication on opt-out path

- prov/psm3/src/psmx3.h
- prov/psm3/src/psmx3_av.c
- prov/psm3/src/psmx3_init.c
proposal: fi_av_insertsvc() implementation for psm3
Maybe ns lookup code in psmx3_getinfo() must be replaced with new psmx3_lookup()
> prov/psm3: fi_av_insertsvc() via ns resolve

- fabtests/prov/efa/src/multi_ep_mt.c
- fabtests/pytest/efa/test_multi_ep.py
Reworked on https://github.com/ofiwg/libfabric/pull/11281
> fabtests/efa: Allow shared AV in multi_ep_mt test

- prov/cxi/src/cxip_nic.c
service list not freed in successful case
> prov/cxi: fix memory leak

- fabtests/benchmarks/benchmark_shared.c
- fabtests/common/shared.c
- prov/efa/src/efa_cq.c
- prov/efa/src/efa_tp_def.h
reworked https://github.com/ofiwg/libfabric/pull/11325
> prov/efa and fabtests: add completion traces and fixes ep finalize semantics

- fabtests/benchmarks/benchmark_shared.c
- fabtests/common/shared.c
- prov/efa/src/efa_cq.c
- prov/efa/src/efa_tp_def.h
backport https://github.com/ofiwg/libfabric/pull/11342
> [v2.2.x] prov/efa and fabtests: add completion traces and fixes ep finalize semantics

- prov/cxi/include/cxip.h
- prov/cxi/src/cxip_coll.c
- prov/cxi/src/cxip_ctrl.c
- prov/cxi/src/cxip_zbcoll.c
add proper handling of concurrent mcast addresses in collective rdma get setup/use and cleanup flow.
> prov/cxi: fix bug related concurrent mcast's

- prov/efa/configure.m4
- prov/efa/src/efa_data_path_direct.c
Make the name up to date with rdma core.
> prov/efa: Rename efadv_cq_attr db to doorbell

- prov/cxi/test/auth_key.c
Test the cxip_cmdq_cp_modify path.
> prov/cxi: increase vni range in auth_key tests

- prov/cxi/include/cxip.h
- prov/cxi/src/cxip_coll.c
Reduce the amount of times we alloc/free root rdma buffers and take wait penalty only once
> prov/cxi: fix performance issue with close_mc()

- prov/efa/src/efa_cq.c
efa_cq_construct_cq_entry can be replaced by the read_entries op to avoid duplicated code.
> prov/efa: remove duplicated efa_cq_construct_cq_entry
