ofiwg/libfabric

- prov/efa/src/efa_fabric.c
The fork handler install was moved in commit ff72bf48a9 when fixing a
bug where the rdma-core hugepage environment variable was set too late.
However, this causes the fork handler to be installed if an EFA device
is not present or if EFA is not used. We only risk corruption with fork
when it is called after the bounce buffers are allocated, registered,
and pinned, so delay installing this handler to validate that fork can
be called safely until then.
> [v1.11.x] prov/efa: move efa_atfork_callback install to fabric init

- prov/shm/src/smr_progress.c
Reverts commit cd459ced7e50e7bd942e2838ec2366558018218c.
The bug seems to be somewhere in the L0 caching,
not the protocol.
> prov/shm: revert add SAR buffer locking

- prov/util/src/util_shm.c
Adding the O_EXCL flag forces the shm_open call to fail
if the shared memory region already exists. This prevents
a segfault/miscommunication which can occur when two peers
try to open an endpoint/shared memory region with the same name.
Cherry picked from commit c403cc4f
> [v1.11.x] util/shm: add O_EXCL flag to shm_open

- prov/verbs/src/fi_verbs.h
- prov/verbs/src/verbs_domain_xrc.c
This code was deprecated with the SIDR connection setup
implementation for shared XRC connections and should have
been removed. No rush.
> prov/verbs: Remove XRC QP temporary reservation dead code

- prov/util/src/util_shm.c
Adding the O_EXCL flag forces the shm_open call to fail
if the shared memory region already exists. This prevents
a segfault/miscommunication which can occur when two peers
try to open an endpoint/shared memory region with the same name.
> util/shm: add O_EXCL flag to shm_open

- src/common.c
ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fff4c61e7e0 at pc 0x14f2cb7ae0b9 bp 0x7fff4c61e650 sp 0x7fff4c61ddd8
WRITE of size 17 at 0x7fff4c61e7e0 thread T0
#0 0x14f2cb7ae0b8  (/lib64/libasan.so.5+0xb40b8)
#1 0x14f2cb7aedd2 in vsscanf (/lib64/libasan.so.5+0xb4dd2)
#2 0x14f2cb7aeede in __interceptor_sscanf (/lib64/libasan.so.5+0xb4ede)
#3 0x14f2cb230766 in ofi_addr_format src/common.c:401
#4 0x14f2cb233238 in ofi_str_toaddr src/common.c:780
#5 0x14f2cb314332 in vrb_handle_ib_ud_addr prov/verbs/src/verbs_info.c:1670
#6 0x14f2cb314332 in vrb_get_match_infos prov/verbs/src/verbs_info.c:1787
#7 0x14f2cb314332 in vrb_getinfo prov/verbs/src/verbs_info.c:1841
#8 0x14f2cb21fc28 in fi_getinfo_ src/fabric.c:1010
#9 0x14f2cb25fcc0 in ofi_get_core_info prov/util/src/util_attr.c:298 …
> src/common.c: fix a stack-buffer-overflow issue

- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_atomic.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_init.c
- prov/efa/src/rxr/rxr_pkt_type_misc.c
- prov/efa/src/rxr/rxr_pkt_type_req.c
- prov/efa/src/rxr/rxr_rma.c
This PR fix three bugs in emulated read and atomic protocol:
1. memory leaks in the emulated read protocol.
2. a bug in rxr_atomic_generic_efa()
3. atomic response data need to have its own buffer pool.
> prov/efa: fix up emulated read and atomic

- prov/efa/src/efa_ep.c
We are seeing crashes and hangs when the Libfabric provider handles RNR
retries. Change this to have the device retry indefinitely while we
debug.
> prov/efa: change rnr_retry to retry indefinite device retries

- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_msg.c
- prov/efa/src/rxr/rxr_pkt_type_misc.c
- prov/efa/src/rxr/rxr_rma.c
This PR contains 2 refactors:
1. simplify the error handling code path in rxr_ep_init.
2. merge rxr_tx_entry_mr_dereg() into rxr_release_tx_entry
> prov/efa: two refactors

- include/ofi.h
The function ofi_get_page_bytes() is expected to return a value
which is multiple of page_size, but it is not doing that currently.
This is because a recent change to function ofi_get_page_end(),
which is used by ofi_get_page_bytes().
Ths patch address the issue by not using ofi_get_page_end() to
calcuated the ending address.
> includ/ofi.h : fix a bug in ofi_get_page_bytes()

- prov/efa/src/efa_domain.c
Currently, EFA uses memhooks monitor for MR cache.
The Open MPI btl/ofi component uses the same memhook
monitor for its own MR cache, and only one set of
memhooks can be registered for the memory operations.
In this case, btl/ofi's memhooks were overwritten
by libfabric's memhooks, causing data corruption.
Note, EFA used to use userfaultd monitor but switched
to memhooks monitor in commit 7fcf46c to address
the dereg-after-free issue, which is that userfaulted
requires MR cache to defer memory de-registration to
after memory was freed. However, the fork support in
rdma-core assumes memory regions are deregistered before
they are freed, and fork support + dereg-after-free
would cause data corruption.
We implemented the dereg-before-free behavior and switched
to use memhooks monitor. but …
> prov/efa: switch to userfaultd monitor for MR cache

- fabtests/common/hmem_ze.c
- include/ofi_hmem.h
- include/ofi_shm.h
- prov/shm/src/smr.h
- prov/shm/src/smr_ep.c
- prov/shm/src/smr_init.c
- prov/shm/src/smr_msg.c
- prov/shm/src/smr_progress.c
- prov/shm/src/smr_rma.c
- prov/shm/src/smr_signal.h
- prov/util/src/util_shm.c
- src/hmem.c
- src/hmem_ze.c
First draft of various fixes/additions for shm L0 IPC support.
Fabtests:
- Change Shared allocation to Device allocation for L0 interface
HMEM:
- Add get base address function for interfaces that require base address in IPC use
L0:
- Add p2p check for L0
- Add shareable handle get and open functions
shm:
- Disable CMA when HMEM interfaces are enabled
- Add shm unix socket name to shm region
- Add unix domain socket when L0 interfaces are enabled for device fd exchange
- Add L0 IPC protocol
> prov/shm, src/hmem_ze: add IPC support for ZE

- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_pkt_cmd.c
Return EAGAIN instead of ENOMEM when unable to allocate a TX packet
in the segmented send path.
The tx_pending counter check used to ensure that rxr_pkt_post_data was only
called when a TX packet is available, however packets may be queued
during RNR/peer backoff and are not pending on the NIC.
> prov/efa: return EAGAIN when pkts are exhausted sending segments

- prov/tcp/src/tcpx.h
- prov/tcp/src/tcpx_cq.c
- prov/tcp/src/tcpx_ep.c
- prov/tcp/src/tcpx_progress.c
- prov/tcp/src/tcpx_rma.c
- prov/tcp/src/tcpx_shared_ctx.c
This is derived from PR #6454.  The main difference is that I removed the flush_pending_xfers function as part of the change, as it is no longer needed.  Other differences are merely function renames, so I can more easily figure out what the various calls are doing without always needing to read the implementation.
> prov/tcp: Flush outstanding operations when disabling the EP

- prov/rxm/src/rxm_cq.c
rxm_handle_comp() is expected to return a value of 0 upon success when
called by rxm_ep_do_progress(). Recent changes to support HMEM caused
an incorrect value to be returned, resulting in a local protection error
occurring during SHMEM AMO operations. This patch supplies a correction
to the erroneous RC.
> prov/rxm: RC correction

- prov/efa/src/efa_mr.c
This reverts commit 26160438360bee3aeec6a8b37a255491f36d82a7.
We are seeing some negative impact of this patch.
> prov/efa: Revert "adjust frequency of flush"

- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_read.c
- prov/efa/src/rxr/rxr_read.h
This PR contains 4 commits that correctly handle the case when lower provider returned an error cq entry and the pkt_entry->x_entry is of type rxr_read_entry.
> prov/efa: handle cq error with read entry

- prov/verbs/src/verbs_ep.c
This PR is a cherry pick of a previously merged fix which was partially overwritten.
> prov/verbs: reapply fix for off-by-one credit initialization

- prov/efa/src/efa_av.c
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_atomic.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_msg.c
- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_entry.c
- prov/efa/src/rxr/rxr_pkt_type_req.c
- prov/efa/src/rxr/rxr_read.c
- prov/efa/src/rxr/rxr_rma.c
A handful of fixes to the queuing logic. This fixes a hang when using the medium message protocol when RNR backoff is handled by the host stack. The one sided/atomic queuing is still suspect and will likely need some testing and changes.
> prov/efa: RNR queuing fixes and cleanup

- include/unix/osd.h
- include/windows/osd.h
- prov/tcp/src/tcpx_conn_mgr.c
- prov/tcp/src/tcpx_ep.c
- src/unix/osd.c
As described in the issue #6493, there is a situation where the call
to accept() would block is the peer aborts the connection in the
middle of the connection handshake.
Here is how Sean describes the problem:
"If a connection request is received, the listening socket would
be marked with POLLIN. If that connection is aborted by the peer
before the thread that checks POLLIN can call accept, it would
find nothing to accept."
Passive EndPoint (PEP) socket now becomes non-blocking so the call
to accept() never blocks.
> prov/tcp: PEP socket is non-blocking

- man/fi_endpoint.3.md
The man pages indicate that the tx:size and rx:size fields
are the minimal number of operations that may be posted to
an EP before send/recv will return EAGAIN.  This is not
true, as internal messages may consume some entries, and
EAGAIN can be returned on the first operation while
communication is being setup.
Change the wording, so that it captures the actual behavior
of what the providers are actually doing.
> man: Correct definition of Tx/Rx size to match behavior

- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_pkt_type_misc.c
Remove the check added in #6500 as it is causing failures. all_get_all passes with this change.
> prov/efa: remove state check and unused state

- prov/rxm/src/rxm_attr.c
- prov/rxm/src/rxm_ep.c
- prov/rxm/src/rxm_init.c
This change removes the upper limit on buffer pool sizes to allow
growth beyond the tx/rx size.  The initial size remains fairly low but
the pools may now expand as necessary, enabling better scalability
The default tx/rx sizes are also bumped up to more sensible
values for RxM
Signed-off-by: Stephen Oost <stephen.oost@intel.com>
> prov/rxm: adjust rx/tx and buffer pool sizes

- prov/rxm/src/rxm_init.c
This fixes a small memory leak when building rxm as a
DL provider.
> [v1.11.x] prov/rxm: Call ofi_mem_fini when built as DL provider

- prov/rxm/src/rxm_init.c
This fixes a small memory leak when building rxm as a
DL provider.
> prov/rxm: Call ofi_mem_fini when built as DL provider

- prov/efa/src/rxr/rxr_pkt_type_misc.c
We need to wait until we get a send completion instead of a successful
send for these packet types, as they could be returned as an RNR error.
This was causing corruption by freeing the entry too early.
> prov/efa: fix receipt/end of read packet handling

- prov/efa/src/rxr/rxr_init.c
Fix two issues with the getinfo path which causes FI_AV_UNSPEC to be set when no hints are specified, and RNR errors to be written to the app when the app does not set the resource management bit.
> prov/efa: getinfo fixes for AV and resource mgmt

- configure.ac
There is a bug in the existing logic which only fails configure if the
default search path is used (--with-cuda) and the CUDA runtime in not
found. The package check silently fails and proceeds with configuration
if a custom path is provided yet no CUDA runtime is found
(--with-cuda=/foo/bar) due to the erroneous AS_IF condition. This was
silently disabling FI_HMEM_CUDA support despite the explicit
configuration.
> configure: Hard fail when CUDA package detection fails

- configure.ac
There is a bug in the existing logic which only fails configure if the
default search path is used (--with-cuda) and the CUDA runtime in not
found. The package check silently fails and proceeds with configuration
if a custom path is provided yet no CUDA runtime is found
(--with-cuda=/foo/bar) due to the erroneous AS_IF condition. This was
silently disabling FI_HMEM_CUDA support despite the explicit
configuration.
(cherry picked from commit dea40f220f18dbdd7c6cae6d3c6f89dd500355bd)
> [v1.11.x] configure: Hard fail when CUDA package detection fails

- prov/util/src/util_shm.c
If shm_open returns an error because the file already exists, check
to see if the process is not running anymore and proceed with rewriting
if the process is dead.
This still prevents two processes from using the same shm name while
also allowing for using the same name if the last process was killed with
SIGKILL and did not get cleaned up by the signal handler.
> prov/shm: retry shm_open without O_EXCL if process is dead

- fabtests/include/hmem.h
Windows build has a minor quibble with mismatched function
declarations.  Add (void) to the function declaration.
> fabtests: Fix function declaration to remove build warning

- man/fi_rxm.7.md
- prov/rxm/src/rxm_domain.c
- prov/rxm/src/rxm_ep.c
- prov/rxm/src/rxm_init.c
- prov/tcp/src/tcpx.h
- prov/tcp/src/tcpx_conn_mgr.c
- prov/tcp/src/tcpx_ep.c
Simplify progressing the deferred queue.
Use a single send call to transfer CM messages.
Rename the CM states.
CM changes are part of a broader attempt to remove blocking send/recv calls during CM message exchange to nonblocking.
Additional updates, plus patch to make sockets nonblocking always.  This avoids potentially long delays blocking progress while waiting for a socket to become ready for sending/receiving data in order to exchange CM messages.
> prov/tcp: Use nonblocking sockets during CM message exchange

- prov/psm2/src/psmx2.h
- prov/psm2/src/psmx2_domain.c
- prov/psm2/src/psmx2_fabric.c
- prov/psm2/src/psmx2_trx_ctxt.c
The calls for creating shared contexts accept fi_tx_attr, which unlike
fi_ep_attr, doesn't have the auth_key. As the result, the default uuid
is used as the job key. Previously the default uuid was stored in the
fabric object. The problem was that the auth_key was also unavailable
when the fabric object is created. Therefore, the default uuid can only
be set via environment variables. This creates discrepancies between
shared contexts and endpoints w.r.t. job key setting. Moving the default
uuid to the domain object solves the issue.
> prov/psm2: Move default uuid from fabric to domain

- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_domain.c
- prov/rxm/src/rxm_ep.c
- prov/rxm/src/rxm_init.c
- prov/tcp/src/tcpx_conn_mgr.c
- prov/util/src/util_cq.c
Plus 2 patches to address coverity warnings
> prov/rxm: Add env var to re-enable direct send feature

- prov/efa/docs/overview.md
Add an overview page with useful EFA information and a short blurb on
prereqs/building and installing Libfabric for use on Amazon EC2.
More to come later.
> prov/efa: Start on EFA developer documentation

- fabtests/functional/msg_sockets.c
- fabtests/ubertest/config.c
- prov/rxm/src/rxm_cq.c
Handle build warnings (hopefully, my compiler doesn't produce them) around string functions in fabtests.
Rework the error handling in rxm atomic response handling to handle build warning around an unused variable (used in debug build).
> fabtests & rxm: Address build warnings

- prov/util/src/util_av.c
Huge pages allocation requires user to reserve some
memory, which cannot be used by normal allocation.
Therefore, we want to reserve as little huge pages as
possible, and use it only for performance critical pools.
This patch removed the HUGEPAGES flags for av_entry_pool
because it does not fall into that category.
> util/util_av : do not use huge pages for av_entry_pool

- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_cq.c
- prov/rxm/src/rxm_ep.c
In rxm_handle_comp(), if we receive an error back from any of the subroutines, we will write an error entry to the CQ.  However, in some cases that is incorrect and can result in writing extra completions to the CQ.  Part of the issue is that the code paths are extremely deep.  This analysis came out of examining a couple of coverity issues.
This is the first set of changes to try to fix this up.  Any errors writing to the CQ should be treated as fatal to the CQ and all EPs bound to that CQ.  Returning error codes back does not help.  In most cases, it results in trying to write yet another entry to the CQ, though this time in error.  In any case, the completion needed by the application has been lost.
We trap CQ write errors, print a warning, and assert.  Future patches can add more …
> prov/rxm: first set of changes to fix up completion error handling

- prov/efa/src/rxr/rxr_rma.c
- When "ENABLE_DEBUG" is defined, the "rx_entry->rx_pending_entry" is inserted into "ep->rx_pending_list" each time rxr_rma_post_efa_emulated_read is called. When there is an error from rxr_pkt_post_crtl, the rx_entry is released by rxr_release_rx_entry, but its rx_pending_entry is not removed from ep->rx_pending_list. This makes the ep->rx_pending_list has a released entry that will be used by later dlist_insert_tail calls, which could cause segmentation fault when memory poisoning is enabled.
- This patch fixes this issue by removing the rx_pending_entry from ep->rx_pending_list before its rx_entry is released.
> prov/efa: Fix a bug in rxr_rma_post_efa_emulated_read

- prov/efa/src/rxr/rxr_pkt_type_req.c
- In rxr_pkt_handle_long_rtw_recv(), rtw_hdr is cast from pkt_entry->pkt. Then rxr_pkt_copy_to_rx is called to copy data from packet entry to target buffer, which could release the packet entry after data copied via rxr_pkt_entry_release_rx().  It then used tx_id stored in the released packet entry to send CTS, which could cause a segmentation fault when memory poisoning is enabled.
- This patch fixes this issue by using an intermediate variable "tx_id" to store the value of "rtw_hdr->tx_id" before the packet entry is released, and assign it to rx_entry->tx_id.
> prov/efa: Fix a bug in rxr_pkt_handle_long_rtw_recv

- prov/efa/src/rxr/rxr_pkt_type_req.c
In rxr_pkt_handle_long_rtw_recv(), rtw_hdr is cast from pkt_entry->pkt.
Then rxr_pkt_copy_to_rx is called to copy data from packet entry to
target buffer, which could release the packet entry after data copied
via rxr_pkt_entry_release_rx(). It then used tx_id stored in the released
packet entry to send CTS, which could cause a segmentation fault when
memory poisoning is enabled. This patch fixes this issue by using an
intermediate variable "tx_id" to store the value of "rtw_hdr->tx_id"
before the packet entry is released, and assign it to rx_entry->tx_id.
> [v1.11.x] prov/efa: Fix a bug in rxr_pkt_handle_long_rtw_recv

- prov/efa/src/rxr/rxr_rma.c
When "ENABLE_DEBUG" is defined, the "rx_entry->rx_pending_entry" is
inserted into "ep->rx_pending_list" each time rxr_rma_post_efa_emulated_read
is called. When there is an error from rxr_pkt_post_crtl, the rx_entry is
released by rxr_release_rx_entry, but its rx_pending_entry is not removed
from ep->rx_pending_list. This makes the ep->rx_pending_list has a released
entry that will be used by later dlist_insert_tail calls, which could cause
segmentation fault when memory poisoning is enabled.
This patch fixes this issue by removing the rx_pending_entry from
ep->rx_pending_list before its rx_entry is released.
> [v1.11.x] prov/efa: Fix a bug in rxr_rma_post_efa_emulated_read

- prov/rxm/src/rxm_cq.c
These cleanups simplify the code paths for the rendezvous protocol messages.  The inject path optimizations are removed.  Code is restructured to reduce line lengths and improve readability.  Errors are converted into asserts, with notes that most of fatal to the protocol and should be used to tear down communication with the peer.  The changes remove more of the possible unaffiliated completions that could be generated to the application.
More work is needed to fully address the rxm_handle_comp() error paths.  The remaining work is in handling receive completions (RXM_RX buffer state).
> prov/rxm: More cleanups in completion handling code paths

- libfabric.spec.in
Removes to following warning when building rpm:
'warning: %makeinstall is deprecated, try %make_install instead'
> spec: use make_install instead of makeinstall

- include/ofi_rbuf.h
- include/ofi_util.h
- prov/shm/src/smr_atomic.c
- prov/shm/src/smr_ep.c
- prov/shm/src/smr_msg.c
- prov/shm/src/smr_rma.c
- prov/udp/src/udpx_ep.c
- prov/util/src/util_cq.c
There is an issue in the util cq aux code path where the insert_aux call should be adding all auxillary entries to the last committed cirq entry but it's calling ofi_cirque_tail which returns the next free entry.
The ofi_cirque_tail function is misleading so this patch renames it to ofi_cirque_next and redfines ofi_cirque_tail to return the last committed entry. All calls to ofi_cirque_tail are renamed in this patch except for the problematic insert_aux call which remains with the redfined ofi_cirque_tail call.
The second patch moves the commit call in insert_aux to make sure that the last committed entry exists.
> include/ofi_rbuf, prov/util: fix util cq issue and rename ofi_cirq function

- prov/rxm/src/rxm_cq.c
Fix coverity reports of unset value.  The value is only used
in a print statement, so is harmless, but initialize it to
ENOMEM to reflect the actual error.
> prov/rxm: Set ret value in rdnv error paths

- prov/shm/src/smr_progress.c
Currently, in smr_progress_resp_entry close(tx_entry->fd) is called
for both smr_src_iov and smr_src_ipc. This is wrong because
pending->fd is only used by IPC.
This patch fix the issue by not close(pending->fd) for smr_src_ipc.
> prov/shm: fix a bug in smr_progress_resp_entry

- configure.ac
- fabtests/configure.ac
- fabtests/functional/cm_data.c
- fabtests/functional/unexpected_msg.c
- fabtests/scripts/runfabtests.sh
Use common command line options to align with other fabtests.
> build: Add configure option to enable ASAN, fabtests: minor updates to 2 tests

- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_atomic.c
- prov/rxm/src/rxm_cq.c
- prov/rxm/src/rxm_domain.c
- prov/rxm/src/rxm_ep.c
- prov/rxm/src/rxm_init.c
Users can specify an eager message size through environment
variables.  However, what's not clear to the user is that rxm
silently reserves a portion of that size of internal headers.
Because the eager size may be used elsewhere by the application,
this can result in non-optimal transfers.
For example, when multi-recv buffers are used, the application
can indicate how much free space remains before the buffer
should be released.  MPI sets this equal to the receive buffer
size (16K).  It then uses the multi-recv buffer to receive
transfers up to 16k in size.  However, the actual eager size
is slightly less than 16k, due to the rxm packet header.  The
result is that 16k transfers from MPI end up being transfered
using either the SAR or rendezvous protocols.  This results
in failures, as …
> prov/rxm: Use eager, sar, and buffer sizes correctly

- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_conn.c
- prov/rxm/src/rxm_cq.c
- prov/rxm/src/rxm_ep.c
Various patches to fix FI_MULTI_RECV for rxm. The provider was delaying the reposting of the FI_MULTI_RECV buffers and not adjusting them correctly, causing hangs when FI_MULTI_RECV was used for SAR or rendezvous messages.
> prov/rxm: FI_MULTI_RECV fixes

- prov/psm3/configure.m4
and both psm2 and psm3 were not built as dl providers.
> prov/psm3: Disable psm3 provider if with-psm2-src is used

- prov/efa/src/rxr/rxr_init.c
Loopback CUDA transfers do not currently work with EFA. NCCL does not require FI_LOCAL_COMM so we can safely add this check until we can support loopback via device transfers or SHM CUDA IPC support. Also fix some warning prints while we're here.
Test description: Verified FI_LOCAL_COMM is dropped when FI_HMEM is requested and that the provider is not selected when both FI_LOCAL_COMM and FI_HMEM are requested. Ran a NCCL perftest and MPI ring_c to verify EFA is still selected.
> prov/efa: exclude EFA when FI_HMEM and FI_LOCAL_COMM are selected

- prov/tcp/src/tcpx_conn_mgr.c
- prov/tcp/src/tcpx_ep.c
There are some differences with non-blocking sockets between Linux and
Windows:
1) connect() on Windows may return EWOULDBLOCK, not EINPROGRESS
2) recv() with MSG_WAITALL flag returns EOPNOTSUPP
> prov/tcp: fixed hang on windows

- prov/rxm/src/rxm_domain.c
Destroy rxm_domain->amo_bufpool_lock in rxm_domain_close and in
error handling code to avoid resource leak.
> prov/rxm: cleanup rxm_domain->amo_bufpool_lock

- prov/psm3/Makefile.include
Before building the provider library, 3 steps are inserted into the make
dependency tree:
1) link all objects/archives in provider into single libpsm3_full.lo
2) using objcopy tool, remove all but fi_psm3_ini from global symbols
3) repack new .o file into libpsm3.a (and make libpsm3.la wrapper)
This will effectively isolate the psm3 provider code to not allow name
collisions with other providers with similar function names when linked
into single libfabric library. As well as preserve function names for
debugging.
> prov/psm3: Only export fi_psm3_ini when building into libfabric

- include/ofi.h
- include/ofi_indexer.h
- include/ofi_mem.h
- include/ofi_osd.h
- prov/rxd/src/rxd_av.c
- prov/rxd/src/rxd_ep.c
- prov/sockets/src/sock_ep.c
- prov/util/src/util_buf.c
- src/indexer.c
The rxd provider allocates and stores a data structure in an index map.  Although the map is reset during cleanup, the allocated structures are lost, resulting in a memory leak.  The latter usually only happens during application exit, but does show up using ASAN.  Add a callback when resetting the idm, so that the structures can be freed.
Enhance the buffer pool to wrap the user's buffer with magic values.  Check that the values are intact whenever the buffers are freed.  This is just to help catch buffer overruns.  No overruns have been detected so far with the checks in place.
> bufpool: check for buffer overruns, idm: add callback to handle cleanup

- README.md
remove the mlx and mxm sections
> readme: Remove deprecated providers from readme.md

- prov/psm3/configure.m4
Reverts ofiwg/libfabric#6575
Patch #6580 Fixed this workaround and is no longer needed.
> Revert "prov/psm3: Disable psm3 provider if with-psm2-src is used"

- NEWS.md
> news: Update news for v1.12 release

- prov/sockets/src/sock_progress.c
Signed-off-by: Gengbin Zheng <gengbin.zheng@intel.com>
> prov/sockets: reset rx_ctx->progress_start when an entry is removed

- src/hmem_ze.c
The global device handle array is overwritten whenever the function
ze_is_addr_valid() is called. This is fine for device memory pointers
since the device handles are always the same. However, if the address
being checked is not a device memory pointer, the retrieved device handle
is NULL. Subsequent calls to ofi_copy_*() function will cause segfault
until another successful check is performed.
There is no need to update the global array here, use a local variable
instead.
> src/hmem_ze: Fix a bug that may overwrite device handle with NULL

- prov/psm3/configure.ac
- prov/psm3/configure.m4
- prov/psm3/psm3/psm_rndv_mod.c
- prov/psm3/psm3/psm_rndv_mod.h
Detect location of RV header automatically if not passed in.
Check locations in following order:
/usr/include/rdma/rv_user_ioctls.h
/usr/include/uapi/rv/rv_user_ioctls.h
/usr/include/rv/rv_user_ioctls.h
If not found in newer rdma dir define and use HAVE_OLD_RV_HEADER.
If found, indicate older location and header are available.
Also added compile test for detecting overflow_cnt field.
define HAVE_NO_PSM3_RV_OVERFLOW_CNT if not found.
Address RV_RING_ALLOC_LEN vs RING_ALLOC_LEN differences
Reviewed-by: Kaike Wan <kaike.wan@intel.com>
Reviewed-by: Todd Rimmer <todd.rimmer@intel.com>
> prov/psm3/rv: Handle location change of rv header

- prov/psm3/psm3/psm_verbs_mr.h
- prov/psm3/psm3/ptl_ips/ips_proto_connect.c
Both cases are not required, but cleaner to have them.
Ifdef around include will just stop the include of an empty file.
Ifdef around assert will always be false as those fields are only set
inside an ifdef.
> prov/psm3: Add missing RNDV_MOD ifdefs

- prov/rxm/src/rxm_cq.c
- prov/tcp/src/tcpx.h
- prov/tcp/src/tcpx_progress.c
- src/iov.c
Not that these make things work, but should improve the code.
Fallback to unexpected msg handling for multi-recv buffers.
Initialize the ignore bits when matching buffers.
> prov/rxm: Minor fixes for dynamic receive buffer handling

- configure.ac
- src/hmem_cuda_gdrcopy.c
Currently, gdrcopy library is always checked and used in if it exists,
even if user specified --without-gdrcopy or --with-gdrcopy=no.
This patch adjust beavior of gdrcopy library checking to the following
1. If cuda library is not available, do not check gdrcopy. This is
because gdrcopy without cuda does not work. If user asked for gdrcopy
by --with-gdrcopy, fail the configure and print error message.
2. If cuda library is available:
2a. If user specify --without-gdrcopy or --with-gdrcopy=no, do not
checkout gdrcopy.
2b. Otherwise check gdrcopy. If gdrcopy does not exist and user asked
for gdrcopy, fail and print error message.
> configure.ac: fix behavior of gdrcopy library checking and usage

- NEWS.md
- configure.ac
- fabtests/COPYING
- fabtests/configure.ac
- include/ofi_epoll.h
- include/windows/config.h
- prov/psm3/Makefile.include
- prov/tcp/src/tcpx_ep.c
- src/common.c
We can only cancel a receive if it's not active.  However, the
current check only allows cancel to proceed if it is.  Fix the
check to look for inactive receives.
> v1.12.0 release - CI validation

- prov/psm3/psm3/include/opa_user.h
https://github.com/ofiwg/libfabric/issues/6614
Reviewed-by: Goldman, Adam <adam.goldman@intel.com>
Signed-off-by: Todd Rimmer <todd.rimmer@intel.com>
> prov/psm3: Add PACK_SUFFIX define to missing header

- prov/psm3/Makefile.include
> prov/psm3: Use AR variable and do not call ar directly

- prov/sockets/src/sock_av.c
In sock_av_insert, the socket addresses stored in the addr arary can be
in different address formats (IPv4 or IPv6). Use the actual sock addrlen
stored in sock av when walking through the addr array, instead of
incorrectly assuming it is struct sockaddr.
Signed-off-by: Gengbin Zheng <gengbin.zheng@intel.com>
> prov/sockets: use correct addrlen when walking through the addr array

- prov/psm3/psm3/psm_rndv_mod.c
- prov/psm3/psm3/psm_utils.c
- prov/psm3/psm3/psm_verbs_ep.c
Remove unused AF_IB stubs.
Fixes: #6623
> prov/psm3: remove dependency on rdmacm headers

- prov/efa/src/efa_av.c
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_type.h
- prov/efa/src/rxr/rxr_pkt_type_misc.c
Currently, when using extra feature (e.g., DELIEVERY_COMPLETE),
the sender triggers a handshake procedure, and won't proceed
futher until receiving the handshake packet from the peer.
However, if posting handshake packet fails at peer side, the
sender will keep waiting, which results in hanging issue.
This patch fixes the issue by
1. queuing the peers to which we previously fail to post
handshake packet with EAGAIN error.
2. re-posting the handshake packet to those queued peers later.
Tested:
1. Add a retry counter (say 2) in rxr_ep structure to intentionally let `rxr_pkt_post_handshake` fail 2 times with -FI_EAGAIN to make sure that peer gets queued in rxr_ep->peer_queued_list and repost 2 times before success.
2. Similar as 1, intentionally let `rxr_pkt_post_handshake` fail the first …
> prov/efa: Re-post handshake packet failed with EAGAIN previously

- prov/efa/src/rxr/rxr_pkt_entry.c
Currently, rx_pkt_entry_release_tx() call
rxr_pkt_entry_release_single_tx() in a loop to release
packet entries linked by pkt_entry->next. This is wrong
because TX pkt_entry are not linked.
This patch address the issue by removing the loop
and merge rxr_pkt_entry_release_tx() into
rxr_pkt_entry_release_single_tx().
> prov/efa: fix a bug in rxr_pkt_entry_release_tx()

- include/ofi_shm.h
- prov/shm/src/smr.h
- prov/util/src/util_shm.c
We can not assume CMA always works when sending to self.
In the container context, CMA to self is not permitted because
the syscalls are already blocked by dropping CAP_SYS_PTRACE
https://docs.docker.com/engine/security/seccomp/.
Fix the issue by enabling CMA check for endpoint itself.
The CMA capability is splitted into cma_cap_self and cma_cap_peer.
Since cma_cap_self and cma_cap_peer might be different, we can
not use field 'cma_cap' as struct iovec in the test CMA call
any more, so use field 'pid' instead.
(cherry picked from commit af391c964c725199948ee7a6bca7686ae3d202db)
> [v1.11.x] prov/shm: Enable CMA check for endpoint itself

- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_init.c
- prov/efa/src/rxr/rxr_pkt_type_misc.c
- prov/efa/src/rxr/rxr_pkt_type_req.c
- prov/efa/src/rxr/rxr_read.c
- prov/efa/src/rxr/rxr_read.h
Pick the last of the relevant EFA changes from the v1.12.0 release to v1.11.x in preparation for 1.11.3.
0a7d3d9f2 prov/efa: exclude EFA when FI_HMEM and FI_LOCAL_COMM are selected
252374efd prov/efa: fix a bug in rxr_read_handle_error()
6e642b7a5 prov/efa: handle read entry error in rxr_cq_handle_cq_error()
bd7fe98dc prov/efa: add type of enum rxr_x_entry_type to rxr_read_entry
52dd32a79 prov/efa: add RXR_READ_ENTRY to enum rxr_x_entry_type
598057edd prov/efa: use rx_atomrsp_pool for atomic response data
> [v1.11.x] EFA fixes from v1.12.0 release

- src/fabric.c
Because EFA supports UD QPs through verbs, the psm3 provider
tries to use it, but fails.  The reason for the failure is
still being investigated.  But anywhere efa can execute, it
should have priority over being matched with another provider.
> core: Move efa provider ahead of psmX providers

- src/fabric.c
Because EFA supports UD QPs through verbs, the psm3 provider
tries to use it, but fails.  The reason for the failure is
still being investigated.  But anywhere efa can execute, it
should have priority over being matched with another provider.
> [v1.12.x] core: Move efa provider ahead of psmX providers

- prov/verbs/src/verbs_domain_xrc.c
MOFED 5.2 and newer linux kernels validate that XRC INI
QP init attributes do not include an SRQ. Adjust XRC INI
QP creation to account for this. This is backwards
compatible with older MOFED versions that didn't have this
additional INI QP check.
> prov/verbs: Fix XRC MOFED 5.2 incompatibility issue

- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_atomic.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_init.c
- prov/efa/src/rxr/rxr_msg.c
- prov/efa/src/rxr/rxr_pkt_entry.c
- prov/efa/src/rxr/rxr_read.c
- prov/efa/src/rxr/rxr_rma.c
This PR contain 3 patches that fix several issues when using shm provider to support cuda buffer:
1.  request the FI_HMEM capability in cuda build
2. fix a bug the wrong descriptor was used for shm provider
3. do not use eager protocol for cuda buffer and local peer.
> prov/efa: use shm provider to support cuda buffer

- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_init.c
This PR contains two commits that enable efa provider to support FI_HMEM and FI_LOCAL_COMM.
1. disable shm provider usage when application request FI_HMEM capability
2. revert the commit that exclude EFA if application requested FI_HMEM and FI_LOCAL_COMM.
> prov/efa: support FI_HMEM and FI_LOCAL_COMM together

- prov/efa/src/efa_domain.c
- prov/efa/src/rxr/rxr_domain.c
Currently, EFA's mr cache does not support cuda memory, thus
during memory registration, the OFI_MR_NOCACHE flag was added
to prevent MR cache being used for cuda memory.
This patch address the issue by first add cuda memory mointor
to efa's mr cache so it can support cuda memory, then stop
adding the OFI_MR_NOCACHE flag to cuda memory
> prov/efa: enable mr cache for cuda memory

- prov/efa/src/efa_domain.c
- prov/efa/src/rxr/rxr_domain.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_init.c
This PR contains 3 fixes to EFA provider to support cuda buffer:
1. do not use shm provider when application request FI_HMEM capability
2. revert "exclude EFA when FI_HMEM and FI_LOCAL_COMM have been requested
3. enable MR cache for cuda memory
> [v1.12.x] efa: bug fixes to support cuda buffer

- configure.ac
When building libfabric with a minimal shell such as `dash` it will fail.
```
export CONFIG_SHELL=/bin/dash
```
```
./configure: 39333: test: 0: unexpected operator
./configure: 39333: test: 0: unexpected operator
./configure: 39333: test: 0: unexpected operator
./configure: 39333: test: 0: unexpected operator
./configure: 39333: test: 0: unexpected operator
./configure: 39333: test: 0: unexpected operator
./configure: 39333: test: 0: unexpected operator
./configure: 39333: test: 0: unexpected operator
./configure: 39333: test: 0: unexpected operator
./configure: 39333: test: 0: unexpected operator
```
```
/bin/dash ./libtool  --tag=CC   --mode=link clang -Wall -O2 -DNDEBUG -fvisibility=hidden -Wall -Wundef -Wpointer-arith   -o util/fi_info util/info.o src/libfabric.la -latomic -lrt …
```
> configure.ac: Fix non-POSIX syntax.

- prov/bgq/configure.m4
- prov/efa/configure.m4
- prov/gni/configure.m4
- prov/hook/hook_debug/configure.m4
- prov/hook/perf/configure.m4
See: https://github.com/ofiwg/libfabric/pull/6646
> configure.m4: Fix non-POSIX syntax.

- src/fabric.c
Because psm3 can run over OPA hardware, it shows up first in
fi_getinfo.  Move psm2 ahead of psm3, since psm2 is tied to
specific HW.
PSM3 is closest to util providers, such as rxm or rxd.  Set
it's default priority to just ahead of those providers.
> core: Shift psm3 priority

- src/fabric.c
Because psm3 can run over OPA hardware, it shows up first in
fi_getinfo.  Move psm2 ahead of psm3, since psm2 is tied to
specific HW.
PSM3 is closest to util providers, such as rxm or rxd.  Set
it's default priority to just ahead of those providers.
> [v1.12.x] core: Shift psm3 priority

- prov/shm/src/smr_progress.c
This path uses ofi_copy_to_hmem_iov to copy data to pending->iov.
This is to handle the case when pending->iov is backed by cuda
memory.
> prov/shm: use ofi_copy_hmem_iov to handl smr_src_inject

- man/fi_cq.3.md
- man/fi_endpoint.3.md
- man/fi_mr.3.md
- man/fi_msg.3.md
Greatly expand the semantics around completions and target
side visibility of the data.  No attempt is being made to
define new behavior of the APIs here.  Rather it should be
describing the behavior that applications are already seeing,
but developers may not be fully aware of.
The visibility of transfer at the target is defined, with
additional descriptions for how applications must handle
heterogenous memory.
> man/cq: Document completion semantics around HMEM

- prov/psm3/Makefile.include
Update timestamp only when checksum changes.
Fixes: #6630
> prov/psm3: Fix building chksum with different builddir

- prov/efa/src/efa_av.c
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_type.h
- prov/efa/src/rxr/rxr_pkt_type_misc.c
Currently, when using extra feature (e.g., DELIEVERY_COMPLETE),
the sender triggers a handshake procedure, and won't proceed
futher until receiving the handshake packet from the peer.
However, if posting handshake packet fails at peer side, the
sender will keep waiting, which results in hanging issue.
This patch fixes the issue by
1. queuing the peers to which we previously fail to post
handshake packet with EAGAIN error.
2. re-posting the handshake packet to those queued peers later.
> [v1.12.x] prov/efa: Re-post handshake packet failed with EAGAIN previously

- config/fi_strip_optflags.m4
- configure.ac
- prov/psm3/Makefile.include
- prov/psm3/configure.m4
Minimal support is avx to enable psm3 provider
Remove avx2 from flags in makefile.
> prov/psm3: Add check for avx2 to configure

- configure.ac
- fabtests/common/hmem_ze.c
- fabtests/configure.ac
- src/hmem_ze.c
Libfabric configure needs to check 2 dependencies now because of an extra one added for the IPC support.
Fabtests configured was failing when using --with-ze=no option because of incorrect flag setting.
Also fixes the use of --with-ze option in both that should fail if ze is not detected/supported
> configure, fabtests/configure: fix ze configure checks

- include/ofi_hmem.h
- prov/util/src/util_mem_monitor.c
- src/hmem.c
Currently in ofi_monitors_add_cache(), if a minitor failed to
start and the error code is -FI_ENOSYS, the error is ignored.
This behavior was to handle the situation that device memory
monitors cannot start if the device memory was not
configured. However, it has an unintended consequence:
if a system memory monitor failed to start, the error was ignored.
As a result, the MR cache was initialized successfully, but it
does not support system memory.
To address this issue, this PR made the following change to
ofi_monitors_add_cache():
1. It introduced an array iface_enabled, which keep record
each type of memory's configure status
2. If a type of memory is not enabled, do not check whether
the monitor can be started.
3. If a type of memory is enabled, and caller specified
a monitor, and the …
> core/mem_monitor: return error when memory minitor failed to start

- src/hmem_cuda.c
Currently cuda_hmem_init return fail if gdrcopy initialization
failed. This is wrong because gdrcopy is an option feature of
cuda, cuda will function properly without gdrcopy.
Meanwhile, in cuda_hmem_cleanup(), we should
call cuda_gdrcopy_hmem_cleanup() only if gdrcopy has been
initialized.
This patch addresses the two issues.
> src/hmem: fix bug in cuda_hmem_init and cuda_hmem_cleanup

- Makefile.am
autogen.sh is needed for someone to test changes to configure
on a released package.  This request came out of conversation
with RedHat debugging build issues with v1.12.0 release.
> package: Add autogen.sh to release package

- Makefile.am
- NEWS.md
- configure.ac
- fabtests/configure.ac
- include/rdma/fabric.h
- include/windows/config.h
autogen.sh is needed for someone to test changes to configure
on a released package.  This request came out of conversation
with RedHat debugging build issues with v1.12.0 release.
> v1.12.1rc1 (PR includes adding autogen.sh to package)

- include/ofi_util.h
- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_attr.c
- prov/rxm/src/rxm_ep.c
- prov/rxm/src/rxm_init.c
- prov/tcp/src/tcpx_attr.c
- prov/tcp/src/tcpx_msg.c
- prov/util/src/util_attr.c
- Fix coverity warning (false positive)
- tcp: increase maximum supported ep attributes to allow larger srx sizes
- rxm: adjust default rx/tx sizes to reduce memory footprint. use different msg rx/tx sizes based on use of srx
- rxm: adjust buffer pool growth sizes and remove use of hugepages
- core: allow a provider to modify the default fi_info values (currently set to the max values)
Details in commit messages.  The goal is to allow rxm to use a larger size for shared receive contexts, versus the same size used when each msg ep has its own rx.  Update tcp to support a larger rx size (so that getinfo doesn't fail those requests), but specify different rx sizes for when shared rx is used vs not.
> tcp/rxm: adjust default tx/rx attribute sizes

- include/ofi_lock.h
- prov/rxm/src/rxm_ep.c
- prov/shm/src/smr_av.c
- prov/tcp/src/tcpx_conn_mgr.c
- prov/tcp/src/tcpx_ep.c
- prov/tcp/src/tcpx_progress.c
- prov/util/src/util_av.c
- prov/util/src/util_cq.c
- prov/verbs/src/verbs_cm_xrc.c
- prov/verbs/src/verbs_cq.c
- prov/verbs/src/verbs_domain_xrc.c
- prov/verbs/src/verbs_ep.c
- prov/verbs/src/verbs_eq.c
Some functions require that a lock be held when they are
called.  Provide a debug check that can verify this.  This
can replace comments in the code that the lock is held with
actual code that documents the requiremen and checks for it.
Update obvious places in the code where locks must be held
to assert on fastlock_held.
> core: Add fastlock_held debug check

- prov/gni/src/gnix_ep.c
Libfabric allows relaxed enforcement of local MR registration thus the user can choose to skip local buffer registration when issuing an RMA. The current code, however, requires a pointer to a NULL pointer for such a case, which is inconvenient to user. This patch allows a NULL pointer to be directly passed.
Background about why we propose this change:
- In MPICH, we always skip local buffer registration and rely on the underlying provider performs necessary operation. Thus, we specify `msg.desc=NULL` when using `fi_readmsg|writemsg`.
- GNI can automatically register the local buffer if `desc` is not provided by user but it still requires a non-NULL `desc` to be passed (e.g., `desc[0] = NULL`). It will be more convenient to user if it accepts a `NULL` pointer directly.
I don't see a clear …
> prov/gni: allow NULL desc in read|write{v,msg}

- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_atomic.c
- prov/rxm/src/rxm_cq.c
- prov/rxm/src/rxm_domain.c
- prov/rxm/src/rxm_ep.c
- prov/rxm/src/rxm_rma.c
rxm maintains an array of buffer pools for transmits per endpoint, 9 total.  Each pool by default can hold up to 16k entries, and 4 of the pools have entries equal to the eager message size (default 16k).  Those 4 pools alone can consume 1GB of pinned memory.  Yee-gads.  They consume 64MB basically for existing.
The only purpose for having separate pools is to save setting either 1 or 2 integer values, depending on the code path.  Wow.
Merge all these pools into a single tx pool.  That pool starts by consuming 16 MB of memory (can be reduced by shrinking the eager size), but is allowed to grow as needed.  The latter is required in order to handle receive side processing for response messages.  The receive side is not sufficiently robust to handle being unable to obtain a tx buffer without …
> prov/rxm: Merge all the tx buffer pools into one to reduce memory footprint

- prov/psm3/Makefile.include
- prov/psm3/configure.m4
- prov/psm3/psm3/include/opa_revision.h
- prov/psm3/psm3/psm.c
- prov/psm3/src/.gitignore
- prov/psm3/src/psm3_revision.c.in
Use object dependency instead of BUILT_SOURCES as BUILT_SOURCES seem to
randomly retrigger. Without a dependency the header would not get built
at all. See Built Sources Example on automake web manual:
https://www.gnu.org/software/automake/manual/html_node/Built-Sources-Example.html
Updated IFS to IEFS.
Add missing replace variables to retrun "<Unknown>" if not defined.
Some values are only available for IEFS releases.
> prov/psm3: Update SRC Checksum to generate into custom header

- config/fi_provider.m4
- configure.ac
Rather than needing to explicitly disable the build for all other
providers when a single provider is desired, add an enable-only
option that only builds providers that are explicitly enabled
> build: Add --enable-only option to only build specified providers

- prov/rxm/src/rxm_conn.c
Non-functional changes to make rxm_cmap_process_connreq() easier to read and remove misleading label usage.
> prov/rxm: Minor non-functional code cleanup/readability changes

- fabtests/common/shared.c
- prov/rxm/src/rxm_conn.c
Don't discard thread interrupts.  Allow the thread to return to the caller or continue processing as usual.
> prov/rxm: Fail wait calls if an interrupt is received

- prov/rxm/src/rxm_cq.c
- prov/rxm/src/rxm_ep.c
- prov/rxm/src/rxm_init.c
Disable direct send optimization for verbs.  For some reason, using it over HFI results in corrupted receive data.  (Works for other verbs devices).
This should still result in a failure on AWS NCCL.  The failure there also suggests that either receive data is corrupted, or tags are not being matched correctly (initial address exchange appears to fail).  But that failure looks related to the dynamic receive patch.
Verify that all CI passes prior to merging.
> prov/rxm: enable optimizations only for tcp provider

- include/rdma/fabric.h
- man/fi_mr.3.md
Some providers may need to know whether memory allocated by a device
API is only accessible by the device (vs host or unified memory).
Add a flag that can be passed into the fi_mr_regattr call to specify
this condition.
Add definition to man pages as well.
> include/rdma, man/fi_mr: add FI_HMEM_DEVICE_ONLY flag for use in fi_mr_regattr

- prov/gni/configure.m4
there was some configury code which was brittle and ended up
failing at some point after some kind of cray software moduel file
changes.
use more standard approach of tweaking CPPFLAGS to have AC_CHECK_TYPES
work.
> prov/gni: swat a configury bug

- man/fi_efa.7.md
- prov/efa/src/efa.h
- prov/efa/src/efa_domain.c
- prov/efa/src/efa_fabric.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_init.c
This series allows applications to use fork again by disabling the internal use of huge pages when fork support is requested and the registration cache is enabled. Applications that require the registration of regions backed by huge pages, fork support, and the registration cache are still not supported and will cause the domain open to fail. That mode will be supported in the future when changes to the linux kernel makes rdma-core fork support irrelevant in general by copying pages into the fork.
For convenience a new environment variable, `FI_EFA_FORK_SAFE`, was also added here and will call `ibv_fork_init()` when set.
Test description: Set the new environment variable and the rdma-core environment variables and verified that huge pages are not used when fork support is not enabled. …
> prov/efa: Allow fork support and MR cache

- prov/efa/src/efa_domain.c
- prov/efa/src/rxr/rxr_domain.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_init.c
A series patches back ported from 1.12.x branch to support cuda communication on same host.
> [v1.11.x] prov/efa: back port support of cuda pointer communication on same host

- fabtests/common/shared.c
- fabtests/include/shared.h
- fabtests/man/fabtests.7.md
Currently for fabtests, we do not have fork tests that
call fork to create a child process when running the test.
Given the fact that plenty of applications uses fork
regularly, we need to enable this option.
This commit adds the `-K` flag for the tests under
fabtests/benchmarks directory. With this option, sender
and receiver will both call fork to create a child process after
endpoint was initialized. The child process will do nothing
> Add -K Flag For Benchmark Tests

- prov/tcp/src/tcpx_progress.c
Fix coverity warning.  We can ignore the return value from
ofi_sock_flush (we have no where to return the value to).
> prov/tcp: Cast away ofi_bsock_flush return value in progress_tx

- src/hmem_cuda.c
cuda_host_register() and cuda_host_unregister() were reporting
cudaMemcpy in FI_WARN instead of cudaHostRegister and cudaHostUnregister
respectively.
> src/hmem: Fix incorrect CUDA warnings

- prov/efa/src/rxr/rxr_pkt_type_misc.c
In rxr_pkt_post_handshake, we always allocate pkt_entry
from tx_pkt_efa_pool even though the peer could be local peer.
However, we only increment 'ep->tx_pending' for successful
send to non-local peer. This causes the mismatch between
ep->tx_pending and number of allocated pkt_entry from
tx_pkt_efa_pool.
This patch fixed this issue by allocating pkt_entry
from tx_pkt_shm_pool for local peer.
> prov/efa: Fix a bug in rxr_pkt_post_handshake

- prov/efa/src/rxr/rxr_pkt_type_misc.c
In rxr_pkt_post_handshake, we always allocate pkt_entry
from tx_pkt_efa_pool even though the peer could be local peer.
However, we only increment 'ep->tx_pending' for successful
send to non-local peer. This causes the mismatch between
ep->tx_pending and number of allocated pkt_entry from
tx_pkt_efa_pool.
This patch fixed this issue by allocating pkt_entry
from tx_pkt_shm_pool for local peer.
> [v1.12.x] prov/efa: Fix a bug in rxr_pkt_post_handshake

- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_type_misc.c
prov/efa: return EAGAIN when pkts are exhausted sending segments
prov/efa: Fix a bug in rxr_pkt_post_handshake
> [V1.11.x] prov/efa: backport two bugfix commits 

- include/ofi_net.h
- prov/tcp/src/tcpx.h
- prov/tcp/src/tcpx_comm.c
- prov/tcp/src/tcpx_cq.c
- prov/tcp/src/tcpx_ep.c
- prov/tcp/src/tcpx_msg.c
- prov/tcp/src/tcpx_progress.c
- prov/tcp/src/tcpx_rma.c
- prov/tcp/src/tcpx_shared_ctx.c
- src/common.c
This series simplifies how the send and receive states are managed.  Each endpoint is active on a single transmit or receive operation at a time.  Until that operation completes, the state associated with the message does not change, except for the remaining data needing to be sent/received.  These changes target a problem where an older received header appears to be processed multiple times as a newly received message.  
The series has gone through a light set of local testing (single node in loopback) only.
> prov/tcp: rework the data code paths

- prov/tcp/src/tcpx_cq.c
- prov/tcp/src/tcpx_init.c
- prov/tcp/src/tcpx_progress.c
Fix possible application hang or stall when using blocking cq read calls.  Fail try_wait if there's data queued in the prefetch buffer (previously staging buffer).
Avoid always trying to call send progress on all endpoints unless the socket has been marked writeable.
> prov/tcp: Fix and an optimization to progress path

- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_cmd.h
Currently, when a packet was injected successfully,
rxr_pkt_post_ctrl_once() only releases the packet, which is not enough.
It should have called the packet's send completion handler.
As a result, the EOR packet's send completion handler was not called
for intra instance communication, causing rx entry leaking.
This patch fix the issue by calling rxr_pkt_handle_send_completion()
upon successfull packet injection.
> prov/efa: fix incorrect handle of successful injection

- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_cq.c
- prov/rxm/src/rxm_ep.c
Receive buffers are not immediately reposted to the msg
rx queue.  Instead they are placed onto a list and queued
on the next pass through rxm_ep_do_progress.  That
function is called if there are queued transmits or if
trying to send a message returns EAGAIN.  However, if
neither of those occur, then the receives will not be
reposted.  This results in hangs or stalls at the msg
ep level, with received data being unable to match with
a receive buffer.
Do not delay reposting buffers.  Post them immediately, so
that incoming receive messages have a place to land.
This fixes a hang seen when running MPI IMB uniband and
biband tests between 2 processes using the default settings.
This change updates the 'repost' buffer tracking as part of
it.  Buffers are always marked for reposting when …
> prov/rxm: Remove repost_ready_list to prevent stalls

- include/ofi_epoll.h
- src/common.c
- src/unix/osd.c
- src/windows/osd.c
Convert pollfds to act more like select, where a given fd
can be used directly as an index into the fdset.  This avoids
the linear searches currently done in the code to find the
fd in the fdset array.
Entries that are invalid are marked with an fd of -1, which
signals that poll() should ignore the entry.  This change
slightly increases the size of the fdset allocation, but
assumes that most entries will be used to reference a valid
fd value.
> core/pollfds: Use direct indexing instead of searches

- include/ofi_epoll.h
- prov/shm/src/smr_ep.c
- prov/sockets/include/sock.h
- prov/sockets/src/sock_conn.c
- prov/sockets/src/sock_ep_msg.c
- prov/sockets/src/sock_progress.c
- prov/tcp/src/tcpx.h
- prov/tcp/src/tcpx_conn_mgr.c
- prov/tcp/src/tcpx_cq.c
- prov/tcp/src/tcpx_ep.c
- prov/tcp/src/tcpx_msg.c
- prov/tcp/src/tcpx_progress.c
- prov/tcp/src/tcpx_rma.c
- prov/usnic/src/usdf_progress.c
- prov/usnic/src/usdf_wait.c
- prov/util/src/util_wait.c
- prov/verbs/src/verbs_eq.c
- src/common.c
Modify epoll abstraction to return which event was signaled.
Update all providers to the new abstraction.
Update tcp to only check sockets for events that have been signaled.
Replace multiple tcp buffer pools of the same object with a single pool.
> prov/tcp: optimize epoll event handling

- prov/efa/src/rxr/rxr_ep.c
In zero copy receive mode, EFA will post application buffer to
directly receive data. Under this mode, EFA will not allocate a
packet entry, instead it convert the application buffer into
a packet entry.
The first part of application buffer is used to store rxr_pkt_entry
object, which store some information of the transaction. This part
is not used to receive data.
Two arguments are required to post a buffer to receive data:
buffer pointer, and buffer length.
Curretly, buffer pointer is pkt_entry->pkt, which points to
the end of the rxr_pkt_entry structure, which is correct.
However, current buffer length is wrong. It is application
buffer length, but it should be application buffer length
subtract sizeof(struct rxr_pkt_entry).
This patch address the issue by specifying correct buffer …
> prov/efa: fix a bug in posting application buffer for zero copy receive

- prov/tcp/src/tcpx.h
- prov/tcp/src/tcpx_cq.c
- prov/tcp/src/tcpx_ep.c
- prov/tcp/src/tcpx_msg.c
- prov/tcp/src/tcpx_progress.c
- prov/tcp/src/tcpx_rma.c
- prov/tcp/src/tcpx_shared_ctx.c
Prep code to add in tx/rx overrun protection.
> prov/tcp: restructure xfer_entry alloc/free code paths

- prov/tcp/src/tcpx.h
- prov/tcp/src/tcpx_domain.c
- prov/tcp/src/tcpx_ep.c
- prov/tcp/src/tcpx_msg.c
- prov/tcp/src/tcpx_progress.c
Limit the number of sends or receives that the user can post before getting EAGAIN.
> prov/tcp: Add tx and rx overflow checks

- prov/efa/src/rxr/rxr_pkt_type_req.c
rxr_pkt_data_from_tx set up a RTM packet's data using information
from tx_entry.
It can avoid memory copy by using application's memory descriptors
(stored in tx_entry->desc).
Currently, if application provided memory descriptors, and used
multiple iov, only the 1st iov was setup in pkt_entry, the rest
was ignored.
This patch addresses the issue by doing memory copy under such
circumstance.
It also rename the function to rxr_pkt_req_data_from_tx() to
avoid confusion.
> prov/efa: fix a bug in rxr_pkt_data_from_tx

- fabtests/include/shared.h
The -H argument which enables FI_HMEM support does not take any arguments.
> fabtests/common: fix FI_HMEM request argument

- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_cmd.h
- prov/efa/src/rxr/rxr_pkt_type_req.c
back port the following 3 commits from master branch to v1.12.x branch:
e81536d48 prov/efa: fix incorrect handle of successful injection
ac7bf2d20 prov/efa: fix a bug in posting application buffer for zero copy receive
1bec449  prov/efa: fix a bug in rxr_pkt_data_from_tx
> [v1.12.x] prov/efa: backport 3 fixes

- include/ofi_atom.h
- include/ofi_shm.h
- prov/shm/src/smr_atomic.c
- prov/shm/src/smr_ep.c
- prov/shm/src/smr_msg.c
- prov/shm/src/smr_progress.c
- prov/shm/src/smr_rma.c
- prov/util/src/util_shm.c
In order to make progress, shm needs to check the cmd list for any
incoming messages and the resp queue for any operation completion
notifications. The only protection for these is the shm lock. This
can cause a lot of lock contention when the EP is trying to make
progress on incoming messages while a peer it trying to send a
message.
These issues are especially evident on particular nodes. Unclear
what the actual cause of the increase in contention is.
Regardless, to fix this, add a signal to the shm region which is used
to check whether there could be an incoming cmd or response. Peers can
still send messages without competing with the target for the lock.
Whenever a cmd is inserted or a response is updated, signal the lock
to let the EP know to try to make progress.
See performance …
> prov/shm: add shm signal to reduce lock contention

- prov/rxm/src/rxm_cq.c
- prov/rxm/src/rxm_domain.c
- prov/rxm/src/rxm_init.c
This set of changes fixes a a bug where the TCP receive side isn't able to determine if an incoming message was tagged and was, therefore, selecting the wrong receive queue to progress.
> prov/rxm: enable dynamic rbuf by default

- include/ofi_net.h
- prov/tcp/src/tcpx.h
- prov/tcp/src/tcpx_cq.c
- prov/tcp/src/tcpx_domain.c
- prov/tcp/src/tcpx_ep.c
- prov/tcp/src/tcpx_msg.c
- prov/tcp/src/tcpx_progress.c
- prov/tcp/src/tcpx_rma.c
- src/common.c
A couple of patches are cleanups which can be pulled out and applied separately.  The rest of the series is an attempt to add support for MSG_ZEROCOPY on larger transfers.  The changes have been tested locally, which forces zerocopy off, so while I believe the general implementation is there, it needs testing where zero copy is supported, plus broad testing on multiple platforms to verify that portability wasn't broken.  And we should probably see if it makes any difference in performance.
More work is needed to make the settings configurable, including forcing zero copy off.  Plus documentation is lacking, which aligns the feature nicely with the zerocopy documentation.
> prov/tcp: Changes in preparation of zero copy support

- fabtests/scripts/runfabtests.sh
- fabtests/ubertest/uber.c
Various fixes to help ubertest run with runfabtests/more options:
- Enable -d option for fi_ubertest that is used in other fabtests to specify a specific domain name
- Add client and server arguments specified on the command line when running runfabtests to ubertest
- Return correct error code for runfabtests to correctly report failures, especially in strict mode
> fabtests/ubertest: add domain selection, pass through arguments, return correct error code

- prov/sockets/src/sock_atomic.c
In `sock_ep_tx_atomic`, the calculation of `total_len` missed `compare_count` in
one of its branches, resulting in overflowing the ring buffer.
Fixes #6587
> prov/sockets: fix mis-calculation of total_len

- prov/rxm/src/rxm_cq.c
The cq entry only contains a valid tag when using the
tcp tagged APIs.  In other cases, the tag is carried
in the rxm header.  Always read from the header, since
we create a fake hdr in the tagged API case.
> prov/rxm: Fix retrieving tag from dyn rbuf

- fabtests/common/shared.c
- fabtests/include/shared.h
- fabtests/man/fabtests.7.md
This PR back-ports https://github.com/ofiwg/libfabric/pull/6694 to v1.11.x branch. This PR had a bug that makes the `-H` argument require an argument. This bug was fixed by https://github.com/ofiwg/libfabric/pull/6751 so back port this PR as well.
> fabtests: back port "Add -K Flag For Benchmark Tests" to v1.11.x branch

- man/fi_tcp.7.md
- prov/tcp/src/tcpx.h
- prov/tcp/src/tcpx_attr.c
- prov/tcp/src/tcpx_init.c
This patch allows the user to override the default tx and rx
size attributes using the environment variables FI_TCP_TX_SIZE and
FI_TCP_RX_SIZE.
> prov/tcp: Add environment variables to override tx/rx size attributes

- fabtests/common/shared.c
- fabtests/include/shared.h
- fabtests/man/fabtests.7.md
backport 2 patches:
add -K option to test fork
fix FI_HMEM request argument
> [v1.12.x] backport fabtests fork change

- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_entry.c
- prov/efa/src/rxr/rxr_pkt_entry.h
- prov/efa/src/rxr/rxr_pkt_type_data.c
- prov/efa/src/rxr/rxr_pkt_type_misc.c
1. fix a bug in rxr_pkt_entry_release_tx() which is missing in v1.12.x
2. fix RNR queuing
> [v1.12.x] prov/efa: backport 2 fixes

- man/fi_mr.3.md
'size' should have been 'size_t' not a separate parameter.  Add
missing ';'.
Fixes #6762
> man/mr: Fix fi_mr_refresh definition

- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_init.c
- prov/efa/src/rxr/rxr_msg.c
This PR backport https://github.com/ofiwg/libfabric/pull/6767 to v1.12.x branch
> [v1.12.x] prov/efa: backport efa enable inject

- prov/rxm/src/rxm_init.c
Shared rx should only enabled for tcp by default.  When the
comparison check switched from strcmp to strcase, the negation
was left behind, resulting in the opposite behavior.
> prov/rxm: Remove incorrect negation from strcasestr check

- fabtests/scripts/runfabtests.sh
If -u is not provided, runfabtests will attempt to find a suitable config
file. If it is not able to find a config file, runfabtests will still run
by passing -u {NULL} into the test causing a hang. Check for a null config
file and return after setting the config file.
> fabtests/runfabtest.sh: skip ubertest if not config file found

- src/fabric.c
If multiple versions of a provider are present, include it in the
list of available provider.  Do not discard the provider just
because it has a lower version number.  This allows loading
different versions of the same provider in case the application
requires a specific version (for testing or features).  To
maintain prior behavior of only exposing the latest version of a
provider, older versions are marked as hidden.
Not really tested, but first part of dealing with issue #6708.  Marking the provider as hidden probably isn't necessary, but avoids the off chance of an app searching based on provider name directly and ending up using the wrong one.
> core: Maintain list of all providers

- include/ofi_mr.h
- prov/efa/src/efa_mr.c
- prov/util/src/util_mr_cache.c
This patch introduce an argument flush_lru to
ofi_mr_cache_flush_unmapped().
Currently ofi_mr_cache_flush_unmapped() does two things:
it will clear the registration in mr_cache->flush_list.
it will remove the first registration in mr_cache->lru_list
if it is not empty.
mr_cache->flush_list contains registrations whose
corresponding memory region was not mapped any more, thus
is always good to clear.
mr_cache->lru_list contains registrations whose use_cnt is 0,
but memory region is still mapped, so they can be reused.
Sometimes, caller want to clear the flush list for some
applications, but do not want to touch lru list because it
might impact performance of other applications. This patch
will allow them to do that by calling ofi_mr_cache_flush()
with flush_lru set to false.
Signed-off-by: …
> [v1.9.x] util/mr_cache: add argument flush_lru to ofi_mr_cache_flush

- include/ofi_lock.h
- include/ofi_util.h
- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_conn.c
- prov/rxm/src/rxm_init.c
- prov/util/src/util_attr.c
- prov/util/src/util_buf.c
Pulling current set of fixes out of the rxm CM rework patch in order to merge them quicker.
- core/bufpool -- handle an alignment request of 0
- prov/rxm - remove unused field
- util/ep - add ofi_ep_lock_held macro
- core/getinfo - fix incorrect negation of strcasestr (how did rxm ever work?)
- prov/rxm - fix calling fi_getinfo incorrectly
> Fixes from PR #6778 

- configure.ac
- prov/shm/src/smr.h
- prov/shm/src/smr_msg.c
- prov/shm/src/smr_progress.c
- prov/shm/src/smr_rma.c
- prov/util/src/util_mr_map.c
- src/hmem_ze.c
Various HMEM related fixes and optimizations:
- Fail MR registration for uninitialized interfaces
- Separate ZE and DRM header dependencies since fallbacks are available
- Fix interface used for shm IPC protocol
- Add device only check in shm IPC protocol path
> prov/shm, prov/util, hmem_ze: hmem, ZE optimizations and fixes

- prov/efa/src/rxr/rxr_init.c
There's still hanging issue when disabling RNR firmware infinite
retry. While working on a fix for it, just reset RNR firmware
retry to EFA_RNR_INFINITE_RETRY to be safe.
> prov/efa: Reset RNR firmware retry to EFA_RNR_INFINITE_RETRY

- prov/efa/src/rxr/rxr_init.c
There's still hanging issue when disabling RNR firmware infinite
retry. While working on a fix for it, just reset RNR firmware
retry to EFA_RNR_INFINITE_RETRY to be safe.
(cherry picked from commit a2a188307ec97403f9c9097c40e51c378bfdf8ac)
> [v1.12.x] prov/efa: Reset RNR firmware retry to EFA_RNR_INFINITE_RETRY

- include/ofi_mr.h
- prov/util/src/util_mr_cache.c
When memory regions become unusable from munmap() or their
reference counts go to 0, the MR Cache places their tracking
data onto a list 'to be disposed of later'.  This commit ensures
that these entries are removed concurrent with other MR Cache
maintenance activities.
In order to make the intent more clear, I have renamed the flush_list to the dead_region_list.
The lack of disposal is a v1.11 bug.  It is my intent that this code find its way into the codebase starting
with this branch.
> prov/util: Ensure dead regions are removed from MR Cache lists

- include/linux/osd.h
- include/ofi_epoll.h
- include/ofi_net.h
- prov/tcp/src/tcpx.h
- prov/tcp/src/tcpx_cq.c
- prov/tcp/src/tcpx_ep.c
- prov/tcp/src/tcpx_init.c
- prov/tcp/src/tcpx_progress.c
- src/common.c
Disabled by default, but code is there for future reference.  Changes negatively impact performance, in some cases significantly.  I'd drop the changes completely, but zerocopy is supposed to provide a benefit, and it's worth trying to uncover why that isn't the case.  However, I won't be able to look into that for a while.
> prov/tcp: Add support for MSG_ZEROCOPY

- include/ofi_mr.h
- prov/util/src/util_mr_cache.c
In ofi_mr_cache_search, if there are dead regions that need to
be flushed, we call cache_flush, but pass in true to flush_lru.
The result is that when cleaning up dead regions, we will always
flush an entry from the cache.
To avoid this, only flush the lru if the cache is full (when
searching to add new entries).
> core/mr_cache: Fix flush_lru setting passed to flush

- prov/rxm/src/rxm_cq.c
> prov/rxm: fixed rx buffer leak

- include/rdma/fi_domain.h
- man/fi_atomic.3.md
- prov/util/src/util_atomic.c
- src/fi_tostr.c
Just the changes needed to support a HW provider that wanted
to use 128-bit integer atomics.
> Minimal changes to support FI_INT128/FI_UINT128

- prov/efa/src/efa_av.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_pkt_entry.c
- prov/efa/src/rxr/rxr_pkt_type_req.c
263e86583 prov/efa: Fix a bug in rxr_pkt_entry_release_tx to ensure we release rxr_pkt_sendv structure before doing memory poisoning. 
651a76549 prov/efa: Fix a bug in efa_rdm_av_remove_one to ensure we properly remove shm address before doing peer reset.
c75811b14 prov/efa: Fix bugs of using uninitialized field.
> prov/efa: Fix a few bugs

- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_atomic.c
- prov/rxm/src/rxm_conn.c
- prov/rxm/src/rxm_cq.c
- prov/rxm/src/rxm_domain.c
- prov/rxm/src/rxm_ep.c
- prov/rxm/src/rxm_init.c
This series creates a distinction between the eager message size and the size of bounce buffers, and targets rxm over tcp.  In the case of rxm over verbs, the two values must be the same.
The eager limit now defines a protocol threshold, similar to sar limit and rendezvous.  That is now independent from the bounce buffer sizes (buffer_size).  When using tcp, send side bounce buffers are not used -- instead 'direct send' is enabled.  With direct send, the user buffers are passed directly to tcp.  Direct send is an existing feature.  On the receiving side, dynamic receive allows tcp to copy data directly into the application buffer, again bypassing any bounce buffer.
The only time receive side bounce buffers are used is in the case of unexpected message handling.  For unexpected messages, …
> prov/rxm: Separate eager msg limit from receive buffer size

- .github/workflows/nroff-elves.sh
- .github/workflows/nroff-elves.yaml
The recent change of the default branch name from "master" to "main"
appears to somehow break hub's method of figuring out the base branch
name.
So get the base branch from the github JSON blob and pass that
explicitly on the command line to hub.
> Nroff Elves: explicitly pass base branch to "hub"

- prov/efa/src/rxr/rxr_pkt_entry.c
- prov/efa/src/rxr/rxr_pkt_type_req.c
4cc9f83 prov/efa: Fix a bug in rxr_pkt_entry_release_tx to ensure we release rxr_pkt_sendv structure before doing memory poisoning.
01c8082 prov/efa: Fix bugs of using uninitialized field.
> [v1.12.x] prov/efa: Fix bugs of using uninitialized field and incorrectly releasing rxr_pkt_sendv structure

- .github/workflows/nroff-elves.yaml
The commit e75aa39d2 to fix the Nroff Elves wasn't quite correct.  The
switch from "master" to "main" somehow mucked up "hub"'s ability to
guess the branch that we wanted to push to.  Hence, we need to
explicitly mention the base branch that we want "hub" to open the pull
request against.
The mistake in e75aa39d2 is that I tested the fix by launching the
Nroff Elves GitHub Action via a Pull Request.  In that case, the Elves
can look up the PR base branch create a new PR against that branch.
But the Nroff Elves are actually run via a (cron-like) schedule, and
there is no base branch when GitHub Actions are launched this way.
So instead, what the Elves really want to do is find the repo's
default branch, and then use that branch as the base branch for the
newly-opened PR.
Signed-off-by: …
> Nroff Elves: no base branch in a scheduled run

- include/ofi_net.h
- prov/tcp/src/tcpx_ep.c
tcpx_ep_disable is called in certain error cases, such as
problems during the CM exchange, if the underlying socket
has been disconnected (error on socket recv), or if the
user calls ep_shutdown.  When the ep is disabled, all
message queues are flushed and current operations are
canceled.  However, the ep is still attached with the
CQ and attempts can be made to progress it.
There's a possibility that data may have been queued
in the buffered socket prior to the ep being disabled.
Since the current receive operation was discarded, any
buffered data would be treated as a new message.  This
can lead to hitting an assert in tcpx_cq_progress that
the ep state is still connected.
To avoid hitting the assert, discard any buffered data.
Also call shutdown on the socket to disable further …
> prov/tcp: Flush bsock and shutdown socket in ep_disable

- prov/efa/src/efa_domain.c
Add the environment variable FI_EFA_DEFAULT_SYSTEM_MEM_MONITOR to select
memory monitor for the efa provider during runtime.
> prov/efa: Use the memory monitor specified by the user

- Makefile.am
- include/ofi_abi.h
- include/ofi_enosys.h
- include/ofi_mr.h
- include/rdma/fabric.h
- include/rdma/fi_ext.h
- libfabric.map.in
- libfabric.vcxproj
- libfabric.vcxproj.filters
- man/fi_fabric.3.md
- man/fi_mr.3.md
- man/fi_provider.3.md
- man/man3/fi_open.3
- man/man3/fi_provider.3
- prov/util/src/util_mem_monitor.c
- prov/util/src/util_mr_cache.c
- src/enosys.c
- src/fabric.c
- src/fi_tostr.c
Re-opening changes posted in PR #6809 after rename of master.
> core: New fi_open / fi_import_fid / fi_export_fid APIs

- prov/shm/src/smr_ep.c
- prov/shm/src/smr_progress.c
If a peer was restarted, the server needs to remap the region to
update the smr pointer. Otherwise, the persistent peer will update the
local pointer and not the actual peer.
To recognize if the peer has been restarted or not, send the PID in the
send_name protocol (exchanges smr region on the first send). If the
PID is different than the one currently mapped in the pointer, unlink
the old region and remap to an updated pointer.
To fully fix this, we also need to track and update outstanding transfers
to and from the peer to either resend or complete in error. Adding TODO for this.
> prov/shm: fix communication with peer that was restarted

- .github/workflows/nroff-elves.sh
- .github/workflows/nroff-elves.yaml
The Nroff Elves have been unhappy recently.  Make a few changes:
* Only run once an hour.  When failures happen, we don't need to get
emails every 15 minutes.  Plus, the Elves only do something
meaningful when a PR is merged with man pages updates, which doesn't
happen that often.
* Emit the entire JSON-ized ${{github}} token in the GitHub Action
logs.  The latest failure is that somehow
${{github.event.repository.default_branch}} is blank when running in
the ofiwg/libfabric repo (but not forks, for some reason).  Since
the Nroff Elves run on a cron schedule (and not a PR), you can't
just make a PR with the changes that you want to debug/test (e.g.,
emit ${{github.event.repository.default_branch}} to see what's going
wrong).  So add an emit of the entire ${{github}} blob to the job
that …
> Nroff Elves: update their contract

- prov/shm/src/smr_av.c
- prov/shm/src/smr_ep.c
- on av_insert, is smr_map_add fails, util_addr will be uninitialized
initialize to FI_ADDR_UNSPEC before every insert
- pass resp in to smr_copy_to_sar on smr_format_sar even though it is not needed
to make coverity happy
- add CMSG_DATA to assert in socket code to surpress coverity warning
> prov/shm: fix issues reported by coverity

- prov/efa/src/efa.h
- prov/efa/src/rxr/rxr_atomic.c
- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_msg.c
- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_entry.c
- prov/efa/src/rxr/rxr_pkt_type_data.c
- prov/efa/src/rxr/rxr_pkt_type_misc.c
- prov/efa/src/rxr/rxr_pkt_type_req.c
- prov/efa/src/rxr/rxr_read.c
- prov/efa/src/rxr/rxr_rma.c
12ad455 Handle FI_ADDR_NOTAVAIL in rxr_ep_get_peer
25ddc04e9c6478c60b6d5cb9b2c08b98094aa720 Add assertion for peer structure
5a840a7d84816e83530e46b996f036cfcb69f998 Do not call rxr_ep_get_peer for local read
> prov/efa: Handle FI_ADDR_NOTAVAIL in rxr_ep_get_peer and add assertion against returned peer

- prov/rxd/src/rxd_av.c
- prov/rxd/src/rxd_ep.c
When removing an address from the AV, the rxd
address/dg address should not be removed as well.
This is because the EP could still be communicating
with a peer for an outstanding transfer (or a retry).
If removed and reinserted, rxd will handle the duplicate
rxd address and map it accordingly.
This fixes a rare failure with the fi_av_xfer test which
is caused by a race condition where a peer tries to send
a retry or ACK after the address was removed from the AV.
> prov/rxd: AV/address cleanup

- include/rdma/providers/fi_prov.h
- man/fi_provider.3.md
- src/var.c
Previously an invalid environment var value for a boolean would result
in the default value being overwritten, this patch fixes that and
prevents the default value from being modified in that case.
---
Based off of #6857, resolves #6853
> Fix fi_param_get's behavior when parsing an invalid boolean value

- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_ep.c
This patch fixes two bugs in rxr_release_rx_entry():
First, this function should clear rx_entry->queued_pkts but
did not.
Second, this function should remove rx_entry from ep->rx_queued_entry_list
but did not.
Meanwhile, rxr_ep_progress_internal() was adjusted to accomodate
the changes to rxr_release_rx_entry()
> prov/efa: fix a bug in rxr_relase_rx_entry()

- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_init.c
backport the following commits to v1.12.x branch
prov/efa: fix a bug in rxr_relase_rx_entry()
prov/efa: adjust out-of-order packet pool chunk size
prov/efa: allocate memory for various packet pools during initialization
> [v1.12.x] prov/efa: backport 3 commits

- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_init.c
prov/efa: fix a bug in rxr_relase_rx_entry()
prov/efa: adjust out-of-order packet pool chunk size
prov/efa: allocate memory for various packet pools during initialization
> [v1.11.x] prov/efa: backport 3 commits

- prov/efa/src/rxr/rxr_pkt_type_req.c
0e14883 prov/efa: Fix bugs of using uninitialized field
bc48aee prov/efa: fix a bug in rxr_pkt_proc_matched_rtm()
> [v1.11.x] prov/efa: backport 2 bugfixes

- prov/efa/src/efa_av.c
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_msg.c
This patch added an unexpected RX queue for each peer to
improve the performance of matching application's receive
operation with unexpected RX entry.
The peer's unexpected rx queue was updated together with
endpoint's unexpected rx queue.
When application posted a receive buffer, if application
specified peer address, the peer's unexpected rx queue
(instead of ep's unexpected RX queue) is used for matching.
This improved performance because there are less RX entry
to search.
> prov/efa: Add unexpected rx queue for each peer

- prov/efa/src/rxr/rxr_pkt_type_misc.c
- prov/efa/src/rxr/rxr_read.c
9d04a6c31f1d3e0efd8f00ba0df4d818373bc7c0 prov/efa: Fix a bug of using uninitialized field of rxr_read_entry
dde4cedad6290fefc570cd3129075acf7a519b23 prov/efa: Fix a bug in rxr_handle_rma_read_completion
> prov/efa: Two bugfixes in local read logic

- prov/efa/src/efa.h
- prov/efa/src/efa_av.c
- prov/efa/src/rxr/rxr_atomic.c
- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_msg.c
- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_entry.c
- prov/efa/src/rxr/rxr_pkt_type_data.c
- prov/efa/src/rxr/rxr_pkt_type_misc.c
- prov/efa/src/rxr/rxr_pkt_type_req.c
- prov/efa/src/rxr/rxr_read.c
- prov/efa/src/rxr/rxr_rma.c
The issues here are
1. uninitialized mr field of struct rxr_read_entry and accessing struct after release, which result in segfault if memory poisoning enabled. Fixed in main branch via PR #6882
de1f8cbc8  [v1.12.x] prov/efa: Fix a bug in rxr_handle_rma_read_completion
6940e12ef [v1.12.x] prov/efa: Fix a bug of using uninitialized field of rxr_read_entry
2. passing FI_ADDR_NOTAVAIL as the address to rxr_ep_get_peer, which also results in segfault. Fixed in main branch via PR #6854
90a0fc419 [v1.12.x] prov/efa: Do not call rxr_ep_get_peer for local read
7fdfaf86f [v1.12.x] prov/efa: Add assertion for peer structure
b336fc2fe [v1.12.x] prov/efa: Handle FI_ADDR_NOTAVAIL in rxr_ep_get_peer
> [v1.12.x] prov/efa: backport bugfixes in local read path

- prov/efa/src/efa_av.c
- prov/efa/src/rxr/rxr_pkt_entry.c
According to uthash document:
https://troydhanson.github.io/uthash/userguide.html#_structure_keys
We should zero out content of key before calling HASH_FIND/ADD,
this patch does that for packet entry look up.
> prov/efa: zero out hash key before calling HASH_FIND

- prov/efa/src/efa.h
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_type_misc.c
- prov/efa/src/rxr/rxr_pkt_type_req.c
This PR fixes bugs in RNR support:
1. A handshake packet encounter RNR was dropped
2. Rx entry encountered RNR when sending RECEIPT packet was not queued thus RECEIPT packets was not resend
3. Tx entry encountered RNR when sending RTR packet was not queued thus RTR packets was not resend
> prov/efa: fix bugs in rnr support

- prov/efa/src/efa_av.c
This patch remove an unnecessary call to memset, which
zero out the key to HASH_ADD.
it is unnecessary because it is followed by a call to memcpy
and the source of the copy has been zeroed out.
> prov/efa: remove unnecessary memset

- include/ofi_shm.h
- prov/shm/src/smr.h
- prov/shm/src/smr_av.c
- prov/shm/src/smr_ep.c
- prov/util/src/util_shm.c
av_lookup was not working properly because it was returning the ep->region name,
not the name in the AV. This causes an issue if the EP has not been mapped yet.
since av_insert can succeed without the peer being mapped yet, av_lookup should
do the same.
This exposed other issues with address name storage inconsistencies. The name being
returned in fi_info->dst_addr/src_addr include the smr_prefix which means they
are being inserted into the AV with those prefixes. However, they were being
stored in the ep without the prefix, since the shm region name does not include
the prefix. This is confusing and causes issues.
This patch moves the prefix elimination to the shm util code since the only reason
it is being removed is because shm regions cannot have '/'s in them. All references
to the EP …
> prov/shm: fix av_lookup

- prov/verbs/src/fi_verbs.c
- prov/verbs/src/fi_verbs.h
- prov/verbs/src/verbs_eq.c
Do not fail a connection just because we can't override
the default rnr value.  This avoids a failure when running
over hnr HCAs.
> prov/verbs: Treat setting RNR as non-fatal

- .github/workflows/pr-ci.yml
This commit adds a new Github Action to take the place of the test
matrix we had with Travis CI. Turns out, Github also provides two
different MacOS runners, so I have included that here as a separate
build job with a basic sanity check build.
---
Example build: https://github.com/rajachan/libfabric/actions/runs/985476987 (or look at the action triggered by this PR)
> Github Action to test PRs against OS Matrix

- .github/workflows/pr-ci.yml
Two commits in this PR. One fixes the PSM3 build issue discussed in https://github.com/ofiwg/libfabric/pull/6896
The other adds clang builds to the matrix, which we had with the Travis setup. Noticed some non-trivial clang warnings with PSM3 (@acgoldma ) and EFA (@wzamazon).
With this, the only thing remaining is coverity. I have a patch for that too, but having trouble getting the script to pickup secrets needed to push results to coverity. Will look at it another day.
> ci: Add back psm3 with dependencies and enable clang builds

- contrib/intel/jenkins/run.py
- contrib/intel/jenkins/runtests.py
- contrib/intel/jenkins/tests.py
mpi_stress is some non-standing internal test of unknown origin
with unknown support.  Remove it from the Intel CI.
Editor automatically fixed some end of line endings as a bonus.
> contrib/intel: Remove mpi_stress

- fabtests/common/shared.c
- fabtests/functional/bw.c
- fabtests/functional/cm_data.c
- fabtests/functional/inj_complete.c
- fabtests/functional/multi_ep.c
- fabtests/functional/multi_mr.c
- fabtests/functional/unexpected_msg.c
- fabtests/include/shared.h
- fabtests/ubertest/verify.c
Current fill/check functions check directly from a buffer.
If the buffer is on the device, it will fail.
To fix this you must copy the buffer from the device to the host before
checking and vice-versa for filling.
> fabtests/hmem: Add device validation

- Makefile.am
- include/ofi_hmem.h
- include/ofi_mr.h
- libfabric.vcxproj
- libfabric.vcxproj.filters
- man/fi_mr.3.md
- prov/util/src/util_mem_monitor.c
- prov/util/src/util_mr_cache.c
- prov/util/src/ze_mem_monitor.c
- prov/verbs/src/verbs_domain.c
- src/hmem_ze.c
Implement the required memory monitor funcitons for buffers allocated
with the oneAPI L0 (ZE) API. Enable MR caching for such buffers in the
verbs provider. Update the man page accordingly.
> util/mr_cache: Add memory monitor for ZE

- fabtests/Makefile.am
- fabtests/common/shared.c
- fabtests/functional/rdm_multi_client.c
- fabtests/include/shared.h
- fabtests/man/fabtests.7.md
- fabtests/man/man1/fi_rdm_multi_client.1
- fabtests/scripts/runfabtests.sh
- fabtests/test_configs/efa/efa.exclude
- fabtests/test_configs/psm2/psm2.exclude
This PR adds a new test `fi_rdm_multi_client`
This program tests the functionality of RDM endpoint in the case that a persistent server does ping-pong with multiple clients that come and leave in sequence. The client connects to a server, sends ping-pong, disconnects with the server by cleaning all fabric resources, and repeats. It will re-use the first client's address for the subsequent clients if the `fi_setname` API is implemented for the tested provider.
> fabtests: Add fi_rdm_multi_client test

- util/pingpong.c
fi_pingpong_dgram() call fi_recv to pre-post a buffer.
Currently, the buffer size in the call to fi_recv is wrong because
it did not include rx_prefix_size and did not conider max control
message size.
This patch address the issue.
> util/pingpong.c: fix the call to fi_recv in fi_pingpong_dgram

- prov/efa/src/efa.h
- prov/efa/src/efa_av.c
- prov/efa/src/efa_msg.c
- prov/efa/src/efa_rma.c
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_atomic.c
- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_cmd.h
- prov/efa/src/rxr/rxr_pkt_type_data.c
- prov/efa/src/rxr/rxr_pkt_type_misc.c
- prov/efa/src/rxr/rxr_pkt_type_req.c
- prov/efa/src/rxr/rxr_read.c
- prov/efa/src/rxr/rxr_read.h
- prov/efa/src/rxr/rxr_rma.c
This PR contains a series of patches that handles the case of a peer was removed from address vector.
> prov/efa: handle removed peer

- fabtests/scripts/runfabtests.sh
Some fabtests are run in server/client mode. In non-strict
mode, if both server and client returning FI_ENODATA or
or FI_ENOSYS, the test is marked as 'Notrun' instead of
'Fail'.
Currently, when the client exits with non-zero code, the
server is immediately killed. However, doing such might
make the test that's supposed to be 'Notrun' to be
reported as 'Fail', because there's no guarantee
that the server has already exited. Killing the server
while it's running will change its return code.
Fix the issue by leaving the server more time (sleep 2s)
to exit.
> fabtests: Do not immediately kill server process

- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_atomic.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_pkt_entry.c
- prov/efa/src/rxr/rxr_read.c
- prov/efa/src/rxr/rxr_rma.c
Each provider defines its own descriptor format. When EFA
uses shm provider to send data, it passes EFA's descritpor
to shm provider, which shm provider does not understand.
This patch addresses the issue by adding a function to
convert EFA's descriptor to SHM's descriptor, and pass
it to shm provider when calling shm's send.
(cherry picked from commit 011856f15d7f4bee042937a0ce95dd5be6f4c402)
> [v1.12.x] prov/efa: use correct descriptor for shm provider's send

- fabtests/scripts/runfabtests.sh
Some fabtests are run in server/client mode. In non-strict
mode, if both server and client returning FI_ENODATA or
or FI_ENOSYS, the test is marked as 'Notrun' instead of
'Fail'.
Currently, when the client exits with non-zero code, the
server is immediately killed. However, doing such might
make the test that's supposed to be 'Notrun' to be
reported as 'Fail', because there's no guarantee
that the server has already exited. Killing the server
while it's running will change its return code.
Fix the issue by leaving the server more time (sleep 2s)
to exit.
(cherry picked from commit 4a79edee7c27b0a26f53c64ab5140f0bb7216696)
> [v1.12.x] fabtests: Do not immediately kill server process

- fabtests/scripts/runfabtests.sh
Some fabtests are run in server/client mode. In non-strict
mode, if both server and client returning FI_ENODATA or
or FI_ENOSYS, the test is marked as 'Notrun' instead of
'Fail'.
Currently, when the client exits with non-zero code, the
server is immediately killed. However, doing such might
make the test that's supposed to be 'Notrun' to be
reported as 'Fail', because there's no guarantee
that the server has already exited. Killing the server
while it's running will change its return code.
Fix the issue by leaving the server more time (sleep 2s)
to exit.
(cherry picked from commit 4a79edee7c27b0a26f53c64ab5140f0bb7216696)
> [v1.11.x] fabtests: Do not immediately kill server process

- prov/efa/configure.m4
- prov/efa/src/efa.h
- prov/efa/src/efa_domain.c
- prov/efa/src/rxr/rxr_init.c
This commit adds:
- autoconf to detect the existance of ibv_is_fork_initialized in
rdma-core
- updates efa_check_fork_enabled to use ibv_is_fork_initialized if
available
- uses ibv_is_fork_initialized to disable fork support when it returns
IBV_FORK_UNNEEDED
- Updates comments/help messages
> prov/efa: Use ibv_is_fork_initialized in EFA fork support

- prov/efa/src/efa.h
- prov/efa/src/efa_av.c
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_entry.c
- prov/efa/src/rxr/rxr_pkt_entry.h
- prov/efa/src/rxr/rxr_pkt_type_misc.c
- prov/efa/src/rxr/rxr_read.c
This PR contains commits that would make efa_av_remove to remove a peer with resources, instead of return -FI_EBUSY. This is to conform with the libfabric standard.
For that to work, this PR also contain commits that handle outstanding TX packets when removing a peer.
> pro/efa: efa_av_remove() remove peer and release resources

- util/pingpong.c
Add option '-6' to use IPv6 address instead of the default IPv4 address.
The server and client must use the same option.
Add debug output showing the address being connected to.
> util/pingpong: Add IPv6 support

- fabtests/benchmarks/dgram_pingpong.c
- fabtests/benchmarks/rdm_cntr_pingpong.c
- fabtests/benchmarks/rdm_pingpong.c
- fabtests/benchmarks/rdm_tagged_bw.c
- fabtests/benchmarks/rdm_tagged_pingpong.c
- fabtests/common/shared.c
The address format can be specified with the "-F" option, which is checked with
strncasecmp() in a predfined order. Previously the "fi_sockaddr_in" format was
checked before the "fi_sockaddr_in6" format, resulting the latter never being
reached. Fix by reversing the order of the two.
In addtion, the option was previously used by only 3 tests: "fi_msg_pingpong",
"fi_msg_bw" and "fi_rma_bw". Now expand the support to all the tests under the
"benchmark" directory.
> fabtests: Bug fixes related to IPv6 address format

- configure.ac
- src/hmem_ze.c
Add configure option '--enable-ze-dlopen' which, when set to true, lets
the ZE library be loaded with dlopen() instead of becoming a runtime
dependency of libfabric.so. This allows libfabric to be built with
ZE support and still be able to run on systems that don't have the ZE
library installed.
Similar work has already been done with hmem/cuda and hmem/rocr.
Fix #6915
> hmem/ze: Enable loading ZE library with dlopen()

- fabtests/test_configs/efa/efa.exclude
This patch enable av_xfer test for efa provider because
OOB address exchange has been supported and this test
works for EFA provider.
> prov/efa: include av_xfter test for efa provider

- fabtests/scripts/runfabtests.sh
Some fabtests are run in server/client mode. In non-strict
mode, if both server and client returning FI_ENODATA or
or FI_ENOSYS, the test is marked as 'Notrun' instead of
'Fail'.
Currently, when the client exits with non-zero code, the
server is immediately killed. However, doing such might
make the test that's supposed to be 'Notrun' to be
reported as 'Fail', because there's no guarantee
that the server has already exited. Killing the server
while it's running will change its return code.
Fix the issue by leaving the server more time (sleep 2s)
to exit.
(cherry picked from commit 4a79edee7c27b0a26f53c64ab5140f0bb7216696)
> [v1.13.x] fabtests: Do not immediately kill server process

- prov/efa/configure.m4
- prov/efa/src/efa.h
- prov/efa/src/efa_domain.c
- prov/efa/src/rxr/rxr_init.c
This commit adds:
- autoconf to detect the existance of ibv_is_fork_initialized in
rdma-core
- updates efa_check_fork_enabled to use ibv_is_fork_initialized if
available
- uses ibv_is_fork_initialized to disable fork support when it returns
IBV_FORK_UNNEEDED
- Updates comments/help messages
> [1.13.x] prov/efa: Use ibv_is_fork_initialized in EFA fork support

- prov/efa/configure.m4
- prov/efa/src/efa.h
- prov/efa/src/efa_domain.c
- prov/efa/src/rxr/rxr_init.c
This commit adds:
- autoconf to detect the existance of ibv_is_fork_initialized in
rdma-core
- updates efa_check_fork_enabled to use ibv_is_fork_initialized if
available
- uses ibv_is_fork_initialized to disable fork support when it returns
IBV_FORK_UNNEEDED
- Updates comments/help messages
> [1.12.x] prov/efa: Use ibv_is_fork_initialized in EFA fork support

- prov/efa/configure.m4
- prov/efa/src/efa.h
- prov/efa/src/efa_domain.c
- prov/efa/src/rxr/rxr_init.c
This commit adds:
- autoconf to detect the existance of ibv_is_fork_initialized in
rdma-core
- updates efa_check_fork_enabled to use ibv_is_fork_initialized if
available
- uses ibv_is_fork_initialized to disable fork support when it returns
IBV_FORK_UNNEEDED
- Updates comments/help messages
> [1.11.x] prov/efa: Use ibv_is_fork_initialized in EFA fork support

- prov/efa/src/efa_msg.c
Currently, the IBV_SEND_INLINE flag was added when
FI_INJECT flag is used. This is inappropriate for
two reasons:
First, IBV_SEND_INLINE requires message size to
be less than or equal to maximum inline size, but
there is no check for that.
Second, IBV_SEND_INLINE is different from inject
because inject means no CQ entry, but using IBV_SEND_INLINE
still generates an CQ entry.
This patch change it to that the IBV_SEND_INLINE flag
is used when the message size is less than or equal to
maximum inline size.
> prov/efa: use IBV_SEND_INLINE when message size fits

- include/ofi_recvwin.h
This patch introduces a new function ofi_recvwin_id_processed(),
which check whether an ID has been processed.
This function uses ofi_val32_gt() and ofi_val64_gt() instead of ">"
to compare two msg_id because the two functions are capable of
handling wrap around cases.
> prov/efa: add function ofi_recvwin_id_processed()

- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_av.c
- prov/rxm/src/rxm_conn.c
- prov/rxm/src/rxm_ep.c
First, address an issue where we weren't comparing the correct address structure (thanks @aingerson)
This exposed an issue, which causes problems at shut down, in loopback tracking and clean up. We were losing track of the recipient side of a loopback connection and not closing and releasing them as we should have been.
> prov/rxm: minor fixes to connection management

- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_msg.c
- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_entry.c
- prov/efa/src/rxr/rxr_pkt_type_misc.c
defer memory allocation to 1st call of the progress engine
> prov/efa: defer memory allocation to 1st call of the progress engine

- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_init.c
Currently, the unexpected packet pool chunk size is the same
with the rx entry pool (8192). Tests have shown that a chunk
size of 1024 can cover majority of use case.
Regression test on 1152 processes also shows that this smaller size
improves the performance of non-blocking collective MPI
benchmarks iallgather, iallgatherv, ialltoall, ialltoallv.
> prov/efa: adjust unexpected packet pool chunk size

- prov/efa/src/efa_msg.c
We encoutered some issues adding enabling IBV_INLINE_SEND.
Therefore this patch disables the usage of IBV_INLINE_SEND,
it will be reverted once the underlying issue has been fixed.
> prov/efa: temporarily disable the usage of IBV_INLINE_SEND

- prov/shm/src/smr_progress.c
Backport #6948, does not include first commit from that as it is not applicable
> [v1.11.x] prov/shm: Fixup progress return values, buffer overrun

- include/rdma/fi_errno.h
- man/fi_domain.3.md
- src/fabric.c
Add a new error code for receiver not ready errors and update the man page discussing this error.
> fi_errno.h: define new RNR error FI_ENORX 

- prov/efa/src/rxr/rxr_pkt_cmd.c
Return FI_ENORX when resource management is disabled and an RNR error occurs.
I'll follow up with another PR soon to improve the error handling for the rest of the errors that can happen here.
Depends on PR #6967
> prov/efa: return FI_ENORX for applicable RNR errors

- fabtests/common/hmem_ze.c
- fabtests/configure.ac
Remove forced runtime dependency on libze_loader.so when ZE support
is enabled.
CUDA and ROCR support have already used dlopen.
> fabtests: Use dlopen to load ZE library

- prov/util/src/util_mem_monitor.c
The import monitor was never initialized which would cause a segfault
when trying to utilize the dlist entry.
> prov/util: Initialize the import monitor

- prov/util/src/util_mem_monitor.c
The import monitor could have already been imported by the time the
monitors have been initialized. Do not set impmon.impfid to NULL to
avoid this case.
> prov/util: Do not set impmon.impfid to NULL on monitor init

- prov/util/src/util_mem_monitor.c
The import monitor could have already been imported by the time the
monitors have been initialized. Do not set impmon.impfid to NULL to
avoid this case.
(cherry picked from commit 0b0839e87e106f5fee55e5b3894d7fcafc57ba67)
> [v1.13.x] prov/util: Do not set impmon.impfid to NULL on monitor init

- prov/util/src/util_mem_monitor.c
The import monitor may already be set at this point, do not override the
monitor if this is the case.
> prov/util: Do not override default monitor if already set

- prov/util/src/util_mem_monitor.c
The import monitor may already be set at this point, do not override the
monitor if this is the case.
(cherry picked from commit 5f611de6ae67fb2dea8c953d715af1716a4af5ce)
> [v1.13.x] prov/util: Do not override default monitor if already set

- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_pkt_cmd.c
This PR backports the commits in https://github.com/ofiwg/libfabric/pull/6992/commits to v1.13.x branch
> [v1.13.x] prov/efa: fix rnr deadlock

- include/ofi_hmem.h
- man/fabric.7.md
- prov/shm/src/smr.h
- prov/shm/src/smr_ep.c
- prov/shm/src/smr_msg.c
- prov/shm/src/smr_progress.c
- prov/shm/src/smr_rma.c
- src/hmem.c
- src/hmem_cuda.c
This PR:
- Adds a new function to the HMEM interface - `is_ipc_enabled`
- introduces an HMEM IPC protocol into the shm provider based on the `get/open/close_handle` and `is_ipc_enabled` functions in the hmem interface. This uses the existing `smr_progress_ipc` function used by Ze, but as it is not based on dma-buf there is a new `smr_format_ipc` function added.
- Implements the necessary functions for IPC in the CUDA HMEM interface
The cuda `get/open_handle` functions have a very high overhead, about 750us total, so IPC handle caching would be a very useful addition in the future.
> hmem, prov/shm: Generic HMEM IPC protocol using get/open/close_handle, implemented those funcs for CUDA

- v1.10.0/man/index.md
- v1.10.1/man/index.md
- v1.11.0/man/index.md
- v1.11.1/man/index.md
- v1.11.2/man/index.md
- v1.12.0/man/index.md
- v1.12.1/man/index.md
- v1.13.0/man/index.md
- v1.13.1/man/index.md
The entry for fabtests man page was placed at the same level as the category.
> gh-pages: Fix indentation of man page index for v1.10.0 to v1.13.1

- prov/efa/Makefile.include
- prov/efa/src/efa.h
- prov/efa/src/rxr/rdm_proto_v4.h
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_pkt_type.h
- prov/efa/src/rxr/rxr_pkt_type_data.c
- prov/efa/src/rxr/rxr_pkt_type_misc.c
- prov/efa/src/rxr/rxr_pkt_type_req.h
This patch moves all constants, flags, and data structures in
protocol v4 to a separate header file rdm_proto_v4.h.
This is to separate protocol definition and implementation.
> prov/efa: move protocol v4 definition to a separate header file

- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_type_req.c
- prov/efa/src/rxr/rxr_read.c
This PR fixes several bugs for data copy on receiver side in FI_MSG_PREFIX mode
Test: 
1. ran fabtests with `-k -v` (enforce prefix mode and data corruption for efa)
2. ran `fi_rdm_tagged_bw -k -v` with device on server side and host on client side to test the local read path.
> prov/efa: Fix the mishandling of prefix size when receiving data

- prov/efa/src/rxr/rxr_pkt_type_req.c
The function rxr_pkt_req_data_from_tx() prepares a REQ packet
to be sent. It can either use the application's sending
buffer directly, or copy data from application's buffer to
packet entry.
Using application's sending buffer is preferred but certain
conditions must be met.
One of the conditions is the application's data must be
in one IOV. This is because EFA device supports sending 2 IOV
at a time, and EFA provider uses 1 IOV for packet header.
The bug is with the checking of this condition, the checking
should have been
"offset + total_data_size <= iov_length",
but is currently.
"offset + total_data_size < iov_length"
Which caused unnecessary copy.
> prov/efa: fix a bug that caused unnecessary copy

- prov/efa/src/rxr/rxr_pkt_type_req.c
The function rxr_pkt_req_data_from_tx() prepares a REQ packet
to be sent. It can either use the application's sending
buffer directly, or copy data from application's buffer to
packet entry.
Using application's sending buffer is preferred but certain
conditions must be met.
One of the conditions is the application's data must be
in one IOV. This is because EFA device supports sending 2 IOV
at a time, and EFA provider uses 1 IOV for packet header.
The bug is with the checking of this condition, the checking
should have been
"offset + total_data_size <= iov_length",
but is currently.
"offset + total_data_size < iov_length"
Which caused unnecessary copy.
(cherry picked from commit a1d272ecbce24ffcf63b0a72edde9e46a6ae38d8)
> [v1.11.x] prov/efa: fix a bug that caused unnecessary copy

- prov/efa/src/rxr/rxr_pkt_type_req.c
The function rxr_pkt_req_data_from_tx() prepares a REQ packet
to be sent. It can either use the application's sending
buffer directly, or copy data from application's buffer to
packet entry.
Using application's sending buffer is preferred but certain
conditions must be met.
One of the conditions is the application's data must be
in one IOV. This is because EFA device supports sending 2 IOV
at a time, and EFA provider uses 1 IOV for packet header.
The bug is with the checking of this condition, the checking
should have been
"offset + total_data_size <= iov_length",
but is currently.
"offset + total_data_size < iov_length"
Which caused unnecessary copy.
(cherry picked from commit a1d272ecbce24ffcf63b0a72edde9e46a6ae38d8)
> [v1.13.x] prov/efa: fix a bug that caused unnecessary copy

- prov/efa/src/rxr/rxr_pkt_type_req.c
The function rxr_pkt_req_data_from_tx() prepares a REQ packet
to be sent. It can either use the application's sending
buffer directly, or copy data from application's buffer to
packet entry.
Using application's sending buffer is preferred but certain
conditions must be met.
One of the conditions is the application's data must be
in one IOV. This is because EFA device supports sending 2 IOV
at a time, and EFA provider uses 1 IOV for packet header.
The bug is with the checking of this condition, the checking
should have been
"offset + total_data_size <= iov_length",
but is currently.
"offset + total_data_size < iov_length"
Which caused unnecessary copy.
(cherry picked from commit a1d272ecbce24ffcf63b0a72edde9e46a6ae38d8)
> [v1.12.x] prov/efa: fix a bug that caused unnecessary copy

- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_type_req.c
- prov/efa/src/rxr/rxr_read.c
Currently, the msg prefix size is not included in the offsets
of data copies on the receiver side, which causes data corruptions when
FI_MSG_PREFIX is specified in hint->mode. This patch expands the truncation
size of rx / read entries to include the prefix size, and shift the
offset of local iov accordingly.
(cherry picked from commit f6504bc898f21baf4ff8bcb5fbe8ce94788aa3f4)
> [v1.13.x] prov/efa: Fix the mishandling of prefix size when receiving data

- util/pingpong.c
> util/pingpong.c: fix a bug in pp_alloc_active_res

- fabtests/benchmarks/rdm_pingpong.c
- fabtests/benchmarks/rdm_tagged_bw.c
- fabtests/benchmarks/rdm_tagged_pingpong.c
Currently, rdm_pingpong, rdm_tagged_bw, rdm_tagged_pingpong
hard-coded hints->mode as FI_CONTEXT after parsing the options.
This will override the modification of hints->mode in some
benchmark options like `-k`, which enforce the msg prefix mode
by doing "hints->mode |= FI_MSG_PREFIX".
> fabtests/benchmarks: Enable modifying hints->mode by options.

- fabtests/test_configs/efa/efa.exclude
This test suite is excluded in current efa test config,
which causes a gap in the test for cases that FI_MSG_PREFIX
is specified in hints->mode.
> fabtests: Enable rdm ep prefix mode test for EFA provider.

- fabtests/common/shared.c
- fabtests/functional/rdm_atomic.c
- fabtests/functional/rdm_multi_client.c
- fabtests/include/shared.h
A couple of fabtests are not calling ft_init, specifically the atomic
tests and rdm multi client test. Those tests use the general memory
allocation path and argument parsing so it is possible for them to call
hmem alloc without calling hmem init. Add calls to ft_init so hmem is
initialized.
Test description: Ran efa/tcp fabtests.
> fabtests: add missing ft_init calls for hmem init

- prov/efa/src/efa.h
- prov/efa/src/efa_fabric.c
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_init.c
Since the efa_fabric and rxr_fabric functionality was squashed a while back,
this variable was redundant and added to unnecessary code complexity.
This change simplifies the code by removing this variable and replacing
with existing functionality as needed. Going forward this will make the code
easier to understand and maintain.
> prov/efa: Remove redundant variable "lower_efa_prov".

- prov/efa/src/rxr/rxr_init.c
If our max message size was set low enough, we could attempt to set a
size_t to a negative value, causing segfaults.
> prov/efa: bugfix: Never set a negative inject size

- util/pingpong.c
> [v1.12.x] util/pingpong.c: fix a bug in pp_alloc_active_res

- prov/efa/docs/efa_rdm_protocol_v4.md
In efa_rdm_protocol_v4.md, the ID of section "handshake protocol
and raw address exchange" should be 2.2, but is currently listed
as 3.2.
> prov/efa: fix an error in section ID in efa_rdm_protocol_v4.md

- util/pingpong.c
> [v1.13.x] util/pingpong.c: fix a bug in pp_alloc_active_res

- util/pingpong.c
> [v1.11.x] util/pingpong.c: fix a bug in pp_alloc_active_res

- prov/efa/src/rxr/rxr_init.c
There were some bugs in the code path and after some review it was
determined that from a user perspective, this environment variable does
not have a lot of value. Thus we remove this variable from usage.
> prov/efa: Remove FI_EFA_SHM_MAX_MEDIUM_SIZE env variable

- fabtests/scripts/runfabtests.sh
This PR backports https://github.com/ofiwg/libfabric/pull/6052 and https://github.com/ofiwg/libfabric/pull/6054 to v1.9.x branch. It adds a check for the availability of python command (and its variants: python2, python3) before running tests. This will guarantee the error code will not mess up when the default `python` command is not available on the system.
> [v1.9.x] Add check for python in runfabtests.sh

- fabtests/scripts/runfabtests.sh
This PR backports https://github.com/ofiwg/libfabric/pull/6052 and https://github.com/ofiwg/libfabric/pull/6054 to v1.10.x branch. It adds a check for the availability of python command (and its variants: python2, python3) before running tests. This will guarantee the error code will not mess up when the default `python` command is not available on the system.
> [v1.10.x] Add check for python in runfabtests.sh

- prov/efa/src/efa_fabric.c
The efa provider was freeing resources upon error that fi_freeinfo later also
frees. This was causing a double free error when the efa info was being
requested, and efa_get_addr failed. This removes the efa frees to info
resources upon error, and instead lets fi_freeinfo handle cleaning up the info
struct.
Signed-off-by: Nikola Dancejic <dancejic@amazon.com>
> prov/efa: Fixing double free in efa provider error path.

- util/pingpong.c
> [v1.10.x] util/pingpong.c: fix a bug in pp_alloc_active_res

- util/pingpong.c
> [v1.9.x] util/pingpong.c: fix a bug in pp_alloc_active_res

- fabtests/benchmarks/rdm_pingpong.c
- fabtests/benchmarks/rdm_tagged_bw.c
- fabtests/benchmarks/rdm_tagged_pingpong.c
This PR backports https://github.com/ofiwg/libfabric/pull/7013 to v1.13.x branch
> [v1.13.x] fabtests/benchmarks: Enable modifying hints->mode by options.

- fabtests/benchmarks/rdm_pingpong.c
- fabtests/benchmarks/rdm_tagged_bw.c
- fabtests/benchmarks/rdm_tagged_pingpong.c
This PR backports https://github.com/ofiwg/libfabric/pull/7013 to v1.12.x branch
> [v1.12.x] fabtests/benchmarks: Enable modifying hints->mode by options.

- fabtests/benchmarks/rdm_pingpong.c
- fabtests/benchmarks/rdm_tagged_bw.c
- fabtests/benchmarks/rdm_tagged_pingpong.c
This PR backports https://github.com/ofiwg/libfabric/pull/7013 to v1.11.x branch
> [v1.11.x] fabtests/benchmarks: Enable modifying hints->mode by options.

- fabtests/benchmarks/rdm_pingpong.c
- fabtests/benchmarks/rdm_tagged_bw.c
- fabtests/benchmarks/rdm_tagged_pingpong.c
This PR backports https://github.com/ofiwg/libfabric/pull/7013 to v1.9.x branch
> [v1.9.x] fabtests/benchmarks: Enable modifying hints->mode by options.

- prov/netdir/src/netdir_ndinit.c
Standard C++ headers are only to be used for compiling C++
Fixes #7041
Signed-off-by: Casey Carter <cacarter@microsoft.com>
> include <assert.h> instead of <cassert> in C file

- prov/efa/src/efa_av.c
- prov/efa/src/efa_fabric.c
- prov/efa/src/efa_mr.c
- prov/efa/src/rxr/rxr_domain.c
There are currently a couple of places where a global variable is used
to control whether or not shared memory is used for intranode
communnication. This can be dangerous if for some reason this gets
out of sync with the actual underlying structures.
This patch changes things to that we primarily check the underlying
structures, and only set those after checking the global variable
once. There are some occurances where making this change isn't
possible but for the most part this patch makese these checks more
defensive.
Also, in some places the check on the global variable is redundant
and any inconsistency would represent an error state, so these checks
were changes to asserts.
> prov/efa: Adding some checking around enabled shared memory transfers

- prov/rxm/src/rxm_conn.c
- prov/rxm/src/rxm_ep.c
- prov/tcp/src/tcpx_ep.c
Should fix #6942
The tcp provider was ignoring the src_addr when creating an active ep.  The result was that the socket would select a src address based on the destination address passed into connect().  This would result in the connection using the wrong src address which would fail tag matching with src addressing.
Modify the rxm provider to reset the src_addr after listening on the passive ep.  This fixes the possibility of using the wrong src_addr in the case where the app calls fi_setname() on the rdm ep.
> rxm/tcp: Ensure that connections use the correct source address

- prov/efa/src/rxr/rxr_ep.c
rxr_ep_check_available_data_bufs_timer() checks and updates
ep->available_data_bufs in progress engine, if it has not been updated.
This patch moved it to after rxr_ep_progress_post_internal_rx_pkts(),
because rxr_ep_progress_post_internal_rx_pkts() will update
ep->available_data_bufs.
> prov/efa: adjust the sequence of rxr_ep_check_available_data_bufs_timer

- fabtests/multinode/src/core.c
Problem reported by asan.  There's no reason to call malloc for
a 24 byte structure.  Just declare it on the stack and avoid
malloc failure checks and free.
> fabtests/multinode: Fix memory leak in multi_setup_fabric

- prov/tcp/src/tcpx.h
- prov/tcp/src/tcpx_conn_mgr.c
- prov/tcp/src/tcpx_ep.c
If an endpoint is closed during the middle of trying to
establish a connection, the associated cm_ctx may be left
dangling.  This happens when rxm identifies peer connections
and aborts one side.
To resolve, maintain a reference to the cm_ctx from the ep
while the cm_ctx is valid.  When closing the ep, free the
cm_ctx if it is still valid.
> prov/tcp: Fix possible memory leak of cm_ctx

- include/ofi_hmem.h
- prov/util/src/util_mem_monitor.c
- src/hmem.c
Providers can use this to determine if hmem support is enabled for a
particular interface, and fail memory registration calls if it's not
supported.
> hmem: add function to get hmem iface initialization status

- prov/util/src/util_shm.c
The shm code assumes FI_ENOENT as the error code if the peer is not
initialized. The old code was using FI_ENOENT if the shm region did
not exist but then FI_EAGAIN if the shm existed but the peer has not
finish initializing, causing interpretation errors in the fi_av_insert
path.
> prov/shm: fix segfault and sigbus error if server is not initialized first

- man/fi_efa.7.md
- prov/efa/src/rxr/rxr_init.c
environment variable FI_EFA_SHM_MAX_MEDIUM_SIZE and then if they
have print an error before bailing.
We are now doing this to avoid the case where someone can silently
set this now-deprecated environment variable.
> prov/efa: Detect when the user sets the now-deprecated

- prov/efa/src/rxr/rxr_ep.c
This patch added a step to wait for queued/inflight send operations
to finish. This step is necessary because a peer might be waiting
for a packet from the endpoint.
This patch used a maxium wait time and set it to 10 second initially.
> prov/efa: wait for uncompleted send operations when closing endpoint

- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_pkt_cmd.c
Currently, the funciton rxr_cq_handle_rx_completion() takes an RX pkt_entry
as input and release is. This patch simplify the function by removing
the releasing of pkt_entry from it. The caller of this function will
release the RX pkt_entry.
> prov/efa: remove releasing of pkt_entry from rxr_cq_handle_rx_completion

- include/rdma/fi_ext.h
This patch allows exporting provider specific definitions to applications
Each provider can choose an unique provider code (12-bits) and define provider
specific values based on it.
> include: Export provider specific definition to application

- man/fi_efa.7.md
- prov/efa/src/efa.h
- prov/efa/src/efa_ep.c
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_ep.c
prov/efa: Allow apps to reset RNR retry counter 
This needs rebase after #7065 is merged.
Update: #7065 merged. This PR has been rebased.
> prov/efa: Allow apps to reset RNR retry counter

- prov/util/src/util_cq.c
msg rx flags should be FI_MSG | FI_RECV, not just FI_RECV
read rx flags should be FI_REMOTE_READ, not FI_READ
read tx flags should be FI_RMA | FI_READ not FI_RMA | FI_RMA
> prov/util: fix util cq flags

- include/ofi_hook.h
- prov/hook/src/hook_domain.c
The credit based flow control mechansim uses functions exported via
the fi_open_ops() interface to coordinate between the rxm and verbs
layers. There are two issues when a hook provider sits between rxm
and verbs:
(1) These exported functions expect verbs objects (ep, domain, etc),
but here the hook objects are passed in.
(2) The 'rxm_send_credits' call expects the ep passed in has 'rxm_conn'
as the fid context, but here the fid context contains the hook ep, and
'rxm_conn' resides in the fid context of the hook ep.
To fix these, the hook provider intercepts the flow control functions
and does necessary object mapping.
> prov/hook: Intercept fi_open_ops() to properly handle flow control ops

- prov/efa/src/rxr/rxr_ep.c
In rxr_ep_wait_send(), "finished" should be
!rxr_ep_has_unfinished_send(rxr_ep)
. However, the "!" was missing, which caused wrong
warning message to printed
This patch fixed the issue
> prov/efa: fix a bug in rxr_ep_wait_send

- prov/efa/src/efa.h
- prov/efa/src/efa_av.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_init.c
Currently, the function rxr_ep_addr_to_shm_name() and its
caller uses SHM_MAX_NAME to define the buffer size for the
shm endpoint name. This is unnecessary because the length
of shm endpoint name can be derived from the name format EFA
used.
This patch remove the usage of SHM_MAX_NAME and the inclusion
of ofi_shm.h in efa.
> prov/efa: remove usage of SHM_MAX_NAME

- prov/efa/src/efa.h
- prov/efa/src/efa_av.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_init.c
Currently, the function rxr_ep_addr_to_shm_name() and its
caller uses SHM_NAME_MAX to define the buffer size for the
shm endpoint name, which introduced a dependency on ofi_shm.h
This dependency is unnecessary because the length of shm endpoint
name can be derived from the name format EFA used.
This patch introduce a macro EFA_SHM_NAME_MAX, and used it
to replace the usage of SMR_NAME_MAX. It also removed the inclusion
of ofi_shm.h to remove the unnecessary dependency.
(cherry picked from commit 002205d6a0107a589f14347a850cc53d6682db47)
> [v1.13.x] prov/efa: remove usage of SMR_NAME_MAX

- prov/rxm/src/rxm_init.c
The rxm provider uses hmem ops for buffer copying, etc. When built
as a DL provider, ofi_hmem_init()/ofi_hmem_fini() should be called.
> prov/rxm: Add hmem initialization for DL build

- src/fabric.c
When loading DL providers from a directory, sort the entries in
alphabeta order so that the order of the providers being loaded
can be controlled by tweaking the file names.
> fabric: Sort DL providers in the same directory

- prov/efa/src/rxr/rxr_pkt_cmd.c
This patch added some comments to clarify the behavior of
rxr_pkt_entry_send(),
rxr_pkt_entry_inject() and
rxr_pkt_handle_send_cmopletion
regarding updating the outstanding TX ops counter in rxr_ep.
> prov/efa: add comments to clarify the behavior regarding TX op counter

- prov/rxm/src/rxm_init.c
> prov/rxm: Fix incorrect function name for hmem cleanup

- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_entry.c
The function rxr_ep_record_tx_op_submitted() should be called for
any TX operations that has successfully submitted to update TX
related counters. However, it is not called for inject operations,
which are also TX operations.
This patch address the issue by calling rxr_ep_record_tx_op_submitted()
in function rxr_pkt_entry_inject().
(cherry picked from commit 0d9b632d3d47a2784c119ff59c453a152760df8c)
> [v1.13.x] prov/efa: update TX counter for inject

- prov/verbs/src/verbs_dgram_ep_msg.c
- prov/verbs/src/verbs_msg.c
- prov/verbs/src/verbs_rma.c
Intel compiler 2018.3.222 generates errors when compiling verbs provider with
rdma-core 34.1:
prov/verbs/src/verbs_rma.c(170): error: a designator for an anonymous union
member can only appear within braces corresponding to that anonymous union
.imm_data = htonl((uint32_t)data)
It's a compiler specific limitation. Change to use assignment statement for
better compatibility.
> prov/verbs: Fix compilation error with anonymous union member initialization

- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_atomic.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_msg.c
- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_cmd.h
- prov/efa/src/rxr/rxr_rma.c
Currently, data packet are sent via `rxr_pkt_post_ctrl`, which call
rxr_pkt_entry_send with flags as 0. This is wrong because data packets
could be sent with FI_MORE to batch several sendings together and
improve performance. This patch fixes this issue and does some refactors:
1. Add flags as an argument of `rxr_pkt_post_ctrl` and let caller specify
the flags like FI_MORE directly.
2. Pass flags to `rxr_pkt_entry_send` correctly inside `rxr_pkt_post_ctrl_once`.
3. Remove the send_flags from `tx_entry`. It's not necessary to bind this flags
with a tx_entry as it's only used to define the additional flags for each pkt
send operations via `rxr_pkt_entry_send()`.
Test:
1. multi-node and single-node fabtests with efa provider
2. OMB pt2pt tests.
3. 32 c5n.18xlarge tests with OMB, IMB, HPCG, …
> prov/efa: Fix a bug in data packet send path and some refactors

- prov/rxm/src/rxm_cq.c
In the rxm_fake_rx_hdr function the rx_buf->pkt.ctrl_hdr.conn_id was
being incorrectly set to conn->remote_index. Since this interface is used
by the receiving side to support tcp optimizations for small messages
this value should be updated with the peer->index. The peer->index
is used to fetch the appropriate connection. Using the remote index
causes the connection lookup to fail.
This patch provides fix for PR 6682.
Signed-off-by: Nikhil Nanal<nikhil.nanal@intel.com>
> prov/rxm: Correcting the setting of conn_id in rx pkt control header

- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_av.c
- prov/rxm/src/rxm_conn.c
- prov/verbs/src/verbs_cm.c
- prov/verbs/src/verbs_ep.c
Fix for use-after-free in verbs provider handling fi_reject() after calling fi_endpoint() + fi_close(ep)
Added missing AV lock around AV data structures (addr_map, peer_pool, conn_pool) to avoid multi-threaded race issues.  AV problems could occur if there are multiple EPs bound to a single AV.
I am still analyzing serialization of the rxm_peer_addr structure when accessed via the rxm_conn structure.
> prov/rxm: Fix multi-threaded access to AV structures

- prov/rxm/src/rxm_cq.c
In the rxm_fake_rx_hdr function the rx_buf->pkt.ctrl_hdr.conn_id was
being incorrectly set to cm_handle->remote_key.Since this interface
is used by the receiving side to support tcp optimizations for small
messages this value should be updated with the cm_handle->key.In this
function the (local)key should be used to fetch the connections. Using
the remote index causes the connection lookup to fail sometimes.
This change is similar to the changes in the main branch,
commit id: 4de6fef248f8191d5a34a07554ee28b0c09ad231
> [v1.13.x] prov/rxm: Correcting setting of conn_id in rx pkt control hdr

- include/ofi_mr.h
- prov/util/src/util_mem_monitor.c
With multiple memory monitors, there is the possibility of having a
deadlock occur with start/stop being encapsulated within the rwlock. To
prevent this, we add a state lock and protect start/stop from each other
using this lock.
> prov/util: Add state lock for mem monitors start/stop

- prov/efa/src/rxr/rxr_pkt_entry.c
- prov/efa/src/rxr/rxr_pkt_entry.h
Copy unexpected messages out of the pre-posted buffer pool for the SHM
provider. Certain workloads can exhaust the SHM receive pool size of 1k on
unexpected messages which can cause application hangs.
This approach incurs an additional memory copy for SHM unexpected
messages, since SHM doesn't require memory to be registered, however,
this will potentially utilize less memory depending on the workload.
> prov/efa: copy unexpected messages out of pre-posted shm buffers

- prov/tcp/src/tcpx.h
- prov/tcp/src/tcpx_conn_mgr.c
- prov/tcp/src/tcpx_ep.c
If an application makes the following calling sequence, use-after-free is possible:
receive a connection request event (info->handle set)
fi_endpoint(... info->handle ...)
fi_close(ep)
fi_reject(info->handle)
This series updates the code to handle that calling sequence.  As part of the changes, it also removes a long-standing limitation where a wait set couldn't be shared between an EQ and CQ.
> prov/tcp: Fixes a possible race condition that can result in use-after-free

- src/hmem_ze.c
* Remove a duplicated code block.
* Fix two "variable may be used uninitialized" warnings.
> hmem/ze: A few minor fixes

- prov/efa/src/rxr/rxr_pkt_entry.c
- prov/efa/src/rxr/rxr_pkt_entry.h
Copy unexpected messages out of the pre-posted buffer pool for the SHM
provider. Certain workloads can exhaust the SHM receive pool size of 1k on
unexpected messages which can cause application hangs.
This approach incurs an additional memory copy for SHM unexpected
messages, since SHM doesn't require memory to be registered, however,
this will potentially utilize less memory depending on the workload.
(cherry picked from commit d9a805b67f1f7b8899f49f944b298d4ebf8d8cb5)
> [v1.13.x] prov/efa: copy unexpected messages out of pre-posted shm buffers

- include/rdma/fi_ext.h
When compiling with -Wpedantic, hit the following warnings.
```
warning: enumerator value for ‘FI_OPT_EFA_RNR_RETRY’ is not an integer
constant expression [-Wpedantic]
FI_OPT_EFA_RNR_RETRY = (1U | FI_PROV_SPECIFIC_EFA),
^
warning: ISO C restricts enumerator values to range of ‘int’ [-Wpedantic]`
```
This is because FI_PROV_SPECIFIC_EFA is defined as
(FI_PROV_SPECIFIC | 0xefa << 20). And it is not an integer constant
expression, since `0xefa << 20` overflows the 1 to the sign bit.
Fix by using 0xefaU and casting the enumerator value to int.
> include: Fix a compiler warning in fi_ext.h

- configure.ac
- include/ofi_atomic.h
- include/ofi_shm.h
- prov/util/src/util_atomic.c
- prov/util/src/util_shm.c
gcc/clang and libatomic can support 128-bit integer operations on
some platforms. If the compiler/library support is available, compile
128-bit atomic support in the util provider.
> prov/util Add support for 128-bit integer atomics

- prov/tcp/src/tcpx.h
- prov/tcp/src/tcpx_progress.c
- prov/tcp/src/tcpx_rma.c
Internal messages do not carry op_context and do not generate error messages to the cq.
Since the rma read control message did not have an op_context and was not marked
internal, it was causing a crash in RxM when errors were sent to the cq.
> prov/tcp: mark rma read control msg as internal

- prov/rxm/src/rxm_cq.c
- src/common.c
Extracting 2 commits from #7112, which should be safe to merge immediately.
> core + prov/rxm: skip calling gettime when result is ignored

- Makefile.am
- include/rdma/fabric.h
Update both the shared library version number and the version
reported by fi_version() for the 1.14 series.
Signed-off-by: Brian Barrett <bbarrett@amazon.com>
> Finish rolling to v1.14.0a1

- prov/efa/src/rxr/rxr_ep.c
Currently, rxr_ep_grow_rx_pkt_pools unconditionally grows
rx_ooo_pkt_pool and rx_unexp_pkt_pool. This is wrong because
these two pkt pools may not be created if user specifies
FI_EFA_RX_COPY_UNEXP=0 and FI_EFA_RX_COPY_OOO=0.
This patch grows these two pkt pools only when they are created,
in the similar pattern of rx_readcopy_pkt_pool.
Test: 
1. Run fabtests with FI_EFA_RX_COPY_UNEXP=0 and FI_EFA_RX_COPY_OOO=0.
2. Run osu micro-benchmarks with FI_EFA_RX_COPY_UNEXP=0 and FI_EFA_RX_COPY_OOO=0.
> prov/efa: Fix a bug in rxr_ep_grow_rx_pkt_pools.

- prov/efa/src/rxr/rxr_ep.c
This patch removed the maximum waiting time in rxr_ep_wait_send()
because all send operations should finish in finite time.
> prov/efa: remove maximum waiting time in rxr_ep_wait_send

- prov/efa/src/rxr/rxr_ep.c
Currently, rxr_ep_grow_rx_pkt_pools unconditionally grows
rx_ooo_pkt_pool and rx_unexp_pkt_pool. This is wrong because
these two pkt pools may not be created if user specifies
FI_EFA_RX_COPY_UNEXP=0 and FI_EFA_RX_COPY_OOO=0.
This patch grows these two pkt pools only when they are created,
in the similar pattern of rx_readcopy_pkt_pool.
(cherry picked from commit 2087db4859115533b596e3cb9c35e467094e8656)
> [v1.13.x] prov/efa: Fix a bug in rxr_ep_grow_rx_pkt_pools.

- fabtests/functional/av_xfer.c
This patch fixed an issue that when some tests failed, the result
"Failed\n" was not printed, which caused a new line is missing.
Signed-off-by: Yossi Leybovich <sleybo@amazon.com>
> fabtests/av_xfer: add missing print on failure

- prov/efa/src/rxr/rxr_ep.c
This patch removed the maximum waiting time in rxr_ep_wait_send().
In theory, all send operations should finish in finite time.
In the event a send operation cannnot complete, having
a maximum waiting time can cause a send operation to be
silently dropped, which is actually worse than keeping
the sending application hanging.
Because silently dropping a send operation can cause the
intended receiver to hang, which would be harder to
find root cause.
(cherry picked from commit 4658746c6f371c4078595380e52f55dc5a47f756)
> [v1.13.x] prov/efa: remove maximum waiting time in rxr_ep_wait_send

- prov/util/src/util_mem_hooks.c
Currently, we cannot detect if another application patches memory relating to how
we monitor memory registration. This change adds this functionality so that if
another application has patched the memory in the same way we'll detect it before
we patch it (again).
If this happens, the ofi_intercept_symbol() function will return FI_EALREADY
under this condition.
> prov/util: Add logic to detect previous memory patching

- fabtests/functional/av_xfer.c
This patch fixed an issue that when some tests failed, the result
"Failed\n" was not printed, which caused a mssiing new line.
Signed-off-by: Yossi Leybovich <sleybo@amazon.com>
(cherry picked from commit efb097ecb1d3f26a756882f03913072336c7435b)
> [v1.13.x] fabtests/av_xfer: add missing print on failure

- prov/efa/src/rxr/rxr_pkt_entry.c
Currently, rxr_pkt_entry_copy will copy the whole
packet entry, which is unnecessary because only
the first pkt_entry->pkt_size contains data.
> prov/efa: fix the memcpy size in rxr_pkt_entry_copy

- prov/efa/src/rxr/rxr_pkt_entry.c
Currently, rxr_pkt_entry_copy will copy the whole
packet entry, which is unnecessary because only
the first pkt_entry->pkt_size contains data.
(cherry picked from commit 8df97d7d61da73b4842c1d4fb3b6cb554bb594ef)
> [v1.13.x] prov/efa: fix the memcpy size in rxr_pkt_entry_copy

- prov/tcp/src/tcpx_cq.c
- prov/tcp/src/tcpx_progress.c
When receiving an RMA write with CQ data, we need to
add the FI_REMOTE_CQ_DATA flag to the completion to
indicate that the CQ data is valid.
> prov/tcp: Set FI_REMOTE_CQ_DATA flag on completions

- src/common.c
- src/fi_tostr.c
The fi_info field name is 'nic', not 'nic_fid' or 'fid_nic'.
The string is inconsistent and should match the name of the
field itself.
Update reporting bus_type field from bus_attr to match the
field name, dropping the fi_ prefix.
> core: Make output for printing fi_info fields consistent

- include/rdma/fi_endpoint.h
- man/fi_endpoint.3.md
Certain Libfabric applications (such as Open MPI) prefer that FI_HMEM transfers
should be attempted via other means if peer to peer device transfer support is
unavailable. Other applications (such as NVIDIA OFI NCCL plugin) only want
FI_HMEM transfers to occur via peer to peer transactions. Add a new endpoint
setopt option that allows applications to state this after selecting a provider
with FI_HMEM support.
> fi_endpoint: add a parameter to allow FI_HMEM p2p configuration

- prov/shm/src/smr_progress.c
This reverts commit cb4e2945a4c06c6a5e396759d7fbb99e058a2fc6.
CQ completions for RMA should only be written for operations carrying CQ data.
> Revert "prov/shm: Fix RMA completion reporting"

- prov/efa/src/efa_msg.c
This reverts commit 67179fe0d78f4dd7ef31349d5ee27807b3219870.
The commit was added because of some underlying issue with device.
The issue has been fixed, so revert the commit
> Revert "prov/efa: temporarily disable the usage of IBV_INLINE_SEND"

- fabtests/common/shared.c
This patch sets the FI_HMEM_DEVICE_ONLY flag if device memory
is used.
> shared/common : set FI_HMEM_DEVICE_ONLY flag for device memory

- fabtests/Makefile.am
- fabtests/man/fabtests.7.md
- fabtests/man/man1/fi_efa_ep_rnr_retry.1
- fabtests/prov/efa/Makefile.include
- fabtests/prov/efa/src/rdm_ep_rnr_retry.c
- fabtests/scripts/runfabtests.sh
This PR adds efa provider specific test `fi_efa_ep_rnr_retry` to test RNR retry count reset via fi_setopt.
It includes the following change  
1. Add efa specific test rdm_ep_rnr_retry.c.
This test resets the RNR retry count via fi_setopt, and then runs a simple program to test if the error cq entry (with error FI_ENORX) can be written to application, if RNR happens. To build the test, also add efa specific Makefile bits in fabtests/prov/efa/Makefile.include, which is included in the top level fabtests/Makefile.am.
2. Update man page for efa specific test
3. Modify runfabtests.sh to run efa provider specific test. Use -P to enable the run.
Testing:
Server:
```
[ec2-user@ip-172-31-41-93 ~]$ FI_EFA_ENABLE_SHM_TRANSFER=0  fi_efa_ep_rnr_retry -p "efa" -R 0  -E
Setting RNR retry count to 0 ... …
```
> fabtests: Add EFA-specific RNR retry test

- prov/tcp/src/tcpx.h
- prov/tcp/src/tcpx_cq.c
- prov/tcp/src/tcpx_msg.c
- prov/tcp/src/tcpx_progress.c
- prov/tcp/src/tcpx_rma.c
- prov/tcp/src/tcpx_shared_ctx.c
Separate CQ flags and control flags associated with data transfers into different separate fields.  Limit CQ flags to those flags defined as part of completion data.
Minor optimization to RMA receive handling to combine checks and loops.
> prov/tcp: Cleanup reporting of CQ flags and optimize RMA handling

- prov/efa/src/efa.h
- prov/efa/src/efa_av.c
- prov/efa/src/efa_cq.c
- prov/efa/src/rxr/rxr_ep.c
This patch split reverse_av into two separate reverse AVs:
cur_reverse_av is a map between (ahn + qpn) and current efa_conn
prv_reverse_av is a map between (ahn + qpn + qkey) and all previous
efa_conns.
prv_reverse_av is used only by rdm endpoint.
cur_reverse_av's key size is smaller thus the search on it is faster.
For dgram endpoint, only cur_reverse_av is searched.
For rdm endpoint, we first search cur_reverse_av, and only when the
current efa_conn's connid does not match connid in packet (which is
less likely to happen), will we search prv_reverse_av. This will
improve the performance.
> prov/efa: split reverse_av into cur_reverse_av and prv_reverse_av

- .github/workflows/stale.yml
Update the configuration of the stale action:
(1) Revise the comment message for marking an issue/pr stale;
(2) Increase the number of operations per run from default 30 to 60 to cover all existing issues
(3) Add a few labels that can exempt an issue/pr from being marked stale 
Signed-off-by: Jianxin Xiong \<jianxin.xiong@intel.com\>
> workflow: Update stale.yml

- include/ofi_hmem.h
- man/fi_endpoint.3.md
- man/fi_mr.3.md
- src/hmem.c
Add an environment variable that users can set to notify Libfabric that p2p
should not be used. The FI_OPT_FI_HMEM_P2P setopt option provides additional
flexibility over this environment variable.
> core/hmem: add a new environment variable to disable FI_HMEM p2p

- prov/efa/src/rxr/rxr_init.c
Fail FI_HMEM support when the FI_HMEM_DISABLE_P2P env is set to true. A future patch series will add support to the EFA provider so that it can fallback to copies.
> prov/efa: fail FI_HMEM support when p2p is disabled

- .github/workflows/stale.yml
Option names use dash instead of underscore.
> workflow: Fix a typo in stale.yml

- src/hmem_cuda.c
- src/hmem_ze.c
Use the new FI_HMEM_DISABLE_P2P environment variable to disable cuda/ze IPC
when this option is turned on, and by proxy not use ipc in the shm provider.
> hmem: disable cuda/ze IPC if p2p is disabled

- prov/psm3/src/psmx3_attr.c
Fail FI_HMEM support when the FI_HMEM_DISABLE_P2P env is set to true.
> prov/psm3: fail FI_HMEM support if p2p is disabled

- prov/rxm/src/rxm_init.c
There are some paths that require p2p, so fail FI_HMEM support if the
environment variable is set to disable p2p.
> prov/rxm: fail FI_HMEM support if p2p is disabled

- prov/efa/src/efa_av.c
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_init.c
Currently, when calling fi_setname on shm provider, the whole buffer
length (EFA_SHM_NAME_MAX) is used as name length. The name for
shm provider is set by function rxr_ep_addr_to_smr_name(), which
did not use the whole buffer.
This patch makes rxr_ep_addr_to_smr_name() to return number of
bytes it wrote, and use it to call fi_setname to be more precise.
> prov/efa: call fi_setname on shm with actual name length

- prov/rxm/src/rxm_conn.c
If we receive a connection failure from verbs, reset
the conn object, so that a subsequent attempt can try
again.
> prov/rxm: Handle connection failures from verbs

- prov/verbs/src/verbs_info.c
Fail FI_HMEM support when the FI_HMEM_DISABLE_P2P env is set to true.
> prov/verbs: fail FI_HMEM support if p2p is disabled

- prov/psm3/Makefile.include
VERSION file is missing from dist.
fixes: #7042 
> prov/psm3: Add VERSION file to EXTRA_DIST

- configure.ac
- prov/efa/configure.m4
Two commits, one to configure.ac and one for EFA to disable 32 bit builds.
```
c22618979 prov/efa: disable build on 32-bit systems
d098dbe5d configure.ac: check size of void*
```
Test description: Dusted off a c1 instance and verified the EFA provider is disabled on a 32 bit system.
> prov/efa: disable 32 bit builds

- include/ofi_util.h
- include/windows/sched.h
- libfabric.vcxproj
- libfabric.vcxproj.filters
- prov/efa/src/efa_fabric.c
- prov/psm2/src/psmx2_attr.c
- prov/psm3/src/psmx3_attr.c
- prov/psm3/src/psmx3_init.c
- prov/util/src/util_attr.c
- prov/util/src/util_shm.c
- prov/util/src/util_wait.c
- prov/verbs/src/verbs_ep.c
- prov/verbs/src/verbs_info.c
Changes made in response to a build log provided by redhat.
- Renamed some internal macros to use the OFI prefix.  Impacts several providers.
- Created new macro to separate use of size_t fields from u64, in order that correct printf format specifier is used.
- Replaced deprecated pthread_yield call with sched_yield
- Fixed casting of ints to pointers of different sizes in shm util code.
> core: Fix build warnings, mostly around printf format specifiers, in several areas

- prov/shm/src/smr_attr.c
HMEM atomics are not supported. Remove this from the hmem info
> prov/shm: disable FI_ATOMIC when FI_HMEM is requested

- prov/rxm/src/rxm_conn.c
If we receive a connection failure from verbs, reset
the conn object, so that a subsequent attempt can try
again.
> [v1.13.x] prov/rxm: Handle connection failures from verbs

- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_conn.c
- prov/rxm/src/rxm_cq.c
2 patches which are simple optimizations to avoid calling gettime() when the results will be ignored.
Change to rxm to try to progress connections if there are any active.  This should improve responsiveness to new connections, which should improve the performance of certain MPI applications.
Marking as do not merge until the performance impact can be analyzed.  Changes are based on suggestions from the Intel MPI team, however.
> prov/rxm: Provide quicker response to CM progress

- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_conn.c
- prov/verbs/src/fi_verbs.c
- prov/verbs/src/fi_verbs.h
- prov/verbs/src/verbs_cm.c
- prov/verbs/src/verbs_cm_xrc.c
- prov/verbs/src/verbs_cq.c
- prov/verbs/src/verbs_dgram_av.c
- prov/verbs/src/verbs_domain.c
- prov/verbs/src/verbs_domain_xrc.c
- prov/verbs/src/verbs_ep.c
- prov/verbs/src/verbs_eq.c
- prov/verbs/src/verbs_info.c
- src/log.c
Includes patch to add time stamps (using time()) to all log messages, so that log messages between processes and systems can be coordinated.
Several verbs error messages were converted from INFO to WARN.  Also replaced the prefix for verbs logging for consistency (VERBS -> VRB)
Added a few new messages to rxm, plus a new log macro to simplify the code.
> core/rxm/verbs: Expand and cleanup log messages

- prov/efa/src/rxr/rxr_ep.c
Progress engine will submit queued read request.
When doing that, it needs to retrieve the peer of the read
to check whether peer is in RNR backoff state.
Local read request (which is used to copy data from host
memory to device memory) does not have a peer, thus
the returned peer pointer would be NULL, therefore
a queued local read requst will cause segfault.
This patch handles that case correctly by not checking
peer state if peer is NULL, it also removed the assertion
of peer not being NULL.
> prov/efa: handle queued local read request correctly

- prov/efa/src/rxr/rxr_msg.c
- prov/efa/src/rxr/rxr_pkt_type.h
- prov/efa/src/rxr/rxr_pkt_type_req.c
- prov/efa/src/rxr/rxr_pkt_type_req.h
- prov/efa/src/rxr/rxr_rma.c
The original protocol selection for emulated write used the
maximum possible message header size, which led to situations
where all of the data was sent within the RTW message leading
to assertion errors.
This patch calculates the exact header size instead.
Signed-off-by: Matt Koop <mkoop@amazon.com>
> prov/efa: fix the emulated write protocol selection

- prov/verbs/src/verbs_mr.c
Need not grant IBV_ACCESS_LOCAL_WRITE for FI_WRITE -
FI_WRITE
The memory buffer may be used as the source buffer for RMA write and atomic  operations
on  the  initiator side.  Note that from the viewpoint of the application, the endpoint
is reading from the memory buffer and copying the data onto the network.
It only needs local read permission which is always enabled.
To fix EFAULT failure when fi_mr_regv() a RO buffer.
Signed-off-by: Xuezhao Liu <xuezhao.liu@intel.com>
> prov/verbs: refine vrb_mr_ofi2ibv_access

- prov/netdir/src/netdir_ep_msg.c
- prov/netdir/src/netdir_ep_rma.c
- prov/netdir/src/netdir_ep_srx.c
- prov/netdir/src/netdir_init.c
- prov/util/src/util_attr.c
The tcp provider requires the use of shared contexts in order to
support the FI_TAGGED capability.  By default, if an application
does not specify a tx or rx cxt_cnt, the returned fi_info should
be 1.  Update the checks in ofi_check_ep_attr to see if the user
has specified a tx or rx cxt_cnt.  If no count was specified and
the provider's fi_info structure requires FI_SHARED_CONTEXT, fail
the info match.
> core/getinfo: Fix check if provider requires use of shared contexts

- prov/rxm/src/rxm_conn.c
If we receive a connection request from the same peer address
and we're in the CONNECTED or ACCEPTING state, the new request
likely indicates that the old connection is no longer valid.
(We expect the lower layer to filter out true duplicate
connection requests).  When this occurs, close the older
connection and accept the new request.
> prov/rxm: Shutdown existing connections if we receive a new request

- man/fi_mr.3.md
There's some confusion around the use of the term optional.
Clarify when the key is used, versus when it is ignored.
> man/mr: Clarify FI_MR_PROV_KEY

- prov/efa/src/rxr/rxr_ep.c
This PR backports https://github.com/ofiwg/libfabric/pull/7238 to v1.13.x branch
> [v1.13.x] prov/efa: handle queued local read request correctly

- prov/efa/src/rxr/rxr_msg.c
- prov/efa/src/rxr/rxr_pkt_type.h
- prov/efa/src/rxr/rxr_pkt_type_req.c
- prov/efa/src/rxr/rxr_pkt_type_req.h
- prov/efa/src/rxr/rxr_rma.c
This PR backports https://github.com/ofiwg/libfabric/pull/7242 to v1.13.x
> [v1.13.x] prov/efa: fix the emulated write protocol selection

- prov/psm3/Makefile.include
Allow to override build date with `SOURCE_DATE_EPOCH` in order to make builds reproducible.
See https://reproducible-builds.org/ for why this is good
and https://reproducible-builds.org/specs/source-date-epoch/
for the definition of this variable.
This date call works with various `date` command implementations.
Also consistently use ISO 8601 date format to be understood everywhere and to be independent of locales.
Also use UTC to be independent of timezone.
> Allow to override build date with SOURCE_DATE_EPOCH

- prov/efa/src/efa.h
- prov/efa/src/efa_av.c
- prov/efa/src/efa_cm.c
- prov/efa/src/efa_domain.c
- prov/efa/src/efa_ep.c
- prov/efa/src/efa_fabric.c
- prov/efa/src/rxr/rxr_pkt_cmd.c
Following are the changes required to let efa provider compile with Microsoft Visual studio Compiler (MSVC)
- Replaced obsolete timezone parameter from gettimeofday call with NULL.
- Changed {} initialization to {0} as {} is not supported by MSVC
- Converted `align_down_to_power_of_2` macro to an inline function to avoid use of statement expressions.
- Refactored fork support initialization into its own function and calling it only if we are not on Windows.  There is no fork support on Windows.
- Hardcoded length of `host_gid` to `RXR_MAX_NAME_LENGTH` to avoid variable length array.
> prov/efa: Changes to allow efa provider compilation with MSVC - Does not enable efa provider for Windows yet

- include/rdma/providers/fi_log.h
- include/windows/alloca.h
- include/windows/asm/types.h
- include/windows/sys/epoll.h
FI_WARN_ONCE macro is changed to avoid statement expression - it is now similar to FI_WARN macro.
The empty header files are needed to compile efa provider with Microsoft Visual studio Compiler (MSVC).
> Make FI_WARN_ONCE MSVC compatible and add missing headers

- include/rdma/fabric.h
- include/rdma/fi_endpoint.h
- include/rdma/fi_trigger.h
- man/fi_endpoint.3.md
- man/fi_getinfo.3.md
- man/fi_trigger.3.md
Many HPC and AI applications use GPUs or other accelerator devices
to perform computation work.  FI_HMEM support allows a NIC
provider to send and receive data stored on a GPU.  However,
the data transfer itself must still be initiated by the host
CPU.  This introduces delays from the time the data is ready to
be transfered until the network transfer is initiated.  Once
the GPU is done processing the data, it must signal the CPU
that the processing is complete, and then the CPU can request
the network transfer.
This patch introduces a new type of triggered operation, called
an XPU trigger.  An XPU trigger works as follows:
1. An endpoint is created with XPU triggering support.  By
default, all data transfers posted to the endpoint follow
the XPU triggering model.
2. The host CPU makes a …
> core: Define XPU triggering capability

- fabtests/man/fabtests.7.md
- fabtests/prov/efa/Makefile.include
- fabtests/prov/efa/src/efa_rnr_shared.c
- fabtests/prov/efa/src/efa_rnr_shared.h
- fabtests/prov/efa/src/rdm_rnr_queue_resend.c
- fabtests/prov/efa/src/rdm_rnr_read_cq_error.c
1.  fi_efa_rnr_read_cq_error is used to test if an RNR error CQ entry can be read. Source rdm_rnr_read_cq_error.c.
2.  fi_efa_rnr_queue_resend is used to check if queuing/re-sending logic works correctly for different packet types. Source rdm_rnr_queue_resend.c.
3. efa_rnr_shared.c stores some routines shared by 1 and 2.
Also update the Makefile and man page accordingly.
> fabtests: Update EFA provider's specific RNR test

- fabtests/scripts/runfabtests.sh
Update test list for EFA provider specific RNR test in runfabtests.sh **after PR#7259 is merged**.
The details are:
(1) check if RNR CQ error entry can be read by application.
"fi_efa_rnr_read_cq_error"
(2) check if RNR queue/re-send logic working correctly for all packet types.
"fi_efa_rnr_queue_resend -c 0 -S 1048576" - CTS, DATA / EOR(RDMA Read)
"fi_efa_rnr_queue_resend -c 0 -o read -S 4" - READRSP
"fi_efa_rnr_queue_resend -c 0 -A read -S 4" - ATOMRSP
"fi_efa_rnr_queue_resend -c 0 -U -S 4" - RECEIPT
"fi_efa_rnr_queue_resend -c 1 -S 4" - EAGER_MSGRTM
"fi_efa_rnr_queue_resend -c 1 -T -S 4" - EAGER_TAGRTM
"fi_efa_rnr_queue_resend -c 1 -S 16384" - MEDIUM_MSGRTM
"fi_efa_rnr_queue_resend -c 1 -T -S 16384" - MEDIUM_TAGRTM
"fi_efa_rnr_queue_resend -c 1 -S 1048576" - LONGCTS_MSGRTM / …
> fabtests: Update test list for EFA specific RNR test in runfabtests.sh

- prov/efa/src/efa_device.c
- prov/efa/src/efa_fabric.c
- prov/efa/src/efa_rma.c
- prov/efa/src/windows/README.Efawin
This pull request provides an alternate Windows specific implementation for `efa_alloc_fid_nic` function.  It is mostly a copy with some Linux specific paths replaced with Windows specific logic.
This pull request also adds the necessary dependency named efawin to efa provider.   This is required for efa provider to work on Windows. The dependency is done in a similar way to netdir provider where we ask the developer to copy files from an external source.  In this case, the efa provider is taking a dependency on a specific version of efawin when compiling for Windows. The intent is to update the instructions with newer versions as they are tested and proven to be compatible with efa provider.
Note that a different pull request will enable compilation of efa provider on Windows.
> prov/efa: Get efa provider ready to be compiled for Windows

- include/ofi_shm.h
- prov/shm/src/smr_atomic.c
- prov/shm/src/smr_ep.c
- prov/shm/src/smr_msg.c
- prov/shm/src/smr_progress.c
- prov/shm/src/smr_rma.c
- prov/util/src/util_shm.c
The shm provider currently uses a spin lock by default. However, this
can cause performance issues if a process gets swapped out while holding
the lock and the process swapped in attempts to acquire the same lock.
This also uses a separate lock initialization which sets the PTHREAD_PROCESS_SHARED
attribute field to make sure this lock is shareable between processes, unlike
the default fastlock_init function which makes the lock private.
> prov/shm: change shm lock to mutex and add shared attr

- prov/rxm/src/rxm_init.c
Passthru is disabled by default, and must be enabled.
> prov/rxm: Fix inversion of passthru environment name

- src/common.c
These were revealed via testing with llvm-unstable. The "64"->"46"
looks like an old typo because INET6_ADDRSTLEN is 46 not 64,
and the other changes are just making room for a possible trailing '\0'.
> Fix potential sscanf overflows.

- Makefile.am
- configure.ac
- include/ofi_hmem.h
- include/ofi_hook.h
- include/ofi_prov.h
- prov/hook/hook_hmem/Makefile.include
- prov/hook/hook_hmem/configure.m4
- prov/hook/hook_hmem/include/hook_hmem.h
- prov/hook/hook_hmem/src/hook_hmem.c
- prov/hook/src/hook_cq.c
- prov/hook/src/hook_domain.c
- src/fabric.c
- src/hmem.c
Initial PR for this hook to open up for discussion/review.
This also changes some hmem op functions and other interfaces so anyone able to review/provide insight on those changes would be greatly appreciated.
> prov/hook_hmem: initial commit for ofi_hook_hmem - MR registration query/registration hook for hmem memory

- prov/efa/src/rxr/rxr_atomic.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_rma.c
The exhaustion of tx entry pool when submitting a request
is common, therefore we not should not report it using
FI_WARN. This patch changed that to FI_DBG.
> prov/efa: adjust print level for tx entry exhausted

- README.md
- fabtests/scripts/runfabtests.cmd
- prov/hook/hook_hmem/Makefile.include
- prov/hook/hook_hmem/include/hook_hmem.h
- prov/hook/hook_hmem/src/hook_hmem.c
- prov/rxm/src/rxm_init.c
If the core provider only supports FI_LOCAL_COMM or FI_REMOTE_COMM
then rxm should only report those in the info and domain caps.
This can occur with the tcp provider using the loopback device,
where only FI_LOCAL_COMM is supported.
> prov/rxm: Restrict reported caps based on core provider

- include/ofi_coll.h
- include/ofi_util.h
- prov/util/src/util_av.c
- prov/util/src/util_coll.c
There is a memory leak of the coll_mc when the parent AV is
destroyed.  To fix the leak, we simplify and restructure the
creation of AV sets.  This may seem like overkill, but is
necessary to fixup object reference counting.
The current code associates a base collective multicast group
(coll_mc) with an AV the first time an AV set is created.  This adds
a coll_mc to the AV, which is what gets leaked.  However, that
coll_mc itself creates an av_set.  Part of the generic creation
of an av_set, a coll_mc is created.  The result is that we have
AV -> coll_mc -> av_set -> coll_mc.  So, there's a double coll_mc
created for the AV.
We can simplify the code by having the AV create an initial av_set
when needed, and let create av_set create the coll_mc.  Then use
that coll_mc and avoid the …
> prov/util: Restructure collective av set creation/destruction

- fabtests/benchmarks/dgram_pingpong.c
This patch added the handling of failed fi_recv in function
run().
Signed-off-by: Yonatan Nachum <ynachum@amazon.com>
> fabtests/dgram_pingpong: handle the error return of fi_recv

- man/fi_mr.3.md
- prov/util/src/util_mem_monitor.c
Clarify that ZE refers to oneAPI Level Zero, as ZE by itself
isn't a well known name, like CUDA, or marketed as such.
> core: Document ZE as oneAPI Level Zero

- prov/efa/src/rxr/rxr_atomic.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_rma.c
The exhaustion of tx entry pool when submitting a request
is common, therefore we not should not report it using
FI_WARN. This patch changed that to FI_DBG.
> [v1.13.x] prov/efa: adjust print level for tx entry exhausted

- prov/efa/src/rxr/rxr_atomic.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_rma.c
The exhaustion of tx entry pool when submitting a request
is common, therefore we not should not report it using
FI_WARN. This patch changed that to FI_DBG.
> [v1.14.x] prov/efa: adjust print level for tx entry exhausted

- prov/verbs/src/fi_verbs.h
- prov/verbs/src/verbs_cq.c
- prov/verbs/src/verbs_ep.c
evaluating for DAOS reported issue
> prov/verbs: Flush any pending send requests on EP destruction

- prov/verbs/src/verbs_eq.c
Not all fields in the fi_fabric_attr are set when reporting an
fi_info structure as part of an FI_CONNREQ event.  Specifically,
the prov_name and api_version are left unset.  These are usually
set by the core when fi_getinfo is called, but that path is not
taken for CM events.
Copy the values from the passive ep.
> prov/verbs: Format fi_fabric_attr reported through FI_CONNREQ event

- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_conn.c
From valgrind, there's a possible use of uninitialized data passed
to the socket send() call.  This comes from rxm_accept_connreq(),
which uses the cm_data union.  Although all fields of cm_data.accept
are set, the sizeof(cm_data.accept) includes extra padded bytes for
alignment purposes.  Those extra bytes are not set and are handed
through the fi_accept() call, which eventually winds its way through
the tcp provider to a socket send() call.
Fix this by adding an explicit pad field to the structure (to ensure
that 32-bit and 64-bit processors use the same size structure), and
set the padded field to 0.
> prov/rxm: Fix possible leak of stack data in cm_accept

- include/ofi_hmem.h
- src/hmem_cuda.c
Expose these functions so providers can try to register CUDA memory to detect
whether the underlying network device supports registering CUDA buffers.
> hmem cuda: add stubs for cudaMalloc and cudaFree

- prov/netdir/src/netdir.h
- prov/netdir/src/netdir_ep.c
- prov/netdir/src/netdir_ep_srx.c
- prov/netdir/src/netdir_init.c
- prov/netdir/src/netdir_pep.c
1 Add netdir provider-wide implementation for fi_getopt.
1.1 Add hooks for common fi_getopt implementation in netdir_ep.c/netdir_pep.c/netdir_ep_srx.c.
1.2 Move fi_getopt implementation from netdir_pep.c to netdir_ep.c and rename from ofi_nd_pep_getopt to ofi_nd_ep_getopt.
1.3 Modify fi_getopt implementation to return value from IND2Adapter::Query instead of hard coded value.
2 Modify fi_enable implementation to allow client control of values used when creating a queue pair.
2.1 Modify tx/rx size/iov_limit values used for fi_getinfo to come from IND2Adapter::Query rather than hard coded values.
2.2 Modify fi_enable implementation to use tx/rx size/iov_limit values when creating tx/rx queue pair rather than maximum allowed so hints can control the actual values used.
on-behalf-of: @cmru-ps …
> netdir / fi_endpoint uses maximum values to create queue pair 

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/build.py
source env/vars.sh before building IMPI
> contrib/intel/jenkins: source env/vars.sh Jenkinsfile

- contrib/intel/jenkins/build.py
replace deprecated MPICH config option
> contrib/intel/jenkins: update mpich_build configure

- contrib/intel/jenkins/build.py
- contrib/intel/jenkins/tests.py
> contrib/intel/jenkins:remove_intel64

- .github/workflows/pr-ci.yml
The Ubuntu distro ZE version was recently updated from 1.4.1 to 1.6.2 which has
an issue in the headers which prevents compilation and causes CI failures.
The issue has been fixed in 1.7.4 but the distro has not been updated yet. This
is a temporary manual workaround to use 1.7.4 instead of the distro version to
avoid CI failures.
Will be removed when the distro gets updated.
> .github/workflows: temporary workaround for failing ZE build

- fabtests/benchmarks/benchmark_shared.c
The inject path doesn't pass a descriptor which will cause hmem buffers
to be used incorrectly. Set the inject size to zero when FI_HMEM is
enabled.
> fabtests: disable inject when FI_HMEM is enabled

- prov/efa/src/efa.h
- prov/efa/src/efa_domain.c
- prov/efa/src/efa_ep.c
- prov/efa/src/efa_fabric.c
- prov/efa/src/efa_mr.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_init.c
- prov/efa/src/rxr/rxr_msg.c
- prov/efa/src/rxr/rxr_pkt_type_base.c
- prov/efa/src/rxr/rxr_rma.c
A handful of patches to start on properly handling FI_HMEM support when peer to peer support is unavailable, and to deal with the deprecation of the gdr sysfs flag in the EFA kernel driver.
We still require RDMA and NVIDIA GPUDirect support for FI_HMEM at this time.
```
prov/efa: change FI_HMEM cap reporting behavior around p2p support
prov/efa: add copy paths for hmem when p2p is disabled
prov/efa: add state to track FI_HMEM support
prov/efa: rename err to ret in rxr_msg_post_rtm
```
Test description: Tested NCCL allreduce perf and MPI ring_c on two p4d.24xlarge instances. Still trying to test this on p3dn.
> prov/efa: FI_HMEM caps refactoring

- .gitignore
This patch added the executables under fabtests/prov/efa/src,
which were generated during compilation, to .gitignore
> .gitignore: add executables under fabtests/prov/efa/src/

- fabtests/test_configs/efa/efa.exclude
The exclusion of "msg" was intented to exclude tests
using msg endpoint, but it accidently excluded test
"fi_unexpected_msg", which is a valid test EFA's rdm endpoint
This patch fixed the issue by excluding "msg_sockets" instead
of "msg", which excluded the test fi_msg_sockets.
With this change, tests that uses msg endpoint will be run,
and EFA provider will return FI_ENODATA, and these tests
will be marked as "notrun".
> fabtests/efa.exclude: exclude msg_sockets instead of msg

- prov/efa/src/efa.h
- prov/efa/src/rxr/rxr_msg.c
- prov/efa/src/rxr/rxr_pkt_type_misc.c
- prov/efa/src/rxr/rxr_read.c
Add a new function called efa_ep_is_hmem_mr to be used for paths where
we want a general HMEM check. CUDA still has a couple of special cases
until we support CUDA IPC.
> prov/efa: add efa_ep_is_hmem_mr function     

- fabtests/scripts/runfabtests.sh
For a multinode test, there are multiple client output, therefore
function multinode_test() call print_results() with empty client
output, and print each client's output by itself.
print_results() does not print client command if client output
is empty, thus client command is not printed for multinode test.
This patch fixed the issue by printing client command in
multinode_test().
> fabtests/runfabtests.sh: print client command for multinode test

- fabtests/test_configs/efa/efa.exclude
EFA does not pass the newly added fi_msg_inject test on single
instance. This patch temporarily excludes this test for EFA to
make CI stable.
> fabtests/efa.exclude: temporarily exclude fi_msg_inject

- Makefile.am
- configure.ac
- fabtests/Makefile.am
- fabtests/Makefile.win
- fabtests/common/hmem.c
- fabtests/common/hmem_neuron.c
- fabtests/common/shared.c
- fabtests/configure.ac
- fabtests/fabtests.vcxproj
- fabtests/fabtests.vcxproj.filters
- fabtests/include/ft_list.h
- fabtests/include/hmem.h
- fabtests/include/shared.h
- fabtests/unit/mr_cache_evict.c
- include/ofi_hmem.h
- include/ofi_mr.h
- include/rdma/fi_domain.h
- libfabric.vcxproj
- libfabric.vcxproj.filters
- man/fi_mr.3.md
- src/hmem.c
- src/hmem_neuron.c
Add support for AWS Trainium accelerators available via the trn1 EC2 instance. Changes to support this in the EFA provider will come soon in a separate PR.
https://aws.amazon.com/ec2/instance-types/trn1/
Commits:
```
fabtests: add AWS Trainium device support
This adds support for AWS Trainium devices to fabtests.
```
```
fabtests: add ft_list.h dlist implementation
Copy over the doubly linked list implementation from Libfabric.
```
```
hmem: add support for AWS Trainium devices
Add support for AWS Trainium devices via the AWS Neuron SDK. Writes to
Trainium will be done via the PCIe BAR and reads from Trainium are not
supported at this time.
Despite accessing Trainium memory via the BAR, we still dlopen the
Neuron runtime so that providers allocate a device page and then
register it with …
```
> hmem: add support for AWS Trainium to Libfabric and Fabtests

- fabtests/Makefile.am
- fabtests/test_configs/efa/efa-neuron.exclude
- man/fi_efa.7.md
- prov/efa/src/efa.h
- prov/efa/src/efa_domain.c
- prov/efa/src/efa_ep.c
- prov/efa/src/efa_fabric.c
- prov/efa/src/efa_mr.c
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_attr.c
- prov/efa/src/rxr/rxr_domain.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_init.c
- prov/efa/src/rxr/rxr_msg.c
- prov/efa/src/rxr/rxr_rma.c
Add support to the EFA provider for AWS Trainium device buffers. RDMA
support and EFA/Trainium peer to peer transactions are required for
Libfabric to support FI_HMEM with Trainium.
Due to the way Libfabric interacts with Trainium buffers, we will force
the LONGREAD protocol for any messages larger than the EFA device MTU
size, so also add a function to check for that.
Test description: Ran fabtests on two trn1 instances.
> prov/efa: add AWS Trainium device support

- fabtests/include/shared.h
- src/fabric.c
Patch to update fabtests to print the generic errno values for CQ/EQ errors, rather than just the provider error values.  For grins, updated fi_strerror to handle negative errno values, so the user can pass in either a positive or negative value.
> core/strerror: treat negative errnums as positive

- fabtests/ubertest/xfer.c
There was a small bug discovered while testing HMEM ZE on
PVC with IPC path. A wrong buffer was used which has been
fixed.
> fabtests/ubertest: Fix tests failing with IPC

- man/fi_domain.3.md
Under certain conditions, such as the shm provider, support for auto
progress would require the allocation of a spinning thread.  The EFA
provider has a similar restriction in that auto progress is not
supported for RMA.  Since existing providers cannot meet this
requirement and never have, remove the text from the man pages.
> man/domain: Remove provider requirement to support auto progress

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/build.py
- contrib/intel/jenkins/tests.py
add a -j flag to libfabric and fabtests build
change build.py to copy a tree of static prebuilt middlewares to use with ci tests
update jenkinsfile stages to remove middleware builds
remove uneccessary build directions in build.py for removed middleware builds
update file paths with new tree copy location
> contrib/intel/jenkins: remove middleware builds from PR pipeline

- fabtests/common/shared.c
- fabtests/functional/msg_inject.c
- fabtests/include/shared.h
- fabtests/multinode/src/core.c
Currently, upon any error return of ft_tsendmsg, the msg_inject test
will fail. However, in case of -FI_EAGAIN, the test should retry the
send.
This patch makes that change to msg_inject.
> fabtests/msg_inject: handle the case ft_tsendmsg return -FI_EAGAIN

- include/ofi_epoll.h
- src/common.c
- src/unix/osd.c
- src/windows/osd.c
When connected to a large number of peers, the poll() system call
can be slow because of the number of fd's to check.  If only a
few peers are actively sending or receiving from the local
endpoint, we can reduce the overhead of checking by maintaining
an array of fd's which are active, or hot.
This adds a hot fd list to the pollfds abstraction, along with
a fairly simple mechanism for tracking fd's which are hot.  A
fairness counter is also maintained to ensure that the full fd
list is periodically checked.  The fairness counter will be
controllable though an environment variable, with a default
value set in follow on patches based on experimentation.
An fd is considered hot if it has data to send and the caller
is blocked waiting for a POLLOUT event.  It is also hot if any
data has been …
> util/pollfds: Introduce hot fd list

- fabtests/test_configs/efa/efa.exclude
The test msg_inject does not handle -FI_EAGAIN error code
correctly, which caused EFA provider to fail.
The issue has been fixed by
#7357
. so this patch enable the test for EFA.
> fabtest/efa.exclude: remove msg_inject from exclusion list

- .github/workflows/pr-ci.yml
Looks like we lost Coverity reporting again, this time due to the move
to Github CI from Travis. This is not as polished as what we had with
Travis, but it gets us back up and running.
> pr-ci: Add back coverity testing

- prov/util/src/util_av.c
This can occur through the path that calls ip_av_nodesym_getaddr().
If the getaddrinfo call inside that function fails, it can return
a positive error code (from getaddrinfo).  This is treated as a
count value in ip_av_insertsym, which then tries to access the
freed address array.
> prov/util: Fix memory access in ip_av_insertsym

- .github/workflows/coverity.yml
- .github/workflows/pr-ci.yml
Running the coverity scan on each PR is not going to work, as PRs from
forks do not get access to repository secrets. Running it as a nightly
cron job with this commit instead.
> pr-ci: Move to a cron-based run

- include/ofi_util.h
- prov/netdir/src/netdir_init.c
- prov/tcp/src/tcpx_attr.c
- prov/util/src/util_attr.c
- prov/util/src/util_coll.c
Restructuring of ofi_alter_info_t callback handlers, plus fix for using an uninitialized variable in an error path.
> util: 1 coverity and 1 build warning fix

- .github/workflows/coverity.yml
We use a compiler extension that supports broader complex type
definitions than what's defined in C99 standard (which only defines
complex floats). For some reason, the version of GCC in this container
does not provide that extension, but clang does. Until we know better,
this action will use the clang compiler to generate the cov-build bundle
needed for the coverity scan
With the default compiler, we will get the following errors that limit
coverity's capture rate:
```
"/usr/include/x86_64-linux-gnu/bits/cmathcalls.h", line 57: error #1044:
_Complex can only be used with floating-point types
__MATHCALL (casin, (_Mdouble_complex_ __z));
^
```
With clang, I no longer see the errors, and the coverage rate has
increased as well.
Fixes #7372
> coverity: Switch to the clang compiler

- src/hmem_cuda.c
According its defintion, the default value of hmem_cuda_use_gdrcopy
should be 1, but the default value was not set in current code.
This patch fix the issue.
> core/hmem_cuda: fix the default value of hmem_cuda_use_gdrcopy

- fabtests/pytest/common.py
This patch added an argument to ClientServerTes, so it can be
used to run tests between different types of memory. Current path
added support to 4 types: host_to_host, host_to_cuda, cuda_to_host
and cuda_to_cuda.
Default memory type is set to "host_to_host" thus current tests
are not affected.
> fabtests/pytest/common.py: add argument memory_type to ClientSeverTest

- prov/verbs/src/fi_verbs.h
- prov/verbs/src/verbs_cq.c
- prov/verbs/src/verbs_ep.c
The full opcode is needed to properly set the completion
flags in the case of an error, when the opcode is not
provided back as part of the completion.
As part of this change, we rename op_ctx to op_queue to
avoid confusion with the opcode, since that field is only
storing which queue the operation was posted to.
> prov/verbs: Store ibv_wr_opcode to use in error cases

- fabtests/pytest/efa/test_rdm.py
This patch introduced a parametrized fixture "memory_type",
which has 4 parameters: host_to_host, host_to_cuda,
cuda_to_host, and cuda_to_cuda.
It then used this fixture as an argument to test on
rdm_pingpoing, rdm_tagged_pingpong, rdm_tagged_bw
> fabtests/efa/test_rdm.py: add cuda tests to rdm tests

- prov/tcp/src/tcpx_cq.c
The use of epoll vs poll events is reversed relative to the
epoll/poll call.
How is this provider working?!?!?!
> prov/tcp: Fix use of incorrect events in progress handler

- include/ofi.h
> include/ofi.h Avoid implicit casting when calling ofi_get_page_start

- prov/efa/src/efa_av.c
- prov/efa/src/rxr/rxr_pkt_cmd.c
This PR contains two commits:
- add the packet type and flags into the warning messages a receiving packet from a removed address is ignored
- adds warning message that contains the ahn and qpn if they cannot be found in the reverse av table.
> prov/efa: Add more warning message when the peer cannot be found for a received packet

- man/fi_av.3.md
Multiple insertions of the same address into the AV can cause
problems with some providers, particularly trying to handle
source address matching.
> man/av: Indicate that the same address should not be inserted twice

- prov/hook/hook_hmem/src/hook_hmem.c
- prov/shm/src/smr_av.c
- src/common.c
Fixes #7400.
The sizeof(str) is smaller than what's needed to store an ipv6
address plus the fi_sockaddr_in6:// header.  Remove the
unneeded MIN call and use the user's len value directly.
> util/ofi_straddr: Fix truncation of ipv6 addressing

- man/fi_efa.7.md
EFA provider only supports FI_PROGRESS_MANUAL, so update it in efa provider and its manpage. 
We need to update this PR once we have a unit test, thus add a "Do not merge" label.
> man: Update efa manpage on progress mode 

- man/fi_cq.3.md
This is not formally documented, but used by the util providers.
When cq_read is called with a count of 0, this can be used to
drive progress.  Formalize this feature for providers that
need manual progress.
Based on inspection, it looks like most providers support this feature as it's part of the util code.
> man/cq: Document that cq_read with a count = 0 is valid

- prov/tcp/src/tcpx.h
- prov/tcp/src/tcpx_cq.c
- prov/tcp/src/tcpx_msg.c
Mark inject operations to not generate a completion, even in
the case of failures.  Generating a completion can result in
reporting of a null context to the user, which if they try
to dereference, will result in a segfault.  This is seen with
rxm running MPI apps.
> prov/tcp: Do not generate error completions for inject msgs

- include/ofi.h
- prov/util/src/util_attr.c
- src/log.c
Utility providers have to call fi_getinfo again to get core providers
resulting in deceptive and confusing log lines where a core provider
might return FI_ENODATA for a utility provider but FI_SUCCESS for the
app. Extra log levels were added that say Begin/End ofi_get_core_info
to make this clearer but these debug-only (not info) logs can get lost
among the hundreds of lines of output.
To make it easier to distinguish between log lines with and without a
core provider, specifically during fi_getinfo, add a log_prefix to the
log output which clarifies that the log line was outputed as part of
the layered fi_getinfo call
For example, the following log line sees changes as such:
libfabric:53685:1643663041:verbs:fabric:vrb_get_matching_info():1514<info> checking domain: #1 mlx5_0 …
> src/log: add utility provider log suffix to make logs easier to read

- fabtests/scripts/runfabtests.py
Currently, runfabtests.py exists with code 0 when
tests has been run succefully, even when some tests
failed.
To address this issue, this patch makes runfabtests.py
to exit with the exit code of pytest.
For reference, pytest return codes are:
0: All tests were collected and passed successfully
1: Tests were collected and run but some of the tests failed
2: Test execution was interrupted by the user
3: Internal error happened while executing tests
4: pytest command line usage error
5: No tests were collected
as documented in
https://docs.pytest.org/en/latest/reference/exit-codes.html
> runfabtests.py: exit with exit code of pytest

- Makefile.am
- include/ofi.h
- include/ofi_prov.h
- prov/hook/hook_debug/Makefile.include
- prov/hook/hook_debug/configure.m4
- prov/hook/hook_hmem/Makefile.include
- prov/hook/hook_hmem/configure.m4
- prov/hook/hook_hmem/src/hook_hmem.c
- prov/hook/perf/Makefile.include
- prov/hook/perf/configure.m4
- prov/hook/src/hook.c
- src/fabric.c
This allows upgrading hooking providers in an existing libfabric
installation, or distributing hooking providers separately
> prov/hook: Enable DL build of hooking providers

- src/common.c
- src/log.c
Previous commit introduced a global variable log_prefix to src/log.c,
and log_prefix is accessed by prov/util/src/util_attr.c
However, src/log.c is not part of common_srcs, thus the variable
in it is not available to dso build of provider.
This patch addresses the issue by move log_prefix to src/common.c.
> core/log,common: move log_prefix to common.c

- fabtests/common/shared.c
fi_mcast prints help string for -d and -p flags twice.
Remove duplicates.
> fabtests: Remove duplicate help prints from fi_mcast

- fabtests/prov/efa/src/rdm_rnr_queue_resend.c
Resolve compilation warning with trigger_rnr_queue_resend returning uninitialized
ret on success.
> fabtests/prov/efa: Make sure trigger_rnr_queue_resend returns 0 on success

- include/rdma/fabric.h
For version check, it is not necessary to check major and minor
separately.  Macros can be simplified to check the whole version
number with >= and < operators.
> include/rdma: Simplify version check macros

- prov/rxm/src/rxm_ep.c
If we receive an unexpected message from a peer that we
have not yet inserted into the local AV, no source address
will be available for that message.  Instead the source
address will be set to FI_ADDR_UNSPEC.  Later, after the
address is inserted into the AV, a message may be posted
referencing the source address.  However, no match will
be made, since the source address was not available
when the message was queued.
This problem occurs during MPI start-up in all to all
communication patters.
To provide source address matching in this case, if the
source address saved with the unexpected message is
FI_ADDR_UNSPEC, retrieve the address currently assigned
to the connection that the message arrived on.  Once the
peer's address is inserted into the AV, the connection
will be updated with the …
> prov/rxm: Fix race handling unexpected messages

- fabtests/pytest/common.py
Currently, the code used ">& output" to direct stderr to stdout, which is
not supported by /bin/sh. This patch used "> output 2>&1" to be more
general
> fabtests/pytest/common.py: fix redirect syntax

- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_conn.c
There are 2 situations where we can receive a connection request
from a peer where we already have a connection that's active.
In one case, the connection may be an older connection to the
same node, but to a client that's no longer running.  In this case,
the old connection needs to be closed and the new connection
accepted.  This is the behavior of the current code.  The code
was structured this way to handle a situation where a client
crashed and was restarted, with the new client choosing the same
network address.  Unless the old connection discarded and the new
request accepted, the re-started client would not be able to
communicate with a running server.
In the second case, the connection may have just been created,
with the request being for a simultaneous connection.  This
occurs …
> prov/rxm: Add PID to CM messages

- fabtests/pytest/efa/test_rdm.py
There is an ongoing hardware issue that will cause fi_rdm test
to fail. This patch remove the test for now to mitigate it.
> fabtests/pytest/efa: remove fi_rdm test for a hardware issue.

- src/linux/osd.c
found using gcc -fsanitize=address.
error: ‘strncpy’ specified bound 16 equals destination size
Signed-off-by: Denis Maryin <denis.maryin@intel.com>
> src/linux: fixed stringop-truncation in ofi_ifaddr_get_speed

- Makefile.am
- configure.ac
- include/ofi_hook.h
- include/ofi_prov.h
- prov/hook/dmabuf_peer_mem/Makefile.include
- prov/hook/dmabuf_peer_mem/configure.m4
- prov/hook/dmabuf_peer_mem/include/dmabuf_reg.h
- prov/hook/dmabuf_peer_mem/include/hook_dmabuf_peer_mem.h
- prov/hook/dmabuf_peer_mem/src/hook_dmabuf_peer_mem.c
- prov/verbs/src/verbs_mr.c
- src/fabric.c
The kernel module dmabuf_peer_mem.ko is a IB peer-memory client for dmabuf. It 
maintains a registry of dmabuf entries, each of which containing information 
such as base address, size, and dmabuf fd. With this registry, it can respond 
to requests from the MOFED RDMA driver to perform virtual address to DMA 
address mapping. The registry is updated by the user space applications via 
the character device /dev/dmabuf_reg. 
This new hooking provider intercepts memory registration calls. It checks if
the buffer to be registered is backed by dmabuf and if so, saves the info to
the registry maintained by the dmabuf_peer_mem.ko kernel module.
This hooking provider only applies to core providers to avoid duplicated action.
Also include two patches to the verbs provider for better out-of-the-box …
> Add new hooking provider dmabuf_peer_mem

- fabtests/Makefile.am
- fabtests/pytest/efa/conftest.py
- fabtests/pytest/efa/test_rdm.py
This patch introduced a new file: pytest/efa/conftest.py, which
will used to host all efa specific fixtures.
As the first step, the patch moved the memory_type fixture from
pytest/test/test_rdm.py to this file.
> pytest/efa/conftest.py: efa specific fixtures

- fabtests/common/hmem_neuron.c
This PR contains two patches that fix the neuron hmem issues in multi client test
1. reset `neuron_handle` to NULL after it's being dlclose() to avoid segfault during multi client test.
2. only call `nrt_init` once so there is no conflict in the neuron resource between the clients.
Test info: Run fabtests on single trn1 instance with -D neuron on both client and server.
> fabtests/common/hmem_neuron.c: Two bug fixes.

- contrib/intel/jenkins/run.py
- contrib/intel/jenkins/runtests.py
- contrib/intel/jenkins/tests.py
Two sets of OneCCL tests, examples and functional, have been
added to the Intel CI. OneCCL has been built in CPU only mode 
currently.
The test output is too wordy and hence will not be printed
on the console. It is being redirected to /dev/null and the
return code is used to determine if test has passed. OneCCL
team will be adding a new non-verbose option to the tests
for reducing output.
The time taken by a complete CI run is about  23 minutes after
these changes.
> contrib/intel: Add OneCCL tests to CI

- .github/workflows/pr-ci.yml
- fabtests/benchmarks/benchmark_shared.c
This PR is a backport of https://github.com/ofiwg/libfabric/pull/7334/commits/65fa2adcb3ff1d70b54d2f593b53a68edc869a1d to v1.14.x branch
> [v1.14.x] fabtests: disable inject when FI_HMEM is enabled

- fabtests/common/shared.c
- fabtests/include/shared.h
- fabtests/pytest/efa/conftest.py
- fabtests/pytest/efa/test_rdm.py
- fabtests/pytest/efa/test_rma_bw.py
The change adds an option to specify a range of messages
to fabtests by using the format 'r:start,increment,end'
to the "-S" option. Prior to this change, we were able to
provide "all" or a specific size to the message size option.
Updates have been made to pytest/efa tests to use this option
for message sizes in the range of 8k-9k with an increment of 4.
Tests were conducted using runfabtests.py to ensure the message
ranges are being processed by pytest (cuda testing is not done).
> fabtests/common: add option to configure message sizes 

- prov/tcp/src/tcpx_progress.c
Commit 45dce66 incorrectly negated a check that is used to signal
any threads waiting on a cq to wake up.  Without this signal,
applications can hang, as reported in issue 7443.  The situation is
as follows:
A thread waits for completions on the CQ. At the time that the thread
blocks, the socket has no outgoing transfers, so the thread calls
poll looking for a POLLIN event.
Another thread tries to send a large transfer. A portion of the data
is accepted by the socket. The rest of the transfer is queued on the ep.
That thread returns.  Additional messages may be posted to the ep, but
since there's already an active transfer, those messages simply get
queued on the tx_queue.
Note that the thread that was blocked on the CQ is still blocked waiting
for a POLLIN event.  However, it should be …
> prov/tcp: Wake-up threads blocked on CQ to update their poll events

- fabtests/benchmarks/dgram_pingpong.c
- fabtests/benchmarks/msg_bw.c
- fabtests/benchmarks/msg_pingpong.c
- fabtests/benchmarks/rdm_cntr_pingpong.c
- fabtests/benchmarks/rdm_pingpong.c
- fabtests/benchmarks/rdm_tagged_bw.c
- fabtests/benchmarks/rdm_tagged_pingpong.c
- fabtests/benchmarks/rma_bw.c
- fabtests/common/shared.c
- fabtests/fabtests.vcxproj.filters
- fabtests/functional/multi_recv.c
- fabtests/functional/rdm_atomic.c
- fabtests/include/shared.h
- fabtests/include/windows/sched.h
- fabtests/pytest/common.py
- fabtests/pytest/conftest.py
- fabtests/scripts/runfabtests.py
- fabtests/scripts/runfabtests.sh
fabtests define a set of standard tests, which run large iterations. People might want to run them with core pinning to reliably track the performance.
This PR introduces a new option "--pin-core" to these tests, and runfabtests.sh/runfabtests.py scripts. It's disabled by default. To enable core pinning, it's required to provide an argument (core_list) to specify which cores to pin. The
core_list format uses a comma-separated list. e.g., fi_rdm_tagged_bw -p "efa" --pin-core 0,2-4 -E
Commit 1: introduces "--pin-core" option to the tests in standard tests list.
Commit 2: introduces "--pin-core" option to runfabtests.sh script
Commit 3: introduces "--pin-core" option to runfabtests.py and pytest based scripts. 
Commit 4: add header file sched.h to build on Windows
> fabtests: Introduce "--pin_core" option

- fabtests/scripts/runfabtests.sh
> fabtests: Fix a typo in usage of runfabtests.sh

- fabtests/scripts/runfabtests.sh
- fabtests/test_configs/tcp/all.test
- fabtests/test_configs/verbs/all.test
- fabtests/ubertest/config.c
- fabtests/ubertest/cq.c
- fabtests/ubertest/fabtest.h
- prov/rxm/src/rxm_cq.c
- prov/rxm/src/rxm_msg.c
The separation of the tcp/verbs and ofi_rxm ubertest config files were preventing failing combinations from running. This fixes the coverage gap as well as some bugs in rxm from that gap.
> prov/rxm, fabtests/ubertest: bug fixes and ubertest updates to validate bug fix

- fabtests/common/shared.c
The help message currently states the option is --pin_core
(with underscore), which is incorrect.
> fabtests/common/shared.c: fix help message of --pin-core

- util/info.c
Commit 4646751 bad.  Always show everything.  Remove wrong check
to verbose path.  Make good.
> util/fi_info: Fix always displaying verbose output

- configure.ac
- prov/util/src/ze_mem_monitor.c
- src/hmem_ze.c
Enabling the ZE DL open path only requires having the ZE headers, not the ZE libraries
but the old code was checking for both.
To minimize this requirement, this rewrites the configure code and cleans it up so we
only take one of the two paths - only check for headers with ze_dlopen or check for
headers and the library.
This also fixes an issue where ENABLE_ZE_DLOPEN was only getting defined when enabled
but it is best practice to always set it and check for #if instead of #ifdef
Additionally, the old enable-ze-dlopen check was redundantly checking for libdl when
it was already checked in the beginning as part of the --with-dl check
This also updates the --with-ze help message to better reflect its usage and removes
redundant empty brackets which are not needed.
Signed-off-by: Alexia …
> configure.ac: rewrite ze checks to minimize ZE dl requirements

- .gitignore
- fabtests/Makefile.am
- fabtests/pytest/common.py
- fabtests/pytest/conftest.py
- fabtests/pytest/default/test_ubertest.py
- fabtests/pytest/options.yaml
- fabtests/scripts/runfabtests.py
This PR contains several improvement to the pytest framework of libfabric:
`fabtests/runfabtests.py: find pytest root dir when running from source`: this commit allows `runfabtests.py` to be run from inside a source code (prior to this patch, runfabtests.py can only be run from fabtests installation)
`fabtests/runfabtsts.py: use argparser's count action for verbose`: this commit uses python's argparser's count action to implement "-v", "-vv", "-vvv" option, which simplified the code
`fabtests/runfabtests.py,conftests.py: introduce options.yaml`: this commit save command line option's definition in a yaml file, and let runfabtest.py and conftest.py to load options from it. This greatly reduced code duplication, and simplified future work to introduce new options
`.gitignore: add …
> fabtests/pytest: a series out improvements

- fabtests/test_configs/udp/udp.exclude
Neither udp or rxd use FI_MSG_PREFIX, disable for udp
> fabtests/test_configs/udp Update Exclude File

- include/ofi_mem.h
- include/ofi_osd.h
- prov/util/src/util_buf.c
This silences a tsan warning that use_cnt is not thread safe.
> core/bufpool: Convert debug use_cnt to an atomic

- prov/tcp/src/tcpx_ep.c
- prov/util/src/util_main.c
Re-arrange endpoint cleanup code to ensure that progress functions
(e.g. reading from the cq) cannot access an endpoint that is
in the process of being destroyed.  Remove the EP from all
progress related lists or poll sets prior to closing the socket or
freeing internal data structures.
This change doesn't fix any known issue; however, there are reports of problems by multi-threaded applications under stress testing where connections are abruptly terminated.  Analyzing whether the current cleanup code can result in problems.
> prov/tcp: Avoid accessing partially destroyed endpoints

- include/ofi_net.h
Reject IP addresses that do not have sin_zero set to 0.  This
will catch malformed IP addresses before they are inserted into
an AV, where sin_zero might contain random/non-zero data.
> core/net: Expand valid IP address check for sin_zero

- fabtests/pytest/conftest.py
On client side, populate_ubertest_command() should added
server_id to command line, but it is passing client_id.
> fabtests/conftest.py: fix a bug in preparing ubertest command

- fabtests/pytest/conftest.py
The command line option usage of fi_multinode is different from
other client/server testing applications. This patch introduced
a new function _populate_multinode_command() to generate correct
command for fi_multinode.
> fabtests/pyetst/conftest.py: fix populate_command for fi_multinode

- prov/efa/src/rxr/rxr_rma.c
EFA provider uses shm provider's write to implement
intra-node write.
Currently, EFA provider always calls shm's fi_writemsg()
to post intranode write request. For fi_writemsg(),
shm provider will write a completion entry. To process shm's
completion entry, EFA needs to create a tx_entry and a
pkt_entry when posting the write request, and use the packet
entry as context.
When application uses inject write, it does not require a completion.
Currently, EFA implement intra-node inject write by deserting the
completion from the shm provider (RXR_NO_COMPLETION flag).
However, it is more efficient to use shm's inject write in this case,
which elliminates the allocation of tx_entry and pkt_entry.
Meanwhile, if shm provider does not need to write completion,
it can chose a more effective …
> prov/efa: use shm's inject write when possible

- prov/shm/src/smr_rma.c
- prov/tcp/src/tcpx_rma.c
- prov/verbs/src/verbs_rma.c
Verify that the source and target buffer lengths are the same for fi_readmsg and fi_writemsg.
Fixes #7418
Uses asserts only, not run time checks, as these are fast paths.  This change is only to help debug apps.
> tcp/verbs/shm: Add assert to check source and target RMA msg lengths match

- fabtests/Makefile.am
- fabtests/pytest/efa/test_av.py
- fabtests/pytest/efa/test_rnr.py
Remove av_xfer test temporarily because of hardware issue.
add RNR tests
> fabtests/pytest/efa: adjust test case

- include/ofi_util.h
- prov/hook/src/hook_domain.c
- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_conn.c
- prov/rxm/src/rxm_domain.c
- prov/verbs/src/fi_verbs.h
- prov/verbs/src/verbs_domain.c
- prov/verbs/src/verbs_ep.c
Credit based flow control only works when both sides support it.
Exchange the information over the connetion manager and disable
flow control if support is missing from either side.
To help this, a new method 'available()' is added to flow_ctrl_ops and
the hook provider is updated to handle this new method.
Fix #6712 
Replace #7480
> prov/rxm,verbs: Negotiate credit based flow control support over CM

- configure.ac
- include/ofi_cuda.h
- include/ofi_hmem.h
- prov/efa/src/efa_domain.c
- prov/efa/src/efa_fabric.c
- prov/efa/src/rxr/rxr_attr.c
- prov/efa/src/rxr/rxr_init.c
- prov/psm3/configure.m4
- prov/util/src/cuda_mem_monitor.c
- prov/util/src/rocr_mem_monitor.c
- src/hmem_cuda.c
- src/hmem_cuda_gdrcopy.c
- src/hmem_rocr.c
Cleanup cuda, rocr, gdrcopy, and neuron config checks to minimize DL dependencies, make consistent defines, and make more readable.
> configure.ac: cleanup device configure checks

- prov/shm/src/smr_msg.c
- prov/shm/src/smr_rma.c
Most sendmsg or writemsg calls with FI_INJECT should work
fine without issues, but an assert is added to make sure we don't
use the IOV protocol.
There is an issue when using FI_INJECT and FI_DELIVERY_COMPLETE
or with hmem IPC enabled since those protocols default to an asynchronous
data copy initiated by the remote side. In order to avoid this
incompatbility, add checks in the IPC and IOV paths to make sure that if
we do need FI_DELIVERY_COMPLETE support and immediately copy the data from
the user buffer, use the SAR protocol which supports both flags.
Fixes #7478
> prov/shm: fix FI_INJECT flag support

- prov/shm/src/smr_atomic.c
The shm data structures are not aligned to support 128-bit
atomics.  Disable support until the structures are analyzed and
alignment can be guaranteed.
Patch also fixes return code for unsupported tagged atomics.
> prov/shm: Remove broken support for 128-bit atomics

- fabtests/pytest/efa/test_rdm.py
The fi_rdm_atomic test's run time has a high variance on
single AWS c6gn instance. The issue is tracked in
https://github.com/ofiwg/libfabric/issues/7002
This patch set the maxiumum timeout of this test to 1800 seconds
while we investigate the root cause.
> fabtests/pytest/efa: set fi_rdm_atomic test timeout to 1800 seconds

- prov/efa/src/rxr/rxr_read.c
- prov/efa/src/rxr/rxr_rma.c
bf291d795 prov/efa: add write context packet to rxr_ep->tx_pkt_list
56a4a4a59 prov/efa: use shm's inject write when possible
99a2aa4df prov/efa: support 0 byte read
c782df679 prov/efa: extract rxr_read_post_once() from rxr_read_post()
> [v1.14.x] prov/efa: back port rma fixes

- contrib/intel/jenkins/Jenkinsfile
removing this cleanup dir function because if two builds are running and one finishes it
will cause the other one to fail with:
stale file handle
file not found
these directories will get deleted during regular jenkins cleanup actions
> contrib/intel/jenkins: remove cleanup directory deletion

- src/fabric.c
Functionality-wise it doesn't matter since the provider will always
be added when ofi_register_provider() is called and the ordering
doesn't affect hooking providers. However, all other providers are
in the list so it makes sense to keep it this way.
> fabric: Add ofi_hook_dmabuf_peer_mem to the ordered provider list

- include/ofi_net.h
- include/ofi_signal.h
- include/windows/osd.h
Build logs are filled with the warning messages since the headers are included
for almost every source file.
windows\osd.h(777,26): warning C4090: 'function': different 'const' qualifiers
windows\osd.h(884,34): warning C4244: 'return': conversion from 'ULONGLONG' to 'long', possible loss of data
windows\osd.h(1039,19): warning C4057: 'function': 'int *' differs in indirection to slightly different base types from 'unsigned int *'
ofi_atom.h(362): warning C4057: 'function': 'volatile long *' differs in indirection to slightly different base types from 'int32_t *'
ofi_signal.h(115,19): warning C4244: '=': conversion from 'ssize_t' to 'int', possible loss of data
ofi_signal.h(147,18): warning C4244: '=': conversion from 'ssize_t' to 'int', possible loss of data
ofi_net.h(180,21): warning …
> include: Fix compiler warnings for Windows build

- include/ofi_shm.h
- prov/shm/src/smr.h
- prov/shm/src/smr_atomic.c
- prov/shm/src/smr_comp.c
- prov/shm/src/smr_ep.c
- prov/shm/src/smr_msg.c
- prov/shm/src/smr_progress.c
- prov/shm/src/smr_rma.c
When the shm provider was first released, it only had
three protocol (inline, inject, iov), making the protocol
selection more or less straightforward. However, as the
provider has developed, three new protocols have been added
(mmap, sar, ipc). The addition of these checks and protocols
has added a lot of complexity to the code, resulting in
very convoluted and hard to follow code with many duplicate
checks.
This patch simplifies all of the protocol code by
isolating each protocol into separate functions, accessible
through an array of function pointers by protocol enum.
These functions are used by the msg, tagged, and rma calls
which all take similar code paths. The atomic calls are
separated since they follow a slightly different pattern
because of the extra atomic/datatype fields. …
> prov/shm: refactor and simplify protocol code

- contrib/intel/jenkins/Jenkinsfile
Abort old builds if a new build gets added to the same job's queue
This will remove the need to abort old builds by hand
It will free up resources more quickly when open PRs have multiple changes pushed in quick succession to only test the latest changes
> contrib/intel/jenkins Cancel Stale Builds

- prov/shm/src/smr_progress.c
If a 0 byte SAR read is issued, the resp->status will
never be updated since it only gets updated in the
copy_to/from_sar path (which will never be taken if there
is no data to copy). To fix this, update the resp->status
when first progressing the SAR message if the message is
complete.
Fixes #7508
> prov/shm: fix 0 byte SAR read

- prov/shm/src/smr_atomic.c
Reported by Coverity.  Given invalid combination of
ofi_op_atomic and FI_ATOMIC_READ, it is possible to reach
code that uses uninitialzed result_iov->iov_len.  Separate
code for ofi_ofi_op_atomic case to avoid the issue.
> prov/shm: Avoid uninitialized variable with invalid atomic parameters

- src/hmem_ze.c
A device may have multiple compute/copy engines that can be used to
perform data copy operations. These engines are organized into groups.
The performance characteristics of the engine groups are not the same
and sometimes the difference can be quite substantial. By default the
first copy-only engine group is used if it is available. However, the
default choice may not fit application specific needs.
Introduce a new environment variable FI_HMEM_ZE_COPY_ENGINE to allow
user to choose a specific engine group (and optionally a specific
engine in that group) to use.
Examples:
export FI_HMEM_ZE_COPY_ENGINE=2		# choose engine group 2
export FI_HMEM_ZE_COPY_ENGINE=2.1	# choose engine group 2, index 1
> hmem_ze: Add runtime option to choose specific copy engine

- fabtests/configure.ac
AC_HELP_STRING was deprecated.
> configure: Replace AC_HELP_STRING with AS_HELP_STRING

- fabtests/Makefile.am
Add sockets.exclude to Makefile.am. It is missing in the install location
> fabtests: Add sockets.exclude to Makefile.am

- prov/shm/src/smr_progress.c
If a 0 byte SAR read is issued, the resp->status will
never be updated since it only gets updated in the
copy_to/from_sar path (which will never be taken if there
is no data to copy). To fix this, update the resp->status
when first progressing the SAR message if the message is
complete.
Cherry-picked from commit 9729ce2285517c6f8e460112b2f035da560e5af5
> [v1.14.x] prov/shm: fix 0 byte SAR read

- fabtests/configure.ac
AC_HELP_STRING was deprecated.
> v1.15.x cherry-pick: configure: Replace AC_HELP_STRING with AS_HELP_STRING

- Makefile.am
- prov/efa/Makefile.include
- prov/efa/configure.m4
- prov/efa/src/efa_av.c
- prov/efa/test/.gitignore
- prov/efa/test/README.md
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
- prov/efa/test/rdma_core_mocks.c
Adding the CMocka framework for unit testing prov/efa.
The unit test I add calls efa_ah_alloc() twice with the same GID, and enforces that the function ibv_create_ah() only gets called once.
> prov/efa: Adding CMocka Framework for unit testing

- fabtests/pytest/efa/test_rdm.py
It is observed that cuda tests requires larger time-out limit (~240 secs)
to test all message sizes for libfabric's debug and mem-poisoning builds, on p4d instances.
Test info: run `runfabtests.py` on 2 c5n and 2 p4n
> fabtests/pytest/efa: Increase timeout limit for cuda tests

- fabtests/pytest/efa/test_multi_recv.py
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_type_misc.c
The PR contains 2 commits that are related to multi-recv:
1st commit added test case that test multi_recv of 8k message, which exposed a bug in EFA's implementation of multi reccv.
2nd commit fixed the bug.
> prov/efa: multi_recv test case and bug fix

- fabtests/common/hmem.c
- fabtests/common/hmem_cuda.c
- fabtests/common/shared.c
- fabtests/include/hmem.h
ft_fill_buf() is used to fill send buffer for data verification.
When the send buffer is on device, ft_fill_buf() will
allocate a host buffer using malloc(), stage the allocated
buffer, then copy data from host buffer to device buffer.
For CUDA, cudaMemcpy() was used to copy data from host buffer
to device buffer.
Accordig to cuda document:
https://docs.nvidia.com/cuda/cuda-runtime-api/api-sync-behavior.html
When host buffer is pageable, cudaMemcpy() "will return once the
pageable buffer has been copied to the staging memory for
DMA transfer to device memory, but the DMA to final destination may
not have completed".
Hence, ft_fill_buff() can cause data corruption on cuda device.
This patch introduced a function ft_hmem_alloc_host(), which will
allocate a host buffer suitable to be used by …
> fabtests/hmem_cuda: used device allocated host buff to fill device buf

- prov/efa/src/rxr/rxr_pkt_type_misc.c
This patch fixed a bug in handle RMA read completion. The
current code did not handle the case that a read completion
is from a multi-recv operation, and did not release resources
used by multi-recv.
(cherry picked from commit c4a74b333acfffdef1d8e6365e801c723cefbe4f)
> [v1.14.x] prov/efa: handle read completion properly for multi_recv

- fabtests/scripts/runfabtests.sh
- fabtests/test_configs/ofi_rxd/ofi_rxd.exclude
- fabtests/test_configs/sockets/sockets.exclude
runfabtests.sh was not properly using the -e flag and wouldn't exclude user input excludes.
sockets now runs quick tests for ubertest because all has failures. See https://github.com/ofiwg/libfabric/issues/7543
sockets now has FI_MSG_PREFIX tests properly disabled
rxd can now run ubertests
> fabtests: Bugfixes to runfabtests.sh and test enabling/disabling

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/tests.py
Only run ubertest,multinode on reg builds.
Allow sockets and udp to run -t all via [PR](https://github.com/ofiwg/libfabric/pull/7546)
Make sockets use quick.test for ubertest in ci because all.test is failing
Re-order the Jenkinsfile pipeline to submit slower tests first so nodes have a higher priority to run those tests first. This will decrease overall runtime.
> contrib/intel/jenkins: Add proper testing for uber,multinode to reduce CI time

- src/fi_tostr.c
Fix incorrect indentation in output from fi_info in the fi_domain_attr section.
on-behalf-of: @cmru-ps <dshinaberry@mru.medical.canon>
> core/fi_tostr: Fix fi_info indentation error

- include/ofi_signal.h
The setting and resetting of a signal is controlled by an
atomic state variable.  However that state is maintained in
user space.  There's a delay between the setting of that state
and the updating of the signal in the kernel (writing a byte
to the signaling socket).  As a result, the two states can
get out of sync, where user space thinks the socket has data
written to it but there's no data there.
Replace the atomic state with a mutex that ensures that
the signal's state and the socket are updated atomically with
respect to other users of the signal.
Hastily thrown together patch to address #7536
> core/signal: Use locks to serialize set/reset of signal

- fabtests/common/hmem_ze.c
- include/ofi_hmem.h
The previous number is 4. We have already encountered systems with more
devices than that. Increase it to 8.
In the long run, we would want to remove this hard-coded limit.
> hmem_ze, fabtests: Increase the number of supported ZE devices

- contrib/intel/jenkins/tests.py
The fi_info test is called with `-f -p <prov>`. There should be
fabric name after the `-f` option.
> contrib/intel/jenkins: Fix fi_info test arguments

- prov/verbs/src/verbs_info.c
Use network interface flags to detect a loopback interface rather than the name of the interface.
The Windows specific getifaddrs in src/windows/osd.c labels every interface with the name eth#. While this function could detect a loopback interface and label it with lo, using flags seemed a more robust option given that interface names can be rather arbitrary.
> prov/verbs: Portable detection of loopback device

- prov/efa/src/rxr/rxr_ep.c
Use `OFI_BUFPOOL_NONSHARED` to allocate the RXR buffer pools.  When fork support is on, registering a buffer with `ibv_reg_mr` will set `MADV_DONTFORK` on the underlying pages.  No data structures needed by the child process created by `fork()` can share these pages.
> prov/efa: Use OFI_BUFPOOL_NONSHARED to allocate RXR buffer pools

- prov/verbs/src/fi_verbs.h
- prov/verbs/src/verbs_cq.c
Switch to use fd_signal for implementing vrb_cq_signal for Windows compatibility because read/write cannot be used on Windows sockets.
on-behalf-of: @cmru-ps <dshinaberry@mru.medical.canon>
> prov/verbs: Windows compatibility for vrb_cq_signal

- prov/util/src/util_mem_monitor.c
The Windows CRTICAL_SECTION is a structure with six fields. All fields initialized with 0 led to a crash when EnterCriticalSection was called in pthread_mutex_lock. The values used were based on the field values after a call to InitializeCriticalSection except for the final field for spin lock count. I figured that might be system dependent, so I opted to use 0 to disable spin lock attempts altogether.
> osd/windows: PTHREAD_MUTEX_INITIALIZER

- fabtests/Makefile.am
- fabtests/common/shared.c
- fabtests/configure.ac
- fabtests/functional/rdm_stress.c
- fabtests/include/shared.h
- fabtests/man/fabtests.7.md
- fabtests/man/man1/fi_rdm_stress.1
- prov/rxm/src/rxm_av.c
- prov/util/src/util_av.c
Stress multi-threaded and multi-process access to an RDM endpoint
with abrupt termination conditions.  This will help verify or
expose race conditions in error handling cases.
This patch defines the general framework of operation and
implements most of the client code.  The server side is still
needed.
The general operation is for the client to parse an input file
describing a set of RPCs to perform.  Each RPC involves sending
a short message to the server.  The server will respond by either
sending a message, a tagged message, or issuing an RMA read or
write operation back to the client.  RMA operations are followed
by a response message.
The client side has a parent process and several child processes.
Child processes are forked from the parent, with each child
executing a set of RPC …
> fabtest/rdm_stress: Add stress test for RDM endpoints

- prov/efa/src/efa_av.c
- prov/efa/src/efa_fabric.c
- prov/efa/src/efa_mr.c
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_atomic.c
- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_init.c
- prov/efa/src/rxr/rxr_msg.c
- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_cmd.h
- prov/efa/src/rxr/rxr_pkt_entry.c
- prov/efa/src/rxr/rxr_pkt_type_misc.c
- prov/efa/src/rxr/rxr_pkt_type_req.c
- prov/efa/src/rxr/rxr_read.c
- prov/efa/src/rxr/rxr_rma.c
Currently, if two endpoints use different shm settings (one enables
shm, the other disable shm), the communication between them
cannot proceed.
This is because when shm is disabled, an endpoint will not create shm
infrastruction. However,its peer does not know that and will try
to use shm with the endpoint.
This patch addressed the issue by always creating shm infrastructures
(endpoint, domain, CQ), and use it for RX operations.
With this patch, enable_shm_transfer means enable the usage shm for
TX operations.
> prov/efa: allow different shm settings between peers

- main/man/index.md
master was renamed, add to main now...
> gh-pages: Add opx to main page list

- prov/util/src/util_buf.c
Fix a warning detected by Coverity.  We check that `page_size` is non-negative.
> core: Fix sign warning in ofi_bufpool_region_alloc

- include/freebsd/osd.h
- include/linux/osd.h
- include/ofi_mem.h
- include/osx/osd.h
- include/unix/osd.h
- include/windows/osd.h
- prov/efa/src/rxr/rxr_ep.c
- prov/util/src/util_buf.c
- src/unix/osd.c
This set of changes is required to fix an issue involving fork support in the efa provider.
All changes apply cleanly (modulo a bit of context fuzz).  Original reviews:
- https://github.com/ofiwg/libfabric/pull/7547
- https://github.com/ofiwg/libfabric/pull/7558
- https://github.com/ofiwg/libfabric/pull/7570
> [v1.14.x] core+efa: backport bufpool mmap changes

- man/fi_opx.7.md
The space is significant here.
> man: Fix header format in fi_opx man page

- fabtests/ubertest/cq.c
When using SELECTIVE_COMPLETION with the writedata function,
ubertest was assuming that this should not generate a completion.
This is true only if RX_CQ_DATA is set (where an RMA data operation
consumes a recv buffer - if that buffer was set to be suppressed,
that should not generate a completion).
This adds a check to return true for an RMA with data if that mode bit
is not set. If it is set, we should drop into the regular SELECTIVE_COMPLETION
checks to see if the completion will be suppressed or not.
> fabtests/ubertest: fix ubertest writedata completion check

- prov/opx/configure.m4
Fixes issues #7573 and #7567 
Disables building OPX if building on a non-x86 machine even if it is running Linux, or if libnuma is not installed.
This should capture all missed dependencies. I went and did an ldd of fi_getinfo and got the list of libraries it depended on and I did not find any more lurking surprises.
> prov/opx: Correctly disable OPX if unsupported.

- fabtests/common/shared.c
- fabtests/man/fabtests.7.md
Update help text for -C option, which is re-used by
fi_rdm_stress, and include in the man page.
> fabtests: Document -C option

- prov/hook/dmabuf_peer_mem/src/hook_dmabuf_peer_mem.c
Indicate that we don't care about the return value from ioctl
by casting the result to (void).  This addresses a coverity
report.
> prov/hook_dmabuf: Cast away ioctl return

- .github/workflows/coverity.yml
Now that Coverity scans have been running relatively well, start sending
nightly reports to the OFIWG devel mailing list. This will mean an
additional email to the list each day, but we will not be spamming users
who will most likely be subscribed to the libfabric-users list.
> coverity: Update notification email

- fabtests/functional/rdm_stress.c
Fixes #7598
Once pthread_create fails, it continues to fail even if all other threads have exited.  There must be some limit to the total number of threads that a single process can spawn.  The test will need to make use of a thread pool to overcome this issue.  And here I was hoping to keep the server relative simple.
> fabtest/rdm_stress: Handle pthread_create errors

- fabtests/functional/rdm_stress.c
- fabtests/include/shared.h
- fabtests/test_configs/ofi_rxm/stress.json
Add support for control file which contains commands to the server.
Same set of commands is used by all clients.
A sample control file is provided - fabtests/test_configs/ofi_rxm/stress.json.
Details on the format is in the comment section at the top of stress.json.
Add check on number of client connections to 128.
> fabtest/rdm_stress: Add control file

- src/hmem_cuda_gdrcopy.c
cuda_gdrcopy_impl() call gdr_copy_from_mapping() with wrong
sequence of arguments. This patch fixed the issue.
(cherry picked from commit 46d11f17505a8b409804fd039c2782883509f22b)
> [v1.15.x] src/hmem_cuda_gdrcopy.c: fix incorrect usage of gdr_copy_from_mapping

- src/hmem_cuda_gdrcopy.c
cuda_gdrcopy_impl() call gdr_copy_from_mapping() with wrong
sequence of arguments. This patch fixed the issue.
(cherry picked from commit 46d11f17505a8b409804fd039c2782883509f22b)
> [v1.14.x] src/hmem_cuda_gdrcopy.c: fix incorrect usage of gdr_copy_from_mapping

- prov/shm/src/smr_signal.h
The shm signal handler cleans up shm allocations and UNIX domain sockets
before handing over to the original signal handler. Previously the orignal
signal handler was not called if it was SIG_DFL.
Change to a simplified logic that covers all scenarios.
Replaces #7285
> prov/shm: Properly chain the original signal handlers

- fabtests/functional/rdm_stress.c
The pthread_create call will fail repeatedly after X number of
threads have been created by the server, even if those threads
are no longer running.  We can either configure the threads to
run in a detached state, so that the system resources are auto-
matically cleaned up, or use a pool of threads to execute the
RPCs.  We use the latter to avoid the overhead of thread
creation as well as put strain on the main CQ read function.
> fabtests/rdm_stress: Rework threading model on server

- fabtests/include/shared.h
- fabtests/ubertest/config.c
When using strncmp with a non-null termianted string,
it may compare unintended characters and return a match.
Compare length of the the two strings before strncmp to
ensure exact match.
> fabtests/ubertests: Fix string comparison to include length

- prov/util/src/util_attr.c
prov/util:  set return code when memory allocation files in ofi_info_to_core().
> prov/util: Fixed return code when memory allocation fails.

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/build.py
- contrib/intel/jenkins/tests.py
Add IMB-NBC test back
Add cleanup of the workspace directory on successful only builds
Add an opt-out feature to allow the intel-jenkins-ci to only run for necessary changes
> contrib/intel/jenkins: Add an opt-out feature, tests, and better cleanup

- .github/workflows/nroff-elves.sh
- .github/workflows/nroff-elves.yaml
Cron scheduled actions are only triggered from the default branch (main).
Change to push activated action so that the man pages on stable branches
can also be properly updated.
Use a more descriptive name for the action.
> workflow: Change nroff-elves.yaml from cron job to on-push action

- .github/workflows/nroff-elves.sh
- .github/workflows/nroff-elves.yaml
Cron scheduled actions are only triggered from the default branch (main).
Change to push activated action so that the man pages on stable branches
can also be properly updated.
Use a more descriptive name for the action.
> [v1.15.x] workflow: Change nroff-elves.yaml from cron job to on-push action

- .github/workflows/nroff-elves.sh
- .github/workflows/nroff-elves.yaml
Cron scheduled actions are only triggered from the default branch (main).
Change to push activated action so that the man pages on stable branches
can also be properly updated.
Use a more descriptive name for the action.
> [v1.14.x] workflow: Change nroff-elves.yaml from cron job to on-push action

- .github/workflows/nroff-elves.sh
- .github/workflows/nroff-elves.yaml
Cron scheduled actions are only triggered from the default branch (main).
Change to push activated action so that the man pages on stable branches
can also be properly updated.
Use a more descriptive name for the action.
> [v1.13.x] workflow: Change nroff-elves.yaml from cron job to on-push action

- fabtests/functional/rdm_stress.c
There are multiple server threads posting receives on the same receive
queue. Receive completion polled from one thread doesn't necessarily
match the receive posted in the same thread. Processing the wrong buffer
could lead to various errors including hang and segfault.
The correct buffer is available as the op_context of the completion
event.
> fabtest/rdm_stress: Use correct buffer to process recv completion

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/build.py
remove opx and efa from ci builds
move opt-out feature to its own stage to be able to opt out of everything
update the skip.sh script to allow PRs to push to any ofiwg/libfabric branch
> contrib/intel/jenkins: remove opx & efa from ci builds, update opt-out feature

- man/fi_mr.3.md
Add a missing bullet for `neuron` in `fi_mr_attr.device`.
> man: add description of `neuron`.

- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_cq.c
If we have a wait object associated with a CQ, signal it.
This fixes possible hangs with applications blocking on
the wait fd.
> prov/rxm: Signal CQ fd after writing completion

- contrib/intel/jenkins/tests.py
Enable mpich and impi osu tests for verbs
> contrib/intel/jenkins: enable verbs mpich and impi osu tests

- prov/tcp/src/tcpx_ep.c
The TCP provider sometimes fails the following assertion:
prov/tcp/src/tcpx_cq.c:69: tcpx_cq_progress: Assertion `ep->state == TCPX_CONNECTED' failed.
tcpx_cq_progress() expects data to be received from a connected endpoint
if 'ep->cur_rx.handler != NULL' and 'ep->cur_rx.entry == NULL'.
However, GDB gives a clear evidence that the EP is disconnected but 'cur_rx'
was not correctly reset:
(gdb) print ep->state
$1 = TCPX_DISCONNECTED
(gdb) print ep->cur_rx->entry
$2 = (struct tcpx_xfer_entry *) 0x0
(gdb) print ep->cur_rx->handler
$3 = (int (*)(struct tcpx_ep *)) 0x7ffff7ecce20 <tcpx_op_msg>
The problem occurs because tcpx_ep_flush_all_queues() resets 'cur_rx'
only if 'cur_rx.entry != NULL'. However, cur_rx.entry may be NULL,
but cur_rx.handler may contain a valid pointer according to GDB. …
> prov/tcp: Fix assertion failure in CQ progress function

- Makefile.am
- include/ofi_hmem.h
- include/ofi_mr.h
- include/rdma/fi_domain.h
- libfabric.vcxproj
- libfabric.vcxproj.filters
- man/fi_mr.3.md
- src/hmem.c
- src/hmem_synapseai.c
This PR adds a new hmem iface `FI_HMEM_SYNAPSEAI` for Habana Gaudi devices.
As an initialization step, this PR only defines dummy `hmem_ops` api functions for `FI_HMEM_SYNAPSEAI` which return `FI_ENOSYS` before real implementations.
> hmem: Introduce FI_HMEM_SYNAPSEAI API to libfabric

- prov/tcp/src/tcpx_ep.c
The TCP provider sometimes fails the following assertion:
prov/tcp/src/tcpx_cq.c:69: tcpx_cq_progress: Assertion `ep->state == TCPX_CONNECTED' failed.
tcpx_cq_progress() expects data to be received from a connected endpoint
if 'ep->cur_rx.handler != NULL' and 'ep->cur_rx.entry == NULL'.
However, GDB gives a clear evidence that the EP is disconnected but 'cur_rx'
was not correctly reset:
(gdb) print ep->state
$1 = TCPX_DISCONNECTED
(gdb) print ep->cur_rx->entry
$2 = (struct tcpx_xfer_entry *) 0x0
(gdb) print ep->cur_rx->handler
$3 = (int (*)(struct tcpx_ep *)) 0x7ffff7ecce20 <tcpx_op_msg>
The problem occurs because tcpx_ep_flush_all_queues() resets 'cur_rx'
only if 'cur_rx.entry != NULL'. However, cur_rx.entry may be NULL,
but cur_rx.handler may contain a valid pointer according to GDB. …
> [v1.14.x] prov/tcp: Fix assertion failure in CQ progress function

- prov/tcp/src/tcpx_ep.c
The TCP provider sometimes fails the following assertion:
prov/tcp/src/tcpx_cq.c:69: tcpx_cq_progress: Assertion `ep->state == TCPX_CONNECTED' failed.
tcpx_cq_progress() expects data to be received from a connected endpoint
if 'ep->cur_rx.handler != NULL' and 'ep->cur_rx.entry == NULL'.
However, GDB gives a clear evidence that the EP is disconnected but 'cur_rx'
was not correctly reset:
(gdb) print ep->state
$1 = TCPX_DISCONNECTED
(gdb) print ep->cur_rx->entry
$2 = (struct tcpx_xfer_entry *) 0x0
(gdb) print ep->cur_rx->handler
$3 = (int (*)(struct tcpx_ep *)) 0x7ffff7ecce20 <tcpx_op_msg>
The problem occurs because tcpx_ep_flush_all_queues() resets 'cur_rx'
only if 'cur_rx.entry != NULL'. However, cur_rx.entry may be NULL,
but cur_rx.handler may contain a valid pointer according to GDB. …
> [v1.15.x] prov/tcp: Fix assertion failure in CQ progress function

- contrib/intel/jenkins/build.py
make skip.sh default to use upstream/main instead of upstream/GIT_BRANCH
upstream/GIT_BRANCH fills GIT_BRANCH with the user's branch name which doesnt match with anything
in private jobs
> contrib/intel/jenkins: make skip.sh default to upstream/main

- fabtests/pytest/pytest.ini
This patch set default values for the junit_xml file written by
runfabtests.py, include test_suite name, whether to save log
for passed test.
> fabtests/pytest/pytest.ini: adjust default behavior of junit_xml

- prov/opx/configure.m4
C11 atomics are required to build the OPX provider.
> prov/opx: Disable if no compiler atomics

- prov/opx/configure.m4
C11 atomics are required to build the OPX provider.
> [v1.15.x] prov/opx: Disable if no compiler atomics (cherry-picked)

- include/ofi_abi.h
Signed-off-by: Theofilos Manitaras <manitaras@cscs.ch>
This PR fixes a problem with the inline assembly when using the Nvidia HPC compilers. The error is the following:
```
<inline asm>:1:64: error: unknown token in expression
.symver fi_freeinfo_,fi_freeinfo@@FABRIC_1.3.symver fi_getinfo_,fi_getinfo@@FABRIC_1.3.symver fi_dupinfo_,fi_dupinfo@@FABRIC_1.3.symver fi_fabric_,fi_fabric@@FABRIC_1.1.symver fi_version_,fi_version@@FABRIC_1.0.symver fi_open_,fi_open@@FABRIC_1.5.symver fi_strerror_,fi_strerror@@FABRIC_1.0
```
So the Nvidia compiler does not produce separate lines for each `asm` use.
The error can be easily reproduced using just a single two line source code `test.c`:
```
__asm__(".symver foo,foo@VER_1");
__asm__(".symver bar,bar@VER_2");
```
```
$ nvc -c test.c
<inline asm>:1:33: …
```
> Fix inline assembly for the Nvidia HPC compilers

- man/fi_opx.7.md
- man/man7/fi_opx.7
Update documentation for new default values for the ENVs:
FI_OPX_RELIABILITY_SERVICE_USEC_MAX: from 100 to 500
FI_OPX_RELIABILITY_SERVICE_PRE_ACK_RATE: from 0 to 64
Signed-off by: Tim Thompson (tim.thompson@cornelisnetworks.com)
> man: Update OPX man page with new default settings

- prov/efa/docs/efa_rdm_protocol_v4.md
According to at least a couple sites on the Internet and the behavior
of the MacDown rendering engine, table syntax is 3 or more dashes in
the dividing between header and table.
Fix a couple of places where constants with underscores were not
in backticks.
Signed-off-by: Brian Barrett <bbarrett@amazon.com>
> efa: Fix markdown formatting in docs

- prov/efa/Makefile.include
- prov/efa/configure.m4
Sets RPATH when the user specifies a cmocka install directory with the --enable-efa-unit-test argument.
> prov/efa: Adding RPATH to EFA Unit Test Executables

- include/ofi_abi.h
- man/fi_opx.7.md
- man/man7/fi_opx.7
[Fix inline assembly for the Nvidia HPC compilers](https://github.com/ofiwg/libfabric/commit/4e62d88ce38d735ebd20999257e304064d5cd710)
[man: Update OPX man page with new default settings](https://github.com/ofiwg/libfabric/commit/1659bb4fffb25e135aeb8984bbfec230b6ba20c7)
> [v1.15.x] cherry-picked

- include/ofi_abi.h
Fixes a problem with the Nvidia compiler, which does not emit
separate lines for multiple `asm` inline assembly declarations.
Signed-off-by: Theofilos Manitaras <manitaras@cscs.ch>
> [v1.14.x] cherry-picked Fix inline assembly for the Nvidia HPC compilers

- include/rdma/fabric.h
- include/rdma/fi_ext.h
- man/fi_av.3.md
- man/fi_getinfo.3.md
- man/fi_peer.3.md
There are 2 patches in this PR.  The first patch replaces the FI_IMPORT_PEER flag with 2 flags: FI_PEER_CQ and FI_PEER_SRX.  The new flags are defined such that these could also be used as capability bits.  However, I didn't document them as capability bits at the moment.  I want to see if that would actually be needed.
The second patch introduces a new feature to the AV, FI_AV_USER_ID.  This allows the user to assign a user-specified id or context with an address.  That id is returned as part of any completion in place of the AV defined fi_addr_t value.  Besides the addition of the new flag, the AV APIs are unchanged, though the use of the flag does modify the behavior of the AV insert calls.
> core/peers: Peer provider support part 2

- fabtests/Makefile.am
- fabtests/prov/efa/Makefile.include
- fabtests/prov/efa/src/efa_info_test.c
- fabtests/pytest/efa/test_efa_info.py
- prov/efa/src/efa_fabric.c
Previously we used our device GID as fabric id, which
is not an appropriate coupling. Since our GID does not
contain information to indicate connectivity, we use a
static/constant fabric id instead.
> prov/efa: Decouple device from fabric id

- Makefile.am
- include/ofi.h
- include/rdma/fabric.h
- include/rdma/fi_ext.h
- include/rdma/providers/fi_log.h
- man/fi_fabric.3.md
- man/fi_provider.3.md
- src/fabric.c
- src/fi_tostr.c
- src/log.c
This PR allows for an application to override the logging functions using fi_open()/fi_import_fid()
Fixes #6525
> log: Logging functions can be imported with fi_import_fid()

- include/ofi_epoll.h
- src/common.c
- src/unix/osd.c
- src/windows/osd.c
The mdtest benchmark is showing significant performance regressions
as a result of commit 7ec82992.  That commit replaced a compact
pollfd array, where all entries are valid, with a sparsely filled
array.  This removed a linear search through the array in order
to update events.
Rather than revert the above commit, we separate the pollfd
context array and pollfd array.  The fd may still be used to
directly index into the context array.  The context structure is
updated to store the corresponding index where the fd is located
in the pollfd array.  This avoids the linear search while
maintaining a compact array.
As a result of these changes, it becomes possible to support
the hot fd array on windows.  Add that as part of this change in
order to align the unix and windows implementations …
> core/pollfds: Use a compact pollfd array

- prov/efa/src/efa_fabric.c
Previously we used our device GID as fabric id, which
is not an appropriate coupling. Since our GID does not
contain information to indicate connectivity, we use a
static/constant fabric id instead.
(cherry picked from commit cf35e27d62d6c0cfe037b339ab7497e845ca1d4f)
> [v1.14.x] prov/efa: Decouple device from fabric id

- fabtests/Makefile.am
- fabtests/prov/efa/Makefile.include
- fabtests/prov/efa/src/efa_info_test.c
- fabtests/pytest/efa/test_efa_info.py
- prov/efa/src/efa_fabric.c
Previously we used our device GID as fabric id, which
is not an appropriate coupling. Since our GID does not
contain information to indicate connectivity, we use a
static/constant fabric id instead.
(cherry picked from commit cf35e27d62d6c0cfe037b339ab7497e845ca1d4f)
> [v1.15.x] prov/efa: Decouple device from fabric id

- libfabric.vcxproj
- prov/efa/Makefile.include
- prov/efa/src/efa.h
- prov/efa/src/efa_domain.c
- prov/efa/src/efa_ep.c
- prov/efa/src/efa_fabric.c
- prov/efa/src/efa_fork_support.c
- prov/efa/src/efa_fork_support.h
- prov/efa/src/efa_hmem.c
- prov/efa/src/efa_hmem.h
- prov/efa/src/efa_mr.c
- prov/efa/src/efa_mr.h
- prov/efa/src/efa_msg.c
- prov/efa/src/rxr/rxr_atomic.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_init.c
- prov/efa/src/rxr/rxr_msg.c
- prov/efa/src/rxr/rxr_pkt_type_base.c
- prov/efa/src/rxr/rxr_pkt_type_misc.c
- prov/efa/src/rxr/rxr_pkt_type_req.c
- prov/efa/src/rxr/rxr_read.c
- prov/efa/src/rxr/rxr_rma.c
This patch moved hmem support status checking, fork_support into separate files. Also moved everything related to MR to efa_mr.c/h.
> prov/efa: split hmem_support_status/mr/fork_support  into seperate header/source files

- prov/efa/src/efa_av.c
- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_cq.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_init.c
- prov/efa/src/rxr/rxr_msg.c
- prov/efa/src/rxr/rxr_pkt_type_data.c
- prov/efa/src/rxr/rxr_pkt_type_misc.c
- prov/efa/src/rxr/rxr_pkt_type_req.c
- prov/efa/src/rxr/rxr_rma.c
The credit calculation in flow control in long-CTS message protocol
is not actually being used because the default tx_min_credits yieds
better bandwidth.
This patch removed it to simplify the code.
> prov/efa: remove unused credit calculation

- include/ofi_epoll.h
- src/common.c
- src/unix/osd.c
- src/windows/osd.c
Updates to fix performance regression relative to v1.12 as a result of using a sparse pollfd array.
> [v1.15.x] [picked] core/pollfds: Use a compact pollfd array 

- prov/efa/src/efa_hmem.c
In efa_hmem_support_status_update_all(), the return value of
efa_hmem_support_status_update_neuron() should be saved in err,
not ret. This patch fixed the issue.
> prov/efa: fix the variable usage in efa_hmem_support_status_update_all()

- prov/efa/configure.m4
prov/efa/configure.m4: Make UTs configure work cross platform, and fix RPATH
> prov/efa/configure.m4: Make EFA Unit Test Configure Cross Platform

- prov/efa/src/efa_hmem.c
domain is not an input argument of the function after the
refactor commit 3b2357b22ce469. the device_caps and ibv_pd
should be accessed via g_device_list.
> prov/efa: Fix a bug in efa_hmem_support_status_update_neuron

- src/fi_tostr.c
Add missing cases for FI_HMEM_NEURON and FI_HMEM_SYNAPSEAI
> fi_tostr: Add missing hmem ifaces.

- src/fi_tostr.c
(cherry picked from commit a4e0bb1dac99b4315d8bcb2f0d77a704ff70d70c)
> [v1.15.x] fi_tostr: add missing hmem iface for neuron

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/common.py
- contrib/intel/jenkins/runtests.py
- contrib/intel/jenkins/tests.py
- fabtests/test_configs/psm3/psm3.exclude
- Adding psm3 provider testing to the CI.
- fi_info -f <fabric> option for psm3 results in failure because mlx5 is not considered 
as a supported fabric name. Hence removed -f option for psm3.
- Three tests are hanging and hence failing for psm3: fi_cq_data, fi_rdm_tagged_peek 
and fi_dgram_waitset. These tests are added to the exclude file until the bug is resolved.
An issue is open on github for the same.
- opx provider was built in libfabric but we do not support/test it and hence removed 
it from the CI build resulting in 6 minutes shorter build time.
> contrib/intel/jenkins: Add psm3 provider testing to CI

- include/ofi.h
- include/rdma/providers/fi_log.h
- prov/mrail/src/mrail.h
- prov/netdir/src/netdir_log.h
- prov/opx/src/test/test_hfi_select.c
- prov/rstream/src/rstream.h
- prov/sockets/include/sock_util.h
- prov/usnic/src/usdf.h
- prov/util/src/util_ns.c
- src/perf.c
- src/unix/osd.c
- src/windows/osd.c
Patch a33a3e577("log: Add the provider header files to the
installation") added the header file fi_log.h to the installation.
Problem is that fi_log.h depends on contrib.h, but the application
cannot find it because it's not installed.
The fix implemented in the patch is to remove the inclusion of fi_log.h
and make FI_DBG() usable even if lifbabric is not compiled in debug
mode. Now that applications can import their own logging callbacks,
it makes sense to always intercept FI_LOG_DEBUG log messages anyway.
> log: remove dependency to config.h from fi_log.h

- prov/opx/include/opa_service.h
- prov/opx/src/fi_opx_init.c
- prov/opx/src/fi_opx_service.c
Fix bug in opx provider where it was returning itself as
a provider choice on systems with no Omnipath hardware.
ofiwg/libfabric Github Issue #7715
Signed-off-by: Tim Thompson <tim.thompson@cornelisnetworks.com>
> prov/opx: Do not return opx as a provider on systems without hardware

- fabtests/scripts/runmultinode.sh
Script allows for fast running of many copies of fi_multinode.
./runmultinode.sh -n <ppn> -h <n1,n2,...> -p <provider> -C <pattern>
-I <iterations> --cleanup (optional)
--cleanup is used to kill all extra processes, possibily on a stuck
run of the test suite. A host list is still required for --cleanup
> fabtests/scripts: add runmultinode.sh

- fabtests/common/windows/getopt.c
Fixed a windows bug that caused the first long option to not be processed.
> fabtests/getopt: Ensure that first option is processed

- prov/verbs/src/verbs_info.c
ibv_close_device() must be called after a successful call to ibv_open_device().
> prov/verbs: Fix a memory leak in vrb_get_sib()

- fabtests/common/shared.c
- fabtests/include/unix/osd.h
- fabtests/include/windows/osd.h
- fabtests/multinode/src/harness.c
- Add calls to ft_startup where needed to ensure WinSock is started on windows
- Change close calls to portable ft_close_fd calls
- Change send/recv calls to portable ofi_[send/recv]_socket calls
- Use ofi_sockerr instead of errno to obtain failure codes from socket calls
- Add necessary OS dependent functions to osd.h to achieve above items
> fabtests/sockets: Make socket calls portable

- prov/hook/hook_hmem/src/hook_hmem.c
- prov/rxm/src/rxm_rma.c
- prov/tcp/src/tcpx_ep.c
- src/common.c
Include IP address as part of addr_list sorting to prioritize ipv4 over ipv6, to make results more consistent.
Update hook_hmem provider version to align with other providers.
Add log message on connect() failures for debug purposes.
Remove use of OFI_UNLIKELY in likely rxm code checks.
> prov/tcp + minor adjustments

- prov/util/src/util_ns.c
On Windows, getaddrinfo returned IPv6 addresses before IPv4 addresses leading
to the name server being started on an IPv6 address. However, name server
clients were attempting to connect to an IPv4 address for the name server.
Trying IPv4 addresses before IPv6 addresses leads to more deterministic
behavior.
> prov/util: Try IPv4 before IPv6 addresses when starting name server

- fabtests/pytest/efa/test_rnr.py
Older efa kernel driver does not support RNR retry capability
and the test will return FI_ENOSYS. Disable the strict mode for
this test explicitly to mark it as skipped in this case.
Test info
`./runfabtests --strict -b -p <bin_path> efa <server_ip> <client_ip>`
Tested on efa instances that have efa kernel support rnr_retry, `test_rnr*` tests passed
Tested on efa instances that have efa kernel not support rnr_retry, `test_rnr*` tests skipped
> fabtests/efa: do not run efa rnr test with strict mode

- contrib/intel/jenkins/tests.py
Verbs osu tests are hanging and causing seg faults. Suspected issue is mlnx 5.5 needs to upgrade to mlnx 5.6 for the RDMA core.
psm3 ubertest is failing also due to the suspected 5.5->5.6 issue.
> contrib/intel/jenkins: disable failing tests [verbs osu, psm3 ubertest]

- src/windows/osd.c
The implementation of ofi_pollfds_do_del() does not work with
the windows version of pollfds when removing an entry from the
middle of the fds.  The issue is that the fds[] and ctx[]
arrays are kept in sync, unlike linux.  So, when swapping an
fds[] entry we also need to swap the ctx[] entries.
To fix, we update the windows implementation to allow the
fds[] and ctx[] arrays to be independent from each other.  When
allocating a ctx[], we search the array for an unused entry.
The get_ctx[] call is also updated to search all ctx[] entries,
since the matching ctx may be beyond the nfds count.
> core/pollfds: Fix windows ofi_pollfds_do_del()

- prov/rxm/src/rxm.h
The windows msvc compiler interprets a 2-bit wide bit field enum as a signed
value. Explicitly cast to unsigned and mask off any remaining sign bits to
obtain behavior from msvc that is equivalent to gcc.
On-behalf-of: https://github.com/cmru-ps <dshinaberry@mru.medical.canon>
> prov/rxm: Cast bit-field to avoid signed behavior on windows

- Makefile.am
- prov/psm3/Makefile.include
Adds new variable which allows providers to add to EXTRA_DIST if needed.
Follows man page example.
Fixes: #7735
> prov/psm3: Add missing files to make dist tarball

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/build.py
Make Jenkins checkout upstream ofiwg/libfabric and run the contrib/intel/jenkins python scripts from there.
This will remove the potential for someone to 'hijack' our CI for 'free labor' by manipulating our python scripts and having the ones from their PR run directly on the CI.
> contrib/intel/jenkins: Security Update

- include/ofi_lock.h
ofi_wait_cond is an abstraction based on the OS, however it
takes as input the raw mutex.  Abstract ofi_wait_cond, so that
callers can use the ofi_mutex_t instead, which differs based on
release vs debug build.
> core: Abstract ofi_wait_cond call

- include/ofi_util.h
- prov/util/src/util_av.c
An MPI test failed because it called fi_av_insert() with a count
of 0 and an invalid address.  Because the address was invalid, the
code assigned it an address length of 0.  This in turn resulted in
the AV setting its internal addrlen to 0, since 0 was smaller than
the current address.
To fix this issue and make the code more robust, define a new
internal AV flag.  When set, it indicates that the addrlen needs
to be determined based on the first address insertion.  After
setting the addrlen, clear the flag to prevent further updates.
As part of the change, we enhance the checks and fail addresses
that are an incorrect length.
> util/av: Handle NULL address insertion

- include/ofi_util.h
- prov/util/src/util_av.c
An MPI test failed because it called fi_av_insert() with a count
of 0 and an invalid address.  Because the address was invalid, the
code assigned it an address length of 0.  This in turn resulted in
the AV setting its internal addrlen to 0, since 0 was smaller than
the current address.
To fix this issue and make the code more robust, define a new
internal AV flag.  When set, it indicates that the addrlen needs
to be determined based on the first address insertion.  After
setting the addrlen, clear the flag to prevent further updates.
As part of the change, we enhance the checks and fail addresses
that are an incorrect length.
> [v1.15.x] util/av: Handle NULL address insertion

- contrib/intel/jenkins/Jenkinsfile
MLNX+HDR is broken for the multiclient test when using the HDR cards.
This issue needs to get investigated more before allowing these tests to
be run with HDR and EDR
> contrib/intel/jenkins: Force verbs;ofi_rxd and psm3 to run on mlnx+edr

- contrib/intel/jenkins/common.py
- contrib/intel/jenkins/run.py
- contrib/intel/jenkins/tests.py
All tests that need to select an interface (every provider except shm) now explicitly select their interface.
This will allow us to know exactly what tests are doing when they run.
common.py has been refactored to follow other py files' style.
OSU tcp tests have been re-enabled for impi since they are now passing.
The general execute condition is being removed because it created a redundant check.
As usual - the ci will be aborted and replayed removing the py_scripts file path from the Jenkinsfile to ensure the changed scripts are being used.
> contrib/intel/jenkins: Interface Selection, tcp-osu-impi enabled, code cleanup

- prov/verbs/include/windows/verbs_nd.h
- prov/verbs/src/windows/verbs_nd_ibv.c
- prov/verbs/src/windows/verbs_nd_ov.c
- prov/verbs/src/windows/verbs_nd_rdma.c
- Move checking of pending asynchronous callbacks into the overlapped structure
and add locking to prevent race conditions between rdma/ibv functions and
asynchronous completion callbacks.
- Add support to ibv_post_send for opcodes IBV_WR_RDMA_READ/WRITE.
- Improve disconnect handling by better distinguishing between host initiated
disconnect and peer initiated disconnect and removing some race conditions.
> prov/verbs_nd: Various fixes for test failures and minor feature additions

- fabtests/common/shared.c
- fabtests/functional/rdm_stress.c
- fabtests/include/shared.h
- fabtests/test_configs/ofi_rxm/stress-rd.json
- fabtests/test_configs/ofi_rxm/stress-wr.json
- include/ofi_mem.h
- include/ofi_util.h
- prov/rxm/src/rxm_av.c
- prov/rxm/src/rxm_conn.c
- prov/rxm/src/rxm_cq.c
- Add new input control files for rdm_stress
- Add general fabtests timeout command line option, used for rpc timeout
- Update rxm error logging to reduce noise, use sparse logging
- Add debug assert option to convert asserts into busy loops (to attach a debugger)
- Modify rdm_stress to remove AV entries for clients that are not reachable
> fabtests: Enhancements to fabtests and rdm_stress specifically

- fabtests/benchmarks/dgram_pingpong.c
This patch makes dgram_pingpong to always use out-of-band
sync method, because dgram endpoing is unreliable thus cannot
be used for sync.
> fabtests/dgram_pingpong.c: use out-of-band sync

- contrib/intel/jenkins/Jenkinsfile
Sometimes jenkins cannot find the py_scripts folder because it was getting created in runtime_location@2/pyscripts instead of runtime_location/py_scripts. Making it explicit will remove this issue.
> contrib/intel/jenkins: Make py_scripts folder explicit to the env.WORKSPACE

- prov/efa/src/efa_domain.c
This patch fix a bug in the error handling path of efa_domain_open().
which is that output domain_fid was not set to back to NULL.
> prov/efa: set domain_fid to NULL on error.

- src/hmem_cuda_gdrcopy.c
This patch fixed a bug in cuda_gdrcopy_hmem_init(), which
is that cuda_gdrcopy_dl_hmem_cleanup() was called even when
the initialization was successful.
> src/hmem_gdrcopy: do not cleanup on successfully initialization

- prov/psm3/configure.ac
Substring substitution is bash extension. Use "remove smallest prefix
pattern" substitution instead.
Reference: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_05_03
> prov/psm3: avoid bashism in configure

- src/hmem_cuda_gdrcopy.c
This patch fixed a bug in cuda_gdrcopy_hmem_init(), which
is that cuda_gdrcopy_dl_hmem_cleanup() was called even when
the initialization was successful.
(cherry picked from commit 6da37d5df70b6708565a735a3a920e6429588190)
> [v1.14.x] src/hmem_gdrcopy: do not cleanup on successfully initialization

- src/hmem_cuda_gdrcopy.c
This patch fixed a bug in cuda_gdrcopy_hmem_init(), which
is that cuda_gdrcopy_dl_hmem_cleanup() was called even when
the initialization was successful.
(cherry picked from commit 6da37d5df70b6708565a735a3a920e6429588190)
> [v1.15.x] src/hmem_gdrcopy: do not cleanup on successfully initialization

- fabtests/Makefile.am
- fabtests/include/shared.h
- fabtests/regression/shm_sighandler_test.c
The test checks if the default signal handler is properly chained in the
handler installed by the shm provider.
> fabtests: Add regression test for shm sighandler restoration (PR#7605)

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/run.py
- contrib/intel/jenkins/runtests.py
- contrib/intel/jenkins/tests.py
- Add OneCCL examples and functional test suites in GPU mode
to libfabric CI.
- Tests run with tcp provider only. There is an issue with
OFI MPI init hook while running tests with psm3 provider.
This needs to be investigated separately.
- One of the functional tests (allreduce_test) is not added
as it is resulting in a segmentation fault. OneCCL team
needs to be consulted for this issue.
- Takes 1 min 42 secs to complete.
> contrib/intel/jenkins: Add OneCCL GPU tests to CI

- include/ofi_shm.h
- prov/shm/src/smr.h
- prov/shm/src/smr_ep.c
- prov/shm/src/smr_init.c
- prov/shm/src/smr_signal.h
Currently, any use of libfabric will cause shm to add its
signal handlers, even if shm is not being used.
This moves the signal handler initialization to fi_endpoint so
we only add them if they are needed.
The old_action free is kept in the shm FINI call since we need
to wait for all EPs to be closed.
This also fixes a typo in the function smr_reg_sig_handler and
fixes some function and variable definition inconsistencies.
> prov/shm: move shm signal handlers initialization to EP

- fabtests/Makefile.win
- fabtests/fabtests.vcxproj
- fabtests/fabtests.vcxproj.filters
- fabtests/include/windows/arpa/inet.h
- fabtests/include/windows/osd.h
- fabtests/include/windows/sched.h
- fabtests/include/windows/unistd.h
- Adds most of the tests handled by linux to the msvc project files
- Adds build commands to the windows nmake makefile
- Add/Modify windows specific include files to provide declarations/definitions
used by the newly built tests
> fabtests: Build verbs related tests on windows

- include/windows/unistd.h
Change the implementation of the windows specific implementation of
usleep to actually sleep and guarantee and relinquishment of the
cpu rather than spin.
> osd-windows/usleep: Modify usleep to sleep rather than spin

- fabtests/functional/rdm_stress.c
- fabtests/test_configs/ofi_rxm/stress.json
Add use of fi_inject() to the server.
> fabtests/rdm_stress: Add support for inject operations

- fabtests/scripts/runfabtests.py
good_address is passed to pytest through shared_options, therefore
there is not need to add it to pytest_args separately.
Signed-off-by: Anas Mousa <anasmous@amazon.com>
> fabtests/runfabtests.py: remove unnecessary good_address argument

- prov/efa/src/rxr/rxr.h
- prov/efa/src/rxr/rxr_pkt_type.h
- prov/efa/src/rxr/rxr_pkt_type_misc.c
Currently, RXR_EOR_IN_FLIGHT was set when EOR was sent successfully
which caused the rx_entry to be released when EOR was queued, and
the queued EOR packet cannot be sent successfully.
This patch fixed the issue by setting RXR_EOR_IN_FLIGHT in
rxr_pkt_handle_rma_read_completion().
> prov/efa: fix the setting of RXR_EOR_IN_FLIGHT

- prov/shm/src/smr_attr.c
- prov/shm/src/smr_init.c
In smr_getinfo, we perform a post-getinfo check that the FI_MR_HMEM
mr_mode bit is set correctly if FI_HMEM has been requested.  However,
there may be valid fi_info structures to return.  By failing
the smr_getinfo call, we leak those structures and fail to return
them as valid.
To fix this we add a domain_attr to pair with the FI_HMEM info
structures, so that util_getinfo can handle the filtering.
> prov/shm: Fix check for FI_MR_HMEM mr_mode

- .appveyor.yml
- fabtests/functional/rdm_multi_client.c
- fabtests/functional/unexpected_msg.c
- fabtests/scripts/runfabtests.cmd
Brings a significant amount of the functionality of runfabtests.sh to
runfabtests.cmd in order to run tests on the verbs provider on windows
in a similar fashion to linux.
> fabtests/runfabtests.cmd: Rewrite to be more like runfabtests.sh

- prov/efa/Makefile.include
- prov/efa/src/efa_av.c
- prov/efa/src/efa_device.c
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
- prov/efa/test/rdma_core_mocks.c
In function efa_device_construct()'s error handling path, resources
(like ibv_ctx) were released, but the pointer was not reset to NULL,
which can caused double free. This patch addressed the issue.
> prov/efa: fix bug in error handling in efa_device_construct()

- prov/psm3/Makefile.am
This fixes an undefined symbol that can result if you build
libpsm3-fi.so from inside prov/psm3.
Signed-off-by: Michael Heinz <michael.heinz@intel.com>
> prov/psm3 Added missing reference to neuron_init.

- prov/efa/src/rxr/rxr_pkt_type_req.c
rxr_pkt_init_runtread_rtm() need to get peer from address. Currently,
it is using pkt_entry->addr, which is wrong because pkt_entry->addr
has not been initialized when the function was called.
This patch fixed the issue by using "tx_entry->addr"
> prov/efa: fix wrong usage of address in rxr_pkt_init_runtread_rtm()

- contrib/intel/jenkins/run.py
- contrib/intel/jenkins/tests.py
contrib/intel/jenkins: disable ze-shm stage while we investigate failures
> contrib/intel/jenkins: disable ze-shm stage while we investigate failures

- fabtests/regression/sighandler_test.c
The test waits for the provider to complete initialization which includes posting
a receive buffer using fi_recv. This ensures the provider anticipates the fi_recv
call and sets the mode bit to support more providers.
> fabtests/sighandler_test: set caps and mode

- prov/shm/src/smr_msg.c
Fixes incorrect use of "peer_id" to "id" when checking sar_status of local
endpoint; in smr_generic_sendmsg path.
Signed-off-by: Jorge Cabrera <jorge.cabrera@intel.com>
> prov/shm: Fix for SAR path

- src/hmem_neuron.c
Currently, libfabric tries to dlopen libnrt.so, which may not
be always on the LD_LIBRARY_PATH during runtime. Change it
to libnrt.so.1 which is in application's RPATH.
> hmem_neuron: change the neuron library file name.

- src/hmem_neuron.c
Currently, libfabric tries to dlopen libnrt.so, which may not
be always on the LD_LIBRARY_PATH during runtime. Change it
to libnrt.so.1 which is in application's RPATH.
(cherry picked from commit 9dccd723e20534c398db854670b9eef2c2590d20)
Backport of https://github.com/ofiwg/libfabric/pull/7821
> [v1.15.x] hmem_neuron: change the neuron library file name.

- prov/efa/Makefile.include
- prov/efa/src/efa_av.c
- prov/efa/test/efa_unit_test_common.c
- prov/efa/test/efa_unit_test_ep.c
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
This unit test is introduced to validate the changes in
https://github.com/ofiwg/libfabric/pull/7558
Test info
```
(venv) [ec2-user@compute-dy-c5n18xlarge-1 libfabric]$ ./prov/efa/test/efa_unit_test
<?xml version="1.0" encoding="UTF-8" ?>
<testsuites>
<testsuite name="efa unit tests" time="0.191" tests="4" failures="0" errors="0" skipped="0" >
<testcase name="test_duplicate_efa_ah_creation" time="0.136" >
</testcase>
<testcase name="test_efa_device_construct_error_handling" time="0.000" >
</testcase>
<testcase name="test_rxr_ep_pkt_pool_flags" time="0.009" >
</testcase>
<testcase name="test_rxr_ep_pkt_pool_page_alignment" time="0.046" >
</testcase>
</testsuite>
</testsuites>
```
> prov/efa: Add unit test for pkt pool flags and page alignment

- fabtests/pytest/efa/test_dgram.py
dgram endpoint is unreliable, which caused the test to fail
randomly.
This patch adjust test_dgram() such that:
strict mode is not used, so -FI_ENODATA will be treated as
pass.
verify there is EFA traffic to be sure dgram endpoint can
be picked up.
> fabtests/pytest/efa: adjust dgram test

- prov/tcp/src/tcpx_ep.c
Access to the socket needs to be serialized.  In tcpx_ep_shutdown,
acquire the ep lock prior to flushing the socket to avoid potential
races calling shutdown with progress threads.
> prov/tcp: Acquire ep lock prior to flushing socket in shutdown

- prov/shm/src/smr_msg.c
Fixes incorrect use of "peer_id" to "id" when checking sar_status of local
endpoint; in smr_generic_sendmsg path.
cherry-picked from commit 361f6bec4cb60d65db34c56557012fe5f917253f
Signed-off-by: Jorge Cabrera <jorge.cabrera@intel.com>
> [v1.15.x] prov/shm: Fix for SAR path

- prov/efa/src/rxr/rxr_atomic.c
This patch released tx_entry on the error handling path of
rxr_atomic_generic_efa();
> [v1.15.x] prov/efa: release tx_entry on error in rxr_atomic_generic_efa()

- fabtests/pytest/efa/efa_common.py
This patch added quote ("") around the filen name in the command
used by efa_retrieve_hw_counter_value() for hw counter file.
This is to address the issue that hw counter file directory is
different between nodes.
> fabtests/efa: fix the command in efa_retrieve_hw_counter_value()

- fabtests/functional/unexpected_msg.c
- fabtests/multinode/src/core.c
- fabtests/multinode/src/core_coll.c
- fabtests/multinode/src/harness.c
- fabtests/multinode/src/pattern.c
Mostly white space cleanup to multinode test.  Converted the 'barrier' implementation to use FI_DELIVERY_COMPLETE for sends, instead of unspecified completion semantics, to ensure that the sends reach the destination.
Also patch to fix a compiler warning in unexpected_msg.
> fabtests/multinode: Code cleanup and switch to DELIVERY_COMPLETE barrier

- include/rdma/fabric.h
- src/common.c
- src/fi_tostr.c
Reserve address and protocol constants for the CXI provider
to avoid conflicts in applications that may be using a
pre-upstream release of the provider with other provider
definitions.
> core: Reserve CXI provider constants to avoid conflicts

- fabtests/Makefile.am
- fabtests/pytest/efa/test_fork_support.py
- fabtests/pytest/efa/test_runt.py
Run fi_rdm_tagged_bw with "-K" with environment variables
` FI_EFA_FORK_SAFE=1` and `RDMAV_FORK_SAFE=1`
> fabtests/efa: add fork-related test

- prov/efa/Makefile.include
- prov/efa/configure.m4
- prov/efa/src/efa.h
- prov/efa/src/efa_av.c
- prov/efa/src/efa_cq.c
- prov/efa/src/efa_ep.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/test/README.md
- prov/efa/test/efa_unit_test_common.c
- prov/efa/test/efa_unit_test_ep.c
- prov/efa/test/efa_unit_test_mocks.c
- prov/efa/test/efa_unit_test_utils.h
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
- prov/efa/test/rdma_core_mocks.c
Migrate efa provider to wide completion APIs. Deprecate ibv_poll_cq
usage in favor of ibv_{start,next,end}_poll verbs.
Signed-off-by: wenduwan <wenduwdan@amazon.com>
In this change we migrate to wide completion APIs to take advantage of additional query capabilities of the extended CQ verbs. Specifically, usage of ibv_poll_cq verb is deprecated in favor of ibv_{start,next,end}_poll verbs.
> prov/efa: adopt wide completion APIs in EFA provider

- fabtests/pytest/efa/test_rnr.py
This PR backports  https://github.com/ofiwg/libfabric/pull/7722 to v1.15.x
> [v1.15.x] fabtests/efa: do not run efa rnr test with strict mode

- include/rdma/fabric.h
- src/common.c
- src/fi_tostr.c
Reserve address and protocol constants for the CXI provider
to avoid conflicts in applications that may be using a
pre-upstream release of the provider with other provider
definitions.
Note that this PR does not add CXI provider functionality to v1.15.x.
> [v1.15.x] core: Reserve CXI provider constants to avoid conflicts

- include/rdma/fi_ext.h
- man/fi_peer.3.md
Add the following fields to the shared receive entry:
- srx pointer to get back to the srx that owns it/is processing a message for it
- owner_context for the owner/allocator to manage resources
- user_context for the user (when the entry represents an incoming message,
not a posted receive)
- flags for a peer to know whether to write completions or not
- change iov[] to iov* - the allocator should be responsible for allocating the
appropriate iov array and can set this pointer to point to where to find the array
Separate the get_msg and get_tagged functions into the following:
- get_msg/get_tagged, queue_msg/queue_tag, free_entry
This allows the peer to allocate and set the rx_entry user_context when an unexpected
message arrives so it has the needed information when the owner calls …
> include/rdma: modify peer_srx API

- contrib/intel/jenkins/build.py
- contrib/intel/jenkins/run.py
- contrib/intel/jenkins/tests.py
Mpi's included - [ompi, mpich, impi]
Integrate run_impi.sh into python
Integrate run_mpich.sh into python
Integrate ompi the same way that impi, and mpich are integrated
Change imb, osu, and mpichtestsuite classes to use new mpi classes
Refactor common code into the super class
Change string notation to use newer "f string" notation which is cleaner than the old ".format()" notation
> contrib/intel/jenkins: Refactor tests.py to run mpis without shell scripts

- src/common.c
ret is not set for OFI_LOCK_NONE.  This only impacts the new
net provider.
> core/genlock: Initialize ret in ofi_genlock_init

- prov/efa/src/rxr/rxr_pkt_type_req.c
Currently, the rxr_tx_entry_try_fill_desc is called
before `rxr_pkt_init_rtm` in rxr_pkt_init_*_medium function.
This caused a performance regression because the tx_entry->desc
was not filled before calling rxr_pkt_init_rtm, which makes
rxr_pkt_init_data_from_tx_entry do extra copy.
This patch fixes this issue by calling rxr_tx_entry_try_fill_desc
before rxr_pkt_init_rtm
> prov/efa: fill tx desc before init rtm pkt.

- include/ofi_util.h
- prov/efa/src/efa_domain.c
- prov/mrail/src/mrail_domain.c
- prov/psm/src/psmx_domain.c
- prov/psm2/src/psmx2_domain.c
- prov/psm3/src/psmx3_domain.c
- prov/rstream/src/rstream_domain.c
- prov/rxd/src/rxd_domain.c
- prov/rxm/src/rxm_domain.c
- prov/shm/src/smr_domain.c
- prov/tcp/src/tcpx_domain.c
- prov/udp/src/udpx_domain.c
- prov/util/src/util_cq.c
- prov/util/src/util_domain.c
- prov/verbs/src/verbs_domain.c
- prov/xnet/src/xnet.h
- prov/xnet/src/xnet_attr.c
- prov/xnet/src/xnet_cq.c
- prov/xnet/src/xnet_domain.c
- prov/xnet/src/xnet_progress.c
Updates the util code + most providers to specify the desired type of domain lock as part of init.  This replaces the flags parameter to init.  Update the net provider to use the progress lock in place of the cq and domain locks (latter is for memory registration).  This change results in minor changes to util/cq.
> prov/util + most: specify domain lock during initialization

- prov/net/src/xnet.h
- prov/net/src/xnet_attr.c
- prov/net/src/xnet_domain.c
- prov/net/src/xnet_fabric.c
- prov/net/src/xnet_init.c
- prov/net/src/xnet_rdm.c
- prov/net/src/xnet_rdm_cm.c
- prov/net/src/xnet_srx.c
Update fi_info attributes reported by net provider for ep, ep with srx, and rdm endpoints.
Fix source address matching for received messages.
Include correct rdm ep port number with CM messages.
> prov/net: Fixes for rdm ep support

- fabtests/pytest/efa/test_runt.py
This patch fixed 2 bugs in test case test_runt_read():
First, the environment variable to enable RDMA should be
FI_EFA_USE_DEVICE_RDMA, not FI_EFA_USE_DEVICE_RDMA_READ
Second, the upper bound assertion of client_send_bytes is
wrong because it did not consider the situation that on
single host, server will use the same EFA device to send
control packets.
> fabtests/pytest/efa: fix 2 bugs in test_runt_read()

- prov/verbs/src/verbs_info.c
- src/common.c
I also wonder if it should enter ofi_bsock_async_done() at all, when zerocopy was never enabled.
> Reduce log messages

- prov/efa/Makefile.include
- prov/efa/configure.m4
- prov/efa/src/efa.h
- prov/efa/src/efa_av.c
- prov/efa/src/efa_cq.c
- prov/efa/src/rxr/rxr_ep.c
- prov/efa/src/rxr/rxr_pkt_cmd.c
- prov/efa/src/rxr/rxr_pkt_cmd.h
- prov/efa/src/rxr/rxr_pkt_entry.h
- prov/efa/src/rxr/rxr_pkt_type.h
- prov/efa/src/rxr/rxr_pkt_type_misc.c
- prov/efa/test/efa_unit_test_av.c
- prov/efa/test/efa_unit_test_common.c
- prov/efa/test/efa_unit_test_cq.c
- prov/efa/test/efa_unit_test_device.c
- prov/efa/test/efa_unit_test_mocks.c
- prov/efa/test/efa_unit_test_mocks.h
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
It is possible that the EFA device would return an unknown AH(-1) for a known
peer in receive op. This is a bug and could cause the received packet to be
discarded. As a mitigation, the EFA provider attempts to recover the AH if the
node supports extensible CQ. The additional efadv verbs allows the receiver
to retrieve peer raw address. Thereby the provider is able to infer the AH via
Raw Address:QPN:QKey.
Signed-off-by: wenduwan <wenduwan@amazon.com>
> prov/efa: recover unknown peer AH with raw address from efadv

- prov/efa/Makefile.include
- prov/efa/src/efa.h
- prov/efa/src/efa_ep.c
- prov/efa/test/efa_unit_test_common.c
- prov/efa/test/efa_unit_test_info.c
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
In efa_ep_destroy(), ofi_endpoint_close() was called on
ep->util_ep unconditionally, even when ep->util_ep has not
been initialized.
This patch check whether ep->util_ep is initialized before
close it
> prov/efa: validate ep->util_ep before closing in efa_ep_destroy()

- prov/efa/src/rxr/rxr_ep.c
- prov/efa/test/efa_unit_test_info.c
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
Currently, rxr_ep_alloc_app_device_info() only support newer version
of API (>=1.5). This patch makes it to support older version of
API.
> prov/efa: make rxr_ep_alloc_app_device_info() to support older API

- prov/psm2/src/psmx2_cq.c
- prov/psm3/src/psmx3_cq.c
The CQ data was not retrieved in psmx3_mq_status_copy for the case of
PSMX3_IOV_RECV_CONTEXT, causing loss of CQ data in fi_tsendmsg.
Fixes #7762 
EDIT: Fixes applied to both psm2 and psm3.
> prov/psm2&3: get cq data for PSMX3_IOV_RECV_CONTEXT

- prov/util/src/util_attr.c
Client can set hints mr_mode bits to FI_MR_UNSPEC to
indicate support for any registration mode.
Discussion #7878 
> prov/util: Fix MR mode bit check for ver 1.5 and greater

- prov/efa/src/efa_mr.c
When ofi_mr_map_remove returns a failure return code, that code is not
the one that is included in the debug message.  This makes it so that
the returned code is logged.
Signed-off-by: Ryan Hankins <rqh@amazon.com>
> print ofi_mr_map_remove return correctly upon failure

- prov/efa/src/rxr/rxr_pkt_cmd.c
This mainly prevents log files from becoming massively bloated when FI_LOG_LEVEL=warn
> prov/efa: Avoid excessive warn logging

- fabtests/common/hmem_neuron.c
- src/hmem_neuron.c
Also changes fabtests to open libnrt.so.1 instead of libnrt.so
> src/hmem_neuron.c Change print to to reflect libnrt.so.1

- fabtests/common/check_hmem.c
- fabtests/pytest/common.py
This PR contains two commits to fix issues in `has_hmem_support()` in `fabtests/pytest/common.py`:
> fabtests: Fix issues in `has_hmem_support()` 

- fabtests/common/hmem_neuron.c
- src/hmem_neuron.c
Also changes fabtests to open libnrt.so.1 instead of libnrt.so
(cherry picked from commit 55dede293de9c144ddc1b2a9b195be8de87e0b4c)
> [v1.15.x] src/hmem_neuron.c Change print to to reflect libnrt.so.1

- include/ofi_epoll.h
- prov/net/src/xnet.h
- prov/net/src/xnet_cm.c
- prov/net/src/xnet_ep.c
- prov/net/src/xnet_progress.c
- prov/net/src/xnet_rdm_cm.c
- src/common.c
From the commit message changing pollfds:
core/pollfds: Add ability to manually select hot/cold sockets
The pollfds implementation maintains 2 arrays of fd's that it
monitors.  One is the default fd set of all watched fd's.  The
other is an array of active fd's.  The active fd set is disabled
by default, but can be enabled through the FI_POLL_FAIRNESS
variable.  An fd is moved to the active list if it had any events
on it within the last 'fairness' number of checks.  An fd is
removed from the active list if no events were reported.
In theory, this sounds like a great idea.  In practice, it does
not work well with some applications.
The issue is that there are situations where an application is
only trying to send or receive data from a small number of sockets,
maybe as few as 1, to the …
> prov/net: Rework active socket monitoring

- prov/psm3/configure.ac
Fixes: https://github.com/ofiwg/libfabric/issues/7901
> psm3: Remove bashisms from psm3 provider build

- fabtests/Makefile.am
- fabtests/component/dmabuf-rdma/dmabuf_reg.c
- fabtests/component/dmabuf-rdma/dmabuf_reg.h
- fabtests/component/dmabuf-rdma/fi-mr-reg-xe.c
- fabtests/component/dmabuf-rdma/fi-rdmabw-xe.c
- fabtests/component/dmabuf-rdma/memcopy-xe.c
- fabtests/component/dmabuf-rdma/mr-reg-xe.c
- fabtests/component/dmabuf-rdma/rdmabw-xe.c
- fabtests/component/dmabuf-rdma/util.c
- fabtests/component/dmabuf-rdma/util.h
- fabtests/component/dmabuf-rdma/xe.c
- fabtests/component/dmabuf-rdma/xe.h
- fabtests/configure.ac
- fabtests/man/fabtests.7.md
These are a mix of OFI, verbs, and oneAPI level-zero tests. They are
intended for validating basic functionality of dmabuf based RDMA.
> fabtests: Add component tests for dmabuf RDMA

- prov/psm3/configure.ac
Fixes: https://github.com/ofiwg/libfabric/issues/7901
> [v1.15.x] psm3: Remove bashisms from psm3 provider build 

- prov/net/src/xnet_init.c
- prov/net/src/xnet_srx.c
Since the net provider is a fork of the tcp provider (and will
eventually return to being the tcp provider), allow setting the
provider name through an environment variable.  This allows
testing the net provider as the "tcp" provider for apps that
explicitly request the provider by name.
This change is intended for debugging/testing purposes as
a work-around for running MPI with the net provider.  We're
currently needing to manually change the name in the code
and rebuild to use the provider (because of issues in MPI).
> prov/net: Add env var to rename provider

- include/ofi_lock.h
- prov/net/src/xnet.h
- prov/net/src/xnet_cq.c
- prov/net/src/xnet_msg.c
- prov/net/src/xnet_progress.c
- prov/net/src/xnet_rma.c
- prov/net/src/xnet_srx.c
Minor change to genlock nolock_held implementation (return true instead of false)
Implement counter calls directly in the net provider.  This removes the requirement to force on the auto-progress thread when blocking counter calls are needed by the app.  Instead, the cntr_wait call can block on the pollfds in the progress object when FI_THREAD_DOMAIN is used.
> prov/net: Changes to improve counter support

- fabtests/pytest/efa/efa_common.py
- fabtests/pytest/efa/test_runt.py
Currently, test_runt fails on system with older version of EFA kernel module, which does not support some HW counters.
This patch address the issue by skipping the test under such case.
> fabtests/efa: fix runt test

- fabtests/Makefile.am
- fabtests/configure.ac
Two of the dmabuf rdma component tests depend on verbs.
> fabtests: Add verbs presence check for component tests

- prov/net/src/xnet.h
- prov/net/src/xnet_rdm_cm.c
Set a connected endpoint to active if:
- The message queue for the endpoint is currently empty
- We post a tagged message to receive data from its peer
- The connection is not already active
The posting of the message likely indicates that data is
expected from the peer soon.
> prov/net: Fixes to provider

- src/fabric.c
Until the opx provider is ready, psm2 should be
the default provider selected for Omnipath fabrics.
Change ofi_ordered_provs_init() accordingly
Signed-off-by: Tim Thompson <tim.thompson@cornelisnetworks.com>
> core/fabric: Make PSM2 higher default priority

- fabtests/configure.ac
According to the AC_CHECK_LIB man page:
If action-if-found is not specified, the default action prepends -llibrary to LIBS
This suggests that if the default action is not provided, the library will not be added to
LIBS by default. This patch explicitly adds the ze_loader and ibverbs libraries to LIBS if
they were found to avoid linking errors.
It also changes the function that the verbs_devel check looks for since older versions might
not have the newer version which has the required function for the test.
> fabtests/configure: fix ze_loader and ibverbs config check for component tests

- prov/util/src/util_cq.c
In ofi_cq_readfrom, aux entries are removed from the aux queue but were
never freed.
ofi_cq_readerr does not have this issue.
> util: Free CQ aux entry memory leak

- configure.ac
- src/hmem_ze.c
The header 'i195_drm.h' could be under either '/usr/include/drm' or
'/usr/include/libdrm' depending on the system and the package it is
installed from.
> configure: Check for alternative path of i915_drm.h
