ofiwg/libfabric

configure.ac
src/hmem_ze.c

The header 'i195_drm.h' could be under either '/usr/include/drm' or
'/usr/include/libdrm' depending on the system and the package it is
installed from.
Cherry-picked from commit 4749c3215aae90f374094cb1430306cea19a4137

[v1.15.x] configure: Check for alternative path of i915_drm.h

---

prov/efa/src/efa_mr.c

We were missing locks around the mr map operations which caused thread
unsafe behavior. Also removed a duplicate ofi_mr_map_remove call in the
error path (It's already called in the fi_close path).

prov/efa: Add locks around mr map

---

contrib/intel/jenkins/tests.py

Add the ze-shm stage back to the CI and disable the actual failing test, (xd2d: cross device to device), rather than the whole stage

contrib/intel/jenkins: Re-enable ze-shm stage

---

src/fabric.c

Until the opx provider is ready, psm2 should be
the default provider selected for Omnipath fabrics.
Change ofi_ordered_provs_init() accordingly
Signed-off-by: Tim Thompson <tim.thompson@cornelisnetworks.com>

[v1.15.x] core/fabric: Make PSM2 higher default priority

---

prov/util/src/util_cq.c

In ofi_cq_readfrom, aux entries are removed from the aux queue but were
never freed.
ofi_cq_readerr does not have this issue.

[v1.15.x] util: Fix CQ aux entry memory leak

---

include/ofi_epoll.h
include/ofi_indexer.h
prov/net/src/xnet.h
prov/net/src/xnet_cm.c
prov/net/src/xnet_ep.c
prov/net/src/xnet_msg.c
prov/net/src/xnet_progress.c
prov/net/src/xnet_rdm.c
prov/net/src/xnet_rdm_cm.c
prov/net/src/xnet_srx.c
src/common.c
src/indexer.c

The objective of this series is to process unexpected messages as soon as the receive buffers for them are posted.  The changes are limited to source-targeted tagged receives.
The follow-on objective to these changes is to remove 'connections that need a receive buffer posted in order to proceed' from the general progress engine.  For example, remove the underlying sockets from monitored poll sets and as part of normal progress.  Progress would then resume once the receive buffer had been posted.

prov/net: First set of patches to improve unexpected msg handling

---

prov/efa/configure.m4
prov/efa/src/efa_cq.c
prov/efa/src/rxr/rxr_ep.c
prov/efa/test/efa_unit_test_cq.c
prov/efa/test/efa_unit_test_mocks.c
prov/efa/test/efa_unit_test_mocks.h

`efadv_wc_read_ah` is renamed to `efadv_wc_read_sgid` in rdma-core.
The new function does not return peer AH but instead 0(success) or
negative(peer AH is known).

prov/efa: update references to efadv_wc_read_sgid

---

contrib/intel/jenkins/run.py
contrib/intel/jenkins/runtests.py
contrib/intel/jenkins/tests.py

Allow setting of environment variables per test run. This is specified through the
runtests.py arg --user_env with a string formatted as a dictionary. For example:
runtests.py --prov=shm --test=fabtests --slurm --user_env="{'FI_SHM_DISABLE_CMA':1,'FI_LOG_LEVEL'='info'}"
This lets us test certain runtime parameters for certain cases only.
This also removes the hard coded verbs variables because FI_VERBS_MR_CACHE_ENABLE was deprecated and
FI_VERBS_INLINE_SIZE is already defaulted to 256 bytes so setting it is redundant.

contrib/intel: add ability to set specific environment variables per test

---

include/ofi_epoll.h
prov/net/src/xnet.h
prov/net/src/xnet_cm.c
prov/net/src/xnet_cq.c
prov/net/src/xnet_ep.c
prov/net/src/xnet_progress.c
prov/net/src/xnet_srx.c
src/common.c
src/unix/osd.c
src/windows/osd.c

Moves all hot fd support from the pollfds abstraction directly into the net provider.  Trying to track hot fd's within pollfds does not work and requires the user of the poll set to control which sockets are hot.  The hot support is removed from pollfds.
Adds a new dynamic poll abstraction, which selects between epoll vs poll at run time.
Updates the net provider to maintain separate fd sets for all fd's and hot fd's.
Updates pollfds to allow the user to specify the type of locking to use.  If no lock is required, we optimize the add/del calls to avoid asynchronous processing and memory allocation.

core/net: Update to pollfds and hot fd polling

---

NEWS.md
src/hmem_neuron.c

This PR backports https://github.com/ofiwg/libfabric/pull/7952 to v1.15.x, and updates `NEWS.md`.

[v1.15.x] hmem_neuron.c: Use nrt_memcpy_to_device to copy from host to dev

---

include/ofi_indexer.h
src/common.c

The max index needs to be 1 less, since indices start at 0.
Should fix coverity warning.

core/indexer: Fix OFI_IDX_MAX_INDEX off by 1 error

---

include/ofi_epoll.h
prov/net/src/xnet.h
prov/net/src/xnet_init.c
prov/net/src/xnet_progress.c
src/common.c
src/fabric.c

Request socket send/receive buffering to 128k as a default.
Convert global ofi_poll_fairness variable to net provider variable.
Use a separate counter from poll fairness to move sockets off the hot set.

prov/net: Updates to socket config and poll behavior

---

fabtests/pytest/efa/test_runt.py

runt_read is not intended to be used on single node, therefore
this patch skip the run_read test on it.

fabtests/pytest/efa: skip runt_read test for single node

---

prov/efa/Makefile.include
prov/efa/src/efa.h
prov/efa/src/efa_cq.c
prov/efa/src/rxr/rxr_ep.c
prov/efa/test/efa_unit_test_common.c
prov/efa/test/efa_unit_test_cq.c
prov/efa/test/efa_unit_test_mocks.c
prov/efa/test/efa_unit_test_mocks.h
prov/efa/test/efa_unit_tests.c
prov/efa/test/efa_unit_tests.h

- Unit test buffer construction used the wrong buffer address, which caused `Bad address` error from `fi_mr_reg` at large buffer sizes, e.g. 8800 bytes. This is a subtle bug and we did not notice it for 4096 bytes.
- The recent change to query peer address from EFA device did not account for the case when EFA DV CQ is not supported in the kernel, which will cause `efadv_create_cq` to fail. In this change we add the handling logic to fallback to `ibv_create_cq_ex` if `efadv_create_cq` fails(for any reason). We use a bit mask to indicate whether the `efa_cq->ibv_cq_ex` is created with `efadv_create_cq` or `ibv_create_cq_ex`, and thereby decide if we should try to query peer address from EFA device.

prov/efa: a unit test bug fix and handle the case when EFA DV CQ is not supported

---

prov/efa/src/efa_mr.c
prov/efa/src/rxr/rxr_ep.c
prov/efa/src/rxr/rxr_msg.c

This PR enables using shm for CUDA hmem. It cannot be merged before https://github.com/ofiwg/libfabric/pull/7893 is merged.

prov/efa: enable using shm via CUDA IPC.

---

fabtests/component/dmabuf-rdma/fi-rdmabw-xe.c

The '-2' option already exists in the Verbs test rdmabw-xe. Now add it
to the OFI test fi-rdmabw-xe. It only applies to the 'read' and 'write'
test types.

fabtests/component/dmabuf-rdma: Add option to run RDMA test in both direction

---

prov/net/src/xnet_rdm_cm.c

Yeah, the title doesn't seem to make sense, but it really does...
For RDM endpoints, when processing a connect request event, we
see if there's already a connection to the peer.  This is handled
in xnet_process_connreq().  If we have an active connection (that
is, there's an ep of state CONNECTED), there are 2 cases that are
considered.
Case 1 is that the current connection is old and no longer
usable.  This can happen if the peer disconnects and restarts, and
is the case for DAOS clients.  We check for this case by comparing
whether the connection is coming from the same or a different
remote process ID.
Case 2 is that the current connection is the new connection.  The
peer has accepted our request for the connection.  And we're simply
processing the peer's original connection request, …

prov/net: Fix incorrect disconnect during connection setup

---

prov/efa/Makefile.include
prov/efa/configure.m4
prov/efa/src/efa_hmem.c
prov/efa/test/efa_unit_test_hmem.c
prov/efa/test/efa_unit_test_mocks.c
prov/efa/test/efa_unit_test_mocks.h
prov/efa/test/efa_unit_tests.c
prov/efa/test/efa_unit_tests.h

neuron_alloc will fail if application did not call nrt_init,
which is ok if it's not running neuron workloads. libfabric
will move on and leave neuron_status->initialized as false.
Also add a unit test for this fix

prov/efa: Do not fail domain open when neuron_alloc failed.

---

prov/efa/src/efa_mr.c

This patch removed the call to efa_mr_hmem_setup() in
efa_mr_cache_regattr() because efa_mr_cache_regattr() already
called the function indirectly when it called ofi_mr_cache_search()

prov/efa: remove redundent call to efa_mr_hmem_setup()

---

prov/efa/src/efa_mr.c

The local variable attr is not initialized to {0},
which could cause attr.device has unexpected value
and make hmem_ops have wrong device input.

prov/efa: Initialize attr in efa_mr_cache_entry_reg.

---

prov/efa/src/efa_mr.c
prov/rxm/src/rxm_domain.c
prov/util/src/util_mr_map.c
prov/verbs/src/verbs_mr.c

Providers should fail MR registration for ifaces that are not initialized
Fixes #7977 

prov/rxm, util, verbs, efa: add iface initialization checks to MR registration

---

prov/efa/configure.m4
prov/efa/src/efa_ep.c
prov/efa/src/efa_hmem.c
prov/efa/src/efa_mr.c
prov/efa/src/efa_mr.h
prov/efa/src/efa_prov_info.c
prov/efa/src/rxr/rxr_ep.c
prov/efa/src/rxr/rxr_msg.c
prov/efa/src/rxr/rxr_rma.c

Use long read for msg and rma operations, regardless of what is
specified by the user for protocol switch over points.
There is no memcpy from host to device for synapseai inside
libfabric.
Test info: 
- Run hccl_demo with allreduce, broadcast, reduce
- Run fabtests between synapseai buffer on two dl1 instances.

prov/efa: add support for synapseai hmem iface

---

fabtests/pytest/efa/efa_common.py
fabtests/pytest/efa/test_efa_info.py
fabtests/pytest/efa/test_from_default.py
prov/efa/src/efa_user_info.c

This patch fixed a bug in setting `info->dest_addr` and added a test for the case.

prov/efa: fix a bug in setting info->dest_addr and add a test

---

prov/util/src/util_mem_monitor.c

prov/core: Fix text in log of UFFD ioctl failure

---

prov/efa/src/rxr/rxr_msg.c

It is efficient to use eager for 0 bytes transfer. This patch
makes rxr_msg_select_rtm use eager protocol for shm when
msg size is 0.

prov/efa: Use eager protocol for shm when msg size is 0

---

include/rdma/fi_ext.h
man/fi_peer.3.md

This means the ep_fid can be can be passed into the fi_recv APIs in order to post recv messages directly to the SRX.

include/fi_ext: change the peer srx fid to an ep_fid

---

contrib/intel/jenkins/Jenkinsfile
contrib/intel/jenkins/build.py
contrib/intel/jenkins/common.py
contrib/intel/jenkins/run.py
contrib/intel/jenkins/runtests.py
contrib/intel/jenkins/summary.py
contrib/intel/jenkins/tests.py

This commit adds a functional summary to the CI.
A new directory (log_dir) is being made to store all the logs for each stage.
These patches add a functional summary stage to the pipeline and to the post stage in the Jenkinsfile.
The pipeline stage is only viewable on passed pipelines. This is because jenkins skips future stages if earlier stages failed. So, this stage is just to provide a clear place to look on passed pipelines for the functional summary.
The functional summary will still be provided in the post stage inside of the always{} clause incase of a test failure where the summary will still provide a list of passed and failed tests during the entire run.
The stages that get summarized in these patches are:
fabtests (tcp, verbs-rxm, verbs-rxd, shm, udp, sockets, psm3) [reg, dl, …

contrib/intel/jenkins: Add functional summary stage to CI

---

man/fi_efa.7.md
prov/efa/src/efa_mr.c
prov/efa/src/rxr/rxr_env.c
prov/efa/src/rxr/rxr_env.h

This PR introduces an environment variable `FI_EFA_SET_CUDA_SYNC_MEMOPS` to control the set/unset of `CU_POINTER_ATTRIBUTE_SYNC_MEMOPS` attribute for cuda ptr. By default this attribute is set as true.

prov/efa: Toggle cuda sync memops via environment variable

---

man/fi_efa.7.md
prov/efa/src/efa_mr.c
prov/efa/src/rxr/rxr_env.c
prov/efa/src/rxr/rxr_env.h

This PR backports https://github.com/ofiwg/libfabric/pull/7995 to v1.16.x

[v1.16.x] prov/efa: Toggle cuda sync memops via environment variable

---

prov/efa/src/rxr/rxr_env.c

The runt_size parameter default changed, but the reported default did not.  Update the reported default to the actual default.

prov/efa: Report correct default for runt_size parameter

---

prov/hook/dmabuf_peer_mem/src/hook_dmabuf_peer_mem.c

When the hooking provider detects valid dmabuf based buffer, set the iface to FI_HMEM_ZE. This allows HMEM buffer copy routines to work properly.

prov/hook/dmabuf_peer_mem: Set iface when auto-detect succeeds

---

prov/hook/dmabuf_peer_mem/src/hook_dmabuf_peer_mem.c

When the hooking provider detects valid dmabuf based buffer, set the iface to FI_HMEM_ZE. This allows HMEM buffer copy routines to work properly.
Cherry-picked from commit 10a8e25cfa8b8f38ea059c08f6bde6f84384f1ac.

[v1.16.x] prov/hook/dmabuf_peer_mem: Set iface when auto-detect succeeds

---

prov/efa/src/rxr/rxr_env.c

The runt_size parameter default changed, but the reported default did not.  Update the reported default to the actual default.
Signed-off-by: Ryan Hankins <rqh@amazon.com>
(cherry picked from commit 6e81dcaf8e36dbae66193c6c2e6ed7a25b98b895)

[v1.16.x] prov/efa: Report correct default for runt_size parameter

---

prov/hook/dmabuf_peer_mem/src/hook_dmabuf_peer_mem.c

When the hooking provider detects valid dmabuf based buffer, set the iface to FI_HMEM_ZE. This allows HMEM buffer copy routines to work properly.
Cherry-picked from commit 10a8e25cfa8b8f38ea059c08f6bde6f84384f1ac.

[v1.15.x] prov/hook/dmabuf_peer_mem: Set iface when auto-detect succeeds

---

fabtests/functional/multi_recv.c
prov/net/src/xnet.h
prov/net/src/xnet_attr.c
prov/net/src/xnet_cq.c
prov/net/src/xnet_msg.c
prov/net/src/xnet_progress.c
prov/net/src/xnet_srx.c
src/common.c

core: Fix NIC interface name checks to be exact match, versus prefix match
prov/net: Fix support for FI_MULTI_RECV
fabtests/multi_recv: Fix crash in cleanup and add buffer validation

[v1.16.x] net: Fix for multi-recv. core: fix iface strcmp.  fabtest: Fix multi-recv test

---

fabtests/functional/rdm_stress.c

When `run_parent()` finishes correctly the '`ret`' variable contains a PID of the last forked child. Then this value is passed to `ft_exit_code()` and test exits with an error. '`ret`' should be zeroed to fix this issue.
Signed-off-by: Lukasz Dorau <lukasz.dorau@intel.com>

fabtests: fix return value of rdm_stress client

---

fabtests/benchmarks/benchmark_shared.c

This patch added data verification to function bandwidth() and bandwidth_rma(),
which is used by fi_rdm_tagged_bw,  fi_msg_bw and fi_rma_bw's writedata option

fabtests/benchmarks: add data verification to some bandwidth tests

---

prov/verbs/src/verbs_info.c

According to libfabric's man pages (fi_verbs.7), MSG EPs in the verbs  provider support FI_SOCKADDR, FI_SOCKADDR_IN, FI_SOCKADDR_IN6 and FI_SOCKADDR_IB.
Since commit fb758f5d7("prov/verbs: set and check address format correctly"), the verbs provider sets fi->addr_format = FI_SOCKADDR for MSG EPs.
The problem is that applications requesting FI_SOCKADDR_IB get FI_ENODATA in gi_getinfo() because ofi_valid_addr_format() only expects FI_SOCKADDR, FI_SOCKADDR_IN and FI_SOCKADDR_IN6 but not FI_SOCKADDR_IB.

util,verbs: FI_SOCKADDR includes support of FI_SOCKADDR_IB

---

prov/verbs/src/verbs_info.c

According to libfabric's man pages (fi_verbs.7), MSG EPs in the verbs  provider support FI_SOCKADDR, FI_SOCKADDR_IN, FI_SOCKADDR_IN6 and FI_SOCKADDR_IB.
Since commit fb758f5d7("prov/verbs: set and check address format correctly"), the verbs provider sets fi->addr_format = FI_SOCKADDR for MSG EPs.
The problem is that applications requesting FI_SOCKADDR_IB get FI_ENODATA in fi_getinfo() because ofi_valid_addr_format() only expects FI_SOCKADDR, FI_SOCKADDR_IN and FI_SOCKADDR_IN6 but not FI_SOCKADDR_IB when the provider format is FI_SOCKADDR.

[v1.16.x] util,verbs: FI_SOCKADDR includes support of FI_SOCKADDR_IB

---

prov/util/src/rocr_mem_monitor.c

Fix syntax error introduced in:
32ead6680c8feb6ee933cf28482a6f3b6bc0a6b8 core and util/prov: introduce cuda ipc monitor
Signed-off-by: Amir Shehata <shehataa@ornl.gov>

util/src: fix syntax error

---

prov/efa/src/efa_user_info.c

Backport https://github.com/ofiwg/libfabric/pull/8026 to v1.16.x

[v1.16.x] prov/efa: Add check of rdma-read capability for synapseai.

---

prov/util/src/rocr_mem_monitor.c

Fix syntax error introduced in:
32ead6680c8feb6ee933cf28482a6f3b6bc0a6b8 core and util/prov: introduce cuda ipc monitor
Signed-off-by: Amir Shehata <shehataa@ornl.gov>

[v1.16.x] util/src: fix syntax error

---

fabtests/Makefile.am
fabtests/pytest/efa/test_av.py
fabtests/pytest/efa/test_rdm.py

This patch re-enable the fi_rdm and fi_av_xfer test for EFA provider.

fabtests/pytest/efa: re-enable fi_rdm and fi_av_xfer test

---

prov/verbs/src/fi_verbs.c

Currently the verbs provider uses dmabuf based memory registration whenever possible and only falls back to regular memory registration when the first approach fails. This works well most of the time. However, sometimes it may be desirable to disable the dmabuf based registration. For example, to test the functionality of the dmabuf peer-mem adapter driver.
This patch adds a runtime option to the verbs provider that allows explicit enabling/disabling of dmabuf support.

prov/verbs: Add option to disable dmabuf support

---

prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_ep.c

rxr_ep now has a new member ibv_cq_ex which is polled directly in
rxr_ep_progress_internal

prov/efa: Directly use ibv_cq_ex in rxr_ep 

---

fabtests/pytest/common.py
fabtests/pytest/requirements.txt

When a test encountered ssh connection issue like "reset by peer", "closed by peer", or "refused", this patch will retry the test for 3 times, with each retry interval 5 seconds.

fabtests/pytest: retry when ssh connection issues are encountered

---

fabtests/pytest/common.py

Add "ssh_exchange_identification: Connection closed by remote host" as an error message that is considered ssh connection issue.

fabtests/pytest: add possible ssh connection error message

---

v1.16.0/man/index.md

gh-pages: Add missing link for fi_peer man page

---

main/man/index.md

A previous patch (commit efa7f61a51b235a5e08c32ec8d9a209e91be65c3) fixed the man pages for v1.16.0, but the link is still missing from main.

gh-pages: Add yet another missing link of fi_peer man page

---

util/pingpong.c

Older Darwin does not have definition for `AI_NUMERICSERV`, which is used in `util/pingpong.c` (and causes build to fail on 10.6). This PR fixes this error.
It mirrors the fix for `MoarVM` from: https://github.com/macports/macports-ports/pull/14932

util/pinpong: add AI_NUMERICSERV definition when it is not defined

---

contrib/intel/jenkins/Jenkinsfile
contrib/intel/jenkins/runtests.py
contrib/intel/jenkins/tests.py

The Jenkins nodes use the naming convention "node-fabric"
Jenkins parses by the '-' and assumes the first element to be the
node name to ssh into. This delimiter conflicts with normal node
naming convention which uses dashes within the node name.
This changes the node/fabric delimiter from - to _ so it doesn't
conflict with regular node names.
Note that this will require a momentary down period between naming
the nodes and merging the PR.
After this change is merged, PRs will have to rebase on upstream
in order to pass.
Verified this works with a single pair of renamed nodes as well as with the daos testing.
Also includes 2 unrelated minor fixes.

contrib/intel: replace '-' delimiter with '_'

---

man/fi_verbs.7.md

Add description of the new environment variable FI_VERBS_USE_DMABUF.

man: Update fi_verbs man page with new runtime parameter

---

man/fi_verbs.7.md

Add description of the new environment variable FI_VERBS_USE_DMABUF.
Cherry-picked from commit 46b9465aae8b8ea19bdcb846e226276ab15284a2.

[v1.16.x] man: Update fi_verbs man page with new runtime parameter

---

contrib/intel/jenkins/Jenkinsfile
contrib/intel/jenkins/build.py
prov/verbs/Makefile.include

Add make distcheck and rpmbuild to jenkins for regular build.
We need to catch problems where a release package does not include all necessary files because of potential missing updates to makefile.includes.

contrib/intel/jenkins: Catch potential release package make issues

---

prov/efa/src/efa_domain.c
prov/efa/src/efa_domain.h
prov/efa/src/efa_fabric.c
prov/efa/src/efa_fork_support.c

When fork support is on, register memory regions was not copied to child processes's memory space.
With MR cache turned on, the registered memory regions remain registered after EFA finished send data from it.
As a result, when both fork support and MR cache are turned on, child processes cannot access some memory they need.
This patch addresses the issue by flush the MR cache when fork is called. Flushing MR cache will cause any memory region that is not actively being used (use_cnt == 0) to be de-registered, therefore they will be copied to child process's memory space

prov/efa: flush MR cache when fork() is called and fork support is ON

---

prov/rxm/src/rxm_atomic.c

128-bit atomics fail (cause segfault) in release build of provider.  Cause is likely related to alignment.  Fail query calls for 128-bit integers to indicate support is not provided.
https://github.com/ofiwg/libfabric/issues/7248
Signed-off-by: Nicolas Morey-Chaisemartin <nmoreychaisemartin@suse.com>

prov/rxm: Disable 128-bit atomics

---

prov/efa/src/efa.h
prov/efa/src/efa_cq.c
prov/efa/src/efa_cq.h
prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_ep.c

In a previous commit, a new member ibv_cq_ex was added to rxr_ep (https://github.com/ofiwg/libfabric/pull/8035)
But only ibv_create_cq was used to open the CQ
This commit adds support for extended CQ which is created by calling efadv_create_cq

prov/efa: Open extended CQ in rxr_ep

---

prov/efa/src/rxr/rxr_pkt_cmd.c

In rxr_pkt_post_req, the rxr_pkt_post_or_queue's inject argument was passed as flags, which is incorrect. This patch make rxr_pkt_post_or_queue called with the correct inject argument.

prov/efa: Fix incorrect argument for rxr_pkt_post_or_queue

---

prov/efa/src/rxr/rxr_pkt_cmd.c

Backport https://github.com/ofiwg/libfabric/pull/8085

[v1.16.x] prov/efa: Fix incorrect argument for rxr_pkt_post_or_queue

---

fabtests/functional/rdm_tagged_peek.c

Since the net provider does not implement an unexpected queue the existing implementation of rdm_tagged_peek hangs as it attempts to read the last message first, forcing the first messages to an assumed unexpected queue in the provider.
This set of changes removes the assumption on the unexpected queue by reading messages in the correct order and ignoring FI_ENOMSG errors when we're searching for a message with FI_PEEK.

fabtests: update rdm_tagged_peek to remove reliance on unexpected messages

---

include/ofi.h
include/ofi_hook.h
include/ofi_util.h
include/rdma/fabric.h
include/rdma/fi_ext.h
man/fi_peer.3.md
prov/hook/dmabuf_peer_mem/src/hook_dmabuf_peer_mem.c
src/fabric.c
src/log.c

This is the first set of changes targeting the support of a provider that only supports collective offloads.  The peer definitions are generic, and not tied specifically to that use case, but should meet it.  The series adds the peer EQ, peer AV, a new peer data transfer flag/mode/feature, and introduces a new type of provider.
The new provider is called (for now) a function provider.  It requires special handling by the libfabric core, as it's not usable stand-alone, nor does it layer over another provider.
The peer eq and av are what one would expect based on the peer cq and srx structures.
The peer data transfer allows the function provider to send and receive data over the main provider's endpoint.  For example, the collective provider send messages between a remote collective …

core/peer: New peer provider objects to support collective offload

---

prov/efa/src/efa_mr.c
prov/efa/src/efa_mr.h

efa_mr_reg_impl() upadte multiple resources. When
one of the resources was failed to be allocated,
the error handling path does not properly deallocate the allocated resources.
This patch address the issue.

prov/efa: fix the error handling path of efa_mr_reg_impl()

---

prov/efa/src/rxr/rxr_pkt_type_req.c

The macro for the raw addr opt header is RXR_REQ_OPT_RAW_ADDR_HDR, not RXR_REQ_OPT_RAW_ADDR_HDR_SIZE

prov/efa: Fix a bug in rxr_pkt_req_max_header_size

---

fabtests/test_configs/net/net.exclude
prov/net/src/xnet.h
prov/net/src/xnet_cm.c
prov/net/src/xnet_ep.c
prov/net/src/xnet_init.c
prov/net/src/xnet_progress.c
prov/net/src/xnet_srx.c

the fd hotlist features did not prove to perform noticeably better than epoll alone, so these changes clean up that code

prov/net: remove fd hotlist support

---

fabtests/common/shared.c
fabtests/functional/rdm_atomic.c
fabtests/functional/scalable_ep.c
fabtests/functional/shared_ctx.c
fabtests/include/shared.h
fabtests/multinode/src/core.c

FI_MR_ENDPOINT requires binding MRs to endpoints and enabling them once they are bound
to all applicable endpoints. This adds that bind and enable and reorders some of the
resource initialization since MR_ENDPOINT requires the endpoint to be enabled at the
point of binding to the MR.

fabtests/common: add support for FI_MR_ENDPOINT

---

man/fi_info.1.md

- Remove the usNIC example as it is no longer supported/used.
- Add more examples for fi_info for a few providers(tcp, verbs). 
Add one example for -v verbose output.
- Add more examples for other fi_info options.
Examples for -c, -m, -a and -e have been added.
The -e example does not have all the environment variables because it is a long list.

libfabric/man: Improve fi_info usage examples

---

prov/efa/src/efa_prov_info.c
prov/efa/src/rxr/rxr_ep.c
prov/efa/src/rxr/rxr_op_entry.c
prov/efa/src/rxr/rxr_pkt_type_req.c
prov/efa/src/rxr/rxr_pkt_type_req.h

Currently, both `rxr_pkt_req_hdr_size` and `rxr_pkt_req_header_size` in `rxr_pkt_type_req.c`  calculate the header size of REQ packets and have considerable code duplication. This PR did some refactors in `rxr_pkt_type_req.c` to remove the code duplication and rename the functions to make them more intuitive.

prov/efa: Refactor the req header size functions

---

prov/efa/src/rxr/rxr_pkt_type_req.c

Backport https://github.com/ofiwg/libfabric/pull/8100

[v1.16.x] prov/efa: Fix a bug in rxr_pkt_req_max_header_size

---

man/fi_cq.3.md

Prettify the formating to clarify what the return codes mean.
Fixes #7997

man/cq: Update formatting in return code

---

prov/efa/src/efa_mr.c

This patch is a temporary workaround for issue:
https://github.com/ofiwg/libfabric/issues/8081
which is current cuda memory monitor does not monitor the event of cuda memory being freed, causing freed memory regions remain in cache.
The long term fix is to implement a cuda memory monitor that monitors cuda memory free event. Before that is implemented, this patch will detect such freed cuda memory region when registering a new memory region, and remove it from cache.
This patch is to be reverted after proper cuda memory monitor was implemented and used by efa.

prov/efa: remove de-allocated CUDA memory region during registration

---

fabtests/test_configs/psm3/psm3.exclude

psm3 is showing transient failures with the multinode test. Will re-enable once issue #8090 is resolved.

fabtests/psm3: disable multinode test

---

prov/efa/src/rxr/rxr.h

rxr_ep_rx_entry_init() is not used any more. This patch removed its declaration.
Signed-off-by: Vishwas Dsouza <vidsouza@amazon.com>

prov/efa: Remove unused function declaration

---

.github/workflows/pr-ci.yml
contrib/intel/jenkins/Jenkinsfile
contrib/intel/jenkins/common.py
contrib/intel/jenkins/run.py
contrib/intel/jenkins/runtests.py
contrib/intel/jenkins/summary.py
contrib/intel/jenkins/tests.py
fabtests/Makefile.am

The intent is to match the current TCP validations and to eventually merge the two.
It is understood that this will increase runtimes.

contrib/intel/jenkins: add CI support for net provider

---

prov/efa/src/efa.h
prov/efa/src/efa_domain.c
prov/efa/src/efa_fabric.c

When fork support is on, register memory regions was not copied to child processes's memory space.
With MR cache turned on, the registered memory regions remain registered after EFA finished send data from it.
As a result, when both fork support and MR cache are turned on, child processes cannot access some memory they need.
This patch addresses the issue by flush the MR cache when fork is called. Flushing MR cache will cause any memory region that is not actively being used (use_cnt == 0) to be de-registered, therefore they will be copied to child process's memory space
(cherry-picked from 5242e5bf5)

[v1.15.x] prov/efa: flush MR cache when fork() is called and fork support is ON

---

prov/efa/src/efa.h
prov/efa/src/efa_domain.c
prov/efa/src/efa_fabric.c

When fork support is on, register memory regions was not copied to child processes's memory space.
With MR cache turned on, the registered memory regions remain registered after EFA finished send data from it.
As a result, when both fork support and MR cache are turned on, child processes cannot access some memory they need.
This patch addresses the issue by flush the MR cache when fork is called. Flushing MR cache will cause any memory region that is not actively being used (use_cnt == 0) to be de-registered, therefore they will be copied to child process's memory space
(cherry-picked from 5242e5bf5)

[v1.14.x] prov/efa: flush MR cache when fork() is called and fork support is ON

---

prov/efa/src/rxr/rxr_pkt_type_req.c

Backport https://github.com/ofiwg/libfabric/pull/8100

[v1.14.x] prov/efa: Fix a bug in rxr_pkt_req_max_header_size

---

prov/efa/src/rxr/rxr_pkt_type_req.c

Backport https://github.com/ofiwg/libfabric/pull/8100

[v1.15.x] prov/efa: Fix a bug in rxr_pkt_req_max_header_size

---

fabtests/common/shared.c

In commit 1b12e5caa, mr close is moved before the ep close unconditionally. For non-FI_MR_ENDPOINT case, it is not safe to close mr before closing ep as the mr may still be used during ep finalization. This patch makes ft_free_res close mr before closing ep only when mr mode is FI_MR_ENDPOINT.

fabtests/common: close mr before closing ep for FI_MR_ENDPOINT only

---

include/rdma/fabric.h
man/fi_peer.3.md

Add FI_CLASS_PEER_AV and FI_CLASS_PEER_AV_SET needed by new peer structures.
@j-xiong - FYI

core/peer: Add missing FI_CLASS_PEER for AV and AV_SET

---

configure.ac

This PR added a config option to enable LTTNG tracing capability for tracing EFA OPs.
Signed-off-by: Tang, Jingyin <jytang@amazon.com>

core: Add a config option "--with-lttng" to enable LTTNG tracing capability in EFA.

---

prov/sockets/src/sock_ep.c

The addr may collide, e.g. with a dynamic process and the port is being recycled, when, the assertion of matching index won't hold since it may find a previous index. Move the index to the matching condition to prevent this error.
```
$ mpirun -n 1 ./th_taskmanager
th_taskmanager: prov/sockets/src/sock_ep.c:1846: sock_ep_lookup_conn: Assertion `conn->av_index == idx' failed.
```
The `th_taskmanager` repeatedly spawns and closes new processes. Eventually one of the processes will reuse a previous port. But the master process still holds all the previous addresses in av table, causing duplicated entries. Because currently, the interface is not connection-based, it is difficult to track the process connections in order to maintain a clean master av table. Luckily, the patch in this PR seems …

prov/sockets: fix assertion in sock_ep_lookup_conn

---

contrib/intel/jenkins/Jenkinsfile
include/ofi.h
include/ofi_mem.h
include/ofi_shm.h
man/fi_shm.7.md
prov/hook/hook_debug/src/hook_debug.c
prov/opx/src/fi_opx_info.c
prov/opx/src/fi_opx_init.c
prov/shm/Makefile.include
prov/shm/configure.m4
prov/shm/src/smr.h
prov/shm/src/smr_av.c
prov/shm/src/smr_dsa.c
prov/shm/src/smr_dsa.h
prov/shm/src/smr_ep.c
prov/shm/src/smr_init.c
prov/shm/src/smr_progress.c
prov/util/src/util_mem_monitor.c
prov/util/src/util_shm.c

Add initial DSA implementation to SHM provider. As part of this made other implementation changes: using multiple SAR buffers per copy operation, modifying SMR freestack to use aligned object allocation.

prov/shm: Enhanced SHM implementation with DSA offload

---

contrib/intel/jenkins/runtests.py

The Jenkins nodes use the naming convention "node-fabric" Jenkins parses by the '-' and assumes the first element to be the node name to ssh into. This delimiter conflicts with normal node naming convention which uses dashes within the node name. This changes the node/fabric delimiter from - to _ so it doesn't conflict with regular node names.
Note that this will require a momentary down period between naming the nodes and merging the PR.
After this change is merged, PRs will have to rebase on upstream in order to pass.
Cherry-picked from commit cb8dc8cc8a8e0c6d8adf6fd0015b9ed14afe3edb

[1.15.x] contrib/intel: change node name delimiter from - to _

---

prov/sockets/src/sock_av.c

Check `conn != SOCK_CM_CONN_IN_PROGRESS` in addition to `conn != NULL`, because `conn` can be partially initialized in `sock_ep_get_conn`. Acessing `SOCK_CM_CONN_IN_PROGRESS->av_index` causes a segfault.

prov/sockets: fix segfault for conn->av_index in sock_av_remove

---

include/ofi_util.h
man/fi_peer.3.md
prov/shm/src/smr.h
prov/shm/src/smr_atomic.c
prov/shm/src/smr_comp.c
prov/shm/src/smr_cq.c
prov/shm/src/smr_domain.c
prov/shm/src/smr_ep.c
prov/shm/src/smr_msg.c
prov/shm/src/smr_progress.c
prov/shm/src/smr_rma.c
prov/util/src/util_cq.c

Adds shared cq, shared rx, and av user id support to shm which uses it internally with itself as a first step to use shm as a peer provider
This includes the same API change from #7816 for CI purposes but will be removed once that is merged. This PR is mainly for testing purposes but also as an initial request for comment. I am still testing and reviewing and will update it. Adding do not merge label until I've cleaned it up and we've merged #7816

prov/shm: add shared cq, shared rx, av user id support

---

prov/sockets/src/sock_av.c

Check conn != SOCK_CM_CONN_IN_PROGRESS in addition to conn != NULL, because conn can be partially initialized in sock_ep_get_conn. Acessing SOCK_CM_CONN_IN_PROGRESS->av_index causes a segfault.
(cherry picked from commit bf66b48c133ccd78292b00b7c12123bed1a0d848)

[v1.16.x] prov/sockets: fix segfault for conn->av_index in sock_av_remove

---

contrib/intel/jenkins/Jenkinsfile

This typo fix will make jenkins pull the right repo/branch for its changes comparison instead of defaulting always to main.
(cherry picked from commit e621442935cf15628769608bbc89178d486683c8)

[v1.16.x] contrib/intel/jenkins: Fix typo in change_target

---

contrib/intel/jenkins/Jenkinsfile

Make jenkins checkout to a custom directory. This will fix the problem of two subjobs running together.
The problem this fixes is when Job1 is running and gets aborted by Job2's disableConcurrentBuilds option. Job2 aborts Job1 and causes Job1 to skip straight to the post cleanup stage where it deletes all workspace directories it used. The problem with this is that Job2 and Job1 shared the same workspace directory and so when Job1 deletes the current working directory of Job2, Job2 fails. Jenkins then gets stuck and cannot start a Job3 until the shared workspace directory is removed by hand.
The solution is to separate these workspaces into job_name/build_number. This way Job1 will checkout into Job/1 and therefore cleanup Job/1/* and Job2 will checkout into Job/2 and cleanup Job/2/* and …

contrib/intel/jenkins: Update jenkins workspace & globalize py_scripts variable

---

configure.ac

NVHPC compilers do not support -Wno-missing-field-initializers. To avoid issues down the road, test all the debug flags before adding to CFLAGS.
See pmodels/mpich#6221 for user report.

configure: Test all debug flags

---

contrib/intel/jenkins/build.py

make distcheck got added to the github action builds which cover all the providers. Having it here is no longer necessary and consummes a lot of build time.

contrib/intel: remove make distcheck

---

include/ofi_mem.h
prov/rxm/src/rxm_ep.c
prov/util/src/util_buf.c

It turns out rxm already uses attrs.alloc_fn/free_fn to handle host registration. Out of the three commits from PR #8137, revert the two commits related to the new flag and keep only the hmem_ze change.

Revert buffer pool flag changes

---

Makefile.am
configure.ac
include/freebsd/osd.h
include/linux/osd.h
include/ofi_net.h
include/osx/osd.h
include/windows/osd.h
prov/net/src/xnet_ep.c
prov/net/src/xnet_progress.c
prov/tcp/src/tcpx_ep.c
prov/tcp/src/tcpx_progress.c
src/common.c
src/iouring.c
src/osx/osd.c
src/windows/osd.c

This PR is an attempt at adding io_uring support to the bsock/byteq datastructures.
To do so, this PR adds a new interface named ofi_sockapi that aims at providing a common interface between io_uring and the traditional sockets.

ofi_net: add io_uring support and update bsock data structure

---

include/ofi.h
src/fabric.c
src/log.c

First patch is a general cleanup of the filtering functionality.
Second removes the restriction to allow the rxm provider to layer over the net provider. net;ofi_rxm is compatible with tcp;ofi_rxm.  This change will allow merging the net and tcp providers back together.
The last patch adds the ability to reorder the fi_info list separately from strict provider ordering.  This allows reporting the net provider's rdm ep support ahead of net;ofi_rxm.

core/getinfo: Reorder default fi_info list

---

src/hmem_ze.c

This reverts commit 1521915774c3fdf6c23d1cc479f870cf097ba1af.
The original commit was based on the fact that the link copy engine (usually command queue group 2) had much lower submission overhead than the main copy engine (usually command queue group 1). This is no longer the case with the latest oneAPI level-zero library. Now the submission overhead is similar among the command queue groups, and the groups are normally ordered descendently by maximum bandwidth.

Revert "hmem_ze: Reverse the order of searching for copy-only engine"

---

contrib/intel/jenkins/run.py
contrib/intel/jenkins/summary.py

Cross device testing was disabled because of unknown failures. This was probably due to the same configuration issue that was causing failures in the h->d and d->d testing.

contrib/intel: re-enable cross device testing

---

.github/workflows/pr-ci.yml

Support for MacOS 10.15 is being deprecated in December 2022. Update to MacOS 12

.github/workflows: update MacOS version

---

fabtests/pytest/common.py
fabtests/pytest/efa/test_mr.py

Instead of checking for "<warn>", make test_cuda_mr to check for specific message.

fabtests/efa/test_mr: check for specific warning message

---

man/fi_efa.7.md
prov/efa/src/efa.h
prov/efa/src/efa_domain.c
prov/efa/src/efa_domain.h
prov/efa/src/efa_ep.c
prov/efa/src/efa_hmem.c
prov/efa/src/efa_hmem.h
prov/efa/src/efa_mr.c
prov/efa/src/rxr/rxr_env.c
prov/efa/src/rxr/rxr_env.h
prov/efa/src/rxr/rxr_ep.c
prov/efa/src/rxr/rxr_msg.c
prov/efa/src/rxr/rxr_op_entry.c
prov/efa/src/rxr/rxr_pkt_type.h
prov/efa/src/rxr/rxr_pkt_type_req.c
prov/efa/src/rxr/rxr_rma.c
prov/efa/test/efa_unit_test_hmem.c
prov/efa/test/efa_unit_tests.c
prov/efa/test/efa_unit_tests.h

Creates a new env variable FI_EFA_MAX_EAGER_MSG_SIZE.
Simplifies code paths for selecting message protocol for send/rma based calls.

prov/efa: Configurable Eager Max Message Size

---

fabtests/pytest/conftest.py
fabtests/pytest/efa/efa_common.py
fabtests/pytest/efa/test_dgram.py
fabtests/pytest/efa/test_runt.py
fabtests/pytest/options.yaml
fabtests/pytest/pytest.ini
fabtests/pytest/requirements.txt
fabtests/scripts/runfabtests.py

This patch used the pytest-xdist package to run tests in parallel. One change made was that each xdist worker need to have its own oob port for oob address exchange.

fabtests/pytest: use pytest-xdist to parallelize tests

---

prov/net/src/xnet.h
prov/net/src/xnet_srx.c

We need to allocate an internal buffer to receive a discarded message.  Once the message has been received, we can free the buffer.  The buffer is stored in the recv_entry iov[0] as iov_base.  The iov_base is freed later.  However, as part of the receive handling, the iov_base can be updated.  This is done to handle partial receives, where we need to wait for additional data to arrive from the peer before receiving more data.
To fix, we need to record the address of the allocation in a separate location, so we can free it later.  Use the existing user_buf pointer for this, which is used in other places to track the start of the buffer.

prov/net: Fix possible crash handling FI_DISCARD

---

fabtests/pytest/efa/efa_common.py

commit d32b195bf1009 merged the stderr to stdout by 2>&1, which will mix the warning message with the hw counter value in the stdout.
It is also possible that process is not assigned as subprocess.run failed due to ssh connection issue, which will cause the undefined process used in the subsequent code.
This patch fixes the two issues above.

fabtests/pytest/efa: Fix bugs in efa_retrieve_hw_counter_value

---

.gitignore
fabtests/Makefile.am
fabtests/pytest/efa/test_efa_protocol_selection.py

Adds fabtest executables to .gitignore.
Adds a new EFA test to make sure that READ protocol is used when environmental controls are set.

fabtests: update .gitignore + fabtests/efa: Add new protocol decision test

---

prov/shm/src/smr_av.c

If the FI_AV_USER_ID flag is set on insert, set the fi_addr to report with completions as the inputed fi_addr from the user.

prov/shm: add support for FI_AV_USER_ID

---

prov/efa/src/rxr/rxr_env.c
prov/efa/src/rxr/rxr_prov.c

prov/efa: Set use_device_rdma as 1 when efa device id is 0xefa2.

---

.github/workflows/pr-ci.yml

Revert ".github/workflows: temporary workaround for failing ZE build"
This reverts commit 52f35998c2a93c37ce527641bfb43580501f8737.
The reverted commit was added as a workaround for a released version of level-zero which was buggy and failed building.
Reverting to test the latest in the distro instead of being stuck on 1.7.4

.github/workflows: Revert level-zero version workaround

---

include/ofi.h
include/ofi_util.h
prov/net/src/xnet_domain.c
prov/rxm/src/rxm.h
prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_domain.c
prov/rxm/src/rxm_init.c
prov/util/src/rxm_av.c
src/common.c
src/fabric.c

When sending or receiving messages, an AV may allocate resources underneath, such as establishing a connection. These connections can persist even if the peer's address is not inserted into the AV or after it's been removed. This can cause use of resources as long as the peer is running, but no longer actively communicating with another peer.
Add the ability to cleanup any underlying resources when removing an address from an AV.  This can free receive buffers, close fd's, etc. to reduce resource utilization.
This capability is disabled by default as it may abruptly terminate communication with a peer if there are data transfers in progress.  To enable, a libfabric wide environment variable must be set.
Signed-off-by: Sean Hefty …

util/rxm_av: Add option to free resources on AV removal

---

fabtests/multinode/include/core.h
fabtests/multinode/src/harness.c

Add an enum to set the pattern in a more readable way

fabtests/multinode: add enum to fix magic numbers

---

prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_atomic.c
prov/efa/src/rxr/rxr_cq.c
prov/efa/src/rxr/rxr_ep.c
prov/efa/src/rxr/rxr_msg.c
prov/efa/src/rxr/rxr_op_entry.h
prov/efa/src/rxr/rxr_pkt_cmd.c
prov/efa/src/rxr/rxr_pkt_type.h
prov/efa/src/rxr/rxr_pkt_type_base.c
prov/efa/src/rxr/rxr_pkt_type_base.h
prov/efa/src/rxr/rxr_pkt_type_data.c
prov/efa/src/rxr/rxr_pkt_type_misc.c
prov/efa/src/rxr/rxr_pkt_type_req.c
prov/efa/src/rxr/rxr_pkt_type_req.h
prov/efa/src/rxr/rxr_rma.c
prov/efa/src/rxr/rxr_rma.h

Code changes:
- Combined the previous tx/rx entry pools to a single entry pool called op_entry_pool.
- Removed unused/redundant variables present in rxr_op_entry.
- Modified dual entries (tx_entry/rx_entry) to op_entry.
- Resolved merge conflicts.
- Adapted naming conventions.
Functional differences:
Prior to this PR, only tx_entry on the responder side could send DATA. Therefore rxr_pkt_init_data, rxr_pkt_handle_data_sent, rxr_pkt_handle_send_completion were using only tx_entry.
Also, only rx_entry on the requestor side could receive DATA and send CTS. Therefore rxr_pkt_handle_data_recv, and rxr_pkt_init_cts, rxr_pkt_handle_cts_sent were using this rx_entry.
With this change, there are only single entries on both ends of the communication - tx_entry on the requestor side and rx_entry on …

prov/efa: simplified emulated read protocol

---

fabtests/scripts/runfabtests.py

fabetsts/runfabtests.py: do not use parallel test by default

---

fabtests/pytest/efa/efa_common.py

It is not necessary to run this check for each efa client-server test. Also, this check will depend on platform in the future.

fabtests/pytest/efa: remove the rdma-read check in efa_run_client_server_test

---

prov/efa/docs/pkt-processing.md
prov/efa/src/efa_av.c
prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_atomic.c
prov/efa/src/rxr/rxr_cq.c
prov/efa/src/rxr/rxr_ep.c
prov/efa/src/rxr/rxr_msg.c
prov/efa/src/rxr/rxr_msg.h
prov/efa/src/rxr/rxr_op_entry.c
prov/efa/src/rxr/rxr_op_entry.h
prov/efa/src/rxr/rxr_pkt_cmd.c
prov/efa/src/rxr/rxr_pkt_entry.c
prov/efa/src/rxr/rxr_pkt_entry.h
prov/efa/src/rxr/rxr_pkt_type.h
prov/efa/src/rxr/rxr_pkt_type_base.c
prov/efa/src/rxr/rxr_pkt_type_base.h
prov/efa/src/rxr/rxr_pkt_type_misc.c
prov/efa/src/rxr/rxr_pkt_type_req.c
prov/efa/src/rxr/rxr_pkt_type_req.h
prov/efa/src/rxr/rxr_read.c
prov/efa/src/rxr/rxr_read.h
prov/efa/src/rxr/rxr_rma.c

This change removes the rxr_rx_entry and rxr_tx_entry macro definitions and replaces them with rxr_op_entry.
Signed-off-by: Vishwas Dsouza <vidsouza@amazon.com>

prov/efa: remove rxr_rx_entry and rxr_tx_entry macro definitions

---

prov/efa/Makefile.include
prov/efa/docs/efa_tracing.txt
prov/efa/src/rxr/rxr_cq.c
prov/efa/src/rxr/rxr_msg.c
prov/efa/src/rxr/rxr_pkt_type_misc.c
prov/efa/src/rxr/rxr_pkt_type_req.c
prov/efa/src/rxr/rxr_tp.h
prov/efa/src/rxr/rxr_tp_def.c
prov/efa/src/rxr/rxr_tp_def.h

This PR adds 9 tracepoints into EFA provider. Detailed tracepoints are listed in its docs `prov/efa/docs/efa_tracing.txt`
Signed-off-by: Tang, Jingyin <jytang@amazon.com>

prov/efa: Add tracepoints to send/recv/read ops

---

prov/shm/src/smr_atomic.c

In smr_atomic_inject() there was an extraneous ofi_cirque_next() call. This didn't cause an issue because ofi_cirque_next() would return the same entry for multiple calls as long as there was no commit function call in between.
Signed-off-by: Amir Shehata <shehataa@ornl.gov>

prov/shm: remove extraneous ofi_cirque_next() call

---

fabtests/multinode/src/core_coll.c
include/ofi_coll.h
include/ofi_enosys.h
include/rdma/fi_collective.h
man/fi_collective.3.md
prov/util/src/util_coll.c
src/enosys.c

Changes introduced by commit d634fb7adc9e27e149ae0480e768d9744faae891 may break upper layer library build. Rework the changes to maintain API compatibility.

collective: Rework the fi_barrier change

---

include/ofi_hmem.h
prov/net/src/xnet_progress.c
prov/shm/src/smr_ep.c
src/hmem.c
src/hmem_ipc_cache.c

At least I think this renames the parameters for consistency and to make them easier to understand.  I didn't update the underlying calls, only the hmemops.  Renames are generally
ptr -> addr
ipc_ptr -> mapped_addr
base -> base_addr
dev_buf -> base_addr
size (when referring to base_addr) -> base_length

core/hmem_ops: Rename parameters for consistency

---

prov/rxm/src/rxm_cq.c

This PR removes source code redundancy between rxm_ep_progress_coll and rxm_ep_progress

prov/rxm: remove redundant code of rxm_ep_progress_coll

---

prov/efa/src/efa_hmem.c

Previous commit wrongly set the max_medium_msg_size to 0 for host memory, which caused medium message protocol not being used. This patch fixed the issue.

prov/efa: fix default value for host memory's max_medium_msg_size

---

fabtests/functional/loopback.c
prov/net/src/xnet.h
prov/net/src/xnet_rdm.c
prov/net/src/xnet_rdm_cm.c
prov/net/src/xnet_srx.c

prov/net: Release lock in case of error in rdm_close
fabtests/loopback: Update to use loopback IP address, fix setting hints, and use tagged messages

prov/net: Fix loopback receive handling + other updates

---

fabtests/regression/sighandler_test.c

This patch gives child more time to handle SIGINT. This allowes 3rd party library signal handler to have enough time to handle the signal.

fabtests/sighandler_test: give child more time to handle signal

---

fabtests/regression/sighandler_test.c

This patch gives child more time to handle SIGINT. This allowes 3rd party library signal handler to have enough time to handle the signal.
(cherry picked from commit 3852a3309a8f470438f5b431b8dca97cc202dc7d)

[v1.16.x] fabtests/sighandler_test: give child more time to handle signal

---

fabtests/functional/rdm_atomic.c

Before this patch, alloc_ep_res() would allocate buffers on the host, but ft_reg_mr() uses opt.iface to register the buffers as cuda buffers. This caused the EFA provider to segfault during memory registration. This patch allocates the result/compare buffers on the device, which allows the memory to be successfully registered.
Testing:
Built-in providers:	dmabuf_peer_mem hook_hmem hook_debug perf rstream shm rxd mrail rxm net tcp udp efa verbs sockets 
Ran:
```
fi_rdm_atomic -E.                    # runs successfully
fi_rdm_atomic -D cuda -E      # everything skips - my next change to EFA will provide atomic support for hmem.
```

fabtests/fi_rdm_atomic: Fix hmem support

---

prov/shm/src/smr_av.c

Set current index, not total count index

prov/shm: fix index when setting FI_ADDR_USER_ID

---

prov/shm/src/smr_av.c

Set current index, not total count index

[v1.17.x] prov/shm: fix index when setting FI_ADDR_USER_ID

---

include/ofi_net.h
prov/net/src/xnet.h
prov/net/src/xnet_progress.c
src/common.c
src/iouring.c

This PR adds support of io_uring to TX operations.
The implementation is still incomplete because of the following missing features:
1. We need a mechanism to cancel all pending io_uring operations
and wait for them to complete before we can close the ring.
Right now, pending operations would cause the code to fail
the assertion failure !ep->cur_tx.uring_busy in
xnet_ep_flush_all_queues().
2. ofi_uring_submit() might return an error or submit fewer
SQs than expected. This is handled using an assertion failure 
right now and we definitely need a better strategy there.

prov/net: TX operations now support io_uring

---

prov/shm/src/smr_progress.c

Outstanding response entries always point to outgoing messages and should always be written to the tx cq.

[v1.17.x] prov/shm: write tx err comp to correct cq

---

prov/shm/src/smr_progress.c

Outstanding response entries always point to outgoing messages and should always be written to the tx cq.

prov/shm: write tx err comp to correct cq

---

include/windows/ifaddrs.h
src/common.c

Add checking for ifa_flags for IFF_RUNNING flag to filter out the interface, which is down and not running. In WinOS, there is not definition of IFF_RUNNING, reset it by IFF_UP.

common: add IFF_RUNNING check to indicate iface is up and running

---

prov/net/src/xnet_progress.c

io_uring implementation is proceding in mainline, but disabled in release branch.

[v1.17.x] prov/net: Eliminate build warning due to partial io_uring support

---

include/windows/ifaddrs.h
src/common.c

Add checking for ifa_flags for IFF_RUNNING flag to filter out the interface, which is down and not running. In WinOS, there is not definition of IFF_RUNNING, reset it by IFF_UP.

[v1.17.x] common: add IFF_RUNNING check to indicate iface is up and running

---

prov/sockets/src/sock_progress.c

This is a back port of #8259 to v1.17.x.
When we make dynamic connections, it is possible for a connect message to arrive before the receiver issue fi_av_insert. This result in conn->av_index being set to FI_ADDR_NOTAVAIL, and leading to future message mismatch.
Retry setting the av_index fixes the issue. It works because the matching will always happen after the receiver issues fi_av_insert or it has to be a wild card receive.

prov/sockets: retry setting conn->av_index

---

prov/shm/src/smr_av.c

fi_addr is an array of values, not an array of pointers so assert(fi_addr[i]) would fail if the application passed in an fi_addr of 0

prov/shm: fix user_id support

---

prov/shm/src/smr_av.c

fi_addr is an array of values, not an array of pointers so assert(fi_addr[i]) would fail if the application passed in an fi_addr of 0

[v1.17.x] prov/shm: fix user_id support

---

contrib/intel/jenkins/Jenkinsfile
contrib/intel/jenkins/summary.py

Add a printout of almost every test that passed to the verbose summary in post stage.
Tests that don't have unique names aren't printed.
Sometimes having a list of every test that gets run is better than just having the total number of tests run.

contrib/intel/jenkins: add verbose summary to post stage

---

prov/net/src/xnet.h
prov/net/src/xnet_cm.c
prov/net/src/xnet_ep.c
prov/net/src/xnet_init.c
prov/net/src/xnet_pep.c
prov/net/src/xnet_progress.c
prov/net/src/xnet_srx.c

Enhancements to support MPI RMA / barrier hangs.  See commit messages for details.

[v1.17.x] prov/net: Add save and restart look-ahead message processing

---

fabtests/Makefile.am
fabtests/component/dmabuf-rdma/fi-rdmabw-xe.c
fabtests/component/dmabuf-rdma/ofi_ctx_pool.h

This allows the test to work with more providers (e.g. psm3).
Also remove FI_HMEM from the hints since it is not a hard requirement for the test.

fabtests/component: Support FI_CONTEXT mode in fi-rdmabw-xe test

---

man/fi_opx.7.md

Slight fix to man page, SDMA is now supported.

man fi_opx: remove PIO-only disclaimer

---

fabtests/Makefile.am
fabtests/component/dmabuf-rdma/fi-rdmabw-xe.c
fabtests/component/dmabuf-rdma/ofi_ctx_pool.h

This allows the test to work with more providers (e.g. psm3).
Also change the FI_HMEM caps setting from always on to only set when device memory is used.
(cherry picked from commit bc56cb3a653e35ca959bbf47cdd3417bce9b9307)

[v1.17.x] fabtests/component: Support FI_CONTEXT mode in fi-rdmabw-xe test

---

fabtests/Makefile.am
fabtests/component/dmabuf-rdma/fi-rdmabw-xe.c
fabtests/component/dmabuf-rdma/ofi_ctx_pool.h

This allows the test to work with more providers (e.g. psm3).
Also change the FI_HMEM caps setting from always on to only set when device memory is used.
(cherry picked from commit bc56cb3a653e35ca959bbf47cdd3417bce9b9307)

[v1.16.x] fabtests/component: Support FI_CONTEXT mode in fi-rdmabw-xe test

---

prov/net/src/xnet_srx.c

We need the saved_entry not unexp_entry.

[v1.17.x] prov/net: Fix crash accessing ep

---

.gitignore

This patch added the Visual Studio Code configuration folder to .gitignore

.gitignore: add Visual Studio Code configuration folder

---

fabtests/pytest/conftest.py
fabtests/pytest/efa/efa_common.py
fabtests/pytest/efa/test_dgram.py
fabtests/pytest/efa/test_runt.py
fabtests/pytest/options.yaml
fabtests/pytest/pytest.ini
fabtests/pytest/requirements.txt
fabtests/scripts/runfabtests.py

Backporting to `v1.16.x` branch
> This patch used the pytest-xdist package to run tests in parallel. Notable changes include:
> 
> 1. This feature is only enabled for EFA provider.
> 
> 2. A new marker "serial" was introduced. Tests that must be run in serial are assigned this marker, and will be run in serial via a separate run.
> 
> 3. Junit parser was used to merge xml report from 2 runs.
> 
> 4. Each xdist worker need to have its own oob port for oob address exchange.
> 
> 5. increased timeout value for individual test because single test can take longer to finish when run in parallel
> 
> Signed-off-by: Wei Zhang <wzam@amazon.com>

[v1.16.x] fabtests/pytest: use pytest-xdist to parallelize tests

---

include/rdma/fabric.h
prov/net/src/xnet.h
prov/net/src/xnet_cm.c

The FI_PEER flag is sufficient for allocating peer objects.

fabric: Remove FI_PEER_DOMAIN

---

prov/rxm/src/rxm_msg.c

Bounce buffer copy overhead is high for ZE device memory. The rendezvous protocol takes advantage of GPU RDMA and performs better even for small messages.

prov/rxm: Always use rendezvous protocol for ZE device memory send

---

prov/rxm/src/rxm_msg.c

Bounce buffer copy overhead is high for ZE device memory. The rendezvous protocol takes advantage of GPU RDMA and performs better even for small messages.

[v1.17.x] prov/rxm: Always use rendezvous protocol for ZE device memory send

---

prov/efa/src/rxr/rxr_ep.c

This patch added initialization of op_entry->entry when initializing tx_entry and rx_entry.
(cherry picked from commit 3de448821985020303256aa2f35456079d5750e4)

[v1.16.x] prov/efa: initialize op_entry->entry during rxr_ep_alloc_rx_entry

---

prov/rxm/src/rxm_msg.c

Bounce buffer copy overhead is high for ZE device memory. The rendezvous protocol takes advantage of GPU RDMA and performs better even for small messages.
(cherry picked from commit 7efb4f8715f062a10b421672057b8d38dbde534e)

[v1.16.x] prov/rxm: Always use rendezvous protocol for ZE device memory send

---

prov/rxm/src/rxm_msg.c

Bounce buffer copy overhead is high for ZE device memory. The rendezvous protocol takes advantage of GPU RDMA and performs better even for small messages.
(cherry picked from commit 7efb4f8715f062a10b421672057b8d38dbde534e)

[v1.15.x] prov/rxm: Always use rendezvous protocol for ZE device memory send

---

prov/efa/src/rxr/rxr_ep.c

This patch added a call to FI_WARN to print endpoint's address and libfabric version after endpoint is created.

prov/efa: add a FI_WARN about endpoint address after it is created

---

prov/efa/src/efa_prov_info.c
prov/efa/src/efa_prov_info.h
prov/efa/src/efa_user_info.c

Back porting to v1.17.x
> Prior to this patch, the provider would ignore the domain name in hints->domain_attr->name even if this was set. This patch fixed this issue.
> 
> Signed-off-by: Vishwas Dsouza <vidsouza@amazon.com>
> (cherry picked from commit 5281cf5dc18daf18414ae27edb49f34427920612)

[v1.17.x] prov/efa: Do no ignore hints->domain_attr->name

---

prov/efa/src/efa_prov_info.c
prov/efa/src/efa_prov_info.h
prov/efa/src/efa_user_info.c

Back porting to v1.16.x
> Prior to this patch, the provider would ignore the domain name in hints->domain_attr->name even if this was set. This patch fixed this issue.
> 
> Signed-off-by: Vishwas Dsouza <vidsouza@amazon.com>

[v1.16.x] prov/efa: Do no ignore hints->domain_attr->name

---

contrib/intel/jenkins/Jenkinsfile

In the event where git cloning upstream/main provides newer python files than the Jenkinsfile is expecting. There will be failures when the new python expected the old Jenkinsfile to call something that it didn't. Changing to checkout the same branches python files to avoid this mismatch.

contrib/intel/jenkins: Make git clone specifiy which branch

---

prov/rxm/src/rxm_fabric.c

The macro is for function parameters only.

prov/rxm: Fix incorrect use of OFI_UNUSED()

---

prov/efa/src/efa_mr.c

This essentially reverts fcc1139, which was necessary to prevent segfaults when calling `ibv_dereg_mr()` with a `NULL` pointer. Since that commit, the call to `ibv_dereg_mr()` was replaced with a call to `efa_mr_dereg_impl()`, which does not necessarily need `efa_mr->ibv_mr`.

prov/efa: Call efa_mr_dereg_impl() unconditionally

---

prov/efa/src/efa.h
prov/efa/src/efa_domain.c
prov/efa/src/efa_hmem.c
prov/efa/src/efa_hmem.h

This commit:
- Centralizes the protocol variable initialization for the various HMEM interfaces
- Defines `EFA_DEF_XXX` macros for default protocol message sizes, to abstract the hardcoded default values from the core logic
- Changes the "update" nomenclature to "init", which better indicates the intention/behavior of the functions
- Initializes the protocol variables for `FI_HMEM_CUDA` when p2p is unavailable (uses `FI_HMEM_SYSTEM` defaults)
- Adds a missing check for `FI_EFA_MIN_READ_WRITE_SIZE` when initializing the `FI_HMEM_SYNAPSEAI` interface info

prov/efa: Clean up efa_hmem_info initialization

---

prov/net/src/xnet.h

Commit 3ae11c498f350e3532d0c6268ca217903b3e5f0e broke inject support by removing the buffering provided for inject.  Add the inject buffer size back into the hdr size.

prov/net: Fix inject support

---

include/ofi_hmem.h
src/hmem.c
src/hmem_cuda.c

Added const to data parameter of cuPointerSetAttribute function pointer to
remove compiler warning.
Move implementation of ofi_copy_to_hmem() and ofi_copy_from_hmem() from
source to header.
Add New HMEM Utility Method.

source/ofi_hmem: Make Copy Utils Public + Warning Cleanup + New HMEM Utility Method

---

include/ofi_hmem.h
src/hmem_cuda.c

The environment variable FI_HMEM_CUDA_ENABLE_XFER control whether CUDA API can be used to copy data. Currently, its help string states that it default value is true, which means by default a provider is safe to make CUDA calls.
However, by default it is not always safe for a provider to make CUDA calls, and some providers does not make CUDA calls by default. Such provider still need to make CUDA calls when user explictly set this environment variable to true.
This patch used an enum (instead of a boolean) to store the value of the user setting. The enum has three possible values:
CUDA_XFER_DISABLED means the environment variable is set to 0
CUDA_XFER_ENABLED means the environment variable is set to 1
CUDA_XFER_UNSPECIED means the environment variable is not set
It then exposed the value …

core/hmem_cuda: adjust FI_HMEM_CUDA_ENABLE_XFER behavior

---

fabtests/functional/rdm_tagged_peek.c
man/fi_peer.3.md
prov/net/src/xnet.h
prov/net/src/xnet_cq.c
prov/net/src/xnet_ep.c
prov/net/src/xnet_init.c
prov/net/src/xnet_progress.c
prov/net/src/xnet_srx.c

man/peer: Clearly indicates that peer APIs are not stable (from v1.17.x)
prov/net: Fix inject support (from v1.17.x)
fabtests/tagged_peek: Restructure and expand test coverage
prov/net: Allow saving multiple small messages to support OOO messages

prov/net (mostly): Allow saving a small number of out-of-order messages

---

src/hmem_cuda.c

Previous commit 148dfd7d7e3a introduced cuda_get_xfer_setting() but did not implement it for non-CUDA build. This patch fixed it.

src/hmem_cuda: implement cuda_get_xfer_setting for non cuda build

---

prov/efa/src/efa.h
prov/efa/src/efa_ep.c
prov/efa/src/efa_hmem.c
prov/efa/src/efa_hmem.h
prov/efa/src/rxr/rxr_ep.c
prov/efa/test/efa_unit_test_hmem.c

This adds a `p2p_required_by_impl` field to the `efa_hmem_info` struct as a way to track the minimum p2p requirements for each supported `FI_HMEM` interface. Since the p2p requirements of each interface is more-or-less unwritten/institutional knowledge, it should be defined in a single place and queried as needed, instead of hardcoding in various places throughout the codebase or deducing from a combination of other parameters.
The `p2p_required_by_impl` field also offers some dynamic configurability if we choose to utilize it. I.e. if we want to set `p2p_required_by_impl` based on some runtime condition.
As an initial use-case, this PR also adds a function for checking the validity of an endpoint p2p opt against a given HMEM interface in a more generic way (i.e. without the need to …

prov/efa: Add `p2p_required_by_impl` to `efa_hmem_info` struct, implement generic p2p opt initialization/validation

---

fabtests/pytest/efa/efa_common.py
fabtests/pytest/efa/test_efa_device_selection.py

The efa_test_device_selection assume both nodes have same device name/numbers, which is not always the case.
This patch addressed the issue.

pytest/efa: handle device differences in test_device_selection

---

prov/rxm/src/rxm_ep.c

Collective providers must be closed during rxm_ep closing to avoid error on AV closing: "off_coll:av:ofi_av_close_lightweight():400<warn> AV is busy".

prov/rxm: close collective providers ep when rxm_ep is closed

---

src/hmem_cuda.c

This effectively defers any limitation(s) on CUDA IPC to the initialization of `cuda_ipc_enabled`, which in turn depends on the status of `FI_HMEM_CUDA_ENABLE_XFER`

src/hmem_cuda: Allow CUDA IPC when P2P disabled

---

contrib/intel/jenkins/Jenkinsfile

Summary.py does not exist on the daos cluster if the opt-out path was taken. Check to see if opt-out path was taken since the 'when' clause cannot be applied here.

contrib/intel/jenkins: Succeed on opt-out path in daos summary stage

---

libfabric.vcxproj
prov/efa/Makefile.include
prov/efa/src/efa_av.c
prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_cq.c
prov/efa/src/rxr/rxr_ep.c
prov/efa/src/rxr/rxr_msg.c
prov/efa/src/rxr/rxr_pkt_cmd.c
prov/efa/src/rxr/rxr_pkt_entry.c
prov/efa/src/rxr/rxr_pkt_entry.h
prov/efa/src/rxr/rxr_pkt_pool.c
prov/efa/src/rxr/rxr_pkt_pool.h
prov/efa/src/rxr/rxr_pkt_type_base.c
prov/efa/src/rxr/rxr_pkt_type_data.c
prov/efa/src/rxr/rxr_pkt_type_misc.c
prov/efa/src/rxr/rxr_pkt_type_req.c
prov/efa/src/rxr/rxr_pkt_type_req.h
prov/efa/src/rxr/rxr_prov.c
prov/efa/src/rxr/rxr_read.c
prov/efa/test/efa_unit_test_common.c
prov/efa/test/efa_unit_test_ep.c

- rxr_pkt_entry is now allocated from a ofi_buf_pool called local_info_pool
- rxr_pkt_entry->pkt has now been renamed to wiredata and is allocated from a separate ofi_buf_pool
- ep->pkt_sendv_pool has been removed and rxr_pkt_entry->send is allocated from the local_info_pool

prov/efa: Allocate rxr_pkt_entry from two separate ofi_buf_pools

---

man/fi_efa.7.md
prov/efa/src/efa.h
prov/efa/src/efa_hmem.c
prov/efa/src/efa_mr.c
prov/efa/src/efa_user_info.c
prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_op_entry.h
prov/efa/src/rxr/rxr_pkt_cmd.c
prov/efa/src/rxr/rxr_pkt_type_base.c

~~NOTE: Marking as "Do not merge" until #8357 is merged into `main` and this PR's branch can be rebased.~~ #8357 merged
This implements various minor changes to enable the `FI_HMEM_CUDA` interface even when GPUDirect RDMA is unavailable.

prov/efa: Enable `FI_HMEM_CUDA` usage when p2p is unavailable

---

prov/net/src/xnet.h
prov/net/src/xnet_attr.c
prov/net/src/xnet_cq.c
prov/net/src/xnet_init.c
prov/net/src/xnet_msg.c
prov/net/src/xnet_progress.c
prov/net/src/xnet_rma.c

This allows for a larger inject size and larger messages to be buffered at the receive side.

prov/net: Dynamically set the inject message size

---

prov/efa/test/README.md
prov/efa/test/efa_unit_test_av.c
prov/efa/test/efa_unit_test_cq.c
prov/efa/test/efa_unit_test_ep.c
prov/efa/test/efa_unit_test_hmem.c
prov/efa/test/efa_unit_tests.c

Previously, the teardown actions were part of the unit test code. With this approach, any unrecoverable failure in one test would cause the subsequent unit tests to fail.
This commit moves the teardown actions to a separate function that is executed by the framework even if one unit test fails and allows for subsequent unit tests to run successfully.

prov/efa: Move unit test teardown actions to teardown function

---

prov/efa/test/efa_unit_tests.c

Using struct efa_resource ** causes incompatible pointer warnings when the setup and teardown functions are used
Example warning
```
prov/efa/test/efa_unit_tests.c:76:96: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
cmocka_unit_test_setup_teardown(test_efa_hmem_info_update_neuron, efa_unit_test_mocks_setup, efa_unit_test_mocks_teardown),
```
These only happen the first time I compile, so I missed them yesterday

prov/efa: Use void ** for setup and teardown functions

---

contrib/intel/jenkins/Jenkinsfile

DSA Node is currently down. This is a temporary patch to allow the CI to pass while everyone is away on vacation.

contrib/intel/jenkins: Disable DSA Testing while DSA Node is down.

---

man/fi_atomic.3.md

man/atomic: Clarify Atomic Correctness Definition in Man Pages

---

src/fabric.c

In case a provider returned an error, print a message in WARN level only if the requested provider matches the failed provider.
Signed-off-by: Firas Jahjah <firasj@amazon.com>

fabric: Improve log level of provider mismatch

---

prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_pkt_cmd.c
prov/efa/src/rxr/rxr_pkt_entry.h
prov/efa/src/rxr/rxr_pkt_type_data.c
prov/efa/src/rxr/rxr_pkt_type_misc.c
prov/efa/src/rxr/rxr_pkt_type_req.c
prov/efa/src/rxr/rxr_pkt_type_req.h

Prior to this patch, the TX entry of a DC longcts
protocol was released when both all DATA packets' send completion have arrived and RECEIPT packet was released.
This is not ideal, because we want to write TX completion as soon as RECEIPT was received.
The current implementation is because of two things:
First, there is no information in the packet
entry can be used to determine whether a DATA packet is used by a DC longcts protocol or a normal longcts protocol,
Second, if a DATA packet is used by a normal longcts protocol, the op_entry's byte_acked must be updated.
Beacuse of 1, we have to update tx_entry->byte_acked when we receive the send completion of a DATA packet, which means the tx_entry must not be released when we received the send completion of the DATA packet.
As a result, we …

prov/efa: simplify implementation of DC longcts protocol

---

Makefile.am
man/fabric.7.md
man/fi_arch.7.md
man/fi_cm.3.md
man/fi_collective.3.md
man/fi_getinfo.3.md
man/fi_guide.7.md
man/fi_intro.7.md
man/fi_provider.7.md
man/fi_setup.7.md
man/fi_tagged.3.md
man/man7/fi_arch.7
man/man7/fi_guide.7
man/man7/fi_intro.7
man/man7/fi_setup.7

Relocate and update the ofi-guide from the adjacent git repo to integrate with the libfabric man pages.  This will make it easier to keep it in sync with API updates and avoid duplicate text between the guide and other man pages.
Update man pages to align with guide, expanding descriptions as needed, with appropriate references between man pages. Remove duplicate and outdated text.

man/guide: Add user-guide to man pages

---

prov/efa/src/efa.h
prov/efa/src/efa_ep.c
prov/efa/src/efa_msg.c
prov/efa/src/rxr/rxr_cq.c
prov/efa/src/rxr/rxr_ep.c
prov/efa/src/rxr/rxr_pkt_entry.c
prov/efa/src/rxr/rxr_pkt_entry.h

For SHM EP, use fi_sendv and fi_recvv
For EFA EP
* Allocate ibv_send_wr and ibv_recv_wr in rxr_pkt_entry
* Still use efa_ep->qp, efa_ep->av and efa_ep->xmit_more_wr*
* Directly call efa_post_flush or ibv_post_recv in rxr_pkt_entry.c

prov/efa: Remove fi_sendmsg/recvmsg but still use efa_ep's qp and av

---

prov/efa/Makefile.include
prov/efa/src/efa.h
prov/efa/src/efa_av.c
prov/efa/src/rxr/efa_rdm_peer.c
prov/efa/src/rxr/efa_rdm_peer.h
prov/efa/src/rxr/rxr.h
prov/efa/src/rxr/rxr_atomic.c
prov/efa/src/rxr/rxr_cq.c
prov/efa/src/rxr/rxr_ep.c
prov/efa/src/rxr/rxr_msg.c
prov/efa/src/rxr/rxr_op_entry.c
prov/efa/src/rxr/rxr_op_entry.h
prov/efa/src/rxr/rxr_pkt_cmd.c
prov/efa/src/rxr/rxr_pkt_cmd.h
prov/efa/src/rxr/rxr_pkt_entry.c
prov/efa/src/rxr/rxr_pkt_type.h
prov/efa/src/rxr/rxr_pkt_type_data.c
prov/efa/src/rxr/rxr_pkt_type_misc.c
prov/efa/src/rxr/rxr_pkt_type_req.c
prov/efa/src/rxr/rxr_pkt_type_req.h
prov/efa/src/rxr/rxr_read.c
prov/efa/src/rxr/rxr_rma.c
prov/efa/test/efa_unit_test_cq.c
prov/efa/test/efa_unit_test_ep.c

The peer structure has been give different names as:
rdm_peer, efa_peer and rxr_peer,
which caused confusion.
This patch unified the name to efa_rdm_peer

prov/efa: rename rdm_peer,efa_peer,rxr_peer to efa_rdm_peer

---

libfabric.vcxproj

Add efa_rdm_peer.c to the list of EFA sources

libfabric.vcxproj: add efa_rdm_peer.c

---

fabtests/pytest/efa/test_rdm.py

EFA only supports FI_HMEM + FI_ATOMIC with CUDA memcpy.

fabtests/pytest/efa: Set FI_HMEM_CUDA_ENABLE_XFER=1

---

prov/efa/src/efa_domain.c
prov/efa/src/efa_hmem.c
prov/efa/src/efa_hmem.h
prov/efa/src/rxr/rxr_ep.c

This is a minor refactor to remove superfluous parameters from the `efa_hmem_info` init functions and reorders them s.t. output params follow any input params.
The motivation is purely for the interface and Doxygen comments to make more sense.

prov/efa: Refactor `efa_hmem.c`, tidy Doxygen comments

---

prov/efa/src/rxr/rxr_pkt_entry.c

This patch added "efa_tp.h" to rxr_pkt_entry.c to fix the compilation failure with lttng enabled.

prov/efa: add missing header file to rxr_pkt_entry.c

---

fabtests/common/shared.c
fabtests/include/shared.h
fabtests/ubertest/domain.c
fabtests/ubertest/test_ctrl.c

Need to allocate host buffer for filling data. Separate function in common code in order to call it from ubertest.

fabtests/ubertest: fix data validation with device memory

---

include/ofi_net.h
prov/net/src/xnet.h
prov/net/src/xnet_progress.c
prov/tcp/src/tcpx.h
prov/tcp/src/tcpx_progress.c
src/common.c

This PR implements a couple of changes to the bsock API in order to support async operations. 
These changes were initially implemented as part of #8262 but I think they deserve their own PR.
The most significant change is the conversion of the return type for the bsock interface. 
The functions now return a int (instead of a size_t) where a value of 0 means success and a value < 0 corresponds to a failure.
The number of bytes received and available for processing is returned in the input/output argument *len.

bsock: A couple of changes to the interface and related to async operations

---

fabtests/multinode/include/coll_test.h
fabtests/multinode/src/core_coll.c

Some collective providers do not support all collective operations. In such a case unsupported operations will not affect the final test result.
A new "query" step is defined for each test. This step verifies via fi_query_collective() whether the operation support. The test is silently skipped if fi_query_collective returns -FI_ENOSYS.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ofiwg/libfabric/8295)

fabtests/multinode: Skip tests for unsupported collective operations

---

src/hmem_synapseai.c

host pointer register and deregister are no-ops for synpase ai. return FI_SUCCESS for them
Signed-off-by: EC2 Default User <ec2-user@ip-172-31-58-230.us-west-2.compute.internal>

hmem_synpaseai: return 0 for host_register and host_deregister

---

prov/efa/test/efa_unit_test_av.c
prov/efa/test/efa_unit_test_common.c
prov/efa/test/efa_unit_test_ep.c
prov/efa/test/efa_unit_tests.c
prov/efa/test/efa_unit_tests.h

No point in continuing the test or checking the return value in the test body

prov/efa: Fail unit test early if resource struct fails

---

prov/efa/src/rxr/rxr_cq.c

This matches the behavior of `rxr_cq_write_tx_error()`

prov/efa: Print local/peer addresses for RX write errors

---

prov/efa/src/rxr/rxr_cq.c

Backporting to `v1.16.x`. Cherry-picked from 51ec51a340f2aca8d408b72351f4676a8a2399a0

[v1.16.x] prov/efa: Print local/peer addresses for RX write errors

---

prov/efa/src/rxr/rxr_cq.c

Backporting to `v1.17.x`. Cherry-picked from 51ec51a340f2aca8d408b72351f4676a8a2399a0

[v1.17.x] prov/efa: Print local/peer addresses for RX write errors

---

prov/net/src/xnet_ep.c
prov/net/src/xnet_progress.c

This patch adds support of io_uring to RX operations.
The implementation is still incomplete because we need a mechanism
to cancel all pending io_uring operations and wait for them to
complete before we can close the ring. Pending receive operations
would cause the code to fail an assertion failure when the endpoint
is shut down.

prov/net: RX operations now support io_uring

---

fabtests/pytest/common.py

In client-server tests, SSH connection error will cause both the client and server processes to be terminated and retried. This is inefficient and problematic.
When the server startup is slow, e.g. > 1 second, OOB address exchange will fail due to SSH connection. In this case, restarting both the server and client does not solve the problem. Instead, we only need to retry the client process.

fabtests/pytest/common.py: retry client process separately in client server tests

---

fabtests/pytest/conftest.py

Neuron runtime runs `lspci` in shell. This is a problem in the current implementation, which runs the remote command in non-interactive mode, e.g. `ssh 1.2.3.4 lspci` produces `sh: lspci: command not found`, because the non-interactive shell has a different environment. The solution is to run the command in interactive mode, i.e. `ssh 1.2.3.4 bash --login -c lspci`.
However, please note the side effect that we are now locked into `bash`.

fabtests/pytest/conftest.py: changes to running remote commands

---

fabtests/pytest/common.py
fabtests/pytest/efa/conftest.py
fabtests/pytest/efa/test_mr.py
fabtests/pytest/efa/test_rdm.py
fabtests/pytest/efa/test_runt.py
fabtests/pytest/pytest.ini
fabtests/pytest/shm/conftest.py
fabtests/scripts/runfabtests.py

Introduce Neuron memory types to test suites. Notably we omitted rdm atomic - Neuron does not currently support atomic ops so we skip those tests
Also included are cosmetic changes that I stumped upon while making the changes.

fabtests/pytest,scripts: add neuron memory types to test suites

---

contrib/intel/jenkins/Jenkinsfile
contrib/intel/jenkins/summary.py

Add dsa testing back because the node is back online
Fix a bug where shmem wasn't properly opening files due to missing underscore and improper resetting of a token check.

contrib/intel/jenkins: Fix shmem summary & add dsa testing back

---

include/ofi_hmem.h
src/hmem.c
src/hmem_neuron.c

Neuron hmem iface is missing ops function pointers, which caused segfault on trn1 hosts.
The function pointers are used in `ofi_hmem_host_register` by SHM provider etc.
This problem was not revealed in AWS CI because it does not test on trn1 hosts, thus the
Neuron code path was not activated.

include,src/hmem: Define missing neuron hmem ops function pointers

---

fabtests/pytest/common.py

Because both client and server utilize all Neuron cores, they cannot request -D neuron on the same node. Thus skip those tests.

fabtests/pytest/common.py: skip neuron to neuron tests on single node

---

prov/efa/src/efa_base_ep.c

The function efa_base_ep_construct() did not handle the case when fi_dupinfo() failed to allocate info object.
The handling of calloc() failure is not right either.
This patch addressed both issues.

prov/efa: fix the error handling of efa_base_ep_construct()

---

prov/efa/src/rdm/rxr_pkt_cmd.c

rxr_pkt_trigger_handshake() initializes a tx_entry to send a RTW packet. It did not initialize the ep field of the tx_entry, this patch fixed the issue.

prov/efa: set tx_entry->ep in rxr_pkt_trigger_handshake()

---

prov/net/src/xnet_rdm.c
prov/net/src/xnet_rdm_cm.c

Running fabtests with ASAN has revealed 2 memory leaks with RDM. When a new endpoint (active or passive) is created, the fi_info object is duplicated and can be deleted by the caller.

prov/net: Fix memory leaks with RDM

---

prov/efa/docs/efa_rdm_protocol_v4.md

recv_length field in LONGCTS_RTR header should be number of bytes that the requester(receiver) is read to receive.

prov/efa: fix rdm protocol doc typo

---

prov/efa/src/efa_prov_info.c
prov/efa/src/efa_prov_info.h
prov/efa/src/efa_user_info.c

If user specified pic bus id in hints, use it to select info.

prov/efa: compare pci bus id in hints

---

prov/efa/src/efa_hmem.c

This resolves a corner case where an instance type such as g4dn.metal has P2P support, but not RDMA read support. When calling `ibv_reg_mr()` with only `IBV_ACCESS_LOCAL_WRITE`, it will succeed - causing `efa_hmem_info[FI_HMEM_CUDA].p2p_supported_by_device` to be true; ultimately allowing `efa_mr_reg_impl()` to attempt to register CUDA memory regions.
This is potentially a temporary mitigation; it may be beneficial for performance on g4dn.metal to allow IBV MR registrations - but it's not yet clear why some `ibv_reg_mr()` calls succeed (see CUDA OMB runs) and some fail (CUDA fabtests).

prov/efa: Ask for remote read in `FI_HMEM_CUDA` init

---

include/ofi_net.h
prov/net/src/xnet.h
prov/net/src/xnet_ep.c
prov/net/src/xnet_progress.c
src/common.c
src/iouring.c

The PR covers the following changes:
- it implements the cancelation of outstanding SQEs when the EP is flushed.
- it fixes a bunch of bugs I found while testing the io_uring support.
With this PR, fabtests reports the same percentage of passed tests whether io_uring is enabled or not (command line `./runfabtests.sh net`).
There is still one test that randomly fails with io_uring, I'm not sure why:
```
$ FI_NET_IO_URING=1 fi_cq_data -e rdm -p "net"   -s 127.0.0.1
Waiting for CQ data from client
remote_cq_data: success
fi_cq_data: prov/net/src/xnet_progress.c:1490: xnet_close_progress: Assertion `slist_empty(&progress->event_list)' failed.
Aborted (core dumped)
```
It looks like the process receives the FI_SHUTDOWN event in the EQ but the application doesn't consume it.

prov/net,uring: cancel outstanding SQEs + various bugfixes 

---

prov/efa/src/rdm/rxr_ep.c
prov/efa/src/rdm/rxr_pkt_type_base.c

shm provider must make cuda calls to transfer cuda memory.
Therefore this patch disable shm usage when application require FI_HMEM capability but cuda is not available.

prov/efa: disable shm when HMEM is requrired and cuda is not allowed

---

include/ofi_util.h
prov/shm/src/smr.h
prov/shm/src/smr_comp.c
prov/shm/src/smr_cq.c
prov/shm/src/smr_ep.c
prov/util/src/util_cq.c

Moves FI_PEER support to util_cq so that any provider using the util_cq to read and write entries can leverage support to be either an owner or peer
Modifies providers using util_cq to streamline CQ functionality and isolate FI_SOURCE/signal optimizations to fewer places

prov/util,shm: add FI_PEER support to util_cq and update shm to use util FI_PEER support

---

prov/efa/src/rdm/rxr.h
prov/efa/src/rdm/rxr_atomic.c
prov/efa/src/rdm/rxr_ep.c
prov/efa/src/rdm/rxr_msg.c
prov/efa/src/rdm/rxr_op_entry.c
prov/efa/src/rdm/rxr_op_entry.h
prov/efa/src/rdm/rxr_pkt_cmd.c
prov/efa/src/rdm/rxr_pkt_type_base.c
prov/efa/src/rdm/rxr_pkt_type_data.c
prov/efa/src/rdm/rxr_pkt_type_misc.c
prov/efa/src/rdm/rxr_pkt_type_req.c
prov/efa/src/rdm/rxr_rma.c

This patch move flags that are only applied to rxr_op_entry from rxr.h to rxr_op_entry.h.
It also rename some flags and added OP/TX/RX_ENTRY to indicate their usage.

prov/efa: move op_entry flags from rxr.h to rxr_op_entry.h

---

Makefile.am
include/ofi_hmem.h
include/ofi_mem.h
include/ofi_mr.h
libfabric.vcxproj
prov/hook/dmabuf_peer_mem/src/hook_dmabuf_peer_mem.c
prov/shm/src/smr_ep.c
prov/util/src/rocr_ipc_monitor.c
prov/util/src/util_mem_monitor.c
prov/verbs/src/verbs_mr.c
src/hmem.c
src/hmem_cuda.c
src/hmem_ipc_cache.c
src/hmem_rocr.c
src/hmem_ze.c

Add the following support:
- Add ROCR IPC for use with SHM provider
- Support Asynchronous ROCR memory copy operations
- improve ROCR device performance by using inline copies instead of asynchronous copies for buffers less than 512KB

Add Support for ROCR IPC

---

man/fi_endpoint.3.md

Add a missing introduction to EFA meta protocol symbol

man/fi_endpoint: add brief FI_PROTO_EFA description

---

prov/efa/src/rdm/rxr_op_entry.c
prov/efa/src/rdm/rxr_op_entry.h
prov/efa/src/rdm/rxr_pkt_type_misc.c
prov/efa/src/rdm/rxr_pkt_type_req.c

prov/efa: remove used efa_domain parameter in rxr_op_entry_try_fill_desc

---

contrib/intel/jenkins/Jenkinsfile
contrib/intel/jenkins/tests.py

Errors in internal scripts weren't catching real failures. CI will fail now until this is merged

contrib/intel: fix OneCCL testing

---

prov/ucx/src/ucx.h
prov/ucx/src/ucx_av.c
prov/ucx/src/ucx_fabric.c

Address the two remaining review comments for the initial push:
(1) use standard macro for checking lookback devices.
(2) use ofi_dyn_arr for variable length tables used in address vector.

ucx provider code refactoring

---

prov/efa/src/rdm/rxr_op_entry.c
prov/efa/src/rdm/rxr_op_entry.h
prov/efa/src/rdm/rxr_pkt_type_misc.c
prov/efa/src/rdm/rxr_pkt_type_req.c
prov/efa/src/rdm/rxr_read.c

A previous commit db95f071ce2d5253b626e6f05751aec32565da2c introduced a few bugs. This patch fixed them.

prov/efa: fix bugs casued by "op_entry directly post read"

---

man/fi_opx.7.md

Man page fixes relevant to the OPX provider, to be pulled into 1.17.x.

Man fixes for opx provider for 1.17.x

---

contrib/intel/jenkins/Jenkinsfile

Have check_target return the target found (default main) instead of setting locally. Print out changeset for debugging purposes

contrib/intel/jenkins: Correctly set global change_target

---

prov/efa/src/rxr/rxr_ep.c

Manually apply a patch to prevent rdm_info from being freed twice. Cherry-picking the fix on main branch results in conflict, and thus we do a simpler fix instead.

[v1.17.x] prov/efa: fix double free in rxr endpoint init

---

prov/efa/src/rdm/rxr_ep.c

Defensively initialize pointers to NULL and prevent freeing unset rxr_ep

prov/efa: initialize pointers to NULL in rxr_endpoint

---

contrib/intel/jenkins/summary.py
contrib/intel/jenkins/tests.py

Make non verbose summary use ':' as a delimiter for post processing in excel
Add impi back as a valid test case for mpichtestsuite

contrib/intel/jenkins: Update summary delimiter for post processing

---

fabtests/test_configs/psm3/psm3.exclude

fi_rdm_tagged_peek and fi_cq_data tests were disabled for the CI because of race condition in psm3. 
Issue has been fixed in the latest psm3 release (11.4) and has been verified manually and by CI.
Github issue: https://github.com/ofiwg/libfabric/issues/7550

contrib/intel/jenkins: Add excluded tests back to psm3 stage

---

prov/efa/Makefile.include
prov/efa/src/efa_prov_info.c
prov/efa/src/efa_prov_info.h
prov/efa/src/efa_user_info.c
prov/efa/src/rxr/rxr_pkt_type_base.c
prov/efa/test/efa_unit_test_ep.c
prov/efa/test/efa_unit_test_mocks.c
prov/efa/test/efa_unit_test_mocks.h
prov/efa/test/efa_unit_tests.c
prov/efa/test/efa_unit_tests.h

[prov/efa: compare pci bus id in hints](https://github.com/ofiwg/libfabric/commit/6b9c85df7f008bb8ddbda8bc22e0a31520b09460)
[prov/efa: avoid unnecessary copy when sending data from shm](https://github.com/ofiwg/libfabric/commit/530d9f93a057c8f9c251a41add0539084a5e8721)
[prov/efa: unit test to verify no copy with shm for small host message](https://github.com/ofiwg/libfabric/commit/92734d0bbdca2e601d37c5a37bbda6478a76393b)

[v1.17.x] prov/efa: back port recent changes

---

man/fi_peer.3.md

The input argument should be struct fi_peer_rx_entry *entry.

man/fi_peer: Fix the input argument in fi_ops_srx_peer

---

prov/efa/src/efa_domain.c
prov/efa/src/efa_domain.h
prov/efa/src/efa_user_info.c
prov/efa/src/rdm/rxr_env.c
prov/efa/src/rdm/rxr_env.h
prov/efa/src/rdm/rxr_rma.c

Prior to this change FI_EFA_USE_DEVICE_RDMA was checked only once when the provider is initialized. Due to this different plugins/libraries setting up the environment for various applications cannot modify the value of this environment variable.
This patch provides this possibility by checking the value of FI_EFA_USE_DEVICE_RDMA once per domain.

prov/efa: Check FI_EFA_USE_DEVICE_RDMA per domain

---

prov/efa/src/rdm/efa_rdm_cq.h

Previously EFA provider supported CQ_DATA size of 8 bytes, but we must change this to 4 bytes to align with rdma-core API for RDMA_WRITE_WITH_IMM which only takes a 4-byte immediate value.

prov/efa: EFA's CQ_DATA size is now 4 bytes

---

prov/opx/configure.m4

Provider needs HFI1_CAP_TID_RDMA defined for debug output. Disable from build if not present in hfi1_user.h file.

prov/opx: Exclude opx from build if missing needed defines

---

prov/rxm/src/rxm_ep.c
prov/util/src/util_cq.c

The peer_cq is never freed, resulting in a minor memory leak.
Fixes #8534

prov/util: Free cq->peer_cq on close

---

contrib/intel/jenkins/Jenkinsfile

Add --branch option to the upstream git clone step to correctly clone the target branch
Make it impossible for check_target to return null

contrib/intel/jenkins: Bugfixes to Jenkinsfile opt-out process

---

prov/shm/src/smr_av.c

When FI_AV_USER_ID flag is set, shm should record the fi_addr passed in as the user id in the map before re-assigning it as the real shm fi_addr.

prov/shm: Fix a bug in smr_av_insert

---

prov/efa/src/efa_domain.c
prov/efa/src/efa_domain.h
prov/efa/src/efa_hmem.c
prov/efa/src/efa_mr.c
prov/efa/src/rdm/rxr_pkt_type_base.c

This patch provides EFA provider the possibility to check the value of FI_HMEM_CUDA_ENABLE_XFER per
domain.

prov/efa: Check FI_HMEM_CUDA_ENABLE_XFER per domain

---

Makefile.am
include/ofi_util.h
include/rdma/fi_ext.h
include/rdma/providers/fi_peer.h
libfabric.vcxproj
libfabric.vcxproj.filters
man/fi_peer.3.md
prov/shm/src/smr.h
prov/sm2/src/sm2.h
src/fabric.c

The peer provider APIs target provider implementations, not applications.  Move the definitions out of fi_ext.h, which is used by apps, and into include/rdma/providers/fi_peer.h.  This better indicates that the APIs are intended for providers, not applications.

core/fi_peer: Move peer provider defines into new header

---

man/fi_ucx.7.md
prov/ucx/configure.m4
prov/ucx/src/ucx.h
prov/ucx/src/ucx_ep.c
prov/ucx/src/ucx_init.c

It's common for applications to keep a pool of preposted receives that won't be all consumed. When the related worker is destroyed, UCX would give a warning message like this for each outstanding request:
mpool.c:55 UCX WARN object xxx {...} was not returned to mpool ucp_requests
Turn off request leak checking when the option is available to avoid unnecessary flooding in the output. Add a runtime option to turn on the checking when needed.

prov/ucx: Suppress UCX request leak warning by default

---

configure.ac

With the `--enable-<feature>` option, it is possible to disable the feature by passing `--enable-<feature>=no` or `--disable-<feature>`. The handling of some of such options (e.g. `--enable-cuda-dlopen`) doesn't take that into account and may incorrectly enable the feature when shouldn't.
Fix by checking the value when the option is given before enabling the feature.
Also fix a few places where a prefix is added to only one side of string comparison.
Fix #8222

configure: Fix the handling of some '--enable-<feature>' options

---

prov/efa/src/efa_mr.c
prov/efa/src/rdm/rxr_pkt_type_base.c

gdrcopy is found to provide faster memory copy for small data sizes. This change allows gdr memory pinning when gdrcopy is enabled, regardless of FI_HMEM_CUDA_ENABLE_XFER flag.

prov/efa: pin gdr buffer when gdrcopy is available

---

prov/efa/src/rdm/rxr_op_entry.c
prov/efa/src/rdm/rxr_pkt_type_req.c

The functions `rxr_pkt_proc_eager_rtw`, `rxr_pkt_handle_longcts_rtw_recv`, and `rxr_pkt_handle_longread_rtw_recv` all incorrectly added FI_WRITE to the op_entry's CQ flags.  In fact, rxr_ep_alloc_rx_entry has already initialized the flags to the correct value: `(FI_REMOTE_WRITE | FI_RMA)`.
Additionally `rxr_op_entry_handle_recv_completed` was incorrectly checking for FI_WRITE flag, when it should have checked for FI_REMOTE_WRITE.

prov/efa: Correct CQ flags to FI_REMOTE_WRITE

---

prov/efa/src/efa_av.c
prov/efa/src/rdm/efa_rdm_peer.h
prov/efa/src/rdm/rxr_env.c
prov/efa/src/rdm/rxr_env.h
prov/efa/src/rdm/rxr_ep.c
prov/efa/src/rdm/rxr_ep.h
prov/efa/src/rdm/rxr_op_entry.c
prov/efa/src/rdm/rxr_op_entry.h
prov/efa/src/rdm/rxr_pkt_entry.c
prov/efa/src/rdm/rxr_pkt_entry.h
prov/efa/src/rdm/rxr_pkt_type_misc.c
prov/efa/src/rdm/rxr_rma.c

Implement rxr_op_entry_post_remote_write, which can be used by rxr_rma_writemsg to post writes using rdma-core.
A single FI_WRITE may generate multiple RDMA writes, and completions are tracked in rxr_pkt_handle_write_completion. When the entire write is complete, rxr_pkt_handle_rma_completion is called.

prov/efa: Implement RDMA write for EFA

---

prov/efa/src/rdm/rxr_rma.c

"inline" should be before the return type. This patch fixed it.

prov/efa: fix declaration of rxr_rma_should_write_using_rdma()

---

prov/efa/src/rdm/rxr_pkt_type_misc.c

rxr_pkt_handle_rma_read_completion call rxr_tracepoint with read_entry->context as an argument, while read_entry is a null ptr at this time. This patch fixes this issue by changing read_entry->context to rx_entry, which is what it was referring to.

prov/efa: Fix a bug in rxr_pkt_handle_rma_read_completion

---

prov/efa/src/rdm/rxr_pkt_type_misc.c
prov/efa/src/rdm/rxr_rma.c

Piror to this patch, rxr_ep_record_tx_op_completed() was not called for the  write operation. 
rxr_ep_record_tx_op_completed() was not called for the  write operation. 
rxr_ep_record_tx_op_submitted() was not called for the  shm write operation. 
This patch addressed both issues.

prov/efa: record tx op submitted/completed for write

---

include/ofi_net.h
prov/tcp/src/xnet.h
prov/tcp/src/xnet_cm.c
prov/tcp/src/xnet_ep.c
prov/tcp/src/xnet_progress.c
src/iouring.c

This PR revisits the existing code for io_uring and starts porting a few CM-related operations associated to the EP.

prov/tcp,io_uring: Move connect() and CM messages to io_uring

---

include/rdma/fi_ext.h
man/fi_efa.7.md
prov/efa/src/rdm/rxr_ep.c

* Added three new options for fi_getopts in fi_ext.h: FI_OPT_EFA_EMULATED_READ FI_OPT_EFA_EMULATED_WRITE FI_OPT_EFA_EMULATED_ATOMICS
* Added documentation in fi_efa.7.md These options can be used by libfabric users to query if an EFA endpoint is using emulation or has hardware support for the Read, Write, and Atomics operations.

include/rdma: New options to fi_getopts for EFA

---

prov/efa/src/rdm/rxr_ep.c

Currently, rdma-core efa provider return IBV_WC_SEND as opcode of a read operation. This issue will be addressed in the future version of rdma-core.
This patch handle the IBV_WC_RDMA_READ opcode to prepare for the future rdma-core change.

prov/efa: handle the IBV_WC_RDMA_READ opcode.

---

prov/efa/configure.m4
prov/efa/src/efa_device.c
prov/efa/src/efa_domain.h

During configure, check efadv.h to see if rdma-core is new enough to include the RDMA write capability flag.
If the flag is available, use it to check the device for RDMA write capability during runtime.

prov/efa: Add rdma_core support for RDMA write

---

prov/tcp/src/xnet_srx.c

In xnet_match_tag_addr(), we lookup the tag queue based on the peer-> fi_addr.  However, there's no guarantee that the peer has been inserted into the AV.  This occurs during certain DAOS tests.  As a result, the tag queue is invalid, and trying to walk it can result in accessing invalid memory.
Add a check for a valid peer->fi_addr prior to checking for matches on the src queue.

prov/tcp: Fix segfault accessing invalid fi_addr

---

prov/efa/src/rdm/rxr_ep.c

During initialization of the qp_ex for efadv and ibv, we must include IBV_QP_EX_WITH_RDMA_WRITE and *_WITH_IMM flags if we intend to issue RDMA writes.
---
Sorry, this should have been in the previous PR, but was missed at the time.

prov/efa: Correct send_ops_flags for RMDA writes

---

prov/hook/dmabuf_peer_mem/src/hook_dmabuf_peer_mem.c

In older oneAPI L0 library IPC handles are not cached so that the returned dmabuf fds need to be explicitly closed to avoid running out of file descriptors.
In newer oneAPI L0 libraries IPC handles are cached so that it becomes not only unnecessary but also errorous to explicitly close the fds.
Detect the IPC handle caching status at runtime so that the dmabuf fds can be correctly handled.

[v1.17.x] prov/hook/dmabuf_peer_mem: Handle IPC handle caching in L0

---

prov/hook/dmabuf_peer_mem/src/hook_dmabuf_peer_mem.c

In older oneAPI L0 library IPC handles are not cached so that the returned dmabuf fds need to be explicitly closed to avoid running out of file descriptors.
In newer oneAPI L0 libraries IPC handles are cached so that it becomes not only unnecessary but also errorous to explicitly close the fds.
Detect the IPC handle caching status at runtime so that the dmabuf fds can be correctly handled.

[v1.16.x] prov/hook/dmabuf_peer_mem: Handle IPC handle caching in L0

---

prov/hook/dmabuf_peer_mem/src/hook_dmabuf_peer_mem.c

In older oneAPI L0 library IPC handles are not cached so that the returned dmabuf fds need to be explicitly closed to avoid running out of file descriptors.
In newer oneAPI L0 libraries IPC handles are cached so that it becomes not only unnecessary but also errorous to explicitly close the fds.
Detect the IPC handle caching status at runtime so that the dmabuf fds can be correctly handled.

[v1.15.x] prov/hook/dmabuf_peer_mem: Handle IPC handle caching in L0

---

prov/hook/dmabuf_peer_mem/src/hook_dmabuf_peer_mem.c

In older oneAPI L0 library IPC handles are not cached so that the returned dmabuf fds need to be explicitly closed to avoid running out of file descriptors.
In newer oneAPI L0 libraries IPC handles are cached so that it becomes not only unnecessary but also errorous to explicitly close the fds.
Detect the IPC handle caching status at runtime so that the dmabuf fds can be correctly handled.

prov/hook/dmabuf_peer_mem: Handle IPC handle caching in L0

---

include/ofi.h
src/fabric.c
src/var.c

Add support for reading environment variables from a config file on the system.  The config file supports a single definition per line, defined as KEY=VALUE any whitespaces (other than '\n') will be preserved.
When loading environment variables, check this file for definitions as a fallback
Runtime definitions will overwrite system definitions
This targets an initial solution for #8308

core: Add basic system-config support

---

fabtests/pytest/efa/test_mr.py

This FI_EFA_USE_DEVICE_RDMA export should be handled by the caller of the script based on platform.

fabtests/pytest/efa: Remove the env append in test_mr.py

---

include/ofi_hmem.h
prov/util/src/cuda_mem_monitor.c

Use correct calls for CUresult values, not cudaError_t calls.
Fixes #8604  -- maybe, I can't test the build for this on my system

core/cuda: Use correct debug string calls

---

include/ofi_atom.h
include/ofi_atomic_queue.h
include/unix/osd.h
include/windows/osd.h

Add atomic indirection to handle cases where an older compiler is being used which doesn't support atomic functions, or have other versions of the atomic functions. The three variants which were added are:
atomic_compare_exchange_weak()
atomic_store_explicit()
atomic_load_explicit()
These are needed for the atomic queue implementation

infra: Add atomic indirection

---

include/ofi_net.h
prov/tcp/src/xnet.h
prov/tcp/src/xnet_cm.c
prov/tcp/src/xnet_progress.c
src/iouring.c

The PR enables io_uring for the code path executed when an incoming request is accepted.

prov/tcp: accept() now supports io_uring

---

prov/tcp/src/xnet_ep.c
prov/tcp/src/xnet_progress.c

This PR fixes a few bugs I found while reviewing/testing the code related to the cancellation of outstanding io_uring requests.

prov/tcp: Fix a few bugs during cancelation of outstanding io_uring requests

---

prov/tcp/src/xnet_progress.c

"ret" must be set to the value of "res", otherwise the caller wouldn't know the reason for a failing call to connect().

prov/tcp: Fix ret not set if connect() fails with io_uring

---

prov/efa/src/efa_domain.c
prov/efa/src/efa_domain.h
prov/efa/src/efa_fabric.c
prov/efa/src/efa_prov.c
prov/efa/src/efa_shm.c
prov/efa/src/efa_shm.h
prov/efa/src/efa_user_info.c
prov/efa/src/rdm/rxr_atomic.c
prov/efa/src/rdm/rxr_ep.c
prov/efa/src/rdm/rxr_read.c
prov/efa/src/rdm/rxr_rma.c
prov/efa/test/efa_unit_test_info.c
prov/efa/test/efa_unit_tests.c
prov/efa/test/efa_unit_tests.h

Currently, shm info is initialized as a global variable `g_shm_info` once. When applications call `fi_getinfo()` multiple times, `g_shm_info` is only created by the first `fi_getinfo()` and won't be changed by subsequent `fi_getinfo()` calls.
This PR addresses this issue by making shm_info created on the fly during efa domain open, based on application info created earlier. A unit test is added to validate the change.

prov/efa: Make shm_info created on the fly during domain open 

---

fabtests/Makefile.am
fabtests/pytest/common.py
fabtests/pytest/default/test_multinode.py
fabtests/pytest/efa/test_efa_shm_addr.py
prov/efa/src/efa_av.c
prov/efa/src/efa_av.h
prov/efa/src/rdm/rxr_ep.c

This PR makes efa provider use shm provider's FI_AV_USER_ID support so the efa/shm address conversion is not needed in the cq read.
Also add efa specific fabtests item `test_efa_shm_addr` that validate the fi_addr_t returned by efa provider's `fi_cq_readfrom` is correct in the scenario where a non-shm peer is inserted first, and a shm peer is inserted later so
the efa fi_addr and shm fi_addr could differ.

prov/efa and fabtests/efa: Use shm provider's FI_AV_USER_ID support and add test 

---

fabtests/pytest/efa/efa_common.py

On Ubuntu 18.04 lsmod is at /sbin/lsmod. We should use the default PATH instead of hardcoding the path.

fabtests/pytest/efa: use lsmod on default PATH

---

fabtests/pytest/efa/efa_common.py

[v1.17.x] fabtests/pytest/efa: use lsmod on default PATH

---

include/rdma/fi_domain.h
man/fi_mr.3.md

Level zero has the concept of drivers and devices, with devices belonging to driver objects.  As a result, two devices can have the same index as long as they are from different drivers. To disambiguate what device might be referred to, extend the API to allow specifying the ze device using a ze_device_handle_t value.  (This is a pointer to a structure).
We determine if the device is given as an index or a pointer based on the range of values.

core/hmem: Allow specifying Ze devices as device_handles

---

prov/tcp/src/xnet_eq.c

ASAN detects a memory leak when running 'fi_rdm_atomic -I 5 -o all -U -p "tcp"':
Direct leak of 24 byte(s) in 1 object(s) allocated from:
0 0x7f8248757a37 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
1 0x7f8248063cf8 in fid_list_search prov/util/src/util_main.c:85
2 0x7f8248397816 in xnet_add_domain_progress prov/tcp/src/xnet_eq.c:167
3 0x7f8248383668 in xnet_ep_bind prov/tcp/src/xnet_ep.c:610
4 0x7f824828ee5b in fi_ep_bind include/rdma/fi_endpoint.h:202
5 0x7f82482911b8 in rxm_open_conn prov/rxm/src/rxm_conn.c:196
6 0x7f8248295fdd in rxm_process_connreq prov/rxm/src/rxm_conn.c:732
7 0x7f8248296e0c in rxm_handle_event prov/rxm/src/rxm_conn.c:829
8 0x7f8248297113 in rxm_conn_progress prov/rxm/src/rxm_conn.c:855
9 0x7f82482ceef9 in rxm_ep_do_progress …

prov/tcp: Fix a leak found by ASAN when EQ destroyed before domain

---

libfabric.vcxproj
prov/efa/Makefile.include
prov/efa/src/rdm/efa_rdm_srx.c
prov/efa/src/rdm/efa_rdm_srx.h
prov/efa/src/rdm/rxr_ep.c
prov/efa/src/rdm/rxr_ep.h
prov/efa/src/rdm/rxr_op_entry.h

This PR add peer_srx to rxr_ep, and initiate its fields and ops functions as stubs. This is a preliminary step that allows future incremental changes.

prov/efa: Initiate peer_srx struct and ops

---

prov/ucx/configure.m4

There was an unwanted comma that led to the follwoing error message:
`configure: line xxxx: ,: command not found`

prov/ucx: Fix a typo in the configure script

---

fabtests/pytest/efa/efa_common.py

This is a follow up bugfix to PR8628. On RHEL7 lsmod is not on the default ssh PATH. For portability, execute the command in interactive shell.
Need to backport to v1.17.x.

fabtests/pytest/efa: execute lsmod in interactive shell

---

fabtests/pytest/efa/efa_common.py

Backport https://github.com/ofiwg/libfabric/commit/54c90d50d067c4aa5802bbfb7945a393ee05d4aa to v1.17.x

[v1.17.x] fabtests/pytest/efa: execute lsmod in interactive shell

---

prov/efa/src/rdm/efa_rdm_srx.c
prov/efa/src/rdm/rxr_ep.c
prov/efa/src/rdm/rxr_msg.c

This commit implements the peer ops of the peer API and uses them internally for the EFA provider
The discard_msg and discard_tag ops are not implemented because they are not called by external applications and are not used by the EFA provider

prov/efa: Implement start_msg and start_tag in peer API

---

prov/efa/src/rdm/rxr_msg.c

It is unnecessary to call progress engine immediately after triggering a handshake. rxr_msg_generic_send does this when an error is returned.

prov/efa: remove redundant progress after triggering handshake

---

man/fi_endpoint.3.md
prov/efa/src/efa_domain.c
prov/efa/src/efa_domain.h
prov/efa/src/efa_hmem.c
prov/efa/src/efa_mr.c
prov/efa/src/efa_user_info.c
prov/efa/src/rdm/rxr_ep.c
prov/efa/src/rdm/rxr_ep.h
prov/efa/src/rdm/rxr_pkt_type_base.c
prov/rxm/src/rxm_ep.c
prov/shm/src/smr_ep.c
prov/verbs/src/verbs_ep.c

This PR implement the FI_OPT_CUDA_API_PERMITTED option for all providers that support FI_HMEM.
It also update the document of `fi_endpoint` to commit that all providers support FI_HMEM will implement this option.
This is to address: https://github.com/ofiwg/libfabric/issues/8639

man, prov/efa,shm,verbs,rxm: implement FI_OPT_CUDA_API_PERMITTED for all providers that support FI_HMEM

---

prov/tcp/src/tcpx_progress.c

I am chasing a bug where the following assertion failure triggers:
./include/ofi_mem.h:402: ofi_buf_free: Assertion `ofi_atomic_dec32(&ofi_buf_region(buf)->use_cnt) >= 0' failed.
Here is the corresponding callstack when the assertion failure happens:
0x7ffff64aca7c  pthread_kill  [/lib/x86_64-linux-gnu/libc.so.6, 0x7ffff6416000]
0x7ffff6458476  raise  [/lib/x86_64-linux-gnu/libc.so.6, 0x7ffff6416000]
0x7ffff643e7f3  abort  [/lib/x86_64-linux-gnu/libc.so.6, 0x7ffff6416000]
0x7ffff643e71b  *unknown*  [/lib/x86_64-linux-gnu/libc.so.6, 0x7ffff6416000]
0x7ffff644fe96  __assert_fail  [/lib/x86_64-linux-gnu/libc.so.6, 0x7ffff6416000]
0x7ffff74c78b3  tcpx_ep_flush_queue  [xxx.so, 0x7ffff686c000]
0x7ffff74c850b  tcpx_ep_flush_all_queues  [xxx.so, 0x7ffff686c000]
0x7ffff74c86bb  tcpx_ep_disable …

[v1.17.x]  prov/tcp: Suspicion of bug where RX entry is freed twice

---

prov/shm/src/smr.h
prov/shm/src/smr_atomic.c
prov/shm/src/smr_dsa.c
prov/shm/src/smr_ep.c
prov/shm/src/smr_progress.c
prov/util/src/rocr_mem_monitor.c

Update the SHM provider to use the ROCR HMEM asynchronous memory operations.
. Add an IPC entry freestack
. When progressing an IPC operation, check if the device is ROCR and trigger
an asynchronous operation.
. When an asynchronous operation is queued, create an IPC entry and
add it to the queue of pending operations.
. During the top level progress loop check the queue of pending asynchronous
operations and query the state of each one. Generate a complete event
for finished operations. Since completions happen outside the context
of libfabric we can't rely on the ep->region->signal flag to be set.
Always check the pending queue. This shouldn't introduce much of an
overhead if the queue is empty

prov/shm: Update SHM to use ROCR

---

prov/util/src/util_cq.c

For peer cq, fi_cq_read is not expected to access cirq and reading cqes. It should only progress the cq.

core/util_cq: fix the behavior of cq_read for FI_PEER

---

libfabric.vcxproj
prov/efa/Makefile.include
prov/efa/docs/efa_rdm_protocol_v4.md
prov/efa/src/rdm/efa_rdm_peer.c
prov/efa/src/rdm/efa_rdm_peer.h
prov/efa/src/rdm/rdm_proto_v4.h
prov/efa/src/rdm/rxr_env.c
prov/efa/src/rdm/rxr_env.h
prov/efa/src/rdm/rxr_ep.c
prov/efa/src/rdm/rxr_ep.h
prov/efa/src/rdm/rxr_pkt_entry.c
prov/efa/src/rdm/rxr_pkt_entry.h
prov/efa/src/rdm/rxr_pkt_type.h
prov/efa/src/rdm/rxr_pkt_type_misc.c
prov/efa/src/rdm/rxr_pkt_type_misc.h
prov/efa/test/efa_unit_test_common.c
prov/efa/test/efa_unit_test_ep.c
prov/efa/test/efa_unit_test_mocks.c
prov/efa/test/efa_unit_test_mocks.h
prov/efa/test/efa_unit_tests.c
prov/efa/test/efa_unit_tests.h

This change introduces a new optional handshake packet field hid(host id) enabled by the HID_HDR flag. The hid value is parsed from a host id file configured in rxr_env.
Notably, hid is optional and provided at best effort, which means:
- It is set to 0 by default.
- If the endpoint fails to parse hid, it will skip the error.
- hid is included in handshake if and only if it is non-zero.

prov/efa: exchange rxr endpoint host id information during handshake

---

prov/shm/src/smr_rma.c

Prior commit b7f25be5c7  introduced a bug that can cause the function smr_generic_rma() to return
without release ep->tx_lock.

prov/shm: fix potential deadlock in smr_generic_rma()

---

prov/efa/src/rdm/rxr_ep.c
prov/efa/src/rdm/rxr_ep.h
prov/efa/test/efa_unit_test_ep.c

In test_rxr_ep_handshake_exchange_host_id(), the mocked return of ibv_wr_read_slid() is always 0, which
is wrong, because it should return peer's ahn.
This patch fixed it.

prov/efa: fix wrong mocked return of ibv_wc_read_slid() in unit test

---

prov/efa/src/efa_user_info.c
prov/efa/test/efa_unit_test_info.c
prov/efa/test/efa_unit_tests.c
prov/efa/test/efa_unit_tests.h

Fix a bug in `efa_user_info_alter_rxr` regarding hmem support, and added a test case for it.

prov/efa: fix getinfo return code when hmem support is requested

---

fabtests/common/hmem_cuda.c
fabtests/include/hmem.h

If user selected device by using "-i" option and
selected CUDA memory, this patch call cudaSetDevice() to use that device.

fabtests: call cudaSetDevice() for selected device

---

include/rdma/fi_ext.h
libfabric.vcxproj
man/fi_efa.7.md
prov/efa/Makefile.include
prov/efa/src/efa.h
prov/efa/src/efa_device.c
prov/efa/src/efa_domain.c
prov/efa/src/efa_domain.h
prov/efa/src/efa_user_info.c
prov/efa/src/rdm/efa_rdm_peer.h
prov/efa/src/rdm/efa_rdm_util.c
prov/efa/src/rdm/efa_rdm_util.h
prov/efa/src/rdm/rxr_env.c
prov/efa/src/rdm/rxr_env.h
prov/efa/src/rdm/rxr_ep.c
prov/efa/src/rdm/rxr_ep.h
prov/efa/src/rdm/rxr_msg.c
prov/efa/src/rdm/rxr_pkt_type_base.c
prov/efa/test/efa_unit_test_common.c
prov/efa/test/efa_unit_test_ep.c
prov/efa/test/efa_unit_test_info.c
prov/efa/test/efa_unit_test_mocks.c
prov/efa/test/efa_unit_tests.c
prov/efa/test/efa_unit_tests.h

move the use_device_rdma option from the domain to the endpoint, and use fi_setopt to control it rather than an environment variable.
This change does not modify the behavior for applications that use API version <1.18.  For these API versions we query the environment value during domain creation, which is (hopefully) the same value we queried during getinfo.
For applications that use API version >= 1.18, we still allow the user to disable RDMA via the environment (FI_EFA_USE_DEVICE_RDMA=0/1).  if fi_setopt() tries to enable RDMA but user has disabled it, then fi_setopt will return `-FI_EINVAL`.  Likewise if the application tries to disable it when the environment has it disabled.
Motivation: https://github.com/ofiwg/libfabric/pull/8529

prov/efa: set use_device_rdma with fi_setopt

---

fabtests/Makefile.am
fabtests/common/shared.c
fabtests/include/shared.h
fabtests/pytest/efa/test_setopt.py
fabtests/scripts/runfabtests.sh
fabtests/unit/setopt_test.c
prov/rxm/src/rxm_conn.c
prov/tcp/src/xnet_rdm_cm.c

FI_OPT_CUDA_API_PERMITTED was introduced in 1.18 API, and all providers that claim support of FI_HMEM are required to implement this option.
This patch added a test for setting this option.

fabtests,tcp,rxm: add test for setting FI_OPT_CUDA_API_PERMITTED

---

prov/efa/test/efa_unit_test_common.c
prov/efa/test/efa_unit_test_ep.c

Fix a bug in unit test resulting in a string not ending properly with the null terminator.
Also add a null check before deleting the tempfile.

prov/efa: fix string initialization bug in unit test

---

prov/efa/test/efa_unit_test_ep.c

Currently test_rxr_ep_handshake_exchange_host_id makes early assertions
that can potentially cause leaked CQE. This prevents RDM endpiont from
closing properly(a hang). This change ensures the CQ be purged before
making assertions.
The test is also simplified to eliminate the redundant fi_recv and
associated rx buffer. Handshake happens behind the scene in the progress
engine. The application does not participate in request initiation.

prov/efa: refactor handshake test to prevent hang

---

include/rdma/fi_ext.h
man/fi_efa.7.md
prov/efa/configure.m4
prov/efa/src/dgram/efa_dgram_ep.c
prov/efa/src/efa_base_ep.c
prov/efa/src/efa_base_ep.h
prov/efa/src/efa_device.c
prov/efa/src/efa_device.h
prov/efa/src/rdm/rxr_ep.c
prov/efa/src/rdm/rxr_ep.h

This PR introduced setopt flags to enable the in order transmission of aligned 128 bytes.
For this change, this PR included a commit that moved the enablement of base_ep from `rxr_ep_ctrl` to `rxr_endpoint`, because the call to `fi_setopt` need to query ibv_qp, and ibv_qp is created during enablement of base_ep.

prov/efa: introduce setopt flags for 128 bytes in order transmission

---

prov/efa/src/rdm/rxr_ep.c

This patch added the assignment to optlen for a few flags.

prov/efa: add assignment to optlen in rxr_ep_getopt()

---

man/fi_getinfo.3.md

Current implementation of fi_getinfo() will return -FI_ENOSYS if the "version" argument of fi_getinfo() is too high to be supported. This patch added that return value to document.

doc/fi_getinfo: add FI_ENOSYS to return value

---

man/fi_getinfo.3.md

Current implementation of fi_getinfo() will return -FI_ENOSYS if the "version" argument of fi_getinfo() is too high to be supported. This patch added that return value to document.
(cherry picked from commit a923f34e9975e0b31b7896777e344baff3669963)

[v1.18.x] man/getinfo: include FI_ENOSYS in return values

---

fabtests/Makefile.am
fabtests/common/shared.c
fabtests/include/shared.h
fabtests/pytest/efa/test_setopt.py
fabtests/scripts/runfabtests.sh
fabtests/unit/setopt_test.c
prov/rxm/src/rxm_conn.c
prov/tcp/src/xnet_rdm_cm.c

back port fi_setopt test for FI_OPT_CUDA_API_PERMITTED to v1.18.x branch

[v1.18.x] fabtests, tcp, rxm: fi_setopt test for FI_OPT_CUDA_API_PERMITTED

---

prov/efa/src/rdm/rxr_ep.c

Fix compiler warning.
(cherry picked from commit dc7d0cacebdc50c66c774d764d2fd050ab1f3dee)

[v1.18.x] prov/efa: fix switch case fallthrough

---

fabtests/unit/setopt_test.c

"op" is used to store the return of getopt(), and should be "int". Current code has it as a "char", which can cause hang. This patch fixed the issue.

unit/setopt_test: fix data type of "op"

---

fabtests/Makefile.am
fabtests/pytest/sm2/conftest.py
fabtests/pytest/sm2/sm2_common.py
fabtests/pytest/sm2/test_av.py
fabtests/pytest/sm2/test_cntr.py
fabtests/pytest/sm2/test_cq.py
fabtests/pytest/sm2/test_dom.py
fabtests/pytest/sm2/test_eq.py
fabtests/pytest/sm2/test_mr.py
fabtests/pytest/sm2/test_rdm.py
fabtests/pytest/sm2/test_sighandler.py
fabtests/pytest/sm2/test_ubertest.py
fabtests/test_configs/sm2/quick.test
fabtests/test_configs/sm2/verify.test

Creates a test directory and config files for SM2 provider. Included only passing tests for SM2 with its current limited functionality.  This is the first step in putting SM2 in AWS CI.  Will expand tests as SM2 functionality increases.

fabtests: Adding tests for SM2 Provider

---

fabtests/unit/setopt_test.c

"op" is used to store the return of getopt(), and should be "int". Current code has it as a "char", which can cause hang. This patch fixed the issue.
(cherry picked from commit 8a3bf0a7c9b1f1903ed8d2268261ef8674e2df3f)

[v1.18.x] unit/setopt_test: fix data type of "op"

---

prov/opx/Makefile.include
prov/opx/include/fi_opx_tid.h
prov/opx/include/opa_udebug.h
prov/opx/include/rdma/opx/fi_opx_debug_counters.h
prov/opx/include/rdma/opx/fi_opx_domain.h
prov/opx/include/rdma/opx/fi_opx_endpoint.h
prov/opx/include/rdma/opx/fi_opx_hfi1_packet.h
prov/opx/include/rdma/opx/fi_opx_hfi1_progress.h
prov/opx/include/rdma/opx/fi_opx_hfi1_sdma.h
prov/opx/include/rdma/opx/fi_opx_hfi1_transport.h
prov/opx/include/rdma/opx/fi_opx_match.h
prov/opx/include/rdma/opx/fi_opx_rma.h
prov/opx/src/fi_opx_atomic.c
prov/opx/src/fi_opx_cm.c
prov/opx/src/fi_opx_domain.c
prov/opx/src/fi_opx_ep.c
prov/opx/src/fi_opx_fabric.c
prov/opx/src/fi_opx_hfi1.c
prov/opx/src/fi_opx_init.c
prov/opx/src/fi_opx_progress.c
prov/opx/src/fi_opx_reliability.c
prov/opx/src/fi_opx_service.c
prov/opx/src/fi_opx_sysfs.c
prov/opx/src/fi_opx_tid_domain.c
prov/opx/src/opa_proto.c

Commits for OPX provider for 1.18. Included are:
-Bug fixes
-Observability enhancements
-Expected recv fixes (note that expected recv is still disabled by default for the OPX provider)
-Improved tag matching
-Some fixes meant to address some Coverity report issues

Opx upstream for 1.18.x

---

include/ofi_util.h
prov/util/src/util_cq.c

Currently, ofi_cq_readfrom always progress the cq before reading the cq entries.
When an owner provider is sharing its cq to a peer provider, it may first progress
the peer provider cq via `fi_cq_read(peer_cq, NULL, 0)`. If a cqe is already written
after the progress, the owner provider can just return it without progressing its owner
cq again. So it is ideal to introduce a method to purely read the cq entries without
progressing the cq. This patch is intended to make that goal. Based on this patch, the
owner provider can return immediately after fi_cq_read(peer_cq, NULL, 0) is called and
ofi_cq_read_entries returns a postive integer.

core/util_cq: split the cq progress and reading entries in ofi_cq_readfrom

---

prov/efa/src/efa_base_ep.c

There has been adjustment regarding rdma-core API
ibv_query_qp_data_in_order(). This patch adjust
the code accordingly.

prov/efa: adopt to rdma-core API adjustment

---

prov/efa/src/efa_base_ep.c

check the presence of the flag using "&", instead of comparing with the flag.

prov/efa: adjust efa_base_ep_support_op_in_order_aligned_128_bytes()

---

prov/tcp/src/xnet.h
prov/tcp/src/xnet_progress.c

Allocate the epoll event array dynamically with the progress engine to reduce the stack size (2 x 8 bytes x 1024 entries). Further reduce the memory by setting max events down to 128 from 1024, since epoll implements fairness on event reporting. (This was verified using a modified version of sock_test.)

[v1.18.x] prov/tcp: Reduce stack size for epoll event array

---

prov/tcp/src/xnet.h
prov/tcp/src/xnet_progress.c

Allocate the epoll event array dynamically with the progress engine to reduce the stack size (2 x 8 bytes x 1024 entries). Further reduce the memory by setting max events down to 128 from 1024, since epoll implements fairness on event reporting. (This was verified using a modified version of sock_test.)

prov/tcp: Reduce stack size for epoll event array

---

prov/efa/src/efa_base_ep.c

check the presence of the flag using "&", instead of comparing with the flag.
(cherry picked from commit f78b5f210806f4b227d1398b09dd10fcf634803d)

[v1.18.x] prov/efa: adjust efa_base_ep_support_op_in_order_aligned_128_bytes()

---

man/fi_efa.7.md

Clarify that those flags will also support write-once semantic

man/fi_efa: add write-once guarantee for IN_ORDER_ALIGNED_128 flags

---

man/fi_efa.7.md

Clarify that those flags will also support write-once semantic

[v1.18.x] man/fi_efa: add write-once guarantee for IN_ORDER_ALIGNED_128 flags

---

include/ofi.h
include/shared/ofi_str.h
src/common.c
src/fi_tostr.c
src/log.c
src/shared/ofi_str.c

Moved functions ofi_strncatf(), ofi_nic_tostr() and other static ofi_tostr_xxx functions from common.c to ofi_str.c. The declaration of these functions are moved from ofi.h to ofi_str.h.

core/tostr: Moved ofi_strncatf() and ofi_nic_tostr() to ofi_str.c.

---

prov/shm/src/smr_progress.c
src/hmem_rocr.c

This is a collection of three smaller fixes:
remove some warnings at compilation due to const'ness of an argument, and typecasts for pointer arithmetic
replace the pthread_spin_lock functionality in the code by the corresponding ofi functions
fix in the offset calculation of the rocr ipc path
Co-authored-by: Edgar Gabriel [edgar.gabriel@amd.com](mailto:edgar.gabriel@amd.com)
Co-authored-by: Amir Shehata [shehataa@ornl.gov](mailto:shehataa@ornl.gov)

[v1.18.x] src/hmem_rocr fixes in the rocr ipc execution path

---

prov/efa/src/efa_shm.c
prov/efa/src/rdm/efa_rdm_cq.c
prov/efa/src/rdm/efa_rdm_cq.h
prov/efa/src/rdm/efa_rdm_peer.h
prov/efa/src/rdm/efa_rdm_srx.c
prov/efa/src/rdm/efa_rdm_srx.h
prov/efa/src/rdm/rxr.h
prov/efa/src/rdm/rxr_atomic.c
prov/efa/src/rdm/rxr_ep.c
prov/efa/src/rdm/rxr_ep.h
prov/efa/src/rdm/rxr_msg.c
prov/efa/src/rdm/rxr_msg.h
prov/efa/src/rdm/rxr_op_entry.c
prov/efa/src/rdm/rxr_op_entry.h
prov/efa/src/rdm/rxr_pkt_cmd.c
prov/efa/src/rdm/rxr_pkt_cmd.h
prov/efa/src/rdm/rxr_pkt_entry.c
prov/efa/src/rdm/rxr_pkt_entry.h
prov/efa/src/rdm/rxr_pkt_pool.c
prov/efa/src/rdm/rxr_pkt_type_data.c
prov/efa/src/rdm/rxr_pkt_type_misc.c
prov/efa/src/rdm/rxr_pkt_type_req.c
prov/efa/src/rdm/rxr_pkt_type_req.h
prov/efa/src/rdm/rxr_read.c
prov/efa/src/rdm/rxr_read.h
prov/efa/src/rdm/rxr_rma.c

This PR contains a series of commits that allow efa use shm as a peer provider to offload the intra-node communication.

prov/efa: Use shm as a peer provider

---

prov/tcp/src/xnet_cq.c

prov/tcp: Change default wait object from pollfd to fd (epoll)

---

src/hmem_ze.c

When seeing if an address is valid within ZE, non ZE allocated memory will still return success but will set the memory type as unknown. Check this and return false if unknown

src/hmem_ze: fix ZE is valid check

---

include/rdma/providers/fi_peer.h
man/fi_peer.3.md
prov/efa/src/rdm/efa_rdm_srx.c
prov/shm/src/smr_ep.c
prov/shm/src/smr_progress.c
prov/sm2/src/sm2_ep.c
prov/sm2/src/sm2_progress.c

Currently, get_tag does not have size as input. However,
middlewares like MPI will call fi_trecvmsg with FI_PEEK
flag in MPI_Probe() to peek if there is an incoming message,
and application will call MPI_Get_count to derive the size of
the incoming message from the output of MPI_Probe().
In this case, owner provider needs to store the incoming message
size in the unexp tagged rx_entry, so it can write it in the CQE
for FI_PEEK.

core/fi_peer, prov/efa,shm,sm2: add size as an input of get_tag op

---

src/hmem_ze.c

When seeing if an address is valid within ZE, non ZE allocated memory will still return success but will set the memory type as unknown. Check this and return false if unknown
Cherry-picked from commit bf2b88c434706196a2c73c5484b1d133c09ae3b9

[v1.18.x] src/hmem_ze: fix ZE is valid check

---

prov/util/src/util_shm.c

The CQ should set FI_ADDR_NOTAVAIL, not FI_ADDR_UNSPEC if the address has not been inserted into the AV so the default value should be ADDR_NOTAVAIL.

prov/shm: init map fi addrs to FI_ADDR_NOTAVAIL

---

contrib/intel/jenkins/Jenkinsfile

DSA node is down. No ETA getting it back up. Disabling to allow CI to pass.

contrib/intel: temporarily disable dsa testing

---

prov/efa/src/rdm/rxr_pkt_type_misc.c

The EFA rdm endpoint could receive multiple handshakes from the same peer address. This happens in av_xfer fabtest. In that case, the sender and receiver addresses are artificially removed  and re-inserted between send and recv ops. Thus the sender could receive two rx completions from seemingly the same peer.

prov/efa: remove assertion on duplicate handshake

---

prov/tcp/src/xnet.h
prov/tcp/src/xnet_progress.c
util/info.c

Reduce stack use by allocating the io_uring events with the progress structure, rather than on the stack.
note: untested (system developed on doesn't even have io_uring, so compile is questionable atm).

prov/tcp: Move io_uring cqe from the stack to progress struct

---

prov/shm/src/smr.h
prov/shm/src/smr_ep.c
prov/shm/src/smr_progress.c

The command context can run out of memory if too many incoming unexpected messages are posted. Switching to a bufpool allows shm to dynamically allocate more memory as needed to accommodate higher unexpected traffic.

prov/shm: switch cmd_ctx pool from freestack to bufpool

---

contrib/intel/jenkins/Jenkinsfile

DSA node is down. No ETA getting it back up. Disabling to allow CI to pass.

[v1.18.x] contrib/intel: temporarily disable dsa testing

---

prov/efa/src/rdm/rxr_ep.c
prov/efa/src/rdm/rxr_op_entry.c
prov/efa/src/rdm/rxr_op_entry.h
prov/efa/src/rdm/rxr_pkt_type_base.c
prov/efa/src/rdm/rxr_pkt_type_misc.c
prov/efa/src/rdm/rxr_rma.c
prov/efa/src/rdm/rxr_rma.h

This patch uses rxr_op_entry for local read.
This changed paved the way to eliminate rxr_read_entry.

prov/efa: use rxr_op_entry for local read

---

prov/efa/src/rdm/rxr_msg.c

Currently, the check for inject size is after we
posting inject to shm. This patch fixes this issue.

prov/efa: check inject size at the beginning

---

prov/efa/src/rdm/rxr_op_entry.c

the function rxr_tx_entry_prepare_local_read_pkt_entry_mr() can be called on a packet entry whose memory has already been registered. Therefore the assertion of tx_entry->rma_iov[0].key being 0 is wrong.
This patch removed it.

prov/efa: remove wrong assertion in preparing local_read_pkt_entry mr

---

include/ofi_atom.h
include/unix/osd.h

When build with --enable-atomics=no, OFI defines its own set of emulated atomics. Some functions were missing from that definition:
ofi_atomic_compare_exchange_weak
ofi_atomic_store_explicit
ofi_atomic_load_explicit
The memory order definitions need to be included in the no atomics as well. Move the ifdef to include them.
Cherry-picked from commit fad158efd99c81e69d5e29d37403ac17d6b2e0d7

[v1.18.x] include/ofi_atom: fix no atomics support

---

prov/efa/src/rdm/rxr_ep.c
prov/efa/src/rdm/rxr_op_entry.h
prov/efa/src/rdm/rxr_pkt_cmd.c
prov/efa/src/rdm/rxr_pkt_entry.h
prov/efa/src/rdm/rxr_pkt_type_misc.c

Prior to this patch pkt_entry->x_entry's type is "void *", after we eliminate rxr_read_entry, this pointer can only be pointer to  rxr_op_entry. This patch makes this explicit.

prov/efa: make pkt_entry->x_entry to be rxr_op_entry

---

include/ofi_atom.h
include/unix/osd.h

When build with --enable-atomics=no, OFI defines its own set of emulated atomics. Some functions were missing from that definition:
ofi_atomic_compare_exchange_weak
ofi_atomic_store_explicit
ofi_atomic_load_explicit
The memory order definitions need to be included in the no atomics as well. Move the ifdef to include them.

include/ofi_atom: fix no atomics support

---

fabtests/pytest/efa/test_rdm.py
fabtests/test_configs/efa/efa.exclude
prov/efa/src/rdm/rxr_ep.c
prov/efa/src/rdm/rxr_msg.c

This PR contains 3 commits to fix bugs in the FI_PEEK related (FI_CLAIM, FI_DISCARD) code path.
This PR should be tested with a modified `rdm_tagged_peek` fabtest, which will be part of a separate PR to fabtests/functional (preparing now)

prov/efa: several bug fixes to FI_PEEK path

---

fabtests/common/shared.c

When -k is passed to fabtest, ft_exchange_keys sends a message which has a length < ft_tx_prefix_size.  This change corrects the issue.

fabtests: correct ft_exchange_keys in prefix-mode

---

.appveyor.yml
libfabric.vcxproj
libfabric.vcxproj.filters
prov/verbs/Makefile.include
prov/verbs/include/fi_verbs.h
prov/verbs/include/ofi_verbs_compat.h
prov/verbs/include/windows/verbs_nd.h
prov/verbs/src/fi_verbs.c
prov/verbs/src/verbs_cm.c
prov/verbs/src/verbs_cm_xrc.c
prov/verbs/src/verbs_cq.c
prov/verbs/src/verbs_dgram_av.c
prov/verbs/src/verbs_dgram_ep_msg.c
prov/verbs/src/verbs_domain.c
prov/verbs/src/verbs_domain_xrc.c
prov/verbs/src/verbs_ep.c
prov/verbs/src/verbs_eq.c
prov/verbs/src/verbs_info.c
prov/verbs/src/verbs_mr.c
prov/verbs/src/verbs_msg.c
prov/verbs/src/verbs_ofi.h
prov/verbs/src/verbs_rma.c

Renames to a couple of verbs header files, which resulted in updating the windows build.  Changed CI to only build with VS 2019 tools v1.42.

prov/verbs + appveyor updates

---

prov/tcp/Makefile.include

The DL name doesn't technically matter, but it is confusing for users wanting a DL build.

[v1.18.x] prov/tcp: Rename DL package from libnet to libtcp

---

prov/tcp/Makefile.include

The DL name doesn't technically matter, but it is confusing for users wanting a DL build.

prov/tcp: Rename DL package from libnet to libtcp

---

include/ofi_hmem.h
prov/efa/src/efa_user_info.c
src/hmem_cuda.c

This PR:
- Implements logic to check the P2P capabilities of the detected CUDA devices, and conditionally enable CUDA IPC availability
- If any device cannot access some other device, consider peer access to be unsupported on the host
- "peer access" in this context refers to the peer-to-peer access capabilities between CUDA devices on the same node
- If peer access is unsupported, prevent CUDA IPC usage
- This mitigates an issue where  `cudaIpcOpenMemHandle()` can fail on hosts with multiple CUDA devices without P2P access - e.g. Amazon EC2 instance types g4dn.12xlarge or g5.48xlarge
- This logic is admittedly not perfect, but is an improvement over simply checking for `cudaMemcpy()` availability
- This change still allows CUDA IPC usage when the host has a single device, regardless of …

src/hmem_cuda: Restrict CUDA IPC based on peer accessibility of devices + refactor

---

libfabric.vcxproj
prov/efa/Makefile.include
prov/efa/docs/pkt-processing.md
prov/efa/src/efa_tp.h
prov/efa/src/efa_tp_def.h
prov/efa/src/rdm/efa_rdm_ope.c
prov/efa/src/rdm/efa_rdm_ope.h
prov/efa/src/rdm/efa_rdm_peer.c
prov/efa/src/rdm/efa_rdm_srx.c
prov/efa/src/rdm/rxr.h
prov/efa/src/rdm/rxr_atomic.c
prov/efa/src/rdm/rxr_ep.c
prov/efa/src/rdm/rxr_ep.h
prov/efa/src/rdm/rxr_msg.c
prov/efa/src/rdm/rxr_msg.h
prov/efa/src/rdm/rxr_pkt_cmd.c
prov/efa/src/rdm/rxr_pkt_cmd.h
prov/efa/src/rdm/rxr_pkt_entry.c
prov/efa/src/rdm/rxr_pkt_entry.h
prov/efa/src/rdm/rxr_pkt_type.h
prov/efa/src/rdm/rxr_pkt_type_base.c
prov/efa/src/rdm/rxr_pkt_type_base.h
prov/efa/src/rdm/rxr_pkt_type_data.c
prov/efa/src/rdm/rxr_pkt_type_misc.c
prov/efa/src/rdm/rxr_pkt_type_req.c
prov/efa/src/rdm/rxr_pkt_type_req.h
prov/efa/src/rdm/rxr_rma.c
prov/efa/src/rdm/rxr_rma.h

First step to retire the legacy term "rxr"

prov/efa: rename "rxr_op_entry" to "efa_rdm_ope"

---

prov/efa/test/efa_unit_test_ep.c

Otherwise unittests can't compile.

prov/efa: skip() tests that require HAVE_EFADV_CQ_EX

---

contrib/intel/jenkins/Jenkinsfile

Adding the option for some stages to use a mlx node instead of a cvl one to reduce runtime of the ci when multiple PRs get opened.

contrib/intel/jenkins: Add mlx selection to reduce cvl bottlenecks

---

.appveyor.yml

The EFA config is the same as the normal debug/release configs. It's not actually EFA related, since the standard builds will also build the EFA provider.  (Actual testing of the EFA provider must be done on AWS).
This reduces CI runtime by half on windows.

windows/appveyor: Remove 'efa' config

---

fabtests/pytest/efa/test_rdm.py
include/ofi_hmem.h
man/fabric.7.md
src/hmem_cuda.c

This removes the initialization logic related to `FI_HMEM_CUDA_ENABLE_XFER` for the `FI_HMEM` CUDA interface in favor of the endpoint option `FI_OPT_CUDA_API_PERMITTED`.
This also removes some facilities which are no longer needed, such as the `cuda_xfer_setting` enum and the dummy `cuda_disabled_cudaMemCpy()` function.
The environment variable itself doesn't seem to have been explicitly defined in any of the section 7 man pages, so no explicit deprecation notices or warning messages were added.

core/hmem: Deprecate `FI_HMEM_CUDA_ENABLE_XFER`

---

prov/efa/src/rdm/efa_rdm_ope.c
prov/efa/src/rdm/rxr_atomic.c
prov/efa/src/rdm/rxr_ep.c
prov/efa/src/rdm/rxr_ep.h
prov/efa/src/rdm/rxr_msg.c
prov/efa/src/rdm/rxr_rma.c

rxr_rm_cq_check() check whether util_cq is overflow, and set the RXR_RM_TX/RX_CQ_FULL flag.
If the flags are full, fi_send/read/write/atomic will return -FI_EAGAIN.
The code as is does not work, because when -FI_EAGAIN is returned, progress engine is not called so if the RXR_RM_TX/RX_CQ_FULL flag is ever set, an application will hang.
Meanwhile, the check itself is not necesary because util_cq can handle the situation that CQ is full
by writing overflow CQ entry.
Therefore, this patch remove the code from critical code path.

prov/efa: remove rxr_rm_tx/rx_cq_check()

---

prov/util/src/util_mr_map.c

Store hmem_data in ofi_mr_map such that it can be retrieved later

prov/util: store hmem_data in ofi_mr_map

---

include/ofi_mem.h

Correctly initialize fs->free in smr_freestack_init(). 
Add new macro smr_freestack_isfull() to determine if freestack is full.
This is required for SM2 b/c it re-uses the SHM file, so we require that we initialize to 0 every time.

include/ofi_mem: smr_freestack_init enhancements

---

include/ofi.h

Introduce two new helper functions:
- ofi_is_size_multiple: check whether a size is a multiple
of given integer.
- ofi_is_addr_aligned: check whether an address is aligned
to given alignment.

core/ofi.h: Add helper functions to check alignment

---

include/ofi_hmem.h
src/hmem_cuda_gdrcopy.c

Introduce equivalent utilities to ofi_copy_from/to_hmem_iov

core/hmem: introduce gdrcopy from/to iov functions

---

prov/efa/src/rdm/rxr.h
prov/efa/src/rdm/rxr_ep.c

RXR_TX_MAX_QUEUE_SIZE is not used any more, so this patch removed it.
RXR_RX_MAX_QUEUE_SIZE is used to as max_cnt of ofi_bufpool_create(). Its value was set to UIN32_MAX, which is same as no limit. Therefore this patch used 0 for max_cnt, which has the same effect and removed RXR_RX_MAX_QUEUE_SIZE.

prov/efa: remove RXR_RX_MAX_QUEUE_SIZE and RXR_TX_MAX_QUEUE_SIZE

---

.appveyor.yml
fabtests/scripts/runfabtests.cmd

The tcp provider is actively supported.  Call the tcp provider. Update the runfabtests.cmd script to invoke only tcp supported tests.  (The cmd script does not process the exclude file.)

ci/appveyor: Switch CI from sockets to tcp provider

---

include/ofi_mr.h
prov/efa/src/efa_mr.c
prov/opx/include/fi_opx_tid_cache.h
prov/shm/src/smr_progress.c
prov/util/src/util_mr_cache.c
prov/verbs/src/verbs_mr.c
src/hmem_ipc_cache.c
src/hmem_rocr.c

Set the response status to SMR_STATUS_BUSY after launching an async copy operation. Set the response status to SMR_STATUS_SUCCESS after the async operation completes.
This will prevent the tx complete on the transmit side until the data from the sending buffer is no longer in use.
This avoids a scenario where the application can overwrite the buffer before it has been copied over, causing the receiving side to get unexpected data.

prov/shm: Fix ROCR data coherency

---

prov/verbs/src/verbs_cq.c
prov/verbs/src/verbs_domain.c
prov/verbs/src/verbs_ep.c
prov/verbs/src/verbs_ofi.h

To ensure that the ep state is consistent, we need to use the same lock when posting sends, receives, handling cm events, and handling async events.  Failures in any of those cases can result in the ep being transitioned into an error state, with the underlying qp being destroyed.
This also reduces the number of locks that we need to acquire to perform a data transfer and will simplify the code flow.  The changes are based on work done with the tcp provider.  One result of the change is that the provider is optimized around FI_THREAD_DOMAIN support, which ultimately ends up being the best option.
This replaces the rx and tx cq locks, which are used in racy ways, with a single progress lock for proper serialization.

prov/verbs: Use progress lock to serialize progress functions

---

prov/shm/src/smr.h
prov/shm/src/smr_ep.c
prov/shm/src/smr_msg.c
prov/shm/src/smr_rma.c

Pass through hmem iface to proto selection logic.

prov/shm: add iface parameter to smr_select_proto

---

prov/efa/test/efa_unit_test_ep.c

This patch fixes a compiler warning

prov/efa: fix an uninitialized variable in unit test

---

include/ofi_net.h
prov/tcp/src/xnet.h
prov/tcp/src/xnet_cm.c
prov/tcp/src/xnet_ep.c
prov/tcp/src/xnet_pep.c
prov/tcp/src/xnet_progress.c
src/iouring.c

This PR is hopefully the last set of major io_uring changes for the TCP provider.
It moves all the poll/epoll operations to io_uring, which allows for progressing outstanding io_uring operations without the extra overhead of epoll()/poll().
As a side-effect it also fixes the issue #6745, which was the real trigger for the entire io_uring work. The circle is now complete :)

prov/tcp: Complete the io_uring implementation (poll_add + polling without poll/epoll overhead)

---

prov/efa/src/efa_base_ep.c

The first argument of this call should be base_ep->qp->ibv_qp.
(cherry picked from commit 0a75f5ec59e57803fa7c7020ce33292d5db7f376)

[v1.18.x] prov/efa: fix a bug when calling ibv_query_qp_data_in_order

---

prov/shm/src/smr.h
prov/shm/src/smr_ep.c
prov/shm/src/smr_msg.c
prov/shm/src/smr_rma.c

Pass through hmem iface to proto selection logic.
This change re-enables CMA for read ops.
(cherry picked from commit 6b4ddb22f7c06a12a28903cb5370da6c1c727545)

[v1.18.x] prov/shm: add iface parameter to smr_select_proto

---

include/ofi_hook.h
prov/hook/src/hook_domain.c
prov/rxm/src/rxm_domain.c
prov/verbs/src/verbs_domain.c
prov/verbs/src/verbs_ep.c

ofi_ops_flow_ctrl defines callbacks for use between rxm and verbs.  Those callbacks include u64 parameters for credit values.  However, the callers use size_t instead.  This results in build warnings.
Fixes #7860

prov/hook,verbs,rxm: Fix credit size parameter for flow ctrl

---

prov/efa/src/efa_hmem.c
prov/efa/src/efa_hmem.h
prov/efa/src/efa_mr.c
prov/efa/src/efa_mr.h
prov/efa/src/rdm/rxr_pkt_type_base.c
prov/efa/src/rdm/rxr_pkt_type_req.c
src/hmem_cuda.c

With the introduction of hmem_data MR field, the gdrcopy handle should be
stored along side device id, and gdrcopy should be requested explicitly
by the caller.
This patch:
1. replaces calls to ofi_copy_from/to_hmem* functions with
ofi_gdrcopy_from/to_cuda* equivalent when a gdrcopy handle is present.
1. removes gdrcopy from cuda hmem copy path

hmem,efa: remove gdrcopy from cuda hmem copy path and make gdrcopy calls explicit

---

fabtests/functional/rdm_tagged_peek.c
fabtests/test_configs/sockets/sockets.exclude

It was possible for the client to complete the finalize send before the server gets the last 0xabc completion, causing a tag mismatch when processing the incorrect receive.
This removes the extra synchronization sends and adds an OOB sync to make sure all of the test sends have finished before quitting the test.

fabtests/rdm_tagged_peek: fix race condition synchronization

---

include/ofi.h
prov/efa/src/rdm/rxr.h
prov/efa/src/rdm/rxr_ep.c
prov/efa/src/rdm/rxr_op_entry.c
prov/efa/src/rdm/rxr_pkt_entry.c
prov/efa/src/rdm/rxr_pkt_entry.h
prov/efa/src/rdm/rxr_pkt_pool.c
prov/efa/src/rdm/rxr_pkt_pool.h
prov/efa/src/rdm/rxr_pkt_type_base.c
prov/efa/src/rdm/rxr_pkt_type_req.c
prov/efa/src/rdm/rxr_pkt_type_req.h
prov/efa/src/rdm/rxr_read.c

This PR backports https://github.com/ofiwg/libfabric/pull/8841 to v1.18.x. It also backports this core change https://github.com/ofiwg/libfabric/pull/8829 as a dependency.

[v1.18.x] core, prov/efa: backport fixes for in-order aligned send/recv support

---

fabtests/benchmarks/benchmark_shared.c
fabtests/benchmarks/rma_bw.c
fabtests/common/shared.c
fabtests/functional/cq_data.c
fabtests/functional/multi_mr.c
fabtests/include/shared.h
fabtests/prov/efa/src/rdm_rnr_queue_resend.c

A series of commits to enable `-o write` and `-o read` to perform data validation.
There is a notable performance impact when validation is enabled.
Addresses https://github.com/ofiwg/libfabric/issues/8784

Enable data integrity checks for fi_rma_bw

---

prov/verbs/src/verbs_cq.c
prov/verbs/src/verbs_ep.c
prov/verbs/src/verbs_ofi.h

Verbs QP can transition to error state for number of reasons such as retransmission time out or protection error, rendering RXM connection unusable until QP is back in RTS state.  Since not all RDMA adapters can transition a QP from error state back to RTS, the solution is to destroy the QP and create a new one on subsequent use.
On a completion with error status, check current QP state (expensive) against error state. Write a FI_SHUTDOWN event to event queue for RXM to process and close the connection.  When a new request to use the connection, a new QP will be created.

prov/verbs: Recover RXM connection from verbs QP in error state

---

prov/efa/src/efa_mr.c
prov/opx/include/fi_opx_tid_cache.h
prov/util/src/util_mr_cache.c
prov/verbs/src/verbs_mr.c
src/hmem_ipc_cache.c

In the ofi_mr_rbt_overlap() function an iovec pointer is passed in as the key. However, it's then passed to util_mr_find_overlap() and assigned to an fi_mr_info pointer. This assumes that only the iovec pointer is accessed. With the addition of the peer_id check that is no longer true.
To avoid this situation allocate an fi_mr_info block on the stack, initialize the block to 0, copy in the iovec info, and pass it to the call to ofi_rbmap_search()

mr/cache: Fix fi_mr_info initialization

---

prov/efa/configure.m4

configure.m4 restored CPPFLAGS before it finished testing various feature support in rdma-core.  This meant feature testing occurred with system default includes rather than the user-specified include paths, resulting in incorrect configure results.

prov/efa: Correct CPPFLAGS during configure

---

prov/efa/src/efa_av.c
prov/efa/src/efa_domain.c
prov/efa/src/efa_shm.c
prov/efa/src/rdm/efa_rdm_ep_fiops.c
prov/efa/src/rdm/rxr_env.c
prov/efa/src/rdm/rxr_env.h

Implement FI_EFA_USE_SM2 environment variable to switch between SHM and SM2.
This cannot merge until https://github.com/ofiwg/libfabric/pull/8808 b/c SM2 in main doesn't implement peer provider.
@sunkuamzn is on vacation, so this updates his changes here: https://github.com/ofiwg/libfabric/pull/8791

prov/efa: Enable SM2 provider as peer provider

---

prov/sm2/src/sm2.h
prov/sm2/src/sm2_av.c
prov/sm2/src/sm2_coordination.c
prov/sm2/src/sm2_coordination.h
prov/sm2/src/sm2_ep.c
prov/sm2/src/sm2_init.c
prov/sm2/src/sm2_util.c

Remove `#define SM2_NAME_MAX 256` and use FI_NAME_MAX for names.  SM2 doesn't care how long names are... and they should be less than FI_NAME_MAX.

prov/sm2: Use FI_NAME_MAX for names

---

include/ofi_epoll.h
prov/tcp/src/xnet_cq.c
prov/tcp/src/xnet_eq.c
src/common.c

We can't get an epoll fd if we don't have real support for epoll.  Update the epoll abstraction and tcp provider to handle the emulated epoll case.

prov/tcp: Handle emulated epoll support

---

prov/efa/configure.m4

configure.m4 restored CPPFLAGS before it finished testing various feature support in rdma-core.  This meant feature testing occurred with system default includes rather than the user-specified include paths, resulting in incorrect configure results.
Signed-off-by: Luke Robison <lrbison@amazon.com>
(cherry picked from commit 302bc43d1cb4c3a8a19115a770232deca77e8735)

[v1.18.x] prov/efa: Correct CPPFLAGS during configure

---

prov/shm/src/smr.h
prov/shm/src/smr_ep.c
prov/shm/src/smr_init.c
prov/shm/src/smr_msg.c
prov/shm/src/smr_rma.c

This patch introduces the no-op logic to switch data transfer protocol based on the availability of gdrcopy, and data size.
For small data sizes, gdrcopy offers better performance than cudaMemcpy. Based on experiments, we have selected 3kb as the threshold.
Note that, gdrcopy is claimed to offer asymmetric H2D/D2H performance, and for larger messages it could be slower than cudaMemcpy. However, here we make a simplification based on our experiments, and use only one threshold for both H2D/D2H copies.

prov/shm: no-op logic to toggle data transfer protocol for gdrcopy

---

prov/verbs/include/fi_verbs.h
prov/verbs/src/verbs_cq.c
prov/verbs/src/verbs_ep.c

Verbs QP can transition to error state for number of reasons such as retransmission time out or protection error, rendering RXM connection unusable until QP is back in RTS state.  Since not all RDMA adapters can transition a QP from error state back to RTS, the solution is to destroy the QP and create a new one on subsequent use.
On a completion with error status, check current QP state (expensive) against error state. Write a FI_SHUTDOWN event to event queue for RXM to process and close the connection.  When a new request to use the connection, a new QP will be created.

[v1.18.x] prov/verbs: Recover RXM connection from verbs QP in error state

---

prov/verbs/include/fi_verbs.h
prov/verbs/src/verbs_cq.c
prov/verbs/src/verbs_ep.c

Verbs QP can transition to error state for number of reasons such as retransmission time out or protection error, rendering RXM connection unusable until QP is back in RTS state.  Since not all RDMA adapters can transition a QP from error state back to RTS, the solution is to destroy the QP and create a new one on subsequent use.
On a completion with error status, check current QP state (expensive) against error state. Write a FI_SHUTDOWN event to event queue for RXM to process and close the connection.  When a new request to use the connection, a new QP will be created.

[v1.17.x] prov/verbs: Recover RXM connection from verbs QP in error state

---

fabtests/pytest/sm2/conftest.py
prov/sm2/src/sm2.h
prov/sm2/src/sm2_attr.c
prov/sm2/src/sm2_ep.c
prov/sm2/src/sm2_msg.c
prov/sm2/src/sm2_progress.c

EFA is not picking up SM2 b/c it does not support FI_HMEM.  OMPI attempts to create a libfabric provider with HMEM support, and if it fails, it tries to create one without HMEM support.  EFA is choosing to not hard-fail if SHM provider cannot be picked up, so when we specify SM2 for EFA, we run without SHM.
This patch adds support for HMEM, and allows EFA to pick up SM2.

prov/sm2: Add HMEM Support to SM2 Inject Protocol

---

include/ofi_hook.h
prov/hook/src/hook_domain.c
prov/rxm/src/rxm_domain.c
prov/verbs/src/verbs_domain.c
prov/verbs/src/verbs_ep.c

ofi_ops_flow_ctrl defines callbacks for use between rxm and verbs.  Those callbacks include u64 parameters for credit values.  However, the callers use size_t instead.  This results in build warnings.

[v1.17.x] prov/hook,verbs,rxm: Fix credit size parameter for flow ctrl

---

include/ofi_hook.h
prov/hook/src/hook_domain.c
prov/rxm/src/rxm_domain.c
prov/verbs/src/verbs_domain.c
prov/verbs/src/verbs_ep.c

ofi_ops_flow_ctrl defines callbacks for use between rxm and verbs.  Those callbacks include u64 parameters for credit values.  However, the callers use size_t instead.  This results in build warnings.

[v1.18.x] prov/hook,verbs,rxm: Fix credit size parameter for flow ctrl

---

fabtests/pytest/efa/efa_common.py
fabtests/pytest/efa/test_rma_bw.py

With newly introduced data verification to rma_bw, the test
can take new longer than 360 seconds (current default) to finish.
This patch increased the default timeout for rma_bw test to
540 seconds

fabtests/pytest/efa: increase default timeout for rma_bw to 540 seconds

---

prov/shm/src/smr_msg.c
prov/shm/src/smr_rma.c
src/hmem.c

From v1.19, OFI_HMEM_DATA_GDRCOPY_HANDLE flag will signal the presence of gdrcopy handle in ofi_mr.hmem_data. SHM provider can take advantage of gdrcopy to achieve lower memcpy latencies from/to cuda devices.
This patch introduces the logic to select gdrcopy on hmem copy paths, with the exception of cuda IPC which is not supported by gdrcopy.
For OMB single-node cuda->cuda latency we are seeing improvement(via EFA owner provider, which is responsible for gdr pinning).
|  pt2pt/osu_latency  |        |       |
|---------------------|--------|-------|
|         Size        | Before | After |
|                   0 |   0.95 |  0.93 |
|                   1 |  15.41 |  2.78 |
|                   2 |  15.18 |  4.36 |
|                   4 |  15.04 |  4.45 |
|                   8 |  15.11 |  4.38 …

prov/shm: introduce gdrcopy awareness to hmem copy

---

fabtests/pytest/shm/conftest.py
fabtests/pytest/sm2/conftest.py

intra node communication involving neuron iface won't work for shm and sm2 because the neuron to host memcpy is currently not supported in libfabric. This patch skips neuron for shm and sm2.

fabtests/pytests: skip neuron memory type for shm and sm2

---

prov/efa/src/efa_shm.c

Do not set efa_env.enable_shm_transfer=0, when we are not able to initialize SHM b/c of its capabilities.  This is b/c efa_env is a global variable. When using OMPI, SM2 fails to be launched for the BTL, which will make the next EP instance of EFA fail for MTL as well.
I verified this doesn't mess up other places where efa_env.enable_shm_transfer is used.  The only other questionable place is in efa_prov_info, where we resize the EFA inject size to the SHM inject size before we are sure that we will be able to use a SHM offload.

prov/efa: Bugfix for initializing SHM offload

---

fabtests/common/shared.c

In addition to the range feature (r:start,step,stop) the -S option now supports an explicit list of message sizes (l:1,1,2,3,5,8,13) of any length.

fabtests: enable a list of arbitrary message sizes

---

include/rdma/fabric.h

Update it to 19 to accomodate some recent changes in public headers, like https://github.com/ofiwg/libfabric/commit/49d1a767c882242b5531c3f2b1318e16310fede0

core: Update FI_MINOR_VERSION

---

prov/efa/src/efa_mr.c
prov/efa/src/efa_shm.c

This PR contains 2 commits to fix the procedure that efa pass gdrcopy handle to shm.
1. Use shm with 1.19 API, since hmem_data is introduced for libfabric >= 1.19
2. Remove the version check in efa_mr.c, since efa is using hmem_data internally so it should not care what api version that application is using

prov/efa: fix the gdrcopy_handle procedure

---

prov/efa/configure.m4

Address some conflicting styles and inconsistent macro usage in
configure.m4.
This commit doesn't have impactful changes for efa configuration.

prov/efa: cleanup configure.m4

---

include/ofi_mem.h

Switching freestack alignment to be at 4096 page boundaries has a latency benefit for both SHM/SM2.
For SHM: .33us -> .32us
For SM2: .2us -> .19us

include/ofi_mem.h: Fix Freestack Alignment

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_tagged.c

rxm_cq_owner_writeerr() expects the err_entry has a valid op_context pointing to ‘struct rxm_coll_buf’
Updated to revert peer CQ support

prov/rxm: revert util peer CQ support

---

prov/rxm/src/rxm.h
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_tagged.c

This reverts commit 93c1a52d2d6b11c82a78035265c00ed3366cbd07.
rxm peer CQ support is only used for peer collectives which have issues with the util peer CQ functions

[v.18.x] prov/rxm: revert rxm util peer CQ support

---

configure.ac

The TCP provider requires liburing >= 2.1 because it depends on the multishot feature for poll.
Enable io_uring support only if io_uring_prep_poll_multishot() and IORING_CQE_F_MORE symbols are both declared.
Fixes #8883

configure.ac: Add checks for liburing >= 2.1

---

prov/tcp/src/xnet.h
prov/tcp/src/xnet_init.c
prov/tcp/src/xnet_progress.c

this change allows for larger buffers on the receive side without forcing larger copies on the send side

prov/tcp: separate the max inject and recv buf size

---

prov/efa/src/rdm/efa_rdm_msg.c

efa_rdm_msg_trecvmsg uses a goto which just
trivially returns ret. This patch removes
this goto and make the function do returns
directly.

prov/efa: Remove unnecessary goto.

---

prov/shm/src/smr_av.c

If the user requests an event to be written to the EQ, we can assume the EQ is not NULL

prov/shm: fix coverity warning

---

prov/shm/src/smr_ep.c
prov/shm/src/smr_progress.c

This patch consists of 2 changes:
1. Do not use inline/inject for read operations. The previous gdrcopy optimization mistakenly activated this path.
2. Explicitly assert inject protocol and read op are mutually exclusive.
We need to devise another approach to optimize cuda read operation other than the current inline/inject proto.
Currently evaluating the change.

prov/shm: fix cuda rma path

---

prov/verbs/include/fi_verbs.h

The implementation uses a uint64_t argument, not size_t.

[1.18.x] prov/verbs: Fix vrb_add_credits signature

---

prov/verbs/src/verbs_ofi.h

The implementation uses a uint64_t argument, not size_t.

prov/verbs: Fix vrb_add_credits signature

---

prov/sm2/src/sm2.h
prov/sm2/src/sm2_ep.c

This removes the implicit cast from int to ssize_t in the critical sm2 path saving an instruction.

prov/sm2: Switch sm2_verify_peer to return ssize_t

---

fabtests/pytest/efa/test_unexpected_msg.py

Currently, efa provider has a bug that cannot handle messages from unknown peers on single node, which makes efa will fail the extended unexpected msg test in https://github.com/ofiwg/libfabric/pull/8914. This bug will be fixed as part of the util SRX work. Temporarily skip this test before the util SRX work is done.

fabtests/efa: Temporarily skip unexpected_msg test on single node

---

prov/tcp/src/xnet.h
prov/tcp/src/xnet_cq.c
prov/tcp/src/xnet_init.c
prov/tcp/src/xnet_progress.c
prov/tcp/src/xnet_srx.c

If we receive a message that's larger than the transfer pool buffer size that's been allocated, dynamically allocate the bounce buffer.  This allows us to queue larger messages in order to make progress with some MPI applications.
@ooststep - This patch should handle saving messages of any size at the receiver.  I tested this by shrinking the inject size to 4 bytes and buffer size to 32 bytes.  That at least allowed fabtests to check this flow.  The changes weren't quite a simple as setting the XNET_FREE_BUF ctrl_flag, but aren't that invasive.  We still have the max_saved limit, but I haven't added any other limits or optimizations.  We'll likely want both prior to merging.
I haven't decided on what limits we'll want, but was at least considering these options (with probably better …

prov/tcp: Dynamically allocate large saved Rx buffers

---

prov/efa/src/rdm/efa_rdm_msg.c
prov/efa/src/rdm/efa_rdm_msg.h
prov/efa/src/rdm/rxr_pkt_type_req.c

efa_rdm_msg_alloc_unexp_rxe_for_msgrtm and efa_rdm_msg_alloc_unexp_rxe_for_tagrtm are mostly the same. This patch merges these two functions into one to remove code duplication.

prov/efa: merge two functions into one.

---

prov/efa/src/rdm/efa_rdm_ep_progress.c

This patch would explicitly allocate memory for ep->map_entry_pool during the 1st call to progress engine.
This prevents that different progress allocate memory at different time and cause delay.

prov/efa: allocate memory for map_entry_pool during 1st call to progress

---

prov/tcp/src/xnet.h
prov/tcp/src/xnet_progress.c
prov/tcp/src/xnet_srx.c

unexpected msg test: Test for handling of multiple, large unexpected messages
rdm_tagged_peek: Add test for handling of truncated messages
MPICH testsuite requires that MPI handle processing multiple messages out of order, where messages may be larger than any expected 'eager' message size.  Set the unexpected fabtest to use 64k transfers, with a window size of 16.
The testsuite also requires that MPI handle receiving a message into a buffer that's too small without breaking communication between peers.  Add this testing to rdm_tagged_peek test, since it has the infrastructure to handle it.

prov/tcp: Progress all ep's on unexp_msg_list when posting recv

---

fabtests/functional/recv_cancel.c

In recv_cancel_host(), the cancel_error_entry should be memset as 0, because fi_cq_readerr uses err_data and err_data_size from it as input. Not initialized error entry will cause unexpected values to be used.

fabtests/recv_cancel: initialize error entry

---

prov/efa/src/efa_prov.c

Efa shouldn't call smr_* functions inside the provider. It also cause warning when HAVE_EFA_DL=1.

prov/efa: Remove smr_cleanup call in efa_prov.c

---

Makefile.am
include/ofi_mb.h
prov/shm/configure.m4
prov/shm/src/smr_ep.c

This patch added an write memory barrier to function
smr_copy_to_sar() and smr_copy_from_sar before updating
resp->status.
This is because resp->status is used by other functions
as indicator for completion of copy. Without the memory barrier,
the copy might not complete when resp-status is updated, which
will lead to data corruption.

prov/shm: add memory barrier before update resp->status for SAR

---

prov/sm2/src/sm2.h
prov/sm2/src/sm2_ep.c
prov/sm2/src/sm2_progress.c

Remove a legacy SHM construct, xfer_ctx_pool. For the unexpected path, SHM needs to copy the message out of the circular buffer and into a temporary context until a receive is posted.  SM2 doesn't need to do this behavior.  SM2 pops the message from the fifo queue, and then can hold onto the peer's xfer_entry until the receiving endpoint posts a buffer that matches it. This change reduces the amount of code on SM2's critical path, and speeds it up a little bit.

prov/sm2: Get rid of xfer_ctx_pool in unexpected recv path

---

.github/workflows/coverity.yml

Try to enable SM2 for Coverity (https://github.com/ofiwg/libfabric/issues/8967)
I expect more work is needed as well.

.github/workflows: Explicitly enable sm2 for Coverity

---

prov/shm/configure.m4

This patch added the missing assignment of atomics_happy when c11 atomics is not available.

prov/shm: fix bug in configure.m4 in atomics_happy assignment happy

---

prov/tcp/src/xnet_progress.c

Fix handling of the case where the user posts a buffer that's too small to receive a message while the message is being actively received into a saved buffer.
xnet_recv_saved() handles the case where the user posts a receive buffer for a message that's currently being saved into a provider buffer.  This is for unexpected message handling where the receive was posted before we could fully read the data from the tcp stream.
The code checks for message truncation and reports an error to the user.  However, it doesn't reset the processing, so that the excess message data is read from the socket.  This results in the excess data being treated as a new message now that truncation errors are no longer fatal to the connection.

prov/tcp: Handle truncation of active message

---

prov/netdir/src/netdir_ep.c

If handle isn't correct type, fail through the error path to silence coverity.

prov/netdir: Fix ep leak in error path in ofi_nd_endpoint

---

.github/workflows/coverity.yml
.github/workflows/gh-man.yaml
.github/workflows/nroff-elves.yaml
.github/workflows/pr-ci.yml

Switch from Node12 to Node16 (whatever that means) in response to Github Actions warnings on PRs.
Fixes #8294

workflows: Update to actions/xxx@v3

---

prov/shm/src/smr.h
prov/shm/src/smr_atomic.c
prov/shm/src/smr_ep.c
prov/shm/src/smr_msg.c
prov/shm/src/smr_rma.c

A series of commits to address https://github.com/ofiwg/libfabric/issues/8976
Ultimately the real cause of the hang may be that there was a path that could use command entries or freestack entries without signalling the peer.  These changes try to address those paths, but also signals the peer any time the peer seems to be out of resources, which should ensure the peer attempts progress.

prov/shm: Handle Freestack Exhaustion, and ensure smr_signal() on EAGAIN

---

fabtests/Makefile.am
fabtests/pytest/efa/test_flood_peer.py

Add a test to flood a peer during startup to ensure good error handling in FI_EAGAIN paths.
---
This test tries to simulate a similar situation as in https://github.com/ofiwg/libfabric/issues/8976, but it's not a perfect reproducer.  In particular main passes this test, but main still had issues on the workloads we were investigating.  Despite that, this is a helpful test, and it does currently error on 1.18.x branch.
The primary reason this test is different than the workload is that the sleep in this test occurs before any exchange of messages.  In the real application we saw an initial exchange, then a flood.

fabtests/pytest: efa test to flood peer during startup

---

prov/shm/src/smr_progress.c

For asynchronous operations the bytes copied is not reported back. When an asynchronous copy completes the entire size requested to be copied should've already been copied. Therefore, keep track of that and report it back in the copy_query API.
Since it's possible to have multiple asynchronous operations for a single copy, if the copy is described over multiple IOVECs, then make sure to add all these up when reporting the final completion.

hmem/rocr: report bytes done

---

prov/hook/hook_hmem/src/hook_hmem.c
prov/tcp/src/xnet_progress.c
src/common.c

In ofi_bsock_send(), we need to check if (-ret) == EAGAIN. The negation is missing, as a result, we won't use the buffered space for queuing messages that can't be written directly to the socket.
This problem was reported by coverity as unreachable code.

common/bsock: Fix error checking for -EAGAIN

---

prov/efa/src/dgram/efa_dgram_ep.c
prov/efa/src/rdm/efa_rdm_atomic.c
prov/efa/src/rdm/efa_rdm_ep_fiops.c
prov/efa/src/rdm/efa_rdm_ep_progress.c
prov/efa/src/rdm/efa_rdm_msg.c
prov/efa/src/rdm/efa_rdm_rma.c
prov/efa/src/rdm/efa_rdm_srx.c

Currently, efa provider always do ofi_mutex_lock/ofi_mutex_unlock to acquire and release ep lock. However, this is not optimal because such lock is unnecessary unless for multi-thread. This patch makes efa provider use ofi_ep_lock_acquire and ofi_ep_lock_release to acquire/release ep lock, which will be no-ops in single thread situation.

prov/efa: optimize ep lock usage.

---

src/common.c
src/fabric.c

Fixes #7706
If the user specified a specific interface, the loopback device should be filtered out (unless the loopback device was the selected device).

prov/tcp: Filter loopback device if iface is specified

---

fabtests/common/shared.c

fabtests: Fix windows build warnings for sscanf

---

fabtests/common/shared.c
fabtests/include/shared.h

Prior to this change, tx_buf and rx_buf is not aligned by default. Moreover, tx_buf is usually on the 2nd half of the whole buf. Therefore, any change to buf_size would change the alignment of tx_buf, which leads to the performance change.
For example, recently fabtests added the data verificiaton of rma_bw, for which 4 bytes was added to buf size, which shifted tx_buf's alignment and changed performance.
To address this issue, this patch make tx_buf and rx_buf to align on 64 bytes boundary by default.

fabtests: make tx_buf and rx_buf aligned to 64 bytes by default

---

include/ofi_mr.h
prov/shm/src/smr_ep.c
prov/shm/src/smr_progress.c

When multiple interface iov support was added, DSA support was skipped because of an incorrect MR check. This adds an extra check to make sure all iovs are host buffers in order to enable the DSA path correctly.

prov/shm: fix DSA enable

---

fabtests/functional/multi_mr.c
fabtests/functional/multi_recv.c
fabtests/include/windows/netdb.h
fabtests/multinode/include/core.h
fabtests/multinode/src/core.c
fabtests/multinode/src/core_coll.c
fabtests/multinode/src/harness.c

Add missing 'void' parameter to function declarations.  Fix one function declaration.
Fixes #8995

fabtests/multinode: Fix function declarations to silence build

---

prov/efa/src/rdm/efa_rdm_srx.c

Peer API recently introduced a new function in peer SRX's owner_ops: https://ofiwg.github.io/libfabric/main/man/fi_peer.3.html
This call is invoked by the peer when any addressing updates have occurred with the peer. This triggers the owner to iterate over any entries whose address is still unknown and call the inputed get_addr function on each to retrieve updated address information.
This patch makes this function as no-op to make https://github.com/ofiwg/libfabric/pull/8907 work because shm provider invoked this call in smr_av_insert. It will be finally replaced by the util_foreach_unspec_addr call defined in util_srx.c after efa provider onboarding the util SRX framework.

prov/efa: Add efa_rdm_srx_foreach_unspec_addr as no-op

---

fabtests/pytest/efa/test_flood_peer.py

Increase timeout of new test_flood_peer.py test to 300 seconds to avoid any question if timeout is due to a hard hang or a slow run.

fabtests/efa: test_flood_peer.py increase timeout

---

fabtests/pytest/efa/test_flood_peer.py

Increase timeout of new test_flood_peer.py test to 300 seconds to avoid any question if timeout is due to a hard hang or a slow run.
Signed-off-by: Luke Robison <lrbison@amazon.com>
(cherry picked from commit 103afcfe5eee620846dd68f55d439ddb5815ab92)

[v1.18.x] fabtests/efa: test_flood_peer.py increase timeout

---

prov/sm2/src/sm2_coordination.c

Fix CID 384050 by allowing common_fd=0 and catching mmap-related errors.
Fix similar leak when mkostemp file creation or map fails.
Change size of mkostemp file's template, as it's not related to FI_NAME_MAX.
check return values of several system calls which were previously ignored.

prov/sm2: Fix startup resource leaks

---

fabtests/common/hmem_cuda.c
fabtests/include/hmem.h

If user selected device by using "-i" option and
selected CUDA memory, this patch call cudaSetDevice() to use that device.
(cherry picked from commit 706cc9fbf2ba49c430757db035dcf9af68eb69e2)

[v1.18.x] backport fabtests: call cudaSetDevice() for selected device

---

man/fi_msg.3.md

The man page currently specifies that driving progress when an operation returns -FI_EAGAIN is "strongly recommended" but should be defined as required for manual progress for applications to be fully compliant.

man/fi_msg: require progress driving for -FI_EAGAIN

---

prov/efa/src/rdm/efa_rdm_ep_progress.c
prov/efa/src/rdm/rxr_pkt_cmd.c
prov/efa/src/rdm/rxr_pkt_entry.c
prov/efa/src/rdm/rxr_pkt_entry.h
prov/efa/src/rdm/rxr_pkt_type.h
prov/efa/src/rdm/rxr_pkt_type_data.c
prov/efa/src/rdm/rxr_pkt_type_misc.c
prov/efa/src/rdm/rxr_pkt_type_req.c
prov/efa/src/rdm/rxr_pkt_type_req.h

For certain packet types such as MEDIUM_RTM, RUNTREAD_RTM and DATA, we send out multiple packets with one call to `ibv_post_send`. Current code use the FI_MORE flag to control the behavior, which require the ep to maintain an internal list of packets that are pending send. In current setting, 1 call to `rxr_pkt_entry_send` does not necessary lead to 1 call to `ibv_post_send`.
This PR has multiple patches that eventually that eliminate the internal list, thus one call to `rxr_pkt_entry_send` will result in 1 call to `ibv_post_send`.

prov/efa: refactor send of multiple packets of same packet type

---

contrib/intel/jenkins/tests.py

tcp;ofi_rxm is missing quotes in oneccl tests which makes invoking it in bash fail

contrib/intel/jenkins: Add missing quotes to oneccl

---

contrib/intel/jenkins/tests.py

tcp;ofi_rxm is missing quotes in oneccl tests which makes invoking it in bash fail

[v1.18.x] contrib/intel/jenkins: Cherry pick add missing quotes to oneccl

---

prov/verbs/src/verbs_cq.c
prov/verbs/src/verbs_ep.c
prov/verbs/src/verbs_ofi.h

The provider reads completions from the HW CQ, processes them, and if needed reports them up to the user in the appropriate format.  Through these steps, it doesn't actually write entries into the libfabric CQ.  However, there are times when it reads from the HW CQ as part of internal progress, but can't report the completions to the user yet.  Rather than writing an entry into the libfabric CQ, it insteads stores the HW completion on a separate list.
The entire process is confusing, results in extra memory, leaves the CQ allocated memory unused, and increases code by not properly leveraging the common CQ functions.
Remove the saved_wc_list and related memory pools.  Instead, after reading from the HW CQ, simply write a completion into the libfabric CQ if one is needed.

prov/verbs: Remove saved_wc_list and use CQ directly

---

fabtests/pytest/efa/test_unexpected_msg.py
prov/efa/Makefile.include
prov/efa/src/efa_domain.c
prov/efa/src/efa_domain.h
prov/efa/src/rdm/efa_rdm_atomic.c
prov/efa/src/rdm/efa_rdm_cq.c
prov/efa/src/rdm/efa_rdm_ep.h
prov/efa/src/rdm/efa_rdm_ep_fiops.c
prov/efa/src/rdm/efa_rdm_ep_progress.c
prov/efa/src/rdm/efa_rdm_ep_utils.c
prov/efa/src/rdm/efa_rdm_msg.c
prov/efa/src/rdm/efa_rdm_msg.h
prov/efa/src/rdm/efa_rdm_ope.c
prov/efa/src/rdm/efa_rdm_ope.h
prov/efa/src/rdm/efa_rdm_peer.c
prov/efa/src/rdm/efa_rdm_rma.c
prov/efa/src/rdm/efa_rdm_srx.c
prov/efa/src/rdm/efa_rdm_srx.h
prov/efa/src/rdm/rxr_pkt_entry.c
prov/efa/src/rdm/rxr_pkt_entry.h
prov/efa/src/rdm/rxr_pkt_type_req.c
prov/efa/test/efa_unit_test_srx.c
prov/efa/test/efa_unit_tests.c
prov/efa/test/efa_unit_tests.h

This PR makes efa provider uses the util SRX framework
proposed in https://github.com/ofiwg/libfabric/pull/8907.
It replaced the recv post (including multi-recv), and msg/tag
matching procedure with the ones defined in util_srx.c

prov/efa: Use util srx framework

---

prov/sm2/src/sm2.h
prov/sm2/src/sm2_ep.c
prov/sm2/src/sm2_progress.c

Reverts ofiwg/libfabric#8960
This gives SM2 unlimited unexpected msg queue buffering again.

Revert "prov/sm2: Get rid of xfer_ctx_pool in unexpected recv path"

---

fabtests/pytest/efa/test_efa_device_selection.py

dgram is unreliable, therefore do not run test in strict mode.
(cherry picked from commit 19aba70a3ad7e1b6e7c6a683c1eb7bd82cb9a456)

[v1.18.x] pytest/efa: unset strict mode for dgram pingpong test

---

prov/efa/Makefile.include
prov/efa/src/rdm/efa_rdm_atomic.c
prov/efa/src/rdm/efa_rdm_ep.h
prov/efa/src/rdm/efa_rdm_ep_progress.c
prov/efa/src/rdm/efa_rdm_ep_utils.c
prov/efa/src/rdm/efa_rdm_msg.c
prov/efa/src/rdm/efa_rdm_ope.c
prov/efa/src/rdm/efa_rdm_ope.h
prov/efa/src/rdm/efa_rdm_rma.c
prov/efa/src/rdm/rxr_pkt_cmd.c
prov/efa/src/rdm/rxr_pkt_cmd.h
prov/efa/src/rdm/rxr_pkt_entry.c
prov/efa/src/rdm/rxr_pkt_entry.h
prov/efa/src/rdm/rxr_pkt_type.h
prov/efa/src/rdm/rxr_pkt_type_data.c
prov/efa/src/rdm/rxr_pkt_type_misc.c
prov/efa/src/rdm/rxr_pkt_type_req.c
prov/efa/src/rdm/rxr_pkt_type_req.h
prov/efa/test/efa_unit_test_rnr.c
prov/efa/test/efa_unit_tests.c
prov/efa/test/efa_unit_tests.h

For some packet type, rxr_pkt_post() may need to send multiple packets.
Prior to this change, to send N packets, rxr_pkt_post() will call rxr_pkt_entry_sendv() N times. The first N - 1 call will has the flag FI_MORE, to indicate there are more to come. The last call without the FI_MORE flag will cause all N packets to be sent via device, which require the endpoint to maintain a list of outgoing packets.
This patch change to rxr_pkt_post() to
1. create N packets
2. call rxr_pkt_entry_send() once to send all N packets.
With this change, some functions became useless and was eliminated by this patch. Including the following functions:
1. efa_rdm_ep_post_flush() was used by rxr_pkt_entry_sendv() to actually post send. With this change, rxr_pkt_entry_sendv() post send directly, therefore …

prov/efa: rxr_pkt_post() call rxr_pkt_entry_sendv() once

---

prov/efa/test/efa_unit_test_rnr.c

rxr_pkt_entry has been renamed to efa_rdm_pke, this patch fixed it.

prov/efa: fix typo in test_efa_rnr_queue_and_resend()

---

prov/efa/src/rdm/efa_rdm_msg.c

Currently, efa_rdm_msg_select_rtm return readbase_rtm if local ep support rdma-read. This is wrong because the read protocols require both local and peer support rdma-read. This patch fixes this issue.

prov/efa: Only select readbase_rtm when both sides support rdma-read

---

prov/efa/src/rdm/rxr_msg.c

Currently, rxr_msg_select_rtm return readbase_rtm if local ep support rdma-read. This is wrong because the read protocols require both local and peer support rdma-read. This patch fixes this issue.
(cherry picked from commit 085c21c)

[v1.18.x] prov/efa: Only select readbase_rtm when both sides support rdma-read

---

prov/efa/src/dgram/efa_dgram_ep.h
prov/efa/src/rdm/efa_rdm_ep.h
prov/efa/src/rdm/efa_rdm_ep_progress.c
prov/efa/src/rdm/efa_rdm_ep_utils.c
prov/efa/src/rdm/efa_rdm_pke.c
prov/efa/src/rdm/efa_rdm_pke.h
prov/efa/src/rdm/rxr_pkt_pool.c
prov/efa/src/rdm/rxr_pkt_pool.h
prov/efa/src/rdm/rxr_pkt_type_base.c

a series of patches that eliminates the recv_wr in packet entry and the sendv_pool, and clean up space in `efa_rdm_pke`

prov/efa: eliminate the recv_wr in packet entry and sendv_pool

---

fabtests/common/shared.c

An incorrect index was used to attempt to set test_sizes.enable_flags. For small list sizes (<3 chars) malloc would become corrupted and future calls would fail unexpectedly.
Setting this variable to 0 was uncessary as the calloc() cleared the memory already.

fabtests: Fix array OOB during fabtest list parsing

---

prov/sm2/src/sm2_msg.c
prov/sm2/src/sm2_progress.c

Add tx_lock to generic inject path.
Add tx_lock (which currently controls freestack access) to buffer return.

prov/sm2: Fix locking

---

contrib/intel/jenkins/Jenkinsfile
contrib/intel/jenkins/run.py
contrib/intel/jenkins/runtests.py
contrib/intel/jenkins/summary.py

Tests missing from summary due to typos that will be added back: oneCCL reg
oneCCL-GPU reg
shmem prov tests (isx, uh, prk)
ze shm h2d reg
ze shm d2d reg
ze shm xd2d reg
Fixing summary.py's expectation of these filenames will bring these tests back to the summary stage. Changing how filenames are generated will also help with some cases and have names make more sense.

contrib/intel/jenkins: Add missing tests from cloudbees migration back to summarizer.

---

libfabric.vcxproj
prov/efa/Makefile.include
prov/efa/src/efa_mr.h
prov/efa/src/rdm/efa_rdm_pke.c
prov/efa/src/rdm/efa_rdm_pke.h
prov/efa/src/rdm/efa_rdm_pke_utils.c
prov/efa/src/rdm/efa_rdm_pke_utils.h
prov/efa/src/rdm/efa_rdm_pkt_type.h
prov/efa/src/rdm/rxr_pkt_cmd.c
prov/efa/src/rdm/rxr_pkt_type_base.c
prov/efa/src/rdm/rxr_pkt_type_base.h
prov/efa/src/rdm/rxr_pkt_type_data.c
prov/efa/src/rdm/rxr_pkt_type_misc.c
prov/efa/src/rdm/rxr_pkt_type_req.c

This patch added following changes to properly set payload and payload_size of a packet:
1. Upon receiving a packet, set its payload and payload_size if the packet contains data.
2. When clone a packet, set cloned packet's payload and payload_size if the packet contains data.
With the above changes, a packet's payload and payload_size is always set properly.  This patch then started using payload and payload_size:
1. it used payload_size to replace fucntion calls to rxr_pkt_data_size() and rxr_pkt_req_data_size(), and eliminated these two functions.
2. it used payload in rxr_pkt_copy_data_to_ope() and renamed the function efa_rdm_pke_copy_payload()
It then eliminated two functions that calculate payload size on the fly: rxr_pkt_data_size() rxr_pkt_req_data_size()

prov/efa: set and use pke->payload and pke->payload_size

---

prov/efa/src/efa_hmem.c
prov/efa/src/efa_prov_info.c

efa_hmem.c and efa_prov_info.c did not include
rxr_pkt_type_req.h therefore cannot find rxr_pkt_max_hdr_size() during compilation. This patch fixed the issue.

prov/efa: include header to fix compilation warning

---

fabtests/pytest/efa/test_rdm.py
prov/efa/src/efa_cntr.c

ofi_cntr_progress will call ep->progress for every ep
it was bound to. There was a ep->lock in efa_rdm_ep_progress,
but it was recently changed to srx_ctx->lock
and moved from efa_rdm_ep_progress() to its upper layer callers.
This patch adds this locking around ofi_cntr_progress.
Also added a test that poll completions with cntr instead of queue, to cover this code path.

prov/efa: Add missing locking around cntr progress

---

prov/efa/Makefile.include
prov/efa/src/rdm/efa_rdm_msg.c
prov/efa/test/efa_unit_test_common.c
prov/efa/test/efa_unit_test_ope.c
prov/efa/test/efa_unit_test_send.c
prov/efa/test/efa_unit_tests.c
prov/efa/test/efa_unit_tests.h

In efa_rdm_msg_sendv, when desc is NULL, we shouldn't try to get desc for shm.
Also add a unit test to scan all fi_send* and fi_tsend APIs for such issue.

prov/efa: Fix a bug in desc convert and adding tests

---

prov/efa/src/rdm/rxr_op_entry.c

Current code apply the byte_in_order_128_byte option only on cuda memory. But the document did not specify this contraint. This patch apply the alignment to all memory types.

[v1.18.x] prov/efa: apply byte_in_order_128_byte for all memory type

---

prov/efa/src/rdm/efa_rdm_ope.c
prov/efa/test/efa_unit_test_cq.c
prov/efa/test/efa_unit_test_ep.c
prov/efa/test/efa_unit_test_mocks.c
prov/efa/test/efa_unit_test_mocks.h
prov/efa/test/efa_unit_test_ope.c
prov/efa/test/efa_unit_test_rnr.c
prov/efa/test/efa_unit_tests.c
prov/efa/test/efa_unit_tests.h

fix efa_rdm_ope_post_remote_write for 0 byte, and add a unit test.

prov/efa: fix 0 byte write and add unit test

---

prov/tcp/src/xnet.h
prov/tcp/src/xnet_domain.c
prov/tcp/src/xnet_ep.c
prov/tcp/src/xnet_rdm.c
prov/tcp/src/xnet_rdm_cm.c

The tcp provider cannot mix rdm and msg endpoints on the same domain because of locking restrictions and optimizations targeting rdm endpoint support.  Fail calls that try to open and endpoint type not supported by the domain.

prov/tcp: Restrict which EPs can be opened per domain

---

prov/sm2/src/sm2_coordination.c
prov/sm2/src/sm2_coordination.h
prov/sm2/src/sm2_fifo.h

This change causes the entire shared memory file to be allocated and mapped into each processes address space on startup. This change fixes a multi-threaded race condition where one thread calls remap in sm2_av_insert() while another thread is in the middle of a sm2_fifo_read(), or sm2_fifo_write(). We need increased memory usage in order to provide correctness to the user.

prov/sm2: Allocate and map maximum size shm file at init

---

contrib/intel/jenkins/tests.py

Use python to invoke launch.py for daos instead of ./ since ./will use the latest version.

contrib/intel/jenkins: use python to invoke launch.py

---

prov/efa/src/rdm/efa_rdm_pke_cmd.c

In efa_rdm_pke_handle_recv_completion(), the counter efa_rx_pkt_posted should be reduced by 1 for each packet. However, prior to this patch, if a packet was ignored due to removed peer, The counter was not reduced. This patch addressed the issue.

prov/efa: fix efa_rx_pkt_posted counter reduction when handle packets

---

prov/efa/src/rdm/efa_rdm_pke.c
prov/efa/src/rdm/efa_rdm_pke_cmd.c

The name and the signature of the function changed, therefore the caller need to be updated accordingly.

prov/efa: fix calling of efa_rdm_pke_print()

---

prov/efa/src/rdm/efa_rdm_ep_fiops.c
prov/efa/src/rdm/efa_rdm_ep_progress.c
prov/efa/src/rdm/efa_rdm_ep_utils.c
prov/efa/src/rdm/efa_rdm_msg.c
prov/efa/src/rdm/efa_rdm_ope.c
prov/efa/src/rdm/efa_rdm_peer.c
prov/efa/src/rdm/efa_rdm_pke.c
prov/efa/src/rdm/efa_rdm_pke.h
prov/efa/src/rdm/efa_rdm_pke_cmd.c
prov/efa/src/rdm/efa_rdm_pke_nonreq.c
prov/efa/src/rdm/efa_rdm_pke_rta.c
prov/efa/src/rdm/efa_rdm_pke_rtm.c
prov/efa/src/rdm/efa_rdm_pke_rtr.c
prov/efa/src/rdm/efa_rdm_pke_rtw.c
prov/efa/src/rdm/efa_rdm_srx.c
prov/efa/test/efa_unit_test_ep.c
prov/efa/test/efa_unit_test_ope.c

According to our coding convention, functions with efa_rdm_pke prefix should use a pointer to efa_rdm_pke as 1st argument. This patch ensures that.

prov/efa: update signature of efa_rdm_pke functions

---

fabtests/common/shared.c
fabtests/functional/unexpected_msg.c
fabtests/include/shared.h

Allows for testing unexpected messages to and from device memory

fabtests: Add HMEM support to fi_unexpected_msg test

---

prov/shm/src/smr_domain.c
prov/sm2/src/sm2_domain.c

SM2 is currently hard coding FI_THREAD_SAFE, but the correct behavior for the provider is to assume the domain thread safety-ness.

prov/sm2: Default to ep->domain->threading

---

fabtests/pytest/common.py
fabtests/pytest/conftest.py
fabtests/pytest/default/test_rdm.py
fabtests/pytest/default/test_rma_bw.py
fabtests/pytest/efa/efa_common.py
fabtests/pytest/efa/test_efa_protocol_selection.py
fabtests/pytest/efa/test_fork_support.py
fabtests/pytest/efa/test_rdm.py
fabtests/pytest/efa/test_rma_bw.py
fabtests/pytest/efa/test_runt.py
fabtests/pytest/shm/shm_common.py
fabtests/pytest/shm/test_rdm.py
fabtests/pytest/shm/test_rma_bw.py
fabtests/pytest/sm2/sm2_common.py
fabtests/pytest/sm2/test_rdm.py

This PR renames the original `completion_type` to `complete_semantic` to better reflect its meaning. Also introduce a new `completion_type` parameter to stand for the `queue` and `counter` completion types.

fabtests/pytest: Two changes on the "completion_type" parameter

---

prov/sm2/src/sm2_progress.c

We need to return the xfer_entry irrespective of the completion status

prov/sm2: Fix return_xfer_entry bug

---

contrib/intel/jenkins/Jenkinsfile
contrib/intel/jenkins/runtests.py
contrib/intel/jenkins/summary.py

Adding daos as multiple different agents will allow concurrent building and parallel running of daos smoke tests. This will allow build, summary, and cleanup to happen while tests are running in a different job.

contrib/intel/jenkins: Split daos into build and test executors

---

fabtests/benchmarks/rdm_cntr_pingpong.c

All other benchmarks have this mode and this allows to run the test with providers requiring it.

fabtests: Add FI_CONTEXT mode to rdm_cntr_pingpong

---

include/rdma/fabric.h
man/fi_endpoint.3.md
prov/sm2/src/sm2_attr.c
src/fi_tostr.c

Libfabric documentation states that endpoints with the same protocol must interoperate. SHM and SM2 cannot interoperate, so SM2 needs a new protocol

prov/sm2: Change SM2 protocol to FI_PROTO_SM2

---

prov/efa/src/efa_domain.c
prov/efa/src/efa_env.c
prov/efa/src/efa_env.h
prov/efa/src/efa_prov_info.c
prov/efa/src/efa_shm.c
prov/efa/src/rdm/efa_rdm_ep_fiops.c

Change the env variable that controls EFA's intranode provider to be more generic.  Switch variable from a bool to a string.

prov/efa: Change FI_EFA_USE_SM2 to FI_EFA_INTRANODE_PROVIDER

---

fabtests/pytest/conftest.py
fabtests/pytest/shm/shm_common.py
fabtests/pytest/shm/test_rdm.py
fabtests/pytest/sm2/sm2_common.py
fabtests/pytest/sm2/test_rdm.py
include/ofi_util.h
prov/efa/src/efa_cntr.c
prov/mrail/src/mrail_cq.c
prov/mrail/src/mrail_ep.c
prov/mrail/src/mrail_rma.c
prov/rxd/src/rxd_cntr.c
prov/rxm/src/rxm_conn.c
prov/rxm/src/rxm_cq.c
prov/rxm/src/rxm_ep.c
prov/rxm/src/rxm_msg.c
prov/rxm/src/rxm_rma.c
prov/tcp/src/xnet.h
prov/tcp/src/xnet_msg.c
prov/tcp/src/xnet_progress.c
prov/tcp/src/xnet_rdm.c
prov/tcp/src/xnet_rdm_cm.c
prov/tcp/src/xnet_rma.c
prov/ucx/src/ucx_callbacks.c
prov/ucx/src/ucx_core.c
prov/ucx/src/ucx_core.h
prov/ucx/src/ucx_rma.c
prov/util/src/util_cntr.c
prov/util/src/util_ep.c

Currently, cntrs for different operations have different
field names in util_ep, which causes code duplication and
makes it hard to expand in the future. This patch refactor
this code path by introducing two arrays: util_ep.cntrs, and
util_ep.cntr_inc_funcs to store the pointers to the cntrs
and its inc functions, which share the uniform procedure
in ep creation, bind, and close.
This PR also expand the rdm test in fabtests/pytest/shm,sm2 to cover cntr completion type.

prov/util,efa,tcp,mrail,rxd,rxm,ucx: Refactor the usage of cntrs

---

prov/mrail/src/mrail_init.c

Currently, "OFI_MRAIL_ADDR_STRC env variable not set!" gets logged at warning on every run, even if we aren't using the mrail provider. Change this to be an info to clean up the warning log.

prov/mrail: Turn Noisy WARN to INFO

---

fabtests/common/shared.c
fabtests/functional/multi_ep.c
fabtests/functional/rdm_atomic.c
fabtests/functional/rdm_rma_event.c
fabtests/functional/rdm_rma_trigger.c
fabtests/functional/scalable_ep.c
fabtests/functional/shared_ctx.c
fabtests/include/shared.h
fabtests/multinode/src/core.c
fabtests/multinode/src/core_coll.c

this fixes running fi_rma_bw -t counter which previously allowed one side to exit while the other was still in the middle of the test
**I did not update the deferred work test because it was convoluted and I think already broken and nobody supports deferred work except the sockets provider... but I can update/rewrite the test it if someone feels strongly about it

fabtests/common: separate RX and RMA counters

---

prov/sm2/src/sm2_coordination.c
prov/sm2/src/sm2_init.c

Modify SM2 to only produce 1 warning per endpoint on successful startup (that SM2 is being used + the endpoints allocation).

prov/sm2: Cleanup warnings on startup

---

include/ofi_enosys.h
include/ofi_util.h
prov/shm/src/smr_atomic.c
prov/shm/src/smr_comp.c
prov/shm/src/smr_msg.c
prov/shm/src/smr_rma.c
prov/sm2/src/sm2_atomic.c
prov/sm2/src/sm2_comp.c
prov/sm2/src/sm2_msg.c
prov/util/src/util_cntr.c
src/enosys.c

This PR contains a series of commits to add FI_PEER support to util counter and make shm/sm2 use it.
Still working on adding fabtests in fabtests/pytest for the cntr for shm and sm2, will push more commits later.

prov/util, shm, sm2: Add FI_PEER support to util counter and make shm/sm2 use it.

---

prov/tcp/src/xnet_progress.c

Commit 489d7804cf78fe2cd6fe119aff595df5b8b8659c added truncation handling in the saved message path but removed the iov truncation of the rx entry iov. This caused erroneous truncation errors because too much data would be read off the socket, causing the next send to report a truncation.
Fixes #9099

prov/tcp: fix missing iov truncation on saved message path

---

fabtests/functional/unexpected_msg.c

unexpected_msg test uses the `-v` option but is not a benchmark, so move the `-v` option from benchmark to shared options
Also allocate `tx_msg_buf` which is required for verification when using device buffers

fabtests/unexpected_msg: Changes to unexpected_msg test

---

fabtests/pytest/efa/efa_common.py
fabtests/pytest/efa/test_rdm.py
include/ofi_util.h
prov/efa/src/efa_cntr.c
prov/efa/src/efa_cntr.h
prov/efa/src/rdm/efa_rdm_ep_fiops.c
prov/util/src/util_cntr.c

This PR makes efa provider open shm's cntr as a peer cntr, so the cntr completion written by shm provider can be populated to efa's cntr.
Also extended the efa rdm fabtests to cover counter completion type. Before this PR, this test will fail on single node.

prov/util, efa: use shm cntr as a peer cntr

---

contrib/intel/jenkins/Jenkinsfile

The middlewares folder doesn't get cleaned up every time after an abort and causes lots of file buildup on the system. Cleanining it up after aborting should alleviate this issue.

contrib/intel/jenkins: Destroy middlewares folder on abort

---

include/ofi_shm.h
prov/shm/src/smr_atomic.c
prov/shm/src/smr_dsa.c
prov/shm/src/smr_ep.c
prov/shm/src/smr_msg.c
prov/shm/src/smr_progress.c
prov/shm/src/smr_rma.c
prov/util/src/util_shm.c

The signal was originally added to reduce locking contention in the shared memory region. Now that the command queue uses atomics instead of locking, the signal adds redunancy and extra atomics. Removing it improves performance.
Requires bumping the shm version

prov/shm: remove shm signal

---

include/ofi_util.h

Add assert for the cntr_index to make sure
it is smaller than the CNTR_CNT
Related coverity scan defects
```
** CID 395887:  Memory - illegal accesses  (OVERRUN)
/include/ofi_util.h: 779 in ofi_ep_peer_tx_cntr_inc()
________________________________________________________________________________________________________
*** CID 395887:  Memory - illegal accesses  (OVERRUN)
/include/ofi_util.h: 779 in ofi_ep_peer_tx_cntr_inc()
773     static inline void ofi_ep_peer_tx_cntr_inc(struct util_ep *ep, uint8_t op)
774     {
775             struct util_cntr *cntr;
776             int cntr_index;
777
778             cntr_index = ofi_get_cntr_index_from_tx_op(op);
>>>     CID 395887:  Memory - illegal accesses  (OVERRUN)
>>>     Overrunning array "ep->cntrs" of 6 8-byte elements at element index 6 …
```

prov/util: Fix the coverify scan defects

---

prov/verbs/src/verbs_cq.c
prov/verbs/src/verbs_ep.c

Flushed CQEs would come ether after the CQE for the op that caused the QP tranition or in QP destrouction.  There is no need to check with flushed CQEs.
Add missing return code check for ibv_query_qp.

prov/verbs: Add additional checks to vrb_shutdown_qp_in_err

---

prov/efa/src/efa_mr.c

prov/efa: fix coverity warnings

---

contrib/intel/jenkins/Jenkinsfile

Add a parameter to help the weekly job not opt-out when the changeset is empty
Change fake boolean variables into actual boolean variables in the jenkinsfile.
This allows for easier checking of whether or not to run in the opt-out stage.
Pipeline will not run if:
Changeset contains only files in:
fabtests/pytests
man
prov/efa
prov/opx
AND
Job is not a weekly job

contrib/intel/jenkins: Add parameter for weekly job to not opt-out

---

include/unix/osd.h

If no atomics are available, ofi will emulate atomics using locks. In this case, no memory ordering is required.
If the atomics ordering primitives are not available, the build will fail. This adds a definition for the memory ordering to allow it to build

include/osd.h: add defintion of memory ordering for no atomics

---

prov/tcp/src/xnet_progress.c

Commit 489d7804cf78fe2cd6fe119aff595df5b8b8659c added truncation handling in the saved message path but removed the iov truncation of the rx entry iov. This caused erroneous truncation errors when a receive was posted that was larger than the matched send because too much data would be read off the socket, corrupting the tcp stream relative to the receiver.
This fixes a sporadic failure in the fi_rdm_tagged_bw test
Cherry-picked from commit 67cf6d97e49f570e77ac86ac148f893ca486a537

[v1.18.x] prov/tcp: fix missing iov truncation on saved message path

---

src/iov.c

Previously either iov_count would be 0, or iov_count=1 and iov[0].iov_len=0.  Now both iov_count=0 and iov[0].iov_len0.
Same for ofi_consume_rma_iov.
---
See https://github.com/ofiwg/libfabric/issues/9035

src/iov.c: ofi_consume_iov consistency

---

contrib/intel/jenkins/runtests.py
contrib/intel/jenkins/summary.py

Fix multinode_performace stage's expected file name in the summarizer
Add more information about what hardware each test ran on to the summary output

contrib/intel/jenkins: Fix multinode filename & add extra information to summary

---

src/iov.c

Removed assert(to_consume) in ofi_consume_iov and ofi_consume_rma_iov. This check is not required as the functions can correctly consume 0 bytes from an iov.
--
A regression was noticed by EFA nightly CI after merging #9050.  Rather than prevent zero-sized consumes, it was decided that it should be legal to consume 0 bytes (as it was before #9050).  See https://github.com/ofiwg/libfabric/pull/9166 for additional context.

src/iov.c: ofi_consume_iov allows 0-byte consume

---

include/unix/osd.h

If no atomics are available, ofi will emulate atomics using locks. In this case, no memory ordering is required.
If the atomics ordering primitives are not available, the build will fail. This adds a definition for the memory ordering to allow it to build
Cherry-picked from commit 367b708b65cf89a9da74eade712cdd94402279ca

[v1.18.x] include/osd.h: add defintion of memory ordering for no atomics

---

prov/tcp/src/xnet.h
prov/tcp/src/xnet_domain.c
prov/tcp/src/xnet_ep.c
prov/tcp/src/xnet_msg.c
prov/tcp/src/xnet_pep.c
prov/tcp/src/xnet_progress.c
prov/tcp/src/xnet_rma.c

Problems reported by thread sanitizer.  There is no locking around checking the CQ or EQ for being empty.  It's unclear if the locking is technically needed, but safer to add given the code is not in a fast path (prior to the app making a blocking call).
Note that with the change, the lock used by the CQ and cntr signaling fd is not technically needed, as the progress lock protects the entire operation.  Removal of the lock is deferred for subsequent patches, as the EQ locking requires further investigation (in order to remove).
Fixes #9148

prov/tcp: Add locking to trywait path for potential data race

---

contrib/intel/jenkins/Jenkinsfile
contrib/intel/jenkins/common.py
contrib/intel/jenkins/run.py
contrib/intel/jenkins/runtests.py
contrib/intel/jenkins/summary.py
contrib/intel/jenkins/tests.py

DAOS was using the output of the wrong command for its log. This PR fixes that issue.
Any invocation of runtests.py can now provide its own logfile instead of using the one generated with slurm or the jenkinsfile.
It also addresses the failure summary case for daos by cleaning up the multiple prints of the same test and providing a better log of what failed.
The summary gets better spacing in addition to the failure case for daos.
The release case gets updated to match the true/false boolean variable update that all other variables in the Jenkinsfile follow.

contrib/intel/jenkins: Fix DAOS logging and summary

---

configure.ac
src/hmem_cuda.c

Check for CUDA devices with nvmlDeviceGetCount_v2() first, to avoid more expensive call to cudaGetDeviceCount() when possible.

Use nvmlDeviceGetCount_v2() first for CUDA check

---

contrib/intel/jenkins/Jenkinsfile
contrib/intel/jenkins/summary.py
contrib/intel/jenkins/tests.py

Import files from sub-clusters (non main pipeline clusters) to be run through the summarizer once rather than have to invoke the summarizer on each cluster.
Add DSA and GPU-V3 to the summary
Cleanup the Jenkinsfile:
Make re-used variables global pipeline environment variables
Add methods for withEnv statements to remove large triple quote shell blocks.
Replace non script{} blocks with script{} blocks for better maintainability 
Reduce new line use in post stage by consolidating one line bracket statements into one line
Reduce most lines to less than 80 characters to follow libfabric coding style

contrib/intel/jenkins: Add file importing to Summarizer & Cleanup Jenkinsfile

---

contrib/intel/jenkins/Jenkinsfile
contrib/intel/jenkins/summary.py

Add FI_LOG_LEVEL=warn to DSA stage so that it prints out information to determine if DSA is actually being used.
The summary stage will then parse this information to determine if DSA was correctly used in the tests and will fail if it did not.

contrib/intel/jenkins: Add tracer check to DSA

---

contrib/intel/jenkins/Jenkinsfile
contrib/intel/jenkins/summary.py

With these changes Cloudbees will send an email at the end of an automatic weekly run to the mail recipients detailed in the controller. This can be turned on or off depending on the weekly environment variable or by removing/adding the new flag --send_mail to the summarizer.

contrib/intel/jenkins: Add automatic emailing support to summary

---

prov/verbs/src/verbs_cq.c
prov/verbs/src/verbs_ep.c

Flushed CQEs would come ether after the CQE for the op that caused the QP tranition or in QP destrouction.  There is no need to check with flushed CQEs.
Add missing return code check for ibv_query_qp.
cherry-picked from main

[v1.18.x] prov/verbs: Add additional checks to vrb_shutdown_qp_in_err

---

prov/efa/src/rdm/rxr_atomic.c
prov/efa/src/rdm/rxr_ep.c
prov/efa/src/rdm/rxr_ep.h
prov/efa/src/rdm/rxr_msg.c
prov/efa/src/rdm/rxr_op_entry.c
prov/efa/src/rdm/rxr_rma.c

rxr_rm_cq_check() check whether util_cq is overflow, and set the RXR_RM_TX/RX_CQ_FULL flag.
If the flags are full, fi_send/read/write/atomic will return -FI_EAGAIN.
The code as is does not work, because when -FI_EAGAIN is returned, progress engine is not called so if the RXR_RM_TX/RX_CQ_FULL flag is ever set, an application will hang.
Meanwhile, the check itself is not necesary because util_cq can handle the situation that CQ is full
by writing overflow CQ entry.
Therefore, this patch remove the code from critical code path.
Reimplementation of commit 1de4f5a9032cd3b2df0cca128735b95dd4a1b5d2

[v1.18.x] prov/efa: remove rxr_rm_tx/rx_cq_check()

---

prov/efa/src/rdm/rxr_rma.c

Currently, efa directly returns shm's inject_write/write_data when the peer is local. In the current code,
the cntr increment only happens in report_tx/rx_complete which happens after efa polls a completion entry from shm cq. However, inject_write won't generate completion, so this cntr increment would never happen.
This patch fixed this issue by incrementing the cntr explicitly after the inject_write returns.

[v1.18.x] prov/efa: report cntr completion for shm inject write.

---

include/ofi_hmem.h
prov/shm/src/smr.h
prov/shm/src/smr_ep.c
prov/shm/src/smr_progress.c
src/hmem.c

This optimization disables the polling of the async ipc list when there are no users of it.
https://github.com/ofiwg/libfabric/issues/9141

prov/shm: Only poll IPC list when ROCR IPC is enabled

---

prov/shm/src/smr.h
prov/shm/src/smr_ep.c
prov/shm/src/smr_msg.c
prov/shm/src/smr_rma.c

The same protocol selection logic was copy/pasted into both smr_generic_rma() and smr_generic_send(). Remove copy/pasted logic and put it in the common function where it belongs.

prov/shm: Move selection logic to smr_select_proto()

---

configure.ac
src/hmem_cuda.c

Checking w/lightweight nvmlDeviceGetCount_v2() call first allows us to avoid the more expensive call to cudaGetDeviceCount() when there's no NVIDIA devices on the node.
(cherry picked from commit fad962b8cb2cc7c0333e166a56b2e1144cd92869)

[v1.18.x] Check for CUDA devices with nvmlDeviceGetCount_v2() first

---

fabtests/pytest/efa/test_unexpected_msg.py
prov/shm/src/smr.h
prov/shm/src/smr_ep.c
prov/shm/src/smr_msg.c

Currently smr_rx_entry is popped from a freestack of a fixed size (rx_size). However, both posted recv and unexpected message allocation will pop rx entry from the same stack, which makes it drained when the number of posted_recv + unexp_message >= rx_size.
This patch switch srx->recv_fs into srx->rx_pool as a buffer pool that can grow, and makes smr_rx_entry allocated from the rx pool
Note that this PR is opened directly to v1.18.x branch because shm's rx entry is already allocated from buffer pool in main branch, after using util srx.

[v1.18.x] prov/shm: change recv entry freestack into bufpool 

---

prov/verbs/include/fi_verbs.h
prov/verbs/src/verbs_ep.c
prov/verbs/src/verbs_eq.c

Flushed CQEs would come ether after the CQE for the op that caused the QP tranition or in QP destrouction.  There is no need to check with flushed CQEs.
Add missing return code check for ibv_query_qp.

[v1.18.x] prov/verbs: Prevent duplicate FI_SHUTDOWN events

---

fabtests/pytest/shm/conftest.py
fabtests/pytest/shm/shm_common.py
fabtests/pytest/shm/test_rma_bw.py
fabtests/test_configs/shm/shm.exclude
prov/shm/src/smr_ep.c
prov/shm/src/smr_progress.c

Currently, SAR protocol doesn't handle 0 byte transfer because it fails to update the resp->status correctly in this corner case. This patch fixes this issue.
Also added test to verify the fix.
The issue can be reproduced by running 
```
fi_rma_bw -p shm -I 5 -v -S 0 -e rdm -s localhost
```
`-v` is needed to make fi_rma_bw run with FI_DELIVERY_COMPLETE, which will force SHM to use SAR protocol.

prov/shm: Handle 0 byte transfer in SAR protocol

---

prov/shm/src/smr_dsa.c
prov/shm/src/smr_ep.c
prov/shm/src/smr_progress.c
prov/shm/src/smr_util.h

Replace SMR_STATUS_SAR_READY with SMR_STATUS_SAR_FULL and SMR_STATUS_SAR_FREE with SMR_STATUS_SAR_EMPTY. The current enum names are confusing to me b/c READY depends on if you are taking the perspective of the sender or the receiver.

prov/shm: Rename SAR status enum to be more clear

---

prov/efa/src/efa_shm.c
prov/efa/test/efa_unit_test_common.c
prov/efa/test/efa_unit_test_info.c

Currently, the tx/rx op flags are hard-coded as FI_COMPLETION for shm, which is wrong because currently efa is using shm as a peer provider and should pass application requested op flags to shm as well.
Also add unit test for this change

prov/efa: Use correct tx/rx op_flags for shm

---

contrib/intel/jenkins/Jenkinsfile

Oneccl-GPU-V3 tests need to be temporarily disabled while node upgrades occur.

contrib/intel/jenkins: Disable Oneccl-GPU-v3 tests

---

prov/tcp/src/xnet_eq.c
prov/verbs/src/verbs_cm.c
prov/verbs/src/verbs_cm_xrc.c
prov/verbs/src/verbs_cq.c
prov/verbs/src/verbs_domain.c
prov/verbs/src/verbs_domain_xrc.c
prov/verbs/src/verbs_ep.c
prov/verbs/src/verbs_eq.c
prov/verbs/src/verbs_ofi.h

Track the connection state of msg endpoints.  This is needed to safely transition into a disconnect state, while ensuring that we only report a shutdown event to the user once.
There are 2 separate ways that we can determine that an endpoint has been disconnected.  One is by reading a disconnect event from the rdma cm.  Another is by reading an error completion from the CQ associated with the underlying QP.  Because we're not guaranteed to get a disconnect event (the remote peer system may have crashed without generating an RDMA disconnect traffic), if we read an error completion from the CQ, we need to notify the user that the local EP is no longer usable.  We do this by generating a local shutdown event.
However, we _could_ read a disconnect event from the EQ.  We have no way of knowing …

prov/verbs: Track ep state to prevent duplicate shutdown events

---

contrib/intel/jenkins/Jenkinsfile
fabtests/pytest/shm/conftest.py
fabtests/pytest/shm/shm_common.py
fabtests/pytest/shm/test_rma_bw.py
fabtests/test_configs/shm/shm.exclude
prov/efa/src/efa_shm.c
prov/efa/test/efa_unit_test_common.c
prov/efa/test/efa_unit_test_info.c
prov/shm/src/smr_ep.c
prov/shm/src/smr_progress.c

This PR backports https://github.com/ofiwg/libfabric/pull/9203 and https://github.com/ofiwg/libfabric/pull/9200 to v1.19.x

[V1.19.x] prov/efa,shm: backport the fix for SHM's 0 byte SAR and EFA's tx/rx op flags

---

fabtests/functional/unexpected_msg.c

Currently, tx/rx_size is opts.transfer_size + ft_tx_prefix_size(),
which may be not large enough for the address message in
exchange_unexp_addr, which is of size FT_MAX_CTRL_MSG. This patch
fixes this issue.

fabtests/unexpected_msg: Make tx/rx_size large enough

---

prov/shm/src/smr.h
prov/shm/src/smr_atomic.c
prov/shm/src/smr_ep.c
prov/shm/src/smr_msg.c
prov/shm/src/smr_progress.c
prov/shm/src/smr_rma.c

The tx_lock allows a sender thread to send at the same time a receiver thread can receive on an endpoint. This change gets rid of that functionality and only allows 1 thread in an endpoint send or receive at a time. When we move all SHM resources to the sender, we suspect that the sender/receiver will be to intertwined to be able to progress independently.
This change also boosts performance by switching to a ofi_genlock instead of an ofi_spinlock.

prov/shm: Replace tx_lock with ep_lock

---

prov/shm/configure.m4
prov/shm/src/smr_dsa.c
prov/shm/src/smr_dsa.h
prov/shm/src/smr_init.c
prov/sm2/configure.m4

Currently, if DSA libraries are found on the build node, the libfabric build will always get linked to the accfg-config library. If the compute nodes do not have this library, runs will fail even if DSA is not being used.
This changes the DSA config checks to only check the headers and then adds DL loading/functions to the DSA code to use the library dynamically so that it can be used on a cluster with different configurations.
Also fixes a compiler warning to remove an unused variable in the DSA code

prov/shm: improve DSA library linking

---

Makefile.am
configure.ac
include/ofi.h
include/ofi_cma.h
include/ofi_mr.h
include/ofi_shm_p2p.h
include/ofi_xpmem.h
include/windows/osd.h
libfabric.vcxproj
man/fi_shm.7.md
prov/gni/configure.m4
prov/shm/src/smr.h
prov/shm/src/smr_ep.c
prov/shm/src/smr_init.c
prov/shm/src/smr_msg.c
prov/shm/src/smr_progress.c
prov/shm/src/smr_rma.c
prov/shm/src/smr_util.c
prov/shm/src/smr_util.h
prov/util/src/cuda_ipc_monitor.c
prov/util/src/rocr_ipc_monitor.c
prov/util/src/util_mem_monitor.c
prov/util/src/util_mr_cache.c
prov/util/src/xpmem_monitor.c
src/fabric.c
src/hmem_ipc_cache.c
src/xpmem.c
src/xpmem_cache.c

Add support for XPMEM the same way as other HMEM entries.
XPMEM makes use of the IPC caching to avoid repeated calls to xpmem_attach()/xpmem_detach()

Add Support for XPMEM

---

contrib/intel/jenkins/Jenkinsfile

Re-enabling oneccl-gpu-v3 stage now that node upgrade has been completed

contrib/intel/jenkins: Re-enable oneccl-gpu-v3

---

src/hmem_cuda.c

[v1.19.x] Try libnvidia-ml.so.1 if .so symlink missing, and skip NVML when not available
Local testing on Debian has shown a case where the libnvidia-ml-so symlink to
libnvidia-ml.so.1 doesn't exist (but libnvidia-ml.so.1 exists).  So, try to
dlopen the .so.1 library if the generic .so dlopen fails.  In either case, if
libnvidia-ml doesn't exist, but the CUDA shared libraries do, skip trying to
use the NVML routines for getting the device count and just proceed to using
the CUDA routine.
Signed-off-by: Quincey Koziol <qkoziol@amazon.com>

[v1.19.x] Try libnvidia-ml.so.1 if .so symlink missing, and skip NVML when not available

---

fabtests/functional/unexpected_msg.c

Add the -U option like other tests do to allow transmission with FI_DELIVERY_COMPLETE

fabtests/unexpected_msg.c: Allow running the test with FI_DELIVERY_COMPLETE

---

src/linux/osd.c
src/mem.c

found using ICC -Wformat -Wformat-security -Werror=format-security 
%zu format specifier is for size_t, for signed size_t %i exists. Destination is ssize_t.

src/linux: Fix ssize_t format specifiers

---

fabtests/pytest/conftest.py
fabtests/pytest/efa/test_unexpected_msg.py
fabtests/pytest/shm/shm_common.py
fabtests/pytest/shm/test_unexpected_msg.py
fabtests/scripts/runfabtests.py

This PR contains a series of commits to allow parallel run for shm provider, and extend test_unexpected_msg for shm and efa

fabtests/pytest: Allow parallel run for shm provider, extend test_unexpected_msg for shm and efa

---

src/linux/osd.c
src/mem.c

found using ICC -Wformat -Wformat-security -Werror=format-security %zu format specifier is for size_t, for signed size_t %i exists. destination is ssize_t.
Signed-off-by: Denis Maryin <denis.maryin@intel.com>
(cherry picked from commit b1e045cf2bb84ac877221b0ce3cf6a40d0c75115)

[v1.18.x] src/linux: Fix ssize_t format specifiers

---

src/linux/osd.c
src/mem.c

found using ICC -Wformat -Wformat-security -Werror=format-security %zu format specifier is for size_t, for signed size_t %i exists. destination is ssize_t.
Signed-off-by: Denis Maryin <denis.maryin@intel.com>
(cherry picked from commit b1e045cf2bb84ac877221b0ce3cf6a40d0c75115)

[v1.19.x] src/linux: Fix ssize_t format specifiers

---

contrib/intel/jenkins/Jenkinsfile
contrib/intel/jenkins/common.py
contrib/intel/jenkins/run.py
contrib/intel/jenkins/runtests.py
contrib/intel/jenkins/summary.py
contrib/intel/jenkins/tests.py

This commit adds dmabuf single node tests to the CI.
The DMABUF stage will run 12 single node tests (H->H read,write,send, D->H read,write,send, H->D read,write,send, D->D read,write,send) and takes 50 seconds.
There are three patches:
Add dmabuf test class and ClientServerTest class.
Add dmabuf stage to Jenkinsfile.
Add summary stage to the summary.

contrib/intel/jenkins: Add dmabuf tests to the CI

---

contrib/intel/jenkins/Jenkinsfile
contrib/intel/jenkins/build.py
contrib/intel/jenkins/summary.py
contrib/intel/jenkins/tests.py

Move our dsa testing to the new designated nodes in the main cluster.
Remove code needed for testing on the designated node and enable it in the main cluster.

contrib/intel/jenkins: Migrate dsa from standalone to main cluster

---

prov/verbs/src/verbs_eq.c

Calling `fi_eq_open` with `wait_obj` equal to `FI_WAIT_SET`, `FI_WAIT_MUTEX_COND` or `FI_WAIT_YIELD` for verbs provider causes a memory leak as we don't release all the objects created prior to validating value of `wait_obj`. Instead of just changing a jump to `err3` this PR moves argument validation to be done sooner (similar to other providers).

prov/verbs: Fix memory leak when creating EQ with unsupported wait object

---

include/rdma/providers/fi_peer.h
man/fi_peer.3.md
prov/efa/src/rdm/efa_rdm_msg.c
prov/shm/src/smr_progress.c
prov/sm2/src/sm2_progress.c
prov/util/src/util_srx.c

include/fi_peer, efa, shm, sm2: update peer srx API to allow for peer modification of the rx_entry

---

contrib/intel/jenkins/Jenkinsfile
contrib/intel/jenkins/common.py
contrib/intel/jenkins/run.py
contrib/intel/jenkins/runtests.py
contrib/intel/jenkins/summary.py
contrib/intel/jenkins/tests.py

This commit adds dmabuf single node tests to the CI.
The DMABUF stage will run 12 single node tests (H->H read,write,send, D->H read,write,send, H->D read,write,send, D->D read,write,send) and takes 50 seconds.
There are three patches:
Add dmabuf test class and ClientServerTest class.
Add dmabuf stage to Jenkinsfile.
Add summary stage to the summary.

[v1.19.x] contrib/intel/jenkins: Add dmabuf tests to the CI

---

.gitignore
contrib/intel/jenkins/Jenkinsfile
contrib/intel/jenkins/common.py
contrib/intel/jenkins/run.py
contrib/intel/jenkins/runtests.py
contrib/intel/jenkins/summary.py
contrib/intel/jenkins/tests.py
fabtests/Makefile.am
fabtests/component/dmabuf-rdma/fi-mr-reg-xe.c
fabtests/component/dmabuf-rdma/fi-rdmabw-xe.c
fabtests/component/dmabuf-rdma/memcopy-xe.c
fabtests/component/dmabuf-rdma/mr-reg-xe.c
fabtests/component/dmabuf-rdma/rdmabw-xe.c

There are two commits:
1. fabtests/component: Rename executables to prefix with xe_ or fi_xe_ #9004
This commit is cherry-picked from upstream to support dmabuf CI.
Adding component tests to the gitignore by renaming them to have xe_ or fi_xe_ prefix to follow previous convention.
2. [v1.18.x] contrib/intel/jenkins: Add dmabuf tests to the CI
This commit adds dmabuf single node tests to the CI.
The DMABUF stage will run 12 single node tests (H->H read,write,send, D->H read,write,send, H->D read,write,send, D->D read,write,send) and takes 50 seconds.
There are three patches:
Add dmabuf test class and ClientServerTest class.
Add dmabuf stage to Jenkinsfile.
Add summary stage to the summary.

[v1.18.x] contrib/intel/jenkins: Add dmabuf tests to the CI

---

include/rdma/providers/fi_peer.h
man/fi_peer.3.md
prov/efa/src/rdm/efa_rdm_msg.c
prov/shm/src/smr_progress.c
prov/sm2/src/sm2_progress.c
prov/util/src/util_srx.c

Switch the peer srx API to allow modification of the rx_entry on the unexpected path before queuing it with the owner. The peer is expected to fill in any available fields that may be returned with a subsequent FI_PEEK operation which reports back the size, CQ data, and flags of the operation.
This also updates the efa, shm, and sm2 providers to match the new definition.

[v1.19.x] include/fi_peer: add cq_data to rx_entry, allow peer to modify on unexp

---

prov/ucx/src/ucx_init.c

Fixes intermittent segmentation fault with ucx on cleanup.
UCX requires ft_finalize because it passes in the ft_transmit_complete flag which forces the queue to be flushed. If the queue isn't flushed, it results in a segmentation fault because ucx marks it as still in use.

prov/ucx: Initialize ep_flush to 1

---

fabtests/pytest/efa/test_unexpected_msg.py

unexpected_msg test will allocate msg_size * 2 * msg_count memory for send/recv The limit size of neuron_tensor_alloc is 4GB. Skip the configurations that can hit such limit on neuron.

fabtests/pytest/efa: Skip some configuration for unexp msg test on neuron

---

fabtests/pytest/efa/test_unexpected_msg.py

unexpected_msg test will allocate msg_size * 2 * msg_count memory for send/recv The limit size of neuron_tensor_alloc is 4GB. Skip the configurations that can hit such limit on neuron.
(cherry picked from commit b27a0afccb0aa636733817052a7495bf0b18f5fe)

[v1.19.x] fabtests/pytest/efa: Skip some configuration for unexp msg test on neuron.

---

contrib/intel/jenkins/Jenkinsfile

Imrove readability and understandability of how build.py works. It is now invoked with a full path and uses the dir command to make sure it starts in the same location every time. UCX run stage was also updated to mirror this.
MPI verbs-rxm was split into IMB and OSU stages to improve overall runtime of the pipeline.

contrib/intel/jenkins: Quality of life updates to build and mpi-verbs

---

prov/efa/test/efa_unit_test_cq.c

Currently, test_impl_ibv_cq_ex_read_unknow_peer_ah doesn't increment efa_rdm_ep->efa_rx_pkts_posted before generating the fake recv completion, which will cause an assertion error in efa_rdm_pke_handle_recv_completion() that asserts efa_rdm_ep->efa_rx_pkts_posted > 0.
This patch fixed it.

prov/efa/test: Fix an assertion error.

---

prov/hook/trace/src/hook_trace.c

Add newline to start trace log for fi_ep_attr, fi_rx_attr and fi_tx_attr. This makes the logs in a consistent format for the attributes.

prov/hook/trace: fixed trace log format on some attributes.

---

contrib/intel/jenkins/Jenkinsfile

Imrove readability and understandability of how build.py works. It is now invoked with a full path and uses the dir command to make sure it starts in the same location every time. UCX run stage was also updated to mirror this.
MPI verbs-rxm was split into IMB and OSU stages to improve overall runtime of the pipeline.

[v1.18.x] Pick Quality of life updates to build and mpi-verbs from main

---

contrib/intel/jenkins/Jenkinsfile

Imrove readability and understandability of how build.py works. It is now invoked with a full path and uses the dir command to make sure it starts in the same location every time. UCX run stage was also updated to mirror this.
MPI verbs-rxm was split into IMB and OSU stages to improve overall runtime of the pipeline.

[v1.19.x] Pick Quality of life updates to build and mpi-verbs from main

---

contrib/intel/jenkins/summary.py

Summary.py will fail with no file found if the opt-out stage forced the pipeline to not run. Opening the file in the -x option will fix this and create the file if it doesn't exist.

contrib/intel/jenkins: Fix summary.py file not found error

---

configure.ac
fabtests/configure.ac

This adds convenience flags for enabling [Leak](https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html#index-fsanitize_003dleak), [Thread](https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html#index-fsanitize_003dthread) and [UndefinedBehavior](https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html#index-fsanitize_003dundefined) sanitizers; on top of the already available [AddressSanitizer](https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html#index-fsanitize_003daddress) flag.

configure.ac: Add configure flags for more sanitizers

---

contrib/intel/jenkins/summary.py

Summary.py will fail with no file found if the opt-out stage forced the pipeline to not run. This is because the log_dir isn't created in the opt-out path. Addint a check/make for it if it doesn't exist fixes this.

[v1.18.x] Pick fix for summary.py file not found

---

prov/psm3/src/psmx3_rma.c

in the provider `psm3`, the function `fi_inject_writedata` does not forward the flag `FI_REMOTE_CQ_DATA` to the `write_generic` function, leading to no cq data being actually generated.
Assuming that the function `fi_writedata` is correct, I presume that adding the flag is the right fix

prov/psm3: add missing `FI_REMOTE_CQ_DATA` for `fi_inject_writedata`

---

prov/efa/src/efa_domain.c
prov/efa/src/efa_env.c
prov/efa/src/efa_env.h
prov/efa/src/efa_prov_info.c
prov/efa/src/efa_shm.c
prov/efa/src/rdm/efa_rdm_ep_fiops.c

SM2 is currently not fully functional as SHM provider yet. Rollback to the earlier enable_shm_transfer env to avoid users picking this provider by accident.
This reverts commit 331c616324e8df64a3373090794d25ded2f476cf.

prov/efa: Revert the change of efa intranode provider selection

---

fabtests/prov/efa/src/rdm_rnr_queue_resend.c
fabtests/pytest/efa/test_rnr.py
prov/efa/src/rdm/efa_rdm_ep.h
prov/efa/src/rdm/efa_rdm_ep_fiops.c
prov/efa/src/rdm/efa_rdm_ep_progress.c
prov/efa/src/rdm/efa_rdm_ope.c
prov/efa/src/rdm/efa_rdm_pke.c
prov/efa/src/rdm/efa_rdm_pke.h
prov/efa/src/rdm/efa_rdm_pke_cmd.c
prov/efa/src/rdm/efa_rdm_pke_cmd.h
prov/efa/src/rdm/efa_rdm_pke_nonreq.c
prov/efa/src/rdm/efa_rdm_pke_nonreq.h
prov/efa/test/efa_unit_test_rnr.c

RDMA writedata can return RNR when the receiver is out of rx entries. This commit queues and resends the writedata packets.

prov/efa: Handle RNRs from RDMA writedata 

---

fabtests/pytest/efa/test_efa_protocol_selection.py

Add cuda memory marker to test_transfer_with_read_protocol_cuda so they can collected with other cuda tests in the same group.

fabtests/pytest/efa: add cuda memory marker

---

fabtests/component/dmabuf-rdma/util.c

For cross node tests, under certain conditions, the read() call may return with bytes read less than size, 
causing exchange_info() to return failure.
This fix would ensure that all the expected data are read.
This bug was found while running 2 node fi_xe_rdmabw test on CI.
Changes have been tested and verified both manually and on the CI.

fabtests/component/dmabuf: Handle partial read scenario for fi_xe_rdmabw test

---

prov/efa/src/rdm/efa_rdm_ep_progress.c

rma_ctx_pkt is unused outside the assert(), which will cause a unused variable warning when building without --enable-debug. This patch fixes it.

prov/efa: Fix a compilation warning

---

fabtests/prov/efa/src/rdm_rnr_queue_resend.c
fabtests/pytest/efa/test_rnr.py
prov/efa/src/rdm/rxr_ep.c
prov/efa/src/rdm/rxr_ep.h
prov/efa/src/rdm/rxr_op_entry.c
prov/efa/src/rdm/rxr_pkt_cmd.c
prov/efa/src/rdm/rxr_pkt_cmd.h
prov/efa/src/rdm/rxr_pkt_entry.c
prov/efa/src/rdm/rxr_pkt_entry.h
prov/efa/src/rdm/rxr_pkt_type.h
prov/efa/src/rdm/rxr_pkt_type_misc.c
prov/efa/src/rdm/rxr_rma.c

Re-implementation of the changes in https://github.com/ofiwg/libfabric/pull/9276 for 1.18.x branch

[v1.18.x] prov/efa: Handle RNRs from RDMA writedata

---

fabtests/pytest/efa/test_efa_protocol_selection.py

Add cuda memory marker to test_transfer_with_read_protocol_cuda so they can collected with other cuda tests in the same group.
(cherry picked from commit 0f6a9653ef6c1c2514a3f50b4700767eb22a9d6e)

[v1.19.x] fabtests/pytest/efa: add cuda memory marker

---

fabtests/pytest/efa/test_efa_protocol_selection.py

Add cuda memory marker to test_transfer_with_read_protocol_cuda so they can collected with other cuda tests in the same group.
(cherry picked from commit 0f6a9653ef6c1c2514a3f50b4700767eb22a9d6e)

[v1.18.x] fabtests/pytest/efa: add cuda memory marker

---

fabtests/component/dmabuf-rdma/util.c

For cross node tests, under certain conditions, the read() call may return with bytes read less than size, 
causing exchange_info() to return failure.
This fix would ensure that all the expected data are read.
This bug was found while running 2 node fi_xe_rdmabw test on CI.
Changes have been tested and verified both manually and on the CI.
This commit needs to be cherry-picked for v1.19.x for CI to work on this branch.
(cherry picked from commit 9e4fdbf)

[v1.19.x] fabtests/component/dmabuf: Handle partial read scenario for  fi_xe_rdmabw test

---

fabtests/component/dmabuf-rdma/util.c

For cross node tests, under certain conditions, the read() call may return with bytes read less than size,
causing exchange_info() to return failure.
This fix would ensure that all the expected data are read.
This bug was found while running 2 node fi_xe_rdmabw test on CI.
Changes have been tested and verified both manually and on the CI.
This commit needs to be cherry-picked for v1.18.x for CI to work on this branch.
(cherry picked from commit 9e4fdbf)

[v1.18.x] fabtests/component/dmabuf: Handle partial read scenario for fi_xe_rdmabw test

---

prov/efa/src/rdm/efa_rdm_ep_progress.c

rma_ctx_pkt is unused outside the assert(), which will cause a unused variable warning when building without --enable-debug. This patch fixes it.
(cherry picked from commit 665f9523dcaf68b57c752c9ff2358e89a76d6c4b)

[v1.19.x] prov/efa: Fix a compilation warning

---

contrib/intel/jenkins/Jenkinsfile

This commit adds two node dmabuf tests to CI.

[v1.18.x] contrib/intel/jenkins: Add two node dmabuf tests to CI

---

contrib/intel/jenkins/Jenkinsfile

The output variable was getting re-written with another log file in the CI.
This commit fixes that error.

contrib/intel/jenkins: Fix logfile variable for dmabuf stage

---

contrib/intel/jenkins/Jenkinsfile

This commit adds two node dmabuf tests to CI.

[v1.19.x] contrib/intel/jenkins: Add two node dmabuf tests to CI

---

configure.ac

This allows building with LTTng-UST without needing to specify an installation prefix (i.e. installed to a default location). Otherwise, you end up invoking the compiler with something like `-Iyes/include` and `-Lyes/lib64`.

configure.ac: Prevent `--with-lttng` from populating `{CPP,LD}FLAGS` with `yes/...` by default

---

contrib/intel/jenkins/summary.py

mpi-tcp OSU & mpichtestsuite still looks for tcp-rxm instead of tcp. Adding tcp to the list will let it find the new test file.

contrib/intel/jenkins: Fix mpi-tcp summary filenames

---

prov/verbs/src/windows/verbs_nd_rdma.c

When fi_listen is called while another passive endpoint is already bound to the same address, it triggers an error, leading to the immediate release of the IND2Listener object. Subsequently, when fi_close is called, it attempts to free the already-released object, causing a use-after-free issue.

prov/verbs_nd: Fix use-after-free in case of failure in fi_listen

---

contrib/intel/jenkins/summary.py

mpi-tcp OSU & mpichtestsuite still looks for tcp-rxm instead of tcp. Adding tcp to the list will let it find the new test file.

[v1.19.x] contrib/intel/jenkins: Pick fix mpi-tcp summary filenames

---

contrib/intel/jenkins/summary.py

mpi-tcp OSU & mpichtestsuite still looks for tcp-rxm instead of tcp. Adding tcp to the list will let it find the new test file.

[v1.18.x] contrib/intel/jenkins: Pick fix mpi-tcp summary filenames

---

prov/efa/src/efa_prov.c

Currently, efa_env_initialize() is called after
efa_util_prov_initialize(). However, efa_util_prov_initialize() uses efa_env to determine the tx/rx size in info.tx/rx_attr which doesn't work because of the calling sequence issue.
This patch fixes this issue by making efa_env_initialize() called before efa_util_prov_initialize().

prov/efa: Fix the efa_env_initialize() call sequence.

---

configure.ac

Cherry-picked from 748bc600389dcb579c85a4e5a78ce647e0defafc

[v1.19.x] configure.ac: Fix `with_synaposeai` typo

---

.github/workflows/pr-ci.yml

This simply installs liblttng-ust-dev in the Actions runner and configures Libfabric with LTTng-UST to ensure tracepoints aren't being broken (currently only affects the EFA provider). The added runtime looks to be minimal/negligible - I ran the build checks several times during testing.
Testing:
- Happy run: https://github.com/darrylabbate/libfabric/actions/runs/6150157381
- Dummy failed run: https://github.com/darrylabbate/libfabric/actions/runs/6150190774
This PR also includes a commit to disambiguate build artifacts (`config.log`) that are uploaded for failed builds.

ci: Ensure LTTng tracepoint correctness in build test

---

prov/efa/src/efa_cntr.c
prov/efa/src/efa_cntr.h

Currently, efa_cntr_wait call cntr->progress, which finally call efa_ep_progress_internal(). However,
efa_ep_progress_internal() must be called inside the srx->lock. This patch fixes this issue.

prov/efa: Add missing locks in efa_cntr_wait.

---

configure.ac

Cherry-picked from 748bc600389dcb579c85a4e5a78ce647e0defafc

[v1.18.x] configure.ac: Fix `with_synaposeai` typo

---

prov/efa/src/efa_cntr.c
prov/efa/src/efa_cntr.h

Backport https://github.com/ofiwg/libfabric/pull/9318 to v1.19.x

[v1.19.x] prov/efa: Add missing locks in efa_cntr_wait.

---

prov/efa/src/efa_domain.c

This patch fixes a bug in EFA device name matching logic, which only accounts for the first prefix match. As a result, efa_10-rdm domain name is matched with efa_1 device instead of efa_10.
(cherry picked from commit 9961ccf2336d1f354f102f1c9b2c3a1305a7db6c)

[v1.18.x] Backport prov/efa: fix efa device name matching

---

prov/shm/src/smr_progress.c

Currently, smr_progress_cmd still uses
ofi_ep_rx_cntr_inc_func to increment rx cntrs.
It should be replaced to ofi_ep_peer_rx_cntr_inc
to onboard peer cntr API as other cntr ops inside
shm.

prov/shm: Use peer cntr inc ops in smr_progress_cmd

---

prov/util/src/util_mr_cache.c

On Windows, where `HAVE_MEMHOOKS_MONITOR` is undefined `ofi_monitors_add_cache` fails with `FI_ENOSYS`. Consequently, it doesn't invoke `ofi_bufpool_create` function, which results in the `cache->entry_pool` being set to `NULL`. Subsequently, when `ofi_bufpool_destroy` is called with a `NULL` pointer it dereferences a null pointer.

prov/util: Avoid attempting to destroy an uninitialized cache entry pool

---

prov/shm/src/smr_rma.c

Currently, smr_generic_rma_inject still increments tx cntr when smr_rma_fast returns a non-zero, which is wrong.
This patch fixes this bug.

prov/shm: only increment tx cntr when inject rma succeeded.

---

prov/shm/src/smr_rma.c

Currently, smr_generic_rma_inject still increments tx cntr when smr_rma_fast returns a non-zero, which is wrong.
This patch fixes this bug.
(cherry picked from commit a80b72472cbc4ef9677453727979db4ee196498b)

[v1.19.x] prov/shm: only increment tx cntr when inject rma succeeded.

---

prov/shm/src/smr_progress.c

Currently, smr_progress_cmd still uses
ofi_ep_rx_cntr_inc_func to increment rx cntrs.
It should be replaced to ofi_ep_peer_rx_cntr_inc
to onboard peer cntr API as other cntr ops inside
shm.
(cherry picked from commit 41b223303c9ba0a278f80c16d2de6972f82ba113)

[v1.19.x] prov/shm: Use peer cntr inc ops in smr_progress_cmd

---

contrib/intel/jenkins/Jenkinsfile

This commit adds two env vars to verbs;ofi_rxd stage: FI_MR_CACHE_MAX_COUNT=0 and FI_MR_CACHE_MONITOR=userfaultfd.
Verbs ofi_rxm stage has two new env vars:
FI_MR_CACHE_MAX_COUNT=0 and FI_MR_CACHE_MONITOR=userfaultfd. The third env var FI_OFI_RXM_USE_SRX=true resulted in assertion failure and core dump. Issue #9336 has been opened for that and it will be added to verbs;ofi_rxm stage after issue has been fixed.
This commit is a fix for issue #7304

contrib/intel/jenkins: Add testing for different key environment variables

---

contrib/intel/jenkins/Jenkinsfile
contrib/intel/jenkins/build.py
contrib/intel/jenkins/run.py
contrib/intel/jenkins/runtests.py
contrib/intel/jenkins/summary.py
contrib/intel/jenkins/tests.py

Add code changes to enable the all tests from the mpich test suite with impi and mpich.
- test.py: class MpichtestSuite modified to build and run PR tests as well as weekly tests (impi & mpich). added functions to process exclude list.
- build.py: options and functions added for extracting mpich tar files. Also added libfabric_mpich option to build libfabric with options exclusive for mpich (-without-ze)
- run.py: changes to calls made to build and execute tests based on MpichTestSuite class.
- summary.py: summary functions modified to create summary based on new log file.
- Jenkinsfile: added prepare build stage; added parallel build stage for libfabric_mpich; increased jenkins timeout limit for weekly tests. Running tests for tcp and verbs-rxm.

intel/ci: Enable-Mpichtestsuite PR and weekly 

---

fabtests/include/unix/osd.h

Fixes #9306
Add missing include to osd.h for socket calls.

fabtests/macos: Fix build error with clang

---

prov/shm/configure.m4

When the shm provider fails to configure, there is no helpful output to let the user know what check failed. This adds some helpful messages.

prov/shm: add more error output

---

man/fi_tagged.3.md

Currently, no providers support returning message data for peek operations. It also has a contradiction on the usage of cq_entry's buf field with fi_cq man page. The latter one says the buf field only applies when the receive buffer was posted with the FI_MULTI_RECV flag.
Remove this paragraph to avoid confusion.

man/fi_tagged: Remove the peek for data ability

---

contrib/intel/jenkins/Jenkinsfile
contrib/intel/jenkins/common.py
contrib/intel/jenkins/runtests.py
contrib/intel/jenkins/summary.py

Fast forwarding the summary to the start of test output. This will eliminate false positives where a user could put a keyword in their title to get the summary to think its something to pay attention to when it actually is just the title.

contrib/intel/jenkins: Add summary fast forward

---

include/ofi_net.h
prov/tcp/src/xnet_progress.c
src/common.c

This patch disables the endpoint if zero-copy reports an error. The goal is to prevent the stream to be corrupted if zero-copy gets disabled after the transfer has started.
Fixes #7887

prov/xnet,common: Disable the EP if an error is detected for zero-copy

---

prov/ucx/src/ucx_init.c

ep_flush needs to initialize to 1 so that the send queue gets flushed by default on ep_close. If it isn't flushed then there is a chance of segmentation faulting when the address handle gets destroyed.

[v1.18.x] prov/ucx: Pick Initialize ep_flush to 1

---

prov/ucx/src/ucx_init.c

ep_flush needs to initialize to 1 so that the send queue gets flushed by default on ep_close. If it isn't flushed then there is a chance of segmentation faulting when the address handle gets destroyed.

[v1.19.x] prov/ucx: Pick Initialize ep_flush to 1

---

include/ofi_util.h
prov/rxd/src/rxd_cntr.c
prov/rxd/src/rxd_cq.c
prov/shm/src/smr_ep.c
prov/sm2/src/sm2_ep.c
prov/udp/src/udpx_ep.c
prov/util/src/rxm_av.c
prov/util/src/util_av.c
prov/util/src/util_cntr.c
prov/util/src/util_cq.c
prov/util/src/util_ep.c
prov/util/src/util_main.c

This change will get rid of unnecessary locking in the common utility code.

prov/util: Switch util_cq, util_av, and util_cntr ep_list_lock to be ofi_genlock

---

contrib/intel/jenkins/Jenkinsfile
contrib/intel/jenkins/build.py
contrib/intel/jenkins/run.py
contrib/intel/jenkins/tests.py

-Moved mpich build from test stage to parallel build stage post libfabric_mpich build stage. 
-excluded idup_nb test from mpichtests for tcp

intel/ci: Changes to build mpich and tcp exclude for mpichsuite

---

fabtests/component/dmabuf-rdma/fi-mr-reg-xe.c
include/rdma/fabric.h
include/rdma/fi_domain.h
man/fi_mr.3.md
prov/verbs/src/verbs_mr.c

This expands the memory registration API to support passing in a DMA-buf region.  DMA buf regions are specified using a struct fi_mr_dmabuf.  The struct fi_mr_attr is updated to accept passing in the dmabuf structure as input, with a flag used to indicate that the registration is for a DMA-buf region.
The verbs provider is updated to support DMA-buf registration.
Changes are compile tested only.  There's no test yet available to verify functionality.

core/verbs: Add native API support for DMA-buf regions

---

prov/efa/docs/efa_rdm_protocol_v4.md
prov/efa/src/rdm/efa_rdm_msg.c
prov/efa/src/rdm/efa_rdm_peer.h
prov/efa/src/rdm/efa_rdm_pke_nonreq.c
prov/efa/src/rdm/efa_rdm_pke_nonreq.h
prov/efa/src/rdm/efa_rdm_protocol.h
prov/efa/src/rdm/efa_rdm_rma.c
prov/efa/test/efa_unit_test_common.c
prov/efa/test/efa_unit_test_ep.c
prov/efa/test/efa_unit_tests.h

This simply adds the "device version" (`ibv_device_attr.vendor_part_id`) to the handshake subprotocol; storing it in the `efa_rdm_peer` struct upon recv. This is then used during RDM protocol selection; ensuring the devices can interoperate before selecting RDMA read.
Currently, the only known incompatibility is between the oldest device versions (`0xEFA0`) and newer ones (`0xEFA1`, `0xEFA2`).
This was tested by running `fi_pingpong` with various EC2 instance types and checking the `rdma_read_bytes` hardware counters before/after.
I'll write unit tests in the meantime, but this can be merged if the feature is considered urgent enough.
Side note: the replacement of license text with SPDX identifiers in file headers was [blessed by …

prov/efa: Disallow RDMA read between incompatible EFA devices

---

prov/efa/src/efa_mr.c

The proprietary SHM MR keygen logic was removed in 773ad4345. This commit removes the leftover macro and assigns the value to the initial CUDA MR keygen value.

prov/efa: Remove unused SHM MR keygen value

---

prov/efa/src/efa_mr.c

If an applications calls fi_mr_reg with an incomplete attr, a segfault could occur

prov/efa: Fix coverity warning in efa_mr_reg_impl

---

prov/shm/src/smr_progress.c

In smr_progress_cmd_atomic, resp is updated after calling smr_progress_inline/inject_atomic, which involves a memcpy in smr_do_atmoic for compare and fetch cases. Currently, there is no memory barrier between the memcpy and the resp update, this can make resp updated before the memcpy is done on ARM, which has a weak memory model. This patch adds a memory barrier before updating the resp to make the operations serialized.

prov/shm: Add memory barrier before updating resp for atomic

---

prov/efa/src/efa_domain.c
prov/efa/src/efa_env.c

When the user sets FI_EFA_ENABLE_SHM_TRANSFER=0, do not create a SHM endpoint.  The current behavior is that we just don't send via SHM when one sets FI_EFA_ENABLE_SHM_TRANSFER=0, but we still create and poll the peer endpoint.  New behavior is to not create SHM endpoint when peer is disabled.

prov/efa: Do not create SHM endpoint when SHM is disabled

---

prov/shm/src/smr_progress.c

Backport the bug fix in https://github.com/ofiwg/libfabric/pull/9370

[v1.19.x] prov/shm: Add memory barrier before updating resp for atomic

---

prov/efa/src/efa_domain.c
prov/efa/src/efa_env.c

When the user sets FI_EFA_ENABLE_SHM_TRANSFER=0, do not create a SHM endpoint.  The current behavior is that we just don't send via SHM when one sets FI_EFA_ENABLE_SHM_TRANSFER=0, but we still create and poll the peer endpoint.  New behavior is to not create SHM endpoint when peer is disabled.
(cherry picked from commit 6b62f34ea40303b878f12a4d16f2160f52dd86b8)

[v1.19.x] prov/efa: Do not create SHM peer when SHM is disabled

---

prov/util/src/util_mem_monitor.c

This is especially needed on Windows where `PTHREAD_MUTEX_INITIALIZER` is not enough and explicit initialization via call to `pthread_mutex_init`/`InitializeCriticalSection` is required before using a mutex.

prov/util: Add missing calls to (de)initialize monitor's mutexes

---

prov/verbs/src/windows/verbs_nd_ov.c

Currently, the verbs provider on Windows always generates an error event for rejected connections without associated error data.

prov/verbs_nd: Fetch rejected connection data

---

prov/util/src/util_av.c
prov/util/src/util_cq.c
prov/util/src/util_ep.c

Switch ep_list_lock to always be a mutex lock until we can agree on a better long term decision. The issue is that some endpoints want the ability to not require FI_THREAD_SAFE at the domain level, but they want to be able to control the endpoint in a seperate thread.  The ep_list_lock is used for both the data path, and the control path.  In order to adhere to the current api, and not break providers that follow the current api, we need to revert this lock to a mutex until we can get a optimal solution for everyone.

prov/util: Switch ep_list_lock to always be mutex

---

prov/efa/src/rdm/efa_rdm_ep_progress.c

This change contains 2 fixes:
1. Payload length should be written to completion.
2. Immediate data and payload length are 32-bit integers from rdma-core and should be converted to 64-bit as per libfabric API.

prov/efa: RDMA write with immediate data completion bugfix

---

prov/efa/src/rdm/efa_rdm_ep_progress.c

This change contains 2 fixes:
1. Payload length should be written to completion.
2. Immediate data should be passed as unsigned integer.
(cherry picked from commit 35060d94e895659f6c3179ce1ade961d7dcbe7d8)

[v1.19.x] prov/efa: RDMA write with immediate data completion bugfix

---

fabtests/functional/cq_data.c

The provider only supports cq_data_size bytes of CQ data, thus the test can only reliably verify the last cq_data_size*8 bits.

fabtests/cq_data: relax CQ data validation to cq_data_size

---

fabtests/common/shared.c
fabtests/include/shared.h
prov/sockets/src/sock_ep.c

This commit adds validation that the fi_info returned with an FI_CONNREQ
event is filled out properly with valid fields. The fi_info should be
similar to the fi_info that is used to open passive endpoint.

fabtests/shared.c: Check if fi_info is returned correctly in case of FI_CONNREQ

---

contrib/intel/jenkins/Jenkinsfile
contrib/intel/jenkins/build.py
contrib/intel/jenkins/common.py
contrib/intel/jenkins/summary.py
contrib/intel/jenkins/tests.py

Change mpi list to be local to stages. This will eliminate all the ompi tests that just get skipped anyways from clogging the pipeline queue and preventing jobs from finishing while there is heavy testing occuring.
The failing imb tests IMB-EXT Accumulate and IMB-RMA All_put_all tests are being disabled in our CI since they are not part of the IMPI team's validation of the IMB tests.
UCX provider is now being required to build on a compute node due to environment issues that were causing the fi_rdm_tagged_peek test to fail.

contrib/intel/jenkins: Fix Failing UCX & IMB tests

---

contrib/intel/jenkins/tests.py

Adding the cloudbees log start string to the daos log will ensure that the daos summarizer doesn't fast forward through the entire test file. This will make the output files look more like all of the other outputs.

contrib/intel/jenkins: Add cloudbees start string to daos log

---

contrib/intel/jenkins/tests.py

Adding the cloudbees log start string to the daos log will ensure that the daos summarizer doesn't fast forward through the entire test file. This will make the output files look more like all of the other outputs.

[v1.18.x] contrib/intel/jenkins: Pick add cloudbees start string to daos log

---

contrib/intel/jenkins/tests.py

Adding the cloudbees log start string to the daos log will ensure that the daos summarizer doesn't fast forward through the entire test file. This will make the output files look more like all of the other outputs.

[v1.19.x] contrib/intel/jenkins: Pick add cloudbees start string to daos log

---

src/hmem_ze.c

The uint64_t device was updated to include the device and driver indices. The index is isolated using the ze_get_device_idx function which masks the driver bits. The cmd_queue used in the copy function was using the full device rather than just the dev_id

[v1.18.x] src/hmem_ze: fix incorrect device id in copy function

---

include/freebsd/osd.h
include/linux/osd.h
include/ofi_hmem.h
include/osx/osd.h
include/windows/osd.h
prov/hook/dmabuf_peer_mem/src/hook_dmabuf_peer_mem.c
prov/hook/hook_hmem/src/hook_hmem.c
prov/shm/src/smr_ep.c
prov/verbs/src/verbs_mr.c
src/hmem.c
src/hmem_cuda.c
src/hmem_rocr.c
src/hmem_ze.c
src/linux/osd.c

Implementation uses the same approach libibverbs does to expand memory region: https://github.com/linux-rdma/rdma-core/blob/master/libibverbs/memory.c

Support ofi_hmem_get_base_addr() with FI_HMEM_SYSTEM

---

src/hmem_ze.c

The uint64_t device was updated to include the device and driver indices. The index is isolated using the ze_get_device_idx function which masks the driver bits. The cmd_queue used in the copy function was using the full device rather than just the dev_id

[v1.19.x] src/hmem_ze: fix incorrect device id in copy function

---

prov/tcp/src/xnet_ep.c
prov/tcp/src/xnet_progress.c

We are hitting an issue where the following assertion fails in
xnet_queue_recv(): assert(!dlist_empty(&ep->unexp_entry));
In GDB, the endpoint state is XNET_DISCONNECTED, but ep->cur_rx
seems to indicate that the endpoint has received a header:
```
(gdb) print ep->cur_rx
[...]
hdr_len = 24,
hdr_done = 24,
data_left = 528,
entry = 0x0,
handler = 0xfffff26bba00 <xnet_op_msg>,
claim_ctx = 0x0
```
ep->cur_rx is supposed to be reset by xnet_reset_rx() when the
endpoint is marked as disconnected in xnet_ep_{disable,close}().
The GDB output above clearly shows the evidence that xnet_progress_rx()
was called after the endpoint was disconnected, which is not supposed
to happen.
The only function that may call xnet_progress_rx() after the
endpoint is disconnected is xnet_queue_recv(), when …

prov/xnet: Reset ep->rx_avail to 0 after RX queue is flushed

---

prov/ucx/src/ucx.h
prov/ucx/src/ucx_domain.c
prov/ucx/src/ucx_init.c

Device memory access is handled by UCX internally. UCX by default uses a memtype cache to speed up identification of where a buffer belongs to. Memory allocator hooks are installed to keep the memtype cache updated.
Not much is needed at the provider level except for adding FI_HMEM to the supported caps. The remaining changes are mostly workarounds for the cases that the memory allocator hooks may not always work as expected and thus the memtype cache may not have the information for the device memory allocation:
* When device memory is registered, check if the allocation is already in the memtype cache. Try updating the cache if the information is missing.
* Enable FI_MR_HMEM mode if the application supports that. This requires all device memory allocation go through the memory …

prov/ucx: Add FI_HMEM support

---

include/ofi_mr.h
include/windows/osd.h
prov/util/src/util_mem_hooks.c
src/fabric.c

If the parent process forks, memhooks could be installed in the child process. If the fork occurred with the MR cache locked and the child memhooks intercepts fire, the child process would deadlock.
Add a pthread_atfork() handler to clear memhooks in the child process.
Note: RDMA is NOT supported in the child process.

core: Implement memhooks atfork child handler

---

contrib/intel/jenkins/Jenkinsfile
contrib/intel/jenkins/build.py
contrib/intel/jenkins/run.py
contrib/intel/jenkins/runtests.py
contrib/intel/jenkins/summary.py
contrib/intel/jenkins/tests.py

Making jobs checkout their own ci resources will make it so they depend on less static things on each cluster. This will make jobs more portable between clusters and will make development work easier.
Move skip and release scripts into jenkinsfile to reduce the number of external files needed.

contrib/intel/jenkins: Make jobs checkout their own ci resources

---

contrib/intel/jenkins/Jenkinsfile
contrib/intel/jenkins/build.py
contrib/intel/jenkins/run.py
contrib/intel/jenkins/runtests.py
contrib/intel/jenkins/summary.py
contrib/intel/jenkins/tests.py

Making jobs checkout their resources will make it so they depend on less static things on each cluster. This will make jobs more portable between clusters and will make development work easier.
Move skip and release scripts into jenkinsfile to reduce the number of external files needed.

[v1.19.x] contrib/intel/jenkins: Pick make jobs checkout their resources

---

contrib/intel/jenkins/Jenkinsfile
contrib/intel/jenkins/build.py
contrib/intel/jenkins/run.py
contrib/intel/jenkins/runtests.py
contrib/intel/jenkins/summary.py
contrib/intel/jenkins/tests.py

Pick CI using its own ci_resources for a job. This will remove the dependency on the local checkout.

[v1.18.x] contrib/intel/jenkins: Pick CI using own resources for job

---

fabtests/component/dmabuf-rdma/fi-rdmabw-xe.c
fabtests/component/dmabuf-rdma/rdmabw-xe.c

We have already seen the need for testing 8-NICs. Increase the limit from 4 to 32 to leave room for future expansion.

fabtests/dmabuf-rdma: Increase the number of NICs that can be tested

---

fabtests/component/dmabuf-rdma/memcopy-xe.c

Previously MAP_PRIVATE was used to map the device buffer for CPU access. It used to work but with the latest Intel GPU driver update the caller would see its own COW pages instead of the device memory. As a result, the data verification at the end of the test would fail.
Changing the map type to MAP_SHARED fixes the issue. It should also work with older drivers.

fabtests/memcopy-xe: Fix data verification error for device buffer

---

include/ofi_mem.h
prov/util/src/util_buf.c

With debug enabled, only return buffers pointers for allocated buffers. This requires additional bounds checking and tracking of allocated buffers.

util/buf: Add bounds checks to ibuf get

---

prov/tcp/src/xnet.h
prov/tcp/src/xnet_cq.c
prov/tcp/src/xnet_progress.c
prov/tcp/src/xnet_srx.c

When FI_MULTI_RECV is enabled for an RX buffer, the last completed slice of the RX buffer should have FI_MULTI_RECV set in the corresponding CQE.
Currently TCP provider assumes the last slice of the RX buffer will get completed last and sets FI_MULTI_RECV flag when the last slice is used.  Completions can get out of order with multiple connections and varied payload sizes using the same RX buffer.  Last slice will not always complete last.
To make sure the last completed RX buffer slice has FI_MULTI_RECV set in the CQE, use a reference counter to track outstanding slices.  Count is initialized to 1 when the RX buffer is first posted and incrememted on every slice allocation.  Upon completion, count is decremented.  When it reaches 0, FI_MULTI_RECV is set for that CQE.

prov/tcp: Set FI_MULTI_RECV for last completed RX slice

---

prov/tcp/src/xnet_progress.c

A recent patch added a check to ensure that ep state is XNET_CONNECTED
when xnet_progress_rx() is called. This new assertion failure has triggered
in one of our tests:
```
10 0x0000fffff15e3fd0 in __assert_fail_base (fmt=0xfffff16fd3c8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0xfffff5820860 "ep->state == XNET_CONNECTED",
file=file@entry=0xfffff581fda0 "prov/tcp/src/xnet_progress.c", line=line@entry=985, function=function@entry=0xfffff5821d80 <__PRETTY_FUNCTION__.30> "xnet_progress_rx") at ./assert/assert.c:92
11 0x0000fffff15e4040 in __GI___assert_fail (assertion=0xfffff5820860 "ep->state == XNET_CONNECTED", file=0xfffff581fda0 "prov/tcp/src/xnet_progress.c", line=985,
function=0xfffff5821d80 <__PRETTY_FUNCTION__.30> "xnet_progress_rx") at …
```

prov/xnet: Do not progress ep that is disconnected

---

src/hmem_ze.c

Update ze_hmem_is_addr_valid() to set the FI_HMEM_HOST_ALLOC based on ze mem type.

hmem: Set FI_HMEM_HOST_ALLOC for ze addr valid

---

prov/shm/src/smr_progress.c

Currently, we always copy the entire command message of 256 bytes on the unexpected path. For inline, we only need the header (sizeof(struct smr_msg_hdr): 64) + size.  For inject, we only need the header.  SAR, IOV, and IPC use the data field in the message, so we continue to copy the entire command message for them (for large message sizes, optimization is less important).

prov/shm: Only copy header + msg on unexpected path

---

fabtests/component/dmabuf-rdma/fi-mr-reg-xe.c
include/rdma/fi_domain.h
man/fi_mr.3.md
prov/verbs/src/verbs_mr.c

base_addr field can be used to pass in the virtual address of the memory region to be registered

core, fabtests, prov/verbs: Add base_addr to fi_mr_dmabuf

---

include/ofi_abi.h
include/ofi_util.h
include/rdma/fabric.h
include/rdma/fi_eq.h
man/fi_cq.3.md
prov/bgq/src/fi_bgq_cq.c
prov/opx/include/rdma/opx/fi_opx_cq_ops_table.h
prov/psm2/src/psmx2_cq.c
prov/psm3/src/psmx3_cq.c
prov/sockets/src/sock_cq.c
prov/util/src/util_cq.c

fi_cq_err_entry::src_addr can be used by CQ errors to report a source address. How this field will be used to CQ error event specific.

Add fi_cq_err_entry::src_addr

---

prov/efa/src/efa_av.c
prov/efa/src/efa_av.h
prov/efa/src/rdm/efa_rdm_pke_cmd.c

Currently, efa progress engine will call efa_av_insert_one() when it gets a message from unknown peer through efa device. which means peer is not local or shm is disabled for transmission. We shouldn't insert shm av anyway in this case.
Also, calling fi_av_insert internally inside progress engine is violating Libfabric standard for FI_AV_TABLE.

prov/efa: do not insert shm av inside efa progress engine

---

prov/efa/src/efa_av.c
prov/efa/src/efa_av.h
prov/efa/src/rdm/efa_rdm_pke_cmd.c

Currently, efa progress engine will call efa_av_insert_one() when it gets a message from unknown peer through efa device. which means peer is not local or shm is disabled for transmission. We shouldn't insert shm av anyway in this case.
Also, calling fi_av_insert internally inside progress engine is violating Libfabric standard for FI_AV_TABLE.
(cherry picked from commit c68c5b3c94f3ced1b53fb98a49ba340a0dfb069d)

[v1.19.x] prov/efa: do not insert shm av inside efa progress engine

---

include/ofi.h

This enables providers to implement their own fid_nic while uses common functions.

util: Add NIC FID functions to ofi.h

---

include/ofi_mr.h

This can be used by providers to store flags, such as FI_HMEM_HOST_ALLOC or FI_HMEM_DEVICE_ONLY, with the MR.

mr_cache: Define ofi_mr_info::flags

---

man/fi_efa.7.md
prov/efa/src/efa_env.c
prov/efa/src/efa_env.h
prov/efa/src/efa_mr.c
prov/efa/src/efa_mr.h
prov/efa/src/rdm/efa_rdm_atomic.c
prov/efa/src/rdm/efa_rdm_ep.h
prov/efa/src/rdm/efa_rdm_msg.c
prov/efa/src/rdm/efa_rdm_rma.c

Remove CUDA sync memops from memory registration path, and make it the user's responsiblity to set the flag if required. Also remove env variable FI_EFA_SET_CUDA_SYNC_MEMOPS from EFA. Adds efa_rdm_attempt_to_sync_memops() EFA RDM endpoint for msg, rma, and atomic protocols.
(cherry picked from commit bc6c52c1fab40b077ce5381638fe86ff4831a83a)

[v1.19.x] prov/efa: Move cuda-sync-memops from MR to EP

---

prov/efa/src/efa_hmem.c

The RUNTINREAD protocol was showing a performance regression on Neuron devices. Switch to always use LONGREAD for Neuron.

prov/efa: Always use LONGREAD for Neuron

---

prov/efa/src/efa_hmem.c

We noticed a performance regression for runting read + neuron so we are choosing to disable it in order to resolve regression.
(cherry picked from commit 56b22865ffc39015cf6cbf54f2888a0e0855f683)

[v1.19.x] prov/efa: Disable RUNTING for Neuron

---

prov/efa/src/efa_domain.c
prov/efa/src/rdm/efa_rdm_atomic.c
prov/efa/src/rdm/efa_rdm_cq.c
prov/efa/src/rdm/efa_rdm_ep.h
prov/efa/src/rdm/efa_rdm_ep_fiops.c
prov/efa/src/rdm/efa_rdm_msg.c
prov/efa/src/rdm/efa_rdm_rma.c
prov/efa/test/efa_unit_test_cq.c
prov/efa/test/efa_unit_test_ep.c
prov/efa/test/efa_unit_test_rnr.c

When shm is disabled during ep enable, we should shut down shm resources as they will never be used. This will reduce unnecessary cost when poking shm ep/cq/av in the later operations.

prov/efa: close shm resource when it is disabled in ep 

---

prov/efa/src/dgram/efa_dgram_ep.h
prov/efa/src/efa_base_ep.c
prov/efa/src/efa_base_ep.h
prov/efa/src/rdm/efa_rdm_ep.h
prov/efa/src/rdm/efa_rdm_ep_fiops.c
prov/efa/src/rdm/efa_rdm_ep_progress.c
prov/efa/src/rdm/efa_rdm_pke.c

Currently, efa_rdm_pke_recvv and efa_rdm_ep_bulk_post_internal_rx_pkts allocate pke_vec, recv_wr_vec, sge_vec from stack inside the function. This patch moves these allocation to heap during ep's creation.

prov/efa: allocate pke_vec, recv_wr_vec, sge_vec from heap

---

include/ofi_hmem.h
prov/efa/src/efa_mr.c
src/hmem_cuda.c
src/hmem_cuda_gdrcopy.c

cuda_gdrcopy_dev_register just needs the iov from the mr_attr as input. This can also remove the extra translation in cuda_dev_register.

hmem/cuda and prov/efa: update cuda_gdrcopy_dev_register's signature
