ofiwg/libfabric

- contrib/intel/jenkins/tests.py
- prov/tcp/src/xnet.h
- prov/tcp/src/xnet_msg.c
- prov/tcp/src/xnet_rdm_cm.c
- prov/tcp/src/xnet_rma.c
This PR makes 3 changes:
1. setting of FI_COMPLETION flags for data transfer interfaces(sends and rmas) by combining it with default  settings for the msg flags and op flags
2. Inheriting tx rx flags set during msg endpoint creation from the corresponding rdm endpoint when connection is being created.  For example, if the application requested selective completion then the corresponding msg endpoint is created with the same settings. 
3. re-enables mpichsuite rma tests into Intel CI for tcp provider.
> prov/tcp: Correct setting of completion flags 

- prov/util/src/util_cntr.c
- prov/util/src/util_ep.c
I mistakenly reverted the wrong lock on #9377, and caused a performance regression.  This change makes the ep->lock be domain dependent, and properly reverts util_cntr ep_list_lock to always be mutex.  This restores most of the performance regression.
> prov/util: Fix revert PR #9377 to revert correct lock

- include/ofi_hmem.h
- prov/efa/src/efa_hmem.c
- prov/efa/src/efa_mr.c
- prov/verbs/src/verbs_mr.c
- src/hmem.c
- src/hmem_neuron.c
- src/hmem_synapseai.c
- src/hmem_ze.c
Now that we have multiple ifaces that support dmabuf, it makes sense to have a common method to retrieve the fd associated with the dmabuf object.
> hmem: Add new op to hmem_ops for getting dmabuf fd

- include/ofi_abi.h
- include/rdma/fabric.h
- libfabric.map.in
- man/fabric.7.md
- man/fi_domain.3.md
- prov/util/src/util_attr.c
- src/abi_1_0.c
- src/fabric.c
- src/log.c
Since both of this changes require ABI updates, I decided to include them in the same PR. If it is easier to have these changes in separate PRs, I can separate it out.
Update: the optional_caps changes have been removed.
> Support for max_ep_auth_key

- include/ofi_util.h
- prov/psm3/src/psmx3_cq.c
- prov/util/src/util_cq.c
- prov/util/src/util_srx.c
The CXI provider uses the util CQ code. When implementing FI_SOURCE_ERR, it was discovered that the util CQ code does not properly support err_data. This PR updates/fixes the util CQ code to support this..
> Update util CQ code to support err_data

- contrib/intel/jenkins/tests.py
This particular rma test fails sometimes and
is currently under investigation. 
Temporarily being disabled from CI to prevent
unrelated PRs to be flagged as  failures.
> intel/ci: disable rma/win_shared_put_flush_load test from mpich suite

- include/ofi_mr.h
- prov/efa/src/efa_hmem.h
- prov/efa/src/efa_mr.c
- prov/efa/src/rdm/efa_rdm_pke_utils.c
- prov/shm/src/smr_ep.c
- src/hmem.c
- src/hmem_cuda.c
remove cuda-specific naming and functions when using `ofi_hmem_dev_reg_*` function family
> hmem: remove cuda-specific functions when using `ofi_hmem_dev_reg_*`

- configure.ac
- include/windows/config.h
- src/fabric.c
- src/hmem.c
This commit introduces a new flag, --enable-restricted-dl. By default, restricted_dl is false, which continues the existing behavior of fi_getinfo. The current behavior of fi_getinfo causes the library to probe all paths in LD_LIBRARY_PATH for all possible provider implementations known by ofi_ordered_provs_init, or in cases where FI_PROVIDER_PATH is defined, a search along a colon-delimited set of paths for any library named lib*-fi.so. A side-effect of the non-FI_PROVIDER_PATH option is that a vast majority of the providers in the ofi_ordered_provs_init list, ordered_prov_names, will not exist on most systems. Usually a small subset of the providers exist, and the rest will not be present. A significant number of metadata fetches to the network filesystem will fail to find the desired …
> core: Add restricted dlopen flag to configure options

- src/hmem_synapseai.c
Synapseai currently initializes successfully if libraries are installed. Make synapseai only claim to be initialized if libraries are installed and a device exists.
> src/hmem: Only initalize synapseai if device exists

- include/windows/config.h
The #define HAVE_EFA 0 line breaks the DHAVE_EFA
option passed to windows build. This patch wraps
this definition with #ifndef to fix this issue.
> include/windows/config.h: fix efa windows build

- prov/rxm/src/rxm_msg.c
- prov/verbs/src/verbs_mr.c
The following changes were made to enable Gaudi-direct support over libfabric verbs provider, to allow peer-to-peer communication using dmabuf mr. They are applicble to device memory with iface value of FI_HMEM_SYNAPSEAI:
* Use dmabuf hmem registration function with synapseai.
* Use rndv protocol for rxm msg send to avoid copy between host and device memory.
> prov/verbs: Add synapseai dmabuf mr support

- contrib/intel/jenkins/Jenkinsfile
The Mudkip partition is being moved to a different cluster. The new Pikachu node will be used instead of the Mudkip ones for DSA tests.
> contrib/intel/jenkins: Switch dsa node to pikachu partition

- libfabric.vcxproj
- libfabric.vcxproj.filters
- prov/rxm/Makefile.include
- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_cq.c
- prov/rxm/src/rxm_domain.c
- prov/rxm/src/rxm_hmem.c
- prov/rxm/src/rxm_msg.c
- prov/rxm/src/rxm_rma.c
This PR adds the usage of gdrcopy when injection is used of send/recv and rma
note: largely based on (https://github.com/ofiwg/libfabric/pull/8836)
comparison with and without gdrcopy (`FI_HMEM_CUDA_USE_GDRCOPY=0/1`):
> rxm: use `gdrcopy` for injection

- include/ofi_hmem.h
- src/hmem.c
- src/hmem_cuda_gdrcopy.c
This PR contains 2 commits that fix the compilation warnings that I observed.
The warnings were
```
src/hmem.c: In function 'ofi_hmem_set_iface_filter':
src/hmem.c:554:17: warning: passing argument 1 of 'strtok' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
entry = strtok(iface_filter_str, token);
^~~~~~~~~~~~~~~~
In file included from ./include/rdma/fi_domain.h:37:0,
from ./include/ofi_hmem.h:41,
from src/hmem.c:39:
/usr/include/string.h:335:14: note: expected 'char * restrict' but argument is of type 'const char *'
extern char *strtok (char *__restrict __s, const char *__restrict __delim)
^~~~~~
src/hmem.c: In function 'ofi_hmem_init':
src/hmem.c:587:43: warning: passing argument 2 of 'ofi_hmem_set_iface_filter' from incompatible pointer type …
```
> hmem: Fix compilation warnings

- configure.ac
- src/fabric.c
The goal of the feature can be achieved more simply by setting FI_PROVIDER_PATH for the user to PROVDLDIR if the variable hasn't been set by the user. This bypasses the most expensive dlopen operations without forcing users to set FI_PROVIDER_PATH to achieve the greatest benefit from the new compile-time flag.
With this change, users can load any provider found in PROVDLDIR by default, which is more flexible than the prior solution which only allowed any provider which was present at compile-time. Additionally, since this change completely avoids the call to ofi_find_prov_libs which incurred the overwhelming majority of the dlopen penalties.
closes #9296
> core: simplify restricted-dl feature

- .github/workflows/gh-man.sh
- .github/workflows/nroff-elves.sh
- .github/workflows/nroff-elves.yaml
GitHub has removed "hub" from their runners since Oct.2, 2023. The recommendation is to use "gh" instead. One benefits is that "gh" has a command for merging the PR, with option to rebase. This allows simpler action script and makes it possible to make "rebase" as the only merge strategy allowed.
> github/actions: migrate from "hub" to "gh"

- include/ofi_atomic_queue.h
- prov/shm/src/smr_util.c
The atomic queue implementation uses atomic operations to allow threads/processes to claim and commit entries into the queue. Because of the use of atomics, padding is essential to allow atomic values to have a dedicated cache line (as atomics will lock the cache line over the course of the operation).
The atomic queue already had padding between the atomics to make sure they were not on the same cache line as each other but this didn't take into account the other fields that might be accessed by other processes as well such as the size and size mask. This could also potentially cause issues with any fields immediately preceeding the queue as well as with fields within the entrytype.
This patch requires the AQ base address to be cache line aligned and pads the atomic values properly so …
> include/ofi_atomic_queue: properly align atomic values

- configure.ac
- include/ofi_hmem.h
- src/hmem.c
- src/hmem_cuda.c
Implement the get_dmabuf_fd API for cuda interface.
> hmem/cuda: Add dmabuf fd ops functions

- .github/workflows/nroff-elves.yaml
The installation of the pandoc package was accidentally removed during the hub->gh convertion. Add it back.
> github/actions: Fix missing package error

- .github/workflows/nroff-elves.sh
The man page convertion action tries to access MarkDown files under 'fabtest'. The correct directory name is 'fabtests'.
> github/actions: Fix incorrect directory name

- prov/sm2/src/sm2.h
- prov/sm2/src/sm2_atomic.c
- prov/sm2/src/sm2_attr.c
- prov/sm2/src/sm2_coordination.h
- prov/sm2/src/sm2_domain.c
- prov/sm2/src/sm2_ep.c
- prov/sm2/src/sm2_fifo.h
- prov/sm2/src/sm2_msg.c
- prov/sm2/src/sm2_progress.c
This PR implements (again) the CMA protocol for arbitrary sized host-host message transfers. It also implements the IPC protocol for arbitrary sized device->host/device transfers and a IPC fallback protocol for host->device transfers.
> prov/sm2: Implement CMA protocol and HMEM

- include/ofi_mr.h
- prov/efa/src/efa_mr.c
- prov/rxm/src/rxm_domain.c
- prov/sockets/src/sock_mr.c
- prov/ucx/src/ucx_domain.c
- prov/util/src/util_mr_cache.c
- prov/util/src/util_mr_map.c
- prov/verbs/src/verbs_mr.c
When mr is registered with FI_MR_DMABUF bit in the flag,
ofi_mr_attr_update should pass the fi_mr_dmabuf object
from the attr user passed.
When inserting the mr to mr map, libfabric
needs to translate the dmabuf object to mr_iov.
When constructing ofi_mr_info from mr_attr for ofi_mr_cache_search.
Convert dmabuf to iov if the flags has FI_MR_DMABUF.
> core: handle dmabuf for ofi_mr functions

- src/hmem_cuda.c
The end of the cuda allocation should be
(uintptr_t) base_addr + total_size - 1.
> hmem/cuda: fix a bug when calculating aligned size.

- fabtests/benchmarks/benchmark_shared.c
Right now, we do not inject if the inject size is equal to the message size.  We should inject in this case, as it is the most likely to cause memory issues. Fix fabtests to test the largest allowable inject message size.
> fabtests: Test max inject size

- fabtests/pytest/efa/conftest.py
- fabtests/pytest/efa/test_rdm.py
- fabtests/pytest/efa/test_rma_bw.py
Add tests to fabtests that test small message sizes without fi_inject. By default, fabtests injects all host messages when the message size is <= the providers inject size.  This change adds testing coverage for fi_send/fi_rma without inject.
> prov/efa: Add testing for small messages without inject

- prov/efa/src/efa.h
- prov/efa/src/efa_env.c
- prov/efa/src/efa_env.h
- prov/efa/src/efa_hmem.c
- prov/efa/src/efa_prov_info.c
Previously, we were subtracting EFA max header size from SHM inject size. Now that we use SHM as a peer provider, we can use SHM's full inject size of 4096. Also cleanup old deprecated env variable, and move hard coded value in place.
> prov/efa: Use SHM's full inject size

- fabtests/common/hmem.c
- fabtests/common/hmem_cuda.c
- fabtests/common/shared.c
- fabtests/configure.ac
- fabtests/functional/unexpected_msg.c
- fabtests/include/hmem.h
- fabtests/include/shared.h
- fabtests/pytest/common.py
- fabtests/unit/mr_test.c
This PR contains 3 commits to add a general option `-R` to support registering memory via dmabuf.
> fabtests: Add dmabuf ops for cuda, add an option to support MR via dmabuf

- libfabric.sln
- libfabric.vcxproj
- prov/efa/src/rdm/efa_rdm_pke.h
This removes the hardcoded padding bytes from the struct definition, which were ostensibly used as a mechanism to enforce alignment of `wiredata` to the 128 byte boundary.
While the `static_assert`s somewhat protect against changes made to the members which the struct is composed of, the manual calculation is a maintenance headache which is prone to developer error, as well as implementation-defined quirks.
More importantly, this change more clearly indicates the intent to align to the 128-byte boundary.
This commit also makes the struct size uniform when debug mode is enabled. This wasn't (currently) necessary, as the 32 bytes of padding were already sufficient for the 16-byte `dlist_entry` struct.
This is the C11-compliant version, utilizing `_Alignas` (stdalign.h)
For sake of …
> prov/efa: Improve `efa_rdm_pke` definition

- fabtests/common/hmem.c
- fabtests/common/hmem_cuda.c
- fabtests/common/shared.c
- fabtests/configure.ac
- fabtests/functional/unexpected_msg.c
- fabtests/include/hmem.h
- fabtests/include/shared.h
- fabtests/pytest/common.py
- fabtests/unit/mr_test.c
Backport https://github.com/ofiwg/libfabric/pull/9500 to v1.20.x
> [v1.20.x] fabtests: Add dmabuf ops for cuda, add an option to support MR via dmabuf

- fabtests/pytest/common.py
- fabtests/pytest/efa/test_mr.py
- fabtests/pytest/options.yaml
This PR contains 2 commits
The first commit makes `do_dmabuf_reg_for_hmem` a cmdline argument to allow user to toggle it without modifying the scripts.
The second commit is to make efa's test_mr.py recognize this argument
> fabtests/pytest: add cmdline argument for dmabuf reg

- fabtests/pytest/common.py
- fabtests/pytest/efa/test_mr.py
- fabtests/pytest/options.yaml
backport https://github.com/ofiwg/libfabric/pull/9530 to v1.20.x
> Fabtests efa dmabuf v1.20.x

- prov/efa/src/efa_env.c
Log an info statement and continue on deprecated env variables that are low impact to the user.
> prov/efa: Do not abort on all deprecated env vars

- prov/efa/src/efa_env.c
Log an info statement and continue on deprecated env variables that are low impact to the user.
(cherry picked from commit 71ba4cbb253e8b91b1d9b3ab9023cdb962bc9a5b)
> [v1.19.x] prov/efa: Do not abort on all deprecated env vars

- prov/efa/src/efa_env.c
Log an info statement and continue on deprecated env variables that are low impact to the user.
(cherry picked from commit 71ba4cbb253e8b91b1d9b3ab9023cdb962bc9a5b)
> [v1.20.x] prov/efa: Do not abort on all deprecated env vars

- prov/util/src/util_attr.c
CXI provider tests were failing due to this missing commit.
> util: Modify domain_attr based on FI_AV_AUTH_KEY

- fabtests/man/fabtests.7.md
To reflect the name change of dmabuf RDMA component tests.
> [v1.20.x] fabtests: Update man page

- fabtests/man/fabtests.7.md
To reflect the name change of dmabuf RDMA component tests.
(cherry picked from commit f3d45793615e968b69110a7dcd500b22e20f222b)
> fabtests: Update man page

- prov/util/src/util_mem_hooks.c
In ofi_write_patch, the bound should be the page end for  address + data_size. And since it's the end of the page, when calculating the length, it needs to add 1 to make the length a multiple of page size.
Fix https://github.com/ofiwg/libfabric/issues/9535
> util/memhooks: Fix a bug when calculating mprotect region

- prov/util/src/util_mem_hooks.c
backport https://github.com/ofiwg/libfabric/pull/9552
> [v1.20.x] util/memhooks: Fix a bug when calculating mprotect region

- prov/util/src/util_mem_hooks.c
backport https://github.com/ofiwg/libfabric/pull/9552
> [v1.18.x] util/memhooks: Fix a bug when calculating mprotect region

- configure.ac
When configured with LTTng-UST support without specifying an installation prefix (--with-lttng), the resulting CPPFLAGS and LDFLAGS contain the (likely) non-existant `yes/` path.
This is a little hacky since it technically breaks builds for people who use `yes/` for some reason, but seems to be the convention used elsewhere.
(cherry picked from commit bbcbaf24af9c232a50a41c87f89d196e641f8bda)
NOTE:
This commit is cherry-picked from main to make CI build check work properly. Without this one, the '--with-lttng' configure option used by CI would lead to failure with the following error message:
checking if libibverbs is linkable by libtool... no
......
configure: verbs provider: disabled
configure: WARNING: verbs provider was requested, but …
> [v1.19.x] configure.ac Fix `--with-lttng` causing `yes/` to populate {CPP,LD}FLAGS

- fabtests/pytest/efa/test_rdm.py
- fabtests/pytest/efa/test_rma_bw.py
Reduce iterations from 5 to 2, and make 1G tests host only for now.
> fabtests/efa: Make 1G tests run faster

- prov/util/src/util_mem_hooks.c
backport https://github.com/ofiwg/libfabric/pull/9552
> [v1.19.x] util/memhooks: Fix a bug when calculating mprotect region

- prov/verbs/src/windows/verbs_nd_ov.c
On `ECONNREFUSED` Mellanox drivers return `0xc000023a` while still writing to `len` a non-zero value. This commit addresses the issue by checking both the error code and `len` for non-zero values.
> prov/verbs_nd: Check error code from GetPrivateData

- configure.ac
- fabtests/common/hmem.c
- fabtests/common/shared.c
- fabtests/component/sock_test.c
- fabtests/functional/rdm_stress.c
- fabtests/functional/rdm_tagged_peek.c
- fabtests/include/shared.h
- fabtests/regression/sighandler_test.c
(1) Fix MacOS build issues
(2) Fix build issue with '--with-lttng' configure option
(3) Fix fi_rdm_tagged_peek test that would fail the ucx provider
> [v1.18.x] Cherry-picked fixes to allow CI build check to pass

- .github/workflows/pr-ci.yml
Instead of turning on "-Werror" permanently, which has been proven to be troublesome, add the flag to the CI build check pipeline. This way we are still able to identify and fix warnings as early as possible while avoid causing failures to other CI jobs.
> github/actions: Add "-Werror" to CI build check runs

- prov/efa/src/rdm/efa_rdm_rma.c
Currently, we always trigger a handshake to check the interoperatability on two sides for rdma capabilities, before determining the protocol to use. However, if the write is to the self peer, we don't need such handshake and just need to check the rdma capability for local ep.
> prov/efa: Don't do handshake for local fi_write

- src/hmem_synapseai.c
backport https://github.com/ofiwg/libfabric/pull/9523
> [v1.19.x] hmem/synapseai: Refine the error handling and warning

- include/ofi_hmem.h
Multiple functions are declared twice in ofi_hmem. Remove the duplicates.
> hmem: Remove duplicate function declarations

- man/fi_provider.7.md
The perl script to convert markdown to man page would remove all content between to lines ending with '---'. Add a space to the end of such lines that are not intended to match the pattern.
> man: Fix the fi_provider.7 man page for the man page converter

- man/fi_provider.7.md
The perl script to convert markdown to man page would remove all content between to lines ending with '---'. Add a space to the end of such lines that are not intended to match the pattern.
(cherry picked from commit 23043e73a48af74652d0199d04d0238e5e7926de)
> [v1.19.x] man: Fix the fi_provider.7 man page for the man page converter

- man/fi_provider.7.md
The perl script to convert markdown to man page would remove all content between to lines ending with '---'. Add a space to the end of such lines that are not intended to match the pattern.
(cherry picked from commit 23043e73a48af74652d0199d04d0238e5e7926de)
> [v1.18.x] man: Fix the fi_provider.7 man page for the man page converter

- man/fi_msg.3.md
- man/fi_rma.3.md
- man/fi_tagged.3.md
The man pages of `fi_msg`, `fi_tagged`, and `fi_rma` gave the false impression that the behavior of `fi_*data` calls could be affected by whether this flag is set. In reality, the flag is not a valid choice for endpoint `op_flags` and the `fi_*data` calls always act as if the flag is set.
Update the man pages to eliminate the confusion.
Reference: https://github.com/ofiwg/libfabric/discussions/9527
> man: Clarify the usage of FI_RMOTE_CQ_DATA flag

- configure.ac
- include/ofi_hmem.h
- prov/verbs/src/verbs_mr.c
- src/hmem.c
- src/hmem_rocr.c
- Added `get_dmabuf_fd` for ROCr under HMEM interface, it acquires dmabuf handle through HSA runtime and is now invoked by `verbs` providers.
- 3 conditions for support of this functionality: ROCr support, Linux kernel support, and a user set environmental variable `FI_HMEM_ROCR_USE_DMABUF` (please let us know if naming is ok) as a switch that will be checked during runtime
- currently for verbs, if dmabuf handle cannot be successfully acquired for any reason, it will opt to not register any memory region and [just crash](https://github.com/ofiwg/libfabric/blob/main/prov/verbs/src/verbs_mr.c#L85). We are not sure if this is intended or a bug, but tentatively we fixed this and make it invoke failover routine in case of failure.
> hmem/rocr: Add ROCr dmabuf support under verbs

- prov/util/src/util_mem_hooks.c
Cherry-picked fomr commit c9fd334faee74c0c38d2f62b93b2f02a0299e371
> [v1.20.x] prov/util_mem_hooks: add missing parantheses

- prov/verbs/src/verbs_cm.c
- prov/verbs/src/verbs_eq.c
Add missing calls to `rdma_destroy_id` after a call to `rdma_reject` to prevent `cm_id` resource leak.
The resource leak can be observed by running `rdma res` and checking the value of `cm_id`. Each time a passive endpoint rejects an incoming connection, `cm_id` is increased. This behavior is not observed when a connection is accepted and then closed abruptly or gracefully by a call to `fi_shutdown`.
I'm not sure about the correctness of `rdma_destroy_id` in XRC path in verbs_eq.c
> prov/verbs: Address cm_id resource leak in rdma_reject path

- contrib/intel/jenkins/tests.py
This tests still shows random failures sometimes on the CI weekly job.
> intel/ci: excluding mt_improbe_sendrecv_huge from mpichsuite testing

- prov/efa/configure.m4
hav_efa_dmabuf_mr should be have_efa_dmabuf_mr.
> prov/efa: Fix a typo in configure.m4

- prov/efa/configure.m4
backport https://github.com/ofiwg/libfabric/pull/9635
> [v1.20.x] prov/efa: Fix a typo in configure.m4

- prov/efa/src/rdm/efa_rdm_rma.c
Currently, we always trigger a handshake to check the interoperatability on two sides for rdma read capabilities, before determining the protocol to use. However, if the read is from the self peer, we don't need such handshake and just need to check the rdma capability for local ep.
> prov/efa: Don't do handshake for local read

- prov/efa/src/rdm/efa_rdm_rma.c
Backport https://github.com/ofiwg/libfabric/pull/9580 and https://github.com/ofiwg/libfabric/pull/9640 to skip handshake for local read and write
> [v1.19.x] don't do handshake for local read and local write

- prov/util/src/util_wait.c
`util_wait_yield_run()` in `prov/util/src/util_wait.c` currently ignores the timeout parameter, leading to hanging applications on our end. This PR copies the timeout logic from `util_wait_fd_run()` in the same file.
> Add missing timeout in util_wait_yield_run()

- prov/efa/src/rdm/efa_rdm_ep.h
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/src/rdm/efa_rdm_ep_progress.c
Currently, efa_rdm_ep_poll_ibv_cq couldn't
handle error for IBV_WC_RECV_RDMA_WITH_IMM
and IBV_WC_RDMA_READ. This patch fixes it.
It also removed the failed_send/write_comps
in the debug build, because these symbols
are never used.
> prov/efa: Fix the ibv cq error handling.

- prov/efa/src/efa_av.c
The memset assigns the same length as the variable we are setting.... no chance anything bad will happen.
> prov/efa: remove unneeded memset

- prov/efa/src/efa_tp.h
- prov/efa/src/rdm/efa_rdm_tracepoint.h
I was playing around on godbolt and saw that while (0) {} generates a noop instruction, but (void) 0; does not.  Get rid of noop instructions from critical path without hurting the readability of the code.
> prov/efa: Get rid of noop instruction from empty #define

- prov/efa/src/rdm/efa_rdm_atomic.c
- prov/efa/src/rdm/efa_rdm_ep.h
- prov/efa/src/rdm/efa_rdm_ep_utils.c
- prov/efa/src/rdm/efa_rdm_msg.c
- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/src/rdm/efa_rdm_ope.h
- prov/efa/src/rdm/efa_rdm_rma.c
- prov/efa/src/rdm/efa_rdm_rma.h
The EFA provider needs to find the peer pointer early so we can decide if we should use SHM to send the message, or if the message should go through EFA.  Instead of losing the pointer, and re-finding it when we create the txe, pass it through parameters to the txe so we don't have to duplicate the effort of finding the peer.
> prov/efa: Pass in peer pointer to txe

- prov/efa/src/rdm/efa_rdm_ep.h
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/src/rdm/efa_rdm_ep_progress.c
backport https://github.com/ofiwg/libfabric/pull/9652
> [v1.20.x] prov/efa: Fix the ibv cq error handling.

- prov/efa/src/rdm/efa_rdm_msg.c
- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/src/rdm/efa_rdm_pke.c
- prov/efa/src/rdm/efa_rdm_pke_req.c
- prov/efa/src/rdm/efa_rdm_rma.c
- prov/efa/test/efa_unit_test_ope.c
The peer pointer is calculated and stored in the txe.  Use this pointer instead of constantly re-calling efa_rdm_ep_get_peer() to get this pointer for performance reasons.
> prov/efa: use peer pointer from txe in read, write and send

- prov/opx/include/rdma/opx/fi_opx_endpoint.h
- prov/opx/src/fi_opx_ep.c
This commit is to add in an initialization that was missing and addresses a bug seen in the OPX provider in the 1.20 release.
> OPX: Initialize cq error data size

- prov/efa/src/rdm/efa_rdm_msg.c
This commit makes a few changes to make the msg path slightly more efficient.
1. Stop initializing msg to 0  in recv path b/c efa_rdm_msg_construct fully init's struct fi_msg
2. Make efa_rdm_msg_recv() and efa_rdm_msg_recvv() directly call efa_rdm_msg_generic_recv()
3. Make efa_rdm_msg_generic_recv() and efa_rdm_msg_generic_recv() an inline function
4. Pass in efa_rdm_ep in send/recv path to make it so we do not need duplicate calls to container_of()
> prov/efa: Make msg path slightly more efficient

- prov/efa/src/rdm/efa_rdm_pke_rtm.c
This patch uses nested if cases to reduce the number of error checks in the fast happy path from 3 to 1 inside
efa_rdm_pke_handle_rtm_rta_recv(). It also cleans up some extra spacing in comments.
> prov/efa: Reduce # of error cases in happy path

- prov/efa/src/rdm/efa_rdm_ep_utils.c
Remove memset of struct efa_rdm_ope (size = 912 bytes) when we alloc an rxe on a progress which progresses a message.  This reduces the time to progress a message by ~40-55ns (3-5% on 1k msg sizes).  This commit removes saftey guard rails in order to squeeze out additional performance from the EFA provider.
> prov/efa: Do not memset rxe to 0 on init

- fabtests/prov/efa/src/efa_exhaust_mr_reg_common.c
- fabtests/prov/efa/src/efa_exhaust_mr_reg_common.h
- fabtests/prov/efa/src/efa_exhaust_mr_reg_rdm_pingpong.c
Some improvements to the MR exhaustion test
* Add a simple test for the unexpected message path
* Get device MR limit by querying the device instead of hardcoding the value
* Close ibv device after use
> fabtests/efa: Improve MR exhaustion test

- prov/rxm/src/rxm_cq.c
Data verification would fail with rxm/verbs when FI_OFI_RXM_USE_RNDV_WRITE is set to 1. It appears that the content of the receive buffer remains unchanged after the rendezvous send is completed.
This only happens when the core provider requires FI_MR_LOCAL mode. The root cause is that MR descriptors passed through the receive call are not translated into rkeys when generating the rendezvous response. As a result, the sender always writes 0 byte.
> prov/rxm: Fix data error with FI_OFI_RXM_USE_RNDV_WRITE=1

- fabtests/benchmarks/benchmark_shared.c
- fabtests/benchmarks/rma_pingpong.c
* Don't init {tx,rx}_buf for writedata tests
* Fail rma_pingpong with `-o write` and HMEM
With this PR, rma_pingpong write test with HMEM fails as expected, and writedata with HMEM succeeds. (Tested on EFA provider.)
> fabtests/benchmarks: fix HMEM support in rma_pingpong benchmark

- prov/efa/src/rdm/efa_rdm_ep_fiops.c
Customers have been complaining that the FI_WARN log for endpoint creation is too noisy. Switch the warn to an info.
> prov/efa: Downgrade EFA Endpoint Creation WARN to INFO

- prov/efa/src/rdm/efa_rdm_ep_fiops.c
Customers have been complaining that the FI_WARN log for endpoint creation is too noisy. Switch the warn to an info.
(cherry picked from commit 56c2aaf6f9aeee39189afa3a4e40bcb9b12ecdfe)
> [v1.20.x] prov/efa: Downgrade EFA Endpoint Creation WARN to INFO

- prov/efa/src/rdm/efa_rdm_atomic.c
- prov/efa/src/rdm/efa_rdm_ep.h
- prov/efa/src/rdm/efa_rdm_ep_utils.c
- prov/efa/src/rdm/efa_rdm_msg.c
- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/src/rdm/efa_rdm_pke.c
- prov/efa/src/rdm/efa_rdm_pke_cmd.c
- prov/efa/src/rdm/efa_rdm_rma.c
- prov/efa/test/efa_unit_test_cq.c
- prov/efa/test/efa_unit_test_ep.c
- prov/efa/test/efa_unit_test_rnr.c
Switch handshake send/response functions to create a txe.  Optimize the EFA send path by removing redundant efa_rdm_ep_get_peer() functions from it.
> prov/efa: Make handshake code use TXE, and provide perf improvements to EFA

- prov/rxm/src/rxm_cq.c
Data verification would fail with rxm/verbs when FI_OFI_RXM_USE_RNDV_WRITE is set to 1. It appears that the content of the receive buffer remains unchanged after the rendezvous send is completed.
This only happens when the core provider requires FI_MR_LOCAL mode. The root cause is that MR descriptors passed through the receive call are not translated into rkeys when generating the rendezvous response. As a result, the sender always writes 0 byte.
(cherry picked from commit 81c0b7a54f2a9376fd6279abc8051c9d20dd4499)
> [v1.20.x] prov/rxm: Fix data error with FI_OFI_RXM_USE_RNDV_WRITE=1

- prov/rxm/src/rxm_cq.c
Data verification would fail with rxm/verbs when FI_OFI_RXM_USE_RNDV_WRITE is set to 1. It appears that the content of the receive buffer remains unchanged after the rendezvous send is completed.
This only happens when the core provider requires FI_MR_LOCAL mode. The root cause is that MR descriptors passed through the receive call are not translated into rkeys when generating the rendezvous response. As a result, the sender always writes 0 byte.
(cherry picked from commit 81c0b7a54f2a9376fd6279abc8051c9d20dd4499)
> [v1.19.x] prov/rxm: Fix data error with FI_OFI_RXM_USE_RNDV_WRITE=1

- prov/rxm/src/rxm_cq.c
Data verification would fail with rxm/verbs when FI_OFI_RXM_USE_RNDV_WRITE is set to 1. It appears that the content of the receive buffer remains unchanged after the rendezvous send is completed.
This only happens when the core provider requires FI_MR_LOCAL mode. The root cause is that MR descriptors passed through the receive call are not translated into rkeys when generating the rendezvous response. As a result, the sender always writes 0 byte.
(cherry picked from commit 81c0b7a54f2a9376fd6279abc8051c9d20dd4499)
> [v1.18.x] prov/rxm: Fix data error with FI_OFI_RXM_USE_RNDV_WRITE=1

- prov/verbs/src/windows/verbs_nd_ov.c
Fixes a regression introduced in commit da40f10, specifically occurring when a call to `GetPrivateData` correctly returns `ND_BUFFER_OVERFLOW`.
Leaving check for `SUCCEEDED(hr)` as that is still returned by some of the older Mellanox drivers on Windows.
> prov/verbs_nd: Resolve regression in user data retrieval

- man/fi_collective.3.md
- man/fi_rxm.7.md
fi_rxm.7: clarify the behavior when message size == FI_OFI_RXM_BUFFER_SIZE.
fi_collective.3: add the missing description of the `count` argument.
> man: Fix fi_rxm.7 and fi_collective.3 man pages

- src/hmem_cuda.c
Compiling with icx uncovered an error from -Wenum-conversion. Need to explicitly cast from CUresult to cudaError_t for ofi_cudaGetErrorName and ofi_cudaGetErrorString calls.
Even with this fix, there is a risk that the return code is not a valid cudaError_t enumeration, but the only consequence will be that the functions return "Unknown Error".
> Fix compiler warning when compiling with ICX

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/build.py
- contrib/intel/jenkins/common.py
- contrib/intel/jenkins/run.py
- contrib/intel/jenkins/runtests.py
- contrib/intel/jenkins/summary.py
- contrib/intel/jenkins/tests.py
Separate software builds by hardware.
This will allow easier debugging in the case of test failures as well as make it easier to distinguish which packages are in use on a given node.
This separates each job by HW type and then builds on that specific hardware. The directory structure is now structured by workspace with everything in sub directories inside it instead of installing to a new location not controlled by cloudbees.
These changes will make it easier to upgrade our CI in the future by enabling movement of an entire HW type to the new software solution instead of having to wait for everything to be ready.
> contrib/intel/jenkins: Update jenkins architecture for future changes

- contrib/intel/jenkins/tests.py
The idup_nb test is showing occasional failures for tcp provider. It is excluded until resolution.
> intel/ci: exclude threads/comm/idup_nb test mpichsuite tests for tcp.

- man/fi_endpoint.3.md
fi_setopt adjust the protocol and implementation
details of an endpoint, so it must be called before the endpoint is enabled via fi_enable.
> man: Regulate the fi_setopt call sequence.

- prov/efa/src/efa_shm.c
In some cases, the shm provider version is older than 1.19 and this causes the shm provider getinfo call to fail. This commit retries with an older API version
> prov/efa: Retry opening shm provider with older API version

- README.md
This commit adds a badge to calculate OpenSSF score after each commit.
A detailed scorecard can be accessed by clicking on the badge.
> libfabric/README.md: Add badge for openssf scorecard

- fabtests/common/hmem_ze.c
- include/ofi_hmem.h
- src/hmem_ze.c
We have already seen setups with 16 ZE devices. Increase the maximum to 32 to leave some room for future growth.
Ultimately we will need to remove this hard limit and allocated the resources dynamicaly. That can be done later.
Also change the behavior for the case when the limit is exceeded.
> hmem/ze: Increase ZE_MAX_DEVICES to 32

- prov/util/src/util_cq.c
I added a bug to util_cq in 96f35fa2 inside ofi_cq_init()'s error path because I switched the order of the lock creation calls, without correctly fixing the cleanup on error path.  This patch corrects the bug.
> prov/util: fix bug in util_cq startup error case

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/tests.py
- prov/tcp/src/xnet.h
- prov/tcp/src/xnet_msg.c
- prov/tcp/src/xnet_rdm_cm.c
- prov/tcp/src/xnet_rma.c
Added the following commits
[prov/tcp: Derive cq flags from op and msg flags](https://github.com/ofiwg/libfabric/pull/9460/commits/a3ed3ad3873fc172b50a6252b1efec3a38981199)
[prov/tcp: Pass through rdm_ep flags to msg eps.](https://github.com/ofiwg/libfabric/pull/9460/commits/dbf226504d9ef7b19ccca811994e528f7a3ad2ca)
[intel/ci: enable mpich rma tests for tcp](https://github.com/ofiwg/libfabric/pull/9460/commits/f80e00051d18381b23bf82d1f0f0b32b317f9cf9)
[intel/ci: disable rma/win_shared_put_flush_load test from mpich suite](https://github.com/ofiwg/libfabric/commit/6bd0b5de4a773e04933f9b585f6e715f3405b98d)
[Intel/CI: Enable Previously Failing tests on CI.](https://github.com/ofiwg/libfabric/commit/7e47412777c634337db47ac1b9d97b701704c725)
[intel/ci: excluding mt_improbe_sendrecv_huge from …
> [v1.19.x] Cherry-picked commits for enabling mpichsuite rma tests

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/tests.py
- prov/tcp/src/xnet.h
- prov/tcp/src/xnet_msg.c
- prov/tcp/src/xnet_rdm_cm.c
- prov/tcp/src/xnet_rma.c
Added the following commits
[prov/tcp: Derive cq flags from op and msg flags](https://github.com/ofiwg/libfabric/pull/9460/commits/a3ed3ad3873fc172b50a6252b1efec3a38981199)
[prov/tcp: Pass through rdm_ep flags to msg eps.](https://github.com/ofiwg/libfabric/pull/9460/commits/dbf226504d9ef7b19ccca811994e528f7a3ad2ca)
[intel/ci: enable mpich rma tests for tcp](https://github.com/ofiwg/libfabric/pull/9460/commits/f80e00051d18381b23bf82d1f0f0b32b317f9cf9)
[intel/ci: disable rma/win_shared_put_flush_load test from mpich suite](https://github.com/ofiwg/libfabric/commit/6bd0b5de4a773e04933f9b585f6e715f3405b98d)
[Intel/CI: Enable Previously Failing tests on CI.](https://github.com/ofiwg/libfabric/commit/7e47412777c634337db47ac1b9d97b701704c725)
[intel/ci: excluding mt_improbe_sendrecv_huge from …
> [v1.18.x] Cherry-picked commits for enabling mpichsuite rma tests

- fabtests/common/hmem_ze.c
- src/hmem_ze.c
libze_loader.so requires level-zero-devel package. Use libze_loader.so.1 instead.
> hmem/ze: Change the library name passed to dlopen

- prov/shm/src/smr_util.h
xpmem is a opt-in feature, and xpmem_cap_self, xpmem_self, and xpmem_peer are not used in fast path. The previous commit e0906f6f inserts xpmem related fields in the middle of smr_region struct, which makes the size of smr_region struct increase from 104 (2 cache lines) to 144 ( 3 cache lines). The insertion of xpmem_cap_self, xpmem_self, and xpmem_peer make the fields (offsets) used in the fast path shifted to the next cache line and causes more cache misses.
This patch moves the xpmem fields to the end of the struct to fix this issue.
> prov/shm: adjust the order of smr_region fields.

- prov/shm/src/smr_util.h
backport https://github.com/ofiwg/libfabric/pull/9742
> [v1.20.x] prov/shm: adjust the order of smr_region fields.

- prov/shm/src/smr_ep.c
Sock variable handle goes out of scope and leaks the handle. This cleans it up properly.
> prov/shm: Fix coverity issue about resource leak

- include/ofi_mr.h
- prov/util/src/cuda_ipc_monitor.c
- prov/util/src/cuda_mem_monitor.c
- prov/util/src/rocr_ipc_monitor.c
- prov/util/src/rocr_mem_monitor.c
- prov/util/src/util_mem_hooks.c
- prov/util/src/util_mem_monitor.c
- prov/util/src/xpmem_monitor.c
- prov/util/src/ze_mem_monitor.c
Log when monitor states are changed.
Log name of default monitor.
> prov/util: Add name field to memory monitors:

- man/fi_efa.7.md
- prov/efa/Makefile.include
- prov/efa/configure.m4
- prov/efa/src/efa.h
- prov/efa/src/efa_domain.c
- prov/efa/src/fi_ext_efa.h
- prov/efa/test/efa_unit_test_domain.c
- prov/efa/test/efa_unit_test_mocks.c
- prov/efa/test/efa_unit_test_mocks.h
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
Make efa onboard the fi_open_ops API, which allows user to access efa specific domain ops. The usage of this API is documented in fi_efa.7.md.
Also added a unit test.
> prov/efa: Introduce efa specific domain operations

- prov/efa/src/efa_hmem.c
we use cuda malloc to allocate temporary cuda buffer for a dummy memory registration to check the p2p support on the platform. It's not needed if users only run host workloads. This patch makes libfabric not hard fail in this situation but leave cuda hmem interface not initialized.
> prov/efa: Don't fail the whole domain init if cudamalloc failed

- prov/efa/src/rdm/efa_rdm_msg.c
- prov/efa/src/rdm/efa_rdm_peer.h
Currently, efa provider always return EAGAIN for send with hmem memory before a handshake is made. This caused unnecessary overhead in the startup. EFA should still moves with copy-based protocols (no rdma-read) before the handshake is made.
> prov/efa: Remove unnecessary handshake in send path

- fabtests/pytest/efa/test_rdm.py
- fabtests/pytest/efa/test_rma_bw.py
- prov/efa/src/rdm/efa_rdm_ope.c
efa_rdm_pke_alloc can return NULL when tx pkt pool is exhausted. In this case we should release allocated pkt entries and return EAGAIN.
> prov/efa: Fix a bug in efa_rdm_ope_post_send

- src/fabric.c
Print provider path on fi_fabric call to help with provider debug.  For users of FI_PROVIDER_PATH with multiple instances of the same provider, this will help to determine the exact provider code being executed.
> core: Print provider path on fabric creation

- include/ofi_hmem.h
- prov/efa/src/rdm/efa_rdm_pke_utils.c
- src/hmem.c
- src/hmem_cuda_gdrcopy.c
Reuse the dev_reg_copy ops recently introduced in hmem API,
in a similar approach as ofi_async_copy_hmem_iov_buf.
Replace the hard-coded ofi_cuda_gdrcopy_*iov ops by
the new ofi_dev_reg_copy_*_iov ops which is general
for all hmem ifaces.
> hmem and prov/efa: introduce ofi_dev_reg_copy_*_iov ops

- prov/efa/src/rdm/efa_rdm_ep.h
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/src/rdm/efa_rdm_ep_progress.c
- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/src/rdm/efa_rdm_pke_cmd.c
- prov/efa/src/rdm/efa_rdm_pke_nonreq.c
- prov/efa/src/rdm/efa_rdm_pke_utils.c
- prov/efa/test/efa_unit_test_cq.c
- prov/efa/test/efa_unit_test_ep.c
Currently efa rdm ep has 2 rx pkt counters:
efa_rx_pkt_posted, efa_rx_pkt_to_post. The
progress engine uses efa_rx_pkt_posted==0
and efa_rx_pkt_to_post==0 to identify whether
the endpoint is progressed the first time.
However, these 2 counters do not cover the activity of all rx pkts. Some rx pkts can be held within
a round of progress engine due to queued hmem
copy or being posted for local read. And when the
rx pkt pool is small (customized by env or hints), the held rx pkts can cause both efa_rx_pkt_posted
and efa_rx_pkt_to_post as 0 in the middle of the
progress engine, which will trigger another
pkt pool grow and fail.
This patch adds an additional counter: efa_rx_pkts_held in efa_rdm_ep to cover this part of rx pkts. And added a stronger assertion that
efa_rx_pkts_posted + …
> prov/efa: Add a missing rx pkt counter

- fabtests/test_configs/tcp/io_uring.exclude
We have identified a hand in fi_bw test due to a race condition. fi_rdm_cntr_pingpong test prints out failures but reports a pass. Both of these tests are disabled in this commit.
> contrib/intel/jenkins: Disable failing io_uring tests

- fabtests/common/shared.c
- fabtests/component/dmabuf-rdma/fi-rdmabw-xe.c
- fabtests/component/dmabuf-rdma/rdmabw-xe.c
- fabtests/component/dmabuf-rdma/xe.c
- fabtests/include/windows/osd.h
- include/windows/osd.h
- src/hmem.c
- src/hmem_ze.c
strtok() is non-reentrant. One error case discovered recently looks like the following:
```
func_A()
{
s = strtok(s1, ',');
while (s) {
func_B(s);
s = strtok(NULL, ',');
}
}
```
somewhere down the calling chain of func_B(), strtok() is called to parse another string, and that destroys the parsing state of s1.
Replace all the remaining occurences of strtok() with the reentrant version strtok_r() to prevent such error from happening again.
> core,fabtests: Replace strtok with strtok_r

- prov/cxi/configure.m4
Running configure with the `--enable-only` option but without enabling cxi generates the following error:
```
configure: error: conditional "HAVE_CRITERION" was never defined.
Usually this means the macro was only invoked conditionally
```
> prov/cxi: Fix configure error with "--enable-only" option

- fabtests/common/shared.c
- fabtests/component/dmabuf-rdma/fi-rdmabw-xe.c
- fabtests/component/dmabuf-rdma/rdmabw-xe.c
- fabtests/component/dmabuf-rdma/xe.c
- fabtests/include/windows/osd.h
- include/windows/osd.h
- src/hmem.c
- src/hmem_ze.c
strtok() is non-reentrant. One error case discovered recently looks like the following:
```
func_A()
{
s = strtok(s1, ',');
while (s) {
func_B(s);
s = strtok(NULL, ',');
}
}
```
somewhere down the calling chain of func_B(), strtok() is called to parse another string, and that destroys the parsing state of s1.
Replace all the remaining occurences of strtok() with the reentrant version strtok_r() to prevent such error from happening again.
(cherry picked from commit ced402e1c12dd400966ff7c05980b2b4b6b4ff99)
> [v1.20.x] core,fabtests: Replace strtok with strtok_r

- fabtests/common/shared.c
- fabtests/component/dmabuf-rdma/fi-rdmabw-xe.c
- fabtests/component/dmabuf-rdma/rdmabw-xe.c
- fabtests/component/dmabuf-rdma/xe.c
- fabtests/include/windows/osd.h
- include/windows/osd.h
- src/hmem_ze.c
strtok() is non-reentrant. One error case discovered recently looks like the following:
```
func_A()
{
s = strtok(s1, ',');
while (s) {
func_B(s);
s = strtok(NULL, ',');
}
}
```
somewhere down the calling chain of func_B(), strtok() is called to parse another string, and that destroys the parsing state of s1.
Replace all the remaining occurences of strtok() with the reentrant version strtok_r() to prevent such error from happening again.
(cherry picked from commit ced402e1c12dd400966ff7c05980b2b4b6b4ff99)
> [v1.19.x] core,fabtests: Replace strtok with strtok_r

- fabtests/component/dmabuf-rdma/fi-rdmabw-xe.c
- fabtests/component/dmabuf-rdma/rdmabw-xe.c
- fabtests/component/dmabuf-rdma/xe.c
- fabtests/include/windows/osd.h
- include/windows/osd.h
- src/hmem_ze.c
strtok() is non-reentrant. One error case discovered recently looks like the following:
```
func_A()
{
s = strtok(s1, ',');
while (s) {
func_B(s);
s = strtok(NULL, ',');
}
}
```
somewhere down the calling chain of func_B(), strtok() is called to parse another string, and that destroys the parsing state of s1.
Replace all the remaining occurences of strtok() with the reentrant version strtok_r() to prevent such error from happening again.
(cherry picked from commit ced402e1c12dd400966ff7c05980b2b4b6b4ff99)
> [v1.18.x] core,fabtests: Replace strtok with strtok_r

- .github/workflows/coverity.yml
LD_LIBRRARY_PATH (for rdma-core libraries) was set to relative path, which didn't work for fabtests build due to working directory change.
Fix by using absolution path.
> github/workflow: Fix coverity build error for fabtests

- prov/cxi/src/cxip_rma.c
Hi all, 
I would like the `cxi` provider to honor the use variable `FI_CXI_DISABLE_NON_INJECT_MSG_IDC=1` in both the `msg` and `rma` paths.
When disabling the use of GDR copy on CUDA devices, here is the latency I get when disabling `NON_INJECT_MSG_IDC` (before the PR):
- `fi_tsend`: `9.779660us` -> `3.314845us`
- `fi_write`: `10.573375us` -> `10.326375us`
> prov/cxi: honor `FI_CXI_DISABLE_NON_INJECT_MSG_IDC` with rma

- .github/workflows/coverity.yml
The LDFLAGS passed to fabtests build command line also needs to use absolute path.
> github/workflow: More fix for coverity build

- .github/workflows/coverity.yml
Also adjust the schedule time to be truely in the night (US).
> github/workflow: Add libfabric lib path to coverity fabtests build

- contrib/intel/jenkins/summary.py
A bug was found in oneccl summary in counting passed tests logic because the log file logged it differently.
Expected log:
[0] [  PASSED  ] [0] 384 tests.
Logged line:
[0] [  PASSED  ] (13 ms)
[0] 384 tests.
The fix is to check whether there are any lines having 'tests.' but not having [0] [  PASSED  ] and [1] [  PASSED  ] in line.
> Intel/CI: Resolve OneCCL summary bug

- fabtests/unit/cq_test.c
opened should only be incremented when
create_cq returns 0. The current implementation
will make it set as the actual opened count
plus 1 when some error happens. This will
cause a double free error when fi_close
the last cq which is not opened.
> fabtests/cq_test: Fix a bug in opened cq cnt

- prov/efa/src/rdm/efa_rdm_pke_cmd.c
- prov/efa/test/efa_unit_test_cq.c
When getting the error with IBV_WC_RECV op
code, it is possible that packet entry is not associated with an ope yet, if the packet is posted by
efa_rdm_ep_bulk_post_internal_rx_pkts().
For such error, we can only warn and write eq
error as it is an EFA internal error and not
associated with application's rx operation.
> prov/efa: Handle rx pkts error without ope

- prov/efa/src/rdm/efa_rdm_rma.c
efa_both_support_rdma_write already covers the
check for self peer. No need to check it explicitly again. Also remove the assertion because we don't need a handshake if the peer is self.
> prov/efa: Remove unnecessary check in rdma write.

- fabtests/common/shared.c
- fabtests/functional/multi_ep.c
- fabtests/functional/rdm_stress.c
- fabtests/ubertest/verify.c
- fabtests/unit/mr_cache_evict.c
There are multiple error handling coverity issues reported recently.
All the issues require simple return statement check.
Each commit is for each issue.
**Following is a list of issues with links:**
**414775 (Calling ft_fill_buf without checking return value):**
https://scan4.scan.coverity.com/#/project-view/61752/10344?selectedIssue=414775
**414776 (Calling fi_close without checking return value):**
https://scan4.scan.coverity.com/#/project-view/61752/10344?selectedIssue=414776
**414778 (Calling ft_sock_send without checking return value):**
https://scan4.scan.coverity.com/#/project-view/61752/10344?selectedIssue=414778
**414807 (Calling ft_sock_recv without checking return value):**
https://scan4.scan.coverity.com/#/project-view/61752/10344?selectedIssue=414807
**414780 (Calling …
> Fabtests: Resolve error handling coverity issues

- prov/shm/src/smr_util.c
Must assert that the id is within the allowable range before using it to check a peer's name
> prov/shm: Fix new coverity issue introduced by 7f23127

- fabtests/include/ft_osd.h
E.g. #include <unix/osd.h> points to libfabric include, while the demanded include file is located in fabtests/include.
> Fix ft_osd includes to point to fabtests/include

- fabtests/prov/efa/src/rdm_rnr_read_cq_error.c
- prov/efa/src/rdm/efa_rdm_atomic.c
- prov/efa/src/rdm/efa_rdm_msg.c
- prov/efa/src/rdm/efa_rdm_rma.c
It's application's responsibility to poll cq
when hitting EAGAIN, efa provider shouldn't have
to progress the ep again inside the transmission
call.
Also fix the EAGAIN handling in rnr_cq_read_error test
> prov/efa, fabtests/efa: Do not progress cq inside transmission call when hitting EAGAIN

- fabtests/prov/efa/src/rdm_rnr_read_cq_error.c
Add a (void) before fi_cq_read(txcq, NULL, 0)
as in this case we don't care the return of fi_cq_read.
> fabtests/efa: Fix coverity issue in rnr_read_cq_err

- prov/shm/src/smr_util.h
The earlier change caused regression for inline message size and didn't bump the SMR protocol version. Revert it before we have a better fix on the alignment and cahce coherency.
This reverts commit b069cb494dc411f1cba9b8f66292c142862da254.
> prov/shm: revert the smr_region fields adjustment

- prov/shm/src/smr_util.h
backport https://github.com/ofiwg/libfabric/pull/9856
> [v1.20.x] prov/shm: revert the smr_region fields adjustment

- include/ofi_hmem.h
- src/hmem_cuda.c
The cuda_is_addr_valid() function makes 2 separate calls to cuPointerGetAttribute() to get the memory type and device. If the caller also wants to know if the cuda buffer is "managed" (i.e. unified memory), a 3rd subsequent call to cuPointerGetAttribute() is necessary (outside of cuda_is_addr_valid()) to retrieve that.
This change gets all three attributes in a single call to cuPointerGetAttributes(). If the address in question points to cuda memory, and that memory is managed/unified, the resulting flags will not have FI_HMEM_DEVICE_ONLY set.
---
Making this change per discussion [here](https://github.com/ofiwg/libfabric/pull/9836#discussion_r1506097433).
Communicating managed/unified status by not setting FI_HMEM_DEVICE_ONLY based on this …
> hmem/cuda: Get multiple attributes at once in cuda_is_addr_valid

- fabtests/functional/multi_ep.c
EPs must be closed first before closing other associated resources. The current logic will cause EBUSY error when closing a CQ that still has EPs binding (when running with shared cq)
> fabtests/multi_ep: close all eps first during clean up

- configure.ac
If --disable-xpmem is passed to configure, skip checking. Fixes a build issue when xpmem is located in the default system directories.
> configure: Do not check for xpmem if disabled

- fabtests/common/shared.c
- fabtests/functional/inject_test.c
- fabtests/include/shared.h
This PR contains two changes
1. Improve ft_sendmsg: Use FT_POST to handle EAGAIN, make inject_test.c and ft_finalize_ep use the new ft_sendmsg function to remove code duplication.
2. Make ft_sync do tx with FI_DELIVERY_COMPLETE: Use FI_DELIVERY_COMPLETE to have a stronger sync up between the sender and receiver, which can enforce the handshake made in the protocols of RDM endpoints.
> fabtests: improve ft_sendmsg, use FI_DELIVERY_COMPLETE for ft_sync

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/build.py
- contrib/intel/jenkins/run.py
- contrib/intel/jenkins/runtests.py
- contrib/intel/jenkins/summary.py
- contrib/intel/jenkins/tests.py
Build shmem in build steps onto specific hardware types
Add back SOS tests
Add support to run test executables instead of using "make check" as implied in SOS repository
Add summarizer support for new test output
Add shmem tests for sockets and verbs-rxm
Add ability to disable failing tests until further investigation
Remove shmem-uh tests since they haven't been updated in 6 years and are stale
Remove unused summary fields
Place performance only tests in weekly
> contrib/intel/jenkins: Update SHMEM testing

- contrib/intel/jenkins/Jenkinsfile
Delete location accidentally got removed and needs to be added back for proper cleanup on abort case
> contrib/intel/jenkins: Add back missing DELETE_LOCATION

- SECURITY.md
This commit adds a SECURITY.md file.
Information about how to report a security vulnerability in libfabric project/source code is mentioned in the file. 
This will also help in improving the OSSF score.
> libfabric/SECURITY.md: Add a SECURITY.md file

- man/fi_rxm.7.md
- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_atomic.c
- prov/rxm/src/rxm_cq.c
- prov/rxm/src/rxm_domain.c
- prov/rxm/src/rxm_init.c
- prov/rxm/src/rxm_msg.c
A new option FI_OFI_RXM_DETECT_HMEM_IFACE is added. With the option turned on, RxM tries to detect the HMEM iface of user buffers if no mr_desc is supplied. This allows successful copy between user buffers located in device memory and internal bounce buffers, as well as registering such user buffer in RxM Rendezvous protocol.
Note that this doesn't allow such buffers to be used in the RxM direct send mode if the core provider requires FI_MR_HMEM because no memory registration is introduced by the option.
> prov/rxm: Add option to auto detect hmem iface of user buffers

- include/windows/osd.h
- src/fabric.c
Existing FI_PROVIDER_PATH specifies a list of directories under which DL providers are searched for. If multiple providers with the same name are found, either the one with the highest version or the one registered first is set to be visible, depending on whether `@` appears at the beginning of FI_PROVIDER_PATH. Others are set to be hidden. This works fine for most cases.  However, sometimes it is desirable to be able to set a preferred provider directly, regardless of the version and the registration order.
Here FI_PROVIDER_PATH is extended to allow setting preferred providers in addition to provder search path. Each preferred provider is specified as `+` followed by the full path to the provider library. If registered successfully, a preferred provider takes precedence over all other …
> core: Extend FI_PROVIDER_PATH to allow setting preferred DL provider

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/build.py
- contrib/intel/jenkins/tests.py
- fabtests/Makefile.am
- fabtests/test_configs/shm/cuda.exclude
Slurm partition name is getting passed in as the device when it shouldn't be.
Add cuda.exclude file for failing cuda tests that need to be revisited in the future
> contrib/intel/jenkins: Fix bug where shm device is slurm partition

- fabtests/scripts/runfabtests.py
This resolves issues when `junitparser` isn't available in `PATH` (or whatever `os.system` searches)
> fabtests: Utilize `junitparser` module directly

- fabtests/common/hmem_cuda.c
this meant to check whether or not dlsym succeeded in resolving cuMemGetHandleForAddressRange but instead checked cuPointerSetAttribute
> fabtests: cuda dmabuf: fix dlsym check

- prov/verbs/src/verbs_cm.c
- prov/verbs/src/verbs_cq.c
- prov/verbs/src/verbs_domain.c
- prov/verbs/src/verbs_ep.c
- prov/verbs/src/verbs_eq.c
- prov/verbs/src/verbs_init.c
- prov/verbs/src/verbs_ofi.h
The PR reworks the verbs provider to avoid blocking the caller in `rdma_resolve_route()`. 
The solution I implemented is based on the following TODO from `vrb_create_ep()`:
```
/* TODO convert this call to non-blocking (use event channel) as well:
* This may likely be needed for better scaling when running large
* MPI jobs.
* Making this non-blocking would mean we can't create QP at EP enable
* time. We need to wait for RDMA_CM_EVENT_ADDR_RESOLVED event before
* creating the QP using rdma_create_qp. It would also require a SW
* receive queue to store recvs posted by app after enabling the EP.
*/
```
Fixes #9494
> prov/verbs: Non blocking EP creation (asynchronous route resolution using event channel)

- fabtests/functional/rdm_stress.c
- fabtests/ubertest/test_ctrl.c
414806: Fix resouce leak
414801, 414809: Replace rand() use with custom get_random_data() that does the same thing but uses /dev/urandom to get the data.
> fabtests: Fix coverity issues 414806, 414801, 414809

- src/xpmem.c
The offset into the XPMEM memory to be copied is calculated on the receiving end. This introduces a constraint on caching. XPMEM code calculates the memory to map to the beginning of the nearest page to the start address and the length to the bottom of the last page. It then caches that memory region and attaches to it if necessary. The offset is calculated based on the original address sent and the address which is calculated for attaching. After getting the mapped address, the copy is done from the mapped address plus the offset.
When searching the cache a cache hit is found if the address being searched is within a memory regions which has already been cached. However, this introduces an issue for XPMEM. Here is an example to illustrate the issue:
address being looked up: …
> prov/xpmem: Fix xpmem memory corruption

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/tests.py
The performance is really bad and takes very long. Until we debug it the ZE IPC path it will be disabled and will use SAR instead.
> contrib/intel/jenkins: Disable ZE IPC path and use SAR instead

- .github/workflows/scorecard.yml
This github action runs OSSF scorecard everyday at 4:00 PM Pacific Time and also updates the score on scorecard badge.
Currently, the scorecard is only run once a week and needs to be run daily to keep the score current.
> .github/workflows: Add scorecard.yml

- prov/shm/src/smr_util.h
Move all of the 8 byte fields together to eliminate extra padding. Previously, the last 8 byte field was after a 4 byte field, forcing the compiler to add extra padding before the 4 byte field and after the third 8 byte field. This increased the size of the memory region and pushed some fields to a new cache line. Consolidating them eliminates those extra bytes and allows for better caching performance.
This also adds a reserved value to force alignment of the next 32 bit field though the compiler should automatically add that memory anyway.
Altering the order of the fields in the shared memory region requires a version increment.
> prov/shm: manually align 8 byte fields in memory region

- man/fi_setup.7.md
`fi_cq_readerr` was previously called on uninitialized `.err_data` and `.err_data_size` in a code snippet from [fi_setup.7.md](https://github.com/ofiwg/libfabric/blob/8b402387c12b9a1ec6a96f600daa726b2b21cb8c/man/fi_setup.7.md#retrieving-errors):
```c
/* Sample error handling */
struct fi_cq_msg_entry entry;
struct fi_cq_err_entry err_entry;
int ret;
ret = fi_cq_read(cq, &entry, 1);
if (ret == -FI_EAVAIL)
ret = fi_cq_readerr(cq, &err_entry, 0);
```
According to [fi_cq.3.md](https://github.com/ofiwg/libfabric/blob/8b402387c12b9a1ec6a96f600daa726b2b21cb8c/man/fi_cq.3.md#completion-fields) however, both `.err_data` and `.err_data_size` must be initialized prior to any call to `fi_cq_readerr`.
> `err_data` : The err_data field is used to return provider specific information, if available, …
> man: Fix uninitialized err_entry

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/build.py
- contrib/intel/jenkins/summary.py
- Add OneCCL DSA stage.
- There was an issue with libfabric being built with ze and oneccl built without.
This led to failure and CCL transport being switched to MPI because oneccl looked for the library.
To avoid this, an else case is added with --with-ze=no.
- Update oneccl summarizer to support DSA + shm summary.
- Add the logic to check whether DSA was actually used or not.
> Intel/CI: Add OneCCL CPU tests with DSA + shm to the CI

- prov/shm/src/smr_util.h
Move all of the 8 byte fields together to eliminate extra padding. Previously, the last 8 byte field was after a 4 byte field, forcing the compiler to add extra padding before the 4 byte field and after the third 8 byte field. This increased the size of the memory region and pushed some fields to a new cache line. Consolidating them eliminates those extra bytes and allows for better caching performance.
This also adds a reserved value to force alignment of the next 32 bit field though the compiler should automatically add that memory anyway.
Altering the order of the fields in the shared memory region requires a version increment.
Cherry-picked from commit d9517e54289c2075f2ad3064a3be5f547b7527ce
> [v1.21.x] prov/shm: manually align 8 byte fields in memory region

- prov/efa/src/dgram/efa_dgram_ep.c
- prov/efa/src/efa_av.c
- prov/efa/src/efa_cq.h
- prov/efa/src/rdm/efa_rdm_cq.c
- prov/efa/src/rdm/efa_rdm_ep_progress.c
- prov/efa/src/rdm/efa_rdm_ep_utils.c
- prov/efa/src/rdm/efa_rdm_pke_cmd.c
- prov/efa/src/rdm/efa_rdm_pke_nonreq.c
- prov/efa/src/rdm/efa_rdm_pke_rta.c
- prov/efa/src/rdm/efa_rdm_pke_rtm.c
- prov/efa/src/rdm/efa_rdm_pke_rtr.c
- prov/efa/src/rdm/efa_rdm_pke_rtw.c
- prov/efa/src/rdm/efa_rdm_pke_utils.c
- prov/efa/src/rdm/efa_rdm_rma.c
This is simply a best-effort attempt at removing some of the overridden error codes that are returned from core Libfabric functions. There are also a few random commits for minor code touchups.
Special attention appreciated for signedness - it's an easy thing to goof up.
> prov/efa: Propagate error codes from core Libfabric functionality untouched

- .github/workflows/pr-ci.yml
I couldn't find any context why Ubuntu 20.04 would be explicitly required for our Actions workflows. Feel free to discard otherwise.
This simplifies the testing matrix and allows us to test with the minimum required LTTng version without needing to deal with the flaky PPA repo for Ubuntu 20.04.
> .github/workflows: Use latest Ubuntu

- prov/efa/src/efa_domain.c
- prov/efa/src/efa_domain.h
- prov/efa/src/rdm/efa_rdm_peer.c
- prov/efa/src/rdm/efa_rdm_peer.h
- prov/efa/src/rdm/efa_rdm_pke_nonreq.c
- prov/efa/src/rdm/efa_rdm_pke_rtm.c
Make the inflight read msg counter per domain rather than per peer.
This counter is used to prevent using runting read when EFA is busy with a read, since in that case runting read would be less performant than a read.
Since any ongoing read, regardless of peer, makes EFA busy the counter should be domain scoped and not peer scoped.
cherry-picked from @ygoldamzn 's PR in https://github.com/aws/libfabric/pull/13
> prov/efa: Make the inflight read msg per domain

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/build.py
- contrib/intel/jenkins/summary.py
- contrib/intel/jenkins/tests.py
Pick CI changes from #9903 and #9904
> [v1.21.x] contrib/intel/jenkins: Pick CI changes for release

- .github/workflows/codeql.yml
This tool runs codeQL github action per PR, per push and everyday at 4 PM PST.
CodeQL checks the code to find security vulnerabilities and automatically uploads the results to GitHub so they can be displayed on pull requests.
Each scan of C language takes ~15 mins and python scan takes ~2 mins.
> .github/workflows: Add codeql.yml file

- prov/efa/src/rdm/efa_rdm_ep_utils.c
Now all tx pkt entry has ope and we
have an assert at the beginning of this
function.
Fix Coverity #413382
> prov/efa: remove unnecessary ope check

- AUTHORS
- NEWS.md
- configure.ac
- fabtests/configure.ac
- include/windows/config.h
For CI testing. Please do not merge. Will be pushed directly.
> v1.21.0rc2

- .github/dependabot.yml
Enables dependabot tool and checks for any version updates to all the github actions weekly on Mondays.
Dependabot.yml file needs to be in .github folder as opposed to .github/workflows like all other workflow yml files since .github folder is checked by github actions and also by OSSF scorecard.
> .github: Add dependabot.yml file

- prov/coll/src/coll_coll.c
CID 407572: Data race condition (MISSING_LOCK)
Accessing av_set->av->av_set without holding lock util_av.lock. Elsewhere, util_av.av_set is written to with util_av.lock held 1 out of 1 times (prov/util/src/util_av.c: ofi_av_close()).
> prov/coll: Fix Coverity issue about race condition accessing av->av_set

- prov/efa/src/efa_shm.c
app_info is the same with the info passed
by application in fi_domain, so it
cannot be NULL.
Fix  coverity issue 384053
> prov/efa: remove unnecessary app_info check

- prov/efa/src/rdm/efa_rdm_cq.c
Currently, efa_rdm_cq_poll_ibv_cq always assigns err_entry as {0} at the beginning while err_entry is only used in the error path. This unconditional assignment (88 bytes) caused additonal overhead in the fast path. This patch fixes it by moving the assignment of err_entry to the error path only
> prov/efa: Remove unconditional assignment of err_entry

- prov/efa/src/rdm/efa_rdm_cq.c
backport https://github.com/ofiwg/libfabric/pull/9942
> [v1.21.x] prov/efa: Remove unconditional assignment of err_entry

- prov/efa/src/efa_cq.h
- prov/efa/src/rdm/efa_rdm_cq.h
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
Two cleanup changes
* Remove unused cq_attr in efa_rdm_ep_open
* Move the declaration of efa_rdm_cq_poll_ibv_cq from efa_cq.h to efa_rdm_cq.h because it is specific for RDM endpoint
> prov/efa: Two cleanup changes

- prov/opx/include/opx_shm.h
- prov/opx/include/rdma/opx/fi_opx_endpoint.h
- prov/opx/src/fi_opx_hfi1.c
- prov/opx/src/fi_opx_reliability.c
Remove busy-waiting/sleeping while SHM FIFO has not been created/initialized. Cast result of CPU_ISSET() to a uint64_t to fix a coverity warning about potentially left-shifting by more than 31 bits. Whitespace/formatting fixups.
This should fix most of, if not all of, the 37 "Waiting while holding a lock" Coverity scan defects (numerous CIDs).
It should also address the bad bit-shift operation (CID 376792) defect.
Lots of whitespace/formatting changes (removing trailing whitespace, proper tab use).
> prov/opx: Fix Coverity scan waiting while holding lock errors.

- .github/workflows/gh-man.yaml
- .github/workflows/nroff-elves.yaml
The man page converter and updater need content write permission to perform push operation.
> github/workflows: Add needed permissions

- fabtests/common/shared.c
- fabtests/component/sock_test.c
Currently the listen() call has a 0 value for backlog. This causes syn (synchronize) flooding on port 3000. Port 3000 is used by fabtests for OOO (out of bounds) exchanges.
This call needs to have a non-zero positive value for backlog to prevent this flooding. Setting the backlog is necessary so that it is changeable by the user and not hidden values that users must set at the kernel level. The kernel variables are called net.ipv4.tcp_max_syn_backlog, and net.core.somaxconn to fix the issue instead. However, it is encouraged that a user make sure all of these values are set appropriately as well as using an adequate size for backlog in the listen call.
> fabtests: Add backlog > 0 to listen call

- prov/efa/src/rdm/efa_rdm_cq.c
When ibv_start_poll or ibv_next_poll return error, it may read a cqe from a destroyed EP (QP). In this case we shouldn't call efa_rdm_cq_get_prov_errno, which may use a freed EP from the pkt_entry (wr_id) and cause segmentation fault.
> prov/efa: Fix error handling in efa_rdm_cq_poll_ibv_cq

- prov/efa/src/rdm/efa_rdm_cq.c
Backport https://github.com/ofiwg/libfabric/pull/9973
> [v1.21.x] prov/efa: Fix error handling in efa_rdm_cq_poll_ibv_cq

- man/fi_pingpong.1.md
- util/pingpong.c
First commit is cleanup.  Second commit adds source address parameter to fix issue #9900, using fi_pingpong in multi-adapter environment.
> Couple fixes to fi_pingpong

- util/pingpong.c
> util/pingpong: Fix out of scope addrinfo memory leak

- contrib/intel/jenkins/Jenkinsfile
No need to run Intel CI when all of a PR's code changes are to contrib/aws
> contrib/intel/jenkins: Add new AWS CI to Intel CI's opt out path

- fabtests/functional/rdm_tagged_peek.c
The tx_attr and the sender should align with the rx_attr at the receiver. For peek test, the receiver can request messages out of order, but the tag matching has to be done in order.
> fabtests/rdm_tagged_peek: Align rx's msg_order with tx's

- prov/efa/src/efa_cntr.c
- prov/efa/src/efa_cntr.h
- prov/efa/src/rdm/efa_rdm_cq.c
Backport https://github.com/ofiwg/libfabric/pull/9991
> [v1.21.x] prov/efa: Use srx lock from domain directly

- include/windows/osd.h
- prov/efa/src/efa_errno.h
- prov/efa/src/rdm/efa_rdm_cq.c
- prov/efa/src/rdm/efa_rdm_pke_cmd.c
- prov/efa/src/rdm/efa_rdm_pke_cmd.h
- prov/efa/test/efa_unit_test_cq.c
This adds a rudimentary function to map proprietary EFA status codes to common Libfabric status codes. This is useful when reporting errors to the application for operations that rely solely on ibverbs or RDMA Core, such as CQ polling.
> prov/efa: Map EFA errnos to Libfabric codes

- prov/efa/src/efa_errno.h
This is for a future minor change to RDMA core, but should be safe to merge ahead of time.
> prov/efa: Add RDMA core errno for remote invalid AH

- prov/usnic/src/usdf_av.c
- prov/usnic/src/usdf_pep.c
- prov/usnic/src/usnic_direct/libnl_utils_common.c
- prov/usnic/src/usnic_direct/usd_queues.c
- prov/usnic/src/usnic_direct/usd_vnic.c
See individual commit messages for details.
> Fix usNIC CIDs

- fabtests/prov/efa/src/rdm_rnr_read_cq_error.c
Currently, rdm_rnr_read_cq_error.c reuse the same comp_err between different fi_cq_readerr, which is wrong because the err_entry has fields as both input and output. The outputted err_entry fields cannot be used as the input for the next call because some of them will be invalid, such as err_entry.err_data. Same issue applies to the completion entry for fi_cq_read.
This patch fixes this issue by declaring comp and comp_err within the block that calls fi_cq_read and fi_cq_readerr.
> fabtests/efa: reset error completion entry for each fi_cq_readerr call

- prov/efa/src/rdm/efa_rdm_pke_req.c
- prov/efa/src/rdm/efa_rdm_pke_req.h
- prov/efa/src/rdm/efa_rdm_protocol.h
AFAICT, This field only corresponds to `fi_cq_tagged_entry.data`, which is a `uint64_t`.
> prov/efa: Fix `cq_data` data type

- prov/shm/src/smr_progress.c
When atomic hmem support was added, a bounce buffer was added to act as a staging buffer for the atomic buffer since we can't access the hmem memory directly. The buffer for FI_ATOMIC_READ wasn't updated appropriately resulting in the incorrect data being copied back to the sender.
> prov/shm: fix atomic read

- prov/efa/src/rdm/efa_rdm_pke_utils.h
The order of payload_offset and segment_offset is flipped in the declaration of efa_rdm_pke_init_payload_from_ope. It didn't introduce trouble today because these two arguments have the same data type.
> prov/efa: Correct the order of arguments in declaration

- prov/shm/src/smr_progress.c
When atomic hmem support was added, a bounce buffer was added to act as a staging buffer for the atomic buffer since we can't access the hmem memory directly. The buffer for FI_ATOMIC_READ wasn't updated appropriately resulting in the incorrect data being copied back to the sender.
Cherry-picked from commit 21a8d97bbe59aa5410d88bb5cf8587346d94eb8c
> [v1.21.x] prov/shm: fix atomic read

- prov/shm/src/smr_progress.c
When atomic hmem support was added, a bounce buffer was added to act as a staging buffer for the atomic buffer since we can't access the hmem memory directly. The buffer for FI_ATOMIC_READ wasn't updated appropriately resulting in the incorrect data being copied back to the sender.
Cherry-picked from commit 21a8d97bbe59aa5410d88bb5cf8587346d94eb8c
> [v1.20.x] prov/shm: fix atomic read

- man/fi_getinfo.3.md
Remove the space between fi_av and its url
> man/fi_getinfo: Fix markdown typo

- src/xpmem.c
> xpmem: pointer of type ‘void *’ used in arithmetic

- prov/efa/src/rdm/efa_rdm_cq.c
- prov/efa/test/efa_unit_test_cq.c
- prov/efa/test/efa_unit_test_ep.c
- prov/efa/test/efa_unit_test_mocks.c
- prov/efa/test/efa_unit_test_mocks.h
Currently, we get ep pointer from the pkt_entry (wc's wr_id), which may be not reliable because some wc can be unsolicited (there is no pkts that the wc consumes thus no valid wr_id). This patch changes this mechanism to be deriving ep from the wc's qpn, which is always available and reliable. This is also what we are doing for dgram cq which is closest to rdma-core interface.
> prov/efa: Get efa_rdm_ep from wc's qpn

- prov/efa/docs/efa_rdm_protocol_v4.md
- prov/efa/src/rdm/efa_rdm_pke_req.c
- prov/efa/src/rdm/efa_rdm_util.h
We are moving to a different direction that doesn't require CQ data to be part of the hdr. Revert this change for now.
This reverts commit 90cd7d5f2d948b1042f20635536ac0eafa485437.
> Revert "prov/efa: Include CQ data header in prefix size"

- contrib/intel/jenkins/Jenkinsfile
OneCCL GPU tests require to use new node which is available with torchic partition.
> Intel/CI: Update oneCCL GPU stage to use torchic partition

- prov/efa/configure.m4
- prov/efa/src/efa_base_ep.c
- prov/efa/src/efa_cq.h
- prov/efa/src/efa_device.c
- prov/efa/src/efa_device.h
- prov/efa/src/rdm/efa_rdm_cq.c
This patch onboards EFA provider with the rdma-core feature that supports unsolicited RDMA write with immediate receive
https://github.com/linux-rdma/rdma-core/pull/1459
. When a rdma-write with imm is unsolicited, libfabric won't release the rx pkt and bump the rx pkt counters.
> prov/efa: Support unsolicited RDMA write with immediate receive

- contrib/intel/jenkins/Jenkinsfile
DMABUF tests require to use new node which is available with torchic partition.
There is no need for 2 node tests hence the two node tests have been removed.
Log file name has been changed and number of nodes have been removed.
> Intel/CI: Update DMABUF stage to use torchic partition

- prov/efa/src/efa_hmem.c
- prov/efa/src/efa_hmem.h
- prov/efa/src/efa_mr.c
- prov/efa/src/efa_mr.h
Introduce a boolean dmabuf_supported in efa_hmem_info, check if dmabuf is supported for different hmem ifaces.
When dmabuf is supported, retrieve the dmabuf fd and use ibv_reg_dmabuf_mr to register memory. 
Otherwise, fall back to ibv_reg_mr. 
Always use ibv_reg_dmabuf_mr when FI_MR_DMABUF is set.
Remove macros in efa_mr_reg_ibv_mr and combine duplicate logic of different hmem ifaces.
> prov/efa: Refactor dmabuf reg

- include/ofi_util.h
- prov/util/src/util_attr.c
- prov/util/src/util_main.c
This commit addresses issue #9443 for tcp provider. 
A new api ofi_match_addr_format() has been introduced to match the exact addressing format with user requested format while running fi_info test with -a option.
Testing:
> fi_info -p tcp -a FI_SOCKADDR_IN -vvv | grep sockaddr
src_addr: fi_sockaddr_in://192.168.5.254:0
src_addr: fi_sockaddr_in://192.168.1.254:0
src_addr: fi_sockaddr_in://10.23.219.26:0
src_addr: fi_sockaddr_in://127.0.0.1:0
src_addr: fi_sockaddr_in://192.168.5.254:0
src_addr: fi_sockaddr_in://192.168.1.254:0
src_addr: fi_sockaddr_in://10.23.219.26:0
src_addr: fi_sockaddr_in://127.0.0.1:0
src_addr: fi_sockaddr_in://192.168.5.254:0
src_addr: fi_sockaddr_in://192.168.1.254:0
src_addr: fi_sockaddr_in://10.23.219.26:0
src_addr: fi_sockaddr_in://127.0.0.1:0
src_addr: …
> prov/util: Fix issue while displaying addresses with fi_info -a <addr_format>

- contrib/intel/jenkins/Jenkinsfile
OneCCL GPU tests require to use new node which is available with torchic partition.
DMABUF tests require to use new node which is available with
torchic partition.
There is no need for 2 node tests hence the two node tests have
been removed.
> [v1.20.x] Intel/CI: Cherry-pick oneccl gpu stage and dmabuf stage commits

- contrib/intel/jenkins/Jenkinsfile
OneCCL GPU tests require to use new node which is available with torchic partition.
DMABUF tests require to use new node which is available with
torchic partition.
There is no need for 2 node tests hence the two node tests have
been removed.
> V1.21.x Intel/CI: Cherry-pick oneccl gpu stage and dmabuf stage commits

- prov/efa/src/efa_base_ep.h
- prov/efa/src/rdm/efa_rdm_ep_progress.c
- prov/efa/src/rdm/efa_rdm_ep_utils.c
- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/src/rdm/efa_rdm_pke.c
- prov/efa/src/rdm/efa_rdm_pke.h
For send, only respect FI_MORE for eager pkt type
because
1. For some non-REQ pkts like CTSDATA, its current implementation
relies on the logic that efa_rdm_ope_post_send always rings the doorbell,
because the ep progress call will keep calling this function until
ope->window is 0, but ope->window will only be decremented after
the CTSDATA pkts are actually posted to rdma-core.
2. For non-eager REQ packets, we already send multiple pkts that contain
data and make the firmware saturated, there is no value to queue
pkts in this case.
> prov/efa: Implement FI_MORE for send and rdma-write

- fabtests/benchmarks/benchmark_shared.c
- fabtests/common/shared.c
- fabtests/include/shared.h
Currently, ft_post_inject_buf doesn't support posting fi_injectdata and fi_tinjectdata when given a cq data. This patch adds such feature without changing the current tests' behavior
> fabtests: support testing inject with cq data

- prov/efa/src/rdm/efa_rdm_msg.c
- prov/efa/src/rdm/efa_rdm_pke_rtm.c
Currently, efa_rdm_pke_rtm_update_rxe updates rxe->tag and rxe->cq_entry.tag for both untagged and tagged operations. This is a bug because it should be updated for ofi_op_tagged operation only.
> prov/efa: Only update tag in rxe for tagged operation.

- fabtests/pytest/common.py
This patch improves the client-server test timeout behavior in 2 ways:
- Save client process output to a file instead of reading from pipe. Currently if the client times out, there is a chance that we cannot read the output.
- Add additional timeout in process.communicate to account for the overhead in process startup.
> fabtests/pytest: improve client-server test timeout behavior

- prov/efa/src/rdm/efa_rdm_pke_utils.c
Efa can directly access memory if the buffer is host memory and the pkt size (hdr + data) is within inline buf size. Libfabric doesn't need to memcpy in this case.
> prov/efa: do not do copy for inline send

- libfabric.vcxproj
- prov/efa/Makefile.include
- prov/efa/docs/pkt-processing.md
- prov/efa/src/efa_cntr.c
- prov/efa/src/efa_domain.c
- prov/efa/src/efa_domain.h
- prov/efa/src/rdm/efa_rdm_cq.c
- prov/efa/src/rdm/efa_rdm_cq.h
- prov/efa/src/rdm/efa_rdm_ep.h
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/src/rdm/efa_rdm_ep_utils.c
- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/src/rdm/efa_rdm_ope.h
- prov/efa/src/rdm/efa_rdm_peer.c
- prov/efa/src/rdm/efa_rdm_peer.h
- prov/efa/src/rdm/efa_rdm_pke_cmd.c
- prov/efa/src/rdm/efa_rdm_pke_nonreq.c
- prov/efa/test/efa_unit_test_cq.c
- prov/efa/test/efa_unit_test_ep.c
This patch includes two aspects of changes that get rid
of the ep_list iteration in cq and cntr progress.
1. Pre-post the internal rx pkts and grow pools during ep enable,
and only repost rx pkts when the ep has recv wc.
2. Move the rnr backoff peer list and other queued ope/pkt lists
into efa_domain, so fi_cq_read can progress these lists once
no matter how many eps are bind.
These 2 changes finally make efa_rdm_ep_progress.c not useful
because there is no dedicated progress for each ep any more.
> prov/efa: Avoid iterating cq->ep_list in cq read

- include/rdma/fi_endpoint.h
- man/fi_endpoint.3.md
Today, `ep_attr->max_msg_size` and `tx_attr->inject_size` define the transport's size limitation for a single data transfer operation. It lacks the flexibility to allow providers having different limits on different categories of operations (msg/tagged/rma/atomic). At the same time, applications can't express usage models that have very different size limits (e.g, only need small send/recv, but want large RMA).
Here a set of options are added to the fi_getopt()/fi_setopt() interface. These options allow the maximum message size and inject size be retrieved or set independently for msg/tagged/rma/atomci operations. The existing definition of `ep_attr->max_msg_size` and `tx_attr->inject_size` remain unchanged -- they are the upper bound of the limits for all the data transfer functions.
A …
> core: Add endpoint options for max message size and inject size

- fabtests/pytest/common.py
> [v1.21.x] Backport pr10063

- prov/efa/src/efa_domain.c
- prov/efa/src/efa_domain.h
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/src/rdm/efa_rdm_ope.h
- prov/efa/src/rdm/efa_rdm_pke_cmd.c
Combine ope_queued_rnr_list, ope_queued_ctrl_list
and ope_queued_read_list in to one list: ope_queued_list. One op entry can only be queued for 1 reason at the same time so there is no value to maintain 3 separate lists
> prov/efa: merge multiple ope queued list

- include/ofi.h
- include/windows/osd.h
- prov/sockets/src/sock_cntr.c
- prov/sockets/src/sock_wait.c
- src/common.c
- src/unix/osd.c
[src/common]: added ofi_get_realtime intefaces to support pthread_cond_timedwait which use CLOCK_REALTIME.In general CLOCK_MONOTONIC is preferred and in use by several providers, therefore new interfaces are added to support the special case of pthread apis.(ref #9614 )
[prov/sockets]: changes made to use ofi_get_realtime instead of ofi_get_time before ofi_wait_cond.
Signed-of-by: Nikhil Nanal <nikhil.nanal@intel.com>
> Added ofi_gettime interfaces to support CLOCK_REALTIME

- prov/efa/src/rdm/efa_rdm_pke_utils.c
This change caused some unexpected message truncation error. Revert it first before further investigation.
This reverts commit 7f7c94d676d41b09bcc7b71a4a434592a8c7490d.
> Revert "prov/efa: do not do copy for inline send"

- contrib/aws/Jenkinsfile
- prov/efa/src/efa_domain.c
- prov/efa/src/efa_domain.h
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/src/rdm/efa_rdm_ope.h
- prov/efa/src/rdm/efa_rdm_pke_cmd.c
The earlier queue list merge caused a hang on platforms that use long-CTS protocol. 
Having a single queue can reduce the number of queues for a idle polling, but may introduce race conditions
between different queued entries and cause more entries
to poll in the busy loop.
We will revert this change first and revisit it later.
Also add c5n test for efa provider in AWS CI
> prov/efa: revert queued list merge and add c5n test for efa provider

- include/rdma/fi_domain.h
- man/fi_mr.3.md
- prov/util/src/util_mr_map.c
The following series of commits updates documentation and defines new fields to enable use-cases which may result in VA to PA changes with memory being registered.
> Support for VA to PA changes

- fabtests/Makefile.am
- fabtests/benchmarks/benchmark_shared.c
- fabtests/pytest/efa/test_rma_pingpong.py
- fabtests/pytest/shm/test_rma_pingpong.py
1. The fixture memory_type was missing in test_rma_pingpong_range_no_inject
2. The RMA pingpong test should not run with 0-byte messages as zero-sized transfers are not supported. We should use different message sizes for rma pingpong, starting from non-zero values.
> Fabtest: test_rma_pingpong bugfix

- prov/efa/src/efa_device.c
These calls are not called when there is no efa device.
it is unnecessary to check g_device_cnt again in the call.
> prov/efa: Remove unnecessary g_device_cnt check.

- prov/efa/src/rdm/efa_rdm_cq.c
efadv_wc_is_unsolicited() can only be called when driver/FW supports unsolicited write recv, in which we create IBV CQ with EFADV_DEVICE_ATTR_CAPS_UNSOLICITED_WRITE_RECV. Otherwise the function pointer will be a NULL and cause segfault.
> prov/efa: Fix efa_rdm_cq_wc_is_unsolicited check

- src/hmem_cuda.c
This fixes a potential issue where the runtime API was erroneously called after a driver API call.
> hmem/cuda: Fix `cuDeviceCanAccessPeer()` error reporting

- include/ofi_iov.h
- prov/hook/dmabuf_peer_mem/src/hook_dmabuf_peer_mem.c
- src/hmem.c
- src/iov.c
Fixes compilation issue reported in #10052.
> Fix incompatible pointer warnings on macOS with GCC 14

- fabtests/common/shared.c
- fabtests/functional/cm_data.c
- fabtests/functional/rdm.c
- fabtests/functional/rdm_multi_client.c
- fabtests/include/shared.h
- fabtests/ubertest/test_ctrl.c
- fabtests/ubertest/verify.c
fabtests: Synchronize on Initialization
fabtests/functional: Add manual init sync to fi_rdm_multiclient
Some providers (verbs ud) might require the server to be fully initialized before the client process calls getinfo with the server address. This causes a No Data Available error due to the fi_info call failing during initialization by not being able to find the name on the server. This is seen most often in cases where a socket (usually oob [out of band]) is initialized before getinfo in the ft_init_fabric sequence. Adding a sync only if an oob socket has been initialized to order the initialization correctly will prevent this from happening.
The syncronization is for client to start getinfo only after the server is done initializing everything.
fi_rdm_multiclient test needs its client …
> fabtests: Synchronize on Initialization

- prov/efa/src/rdm/efa_rdm_ep.h
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/src/rdm/efa_rdm_ep_utils.c
- prov/efa/src/rdm/efa_rdm_msg.c
- prov/efa/src/rdm/efa_rdm_pke.c
- prov/efa/src/rdm/efa_rdm_pke.h
- prov/efa/src/rdm/efa_rdm_pke_cmd.c
- prov/efa/src/rdm/efa_rdm_pke_rtm.c
Allocate user posted rx pkts from a separate user_rx_pkt_pool.
Posting user recv buffer to user recv QP without prefix.
>  prov/efa: Post user recv buffer to user recv QP

- fabtests/test_configs/psm3/psm3.exclude
- fabtests/test_configs/ucx/ucx.exclude
fi_rdm_tagged_peek fails to cleanup with "munmap_chunk(): invalid pointer" when trying to free hfi_nids in psm_ep.c:1161.
This test is successful when FI_PROVIDER is unset and fails when it is set to "psm3" or "PSM3". There is an open issue in ofiwg/libfabric to track this bug. When it is resolved we can re-enable this test.
Issue opened: #10123
fi_rdm_tagged_peek fails to cleanup with "segmentation failt" when trying to cleanup the endpoint.
This failure is a race condition and has no known 100% fail case.
Issue opened: #10126
> fabtests: Disable fi_rdm_tagged_peek for cleanup failure for psm3 and ucx

- man/fi_verbs.7.md
- prov/verbs/src/verbs_init.c
Let the user set the FI_VERBS_INLINE_SIZE environment variable to decide the maximum size of an inline transfer. The getinfo call will check if the device is capable of this size. If it is capable it will use it. If it not capable then the size is too big and we can goto the backwards search to find the largest inline size that is smaller than the FI_VERBS_INLINE_SIZE variable.
If a user wants the maximum inject size that a device can do then they should set this FI_VERBS_INLINE_SIZE variable to 0 so that the device can find its largest inject size.
> prov/verbs: Optimize search for device max inline size

- src/hmem_ze.c
ZE IPC implementation broken for newer Agamas. Disable until fixed
> src/hmem_ze: disable ZE IPC

- src/hmem_ze.c
ZE IPC implementation broken for newer Agamas. Disable until fixed
> [v1.21.x] src/hmem_ze: disable ZE IPC

- contrib/intel/jenkins/Jenkinsfile
Migrate all of fabtests to using the new CI.
Add support for new CI's summarizer.
Use both old CI and new CI summarizers to report all the tests.
All stages with new CI will be using the convention CI_ prefix.
> contrib/intel/jenkins: Migrate Fabtests to new CI model

- src/var.c
The wrong string was set to NULL when asprintf failed. This could cause undefined pointer being used later.
> core: Fix an error in the error handling path of fi_param_define()

- prov/efa/src/efa_cntr.c
- prov/efa/src/efa_cntr.h
- prov/efa/test/efa_unit_test_cntr.c
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
It may be possible that application (currently fabtests)
only use fi_cntr_read to poll completions without calling fi_cq_read. In this case, the first fi_cntr_read should post rx buffers to all bounded eps as well.
> prov/efa: Post rx buffer in the first fi_cntr_read

- prov/efa/src/efa_mr.c
> prov/efa: log hmem iface name instead of enum

- prov/efa/src/efa_hmem.c
- prov/efa/src/efa_mr.c
- src/hmem_neuron.c
If dmabuf is not supported, get_dmabuf_fd should return -FI_EOPNOTSUPP
> hmem,prov/efa: change neuron get_dmabuf_fd error code

- .github/workflows/clang-format-check-cn.yml
- .github/workflows/clang-format-check.yml
- .github/workflows/codeql.yml
- .github/workflows/coverity.yml
- .github/workflows/gh-man.yaml
- .github/workflows/nroff-elves.yaml
- .github/workflows/pr-ci.yml
- .github/workflows/stale.yml
OSSF scorecard has 1/10 score for pinned-dependencies. To increase this score all dependencies have to be pinned by hash.
OSSF help suggests using StepSecurity Tool to update the dependency. For more information:
https://github.com/ossf/scorecard/blob/7ce8609469289d5f3b1bf5ee3122f42b4e3054fb/docs/checks.md#pinned-dependencies
To check the list of dependencies flagged in report, go to Pinned-Dependencies section:
https://securityscorecards.dev/viewer/?uri=github.com/ofiwg/libfabric
> .github/workflows: Pin all dependencies by hash instead of version number

- prov/efa/Makefile.include
- prov/efa/configure.m4
- prov/efa/src/efa_domain.c
- prov/efa/src/efa_env.c
- prov/efa/src/efa_env.h
- prov/efa/src/efa_hmem.c
- prov/efa/src/efa_hmem.h
- prov/efa/src/efa_mr.c
- prov/efa/test/efa_unit_test_common.c
- prov/efa/test/efa_unit_test_ep.c
- prov/efa/test/efa_unit_test_hmem.c
- prov/efa/test/efa_unit_test_mocks.c
- prov/efa/test/efa_unit_test_mocks.h
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
This patch removes the trial device memory registration with EFA device during domain initialization; instead, we query the sysfs to retrieve the P2P provider information emitted by the kernel module.
As a result, we have to delay the dmabuf support status check to the 1st application fi_mr_reg* call:
- We always register the region via ibv_reg_dmabuf_mr if the application requests FI_MR_DMABUF
- We will disable dmabuf if the hmem interface does not have P2P support
- For the 1st fi_mr_reg* call, we will try ibv_reg_dmabuf_mr
- If the 1st fi_mr_reg* call failed via ibv_reg_dmabuf_mr, we will NOT try ibv_reg_dmabuf_mr again, but always fallback to ibv_reg_mr API for that hmem interface
- Otherwise we will always use ibv_reg_dmabuf_mr for that hmem interface
> prov/efa: refactor hmem interface initialization

- prov/efa/Makefile.include
- prov/efa/src/efa_domain.c
- prov/efa/src/efa_domain.h
- prov/efa/src/efa_mr.c
- prov/efa/test/efa_unit_test_mr.c
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
Introduce ibv_mr_reg_cnt and ibv_mr_reg_sz in efa_domain to record the total count and size of mr within the efa domain (ibv pd). Print the total mr count and size as part of the warning message from failed mr reg. This will help troubleshoot the ENOMEM error hit by customers that can be caused by MR exceeding the limit.
> prov/efa: Log MR consumption

- prov/efa/src/rdm/efa_rdm_pkt_type.h
- prov/efa/test/efa_unit_test_ep.c
Fix some unit test build warnings caused by https://github.com/ofiwg/libfabric/commit/94245648abed71e5a55c92cfeee682c3ba984821
> prov/efa: Fix unit test build warnings

- prov/efa/src/efa_strerror.c
efa_show_help() calls fprintf() to always print the error string. However, the context needed for that help to make any sense (the real error message) is in an EFA_WARN() block, so it doesn't print by default. This leads to some really weird log files, where only the show help string appears.
> prov/efa: Use EFA_WARN in efa_show_help

- fabtests/Makefile.am
- fabtests/Makefile.win
- fabtests/common/hmem.c
- fabtests/common/hmem_synapseai.c
- fabtests/common/shared.c
- fabtests/configure.ac
- fabtests/fabtests.vcxproj
- fabtests/fabtests.vcxproj.filters
- fabtests/include/hmem.h
- fabtests/man/fabtests.7.md
The following changes adds synapaseai support to fabtests' benchmark tests.
Choosing iface value of FI_HMEM_SYNAPSEAI will implicitly set option FT_OPT_REG_DMABUF_MR.
> fabtests/benchmarks: Add synapseai support

- include/ofi_rbuf.h
- src/mem.c
This commit fixes integer overflow issues detected by coverity.
> libfabric/core: Fix coverity issues 426807 and 426820

- fabtests/common/shared.c
- fabtests/include/shared.h
- fabtests/pytest/efa/conftest.py
- fabtests/pytest/efa/test_rdm.py
- prov/efa/src/rdm/efa_rdm_cq.c
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/src/rdm/efa_rdm_ep_utils.c
- prov/efa/src/rdm/efa_rdm_msg.c
- prov/efa/src/rdm/efa_rdm_pke.c
Backport https://github.com/ofiwg/libfabric/pull/10168
> [v1.22.x] fabtests, prov/efa: Add benchmark option for FI_OPT_MAX_MSG_SIZE

- contrib/intel/jenkins/Jenkinsfile
Keep job logs on failure
Make summary in post always do verbose first to properly view failing tests
Only run summary in post if opt-out path is not taken
Return shell error code properly for CI runner stages
> contrib/intel/jenkins: Minor Pipeline bugfixes

- man/fi_shm.7.md
- man/man7/fi_shm.7
- prov/shm/src/smr_dsa.c
- prov/shm/src/smr_init.c
Adding support for write() method to submit DSA work and changes to page fault handling
Will cherry-pick from 1.21.X to 1.22.X
> prov/shm: Add support for write() method to submit DSA work and changes to page fault handling

- prov/opx/include/rdma/opx/fi_opx_hfi1_sdma.h
- prov/opx/src/fi_opx_hfi1.c
Cornelis Networks bug fixes for v1.22.x:
- Improve performance by setting ACK bit when sending a single SDMA packet;
- Assert fix.
> Opx bug fixes for 1.22.x

- fabtests/configure.ac
This fix is a result of a change in the latest version of synapseai drivers
> fabtests/benchmarks: Fix synapseai fabtests build

- fabtests/configure.ac
- prov/opx/Makefile.include
Separate the two fixes from #10211 so these can be merged earlier while waiting for another patch before cutting the final release.
> [v1.22.x] Fixes for 1.22.0

- fabtests/pytest/shm/test_unexpected_msg.py
It is observed 1M caused some OOM error for some cuda allocation, 9000 should be big enough as it exceeds the shm's inject size.
> fabtests/pytest/shm: reduce the msg size in test_unexpected_msg

- man/fi_efa.7.md
- prov/efa/src/efa_base_ep.c
- prov/efa/src/efa_cq.h
- prov/efa/src/efa_env.c
- prov/efa/src/efa_env.h
- prov/efa/src/rdm/efa_rdm_cq.c
- prov/efa/src/rdm/efa_rdm_util.h
Introduce FI_EFA_USE_UNSOLICITED_WRITE_RECV which means whether to use the unsolicited write recv feature from device when it's available. Setting this variable to 0 will disable this feature.
> prov/efa: Allow disabling unsolicited write recv via env

- src/hmem_cuda.c
Move the libnvml.so -> libnvml.so.1 dlopen log from warning to info as they are informational only. Adjust the warning log when libnvlml.so.1 dlopen failure.
> hmem/cuda: Modify the logging for nvml dlopen

- contrib/aws/Jenkinsfile
CentOS 7 has reached EOL
(cherry picked from commit abb9edc9338d23df95d094c033dbc9c18ef7bb3d)
> [v1.22.x] contrib/aws: deprecate centos7 tests

- src/hmem_rocr.c
Two symbols were added to check for and then get the dmabuf fd. They were not initialized.
> hmem/rocr: Fix dmabuf for amd gpu implementation

- prov/efa/test/efa_unit_test_hmem.c
Fix a bug in ibv_reg_mr mocked function that did not have a return value.
> prov/efa: fix typo in hmem unit test

- src/hmem_rocr.c
Two symbols were added to check for and then get the dmabuf fd. They were not initialized.
> hmem/rocr: Fix dmabuf for amd gpu implementation - 1.21

- prov/efa/src/rdm/efa_rdm_ep_utils.c
- prov/efa/test/efa_unit_test_ep.c
When user doesn't register the recv buffer, libfabric should try to register it so it can be posted to device for receive. If the registration failed, an EAGAIN will be returned.
> prov/efa: Register user recv buffer for zero-copy receive mode

- fabtests/pytest/efa/test_rdm.py
- prov/efa/docs/efa_rdm_protocol_v4.md
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/test/efa_unit_test_ep.c
zero-copy receive cannot work with mixed efa and shm traffic, this patch makes shm disabling as a requirement for using zero-copy recv.
> prov/efa: Require shm to be disabled for using zero-copy recv

- fabtests/pytest/efa/test_rdm.py
- prov/efa/docs/efa_rdm_protocol_v4.md
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/src/rdm/efa_rdm_ep_utils.c
- prov/efa/test/efa_unit_test_ep.c
backport https://github.com/ofiwg/libfabric/pull/10259 and https://github.com/ofiwg/libfabric/pull/10258
> [v1.22.x] prov/efa: backport two zcpy changes

- src/hmem_rocr.c
Two symbols were added to check for and then get the dmabuf fd. They were not initialized.
> hmem/rocr: Fix dmabuf for amd gpu implementation - 1.22

- man/fi_endpoint.3.md
Otherwise, when rendered on the OFIWG site, it reads as if the restrictions only apply when the opt is set to `FI_HMEM_P2P_DISABLED`.
The formatting looks fine when previewed via GitHub - hopefully that carries over.
> man: Fix formatting for `FI_OPT_FI_HMEM_P2P` prose

- contrib/intel/jenkins/Jenkinsfile
Let run ci script properly sys.exit(error_code) instead of using Jenkins shell command to return the error code. This will make new CI stages properly fail when a test fails or if a job config is invalid.
Separate grass tests to be on different partitions. This will prevent tests from using a node from set one with a node from set two. These sets are going to be called bulbasaur and chikorita.
> contrib/intel/jenkins: Split jobs across nodes better & fail run_ci using script exit

- Makefile.am
- include/rdma/fabric.h
- include/rdma/fi_domain.h
- include/rdma/fi_tagged.h
- libfabric.def
- libfabric.map.in
- man/fi_atomic.3.md
- man/fi_av.3.md
- man/fi_domain.3.md
- man/fi_endpoint.3.md
- man/man3/fi_fabric2.3
- src/abi_1_0.c
- src/fabric.c
This is the second part of reworked #10009. It contains new features.
> 2.0 new features

- Makefile.am
- include/linux/osd.h
- include/ofi_hmem.h
- include/ofi_mr.h
- libfabric.vcxproj
- prov/shm/src/smr.h
- prov/shm/src/smr_ep.c
- prov/shm/src/smr_msg.c
- prov/shm/src/smr_progress.c
- prov/shm/src/smr_rma.c
- prov/shm/src/smr_util.c
- prov/shm/src/smr_util.h
- prov/util/src/util_mem_monitor.c
- prov/util/src/ze_ipc_monitor.c
- src/hmem.c
- src/hmem_cuda.c
- src/hmem_ipc_cache.c
- src/hmem_rocr.c
- src/hmem_ze.c
Refactor close_handle to add new field for ze pidfd method
Implement ze pidfd method for ze-ipc copies
Remove old method's (socket by path) code
> prov/shm: Re-enable ze-ipc with new pidfd method

- include/ofi_prov.h
The netdir provider has been removed. Remove the remaining of it from include/ofi_prov.h.
> Remove remaining of the netdir provider

- src/hmem_rocr.c
When calling rocr_is_addr_valid() with a host memory address, ofi_hsa_amd_pointer_info() will return success, but the pointer type will be set to HSA_EXT_POINTER_TYPE_UNKNOWN. In this case, avoid attempting to get device info, which will fail due to an invalid agent owner and output spurious log warnings.
> hmem/rocr: Don't attempt to get device info when pointer type is unknown.

- prov/verbs/configure.m4
- prov/verbs/src/verbs_ep.c
- prov/verbs/src/verbs_ofi.h
~The checks for the verbs provider can pass on a FreeBSD system, but will fail to compile because asm/types.h is not available.~
Updated description: 2024-08-01
The verbs provider uses asm/types.h for __BITS_PER_LONG, but that header
is limited to Linux systems. LONG_WIDTH is defined in C23 in
limits.h. Use it instead, and add logic to define it if not
available. This will allow the verbs provider to compile on FreeBSD
systems.
> prov/verbs: Replace __BITS_PER_LONG with LONG_WIDTH

- contrib/aws/Jenkinsfile
Amazon Linux 2023 has 6.x kernel which is not covered in CI.
Also test tcp/socket providers on non-EFA platforms to conserve capacity.
> contrib/aws: add coverage for Amazon Linux 2023

- include/ofi_enosys.h
- include/ofi_mem.h
- include/ofi_tree.h
- include/ofi_util.h
- libfabric.vcxproj
- libfabric.vcxproj.filters
- prov/tcp/Makefile.include
- prov/tcp/src/xnet.h
- prov/tcp/src/xnet_av.c
- prov/tcp/src/xnet_domain.c
- prov/tcp/src/xnet_rdm.c
- prov/util/src/util_av.c
- prov/util/src/util_buf.c
- src/enosys.c
- src/tree.c
In many multi-threaded workloads it's common for the application to manage many eps, each on their own threads, but under a single domain while setting their threading semantics as `FI_THREAD_COMPLETION`.  The tcp provider has been optimized for single threaded processes and doesn't do anything special for this use case.
Ideally, these applications would restructure their objects to follow `FI_THREAD_DOMAIN` semantics, with a domain per thread.
This set of changes introduces a path to handle `FI_THREAD_COMPLETION` semantics by multiplexing the application's domain over many 'subdomain' - one per ep - which each follow FI_THREAD_DOMAIN semantics.  Associated AVs and MRs will also be multiplexed.  CQs and CNTRs will be migrated to the appropriate subdomains.
> prov/tcp: optimize FI_THREAD_COMPLETION

- prov/util/src/rocr_mem_monitor.c
The name field in struct ofi_mem_monitor was not set in the #HAVE_ROCR case.  This update initializes the name to "rocr" in the rocr_monitor.
> prov/util: Initialize ROCR name in memory monitor struct

- prov/efa/src/rdm/efa_rdm_cq.c
Currently, efa_rdm_cq_poll_ibv_cq used dlist_foreach to iterate the eps, which involves the removal of ep's dlist entry. It is recommended to use dlist_foreach_*safe method to have additional tmp variable to store the entry->next pointer before dlist_remove(ep->entry). Though Libfabric's current dlist implementation doesn't really destroy ep->entry in dlist_remove, it may cause use-after-free error when the behavior changes in the future.
> prov/efa: Use dlist_foreach_container_safe to iterate progressed ep list

- prov/efa/Makefile.include
- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/test/efa_unit_test_mocks.c
- prov/efa/test/efa_unit_test_mocks.h
- prov/efa/test/efa_unit_test_ope.c
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
txe should be released when efa_rdm_ope_post_remote_read_or_queue returns error.
> prov/efa: Fix a memory leak in local read

- include/ofi_shm_p2p.h
- include/ofi_xpmem.h
- prov/shm/src/smr_progress.c
- prov/shm/src/smr_rma.c
- prov/shm/src/smr_util.h
- src/xpmem.c
- src/xpmem_cache.c
libxpmem defines symbols such as xpmem_init(void) which conflict with ofi. Prefix public xpmem symbols in ofi to avoid interposition.
> xpmem,shm: prefix public xpmem symbols with ofi

- prov/efa/src/rdm/efa_rdm_cq.c
backport https://github.com/ofiwg/libfabric/pull/10300
> [v1.22.x] prov/efa: Use dlist_foreach_container_safe to iterate progressed ep list

- fabtests/pytest/efa/test_rma_pingpong.py
(cherry picked from commit 2abe00b62ccf37dc7d12afe3a5a23f2067f6b52a)
> [v1.22.x] fabtests: Pass `memory_type` to client server test

- prov/efa/src/rdm/efa_rdm_ep_utils.c
In efa_rdm_ep_post_handshake, the pke exhaustion shouldn't be a warning as it is normal for a stressful receiver and should be handled by EAGAIN / flow control
> prov/efa: Adjust the logging for pke exhaustion

- include/ofi_shm_p2p.h
- include/ofi_xpmem.h
- prov/shm/src/smr_progress.c
- prov/shm/src/smr_rma.c
- prov/shm/src/smr_util.h
- src/xpmem.c
- src/xpmem_cache.c
libxpmem defines symbols such as xpmem_init(void) which conflict with ofi. Prefix public xpmem symbols in ofi to avoid interposition.
(cherry picked from commit 23973529c9e74b0562a0550d0fa3d863ee89d11a)
> [v1.22.x] xpmem,shm: prefix public xpmem symbols with ofi

- fabtests/common/hmem_synapseai.c
- fabtests/configure.ac
scal.h is not a public file. on next synapse release this commit will be updated to use a new synapse api.
> fabtests/synapse - remove dependency of scal

- prov/cxi/include/cxip.h
- prov/cxi/src/cxip_if.c
- prov/cxi/src/cxip_telemetry.c
Define cxi internal CXIP_PATH_MAX for use to avoid using PATH_MAX where appropriate for stack variables.
> prov/cxi: FI_PATH_MAX is removed in 2.0 API

- prov/efa/Makefile.include
- prov/efa/src/rdm/efa_rdm_pke_rtm.c
- prov/efa/test/efa_unit_test_pke.c
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
Fallback long cts rtm doesn't have any payload. In this case, this function shouldn't touch the tx entry as it may be released earlier as the CTSDATA pkts have already kicked off and finished the send.
> prov/efa: Correctly handle fallback longcts-rtm send completion

- prov/efa/Makefile.include
- prov/efa/src/rdm/efa_rdm_pke_rtm.c
- prov/efa/test/efa_unit_test_pke.c
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
backport https://github.com/ofiwg/libfabric/pull/10318
> [v1.22.x] prov/efa: Correctly handle fallback longcts-rtm send completion

- fabtests/benchmarks/benchmark_shared.c
- fabtests/common/shared.c
- fabtests/functional/inject_test.c
- fabtests/include/shared.h
- fabtests/pytest/efa/test_rdm.py
- fabtests/pytest/efa/test_rma_bw.py
- Add the option `--use-fi-more` to allow tests with FI_MORE flag set
- Run rdm_tagged_bw with `fi_sendmsg/fi_tsendmsg`, run rma write/writedata with `fi_writemsg` to allow testing with customized flags
- Add efa pytests with FI_MORE for `fi_rma_bw` and `fi_rdm_tagged_bw`
> fabtests: Add option for FI_MORE and fabtests with FI_MORE

- man/fi_domain.3.md
- man/fi_endpoint.3.md
Replace a few occurences of '**text**' with '*text*' for consistency. Remove unnecessary ':'s.
Also add a missing "deprecated" note.
> man: Fix mark-down formats

- prov/verbs/src/verbs_info.c
Reported by Coverity:
"Variable fi going out of scope leaks the storage it points to."
> prov/verbs: Fix resource leak in error handling path

- include/ofi.h
- include/rdma/providers/fi_peer.h
- man/fi_domain.3.md
- man/fi_getinfo.3.md
- man/fi_peer.3.md
- prov/efa/src/efa_shm.c
- prov/efa/src/rdm/efa_rdm_msg.c
- prov/shm/src/smr_attr.c
- prov/shm/src/smr_progress.c
- prov/sm2/src/sm2_progress.c
- prov/util/src/util_srx.c
- src/fi_tostr.c
Update srx flow to take in match attributes
Rename peer_rx_entry->size to msg_size and clarify usage in man pages
Update providers and implementation to match updates
Add FI_PEER as a primary capability which signals support for being used as a peer
> include/rdma, prov/shm,efa,util: fi_peer API changes

- fabtests/benchmarks/benchmark_shared.c
- fabtests/common/shared.c
- fabtests/include/shared.h
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/test/efa_unit_test_ep.c
This also:
- Calls `fi_setopt(..., FI_OPT_INJECT_{MSG,RMA}_SIZE)` if `-j` is specified
- Retrieves the inject size via `fi_getopt()` in the pingpong/bw fabtests functions; falling back to `fi->tx_attr->inject_size` unless `-j` was specified
- Adds support for `FI_OPT_INJECT_RMA_SIZE` in the EFA provider, which was overlooked originally
> fabtests: Utilize `fi_setopt`/`fi_getopt` sequence for inject size (`-j`), prov/efa: Update EP's `inject_size` in zero-copy mode

- fabtests/benchmarks/benchmark_shared.c
- fabtests/common/shared.c
- fabtests/include/shared.h
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/test/efa_unit_test_ep.c
> [v1.22.x] fabtests: Utilize `fi_setopt`/`fi_getopt` sequence for inject size (`-j`)

- prov/psm2/src/psmx2_cq.c
- prov/psm3/src/psmx3_cq.c
Use optimized lock function to unlock on CQ write error instead of direct unlock which causes an assert failure if FI_THREAD_DOMAIN is specified
> prov/psm2,psm3: fix incorrect unlock function

- prov/efa/src/dgram/efa_dgram_ep.c
In efa_dgram_ep_progress_internal, cq_entry was declared without initializing as 0. It casts this array's pointer into smaller structs like `fi_cq_entry` during the cq->read_entry call, which doesn't have the flags member, and then cast it back to fi_cq_tagged_entry which has flags. This finally makes the temp_cq_entry struct has a flags from uninitialized values and can cause illegal flags to be used in the cq write. This patch fixes issue by initializing the cq entry array as 0.
> prov/efa: Zero the cq entry array in dgram ep progress

- prov/efa/src/dgram/efa_dgram_ep.c
backport https://github.com/ofiwg/libfabric/pull/10345
> [v1.22.x] prov/efa: Zero the cq entry array in dgram ep progress

- prov/shm/src/smr.h
- prov/shm/src/smr_av.c
- prov/shm/src/smr_comp.c
- prov/shm/src/smr_ep.c
- prov/shm/src/smr_progress.c
- prov/shm/src/smr_util.c
- prov/shm/src/smr_util.h
Fix progress error cases to always be positive ints when calling write_err_comp
Make id always be valid when looking up if pid_fd has been set for level-zero
> prov/shm: Fix progress error cases and init id paths

- prov/efa/src/rdm/efa_rdm_ope.c
Currently, efa provider tries to register user buffer in transport in multiple places without checking whether application sets FI_MR_LOCAL, which is not complied with Libfabric standard. Add warning when application sets FI_MR_LOCAL but does not provide a valid desc parameter into applicable data transfer operations.
> prov/efa: Respect FI_MR_LOCAL in transport path

- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/src/rdm/efa_rdm_pke_utils.c
- prov/efa/src/rdm/efa_rdm_pke_utils.h
Currently EFA provider doesn't handle the *msg call with FI_INJECT flags correctly. It allows user to pass in a buffer with valid MR while doing inject - outbound buffer should be reusable immediately after function returns.
That being said, without the inline HW support, EFA provider should do a copy from the user buffer to the internal bounce buffer even if application provides a valid MR for the buffer.
The inject rdma write path assumes the outbound buffer is always FI_HMEM_SYSTEM, but it doesn't have to.
> prov/efa:  Fix fi_sendmsg/fi_writemsg with FI_INJECT

- fabtests/Makefile.am
- fabtests/common/shared.c
- fabtests/include/shared.h
- fabtests/multinode/include/core.h
- fabtests/multinode/src/core.c
- fabtests/multinode/src/harness.c
- fabtests/multinode/src/timing.c
- fabtests/scripts/runmultinode.py
Made a few updates to the multinode test:
1. accept a -x flag to turn off setting the service/node/flags
- this is needed to work with CXI
2. accept a -u flag to set a process manager: pmi or pmix
3. modify the code to get the rank from the appropriate environment variable if a process manager is specified.
4. Add a runmultinode.py script which enables users to run the test using a backing process manager. The python script takes a YAML configuration file which defines the environment and test. An example python configuration file:
multinode:
environment:
FI_MR_CACHE_MAX_SIZE: -1
FI_MR_CACHE_MAX_COUNT: 524288
FI_SHM_USE_XPMEM: 1
FI_LOG_LEVEL: info
bind-to: core
map-by-count: 1
map-by: l3cache
pattern: full_mesh
Script Usage:
usage: runmultinode.py [-h] [--dry-run] [--ci CI] [-C …
> fabtests: multinode test updates

- prov/tcp/src/xnet_rdm.c
this would address https://scan4.scan.coverity.com/#/project-view/61734/10344?selectedIssue=441178
> prov/tcp: initialize addr_size when duplicating an av

- prov/efa/src/rdm/efa_rdm_msg.c
- prov/efa/src/rdm/efa_rdm_rma.c
p2p is required for rdma read because the user buffer has to be registered to efa device.
Add p2p check for subprotocols that use RDMA read.
> prov/efa: Check p2p support to use rdma read

- prov/shm/src/smr_attr.c
SMR_DOMAIN_CAPS was recently added to include FI_PEER, FI_AV_USER_ID but a typo caused an smr_info data corruption
> prov/shm: fix incorrect capability set

- prov/efa/src/rdm/efa_rdm_ep_fiops.c
Disabling shm via fi_setopt shouldn't be a warning. Move the logging to info level.
> prov/efa: Adjust log level for shm disabling.

- prov/efa/docs/efa_rdm_protocol_v4.md
- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/src/rdm/efa_rdm_pke_nonreq.c
- prov/efa/src/rdm/efa_rdm_pke_rtm.c
- prov/efa/src/rdm/efa_rdm_pke_rtw.c
- prov/efa/src/rdm/efa_rdm_pke_utils.h
p2p is required for RDMA read because the user buffer has to be registered to efa device.
When p2p is not available, receiver should send a NACK packet to make sender fall back to long CTS protocol to avoid RDMA read.
> prov/efa: Use READ NACK protocol if P2P is not available for RDMA read

- prov/efa/docs/efa_rdm_protocol_v4.md
- prov/efa/src/rdm/efa_rdm_msg.c
- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/src/rdm/efa_rdm_pke_nonreq.c
- prov/efa/src/rdm/efa_rdm_pke_rtm.c
- prov/efa/src/rdm/efa_rdm_pke_rtw.c
- prov/efa/src/rdm/efa_rdm_pke_utils.h
- prov/efa/src/rdm/efa_rdm_pkt_type.h
- prov/efa/src/rdm/efa_rdm_rma.c
Backport https://github.com/ofiwg/libfabric/pull/10352 and https://github.com/ofiwg/libfabric/pull/10363
> [v1.21.x] prov/efa: Use emulated read or READ NACK protocol if P2P is not available for RDMA read

- prov/efa/docs/efa_rdm_protocol_v4.md
- prov/efa/src/rdm/efa_rdm_msg.c
- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/src/rdm/efa_rdm_pke_nonreq.c
- prov/efa/src/rdm/efa_rdm_pke_rtm.c
- prov/efa/src/rdm/efa_rdm_pke_rtw.c
- prov/efa/src/rdm/efa_rdm_pke_utils.h
- prov/efa/src/rdm/efa_rdm_rma.c
Backport https://github.com/ofiwg/libfabric/pull/10352 and  https://github.com/ofiwg/libfabric/pull/10363
> [v1.22.x] prov/efa: Use emulated read or READ NACK protocol if P2P is not available for RDMA read

- include/ofi_net.h
- include/ofi_util.h
- prov/util/src/util_av.c
- src/common.c
This prevents `(null)` from being logged when addr isn't compatible with `struct sockaddr`
> util/av: Log AV insert with AV's specified address format

- fabtests/prov/lpp/src/main.c
suppress compiler warning for non-debug build
> fabtests/lpp: Fix compiler warning about unused variables

- fabtests/pytest/efa/conftest.py
- fabtests/pytest/efa/test_rdm.py
- fabtests/pytest/efa/test_rma_bw.py
- fabtests/pytest/efa/test_rma_pingpong.py
Currently, we always test mixed memory type workload in two directions explicitly: like cuda-to-host, host-to-cuda.
However. pingpong and rma read/write test are all bi-directional, which means there is no difference for cuda-to-host and host-to-cuda. Running them twice in this situation is not necessary and causing longer test duration.
This patch improves this by having a reduced memory type list for bi-directional tests.
> fabtests/efa: Avoid testing duplicate mixed memory type workload

- prov/efa/src/efa_errno.h
- prov/efa/src/efa_strerror.c
- prov/efa/src/rdm/efa_rdm_cq.c
- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/src/rdm/efa_rdm_util.c
- prov/efa/src/rdm/efa_rdm_util.h
Extend the error message when the receiver has zcpy recv turned on but get a rtm pkt that it cannot handle. The extended error message includes possible root causes and the potential mitigations.
> prov/efa: Improve the zero-copy recv error message.

- include/ofi_abi.h
- man/fabric.7.md
ABI version is updated to 1.8 to accommodate fi_fabric2() API introduced in https://github.com/ofiwg/libfabric/pull/10279
> core: 1.8 ABI compat

- fabtests/pytest/efa/conftest.py
- fabtests/pytest/efa/test_rdm.py
- fabtests/pytest/efa/test_rma_bw.py
- fabtests/pytest/efa/test_rma_pingpong.py
backport https://github.com/ofiwg/libfabric/pull/10375
> [v1.22.x] fabtests/efa: Avoid testing duplicate mixed memory type workload

- prov/efa/test/efa_unit_test_cq.c
- prov/efa/test/efa_unit_test_ep.c
Currently, the test uses hard-coded 0 as the return value of efa_mock_ibv_read_qp_num_return_mock, which is wrong as the qpn can be non-zero when there are other qp that share the device. This patch fixes this issue by using the correct qp num associated with the ep.
> prov/efa/test: Use correct qp num in the mock

- prov/efa/src/rdm/efa_rdm_ep.h
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/test/efa_unit_test_ep.c
user_info is just a duplication of fi_info passed
by fi_endpoint(), which is duplicated to base_ep.info already.
> prov/efa: Remove dupliated user_info in efa_rdm_ep

- include/ofi_abi.h
CURRENT_SYMVER() is just a shortcut for DEFAULT_SYMVER() with version set to CURRENT_ABI. Using DEFAULT_SYMVER() directly makes the version info more visible from the code and eliminate the need to change from CURRENT_SYMVER() to DEFAULT_SYMVER() when the ABI version is bumped.
Remove the definition of CURRENT_SYMVER() from the header. Update the documentation accordingly.
> core: Remove CURRENT_SYMVER() macro

- prov/efa/src/rdm/efa_rdm_ep.h
- prov/efa/src/rdm/efa_rdm_pke_utils.c
For system memory, it should use p2p even with unregistered buffer. Otherwise it will affect performance.
> prov/efa: always use p2p for system memory

- prov/efa/src/rdm/efa_rdm_ep.h
Backport https://github.com/ofiwg/libfabric/pull/10392
> [v1.21.x]prov/efa: always use p2p for system memory

- prov/efa/src/rdm/efa_rdm_ep.h
- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/src/rdm/efa_rdm_pke_utils.c
- prov/efa/src/rdm/efa_rdm_pke_utils.h
Backport https://github.com/ofiwg/libfabric/pull/10347 and https://github.com/ofiwg/libfabric/pull/10392
> [v1.22.x]prov/efa: always use p2p for system memory

- prov/efa/docs/efa_rdm_protocol_v4.md
- prov/efa/src/rdm/efa_rdm_ep.h
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/src/rdm/efa_rdm_peer.h
- prov/efa/src/rdm/efa_rdm_protocol.h
- prov/efa/test/efa_unit_test_cq.c
- prov/efa/test/efa_unit_test_ep.c
backport 
- https://github.com/ofiwg/libfabric/pull/10382
- https://github.com/ofiwg/libfabric/pull/10390
- https://github.com/ofiwg/libfabric/pull/10391
> [v1.22.x] prov/efa: backport several recent changes

- fabtests/pytest/efa/test_unexpected_msg.py
The EFA limit for single MR that enables remote write is 1M pages aka 4GB for regular pages. Currently test_unexpected_msg can hit this limit for certain msg_size & msg_count combo. This patch skips such combos that can hit the limit to avoid errors.
> fabtests/pytest/efa: Skip memory registration that hit device limit

- fabtests/pytest/efa/test_unexpected_msg.py
backport https://github.com/ofiwg/libfabric/pull/10402
> [v1.22.x] fabtests/pytest/efa: Skip memory registration that hit device limit

- prov/efa/test/efa_unit_test_common.c
- prov/efa/test/efa_unit_test_cq.c
- prov/efa/test/efa_unit_test_ep.c
- prov/efa/test/efa_unit_test_rnr.c
- prov/efa/test/efa_unit_tests.h
Currently, all unit tests disable shm transfer by
closing the shm ep directly, which is a hacky
shortcut. This hack can cause trouble when more
procedure is needed for shm closure. This patch
fixes this issue by disabling shm via the public
fi_setopt API with FI_OPT_SHARED_MEMORY_PERMITTED
as false.
A common utility function
efa_unit_test_resource_construct_rdm_shm_disabled() is introduced and all test functions that need to
disable shm should use this common function instead.
> prov/efa/test: Disable shm via fi_setopt

- prov/efa/src/fi_ext_efa.h
fi_ext_efa.h uses fid_mr from fi_domain.h. Import
the dependency header for self-containing.
> prov/efa: Add dependency header file in fi_ext_efa.h

- fabtests/prov/lpp/src/atomic.c
- fabtests/prov/lpp/src/main.c
- fabtests/prov/lpp/src/msg.c
- fabtests/prov/lpp/src/rcq_data.c
- fabtests/prov/lpp/src/rma.c
- fabtests/prov/lpp/src/test_util.h
Fix compiler warnings about incorrect placement of const and inline identifiers
> fabtests/prov/lpp: fix compile warnings

- prov/efa/src/rdm/efa_rdm_ep_fiops.c
For unimplemented options, we shouldn't need a warning. Application can tell from the FI_ENOPROTOOPT rc and do the fall back accordingly.
> prov/efa: Adjust log level for setopt/getopt

- fabtests/prov/efa/Makefile.include
- fabtests/prov/efa/src/efa_rdma_checker.c
- fabtests/pytest/efa/efa_common.py
- fabtests/pytest/efa/test_efa_protocol_selection.py
- prov/efa/src/efa_env.c
FI_EFA_INTER_MIN_READ_WRITE_SIZE is only applied to emulated write protocols. When efa device support rdma write,
rdma write will be always used.
This PR introduces a efa_rdma_checker.c code to check efa device's rdma read/write capability on a given platform, and
skip inter_min_read_write_size test in fabtests if the device support rdma-write.
> prov/efa, fabtests/efa: Only test inter_min_read_write_size for for emulated write path 

- fabtests/pytest/efa/test_rdm.py
- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/src/rdm/efa_rdm_pke_cmd.c
- prov/efa/src/rdm/efa_rdm_pke_nonreq.c
When application requests FI_DELIVERY_COMPLETE, it should fallback to the DC version of LONG CTS RTMs, as the default LongCTS is not DC.
> prov/efa: Make NACK protocol fall back to DC longCTS when DC is requested

- .github/workflows/pr-ci.yml
Note that the `[s]brk()` usage in `fabtests/unit/mr_cache_evict.c` currently precludes the macOS version from being bumped past 13. The "`int` from `void *`" warnings turn into errors in the newer XCode versions.
> actions: Bump macOS version, ignore warning if `libtool` is already installed

- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/src/rdm/efa_rdm_pke_rtw.c
1. Correctly handle fallback longcts-rtw send completion
2. When FI_DELIVERY_COMPLETE is requested, also remove NACK packet from rxe map after recv completed
> prov/efa: Fill the gap in Read NACK protocol 

- fabtests/configure.ac
- fabtests/prov/efa/Makefile.include
- fabtests/prov/efa/configure.m4
Create efa provider's own configure.m4 and make configure.ac call it.
Build efa_rdma_checker conditionally when all symbols are available.
> fabtests/configure, efa: call provider specific configure

- fabtests/pytest/efa/test_rdm.py
- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/src/rdm/efa_rdm_pke_cmd.c
- prov/efa/src/rdm/efa_rdm_pke_nonreq.c
- prov/efa/src/rdm/efa_rdm_pke_rtw.c
Backport https://github.com/ofiwg/libfabric/pull/10412
> [v1.22.x] prov/efa: Make NACK protocol fall back to DC longCTS when DC is requested

- prov/efa/src/rdm/efa_rdm_atomic.c
- prov/efa/src/rdm/efa_rdm_ep.h
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/src/rdm/efa_rdm_ep_utils.c
- prov/efa/src/rdm/efa_rdm_msg.c
- prov/efa/src/rdm/efa_rdm_rma.c
- prov/efa/src/rdm/efa_rdm_srx.c
- prov/efa/test/efa_unit_test_ep.c
Remove duplicate references of `tx_iov_limit`, `rx_iov_limit`, `tx_size`, and `rx_size`, and access them via info instead. This can not only save the memory of `efa_rdm_ep` struct, but also well separate the attributes from `fi_info` or specific to `efa_rdm_ep`.
> prov/efa: Remove duplicated fields in efa_rdm_ep

- man/fi_efa.7.md
- prov/efa/configure.m4
- prov/efa/src/efa_base_ep.c
- prov/efa/src/efa_base_ep.h
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
To prioritize the messages from a given endpoint, user can specify ` fi_info->tx_attr->tclass = FI_TC_LOW_LATENCY` in the fi_endpoint() call to set the service level in rdma-core. All other tclass values will be ignored.
> prov/efa: Use tclass to prioritize the messages from an ep

- fabtests/configure.ac
- fabtests/prov/efa/Makefile.include
- fabtests/prov/lpp/Makefile.include
add --enable-efa=yes/no --enable-lpp=yes/no, defaulted to yes to turn off these providers if they are not needed to be built.
> fabtests: Add extra configure options for efa and lpp tests

- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/test/efa_unit_test_ep.c
When zcpy rx is on, both inject_msg_size and inject_rma_size should be reported as inline buf size.
> prov/efa: report correct inject_msg_size for zcpy rx

- include/ofi_mr.h
- prov/util/src/util_mr_cache.c
A provider may update the memory region that is added to accommodate
for instance alignment of the region to a larger page boundary. In such
cases, the MR cache info used to search the cache should use the updated
region.
This allows the provider to avoid walking /proc/pid/smaps if the
underlying kernel component may more efficiently determine the backing
page size.
> prov/util: Allow providers to update cache MR IOV

- contrib/intel/jenkins/Jenkinsfile
psm3 is failing onecclgpu because of a missing package. Disable it until the package dependency is resolved.
> contrib/intel/jenkins: Temporarily disable psm3 in onecclgpu

- prov/efa/src/rdm/efa_rdm_atomic.c
- prov/efa/src/rdm/efa_rdm_ep.h
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/src/rdm/efa_rdm_ep_utils.c
- prov/efa/src/rdm/efa_rdm_msg.c
- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/src/rdm/efa_rdm_rma.c
- prov/efa/src/rdm/efa_rdm_srx.c
- prov/efa/test/efa_unit_test_common.c
- prov/efa/test/efa_unit_test_cq.c
- prov/efa/test/efa_unit_test_ep.c
- prov/efa/test/efa_unit_test_rnr.c
- prov/efa/test/efa_unit_tests.h
a443ad6ce9d2c49371c85523dd7f598f5d109f2b, 49922d1740ab30eea1c560da9ab7b386a5298e32 and ee37cbfe14f4e934e271bb4c371579b50890ba5e were all necessary in order to cleanly backport changes from #10413.
> [v1.22.x] prov/efa: Backport recent changes

- fabtests/prov/lpp/src/test_util.c
Remove deprecated FI_MR_BASIC flag
> fabtests/lpp: remove deprecated FI_MR_BASIC

- fabtests/common/shared.c
Added condition to make preposted rx buffers based on FT_OPT_NO_PRE_POSTED_RX in case of msg endpoint based init code in fabtests. Changes similar to https://github.com/ofiwg/libfabric/pull/10394
> Fabtests: Added inband sync to ft_init_fabric_cm.

- prov/efa/src/efa_mr.c
When FI_MR_DMABUF flags are passed, provided that dmabuf export requirements for
cuda have been confirmed during init, skip ofi_hmem_dev_register calls.
efa_mr_hmem_setup previously always called ofi_hmem_dev_register on all
FI_HMEM_CUDA calls, regardless of the presence of FI_MR_DMABUF in flags. When
gdrcopy is enabled, this means deconstructing the fi_mr_dmabuf into a struct
iovec from its {base, offset, len} 3-tuple, then passing the resulting iovec to
gdr_pin followed by gdr_map.
The very fact that we have been provided a cuda dmabuf means that the memory is
already pinned, properly aligned, and ready for import by other kmods, which is
enforced in the cudart apis for acquiring one. At best, this is unnecessary for
dmabuf arguments, and at worst the pgprot modifications done by gdrdrv …
> prov/efa: avoid gdr_pin/gdr_map for dmabuf mrs

- fabtests/multinode/src/harness.c
- fabtests/scripts/runmultinode.py
Allow the -E parameter in the harness code. It enables out of band address exchange which is needed by CXI.
Adjust the runmultinode.py script to use the correct command line options.
> fabtests: Multinode update

- configure.ac
- prov/util/src/util_mem_monitor.c
In order to receive unmap events, uffd uses 'mode missing' when registering memory regions. This implies getting page fault events as well. So handle them by returning a zero-filled page.
> Fix application + uffd hangs due to not handling page faults

- fabtests/pytest/efa/test_runt.py
The current assertion check for send read wrs and bytes are based on the exact calculation of benchmark data size + fabtests control message size, which is too strict. Fabtests may change control message sizes which should not impact this test.
This patch looses the assertion for read request counters which make it have enough coverage for the benchmark data size.
> fabtests/pytest/efa: Loose assertion for read request counters

- src/xpmem.c
We build libfabric with xpmem support but we may run it on a OS without the kernel module loaded.
Change FI_WARN to FI_INFO to reduce the noise in the log following the same model as cuda dlopen: https://github.com/ofiwg/libfabric/blob/main/src/hmem_cuda.c#L483-L487
> xpmem: Change the log level to info

- prov/efa/src/rdm/efa_rdm_ope.h
shm_desc and peer_unexp_entry are not used after
moving to peer provider and util srx
> prov/efa: Remove unused fields in efa_rdm_ope

- fabtests/prov/efa/src/rdm_rnr_read_cq_error.c
The current check for rnr cq error message string
is unnecessary and fragile as we may adjust
the error message. This patch removes such error
message check and relies on the error code check.
> fabtests/efa: Remove rnr cq error message check

- Makefile.am
- configure.ac
- include/ofi_mr.h
- libfabric.vcxproj
- man/fi_mr.3.md
- prov/util/src/kdreg2_mem_monitor.c
- prov/util/src/util_mem_monitor.c
Two changes:
1. Add in a configure option to select a default FI_HMEM_SYSTEM memory monitor during compile time. This avoids having to rely on the hardcoded order list of memory monitors.
2. New memory monitor called kdreg2.
> Memory Monitor Updates

- include/ofi_mr.h
- prov/util/src/util_mem_monitor.c
Without this change, the following segfault can happen.
#0  0x00001555546a66de in malloc () from /lib64/libc.so.6
#1  0x00001555555351f8 in _dl_new_object () from /lib64/ld-linux-x86-64.so.2
#2  0x000015555552f413 in _dl_map_object_from_fd () from /lib64/ld-linux-x86-64.so.2
#3  0x000015555553252a in _dl_map_object () from /lib64/ld-linux-x86-64.so.2
#4  0x000015555553d700 in dl_open_worker () from /lib64/ld-linux-x86-64.so.2
#5  0x000015555476002d in _dl_catch_exception () from /lib64/libc.so.6
#6  0x000015555553d28b in _dl_open () from /lib64/ld-linux-x86-64.so.2
#7  0x000015555475f37d in do_dlopen () from /lib64/libc.so.6
#8  0x000015555476002d in _dl_catch_exception () from /lib64/libc.so.6
#9  0x00001555547600bf in _dl_catch_error () from /lib64/libc.so.6
#10 0x000015555475f497 in …
> prov/util: Change uffd stop routine to use pipe

- fabtests/include/unix/osd.h
CMPLX is introduced in C11, it may be undefined in C99. Compilation error was observed with Coverity scan.
> fabtest: Fix compilation error with C99

- src/xpmem.c
> xpmem: Fix compilation warning

- prov/cxi/test/ep.c
The cxi provider shared RX unittests verify that the cxi provider returns -FI_ENOSYS. With linkx support, this is not the case. Remove these now invalid tests.
> prov/cxi: Remove srx unittests

- prov/cxi/src/cxip_rma.c
Report order used for an RMA operation in debug
and error output.
> prov/cxi: Report RMA ordering used in debug output

- src/common.c
1. Fixes the QDR and FDR10 ib speed (8->10)
2. Support HDR (64) and NDR (128) ib speed
3. Support width enum 16
All the values are referenced to upstream
rdma-core:
https://github.com/linux-rdma/rdma-core/blob/master/libibverbs/examples/devinfo.c#L126C20-L154
> src/common.c: Update ofi_vrb_speed

- prov/efa/src/efa_domain.c
- prov/efa/src/efa_domain.h
- prov/efa/src/efa_hmem.c
- prov/efa/src/efa_hmem.h
- prov/efa/src/efa_mr.c
- prov/efa/src/efa_prov.c
- prov/efa/src/rdm/efa_rdm_ep.h
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/src/rdm/efa_rdm_msg.c
- prov/efa/src/rdm/efa_rdm_peer.c
- prov/efa/src/rdm/efa_rdm_rma.c
- prov/efa/test/efa_unit_test_ep.c
- prov/efa/test/efa_unit_test_hmem.c
- prov/efa/test/efa_unit_test_runt.c
Currently efa_hmem_info is part of efa_domain and created for every efa domain. hmem_info init involves several operations like device memory allocation / free, and trial ibv reg mr, which is expensive and can potentially cause more memory usage. Make efa_hmem_info a global variable and call it only once per process. Remove p2p_disabled_by_user from efa_hmem_info since it is only used for ep level operations, not global.
> prov/efa: Make efa_hmem_info a global variable

- fabtests/common/shared.c
The compiler can't properly follow the def-use chain guarded by the same condition and complains about the variable could be used w/o initialization:
if (atomic == FI_ATOMIC_COMPARE) {
check_cmp =  ...;
}
......
if (atomic == FI_ATOMIC_COMPARE) {
use check_cmp in macro
}
> fabtests: Fix compiler warning about unitialized variable

- prov/verbs/src/verbs_mr.c
Now all the non-system HMEM ifaces have get_dmabuf_fd method defined, it's safe to always try the dmabuf based memory registration first. If it fails for any reason (e.g. CUDA is not configured with dmabuf support), the failover path will try the peer memory approach when available.
> prov/verbs: Enable implicit dmabuf mr reg for more HMEM ifaces

- man/fi_cxi.7.md
- prov/cxi/src/cxip_info.c
- prov/cxi/src/cxip_iomm.c
Enable use of dmabuf by default for ROCR
Remove unneeded disable_dmabuf_cuda and disable_dmabuf_rocr environment variables.
Set FI_HMEM_ROCR_USE_DMABUF to enabled by default.
Update CXI man page.
Disable use of dmabuf by default for cuda
Remove use of deprecated FI_ORDER_NONE
> prov/cxi: Cxi dmabuf defaults

- src/hmem_cuda.c
Add FI_HMEM_CUDA_USE_DMABUF environment variable and default to enabled.
There are applications that can run out of GPU BAR space when using dmabuf and gdrcopy both register memory.
> hmem/cuda: Add env variable to enable/disable CUDA DMABUF

- fabtests/test_configs/ofi_rxm/tcp.test
ubertest implementation currently requires FI_RMA_EVENT when using RMA and counters This will cause tcp to return ENODATA for these combinations and cause runfabtests to fail.
This should get updated in ubertest to not require it but remove testing for now
> test_configs/ofi_rxm/tcp.test: remove cntr RMA testing

- prov/hook/hook_hmem/src/hook_hmem.c
ifdef should be if here, as HAVE_HOOK_HMEM_DL is defined anyway.
> prov/hook: Fix the preprocessor

- prov/cxi/src/cxip_coll.c
Don't treat CXIP_COLL_RC_FLT_OVERFLOW and CXIP_COLL_RC_FLT_INVALID as errors. Add logging for when one of these two or CXIP_COLL_RC_FLT_INEXACT is encountered.
> prov/cxi: ignore FLT_OVERFLOW and FLT_INVALID errors

- prov/efa/src/efa_base_ep.c
- prov/efa/src/efa_base_ep.h
When driver doesn't support non-zero sl, the qp creation will fail. In this case, fallback to zero sl qp.
> prov/efa: Fall back to zero sl when non-zero sl qp creation failed

- prov/cxi/src/cxip_mr.c
- prov/cxi/test/mr.c
Clients could provider RKEYs greater than 4 bytes and the CXI provider would not detect it.
> Fix incorrect checking of client RKEY

- include/rdma/fabric.h
The windows.h header is not necessary for ssize_t definition on Windows platform since BaseTsd.h already provides the required SSIZE_T type definition. Remove this redundant include to reduce compilation dependencies.
> core: Remove redundant windows.h

- prov/cxi/test/coll.c
Update the unit tests for collectives to account for previously-merged PR: https://github.com/ofiwg/libfabric/pull/10513
> prov/cxi: update unit test for collectives

- contrib/aws/Jenkinsfile
- prov/efa/Makefile.include
- prov/efa/src/rdm/efa_rdm_cq.c
- prov/efa/test/efa_unit_test_cq.c
- prov/efa/test/efa_unit_test_mocks.c
- prov/efa/test/efa_unit_test_mocks.h
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
When getting an wc error for rdma with imm + unsolicited recv, there is no wr_id / pkt_entry associated. Libfabric should write the eq error directly.
Also added unit tests to cover both solicited and unsolicited recv error path.
> prov/efa: Fix the error handling for unsolicited recv

- prov/efa/src/efa_mr.c
backport https://github.com/ofiwg/libfabric/pull/10445
> [v1.22.x] prov/efa: avoid gdr_pin/gdr_map for dmabuf mrs

- prov/shm/src/smr.h
- prov/shm/src/smr_progress.c
- prov/util/src/util_srx.c
fix util_srx implementation to properly set msg_size and flags and remove setting in shm
> prov/util, shm: fix util srx to adhere to peer api (setting msg_size and flags correctly)

- util/pingpong.c
The calculation of `power_of_two` would overflow when `i` reaches 32. Based on the size of allocated array `sizes`, `i` should be less than 32. Add explicit loop limit to suppress the warning.
> util/pingpong: Fix coverity issue about integer overflow

- prov/verbs/src/verbs_eq.c
The function `vrb_eq_xrc_recip_conn_event` was defined as size_t but can return a nagative value on error which would overflow when casted to int. Change the type to ssize_t.
Also change the return type of `vrb_eq_xrc_connected_event` to ssize_t to be consistent with its caller and the function it calls.
> prov/verbs: Fix coverity issue about overflowed return value

- prov/cxi/test/mr.c
For invalid_client_rkey, -FI_EKEYREJECTED will be returned if FI_MR_PROV_KEY is not being used.
> prov/cxi: Correct checking of MR test rc

- contrib/intel/jenkins/Jenkinsfile
Migrate SHMEM tests to use new CI
Separate tcp and tcp;ofi_rxm testing
Use new CI to build the things it runs
Add cluster health check stage to reboot nodes as needed
> contrib/intel/jenkins: Update CI to v1.2.0 and migrate build/tests

- prov/efa/src/efa_cntr.c
- prov/efa/src/efa_cntr.h
- prov/efa/src/rdm/efa_rdm_cq.c
- prov/efa/src/rdm/efa_rdm_cq.h
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/test/efa_unit_test_cntr.c
- prov/efa/test/efa_unit_test_cq.c
We cannot only iterate eps and post initial batch of internal rx pkt once, as there can be more eps joining later after the cq read call. This patch fixes by introducing a bit in cq/ctnr that indicates whether a ep list scan is needed. This bit is set as true when a new ep is bind to the cq, and will be set as false every time when a scan is done.
> prov/efa: Fix the ep list scan in cq/cntr read

- prov/efa/src/efa_base_ep.c
- prov/efa/src/efa_base_ep.h
- prov/efa/src/rdm/efa_rdm_ep.h
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/src/rdm/efa_rdm_msg.c
- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/src/rdm/efa_rdm_rma.c
- prov/efa/test/efa_unit_test_ep.c
Move these fields to base ep so they can be accessed by efa-raw.
> prov/efa: Move inject sizes from rdm ep to base ep

- prov/efa/test/efa_unit_test_cq.c
When device supports unsolicited write, efadv_wc_is_unsolicited is called in the error path of IBV_WC_RECV as well, but we failed to setup its mock in the unit test, it will cause a segfault inside the rdma-core function when we don't really have a cqe, which is what the current unit test does.
This patch fixes this bug.
> prov/efa: Fix the read_bad_recv_status unit test

- prov/efa/test/efa_unit_test_cq.c
backport https://github.com/ofiwg/libfabric/pull/10556
> [v1.22.x] prov/efa: Fix the read_bad_recv_status unit test

- prov/lnx/include/lnx.h
- prov/lnx/src/lnx_av.c
- prov/lnx/src/lnx_cq.c
- prov/lnx/src/lnx_domain.c
- prov/lnx/src/lnx_ep.c
- prov/lnx/src/lnx_init.c
- prov/lnx/src/lnx_ops.c
1. must pass an ep fid for fi_srx_context to comply with API symantics
2. Don't overwrite attribute flags passed in fi_av_open() by application
3. Enforce the use of FI_AV_TABLE type as the other types have been deprecated
4. Check for NULL entry before calling ofi_mr_cache_delete()
> prov/lnx: Fix various issues with initial commit

- src/fabric.c
Since xpmem installs memory monitors, these need to be cleaned up before cleaning up the monitors to avoid an assert in debug mode.
> xpmem: Cleanup xpmem before monitors

- prov/sockets/src/sock_av.c
Added a error logging print in sock_av_report_success to report failures if the sock_eq_report_event fails.
> prov/sockets: Fixed coverity issue for unchecked return value in sock_av_report_success .

- fabtests/pytest/efa/conftest.py
- fabtests/pytest/efa/test_rma_bw.py
- fabtests/pytest/efa/test_rma_pingpong.py
For fi_read, there is no difference between DC and non-DC as it's not
a transmission. For write and writedata, if device support rdma-write,
all the transmissions are DC already.
Also merge memory_type and check_rma_bw_memory_type to clean up the code.
> fabtests/pytest/efa: Avoid duiplicate completion semantic for RMA test

- prov/cxi/test/deferred_work.c
Rgroups implementation requires resource_limits true to use the service.
Only verify extra queue work for limited test.
NETCASSINI-6912
> cxi/prov: Fix deferred work test

- prov/cxi/include/cxip.h
- prov/cxi/src/cxip_coll.c
The fi_close() operation manages its internal state and return FI_SUCCESS, or a fatal error code on error.
> prov/cxi: synchronous fi_close on collective multicast

- fabtests/pytest/efa/conftest.py
- fabtests/pytest/efa/test_rma_bw.py
- fabtests/pytest/efa/test_rma_pingpong.py
Backport https://github.com/ofiwg/libfabric/pull/10578
> [v1.22.x] fabtests/pytest/efa: Avoid duiplicate completion semantic for RMA test

- prov/verbs/src/verbs_ep.c
Race Fix: Resolved a data race in the vrb_open_ep function of the verbs provider caused by concurrent modifications to the global variable vrb_ep_ops. This issue violated the FI_THREAD_SAFE threading model, leading to unpredictable behavior when creating endpoints from multiple threads.
Detailed race description: https://github.com/ofiwg/libfabric/issues/10569
Signed-off-by: Piotr Chmiel  <piotr.chmiel@hotmail.com>
> prov/verbs: Fix data race vrb_open_ep function

- include/windows/osd.h
> include/windows/osd.h: remove duplicate strtok_r definition

- include/windows/osd.h
Cherry-picked from commit 6f245834b156763b8ad3f480cf0708cfde5df5c1
> [v1.19.x] include/windows/osd.h: remove duplicate strtok_r definition

- include/windows/osd.h
Cherry-picked from commit 6f245834b156763b8ad3f480cf0708cfde5df5c1
> [v1.20.x] include/windows/osd.h: remove duplicate strtok_r definition

- include/windows/osd.h
Cherry-picked from commit 6f245834b156763b8ad3f480cf0708cfde5df5c1
> [v1.21.x] include/windows/osd.h: remove duplicate strtok_r definition

- include/windows/osd.h
Cherry-picked from commit 6f245834b156763b8ad3f480cf0708cfde5df5c1
> [v1.18.x] include/windows/osd.h: remove duplicate strtok_r definition

- include/windows/osd.h
Cherry-pick 6f245834b156763b8ad3f480cf0708cfde5df5c1
> [v1.22.x] include/windows/osd.h: remove duplicate strtok_r definition

- include/windows/osd.h
> [v2.0.x] include/windows/osd.h: remove duplicate strtok_r definition

- include/ofi_util.h
- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_attr.c
- prov/rxm/src/rxm_conn.c
- prov/rxm/src/rxm_cq.c
- prov/rxm/src/rxm_domain.c
- prov/rxm/src/rxm_ep.c
- prov/rxm/src/rxm_init.c
- prov/rxm/src/rxm_msg.c
- prov/rxm/src/rxm_tagged.c
- prov/tcp/src/xnet_av.c
- prov/util/src/rxm_av.c
Add rxm support for FI_PEER (srx, cq, and cntr) and FI_AV_USER_ID to be used with the link provider
> prov/rxm: add FI_PEER support to rxm

- prov/lnx/include/lnx.h
- prov/lnx/src/lnx_av.c
- prov/lnx/src/lnx_ops.c
Convert peer table to use buffer pools in order to utilize the built-in capabilities of expanding the table as more peers are added dynamically.
The peer table is protected by a read/write lock. Locking/unlocking callbacks are set only if needed.
> prov/lnx: Convert peer table to use buffer pools

- prov/lnx/include/lnx.h
flags is allocated on the stack which might have some random values. Ensure it's initialized to 0 because if sent to SHM provider uninitialized it could cause the provider to misbehave, since it's value is being checked.
> prov/lnx: Initialize flags to 0

- prov/ucx/src/ucx_core.c
- prov/ucx/src/ucx_domain.c
- prov/ucx/src/ucx_fabric.c
When reading the two runtime parameters the condition for the actions was inverted by mistake.
> prov/ucx: Fix incorrect return value checking for fi_param_get()

- Makefile.am
Since the ABI is still backward compatible, there is no need to bump the library major version which unnecessarily introduces incompatibilty between RPM packages due to soname change.
> Makefile.am: Keep using libfabric.so.1 as the soname

- fabtests/common/shared.c
- fabtests/functional/multi_recv.c
- fabtests/include/shared.h
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/test/efa_unit_test_srx.c
- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_ep.c
- prov/shm/src/smr.h
- prov/shm/src/smr_ep.c
> prov/shm,rxm,efa, fabtests: fix min multi recv size setting

- man/fi_lnx.7.md
The '<' symbol has special meaning and must be escaped.
> man: Fix MarkDown format issue in fi_lnx man page

- man/fi_lnx.7.md
The '<' symbol has special meaning and must be escaped.
(cherry picked from commit 45b7b2446cb1093bb3efae7138114fed96670797)
> [v2.0.x] Fix MarkDown format issue in fi_lnx man page

- fabtests/common/hmem_cuda.c
- src/hmem_cuda.c
When the CUDA toolkit is installed, a set of "stub" libraries are installed under /usr/local/cuda*/lib64/stubs/. These libraries include a SONAME field with a `.1' suffix, but the filenames of these stubs are bare. eg:
> $ readelf -d /usr/local/cuda-12.5/lib64/stubs/libnvidia-ml.so | grep soname
> 0x000000000000000e (SONAME)  Library soname: [libnvidia-ml.so.1]
The CUDA toolkit does not include any library file with the name `libnvidia-ml.so.1` (or `libcuda.so.1`, etc.), as these are provided by the driver package. This disconnect between the stub filename in the toolkit and the SONAME within it is done intentionally to allow linking with the stub at build time, while ensuring it's never loaded at runtime.
In normal dynamic linking cases (ie: without dlopen), the SONAME field of …
> hmem/cuda: avoid stub loading at runtime

- prov/tcp/src/xnet_ep.c
xnet_endpoint updates the static global variable: xnet_ep_fi_ops.
This naturally causes a data race. This PR eliminates the write.
Signed-off-by: Dariusz Sciebura <dariusz.sciebura@gmail.com>
> prov/tcp: Fix race in writing to xnet_ep_fi_ops

- prov/efa/Makefile.include
- prov/efa/test/efa_unit_test_mocks.c
- prov/efa/test/efa_unit_test_mocks.h
- prov/efa/test/efa_unit_test_msg.c
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
Add unit tests for efa_msg. Use FI_EP_RDM as ep type and override efa_msg_ops.
> prov/efa: Add unit tests for efa_msg

- contrib/intel/jenkins/Jenkinsfile
Uplevel pre-build so that it isn't copied over for summarizing
Always cleanup at the end of a pipeline
Update slurm partition names for new cluster
Put mpichtestsuite stage as first test to execute because it is the slowest. This allows other tests to complete in parallel on the other nodes while mpichtestsuite is running.
> contrib/intel/jenkins: Uplevel pre-build, always cleanup, update slurm partition names

- fabtests/benchmarks/benchmark_shared.c
- fabtests/common/shared.c
- fabtests/include/shared.h
fixed fabtests send and recv functions to use flags argument type as uint64_t instead of int as the underlying fi calls use uint64_t. removed declaration of unused function ft_writemsg from shared.h
> fabtests: corrected flags argument type in ft_sendmsg/ft_recvmsg

- prov/shm/src/smr_util.c
Could result in a peer getting incorrectly unmmaped
> prov/shm: fix name compare bug

- prov/lpp/configure.m4
- prov/shm/src/smr_util.c
- Fix lpp configure bug - check for atomics and don't build if not found
- Fix shm name compare bug
> [v2.0.x] prov/shm,lpp: cherry-picked commits

- fabtests/pytest/efa/test_multi_ep.py
- prov/efa/src/efa_av.c
- prov/efa/src/efa_av.h
- prov/efa/src/efa_base_ep.c
- prov/efa/src/efa_errno.h
- prov/efa/src/rdm/efa_rdm_ep.h
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/src/rdm/efa_rdm_ep_utils.c
- prov/efa/src/rdm/efa_rdm_peer.c
- prov/efa/src/rdm/efa_rdm_peer.h
- prov/efa/test/efa_unit_test_av.c
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
Before this change, the EFA AV entry contained a reference to efa_rdm_peer which is specific to a given endpoint. This member also prevented binding a single AV to multiple endpoints.
This change removes efa_rdm_peer from AV entry  by adding a hashmap to the endpoint that maps fi_addr to efa_rdm_peer. And it also enables multiple EFA endpoints to bind to the same AV.
> prov/efa: Decouple AV entry from endpoint

- man/fi_setup.7.md
Old: `That is, a provider may grant an application a secondary capability, whether the application.`
New: `That is, a provider may grant an application a secondary capability, regardless of whether the application requested it.`
> man/fi_setup: Complete partial sentence

- prov/cxi/include/cxip.h
Remove all CXI_MAP_IOVA_ALLOC references from libfabric.
> prov/cxi: Remove CXI_MAP_IOVA_ALLOC flag.

- fabtests/pytest/common.py
This commit fixes the following bugs in neuron fabtests
1. The neuron accelerator detection is broken on some OSs because the full path of the executable `neuron-ls` was not used
2. Before this commit, each pytest worker was assigned a single  neuron core. This works on multi node tests but fails on single node tests because a neuron core can only be opened by a single process. This commit assigns two different neuron cores to each pytest worker for client-server tests: one for the server and one for the client. Trn1 has 2 cores per neuron device and Trn2 has 8 cores per neuron device, so
this assignment works for both.
3. When running in serial mode, the env var PYTEST_XDIST_WORKER is not set, so the NEURON_RT_VISIBLE_CORES env var is also not set. This causes the server to occupy all …
> [v2.0.x] fabtests: Bugfixes for neuron

- prov/efa/src/efa_domain.c
- prov/efa/src/efa_user_info.c
efa_fork_support_enable_if_requested was moved to EFA_INI, so efa_fork_support_install_fork_handler can be registered at any stage that is later. Move efa_fork_support_install_fork_handler back to efa_domain_open to avoid installing fork handler for non-EFA provider during fi_getinfo's provider discovery process.
> prov/efa: Move fork handler installation to efa_domain_open

- prov/cxi/src/cxip_ctrl.c
- prov/cxi/src/cxip_mr.c
- prov/cxi/src/cxip_msg_hpc.c
- prov/cxi/src/cxip_msg_rnr.c
- prov/cxi/src/cxip_rdzv_pte.c
When MRs and EPs should ignore drop count during init. Failing to do this may result in enable hangs.
> prov/cxi: Ignore drop count during init

- prov/efa/src/efa_domain.c
- prov/efa/src/efa_user_info.c
efa_fork_support_enable_if_requested was moved to EFA_INI, so efa_fork_support_install_fork_handler can be registered at any stage that is later. Move efa_fork_support_install_fork_handler back to efa_domain_open to avoid installing fork handler for non-EFA provider during fi_getinfo's provider discovery process.
Signed-off-by: Jessie Yang <jiaxiyan@amazon.com>
(cherry picked from commit 1e3cca62ff490fd44e3eecb7b61a1349164e8aa6)
> [v2.0.x] prov/efa: Move fork handler installation to efa_domain_open

- prov/efa/src/efa_msg.c
- prov/efa/src/efa_rma.c
efa_post_send, efa_post_write, efa_post_read accesses base_ep->is_wr_started bool which needs to be protected by a lock, otherwise there will be a race condition when multiple threads to call them at the same time
Same issue with efa_post_recv which accesses the recv_wr_index
This patch adds the required locking to protect these resources. This lock is a no-op unless FI_THREAD_SAFE.
> prov/efa: Add missing locks in efa_msg and efa_rma

- man/fi_cxi.7.md
- prov/cxi/include/cxip.h
- prov/cxi/src/cxip_cq.c
- prov/cxi/src/cxip_ctrl.c
- prov/cxi/src/cxip_ep.c
- prov/cxi/src/cxip_evtq.c
- prov/cxi/src/cxip_fabric.c
- prov/cxi/src/cxip_rxc.c
- prov/cxi/src/cxip_txc.c
- prov/cxi/test/cxip_test_common.c
- prov/cxi/test/tagged.c
Implement cxi managed internal wait FDs. EP bound to CQ(s) with wait_obj  will allocate
their own internal CXI wait object and add the sysfs_notify FD to the CQ. Fix CQ trywait logic
to correctly enable h/w EQ interrupts and include control EQ which may require progress be initiated.
> prov/cxi: Fix CQ wait FD logic

- contrib/aws/Jenkinsfile
Skip the default checkout of the workspace because we explicitly checkout out the workspace after we clean it.
> contrib/aws: Skip default checkout

- prov/efa/src/efa_rma.c
- prov/efa/test/efa_unit_test_rma.c
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
We previously set the inject size to 0 to prevent using inline write, but application can use inject rma for 0 size message. Make rma inject temporarily return FI_ENOSYS before firmware supports inline write.
> prov/efa: Remove inline write logic for efa_rma inject

- fabtests/pytest/efa/test_multi_ep.py
- prov/efa/src/efa_av.c
- prov/efa/src/efa_av.h
- prov/efa/src/efa_base_ep.c
- prov/efa/src/efa_errno.h
- prov/efa/src/rdm/efa_rdm_ep.h
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/src/rdm/efa_rdm_ep_utils.c
- prov/efa/src/rdm/efa_rdm_peer.c
- prov/efa/src/rdm/efa_rdm_peer.h
- prov/efa/test/efa_unit_test_av.c
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
This reverts commit c3f9e2134bfc8524ac80a1306835bbfdc8b4dcb3.
Commit c3f9e2134  is causing some performance regressions. Revert the commit while we debug them.
> Revert "prov/efa: Decouple AV entry from endpoint"

- prov/cxi/src/cxip_eq.c
- prov/cxi/test/eq.c
Make sure wait objects are not allowed for cxi EQs.
> prov/cxi: cxi EQ do not support wait objects

- contrib/aws/Jenkinsfile
It is easier for Developers to manage the CI if it is all in one place.
Scale up faster to reduce runtime.
> contrib/aws: Remove test config file, and pass in command line arguments instead, and scale up faster to reduce runtime

- man/fi_efa.7.md
- prov/efa/src/efa_av.c
- prov/efa/src/efa_av.h
FI_AV_MAP is deprecated in Libfabric 2.x. EFA provider was overriding AV type to FI_AV_TABLE even before this change. This change removes all references to FI_AV_MAP in the EFA provider. It will print a warning and switch to FI_AV_TABLE if the application requests FI_AV_MAP.
> prov/efa: Deprecate FI_AV_MAP

- prov/efa/src/efa_base_ep.c
- prov/efa/src/efa_base_ep.h
- prov/efa/src/rdm/efa_rdm_cq.c
- prov/efa/src/rdm/efa_rdm_cq.h
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/test/efa_unit_test_cq.c
- prov/efa/test/efa_unit_test_ep.c
The structs efa_rdm_cq and efa_cq share the
same members util_cq and ibv_cq. This patch makes efa_rdm_cq use efa_cq as a subset so we can convert between efa_rdm_cq and efa_cq via container_of, like efa_rdm_ep and efa_base_ep.
> prov/efa: Make efa_rdm_cq use efa_cq

- prov/efa/src/efa_av.c
- prov/efa/src/efa_av.h
71dd1a12 deprecates FI_AV_MAP support for the EFA provider.  With this deprecation, we no longer need to maintain util_av_fi_addr and fi_addr in the efa_conn struct b/c they will always be equal.
> prov/efa: Remove util_av_fi_addr from efa_conn

- prov/cxi/src/cxip_cq.c
ofi_cq_strerror() was being called instead of cxip_cq_strerror().
> prov/cxi: Fix fi_cq_strerror

- prov/efa/src/efa_base_ep.h
- prov/efa/src/rdm/efa_rdm_protocol.h
struct efa_ep_addr is used in both the DGRAM and RDM providers, so the structure definition should be in a common file, and not an RDM only file.
> prov/efa: Move struct efa_ep_addr to efa_base_ep

- man/fi_efa.7.md
- man/fi_endpoint.3.md
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/test/efa_unit_test_ep.c
This PR contains two commits to regulate the usage of some optnames for the fi_setopt/fi_getopt calls,
including the EFA specific ones:
FI_OPT_EFA_USE_DEVICE_RDMA, FI_OPT_EFA_SENDRECV_IN_ORDER_ALIGNED_128_BYTES,
and FI_OPT_EFA_WRITE_IN_ORDER_ALIGNED_128_BYTES
and the common one: FI_OPT_SHARED_MEMORY_PERMITTED
> core,prov/efa: Regulate the usage of optnames

- prov/efa/src/rdm/efa_rdm_ep_fiops.c
Closing an ep with outstanding receives is a legal use case. There shouldn't be warning for this.
> prov/efa: Adjust the logging level for unreleased rxe

- prov/efa/src/efa.h
- prov/efa/src/efa_cq.c
- prov/efa/src/efa_msg.c
- prov/efa/src/efa_rma.c
- prov/efa/src/rdm/efa_rdm_pke.h
- prov/efa/src/rdm/efa_rdm_protocol.h
- prov/efa/src/rdm/efa_rdm_util.h
- prov/efa/test/efa_unit_test_cq.c
Store the completion flags and peer address in FI_CONTEXT2 and retrieve later when writing cq.
> prov/efa: Implement FI_CONTEXT2 in EFA Direct

- prov/cxi/Makefile.include
- prov/cxi/test/mr_cache.c
- prov/cxi/test/test.sh
An MR cache utilizing kdreg2 will have incorrect MR cache count stats without unsubscribe.
> prov/cxi: Test monitor unsubscribe

- prov/efa/src/efa_hmem.c
prior to this patch, when efa_hmem_info_check_p2p_support_cuda elected to attempt dmabuf for p2p, we previously leaked the file descriptor returned by cuMemGetHandleForAddressRange in all cases. This ultimately meant the dmabuf stuck around for the lifetime of the process, even after dereg and after releasing the memory back to the device mempool.
All calls to cuda_get_dmabuf_fd need a corresponding close call.
> prov/efa: fix leak of dmabuf fd in cuda p2p probe

- include/ofi_hmem.h
- prov/cxi/include/cxip.h
- prov/cxi/src/cxip_iomm.c
- prov/cxi/test/cuda.c
- prov/cxi/test/rocr.c
- src/hmem.c
- src/hmem_cuda.c
- src/hmem_rocr.c
For some HMEM ifaces, ofi_hmem_get_dmabuf_fd() may result in a new FD being allocated. Define ofi_hmem_put_dmabuf_fd() to close FD.
Support ofi_hmem_get_dmabuf_fd() with ROCR.
Update CXI provider accordingly.
> hmem: Define ofi_hmem_put_dmabuf_fd

- fabtests/prov/efa/configure.m4
- fabtests/prov/efa/src/efa_rdma_checker.c
- fabtests/pytest/efa/efa_common.py
~~This includes 2 commits:~~
1. add rdma check for unsolicited write recv
~~2. Fix rx buf size to not exceed max_msg_size
When the option max_msg_size is set, the rx buf size should not exceed this limit.~~
> fabtests/efa: add rdma check for unsolicited write recv

- prov/cxi/configure.m4
- prov/cxi/src/cxip_curl.c
fix #10710 
ensures libcurl dlopen path is correct
If the user passes '--with-curl=<path>' to configure, then the dlopen of libcurl should honor that selection and use the file path passed in
> prov/cxi: Add FI_CXI_CURL_LIB_PATH #define from autoconf 

- prov/tcp/src/xnet_rdm.c
As there may be multiple threads calling xnet_ini_rdm in parallel, simultaneous writing to 'ops_open' field of fi_ops struct causes data race.
Signed-off-by: Dariusz Sciebura [dariusz.sciebura@gmail.com](mailto:dariusz.sciebura@gmail.com)
> prov/tcp: Fix data race caused by parallel access to xnet_rdm_fid_ops

- include/ofi.h
- include/unix/osd.h
- include/windows/osd.h
- src/common.c
In ofi_get_core_info, which is supposed to be thread safe ("Multiple threads may call fi_getinfo simultaneously, without any requirement for serialization."), a global variable 'log_prefix' is modified, which may lead to a data race. Changing the variable to a thread local one, fixes that problem.
Signed-off-by: Dariusz Sciebura <dariusz.sciebura@gmail.com>
> core/logging: Fix data race on log_prefix

- prov/rxm/src/rxm_ep.c
this prevents a segfault when the application calls fi_getopt of FI_OPT_MIN_MULTI_RECV before the endpoint gets enabled.
> prov/rxm: fix rxm multi recv getopt segfault

- man/fi_efa.7.md
This links to a non-existing page unless viewed via the GitHub source.
Hard-linking to the RDM protocol doc is subject to breakage. Hard-linking to the doc on a frozen ref can become out-of-sync.
> man/fi_efa: Remove relative link

- .github/workflows/gh-man.sh
- .github/workflows/nroff-elves.sh
The man page converter action would fail w/o approval due to updated branch merge policy.
Update the GH man page updater similarly even if current branch policy is different. The policy can be changed in the future.
> github/actions: Approve PR before merge

- .github/workflows/gh-man.sh
- .github/workflows/nroff-elves.sh
Merge cannot be done automatically due to the new review approval requirement on the main and stable branches.
Revert previous change about adding an approval review since self-approval is not allowed.
Add a random number to the temporary branch to avoid conflict among multiple action runs since now the temporary branches need to be deleted manually.
> github/actions: Change to manual merge for the man page converter

- prov/util/src/util_srx.c
The flags that are passed to util_init_rx_entry when called from util_srx_generic_trecv are not OR'ed with FI_TAGGED | FI_RECV. The function util_srx_generic_trecv is also called in a different flow from util_get_recv_entry with the flags OR'ed (working flow). The same issue is present in the util_srx_generic_recv function but instead of FI_TAGGED it should be FI_MSG.
> prov/util: Fix flag initialization for generic receive of unexpected entry

- fabtests/pytest/common.py
- fabtests/pytest/efa/conftest.py
- fabtests/pytest/efa/efa_common.py
- fabtests/pytest/efa/test_av.py
- fabtests/pytest/efa/test_cq.py
- fabtests/pytest/efa/test_efa_device_selection.py
- fabtests/pytest/efa/test_efa_info.py
- fabtests/pytest/efa/test_efa_protocol_selection.py
- fabtests/pytest/efa/test_efa_shm_addr.py
- fabtests/pytest/efa/test_flood_peer.py
- fabtests/pytest/efa/test_fork_support.py
- fabtests/pytest/efa/test_mr.py
- fabtests/pytest/efa/test_multi_ep.py
- fabtests/pytest/efa/test_multi_recv.py
- fabtests/pytest/efa/test_rdm.py
- fabtests/pytest/efa/test_rma_bw.py
- fabtests/pytest/efa/test_rma_pingpong.py
- fabtests/pytest/efa/test_rnr.py
- fabtests/pytest/efa/test_runt.py
- fabtests/pytest/efa/test_setopt.py
- fabtests/pytest/efa/test_unexpected_msg.py
- prov/efa/src/efa_user_info.c
Separate out some commits from https://github.com/ofiwg/libfabric/pull/10735 to make review and testing easier
> prov/efa, fabtests: Changes to support adding efa-direct fi_info objects

- prov/cxi/src/cxip_eq.c
- prov/cxi/test/cxip_test_common.c
- prov/cxi/test/cxip_test_common.h
- prov/cxi/test/eq.c
Add provider specific support for EQ with FI_WAIT_YIELD attribute. FI_WAIT_FD is not supported at this time.
> prov/cxi: Add FI_WAIT_YIELD EQ waitobj support

- man/fi_endpoint.3.md
- prov/util/src/util_srx.c
When canceling a multi-recv entry, FI_MULTI_RECV was never set as part of the error entry flags. Fix so that the user can determine if the buffer is still in use.
> prov/util: fix FI_MULTI_RECV not set on FI_ECANCELED

- .github/workflows/coverity.yml
- .github/workflows/pr-ci.yml
Dependabot is not enabled on 1.21.x branch. This commit updates the upload-artifact version to v4.
> [v1.21.x] .github/workflows: Update upload-artifacts version to v4

- prov/efa/src/efa.h
- prov/efa/src/efa_domain.c
- prov/efa/src/efa_hmem.c
- prov/efa/src/efa_prov.c
- prov/efa/src/efa_prov.h
- prov/efa/src/efa_prov_info.c
- prov/efa/src/efa_prov_info.h
- prov/efa/src/efa_user_info.c
- prov/efa/src/efa_user_info.h
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/test/efa_unit_test_av.c
- prov/efa/test/efa_unit_test_cntr.c
- prov/efa/test/efa_unit_test_common.c
- prov/efa/test/efa_unit_test_cq.c
- prov/efa/test/efa_unit_test_domain.c
- prov/efa/test/efa_unit_test_ep.c
- prov/efa/test/efa_unit_test_hmem.c
- prov/efa/test/efa_unit_test_info.c
- prov/efa/test/efa_unit_test_mr.c
- prov/efa/test/efa_unit_test_msg.c
- prov/efa/test/efa_unit_test_ope.c
- prov/efa/test/efa_unit_test_pke.c
- prov/efa/test/efa_unit_test_rdm_peer.c
- prov/efa/test/efa_unit_test_rma.c
- prov/efa/test/efa_unit_test_runt.c
- prov/efa/test/efa_unit_test_send.c
- prov/efa/test/efa_unit_test_srx.c
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
efa-direct is a new provider that provides direct access to the EFA
device with minimal overhead and features. It does not support SAS
ordering, tagged messaging, atomics. It does not have  copy based
protocols and cannot support sending/receiving large message sizes
and HMEM devices that don't have p2p support.
The functionality provided by the efa-direct provider is a subset of the
efa rdm provider. When applications do not require  capabilities only
supported by the efa rdm provider, it is more performant for them to use
the efa-direct provider. Accordingly, the efa-direct fi_info objects are
returned before the efa rdm fi_info objects in the fi_getinfo call.
> prov/efa: Add new efa-direct fi_info objects

- contrib/aws/Jenkinsfile
The sockets provider is being deprecated in favor of the tcp, udp, and utility providers.
> contrib/aws: remove sockets provider test

- prov/efa/src/rdm/efa_rdm_ope.c
efa_rdm_txe_construct is called to construct a txe for the handshake packet and to construct txes for send, RMA and atomic operations.
iov_count is 0 only in the handshake path. When efa_rdm_txe_construct is called as part of an fi_send or fi_read or fi_write call from the application, iov_count is never 0.
The handshake packet is posted internally by the EFA provider, so it does not make sense to allocate and consume prefix space. Instead just check for iov_count before consuming the prefix space.
> prov/efa: Bug fix in the RDM path with FI_MSG_PREFIX mode

- prov/shm/src/smr_util.c
EP names have the format fi_shm://<shm_name> to be consistent with other provider formats. Since shared memory names cannot have slashes in them, the shm provider skips this prefix when creating the shared memory region. However, it does not do this when inserting the names into the map which causes an issue when comparing names in the map against region names.
This removes the prefix for map additions as well so that names match in both data structures.
> prov/shm: remove prefix from map inserts

- fabtests/test_configs/tcp/io_uring.exclude
io_uring multi_recv fails intermittently by hanging. Adding it to the disable list until the kernel update comes in for CI to support it.
> fabtests/test_configs: io_uring disable multi_recv

- prov/efa/src/efa_prov.c
- prov/efa/src/efa_prov_info.c
Remove bool enable_hmem and avoid checking system HMEM iface
If efa_prov_info_set_fabric_name fails with ENOMEM, print a warning and continue
efa_hmem_info_initialize calls ibv_reg_mr to test for p2p support.
On older kernels (without support for IBV_FORK_UNNEEDED), efa_fork_support_enable_if_requested calls ibv_fork_init, when fork support is requested.
If ibv_fork_init is called, it must be called before any ibv_reg_mr calls. Otherwise, ibv_fork_init will return EINVAL.
Therefore, efa_fork_support_enable_if_requested must be called before efa_hmem_info_initialize.
> prov/efa: efa-direct path fixes

- src/common.c
Only disable ep if the failure can not be retried.
> prov/tcp: Only disable ep if the failure can not be retried

- include/ofi.h
Fixes #10634 .
First patch enhances performance for compilers that support `__builtin_clz`: these include GCC,Clang and their derivatives.
Some statistics for emitted code are shipped in the patch.
Many other architectures might get disparaged by patch, including RISC-V 64-bit without Zbb extension.
Second patch removes an unnecessary instruction from original roundup_power_of_two.
> enchance performace of roundup_power_of_two

- prov/efa/Makefile.include
- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/src/rdm/efa_rdm_pke.c
- prov/efa/src/rdm/efa_rdm_pke.h
- prov/efa/src/rdm/efa_rdm_srx.c
- prov/efa/test/efa_unit_test_mocks.c
- prov/efa/test/efa_unit_test_mocks.h
- prov/efa/test/efa_unit_test_pke.c
- prov/efa/test/efa_unit_test_srx.c
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
backport https://github.com/ofiwg/libfabric/pull/10784
> [v2.0.x] prov/efa: Fix the unexp_pkt clean up.

- prov/cxi/test/test.sh
- prov/cxi/test/test_sw.sh
This commit resolves a bug in certain CXI criterion test cases where the le_pools[] max_alloc value was being decreased for all LE pool entries.  This resulted in unintended LE append failures + NMIs + inbound wait timeouts related to the CXI eth driver.  Now, the test only lowers the max_alloc value for LE pools associated with the default CXI service, which is used during the criterion tests.  Additionally, instances of csrutil have been replaced with cxiutil.
> prov/cxi: Fix bug in constrained LE test cases in test.sh and test_sw.sh

- contrib/intel/jenkins/Jenkinsfile
- fabtests/scripts/runmultinode.sh
Update the oneccl CPU and separate it to use different partitions.
> v1.22.x Intel/CI: Update oneccl CPU stage

- prov/efa/src/efa_prov.c
Currently EFA_INI only return efa_prov
when there is efa device and the device info
setup correctly. This makes fi_getinfo
with FI_PROV_ATTR_ONLY not return efa
on non-efa instances. This patch
fixes it.
> prov/efa: Always return efa_prov in EFA_INI

- prov/verbs/src/verbs_info.c
- prov/verbs/src/verbs_init.c
Previously NULL was returned if vrb_os_ini() failed. This mainly affected Windows because the function would always succeed on Linux. On Windows, the function would fail if the ND driver failed to initialize.
Returning NULL from VEBRS_INI prevents fi_getinfo() from working as expecetd when the FI_PROV_ATTR_ONLY flags is used. This patch moves the vrb_os_ini() check to vrb_init_info() which is invoked when fi_getinfo() is called the first time.
Similar to #10794
> prov/verbs: Always return vrb_prov in VERBS_INI

- prov/efa/src/efa_prov_info.c
- prov/efa/src/efa_user_info.c
- prov/efa/test/efa_unit_test_info.c
The RDM path requires manual progress for connection management (e.g. sending and receiving handshake packets) and for data transfers (e.g. long CTS protocol). So it cannot claim support for FI_PROGRESS_AUTO.
> prov/efa: Do not claim support for FI_PROGRESS_AUTO in the RDM path

- include/ofi_util.h
- prov/coll/src/coll_coll.c
- prov/efa/src/efa_av.c
- prov/rxd/src/rxd_av.c
- prov/shm/src/smr_av.c
- prov/sm2/src/sm2_av.c
- prov/tcp/src/xnet_rdm.c
- prov/util/src/rxm_av.c
- prov/util/src/util_av.c
The util_av lock will be held in the fast path in the EFA provider. With the correct threading and progress models
(FI_THREAD_DOMAIN/FI_THREAD_COMPLETION and FI_PROGRESS_CONTROL_UNIFIED), this lock should also be a no-op. Similar to the ep_list_lock.
This commit changes the mutex to a genlock that becomes a no-op for the correct threading and progress models and a mutex otherwise.
> include, prov: Change util_av lock to genlock

- fabtests/test_configs/psm3/psm3.exclude
Issue #10123 is resolved and this test can be re-enabled.
> fabtests/test_configs/psm3: Re-enable psm3 rdm_tagged_peek

- fabtests/functional/multi_ep.c
The current test hard-coded the transfer size as 256, this patch allows the test to run with customized
transfer size
> fabtests/multi_ep: Support customized transfer size

- prov/efa/src/efa_device.c
- prov/efa/src/efa_prov.c
Commit b7b9dd6 makes efa_prov always returned
by EFA_INI, even when efa device is not available. Then in `fi_fini` the efa_prov_finialize` will be
triggered on non-EFA platform. However, the current efa_prov_finalize doesn't handle the case where
the resources were not created, and it will cause
a double free error.
This patch fixex this issue.
> prov/efa: Fix the clean up issue for efa_util_prov

- src/hmem_rocr.c
> core/util: Fix missing rocr dlopen function assignments

- fabtests/prov/efa/Makefile.include
- fabtests/prov/efa/src/efa_shared.h
- fabtests/prov/efa/src/rdm_rnr_read_cq_error.c
- prov/efa/src/efa_msg.c
- prov/efa/src/efa_rma.c
- prov/efa/src/rdm/efa_rdm_pke.c
This PR contains 2 changes to fix the rnr cq read error test for efa-direct:
1. The error code returned by efa-direct in the fi_send call is wrong when hitting resource exhaustion. It needs a conversion for ibv errno to fi errno
2. For the cq read error test, efa-direct doesn't prepost any rx buffer internally, it posts whatever application posts, the total_send needs to be adjusted to match this behavior difference.
> prov/efa: Fix the rnr cq read error test for efa-direct

- fabtests/Makefile.am
- fabtests/prov/efa/Makefile.include
- fabtests/prov/efa/src/rdm_remote_exit_early.c
- fabtests/pytest/efa/test_remote_exit_early.py
Add tests to make sure when sender exits early in the middle of send, receiver polls cq and handle errors gracefully.
Add options for receiver posts receive, sender post tagged send, and sender posts fi_writedata.
> fabtests/prov/efa: Add remote exit early test

- fabtests/common/shared.c
In FT_OPT_ALLOC_MULT_MR mode, currently tx/rx_mr_size is set as the opts.transfer_size, and the subsequent ft_alloc_ctx_array will use this size to allocate
tx/rx buffers in the ctx array.
However, when test call ft_post_rx_buf, it will
finally post a size as MAX(opts.transfer_size, FT_MAX_CTRL_MSG). When opts.transfer_size is smaller than FT_MAX_CTRL_MSG, it will cause test call fi_recv of size larger than the actual buffer (and MR) size and cause error when the provider offload the recv directly to hardware.
This patch fixes this issue by making the tx/rx_mr_size has a min value as the FT_MAX_CTRL_MSG.
> fabtests/common: Set the min of tx/rx_mr_size

- fabtests/pytest/efa/conftest.py
- fabtests/pytest/efa/test_av.py
- fabtests/pytest/efa/test_cq.py
- fabtests/pytest/efa/test_efa_device_selection.py
- fabtests/pytest/efa/test_efa_protocol_selection.py
- fabtests/pytest/efa/test_fork_support.py
- fabtests/pytest/efa/test_multi_ep.py
- fabtests/pytest/efa/test_multi_recv.py
- fabtests/pytest/efa/test_rdm.py
- fabtests/pytest/efa/test_rma_bw.py
- fabtests/pytest/efa/test_rma_pingpong.py
- fabtests/pytest/efa/test_rnr.py
- fabtests/pytest/efa/test_runt.py
- fabtests/pytest/efa/test_unexpected_msg.py
Run fabtests for efa-direct up to device max msg size(8K) where FI_RMA is supported.
RMA tests currently post a recv with the max transfer size. It could run up to max rdma size after fixing fabtests to post the recv within device max msg size.
Also skip 0 byte for rma because fabtests use inject for messages smaller than inject_size, but efa-direct does not support it until firmware supports inline write.
> fabtests/efa: Add fabtests for efa-direct

- contrib/aws/Jenkinsfile
Add coverage for efa-direct tests on trn1, which has unsolicited write recv capability to test rma.
> contrib/aws: Add trn1 fabtests with efa direct

- fabtests/prov/efa/src/rdm_remote_exit_early.c
Fix the unused value reported by Coverity Scan.
> fabtests/efa: print err for recv failure

- fabtests/functional/av_xfer.c
This test does not require tagged messaging
> fabtests: Do not require FI_TAGGED for fi_av_xfer test

- prov/cxi/src/cxip_cq.c
cxi_cq->util_cq.cq_fid.ops is being overwritten after call to ofi_cq_init() which sets the ops to the peer callbacks. Update the code to only override this structure in the non-peer case.
> prov/cxi: Fix peer CQ support

- fabtests/prov/efa/src/rdm_remote_exit_early.c
- fabtests/pytest/efa/test_remote_exit_early.py
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
If the sender exits early, there may still be unreleased rxe in the srx->rx_pool during util_srx_close, which will cause an
assertion error when the pool is destroyed. Release the matched rxe before calling util_srx_close.
fabtests/efa: Add remote exit early test with post recv
When rdma read is available and message size >= 1M, long read or runt read protocol is used and server is expected to get a cq entry or cq error.
Otherwise, if long CTS is used and sender exits before sending CTS data, receiver is expected to timeout after sending the CTS packet without getting a cq entry or cq error.
> prov/efa: released matched rxe before destroying the srx rx_pool

- prov/efa/src/efa_av.c
- prov/efa/src/efa_av.h
- prov/efa/src/efa_domain.c
- prov/efa/src/efa_domain.h
- prov/efa/src/efa_mr.c
- prov/efa/src/rdm/efa_rdm_ep_utils.c
- prov/efa/test/efa_unit_test_av.c
- prov/efa/test/efa_unit_test_domain.c
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
efa_av->ep_type was used to distinguish between the RDM path and the
DGRAM path. The efa-direct path has FI_EP_RDM ep type but it does not
require a efa_conn->rdm_peer. But the efa-direct path still uses unique connid
based on timestamp.
Use efa_domain->info_type to distinguish the three code paths.
domain->rdm_ep can't distinguish between efa-direct and dgram code paths
> prov/efa: Remove efa_av->ep_type in favor of efa_domain->info_type

- prov/cxi/src/cxip_cq.c
Fix possible CQ segfault when NULL attributes passed to open.
Error was introduced commit 0ad502e.
> proc/cxi: Fix possible fi_cq_open segfault

- prov/efa/src/efa_av.c
- prov/efa/src/efa_av.h
- prov/efa/src/efa_domain.c
- prov/efa/src/efa_domain.h
- prov/efa/src/efa_mr.c
- prov/efa/src/rdm/efa_rdm_ep_utils.c
- prov/efa/test/efa_unit_test_av.c
- prov/efa/test/efa_unit_test_domain.c
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
Cherry-pick commits from https://github.com/ofiwg/libfabric/pull/10827
> [v2.1.x] prov/efa: Do not allocate rdm_peer struct for efa-direct and dgram paths

- fabtests/ubertest/config.c
- fabtests/ubertest/fabtest.h
This fixes compilation with gcc 15 which is stricter about function arguments.
> Fix some test function prototypes

- fabtests/prov/efa/src/rdm_remote_exit_early.c
Bind eq to ep so it can write eq error for internal ope instead of aborting application.
> fabtests/prov/efa: Bind eq to ep in remote exits early test

- fabtests/prov/efa/src/rdm_remote_exit_early.c
Backport bugfix https://github.com/ofiwg/libfabric/pull/10859
Bind eq to ep so it can write eq error for internal ope instead of aborting application.
Signed-off-by: Jessie Yang <jiaxiyan@amazon.com>
(cherry picked from commit fb04567ed4830859d77649b2bc9545339e64012e)
> [v2.1.x]fabtests/prov/efa: Bind eq to ep in remote exits early test

- prov/opx/include/fi_opx_tid_cache.h
- prov/opx/include/rdma/opx/fi_opx.h
- prov/opx/src/fi_opx_tid_cache.c
GCC 15 defaults to C23, in which `static_assert` is a keyword (rather than an alias to `_Static_assert`), and the interpretation of function declarations without parameters changed from unspecified (as in K&R) to `void`.
Fixes: #10796
> Fix build with GCC 15

- include/ofi_mem.h
- prov/util/src/util_buf.c
When a buf pool allocates a new chunk of memory, the entire memory
chunk is zeroed out via a call to memset. This can be quite costly,
occur at inconvenient times, and end up being wasteful when buf pool
users initialize their own entries.
This change adds a new OFI_BUFPOOL_NO_ZERO flag and will skip
the memset when that flag is set.
> util/bufpool: Add new flag to skip zeroing new memory allocations

- prov/cxi/test/auth_key.c
The cxi-driver no longer allows services with overlapping VNIs so use a different VNI than the default.
> prov/cxi: fix ss_plugin_auth_key_priority test

- man/fi_opx.7.md
- prov/opx/include/rdma/opx/fi_opx_domain.h
- prov/opx/include/rdma/opx/fi_opx_eq.h
- prov/opx/include/rdma/opx/fi_opx_hfi1.h
- prov/opx/include/rdma/opx/fi_opx_hfi1_progress.h
- prov/opx/include/rdma/opx/fi_opx_hfi1_sdma.h
- prov/opx/include/rdma/opx/fi_opx_hfi1_transport.h
- prov/opx/include/rdma/opx/fi_opx_progress.h
- prov/opx/include/rdma/opx/fi_opx_reliability.h
- prov/opx/src/fi_opx_cntr.c
- prov/opx/src/fi_opx_cq.c
- prov/opx/src/fi_opx_domain.c
- prov/opx/src/fi_opx_ep.c
- prov/opx/src/fi_opx_hfi1.c
- prov/opx/src/fi_opx_hfi1_sdma.c
- prov/opx/src/fi_opx_init.c
- prov/opx/src/fi_opx_progress.c
- prov/opx/src/fi_opx_reliability.c
- prov/opx/src/fi_opx_rma.c
- prov/opx/src/fi_opx_sep.c
- prov/opx/src/opa_proto.c
Includes:
- Bug fixes for link bounce, SDMA error handling, and Coverity defects
- Change to auto progress to make it interrupt-driven
- Change to copy SCB header data directly to replay the SCB, along with a lot of consolidation this enabled
> Cornelis Networks opx provider upstream 2025 03 13

- prov/efa/src/efa_av.c
- prov/efa/src/efa_user_info.c
Open MPI uses FI_AV_MAP and it's not nice to flood all Open MPI applications with these log lines
(cherry picked from commit 996a6c1911ca91a8cb9367da854c09086963303b)
> [v2.1.x] prov/efa: Change FI_AV_MAP logs to info

- prov/verbs/src/verbs_info.c
ofi_str_toaddr() allocates memory to store the address (pointed by 'addr'),
but this memory is not freed if the address format is different than FI_ADDR_IB_UD.
Leak detected by ASAN:
```
Direct leak of 16 byte(s) in 1 object(s) allocated from:
0 0xfffff78e095c in calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:77
1 0xfffff712d700 in ofi_hostname_toaddr src/common.c:825
2 0xfffff712dfbc in ofi_str_toaddr src/common.c:895
3 0xfffff72ced04 in vrb_handle_ib_ud_addr prov/verbs/src/verbs_info.c:1730
4 0xfffff72d018c in vrb_get_match_infos prov/verbs/src/verbs_info.c:1847
5 0xfffff72d0ab0 in vrb_getinfo prov/verbs/src/verbs_info.c:1924
6 0xfffff7102758 in fi_getinfo_ src/fabric.c:1377
7 0xfffff718b988 in ofi_get_core_info prov/util/src/util_attr.c:330
8 0xfffff718bbdc in …
```
> prov/verbs: Memory leak for address formats different than FI_ADDR_IB_UD

- man/fi_mr.3.md
- prov/util/src/util_mr_map.c
MR key is only needed for remote access. If remote access rights are not asked
for, MR registration should succeed even if key allocation fails. To prevent
key confliction with a future registration that needs the key, don't even try
to allocation the key if it is not needed.
A special key, FI_KEY_NOTAVAIL, is assigned for such case.
Fixes #10882
> prov/util: Only allocate MR key when needed

- fabtests/pytest/efa/test_efa_shm_addr.py
The test only uses 2 nodes, so it's not a multinode test
> fabtests/efa: Do not set multinode marker for test_efa_shm_addr

- src/common.c
ifa->ifa_addr might be NULL, thus led to crash.
Fixes #10674
> common: ofi_ifname_toaddr check ifa->ifa_addr for null

- .gitignore
The tool 'bear'[1] can be used to generate the C language server protocol database file while compiling: 'bear -- make -j $(nproc)'
The clangd will parse the compile_commands.json language metadata into the .cache directory. Add it for clean git status track.
[1]: https://github.com/rizsotto/Bear
> .gitignore: Add vscode clangd compilation database file and directory

- include/rdma/fabric.h
- man/fi_av.3.md
FI_FIREWALL_ADDR indicates to the provider that the inserted addresses may be restricted by a firewall.
> av: introduce FI_FIREWALL_ADDR flag for insert operations

- .github/workflows/coverity.yml
- .github/workflows/pr-ci.yml
v34.1 cannot build anymore because cmake version is too low. Update to latest v56.0 to fix this.
> .github/workflows: Update rdma-core version to v35.0

- fabtests/Makefile.am
- fabtests/Makefile.win
- fabtests/benchmarks/rdm_bw_mt.c
- fabtests/fabtests.vcxproj
- fabtests/fabtests.vcxproj.filters
- fabtests/include/osx/osd.h
- fabtests/include/windows/pthread.h
- fabtests/pytest/default/test_rdm.py
- fabtests/scripts/runfabtests.cmd
- fabtests/scripts/runfabtests.sh
- fabtests/test_configs/efa/efa.exclude
- fabtests/test_configs/psm3/psm3.exclude
- fabtests/test_configs/tcp/io_uring.exclude
This test creates a 1:1 relationship of num_eps:num_threads
where parallel sends ep[n] <-> ep[n] happen on each thread.
This code also comes with a TODO detailed in rdm_bw_mt.c.
Essentially the fabtests common code needs to be refactored
to make all fabric_resouces and buffer_resources objectified
instead of global variables. Once this happens more tests like
this can use the common code and submit a fabric_resources
object with a buffer_resources object to a common call so it
uses the passed in resources instead of the global ones.
This refactoring will take place in a later Pull-Request but
for now it is important to get this test enabled in CI and
the refactoring can happen later.
> fabtests/benchmarks: Add multi-threaded rdm bandwidth test

- prov/tcp/src/xnet_cm.c
If ofi_recv_socket() returns 0, it indicates the socket has been closed. This is not an error condition therefore it shouldn't use errno since this is just a leftover from previous error.
To make things worse, if the leftover error is EAGAIN, the caller
xnet_req_done() will handle that error specially that will leave the
endpoint in a weird state.
> prov/tcp: handle the error correctly

- contrib/intel/jenkins/Jenkinsfile
Jenkins doesn't let environment variables change with the '='. Instead we must use the withEnv block to update an environment variable for specific stages.
> contrib/intel/jenkins: Modify env var withEnv instead of '='

- prov/verbs/src/verbs_ep.c
Since verbs only supports a single element for atomic operations, the work request takes in the value to be compared/swapped/operated, not the pointer to the buffer with the values. Update the fields to dereference the pointer and submit the value itself. This also fixes the incorrect msg parameter being inputted in various places. The msg->addr was being used (fi_addr_t) instead of the msg->msg_iov->addr which has the pointer to the data buffer.
This also changes query atomic query return to be -FI_ENOSYS instead of -FI_EINVAL when querying unsupported op/datatype combinations to match with the man pages and the rest of the returns.
> prov/verbs: fix atomic work request fields

- fabtests/benchmarks/rdm_bw_mt.c
fi_close's return value isn't checked. Checking it and reporting as needed will satisfy coverity 459655, 459564, and 459563 issues.
> fabtests/benchmarks: Fix rdm_bw_mt unchecked fi_close return

- contrib/intel/jenkins/Jenkinsfile
Jenkins doesn't let environment variables change with the '='. Instead we must use the withEnv block to update an environment variable for specific stages.
> [v2.1.x] contrib/intel/jenkins: Pick modify env var withEnv instead of =

- contrib/intel/jenkins/Jenkinsfile
Jenkins doesn't let environment variables change with the '='. Instead we must use the withEnv block to update an environment variable for specific stages.
> [v2.0.x] contrib/intel/jenkins: Pick modify env var withEnv instead of =

- include/ofi_util.h
- include/rdma/fi_endpoint.h
- prov/rxm/src/rxm_conn.c
- prov/tcp/src/xnet.h
- prov/tcp/src/xnet_init.c
- prov/tcp/src/xnet_rdm.c
- prov/tcp/src/xnet_rdm_cm.c
- prov/util/src/rxm_av.c
This PR allows the server and client to exchange feature flags, and firewall is introduced as the first feature in the features.
In order to mark a node is behind firewall, the node will set an environmental variable `FI_TCP_FIREWALL_ADDR`, and in that case, peer should never try to initiate a connection back to this node.
> prov/tcp,rxm: add firewall support for RDM

- man/fi_verbs.7.md
According to Mellanox documentation, atomics have limited support on little endian machines and the result buffer will remain in big endian, requiring the caller to handle conversion. Document this limitation in the man pages as this will show up in OFI verbs atomics results as well
Fixes #10911 10911
> man/verbs: clarify little endian limitation for verbs atomics

- include/rdma/fi_errno.h
- man/fi_av.3.md
- man/fi_errno.3.md
- prov/rxm/src/rxm_conn.c
- prov/tcp/src/xnet_rdm_cm.c
- src/fabric.c
This PR adds a new error code FI_EFIREWALLADDR to specify that the dest host is unreachable due to firewall.
> prov/tcp,rxm: Add a new error code for firewall

- prov/efa/src/efa_base_ep.c
- prov/efa/src/efa_cq.c
A race condition may happen when ep enable/close and cq poll access the qp_table at the same time.
Add ep_list_lock to lock cq during qp enable and destroy.
> prov/efa: Add lock to ensure efa direct cq poll is thread safe

- prov/efa/src/efa_base_ep.c
- prov/efa/src/efa_cq.c
A race condition may happen when ep enable/close and cq poll access the qp_table at the same time.
Add ep_list_lock to lock cq during qp enable and destroy.
Signed-off-by: Jessie Yang <jiaxiyan@amazon.com>
(cherry picked from commit 66fe37169bb78668f5e89ee43bf08e766926b440)
> [v2.1.x]prov/efa: Add lock to ensure efa direct cq poll is thread safe

- prov/cxi/include/cxip.h
- prov/cxi/src/cxip_atomic.c
- prov/cxi/src/cxip_coll.c
- prov/cxi/src/cxip_ep.c
- prov/cxi/src/cxip_iomm.c
- prov/cxi/src/cxip_mr.c
- prov/cxi/src/cxip_msg.c
- prov/cxi/src/cxip_msg_rnr.c
- prov/cxi/src/cxip_ptelist_buf.c
- prov/cxi/src/cxip_rma.c
- prov/cxi/src/cxip_txc.c
- prov/cxi/test/av.c
- prov/cxi/test/mem_reg.c
- prov/cxi/test/mr.c
- prov/cxi/test/mr_cache.c
By default, for cached local memory registrations, the CXI provider would always set access control to read/write. This was resulting in read-only memory registration to fail.
This issue is resolved by having each libfabric RDMA operation implementation defining exactly the access control it requires. For example, fi_send() requires read and fi_recv() requires write. This information is then passed into the memory registration function. If caching is disable, the access control are passed into the kernel unmodified. If caching is enabled, the following happens during memory registration:
1. Evict any overlapping entries with access control mismatch.
2. Register memory as read/write.
3. If read/write memory registration fails, attempt read-only.
> Support read only memory registrations

- prov/opx/include/rdma/opx/fi_opx_endpoint.h
This change rearranges some fields in the fi_opx_endpoint struct to make room for a larger fid_ep. The rpc_reserved field added here can simply be removed to allow for a larger fid_ep without altering alignment of other struct members.
> prov/opx: Make room for new RPC field in fid_ep

- contrib/intel/jenkins/Jenkinsfile
Remove this option so multiple stages can fail
It will also make finding failures much easier
> contrib/intel/jenkins: Remove ParallelAlwaysFailFast

- man/fi_endpoint.3.md
Libfabric's memory model is valid until after fi_close(ep) returns or a completion is generated for a buffer given to libfabric via a data transfer API.
> man: Clarify fi_close behavior on FI_ENDPOINT

- configure.ac
- fabtests/common/hmem_cuda.c
- fabtests/configure.ac
- src/hmem_cuda.c
On GB200 platform, when trying to allocate GPU memory using cuMemAlloc(), Nvidia driver only returns addresses from BAR4 which is intended for CPU access via C2C, and not from BAR1 which is intended for GPU direct.
Use the new flag CU_MEM_RANGE_FLAG_DMA_BUF_MAPPING_TYPE_PCIE to cuMemGetHandleForAddressRange so it will force the use of BAR1 in Cuda 12.8 and Nvidia driver 570.86.15.
> hmem/cuda: Add a flag for exporting dmabuf fd on GB200

- prov/cxi/include/cxip.h
- prov/cxi/src/cxip_av.c
- prov/cxi/src/cxip_msg.c
The cxip_addr structure uses bit fields: a 9-bit `pid` and a 20-bit `nic`, both packed into a single uint32_t, leaving 3 bits of padding. When initializing an auth_key_addr variable on the stack using:
auth_key_addr = {
.nic = addr->nic,
.pid = addr->pid,
};
the 3 padding bits may remain uninitialized.
Since auth_key_addr is then passed to HASH_ADD(), the HASH_VALUE() function computes the hash based on *all* bits in the structure, including the padding.
Later, during a lookup with HASH_FIND() in cxip_av_lookup_fi_addr(), a new cxip_addr structure is *explicitly zeroed* before setting fields. This discrepancy causes the hash values to mismatch: the original entry (with garbage padding) and the lookup key (with zeroed padding) produce different hashes. As a result, the lookup fails, …
> prov/cxi: Fix uninitialized padding in cxip_addr structure causing hash mismatches

- prov/efa/src/efa_domain.c
- prov/efa/src/efa_domain.h
- prov/efa/src/efa_fork_support.c
- prov/efa/src/efa_prov.c
A race condition was discovered when initializing EFA using multiple threads. The EFA Provider has a global variable called g_efa_domain_list, which holds a list of all the EFA domains in a fabric. The list is initialized in efa_prov.c in the fi_info path, and then used in domain open path (fork support, and adding a domain to the list). The list needs to be protected by a mutex so that we don't have a race condition of two threads trying to modify the list at the same time. The libfabric man pages state that all control interfaces will always be thread safe unless control progress model is FI_PROGRESS_CONTROL_UNIFIED.
> prov/efa: Add lock around g_efa_domain_list

- prov/efa/src/efa_domain.c
- prov/efa/src/efa_domain.h
- prov/efa/src/efa_fork_support.c
- prov/efa/src/efa_prov.c
A race condition was discovered when initializing EFA using multiple threads. The EFA Provider has a global variable called g_efa_domain_list, which holds a list of all the EFA domains in a fabric. The list is initialized in efa_prov.c in the fi_info path (thread safe), and then used in domain open path (fork support, and adding a domain to the list). The list needs to be protected by a mutex so that we don't have a race condition of two threads trying to modify the list at the same time. The libfabric man pages state that all control interfaces will always be thread safe unless control progress model is FI_PROGRESS_CONTROL_UNIFIED.
(cherry picked from commit 2186aad5b6b01b36e5f75186b6f88d18762a6a25)
> [v2.1.x] prov/efa: Add lock around g_efa_domain_list

- prov/efa/docs/naming_convention.md
- prov/efa/src/efa_av.c
- prov/efa/src/efa_device.c
- prov/efa/src/efa_device.h
- prov/efa/src/efa_domain.c
- prov/efa/src/efa_env.c
- prov/efa/src/efa_fork_support.c
- prov/efa/src/efa_hmem.c
- prov/efa/src/efa_prov.c
- prov/efa/src/efa_prov_info.c
- prov/efa/src/efa_user_info.c
- prov/efa/src/rdm/efa_rdm_pke_nonreq.c
- prov/efa/src/rdm/efa_rdm_util.c
- prov/efa/test/efa_unit_test_cq.c
- prov/efa/test/efa_unit_test_device.c
- prov/efa/test/efa_unit_test_hmem.c
- prov/efa/test/efa_unit_test_info.c
- prov/efa/test/efa_unit_tests.h
FI_EFA_IFACE is used to restrict the EFA devices that are visible to the
application. There is no need to initialize devices that the application
does not want to use.
However, we still want to keep track of all GIDs on the instance even if
they are not selected in FI_EFA_IFACE because we use that list to
determine if a peer is local and create SHM provider resources for such
local peers.
So this commit splits efa_device_construct into two parts: the first
part initializes efa_device fields up to and including the GID. The
second part initializes the protection domain and prov_info structs. The
second part is only executed for EFA devices that match the FI_EFA_IFACE
filter.
And it introduces g_efa_ibv_gid_list and g_efa_ibv_gid_cnt to keep track
of all EFA device GIDs on the instance …
> prov/efa: Only initialize devices that match FI_EFA_IFACE filter and avoid initializing non-EFA devices

- prov/efa/docs/naming_convention.md
- prov/efa/src/efa_av.c
- prov/efa/src/efa_device.c
- prov/efa/src/efa_device.h
- prov/efa/src/efa_domain.c
- prov/efa/src/efa_env.c
- prov/efa/src/efa_fork_support.c
- prov/efa/src/efa_hmem.c
- prov/efa/src/efa_prov.c
- prov/efa/src/efa_prov_info.c
- prov/efa/src/efa_user_info.c
- prov/efa/src/rdm/efa_rdm_pke_nonreq.c
- prov/efa/src/rdm/efa_rdm_util.c
- prov/efa/test/efa_unit_test_cq.c
- prov/efa/test/efa_unit_test_device.c
- prov/efa/test/efa_unit_test_hmem.c
- prov/efa/test/efa_unit_test_info.c
- prov/efa/test/efa_unit_tests.h
Backport changes from https://github.com/ofiwg/libfabric/pull/10990
> [v2.1.x] prov/efa: Only initialize devices that match FI_EFA_IFACE filter and avoid initializing non-EFA devices

- fabtests/common/hmem_cuda.c
- src/hmem_cuda.c
cuMemGetHandleForAddressRange will return CUDA_ERROR_NOT_SUPPORTED on platforms where GPU memory is not cache coherent with the CPU. Also add runtime fallback for this error code.
> hmem_cuda: Add fallback for dmabuf flag with CUDA_ERROR_NOT_SUPPORTED

- fabtests/common/hmem_cuda.c
- src/hmem_cuda.c
cuMemGetHandleForAddressRange will return CUDA_ERROR_NOT_SUPPORTED on platforms where GPU memory is not cache coherent with the CPU. Also add runtime fallback for this error code.
(cherry picked from commit a1be501bfdaab904f22a4e8bb357c9cb781b8a9e)
> [v2.1.x]hmem_cuda: Add fallback for dmabuf flag with CUDA_ERROR_NOT_SUPPORTED

- prov/cxi/configure.m4
- prov/cxi/include/cxip.h
- prov/cxi/src/cxip_coll.c
- prov/cxi/src/cxip_curl.c
- prov/cxi/src/cxip_dom.c
- prov/cxi/src/cxip_info.c
Added new configure option to enable dynamic binding of curl symbols.
This option is needed to support static and dynamic binding of these symbols. The new configure option to enable dlopen during curl init is --enable-cxi-curl-dlopen.
> prov/cxi: Added new configure option to enable dynamic binding of curl symbols

- fabtests/scripts/runmultinode.py
Suppress warnings from Amazon security scan.
similar to https://github.com/ofiwg/libfabric/pull/9339
> fabtests/scripts: use yaml safe_load

- util/pingpong.c
[Patch](https://github.com/ofiwg/libfabric/blame/5dd902300d2c5cdf27f436ffe430d4217c093f5c/util/pingpong.c#L1882) from later version. [Commit](https://github.com/ofiwg/libfabric/commit/17d9cf2c5a168bc22b6e98d2220cd7f802861233) related to the patch. Description of the patch:
pingpong doesn't support FI_MR_ENDPOINT today, So the mr is associated with domain instead of ep. It is unsafe to close mr before closing ep because it can cause an EBUSY error when there are outstanding recvs of the mr posted to the ep/qp. This patch fixes this issue by moving the mr close after.
> Applied patch from later version to prevent errors returned when using fi_close

- include/ofi_util.h
- include/rdma/fabric.h
- man/fi_getinfo.3.md
- prov/rxd/src/rxd.h
- prov/rxd/src/rxd_init.c
- prov/rxm/src/rxm_init.c
- prov/verbs/src/verbs_domain.c
- prov/verbs/src/verbs_eq.c
- prov/verbs/src/verbs_info.c
- prov/verbs/src/verbs_init.c
- prov/verbs/src/verbs_ofi.h
The verbs provider loads the list of verbs devices available on the node
only once, on the first call to fi_getinfo().
If a network device is added (hot-plugged) after this initial call to
fi_getinfo(), it won't be visible in libfabric.
A subsidiary problem is that fi_getinfo() only returns network
adapters with active links.
If the link is initially inactive and becomes active after the first call to
fi_getinfo(), this interface will not be visible in libfabric.
This is a particularly a problem for long-running services where restarting
a process to discover newly added network devices is not an option.
With this patch, the list of verbs interfaces is reloaded on each call
to fi_getinfo().
Fixes #10881
> prov/verbs: Reload the list of interfaces on each call to fi_getinfo()

- include/rdma/fabric.h
- man/fi_tcp.7.md
- prov/tcp/src/xnet_ep.c
Adds the ability to retrieve the underlying file descriptor associated with an active endpoint in the tcp provider. This functionality is exposed through `fi_control()` using the new `FI_GET_FD` command.
The primary motivation is to allow applications to tune socket options that are not exposed through the libfabric API, such as:
- `SO_SNDBUF`: Control send buffer size
- `SO_RCVBUF`: Control receive buffer size
- `SO_BUSY_POLL`: Enable busy polling for lower latency
- ...
> prov/tcp: Add FI_GET_FD support to tcp provider

- include/ofi_util.h
- prov/efa/src/efa_domain.c
- prov/util/src/util_attr.c
The EFA provider does not support the FI_THREAD_COMPLETE locking
optimization. EFA attempts to lock the SRX lock in both the tx
and completion path. This behavior leads to an ofi_genlock assertion
being hit when a FI_THREAD_COMPLETE App runs with EFA compiled in
debug mode. Switch EFA to use locking in order to provide the correct
behavior for FI_THREAD_COMPLETE.
> prov/util & prov/efa: Use mutex locks for FI_THREAD_COMPLETE

- include/ofi_util.h
- prov/efa/src/efa_domain.c
- prov/util/src/util_attr.c
Back Ports the two commits:
```
commit e6bec45f571e6434201f042056fe6c599c3bb710 (HEAD -> v2.1.x-backport-use-locks-for-fi-thread-completion, szegel/v2.1.x-backport-use-locks-for-fi-thread-completion)
Author: Seth Zegelstein <szegel@amazon.com>
Date:   Fri Apr 4 23:43:00 2025 +0000
[v2.1.x]prov/efa: Use mutex locks for FI_THREAD_COMPLETE
The EFA provider does not support the FI_THREAD_COMPLETE locking
optimization. EFA attempts to lock the SRX lock in both the tx
and completion path. This behavior leads to an ofi_genlock assertion
being hit when a FI_THREAD_COMPLETE App runs with EFA compiled in
debug mode. Switch EFA to use locking in order to provide the correct
behavior for FI_THREAD_COMPLETE.
(cherry picked from commit …
```
> [v2.1.x] prov/efa & prov/util: EFA Use Locks for FI_THREAD_COMPLETION

- prov/efa/src/efa_domain.c
Commit 633d2919 added a mutex lock around g_efa_domain_list list insertion in order to keep the EFA control interface thread safe, but forgot to add the mutex lock around the list item removal.  This commit fixes that mistake.
> prov/efa: Use Mutex when removing from g_efa_domain_list

- prov/efa/src/efa_av.c
The actual function is declared below, with no callers in between.
> prov/efa: Delete unused efa_conn_release prototype

- prov/efa/src/efa_av.c
- prov/efa/src/efa_av.h
- prov/efa/src/efa_base_ep.c
- prov/efa/src/efa_base_ep.h
- prov/efa/src/efa_device.c
- prov/efa/src/efa_device.h
- prov/efa/src/efa_domain.c
- prov/efa/src/efa_domain.h
- prov/efa/src/efa_fork_support.c
- prov/efa/src/efa_hmem.c
- prov/efa/src/rdm/efa_rdm_pke.c
- prov/efa/test/efa_unit_test_av.c
- prov/efa/test/efa_unit_test_cq.c
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
This PR has 2 changes:
1. Make 1:1 relationship between efa domain and pd: Today, protection domain (PD) is created in efa_device discovery, when
multiple domains are created against the same efa_device in the
same process, there will share the same PD. Such implementation breaks
the boundary of domain that resources created in different
domains can finally interfere with each other, such as MR and AH.
This patch fixes this issue by making PD created/destroyed by domain
open and close, so there is a 1:1 relationship between domain
and PD.
2. Move address handle to domain level: Today, the efa address handle (AH) resources are
created and tracked in the AV level. This is wrong because for multiple AVs created in the same domain, they share the same PD and the created AHs will not be …
> prov/efa: Create 1:1 relationship between domain and PD, move address handle to domain level

- .appveyor.ps1
A new version of the Windows EFA driver has been officially released. It is now available using a new [tag v1.1.0](https://github.com/aws/efawin/tree/v1.1.0) in the efawin repository. The change is required on the v1.15.x branch, which is used by the [AWS CDI-SDK](https://github.com/aws/aws-cdi-sdk). The AWS CDI-SDK will be updated to use this branch and the new driver after this pull request has been merged.
This change updates the .appveyor.ps1 Windows install script to use the new tag.
> Support new Windows EFA driver v1.1.0 released in Q2 of 2025

- prov/efa/src/efa_domain.c
Commit 633d2919 added a mutex lock around g_efa_domain_list list insertion in order to keep the EFA control interface thread safe, but forgot to add the mutex lock around the list item removal.  This commit fixes that mistake.
(cherry picked from commit 2015b6c6c3773bd8c6d4bd6bba3b3d5b741fbf29)
> [v2.1.x]prov/efa: Use Mutex when removing from g_efa_domain_list

- prov/efa/src/efa_device.c
This commit fixes a bug that happens on instances with multiple EFA devices and the FI_EFA_IFACE filter is used to select any EFA device except the last one.
> prov/efa: Clear cur_device when filtering EFA devices with FI_EFA_IFACE

- prov/efa/src/efa_device.c
This commit fixes a bug that happens on instances with multiple EFA devices and the FI_EFA_IFACE filter is used to select any EFA device except the last one.
(cherry picked from commit 938635ef52d0d279a34ead381ee50c6b095cf4b6)
> [v2.1.x] prov/efa: Clear cur_device when filtering EFA devices with FI_EFA_IFACE

- prov/cxi/include/cxip.h
Allow libfabric to build with both new and older drivers passing CXI_MAP_IOVA_ALLOC on event queue allocation if defined. This is to facilitate upstream builds independent of SHS release.
> prov/cxi: decouple the existence CXI_MAP_IOVA_ALLOC for builds

- prov/cxi/include/cxip.h
- prov/cxi/src/cxip_curl.c
- prov/cxi/src/cxip_info.c
Fix compiler warnings for when curl/json DL open is not enabled (wrong function return type and unused variables, improper log statement).
> prov/cxi: Fix compiler warnings related to curl/json dl_open

- fabtests/pytest/efa/efa_common.py
ibv_devices can return non-EFA IB devices, use the domain names returned by fi_info to get the device list which should exclude the non-efa devices.
> fabtests/efa: Fix get_efa_device_names

- contrib/intel/jenkins/Jenkinsfile
- contrib/intel/jenkins/Jenkinsfile_daos.nightly
RED is an external Intel CI tool designed to run with the other Intel test runner for the libfabric team.
It provides one point of entry into the Jenkinsfile so that less changes will need to occur to it which means less CI backports.
Daos cannot yet run with RED and has other issues running on a per-pr basis so it is getting its own nightly jenkinsfile job.
> contrib/intel/jenkins: Move daos to nightly testing, migrate to RED CI runner

- prov/rxm/src/rxm.h
- prov/rxm/src/rxm_conn.c
- prov/verbs/src/verbs_domain.c
verbs provider enabled the flow control by checking qp type (IBV_QPT_RC), but the qp might not be created when the checking happened. Change to check ep type to ensure flow control is enabled for FI_EP_MSG.
> prov/rxm,verbs: fix the flow control enabling checking

- prov/cxi/include/cxip.h
Allow libfabric to build with both new and older drivers passing CXI_MAP_IOVA_ALLOC on event queue allocation if defined. This is to facilitate upstream builds independent of SHS release.
(cherry picked from commit d56969009907c35842011708ae55373a85cce8c3)
> [v2.0.x] prov/cxi: decouple existence CXI_MAP_IOVA_ALLOC for build

- prov/usnic/src/usnic_direct/usd_ib_sysfs.c
ASAN detects the following memory leak in usdb_ib_get_devlist() when fi_info is executed with the usnic provider enabled:
```
Direct leak of 40 byte(s) in 1 object(s) allocated from:
0 0xfffff78e76d0 in malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
1 0xfffff6eb9954 in __vasprintf_internal libio/vasprintf.c:116
2 0xfffff6eb99ac in __vasprintf libio/vasprintf.c:141
3 0xfffff78bad14 in vasprintf ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:1680
4 0xfffff78bc214 in asprintf ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:1732
5 0xfffff73c873c in usd_ib_get_devlist prov/usnic/src/usnic_direct/usd_ib_sysfs.c:98
6 0xfffff73c6468 in do_usd_init (/nfs_home/sdidelot/usr/libfabric/lib/libfabric.so.1+0x3c6468) …
```
> prov/usnic: Fix memory leak in usd_ib_get_devlist()

- contrib/intel/jenkins/Jenkinsfile
Auth stage got removed by accident.
This adds it back.
> contrib/intel/jenkins: Add auth stage back

- prov/cxi/include/cxip.h
Allow libfabric to build with both new and older drivers passing CXI_MAP_IOVA_ALLOC on event queue allocation if defined. This is to facilitate upstream builds independent of SHS release.
(cherry picked from commit d56969009907c35842011708ae55373a85cce8c3)
> [v2.1.x] prov/cxi: decouple existence CXI_MAP_IOVA_ALLOC for build

- contrib/intel/jenkins/Jenkinsfile
Auth stage got removed by accident.
This adds it back.
> [v2.1.x] contrib/intel/jenkins: Pick add back auth stage from main

- contrib/intel/jenkins/Jenkinsfile
If return status is true then errors will not get propogated up to the controller to fail a build. Switching it to false will allow the stages to properly fail.
> contrib/intel/jenkins: Make stages turn red on fail

- contrib/intel/jenkins/Jenkinsfile
If return status is true then errors will not get propogated up to the controller to fail a build. Switching it to false will allow the stages to properly fail.
> [v2.1.x] contrib/intel/jenkins: Pick make stages turn red on fail from main

- contrib/intel/jenkins/Jenkinsfile
If return status is true then errors will not get propogated up to the controller to fail a build. Switching it to false will allow the stages to properly fail.
> [v2.0.x] contrib/intel/jenkins: Pick make stages turn red on fail from main

- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/test/efa_unit_test_domain.c
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
When closing an endpoint, remove peers associated with that endpoint from domain level lists
> prov/efa: Clear domain level peer lists when closing endpoints

- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/src/rdm/efa_rdm_ope.h
- prov/efa/src/rdm/efa_rdm_peer.c
- prov/efa/src/rdm/efa_rdm_pke.c
- prov/efa/test/efa_unit_test_ope.c
- prov/efa/test/efa_unit_test_pke.c
- prov/efa/test/efa_unit_test_rdm_peer.c
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
ooo, unexp, and readcopy rx pkts are cloned
from the original rx pkts allocated in the rx pkt pool, but they are not inserted to the rx pkt list when
they are created. This caused non-processed pkts
not cleaned up before creating the buffer pools
and cause assertion errors. This patch
fixes this issue by inserting them into
rx pkt list when they are cloned. So they
will be all cleaned during the scan of
rx_pkt_list during ep close.
> prov/efa: Track cloned rx pkts

- prov/cxi/src/cxip_msg_hpc.c
When issuing rendezvous gets with the alt_read rendezvous protocol active we need to
use the tc_type of restricted.
> prov/cxi: Fix the use of alt_read rget restricted TC type

- prov/cxi/test/startvm-setup.sh
Adjust to latest cxi-driver paths to allow CI builds to load them properly.
> prov/cxi: fix cxi driver paths for CI

- prov/efa/src/efa_cntr.c
- prov/efa/src/rdm/efa_rdm_cq.c
- prov/efa/test/efa_unit_test_cntr.c
- prov/efa/test/efa_unit_test_cq.c
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
Currently, cq and cntr read don't check the qp status of the bound ep before posting the initial rx pkts. This is a bug and will cause a crash when a cq/cntr read is called before the bound ep is enabled.
> prov/efa: post initial rx pkt when qp is enabled.

- prov/efa/test/efa_unit_test_info.c
https://github.com/ofiwg/libfabric/commit/1a4209e7dda995d8a1f20fb3ab0dd458961333c1 removed unit tests that use this function.
Silence the warning: ‘get_first_nic_name’ defined but not used [-Wunused-function]
> prov/efa: remove unused function get_first_nic_name

- prov/cxi/include/cxip.h
- prov/cxi/src/cxip_ctrl.c
- prov/cxi/src/cxip_msg_hpc.c
- prov/cxi/src/cxip_zbcoll.c
Extend side-band control message to pass 64-bits of opaque data from as part of control message. This data is completely opaque to control messaging. The source/target of the message may layer validity of the data using match bits appropriate for the usage.
> prov/cxi: Allow for passing opaque 64-bit data in ctrl_msg

- prov/cxi/include/cxip.h
Allow libfabric to build with both new and older drivers passing CXI_MAP_IOVA_ALLOC on event queue allocation if defined. This is to facilitate upstream builds independent of SHS release.
(cherry picked from commit d56969009907c35842011708ae55373a85cce8c3)
> [v1.22.x] prov/cxi: decouple existence CXI_MAP_IOVA_ALLOC for build

- prov/efa/src/rdm/efa_rdm_cq.c
- prov/efa/src/rdm/efa_rdm_ep.h
- prov/efa/src/rdm/efa_rdm_ep_utils.c
- prov/efa/src/rdm/efa_rdm_peer.c
- prov/efa/src/rdm/efa_rdm_pke_cmd.c
- prov/efa/src/rdm/efa_rdm_pke_cmd.h
- prov/efa/src/rdm/efa_rdm_pke_nonreq.c
- prov/efa/src/rdm/efa_rdm_pke_nonreq.h
- prov/efa/src/rdm/efa_rdm_pke_rtm.c
- prov/efa/src/rdm/efa_rdm_pke_rtm.h
- prov/efa/src/rdm/efa_rdm_srx.c
- prov/efa/test/efa_unit_test_cq.c
- prov/efa/test/efa_unit_test_mocks.c
- prov/efa/test/efa_unit_test_mocks.h
- prov/efa/test/efa_unit_test_rnr.c
This change is useful for two reasons
(1) The efa_rdm_ep_get_peer function accesses the AV and it's easier to
lock access to the AV when the call happens in fewer places
(2) With an implicit AV, the fi_addr will always be -1 for peers not
explicitly inserted to the AV. So efa_rdm_ep_get_peer will need to do
a reverse hashmap lookup with a significant performance cost for such
peers. So minimizing the number of calls to efa_rdm_ep_get_peer is more
performant.
> prov/efa: Minimize calls to efa_rdm_ep_get_peer in the CQ read path

- fabtests/benchmarks/rdm_bw_mt.c
- fabtests/common/hmem.c
- fabtests/common/hmem_cuda.c
- fabtests/common/shared.c
- fabtests/include/hmem.h
All calls to ft_hmem_get_dmabuf_fd need a corresponding close call. Or the dmabuf will stick around for the lifetime of the process, even after dereg and releasing the memory back to the device mempool.
similar to https://github.com/ofiwg/libfabric/pull/10708
> fabtests: fix leak of dmabuf fd

- prov/verbs/src/verbs_info.c
- prov/verbs/src/verbs_msg.c
In init info, move device name checking before iterating on domain types to reduce un-necessary checking.
> prov/verbs: bug fix and optimize init info.

- include/ofi_util.h
- man/fi_lnx.7.md
- prov/cxi/src/cxip_msg_hpc.c
- prov/lnx/Makefile.include
- prov/lnx/include/lnx.h
- prov/lnx/src/lnx_av.c
- prov/lnx/src/lnx_cq.c
- prov/lnx/src/lnx_domain.c
- prov/lnx/src/lnx_ep.c
- prov/lnx/src/lnx_init.c
- prov/lnx/src/lnx_mr.c
- prov/lnx/src/lnx_ops.c
- prov/util/src/rxm_av.c
- prov/util/src/util_av.c
- src/fabric.c
Refactor LNX to allows for:
- multiple domains per fabric
- multiple endpoints per domain
- multiple completion queues per domain
- multiple address vectors per domain
Remove all extra functionality except for tagged messages. Other
functionality will be added in follow up patches.
Add support for fi_mr_regattr. This patch doesn't support memory
registration for RMA operations.
Add support for FI_CLAIM, FI_DISCARD and FI_PEEK on the receive path.
Beside the above changes. The PR addresses some bugs found in the lnx FI_PEER
path in the rxm and cxi providers
> Lnx refactor main

- include/ofi_util.h
- prov/util/src/util_attr.c
- prov/verbs/src/verbs_init.c
Access to vrb_util_prov.info is now guarded by the vrb_info_mutex mutex, as the list it references may change if the application triggers an interface rescan using the FI_RESCAN flag.
This issue was discovered during internal testing at DDN with FI_RESCAN enabled.
> prov/verbs: Fix (yet another) unprotected access to vrb_util_prov.info

- prov/efa/src/efa_domain.c
- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/src/rdm/efa_rdm_ope.h
EFA_RDM_OPE_FREE is not a legal state.
It is currently set before the ope is freed,
but we should not access the ope after
its freed. This patch removes this
enum and its references. It keeps the enum
of EFA_RDM_TXE_REQ to be 1 because otherwise
the fresh allocated OPEs will have a state
as EFA_RDM_TXE_REQ (0).
> prov/efa: Remove free ope state

- prov/cxi/include/cxip.h
- prov/cxi/src/cxip_coll.c
- prov/cxi/src/cxip_msg_hpc.c
Implement a retry mechanism to handle the case where the hardware root for the multicast tree does not receive expected contributions from one or more leaves within the timeout period. Also handle the case where a contribution is received after the timeout period has passed.
> prov/cxi: retry root->leaf send after timeout

- prov/cxi/src/cxip_msg_hpc.c
The following community upstream commit: fb928f48f27dc1591781101aa55d7cb8b026b693 locking changes opens a window for FI_THREAD_SAFE locking to deadlock should portals flow control occur and a receive buffer is posted. Fix buy progressing without taking the lock now held.
> prov/cxi: Fix regression which could cause FI_THREAD_SAFE deadlock

- man/fi_efa.7.md
- prov/efa/src/efa_domain.c
- prov/efa/src/fi_ext_efa.h
- prov/efa/test/efa_unit_test_domain.c
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
Add the domain operation query_addr to retrieve the ahn, remote_qpn, and remote_qkey for a given endpoint and destination address. This enables applications to construct the metadata of a wqe.
> prov/efa: Add a domain operation to query address info

- libfabric.spec.in
Commit https://github.hpe.com/hpe/hpc-shs-libfabric-netc/commit/b690555e2998fa9cfe6cebc874f42c9281887610 broke the specfile. This is the fix.
Signed-off-by: Terrence Mitchem <terrence.mitchem@hpe.com>
> build: Add fi_mon_sampler to specfile's %files section

- man/fi_efa.7.md
- prov/efa/Makefile.include
- prov/efa/configure.m4
- prov/efa/src/efa_base_ep.c
- prov/efa/src/efa_cq.c
- prov/efa/src/efa_cq.h
- prov/efa/src/efa_device.c
- prov/efa/src/efa_device.h
- prov/efa/src/efa_domain.c
- prov/efa/src/fi_ext_efa.h
- prov/efa/src/rdm/efa_rdm_cq.c
- prov/efa/test/efa_unit_test_domain.c
- prov/efa/test/efa_unit_test_mocks.c
- prov/efa/test/efa_unit_test_mocks.h
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
Following rdma core changes, enable querying of QP work queue and completion queue's attributes in domain operations, which can be used for accelerator driven datapath.
Enable creation of CQs on top of pre-allocated memory buffers. The memory can be passed by supplying
the struct fi_efa_cq_init_attr with the flag FI_EFA_CQ_INIT_FLAGS_EXT_MEM_DMABUF.
> prov/efa: Extend domain ops to allow querying of QP and CQ attributes

- prov/efa/src/rdm/efa_rdm_ep_fiops.c
The ibv extended cq creation is moved from ep to cq open. Remove this stale code.
> prov/efa: Clean stale error handling

- src/log.c
The array is no longer terminated with a NULL pointer. Check the array boundary instead.
Fixes #11116
> log: Fix buffer overrun when accessing the 'log_levels' array

- man/fi_mr.3.md
This change was previously merged in
https://github.com/ofiwg/libfabric/pull/11112 but that PR updated the wrong file
> man/fi_mr: Clarify fi_close behavior

- prov/shm/src/smr.h
- prov/shm/src/smr_ep.c
- prov/shm/src/smr_util.h
The shm provider does its best to randomize an EP name and make it unique by defaulting to "pid:domain_id:ep_id"
If there already exists a region with that name, the provider wil try to map to the existing region and see if the pid is alive and remap if the pid is dead.
This method doesn't work well with docker containers as the pids live within the container. This means you can have a docker pid 100 that coincides with a host system pid 100 running a root service OR you could have two docker containers running simultaneously that are trying to use the same pid (and therefore shm region name). This can result in a failure to create the shm region or failure to detect whether the pid is actually alive. To fix this, we can fallback to a retry of the shm create and append a random seed …
> [v2.2.x] prov/shm: add shm rename and retry

- prov/verbs/src/verbs_info.c
- prov/verbs/src/verbs_init.c
- prov/verbs/src/verbs_ofi.h
Problem:
Currently, interfaces are reloaded while holding `vrb_info_mutex`.
Since reloading interfaces can take a significant amount of time,
this may block other threads attempting to acquire `vrb_info_mutex`,
leading to potential performance issues.
Solution:
This patch addresses the issue by moving the call to `vrb_init_info()`
(which reloads the list of interfaces) outside the critical section
protected by `vrb_info_mutex`. Once the new interface lists are prepared,
the lock is briefly acquired to safely swap `vrb_devs` and `vrb_util_prov.info`.
> prov/verbs: Avoid holding vrb_info_mutex when reloading interfaces

- prov/efa/src/rdm/efa_rdm_ep.h
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/src/rdm/efa_rdm_msg.c
- prov/efa/src/rdm/efa_rdm_msg.h
- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/src/rdm/efa_rdm_peer.c
- prov/efa/src/rdm/efa_rdm_peer.h
- prov/efa/src/rdm/efa_rdm_pke_cmd.c
- prov/efa/src/rdm/efa_rdm_pke_rtm.c
- prov/efa/src/rdm/efa_rdm_pke_rtm.h
- prov/efa/src/rdm/efa_rdm_pke_rtw.c
- prov/efa/src/rdm/efa_rdm_pke_rtw.h
- prov/efa/src/rdm/efa_rdm_pke_utils.h
- prov/efa/src/rdm/efa_rdm_rxe_map.c
- prov/efa/src/rdm/efa_rdm_rxe_map.h
- prov/efa/test/efa_unit_test_ope.c
- prov/efa/test/efa_unit_test_srx.c
This change is necessary to implement an implicit AV.
With an implicit AV, using the fi_addr is no longer an option for
identifying different peers. All unknown peers will have fi_addr set
to -1. And the index in the implicit AV can be re-used, so it's not
guaranteed to be unique.
This commit makes the rxe_map part of the peer struct and only uses the
msg_id as the hash key
> prov/efa: Make rxe_map part of the efa_rdm_peer struct

- fabtests/benchmarks/benchmark_shared.c
- fabtests/common/shared.c
- fabtests/functional/flood.c
- fabtests/functional/unexpected_msg.c
- fabtests/include/shared.h
- fabtests/multinode/src/core.c
Use the default remote_fi_addr explicitly for current callers.
> fabtests: Support customized fi_addr for ft_post_rx_buf

- fabtests/pytest/common.py
prepare_base_command failed to return the default additional_env for ubertest and host test. This patch fixes it.
> fabtests/pytest: Fix the additional environment return

- prov/efa/src/efa_base_ep.c
- prov/efa/src/efa_base_ep.h
- prov/efa/src/efa_cntr.c
- prov/efa/src/efa_cq.c
- prov/efa/src/efa_cq.h
- prov/efa/src/efa_ep.c
- prov/efa/src/rdm/efa_rdm_cq.c
- prov/efa/src/rdm/efa_rdm_cq.h
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/test/efa_unit_test_cq.c
- prov/efa/test/efa_unit_test_ep.c
Backport https://github.com/ofiwg/libfabric/pull/11151
> [v2.1.x] prov/efa: Drain cq after qp destroy

- prov/verbs/src/verbs_info.c
bnxt_re also supports peermem access. Allow peermem access if the device name matches with bnxt_re.
> libfabric: Allow peer mem support for bnxt_re devices also

- Makefile.am
The monitor sampler can now be disabled together with the monitor provider by running configure with `--disable-monitor` option. This can also serves as a workaround for old gcc compilers (e.g. 4.8.5) that don't support the `_Atomic` keyword.
> util/mon_sampler: Disable the sampler together with the monitor provider

- prov/efa/src/efa_av.c
- prov/rxm/src/rxm_domain.c
- prov/shm/src/smr_av.c
- prov/sm2/src/sm2_av.c
- prov/util/src/util_srx.c
util_queue_[msg,tag] and util_get_[msg,tag] expect the caller to acquire the SRX lock. This commit requires the callers of util_foreach_unspec to also do the same.
> prov/util,rxm,shm,sm2: Get srx lock in the caller of util_foreach_unspec

- man/fi_efa.7.md
- prov/efa/src/efa_domain.c
- prov/efa/src/fi_ext_efa.h
- prov/efa/test/efa_unit_test_domain.c
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
prov/efa: Move gda operations to FI_EFA_GDA_OPS
Use a different key string for GDA related operations.
prov/efa: Add query_lkey to GDA ops
Expose lkey to enable applications to construct the TX/RX buffer descriptor in the wqe for send/recv operations.
> prov/efa: Move gda operations to FI_EFA_GDA_OPS

- prov/efa/src/efa_av.c
- prov/efa/src/efa_av.h
- prov/efa/src/efa_domain.c
- prov/efa/src/rdm/efa_rdm_cq.c
- prov/efa/src/rdm/efa_rdm_ep.h
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/src/rdm/efa_rdm_ep_utils.c
- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/src/rdm/efa_rdm_pke.c
- prov/efa/src/rdm/efa_rdm_pke_cmd.c
- prov/efa/src/rdm/efa_rdm_pke_cmd.h
- prov/efa/src/rdm/efa_rdm_pke_nonreq.c
- prov/efa/src/rdm/efa_rdm_pke_print.c
- prov/efa/test/efa_unit_test_av.c
- prov/efa/test/efa_unit_test_common.c
- prov/efa/test/efa_unit_test_cq.c
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
This commit adds an implicit AV to store addressing information of peers
that have not been explicitly inserted into the AV by the application.
When an application calls fi_av_insert for a peer that is already
present in the implicit AV, the AV entry is moved to the explicit AV.
> prov/efa: Add implicit AV and logic to move entries to explicit AV

- include/ofi_hmem.h
- prov/efa/src/efa_mr.c
- src/hmem.c
- src/hmem_neuron.c
This patch reverts an earlier change that aims to do dmabuf reg only when FI_MR_DMABUF flag is set.
We still want to use dmabuf by default even when this flag is not set.
It also adds the clean up of the dmabuf fd after the ibv_reg_dmabuf_fd to fix the fd leak.
This reverts commit 043e968534491319d1b9afc22e482783d5779677.
> prov/efa: Use dmabuf by default for neuron mr

- configure.ac
When checking if clang is being used for linking, the pattern `*clang*` may incorrectly match a non-clang loader that is located under a path containing `clang`.
Fix by making sure the pattern only matches the filename part of a path.
Fix #11138
> configure: Fix clang checking

- prov/cxi/include/cxip.h
- prov/cxi/src/cxip_coll.c
The first time a particular reduction ID is used is not the only time we may need to arm the reduction engine. We also need to re- arm if the 'next' reduction is initiated after the previous arming period has expired. Replace the "first send" logic with "need to arm" logic.
> prov/cxi: correct reduction engine arming behavior

- include/ofi_util.h
- include/rdma/providers/fi_peer.h
- man/fi_peer.3.md
- prov/lnx/include/lnx.h
- prov/lnx/src/lnx_ops.c
- prov/util/src/util_srx.c
fi_peer_rx_entry has two internal fi_peer_rx_entry fields so the struct could be castable to a dlist_entry or slist_entry. This suggests a dependency between the external headers and the internal headers which if difficult to ensure. In addition, there is no real reason for the owner and peer to share an entry for tracking the peer entry. The owner and peer each have their own structs and mechanisms for tracking the entry when the resource is on their side so the extra fields can be removed completely.
Since there is a requirement for all peers/owners to use the same version of libfabric, there is no issue with backwards compatibility
> include/fi_peer.h, prov/util,lnx: remove fi_peer_rx_entry dlist fields

- prov/efa/src/efa_prov.c
- prov/efa/src/efa_prov_info.c
- prov/efa/src/efa_prov_info.h
- prov/efa/test/efa_unit_test_info.c
Currently, efa_prov_info_set_hmem_flags is called as part of device list initialization, which is before efa_hmem_info_initialize() is called. This will make the efa_prov_info_set_hmem_flags not work because the metadata in `g_efa_hmem_info` is not initialized yet.
This patch fixes this issue by moving efa_prov_info_set_hmem_flags to efa_util_prov_initialize()'s efa-direct prov_info construction, which happens after the efa_hmem_info_initialize() call.
> prov/efa: Fix the hmem flags setting

- fabtests/prov/efa/Makefile.include
- fabtests/prov/efa/configure.m4
- fabtests/prov/efa/src/efa_exhaust_mr_reg_common.c
- fabtests/prov/efa/src/efa_exhaust_mr_reg_common.h
- fabtests/prov/efa/src/efa_rdma_checker.c
- fabtests/pytest/efa/test_rdm.py
- prov/efa/test/efa_unit_test_cq.c
The first ibv device can be non-EFA. Loop through the device list and query the first EFA device.
> fabtests/efa: Fix EFA device query 

- prov/efa/src/efa_prov.c
- prov/efa/src/efa_prov_info.c
- prov/efa/src/efa_prov_info.h
- prov/efa/test/efa_unit_test_info.c
Currently, efa_prov_info_set_hmem_flags is called as part of device list initialization, which is before efa_hmem_info_initialize() is called. This will make the efa_prov_info_set_hmem_flags not work because the metadata in `g_efa_hmem_info` is not initialized yet.
This patch fixes this issue by moving efa_prov_info_set_hmem_flags to efa_util_prov_initialize()'s efa-direct prov_info construction, which happens after the efa_hmem_info_initialize() call.
(cherry picked from commit 0dfeba9efaca066a6981bab4bc4117fea6fca830)
> [v2.1.x] Backport prov/efa: Fix the hmem flags setting

- prov/lnx/src/lnx_ops.c
A recent commit removed the fi_peer_rx_entry next/prev fields disallowing casting from a dlist_entry to an rx_entry and moving the dlist_entry into the lnx_entry. Two containers/casts were missed
> prov/lnx: fix missing peer_entry field updates

- .gitignore
- examples/Makefile
- examples/README.md
- examples/rdm.c
Add a new examples/ directory which is intended to have standalone, single-file examples that show how to use libfabric and its features. A single Makefile is provided for simplicity in building. Each test will be completely contained in a single file with no cross depdencies and will be thoroughly commented to explain each step in the program.
Each test executable will have the prefix fi_example_
This commit comes with the first example - fi_example_rdm which outlines a simple server-client and send-recv
> examples: add example directory with first example

- configure.ac
This check needs to happen before the DMABUF check so that the user doesn't need to set CFLAGS="-I/cuda_install_location" before running configure. This will let the AC_CHECK_DECL properly update CPPFLAGS and LDFLAGS before the DMABUF checks.
> configure.ac: Move cuda cppflag set before DMABUF check

- contrib/aws/Jenkinsfile
After we acquire the trn1 lock, attempt to cleanup all trn1 clusters in the region to prevent ICE which leads to CI failure.
> contrib/aws: Cleanup leaked trn1 clusters

- fabtests/pytest/efa/test_gda.py
Add testset short and fabric so it will be picked up by our CI.
> fabtests/efa: Add pytest marker and fixture to GDA fabtest

- man/fi_efa.7.md
- prov/efa/src/efa_domain.c
GPU Direct Async (GDA) is designed to minimize CPU intervention for optimal performance. Applications should use efa-direct fabric to open GDA domain ops. Return -FI_EOPNOTSUPP for non efa direct domains.
(cherry picked from commit a726b2507f4c7059a58cc4c58039f8b0e5c94951)
> [v2.2.x]prov/efa: Restrict GDA domain ops to efa-direct

- prov/cxi/src/cxip_curl.c
The current version of Libfabric does not consider a custom installation of the json-c dependency.
When providing the option `--with-json-c=DIR`, the selected json-c library is the system default and not the one located at DIR.
This is because `prov/cxi/src/cxip_curl.c` is using `lib_name` (with default value "libjson-c.so") instead of `json_libpath`.
> prov/cxi: Fix dlopen using default value for json-c library

- prov/cxi/include/cxip.h
This reverts commit e5b8ad7f7b88229ae7644753c6e04a2ebd0f7be6.
Ordering will be deprecated in release notes.
> Revert "prov/cxi: Fix RMA/AMO network ordering"

- prov/cxi/include/cxip.h
CXI provider supports FI_ORDER_RMA_RAR message order.
> prov/cxi: Add support for FI_ORDER_RMA_RAR

- prov/efa/docs/overview.md
Fixing non-working hyperlinks in prov/efa/docs/overview.md.
> prov/efa : Fix stale links in docs/overview.md

- prov/efa/src/efa_cq.c
This reverts commit 42801061399075ff9ff4542c750b5c1dbf033d48.
Nightly tests showed that this commit breaks aws-ofi-nccl functional tests.
> Revert "prov/efa: Optimizie the locking for efa cq"

- prov/cxi/include/cxip.h
- prov/cxi/include/fi_cxi_ext.h
- prov/cxi/src/cxip_coll.c
- prov/cxi/src/cxip_cq.c
- prov/cxi/src/cxip_ctrl.c
- prov/cxi/src/cxip_msg_hpc.c
- prov/cxi/src/cxip_zbcoll.c
- prov/cxi/test/coll.c
This is needed for leaf nodes after a packet drop with the final result of a collective operation.
> prov/cxi: RDMA get logic on a collective root/leaf

- prov/efa/src/efa_cq.c
- prov/efa/src/efa_cq.h
- prov/efa/src/efa_data_path_ops.h
- prov/efa/src/efa_domain.c
- prov/efa/src/rdm/efa_rdm_cq.c
- prov/efa/src/rdm/efa_rdm_cq.h
- prov/efa/src/rdm/efa_rdm_ep.h
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
- prov/efa/src/rdm/efa_rdm_ep_utils.c
- prov/efa/src/rdm/efa_rdm_ope.c
- prov/efa/src/rdm/efa_rdm_ope.h
- prov/efa/src/rdm/efa_rdm_pke.c
- prov/efa/src/rdm/efa_rdm_pke.h
- prov/efa/src/rdm/efa_rdm_pke_cmd.c
- prov/efa/src/rdm/efa_rdm_pke_rtm.c
- prov/efa/src/rdm/efa_rdm_pke_utils.h
- prov/efa/src/rdm/efa_rdm_protocol.h
- prov/efa/test/efa_unit_test_rnr.c
This silently drops applicable outstanding operations for a closing EP, instead of reporting completions. Exceptions are RECEIPT and EOR packets when `FI_RM_ENABLED` is set - these packets will be reposted when RNR is encountered.
> prov/efa: Fix the wait_send procedure

- contrib/intel/jenkins/Jenkinsfile
Fix fabtests/pytests to be fabtests/pytest so that PRs with changes only in files fabtests/pytest/* get properly skipped.
> contrib/intel/jenkins: Update opt-out files

- contrib/intel/jenkins/Jenkinsfile
Remove the s from pytests so fabtests/pytest can be excluded.
> [v2.0.x] contrib/intel/jenkins: Pick Update opt-out files

- contrib/intel/jenkins/Jenkinsfile
Remove the s from pytests so fabtests/pytest can be excluded.
> [v2.2.x] contrib/intel/jenkins: Pick Update opt-out files

- contrib/intel/jenkins/Jenkinsfile
Remove the s from pytests so fabtests/pytest can be excluded.
> [v2.1.x] contrib/intel/jenkins: Pick Update opt-out files

- prov/cxi/include/cxip.h
- prov/cxi/src/cxip_coll.c
- prov/cxi/src/cxip_curl.c
- prov/cxi/src/cxip_info.c
We were using a 100ms timeout mechanism out of band from normal curl timeout behavior. This can cause us to give up prematurely in the case of slow DNS resolution. Instead, we'll now use the normal curl timeout and set it to 5 seconds instead of the default of 300s.
> prov/cxi: use native curl timeout

- prov/efa/src/efa_domain.c
GPU cannot do a blocking wait on CQ entries because system FDs are only accessible to CPU.
Always initialize nevents to prevent accessing uninitialized memory during efa_cq_close.
> prov/efa: Initialize nevents in efa_domain_cq_open_ext

- fabtests/pytest/efa/test_rma_bw.py
Skip test_rma_bw_sread when FI_RMA is not supported in efa-direct by using rma_fabric.
> fabtests/efa: fix missing rdma check in test_rma_bw_sread

- include/ofi.h
- prov/efa/src/efa_prov.c
- prov/hook/hook_hmem/src/hook_hmem.c
- prov/lpp/src/lpp_util.c
- prov/rxm/src/rxm_init.c
- prov/shm/src/smr_init.c
- prov/sockets/src/sock_fabric.c
- prov/tcp/src/xnet_init.c
- prov/ucx/src/ucx_init.c
- prov/verbs/src/verbs_init.c
- src/common.c
- src/fabric.c
Runtime parameters decalared in common.c weren't initialized for DL providers because the initialization was done in core-only code.
Move the initialization to a common function `ofi_params_init` which can be called from DL providers.
Fixes #11312
> core/common: Make common runtime parameters working for DL providers

- fabtests/pytest/efa/test_rma_bw.py
- prov/efa/src/efa_domain.c
Backport https://github.com/ofiwg/libfabric/pull/11330 and https://github.com/ofiwg/libfabric/pull/11326
> [v2.2.x]fabtests/efa: fix missing rdma check in test_rma_bw_sread

- prov/cxi/src/cxip_msg.c
- prov/cxi/src/cxip_msg_rnr.c
- prov/cxi/test/msg.c
RNR receive counters are offloaded to hardware, avoid software updates with counter progress scheme. Only require counter progress an EP if required.
> prov/cxi: Fix RNR counter logic for new counter progress

- prov/efa/Makefile.include
- prov/efa/configure.m4
- prov/efa/src/efa_cq.c
- prov/efa/src/efa_data_path_direct.c
- prov/efa/src/efa_data_path_direct_entry.h
- prov/efa/src/efa_data_path_direct_structs.h
- prov/efa/src/efa_data_path_ops.h
- prov/efa/src/efa_io_regs_defs.h
- prov/efa/test/efa_unit_test_cq.c
- prov/efa/test/efa_unit_test_data_path_ops.c
- prov/efa/test/efa_unit_test_mocks.c
- prov/efa/test/efa_unit_test_mocks.h
- prov/efa/test/efa_unit_tests.c
- prov/efa/test/efa_unit_tests.h
Bypass ibv_get_cq_event and ibv_req_notify_cq.
Turn off direct cq data path when wait is requested during fi_cq_open and doorbell is not exposed in efadv_cq_attr.
> prov/efa: Bypass rdma-core in blocking cq read path

- fabtests/prov/efa/src/efagda/cuda_kernel.cu
The CUDA compiler was incorrectly optimizing away memory reads of the completion queue entry (CQE) flags field, assuming the memory content was constant. However, the CQE flags are updated asynchronously by the EFA device hardware, and repeated reads must fetch the current value from memory rather than using a cached register value. Without this fix, the efa_cqe_is_pending() function could return stale data, causing completion polling to hang or miss valid completions.
> fabtests/efa: Add volatile to prevent compiler optimization of CQE flag

- man/fi_efa.7.md
- prov/efa/src/efa_env.c
We are moving in this direction. Making it on
by default will help testing and benchmarking
> prov/efa: Enable direct data path by default

- configure.ac
The original text as not as clear as it could be why this option is useful. This commit amends the text to make it clearer. 
I've tested this by running autogen.sh to generate the configuration files from a clean build, and run ./configure to ensure everything looks fine, including the help text.
> configure: Improve restricted-dl help text

- prov/efa/src/efa.h
Increase default ibv_cq size on efa-direct from 1k to 16k.  Having too small of a cq can lead to cq overflow, which will cause completions to be dropped. Users can choose to specify cq size in cq_attr which will override this number.
> prov/efa: Increase default efa-direct ibvcq size

- prov/opx/include/rdma/opx/opx_debug.h
Commit 4c73112f0acb added a call to opx_debug_ep_list_free with arguments while it takes none. This triggers the following compilation error with GCC15 (comes with std=gnu23 as default): prov/opx/src/opx_debug.c:411:6: error: conflicting types for 'opx_debug_ep_list_free'; have 'void(void *)'
411 | void opx_debug_ep_list_free(void *opx_ep)
|      ^~~~~~~~~~~~~~~~~~~~~~
In file included from prov/opx/src/opx_debug.c:40:
./prov/opx/include/rdma/opx/opx_debug.h:47:6: note: previous declaration of 'opx_debug_ep_list_free' with type 'void(void)'
47 | void opx_debug_ep_list_free();
|      ^~~~~~~~~~~~~~~~~~~~~~
Remove the unneed argument to solve the issue.
Fixes: 4c73112f0acb ("prov/opx: Add debug dump of endpoint upon receiving SIGUSR2")
> prov/opx: fix compilation error

- prov/efa/src/rdm/efa_rdm_pke.c
Only becomes important when the dlist sizes are tracked
See https://github.com/ofiwg/libfabric/pull/9360 for more context
> prov/efa: Insert write packets to tx debug list

- prov/util/src/util_attr.c
Domain control_progress attribute was added earlier to provide a lockless statemachine in libfabric with FI_THREAD_DOMAIN threading and FI_PROGRESS_CONTROL_UNIFIED control_progress mode. However there was no way for a user to provide the required control_progress attribute. This patch is adding the support for allowing user to override the control_progress along with the other domain attributes.
> prov/util: configure control_progress with the user provided progress mode

- prov/efa/src/efa.h
- prov/efa/src/efa_av.c
- prov/efa/src/efa_env.c
- prov/efa/src/efa_env.h
- prov/efa/src/rdm/efa_rdm_cq.c
Backport of https://github.com/ofiwg/libfabric/pull/11369, https://github.com/ofiwg/libfabric/pull/11337 and https://github.com/ofiwg/libfabric/pull/11401
> [v2.3.x] Backport implicit AV and efa-direct CQ size changes

- prov/efa/configure.m4
- prov/efa/src/efa_base_ep.c
Add configure check and use the flag in ibv_query_qp_data_in_order() calls when available. This flag queries device-only data ordering capabilities without considering CPU architecture, needed for GPU polling scenarios.
> prov/efa: Use IBV_QUERY_QP_DATA_IN_ORDER_DEVICE_ONLY flag when available

- prov/efa/configure.m4
- prov/efa/src/efa_base_ep.c
backport https://github.com/ofiwg/libfabric/pull/11414
> [v2.2.x] prov/efa: Use IBV_QUERY_QP_DATA_IN_ORDER_DEVICE_ONLY flag when available

- prov/cxi/src/cxip_coll.c
We were not (re)setting the timer for the "need to re-arm" logic on the leaf side. This resulted in a performance blip when the timer eventually expired. We now reset this timer as soon as the leaf sees an ARM packet.
> prov/cxi: reset timer on rx of ARM packet

- prov/efa/src/efa_cq.c
- prov/efa/src/efa_cq.h
efa_cq->err_buf is only needed by efa-direct cq which can store the err data on the util cq bypass path. Make it allocated on demand during the efa-direct
cq open to save memory.
> prov/efa: Allocate cq err_buf on demand

- prov/efa/src/efa_data_path_ops.h
- prov/efa/test/efa_unit_test_cq.c
backport https://github.com/ofiwg/libfabric/pull/11405
> [v2.3.x] prov/efa: Ignore stale cqes from destroyed qps

- prov/efa/src/efa_base_ep.c
- prov/efa/src/efa_base_ep.h
- prov/efa/src/efa_ep.c
- prov/efa/src/rdm/efa_rdm_ep_fiops.c
backport https://github.com/ofiwg/libfabric/pull/11439
> [v2.3.x] prov/efa: acquire the same lock for qp lifecycle

- prov/cxi/test/fi_info_test.sh
DEVICE is supposed to be non-existent for this test case. But many systems have multiple cxi devices, so cxi1 may exist. Update to one that definitely will not exist.
> prov/cxi: fix DEVICE in fi_info_test

- prov/cxi/include/cxip.h
- prov/cxi/src/cxip_cmdq.c
- prov/cxi/src/cxip_dom.c
When looking for an idle cmdq, besides checking if the rd and wr pointers match, also check if the cq ack counter is 0.
> prov/cxi: check cmdq_ack_counter before selecting cmdq
